### ISSUE TITLE
Using the io.spring.dependency-management plugin from a kotlin script plugin produces an error.

### ISSUE THREAD

**Issue by nbabb** [gradle/gradle#20531] opened 2022-04-22 14:01 UTC
I am using the `io.spring.dependency-management` plugin in a gradle script plugin (from buildSrc) without issues.  When I convert this to Kotlin dsl I get an error `Unresolved reference: imports`.  I am able to use this plugin from a build.gradle.kts file directly.

### Expected Behavior
I'd expect to be able to use this plugin from a kotlin script plugin.

### Current Behavior
Receive an error `Unresolved reference: imports`.

### Context
I am trying to provide dependency management in one place for several sub projects.

### Steps to Reproduce 
I have the following in a gradle script plugin file in buildSrc, that I reference as a plugin from sub project build.gradle.kts files

```
plugins {
    id 'io.spring.dependency-management'
}

repositories {
    maven {
        url "https://<mycompany>.jfrog.io/foo/bar"
        credentials {
            username = artifactory_user
            password = artifactory_password
        }
    }
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-gcp-dependencies:1.2.8.RELEASE"
        mavenBom "org.springframework.cloud:spring-cloud-vault-dependencies:3.0.3"
    }
}
```

When I convert this file to a kotlin gradle script plugin, like so.

```
plugins {
    id("io.spring.dependency-management")
}

repositories {

    maven {
        url = uri("https://<mycompany>.jfrog.io/foo/bar")
        credentials {
            val artifactory_user: String by project
            val artifactory_password: String by project
            username = artifactory_user
            password = artifactory_password
        }
    }
}

dependencyManagement {
    imports {
        mavenBom("org.springframework.cloud:spring-cloud-gcp-dependencies:1.2.8.RELEASE")
        mavenBom("org.springframework.cloud:spring-cloud-vault-dependencies:3.0.3")
    }
}
```
I get an error `buildSrc\src\main\kotlin\spring-dependency-management.gradle.kts: (23, 5): Unresolved reference: imports`

### Your Environment
We are using gradle 7.4.2 and using `id("io.spring.dependency-management") version "1.0.11.RELEASE"` version of the plugin

**Comment by ljacomet** [comment] 2022-05-15 20:03
Closing as cannot reproduce

**Closed by ljacomet** 2022-05-15 20:03 UTC

**Comment by digulla** [comment] 2022-05-25 12:35
You will get the error when you try to use `dependencyManagement ` in the root `settings.gradle.kts`.

I also tried to use `import` inside of `dependencyResolutionManagement` but get the same error (`Unresolved reference: imports`).

The problem here is that the error message is useless. In addition of telling us what it can't do, it should give a list of allowed child elements. This is especially problematic for first time users because they are left in the dark what the cause of the problem could be and how it might be solved.

**Comment by mrclrchtr** [comment] 2023-07-18 13:50
Hi, I reproduced the problem here: https://github.com/mrclrchtr/gradle-issue-reproducer/actions/runs/5588272143/jobs/10214798895

Is it possible to do something like this?
https://github.com/mrclrchtr/gradle-issue-reproducer/blob/kotlin-dsl/buildSrc/src/main/kotlin/spring-dependency-management-conventions.gradle.kts

```
import org.springframework.boot.gradle.plugin.SpringBootPlugin

plugins {
    kotlin("jvm")
    id("io.spring.dependency-management")
}

dependencyManagement {
    imports {
        mavenBom(SpringBootPlugin.BOM_COORDINATES)
    }
}
```

**Comment by mrclrchtr** [comment] 2023-12-26 11:41
@ljacometcould you please reopen the issue?

**Comment by mrclrchtr** [comment] 2024-05-01 11:49
@ljacomet or @hegyibalint, could you please reopen the issue? If not, I can create a new issue with the same content, but it probably makes more sense to reopen this one to keep the context.
