### ISSUE TITLE
Using org.gradle.api.testing.Test in a maven project

### ISSUE THREAD

**Issue by jmholzinger** [gradle/gradle#6207] opened 2018-08-06 23:22 UTC
I'm trying to create a Gradle plugin using the Maven build system. Building the plugin using Gradle would be ideal, and I have successfully built the plugin using the "java-gradle-plugin" plugin, but my organization uses Maven as the primary build system and I would like to avoid introducing a new build system in our infrastructure to build one project.

I'm creating a plugin that automatically configures the "test" task so I need access to the "org.gradle.api.testing.Test" class, but I cannot find the class in any of the hosted dependencies. Are there any dependencies that I can add to my POM so that I can properly build this project?

### Expected Behavior
I would expect to be able to add another dependency to my POM so that I have access to the class, my dependencies currently look like this:

```
<dependencies>
    <dependency>
        <groupId>javax.inject</groupId>
        <artifactId>javax.inject</artifactId>
        <version>1</version>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>org.codehaus.groovy</groupId>
        <artifactId>groovy</artifactId>
        <version>${groovy.version}</version>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>org.gradle</groupId>
        <artifactId>gradle-core</artifactId>
        <version>${gradle.version}</version>
        <scope>provided</scope>
    </dependency>
</dependencies>
```

### Current Behavior
None of the public dependencies that I've looked at have the class included in them and I cannot find an equivalent dependency to "gradle-api-4.9.jar" that is included when using the "java-gradle-plugin" plugin.

**Comment by big-guy** [comment] 2018-08-06 23:51
I'm going to close this as a dupe of https://github.com/gradle/gradle/issues/1164 (which broadly talks about building Gradle plugins with Maven). 

I'm not sure why you need to build a Gradle plugin if you're not allowed to use Gradle. 
I think you're going to be better off trying something like https://github.com/LendingClub/gradle-maven-plugin (it's a Maven plugin for running Gradle builds) if you have to use Maven.

The gradle-core jar you found is only part of the Gradle API and isn't intended for plugin development.

**Closed by big-guy** 2018-08-06 23:51 UTC
