### ISSUE TITLE
failed to build in jenkins when using specific pr title

### ISSUE THREAD

**Issue by spac3hit** [gradle/gradle#1528] opened 2017-03-07 10:01 UTC
### Expected Behavior
Build gradle project on jenkins successfully.

### Context
notifying a Jenkins job when a new pr is opened in github using a webhook (ghprb) -> Jenkins ghprb plugin retrieves the pr info sent >> trigger a build.

### Steps to Reproduce (for bugs)
bin/gradle -DghprbActualCommitAuthorEmail=x@y -DghprbTriggerAuthorLogin= -DghprbGhRepository=project -DghprbTargetBranch=branch -DghprbPullId=1 -DghprbCredentialsId=xyz -DghprbAuthorRepoGitUrl=https://github.com -DghprbTriggerAuthor= -DghprbPullAuthorEmail= -DghprbPullLink=https://github.com/pull/1 -Dsha1=repo/pr/1/merge -DghprbPullAuthorLoginMention= "-DghprbPullDescription=GitHub pull request #1 of commit 111111111111, no merge conflicts." -DghprbActualCommit=111111111111 -DghprbPullAuthorLogin=author -DghprbSourceBranch=branch "-DghprbActualCommitAuthor=author author" -DghprbTriggerAuthorLoginMention= "-DghprbPullLongDescription=long description" -DghprbTriggerAuthorEmail= -DGIT_BRANCH=branch '-DghprbPullTitle="renaming XYZ >> 'xyz'"' -DghprbCommentBody=null clean build -Pproperty=property -b build.gradle

The problem resides in this peoperty: '-DghprbPullTitle="renaming XYZ >> 'xyz'"'
That's the pull request title. 

With[ '-DghprbPullTitle="renaming XYZ >> 'xyz'"' ] (and with << operator instead of >>) When build is triggered on jenkins, I get the following error:
....
FAILURE: Build failed with an exception.

What went wrong:
Task 'XYZ' not found in root project 'github-project'.
....

With[ '-DghprbPullTitle="renaming XYZ >>> 'xyz'"' ]:
....
bin/gradle: 1: eval: Syntax error: redirection unexpected
....
it is a unix syntax error. Probably jenkinsci(Jenkins) or janinko(ghprb) should care for this issue. But I thought this may help in solving the issue.

With[ '-DghprbPullTitle="aribitraryName >>"' ] (Also unix syntax error):
....
bin/gradle: 1: eval: cannot create : Directory nonexistent
....

### Environment
hint:(in win os it works fine.)
os: ubuntu 14.04.4 LTS

**Comment by wolfs** [comment] 2017-03-07 11:34
Thank you for the well written bug report. This sounds more like a bug in the [Jenkins Gradle plugin](https://wiki.jenkins-ci.org/display/JENKINS/Gradle+Plugin) than in Gradle itself. I think the main problem is that
1) all build parameters are passed to Gradle as system properties automatically
2) the given system property contains `>>` and `'`.

To check if it is a problem for Gradle itself, could you try passing the property correctly masked on the command line to `gradle` or `gradlew`? If this works, please open an issue for the Jenkins Gradle plugin.

**Comment by spac3hit** [comment] 2017-03-07 13:09
executed the same command from cli; I get the same errors.

**Comment by wolfs** [comment] 2017-03-07 22:03
Yeah, that's what I assumed. The question is how the command got assembled. I suppose that the Jenkins job parameter value is 
```
ghprbPullTitle=renaming XYZ >>> 'xyz'
```,
right?

The Jenkins Gradle plugin converts this to a system property command line expression, in your case:
```
 '-DghprbPullTitle="renaming XYZ >>> 'xyz'"'
```

This is wrongly quoted for the shell. A possible right quoting would be:
```
'-DghprbPullTitle="renaming XYZ >> '"'xyz'"'"'
```
This is not ideal since it passes `"renaming XYZ >> 'xyz'"` as system property while it should probably pass `renaming XYZ >> 'xyz'`. But passing this correctly masked String on the shell to Gradle does not make Gradle fail:
```
gradle '-DghprbPullTitle="renaming XYZ >> '"'xyz'"'"'
```

And this would mean that the problem is in the quoting logic of the Jenkins Gradle plugin and not with the Gradle start script. Do you agree?
The problem you are describing has been on my radar: https://github.com/jenkinsci/gradle-plugin/blob/master/src/test/groovy/hudson/plugins/gradle/GradlePluginIntegrationTest.groovy#L204

**Comment by spac3hit** [comment] 2017-03-08 09:36
Yes, That's right. Jenkins job parameter is: `ghprbPullTitle=renaming XYZ >>> 'xyz'`.
I tried a bunch of possibilities and found the following work as charm:
`
"-DghprbPullTitle=renaming XYZ >> \'xyz\'"
-DghprbPullTitle="renaming XYZ >> \'xyz\'"
`
this `'-DghprbPullTitle="renaming XYZ >> '"'xyz'"'"'` doesn't work, I think the system is trying to redirect smthn to a file.
Also it is described in the Java docs:

> -Dproperty=value
Sets a system property value. The property variable is a string with no spaces that represents the name of the property. The value variable is a string that represents the value of the property. If value is a string with spaces, then enclose it in quotation marks (for example -Dfoo="foo bar").
And escape special characters or quotations to adhere to the shell syntax.

In the Shell Command Language definition it is stated that:

> Enclosing characters in single-quotes (' ') preserves the literal value of each character within the single-quotes. A single-quote cannot occur within single-quotes.

So yeah, I agree it is a ghprb issue.

**Comment by wolfs** [comment] 2017-03-08 09:49
Please open a bug for [Jenkins Gradle plugin](https://wiki.jenkins-ci.org/display/JENKINS/Gradle+Plugin) in the [Jenkins issue tracker](https://issues.jenkins-ci.org). I am closing this issue.

**Closed by wolfs** 2017-03-08 09:49 UTC

**Comment by spac3hit** [comment] 2017-03-22 14:39
Just for reference: [JENKINS-42573](https://issues.jenkins-ci.org/browse/JENKINS-42573)
