### ISSUE TITLE
Platform dependencies not possible in dependency block of test suite plugin

### ISSUE THREAD

**Issue by toerni** [gradle/gradle#19065] opened 2021-11-19 17:56 UTC
While testing the new test-suite plugin, I tried to add a dependency to my platform in the new dependency block using kotlin dsl

### Expected Behavior

Expecting the dependency below to compile

```
testing {
    suites {

        val integrationtest by registering(JvmTestSuite::class) {
            this.useJUnitJupiter()


            dependencies {
                implementation(platform(project(":myPlatform")))
            }
            
            targets {
                all {
                    testTask.configure {
                        shouldRunAfter(tasks.named("test"))
                        testLogging {
                            events(FAILED, SKIPPED)
                            exceptionFormat = TestExceptionFormat.FULL
                        }
                    }
                }
            }
        }
    }
}
```

### Current Behavior

platform dependency does not compile in script plugin in buildSrc

![image](https://user-images.githubusercontent.com/2105382/142669008-f4e56176-90df-413f-a7a3-997af90794c2.png)

### Your Environment
* gradle 7.3
* jvm-test-suite plugin
* used in a script plugin in `buildSrc`

**Comment by Vampire** [comment] 2021-11-19 19:55
It is the same also for normal build scripts, not only precompiled script plugins.
The problem is, that within the test suite `dependencies` block the context object is `JvmComponentDependencies` and not `DependencyHandlerScope`.
Although the `project(...)` call is not read, it also is a different `project` call than one would expect to happen.
Also other things from `DependencyHandlerScope` are missing like `testFixture(...)`.

Work-arounds are to use something like
```kts
implementation(project.dependencies.platform(project.dependencies.project(":myPlatform")))
```
within the test suite dependencies block, or to use the normal dependencies block like with
```kts
val integrationtestImplementation by configurations.getting
dependencies {
    integrationtestImplementation(platform(project(":myPlatform")))
}
```

**Comment by grossws** [comment] 2022-11-19 22:38
Still relevant

**Comment by jfurmankiewiczpros** [comment] 2022-12-28 15:32
Any updates on this? We just tried to use the jvm-test-suite plugin, but the lack of support for platform has been an unexpected roadblock. We have to go back to custom source sets for integration tests instead of using this cool new plugin.

**Comment by LarsKaulen** [comment] 2023-01-12 07:18
Can somebody give a small groovy example, how this should work with 7.6?

Because when I use
```
dependencies {
    testImplementation(platform("com.example:platform"))
}
```
or
```
testing {
    suites {
        configureEach {
            dependencies {
                implementation(project.dependencies.platform("com.example:platform"))
            }
        }
    }
}
```
in a convention plugin everything works as intended, but when using
```
testing {
    suites {
        configureEach {
            dependencies {
                implementation(platform("com.example:platform"))
            }
        }
    }
}
```
I get the following errors:
```
Cannot set attributes for dependency "com.example:platform:null": it was probably created by a plugin using internal APIs
Could not resolve: com.example:platform
```

Might that be a problem in my platform definition/creation?

**Comment by tresat** [comment] 2023-01-12 13:44
@LarsKaulen can you put together a reproducer?  I just tried this and I'm not seeing that problem.

**Comment by LarsKaulen** [comment] 2023-01-12 15:02
Yeah, you can find it [here](https://github.com/LarsKaulen/gradle-reproducers/tree/test-suite-dependency-on-platform)

You can see it works with `implementation(project.dependencies.platform("org.example.gradle:platform"))` [here](https://github.com/LarsKaulen/gradle-reproducers/tree/0ab987d4be7d357a60d09e37c9aa328d1a7e0945) and [here](https://github.com/LarsKaulen/gradle-reproducers/actions/runs/3903386896)

You can see it does not work with `implementation(platform("org.example.gradle:platform"))` [here](https://github.com/LarsKaulen/gradle-reproducers/commit/b245045478e603291366adca6e3de7c4e054f43a) and [here](https://github.com/LarsKaulen/gradle-reproducers/actions/runs/3903427539).

**Comment by tresat** [comment] 2023-01-12 17:24
I'm investigating the issue with convention plugins.

**Comment by tresat** [comment] 2023-01-13 19:54
@LarsKaulen - Thanks for following up on this.  There was indeed a problem using Test Suites and platforms which will be fixed in the next 7.x release (see the attached PR #23535).

**Closed** 2023-01-20 16:28 UTC
Labels: a:bug, in:test-suites
