### ISSUE TITLE
Can't assemble Gradle project when buildSrc uses non-Java 8 toolchain - very confusing errors

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#23993] opened 2023-02-21 22:57 UTC
I have a Gradle 8.0.1 project with a buildSrc that sets Java Toolchain version 11

```kotlin
// buildSrc/build.gradle.kts

plugins {
  `kotlin-dsl`
}

dependencies {
  val kotlinVer = "1.8.0"
  implementation(platform(kotlin("bom", kotlinVer)))
  implementation("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVer")
  implementation("org.jetbrains.kotlin:kotlin-serialization:$kotlinVer")

  implementation("org.jetbrains.kotlin:kotlin-tooling-metadata:$kotlinVer")
  implementation("org.jetbrains.kotlin:kotlin-util-klib-metadata:$kotlinVer")

  implementation("org.jetbrains.kotlinx:kotlinx-metadata-klib:0.0.3")
}


kotlin {
  jvmToolchain(11)
}
```

When I try and `./gradlew assemble` the project, I get a weird error.

```
Could not determine the dependencies of null.
> Could not resolve all task dependencies for configuration ':buildSrc:buildScriptClasspath'.
   > Could not resolve project :buildSrc.
     Required by:
         project :buildSrc
      > No matching variant of project :buildSrc was found. The consumer was configured to find a library for use during runtime, compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.0.1' but:
          - Variant 'apiElements' capability :buildSrc:unspecified declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component for use during compile-time, compatible with Java 11 and the consumer needed a component for use during runtime, compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.1')
          - Variant 'mainSourceElements' capability :buildSrc:unspecified declares a component, and its dependencies declared externally:
              - Incompatible because this component declares a component of category 'verification' and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.1')
                  - Doesn't say anything about its usage (required runtime)
          - Variant 'runtimeElements' capability :buildSrc:unspecified declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 11 and the consumer needed a component, compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.1')
          - Variant 'testResultsElementsForTest' capability :buildSrc:unspecified:
              - Incompatible because this component declares a component of category 'verification' and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.1')
                  - Doesn't say anything about its usage (required runtime)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

The errors are very confusing

* `Could not determine the dependencies of null`
* `Could not resolve project :buildSrc. Required by: project :buildSrc`

When I set the Toolchain to be Java 8

```kotlin
kotlin {
  jvmToolchain(8)
}
```

the project assembles correctly. But I don't want to use Java 8, I want to use Java 11.

I have no idea how to continue...

[kotlin-on-the-rocksdb.zip](https://github.com/gradle/gradle/files/10798471/kotlin-on-the-rocksdb.zip)

### Version

* Gradle 8.0.1
* Windows 10

**Comment by eskatos** [comment] 2023-02-22 09:54
`:buildSrc:buildScriptClasspath` is the configuration that contains the outputs of `buildSrc` for use in the root project script classpath.

What version of Java are you using to run Gradle?

**Comment by aSemy** [comment] 2023-02-22 10:19
I set IntelliJ to use Java 11, the machine's default is Java 17, and I have 8, 11, and 17 installed.

**Comment by eskatos** [comment] 2023-02-22 12:47
I cannot reproduce your problem using the correct Java version to run the build.

However, if I'm using Java 8 to run the build where I ask it to build the build logic for Java 11 I get the exact same error you reported when it tries to resolve the `:buildSrc:buildScriptClasspath` for the build scripts. As I expected.

If your `buildSrc` is configured to use a Java 11 toolchain then you must run your build with a Java >= 11.

As far as I can see this is working as expected. I'm going to close this issue. Please provide a self contained reproducer with build scans or other output stating what Java version you are using to run Gradle.

**Closed by eskatos** 2023-02-22 12:47 UTC
Labels: closed:unreproducible

**Comment by eskatos** [comment] 2023-02-22 13:14
About the IDE use case:

Your screenshot is not about the Java version used to run Gradle but the Java version the source code should be built with.

You need to go to Gradle settings in IDEA:
![image](https://user-images.githubusercontent.com/132773/220629432-c405bb87-72d5-4da4-86a1-b930be7f0fca.png)

----
About the command line output you added above: please verify your `JAVA_HOME` and the output of `./gradlew --version`. The latter will tell you which Java is coming from `JAVA_HOME`. That's what Gradle uses when run from the command line.

**Comment by aSemy** [comment] 2023-02-22 13:30
Ahh thank you, that makes sense. Yes, `JAVA_HOME` was set to the 1.8 install. 

Thank you for helping.

I think my misunderstanding stemmed from [the Java toolchain docs](https://docs.gradle.org/current/userguide/toolchains.html)

> By default, Gradle uses the same Java toolchain for running Gradle itself and building JVM projects.

I thought that this meant I would only need to set toolchain version once.

**Comment by eskatos** [comment] 2023-02-22 14:05
Good you sorted it out!
When you have questions, please prefer using our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).
Triaging issues takes us time and such usage problems makes for less time to make Gradle better.

**Comment by bric3** [comment] 2023-03-30 09:41
I had this error as well, this was due to the fact the buildSrc was setup with the following java target.

```kotlin
java {
    targetCompatibility = JavaVersion.VERSION_19
}
```

But the error message is at best really **confusing**, as I was trying to configure the JVM that run gradle with JDK 1.8 or JDK 11 (IntelliJ picked 11 by default).
Only after noticing in the original comment the following

```kotlin
kotlin {
  jvmToolchain(8)
}
```

I looked at the `build.gradle.kts` and noticed the java target compatibility. I would have expected the `buildSrc` to fail since Gradle was configured to run with JDK 11.

------

For reference the error

```
Could not determine the dependencies of null.
> Could not resolve all task dependencies for configuration ':buildSrc:buildScriptClasspath'.
   > Could not resolve project :buildSrc.
     Required by:
         project :buildSrc
      > No matching variant of project :buildSrc was found. The consumer was configured to find a library for use during runtime, compatible with Java 11, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.0.2' but:
          - Variant 'apiElements' capability :buildSrc:unspecified declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component for use during compile-time, compatible with Java 19 and the consumer needed a component for use during runtime, compatible with Java 11
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.2')
          - Variant 'mainSourceElements' capability :buildSrc:unspecified declares a component, and its dependencies declared externally:
              - Incompatible because this component declares a component of category 'verification' and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.2')
                  - Doesn't say anything about its usage (required runtime)
          - Variant 'runtimeElements' capability :buildSrc:unspecified declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 19 and the consumer needed a component, compatible with Java 11
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.2')
          - Variant 'testResultsElementsForTest' capability :buildSrc:unspecified:
              - Incompatible because this component declares a component of category 'verification' and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.2')
                  - Doesn't say anything about its usage (required runtime)
```

**Comment by bric3** [comment] 2023-04-18 09:02
Ah indeed, I didn't even get the message right.
