### ISSUE TITLE
Define API to control the cacheability of artifact transforms

### ISSUE THREAD

**Issue by doniwinata0309** [gradle/gradle#21067] opened 2022-06-22 11:29 UTC
### Expected Behavior

capability to control cacheable of artifact transform similar to common task:

tasks.named("<taskname>").configure {
    outputs.cacheIf { false }
}

### Current Behavior

Currently unable to control cacheability from artifact transform. 
### Context

Our android build having this issue: https://issuetracker.google.com/issues/169266011 
From chrome trace I can see artifact transform dominating our build and each of them are very large artifact. They also easy to miss and consuming lot of resource.

**Comment by ov7a** [comment] 2024-10-22 13:22
Sorry for the late reply. 

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/27706

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

**Closed by ov7a** 2024-10-22 13:22 UTC
Labels: a:feature, in:artifact-transforms
