### ISSUE TITLE
Document how to build all transitive dependencies from source

### ISSUE THREAD

**Issue by DemiMarie** [gradle/gradle#27167] opened 2023-11-27 03:34 UTC
### Expected Behavior

It is practical for distributions (such as Fedora and Debian) to build all transitive dependencies of Gradle from source code without requiring any precompiled binary dependencies (except for an initial bootstrap).

One approach would be to provide releases that include all necessary source code bundled with Gradle.  Distributions often prefer to not bundle dependencies, but this can often be worked around.  Shipping executable binary code built by a third party is typically forbidden under nearly all circumstances, except for firmware (which Gradle obviously isn’t).

### Current Behavior (optional)

It is not practical for distributions to build all transitive dependencies of Gradle from source.

### Context

Most Linux distributions strictly forbid shipping executable code that the distribution did not itself build from source. 
 Discussions on https://lists.fedoraproject.org indicate that Gradle does not make this simple.  As a result, Debian has Gradle 4.4.1 and Fedora doesn’t package Gradle at all.  Current Fedora packaging guidelines recommend using Maven instead, even when upstream does not support Maven builds.

**Comment by cobexer** [comment] 2023-11-28 13:55
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #26516
***
See [this comment](https://github.com/gradle/gradle/issues/26516#issuecomment-1744912753) on the original issue
If you have anything new to add to the discussion please add it there.

**Closed by cobexer** 2023-11-28 13:55 UTC
Labels: a:feature, to-triage
