### ISSUE TITLE
Project's dependencies cannot be used inside custom JvmTestSuite

### ISSUE THREAD

**Issue by jzrebiec** [gradle/gradle#24050] opened 2023-02-27 10:52 UTC
### Expected Behavior
Project's dependencies can be used inside custom JvmTestSuites like in standard test task

### Current Behavior
Compilation error with unresolved reference

### Context
I want to separate my tests into different categories.

### Steps to Reproduce 
Code: https://github.com/jzrebiec/jvm-test-suite-issue/commit/1ba571a4ac9e01e8c0d4ed5f8d9b759f7d8bd769 
Result: https://github.com/jzrebiec/jvm-test-suite-issue/actions/runs/4281493392/jobs/7454618649

### Your Environment

Build scan URL:

**Comment by eskatos** [comment] 2023-03-03 10:30
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/23477

Which is currently planned for Gradle 8.2.

Please add your use case and 👍 to that issue.

----

In the meantime your best bet is the following:
```
archTestImplementation.extendsFrom(configurations.implementation)
archTestCompileOnly.extendsFrom(configurations.compileOnly)
```

**Closed by eskatos** 2023-03-03 10:30 UTC
Labels: closed:duplicate
