### ISSUE TITLE
Support providers in `project.version`

### ISSUE THREAD

**Issue by bric3** [gradle/gradle#29250] opened 2024-05-22 08:21 UTC
### Expected Behavior

When configuring the project, one can pass an object to the `project.version`, with providers being pushed by the Gradle team I would expect the version to be provider aware.

(And likely other project properties, but they are probably less important than version, because a version can be computed from slower datasource, e.g `git`).

### Current Behavior (optional)

Reproducer.

`build.gradle.kts`
```kotlin
plugins { application }
version = providers.provider { "42" }
```

```shell
$ ./gradlew assemble
```

Will produce (on macOs) the following file name

```shell
$ l build/libs/
Permissions Size User          Date Modified Name
.rw-r--r--@  261 brice.dutheil 22 May 10:10  version-provider-provider(?).jar
```

### Context

Could it be possible to change the behavior of the `version` accessor so that when a provider is passed to the setter, the getter retrieves the provider value instead of giving pack the provider as is.

This behavior might be behind a feature flag to ensure nothing breaks in consuming code. But since `version` is not provider aware, I wonder if there is a lot of plugin or build that expects a provider there.

**Comment by ljacomet** [comment] 2024-05-22 08:59
This issue will be closed as a duplicate of

* #13672

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

**Closed by ljacomet** 2024-05-22 08:59 UTC
Labels: a:feature, closed:duplicate

**Comment by bric3** [comment] 2024-05-22 09:08
Sorry I missed that issue it seems.

> Please add your use case and 👍 to that issue.

Done.
