### ISSUE TITLE
CLI options fail with "linked to multiple elements in class" error when inherited from interface and defined in class

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#19868] opened 2022-02-09 22:33 UTC
### Expected Behavior

Can declare `@set:Option` in an interface and have a task extend that interface to inherit options.

### Current Behavior

7.3 -> 7.4 broke this functionality

```
* What went wrong:
@Option 'resolution-strategy' linked to multiple elements in class 'com.github.triplet.gradle.play.tasks.PublishBundle_Decorated'.
```

### Context + repro

See https://github.com/Triple-T/gradle-play-publisher/issues/1037 for a real-world repro. You can `cd testapp` and then `./gradlew wrapper --gradle-version 7.4` 2 times. To repro, run `./gradlew pBun --resolution-strategy fail -S`.

**Comment by octylFractal** [comment] 2022-02-15 17:28
Do note that the expected behavior here:
> Can declare `@set:Option` in an interface and have a task extend that interface to inherit options.

is exactly what works, and was added by #18510. The issue here is that your classes' methods are _also_ annotated with `@Option`, due to how Kotlin handles delegates, and therefore the `@Option` _is_ defined twice. I will attempt to fix this so that overrides aren't counted as duplicate options.

If you're wondering why it works in 7.3, the PR mentioned above wasn't merged, and therefore Gradle didn't look at your interfaces. It only saw the `@Option` on the classes' methods, which were implicitly added by Kotlin.

**Comment by SUPERCILEX** [comment] 2022-02-15 19:10
Ohhhh, interesting. Thanks for the explanation!

**Closed** 2022-02-18 03:32 UTC
Labels: a:regression, to-triage, in:writing-tasks

**Comment by Calldorado-com** [comment] 2022-09-20 17:25
Thanks! Worked by upgrading to 7.4.2!
