### ISSUE TITLE
6.4-rc-1 - Java Modules project does not export resources to build

### ISSUE THREAD

**Issue by francogp** [gradle/gradle#12879] opened 2020-04-22 23:20 UTC
### Expected Behavior
Project should find resources using SomeObject.class.getResource("file") located in project src/main/resources;

### Current Behavior
SomeObject.class.getResource("file") return null

My temporary fix is to I add this to gradle:
```
sourceSets {
    main {
        output.resourcesDir = java.outputDir
    }
}
```
### Context
I cannot run any project that use the intelliJ structure like:

src/main/java                  -> work fine
src/main/resources         -> It is exported to build, but not located by java using MODULES only

### Steps to Reproduce 
1) Use java modules. If you use classic mode, it work just fine. It only fail with modules
2) use the project structure, like intellij:
src/main/java                 
src/main/resources   
3)  try to load some file in resources, like  SomeObject.class.getResource("file") 

### Your Environment
* The bug can be reproduced in all main OS (windows, ubuntu, mac..)
* Tested with intellij 2020.1

**Comment by ljacomet** [comment] 2020-04-23 07:19
When the code `SomeObject.class.getResource("file")` fails to locate the `file`, is it running through IntelliJ or through Gradle?

From ready your description, it looks like the issue is more with the IDE integration than the support of JPMS in Gradle 6.4.

**Comment by francogp** [comment] 2020-04-23 17:51
> When the code `SomeObject.class.getResource("file")` fails to locate the `file`, is it running through IntelliJ or through Gradle?
> 
> From ready your description, it looks like the issue is more with the IDE integration than the support of JPMS in Gradle 6.4.

Using intellij, but delegating all to Gradle. I will test terminal gradle later. The problem is present also on 6.3 using well known plugins to support modules.

**Comment by jjohannes** [comment] 2020-04-24 08:29
@francogp I think this has to be addressed on the IDEA side. The problem is that IDEA runs the app from the _classes_ folder which does not include the resources. That resources are placed into a different folder by Gradle is by design and never was an issue in pre-module time. Now, ideally, everything belonging to a module should be in one folder, or better in one Jar (then the Manifest is also available which may contain important information like Automatic-Module-Name).

I think what IDEA should do is run the JAR in case of a module. I think this is a related issue:
https://youtrack.jetbrains.com/issue/IDEA-197469

If you use the Gradle `run` task, you will already get this behavior (see: https://github.com/gradle/gradle/issues/890#issuecomment-611592961) and it should work as expected.

**Comment by jjohannes** [comment] 2020-05-04 10:20
Closing this as the issue is tracked here: https://youtrack.jetbrains.com/issue/IDEA-197469

**Closed by jjohannes** 2020-05-04 10:20 UTC
Labels: @jvm, from:contributor, in:jvm-ecosystem, in:modular-java
