### ISSUE TITLE
Improve `Support for nested build without a settings` deprecation warning 

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#5371] opened 2018-05-11 11:21 UTC
### Expected Behavior

`gradle init` in an empty folder shouldn't generate deprecation warning.

### Current Behavior

```
$ gradle init --warning-mode=all
Support for nested build without a settings file was deprecated and will be removed in Gradle 5.0. You should create a empty settings file in /path/to/project
```

### Context
Gradle 4.8

**Comment by marcphilipp** [comment] 2018-05-11 12:09
Looks like this deprecation message was introduced as part of #3137 for 4.4.

**Comment by blindpirate** [comment] 2018-05-11 12:56
Thanks @lacasseio, I guess some ancestor directories of your init directory contain a `settings.gradle` file.

For example, run `gradle init` in childDir of

```
+-- parentDir
  +-- childDir
```
won't cause a deprecation warning, but run `gradle init` in childDir of

```
+-- parentDir
  +-- settings.gradle
  +-- childDir
```

will cause such warning. That's expected behavior. However, if this even makes you confused, I guess we should improve the warning message to at least make users aware of what happens here. I'll keep it open.

**Comment by lacasseio** [comment] 2018-05-11 13:00
Good point, I have a settings file in a parent directory. Given using this `settings.gradle` file is not expected in this use case, we could live with the deprecation warning wait until the next major release to have this fixed automatically.

**Comment by oehme** [comment] 2018-05-11 15:19
It won't be fixed automatically, it'll fail in 5.0. So we definitely need to change this so that `gradle init` doesn't trigger this warning.

**Closed** 2018-07-31 15:27 UTC
Labels: a:chore, from:member, in:build-init-plugin
