### ISSUE TITLE
`DependencyHandler.testFixtures()` is incompatible with project isolation

### ISSUE THREAD

**Issue by erdi** [gradle/gradle#28186] opened 2024-02-22 12:05 UTC
### Current Behavior

When using `DependencyHandler.testFixtures()` in a project with project isolation enabled IntelliJ sync fails due to incompatibility of that method with project isolation.

### Expected Behavior

IntelliJ sync does not fail when using `DependencyHandler.testFixtures()` in a project with project isolation enabled.

### Context (optional)

Stacktrace from configuration cache report:
```
org.gradle.api.InvalidUserCodeException: Cannot access project ':a' from project ':b'
	at org.gradle.internal.component.external.model.ProjectDerivedCapability.equals(ProjectDerivedCapability.java:71)
	at com.google.common.base.Objects.equal(Objects.java:54)
	at com.google.common.collect.Lists.equalsImpl(Lists.java:1010)
	at com.google.common.collect.ImmutableList.equals(ImmutableList.java:685)
	at com.google.common.base.Objects.equal(Objects.java:54)
	at org.gradle.kotlin.dsl.TestImplementationConfigurationAccessorsKt.testImplementation(Unknown Source)
	at Build_gradle$1.invoke(build.gradle.kts:42)
	at Build_gradle$1.invoke(build.gradle.kts:7)
	at org.gradle.kotlin.dsl.ProjectExtensionsKt.dependencies(ProjectExtensions.kt:236)
	at Build_gradle.<init>(build.gradle.kts:7)
	at Program.execute(Unknown Source)
	at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.evaluateSecondStageOf(Interpreter.kt:443)
	at Program.execute(Unknown Source)
	at org.gradle.tooling.internal.consumer.connection.NestedActionAwareBuildControllerAdapter.findModel(NestedActionAwareBuildControllerAdapter.java:31)
	at com.intellij.gradle.toolingExtension.modelAction.DefaultBuildController.findModel(DefaultBuildController.java:69)
	at com.intellij.gradle.toolingExtension.modelProvider.GradleClassProjectModelProvider.populateProjectModels(GradleClassProjectModelProvider.java:52)
	at com.intellij.gradle.toolingExtension.modelAction.GradleModelFetchAction.addProjectModels(GradleModelFetchAction.java:184)
	at com.intellij.gradle.toolingExtension.modelAction.GradleModelFetchAction.lambda$addModels$2(GradleModelFetchAction.java:161)
	at com.intellij.gradle.toolingExtension.modelAction.GradleModelFetchAction.lambda$forEachModelFetchPhase$1(GradleModelFetchAction.java:153)
	at java.base/java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:601)
	at com.intellij.gradle.toolingExtension.modelAction.GradleModelFetchAction.forEachModelFetchPhase(GradleModelFetchAction.java:153)
	at com.intellij.gradle.toolingExtension.modelAction.GradleModelFetchAction.addModels(GradleModelFetchAction.java:158)
	at com.intellij.gradle.toolingExtension.modelAction.GradleModelFetchAction.execute(GradleModelFetchAction.java:67)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.doExecute(ProjectImportAction.java:138)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:91)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:39)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

Cause of the incompatibility seems to be similar to the one in https://github.com/gradle/gradle/issues/27872, namely `ProjectDerivedCapability` is accessing project name, group and version.

### Steps to Reproduce

Add a dependency on test fixtures of another project in the build, enable project isolation and import the build into IntelliJ.

### Gradle version

8.5

**Comment by ljacomet** [comment] 2024-02-22 13:47
This issue will be closed as a duplicate of

* #27872

Please add your use case and 👍 to that issue.

***

Since that other issue covers the general context of dependency resolution and project coordinates access, your specific case fits in.

**Closed by ljacomet** 2024-02-22 13:47 UTC
Labels: a:bug, closed:duplicate, to-triage
