### ISSUE TITLE
Wrapper 4.1-4.8 cause SSL handshake failure MacOs 

### ISSUE THREAD

**Issue by djkingCanada** [gradle/gradle#5736] opened 2018-06-19 23:31 UTC
Updating a project from 2.3 to 4.8...

Installed 4.8 using homebrew, generated a new wrapper
wrapper --gradle-version 4.8 

./gradlew tasks
leads to 

Exception in thread "main" javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:328)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:322)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1614)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:987)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:66)
	at org.gradle.wrapper.Download.download(Download.java:51)
	at org.gradle.wrapper.Install$1.call(Install.java:62)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

 how ever
gradle wrapper --gradle-version 4.0 

./gradlew tasks works just fine.

4.1-4.8 all produce the same exception.

./gradlew -version
------------------------------------------------------------
Gradle 4.0
------------------------------------------------------------

Build time:   2017-06-14 15:11:08 UTC
Revision:     316546a5fcb4e2dfe1d6aa0b73a4e09e8cecb5a5

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_161 (Oracle Corporation 25.161-b12)
OS:           Mac OS X 10.13.5 x86_64

gradle -version
------------------------------------------------------------
Gradle 4.8
------------------------------------------------------------

Build time:   2018-06-04 10:39:58 UTC
Revision:     9e1261240e412cbf61a5e3a5ab734f232b2f887d

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_161 (Oracle Corporation 25.161-b12)
OS:           Mac OS X 10.13.5 x86_64

gradle works just fine.  Also I get the same error when trying to run -version, so seems to be crashing when gradlew tries to download a new version, 4.1-4.8.

**Comment by marcphilipp** [comment] 2018-06-20 06:15
@djkingCanada Thanks for reporting! We're already working on a fix for 4.8.1 in #5734.

**Comment by ljacomet** [comment] 2018-06-20 07:11
That looks like a different problem. #5734 only enables TLSv1.2 support for JDK 7.

And here the error is with JDK8.

@djkingCanada:
Are you behind a company proxy? Which URL is this trying to hit?

**Comment by marcphilipp** [comment] 2018-06-20 07:18
@ljacomet You're right, I missed the JDK 8 part.

This looks more like a problem with SSL certificates on the JDK you're using. But as @ljacomet mentioned, we first need to know which URL is problematic. Looks like it's downloading a distribution via the wrapper so it's probably https://services.gradle.org/distributions/gradle-4.8-all.zip.

@djkingCanada Please confirm.

Once we do, here's how to list the available CA certs:
`keytool -list -keystore $JAVA_HOME/jre/lib/security/cacerts`

**Comment by djkingCanada** [comment] 2018-06-20 17:04
Downloading https://services.gradle.org/distributions/gradle-4.8-bin.zip
is the line before the exception, so I think that's what it is trying to do. 

keytool dump:
[certs.list.txt](https://github.com/gradle/gradle/files/2120326/certs.list.txt)

**Comment by djkingCanada** [comment] 2018-06-20 17:09
I'm in a corporate env, so firewalls but no proxy that I'm aware of.

**Comment by djkingCanada** [comment] 2018-06-20 23:56
Not sure why 4.0 worked, but I'm not getting this if I try the 4.0 all version, so looks like it is a generic pix issue an not a code change that was introduced in the wrapper.

**Comment by marcphilipp** [comment] 2018-06-21 06:51
Strange. Have you tried a different JDK?

Could you download `SSLPoke` from [here](https://confluence.atlassian.com/kb/unable-to-connect-to-ssl-services-due-to-pkix-path-building-failed-779355358.html) and the following?

```
java SSLPoke services.gradle.org 443
```

**Comment by djkingCanada** [comment] 2018-06-21 19:17
SSLPoke works just fine on java SSLPoke services.gradle.org 443
Going to use HTTP in wgradle.properteis and move on.

**Comment by djkingCanada** [comment] 2018-06-21 20:05
Also had the issue with JDK 9, and when I connected my laptop to my cell phone hotspot, so it's not a VM / corporate network issue.

**Comment by ljacomet** [comment] 2018-06-21 20:15
Are the Java installations vanilla or provided by your company?

Also, it will be very hard for us to even look at this problem without either a reproducible test case or a detailed analysis of the SSL failure.
Turning debug on might be a good idea for that second point with `-Djavax.net.debug=ssl:handshake:verbose` or `-Djavax.net.debug=all`

**Comment by djkingCanada** [comment] 2018-06-21 20:38
JDKs are straight for Oracle, latest and greatest for 8 (Updated after reporting the issue)  and 9.  I'll try the debug statements.

**Comment by djkingCanada** [comment] 2018-06-21 20:47
Here is debug log of the failing handshake, using 4.7 as I have 4.8 cached now :)
[handshake.txt](https://github.com/gradle/gradle/files/2125278/handshake.txt)

**Comment by djkingCanada** [comment] 2018-06-21 21:03
So I took a look at the download code for Wrapper and it just does a URL.open() so I thought I'd give that a try, and was able to dump the HTML from the https://services.gradle.org site no problem, here is the log of that handshake:
[Handshake-good.txt](https://github.com/gradle/gradle/files/2125321/Handshake-good.txt)
 
I have a work around using wrapper.properties to avoid HTTPS, but I <3 gradle so if I can help it be more reliable I'd love to help.

**Comment by djkingCanada** [comment] 2018-06-21 21:06
I checked no init scripts.

**Comment by ljacomet** [comment] 2018-06-22 07:33
With both handshakes, it is obvious where the problem lies.

Compare this from the failing connection:
```
Reload the trust store
Reload trust certs
Reloaded 2 trust certs
adding as trusted cert:
  Subject: CN=Shaw Prod Issuing CA 1, DC=PRD, DC=AD
  Issuer:  CN=Shaw Prod Root CA
  Algorithm: RSA; Serial number: 0x1a6604ac00040000000e
  Valid from Tue Jun 30 10:08:06 MDT 2015 until Mon Jun 30 10:18:06 MDT 2025

adding as trusted cert:
  Subject: CN=Shaw Prod Root CA
  Issuer:  CN=Shaw Prod Root CA
  Algorithm: RSA; Serial number: 0x5708248916f58dbe472615041ed2f22c
  Valid from Wed May 26 14:36:11 MDT 2010 until Sat Jun 30 08:57:04 MDT 2035
```

with the following from the good connection:
```
trustStore is: /Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre/lib/security/jssecacerts
trustStore type is : jks
trustStore provider is :
init truststore
adding as trusted cert:
  Subject: CN=Equifax Secure Global eBusiness CA-1, O=Equifax Secure Inc., C=US
  Issuer:  CN=Equifax Secure Global eBusiness CA-1, O=Equifax Secure Inc., C=US
  Algorithm: RSA; Serial number: 0xc3517
  Valid from Sun Jun 20 22:00:00 MDT 1999 until Sun Jun 21 22:00:00 MDT 2020

adding as trusted cert:
  Subject: CN=Entrust Root Certification Authority - EC1, OU="(c) 2012 Entrust, Inc. - for authorized use only", OU=See www.entrust.net/legal-terms, O="Entrust, Inc.", C=US
  Issuer:  CN=Entrust Root Certification Authority - EC1, OU="(c) 2012 Entrust, Inc. - for authorized use only", OU=See www.entrust.net/legal-terms, O="Entrust, Inc.", C=US
  Algorithm: EC; Serial number: 0xa68b79290000000050d091f9
  Valid from Tue Dec 18 08:25:36 MST 2012 until Fri Dec 18 08:55:36 MST 2037

adding as trusted cert:
  Subject: CN=SecureTrust CA, O=SecureTrust Corporation, C=US
  Issuer:  CN=SecureTrust CA, O=SecureTrust Corporation, C=US
  Algorithm: RSA; Serial number: 0xcf08e5c0816a5ad427ff0eb271859d0
  Valid from Tue Nov 07 12:31:18 MST 2006 until Mon Dec 31 12:40:55 MST 2029

[edited because quite long]

adding as trusted cert:
  Subject: CN=COMODO ECC Certification Authority, O=COMODO CA Limited, L=Salford, ST=Greater Manchester, C=GB
  Issuer:  CN=COMODO ECC Certification Authority, O=COMODO CA Limited, L=Salford, ST=Greater Manchester, C=GB
  Algorithm: EC; Serial number: 0x1f47afaa62007050544c019e9b63992a
  Valid from Wed Mar 05 17:00:00 MST 2008 until Mon Jan 18 16:59:59 MST 2038

[end removed because really long]
```

and that `COMODO ECC Certification Authority` is the root certificate for  https://services.gradle.org.

So you need to figure out why when running Gradle you end up with a different truststore.

I am going to close this as it really does not look like a Gradle issue but rather an environment issue.

**Closed by ljacomet** 2018-06-22 07:33 UTC
Labels: a:bug, from:contributor, in:core

**Comment by subash1** [comment] 2019-05-08 20:03
@djkingCanada have you found the solution

**Comment by a4ambrish** [comment] 2020-01-19 17:56
Please check the size of cacerts file into your JAVA_HOME lib/security/cacerts and if it is not having root certificates then simply replace it with cacerts file from any other version of the JDK.
