### ISSUE TITLE
Gradle 4.3 ignores proxy settings from _JAVA_OPTIONS system variable

### ISSUE THREAD

**Issue by BrainStone** [gradle/gradle#3364] opened 2017-11-03 12:39 UTC
### Expected Behavior
Up to Gradle 4.2 I was able to provide global proxy information for all Java processes by setting the system variable `_JAVA_OPTIONS` to something like this:  
`export _JAVA_OPTIONS='-Dhttp.proxyHost=proxy.ip -Dhttp.proxyPort=3128 -Dhttps.proxyHost=proxy.ip -Dhttps.proxyPort=3128'`

I'd expect this to still work for Gradle 4.3

### Current Behavior
Currently it appears to be ignored, du to the recent changes related to Time Outs for HTTP request. The end result is that all dependecies time out, while I'm still able to connect to the internet and download the appropriate jars through any ther application.

Example log:
```
* What went wrong:
A problem occurred evaluating root project 'Core'.
> Could not resolve all files for configuration 'classpath'.
   > Could not download gradle-lombok.jar (io.franzbecker:gradle-lombok:1.10)
      > Could not get resource 'https://plugins.gradle.org/m2/io/franzbecker/gradle-lombok/1.10/gradle-lombok-1.10.jar'.
         > Could not HEAD 'https://plugins.gradle.org/m2/io/franzbecker/gradle-lombok/1.10/gradle-lombok-1.10.jar'.
            > Read timed out
   > Could not download spongegradle.jar (gradle.plugin.org.spongepowered:spongegradle:0.8.1)
      > Could not get resource 'https://plugins.gradle.org/m2/gradle/plugin/org/spongepowered/spongegradle/0.8.1/spongegradle-0.8.1.jar'.
         > Could not HEAD 'https://plugins.gradle.org/m2/gradle/plugin/org/spongepowered/spongegradle/0.8.1/spongegradle-0.8.1.jar'.
            > Read timed out
   > Could not download gradlePlugin.jar (gradle.plugin.com.github.spotbugs:gradlePlugin:1.5)
      > Could not get resource 'https://plugins.gradle.org/m2/gradle/plugin/com/github/spotbugs/gradlePlugin/1.5/gradlePlugin-1.5.jar'.
         > Could not HEAD 'https://plugins.gradle.org/m2/gradle/plugin/com/github/spotbugs/gradlePlugin/1.5/gradlePlugin-1.5.jar'.
            > Read timed out
   > Could not download gradle-plugins.jar (io.freefair.gradle:gradle-plugins:2.0.2)
      > Could not get resource 'https://plugins.gradle.org/m2/io/freefair/gradle/gradle-plugins/2.0.2/gradle-plugins-2.0.2.jar'.
         > Could not HEAD 'https://plugins.gradle.org/m2/io/freefair/gradle/gradle-plugins/2.0.2/gradle-plugins-2.0.2.jar'.
            > Read timed out
```

### Context
I'm working behind a proxy and did succeed in properly having all Java applications work by setting proxy values in the `_JAVA_OPTIONS` environment variable.

### Steps to Reproduce (for bugs)
- Work behind a proxy and set the `_JAVA_OPTIONS` environment variable to an appropriate value.
- Execute any gradle task that needs dependcies to be downloaded and watch them time out.

### Your Environment
- OS: Fedora 26
- Network: University network behind a proxy
- Java: openjdk version "1.8.0_144"

 * Build scan URL: Not possible as I currently can't download dependcies. Including plugins

**Comment by oehme** [comment] 2017-11-03 15:55
I'm not sure why the timeout handling would affect this, except if the repository in question takes longer than 10s to respond due to the proxy.

We do intend to raise those timeouts to 30s, but it would be interesting if anything else has changed here. /cc @bmuschko

**Comment by BrainStone** [comment] 2017-11-03 16:04
Tbh I can only guess. But based on the fact that it worked on 4.2 and on 4.3 it doesn’t I’m guessing that something related to the timeout causes the the proxy settings to be ignored/overridden. I’m certain that the repos respond in a timely manner. I tested downloading the mentioned jar files with wget and they were downloaded well within a second each.

**Comment by bmuschko** [comment] 2017-11-03 16:49
@BrainStone Just as a test could you try to add `-Dhttp.connectionTimeout=60000` and `-Dhttp.socketTimeout=60000` to `_JAVA_OPTIONS` to see if that works? I am going to try to identify if there's something else going in the meantime.

**Comment by bmuschko** [comment] 2017-11-03 18:54
So far I haven't been able to reproduce the issue. I used the following build script:

```
apply plugin: 'base'

repositories {
    mavenCentral()
}

configurations {
    myConf
}

dependencies {
    myConf 'commons-lang:commons-lang:2.5'
}

task copyLibs(type: Copy) {
    from configurations.myConf
    into "$buildDir/libs"
}
```

Here's what I did:

1. Delete the Gradle cache (`~/.gradle`) to ensure that Gradle has to make the actual HTTP call and does not get the artifact from the cache.
2. Killed all Gradle daemon processes to ensure that a new daemon is started that uses the environment variable.
2. Run `export _JAVA_OPTIONS='-Dhttp.proxyHost=proxy.ip -Dhttp.proxyPort=3128 -Dhttps.proxyHost=proxy.ip -Dhttps.proxyPort=3128'`.
3. Run `gradle clean copyLibs`.

I see the following error message which indicates that it tries to use the Proxy settings for the HTTPS call:

```
clean UP-TO-DATE
:copyLibs FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':myConf'.
> Could not resolve commons-lang:commons-lang:2.5.
  Required by:
      project :
   > Could not resolve commons-lang:commons-lang:2.5.
      > Could not get resource 'https://repo1.maven.org/maven2/commons-lang/commons-lang/2.5/commons-lang-2.5.pom'.
         > Could not GET 'https://repo1.maven.org/maven2/commons-lang/commons-lang/2.5/commons-lang-2.5.pom'.
            > proxy.ip: unknown error
```

What I think happened for you is that the HTTP call got through your proxy but `https://plugins.gradle.org` didn't respond within the 10 seconds timeout. I have recently seen some intermittent issues with plugin portal. Could you give it another try to see if it works for you now? Please also try to change the default HTTP(S) timeout settings.

**Comment by BrainStone** [comment] 2017-11-05 16:25
I apologize for my late reply. I currently can't access the university computers. But one thing that might make a difference I didn't pay too much attention to before was the fact that it failed on downloading the plugins or to be more precise dependencies in the buildscript block. Not the regular dependencies themselves.

I will check what you asked me to as soon as I get access to the computers again. Could you also please check that with buildscript dependencies @bmuschko ?

Thanks a lot for looking into this!

**Comment by bmuschko** [comment] 2017-11-05 17:00
@BrainStone The code for downloading dependencies ends up using the same HTTP handling code so that shouldn't matter. I get the same issue when using the following build script and the procedure described above:

```
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "io.franzbecker:gradle-lombok:1.10"
  }
}

apply plugin: "io.franzbecker.gradle-lombok"
```

```
$ gradle buildEnvironment
Picked up _JAVA_OPTIONS: -Dhttp.proxyHost=proxy.ip -Dhttp.proxyPort=3128 -Dhttps.proxyHost=proxy.ip -Dhttps.proxyPort=3128
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'httpProxy'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve io.franzbecker:gradle-lombok:1.10.
     Required by:
         project :
      > Could not resolve io.franzbecker:gradle-lombok:1.10.
         > Could not get resource 'https://plugins.gradle.org/m2/io/franzbecker/gradle-lombok/1.10/gradle-lombok-1.10.pom'.
            > Could not GET 'https://plugins.gradle.org/m2/io/franzbecker/gradle-lombok/1.10/gradle-lombok-1.10.pom'.
               > proxy.ip: unknown error
```

**Comment by bmuschko** [comment] 2017-11-06 15:18
@BrainStone Do you have any other feedback here? At the moment it doesn't look like an actual issue. We'll soon release Gradle 4.3.1 with a couple of changes to the behavior. For example the timeout for HTTP requests will be set to 30 secs instead of 10 secs.

**Comment by BrainStone** [comment] 2017-11-06 22:13
I'll try to do some more debugging on my end asap. Will let you know.

**Comment by bmuschko** [comment] 2017-11-07 00:16
A debug log might be helpful. Definitely send it over so we can have a look.

**Comment by BrainStone** [comment] 2017-11-07 08:06
So I created an example repo where I can recreate the issue. I've noticed that it doesn't fail for all buildscript dependecies, but it fails for the one in the example repo: https://github.com/BrainStone/gradle-issue3364-example

I ran `./gradlew --debug build | tee gradle.log` and uploaded the file here: https://gist.github.com/BrainStone/d07a24d9e3cd649e15b43e59d3ede2fd

I hope that helps.

**Comment by bmuschko** [comment] 2017-11-07 15:53
@BrainStone Thanks, I will have a look right now.

**Comment by bmuschko** [comment] 2017-11-07 16:26
> So I created an example repo where I can recreate the issue. I've noticed that it doesn't fail for all buildscript dependecies, but it fails for the one in the example repo

Had a look at the debug log and it doesn't seem like your build is failing. In fact the HTTP GET request happens here for the buildscript dependency. Is that the one that's failing?

```
09:03:36.892 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver] Attempting to resolve component for gradle.plugin.com.github.spotbugs:gradlePlugin:1.6.0 using repositories [maven]
09:03:36.892 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading https://plugins.gradle.org/m2/gradle/plugin/com/github/spotbugs/gradlePlugin/1.6.0/gradlePlugin-1.6.0.pom
09:03:36.892 [DEBUG] [org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor] Constructing external resource: https://plugins.gradle.org/m2/gradle/plugin/com/github/spotbugs/gradlePlugin/1.6.0/gradlePlugin-1.6.0.pom
09:03:36.892 [INFO] [org.gradle.cache.internal.DefaultCacheAccess] Creating new cache for metadata-2.31/artifact-at-url, path /tmp/modules-2/metadata-2.31/artifact-at-url.bin, access org.gradle.cache.internal.DefaultCacheAccess@5b58bb06
09:03:36.892 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Opening cache artifact-at-url.bin (/tmp/modules-2/metadata-2.31/artifact-at-url.bin)
09:03:36.893 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Download https://plugins.gradle.org/m2/gradle/plugin/com/github/spotbugs/gradlePlugin/1.6.0/gradlePlugin-1.6.0.pom' started
09:03:36.893 [DEBUG] [org.gradle.internal.resource.transport.http.HttpResourceAccessor] Constructing external resource: https://plugins.gradle.org/m2/gradle/plugin/com/github/spotbugs/gradlePlugin/1.6.0/gradlePlugin-1.6.0.pom
09:03:36.893 [DEBUG] [org.gradle.internal.resource.transport.http.HttpClientHelper] Performing HTTP GET: https://plugins.gradle.org/m2/gradle/plugin/com/github/spotbugs/gradlePlugin/1.6.0/gradlePlugin-1.6.0.pom
```

and here:

```
09:03:49.763 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Executing request GET /m2/com/github/spotbugs/spotbugs-annotations/3.1.0/spotbugs-annotations-3.1.0.pom HTTP/1.1
```

I can also see that the proxy is being used for HTTP requests:

```
09:03:36.899 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection request: [route: {tls}->http://proxy.ira.uni-karlsruhe.de:3128->https://plugins.gradle.org:443][total kept alive: 0; route allocated: 0 of 20; total allocated: 0 of 20]
09:03:36.899 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection leased: [id: 38][route: {tls}->http://proxy.ira.uni-karlsruhe.de:3128->https://plugins.gradle.org:443][total kept alive: 0; route allocated: 1 of 20; total allocated: 1 of 20]
09:03:36.899 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Opening connection {tls}->http://proxy.ira.uni-karlsruhe.de:3128->https://plugins.gradle.org:443
09:03:36.900 [DEBUG] [org.apache.http.impl.conn.DefaultHttpClientConnectionOperator] Connecting to proxy.ira.uni-karlsruhe.de/141.3.10.130:3128
```

I also searched for `ERROR` and `WARN` in your log but couldn't find any. Which dependency is failing for you? Can you please point me to the error in the log file? Did you have a chance to try out my suggestion about setting the timeouts?

Soon we'll release 4.3.1 which includes a couple of changes to dependency error handling. Maybe that will actually solve it for you also.

BTW: I couldn't compile your code due to a missing, declared dependency on Guava. Adding `compile 'com.google.guava:guava:23.0'` does fix the compilation issue. Is that what you were tripping over?


```
./gradlew clean build
Parallel execution is an incubating feature.

> Task :compileJava FAILED
/Users/bmuschko/dev/projects/gradle-playground/gradle-issue3364-example/src/main/java/test/Test.java:3: error: package com.google.common.base does not exist
import com.google.common.base.Preconditions;
                             ^
/Users/bmuschko/dev/projects/gradle-playground/gradle-issue3364-example/src/main/java/test/Test.java:7: error: cannot find symbol
    Preconditions.checkArgument(args.length == 0, "No arguments allowed!");
    ^
  symbol:   variable Preconditions
  location: class Test
2 errors
```

**Comment by bmuschko** [comment] 2017-11-07 17:04
@BrainStone Could you try out your project with a snapshot of the 4.3.1 release? https://downloads.gradle.org/distributions-snapshots/gradle-4.3.1-20171107130851+0000-bin.zip

**Comment by BrainStone** [comment] 2017-11-08 01:29
Hm. I must have forgotten to capture stderr. Will do it again.

Is there a command to set the wrapper to that version?

**Comment by bmuschko** [comment] 2017-11-08 01:38
@BrainStone If you copied the logs from the console then I believe standard output/error should be in there already. Maybe a little screencast with [Asciinema](https://asciinema.org/) might be helpful as well.

**Comment by BrainStone** [comment] 2017-11-08 09:06
Interstingly enough the 4.3.1 snapshot works.

I still captured the output for gradle 4.2, 4.3 and 4.3.1-SNAPSHOT in case you are interested: https://gist.github.com/BrainStone/72d0245a5b8c76df79d3080a6af3ae47 (this time I captured stdout and stderr).

Thank you for your patience!

**Comment by bmuschko** [comment] 2017-11-08 16:22
Thanks for providing the full log. I see that the proxy is used but the request times out. This has been mitigated by increasing the timeout to 30 seconds in 4.3.1. I am going to close this issue as 4.3.1 works fine for you. Let us know if you are still experiencing issues with that version.

**Closed by bmuschko** 2017-11-08 16:22 UTC
Labels: a:bug, from:contributor, in:core

**Comment by nb312** [comment] 2018-08-15 07:07
I still have this problem .
```
15:05:40.455 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
15:05:40.456 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
15:05:40.456 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
15:05:40.456 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] A problem occurred configuring root project 'NBExample'.
15:05:40.456 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Could not resolve all files for configuration ':classpath'.
15:05:40.456 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > Could not resolve com.android.tools.build:gradle:3.1.3.
15:05:40.456 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]      Required by:
15:05:40.456 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]          project :
15:05:40.456 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]       > Could not resolve com.android.tools.build:gradle:3.1.3.
15:05:40.456 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]          > Could not get resource 'https://dl.google.com/dl/android/maven2/index.html/com/android/tools/build/gradle/3.1.3/gradle-3.1.3.pom'.
15:05:40.456 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]             > Could not HEAD 'https://dl.google.com/dl/android/maven2/index.html/com/android/tools/build/gradle/3.1.3/gradle-3.1.3.pom'.
15:05:40.456 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]                > dl.google.com:443 failed to respond
15:05:40.456 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
15:05:40.456 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
15:05:40.456 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.  Run with --scan to get full insights.
15:05:40.456 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
15:05:40.456 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
15:05:40.456 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] 
15:05:40.456 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 2s

```
