### ISSUE TITLE
startParameter.setExcludedTaskNames(['test']) not working on 6.8 and 6.8+ versions

### ISSUE THREAD

**Issue by sajjad4u** [gradle/gradle#17989] opened 2021-08-10 10:33 UTC
I have a main project and 2 subprojects and It is  build  programmatically with task in build.gradle in main project (myproject) and tht same was working till the gradle version 6.7.1 but in later versions like 6.8+ the skip test task seems not working as it is running the compileTestJava in subprojects. 

**Project Structure**
```
myproject > subproject1 > subproject1-code
                        > subproject1-test
          > subproject2 > subproject2-code
                        > subproject2-test
```
**build.gradle (myproject)**
```
String[] buildOrder = [
        "subproject1",
        "subproject2",
]

task myBuild() {
    buildOrder.each { def componentName ->
        def componentTaskName = componentName.replaceAll('/', '_')
        tasks.create(name: "build_$componentTaskName", type: GradleBuild) {
	          buildFile = componentName + "/build.gradle"
	          startParameter.setExcludedTaskNames(['test'])
	          tasks = ['clean', 'build']
        }
        build.dependsOn "build_$componentTaskName"
    }
}
```

**Comment by sajjad4u** [comment] 2021-08-15 12:32
hi

**Comment by sajjad4u** [comment] 2021-08-15 12:33
Is there any update

**Comment by donat** [comment] 2021-08-16 14:44
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

This issue will be closed after 7 days, unless you can provide more information.

**Comment by philipp94831** [comment] 2021-09-06 05:40
Hi, I also experience issues with Gradle 6.8. I am using the [release plugin](https://plugins.gradle.org/plugin/net.researchgate.release) but exclude test when running it. With Gradle 6.7.x this just worked fine but with Gradle 6.8.x it does not work anymore. I also created a small project with which you can reproduce the issue: https://github.com/philipp94831/gradle-exclusion-demo. Should I open another issue or is this related to this?

**Comment by donat** [comment] 2021-12-01 15:42
Duplicate of https://github.com/gradle/gradle/issues/18196

**Closed by donat** 2021-12-01 15:42 UTC
Labels: a:regression, closed:duplicate, affects-version:6.8
