### ISSUE TITLE
Disallow multiple tasks having the same output file

### ISSUE THREAD

**Issue by mathjeff** [gradle/gradle#12173] opened 2020-02-07 20:36 UTC
### Expected Behavior
If two tasks declare the same file as output, it would be nice for Gradle to report an error.

In practice, it would probably be good enough to enforce that no two tasks that executed during the same build declared the same file as an output
It would probably also be good enough to wait until after the tasks execute before running these checks
It would probably also be good enough to only enable this validation by default for regular files

### Current Behavior
If two Gradle plugins both choose the same filepath at which to generate an output file, then Gradle doesn't report an error. It seems that tasks that depend on this filepath will observe different file content based on which task executed most recently.

### Context
I was observing was that the shadow plugin and, I think, the kotlin plugin, were both writing to build/libs/$projectname.jar , causing the consumer, lint, to observe one of the files seemingly at random and ultimately resulting in a seemingly random set of lint checks running. See https://android-review.googlesource.com/c/platform/frameworks/support/+/1230051/1//COMMIT_MSG

**Comment by mathjeff** [comment] 2020-05-07 15:43
Looks like this might be a duplicate of https://github.com/gradle/gradle/issues/9041 , moving some info over to there

**Comment by mlopatkin** [comment] 2021-06-10 09:09
Duplicate of #9041

**Closed by mlopatkin** 2021-06-10 09:09 UTC
Labels: a:feature, to-triage
