### ISSUE TITLE
Init Scripts no longer have ability to turn parallelism off

### ISSUE THREAD

**Issue by JasonGriffith** [gradle/gradle#3844] opened 2017-12-19 00:51 UTC
Hello!

In Gradle 4.0.2, it was possible to disable parallelism in an init script with this:
gradle.startParameter.parallelProjectExecutionEnabled = false
gradle.startParameter.maxWorkerCount = 1

Somewhere in, on, or around Gradle 4.3.1, that no longer works.

We'd like to have this ability because it allows us to wrap any and all Gradle invokations with a tool that watches O/S-level reads and writes, and helps us build correct inputs and outputs for our custom tasks.  We can, of course, work around this issue by turning parallelism off before running all of this, but having to do nothing other than specify an init script to invoke this tool is wiiiiiicked awesome.  Would love to keep that :)

### Expected Behavior
For at least Windows, when an init script with the above code is invoked, parallelism is turned off and all tasks execute serially.  I'm not sure if this hits other operating systems.

### Current Behavior
Nothing happens; parallelism is unaffected and tasks run in-parallel.

### Context
We have a tool that watches for file reads and writes for any Gradle task.  Tasks run in-parallel wreck this as we can't tell which task is affecting which file.

### Steps to Reproduce (for bugs)
[InitScriptParallelismDemo.zip](https://github.com/gradle/gradle/files/1569901/InitScriptParallelismDemo.zip)

The attached demo is set to use Gradle 4.0.2 through the wrapper, and the steps spelled out in /build.gradle should show what to execute and what the results are:

gradlew allTheThings
    > Runs in serial
gradlew aTT --parallel
    > Runs in parallel
gradlew aTT --parallel -I init.serial.gradle
    > **Runs in serial**

set GRADLE_OPTS=-Dorg.gradle.parallel=true
gradlew aTT
    > Runs in parallel
gradlew aTT -I init.serial.gradle
    > **Runs in serial**

Now update to use Gradle 4.4 (assuming you have a 'gradle' binary on the PATH):
gradle wrapper --gradle-version 4.4

gradlew allTheThings
    > Runs in serial
gradlew aTT --parallel
    > Runs in parallel
gradlew aTT --parallel -I init.serial.gradle
    > **Runs in parallel**

set GRADLE_OPTS=-Dorg.gradle.parallel=true
gradlew aTT
    > Runs in parallel
gradlew aTT -I init.serial.gradle
    > **Runs in parallel**

### Your Environment
Windows 10.  No build scans aimed at gradle.org, but I'd recommend unzipping and trying the demo.

Thank you very much!

**Comment by ghale** [comment] 2017-12-20 15:43
This is happening because we've moved some things around such that the parallelism configuration is being set early in the build process when we parse the command line, but subsequent changes to `StartParameter` are not being reflected in the underlying services.  In other words, `StartParameter` is no longer the source of truth for this information.  The fact that it worked before was more a side effect of the implementation than necessarily intended functionality.  We _could_ provide a way for the user to modify the parallelism configuration after the build has started, but doing this inside an init script would be pretty late (i.e. other things could have happened in parallel already, such as configuration resolution).  It's possible that in earlier versions of Gradle, this was early enough that nothing would be affected during the period that parallelism was still enabled before you disabled it, but I'm sure this is no longer the case.  In other words, setting it after the build has started would be solution to a use case for dynamically modifying the parallelism as a response to some state/event - it wouldn't be a solution to a use case for wanting to disable it altogether.

If you just want parallelism disabled, setting `--max-workers=1` or setting `org.gradle.workers.max=1` in a gradle.properties file is probably a better solution.

**Comment by JasonGriffith** [comment] 2017-12-20 18:16
Thanks for the explanation, Gary.  Kinda figured it was something along those lines. :) 

However, I think having a place for folks to put code that executes before anything happens is powerful.  As a user, the phrase "initialization script" fits that bill perfectly (IMO), and the documentation clearly states that these scripts are run before "the build" starts...  Shouldn't setting startParameters in an init script be expected to have an effect?  Feel free to close this bug if ya'll disagree, but I'll just leave it open because to be honest it still seems like this should work or at least spit out a warning that you done messed up.

At any rate, thanks for the other solution!  I was really shooting for just an extra blurb for folks to tack on to a gradle command to run this report, and adding a "--max-workers=1" to the end hits that goal.  Cheers!

**Comment by ghale** [comment] 2017-12-20 21:02
That's a good suggestion - we should probably warn when this happens (a max-worker change to `StartParameter`) after the parallelism configuration has been set.  I think it's a valid feature to be able to modify this while Gradle is running, and something that we probably will support at some point, but it might not necessarily be via `StartParameter`.

The term "the build" is really overloaded and I should be more explicit.  What I really mean here is "the invocation of Gradle".  Running the init script is part of that invocation and the problem is that once you start running the init script, there are already certain things that need to be known and set up (such as the configuration of parallelism).  `StartParameter` is a little coarse in that it contains some settings that affect the whole invocation and other settings that affect just things that occur after the init script has executed.  Changes to things that affect the whole invocation (such as parallelism) while the init script is running need to be propagated to services and the such that are already configured with the initial settings.  This is not difficult to do for the parallelism settings, but the wiring just isn't there right now to do this.

**Comment by JasonGriffith** [comment] 2017-12-21 18:42
Thanks, Gary!

Stefan, we weren't wrapping this before, but now we are and are doing exactly what you're suggesting.  :)  Cheers!

**Comment by bmuschko** [comment] 2017-12-27 16:42
Looks like we can close the issue. Please add another comment if you need further assistance.

**Closed by bmuschko** 2017-12-27 16:42 UTC
Labels: a:bug, from:contributor
