### ISSUE TITLE
Gradle cannot snapshot classes in org.glassfish.hk2.external:asm-all-repackaged:2.5.0-b32

### ISSUE THREAD

**Issue by adrian-baker** [gradle/gradle#5160] opened 2018-04-24 20:43 UTC
Upon enabling incremental compilation for a spring boot project, I got the following exception:

    org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileJava'.
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
            at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
            at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
            at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
            at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
            at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
            at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
            at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
            at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
            at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
            at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
            at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
            at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
            at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
            at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
            at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
            at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
            at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
            at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
            at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
            at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:596)
            at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
            at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
            at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
            at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
    Caused by: org.gradle.api.GradleException: Could not expand ZIP 'C:\Users\adrian\.gradle\caches\modules-2\files-2.1\org.glassfish.hk2.external\asm-all-repackaged\2.5.0-b32\dc705f1d54cd5a96cbc5a473525e75ef1cb59a9e\asm-all-repackaged-2.5.0-b32.jar'.
            at org.gradle.api.internal.file.archive.ZipFileTree.visit(ZipFileTree.java:104)
            at org.gradle.api.internal.file.collections.FileTreeAdapter.visit(FileTreeAdapter.java:116)
            at org.gradle.api.internal.tasks.compile.incremental.jar.DefaultJarSnapshotter.createSnapshot(DefaultJarSnapshotter.java:45)
            at org.gradle.api.internal.tasks.compile.incremental.jar.CachingJarSnapshotter$1.create(CachingJarSnapshotter.java:42)
            at org.gradle.api.internal.tasks.compile.incremental.jar.CachingJarSnapshotter$1.create(CachingJarSnapshotter.java:40)
            at org.gradle.api.internal.tasks.compile.incremental.jar.DefaultJarSnapshotCache$1.create(DefaultJarSnapshotCache.java:53)
            at org.gradle.api.internal.tasks.compile.incremental.jar.DefaultJarSnapshotCache$1.create(DefaultJarSnapshotCache.java:51)
            at org.gradle.cache.internal.MinimalPersistentCache.get(MinimalPersistentCache.java:36)
            at org.gradle.api.internal.tasks.compile.incremental.jar.DefaultJarSnapshotCache.get(DefaultJarSnapshotCache.java:51)
            at org.gradle.api.internal.tasks.compile.incremental.jar.DefaultJarSnapshotCache.get(DefaultJarSnapshotCache.java:28)
            at org.gradle.api.internal.tasks.compile.incremental.jar.CachingJarSnapshotter.createSnapshot(CachingJarSnapshotter.java:40)
            at org.gradle.api.internal.tasks.compile.incremental.jar.JarClasspathSnapshotFactory.createSnapshot(JarClasspathSnapshotFactory.java:43)
            at org.gradle.api.internal.tasks.compile.incremental.jar.JarClasspathSnapshotMaker.maybeInitialize(JarClasspathSnapshotMaker.java:63)
            at org.gradle.api.internal.tasks.compile.incremental.jar.JarClasspathSnapshotMaker.getJarClasspathSnapshot(JarClasspathSnapshotMaker.java:52)
            at org.gradle.api.internal.tasks.compile.incremental.CurrentCompilation.getClasspathSnapshot(CurrentCompilation.java:42)
            at org.gradle.api.internal.tasks.compile.incremental.RecompilationSpecProvider.processJarClasspathChanges(RecompilationSpecProvider.java:53)
            at org.gradle.api.internal.tasks.compile.incremental.RecompilationSpecProvider.provideRecompilationSpec(RecompilationSpecProvider.java:46)
            at org.gradle.api.internal.tasks.compile.incremental.SelectiveCompiler.execute(SelectiveCompiler.java:57)
            at org.gradle.api.internal.tasks.compile.incremental.SelectiveCompiler.execute(SelectiveCompiler.java:33)
            at org.gradle.api.internal.tasks.compile.incremental.IncrementalResultStoringDecorator.execute(IncrementalResultStoringDecorator.java:44)
            at org.gradle.api.internal.tasks.compile.incremental.IncrementalResultStoringDecorator.execute(IncrementalResultStoringDecorator.java:28)
            at org.gradle.api.internal.tasks.compile.incremental.IncrementalAnnotationProcessingCompiler.execute(IncrementalAnnotationProcessingCompiler.java:50)
            at org.gradle.api.internal.tasks.compile.incremental.IncrementalAnnotationProcessingCompiler.execute(IncrementalAnnotationProcessingCompiler.java:36)
            at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:156)
            at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:126)
            at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
            at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
            at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
            at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
            at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
            at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
            ... 29 more
    Caused by: java.lang.ArrayIndexOutOfBoundsException: 32800
            at org.objectweb.asm.ClassReader.readUTF(ClassReader.java:3351)
            at org.objectweb.asm.ClassReader.readUTF8(ClassReader.java:3338)
            at org.objectweb.asm.ClassReader.readModule(ClassReader.java:665)
            at org.objectweb.asm.ClassReader.accept(ClassReader.java:503)
            at org.objectweb.asm.ClassReader.accept(ClassReader.java:355)
            at org.gradle.api.internal.tasks.compile.incremental.asm.ClassDependenciesVisitor.analyze(ClassDependenciesVisitor.java:71)
            at org.gradle.api.internal.tasks.compile.incremental.analyzer.DefaultClassDependenciesAnalyzer.getClassAnalysis(DefaultClassDependenciesAnalyzer.java:34)
            at org.gradle.api.internal.tasks.compile.incremental.analyzer.DefaultClassDependenciesAnalyzer.getClassAnalysis(DefaultClassDependenciesAnalyzer.java:42)
            at org.gradle.api.internal.tasks.compile.incremental.analyzer.CachingClassDependenciesAnalyzer$1.create(CachingClassDependenciesAnalyzer.java:37)
            at org.gradle.api.internal.tasks.compile.incremental.analyzer.CachingClassDependenciesAnalyzer$1.create(CachingClassDependenciesAnalyzer.java:35)
            at org.gradle.cache.internal.MinimalPersistentCache.get(MinimalPersistentCache.java:36)
            at org.gradle.api.internal.tasks.compile.incremental.analyzer.CachingClassDependenciesAnalyzer.getClassAnalysis(CachingClassDependenciesAnalyzer.java:35)
            at org.gradle.api.internal.tasks.compile.incremental.jar.DefaultJarSnapshotter$1.visitFile(DefaultJarSnapshotter.java:66)
            at org.gradle.api.internal.file.archive.ZipFileTree.visit(ZipFileTree.java:97)
            ... 65 more

The root cause appears to that Spring -> Jersey includes a dependency on a library compiled for JDK 1.9 (https://github.com/eclipse-ee4j/jersey/issues/3617). 

However it seems unfortunate that the error isn't more obvious. The workarounds I can see:
- upgrade to Java 9?
- disabling incremental compilation
- forcing the asm dependency to an earlier version (2.4.0 works)
- avoiding the use of the Spring starter projects, which seem to pull in a large amount of stuff into the compile classpath (https://github.com/spring-projects/spring-boot/issues/8341).

Simple example reproducing the issue at https://github.com/adrian-baker/gradle-scratchpad/tree/master/bug-incremental-build-fails-with-asm-all-repackaged .

**Comment by oehme** [comment] 2018-04-25 07:49
This is either an ASM bug or `asm-all-repackaged-2.5.0-b32.jar` is corrupt. The issue is slightly confusing, because this is ASM looking at a jar that contains ASM ;) So either the latest version of ASM can't read valid bytecode or the glassfish folks have made a mistake when repackaging that jar.

**Comment by oehme** [comment] 2018-04-25 07:52
You could try adding a dependency on the original `asm-all-2.5.0-b32` jar. If that works, the repackaged one is broken.

**Comment by oehme** [comment] 2018-04-28 06:27
That's odd, javac usually also throws up on malformed jars. Maybe it's something that javac accepts and asm does not. Would be great to get an opinion from the asm team.

At the least Gradle should not fail but just deactivate incremental compilation instead.

**Comment by oehme** [comment] 2018-05-04 13:40
This is probably caused by https://bugs.openjdk.java.net/browse/JDK-8144185 and a duplicate of https://github.com/gradle/gradle/issues/3935. The ASM maintainers decided against a fix, because this was a JDK bug and is already fixed in the JDK.

**Closed** 2018-05-04 13:41 UTC
Labels: a:bug, from:contributor, in:jvm-platform
