### ISSUE TITLE
Could not resolve all artifacts for configuration 'incomingCatalogForLibs0'.

### ISSUE THREAD

**Issue by yuvaraj119** [gradle/gradle#29072] opened 2024-05-08 22:48 UTC
### Current Behavior

Could not resolve all artifacts for configuration 'incomingCatalogForLibs0'.
Could not resolve com.xxx:gradle-version-catalog:0.1.0.
Required by:
      unspecified:unspecified:unspecified
   > No matching variant of com.xxx:gradle-version-catalog:0.1.0 was found. The consumer was configured to find attribute 'org.gradle.category' with value 'platform', attribute 'org.gradle.usage' with value 'version-catalog' but:
       - Variant 'apiElements':
           - Incompatible because this component declares attribute 'org.gradle.category' with value 'library', attribute 'org.gradle.usage' with value 'java-api' and the consumer needed attribute 'org.gradle.category' with value 'platform', attribute 'org.gradle.usage' with value 'version-catalog'
       - Variant 'runtimeElements':
           - Incompatible because this component declares attribute 'org.gradle.category' with value 'library', attribute 'org.gradle.usage' with value 'java-runtime' and the consumer needed attribute 'org.gradle.category' with value 'platform', attribute 'org.gradle.usage' with value 'version-catalog'

### Expected Behavior

com.xxx:gradle-version-catalog:0.1.0 should get resolved and toml file should be available to use in project

### Context (optional)

I tried different solutions like 
tasks.withType(GenerateModuleMetadata) {
    enabled = false
}

metadataSources {
                mavenPom()
                artifact()
                ignoreGradleMetadataRedirection()
            }

but still not working.
There one strange scenario 
I published snapshot version 3 times and jfrog created multiple versions with date appended under same 0.1.0-SNAPSHOT
I was able to use the snapshot version 3 when i give the version like this 
'from(com.xxx:gradle-version-catalog:0.1.0-20240508.222545-3)'
but when i try snapshot 1 and 2 was not able to access.
When i did a release version 0.1.0 i was not able to access same error as above.

### Steps to Reproduce

Create a gradle project add libs.versions.toml file.
Publish the libs to jfrog repo 
Now try to add the dependencies in Android project it will throw the above current behavior error.

### Gradle version

8.1.1

**Comment by ljacomet** [comment] 2024-05-15 08:36
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

The error indicates that the produced metadata does not include the `platform/version-catalog` variant.
There are a couple reasons that could explain this:
* Missing `.module` file in the publication
* Gradle configured to ignore Gradle module metadata

These issues are not bugs but usage problems. 

If you believe our analysis is wrong, please provide a reproducer and sample of the published metadata.

**Closed by ljacomet** 2024-05-15 08:36 UTC
Labels: closed:question

**Comment by yuvaraj119** [comment] 2024-05-30 21:36
I can see module and gradle is configured to add the gradle module metadata 
Here artifacts deployed in artifactory 
![image](https://github.com/gradle/gradle/assets/10301575/a616d326-0f31-4c57-a073-83835dfd4ef1)

**Comment by ov7a** [comment] 2024-06-04 13:19
We appreciate the effort, but we must ask for more information so that we can triage it. 

We do not see an immediate root cause, and we need a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) for the triage. If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project.
