### ISSUE TITLE
unable to run multiple tasks with the same @Option annotation

### ISSUE THREAD

**Issue by gerhard6** [gradle/gradle#4621] opened 2018-03-07 14:50 UTC
### Expected Behavior
no error

### Current Behavior
```
$ cat build.gradle
class Task1 extends DefaultTask {
        @Option(option="url", description="d")  
        String url
        @TaskAction
        action() {
                assert url
                logger.warn("url: $url")
        }
}

class Task2 extends DefaultTask {
        @Option(option="url", description="d")
        String url
        @TaskAction
        action() {
                assert url
                logger.warn("url: $url")
        }
}
task task1(type: Task1)
task task2(type: Task2)


$ ./gradlew task1 task2  --url u
:task1 FAILED     (.. on "assert url")
```

### Steps to Reproduce (for bugs)
see build.gradle above.
I have 2 tasks, both of them have the same @Option defined.
Calling both tasks together in on command line invocation fails; in contrast, calling them individually works.

### Your Environment
gradle 4.6

**Comment by big-guy** [comment] 2018-03-07 18:23
The options are scoped to the task, so you would need to do:

`gradle task1 --url u task2 --url u`

**Comment by oehme** [comment] 2018-03-08 08:28
Duplicate of #2032

**Closed by oehme** 2018-03-08 08:28 UTC
