### ISSUE TITLE
Building gradle v7.0.0 dist from source - Failed to apply plugin 'com.gradle.enterprise.gradle-enterprise-conventions-plugin'

### ISSUE THREAD

**Issue by stefan1000** [gradle/gradle#16928] opened 2021-04-21 14:56 UTC
Hi, 

I'm trying to build gradle v7.0.0 from source (git checkout), but it fails with an IllegalArgumentException on 
[16:11:06]W:		 [Gradle failure report] > Failed to apply plugin 'com.gradle.enterprise.gradle-enterprise-conventions-plugin'.
[16:11:06]W:		 [Gradle failure report]    > java.lang.IllegalArgumentException (no error message)

Do I miss something here ? 

[16:11:06]W:		 [Gradle failure report] * Exception is:
[16:11:06]W:		 [Gradle failure report] org.gradle.api.plugins.InvalidPluginException: An exception occurred applying plugin request [id: 'com.gradle.enterprise.gradle-enterprise-conventions-plugin', version: '0.7.2']
[16:11:06]W:		 [Gradle failure report] 	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.exceptionOccurred(DefaultPluginRequestApplicator.java:207)
[16:11:06]W:		 [Gradle failure report] 	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:189)
[16:11:06]W:		 [Gradle failure report] 	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.lambda$applyLegacyPlugins$3(DefaultPluginRequestApplicator.java:138)
[16:11:06]W:		 [Gradle failure report] 	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyLegacyPlugins(DefaultPluginRequestApplicator.java:138)
[16:11:06]W:		 [Gradle failure report] 	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:122)
[16:11:06]W:		 [Gradle failure report] 	at org.gradle.kotlin.dsl.provider.PluginRequestsHandler.handle(PluginRequestsHandler.kt:48)
[16:11:06]W:		 [Gradle failure report] 	at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator$InterpreterHost.applyPluginsTo(KotlinScriptEvaluator.kt:192)
[16:11:06]W:		 [Gradle failure report] 	at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.applyPluginsTo(Interpreter.kt:373)
[16:11:06]W:		 [Gradle failure report] 	at Program.execute(Unknown Source)

**Comment by ljacomet** [comment] 2021-04-26 16:42
That should not happen.

Can you share steps to reproduce this? Like OS, JVM version, ...

**Comment by stefan1000** [comment] 2021-04-27 07:24
I've tried it on Win10 Pro x64 10.0.19041 and Win Server 2021 R2 x64 6.3.9600 Build 9600 with
`openjdk 11.0.5 2019-10-15 LTS
OpenJDK Runtime Environment Corretto-11.0.5.10.1 (build 11.0.5+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.5.10.1 (build 11.0.5+10-LTS, mixed mode)`

**Comment by blindpirate** [comment] 2021-04-27 07:27
@stefan1000 Can you rerun with `--stacktrace` then paste the whole stacktrace? Your current stacktrace lacks important information, without which we can't know the root cause.

**Comment by stefan1000** [comment] 2021-04-27 07:30
[stacktrace.txt](https://github.com/gradle/gradle/files/6382702/stacktrace.txt)

I could also share the full teamcity debug build log, but not via the public tracker, it shows an error near the exception:
`[09:12:29] :	 [Step 1/1] net.rubygrapefruit.platform.NativeException: Could not query file systems: could not get volume information (errno 5)
[09:12:29] :	 [Step 1/1] 	at net.rubygrapefruit.platform.internal.PosixFileSystems.getFileSystems(PosixFileSystems.java:32)
[09:12:29] :	 [Step 1/1] 	at org.gradle.internal.watch.vfs.impl.DefaultWatchableFileSystemDetector.detectUnsupportedFileSystems(DefaultWatchableFileSystemDetector.java:64)
`

**Comment by blindpirate** [comment] 2021-04-27 07:45
@stefan1000 I think I found something fishy, there's an environment variable causing this. For now, you should be able to workaround this issue by commenting this plugin (`gradle-enterprise-conventions-plugin`):

https://github.com/gradle/gradle/blob/23f7bcb19874380c85acd30df074af6772dde265/settings.gradle.kts#L14

It's just a plugin collecting information for the build and has no effect the generated artifacts. I need to take a closer look at the code.

**Comment by stefan1000** [comment] 2021-04-27 10:01
I can confirm that it works without that plugin. Should the collection of information from user machine be optional and not on by default ?

**Comment by ljacomet** [comment] 2021-05-26 12:29
The information collected is added to the build scan. If you do not opt-in to publish the build scan, that information does not leave your machine.

And by default no build scans are produced.

**Comment by ljacomet** [comment] 2021-07-07 14:22
Closing as no further action is planned on this topic.

**Closed by ljacomet** 2021-07-07 14:22 UTC
Labels: a:bug, in:building-gradle
