### ISSUE TITLE
Gradle build daemon crashes when environment variable contains emoji

### ISSUE THREAD

**Issue by floscher** [gradle/gradle#7448] opened 2018-10-18 12:48 UTC
### Expected Behavior
`TEST="🎉" ./gradlew build` should start a normal build
### Current Behavior
`TEST="🎉" ./gradlew build` finishes with the message:
```
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
```
Stack trace:
<details>

```
* Exception is:
org.gradle.launcher.daemon.client.DaemonDisappearedException: Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
        at org.gradle.launcher.daemon.client.DaemonClient.handleDaemonDisappearance(DaemonClient.java:242)
        at org.gradle.launcher.daemon.client.DaemonClient.monitorBuild(DaemonClient.java:218)
        at org.gradle.launcher.daemon.client.DaemonClient.executeBuild(DaemonClient.java:179)
        at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:142)
        at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:93)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:53)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:207)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:403)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:376)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:37)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:23)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:369)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:299)
        at org.gradle.launcher.Main.doAction(Main.java:36)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:31)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

</details>

### Context
I used an emoji in a git commit message. When building the commit in CI, my CI provider put the commit message into an environment variable. The build pipeline failed because of this: https://gitlab.com/floscher/gradle-josm-plugin/pipelines/33430172

I used Gradle version `5.0-milestone-1` in all builds mentioned in this comment.

### Steps to Reproduce (for bugs)
Start a Gradle build while an environment variable contains an emoji

### Your Environment
This happened on:
* Ubuntu 18.04.1 with OpenJDK 10
* Alpine Linux 3.8 with OpenJDK 8 ([CI job](https://gitlab.com/floscher/gradle-josm-plugin/-/jobs/109714623))
* Debian Sid slim with OpenJDK 10 ([CI job](https://gitlab.com/floscher/gradle-josm-plugin/-/jobs/109714624))
* Debian Sid slim with OpenJDK 11 ([CI job](https://gitlab.com/floscher/gradle-josm-plugin/-/jobs/109714625))

It does **not** happen on:
* Alpine Linux 3.8 with OpenJDK 12 ([CI job](https://gitlab.com/floscher/gradle-josm-plugin/-/jobs/109705245))

**Comment by marcphilipp** [comment] 2018-10-18 13:13
Can you reproduce this locally and check the daemon logs in `~/.gradle/daemon/5.0-milestone-1/`?

**Comment by marcphilipp** [comment] 2018-10-19 07:06
@floscher Can you try setting a locale and/or using Java 11?

**Comment by dnfield** [comment] 2019-01-01 07:38
Seems like a duplicate of https://github.com/gradle/gradle/issues/3117

**Comment by marcphilipp** [comment] 2019-01-02 09:08
@dnfield Good catch, thanks!

**Comment by marcphilipp** [comment] 2019-01-02 09:08
Duplicate of #3117

**Closed by marcphilipp** 2019-01-02 09:08 UTC
