### ISSUE TITLE
Gradle ChangingModules caching (with kotlin?) is not invalidating properly

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#4062] opened 2018-01-17 19:26 UTC
I'm not sure if this is explicitly a kotlin-dsl bug or not, gradle 4.4.1, https://github.com/gradle/kotlin-dsl/issues/648

https://discuss.gradle.org/t/gradle-caching-with-kotlin-is-not-invalidating-properly/25249

### Expected Behavior

gradle should refetch changing modules when they're not set to be cached, every time, or if I have the expiration set to a minute, then after a minute.

### Current Behavior
gradle appears to be caching changing modules for the default? amount of time

### Steps to Reproduce (for bugs)

current partial config, more info in the discuss, though I can probably provide more if necessary

```
configurations.all({
    resolutionStrategy.cacheChangingModulesFor(0, TimeUnit.SECONDS)
})

...
    implementation("com.xenoterracide:util:0.1.4-SNAPSHOT", { isChanging = true })
    implementation("com.xenoterracide.entities:entities-api:0.2.0-SNAPSHOT", { isChanging = true })
    implementation("com.xenoterracide.entities:entities-jpa:0.2.0-SNAPSHOT", { isChanging = true })
    implementation("com.xenoterracide.rpf:sec:0.1.0-SNAPSHOT", { isChanging = true })
    implementation("com.xenoterracide.rpf:sec-dtos:0.1.0-SNAPSHOT", { isChanging = true })
    implementation("com.xenoterracide.rpf:constants:0.1.0-SNAPSHOT", { isChanging = true })
```

### Your Environment
```
------------------------------------------------------------
Gradle 4.4.1
------------------------------------------------------------

Build time:   2017-12-20 15:45:23 UTC
Revision:     10ed9dc355dc39f6307cc98fbd8cea314bdd381c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_151 (Oracle Corporation 25.151-b12)
OS:           Linux 4.8.11-coreos-r2 amd64
```

**Comment by bigdaz** [comment] 2018-01-17 19:43
Based on the fact you're using the Spring Dependency Management plugin, I suspect that you're hitting https://github.com/gradle/gradle/issues/3019. You could help confirm this by [setting `cacheChangingModulesFor` in the `dependencyManagement` block](https://github.com/spring-gradle-plugins/dependency-management-plugin#configuring-the-dependency-management-resolution-strategy) _as well_.

If this is the case, the behaviour you're seeing is due to:
1) Spring DM using detached configurations, which are not included in `configurations.all`
2) The Spring DM configuration being the first to resolve, setting the effective cache timeout for all subsequent resolution (bug #3109)

The fix for this missed the cutoff for Gradle 4.5, but we hope to have it in 4.6.

**Comment by bigdaz** [comment] 2018-01-22 01:06
@xenoterracide Any chance you can try out [my suggestion]([url](https://github.com/gradle/gradle/issues/4062#issuecomment-358420550)) above? That will help us to determine if this is a different bug or another manifestation of #3109.

**Comment by xenoterracide** [comment] 2018-01-26 22:36
hi, sorry for taking so long to get back to you, kind of just kept slipping my mind since all this is on a hobby project.  Yes that suggestion seems to fix the problem. Tested by

B depends on A

1. executing build B
1. make change to A
1. incorporate change in B
1. build B, verify error
1. build A
1. build B again, verify error is gone, and resource has updated

**Comment by bigdaz** [comment] 2018-01-26 22:39
Thanks for confirming. Closing as duplicate of #3109.

**Closed by bigdaz** 2018-01-26 22:39 UTC
Labels: a:bug, from:contributor, in:dependency-management
