### ISSUE TITLE
Execution failed for task ':react-native-safe-area-context:compileReleaseKotlin'.

### ISSUE THREAD

**Issue by aayushnaphade** [gradle/gradle#29248] opened 2024-05-22 07:50 UTC
### Current Behavior

`Running 'gradlew :app:assembleRelease' in /home/expo/workingdir/build/android
Downloading https://services.gradle.org/distributions/gradle-8.6-all.zip
10%.
20%.
30%.
40%
50%.
60%
70%
80%
90%.
100%
Welcome to Gradle 8.6!
Here are the highlights of this release:
 - Configurable encryption key for configuration cache
 - Build init improvements
 - Build authoring improvements
For more details see https://docs.gradle.org/8.6/release-notes.html
To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.6/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
Daemon will be stopped at the end of the build
Path for java installation '/usr/lib/jvm/openjdk-17' (Common Linux Locations) does not contain a java executable
> Task :expo-updates-gradle-plugin:checkKotlinGradlePluginConfigurationErrors
> Task :gradle-plugin:checkKotlinGradlePluginConfigurationErrors
> Task :expo-updates-gradle-plugin:pluginDescriptors
> Task :expo-updates-gradle-plugin:processResources
> Task :gradle-plugin:pluginDescriptors
> Task :gradle-plugin:processResources
> Task :gradle-plugin:compileKotlin
> Task :gradle-plugin:compileJava NO-SOURCE
> Task :gradle-plugin:classes
> Task :gradle-plugin:jar
> Task :expo-updates-gradle-plugin:compileKotlin
> Task :expo-updates-gradle-plugin:compileJava NO-SOURCE
> Task :expo-updates-gradle-plugin:classes
> Task :expo-updates-gradle-plugin:jar
> Configure project :app
ℹ️  Applying gradle plugin 'expo-updates-gradle-plugin' (expo-updates@0.25.14)
> Configure project :expo-modules-core
Checking the license for package NDK (Side by side) 26.1.10909125 in /home/expo/Android/Sdk/licenses
License for package NDK (Side by side) 26.1.10909125 accepted.
Preparing "Install NDK (Side by side) 26.1.10909125 v.26.1.10909125".
"Install NDK (Side by side) 26.1.10909125 v.26.1.10909125" ready.
Installing NDK (Side by side) 26.1.10909125 in /home/expo/Android/Sdk/ndk/26.1.10909125
"Install NDK (Side by side) 26.1.10909125 v.26.1.10909125" complete.
"Install NDK (Side by side) 26.1.10909125 v.26.1.10909125" finished.
> Configure project :expo
Using expo modules
  - expo-asset (10.0.6)
  - expo-barcode-scanner (13.0.1)
  - expo-camera (15.0.9)
  - expo-constants (16.0.1)
  - expo-eas-client (0.12.0)
  - expo-file-system (17.0.1)
  - expo-font (12.0.5)
  - expo-image-loader (4.7.0)
  - expo-json-utils (0.13.1)
  - expo-keep-awake (13.0.2)
  - expo-location (17.0.1)
  - expo-manifests (0.14.3)
  - expo-modules-core (1.12.11)
  - expo-structured-headers (3.8.0)
  - expo-updates (0.25.14)
Checking the license for package Android SDK Build-Tools 34 in /home/expo/Android/Sdk/licenses
License for package Android SDK Build-Tools 34 accepted.
Preparing "Install Android SDK Build-Tools 34 v.34.0.0".
"Install Android SDK Build-Tools 34 v.34.0.0" ready.
Installing Android SDK Build-Tools 34 in /home/expo/Android/Sdk/build-tools/34.0.0
"Install Android SDK Build-Tools 34 v.34.0.0" complete.
"Install Android SDK Build-Tools 34 v.34.0.0" finished.
Checking the license for package Android SDK Platform 34 in /home/expo/Android/Sdk/licenses
License for package Android SDK Platform 34 accepted.
Preparing "Install Android SDK Platform 34 (revision 3)".
"Install Android SDK Platform 34 (revision 3)" ready.
Installing Android SDK Platform 34 in /home/expo/Android/Sdk/platforms/android-34
"Install Android SDK Platform 34 (revision 3)" complete.
"Install Android SDK Platform 34 (revision 3)" finished.
Path for java installation '/usr/lib/jvm/openjdk-17' (Common Linux Locations) does not contain a java executable
> Task :expo-asset:preBuild UP-TO-DATE
> Task :expo-barcode-scanner:preBuild UP-TO-DATE
> Task :expo-barcode-scanner:preReleaseBuild UP-TO-DATE
> Task :expo-asset:preReleaseBuild UP-TO-DATE
> Task :expo-barcode-scanner:writeReleaseAarMetadata
> Task :expo-camera:preBuild UP-TO-DATE
> Task :expo-camera:preReleaseBuild UP-TO-DATE
> Task :expo-asset:writeReleaseAarMetadata
> Task :expo-constants:createExpoConfig
> Task :expo-constants:preBuild
> Task :expo-constants:preReleaseBuild
> Task :expo:generateExpoModulesPackageListTask
> Task :expo:preBuild
> Task :expo:preReleaseBuild
> Task :expo:writeReleaseAarMetadata
> Task :expo-eas-client:preBuild UP-TO-DATE
> Task :expo-eas-client:preReleaseBuild UP-TO-DATE
> Task :expo-constants:writeReleaseAarMetadata
> Task :expo-file-system:preBuild UP-TO-DATE
> Task :expo-file-system:preReleaseBuild UP-TO-DATE
> Task :expo-eas-client:writeReleaseAarMetadata
> Task :expo-font:preBuild UP-TO-DATE
> Task :expo-font:preReleaseBuild UP-TO-DATE
> Task :expo-camera:writeReleaseAarMetadata
> Task :expo-image-loader:preBuild UP-TO-DATE
> Task :expo-image-loader:preReleaseBuild UP-TO-DATE
> Task :expo-image-loader:writeReleaseAarMetadata
> Task :expo-json-utils:preBuild UP-TO-DATE
> Task :expo-json-utils:preReleaseBuild UP-TO-DATE
> Task :expo-font:writeReleaseAarMetadata
> Task :expo-keep-awake:preBuild UP-TO-DATE
> Task :expo-keep-awake:preReleaseBuild UP-TO-DATE
> Task :expo-file-system:writeReleaseAarMetadata
> Task :expo-location:preBuild UP-TO-DATE
> Task :expo-location:preReleaseBuild UP-TO-DATE
> Task :expo-json-utils:writeReleaseAarMetadata
> Task :expo-manifests:preBuild UP-TO-DATE
> Task :expo-manifests:preReleaseBuild UP-TO-DATE
> Task :expo-keep-awake:writeReleaseAarMetadata
> Task :expo-modules-core:preBuild UP-TO-DATE
> Task :expo-modules-core:preReleaseBuild UP-TO-DATE
> Task :expo-manifests:writeReleaseAarMetadata
> Task :expo-structured-headers:preBuild UP-TO-DATE
> Task :expo-structured-headers:preReleaseBuild UP-TO-DATE
> Task :expo-location:writeReleaseAarMetadata
> Task :expo-updates:preBuild UP-TO-DATE
> Task :expo-updates:preReleaseBuild UP-TO-DATE
> Task :expo-structured-headers:writeReleaseAarMetadata
> Task :expo-updates-interface:preBuild UP-TO-DATE
> Task :expo-updates-interface:preReleaseBuild UP-TO-DATE
> Task :expo-updates-interface:writeReleaseAarMetadata
> Task :react-native-async-storage_async-storage:preBuild UP-TO-DATE
> Task :react-native-async-storage_async-storage:preReleaseBuild UP-TO-DATE
> Task :react-native-async-storage_async-storage:writeReleaseAarMetadata
> Task :react-native-gesture-handler:preBuild UP-TO-DATE
> Task :react-native-gesture-handler:preReleaseBuild UP-TO-DATE
> Task :react-native-gesture-handler:writeReleaseAarMetadata
> Task :react-native-safe-area-context:preBuild UP-TO-DATE
> Task :react-native-safe-area-context:preReleaseBuild UP-TO-DATE
> Task :expo-updates:writeReleaseAarMetadata
> Task :react-native-screens:preBuild UP-TO-DATE
> Task :react-native-screens:preReleaseBuild UP-TO-DATE
> Task :react-native-safe-area-context:writeReleaseAarMetadata
> Task :react-native-share:preBuild UP-TO-DATE
> Task :react-native-share:preReleaseBuild UP-TO-DATE
> Task :react-native-share:writeReleaseAarMetadata
> Task :react-native-svg:preBuild UP-TO-DATE
> Task :react-native-svg:preReleaseBuild UP-TO-DATE
> Task :expo-modules-core:writeReleaseAarMetadata
> Task :react-native-vector-icons:preBuild UP-TO-DATE
> Task :react-native-vector-icons:preReleaseBuild UP-TO-DATE
> Task :react-native-screens:writeReleaseAarMetadata
> Task :react-native-webview:preBuild UP-TO-DATE
> Task :react-native-webview:preReleaseBuild UP-TO-DATE
> Task :react-native-svg:writeReleaseAarMetadata
> Task :expo:generateReleaseResValues
> Task :expo:generateReleaseResources
> Task :react-native-webview:writeReleaseAarMetadata
> Task :expo-asset:generateReleaseResValues
> Task :expo-asset:generateReleaseResources
> Task :expo:packageReleaseResources
> Task :expo-barcode-scanner:generateReleaseResValues
> Task :expo-barcode-scanner:generateReleaseResources
> Task :expo-asset:packageReleaseResources
> Task :expo-camera:generateReleaseResValues
> Task :expo-camera:generateReleaseResources
> Task :expo-barcode-scanner:packageReleaseResources
> Task :expo-constants:generateReleaseResValues
> Task :expo-constants:generateReleaseResources
> Task :expo-camera:packageReleaseResources
> Task :expo-constants:packageReleaseResources
> Task :expo-eas-client:generateReleaseResValues
> Task :expo-eas-client:generateReleaseResources
> Task :expo-file-system:generateReleaseResValues
> Task :expo-file-system:generateReleaseResources
> Task :expo-eas-client:packageReleaseResources
> Task :expo-font:generateReleaseResValues
> Task :expo-font:generateReleaseResources
> Task :expo-font:packageReleaseResources
> Task :expo-image-loader:generateReleaseResValues
> Task :expo-image-loader:generateReleaseResources
> Task :expo-image-loader:packageReleaseResources
> Task :expo-json-utils:generateReleaseResValues
> Task :expo-json-utils:generateReleaseResources
> Task :expo-file-system:packageReleaseResources
> Task :expo-json-utils:packageReleaseResources
> Task :expo-keep-awake:generateReleaseResValues
> Task :expo-keep-awake:generateReleaseResources
> Task :expo-location:generateReleaseResValues
> Task :expo-location:generateReleaseResources
> Task :expo-keep-awake:packageReleaseResources
> Task :expo-location:packageReleaseResources
> Task :expo-manifests:generateReleaseResValues
> Task :expo-modules-core:generateReleaseResValues
> Task :expo-manifests:generateReleaseResources
> Task :expo-modules-core:generateReleaseResources
> Task :expo-manifests:packageReleaseResources
> Task :expo-modules-core:packageReleaseResources
> Task :expo-structured-headers:generateReleaseResValues
> Task :react-native-vector-icons:writeReleaseAarMetadata
> Task :expo-structured-headers:generateReleaseResources
> Task :expo-updates:generateReleaseResValues
> Task :expo-updates:generateReleaseResources
> Task :expo-structured-headers:packageReleaseResources
> Task :expo-updates-interface:generateReleaseResValues
> Task :expo-updates-interface:generateReleaseResources
> Task :expo-updates:packageReleaseResources
> Task :react-native-async-storage_async-storage:generateReleaseResValues
> Task :react-native-async-storage_async-storage:generateReleaseResources
> Task :expo-updates-interface:packageReleaseResources
> Task :react-native-gesture-handler:generateReleaseResValues
> Task :react-native-gesture-handler:generateReleaseResources
> Task :react-native-async-storage_async-storage:packageReleaseResources
> Task :react-native-safe-area-context:generateReleaseResValues
> Task :react-native-safe-area-context:generateReleaseResources
> Task :react-native-gesture-handler:packageReleaseResources
> Task :react-native-screens:generateReleaseResValues
> Task :react-native-screens:generateReleaseResources
> Task :react-native-safe-area-context:packageReleaseResources
> Task :react-native-share:generateReleaseResValues
> Task :react-native-share:generateReleaseResources
> Task :react-native-share:packageReleaseResources
> Task :react-native-svg:generateReleaseResValues
> Task :react-native-svg:generateReleaseResources
> Task :react-native-screens:packageReleaseResources
> Task :react-native-svg:packageReleaseResources
> Task :react-native-vector-icons:generateReleaseResValues
> Task :react-native-webview:generateReleaseResValues
> Task :react-native-vector-icons:generateReleaseResources
> Task :react-native-webview:generateReleaseResources
> Task :react-native-vector-icons:packageReleaseResources
> Task :react-native-webview:packageReleaseResources
> Task :expo:extractDeepLinksRelease
> Task :expo-asset:extractDeepLinksRelease
> Task :expo-asset:processReleaseManifest
> Task :expo-barcode-scanner:extractDeepLinksRelease
> Task :expo:processReleaseManifest
> Task :expo-camera:extractDeepLinksRelease
> Task :expo-barcode-scanner:processReleaseManifest
> Task :expo-constants:extractDeepLinksRelease
> Task :expo-camera:processReleaseManifest
> Task :expo-eas-client:extractDeepLinksRelease
> Task :expo-constants:processReleaseManifest
> Task :expo-file-system:extractDeepLinksRelease
> Task :expo-eas-client:processReleaseManifest
> Task :expo-font:extractDeepLinksRelease
> Task :expo-file-system:processReleaseManifest
/home/expo/workingdir/build/node_modules/expo-file-system/android/src/main/AndroidManifest.xml:6:9-8:20 Warning:
	provider#expo.modules.filesystem.FileSystemFileProvider@android:authorities was tagged at AndroidManifest.xml:6 to replace other declarations but no other declaration present
> Task :expo-image-loader:extractDeepLinksRelease
> Task :expo-font:processReleaseManifest
> Task :expo-json-utils:extractDeepLinksRelease
> Task :expo-image-loader:processReleaseManifest
> Task :expo-keep-awake:extractDeepLinksRelease
> Task :expo-json-utils:processReleaseManifest
> Task :expo-location:extractDeepLinksRelease
> Task :expo-keep-awake:processReleaseManifest
> Task :expo-manifests:extractDeepLinksRelease
> Task :expo-location:processReleaseManifest
> Task :expo-modules-core:extractDeepLinksRelease
> Task :expo-manifests:processReleaseManifest
> Task :expo-structured-headers:extractDeepLinksRelease
> Task :expo-modules-core:processReleaseManifest
/home/expo/workingdir/build/node_modules/expo-modules-core/android/src/main/AndroidManifest.xml:8:9-11:45 Warning:
	meta-data#com.facebook.soloader.enabled@android:value was tagged at AndroidManifest.xml:8 to replace other declarations but no other declaration present
> Task :expo-structured-headers:processReleaseManifest
> Task :expo-updates:extractDeepLinksRelease
> Task :expo-updates-interface:extractDeepLinksRelease
> Task :expo-updates:processReleaseManifest
> Task :react-native-async-storage_async-storage:extractDeepLinksRelease
> Task :expo-updates-interface:processReleaseManifest
> Task :react-native-async-storage_async-storage:processReleaseManifest
package="com.reactnativecommunity.asyncstorage" found in source AndroidManifest.xml: /home/expo/workingdir/build/node_modules/@react-native-async-storage/async-storage/android/src/main/AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
Recommendation: remove package="com.reactnativecommunity.asyncstorage" from the source AndroidManifest.xml: /home/expo/workingdir/build/node_modules/@react-native-async-storage/async-storage/android/src/main/AndroidManifest.xml.
> Task :react-native-gesture-handler:extractDeepLinksRelease
> Task :react-native-gesture-handler:processReleaseManifest
package="com.swmansion.gesturehandler" found in source AndroidManifest.xml: /home/expo/workingdir/build/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
Recommendation: remove package="com.swmansion.gesturehandler" from the source AndroidManifest.xml: /home/expo/workingdir/build/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml.
> Task :react-native-safe-area-context:extractDeepLinksRelease
> Task :react-native-safe-area-context:processReleaseManifest
package="com.th3rdwave.safeareacontext" found in source AndroidManifest.xml: /home/expo/workingdir/build/node_modules/react-native-safe-area-context/android/src/main/AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
Recommendation: remove package="com.th3rdwave.safeareacontext" from the source AndroidManifest.xml: /home/expo/workingdir/build/node_modules/react-native-safe-area-context/android/src/main/AndroidManifest.xml.
> Task :react-native-screens:extractDeepLinksRelease
> Task :react-native-screens:processReleaseManifest
package="com.swmansion.rnscreens" found in source AndroidManifest.xml: /home/expo/workingdir/build/node_modules/react-native-screens/android/src/main/AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
Recommendation: remove package="com.swmansion.rnscreens" from the source AndroidManifest.xml: /home/expo/workingdir/build/node_modules/react-native-screens/android/src/main/AndroidManifest.xml.
> Task :react-native-share:extractDeepLinksRelease
> Task :react-native-share:processReleaseManifest
package="cl.json" found in source AndroidManifest.xml: /home/expo/workingdir/build/node_modules/react-native-share/android/src/main/AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
Recommendation: remove package="cl.json" from the source AndroidManifest.xml: /home/expo/workingdir/build/node_modules/react-native-share/android/src/main/AndroidManifest.xml.
> Task :react-native-svg:extractDeepLinksRelease
> Task :react-native-svg:processReleaseManifest
package="com.horcrux.svg" found in source AndroidManifest.xml: /home/expo/workingdir/build/node_modules/react-native-svg/android/src/main/AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
Recommendation: remove package="com.horcrux.svg" from the source AndroidManifest.xml: /home/expo/workingdir/build/node_modules/react-native-svg/android/src/main/AndroidManifest.xml.
> Task :react-native-vector-icons:extractDeepLinksRelease
> Task :react-native-vector-icons:processReleaseManifest
package="com.oblador.vectoricons" found in source AndroidManifest.xml: /home/expo/workingdir/build/node_modules/react-native-vector-icons/android/src/main/AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
Recommendation: remove package="com.oblador.vectoricons" from the source AndroidManifest.xml: /home/expo/workingdir/build/node_modules/react-native-vector-icons/android/src/main/AndroidManifest.xml.
> Task :react-native-webview:extractDeepLinksRelease
> Task :react-native-webview:processReleaseManifest
> Task :expo:compileReleaseLibraryResources
> Task :expo:parseReleaseLocalResources
> Task :expo:generateReleaseRFile
> Task :expo-asset:compileReleaseLibraryResources
> Task :expo-asset:parseReleaseLocalResources
> Task :expo-asset:generateReleaseRFile
> Task :expo-barcode-scanner:compileReleaseLibraryResources
> Task :expo-barcode-scanner:parseReleaseLocalResources
> Task :expo-barcode-scanner:generateReleaseRFile
> Task :expo-camera:compileReleaseLibraryResources
> Task :expo-camera:parseReleaseLocalResources
> Task :expo-camera:generateReleaseRFile
> Task :expo-constants:compileReleaseLibraryResources
> Task :expo-constants:parseReleaseLocalResources
> Task :expo-constants:generateReleaseRFile
> Task :expo-eas-client:compileReleaseLibraryResources
> Task :expo-eas-client:parseReleaseLocalResources
> Task :expo-eas-client:generateReleaseRFile
> Task :expo-file-system:compileReleaseLibraryResources
> Task :expo-file-system:parseReleaseLocalResources
> Task :expo-file-system:generateReleaseRFile
> Task :expo-font:compileReleaseLibraryResources
> Task :expo-font:parseReleaseLocalResources
> Task :expo-font:generateReleaseRFile
> Task :expo-image-loader:compileReleaseLibraryResources
> Task :expo-image-loader:parseReleaseLocalResources
> Task :expo-image-loader:generateReleaseRFile
> Task :expo-json-utils:compileReleaseLibraryResources
> Task :expo-json-utils:parseReleaseLocalResources
> Task :expo-json-utils:generateReleaseRFile
> Task :expo-keep-awake:compileReleaseLibraryResources
> Task :expo-keep-awake:parseReleaseLocalResources
> Task :expo-keep-awake:generateReleaseRFile
> Task :expo-location:compileReleaseLibraryResources
> Task :expo-location:parseReleaseLocalResources
> Task :expo-location:generateReleaseRFile
> Task :expo-manifests:compileReleaseLibraryResources
> Task :expo-manifests:parseReleaseLocalResources
> Task :expo-manifests:generateReleaseRFile
> Task :expo-modules-core:compileReleaseLibraryResources
> Task :expo-modules-core:parseReleaseLocalResources
> Task :expo-modules-core:generateReleaseRFile
> Task :expo-structured-headers:compileReleaseLibraryResources
> Task :expo-structured-headers:parseReleaseLocalResources
> Task :expo-structured-headers:generateReleaseRFile
> Task :expo-updates:compileReleaseLibraryResources
> Task :expo-updates:parseReleaseLocalResources
> Task :expo-updates:generateReleaseRFile
> Task :expo-updates-interface:compileReleaseLibraryResources
> Task :expo-updates-interface:parseReleaseLocalResources
> Task :expo-updates-interface:generateReleaseRFile
> Task :react-native-async-storage_async-storage:compileReleaseLibraryResources
> Task :react-native-async-storage_async-storage:parseReleaseLocalResources
> Task :react-native-async-storage_async-storage:generateReleaseRFile
> Task :react-native-gesture-handler:compileReleaseLibraryResources
> Task :react-native-gesture-handler:parseReleaseLocalResources
> Task :react-native-gesture-handler:generateReleaseRFile
> Task :react-native-safe-area-context:compileReleaseLibraryResources
> Task :react-native-safe-area-context:parseReleaseLocalResources
> Task :react-native-safe-area-context:generateReleaseRFile
> Task :react-native-screens:compileReleaseLibraryResources
> Task :react-native-screens:parseReleaseLocalResources
> Task :react-native-screens:generateReleaseRFile
> Task :react-native-share:compileReleaseLibraryResources
> Task :react-native-share:parseReleaseLocalResources
> Task :react-native-share:generateReleaseRFile
> Task :react-native-svg:compileReleaseLibraryResources
> Task :react-native-svg:parseReleaseLocalResources
> Task :react-native-svg:generateReleaseRFile
> Task :react-native-vector-icons:compileReleaseLibraryResources
> Task :react-native-vector-icons:parseReleaseLocalResources
> Task :react-native-vector-icons:generateReleaseRFile
> Task :react-native-webview:compileReleaseLibraryResources
> Task :react-native-webview:parseReleaseLocalResources
> Task :react-native-webview:generateReleaseRFile
> Task :expo:checkKotlinGradlePluginConfigurationErrors
> Task :expo:generateReleaseBuildConfig
> Task :expo-asset:checkKotlinGradlePluginConfigurationErrors
> Task :expo-asset:generateReleaseBuildConfig
> Task :expo-modules-core:checkKotlinGradlePluginConfigurationErrors
> Task :expo-modules-core:generateReleaseBuildConfig
> Task :expo-asset:javaPreCompileRelease
> Task :expo-barcode-scanner:checkKotlinGradlePluginConfigurationErrors
> Task :expo-barcode-scanner:generateReleaseBuildConfig
> Task :expo-barcode-scanner:javaPreCompileRelease
> Task :expo-camera:checkKotlinGradlePluginConfigurationErrors
> Task :expo-camera:generateReleaseBuildConfig
> Task :expo-camera:javaPreCompileRelease
> Task :expo-constants:checkKotlinGradlePluginConfigurationErrors
> Task :expo-constants:generateReleaseBuildConfig
> Task :expo-constants:javaPreCompileRelease
> Task :expo-eas-client:checkKotlinGradlePluginConfigurationErrors
> Task :expo-eas-client:generateReleaseBuildConfig
> Task :expo-eas-client:javaPreCompileRelease
> Task :expo-file-system:checkKotlinGradlePluginConfigurationErrors
> Task :expo-file-system:generateReleaseBuildConfig
> Task :expo-font:checkKotlinGradlePluginConfigurationErrors
> Task :expo-font:generateReleaseBuildConfig
> Task :expo-file-system:javaPreCompileRelease
> Task :expo-image-loader:checkKotlinGradlePluginConfigurationErrors
> Task :expo-image-loader:generateReleaseBuildConfig
> Task :expo-font:javaPreCompileRelease
> Task :expo-json-utils:checkKotlinGradlePluginConfigurationErrors
> Task :expo-json-utils:generateReleaseBuildConfig
> Task :expo-image-loader:javaPreCompileRelease
> Task :expo-keep-awake:checkKotlinGradlePluginConfigurationErrors
> Task :expo-json-utils:javaPreCompileRelease
> Task :expo-location:checkKotlinGradlePluginConfigurationErrors
> Task :expo-keep-awake:generateReleaseBuildConfig
> Task :expo-keep-awake:javaPreCompileRelease
> Task :expo-manifests:checkKotlinGradlePluginConfigurationErrors
> Task :expo-manifests:generateReleaseBuildConfig
> Task :expo-location:generateReleaseBuildConfig
> Task :expo-location:javaPreCompileRelease
> Task :expo-structured-headers:checkKotlinGradlePluginConfigurationErrors
> Task :expo-manifests:javaPreCompileRelease
> Task :expo-updates:checkKotlinGradlePluginConfigurationErrors
> Task :expo-updates:generateReleaseBuildConfig
> Task :expo-structured-headers:generateReleaseBuildConfig
> Task :expo-structured-headers:javaPreCompileRelease
> Task :expo-updates-interface:checkKotlinGradlePluginConfigurationErrors
> Task :expo-updates-interface:generateReleaseBuildConfig
> Task :expo-updates-interface:javaPreCompileRelease
> Task :expo:javaPreCompileRelease
> Task :react-native-async-storage_async-storage:generateReleaseBuildConfig
> Task :react-native-async-storage_async-storage:javaPreCompileRelease
> Task :expo-updates:javaPreCompileRelease
> Task :react-native-gesture-handler:checkKotlinGradlePluginConfigurationErrors
> Task :react-native-gesture-handler:generateReleaseBuildConfig
> Task :app:buildKotlinToolingMetadata
> Task :app:checkKotlinGradlePluginConfigurationErrors
> Task :app:generateCodegenSchemaFromJavaScript SKIPPED
> Task :app:generateCodegenArtifactsFromSchema SKIPPED
> Task :app:generatePackageList
> Task :app:preBuild
> Task :app:preReleaseBuild
> Task :app:generateReleaseBuildConfig
> Task :react-native-async-storage_async-storage:compileReleaseJavaWithJavac
/home/expo/workingdir/build/node_modules/@react-native-async-storage/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java:84: warning: [removal] onCatalystInstanceDestroy() in NativeModule has been deprecated and marked for removal
  public void onCatalystInstanceDestroy() {
              ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/expo/workingdir/build/node_modules/@react-native-async-storage/async-storage/android/src/javaPackage/java/com/reactnativecommunity/asyncstorage/AsyncStoragePackage.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
> Task :expo-modules-core:compileReleaseKotlin
> Task :expo-modules-core:javaPreCompileRelease
> Task :react-native-async-storage_async-storage:bundleLibCompileToJarRelease
> Task :react-native-gesture-handler:javaPreCompileRelease
> Task :react-native-safe-area-context:checkKotlinGradlePluginConfigurationErrors
> Task :react-native-safe-area-context:generateReleaseBuildConfig
> Task :react-native-safe-area-context:compileReleaseKotlin FAILED
e: file:///home/expo/workingdir/build/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaContextModule.kt:17:63 Type mismatch: inferred type is Map<String, Any>? but Any was expected
> Task :app:checkReleaseAarMetadata
> Task :react-native-gesture-handler:compileReleaseKotlin
w: file:///home/expo/workingdir/build/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/RNGestureHandlerPackage.kt:69:42 'constructor ReactModuleInfo(String!, String!, Boolean, Boolean, Boolean, Boolean, Boolean)' is deprecated. Deprecated in Java
w: file:///home/expo/workingdir/build/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/core/FlingGestureHandler.kt:25:26 Parameter 'event' is never used
> Task :expo-modules-core:compileReleaseKotlin
w: file:///home/expo/workingdir/build/node_modules/expo-modules-core/android/src/main/java/expo/modules/adapters/react/permissions/PermissionsService.kt:20:26 'Promise' is deprecated. AsyncFunction will crash when called. Use expo.modules.kotlin.Promise instead
w: file:///home/expo/workingdir/build/node_modules/expo-modules-core/android/src/main/java/expo/modules/adapters/react/permissions/PermissionsService.kt:63:51 'Promise' is deprecated. AsyncFunction will crash when called. Use expo.modules.kotlin.Promise instead
w: file:///home/expo/workingdir/build/node_modules/expo-modules-core/android/src/main/java/expo/modules/adapters/react/permissions/PermissionsService.kt:90:54 'Promise' is deprecated. AsyncFunction will crash when called. Use expo.modules.kotlin.Promise instead
w: file:///home/expo/workingdir/build/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/defaultmodules/CoreModule.kt:6:34 'ReactFeatureFlags' is deprecated. Deprecated in Java
w: file:///home/expo/workingdir/build/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/defaultmodules/CoreModule.kt:71:12 'ReactFeatureFlags' is deprecated. Deprecated in Java
w: file:///home/expo/workingdir/build/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/events/KModuleEventEmitterWrapper.kt:97:7 'constructor Event<T : Event<(raw) Event<*>>!>(Int)' is deprecated. Deprecated in Java
w: file:///home/expo/workingdir/build/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/types/JSTypeConverterHelper.kt:44:17 'get(String!): Any?' is deprecated. Deprecated in Java
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':react-native-safe-area-context:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 4m 25s
280 actionable tasks: 280 executed
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.`

### Expected Behavior

i'm usig expo eas build to build my apk .. i just recently upgraded my expo sdk to 51 and verything is working fine in the expo go 

### app config
Using app configuration:
{
  "name": "Park-In Partner",
  "slug": "parkin-client",
  "version": "1.0.0",
  "web": {
    "favicon": "./assets/faviicon2.png"
  },
  "experiments": {
    "tsconfigPaths": true
  },
  "orientation": "portrait",
  "icon": "./assets/icon2.png",
  "userInterfaceStyle": "light",
  "splash": {
    "image": "./assets/parkinlogo.png",
    "resizeMode": "contain",
    "backgroundColor": "#ffffff"
  },
  "assetBundlePatterns": [
    "**/*"
  ],
  "ios": {
    "supportsTablet": true
  },
  "android": {
    "adaptiveIcon": {
      "foregroundImage": "./assets/icon2.png",
      "backgroundColor": "#ffffff"
    },
    "package": "com.parkin.parkinclient"
  },
  "extra": {
    "eas": {
      "projectId": "8de9429a-18d7-4xxx-9488-747fe6ad7b86"
    }
  },
  "owner": "aayushnaphade",
  "runtimeVersion": {
    "policy": "appVersion"
  },
  "updates": {
    "url": "https://u.expo.dev/8de9429a-18d7-444b-9488-xxxxxad7b86"
  },
  "sdkVersion": "51.0.0",
  "platforms": [
    "ios",
    "android",
    "web"
  ]
}

### expo doctor 
Running "expo doctor"
Running 12 checks on your project...
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
Didn't find any issues with the project!

### Steps to Reproduce

it's my first bug report ....

### Gradle version

8.6

### Your Environment (optional)

**eas config**
{
  "cli": {
    "version": ">= 7.6.2"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "channel": "development",
      "android": {
        "buildType": "apk"
      }
    },
    "preview": {
      "distribution": "internal",
      "android": {
        "buildType": "apk"
      },
      "channel": "preview"
    },
    "preview2": {
      "android": {
        "gradleCommand": ":app:assembleRelease"
      },
      "channel": "preview2"
    },
    "preview3": {
      "developmentClient": true,
      "channel": "preview3"
    },
    "production": {
      "channel": "production",
      "android": {
        "buildType": "apk"
      }
    }
  },
  "submit": {
    "production": {}
  }
}

**Comment by ljacomet** [comment] 2024-05-22 08:56
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

The issue is most likely related to the tech stack used to abstract that Android app and its Gradle build. There is nothing we can do to help. Check with the `expo` community.

**Closed** 2024-05-22 08:56 UTC
Labels: a:bug, to-triage, closed:question
