### ISSUE TITLE
Composite Build support for plugins block

### ISSUE THREAD

**Issue by rwinch** [gradle/gradle#1518] opened 2017-03-06 15:00 UTC
The [documentation](https://docs.gradle.org/current/userguide/composite_builds.html?_ga=1.44342436.120894357.1435784450#current_limitations_and_future_work) states:

> Substituting plugins only works with the buildscript block but not with the plugins block.

It would be nice if this feature was added for users who want to provide samples of the plugin in use and test the sample out using composite builds.

### Expected Behavior

When a project uses the plugins syntax and provides `--include-build` definition for the build, the project should use the included project to resolve Gradle plugins within a `plugins` block (not just `buildscript`).

### Current Behavior

Composite builds do not resolve plugins within the plugins block. The resolution fails.

### Context

The disadvantage right now is that if you want to easily test the samples out, you must use the `buildscript` syntax which is not nearly as concise as the plugins syntax. I'd prefer samples to be the concise plugins syntax so that users do not have to translate from the `buildscript` syntax.

Related forum post https://discuss.gradle.org/t/composite-build-support-for-plugins-block/21749

**Comment by mflis** [comment] 2017-03-22 23:19
From my experience composite builds works on plugins block, but only when you have uploaded this plugin to repository declared in  `pluginRepositories`. 

My usual workflow, when working on new version of plugin:
- ensure that plugin is published to maven repository declared in `pluginRepositories`
- make some changes in plugin
- build project using my plugin with `--include-build` pointing to plugin project location

However when I wanted to bump version of my plugin without uploading bumped version to maven repository, then it wouldn't work

**Comment by oehme** [comment] 2017-09-06 13:34
Duplicate of #2528

**Closed by oehme** 2017-09-06 13:34 UTC
Labels: a:feature, from:contributor, in:composite-builds, in:test-kit
