### ISSUE TITLE
[4.3.1] - Unable to determine the version of the Android plugin to include in the build scan, due to java.lang.ClassNotFoundException: com.android.builder.Version

### ISSUE THREAD

**Issue by jaredsburrows** [gradle/gradle#3475] opened 2017-11-14 18:17 UTC
## Description
Related: https://github.com/KeepSafe/dexcount-gradle-plugin/issues/224
Google moved this class from `com.android.builder.Version` to `com.android.builder.model.Version`.

## Exception
```
Unable to determine the version of the Android plugin to include in the build scan, due to java.lang.ClassNotFoundException: com.android.builder.Version
```

**Comment by oehme** [comment] 2017-11-15 08:44
@ldaley Could you look into this?

**Comment by jaredsburrows** [comment] 2017-11-16 17:35
@oehme Is there a reason by build scan needs the `Version` class?

**Comment by bmuschko** [comment] 2017-11-16 17:42
@jaredsburrows Can you provide us with the stack trace for the message you provided above?

**Comment by oehme** [comment] 2017-11-16 18:59
I don't think we need a stacktrace here, we know what the problem is already.

The scan UI displays the Android plugin version, so we get it through that class. Should be a rather simple fix.

**Comment by jaredsburrows** [comment] 2017-11-16 19:53
We can either check of the instance of the plugins at runtime or do something like this: https://github.com/Kotlin/dokka/blob/master/runners/gradle-plugin/src/main/kotlin/main.kt#L30.

**Comment by etiennestuder** [comment] 2017-11-21 10:33
Build scan plugin version 1.10.2 (already released) properly handles the reported scenario.

**Comment by oehme** [comment] 2017-11-21 10:53
Thanks @etiennestuder!

**Comment by etiennestuder** [comment] 2017-11-21 11:14
@oehme My bad. It is fixed on master but not in 1.10.2 :-(

**Comment by jaredsburrows** [comment] 2017-11-22 02:54
@etiennestuder When will you open source the scan plugin? I will close this since you said it is already fixed.

**Comment by etiennestuder** [comment] 2017-11-22 04:54
@jaredsburrows We have no plans to open-source the b

**Comment by jaredsburrows** [comment] 2017-11-22 13:04
@etiennestuder Why open this if you said it is fixed?

**Comment by etiennestuder** [comment] 2017-11-22 19:45
@jaredsburrows Because the fix is not yet released.

**Comment by etiennestuder** [comment] 2017-11-23 11:59
This is fixed in the now release build scan plugin v1.10.3.

**Closed** 2017-11-23 11:59 UTC
Labels: a:bug

**Comment by jaredsburrows** [comment] 2017-11-23 14:03
Thank you!
