### ISSUE TITLE
Allow having extra modules in lock-file

### ISSUE THREAD

**Issue by prageeth** [gradle/gradle#6472] opened 2018-08-22 17:23 UTC
### Context
We currently have a dynamic resolver depending on build platform (OS specific) for a particular library we use; e.g. `abc.jar` and `abc-mac.jar`. We want to have both modules in the lock-file; and when running the task on gradle, gradle should be able to ignore the unused module. In our case, both jars have the same interface but one of them use native libraries differently.

### Expected Behavior
Gradle should not complain about the extra module stated in the lockfile. As I see it, the lockfile should be used to lock down dependency versions. I can understand that if there's a missing version for a resolved module, this could be a problem; but having an extra module shouldn't be an issue.

### Current Behavior
Gradle throws an error for this extra module, if you have both versions in the lock file:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task 'build'.
> Could not resolve all dependencies for configuration 'build:runtimeClasspath'.
   > Dependency lock state for configuration 'runtimeClasspath' is out of date: Did not resolve 'abc:1.2.3' which is part of the lock state
```

### Steps to Reproduce (for bugs)
Add an extra module to the file manually after creating a lock-file using `--write-locks`. Then re-run the task. The above error will be thrown.

### Proposed Solution
Allow extra modules to be left in the lock file. I think it would make sense to overwrite the whole file if `--write-locks` is used, but otherwise I would say leave them as is if only selective modules are updated using `--update-locks`. 

This should be achievable by not using the extra modules for validation:
https://github.com/gradle/gradle/blob/2deff08a55118e16fd85b869f45f138739d44225/subprojects/dependency-management/src/main/java/org/gradle/internal/locking/DependencyLockingArtifactVisitor.java#L158

**Comment by prageeth** [comment] 2018-08-30 09:27
@ljacomet Thanks for the feedback. I can settle with the proposed solution https://github.com/gradle/gradle/issues/5639. Is this something that is being worked on?

**Comment by ljacomet** [comment] 2018-08-30 09:31
It is on the TODO list but not planned for the near future. It will most likely not make it to the next Gradle release, 5.0.

**Comment by prageeth** [comment] 2018-08-30 09:34
Thanks for the update! I've also asked a question in https://github.com/gradle/gradle/issues/5639 regarding the workaround mentioned by @melix; any help regarding this would be highly appreciated as we've currently hit a dead-end because if this issue. Thanks!

**Comment by ljacomet** [comment] 2018-09-04 13:42
I am closing this as a duplicate of #5639 regarding the issue faced, even though the solution was totally different.

**Closed by ljacomet** 2018-09-04 13:42 UTC
Labels: in:dependency-management
