### ISSUE TITLE
Task :prepareKotlinBuildScriptModel is failing with HTTP 407 while trying to download gradle sources

### ISSUE THREAD

**Issue by spyroid** [gradle/gradle#18515] opened 2021-10-03 11:32 UTC
In SourceDistributionProvider class there is a hardcoded url to **https://services.gradle.org**  which is, of course, blocked in our company and while refreshing a project, task :prepareKotlinBuildScriptModel is failing with HTTP 407.  And looks like this error happening when env GRADLE_HOME is set.   

Think this url need to be taken from distributionUrl property

### Expected Behavior
Task :prepareKotlinBuildScriptModel is finished successfully 

### Current Behavior
Task :prepareKotlinBuildScriptModel is failing with HTTP 407

### Steps to Reproduce 
Create any simple project ether with gradle init or https://start.spring.io/ 
set env GRADLE_HOME=[path to gradle]
block services.gradle.org
Import a project to IntelliJ

### Your Environment
Gradle 7.2

**Comment by octylFractal** [comment] 2021-10-14 17:13
Duplicate of #18249

**Closed by octylFractal** 2021-10-14 17:13 UTC
Labels: a:bug, in:kotlin-dsl, to-triage
