### ISSUE TITLE
Allow projects to have aliases

### ISSUE THREAD

**Issue by anuraaga** [gradle/gradle#18291] opened 2021-09-15 13:16 UTC
Currently it's difficult to decouple folder structure from the build. #847 is a very long standing issue and composite builds also can't work if Maven coordinates don't match the folder structure. For large projects, it may be important to be able to decouple these though.

Some discussion in https://github.com/open-telemetry/opentelemetry-java/pull/3603

I think if projects could have aliases, it would solve these problems. We can set the project name to the maven artifact ID, but to allow shorter names that reflect the folder structure in task names and project dependencies, we could have aliases that match the folder name.

**Comment by Oberon00** [comment] 2021-09-15 13:38
What name should then be logged in the output e.g. if the task failed? Which alias is canonical? Gradle is already quite complex. Do you see this more as a workaround for #847 and https://docs.gradle.org/current/userguide/composite_builds.html#current_limitations_and_future_work or an independently desirable feature?

**Comment by ljacomet** [comment] 2021-09-17 08:16
closing as duplicate of #847
When the issue around project identity / publication identity gets resolved, this will be considered as well.

**Closed by ljacomet** 2021-09-17 08:16 UTC
Labels: a:feature, closed:duplicate, in:multi-projects

**Comment by Oberon00** [comment] 2021-09-17 08:19
@ljacomet

> When the issue around project identity / publication identity gets resolved, this will be considered as well.

If you plan to consider this issue, why did you close it? I get that it may "depend on" #847, but how is it a duplicate?

**Comment by ljacomet** [comment] 2021-09-17 08:52
Because there is no need to have multiple entry points to a single conceptual problem.
In short, when users want to have `:client:util` and `:server:util` as easy to use project names but require effectively different identities, we are talking about identity - the full coordinates required by dependency management and publication - and a convenient name to use inside the build.

**Comment by Oberon00** [comment] 2021-09-20 13:12
Doesn't look like a gradle-side solution is coming 😕 https://github.com/gradle/gradle/issues/18291 was closed as duplicate of the very old https://github.com/gradle/gradle/issues/847.

If the main concern is gradle task names, maybe a task rule could be used to dispatch tasks like `:instrumentation-apache-camel-2.20-javaagent to `:instrumentation:apache-camel-2.20:opentelemetry-instrumentation-apache-camel-2.20-javaagent` (not sure how the current project name actually is). Though personally I think I would be content just using command line history or an IDE or the kebap abbreviations

**Comment by ljacomet** [comment] 2021-09-20 20:05
Unfortunately this is not an easy issue to solve. An attempt was made a couple release ago but ultimately failed as it was causing too much breakages in existing builds.
We are fully aware of it but have a number of things we want to fix first before doing a dedicated effort on this.

**Comment by Oberon00** [comment] 2021-09-21 09:32
Whoops sorry this comment was meant for the downstream issue.
