### ISSUE TITLE
Deadlock in dependency resolution

### ISSUE THREAD

**Issue by erdi** [gradle/gradle#26825] opened 2023-10-24 16:00 UTC
### Current Behavior

After upgrading from 8.2.1 (we skipped 8.3 as [advised](https://github.com/gradle/gradle/issues/25834#issuecomment-1662247648)) to 8.4 resolving dependencies in all resolvable configurations in all projects (triggered by running `ReportTask` from [`com.github.jk1.dependency-license-report`](https://plugins.gradle.org/plugin/com.github.jk1.dependency-license-report)  across all projects in parallel execution mode) hangs the build.

### Expected Behavior

Resolving dependencies in all resolvable configurations in all projects does not hang the build on 8.4.

### Context (optional)

We've not seen any deadlocks on 8.2.1 or earlier but after switching to 8.4 this deadlocked in 90% of so far executed builds on CI.

I'm not sure if this is significant but it happens in a 1300 project build which includes a build that has an included build.

I'll happily provide more information that is needed to track this down, just please tell me what you need.

### Steps to Reproduce

I've attached a [thread dump](https://github.com/gradle/gradle/files/13120425/dump.txt) taken upon the stuck build being killed. Issue only occurs in CI, I wasn't able to reproduce it locally so I believe that the problem is somewhat transient. 

I did not dig too deep but you can see that three threads are waiting on `0x0000000674bd6000` and another thread which is waiting on another lock is holding it and the waiting threads seem to have `org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolverDescriptorParseContext.resolveMetaDataArtifactFile` in the stack.

### Gradle version

8.4

**Comment by ov7a** [comment] 2023-10-26 12:07
Thank you for providing a valid report.

The issue is in the backlog of the relevant team and is prioritized by them.

Related:
* https://github.com/gradle/gradle/issues/26790

**Comment by ghale** [comment] 2023-11-17 11:16
Hey @erdi!  I think I have a fix for this problem.  Can you give the following nightly a try and see if the issue still happens?
```
$ ./gradlew wrapper --gradle-version=8.6-20231116190533+0000
```

**Comment by erdi** [comment] 2023-11-17 11:53
👀

**Comment by erdi** [comment] 2023-11-18 14:48
Unfortunately it's still getting deadlocked on that version. 

I'm attaching a [threadump](https://github.com/gradle/gradle/files/13400618/threaddump.txt) taken upon the stuck build using `8.6-20231116190533+0000` being killed. Hopefully that helps.

**Comment by ghale** [comment] 2023-11-20 18:18
I got mixed up and copied the wrong nightly version (8.6-20231116190533+0000 does not have my fix).  Can you try the following version instead?

8.6-20231118001259+0000

**Comment by erdi** [comment] 2023-11-20 21:40
I got 3 successful builds on `8.6-20231118001259+0000` whereas on `8.6-20231116190533+0000` I had three failures so it looks like your fix is working, @ghale.

**Closed** 2023-11-22 14:05 UTC
Labels: a:regression, in:dependency-resolution
