### ISSUE TITLE
Conflicts between Windows10 hotspot and connection to the Gradle daemon.

### ISSUE THREAD

**Issue by ducrohet** [gradle/gradle#14958] opened 2020-10-22 16:39 UTC
Hi folks, we are seeing a few reports on the AGP bug tracker regarding issues related to Studio connecting to the Gradle daemon when win10 hotspots are turned on.

Here are 2 reports (de-duplicated into a single issue): https://issuetracker.google.com/170981665
And another that's not confirmed yet to be tied to hotspot: https://issuetracker.google.com/issues/171155457

**Comment by SchlauFuchs** [comment] 2020-12-04 05:57
It is not just gradle. I have the same issue with deluge (the software I get my LibreOffice updates with ;)  ). When the hotspot is running, I cannot start the deluge daemon. The problem might root in Windows 10 network stuff.

**Comment by zuilintan** [comment] 2020-12-20 17:35
> 这不只是摇篮。我在deluge中遇到了同样的问题（我用;获得LibreOffice更新的软件）。热点运行时，我无法启动deluge守护程序。该问题可能源于Windows 10网络内容。

I tried to backtrack to 6.1.1 and the problem was solved

**Comment by NotNotMarshall** [comment] 2021-03-11 18:57
Same with versions 6.7.x and 6.8.x
The only solution is to downgrade for now as @zuilintan said

**Comment by big-guy** [comment] 2021-03-12 01:56
@NotNotMarshall Does this happen for you on the command-line too or just through the IDE/AS?

**Comment by SchlauFuchs** [comment] 2021-03-12 02:53
it is independend of using IDEA.

**Comment by NotNotMarshall** [comment] 2021-03-12 12:09
> @NotNotMarshall Does this happen for you on the command-line too or just through the IDE/AS?

Both

**Comment by NotNotMarshall** [comment] 2021-03-12 12:10
The only solution for now is to either:

Downgrade to Gradle 6.1.1.
Do not use a WiFi hotspot on Windows 10.
Do not start a program which listens on the localhost address of your PC, e.g. a Node or an Apache webserver, or whatever that binds to your loopback address.
Set Android Studio to use ipv6.
If you're sharing your network adapter's connection with another adapter, or you're bridging 2 network adapter connections (like I do), give them a static IP outside the range of your default gateway. For example if your main network's gateway is 192.168.1.x then when you Bridge or Share connections, set the Receiver adapter (the one which the internet is shared to) to use a static IP in a range like 192.168.0.x (trust me it will work).

**Comment by sohaib3335** [comment] 2021-03-22 13:00
I have the same issue and it is pretty much annoying. Have been using many tools out there but specifically Gradle is often too problematic. 
Just as Android Studio automatically upgraded the Gradle version, it started causing the issue.

**Comment by icnahom** [comment] 2021-04-03 15:02
Unless I downgrade my gradle I cannot connect to adb wirelessly.

Process just keeps “Starting Gradle daemon”. Maybe it's because we can't reach (ping) localhost when hotspot is on.

**Comment by har2008preet** [comment] 2021-05-16 07:06
> The only solution for now is either of these:
> 
> 1. Downgrade to Gradle 6.1.1.
> 2. Do not use a WiFi hotspot on Windows 10.
> 3. Do not start a program which listens on the localhost address of your PC, e.g. a Node or an Apache webserver, or whatever that binds to your loopback address.
> 4. Set Android Studio to use ipv6.
> 5. If you're sharing your network adapter's connection with another adapter, or you're bridging 2 network adapter connections (like I do), give them a static IP outside the range of your default gateway. For example if your main network's gateway is 192.168.1.x then when you Bridge or Share connections, set the Receiver adapter (the one which the internet is shared to) to use a static IP in a range like 192.168.0.x (trust me it will work).

Step 5 works 💯 Thanks @NotNotMarshall

**Comment by icnahom** [comment] 2021-07-11 19:26
Any findings on this?

**Comment by infahash** [comment] 2021-07-17 09:08
@NotNotMarshall 
(☞ﾟヮﾟ)☞ Step 5 worked great. Thanks for sharing.
saved lot of time I used to restart pc because can't find the reason

**Comment by icnahom** [comment] 2021-07-22 18:48
Step 5 disables the internet shared to devices.

**Comment by mlopatkin** [comment] 2021-08-24 09:59
Duplicate of #14528.

**Closed by mlopatkin** 2021-08-24 09:59 UTC
Labels: a:bug, to-triage

**Comment by NotNotMarshall** [comment] 2021-09-13 19:59
> @NotNotMarshall
> (☞ﾟヮﾟ)☞ Step 5 worked great. Thanks for sharing.
> saved lot of time I used to restart pc because can't find the reason

Glad it helped :)

**Comment by NotNotMarshall** [comment] 2021-09-13 19:59
> > The only solution for now is either of these:
> > 
> > 1. Downgrade to Gradle 6.1.1.
> > 2. Do not use a WiFi hotspot on Windows 10.
> > 3. Do not start a program which listens on the localhost address of your PC, e.g. a Node or an Apache webserver, or whatever that binds to your loopback address.
> > 4. Set Android Studio to use ipv6.
> > 5. If you're sharing your network adapter's connection with another adapter, or you're bridging 2 network adapter connections (like I do), give them a static IP outside the range of your default gateway. For example if your main network's gateway is 192.168.1.x then when you Bridge or Share connections, set the Receiver adapter (the one which the internet is shared to) to use a static IP in a range like 192.168.0.x (trust me it will work).
> 
> Step 5 works 💯 Thanks @NotNotMarshall

Glad to hear it :)

**Comment by NotNotMarshall** [comment] 2021-09-13 20:00
> Step 5 disables the internet shared to devices.

No it doesn't. Please contact me on my Telegram if you want further help :)

**Comment by DevenValisten** [comment] 2021-12-06 16:30
> > Step 5 disables the internet shared to devices.
> 
> No it doesn't. Please contact me on my Telegram if you want further help :)

i face the same problem

**Comment by NotNotMarshall** [comment] 2021-12-10 15:46
> > > Step 5 disables the internet shared to devices.
> > 
> > 
> > No it doesn't. Please contact me on my Telegram if you want further help :)
> 
> i face the same problem

No it doesn't. Please contact me on my Telegram if you want further help :)

**Comment by DevenValisten** [comment] 2021-12-11 07:45
> > > > Step 5 disables the internet shared to devices.
> > > 
> > > 
> > > No it doesn't. Please contact me on my Telegram if you want further help :)
> > 
> > 
> > i face the same problem
> 
> No it doesn't. Please contact me on my Telegram if you want further help :)

I can't find your Telegram account.

**Comment by NotNotMarshall** [comment] 2021-12-12 15:24
> > > > > Step 5 disables the internet shared to devices.
> > > > 
> > > > 
> > > > No it doesn't. Please contact me on my Telegram if you want further help :)
> > > 
> > > 
> > > i face the same problem
> > 
> > 
> > No it doesn't. Please contact me on my Telegram if you want further help :)
> 
> I can't find your Telegram account.

I didn't even gave you my Telegram ID yet, what're you talking about? lol 

Anyway here it is: https://t.me/AlanTheGreyPatchLad

**Comment by NotNotMarshall** [comment] 2021-12-12 15:25
> > > > > Step 5 disables the internet shared to devices.
> > > > 
> > > > 
> > > > No it doesn't. Please contact me on my Telegram if you want further help :)
> > > 
> > > 
> > > i face the same problem
> > 
> > 
> > No it doesn't. Please contact me on my Telegram if you want further help :)
> 
> I can't find your Telegram account.

I didn't even gave you my Telegram ID yet, what're you talking about? lol

Anyway here it is: https://t.me/IncZero
