### ISSUE TITLE
gradle deamon hangs periodically and has no clue whats happening 

### ISSUE THREAD

**Issue by sjillidimudi** [gradle/gradle#22298] opened 2022-10-03 15:46 UTC
Gradle build hangs indefinitely some times . Either from the Idea or from outside , it hangs . When the thread dump is taken , it always pointed out to below suspicious stack as this stack is common in every thread dump when it hanged.

`
"Daemon worker Thread 2" #429 prio=5 os_prio=0 tid=0x272a6800 nid=0xe28c runnable [0x279fd000]
   java.lang.Thread.State: RUNNABLE
        at net.rubygrapefruit.platform.internal.jni.PosixFileSystemFunctions.listFileSystems(Native Method)
        at net.rubygrapefruit.platform.internal.PosixFileSystems.getFileSystems(PosixFileSystems.java:30)
        at org.gradle.internal.watch.vfs.impl.DefaultWatchableFileSystemDetector.detectUnsupportedFileSystems(DefaultWatchableFileSystemDetector.java:60)
        at org.gradle.internal.watch.registry.impl.WatchableHierarchies.invalidateUnsupportedFileSystems(WatchableHierarchies.java:125)
        at org.gradle.internal.watch.registry.impl.WatchableHierarchies.removeUnwatchableFileSystems(WatchableHierarchies.java:114)
        at org.gradle.internal.watch.registry.impl.WatchableHierarchies.removeUnwatchableContent(WatchableHierarchies.java:83)
        at org.gradle.internal.watch.registry.impl.HierarchicalFileWatcherUpdater.buildFinished(HierarchicalFileWatcherUpdater.java:114)
        at org.gradle.internal.watch.registry.impl.DefaultFileWatcherRegistry.buildFinished(DefaultFileWatcherRegistry.java:157)
        at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem$2.lambda$call$0(WatchingVirtualFileSystem.java:199)
        at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem$2$$Lambda$1032/10747500.get(Unknown Source)
        at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem.withWatcherChangeErrorHandling(WatchingVirtualFileSystem.java:320)
        at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem.access$1000(WatchingVirtualFileSystem.java:53)
        at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem$2.call(WatchingVirtualFileSystem.java:199)
        at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem$2.call(WatchingVirtualFileSystem.java:179)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:79)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$$Lambda$24/11226545.apply(Unknown Source)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:79)
        at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem.lambda$beforeBuildFinished$5(WatchingVirtualFileSystem.java:179)
        at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem$$Lambda$1031/30090470.apply(Unknown Source)
        at org.gradle.internal.vfs.impl.VfsRootReference.update(VfsRootReference.java:40)
        at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem.beforeBuildFinished(WatchingVirtualFileSystem.java:179)
        at org.gradle.tooling.internal.provider.FileSystemWatchingBuildActionRunner.run(FileSystemWatchingBuildActionRunner.java:94)
        at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:41)
        at org.gradle.launcher.exec.RootBuildLifecycleBuildActionExecutor.lambda$execute$0(RootBuildLifecycleBuildActionExecutor.java:40)
        at org.gradle.launcher.exec.RootBuildLifecycleBuildActionExecutor$$Lambda$74/16828419.apply(Unknown Source)
        at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:154)
        at org.gradle.launcher.exec.RootBuildLifecycleBuildActionExecutor.execute(RootBuildLifecycleBuildActionExecutor.java:40)
        at org.gradle.internal.buildtree.DefaultBuildTreeContext.execute(DefaultBuildTreeContext.java:40)
        at org.gradle.launcher.exec.BuildTreeLifecycleBuildActionExecutor.lambda$execute$0(BuildTreeLifecycleBuildActionExecutor.java:56)
        at org.gradle.launcher.exec.BuildTreeLifecycleBuildActionExecutor$$Lambda$25/3230554.apply(Unknown Source)
        at org.gradle.internal.buildtree.BuildTreeState.run(BuildTreeState.java:53)
        at org.gradle.launcher.exec.BuildTreeLifecycleBuildActionExecutor.execute(BuildTreeLifecycleBuildActionExecutor.java:56)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor$3.call(RunAsBuildOperationBuildActionExecutor.java:61)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor$3.call(RunAsBuildOperationBuildActionExecutor.java:57)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:79)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$$Lambda$24/11226545.apply(Unknown Source)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:79)
        at org.gradle.launcher.exec.RunAsBuild
`

### Expected Behavior
gradle should build the project with out any issues . 

### Current Behavior
Currently it just hangs 

### Context
Gradle any action hangs at that time . Either from the intellij or from command line . 

### Steps to Reproduce 
It happens sporadically . Once it starts , there is no way to make it work until it starts working again . I dont have steps to reproduce ,

### Your Environment
gradle : 7.2
Operating System : Windows 10.

**Comment by jbartok** [comment] 2022-10-13 06:31
Sorry that you're having trouble with Gradle!

I fully understand that this is a genuine and annoying issue, but it's unlikely we can do anything about it, without a way to reproduce... Can you pls. at least give us the full thread dump, when you experience it again? Thanks in advance.

**Comment by sjillidimudi** [comment] 2022-10-13 13:09
One interesting update i have is .. today the issue happened and left it like that and moved on to some other stuff .. after some time when i looked back the process is up and running .  It seems its not struck but this `net.rubygrapefruit.platform.internal.jni.PosixFileSystemFunctions.listFileSystems(Native Method)` call seems to taking its sweet time . My service generally starts in 30 sec .. and i have waited for 5 minutes before i moved on to the next task.

**Comment by wolfs** [comment] 2022-10-14 08:56
I think this is a duplicate of #17955. Closing as such. Please comment if it this is not the case. Note that https://github.com/gradle/gradle/issues/17955 lists a workaround: add `org.gradle.vfs.watch=true` to your `gradle.properties`.

**Closed by wolfs** 2022-10-14 08:56 UTC
Labels: in:daemon, a:bug, re:windows, closed:duplicate

**Comment by sjillidimudi** [comment] 2022-11-13 20:05
I agree . Recently some of mounted drives were offline . I didn't get a chance to test as things got changed and i have no access to the specific problematic machine any more.
