### ISSUE TITLE
Using a version catalog entry with children with a configuration closure does not work

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#19609] opened 2022-01-18 20:58 UTC
If in Gradle 7.3.3 you have in your version catalog TOML file the libraries `foo` and `foo-bar` defined
and then try to use it like `implementation(libs.foo) { exclude("...", "...") }` you only get
```
None of the following functions can be called with the arguments supplied: 
public fun <T : Dependency> DependencyHandler.implementation(dependency: TypeVariable(T), action: Action<TypeVariable(T)>): TypeVariable(T) defined in org.gradle.kotlin.dsl
public fun DependencyHandler.implementation(dependencyNotation: String, dependencyConfiguration: Action<ExternalModuleDependency>): ExternalModuleDependency defined in org.gradle.kotlin.dsl
public fun DependencyHandler.implementation(dependencyNotation: Provider<*>, dependencyConfiguration: Action<ExternalModuleDependency>): Unit defined in org.gradle.kotlin.dsl
```

If you change `foo-bar` to `fooBar`, the same code works.

**Comment by octylFractal** [comment] 2022-01-19 16:21
Duplicate of #18617

**Closed by octylFractal** 2022-01-19 16:21 UTC
Labels: a:bug, in:dependency-version-catalog
