### ISSUE TITLE
GradleVersion doesn't recognize +

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#28761] opened 2024-04-10 11:59 UTC
### Current Behavior

per comment on another ticket, I'm led to believe that the `GradleVersion` class will replace `VersionNumber`

Referring to https://docs.gradle.org/current/userguide/single_versions.html#version_ordering

gradle supports '+' in version strings

When using `GradleVersion.version` I'm getting this error

```
java.lang.IllegalArgumentException: '0.1.1-alpha.1+1.g9b3db35' is not a valid Gradle version string (examples: '1.0', '1.0-rc-1')
```

### Expected Behavior

gradle should happily parse this version as it's a valid [semver](https://semver.org)

### Context (optional)

In the event this is a valid version for gradle to handle in dependencies but not a valid use case for `GradleVersion`, I need a way to compare the versions I'm generating for gradle plugins.

Related to https://github.com/gradle/gradle/issues/28755
I'm developing a workaround for https://github.com/gradle/gradle/issues/28609

### Steps to Reproduce

```java
   assertThat(GradleVersion.version("0.1.1-alpha.1+1.g9b3db35"))
        .isGreaterThan(GradleVersion.version("0.0.0"))
        .isGreaterThan(GradleVersion.version("0.1.0"))
        .isLessThan(GradleVersion.version("0.1.1"));
```

### Gradle version

8.7

**Comment by ov7a** [comment] 2024-04-11 12:05
This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/28755

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

The comment in the issue wasn't intended to mean "use GradleVersion instead of VersionNumber". Gradle versions themselves don't have '+' in the id, so it's ok.

**Closed by ov7a** 2024-04-11 12:05 UTC
Labels: a:bug, to-triage
