### ISSUE TITLE
Change the default of java-gradle-plugin to enableStricterValidation=true for Gradle 9.0

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#30825] opened 2024-10-07 16:02 UTC
### Expected Behavior

Applying `java-gradle-plugin` should enforce strict rules to make sure plugins are doing the right things (e.g. marking task inputs and outputs)

### Current Behavior (optional)

The checks are default off, and developers have to explicitly enable it with
```
validatePlugins {
    enableStricterValidation = true
}
```

### Context

Plugins have a huge impact on the whole ecosystem, as fixing one plugin often means fixing thousands of builds. Starting in Gradle 9.0 we should default to enabling these stricter validations.

**Comment by ov7a** [comment] 2024-10-08 13:36
This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/22600

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

**Closed by ov7a** 2024-10-08 13:36 UTC
Labels: a:feature, to-triage
