### ISSUE TITLE
API browser's search results don't have background

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#25353] opened 2023-06-10 18:14 UTC
### Issue type

Wrong or misleading information

### Problem description

I think it's easiest if I just put a screenshot

![image](https://github.com/gradle/gradle/assets/2906988/6d3a5135-44e4-408e-9002-0920c703eb3a)

### Context (optional)

It applies to all pages inside javadoc.

### Page with the problem

https://docs.gradle.org/current/javadoc/org/gradle/api/Project.html

**Comment by ljacomet** [comment] 2023-06-12 08:51
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before a fix is made.

**Comment by TWiStErRob** [comment] 2023-11-15 21:40
Looks good now on both desktop and mobile.

![Screenshot_20231115-211134](https://github.com/gradle/gradle/assets/2906988/e4c1bacb-feb9-4bd2-a4b2-c83a676e1e30)

**Comment by ljacomet** [comment] 2024-05-31 07:27
Fixed in #28712

**Closed by ljacomet** 2024-05-31 07:27 UTC
Labels: in:documentation-infrastructure, a:bug
