### ISSUE TITLE
"Unable to find source java class" error when file modified sits within symlinked source directory

### ISSUE THREAD

**Issue by Diarrhio** [gradle/gradle#9202] opened 2019-04-24 00:58 UTC
We have a build system which generates build.gradle files outside our source directory, because we want our source tree to be free of any build and output related files. Therefore, our build system will create symlinks to source directories in our source tree and sets the `sourceSets.main.java.srcDirs` property to point to the symLink.

Our build system also generates some java files of its own and writes them in a directory which is a sibling of the symlink. Our directory layout is like this:

```
src/main/java/
              build/
                   com/
                       foo/bar/x 
             linkparent/
                      com/          // <- This is a symlink to a source directory outside of the project
                          foo/bar/y
```

In the build.gradle file, we have:
```
	sourceSets {
		main {
			java {
				srcDirs = ['src/main/java/build', 'src/main/java/linkparent']
			}
		}
	}
```

What we are seeing is odd. If we clean and build, we get successful builds. However, if we modify a file under the symlink and do a build, we get the following error:

> Execution failed for task ':app:compileDebugJavaWithJavac'.
> Unable to find source java class: '/Users/dario/Dev/Builds/AS34App/app/src/main/java/src-source/com/example/as34app/MainJavaClass.java' because it does not belong to any of the source dirs: '[/Users/dario/Dev/Builds/AS34App/app/src/main/java/build, /Users/dario/Dev/Builds/AS34App/app/src/main/java/src-source, /Users/dario/Dev/Builds/AS34App/app/src/debug/java, /Users/dario/Dev/Builds/AS34App/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r, /Users/dario/Dev/Builds/AS34App/app/build/generated/source/buildConfig/debug, /Users/dario/Dev/Builds/AS34App/app/build/generated/aidl_source_output_dir/debug/compileDebugAidl/out, /Users/dario/Dev/Builds/AS34App/app/build/generated/renderscript_source_output_dir/debug/compileDebugRenderscript/out]'

That output is from a very simple test project I set up, not using our build system. Just a simple project with the same directory structure.

If I clean and build, I once again get a successful build. But again, modifying any file under the symlinked directory means I need to clean and build, which makes for very long development cycles.

### Expected Behavior
Symlinked source directories should behave just like regular source directories

### Current Behavior
Symlinked sourece directories cause build failures when source files under those symlinked directories are modified

### Context
Just trying to edit java source files and build.

### Steps to Reproduce 
See attached project.
* Navigate to project and do `./gradlew build`
* Modify the MainJavaClass.java file under the symlinked source directory
* Do `./gradlew build`
* You should see error similar to above
* Do `./gradlew clean` and then `./gradlew build`
* You should see a successful build
* Repeat by modifying MainJavaClass.java

I was unable to reproduce this with Kotlin files, only Java files

### Your Environment
* macOS: 10.14.4 (18E226)
* Gradle 5.1.1
* Android Studio 3.4, though this issue seems unrelated to Android Studio and has been around since Android Studio 3.0 upgraded gradle to 3.x
* Build scan URL: https://gradle.com/s/goyouqnnog7cq
[AS34App.zip](https://github.com/gradle/gradle/files/3110115/AS34App.zip)

**Comment by big-guy** [comment] 2019-04-24 21:55
Instead of using symlinks, could you just configure the Gradle build to look at the target of the symlink?

@oehme it looks like you may recognize this (SourceToNameConverter).  Any thoughts? I don't see a simple fix to this (short of not doing the hacky path juggling).

**Comment by ThomasCraigNelson** [comment] 2019-04-24 23:05
This is not a practical workaround for situations such as mine where I'm trying to introduce gradle where the source does not live by the conventions and it would be viewed as disruptive to make it do so.  Not everyone has the ability to start fresh.  Anyway a clean build has no issue and I believe the bug is in SourceToNameConverter.getClassName.

**Comment by Diarrhio** [comment] 2019-04-24 23:12
> Instead of using symlinks, could you just configure the Gradle build to look at the target of the symlink?

If I use absolute paths to target of the symlink, the issue disappears, but this is not ideal as it will involve a decent amount of work on our side. This also seems like something Gradle should handle, though I'm not at all familiar with the Gradle codebase so I have no idea what is actually involved in fixing it. If it's too problematic for Gradle to follow symlinks, let me know and I'll get us to budget some time to workaround on our end. Thanks.

**Comment by oehme** [comment] 2019-05-28 13:15
The problem is in the fact that the `getRelativePath` method we use (from ANT) uses canonical paths. It shouldn't do that, but instead only compare the normalized paths just like all other code in Gradle. We can use `java.nio.Path.relativize` for that.

**Comment by wroth** [comment] 2019-10-03 20:30
Is this change (allowing the use of symbolic links) in Gradle 5.6.2?   It was unclear (well, to me :-) ) from the above.  We would also find this extremely useful.

**Comment by shamilovtim** [comment] 2019-12-25 06:23
same problem here. both my gradle and my symlinks files are generated so unfortunately this problem hurts bad

**Comment by melix** [comment] 2020-03-17 15:24
I confirm that this seems to be fixed by #12511 but I still need to write a proper test for it.

**Comment by melix** [comment] 2020-03-17 16:38
Well, it seems this is already fixed on `master` too, since `SourceToNameConverter` has been removed.

**Comment by ljacomet** [comment] 2020-03-23 09:23
Closing since this is already fixed

**Closed by ljacomet** 2020-03-23 09:23 UTC
Labels: @jvm, a:bug, from:contributor, in:jvm-ecosystem
