### ISSUE TITLE
Gradle 4.6+ times out where older Gradle versions resolved quickly

### ISSUE THREAD

**Issue by chriskessel** [gradle/gradle#6203] opened 2018-08-06 18:53 UTC
We reference multiple repositories through our artifactory server, first ones from remote-repos mappe din artifactory, then through two different defined repository setups because some of our libraries are stored in an old weird ivy directory format.

```
        maven {
            url 'http://artifactoryserver/artifactory/remote-repos'
        }
        maven {
            url 'http://artifactoryserver/artifactory/internal-repos'
        }
        ivy {
            url 'http://artifactoryserver/artifactory/internal-repos'
            layout "pattern", {
                artifact "[organization]/[module]/[revision]/[artifact]-([classifier]-)[revision](-[suffix]).[ext]"
            }
        }
 ```
Here's a case of an internal library, found in first internal-repos, looking for a dependency it should find in the 2nd ivy based one. This worked in Gradle 4.5. This no longer works in 4.6+ (I've tried 4.6 and 4.9).
```
> Could not resolve joda-time:joda-time:2.9.7-2017b.
  Required by:
      project :domain > com.mycompany:myinternallib:1.1
   > Could not resolve joda-time:joda-time:2.9.7-2017b.
      > Could not get resource 'http://artifactoryserver/artifactory/remote-repos/joda-time/joda-time/2.9.7-2017b/joda-time-2.9.7-2017b.jar'.
         > Could not HEAD 'http://artifactoryserver/artifactory/remote-repos/joda-time/joda-time/2.9.7-2017b/joda-time-2.9.7-2017b.jar'.
            > Read timed out
```
### Expected Behavior
It should continue on to the next repository to find the dependency.

### Current Behavior
It stops after finding the dependency in internal-repose, then failing to find the nested dependency in the remote-repos (which it's not there, its in later internal-repos).

### Context
I can't upgrade past Gradle 4.5.

### Steps to Reproduce (for bugs)
Not sure, I guess set up a similar set of dependencies? 

### Your Environment
Gradle 4.9, Java 1.8, artifactory 2.6.6 (yea, it's ancient, I know)

I'm guessing this has been filed before, but my attempt to find the same problem failed. Sorry :(.

**Comment by oehme** [comment] 2018-08-07 10:15
> Read timed out

This is expected behavior - A read timeout is a fatal error and Gradle will not continue to other repositories, as that would mean a non-reproducible results. Gradle will only continue if it gets a clear "not found" (404) from the repository.

**Comment by chriskessel** [comment] 2018-08-07 14:26
The problem is this timeout ONLY happens with 4.6 and earlier. I can build it hundreds of times in a row with gradle 4.5 without error.

What changed in 4.6?

**Comment by oehme** [comment] 2018-08-07 14:55
We introduced a timeout of half a minute in Gradle 4.6. Does your company repo have connectivity problems?

**Comment by chriskessel** [comment] 2018-08-07 15:26
I've never noticed any connection issues, builds have always succeeded in the past. It certainly looks to be failing right at about the 30 second time frame though. If there wasn't a timeout, then previously wouldn't the build have never completed or failed after some long timeout?

The failure is every single time with 4.6+ and never fails with 4.5 (we have thousands of builds in Jenkins without issue in 4.5), so presumbly something in the logic must have changed in addition to a timeout. Is it using HEAD where it didn't use HEAD before or some such?

```

```

**Comment by oehme** [comment] 2018-08-07 15:38
Before Gradle 4.6, the build would never have completed unless the server finally returned something. I'm not aware of any change to the network requests we send in 4.6. We always used HEAD requests for JARs.

Are you sure it's actually making a network request with 4.5? It may be fully cached while 4.6 may be revalidating the cache due to an update to the metadata layout. You could check by using an empty `--gradle-user-home` with 4.5 and watching for any unusually long download times.

**Comment by chriskessel** [comment] 2018-08-07 15:51
I renamed my .gradle directory to .gradlebak and rebuilt. The dependency downloads were quick, nothing unexpectedly slow anywhere.

Even with downloading all the dependencies (~600 downloads), the entire build took 109 seconds.

**Comment by chriskessel** [comment] 2018-08-07 15:57
FWIW, the failure in 4.9 seems to be on the first "weird ivy style" repo dependency. 4.5 has no problem with it,
```
Download http://myartifactoryserver/artifactory/internal-repos/com.mycompany/myinternallib/20180717150637/ivy-20180717150637.xml
...variety of transitive dependencies...
Download http://myartifactoryserver/artifactory/internal-repos/com.mycompany/myinternallib/20180717150637/myinternallib-20180717150637.jar
```
In 4.9, it gives that error I noted at the very top, failing to get joda-time.

**Comment by oehme** [comment] 2018-08-07 15:58
I'm afraid we'll need to dig into the debug logs comparing 4.5 and 4.9. Can you provide those?

**Comment by chriskessel** [comment] 2018-08-07 16:02
Just the --debug flag? Do you need both 4.5 and 4.9?

**Comment by oehme** [comment] 2018-08-07 16:10
Yes, we'd need the `--debug` log of both to be able to compare.

**Comment by chriskessel** [comment] 2018-08-07 16:12
Ok, cool! I'll work on generating those and obfuscating any company specific names I'd get yelled at for leaving as is. Hopefully it won't take too long.

**Comment by chriskessel** [comment] 2018-08-07 16:28
Ok, big files...
[gradle45.txt](https://github.com/gradle/gradle/files/2267245/gradle45.txt)
[gradle49.txt](https://github.com/gradle/gradle/files/2267246/gradle49.txt)

**Comment by bigdaz** [comment] 2018-08-08 14:07
@chriskessel Thanks for the detailed report and the logs. It looks like Gradle 4.9 is failing to parse the Artifactory response to http://artifactory.myorg.io/artifactory/internal-repos/joda-time/joda-time/2.9.7-2017b/joda-time-2.9.7-2017b.pom. There's an error in the 4.9 log (snippet below) that looks suspicious. 

In Gradle 4.6 we [upgraded the version of Apache HttpClient](https://github.com/gradle/gradle/commit/ee7e5d52d03a83dd37118892a2aea9996784e667) that is used internally by Gradle. It's possible that this upgraded version is somehow incompatible with Artifactory 2.6.6.

To help isolate this issue further, you could try a simple build script that resolves `joda-time:joda-time:2.9.7-2017b` from `http://artifactoryserver/artifactory/internal-repos`. If this works, see what additional complexity is required in order to reproduce the resolution failure with Gradle 4.9. (ie try additional repository definitions, try resolving the Ivy module that drags in `joda-time` transitively, etc).

Here's the error message I see in the logs:
```
09:25:06.433 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Executing request GET /artifactory/internal-repos/joda-time/joda-time/2.9.7-2017b/joda-time-2.9.7-2017b.pom HTTP/1.1
09:25:06.433 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Target auth state: UNCHALLENGED
09:25:06.433 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Proxy auth state: UNCHALLENGED
09:25:06.456 [DEBUG] [org.apache.http.impl.conn.DefaultHttpResponseParser] Garbage in response: HTTP/1.1 200 OK
09:25:06.456 [DEBUG] [org.apache.http.impl.conn.DefaultHttpResponseParser] Garbage in response: Server: nginx/1.1.19
09:25:06.456 [DEBUG] [org.apache.http.impl.conn.DefaultHttpResponseParser] Garbage in response: Date: Tue, 07 Aug 2018 16:16:55 GMT
09:25:06.456 [DEBUG] [org.apache.http.impl.conn.DefaultHttpResponseParser] Garbage in response: Content-Type: application/x-maven-pom+xml
09:25:06.456 [DEBUG] [org.apache.http.impl.conn.DefaultHttpResponseParser] Garbage in response: Content-Length: 32016
09:25:06.456 [DEBUG] [org.apache.http.impl.conn.DefaultHttpResponseParser] Garbage in response: Connection: keep-alive
09:25:06.456 [DEBUG] [org.apache.http.impl.conn.DefaultHttpResponseParser] Garbage in response: X-Artifactory-Id: fce5fb90148f9680:1dc0317f:165101752fa:-8000
09:25:06.456 [DEBUG] [org.apache.http.impl.conn.DefaultHttpResponseParser] Garbage in response: Last-Modified: Tue, 21 Mar 2017 19:10:06 GMT
09:25:06.456 [DEBUG] [org.apache.http.impl.conn.DefaultHttpResponseParser] Garbage in response: ETag: 81cf9df2980a2f611c0136943763bd3965920e8c
09:25:06.456 [DEBUG] [org.apache.http.impl.conn.DefaultHttpResponseParser] Garbage in response: X-Checksum-Sha1: 81cf9df2980a2f611c0136943763bd3965920e8c
09:25:06.456 [DEBUG] [org.apache.http.impl.conn.DefaultHttpResponseParser] Garbage in response: X-Checksum-Md5: 401329009a2305914756acf4c5f430b2
09:25:06.456 [DEBUG] [org.apache.http.impl.conn.DefaultHttpResponseParser] Garbage in response: Content-Disposition: attachment; filename=joda-time-2.9.7-2017b.pom
09:25:06.456 [DEBUG] [org.apache.http.impl.conn.DefaultHttpResponseParser] Garbage in response: X-Artifactory-Filename: joda-time-2.9.7-2017b.pom
09:25:06.456 [DEBUG] [org.apache.http.impl.conn.DefaultHttpResponseParser] Garbage in response: 
09:25:06.456 [DEBUG] [org.apache.http.impl.conn.DefaultHttpResponseParser] Garbage in response: <?xml version="1.0" encoding="UTF-8"?>
09:25:06.456 [DEBUG] [org.apache.http.impl.conn.DefaultHttpResponseParser] Garbage in response: <project
09:25:06.456 [DEBUG] [org.apache.http.impl.conn.DefaultHttpResponseParser] Garbage in response:     xmlns="http://maven.apache.org/POM/4.0.0"
09:25:06.456 [DEBUG] [org.apache.http.impl.conn.DefaultHttpResponseParser] Garbage in response:     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
09:25:06.457 [DEBUG] [org.apache.http.impl.conn.DefaultHttpResponseParser] Garbage in response:     xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
09:25:06.457 [DEBUG] [org.apache.http.impl.conn.DefaultHttpResponseParser] Garbage in response: 
09:25:06.457 [DEBUG] [org.apache.http.impl.conn.DefaultHttpResponseParser] Garbage in response:   <modelVersion>4.0.0</modelVersion>
09:25:06.457 [DEBUG] [org.apache.http.impl.conn.DefaultHttpResponseParser] Garbage in response:   <groupId>joda-time</groupId>
09:25:06.457 [DEBUG] [org.apache.http.impl.conn.DefaultHttpResponseParser] Garbage in response:   <artifactId>joda-time</artifactId>
09:25:06.457 [DEBUG] [org.apache.http.impl.conn.DefaultHttpResponseParser] Garbage in response:   <packaging>jar</packaging>
09:25:06.457 [DEBUG] [org.apache.http.impl.conn.DefaultHttpResponseParser] Garbage in response:   <name>Joda-Time</name>
09:25:06.457 [DEBUG] [org.apache.http.impl.conn.DefaultHttpResponseParser] Garbage in response:   <version>2.9.7-2017b</version>
09:25:06.457 [DEBUG] [org.apache.http.impl.conn.DefaultHttpResponseParser] Garbage in response:   <description>Date and time library to replace JDK date handling</description>
09:25:06.457 [DEBUG] [org.apache.http.impl.conn.DefaultHttpResponseParser] Garbage in response:   <url>http://www.joda.org/joda-time/</url>
```

**Comment by chriskessel** [comment] 2018-08-08 15:18
I created a build.gradle that's just the joda-time dependency. It's related to the repository sequencing. The following repositories definition works in 4.9 and it resolves the joda-time library (we've got a customized joda version in our internal repo for internal reasons).

```
       repositories {
//            maven {
//                url 'http://artifactory.myorg.io/artifactory/remote-repos'
//            }
            maven {
                url 'http://artifactory.myorg.io/artifactory/internal-repos'
            }
        }
```

If I uncomment that first maven repo, it fails. I've tried to massively trim down the project to just this one dependency, new file attached. Still has that same "garbage" response. It's from the remote-repo though, so seems like regardless of why that failed, it should still try move on to the next repo and find it?

If I swap the order of the repos, it works, but that'll cause problems in our build because we have some cases where the internal-repo has a file, but we want to get the remote-repo file if it's there. And these are cross-team shared repos, so I can't go clean out or rename anything in them or I might break other teams.

[simpletest.txt](https://github.com/gradle/gradle/files/2270764/simpletest.txt)

**Comment by bigdaz** [comment] 2018-08-09 21:56
Gradle will only look in the second repository if it can successfully determine that the module is _missing_ from the first repository.  In this case the first repository is returning an invalid response (timing out), causing an exception in our HTTP client. This failure does not tell Gradle definitively that the module is missing, so Gradle does not continue on to check the second repository.

We implemented it this way to avoid non-reproducible build results when a repository is temporarily offline or misbehaving.

So the key question is why HttpClient is not able to successfully make `HEAD` requests to Artifactory 2.6.6. There may be some things we can do to address this, although Artifactory 2.6.6 was end-of-life on 20-Jun-2014: https://www.jfrog.com/confluence/display/RTF/End+of+Life

**Comment by chriskessel** [comment] 2018-08-09 22:01
I'll see if we can update artifactory :) and let you know if it's still an issue. That'll be a fun internal boulder to push uphill...

Thanks for the time you spent looking into this, I appreciate it!

**Comment by bigdaz** [comment] 2018-08-09 22:18
Even if you can't update Artifactory across the board, it might be possible to install a newer version of Artifactory as a cache/proxy in front of the corporate Artifactory instance. I'm not an expert, but I've done this using a local Artifactory instance to proxy a bunch of remote instances.

**Comment by cw1427** [comment] 2018-08-21 06:28
@bigdaz ,  Well in some case, like network problem happened on the first repository,  but it is fine for the second one.  How could let Gradle keep go on trying on the second local repository ?

**Comment by tshasc** [comment] 2018-10-03 16:19
> > Read timed out
> 
> This is expected behavior - A read timeout is a fatal error and Gradle will not continue to other repositories, as that would mean a non-reproducible result. Gradle will only continue if it gets a clear "not found" (404) from the repository.

Is it possible to avoid this and let Gradle continue to the other repositories when met timeout?

**Comment by chriskessel** [comment] 2018-10-05 14:30
FWIW, one of our engineers started sniffing around with packet trace. He tracked the garbage in the artifactory response to an old nginx in front of our artifactory instance (or something like that). We were able to put a new version of that in place, left the actual artifactory instance alone, and things worked.

**Comment by oehme** [comment] 2018-10-05 16:17
Glad you found the culprit :)

**Closed by oehme** 2018-10-05 16:17 UTC
Labels: a:bug, affects-version:4.6, from:contributor, in:dependency-management
