### ISSUE TITLE
`dependencies` task support for configuration cache

### ISSUE THREAD

**Issue by mathjeff** [gradle/gradle#19095] opened 2021-11-23 18:40 UTC
### Expected Behavior
Running `./gradlew :subproject:dependencies && ./gradlew :subproject:dependencies` should succeed even if configuration caching is enabled

### Current Behavior
Running `./gradlew :subproject:dependencies && ./gradlew :subproject:dependencies` fails because the set of dependencies has been discarded

```
frameworks/support$ ./gradlew viewpager2:viewpager2:dependencies
Configuration cache is an incubating feature.
Reusing configuration cache.
> Task :viewpager2:viewpager2:dependencies FAILED

1 problem was found reusing the configuration cache.
- Task `:viewpager2:viewpager2:dependencies` of type `org.gradle.api.tasks.diagnostics.DependencyReportTask`: cannot deserialize object of type 'org.gradle.api.artifacts.Configuration' as these are not supported with the configuration cache.
  See https://docs.gradle.org/7.2/userguide/configuration_cache.html#config_cache:requirements:disallowed_types

See the complete report at file:///Users/jellefresen/workspace/android/androidx-compose/frameworks/support/build/reports/configuration-cache/9y7v26ujv7wt5ov514l2f5976/4c6ykuuvrws934qp4ff0uw25c/configuration-cache-report.html

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':viewpager2:viewpager2:dependencies'.
> The value of this property has been discarded during serialization.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 892ms
1 actionable task: 1 executed
Configuration cache entry reused with 1 problem.
```

**Comment by eskatos** [comment] 2021-11-24 07:33
Thanks @mathjeff 
Closing as a duplicate of https://github.com/gradle/gradle/issues/17470

**Closed by eskatos** 2021-11-24 07:33 UTC
Labels: a:bug, to-triage
