### ISSUE TITLE
[feature] provide `android` application as one of the `init` plugins

### ISSUE THREAD

**Issue by joe733** [gradle/gradle#26272] opened 2023-09-04 11:41 UTC
## Expected Behavior

Requesting generation of an android project using `gradle init` task.

## Current Behavior

Currently `grade init` supports only these types of applications:

```console
$ gradle init
Select type of project to generate:
  1: basic
  2: application
  3: library
  4: Gradle plugin
Enter selection (default: basic) [1..4] 2

Select implementation language:
  1: C++
  2: Groovy
  3: Java
  4: Kotlin
  5: Scala
  6: Swift
Enter selection (default: Java) [1..6]
```

![Screenshot from 2023-09-04 17-07-14](https://github.com/gradle/gradle/assets/38415384/b52ec845-383e-4c6e-8664-0ee3fdfd0c24)

## Context

I'm trying to develop an android application using only command line tools, USB cable and a phone.

**Comment by jbartok** [comment] 2023-09-06 12:52
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #1686 

Please add your use case and 👍 to that issue.

***

We would not add this ourselves, but we could make init support templates so others can.

Also relates to:
* #2339

**Closed by jbartok** 2023-09-06 12:52 UTC
Labels: a:feature, to-triage
