### ISSUE TITLE
Start signing distributions/gradle-*-bin.zip artifacts

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#20782] opened 2022-05-13 19:40 UTC
Currently, there is no way to verify that a given `gradle-*-bin.zip` was built by Gradle and has not been modified. Gradle download page provides a sha256 sum, but it would a lot better if these zip files came with `gradle-*-bin.zip.asc` pgp armor files that would allow validating that the zip was in fact signed with a key that is only held by Gradle.

### Expected Behavior
Gradle also ships .asc files to allow validating the distribution is un-modified.

### Current Behavior
Only sha256 sum is provided.

### Context
As we tried to tighten our toolchain security, this will be one vital step to verify that prebuilt binaries are from Gradle.

**Comment by liutikas** [comment] 2022-06-10 23:47
Any updates here? It is a fairly minimal effort for Gradle to add a signing step and it would be very helpful in validation.

**Comment by ov7a** [comment] 2024-03-19 13:41
Sorry for the late reply.

***

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/13778

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

**Closed by ov7a** 2024-03-19 13:41 UTC
Labels: a:feature, in:building-gradle
