### ISSUE TITLE
Unable to use Windows SSL trust store

### ISSUE THREAD

**Issue by knolleCC** [gradle/gradle#6584] opened 2018-08-31 08:35 UTC
The JRE can be set to use the Windows trust store via `javax.net.ssl.trustStoreType=Windows-ROOT`.
Gradle seems to have its own trust store handling which does not respect this setting.
As far as I understand the code in `DefaultSslContextFactory.java`, there always needs to be a trust store file (`javax.net.ssl.trustStore=SOME-FILE`) or code will fall back to use the default JRE files.
Why does gradle not use the Java default method?

Actual problem:
I want to use a maven repository via HTTPS with a special company certificate.

Goal: 
Support Windows trust store usage via `javax.net.ssl.trustStoreType=Windows-ROOT/MY` as the JRE does.

**Comment by wendlm** [comment] 2018-09-28 09:19
We encounter the same problem which is very annoying actually, cause we have to add our own company certificate to the JVM keystore each time we change the JVM.

**Comment by hbdesiato** [comment] 2018-10-22 15:06
There is a workaorund: Just set `javax.net.ssl.trustStore` to any readable regular file. This file will be ignored if you set `javax.net.ssl.trustStoreType=Windows-ROOT`.

Adding the following lines to your gradle.properties file should work:
```
systemProp.javax.net.ssl.trustStore=C:\\Windows\\win.ini
systemProp.javax.net.ssl.trustStoreType=Windows-ROOT

```

**Comment by TTMaZa** [comment] 2019-04-04 06:29
Have you tried 
systemProp.javax.net.ssl.trustStore=NUL

**Comment by justin-michel-boeing** [comment] 2019-08-21 14:36
Setting the trustStore property to the win.ini worked for me, but others on my team now can't build and are getting  IOException:  Invalid keystore format 

Is anyone acknowledging that this is a bug in gradle, and are there plans to fix it?

**Comment by knolleCC** [comment] 2020-01-27 13:24
> Adding the following lines to your gradle.properties file should work:
> 
> ```
> systemProp.javax.net.ssl.trustStore=C:\\Windows\\win.ini
> systemProp.javax.net.ssl.trustStoreType=Windows-ROOT
> ```

Thanks @hbdesiato, this works for me. Still I would appreciate this bug to be fixed and still I wonder why they do not use the default JRE mechanism.

**Comment by knolleCC** [comment] 2020-01-27 13:41
> Still I would appreciate this bug to be fixed and still I wonder why they do not use the default JRE mechanism.

Uhm, seems I have to apologize. Using Gradle 6.0.1, just specifying "javax.net.ssl.trustStoreType=Windows-ROOT" now works for me. Did they fix this already?

**Comment by knolleCC** [comment] 2020-03-04 14:06
> Uhm, seems I have to apologize. Using Gradle 6.0.1, just specifying "javax.net.ssl.trustStoreType=Windows-ROOT" now works for me. Did they fix this already?

Hmm, forget what I posted in Jan... it still only works with a file path (trustStore parameter). The code prooves it: https://github.com/gradle/gradle/blob/master/subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/DefaultSslContextFactory.java

**Comment by MarkRx** [comment] 2022-04-08 12:32
This still happens in Gradle 7.4.2. Please re-open.

**Comment by guai** [comment] 2022-12-21 07:54
@wolfs pls reopen

**Comment by jbartok** [comment] 2023-04-19 09:30
The issue is in the backlog of the relevant team, but the existence of a workaround makes it non-critical, so it might take a while before a fix is made.

**Comment by ov7a** [comment] 2023-05-22 17:14
Fixed by #25106

**Closed by ov7a** 2023-05-22 17:14 UTC
Labels: a:bug, windows, in:remoting, has:workaround
