### ISSUE TITLE
Gradle should not try to download jars for plugin marker artifacts

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#6155] opened 2018-08-01 08:34 UTC
When using the plugins DSL, Gradle resolves the plugin marker artifact (a pom) first to determine where the actual plugin artifact is. The marker artifact has packaging `pom` and our Maven resolver tries to download the `jar` file when the packaging is `pom` (see https://github.com/gradle/gradle/blob/fd798e764b10e8aedb898757b89124bfffdc660c/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/resolver/MavenResolver.java#L246).

For plugin marker artifacts there will never be `jar` artifacts, so we should not try to resolve them.

Whenever the plugin has been resolved successfully, we do not try to resolve the plugin marker artifact again, so the above issue can only be a problem when resolving the plugin for the first time. It is a problem especially for mirroring the plugin portal, since `404` responses may not be cached by the mirror and therefore the mirrored repository is queried for the marker artifact. If the mirrored repository is unstable, this may cause build failures.

**Comment by oehme** [comment] 2018-08-01 08:54
I honestly don't understand why we'd ever look for a jar when the POM says `<packaging>pom</packaging>`.

**Comment by wolfs** [comment] 2018-08-01 09:02
Me neither. Maybe @bigdaz can shed some light on this?

**Comment by bigdaz** [comment] 2018-08-01 13:52
For background, here's the way Gradle determines which artifacts are part of a Maven module.

Since a POM doesn't explicitly list the artifacts of a Maven module, we use the value of `packaging` to infer this:
1. If it's a [known jar packaging](https://github.com/gradle/gradle/blob/427142e25e46a5ec1e4751bae73ad7ffe0025a91/subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/maven/DefaultMavenModuleResolveMetadata.java#L55) we will assume there is a single 'jar' artifact. We don't check, and if this is incorrect we will fail when resolving the artifacts.
2. If it's an unknown packaging (eg `war`), we first check to see if there's an artifact with an extension matching the `packaging` (eg `module-1.0.war`). If that doesn't exist, we assume there's a `jar`artifact (we don't check and will fail resolving artifacts if this is wrong).
3. Finally, if it's a `pom` packaging, we first check to see if there's a `jar` artifact. If that doesn't exist, we assume there is _no_ artifact for the module.

This behaviour was inherited from Ivy. I presume there are examples of published POM files with `packaging == 'pom'` and a `jar` artifact. If we didn't do the check, then we would not include the artifact when resolving. This would be a breaking change.

**Comment by oehme** [comment] 2018-08-01 15:04
I think we should do that breaking change for 5.0. A `pom` packaging explicitly means "there is no other artifact", so we shouldn't look for one.

**Comment by bigdaz** [comment] 2018-08-01 16:02
I think we should put this change through a deprecation cycle.

**Comment by oehme** [comment] 2018-08-01 16:18
Such an artifact would not be resolved by Maven, so I would consider this extra network request a bug that doesn't require a deprecation. But it's up to you. Meanwhile we can make the portal return 404 immediately when seeing such a request.

**Comment by bigdaz** [comment] 2018-08-01 16:45
> Such an artifact would not be resolved by Maven, so I would consider this extra network request a bug that doesn't require a deprecation.

If that's the case (Maven won't resolve the jar), then I agree with you. I assumed that Ivy did things this way in order to reproduce the Maven behaviour.

If we can fix the portal, then as you say it will aid older version of Gradle as well. There's also the option of treating plugin-marker resolution as a special case, which we could do immediately.

**Comment by melix** [comment] 2018-09-14 09:35
Wouldn't it be possible to depend on the `@pom` artifact directly, instead? This would let us keep the existing, somehow controversial behavior, while avoiding to get the jars in the plugin marker case?

**Comment by melix** [comment] 2018-09-14 10:03
Ok so after a chat with @eskatos I think I understand better the problem and we have found a solution.

The issue is triggered by the fact that we construct a marker dependency, and if the dependency exists, we actually add it directly to the plugin classpath, and rely on the fact it has a transitive dependency on the real plugin to resolve. The consequence is that when we resolve the plugin classpath, we have the marker on it, and therefore we will try to get its artifacts, including the jar.

Now, we think we can be smarter: in `ArtifactRepositoriesPluginResolver`, the method that checks if the plugin exists has access to the `ResolutionResult` of the marker query. As such, it also has access to the transitive dependencies of the marker. So, instead of adding a dependency on the marker, we can extract the coordinates of the plugin from the transitive dependency, and add it instead of the marker.

@eskatos mentioned that this should be done with care because there are cases were the marker doesn't exist and is an explicit target coordinate, in which case we should add it directly.

**Comment by oehme** [comment] 2018-09-14 10:14
It would still be good to also fix up the portal so it immediately returns `false` when getting a query for a marker JAR. That way all old Gradle versions will also be fixed.

**Comment by oehme** [comment] 2018-09-14 13:53
> It would only make the server respond faster.

Well "only" is understatement here, JCenter times out on a regular basis for those requests.

**Comment by eskatos** [comment] 2018-09-25 08:05
Gradle 5.x won't try to download plugin marker artifacts, see #6774

**Closed** 2018-09-25 08:06 UTC
Labels: dev-productivity, in:dependency-management
