### ISSUE TITLE
List and ListProperty @Options do not work (at least from Kotlin)

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#11613] opened 2019-12-07 02:34 UTC
I tried various variants in a Kotlin task in Gradle 5.6.3 to get this working, but none worked. The option is shown in the help for the task, but it does not accept any values, no matter whether an option values method is present or not.
Some variants I tried:
```kotlin
@get:Option(
        option = "foo",
        description = "The foo"
)
var foo: java.util.ArrayList<String> = java.util.ArrayList()
```
```kotlin
@get:Option(
        option = "foo",
        description = "The foo"
)
abstract var foo: List<String>
```
```kotlin
@get:Option(
        option = "foo",
        description = "The foo"
)
abstract var foo: List<Foo>

enum class Foo { BAR, BAZ, BAM }
```
```kotlin
@get:Option(
        option = "foo",
        description = "The foo"
)
abstract val foo: ListProperty<String>
```

**Comment by SUPERCILEX** [comment] 2020-02-22 21:35
You're applying the annotation to getters, try `set:Option` 🙂

**Comment by Vampire** [comment] 2020-02-23 23:25
Ah, right for case 2 and 3, thanks, I missed that it is supposed to be on the setter, as for normal `Property<String>`, it works as expected on the getter.
But at least it should not be shown in the help-command output if it is not effective when it is on the getter instead of the setter.

For the last case, the `ListProperty` though, it will not work, as it is a `val` which has no setter or field.
And even if I change it to `var` which would be anti-pattern anyway, it will not work, as you then get an error that the value cannot be casted go `ListProperty`.

**Comment by SUPERCILEX** [comment] 2020-02-23 23:29
Good point, it'd be nice if it worked with properties.

**Comment by Vampire** [comment] 2021-03-11 22:30
Still the same with 6.8.3.
Option 2 and 3 are in the help though it does not work as the annotation is on the gettet instead of on the setter,
Option 4 is not accepting arguments and if applied to the setter is said to not be castable.

**Comment by jbartok** [comment] 2023-05-25 14:29
Duplicate of 
* https://github.com/gradle/gradle/issues/10517

**Closed by jbartok** 2023-05-25 14:29 UTC
Labels: a:bug, in:provider-api

**Comment by Vampire** [comment] 2023-05-25 14:53
For point 4, the `ListProperty` case, I agree it is a duplicate.

But that the options for cases 2 and 3 are added to the help output while they cannot be used is a separate issue.
Would it make sense to reopen this issue and handle just that here @jbartok?

**Comment by jbartok** [comment] 2023-05-29 07:55
Ok. Would you mind setting up a fresh issue with just those cases? I think it would be less confusing than reopening this one with all its baggage. We can then just link to this one, for the sake of completeness.

**Comment by Vampire** [comment] 2023-05-29 17:16
Not at all: #25215
