### ISSUE TITLE
Override config when publish

### ISSUE THREAD

**Issue by DorisGM** [gradle/gradle#21045] opened 2022-06-20 04:34 UTC
### Expected Behavior
When I defined multiple MavenPublication， I publish one won‘t be override by another MavenPublication

### Current Behavior
First Maven Publication（example stable） always be override by second maven publish

### Context
```
apply plugin: 'maven-publish'

def GROUP_ID = 'com.test'
def VERSION_NAME = '1.0'
def ARTIFACT_ID = "Xdd"

 
publishing {
    publications {
        //开发环境


        //预发布环境
        stable(MavenPublication) {
            groupId = GROUP_ID 
            artifactId = ARTIFACT_ID 
            version = VERSION_NAME
            versionMapping {
                allVariants {
                    fromResolutionResult()
                }
            }
            println version + "------------------------2"
            artifact "build/outputs/aar/x-debug.aar"
            pom.withXml {
                def dependenciesNode = asNode().appendNode("dependencies")
                configurations.implementation.allDependencies.forEach() {
                    Dependency dependency ->
                        if (dependency.version != "unspecified" && dependency.name != "unspecified") {
                            def dependencyNode = dependenciesNode.appendNode('dependency')
                            dependencyNode.appendNode('groupId', dependency.group)
                            dependencyNode.appendNode('artifactId', dependency.name)
                            dependencyNode.appendNode('version', dependency.version)
                        }
                }
            }
        }

        dev(MavenPublication) {
            groupId = GROUP_ID
            artifactId = ARTIFACT_ID
            VERSION_NAME += '-SNAPSHOT'
            version = VERSION_NAME
            println version + "------------------------1"
            artifact "build/outputs/aar/x-debug.aar"
            pom.withXml {
                def dependenciesNode = asNode().appendNode("dependencies")
                configurations.implementation.allDependencies.forEach() {
                    Dependency dependency ->
                        if (dependency.version != "unspecified" && dependency.name != "unspecified") {
                            def dependencyNode = dependenciesNode.appendNode('dependency')
                            dependencyNode.appendNode('groupId', dependency.group)
                            dependencyNode.appendNode('artifactId', dependency.name)
                            dependencyNode.appendNode('version', dependency.version)
                        }
                }
            }
        }
    }
    repositories {
        maven {
            def releasesRepoUrl = "xxxxxxxx"
            def snapshotsRepoUrl = "xxxxxx"
            url = VERSION_NAME.endsWith('SNAPSHOT') ? snapshotsRepoUrl : releasesRepoUrl
            println version 
            credentials {
                username 'xxxxx
                password 'xxxx'
            }
        }
    }
}

```

### Steps to Reproduce 
when  I publish by publishStablePublicationToMavenRepository.  I found VERSION_NAME  is 1.0.snapshot. This is wrong for me . It  should be 1.0. 
why i only publish one ,but  stable and dev both run?
### Your Environment
Android studio Chipmunk
gradle version is 7.0.2

**Comment by donat** [comment] 2022-06-20 14:39
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

This issue will be closed after 7 days, unless you can provide more information.


It seems like you overwrite `VERSION_NAME` in the configuration of the second publication:
```
VERSION_NAME += '-SNAPSHOT'
```

**Comment by DorisGM** [comment] 2022-06-21 09:49
I uploaded this project . 
[TestGradlePublish.zip](https://github.com/gradle/gradle/files/8947686/TestGradlePublish.zip)

My point is  why i execute 'publishStablePublicationToMavenRepository' gradle task, it seems all of publications "stable" and "dev" be execute.  You can see picture to see logs.  I added some println .  
![maven-publish](https://user-images.githubusercontent.com/22267767/174769481-558fe7d3-8d1f-47f5-8623-101fe09cfda0.png) 

I only want to execute stable without 'dev'.  And it only print  out " $version + "------------------------2"

Because of  I want to decide the repository url according to the version number.  If both of "stable" and "dev" be run when i execute "publishStablePublicationToMavenRepository"  Version_name will always 1.0-SNAPSHOT
It's not what I want.

**Comment by DorisGM** [comment] 2022-07-04 03:54
Hi team，How about this issue？

**Comment by big-guy** [comment] 2024-01-02 17:34
We think the way you're configuring the publications may be the issue because you're modifying shared variables between them.

We're going to close this issue, but please open a new one if you have a simpler reproducer.

**Closed by big-guy** 2024-01-02 17:34 UTC
Labels: in:publishing-plugins, a:bug, in:configuration-model, @support
