### ISSUE TITLE
Expected ResolvedDependencyResult but found DefaultUnresolvedDependencyResult when trying to sync

### ISSUE THREAD

**Issue by sjaloomconnect** [gradle/gradle#12723] opened 2020-04-05 21:30 UTC
I am using android studio 3.6.2 and gradle 6.3-all, I tried to sync my project and got the follow error:

    Expected org.gradle.api.artifacts.result.ResolvedDependencyResult but found org.gradle.api.internal.artifacts.result.DefaultUnresolvedDependencyResult

No idea how to fix this.

**Comment by yesersin** [comment] 2020-04-06 14:25
yes, i get an error too.

Does anyone have a solution proposal?

**Comment by sjaloomconnect** [comment] 2020-04-07 12:23
Is there a solution? As I need to deliver my app and its frustrating not to be able to do so.

**Comment by LiamScriven** [comment] 2020-04-08 12:55
Also having the same error, no luck fixing it so far

**Comment by sjaloomconnect** [comment] 2020-04-11 18:57
Ok, somehow I managed to fix it. I exited Android Studio and removed the .idea and .gradle folders and the .iml file from the project folder. Then I run the following command: watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf node_modules/ && npm cache verify && npm install && npm start -- --reset-cache. After that I opened android studio and opened the project file again. Gradle could start and all worked fine again.

**Comment by vicary** [comment] 2020-07-07 09:47
Did `rm -rf node_modules && yarn` and it doesn't work, ended up opening with Android Studio, right-clicking the project name in the *Gradle* window and choose *Refresh Gradle Dependencies*.

I wonder if that is safe for React Native projects because from the logs it appears to do minor upgrades for the dependencies, where React Native is really sensitive and tends to break in the past.

**Comment by omars94** [comment] 2020-07-10 12:26
i am also having same issue
Expected org.gradle.api.artifacts.result.ResolvedDependencyResult but found org.gradle.api.internal.artifacts.result.DefaultUnresolvedDependencyResult

react-native 0.63.0
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

gradle-wrapper.properties
distributionUrl=https://services.gradle.org/distributions/gradle-6.1.1-all.zip

build.gradle
classpath 'com.android.tools.build:gradle:4.0.0'

**Comment by ntkzwane** [comment] 2020-07-12 09:59
This started happening on my side when I upgraded react-native to `0.63.0`. Got it working by deleting everything in `$HOME/.gradle` except for the `gradle.properties` file (I tried clearing just the cache but that didn't work).

**Comment by carloscuesta** [comment] 2020-08-03 07:23
I'm also seeing this on our pipeline and we hadn't changed anything. Friday was working perfectly, now we're getting the error that is stated on the issue

**Comment by giftiiconhari** [comment] 2020-08-10 13:12
Expected org.gradle.api.artifacts.result.ResolvedDependencyResult but found org.gradle.api.internal.artifacts.result.DefaultUnresolvedDependencyResult
unable to find the solution please help me

**Comment by NiranjanShah** [comment] 2020-09-03 11:32
Facing same issue, can any one assist please

**Comment by rcidt** [comment] 2021-12-08 20:06
Over a year later, I am now also getting this issue. Any news?

**Comment by reactnativedeveloper013** [comment] 2021-12-11 09:25
Expected org.gradle.api.artifacts.result.ResolvedDependencyResult but found org.gradle.api.internal.artifacts.result.DefaultUnresolvedDependencyResult

Any news? i am facing same issue. please help me

**Comment by jemoav** [comment] 2021-12-19 12:02
same here

**Comment by FansPro** [comment] 2022-03-23 02:20
This issue still exist.

**Comment by Davete0302** [comment] 2022-05-10 03:57
Any solution to this?

**Comment by Nirodha26** [comment] 2022-05-11 02:50
Getting this issue and mentioned suggestions didn't work. Any solution for this?

**Comment by Dung1128** [comment] 2022-05-11 06:53
This issue still exist. Any solution for this?

**Comment by riyansghrt** [comment] 2022-05-12 14:42
any solution for this ?

**Comment by glorynguyen** [comment] 2022-05-13 03:57
This issue also occurs on my React Native app 
I can build successful last week but yesterday I can't build.

React Native: 0.59.9
Gradle version: 5.6.2
Command run: `react-native run-android`
Log:

```
FAILURE: Build failed with an exception.

* What went wrong:
Expected org.gradle.api.artifacts.result.ResolvedDependencyResult but found org.gradle.api.internal.artifacts.result.DefaultUnresolvedDependencyResult
```
My workaround solution:
I ran command `npx react-native run-android` instead of `react-native run-android` then can build success. Hope it help in your case

**Comment by Davete0302** [comment] 2022-05-13 09:54
What I did was update my gradle.wrapper and com.android.tools.build:gradle to a higher version.
For reference:
```
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip
classpath 'com.android.tools.build:gradle:4.1.0'
```

**Comment by Talha8840** [comment] 2022-05-13 18:41
> 

Doesnt works for me

**Comment by FansPro** [comment] 2022-06-27 07:42
Update Node version to 18 may resolve this issue. Delete the app/build file, rebuild the project. 
In my project cased by the library lower version(eg: "react-native-camera -> 2.10.1") and react-native version: 0.59.8.

**Comment by ChurikiTenna** [comment] 2022-09-30 06:22
I found literaly no information about this.

**Comment by mahmood-heja** [comment] 2022-11-16 13:43
I have same issu on flutter and resolved by upgrade gralde version 

build.gradle

    classpath 'com.android.tools.build:gradle:7.1.0'

gradle.warpper.properties

    distributionUrl=https\://services.gradle.org/distributions/gradle-7.5.1-bin.zip

**Comment by swithun92** [comment] 2022-11-29 13:22
I've noticed this error a couple of times after updating packages that have conflicts. If you've recently updated one of your packages with the --legacy-peer-deps or --force flag try downgrading that package back to a version you know was safe, if it works again you will need to do the upgrade that package the proper way. As others have found the proper way may involve upgrading other packages.

**Comment by PCSIDev** [comment] 2023-01-28 18:20
I feel very sad for Android community. TBH it sucks because no concrete info on error. Pity stuff man.

**Comment by ov7a** [comment] 2023-09-20 12:12
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

Sorry for the late reply. We're having trouble reproducing this issue and given its age, we believe that upgrading to the latest versions of Gradle and Android Studio would fix it.

**Closed by ov7a** 2023-09-20 12:12 UTC
Labels: a:bug, to-triage

**Comment by wahidshadab** [comment] 2024-12-16 05:19
+1
Expected org.gradle.api.artifacts.result.ResolvedDependencyResult but found org.gradle.api.internal.artifacts.result.DefaultUnresolvedDependencyResult
