### ISSUE TITLE
Findbugs support for Java 9

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#720] opened 2016-10-19 13:00 UTC
The first preview of Findbugs supporting Java 9 has just been released: https://github.com/findbugsproject/findbugs/releases/tag/3.1.0_preview1

All of our code quality plugins (including the FindBugs plugins) [resolve the FindBug dependency as external dependency](https://github.com/gradle/gradle/blob/master/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/FindBugsPlugin.java#L96) via GAV. Currently, the FindBugs version 3.1.0 (supporting Java 9) is not available on Maven Central/JCenter yet. I [asked about an ETA for the publish date](https://github.com/findbugsproject/findbugs/issues/105#issuecomment-225896443) but it looks like it is going to take a while as it also relies on ASM 6 and BCEL 6 preview builds. 

At the moment I don't think it's worth trying out the SNAPSHOT version of FindBugs as it would require additional changes to the FindBugs plugin to be able to point to local library files. Also we'd need to provide those libraries with the Gradle distribution which we definitely do not want to do.

As part of this FindBugsIntegrationTest needs to be fixed for Java 9

**Comment by wolfs** [comment] 2016-11-06 13:37
Looks like this could never happen: [I'm really sorry to say, but FindBugs project in its current form 
is dead.](https://mailman.cs.umd.edu/pipermail/findbugs-discuss/2016-November/004321.html)

**Comment by jsotuyod** [comment] 2016-11-06 14:36
I'm the one that started that thread on fb-discuss, and I'm also the one [pushing forward a hard fork, called SpotBugs](https://mailman.cs.umd.edu/pipermail/findbugs-discuss/2016-November/004330.html). The community is already getting behind it, and even devs from the original FindBugs team [are already onboard](https://github.com/orgs/spotbugs/people)

The fork vows to keep binary compatibility for at least a logical timeframe for people and integrations to switch before even considering breaking changes. So once we make a release, just swapping the dependency should be enough.

Right now, our priority is sorting out naming issues / website, and getting together a 3.1.0 release with proper Java 8 and Java 9 support (some detectors still don't report on lambdas, 'though they don't break when finding them). Once ready we will publish in `mavenCentral` and `jcenter`, under `com.github.spotbugs:spotbugs`, and we will gladly help you integrate.

**Comment by eriwen** [comment] 2016-11-06 22:55
Nice @jsotuyod!

**Comment by huxi** [comment] 2016-11-07 19:52
There's also https://github.com/amaembo/huntbugs
I don't know if spotbugs/huntbugs collaborate in some way. Maybe @jsotuyod and @amaembo can chime in about this. Just mentioning it for the sake of completeness.

**Comment by jsotuyod** [comment] 2016-11-07 20:02
HuntBugs is @amaembo's personal project (he is an inactive FindBugs team member). It's not a fork, but a complete rewrite upon a different set of libraries, and is therefore incompatible with existing integrations / plugins. It has been able to reproduce ~40% of FindBugs' detectors. It's development is dormant at the moment as he is focusing his efforts on writing detectors for IntelliJ IDEA's analyzer. There are no concrete plans AFAIK to resume development in the short-term.

All this is taken from @amaembo's email on that same topic: https://mailman.cs.umd.edu/pipermail/findbugs-discuss/2016-November/004324.html

**Comment by bmuschko** [comment] 2017-07-18 12:43
I [asked about this again](https://github.com/findbugsproject/findbugs/issues/105#issuecomment-316046596) it looks like FindBugs will never support Java 9. SpotBugs is the replacement. I am going to close this issue. If FindBugs should ever support Java 9 then we can reopen this issue.

**Closed by bmuschko** 2017-07-18 12:43 UTC
Labels: a:feature, in:findbugs-plugin, in:modular-java, is:blocked
