### ISSUE TITLE
OAuth-Support for maven repositories

### ISSUE THREAD

**Issue by paulwellnerbou** [gradle/gradle#5571] opened 2018-05-29 19:41 UTC
Maven repositories which require Authentication can be used with gradle, but this just works with Basic Authentication and AWS S3. This works even with Bitbucket used as maven repository, but not for others, such as Gitlab.

I think OAuth support (or a generic HTTP header Authentication) would be a nice feature.

### Expected Behavior

Similar to maven, which supports this already, I expect something similar to this to work:

```
repositories {
    maven {
        url "<URL>"
        credentials(HttpHeaderCredentials) {
            header { Authorization: "Bearer <OAuth2 token>" }
        }
    }
```

If this implementation is generic, it will support any HTTP headers sent as Authorization.

### Current Behavior

Currently only Basic Auth and AWS S3 Auth is supported.

### Context

I was trying to (mis-) use a Gitlab repository as maven repository, similar as described [here for bitbucket](https://jeroenmols.com/blog/2016/02/05/wagongit/) or [here using maven](https://ubs-soft.com/maven-private-repository-in-gitlab/). But this does not seem to be possible, only Basic Auth and S3 are supported, [as far as I found out](https://docs.gradle.org/current/userguide/repository_types.html).

I tried to get [help on stackoverflow](https://stackoverflow.com/questions/50522734/maven-repository-with-oauth2-or-any-other-http-header-authentification) and [Gradle forums](https://discuss.gradle.org/t/maven-repository-with-oauth2-or-any-other-http-header-authentification/27067), without success so far.

Independently of my plans on using Gitlab or not, I think OAuth support for repositories might be a feature worth to develop for Gradle. Or, more generally, support for any HTTP headers.

I would like to start working on this. I suspect it might be difficult if not impossible to create a plugin solving this, so I will have a look at the gradle code itself. Maybe you can give me a hint where to start, which classes to look at, which tests to run and extend?

Thanks!

**Comment by marcphilipp** [comment] 2018-05-30 10:19
Can Gitlab generate application specific passwords or personal access tokens?

**Comment by paulwellnerbou** [comment] 2018-05-30 10:40
@marcphilipp, Gitlab can generate access tokens (OAuth2 and personal access tokens), [see here](https://docs.gitlab.com/ee/api/#personal-access-tokens).

**Comment by marcphilipp** [comment] 2018-05-30 10:46
Thanks! But they seem to be using a custom header instead of basic authentication or even the standard `Authorization` header. I was hoping you could use it as a workaround as it would have worked for GitHub.

**Comment by paulwellnerbou** [comment] 2018-05-30 10:53
Yes, that's what I was hoping, too. And after a bit of research I did not find any workaround. For my use case the easiest solution would be to switch to bitbucket or AWS. But I think it might be useful for Gradle users to add an authentication scheme which can add headers to the request.

I digged and debugged a bit into the gradle code and landed in `HttpClientConfigurer`, where the apache httpclient is configured.

So my first approach would be to add a new class extending from `Credentials` (works so far already), and create a custom authentication theme similar to [this documentation for httpclient-3](http://hc.apache.org/httpclient-3.x/authentication.html#Custom_authentication_scheme), which is able to add headers to requests.

**Comment by marcphilipp** [comment] 2018-05-30 11:01
Sounds good to me! Beware the supported `org.gradle.api.credentials.Credentials` are currently hardcoded in a few places, e.g.

https://github.com/gradle/gradle/blob/8a7b8ea7bfd2c38689c8fa339c66485f610c10a9/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/AuthenticationSupporter.java#L133-L151

**Comment by paulwellnerbou** [comment] 2018-05-30 11:26
Thanks, @marcphilipp. Yes, I noticed it. I created already another `Credentials` and `Authetication` type copying the class hierarchies of `PasswordCredentials` and `BasicAuthentication`. This works, and the type is successfully initialized using

```
    maven {
        credentials(HttpHeaderCredentials) {
            ...
        }
        url "..."
    }
```

Next step would be to implement another authentication scheme for apache's httpclient. I will do this separated from gradle in a separate library and use it inside gradle.

**Comment by paulwellnerbou** [comment] 2018-06-01 13:33
Just created a pull request with my first approach. I would need a bit of support regarding the test code.

**Comment by paulwellnerbou** [comment] 2018-06-04 11:16
@marcphilipp, is there any chance to get a bit of help for the test code? Or do you know who I could contact?

**Comment by marcphilipp** [comment] 2018-06-05 08:50
@paulwellnerbou Thanks for the ping, I'll take a look at your PR later today.

**Comment by paulwellnerbou** [comment] 2018-06-11 21:03
@marcphilipp, another ping from my side, sorry.
Any remarks on my changes?

**Comment by olsemv** [comment] 2018-06-28 15:11
I am very interested in this issue.  I have been following the progress for the last several weeks.  I don't want to sound impatient, but may I ask how the development is going?  I would be happy to be an early adopter or tester if you need one.  Thanks.

**Comment by paulwellnerbou** [comment] 2018-06-29 07:10
Same for me. @marcphilipp: Any chance to get this reviewed?

**Comment by paulwellnerbou** [comment] 2018-06-29 07:11
@olsemv: If you check out this branch, you can test it already. Just build it and use the built distribution to build your gradle project.

**Comment by paulwellnerbou** [comment] 2018-06-29 15:36
@marcphilipp: Thanks very much. I followed your remarks so far and added documentation.

**Comment by paulwellnerbou** [comment] 2018-07-03 06:14
@marcphilipp, another ping from here. I changed the code where you requested changes added a paragraph to the documentation.

**Comment by paulwellnerbou** [comment] 2018-07-03 12:13
@marcphilipp, thanks again for the review. Hope I got all this time.

**Comment by olsemv** [comment] 2018-07-09 19:15
I am trying to access artifacts in a Microsoft Team Foundation Server (TFS) Maven repository.  I am using a personal access token generated by TFS.

I checked out this branch as of 2 July 2018 and built it.  I then used the generated gradle to build a test app with the following in the build.gradle file.

`repositories {
    maven {
	url "https://<host>/tfs/DefaultCollection/_packaging/Java/maven/v1"
        credentials(HttpHeaderCredentials) {
            header "Private-Token: <TFS generated Personal Access Token>"
        }
        authentication {
            header(HttpHeaderAuthentication)
        }
    }
}
`

I get the response:
`Received status code 401 from server: Unauthorized`

Am I using this new functionality incorrectly?

**Comment by paulwellnerbou** [comment] 2018-07-10 07:47
@olsemv, no, the first proposal was changed, take a look at the generated documentation (or the tests) on how to use it.

**Comment by olsemv** [comment] 2018-07-10 16:11
Updated the documentation in this branch and tried the following with the same result.

```
repositories {
	maven {
		url "https://<host>/tfs/DefaultCollection/_packaging/Java/maven/v1"
		credentials(HttpHeaderCredentials) {
			name = "Private-Token"
			value = "<TOKEN>"
		}
		authentication {
			header(HttpHeaderAuthentication)
		}
	}
}
```

Is this correct?

**Comment by marcphilipp** [comment] 2018-07-11 06:37
@olsemv Does TFS use the `Private-Token` header?

**Comment by paulwellnerbou** [comment] 2018-07-14 06:59
@olsemv, it does not seem so, as I can read here (https://docs.microsoft.com/en-us/vsts/package/get-started-maven?view=vsts), TFS uses basic authentification. Are you able to access your URL with cURL?

```shell
curl -h "Private-Token: <TOKEN>" https://<host>/tfs/DefaultCollection/_packaging/Java/maven/v1
```

**Comment by olsemv** [comment] 2018-07-16 15:34
I tried using cURL with the TFS-generated Personal Access Token as you suggested, but get the following error:
`Resource not available for anonymous access. Client authentication required.`

It is the same error I get if I remove the header information altogether.

cURL does work if I use the maven authorization token as such:
`curl -H "Authorization: <TOKEN>" "https://<host>/tfs/DefaultCollection/_packaging/Java/maven/v1"`

The maven authorization token does not work in the new gradle.

**Comment by paulwellnerbou** [comment] 2018-07-16 15:53
If TFS's header is `Authorization` and not `Private-Token`, why do you try to use `Private-Token`? That's an example which works for example for Gitlab.

Did you try
```
repositories {
	maven {
		url "https://<host>/tfs/DefaultCollection/_packaging/Java/maven/v1"
		credentials(HttpHeaderCredentials) {
			name = "Authorization"
			value = "<TOKEN>"
		}
		authentication {
			header(HttpHeaderAuthentication)
		}
	}
}
```
This would be the equivalent to your given cURL example.

**Comment by paulwellnerbou** [comment] 2018-07-16 18:03
@olsemv, thanks for trying it again. Very good to know, that this works with TFS as well. So we have at least two more systems supported in Gradle now: TFS and Gitlab.

**Comment by sberyozkin** [comment] 2018-07-19 09:40
Hi All, when can this fix make it into the next Gradle 4.x release ? Thanks, Sergey

**Comment by marcphilipp** [comment] 2018-07-19 10:49
@sberyozkin I'll take care of merging the PR for this issue so it will be in 4.10.

**Comment by sberyozkin** [comment] 2018-07-19 14:41
Nice, thanks :-)

**Closed** 2018-07-20 06:41 UTC
Labels: a:feature, from:contributor, in:dependency-management

**Comment by olsemv** [comment] 2018-09-04 17:40
I just downloaded the recently released 4.10.  It appears this functionality is not working as it was in the pre-release version.  Did this modification get included into 4.10 as planned?

**Comment by paulwellnerbou** [comment] 2018-09-05 06:32
@olsemv: Works for me perfectly. What's the problem?

**Comment by olsemv** [comment] 2018-09-05 15:51
Sheesh - sorry!  I forgot to restart my console window after modifying the environment variable to point to the new version of gradle.  It works perfectly.  Thanks again.

**Comment by CommanderTvis** [comment] 2019-01-12 15:37
> If TFS's header is `Authorization` and not `Private-Token`, why do you try to use `Private-Token`? That's an example which works for example for Gitlab.
> 
> Did you try
> 
> ```
> repositories {
> 	maven {
> 		url "https://<host>/tfs/DefaultCollection/_packaging/Java/maven/v1"
> 		credentials(HttpHeaderCredentials) {
> 			name = "Authorization"
> 			value = "<TOKEN>"
> 		}
> 		authentication {
> 			header(HttpHeaderAuthentication)
> 		}
> 	}
> }
> ```
> This would be the equivalent to your given cURL example.

How can I use it in Kotlin DSL?

**Comment by mikemike396** [comment] 2019-02-28 19:38
Has anyone tried this with Github as the Maven repo yet?

I am getting unable to resolve dependence 

```
        maven {
            url "https://api.github.com/repos/COMPANYNAME/REPONAME/contents/repo"
            credentials(HttpHeaderCredentials) {
                name = "Authorization"
                value = "KEY"
            }
            authentication {
                header(HttpHeaderAuthentication)
            }
        }
```

**Comment by paulwellnerbou** [comment] 2019-03-01 09:42
@mikemike396 With Github I didn't, I tried it with Gitlab only. Is Github offering a similar authorization method? If yes (e.g. basic auth) it should work.

What is the exact (and long) error message?

**Comment by mikemike396** [comment] 2019-03-01 16:45
> @mikemike396 With Github I didn't, I tried it with Gitlab only. Is Github offering a similar authorization method? If yes (e.g. basic auth) it should work.
> 
> What is the exact (and long) error message?

Looks like 403 error. Log attached. 

[GradleError.txt](https://github.com/gradle/gradle/files/2920311/GradleError.txt)

![image](https://user-images.githubusercontent.com/14999806/53652594-49b4a280-3c17-11e9-8422-df866924c7f0.png)

![image](https://user-images.githubusercontent.com/14999806/53652683-7a94d780-3c17-11e9-93d2-b0b797528cf6.png)

**Comment by mikemike396** [comment] 2019-03-01 19:14
Update. I believe I have it connected to Github correctly now, but I am getting a new error 

I tried removing any BOM in front of the XML tag, and made sure there are no hidden characters. Any ideas? 

"[Fatal Error] librarywithpublishmavenlocalviagradle-1.0.pom:2:1: Content is not allowed in prolog."

`Caused by: org.xml.sax.SAXParseException; systemId: file:/Users/username/.gradle/caches/modules-2/files-2.1/com.companyName/librarywithpublishmavenlocalviagradle/1.0/7cfdf93f5300e14876fb1b5b19000dc975d02228/librarywithpublishmavenlocalviagradle-1.0.pom; lineNumber: 2; columnNumber: 1; Content is not allowed in prolog.
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser.PomReader.parseToDom(PomReader.java:255)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser.PomReader.access$100(PomReader.java:59)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser.PomReader$2.transform(PomReader.java:141)
`

Log: [NewGradleError.txt](https://github.com/gradle/gradle/files/2920755/NewGradleError.txt)
