### ISSUE TITLE
Native project without sources has UP-TO-DATE task status instead of NO-SOURCE

### ISSUE THREAD

**Issue by pioterj** [gradle/gradle#1962] opened 2017-05-08 11:20 UTC
Native project without source code has `UP-TO-DATE` task status instead of `NO-SOURCE`. The current behavior is misleading, inconsistent and reduces usability of build scans.

### Expected Behavior
Compilation and linking of native source code should be marked as NO-SOURCE when there's no source code.

### Current Behavior
All tasks are marked UP-TO-DATE.

### Steps to Reproduce (for bugs)
- ` mkdir native-executable`
- `cd native-executable`
- `mkdir -p src/main/cpp` (optional, the problem exists also without it)
- Add `build.gradle` with the following content:

```
apply plugin : 'cpp' // or 'c'

model { 
    components {
        main(NativeExecutableSpec)   
    }
}
```

- Run `gradle build`
- All tasks are UP-TO-DATE

### Your Environment
- Tested on Gradle 3.5
- Build scan URL:  https://gradle.com/s/hdqr2tgl62j52

**Comment by pioterj** [comment] 2017-05-08 11:49
What's also different compared to Java projects is that `compileMainExecutableMainCpp` task doesn't even show up unless there is code to compile.

**Comment by big-guy** [comment] 2018-02-21 07:47
Dupe of https://github.com/gradle/gradle-native/issues/76

**Closed by big-guy** 2018-02-21 07:47 UTC
Labels: from:member, in:native-platform
