### ISSUE TITLE
Plugins java-gradle-plugin and mavan-plugin break builds of downstream project in a multi-project build

### ISSUE THREAD

**Issue by mklaehn** [gradle/gradle#2742] opened 2017-08-17 10:28 UTC
When in a multi-project build and using 'maven-publish' in combination with 'java-gradle-plugin' and its way of declaring gradle plugins via the 'gradlePlugin' extension it is impossible to depend on the project declaring the gradle plugins. This actually causes the effect of issue #1061.

### Expected Behavior
Declaration of a downstream project (multi project dependency) is possible without breaking the build.

### Current Behavior
A project with applied plugins 'java-gradle-plugin' and 'maven-publish' in combination with publications and gradlePlugin extensions configured causes the effect of #1061 or more specifically
```
FAILURE: Build failed with an exception.

* Where:
Build file '[...]/build.gradle' line: 7

* What went wrong:
A problem occurred configuring project ':beta'.
> Exception thrown while executing model rule: PublishingPlugin.Rules#publishing(ExtensionContainer)
   > Publishing is not yet able to resolve a dependency on a project with multiple different publications.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
Total time: 0.802 secs
```

with --stacktrace the following stacktrace is printed
```
* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':beta'.
        at org.gradle.execution.TaskNameResolver.discoverTasks(TaskNameResolver.java:100)
        at org.gradle.execution.TaskNameResolver.access$100(TaskNameResolver.java:32)
        at org.gradle.execution.TaskNameResolver$MultiProjectTaskSelectionResult.collect(TaskNameResolver.java:171)
        at org.gradle.execution.TaskNameResolver$MultiProjectTaskSelectionResult.collect(TaskNameResolver.java:181)
        at org.gradle.execution.TaskNameResolver$MultiProjectTaskSelectionResult.collectTasks(TaskNameResolver.java:166)
        at org.gradle.execution.TaskNameResolver.selectWithName(TaskNameResolver.java:55)
        at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:87)
        at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:75)
        at org.gradle.execution.commandline.CommandLineTaskParser.parseTasks(CommandLineTaskParser.java:42)
        at org.gradle.execution.TaskNameResolvingBuildConfigurationAction.configure(TaskNameResolvingBuildConfigurationAction.java:44)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:25)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:54)
        at org.gradle.execution.DefaultTasksBuildExecutionAction.configure(DefaultTasksBuildExecutionAction.java:44)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:25)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:54)
        at org.gradle.execution.ExcludedTaskFilteringBuildConfigurationAction.configure(ExcludedTaskFilteringBuildConfigurationAction.java:47)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.select(DefaultBuildConfigurationActionExecuter.java:36)
        at org.gradle.initialization.DefaultGradleLauncher$3.run(DefaultGradleLauncher.java:175)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:172)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:33)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:112)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:92)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:66)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:79)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:51)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:59)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.HintGCAfterBuild.execute(HintGCAfterBuild.java:44)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:293)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.model.internal.core.ModelRuleExecutionException: Exception thrown while executing model rule: PublishingPlugin.Rules#publishing(ExtensionContainer)
        at org.gradle.model.internal.registry.DefaultModelRegistry.fireAction(DefaultModelRegistry.java:460)
        at org.gradle.model.internal.registry.DefaultModelRegistry.access$700(DefaultModelRegistry.java:41)
        at org.gradle.model.internal.registry.DefaultModelRegistry$RunModelAction.apply(DefaultModelRegistry.java:1154)
        at org.gradle.model.internal.registry.DefaultModelRegistry.transitionTo(DefaultModelRegistry.java:360)
        at org.gradle.model.internal.registry.DefaultModelRegistry.transition(DefaultModelRegistry.java:439)
        at org.gradle.model.internal.registry.DefaultModelRegistry.atStateOrMaybeLater(DefaultModelRegistry.java:203)
        at org.gradle.model.internal.registry.DefaultModelRegistry.atStateOrLater(DefaultModelRegistry.java:190)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.discoverTasks(DefaultTaskContainer.java:212)
        at org.gradle.execution.TaskNameResolver.discoverTasks(TaskNameResolver.java:98)
        ... 66 more
Caused by: java.lang.UnsupportedOperationException: Publishing is not yet able to resolve a dependency on a project with multiple different publications.
        at org.gradle.api.publish.internal.ProjectDependencyPublicationResolver.resolve(ProjectDependencyPublicationResolver.java:51)
        at org.gradle.api.publish.maven.internal.publication.DefaultMavenPublication.addProjectDependency(DefaultMavenPublication.java:120)
        at org.gradle.api.publish.maven.internal.publication.DefaultMavenPublication.from(DefaultMavenPublication.java:111)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:382)
        at org.gradle.internal.metaobject.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:170)
        at org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:96)
        at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.invokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:59)
        at build_bzqgh5dp4617inwberbyjuvf2$_run_closure1$_closure4$_closure5$_closure6.doCall([...]/build.gradle:7)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:70)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
        at org.gradle.api.internal.AbstractPolymorphicDomainObjectContainer.create(AbstractPolymorphicDomainObjectContainer.java:66)
        at org.gradle.api.internal.PolymorphicDomainObjectContainerConfigureDelegate._configure(PolymorphicDomainObjectContainerConfigureDelegate.java:45)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:68)
        at build_bzqgh5dp4617inwberbyjuvf2$_run_closure1$_closure4$_closure5.doCall([...]/build.gradle:6)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:70)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
        at org.gradle.util.ConfigureUtil.configureSelf(ConfigureUtil.java:148)
        at org.gradle.api.internal.AbstractNamedDomainObjectContainer.configure(AbstractNamedDomainObjectContainer.java:74)
        at org.gradle.api.internal.AbstractNamedDomainObjectContainer.configure(AbstractNamedDomainObjectContainer.java:29)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:104)
        at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
        at org.gradle.api.publish.internal.DefaultPublishingExtension.publications(DefaultPublishingExtension.java:48)
        at org.gradle.api.publish.internal.DefaultPublishingExtension_Decorated.publications(Unknown Source)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:382)
        at org.gradle.internal.metaobject.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:170)
        at org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:96)
        at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.invokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:59)
        at build_bzqgh5dp4617inwberbyjuvf2$_run_closure1$_closure4.doCall([...]/build.gradle:5)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:70)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
        at org.gradle.listener.ActionBroadcast.execute(ActionBroadcast.java:39)
        at org.gradle.api.internal.plugins.ExtensionsStorage$DeferredConfigurableExtensionHolder.configureNow(ExtensionsStorage.java:183)
        at org.gradle.api.internal.plugins.ExtensionsStorage$DeferredConfigurableExtensionHolder.get(ExtensionsStorage.java:162)
        at org.gradle.api.internal.plugins.ExtensionsStorage.getByType(ExtensionsStorage.java:77)
        at org.gradle.api.internal.plugins.DefaultConvention.getByType(DefaultConvention.java:113)
        at org.gradle.api.publish.plugins.PublishingPlugin$Rules.publishing(PublishingPlugin.java:79)
        at org.gradle.model.internal.method.WeaklyTypeReferencingMethod.invoke(WeaklyTypeReferencingMethod.java:100)
        at org.gradle.model.internal.inspect.DefaultModelRuleInvoker.invoke(DefaultModelRuleInvoker.java:36)
        at org.gradle.model.internal.inspect.UnmanagedModelCreationRuleExtractor$UnmanagedElementCreationAction.execute(UnmanagedModelCreationRuleExtractor.java:77)
        at org.gradle.model.internal.inspect.ModelRuleExtractor$DefaultExtractedRuleSource$ContextualizedModelAction.execute(ModelRuleExtractor.java:515)
        at org.gradle.model.internal.registry.DefaultModelRegistry$4.run(DefaultModelRegistry.java:455)
        at org.gradle.model.internal.registry.RuleContext.run(RuleContext.java:42)
        at org.gradle.model.internal.registry.DefaultModelRegistry.fireAction(DefaultModelRegistry.java:452)
        ... 74 more
```

### Context
I was attempting to add a project dependency to a project inside the same multi project build that uses the plugin 'java-gradle-plugin' and declares the plugins of the project using the 'gradlePlugin' configuration section inside the build file.

A stripped down example follows
File: settings.gradle
```
rootProject.name = 'test'

include ':alpha'
include ':beta'
```

File: build.gradle
```
allprojects {
    apply plugin: 'java'
    apply plugin: 'maven-publish'
    publishing {
        publications {
            archives(MavenPublication) {
                from components.java
            }
        }
    }
}

project(':alpha') {
    apply plugin: 'java-gradle-plugin'
    gradlePlugin { // (1) problematic configuration
        plugins {
            myPlugin {
                id = 'myPlugin'
                implementationClass = 'com.company.plugins.MyPlugin'
            }
        }
    }
}

project(':beta') {
    dependencies {
        compile project(':alpha') // (2) problematic project dependency
    }
}
```

The use of the configuration marked with (1) and the project dependency marked with (2) cause the build error.

### Steps to Reproduce (for bugs)

Consider the files settings.gradle and build.gradle from above cause the error.
Removing either the configuration section (1) or the project dependency (2) will let the build succeed.
However as the project dependency is intended only removing configuration section (1) is viable and thus preventing the usage of the plugins (intended to publish) in the [plugins DSL](https://docs.gradle.org/4.1/userguide/plugins.html#sec:plugins_block).

### Your Environment
Affected Gradle Versions: from 2.14 onwards (tested up to 4.1)

**Comment by oehme** [comment] 2017-08-17 10:35
Does it work if you exclude your custom `archives ` configuration from the plugin project?

**Comment by oehme** [comment] 2017-08-17 10:37
I'll close this as a duplicate of #1061

**Closed by oehme** 2017-08-17 10:37 UTC

**Comment by mklaehn** [comment] 2017-08-17 10:58
If I exclude the custom archives configuration it does work.

However a publication rarely contains solely the component jar file. Usually there's also a javadoc/groovydoc zip file or an source.zip. In order to do that I have to add them to a publication. What would the name of that non-custom publication be?

**Comment by oehme** [comment] 2017-08-17 11:50
It's called `gradlePlugin`.

**Comment by mklaehn** [comment] 2017-08-17 12:16
Sorry @oehme.

I just checked with the following snipped
```
allprojects {
    tasks.each{task ->
        task.doLast{
            publishing.publications.each{println "Task ${task.path} knows Publication '${it.name}'"}
        }
    }
}
```
and nowhere in the output is a Publication named `gradlePlugin`.

**Comment by oehme** [comment] 2017-08-17 12:53
Sorry my bad, it's `pluginMaven`.

**Comment by mklaehn** [comment] 2017-08-17 13:06
Ok, I can verify it's there. However if that is the default Publication I have to believe what you're telling me as that name is not mentioned in any documentation (dsl, groovydoc, javadoc nor userguide).

All those documentations do is tell the user to add artefacts, customize publication or simply add custom ones. So it's "slightly" inconvenient to - especially in this case - have to know that a) there is a default Publication and b) what it's name is.

**Comment by oehme** [comment] 2017-08-17 13:13
I agree the documentation could be more thorough here. Also, the error message should list the publications it couldn't decide about.

**Comment by mklaehn** [comment] 2017-08-17 13:23
The message in the Failed Build (see Current Behavior in issue text) does not contain such a message. Additionally I just searched the codebase and `pluginMaven` is added by [MavenPluginPublishingRules.java#L66](https://github.com/gradle/gradle/blob/master/subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/plugins/MavenPluginPublishingRules.java#L66). Which really doesn't make it a default Publication per se, and solves why no mention of that Publication is in any of the documentations.

This again brings us to the point that by using the plugin `java-gradle-plugin` on a upstream project (from a project dependency point of view) causes the behavior described in #1061. This also means that this issue might not really be a duplicate.

@oehme, what do you think?

**Comment by oehme** [comment] 2017-08-17 13:44
> The message in the Failed Build (see Current Behavior in issue text) does not contain such a message.

That's why I said it *should* be there, as in we need to fix that.

> This also means that this issue might not really be a duplicate.

There are two publications conflicting for priority, which is what #1061 is about. So this is a duplicate of that issue.

**Comment by mklaehn** [comment] 2017-08-17 14:44
> There are two publications conflicting for priority, which is what #1061 is about. So this is a duplicate of that issue.

A) What does it matter if I have two Publications? (Again) The Documentation has nothing to say against having multiple Publications. 

Quite on the contrary (from [36.2.5. Publishing multiple modules](https://docs.gradle.org/4.1/userguide/publishing_maven.html#sec:publishing_multiple_modules_to_maven)):
> If a project defines multiple publications then Gradle will publish each of these to the defined repositories. ...

This means I must have the ability to declare as many Publication as I want or need in order to achieve my build goal.

B) What does conflicting for priority mean? I can't find a mention that Publications are ranked by some kind of order or in this case - as you mention - priority.

Duplication aside, the effect I have is that once I apply plugins `java-gradle-plugin` and `maven-publish` to Project A it is configured - by the Plugin - in such a way that it will break the configuration phase of a Gradle Build if Project A is declared as a Project Dependency by any other Project in a multi project build. Even worse is that suddenly I have to know the name of a Publication that is mentioned nowhere (except as an implementation detail in the actual source code).

I know you said that the documentation could be better. If you want I can open issues for the points you pointed out so far?

Now, Documentation aside, this leaves us with the restriction of using the (implementation detail) Publication of the plugin to publish my additional artefacts - as you pointed out any other Publications cause the build to break.

That restriction is a bug.

**Comment by oehme** [comment] 2017-08-17 15:15
> What does it matter if I have two Publications?

The problem is simple: How is Gradle supposed to know which publication to use when depending on that upstream project? This is what #1061 is about. Whatever we do to fix that will also fix the problem you are seeing here.

> I know you said that the documentation could be better. If you want I can open issues for the points you pointed out so far?

Please go ahead.
