### ISSUE TITLE
Allow for custom build-init types - similar feature to maven archetypes

### ISSUE THREAD

**Issue by ieugen** [gradle/gradle#13622] opened 2020-06-29 14:29 UTC
Hi, 

I think this would be a nice feature of Gradle for extending build-init to allow for custom, user supplied types. 
I'm referring to  https://docs.gradle.org/current/userguide/build_init_plugin.html  .

### Expected Behavior

When I run `gradle init` I should be able to select a custom build-init type. 
Right now, only the types delivered with Gradle are available: java, java-library, etc.
Gradle will download and execute and the code associated with my custom type. 

The expected results are a new project initialized with the rules defined in my custom type. 

Extend build init to specify the custom init type you want to use:

Example (with suggestion for cli parameters):
`gradle init --type custom com.my.custom.build.type:4.3.1 --repo-url https://central.maven.org`

Running the above command will do the following:
* Download the custom type identified by the id and version given as parameters.
* Cache the result for later use
* Execute the code to create the project structure provided by the custom build-init type

#### Changes

* A new `BuildInitializer` implementation for the custom build-init type
* Documentation updates for the feature

The custom build type is published on existing infrastructure: plugins.gradle.org or maven central or whatever. 
Defaults to plugins.gradle.org ?!

People on gradle slack channel pointed out that we might need to have an open source version of plugin-publish to be able to customize where we push the artifacts ?! 

#### Benefits

* Gradle source code does not increase by a lot. 
* People get a solution for adding their own custom build-init types
* People get the ability to control and evolve the versions of the custom build-init types.
* The solution reuses existing infrastructure for distribution

I imagine that people who will benefit the most are: 
* Trainers who teach Gradle and need a way to bootstrap a specific Gradle project
* Projects that rely on scaffolding for fast bootstrapping

### Current Behavior

When I run `gradle init` I get a list of built-in types. 
No option to extend / use custom.
```
gradle init 
Select type of project to generate:
  1: basic
  2: application
  3: library
  4: Gradle plugin
```

### Context
I would like be be able to provision templates for projects via gradle.
The only tool people should have available is gradle. 
This is very useful in trainings and when bootstrapping new projects that have an opinionated structure.
It's very useful to standardize on a project structure - similar to maven archetypes.

Personally I would like to bootstrap a project for building static websites.

I would like to: `gradle init --type custom --id com.example.static-web:0.3` and Gradle will download the custom build-init type and run it to initialize my project.

Related links
* https://discuss.gradle.org/t/add-new-types-to-build-init-plugin/29497/2 
* https://github.com/gradle/gradle/blob/master/subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/BuildInitializer.java

**Comment by eskatos** [comment] 2020-07-04 07:49
Thanks for the nicely written feature request @ieugen !

Note that `BuildInitializer` is internal and a new public API should be introduced.

This is however a duplicate of https://github.com/gradle/gradle/issues/1686

I'm closing this issue, if you are interested by such feature, please upvote on https://github.com/gradle/gradle/issues/1686 that already has more 👍

**Closed by eskatos** 2020-07-04 07:49 UTC
Labels: a:feature, from:contributor
