### ISSUE TITLE
Can't test code using SLF4J SimpleLoggerFactory in Java 9 / Jigsaw module

### ISSUE THREAD

**Issue by dmolesUC3** [gradle/gradle#6565] opened 2018-08-29 16:58 UTC
### Expected Behavior

- tests should run and pass
- failing that, tests should exit without hanging the Gradle daemon

### Current Behavior

- test execution hangs with the following stacktrace:

```
java.lang.ClassCastException: class org.slf4j.impl.SimpleLoggerFactory cannot be cast to class org.gradle.internal.logging.slf4j.OutputEventListenerBackedLoggerContext (org.slf4j.impl.SimpleLoggerFactory is in module slf4j.simple@1.7.25 of loader 'app'; org.gradle.internal.logging.slf4j.OutputEventListenerBackedLoggerContext is in unnamed module of loader java.net.URLClassLoader @e45f292)
        at org.gradle.internal.logging.slf4j.Slf4jLoggingConfigurer.configure(Slf4jLoggingConfigurer.java:42)
        at org.gradle.internal.logging.config.LoggingSystemAdapter.startCapture(LoggingSystemAdapter.java:54)
        at org.gradle.internal.logging.services.DefaultLoggingManager$StartableLoggingSystem.start(DefaultLoggingManager.java:329)
        at org.gradle.internal.logging.services.DefaultLoggingManager.start(DefaultLoggingManager.java:78)
        at org.gradle.internal.logging.services.DefaultLoggingManager.start(DefaultLoggingManager.java:37)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:83)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:64)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:62)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:67)
```

### Context

Trying to update existing project to run under JDK 11

### Steps to Reproduce (for bugs)

- with JDK 10 or 11:
   - clone the minimal self-contained example project [dmolesUC3/gradle-slf4j-jigsaw](https://github.com/dmolesUC3/gradle-slf4j-jigsaw)
   - from the project root directory, run `./gradlew check`

### Your Environment

```
------------------------------------------------------------
Gradle 4.10
------------------------------------------------------------

Build time:   2018-08-27 18:35:06 UTC
Revision:     ee3751ed9f2034effc1f0072c2b2ee74b5dce67d

Kotlin DSL:   1.0-rc-3
Kotlin:       1.2.60
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          11-ea (Oracle Corporation 11-ea+26)
OS:           Mac OS X 10.13.6 x86_64
```

**Note:** same failure under Java 10 release version, although exception message is less informative.

**Comment by oehme** [comment] 2018-09-12 20:31
Duplicate of #4981

**Closed by oehme** 2018-09-12 20:31 UTC
