### ISSUE TITLE
Jacoco fails due to passing an invalid command-line argument when run in Turkish locale

### ISSUE THREAD

**Issue by trejkaz** [gradle/gradle#8070] opened 2018-12-18 00:23 UTC
### Expected Behavior

Running Gradle under Turkish locale should still pass valid command-line arguments to the jacoco agent.

### Current Behavior

Running Gradle under Turkish locale results in passing "output=fıle", which is invalid.

### Context

I have been experimenting with a Gradle plugin which randomises the environment tests are run under.

The first project I happened to experiment with also happened to be a Gradle plugin project, which had TestKit tests. It turns out that when you run TestKit under Turkish locale, the Gradle it starts is run in the same locale, which exposes this bug. I imagine that there is some kind of workaround where I figure out how it's doing that and try to stop it.

### Steps to Reproduce (for bugs)

* Clone: https://github.com/trejkaz/jacoco-turkish-issue
* Run: `./gradlew -Duser.language=tr -Duser.country=TR --info clean test`

### Your Environment

Gradle 5.0
Java 1.8.0_172
macOS 10.13.6

**Comment by marcphilipp** [comment] 2019-01-02 10:19
@trejkaz Thanks for submitting this issue! I think we should fix this issue in general.

**Comment by marcphilipp** [comment] 2019-01-02 10:19
Duplicate of #1506

**Closed by marcphilipp** 2019-01-02 10:19 UTC
Labels: a:bug, from:contributor, in:tooling-api

**Comment by lobemus** [comment] 2021-03-13 00:10
I have same problem. What can I do?
