### ISSUE TITLE
Support Provider.ifPresent(Consumer<T>)

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#15962] opened 2021-01-28 10:28 UTC
We have some code that uses `if (getOrNull() != null)` to allow for `null` values not to be handled. The code would look a lot better with introducing something akin to `java.util.Optional.ifPresent(Consumer<T>)`.

**Comment by melix** [comment] 2021-05-27 10:25
Duplicate of #13401

**Closed by melix** 2021-05-27 10:25 UTC
Labels: a:feature, in:provider-api
