### ISSUE TITLE
make repositories.maven.credentials(PasswordCredentials::class, "<name>")

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#31390] opened 2024-11-22 20:42 UTC
### Expected Behavior

as an alternative to using the same provider twice

```kts
pluginManagement {
  repositories {
    maven("https://maven.pkg.github.com/xenoterracide/gradle-semver") {
      name = "semver"
      mavenContent {
        includeGroup("com.xenoterracide.gradle.semver")
        includeModule("com.xenoterracide.gradle", "semver")
      }
      credentials(PasswordCredentials::class, "gh")
    }
    gradlePluginPortal()
  }
}
dependencyResolutionManagement {
  repositories {
    maven("https://maven.pkg.github.com/xenoterracide/java-commons") {
      name = "commons"
      mavenContent {
        includeGroupAndSubgroups("com.xenoterracide")
        includeModule("com.xenoterracide", "tools")
      }
      credentials(PasswordCredentials::class, "gh")
    }
```

### Context

instead of doing this or something like this twice

```kts
      credentials {
        val creds = providers.credentials(PasswordCredentials::class, "gh").get()
        username = creds.username
        password = creds.password
      }
```

although this might not be necessary if

```java
credentials(providers.credentials(PasswordCredentials::class, "gh")
```

which I think there might already be a ticket for

**Comment by ljacomet** [comment] 2024-11-27 09:53
This issue will be closed as a duplicate of

* #16432

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

Related:
* #3972
* #30823

**Closed by ljacomet** 2024-11-27 09:53 UTC
Labels: a:feature, to-triage
