### ISSUE TITLE
New i/f o.g.a.r.Report#getRequired() should have default implementation for backwards compatibility

### ISSUE THREAD

**Issue by DPUkyle** [gradle/gradle#11923] opened 2020-01-16 17:36 UTC
I'm working with @KengoTODA on his rewrite of the spotbugs plugin. When I try to instantiate a class compiled against Gradle API 6.0.1 but using 6.1 at runtime, Gradle will fail with: 
```
FAILURE: Build failed with an exception.

* What went wrong:
Method com/github/spotbugs/snom/internal/SpotBugsTextReport.getRequired()Lorg/gradle/api/provider/Property; is abstract
```
### Expected Behavior

Existing code should run with Gradle 6.1.

### Current Behavior

See exception above.

### Context

My suggestion is to use the `default` keyword and provide an implementation to satisfy the contract of `Property<Boolean> getRequired();`.

**Comment by DPUkyle** [comment] 2020-01-16 17:52
The same goes for `Provider<? extends FileSystemLocation> getOutputLocation();`:

```
FAILURE: Build failed with an exception.

* What went wrong:
Method com/github/spotbugs/snom/internal/SpotBugsTextReport.getOutputLocation()Lorg/gradle/api/file/RegularFileProperty; is abstract
```

**Comment by big-guy** [comment] 2020-01-16 17:54
This is a dupe of https://github.com/gradle/gradle/issues/11189

This should be using ObjectFactory: https://github.com/KengoTODA/spotbugs-gradle-plugin-v2/blob/e49acac641ead60537ff08e5c7e33f619da030f5/src/main/groovy/com/github/spotbugs/snom/SpotBugsTask.groovy#L252

We're not going to add default methods for these new methods.  Gradle's runtime decorator adds the implementation already.

**Closed by big-guy** 2020-01-16 17:54 UTC
Labels: a:bug, from:contributor
