### ISSUE TITLE
GradleRunner.withPluginClasspath() does not make plugin classes available in a Kotlin build script even when plugin is applied

### ISSUE THREAD

**Issue by netvl** [gradle/gradle#12284] opened 2020-02-19 22:14 UTC
When you use `GradleRunner.create().withPluginClasspath()`, contrary to expectations, you can't access any classes defined in the plugin within the buildscript under test, even if the plugin is applied, like you can in a regular build (where applying a plugin brings its implementation to the build script classpath automatically).

### Expected Behavior

The following test:

```kotlin
GradleRunner.create()
    .withPluginClasspath()
    .withProjectDir(someDir)
    .withArguments("example")
    .build()
```

and the following build script:

```kotlin
import org.example.gradle.ExampleTask

plugins {
    id("org.example.plugin")
}

tasks.register<ExampleTask>("example") {
    doLast {
        println("Inside example task")
    }
}
```

and the following code in the `org/example/gradle/ExamplePlugin.kt` file:

```kotlin
package org.example.gradle

import org.gradle.api.Project
import org.gradle.api.Plugin
import org.gradle.api.DefaultTask

open class ExamplePlugin: Plugin<Project> {
    override fun apply(project: Project) {
    }
}

open class ExampleTask : DefaultTask() {
}
```

should work and produce the `Inside example task` output.

### Current Behavior

The build invocation fails with an exception:

```
    FAILURE: Build failed with an exception.

    * Where:
    Build file '/private/var/folders/sk/vs171fcx3834w99kbymqt8jr0000gn/T/whatever14212528129363258165/build.gradle.kts' line: 1

    * What went wrong:
    Script compilation errors:

      Line 1: import org.example.gradle.ExampleTask
                         ^ Unresolved reference: example

      Line 7: tasks.register<ExampleTask>("example") {
                             ^ Unresolved reference: ExampleTask

      Line 7: tasks.register<ExampleTask>("example") {
                                                     ^ Type mismatch: inferred type is () -> Unit but Class<TypeVariable(T)!>! was expected

      Line 8:     doLast {
                  ^ Unresolved reference: doLast

    4 errors
```

### Context

I need to test my Gradle plugin, and I wanted to use Kotlin DSL everywhere, so that's how I observe this issue - with Kotlin DSL, it is very hard to avoid imports of classes provided by the plugin with Kotlin, with Groovy this problem might be less apparent but is probably still there.

### Steps to Reproduce 

[testplugin.zip](https://github.com/gradle/gradle/files/4227728/testplugin.zip)

```
> unzip testplugin.zip
> cd testplugin
> ./gradlew check
```

### Your Environment

Gradle 6.2
macOS 10.15.3

**Comment by netvl** [comment] 2020-02-19 23:32
Curiously, it seems that the old approach with manually generating the
```
buildscript {
    dependencies {
        classpath(files(...))
    }
}
```
does not work as well, and fails with exactly the same message. When I run exactly the same build script, without any modifications, via the `./gradlew` command directly, it does work.

**Comment by netvl** [comment] 2020-02-19 23:44
Ok, I think that the culprit is the `debug` mode: the build fails with `withDebug(true)` but works with `withDebug(false)`, so somehow class resolution for Kotlin build scripts is different for debug and non-debug builds. This makes this problem a bit less severe, but still inability to debug integration tests seems quite bad.

**Comment by eskatos** [comment] 2020-02-20 12:17
Yes, the incompatibility with `withDebug(true)` is a known bug https://github.com/gradle/gradle/issues/6862

**Comment by netvl** [comment] 2021-03-14 10:07
Still an issue I believe.

**Comment by ljacomet** [comment] 2021-06-10 09:01
closing as duplicate of #6862

**Closed by ljacomet** 2021-06-10 09:01 UTC
Labels: a:bug, closed:duplicate, in:kotlin-dsl, in:test-kit
