### ISSUE TITLE
Resolution of the configuration was attempted from a context different than the project context seemingly in Gradle

### ISSUE THREAD

**Issue by anuraaga** [gradle/gradle#17355] opened 2021-06-04 05:25 UTC
### Expected Behavior

No deprecation warnings

### Current Behavior

When refreshing a project in IntelliJ (but I can't find any CLI task with similar behavior), I get the warning `Resolution of the configuration :dependencyManagement:detachedConfiguration1 was attempted from a context different than the project context. Have a look at the documentation to understand why this is a problem and how it can be resolved.`

Stack trace looks something like below. I can't find any logic from my own build scripts in the stack trace, it seems to be internal to Gradle. Could still be a configuration issue but don't see anything wrong.

Configuration defined at https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/gradle/java.gradle#L68, we never call `resolve` on it.

```
Unknown:LazyJVM.kt:74 | &nbsp;
-- | --
at&nbsp;org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:596)at&nbsp;org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1900(DefaultConfiguration.java:150)at&nbsp;org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$SelectedArtifactsProvider.getValue(DefaultConfiguration.java:1341)at&nbsp;org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$SelectedArtifactsProvider.getValue(DefaultConfiguration.java:1331)at&nbsp;org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getSelectedArtifacts(DefaultConfiguration.java:1403)at&nbsp;org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.visitContents(DefaultConfiguration.java:1390)at&nbsp;org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.visitContents(DefaultConfiguration.java:499)at&nbsp;org.gradle.api.internal.file.AbstractFileCollection.getFiles(AbstractFileCollection.java:130)at&nbsp;org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getFiles(Unknown Source)at&nbsp;org.gradle.kotlin.dsl.resolver.SourceDistributionResolver$sourceDirs$2.invoke(SourceDistributionProvider.kt:59)at&nbsp;org.gradle.kotlin.dsl.resolver.SourceDistributionResolver$sourceDirs$2.invoke(SourceDistributionProvider.kt:38)at&nbsp;kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)at&nbsp;org.gradle.kotlin.dsl.resolver.SourceDistributionResolver.getSourceDirs(SourceDistributionProvider.kt)at&nbsp;org.gradle.kotlin.dsl.resolver.SourceDistributionResolver.sourceDirs(SourceDistributionProvider.kt:49)at&nbsp;org.gradle.kotlin.dsl.resolver.SourcePathProvider.downloadedSources(SourcePathProvider.kt:72)at&nbsp;org.gradle.kotlin.dsl.resolver.SourcePathProvider.sourceRootsOf(SourcePathProvider.kt:64)at&nbsp;org.gradle.kotlin.dsl.resolver.SourcePathProvider.sourcePathFor(SourcePathProvider.kt:42)at&nbsp;org.gradle.kotlin.dsl.tooling.builders.KotlinScriptTargetModelBuilder.gradleSource(KotlinBuildScriptModelBuilder.kt:428) | &nbsp; | &nbsp; | at&nbsp;org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:596) | &nbsp; | &nbsp; | &nbsp; | at&nbsp;org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1900(DefaultConfiguration.java:150) | &nbsp; | &nbsp; | &nbsp; | at&nbsp;org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$SelectedArtifactsProvider.getValue(DefaultConfiguration.java:1341) | &nbsp; | &nbsp; | &nbsp; | at&nbsp;org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$SelectedArtifactsProvider.getValue(DefaultConfiguration.java:1331) | &nbsp; | &nbsp; | &nbsp; | at&nbsp;org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getSelectedArtifacts(DefaultConfiguration.java:1403) | &nbsp; | &nbsp; | &nbsp; | at&nbsp;org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.visitContents(DefaultConfiguration.java:1390) | &nbsp; | &nbsp; | &nbsp; | at&nbsp;org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.visitContents(DefaultConfiguration.java:499) | &nbsp; | &nbsp; | &nbsp; | at&nbsp;org.gradle.api.internal.file.AbstractFileCollection.getFiles(AbstractFileCollection.java:130) | &nbsp; | &nbsp; | &nbsp; | at&nbsp;org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getFiles(Unknown Source) | &nbsp; | &nbsp; | &nbsp; | at&nbsp;org.gradle.kotlin.dsl.resolver.SourceDistributionResolver$sourceDirs$2.invoke(SourceDistributionProvider.kt:59) | &nbsp; | &nbsp; | &nbsp; | at&nbsp;org.gradle.kotlin.dsl.resolver.SourceDistributionResolver$sourceDirs$2.invoke(SourceDistributionProvider.kt:38) | &nbsp; | &nbsp; | &nbsp; | at&nbsp;kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) | &nbsp; | &nbsp; | &nbsp; | at&nbsp;org.gradle.kotlin.dsl.resolver.SourceDistributionResolver.getSourceDirs(SourceDistributionProvider.kt) | &nbsp; | &nbsp; | &nbsp; | at&nbsp;org.gradle.kotlin.dsl.resolver.SourceDistributionResolver.sourceDirs(SourceDistributionProvider.kt:49) | &nbsp; | &nbsp; | &nbsp; | at&nbsp;org.gradle.kotlin.dsl.resolver.SourcePathProvider.downloadedSources(SourcePathProvider.kt:72) | &nbsp; | &nbsp; | &nbsp; | at&nbsp;org.gradle.kotlin.dsl.resolver.SourcePathProvider.sourceRootsOf(SourcePathProvider.kt:64) | &nbsp; | &nbsp; | &nbsp; | at&nbsp;org.gradle.kotlin.dsl.resolver.SourcePathProvider.sourcePathFor(SourcePathProvider.kt:42) | &nbsp; | &nbsp; | &nbsp; | at&nbsp;org.gradle.kotlin.dsl.tooling.builders.KotlinScriptTargetModelBuilder.gradleSource(KotlinBuildScriptModelBuilder.kt:428)
&nbsp; | &nbsp; | at&nbsp;org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:596) | &nbsp;
&nbsp; | &nbsp; | at&nbsp;org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1900(DefaultConfiguration.java:150) | &nbsp;
&nbsp; | &nbsp; | at&nbsp;org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$SelectedArtifactsProvider.getValue(DefaultConfiguration.java:1341) | &nbsp;
&nbsp; | &nbsp; | at&nbsp;org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$SelectedArtifactsProvider.getValue(DefaultConfiguration.java:1331) | &nbsp;
&nbsp; | &nbsp; | at&nbsp;org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getSelectedArtifacts(DefaultConfiguration.java:1403) | &nbsp;
&nbsp; | &nbsp; | at&nbsp;org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.visitContents(DefaultConfiguration.java:1390) | &nbsp;
&nbsp; | &nbsp; | at&nbsp;org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.visitContents(DefaultConfiguration.java:499) | &nbsp;
&nbsp; | &nbsp; | at&nbsp;org.gradle.api.internal.file.AbstractFileCollection.getFiles(AbstractFileCollection.java:130) | &nbsp;
&nbsp; | &nbsp; | at&nbsp;org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getFiles(Unknown Source) | &nbsp;
&nbsp; | &nbsp; | at&nbsp;org.gradle.kotlin.dsl.resolver.SourceDistributionResolver$sourceDirs$2.invoke(SourceDistributionProvider.kt:59) | &nbsp;
&nbsp; | &nbsp; | at&nbsp;org.gradle.kotlin.dsl.resolver.SourceDistributionResolver$sourceDirs$2.invoke(SourceDistributionProvider.kt:38) | &nbsp;
&nbsp; | &nbsp; | at&nbsp;kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) | &nbsp;
&nbsp; | &nbsp; | at&nbsp;org.gradle.kotlin.dsl.resolver.SourceDistributionResolver.getSourceDirs(SourceDistributionProvider.kt) | &nbsp;
&nbsp; | &nbsp; | at&nbsp;org.gradle.kotlin.dsl.resolver.SourceDistributionResolver.sourceDirs(SourceDistributionProvider.kt:49) | &nbsp;
&nbsp; | &nbsp; | at&nbsp;org.gradle.kotlin.dsl.resolver.SourcePathProvider.downloadedSources(SourcePathProvider.kt:72) | &nbsp;
&nbsp; | &nbsp; | at&nbsp;org.gradle.kotlin.dsl.resolver.SourcePathProvider.sourceRootsOf(SourcePathProvider.kt:64) | &nbsp;
&nbsp; | &nbsp; | at&nbsp;org.gradle.kotlin.dsl.resolver.SourcePathProvider.sourcePathFor(SourcePathProvider.kt:42) | &nbsp;
&nbsp; | &nbsp; | at&nbsp;org.gradle.kotlin.dsl.tooling.builders.KotlinScriptTargetModelBuilder.gradleSource(KotlinBuildScriptModelBuilder.kt:428)
```

### Steps to Reproduce 

Clone https://github.com/open-telemetry/opentelemetry-java-instrumentation and refresh in IntelliJ. Possibly only reproduces with my IntelliJ plugins.

### Your Environment

Build scan URL:
https://scans.gradle.com/s/6qlevbvbkacei

**Comment by mlopatkin** [comment] 2021-06-04 08:44
@anuraaga Could you please provide your IntelliJ version? This is very likely an incompatibility in an older IJ version. Please try using a new IntelliJ version.

**Comment by anuraaga** [comment] 2021-06-04 10:29
Sorry for missing in the original report, the IntelliJ version is latest, 2021.1.2.

**Comment by mlopatkin** [comment] 2021-06-04 11:47
Thank you. I'm closing this issue as it is a duplicate of #17039.

**Closed by mlopatkin** 2021-06-04 11:47 UTC
Labels: a:bug, to-triage
