### ISSUE TITLE
order of execution of configuration closures for Task Configuration Avoidance

### ISSUE THREAD

**Issue by matteomazza91** [gradle/gradle#25606] opened 2023-07-04 16:34 UTC
### Expected Behavior

the configuration closure passed to `TaskContainer.register` should take precedence on other configuration closures e.g. `withType`.

i.e. the `register` closure should be the first to be executed when a task is created.

### Current Behavior (optional)

At the moment (gradle 8.2) this fails with `the value for task ':myTask' property 'archiveFileName' is final and cannot be changed any further.` showing that the `register` closure is executed after the `withType`

Note: this is not the actual use-case. it's just a simple snippet of code to explain the intended behaviour.
```
tasks.withType<Zip>().configureEach {
  archiveFileName.set("test-2")
  archiveFileName.finalizeValue()
}

val t = tasks.register<Zip>("myTask") {
  from("./")
  destinationDirectory.set(file("${buildDir}/dist"))
  archiveFileName.set("test-1")
}

```

### Context

This came up while trying to configure some tasks that are registered by a plugin.
The call of the `register` api (in the plugin) is located inside a `configureEach` as shown below.

```
class Something implements Plugin<Project> {
    
    void apply(Project project) {
        SomeExtension extension = project.extensions.create(someName, SomeExtension)
        extension.something.configureEach {
             project.tasks.register( [...]
```

this cause the register closure to be executed after the withType closure in the project buildscript (that is consuming this plugin).
So some `Property<>`s, that are `set` in the `withType` closure by the project, are overridden in the register closure by the plugin.

**Comment by jbartok** [comment] 2023-07-05 13:00
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/21424

Please add your use case and 👍 to that issue.

**Closed by jbartok** 2023-07-05 13:00 UTC
Labels: a:feature, to-triage
