### ISSUE TITLE
New plugins DSL does not allow to set plugin version using ExtraPropertiesExtension

### ISSUE THREAD

**Issue by bitsydarel** [gradle/gradle#6445] opened 2018-08-21 05:10 UTC
I was trying to update our projects build script to use the new gradle plugings DSL.
But i had issue defining plugins this way:
plugins {
    id 'org.jetbrains.kotlin.kapt' version project.kotlin_version
}

or this way:
plugins {
    id 'org.jetbrains.kotlin.kapt' version "$kotlin_version"
}

it's only work if i define it :
plugins {
    id 'org.jetbrains.kotlin.kapt' version '2.61.1'
}

I understand that the plugin version needs to be statically set so gradle can quickly apply it, but if I'm using the plugin in many subprojects (modules) I want to use the same version of the plugin everywhere and if I need to change it, I only want to change it at one place.
So using the project properties will be really handy.

I'm using gradle 4.9  with android gradle plugin 3.1.4

**Comment by oehme** [comment] 2018-08-21 07:46
Duplicate of https://github.com/gradle/gradle/issues/1697

**Closed by oehme** 2018-08-21 07:46 UTC
