### ISSUE TITLE
testReleaseUnitTest (minifyEnabled=true) fails in Gradle 8 with java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by MIchaelZablianov** [gradle/gradle#30453] opened 2024-09-08 11:36 UTC
### Current Behavior

since upgrade to Gradle 8 TestReleaseUnitTest fails on minify enabled builds with error : 
java.lang.NoClassDefFoundError: com/example/mobile/mylibrary/MyLib
	at com.example.mobile.mylibrary.ExampleInstrumentedTest.fromMyLibTest(ExampleInstrumentedTest.kt:19)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:112)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:54)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:92)
	at jdk.proxy1/jdk.proxy1.$Proxy4.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:183)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:132)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:103)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:63)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:121)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.lang.ClassNotFoundException: com.example.mobile.mylibrary.MyLib
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)

it seems like it cannot recognize the Lib's code in release/minified builds

### Expected Behavior

testReleaseUnitTest runs corre3ctly as testDebugUnitTest does

### Context (optional)

Trying to run tests in release build (minifyEnabled = true) in and android library project, android application project seem to run tests ok, the issue is in android library projects.

### Steps to Reproduce

1. create an android library project (plugin com.android.library) 
2. in the android lib project create unit test for a class declared in the lib
3. run task testReleaseUnitTest

### Gradle version

8.10

### Gradle version that used to work

7.4

### Your Environment (optional)

mac , m1 chip

**Comment by Dussim** [comment] 2024-09-09 07:51
Hi @MIchaelZablianov Look at this release notes form Android Gradle Plugin 8.4.0 https://developer.android.com/build/releases/past-releases/agp-8-4-0-release-notes#library-classes-shrunk

Previously even tho you set minifyEnabled to true the behavior was a bit srange and it wasnt actually minified for publishing (release variant)

**Comment by ljacomet** [comment] 2024-09-09 08:31
This is an issue with the Android Gradle Plugin, which is developed by Google and cannot be addressed in the Gradle Build Tool project. We also cannot just move the issue.

Reach out to the Android community for questions: https://source.android.com/docs/setup/community

If you believe this is not an Android issue, please update with a reproducer that does not involve Android.

**Closed by ljacomet** 2024-09-09 08:31 UTC
Labels: a:regression, to-triage

**Comment by xiushaomin** [comment] 2024-12-03 10:02
@MIchaelZablianov  did you fix this issue？

**Comment by Dussim** [comment] 2024-12-03 10:15
@xiushaomin if you encounter this problem please read link I provided, it is entirely on android plugin side https://developer.android.com/build/releases/past-releases/agp-8-4-0-release-notes#library-classes-shrunk

Baseline is **you should probably do not minify** your `android-library` modules but that depends.

**Comment by xiushaomin** [comment] 2024-12-12 06:39
> [@xiushaomin](https://github.com/xiushaomin) if you encounter this problem please read link I provided, it is entirely on android plugin side https://developer.android.com/build/releases/past-releases/agp-8-4-0-release-notes#library-classes-shrunk
> 
> Baseline is **you should probably do not minify** your `android-library` modules but that depends.

thanks for you share, that's the root cause.
