### ISSUE TITLE
Error: Problems reading data from Binary store in /tmp/gradle

### ISSUE THREAD

**Issue by ErandiDissanayaka** [gradle/gradle#17656] opened 2021-07-08 11:28 UTC
I am getting the Error as follows, when I try to run the flutter app.

```
What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
Could not resolve all dependencies for configuration ':app:debugCompileClasspath'.
Problems reading data from Binary store in /tmp/gradle4420452894670361188.bin offset 455548 exists? true
```

I have set this in build.gradle

classpath 'com.google.gms:google-services:4.3.3'

I have this dependency in app/build.gradle

apply plugin: 'com.google.gms.google-services'

When I remove app/build.gradle google-services plugin, app worked fine. Since I need google-services plugin, I want to know how to solve this problem. Thanks!

This is the flutter doctor -v output.

```
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.3 at /opt/flutter
    • Framework revision f4abaa0735 (6 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/**/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.
[✓] Chrome - develop for the web
    • Chrome at google-chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 57.0.1
    • Dart plugin version 201.9380
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
[✓] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /home/**/Office Works/Softwares/idea-IC-193.6494.35
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
[✓] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at /opt/idea
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
[✓] VS Code (version 1.50.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.17.0
```

**Comment by bpsourav21** [comment] 2021-07-08 14:21
I am getting similar error for last 2 days with my react-native app. Still looking for soultion

**Comment by ljacomet** [comment] 2021-07-09 08:38
This is most likely caused by a corner case in the dependency resolution engine. Unfortunately without a reproducer it is quite impossible to track down.

Can one of you share such a reproducer?

An alternative is to tweak dependency declarations as the order in which the graph is walked is sometimes a way to work around the bug. Tweak means: adding versions where you expect it from a platform, re-ordering declarations, etc ...

**Comment by ErandiDissanayaka** [comment] 2021-07-09 11:08
I could solve the issue by upgrading the gradle to gradle-6.7.

>distributionUrl=https\://services.gradle.org/distributions/gradle-6.0-all.zip

**Comment by ljacomet** [comment] 2021-07-09 16:19
Indeed, I should have asked about the Gradle version. A number of fixes in this area were made during the 6.x line. I would encourage you to upgrade to Gradle 6.9 or even 7.x.

I'll close this issue for now. A new issue with a recent Gradle version and a reproducer can be opened if needed.

**Closed by ljacomet** 2021-07-09 16:19 UTC
Labels: a:bug, in:dependency-resolution, to-triage
