### ISSUE TITLE
Circular dependency in project with nested shared subproject.

### ISSUE THREAD

**Issue by urosjarc** [gradle/gradle#29338] opened 2024-05-28 14:55 UTC
### Current Behavior

I have unknown circular dependency error in the project, I have created minimal working example displaying my error:
> https://github.com/urosjarc/gradle-circular-dependency

In README.md I have explained the project structure and error

### Expected Behavior

The project dependencies are OK, there should not be circular dependency in my project....

### Steps to Reproduce

I have created minimal working example displaying my error:
> https://github.com/urosjarc/gradle-circular-dependency
You can clone the project and run `main.kt` inside `company:core` subproject.

### Gradle version

distributionUrl=https\://services.gradle.org/distributions/gradle-8.4-bin.zip

**Comment by ljacomet** [comment] 2024-05-30 12:49
This issue will be closed as a duplicate of

* #847

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

Your `*:core` and `*:app` subprojects will end up clashing in terms of identity. You will have to either give them different project names (artifact ID) or different group.

**Closed by ljacomet** 2024-05-30 12:49 UTC
Labels: a:bug, in:dependency-resolution, in:multi-projects
