### ISSUE TITLE
@file annotation in precompiled script plugins leads to unexpected behavior on publishing

### ISSUE THREAD

**Issue by WebTiger89** [gradle/gradle#20865] opened 2022-05-26 17:44 UTC
Im facing a really strange behavior with `precompiled script plugins`. I have an IntelliJ project with a bunch of precompiled script plugins which I publish to maven local. As soon as one of the script plugins exists of a @file annotation the publishing does not respect the package structure anymore. For instance in src/main/kotlin/de/example/configuration/myplugin.gradle.kts:

```
@file:Suppress("UnstableApiUsage")

package de.example.configuration
```

When I publish to maven local, the binaries are published directly into the _~/.m2/repository/_ folder. When I comment the first line, it is published to _~/.m2/repository/de/example/configuration/_

A slack community user already figured out the suspicious line:
https://github.com/gradle/gradle/blob/master/subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/PrecompiledScriptPlugin.kt#L122

Discussion here:
https://gradle-community.slack.com/archives/CAHSN3LDN/p1653585192781079

**Comment by eskatos** [comment] 2023-02-03 09:51
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/16154

Please add your 👍 to that issue.

**Closed by eskatos** 2023-02-03 09:51 UTC
Labels: in:kotlin-dsl, closed:duplicate, in:precompiled-script-plugin
