### ISSUE TITLE
Document ArtifactView API

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#10867] opened 2019-09-25 10:57 UTC
This could be included in `artifact_transforms.adoc`.

**Comment by ljacomet** [comment] 2020-01-10 11:02
This also should cover how to get to the metadata files for custom processing.
It should replace of supplement https://docs.gradle.org/5.6.3/userguide/working_with_dependencies.html#accessing_a_modules_metadata_file in order to answer the use case of #11449

**Comment by lkasso** [comment] 2024-07-30 21:50
Closing as duplicate of https://github.com/gradle/gradle/issues/26007

**Closed by lkasso** 2024-07-30 21:50 UTC
Labels: in:documentation-infrastructure, closed:duplicate, a:documentation
