### ISSUE TITLE
Multiple incompatible variants of org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.21 were selected

### ISSUE THREAD

**Issue by danny-su** [gradle/gradle#22869] opened 2022-11-28 03:39 UTC
A problem occurred configuring project ':buildSrc'.
> Could not resolve all files for configuration ':buildSrc:classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.21.
     Required by:
         project :buildSrc > org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:1.7.21 > org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.21
      > Multiple incompatible variants of org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.21 were selected:
           - Variant org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.21 variant gradle70RuntimeElements has attributes {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=7.0, org.gradle.status=release, org.gradle.usage=java-runtime}
           - Variant org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.21 variant gradle71RuntimeElements has attributes {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=7.1, org.gradle.status=release, org.gradle.usage=java-runtime}

**Gradle Version: 7.6**

**Comment by eskatos** [comment] 2022-11-29 11:04
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/22510

Its root cause is in the Kotlin Gradle Plugin, see https://youtrack.jetbrains.com/issue/KT-54691/Kotlin-Gradle-Plugin-libraries-alignment-platform

**Closed by eskatos** 2022-11-29 11:04 UTC
Labels: closed:duplicate, closed:kotlin
