### ISSUE TITLE
Support task lock option

### ISSUE THREAD

**Issue by imanushin** [gradle/gradle#11610] opened 2019-12-06 18:32 UTC
Idea: support ability to mark tasks, which shouldn't be executed in parallel. This idea is pretty same with [Shared Resources](https://www.jetbrains.com/help/teamcity/shared-resources.html) feature of TeamCity.

### Expected Behavior
This can be done by attaching a "lock identity" for each task. 

Then:
* If task X has the same lock with any of executing now - it should wait until finishing.
* If task X doesn't have the same lockIdentity with any executing now - it can be started.

Lock identity can have ```String``` type (and default value is ```project.fullName + task.name```).

### Current Behavior
Gradle doesn't have inter-project parallelism controlled feature.

### Context
Why it is needed for me:
* For current moment my project has integration tests, which uses shared resource - database.
* Integration tests couldn't be executed in parallel with each other (even at the other subproject).
* If they are disabled (which is controlled via project properties) then even tests can be executed in parallel.

The following solution allows me to have fully parallel build if integration tests are disabled. In addition, even if integration tests are enabled I'm able to have parallel task execution.

**Comment by big-guy** [comment] 2019-12-09 20:49
This is similar to/a dupe of #7047.  The idea is similar to what you have here where you can have a task require a shared resource and Gradle takes care of acquiring it before the task is allowed to execute.

**Closed by big-guy** 2019-12-09 20:49 UTC
Labels: a:feature, from:contributor
