### ISSUE TITLE
Incremental cache lost after a compilation error when using Micronaut

### ISSUE THREAD

**Issue by nassimus26** [gradle/gradle#19453] opened 2021-12-30 02:18 UTC
The cache is lost after any compilation error when Micronaut-inject is shipped with the project, so for example :

1- Build this project a first time

2- Make a build error, for example by removing any parentheses on the line 12 ( `log.debug` ) of the `test.Application` class in the `/grails-app/init` folder, please note that Micronaut injection must be triggered in the code, that's why I added the first line `TriggerMicronaut.getDeclaredField("name")` by calling reflection API

3- Build the project, so the build will fails

4- Correct the code, to succeed the next compilation

5- Rebuild the project, here, instead of having an incremental build (just one file), we got the message :

```
> Task :compileGroovy
Build cache key for task ':compileGroovy' is 8155b9162e73ad3dbcf1e6e45d38c585
Task ':compileGroovy' is not up-to-date because:
  Task has failed previously.
The input changes require a full rebuild for incremental task ':compileGroovy'.
Groovy compilation avoidance is an incubating feature.
Full recompilation is required because no incremental change information is available. This is usually caused by clean builds or changing compiler arguments.
```

I am using Gradle 7.3.3 ( latest version ), with open JDK 16

[micronaut-cache-conflict.zip](https://github.com/gradle/gradle/files/7791258/micronaut-cache-conflict.zip)

**Comment by oehme** [comment] 2021-12-30 11:56
This is expected and a duplicate of https://github.com/gradle/gradle/issues/13766.

**Comment by nassimus26** [comment] 2021-12-30 12:00
@oehme I am not sure because when Micronaut is not implicated in the build, it seems working, but maybe the problem could also happening without Micronaut, in this case, yes it’s a duplicate

**Comment by oehme** [comment] 2021-12-30 12:04
Ah sorry I misread the steps. You're right, this is not a duplicate. I'll have a look what's going on in this scenario.

**Comment by nassimus26** [comment] 2021-12-30 12:05
@oehme thanks, I hope it gonna be fixed soon

**Comment by nassimus26** [comment] 2021-12-30 15:25
@oehme I am not sure but it seems, that when I cancel the build before it finish it leads to the same problem I think

**Comment by nassimus26** [comment] 2022-03-16 19:25
Any update about this issue ?!

**Comment by asodja** [comment] 2022-03-19 15:56
This looks like an issue when compilation fails and we do a full recompilation after the failure. We plan to fix this, but due to other priorities it very likely won't be fixed in next two months.

**Comment by asodja** [comment] 2022-06-07 10:38
The linked PR https://github.com/gradle/gradle/pull/20950 probably fixes this issue. The reproducer doesn't work with any of latest Gradle (7.3.3 or 7.4.2) so I can't test it (wrapper has version 5.6.4).

So unless a reproducer that shows this is not an issue with "full recompilation after the failure" is added, this issue will be closed once https://github.com/gradle/gradle/pull/20950 get merged. Of course you can always open new issue.

**Comment by nassimus26** [comment] 2022-06-07 10:47
@asodja hi,  this issue was opened 4months ago, you asked me to try with the last version, so I create a new issue with the last version, but now it’s not the last version anymore, but all you need to check if it fixed or not, is to change the version of gradle in the joined test project, otherwise each time I will create a new issue with the last version, then it had to wait to a new version then you will ask the same thing ….

**Comment by asodja** [comment] 2022-06-07 11:12
I understand that it's not feasible for you to update Gradle version for me and that totally makes sense. The problem I am facing is, that when I try to reproduce the issue with the version specified in this issue (7.3.3) and reproducer linked in the issue: https://github.com/gradle/gradle/files/7791258/micronaut-cache-conflict.zip I get:
```
❯ ./gradlew :compileGroovy

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/asodja/Downloads/micronaut-cache-conflict 3/build.gradle' line: 19

* What went wrong:
A problem occurred evaluating root project 'micronaut-cache-conflict'.
> Failed to apply plugin class 'nebula.plugin.extraconfigurations.ProvidedBasePlugin'.
   > No such property: COMPILE_CONFIGURATION_NAME for class: org.gradle.api.plugins.JavaPlugin
```
I also tried with version 7.0 and got the same problem. This indicates that the plugin that is used in the reproducer is not updated to work with 7.x.

So it seems to me that the reproducer was actually not run with Gradle 7.3.3.

**Comment by nassimus26** [comment] 2022-06-07 11:18
Strange this test project was created and tested with version 7.3.3 (latest at that date), I will recheck.

**Comment by asodja** [comment] 2022-06-07 11:48
Thanks for rechecking it.

**Closed** 2022-07-08 12:16 UTC
Labels: a:bug, in:annotation-processing
