### ISSUE TITLE
Task is incorrectly considered out-of-date if ignored directory changes

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#5832] opened 2018-07-01 22:26 UTC
Example include: `include("**/bar.txt")`
Example dir: `dir/foo/bar.txt`
Example tree: `project.fileTree("dir")`

If I suddenly add `dir/bar/foo.txt`, the task will be re-run even though none of the actual inputs changed. Furthermore, the `IncrementalTaskInputs` will report the file `dir/bar` which is wrong since nothing has changed in there that we care about.

Full example:
```kt
    @Suppress("MemberVisibilityCanBePrivate", "unused") // Used by Gradle
    @get:PathSensitive(PathSensitivity.RELATIVE)
    @get:SkipWhenEmpty
    @get:InputFiles
    protected val targetFiles: FileCollection by lazy {
        project.fileTree(resDir).apply {
            fun Array<out Detail>.include() {
                for (detail in this) include("**/${detail.fileName}")
            }
 
            AppDetail.values().include()
            ListingDetail.values().include()
            for (type in ImageType.values()) include("**/${type.fileName}/*")
        }
    }
```

**Comment by wolfs** [comment] 2018-07-02 16:22
@SUPERCILEX Thank you for reporting. Currently, an include as `**/bar.txt` means to include all directories (`**` takes care of that). We currently don't have a way to say for an input that it only cares about files. That would be covered by #2463.

I am closing this issue as a duplicate of #2463.  Please comment on that issue if you think something is missing from there or re-open this issue if you disagree.

**Closed by wolfs** 2018-07-02 16:22 UTC
Labels: in:incremental-build

**Comment by SUPERCILEX** [comment] 2018-07-02 18:05
Gotya, thanks for the tip!
