### ISSUE TITLE
Catalog should play nice with native dependencies too

### ISSUE THREAD

**Issue by elect86** [gradle/gradle#16869] opened 2021-04-16 16:03 UTC
Catalogs help with normal binary dependencies, but with runtime natives only is still quite verbose

### Expected Behavior

I'd like the possibility to have something like this:

```
implementation(jogamp.gluegen)
runtimeOnly(jogamp.gluegen, classifier = joglNative) 
```

### Current Behavior

this is what the current implementation requires instead:

```
implementation(jogamp.gluegen)
val gluegen = jogamp.gluegen.get()
runtimeOnly(gluegen.module.group, gluegen.module.name, gluegen.versionConstraint.toString(), classifier = joglNative) 
```

### Context

Dealing extensively with dependencies for native libraries

I also tried
```
runtimeOnly(jogamp.gluegen) { 
    artifact { 
        name = "joglNative" // also `jogamp.gluegen.get().module.name
        classifier = joglNative 
    }
}
```

but I get

> FAILURE: Build failed with an exception.
> * What went wrong:
Could not resolve all dependencies for configuration ':runtimeClasspath'.

**Comment by melix** [comment] 2021-04-23 13:53
Closing as duplicate of #16768

**Closed by melix** 2021-04-23 13:53 UTC
Labels: a:feature, in:dependency-version-catalog
