### ISSUE TITLE
StringIndexOutOfBoundsException on test failure

### ISSUE THREAD

**Issue by MatFl** [gradle/gradle#2077] opened 2017-05-18 13:43 UTC
On my build server (Windows 2012 R2 x64) I get a exception from gradle when a test is failing. The test is set to continue, so the build shouldn't stop.

I am not using the build cache, and the build is not parallel. The gradle wrapper version is 3.5. The failing test is an android instrumentation test.

On my dev machine (Ubuntu 16.04 x64) the test "fails correctly". So the build continues as it should.

Here is the stacktrace:

```
FAILURE: Build failed with an exception.

* What went wrong:
String index out of range: -1

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1967)
        at org.gradle.internal.logging.text.AbstractLineChoppingStyledTextOutput$StateContext.flushLineText(AbstractLineChoppingStyledTextOutput.java:115)
        at org.gradle.internal.logging.text.AbstractLineChoppingStyledTextOutput$2.execute(AbstractLineChoppingStyledTextOutput.java:167)
        at org.gradle.internal.logging.text.AbstractLineChoppingStyledTextOutput$2.execute(AbstractLineChoppingStyledTextOutput.java:160)
        at org.gradle.internal.logging.text.AbstractLineChoppingStyledTextOutput$1.execute(AbstractLineChoppingStyledTextOutput.java:146)
        at org.gradle.internal.logging.text.AbstractLineChoppingStyledTextOutput$1.execute(AbstractLineChoppingStyledTextOutput.java:131)
        at org.gradle.internal.logging.text.AbstractLineChoppingStyledTextOutput.doAppend(AbstractLineChoppingStyledTextOutput.java:41)
        at org.gradle.internal.logging.text.AbstractStyledTextOutput.text(AbstractStyledTextOutput.java:73)
        at org.gradle.internal.logging.text.AbstractStyledTextOutput.println(AbstractStyledTextOutput.java:68)
        at org.gradle.internal.logging.events.LogEvent.render(LogEvent.java:44)
        at org.gradle.internal.logging.console.StyledTextOutputBackedRenderer.onOutput(StyledTextOutputBackedRenderer.java:62)
        at org.gradle.internal.logging.sink.ProgressLogEventGenerator.doOutput(ProgressLogEventGenerator.java:63)
        at org.gradle.internal.logging.sink.ProgressLogEventGenerator.onOutput(ProgressLogEventGenerator.java:53)
        at org.gradle.internal.logging.sink.OutputEventRenderer$2.onOutput(OutputEventRenderer.java:237)
        at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:221)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:145)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
        at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:315)
        at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:225)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:138)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:35)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy1.onOutput(Unknown Source)
        at org.gradle.internal.logging.sink.OutputEventRenderer.onOutput(OutputEventRenderer.java:306)
        at org.gradle.launcher.daemon.client.DaemonClient.monitorBuild(DaemonClient.java:205)
        at org.gradle.launcher.daemon.client.DaemonClient.executeBuild(DaemonClient.java:167)
        at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:130)
        at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:81)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:281)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:254)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:33)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:247)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:182)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:31)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

**Comment by MatFl** [comment] 2017-05-22 06:20
Regarding your comment on #2079 (https://github.com/gradle/gradle/issues/2079#issuecomment-302733304): the exception is thrown even if the stacktrace is not beeing printend.

**Comment by MatFl** [comment] 2017-07-20 06:04
I am still getting this exception with gradle 4.0.1 and com.android.tools.build:gradle 2.3.3

**Comment by MathiasSeguy-Android2EE** [comment] 2017-07-21 12:22
Oh yeah, I have the same.
(I write again the bug I am facing, (it's the same) but sometimes, it help to have another description)
Hi
I am an Android developer and this year I use extensively Gradle in my android build system, creating a build systems that fits my Android development. What I am doing is just, build my app, run it tests (instrumented and Unit tests),  generate the apk (or the aar), generate my reports, and push on a Nexus. Nothing exceptional.
The problem I am facing is the following.
My build process works well if  my gradle-wrapper is under 3.3 but AndroidStudio doesn't want to launch the application (because my gradle version is too old).
If I update, (since 3.5 until 4.+ rc, because for each version, I try again, just in case) my instrumented tests run from my gradle file fail. with the following exception:
_14:10:53.049 [INFO] [org.gradle.api.Task]
mycms.acms.renaultnissan.com.mycms.addvehicle.AddVehicleConfirmationUITest > checkSuccess_AuthorizedVehicleVinOpenAddVehicle[Nexus 5X - 7.1.1] SUCCESS 
<==========---> 78% EXECUTING [1m 44s]
> :app:connectedMycmsMockDebugAndroidTest

FAILURE: Build failed with an exception._

* What went wrong:
String index out of range: -1
yes that's all, me I don't have the stacktrace :'( not fair :), even with a --debug --stracktrace
...
It seems, from my point of view, that my build lost the pipe with the process of instrumentedTests and so say "Hey, tests fail because the process is gone", like a timeout or a broken pipe. But my tests are still running on my device, they are all running the one after the others even with my gradle process crashed. My instrumented tests run until their normal end, while my build process has crashed minutes ago (I have a lot of tests).

Ok to reproduce, create a new project with AndroidStudio, creat few instrumented tests (we use Espresso for them) and run instrumented tests  using connected**AndroidTest task.

Then play with those line in your gradle-wrapper.properties:
#distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-milestone-1-all.zip

AndroidStudio 2.3 and 3.+ canary are both reproducing the problem. 
Windows 10

**Comment by lacasseio** [comment] 2017-07-23 14:57
This will be fixed in 4.1. I'm closing it now.

**Closed by lacasseio** 2017-07-23 14:57 UTC
Labels: a:bug, affects-version:3.5, from:contributor, in:logging

**Comment by MathiasSeguy-Android2EE** [comment] 2017-07-23 16:10
<3 in love :)
Thank you

**Comment by Kisty** [comment] 2017-08-14 14:45
@MathiasSeguy-Android2EE Any chance you're using `assume*()` calls in tests? I've had the same problem and ran into this bug. Had narrowed it down to problems when an `org.junit.AssumptionViolatedException` is thrown https://issuetracker.google.com/issues/64551067
