### ISSUE TITLE
Lombok / Gradle 4.9 problem with Groovy folder names(s) ... 

### ISSUE THREAD

**Issue by aplatypus** [gradle/gradle#6120] opened 2018-07-30 01:03 UTC
There is a problem with Gradle v4.9 that works fine with Gradle v4.8.1 processing/compiling Java and Groovy code when the files sit under a `groovy` sourceSet tree (as shown).

```
   build.gradle
   settings.gradle
   common.gradle
   TestingSupport/
    |
    +-- src/
         |
         + main/
         |  |
         |  + groovy/
         |  |   |
         |  |   +- au/...
         |  + resources/
         + test/
            |
            + groovy/
            |
            + resources/
```
*  According to the documentation Java and Groovy files can be in the same source tree.
   * Testing code uses the Groovy based [Spock tool](spockframework.org/)
   * This project keeps files under the `./src/main/groovy/` tree
* I am posting here because I can't be sure where cause lies.  
**  Gradle is the only thing that has changed in this build.
**  This library has been stable for several months.

### Expected Behavior

* `gradle TestingSupport:build`
  * Expect this command to complete successfully using: **`Gradle v4.9`** 
  * Using the `src/*/gradle/` sourceSet naming.
  * Processing Lombok and other annotation processing accurately.
* I expect support for both `src/*/gradle/` and `src/*/java/` to remain unchanged

### Current Behavior

`gradle TestingSupport:build`

* Fails when run with `Gradle v4.9`
  * This command successfully compiles all the code and passes `TestingSupport` test cases using `Gradle 4.8.1` and earlier versions.
* The command also completes successfully when the sourceSet is changed to:  **`./src/main/java/`** 
   from: `./src/main/groovy/`.
   * The Gradle v4.9 evidently processes ghe Groovy folder differently than the Java folder usiing or `Gradle 4.9`.
   * I'd expect v4.9 to work in the same wayas:  `Gradle v4.8.1` and before. 
   * It is not desirable to have to rename the folders in every test set and utility projects.
*  The problems induced are related to annotation processing for [Lombok](https://projectlombok.org)
*  The first error is on a plain Java class _with no annotations_ as follows...
   * This fileis just pure Java and one method:
```
/***
 *  Information
 *    - Main class used to report on the module's version, etc.
 */
public class Information   extends ModuleInformation {
    private static final    String      CLASS_NAME  = Information.class.getSimpleName();
    private static final    ReleaseInfo RELEASE     = ModuleRelease.getInstance();

    protected boolean showVersion( String[] args )  {
	Monitor.getInstance().logRuntimeContext( RELEASE );
	System.out.println("runMain...  "+ RELEASE.getModuleName() +" -- Informaton class.");
           :
    }
}
```
   * Yet an error calling or finding Lombok is generated
```
public class Information   extends ModuleInformation
       ^
        at lombok.javac.apt.LombokProcessor.getJavacProcessingEnvironment(LombokProcessor.java:413)
        at lombok.javac.apt.LombokProcessor.init(LombokProcessor.java:89)
        at lombok.core.AnnotationProcessor$JavacDescriptor.want(AnnotationProcessor.java:128)
        at lombok.core.AnnotationProcessor.init(AnnotationProcessor.java:181)
        at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.init(AnnotationProcessor.java:73)
        at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.init(DelegatingProcessor.java:57)
        at org.gradle.api.internal.tasks.compile.processing.IsolatingProcessor.init(IsolatingProcessor.java:44)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:500)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:597)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:690)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
        at org.gradle.api.internal.tasks.compile.AnnotationProcessingCompileTask.call(AnnotationProcessingCompileTask.java:85)
        at org.gradle.api.internal.tasks.compile.ResourceCleaningCompilationTask.call(ResourceCleaningCompilationTask.java:53)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:50)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:36)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler$2$1.compile(ApiGroovyCompiler.java:169)
        at org.codehaus.groovy.tools.javac.JavaAwareCompilationUnit.gotoPhase(JavaAwareCompilationUnit.java:105)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:568)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:537)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:179)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:57)
        at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:77)
        at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:65)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerCallable.call(AbstractDaemonCompiler.java:88)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerCallable.call(AbstractDaemonCompiler.java:76)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:42)
    :
```
*  Other errors occur in Java classes using Lombok -- the annotations are not processed.
   * It looks like a result of the first error.
   * Unfortuately none of that code compiles making the library useless.
   * Example:
```
gradle TestingSupport:build
  :
  ... TestingSupport\src\main\groovy\au\com\fourtel\tmacs\unittest\TestContext.java:78: error: cannot find symbol
            log.error( msg );
            ^
  symbol:   variable log
```

### Context
* All unit tests use spock under a `groovy` source tree.  Testing is compromised using v4.9
* The testing tools we have will not work
* Other annotations are likely to cause a problem in other areas

### Steps to Reproduce (for bugs)

* make a gradle project with java and groovy source under: `src/main/groovy`
* use the latest Lombok build as dependency
* Add a couple of example classes, with and without Lombok annotations
  * No lombok
```
/***
 *  Information
 *    - Main class used to report on the module's version, etc.
 */
public class Information   {
    private static final    String      CLASS_NAME  = Information.class.getSimpleName();

    protected boolean showVersion( String[] args )  {
	System.out.println("runMain...  "+ CLASS_NAME +" -- Informaton class.");
           :
    }
}
```

* with Lombok
```
@Slf4j
public class InformationX   {
    private static final    String      CLASS_NAME  = Information.class.getSimpleName();

    protected boolean showVersion( String[] args )  {
	log.info( "runMain...  "+ CLASS_NAME +" -- Informaton class.");
           :
    }
}
```

### Your Environment

 * Build scan URL: https://gradle.com/s/mzwyjdyy76gg4

**Comment by marcphilipp** [comment] 2018-07-30 06:34
@oehme Is this issue related to incremental annotation processing related changes?

**Comment by oehme** [comment] 2018-07-30 08:12
Duplicate of https://github.com/rzwitserloot/lombok/pull/1718

**Closed by oehme** 2018-07-30 08:12 UTC
