### ISSUE TITLE
Set PMD noCache option until PMD's incremental analysis mode is supported

### ISSUE THREAD

**Issue by ebruneton** [gradle/gradle#8277] opened 2019-01-20 15:08 UTC
### Expected Behavior
When PMD is used to check code quality, there should be no warning when all PMD rules are satisfied.

### Current Behavior
There is always a warning "This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/pmd-6.8.0/pmd_userdocs_incremental_analysis.html" (example: https://gitlab.ow2.org/asm/asm/-/jobs/10540)

### Context
PMD introduced incremental analysis, and logs a warning when it is not used, unless an explicit noCache option is set (https://pmd.github.io/pmd/pmd_userdocs_cli_reference.html#options). An attempt was made to use this mode in Gradle (https://github.com/gradle/gradle/pull/2223) but was reverted (https://github.com/gradle/gradle/pull/3125). Until proper support for Incremental Analysis is implemented, I think the noCache option should be set to avoid polluting the build logs with irrelevant warnings (the user has no way to use incremental analysis, and no way to filter out these warnings).

This can be done with a one-line change in https://github.com/gradle/gradle/blob/8822e105b560e9dcc160c7cc887113c502ca9f43/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/PmdInvoker.groovy#L66

Just after this line add

`antPmdArgs["noCache"] = true`

and the spurious warnings disappear.

**Comment by nresare** [comment] 2019-04-24 15:37
This issue is still reproducible in gradle-5.4, so I opened a PR with the suggested fix to get the ball rolling.

**Comment by aalmiray** [comment] 2019-05-06 16:01
Thank you for taking the time to propose a fix for this issue. May I suggest the following improvements to make it easier to adopt this change?

 - add a property to `Pmd` task to configure the caching strategy. Simply setting `noCache` to `true` is not ideal.
 - it looks like the starting value for this property should be `true`.
 - add a test for all values of this new property (`false`, `true`) and when a value is not specified ( task should use the default value).

**Comment by nresare** [comment] 2019-05-07 13:39
@aalmiray as you can see in the original problem description above, the effort to enable incremental analysis (the feature referred to as _cache_ by PMD) has been reverted in https://github.com/gradle/gradle/pull/3125 citing several upstream issues that needs a resolution.

Enabling the cache is not as simple as setting the cache property to `true` and doing so would not have the intended effect. To not set the parameter has the same effect as setting it to false, but with the mentioned warning printed on each invocation.

It is my assumption that once the blocking issues has been resolved, incremental analysis should be "always on", but this is not something that needs to be settled right now.

**Comment by huxi** [comment] 2019-05-07 18:31
Just for the record: the upstream issues have been fixed for over a year as I mentioned in https://github.com/gradle/gradle/pull/3125#issuecomment-356220647

**Closed** 2019-06-20 21:13 UTC
