### ISSUE TITLE
Composite build should work out-of-the-box with more project outputs

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#2529] opened 2017-07-19 18:47 UTC
In the first iteration, composite builds will only automatically substitute a project dependency when that project has a group + name that exactly matches an external dependency, and will only substitute the primary jar output from that project. For any other type of publication, an explicit substitution must be declared in the composite build.

We should support most common use cases without requiring specific configuration in the composite build. Examples include:

- Using the maven-publish or ivy-publish plugin to declare outputs
- Projects that publish non-jar artifacts
- Projects that produce multiple outputs with different configuration instances

These use cases might be solved by allowing these projects to explicitly declare the output components and variants for a project, rather than configuring and inspecting the producer builds for different types of output declarations.

**Comment by EronWright** [comment] 2018-04-04 20:58
May I suggest another use case: consuming shaded jars (as produced by the shadow plugin).

**Comment by AghilasMessara** [comment] 2019-06-17 07:42
Is there a workaround for this?
I'm trying to do a dependency substitution from an included build but since the output is custom it doesn't work.

**Comment by svermeulen** [comment] 2019-12-10 03:15
I wish we could just specify a non-default configuration like this:

```
includeBuild '/Users/svermeulen/Projects/foo' {
    configuration = 'bar'
}
```

Then in the foo project:

```
project.artifacts {
  "default" defaultZipFile, {
    builtBy 'buildDefaultZip'
  }
  "bar" barZipFile, {
    builtBy 'buildBarZip'
  }
}
```

This becomes an issue when you want to have multiple different ways of including a composite build.  My workaround is to temporarily change the artifact that 'default' points to but it's not ideal to have to do that all the time

**Comment by rschmitt** [comment] 2020-08-25 22:49
Are there any updates here? I was wondering if maybe the dependency management improvements in Gradle 6 (such as variant-aware dependency substitution) might offer a way to solve this problem, or a better way to work around it.

**Comment by svermeulen** [comment] 2020-08-26 18:17
I'm not associated with the project but in my experience, when using composite builds, gradle 6+ will automatically choose the correct variant to use, which is really nice

**Comment by jjohannes** [comment] 2021-05-26 09:48
I can confirm what @svermeulen wrote above. At least since Gradle 6+, all components – be it an included build or a published component from repositories – share their outputs in a unified way using [variant aware dependency management](https://docs.gradle.org/current/userguide/variant_model.html). This should be used to declare the "publications" of a project. See, for example, the user manual section on [sharing outputs between projects](https://docs.gradle.org/current/userguide/cross_project_publications.html) for how to use this in a custom setup. 

There are plans to improve the API/DSL and conveniences around this for custom setups (see #9834), but the fundamental functionality is there and it is working.

I am closing this issue. If there is a concrete case you expect to work that does not, please open a new issue with a reproducer.

**Closed by jjohannes** 2021-05-26 09:48 UTC
Labels: @core, a:feature, in:composite-builds
