### ISSUE TITLE
Gradle always does full recompilation after getting result of compileJava task from Build cache 

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#14917] opened 2020-10-20 04:59 UTC
So it looks like Gradle build cache is not that effective for compileJava task since Gradle will always do full recompilation due to missing source-classes mapping or missing compilation result. I tested with version 6.7 but this issue might be older.

I expect incremental compilation, but I get full recompilation on all occasions. 

### Expected Behavior
Gradle does incremental compilation after getting result for compileJava from build cache.

### Current Behavior
Gradle does full recompilation after getting result for compileJava from build cache.

### Context
Build cache is not that useful for compile Java. This affects work productivity when for example switching branches etc.

### Steps to Reproduce 
1. git clone git@github.com:asodja/gradle-full-recompilation.git
2. `./gradlew compileJava --info` -> Everything will be compiled nicely
3. `./gradlew compileJava --info` -> compileJava will be reported `UP-TO-DATE`
4. `./gradlew clean compileJava --info` -> compileJava will be reported `FROM-CACHE`
5. Add some dummy statement to TestClass1.build(), like `System.out.println("123");`
6. `./gradlew compileJava --info` -> expected incremental compilation, I get `Full recompilation is required because unable to get source-classes mapping relationship from last compilation.` or sometime `Full recompilation is required because no previous compilation result is available.`

### Your spec
Mac OS Catalina 10.15.6
Gradle 6.7
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
(For some reason I don't get build scan activate email right now)

**Comment by oehme** [comment] 2021-03-11 15:23
Duplicate of https://github.com/gradle/gradle/issues/4951

**Closed** 2021-04-08 06:09 UTC
Labels: @execution, a:bug
