### ISSUE TITLE
Command failed: gradlew.bat installDebug

### ISSUE THREAD

**Issue by wxy1234567890** [gradle/gradle#8571] opened 2019-02-21 01:13 UTC
FAILURE: Build failed with an exception.

* Where:
Settings file 'F:\myRNproject\android\settings.gradle' line: 3

* What went wrong:
Could not compile settings file 'F:\myRNproject\android\settings.gradle'.
> startup failed:
  settings file 'F:\myRNproject\android\settings.gradle': 3: unexpected char: '\' @ line 3, column 127.
     ules\react-native-vector-icons\android')
                                   ^

  1 error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

Command failed: gradlew.bat installDebug

Error: Command failed: gradlew.bat installDebug
    at checkExecSyncError (child_process.js:616:11)
    at Object.execFileSync (child_process.js:634:13)
    at runOnAllDevices (F:\myRNproject\node_modules\react-native\local-cli\runAndroid\runAndroid.js:299:19)
    at buildAndRun (F:\myRNproject\node_modules\react-native\local-cli\runAndroid\runAndroid.js:135:12)
    at isPackagerRunning.then.result (F:\myRNproject\node_modules\react-native\local-cli\runAndroid\runAndroid.js:65:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by blindpirate** [comment] 2019-02-21 01:15
Duplicate of https://github.com/gradle/gradle/issues/8570

**Closed by blindpirate** 2019-02-21 01:15 UTC

**Comment by flutterq2** [comment] 2021-08-09 03:22
[[Solved] Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
](https://exerror.com/error-command-failed-gradlew-bat-appinstalldebug-preactnativedevserverport8081/)

**Comment by grandhisaikiranmayi** [comment] 2023-01-02 23:05
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':@klarna/react-native-vector-drawable'.
> The project name '@klarna/react-native-vector-drawable' must not contain any of the following characters: [/, \, :, <, >, ", ?, *, |]. Set the 'rootProj
ect.name' or adjust the 'include' statement (see https://docs.gradle.org/7.3/dsl/org.gradle.api.initialization.Settings.html#org.gradle.api.initialization
.Settings:include(java.lang.String[]) for more details).

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI wi
th --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! resure@0.0.1 android: `react-native run-android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the resure@0.0.1 android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
