### ISSUE TITLE
Incorrect snapshot resolution with Gradle metadata

### ISSUE THREAD

**Issue by Egorand** [gradle/gradle#9462] opened 2019-05-18 01:26 UTC
### Expected Behavior

SNAPSHOT dependencies are properly resolved between two Kotlin Multiplatform libraries.

### Current Behavior

Gradle doesn't seem to pickup the latest snapshot for a platform module of a Kotlin Multiplatform project, published using Gradle metadata, even after 24 hours (default caching timeout) have elapsed.

### Context

1. The snapshot of [Okio](https://github.com/square/okio), a Kotlin Multiplatform library, has been published at around 2 am UTC on May 16th, as can be seen [here](https://oss.sonatype.org/content/repositories/snapshots/com/squareup/okio/).
2. Wire, another Kotlin Multiplatform library, depends on Okio's latest SNAPSHOT version.
3. Building Wire with `./gradlew :wire-runtime:assemble` fails because of a missing Okio method, that has been added in the latest SNAPSHOT.
4. Building Wire with `./gradlew :wire-runtime:assemble --refresh-dependencies` succeeds, but subsequent attempts to build with `./gradlew :wire-runtime:assemble` again fail.

### Steps to Reproduce 

1. Download Wire from Github: https://github.com/square/wire
2. Checkout the following branch: `egorand/190515/message-to-common`
3. Build the project with `./gradlew :wire-runtime:assemble`

### Your Environment

Build scan (`./gradlew :wire-runtime:assemble`) URL: https://scans.gradle.com/s/3yqr4zm2ulfoi
Build scan (`./gradlew :wire-runtime:assemble --refresh-dependencies`) URL: https://scans.gradle.com/s/q6zprgktl6h3a

**Comment by Egorand** [comment] 2019-05-18 01:28
Would appreciate someone to triage this for me. If this turns out to be a Kotlin issue - I'll move it to Kotlin's issue tracker.

**Comment by ljacomet** [comment] 2019-06-04 14:41
Sorry this took so long to get an answer to you.

I have been unable to reproduce the problem, running a command that downloads the dependencies resulted in the latest `-SNAPSHOT` artifacts to be picked up properly.

One optimization that Gradle does is to copy a file from the local Maven repo in case it can be found. Could it be that you have a `-SNAPSHOT` version in your local Maven repo that would interfere with the remote fetch?

I do not think anything in the Kotlin plugin ecosystem should interfere with dependency metadata / binaries fetching.

**Comment by Egorand** [comment] 2019-06-04 14:59
Thanks for looking into this!

> running a command that downloads the dependencies resulted in the latest -SNAPSHOT artifacts to be picked up properly.

I've also been able to get the latest snapshot when using `--refresh-dependencies`, but strangely enough it wouldn't work next time I omitted the flag.

> One optimization that Gradle does is to copy a file from the local Maven repo in case it can be found. 

That would require `mavenLocal()` in the `repositories` block though, which I'm pretty sure I don't have.

I'll investigate further ensuring that there are no caches/local repos interfering, and will report back if the problem persists. Overall, my thinking was that it could be a bug in the way Gradle metadata's versioning scheme handles snapshots, but it looks like it worked fine for you.

**Comment by ljacomet** [comment] 2019-10-14 14:28
So while I still have not managed to pinpoint the exact issue, it is more than likely this is caused by invalid publication of `-SNAPSHOT` versions with Gradle Module Metadata.
The `.module` file references the published artifact but we never replaced its `-SNAPSHOT` with the unique version.

Through #10919 and #11037, we are fixing this for Gradle 6.0.

As a consequence, `.module` file _will be different_ for different unique snapshots, no longer causing a md5 / sha1 clash in cache and so the problem should disappear.
Note that this will require _publication_ with Gradle 6+.

**Comment by xenoterracide** [comment] 2019-10-14 18:22
@ljacomet hmm... if this is caused by module metadata then not using it should cause the problem to disappear? I can test that

**Comment by ljacomet** [comment] 2019-10-16 16:54
So after some more work on this, there were multiple problems causing this:
* Publication of `SNAPSHOT` with Gradle Module Metadata is broken in 5.x and should not be done until 6.0 is released. This caused the `.module` files to not properly reference the artifact in variants.
* Parsing of Gradle Module Metadata for a `SNAPSHOT` version was not properly covered and resulted in the module _not_ marked as `changing`.

The combination of both bugs caused this weird not updating behaviour, unless `--refresh-dependencies` is passed, but then only for the build using that flag!

One possible workaround is to [ignore Gradle Module Metadata redirection](https://docs.gradle.org/5.6.2/userguide/repository_types.html#sub:supported_metadata_sources) (example 15) for the repository where this SNAPSHOT is found.

Another possible workaround is to nuke the dependency cache for that specific SNAPSHOT, getting rid of content under:
* `.gradle/caches/modules-2/metadata-2.71/descriptors/org.example.snapshot/my-snapshot/1.0-SNAPSHOT`
* `.gradle/caches/modules-2/files-2.1/org.example.snapshot/my-snapshot/1.0-SNAPSHOT`
where `org.example.snapshot:my-snapshot:1.0-SNAPSHOT` are the GAV of your snapshot.

Note that the cache has to be nuked each time you want a more recent version.

Unfortunately, the proper fix in Gradle 6.0 for publishing `SNAPSHOT` will break their resolution by existing 5.x releases (from 5.3 to 5.6.2). However a fix will be delivered with the upcoming 5.6.3 making it compatible with 6+ producers.

**Comment by Egorand** [comment] 2019-10-16 17:07
@ljacomet just to confirm, does this issue only affect SNAPSHOT artifacts?

**Comment by ljacomet** [comment] 2019-10-16 17:12
Yes, only `SNAPSHOT` are affected, you are all good for releases

**Comment by xenoterracide** [comment] 2019-10-16 17:45
fix confirmed in 6.0 nightly, thanks for the work

**Closed** 2019-10-16 19:22 UTC
Labels: a:bug, in:dependency-management
