### ISSUE TITLE
`java-test-fixtures` conflicts with `org.jetbrains.kotlin.jvm` plugin

### ISSUE THREAD

**Issue by tmohme-hypoport** [gradle/gradle#11501] opened 2019-11-28 15:45 UTC
Up to Gradle 5.6.4 we had no issues applying both the `java-test-fixtures` plugin and the `org.jetbrains.kotlin.jvm` plugin together.
With Gradle 6.0.1, we get compile errors from the kotlin compiler, stating that access is not allowed from a test class  to an internal function in a main class ("Cannot access 'greet': it is internal in 'Greeter'").
Somehow the kotlin compiler _should_ manage to allow test code to access internal main code  (and actually does it successfully up to Gradle 5.6.4) with its "friend-paths" option. 

During a detailed investigation I found that the only difference in the Kotlin compiler arguments is in the "-classpath" argument.

For Gradle 6.0.1:
The build runs successfully only _without_ the `java-test-fixtures` plugin.
Without the `java-test-fixtures` plugin, the first "-classpath" entry is ".../build/classes/kotlin/main" while with the plugin it is ".../build/libs/\<project-name\>.jar". 
Everything else is the same.
Especially the `-Xfriend-paths` compiler option did not change.
To find this information run the build(s) with `--debug` and look for `Kotlin compiler args`.

For Gradle 5.6.4
Compared with the Gradle 6.0.1 build with the `java-test-fixtures` plugin, there is an *additional* (first) entry on the Kotlin compiler's `-classpath` argument: ".../build/classes/kotlin/main".

My guess is that the issue arises because the `-classpath` and the `-Xfriend-paths` arguments deviate from each other.
To me it is not clear whether the root cause of the issue lies in the `java-test-fixtures` plugin or in the `org.jetbrains.kotlin.jvm` plugin. I'm posting this here, because there's a clear distinction (have an issue or not) depending on the Gradle version.

### Expected Behavior
The attached sample project should build without issues.

### Current Behavior
The attached sample projects fails to build with compile errors for the test sources.

### Context
It worked fine with Gradle 5.6.4 and it doesn't work with Gradle 6.0.1 (didn't test with 6.0).
With the current behaviour we either would have to restructure our build significantly or will postpone switching to Gradle 6.x until the issue is resolved.

### Steps to Reproduce 
Unpack the attached sample project, run `./gradlew clean build --rerun-tasks --no-build-cache`.
For a crosscheck either switch back to Gradle 5.6.4 or do not apply the `java-test-fixtures` plugin which is functionally unnecessary for the sample project.

### Your Environment
The build-scan service (https://scans-in.gradle.com/in/6.0.1/3.0) seems to be down right now, so I can't provide a build-scan.

My Environment:
- Kotlin 1.3.61 (same issue with 1.3.60)
- macOS 10.15.1
- OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)

**Comment by tmohme-hypoport** [comment] 2019-11-28 15:49
[kotlin-internal.zip](https://github.com/gradle/gradle/files/3902392/kotlin-internal.zip)

**Comment by joshschriever** [comment] 2019-12-02 17:51
I'm also having this problem and it's blocking me from updating to Gradle 6

**Comment by tmohme-hypoport** [comment] 2020-02-03 14:45
For others stumbling over this issue:
A possible workaround is described in [Kotlin issue KT-34901](https://youtrack.jetbrains.com/issue/KT-34901).

**Comment by oxc** [comment] 2020-06-07 22:55
> For others stumbling over this issue:
> A possible workaround is described in [Kotlin issue KT-34901](https://youtrack.jetbrains.com/issue/KT-34901).

I can't confirm that workaround solving the problem (also see https://github.com/gradle/gradle/issues/11968#issuecomment-577116263), but it seems that the issue was fixed in the Kotlin 1.4 version of the plugin (see [Kotlin Issue KT-39433](https://youtrack.jetbrains.com/issue/KT-39433))

**Comment by oxc** [comment] 2020-06-09 09:52
FYI: this was caused by the changes introduced to fix #10872

**Comment by octylFractal** [comment] 2021-11-15 19:23
I tested with 1.5.30, and the provided reproducer no longer fails to compile. Considering this fixed.

**Closed by octylFractal** 2021-11-15 19:23 UTC
Labels: in:testing, a:bug, in:java-plugins, in:integrations

**Comment by azban** [comment] 2021-11-17 21:52
I'm still seeing this issue with 1.5.30 and 1.6.0

**Comment by octylFractal** [comment] 2021-11-17 21:55
Please provide a reproducer project in full, as the one given here is working.
