### ISSUE TITLE
Gradle ignores transitive dependencies for dependency declared with `@type`

### ISSUE THREAD

**Issue by AndreasErne** [gradle/gradle#1487] opened 2017-03-02 09:38 UTC
The bug discussed in https://discuss.gradle.org/t/gradle-ignores-transitive-dependencies-when-specifying-a-classifier/2417 applies to Gradle 3.4 too.

This is very sad as it renders Gradle unusable for non-trivial dependency setups.

**Comment by asaarnak** [comment] 2017-04-05 07:16
I don't know if it's related but i had a issue with maven classifier also.
Tested on 3.4.1 and 3.5-rc3.
```
repositories {
    maven {
        url uri(theLocalMavenUri)
    }
    maven {
        url theMavenArtifactory
    }
}
dependencies {
    compileOnly(
            "com.querydsl:querydsl-apt:4.1.4:jpa",
    )
}
```
1. When only the `querydsl-apt-4.1.4.jar` without classifier is installed in local repo.
2. Then `querydsl-apt-4.1.4-jpa.jar` will fail and not fallback to the maven artifactory.
3. When using theMavenArtifactory repo first then it succeeds.
```
Could not resolve all files for configuration ':compileClasspath'.
> Could not find querydsl-apt-jpa.jar (com.querydsl:querydsl-apt:4.1.4).
  Searched in the following locations:
      file:/.m2/repository/com/querydsl/querydsl-apt/4.1.4/querydsl-apt-4.1.4-jpa.jar
```

**Comment by vadeg** [comment] 2017-05-29 13:27
Same problem in 3.5

**Comment by vadeg** [comment] 2017-05-29 13:46
@asaarnak see [GRADLE-3178](https://issues.gradle.org/browse/GRADLE-3178). It seems that bug was closed but wasn't fixed.

**Comment by asaarnak** [comment] 2017-05-29 14:01
@vadeg very similar problem, but not the same.
I had a problem with library classifier not extension.

file:/.m2/repository/com/querydsl/querydsl-apt/4.1.4/querydsl-apt-4.1.4-**jpa**.jar

**Comment by tprochazka** [comment] 2017-08-09 21:04
I have problem with this only when artifact is published to the localMaven() repository. It it is in the company Artifactory repo it works normally. But still it is big issue because I can't test the artifact locally before commit to GIT :-( Classifiers are most buggy thing on the whole Gradle.

**Comment by tprochazka** [comment] 2017-08-09 22:00
Here is debug log

> 23:52:28.052 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/C:/Users/tomas/.m2/repository/com/xyz/android/xyz-android-abcd/1.0.5-SNAPSHOT/xyz-android-abcd-1.0.5-SNAPSHOT.pom
> 23:52:28.054 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/C:/Users/tomas/.m2/repository/com/xyz/android/xyz-android-abcd/1.0.5-SNAPSHOT/xyz-android-abcd-1.0.5-SNAPSHOT.aar
> 23:52:28.054 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.MavenResolver] POM file found for module 'com.xyz.android:xyz-android-abcd:1.0.5-SNAPSHOT' in repository 'MavenLocal' but no artifact found. Ignoring.
> 23:52:28.054 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/C:/Users/tomas/.m2/repository/com/xyz/android/xyz-android-abcd/1.0.5-SNAPSHOT/xyz-android-abcd-1.0.5-SNAPSHOT-debug.aar
> 23:52:28.054 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver] Found artifact but no meta-data for module 'com.xyz.android:xyz-android-abcd:1.0.5-SNAPSHOT' in repository 'MavenLocal', using default meta-data.
> 23:52:28.054 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Detected non-existence of module 'com.xyz.android:xyz-android-abcd:1.0.5-SNAPSHOT' in resolver cache 'maven'
> 23:52:28.054 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Detected non-existence of module 'com.xyz.android:xyz-android-abcd:1.0.5-SNAPSHOT' in resolver cache 'maven2'
> 23:52:28.054 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Detected non-existence of module 'com.xyz.android:xyz-android-abcd:1.0.5-SNAPSHOT' in resolver cache 'MavenRepo'
> 23:52:28.054 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Detected non-existence of module 'com.xyz.android:xyz-android-abcd:1.0.5-SNAPSHOT' in resolver cache 'BintrayJCenter'
> 23:52:28.054 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Detected non-existence of module 'com.xyz.android:xyz-android-abcd:1.0.5-SNAPSHOT' in resolver cache 'maven3'
> 23:52:28.054 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Detected non-existence of module 'com.xyz.android:xyz-android-abcd:1.0.5-SNAPSHOT' in resolver cache 'maven4'
> 23:52:28.054 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/C:/PJazyky/_Projekty_com/xyz/xyz-cleaner/app/libs/xyz-android-abcd-1.0.5-SNAPSHOT-debug.aar
> 23:52:28.055 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/C:/PJazyky/_Projekty_com/xyz/xyz-cleaner/app/libs/xyz-android-abcd-debug.aar
> 23:52:28.055 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver] No meta-data file or artifact found for module 'com.xyz.android:xyz-android-abcd:1.0.5-SNAPSHOT' in repository 'flatDir'.
> 23:52:28.055 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Detected non-existence of module 'com.xyz.android:xyz-android-abcd:1.0.5-SNAPSHOT' in resolver cache 'maven5'
> 23:52:28.055 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver] Using com.xyz.android:xyz-android-abcd:1.0.5-SNAPSHOT from Maven repository 'MavenLocal'
> 


Interesting is this line

> 23:52:28.054 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.MavenResolver] POM file found for module 'com.xyz.android:xyz-android-abcd:1.0.5-SNAPSHOT' in repository 'MavenLocal' but no artifact found. Ignoring.

It looks that it found the pom.xml and then trying to search for the file which is not there because there is just version with classifier avast-xyz-abcd-1.0.5-SNAPSHOT-debug.aar, but then it found it in another way probably, but without pom.xml already. Very weird.

**Comment by nsoft** [comment] 2019-01-29 23:45
This looks like it might have changed slightly by 5.1.1. For a transitive dependency from a -SNAPSHOT publication to mavenLocal(). I'm now seeing the a library (and it's transitive dependencies) listed in dependencies task for compile/runtime/etc, (unlike @tprochazka)  but when I actually try to compile with `./gradlew build` it still fails, unable to find the classes in the library just shown in the dependencies output (woodstox). Unfortunately, this situation where dependencies disagree with actual compile is possibly even more confusing...
````
[build.log](https://github.com/gradle/gradle/files/2810197/build.log)
[build-dep.log](https://github.com/gradle/gradle/files/2810198/build-dep.log)
repositories {
    maven {
        url 'http://localhost:8090/repository/internal'
        credentials {
            username customerArchivaUser
            password customerArchivaPassword
        }
    }
    maven {
        url 'http://localhost:8090/repository/snapshots'
        credentials {
            username customerArchivaUser
            password customerArchivaPassword
        }
    }
    mavenLocal()
}

dependencies {
    compile (group: 'org.jesterj', name: 'jesterj-ingest', version: '1.0-SNAPSHOT') {
        transitive=true
    }
}
````
Attaching log for `clean build` vs log for `dependencies`

**Comment by big-guy** [comment] 2019-01-30 01:43
@nsoft your problem looks pretty different.  Could you open a separate issue with some more details (e.g., last version that this worked with) and if you can a stripped down project we could try?

**Comment by nsoft** [comment] 2019-01-30 16:54
Actually as an update when I went to fall back to uploading to my Archiva (irritating but doable in my case), it still didn't resolve the deps for compile. (though it was transitively resolving other stuff from Archiva previously, with released versions (1.0-beta2). So my problem seems to be less like Tomas's than I thought. Also I think I misinterpreted the phrase "classifier, type or extension" to include versions with -SNAPSHOT type suffixes, but on re-reading I suspect the OP meant "stuff after a 3rd : " instead. I had to move on so I manually added the key transitive deps I needed (which then themselves resolved transitively with no problem via archiva). If I get a chance I'll fiddle with it some more and open a ticket, probably focusing on -SNAPSHOT versions.

**Comment by nsoft** [comment] 2019-01-30 16:57
although https://github.com/gradle/gradle/issues/1487#issuecomment-304668032 makes me wonder if this isn't related after-all there's possibly some confusion between the jar name implied by 1.0-foo vs 1.0:foo...

**Comment by tprochazka** [comment] 2019-01-30 22:43
We rather stopped using classifiers in all our internal libraries, during waiting for the fix :-(

**Comment by dryganets** [comment] 2019-02-16 01:21
**The workaround for this issue is to publish your artifacts without classifier locally. Or just copy if you are too lazy to modify your build scripts :)**

I bumped into the same problem today. Spend half of the day figuring it out till found this issue. Thanks guys.
The root cause of the problem in the protection inside of the MavenLocalRepository:
https://github.com/gradle/gradle/blob/deee60cad53968d5b7f994917b818fcc2d37fb3c/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultMavenLocalArtifactRepository.java#L118
The validator has no information about classifier hence passes null so Maven dependency got ignored.

It is a miracle that in this case dependency resolution is working at all - the IvyRepository picks up the flag at the very last moment and carries it :D

**Comment by dryganets** [comment] 2019-02-16 01:43
A possible fixes in gradle are:
1. Extend the search to use regexp
1. Somehow pass the desiered classifer down to the validator (pom file have no information about classifiers)

I don't know if validation removal is an option at all, but probably somebody from the gradle team could tell better.

**Comment by dryganets** [comment] 2019-02-19 20:27
Workaround for Android:
```
// Configure the Android maven publication
apply plugin: 'com.github.dcendents.android-maven'

group = GROUP
version = VERSION

// run as `gradlew build install -PpublishFlavorless to trigger workaround locally
def publishFlavorless = project.hasProperty('publishFlavorless')
def firstTask = null

android.libraryVariants.all { variant ->
    if (variant.name.toLowerCase().contains("debug")) {
        // Workaround for https://github.com/gradle/gradle/issues/1487
        if (publishFlavorless && firstTask == null) {
            def bundleTask = tasks["bundle${variant.name.capitalize()}Aar"]
            firstTask = bundleTask
            artifacts {
                archives(firstTask.archivePath) {
                    builtBy firstTask
                    name = project.name
                }
            }
        }
        return
    }

    def bundleTask = tasks["bundle${variant.name.capitalize()}Aar"]

    artifacts {
        archives(bundleTask.archivePath) {
            classifier variant.flavorName
            builtBy bundleTask
            name = project.name
        }
    }
}

install {
    repositories.mavenInstaller {
        // This generates POM.xml with proper parameters
        pom.project {
            name POM_NAME
            artifactId POM_ARTIFACT_ID
            // Has to be 'aar' for transitive dependency to work
            packaging POM_PACKAGING
            description POM_DESCRIPTION
        }
    }
}
```

**Comment by tprochazka** [comment] 2019-02-26 22:39
@dryganets Sadly 'com.github.dcendents.android-maven' is not good workaround already, because this project is dead and not working with Gradler 5.1+, because of https://github.com/dcendents/android-maven-gradle-plugin/issues/80 

I'm currently looking for an alternative way.

**Comment by hlms** [comment] 2020-03-26 04:59
Guys, 
I wish this gets fixed sooner than letter!  
People are getting stuck into mysterious issues!

**Comment by piyushwadhwani** [comment] 2020-04-25 15:48
thats why  i hate gradle too many bugs and breaking changes

**Comment by ljacomet** [comment] 2020-04-27 08:54
@piyushwadhwani I deleted your last comment, please see https://gradle.org/conduct/

**Comment by ljacomet** [comment] 2020-05-18 12:50
This issue seems to mix a number of different things.

The title, edited a number of times, mentions using `@type`. I know this in the context of Ivy dependencies and is something not supported by Gradle (#1386).

A number of messages mention Maven classifiers.
In recent Gradle versions, using a classifier on a dependency results in the metadata being used and thus transitive dependencies are included:

`implementation group: 'com.google.inject', name: 'guice', classifier: 'no_aop', version:'3.0'`

will produce:

```
compileClasspath - Compile classpath for source set 'main'.
\--- com.google.inject:guice:3.0
     +--- javax.inject:javax.inject:1
     +--- aopalliance:aopalliance:1.0
     \--- org.sonatype.sisu.inject:cglib:2.2.1-v20090111
          \--- asm:asm:3.1
```

However using `ext` indicates to Gradle that only the specific file should be resolved and thus all metadata is ignored.

So using `implementation group: 'com.google.inject', name: 'guice', classifier: 'no_aop', version:'3.0', ext: 'jar'` results in

```
compileClasspath - Compile classpath for source set 'main'.
\--- com.google.inject:guice:3.0
```

And this is by design.

Given the different topics and age of this ticket, I would strongly recommend opening separate issues for the problems not addressed by the answer above, and linking them to here.

**Comment by ljacomet** [comment] 2020-11-17 16:52
Closing as no further work will happen in this context. In light of my previous comment, please open issue for specific points.

**Closed by ljacomet** 2020-11-17 16:52 UTC
Labels: @jvm, a:bug, closed:not-fixed, from:contributor, in:dependency-management
