### ISSUE TITLE
WorkerExecutor not considered a Gradle Managed Thread

### ISSUE THREAD

**Issue by ThadHouse** [gradle/gradle#8466] opened 2019-02-10 17:31 UTC
Resolving configurations from the Worker API has a deprecation warning. It seems like the worker should be considered a gradle managed api, so should work. 

### Expected Behavior
No  deprecation warning.

### Current Behavior
Deprecation warning `The configuration :nativeLib was resolved without accessing the project in a safe manner.`. 

### Context
We are using gradle to deploy binaries to a remote system over ssh. We don't want these ssh connections blocking the entire parallel build process, so we perform these operations with the Worker API. However, some of these operations need to check for file existence on the device before resolving the configuration. So we can't resolve configurations before starting the worker.

### Steps to Reproduce (for bugs)
1. Use a WorkerExecutor to resolve a configuration.

### Your Environment
 * Build scan URL: https://scans.gradle.com/s/hyfcomnzga76q/deprecations?openStackTraces=WyIwLTAiXQ&openUsages=WzEsMF0

**Comment by big-guy** [comment] 2019-02-10 17:50
Sorry, this is working as designed.  Why can't you resolve configurations before submitting the worker action?

Worker actions are restricted to only their serializable inputs, the worker action you have intentionally tries to go around that:
https://github.com/JacisNonsense/EmbeddedTools/blob/master/src/main/groovy/jaci/gradle/deploy/artifact/ArtifactDeployWorker.groovy#L14-L17

As part of running a worker action, we release the project lock that prevents concurrent access to project state and allows parallel execution of other worker actions/tasks.  Resolving configurations can mutate project state, so for this to work safely, the worker action would need to keep the project lock and block parallel execution. Obviously, that sort of defeats the purpose...

**Closed by big-guy** 2019-02-10 17:50 UTC

**Comment by ThadHouse** [comment] 2019-02-10 18:34
There are some cases where we depend on files on the remote system in order to know what to actually resolve. Our customer base is very sensitive to download sizes, so the least we can download the better. We could ping pong workers and tasks, and try and get some stuff working there for those requirements.

If that is the case, what is considered a Gradle Managed Thread in the context of that deprecation help document. Maybe we can solve it by moving away from the Worker to what is considered a Managed Thread.

**Comment by big-guy** [comment] 2019-02-12 07:54
I suppose, technically, the worker thread is a "Gradle Managed Thread", but the underlying problem is that we've found dependency resolution happening without a project lock.  The message is intended to provide some context for two common places we see this happening:
1. You've created a thread (via `new Thread(...)`) and you're doing dependency resolution in it.  Since that thread isn't a "Gradle Managed Thread" and there isn't a lock being held, we warn you about it.
2. From one task, you're reaching across into other another project's configurations and resolving things there. Here, you're in a "Gradle Managed Thread", but you're not holding the project lock for the configuration being resolved. 

You're sort of falling between these two cases.  You're in a "Gradle Managed Thread" (the worker), but you're effectively reaching into another project and doing dependency resolution without a project lock.  Without a project lock, you're treading into unsafe behavior that can cause strange errors when the same project is mutated at the same time or deadlocks. This is why we're warning about this now. This has always been unsafe, but we've only now started to detect it.

A few options...
1) Resolve the configuration before submitting the actions to the worker and deal with the fallout from that.
2) Stop using the worker API and go back to doing everything in the task action. This keeps the project lock, but blocks everything else.
3) Do the work to gather what you need to know about the remote system, figure out if you need to do dependency resolution and do it (or not), then submit the actions to the workers.
4) Live dangerously with the unsafe behavior (could cause deadlocks, random failures, concurrency failures)

**Comment by gervarro** [comment] 2021-12-13 22:52
@big-guy: Could you please give some hints what are exactly considered as "Gradle Managed Threads"?

I got the same warning when dependency resolution was carried out in a `gradle.projectsEvaluated { }` block. Are these notification processing actions not managed by Gradle? Why is it wrong to resolve dependencies in these notification processing blocks?
