### ISSUE TITLE
Transient error with incremental Groovy compilation

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#9963] opened 2019-07-16 08:47 UTC
I got this error more than once now:

```text
* What went wrong:
Execution failed for task ':core:compileIntegTestGroovy'.
> Duplicate key org.gradle.JansiEndUserIntegrationTest (attempted merging values /Users/lptr/Workspace/gradle/gradle/subprojects/core/src/integTest/groovy/org/gradle/JansiEndUserIntegrationTest.groovy and org/gradle/JansiEndUserIntegrationTest.groovy)
```

It goes away after running `clean`.

Build scan: https://e.grdev.net/s/daipugfy2s6d6

**Comment by ghale** [comment] 2019-07-16 13:26
I saw this recently as well.  My experience was that it went away after just re-running the compile task (no `clean` necessary).

**Comment by wolfs** [comment] 2019-07-17 07:01
This is a duplicate of https://github.com/gradle/gradle/issues/9936. Right @blindpirate?

**Comment by blindpirate** [comment] 2019-07-17 08:13
Yes. @lptr A quick workaround would be `find . -name '*mapping.txt' | xargs rm -rf`. Sorry for the inconvinence.

Closing due to duplication.

**Closed by blindpirate** 2019-07-17 08:13 UTC
Labels: @dev-productivity
