### ISSUE TITLE
[4.6] - Filtering tests when there is a failure, "No tests found" error message and no test reports generated

### ISSUE THREAD

**Issue by jaredsburrows** [gradle/gradle#4718] opened 2018-03-14 02:09 UTC
## Description:
Running `gradlew test --tests="*LicenseReportTaskJavaSpec*"` causing 2 issues:
1. No test report
2. `No tests found for given includes` error even though it does run the test
3. This project is also using the new `failFast` feature

## Error:
```
5 tests completed, 1 failed


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> No tests found for given includes: [*LicenseReportTaskJavaSpec*](--tests filter)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
7 actionable tasks: 7 executed
```

## Repro:
```
git clone https://github.com/jaredsburrows/gradle-license-plugin
cd gradle-license-plugin
Mess up a random test to get it to fail
gradlew test --tests="*TestName*"
```

**Comment by oehme** [comment] 2018-03-14 09:57
Do you also see this without `failFast`?

**Comment by jaredsburrows** [comment] 2018-03-14 10:03
@oehme No. Only with `failFast`.

**Comment by oehme** [comment] 2018-03-14 13:12
Got it, thanks! @acourtneybrown would you mind looking into this? Sounds like a regression caused by our new fail-fast feature.

**Comment by acourtneybrown** [comment] 2018-03-14 22:02
@jaredsburrows it looks like you didn't push your `jb/map-packages-to-full-license` branch to the repo you mentioned.  Would you please do that & let me know when it's there?

**Comment by jaredsburrows** [comment] 2018-03-14 23:06
@acourtneybrown Sorry about that. I merged that branch already.

All you need to do is checkout the project, mess up a test and then run `gradlew test --tests="*TestName*"`.

**Comment by acourtneybrown** [comment] 2018-03-19 20:40
Fixed by #4752

**Closed** 2018-03-19 20:41 UTC
Labels: a:bug, affects-version:4.6, from:contributor, in:testing

**Comment by jaredsburrows** [comment] 2018-03-20 03:14
Thanks @acourtneybrown!

**Comment by nikhil09541** [comment] 2020-07-30 10:38
@acourtneybrown : I am facing same issue while running the groovy test on my machine. While running the whole bundle of tests all of them pass. But I am unable to run a single test in the repo.
