### ISSUE TITLE
Response 304: Not Modified has no content

### ISSUE THREAD

**Issue by ilya-g** [gradle/gradle#4703] opened 2018-03-13 14:13 UTC
I'm getting intermittent failures during resolving dependencies on the build server.

```
	* What went wrong:
	Execution failed for task ':kotlin-gradle-plugin-api:compileKotlin'.
	> Could not resolve all files for configuration ':kotlin-gradle-plugin-api:compileClasspath'.
	   > Could not download bcpkix-jdk15on.jar (org.bouncycastle:bcpkix-jdk15on:1.48)
	      > Could not get resource 'https://jcenter.bintray.com/org/bouncycastle/bcpkix-jdk15on/1.48/bcpkix-jdk15on-1.48.jar'.
	         > Response 304: Not Modified has no content!
```

The error message is not clear to me: the HTTP response 304 is expected to have no content.

### Your Environment

* Gradle 4.5.1
* Ubuntu 16.04
* Link to the build log: https://teamcity.jetbrains.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=1348545&_focus=21541 (Use Login as guest if required)

**Comment by ltm** [comment] 2018-03-13 18:38
We're seeing the same thing with Gradle 3.3. I believe it's caused by an incorrectly configured Bintray CDN.

An HTTP HEAD request returns `ETag: 28b7614b908a47844bb27e3c94b45b6893656265`:

```
$ curl -I https://jcenter.bintray.com/org/bouncycastle/bcpkix-jdk15on/1.48/bcpkix-jdk15on-1.48.jar
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 13 Mar 2018 18:25:27 GMT
Content-Type: application/java-archive
Content-Length: 585181
Connection: keep-alive
Last-Modified: Tue, 12 Feb 2013 06:30:34 GMT
Accept-Ranges: none
ETag: 28b7614b908a47844bb27e3c94b45b6893656265
X-Checksum-Sha1: 28b7614b908a47844bb27e3c94b45b6893656265
```

However, an HTTP GET request returns a redirect to `akamai.bintray.com` which returns `ETag: "f8fc0496846f567ec951ac0a0e25ed00:1453438212"`:

```
$ curl -sL -D - https://jcenter.bintray.com/org/bouncycastle/bcpkix-jdk15on/1.48/bcpkix-jdk15on-1.48.jar -o /dev/null 
HTTP/1.1 302 
Server: nginx
Date: Tue, 13 Mar 2018 18:25:43 GMT
Content-Length: 0
Connection: keep-alive
Location: https://akamai.bintray.com/28/28b7614b908a47844bb27e3c94b45b6893656265?[snip]

HTTP/1.1 200 OK
Accept-Ranges: bytes
ETag: "f8fc0496846f567ec951ac0a0e25ed00:1453438212"
Last-Modified: Tue, 12 Feb 2013 06:30:34 GMT
Server: AkamaiNetStorage
Content-Length: 585181
Date: Tue, 13 Mar 2018 18:25:43 GMT
Connection: keep-alive
Content-Type: application/octet-stream
content-disposition: attachment;filename="bcpkix-jdk15on-1.48.jar"
```

**Comment by ltm** [comment] 2018-03-13 21:02
We're seeing the same thing with Gradle 3.3.

It appears to be a misconfiguration of the Bintray CDN. Akamai intermittently responds with `304 Not Modified` for requests made without precondition headers (e.g. `If-Modified-Since`, `If-None-Match`):

```
$ curl -H 'Pragma: akamai-x-cache-on, akamai-x-cache-remote-on, akamai-x-check-cacheable, akamai-x-get-cache-key, akamai-x-get-ssl-client-session-id, akamai-x-get-true-cache-key, akamai-x-get-request-id' -s -D - 'https://akamai.bintray.com/28/28b7614b908a47844bb27e3c94b45b6893656265?[snip]' -o /dev/null
HTTP/1.1 304 Not Modified
Last-Modified: Tue, 12 Feb 2013 06:30:34 GMT
ETag: "f8fc0496846f567ec951ac0a0e25ed00:1453438212"
Date: Tue, 13 Mar 2018 20:41:36 GMT
X-Cache: TCP_HIT from a23-50-225-223.deploy.akamaitechnologies.com (AkamaiGHost/9.2.4-22045714) (-)
X-Cache-Key: S/=/10390/422085/365d/jfrog.download.akamai.com/338731/production/28/28b7614b908a47844bb27e3c94b45b6893656265
X-True-Cache-Key: /=/jfrog.download.akamai.com/338731/production/28/28b7614b908a47844bb27e3c94b45b6893656265
Connection: keep-alive
Content-Type: application/octet-stream
content-disposition: attachment;filename="bcpkix-jdk15on-1.48.jar"
X-Check-Cacheable: YES
X-Akamai-Request-ID: 1effd9fd
```

**Comment by ltm** [comment] 2018-03-13 21:33
To further clarify, it appears to always be the Akamai backend `a23-50-225-223.deploy.akamaitechnologies.com`:

```
$ curl -H 'Pragma: akamai-x-cache-on' -sL -D - 'https://jcenter.bintray.com/org/bouncycastle/bcpkix-jdk15on/1.48/bcpkix-jdk15on-1.48.jar' -o /dev/null
HTTP/1.1 302 
Server: nginx
Date: Tue, 13 Mar 2018 21:31:06 GMT
Content-Length: 0
Connection: keep-alive
Location: https://akamai.bintray.com/28/28b7614b908a47844bb27e3c94b45b6893656265?[snip]

HTTP/1.1 304 Not Modified
Last-Modified: Tue, 12 Feb 2013 06:30:34 GMT
ETag: "f8fc0496846f567ec951ac0a0e25ed00:1453438212"
Date: Tue, 13 Mar 2018 21:31:06 GMT
X-Cache: TCP_HIT from a23-50-225-223.deploy.akamaitechnologies.com (AkamaiGHost/9.2.4-22045714) (-)
Connection: keep-alive
Content-Type: application/octet-stream
content-disposition: attachment;filename="bcpkix-jdk15on-1.48.jar"
```

Other backends return `200 OK`:

```
$ curl -H 'Pragma: akamai-x-cache-on' -sL -D - 'https://jcenter.bintray.com/org/bouncycastle/bcpkix-jdk15on/1.48/bcpkix-jdk15on-1.48.jar' -o /dev/null
HTTP/1.1 302 
Server: nginx
Date: Tue, 13 Mar 2018 21:31:10 GMT
Content-Length: 0
Connection: keep-alive
Location: https://akamai.bintray.com/28/28b7614b908a47844bb27e3c94b45b6893656265?[snip]

HTTP/1.1 200 OK
Server: Apache
ETag: "f8fc0496846f567ec951ac0a0e25ed00:1453438212"
Last-Modified: Tue, 12 Feb 2013 06:30:34 GMT
Accept-Ranges: bytes
Content-Length: 585181
Date: Tue, 13 Mar 2018 21:31:10 GMT
X-Cache: TCP_HIT from a23-50-225-229.deploy.akamaitechnologies.com (AkamaiGHost/9.2.4-22045714) (-)
Connection: keep-alive
Content-Type: application/octet-stream
content-disposition: attachment;filename="bcpkix-jdk15on-1.48.jar"
```

This explains the intermittent nature of this problem.

**Comment by aistomin** [comment] 2018-03-15 10:22
Is any workaround available to solve this problem? As I'm a kinda newbie to Gradle I feel completely helpless and my development process is completely blocked. :) I would appreciate any hint.

**Comment by ltm** [comment] 2018-03-15 17:00
@aistomin There are a few things you can try as workarounds:
* Replace `jcenter()` with `jcenter { url "http://jcenter.bintray.com" }` in `build.gradle`
* Replace `jcenter()` with `mavenCentral()` in `build.gradle`
* Run your build in a different region (if running on AWS try `us-west-2` instead of `us-east-1`)

**Comment by mike866** [comment] 2018-03-16 13:48
I'm experiencing same issue while building android app on CircleCI. Workarounds listed above doesn;t seem to solve the issue. Any other ideas?

**Comment by erchenger** [comment] 2018-03-16 16:19
Kinda surprising this is not showing up on their http://status.bintray.com/.

**Comment by joaspacce** [comment] 2018-03-16 22:18
Any updates on this issue?

**Comment by ltm** [comment] 2018-03-19 13:11
I reached out to JFrog support and they confirmed they're working on resolving the issue. They've updated http://status.bintray.com, so I would check there for updates going forward.

**Comment by michaelknoch** [comment] 2018-03-23 10:39
has there been any progress?

**Comment by michaelknoch** [comment] 2018-03-23 17:05
is there a known workaround? My build on circleCI is broken since days

**Comment by ltm** [comment] 2018-03-25 16:13
JFrog just fixed the issue. I've confirmed that we're no longer getting `304 Not Modified`.

**Comment by aistomin** [comment] 2018-03-25 16:21
@ltm I do not think it's true, I got the error a minute ago.

**Comment by ltm** [comment] 2018-03-25 16:29
@aistomin Okay, I'll let them know. It might help if you could post the output of the following command (where `[path]` is a file that returns `304 Not Modified`):

```
curl -H 'Pragma: akamai-x-cache-on, akamai-x-cache-remote-on, akamai-x-check-cacheable, akamai-x-get-cache-key, akamai-x-get-ssl-client-session-id, akamai-x-get-true-cache-key, akamai-x-get-request-id' -sL -D - 'https://jcenter.bintray.com/[path]' -o /dev/null
```

**Comment by aistomin** [comment] 2018-03-25 16:36
@ltm I can not reproduce it locally, it happens in Bitbucket-Pipelines Docker. The only thing I see is:
```
* What went wrong:
A problem occurred configuring root project 'build'.
> Could not resolve all files for configuration ':classpath'.
   > Could not download bcpkix-jdk15on.jar (org.bouncycastle:bcpkix-jdk15on:1.48)
      > Could not get resource 'https://jcenter.bintray.com/org/bouncycastle/bcpkix-jdk15on/1.48/bcpkix-jdk15on-1.48.jar'.
         > Response 304: Not Modified has no content!
``` 
Is it also not constantly reproduceable: like 3 of 10 builds are failing.  It was never constantly reproduceable for me.

**Comment by ltm** [comment] 2018-03-25 16:38
@aistomin Would you be able to run the curl command as part of your build script?

**Comment by aistomin** [comment] 2018-03-25 16:58
@ltm Here we go:
```
+ curl -H "$PRAGMA_PARAM" -sL -D - 'https://jcenter.bintray.com/org/bouncycastle/bcpkix-jdk15on/1.48/bcpkix-jdk15on-1.48.jar' -o /dev/null
HTTP/1.1 302 
Server: nginx
Date: Sun, 25 Mar 2018 16:56:18 GMT
Content-Length: 0
Connection: keep-alive
Location: https://akamai.bintray.com/28/28b7614b908a47844bb27e3c94b45b6893656265?__gda__=exp=1521997698~hmac=e9c8efd78f4bb07325f9decbe44071f174be5b619248e36393429e99358311c1&response-content-disposition=attachment%3Bfilename%3D%22bcpkix-jdk15on-1.48.jar%22&response-content-type=application%2Foctet-stream&requestInfo=U2FsdGVkX1817xgC2KIZ70epHcm1WQPObqB8ehaz_aOioSpR1MNJE8aYY7X4rQW8qqHHQoaK5L2VSrDGy4ZoWrsVbXwlge_7mJef5diBo8PIR56jPLlYByFc57m4wwYycXkPYszMFzkf3KVl70uH5qMEHgD00vRCh8saAfIk8NU
HTTP/1.1 304 Not Modified
Last-Modified: Tue, 12 Feb 2013 06:30:34 GMT
ETag: "f8fc0496846f567ec951ac0a0e25ed00:1453438212"
Date: Sun, 25 Mar 2018 16:56:19 GMT
X-Cache: TCP_HIT from a23-50-225-223.deploy.akamaitechnologies.com (AkamaiGHost/9.2.4-22045714) (-)
X-Cache-Key: S/=/10390/422085/365d/jfrog.download.akamai.com/338731/production/28/28b7614b908a47844bb27e3c94b45b6893656265
X-True-Cache-Key: /=/jfrog.download.akamai.com/338731/production/28/28b7614b908a47844bb27e3c94b45b6893656265
Connection: keep-alive
Content-Type: application/octet-stream
content-disposition: attachment;filename="bcpkix-jdk15on-1.48.jar"
X-Check-Cacheable: YES
X-Akamai-Request-ID: 62f206d8
```
`PRAGMA_PARAM` variable is what you've said: `'Pragma: akamai-x-cache-on, akamai-x-cache-remote-on, akamai-x-check-cacheable, akamai-x-get-cache-key, akamai-x-get-ssl-client-session-id, akamai-x-get-true-cache-key, akamai-x-get-request-id'` (Bitbucket has a bug with yaml parsing, so I needed to wrap it into environment variable).

**Comment by Apsaliya** [comment] 2018-03-26 05:35
http://status.bintray.com/# still shows status `Intermittent download failures`.

**Comment by joaspacce** [comment] 2018-03-26 14:07
Hi, I made it work onn my CircleCI build adding `mavenCentral()` on top of `jcenter()` in the top level `build.gradle`.

e.g.:
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        mavenCentral()
        jcenter()        
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        mavenCentral()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}

subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 25
                buildToolsVersion '25.0.0'
            }
        }
    }
}
```

**Comment by aistomin** [comment] 2018-03-29 07:32
The problem is solved for me. Yesterday and today I had more than 10 successful builds and not a single fail.

**Comment by Apsaliya** [comment] 2018-03-30 06:09
Me too. BB pipelines are going through now.

**Comment by pioterj** [comment] 2018-04-09 14:28
This was a temporary issue with Bintray, closing.

**Closed by pioterj** 2018-04-09 14:28 UTC
Labels: a:bug, from:contributor, in:dependency-management

**Comment by ilya-g** [comment] 2018-04-09 17:04
@pioterj I don't get why this has been closed. While the bintray issue has been gone, the error message is still unclear.
I'd expect something like "Response 304 is unexpected"

**Comment by pioterj** [comment] 2018-04-10 10:59
@ilya-g I thought the primary issue was regarding intermittent failures. This is what most people commented on anyway. To avoid confusion, would you mind opening a separate issue for the error message itself?

**Comment by PayelKarmakar06** [comment] 2019-07-09 07:18
> maven {
>             // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
>             url "$rootDir/../node_modules/react-native/android"
>         }

Why this maven declaration was required (the last one)? I am using Ionic Native, what would be the url for me?
