### ISSUE TITLE
Could not write standard input to Gradle Worker Daemon

### ISSUE THREAD

**Issue by pinxiong** [gradle/gradle#15665] opened 2020-12-30 09:54 UTC
### Expected Behavior

I wannt build the project of [grpc-java](https://github.com/grpc/grpc-java/tree/v1.34.x)
### Current Behavior

When I use gradle to build the project, an exception occurred as follows:
![gradle bug](https://user-images.githubusercontent.com/7067417/103342933-ba53d100-4ac5-11eb-9ee2-23c072603013.png)

### Context

I wannt build the project of [grpc-java](https://github.com/grpc/grpc-java/tree/v1.34.x) for study, which I can debug the `grpc-java` 's source codes.

### Steps to Reproduce 

1. Download the [grpc-java](https://github.com/grpc/grpc-java/tree/v1.34.x) project
2. Create $project-root$/`gradle.properties` file
3. Add `skipAndroid=true` and `skipCodegen=true` in `gradle.properties` file
4. Use Windows `cmd` to run `gradle build` or Use IDEA terminal to run `gradlew build`

### Your Environment

Build scan URL: https://scans.gradle.com/s/33robo6iif7o6
Operating System: Windows 10
Machine: desktop
JDK: openjdk 1.8.0_265

**Comment by mayspb** [comment] 2021-02-19 09:33
I left comment on your [previous report](https://github.com/grpc/grpc-java/issues/7767#issuecomment-781607326_). May be downgrading java version would resolve this issue.

**Comment by pinxiong** [comment] 2021-02-19 15:33
> I left comment on your [previous report](https://github.com/grpc/grpc-java/issues/7767#issuecomment-781607326_). May be downgrading java version would resolve this issue.

Thanks for your help, I'll try it.

**Comment by mlopatkin** [comment] 2021-08-04 16:15
I believe the IOException is a red herring there. The actual problem is that the worker process failed to start because of
```
java.lang.InternalError: Could not create SecurityManager: worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager   
  at sun.misc.Launcher.<init>(Launcher.java:106)   
  at sun.misc.Launcher.<clinit>(Launcher.java:54)   
  at java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:1444) 
  at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:1429)
```

This error indicates that the worker process failed to start. Unfortunately, it is hard to say what went wrong without a reproducer. There are multiple potential reasons for that failure, e. g. corrupted data in `$GRADLE_USER_HOME` folder. See https://github.com/gradle/gradle/issues/4689#issuecomment-803924544 for some advice.

@pinxiong, are you still able to reproduce the issue by chance? I'll close the issue otherwise because we cannot proceed without more information.

**Comment by pinxiong** [comment] 2021-08-05 01:16
@mlopatkin I don't have the previous environment to reproduce this issue because it has been over for a long time, and I have chosen another way to meet my needs.

**Comment by mlopatkin** [comment] 2021-08-05 07:50
> @mlopatkin I don't have the previous environment to reproduce this issue because it has been over for a long time, and I have chosen another way to meet my needs.

Thanks, that is understandable. Sorry, we didn't get to this issue in time.

**Closed by mlopatkin** 2021-08-05 07:50 UTC
Labels: a:bug, in:workers, to-triage
