### ISSUE TITLE
Signing plugin signing.gnupg.passphrase is not being picked up while signing artifacts

### ISSUE THREAD

**Issue by CuriousNikhil** [gradle/gradle#17314] opened 2021-05-30 05:46 UTC
Hi, I'm on how to use signing on Gradle 7.0 (I’m using gradle 7.0 Kotlin dsl -  To sign the artifact)

```
signing {
    useGpgCmd()
    sign(publishing.publications["somePublicatioin"])
}
```

According to documentation I’ve tried setting up the keyName and passphrase in my `gradle.properties`
https://docs.gradle.org/current/userguide/signing_plugin.html#example_configure_the_gnupgsignatory
```
signing.gnupg.executable=gpg
signing.gnupg.useLegacyGpg=true
signing.gnupg.keyName=24875D73
signing.gnupg.passphrase=password
```
But everytime when I’m running ./gradlew publish , gnupg is asking me to put the passphrase

![image](https://user-images.githubusercontent.com/16976114/120093518-75959a00-c138-11eb-8ae7-007850d2879c.png)

Any idea why is this happening?

**Comment by bmuskalla** [comment] 2021-05-31 08:45
@CuriousNikhil Could you provide a small reproducer (without keys :) ) for us? Thanks!

**Comment by runningcode** [comment] 2021-06-01 15:59
This seems like a duplicate of https://github.com/gradle/gradle/issues/11706

**Comment by mlopatkin** [comment] 2021-06-01 16:12
> This seems like a duplicate of #11706
> A reproducer project is available in this ticket as well: #17300

My understanding is that this bug is about unexpected passphrase entry screen (passphrase is already provided in properties) while others are about broken passphrase screen.

**Comment by runningcode** [comment] 2021-06-01 16:26
Yeah, you are right @mlopatkin. I saw that screenshot and my brain short circuited to the other issue :)

**Comment by mlopatkin** [comment] 2021-06-16 16:10
@CuriousNikhil what version of the GnuPG are you using (i.e. what is the output of `gpg --version`)? I see the warning about `--no-use-agent` being obsolete so I strongly suspect that you are using GnuPG 2.x. For 2.x you should specify `signing.gnupg.useLegacyGpg=false` or just omit this line completely as it is a default, otherwise the password won't be picked up and you'll see the prompt.

**Comment by mlopatkin** [comment] 2021-06-25 15:37
Closing the issue as there is no response and the observed behavior is somewhat intended.

**Closed by mlopatkin** 2021-06-25 15:37 UTC
Labels: a:bug, in:signing-plugin
