### ISSUE TITLE
Extract gradle daemon to a separate service

### ISSUE THREAD

**Issue by purpleP** [gradle/gradle#13685] opened 2020-07-04 09:19 UTC
Motivations is to be able to run builds in docker without sacrificing any performance.

Let's say the team uses `gradle` as a generic build tool not just java code. This means that certain tasks have dependencies like `npm`, `yarn` etc of arbitrary complexity.
What a the ways to tackle this? I know basically two ways - `nix` and `docker`.
`Nix` is a very good idea and probably ultimately better but it has problems with build speed, incremental builds and it's still not that popular.
`Docker` on the other hand is already industry standard of deploying software, has good support on mac and windows etc. It's already used in tools like Jenkins as one of the way to specify build environment.

So my vision is that developer shouldn't have to setup his machine to build particular software in any way except of installing docker (or nix).
Then he uses some kind of easily discoverable method to build software inside of a container (`make` for example).

It can be done with gradle, but one would loose some efficiency because of the daemon. Or one would have to use experimental file-watch feature which wouldn't help in Jenkins environments anyway.

In any case I think "explicit is better than implicit" applies here. Making daemon a separate service would also have the benefit of being able to to distributed builds probably.

**Comment by ov7a** [comment] 2023-09-20 12:27
Sorry for the late reply.

***

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/17511

Please add your use case and 👍 to that issue.

***

We currently don't have plans to extract the Gradle daemon into a separate remote service.

**Closed by ov7a** 2023-09-20 12:27 UTC
Labels: a:feature, to-triage
