### ISSUE TITLE
Invalid detection of Java 8 version on Alpine Linux

### ISSUE THREAD

**Issue by piotrminkina** [gradle/gradle#28873] opened 2024-04-18 16:28 UTC
### Current Behavior

```console
$ ./gradlew javaToolchains

> Task :javaToolchains

 + Options
     | Auto-detection:     Enabled
     | Auto-download:      Enabled

 + Alpine JDK 17.0.10+7-alpine-r0
     | Location:           /usr/lib/jvm/java-17-openjdk
     | Language Version:   17
     | Vendor:             Alpine
     | Architecture:       amd64
     | Is JDK:             true
     | Detected by:        Common Linux Locations

 + Alpine JDK 17.0.10+7-alpine-r0
     | Location:           /usr/lib/jvm/java-1.8-openjdk
     | Language Version:   17
     | Vendor:             Alpine
     | Architecture:       amd64
     | Is JDK:             true
     | Detected by:        Common Linux Locations
```

Giving JAVA_HOME variable gives better results, but still not ideal. I don't understand why Gradle detected "IcedTea JDK" here.

```console
$ JAVA_HOME=/usr/lib/jvm/java-8-openjdk/ ./gradlew javaToolchains

> Task :javaToolchains

[...]

 + IcedTea JDK 1.8.0_402-b06
     | Location:           /usr/lib/jvm/java-1.8-openjdk
     | Language Version:   8
     | Vendor:             IcedTea
     | Architecture:       amd64
     | Is JDK:             true
     | Detected by:        Common Linux Locations

```

### Expected Behavior

```console
$ ./gradlew javaToolchains

> Task :javaToolchains

 + Options
     | Auto-detection:     Enabled
     | Auto-download:      Enabled

 + Alpine JDK 17.0.10+7-alpine-r0
     | Location:           /usr/lib/jvm/java-17-openjdk
     | Language Version:   17
     | Vendor:             Alpine
     | Architecture:       amd64
     | Is JDK:             true
     | Detected by:        Common Linux Locations

 + Alpine JDK 1.8.0_402-b06
     | Location:           /usr/lib/jvm/java-1.8-openjdk
     | Language Version:   8
     | Vendor:             Alpine
     | Architecture:       amd64
     | Is JDK:             true
     | Detected by:        Common Linux Locations
```

### Context (optional)

Despite the existing installation of Java version 1.8, Gradle is unable to build a project that requires this version of Java to compile. There is my build file:

```gradle
plugins {
    id 'java'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

tasks.named('wrapper') {
    gradleVersion = '8.7'
}
```

And this is the result of the build:

```console
$ ./gradlew assemble

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileJava'.
> Could not resolve all dependencies for configuration ':compileClasspath'.
   > Failed to calculate the value of task ':compileJava' property 'javaCompiler'.
      > Cannot find a Java installation on your machine matching this tasks requirements: {languageVersion=8, vendor=any, implementation=vendor-specific} for LINUX on x86_64.
         > No locally installed toolchains match and toolchain download repositories have not been configured.
```

### Steps to Reproduce

1. Prepare a project directory with Gradle Wrapper and a build file containing above source.
2. Get the Alpine Linux v3.19 distribution or run this command: `docker run --rm -it -w /project -v "$PWD:/project" alpine:3.19 sh`
3. Install Java JDK version 8 and another one with higher version (I installed version 17): `apk --update add openjdk8-jdk openjdk17-jdk`
4. Run the command `./gradlew javaToolchains` and/or try to compile some Java source.

### Gradle version

8.2.1, 8.7

### Your Environment (optional)

* Ubuntu 22.04.4 LTS (host)
* Docker version 20.10.18, build b40c2f6
* Alpine Linux 3.19.1 (container)

**Comment by ov7a** [comment] 2024-04-19 07:43
This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/24300

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

See [the docs](https://docs.gradle.org/current/userguide/toolchains.html#sec:limitations).

**Closed by ov7a** 2024-04-19 07:43 UTC
Labels: a:bug, to-triage

**Comment by piotrminkina** [comment] 2024-04-19 08:05
@ov7a Thank you for the clarification, sorry for the inconvenience.
