### ISSUE TITLE
Improve Diagnostics for: No matching configuration of project...

### ISSUE THREAD

**Issue by kolotyluk** [gradle/gradle#23869] opened 2023-02-10 22:56 UTC
### Expected Behavior
The diagnostics should be clear and easy to comprehend without having to read the minds of the developers who write the diagnostics.

### Current Behavior
Diagnostics are often abstruse and hard to fathom, as if whoever wrote the diagnostics expects us to read their mind.

### Context

    jas-lib % gradle clean build
    
    > Configure project :elastic-store
    Using INDEXER: elastic
    
    > Configure project :eps-store
    Using DB: cassandra
    
    > Configure project :opensearch-store
    Using INDEXER: elastic

    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Could not determine the dependencies of task ':compileGroovy'.
    > Could not resolve all task dependencies for configuration ':compileClasspath'.
       > Could not resolve project :common-utils.
         Required by:
             project :
          > No matching configuration of project :common-utils was found. The consumer was configured to find an API of a library compatible with Java 11, preferably not packaged as a jar, preferably optimized for standard JVMs, and its dependencies declared externally but:
              - None of the consumable configurations have attributes.

This issue is affecting my sanity.

I am trying to resolve the error, but there is too much jargon, and not enough ***useful*** details. I know there is possibly some problem with Java versions, but too often Gradle complains about things that have nothing to do with the actual problem, so Gradle diagnostics can generally not be trusted to be accurate.

What do you mean in the template comments by

    What other alternatives have you considered?

#### Specifically 

1. `The consumer was configured...`
   1. You should state the name of the consumer here so that I don't have to guess.
   2. Is `:opensearch-store` the consumer or is `:common-utils` the consumer?
   3. The relationship between producer and consumer should be explicitly clear, such as the names.
1. `project:`
   1. Why is there nothing after this. Does Gradle not know at this point what project it is referring to?

### Misc

    ------------------------------------------------------------
    Gradle 7.6
    ------------------------------------------------------------
    
    Build time:   2022-11-25 13:35:10 UTC
    Revision:     daece9dbc5b79370cc8e4fd6fe4b2cd400e150a8
    
    Kotlin:       1.7.10
    Groovy:       3.0.13
    Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
    JVM:          11.0.13 (Azul Systems, Inc. 11.0.13+8-LTS)
    OS:           Mac OS X 13.2 aarch64

**Comment by kolotyluk** [comment] 2023-02-13 22:06
Our of curiosity, I tried Chat GPT

    What does the following Gradle error mean? * What went wrong:
    Could not determine the dependencies of task ':compileGroovy'.
    > Could not resolve all task dependencies for configuration ':compileClasspath'.
       > Could not resolve project :common-utils.
         Required by:
             project :
          > No matching configuration of project :common-utils was found. The consumer was configured to find an API of a     library compatible with Java 11, preferably not packaged as a jar, preferably optimized for standard JVMs, and its     dependencies declared externally but:
              - None of the consumable configurations have attributes.

Generating the answer

    This Gradle error message is indicating that there's a problem with resolving the dependencies of the task  ':compileGroovy'. Specifically, it's having trouble resolving the project ":common-utils", which is a required dependency for the current project.

    The message says that "No matching configuration of project :common-utils was found", meaning that Gradle was unable to find the necessary information to build the project, such as the location of the source code or the dependencies required to build it. This could be due to a variety of reasons, such as a missing or incorrect entry in the build file or a misconfigured repository.

    Additionally, the message mentions that the consumer of the library is configured to find an API compatible with Java 11 and its dependencies declared externally, but none of the consumable configurations have attributes. This could indicate a mismatch between the Java version specified in the build file and the version required by the ":common-utils" project.

    To resolve this issue, you should first verify that the ":common-utils" project is correctly configured and that its dependencies are declared correctly in its build file. You should also ensure that the Java version specified in your build file matches the version required by the ":common-utils" project.

While this response did not directly solve my problem, it did give me more to think about and investigate.

Eventually, I did solve the problem, but it was not easy, and it's too twisted a problem to describe the solution.

**Comment by eskatos** [comment] 2023-02-21 10:14
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/12126

Please add your 👍 to that issue.

----

The consumer here is the `:compileClasspath` configuration resolved for the `:compileGroovy` task in the root project as shown in the contextual error diagnostic tree. The link to the root project is implicit because `:compileGroovy` means the `compileGroovy` task in the root project `:`. In a sub project you would have got `:my-subproject:compileGroovy`.

Just opened an issue about clarifying this last point at
*  https://github.com/gradle/gradle/issues/23986

**Closed by eskatos** 2023-02-21 10:14 UTC
Labels: a:feature, to-triage
