### ISSUE TITLE
build cache key consistent, but build cache always misses

### ISSUE THREAD

**Issue by liblit** [gradle/gradle#8584] opened 2019-02-22 02:56 UTC
### Expected Behavior

When the build cache is enabled for a given task, and that task’s build cache key does not change from one build to the next, outputs created in one build should be retrieved from the cache in subsequent builds instead of being rebuilt.

### Current Behavior

The build cache key for my task is unchanging, but the task’s outputs are never retrieved from the cache. They are stored into the cache after each rebuild, but the cache always misses the next time around.

### Context

I have [a custom task class](https://github.com/wala/WALA/blob/master/buildSrc/src/main/groovy/verified-download.groovy), implemented in Groovy. It is a `@CacheableTask` with several `@Input` properties plus one `@OutputFile` property. Both `--scan` and `-Dorg.gradle.caching.debug=true` show that the build cache for a given task instance remains consistent: it does not change each time I rebuild. In spite of this, the build cache never hits.

For example, [one build scan](https://scans.gradle.com/s/faxy7kogsylyo/timeline?showCache&task=sc3m56t5pbcmg) shows:

> |Build cache result |Miss (local), Store (local)|
> |---|---|
> |Cache key|8dde787e4212662d5cefe1cd040b401d|
> |Cache artifact|39.58 kB / 2 entries|
> |Pack|0.021s|

After manually removing the output file and running a second build, [the second build’s scan](https://scans.gradle.com/s/umfa742v2tnrm/timeline?showCache&task=sc3m56t5pbcmg) shows:

> |Build cache result |Miss (local), Store (local)|
> |---|---|
> |Cache key|8dde787e4212662d5cefe1cd040b401d|
> |Cache artifact|39.58 kB / 2 entries|
> |Pack|0.026s|

Notice that the cache key has not changed. In spite of this, the “Store (local)” from the first build was followed by a “Miss (local)” in the second build. Why did the second build miss given that the first build stored the artifact and the key remained the same?

I can see the gzip’d tar archive stored in `~/.gradle/caches/build-cache-1/8dde787e4212662d5cefe1cd040b401d`. But if I remove the task’s output file and rebuild, Gradle always performs the task’s work anew, rather than using the copy stored in the build cache. Gradle even replaces this stored copy with the newly-rebuilt task output.

All documentation I can find on debugging the build cache focuses on figuring out why the build cache key is changing. **My build cache key is not changing.** How do I diagnose build cache misses when the problem is *not* due to unwanted build key changes?

### Steps to Reproduce (for bugs)

1. Clone the [WALA project](https://github.com/wala/WALA) and check out the `master` branch.

1. Run `./gradlew downloadJLex -Dorg.gradle.caching.debug=true` to perform one of the many downloads used when building this project. Make a note of the final build cache key computed for task `:com.ibm.wala.cast.java.test.data:downloadJLex`.

1. Remove the entire `com.ibm.wala.cast.java.test.data/src/JLex` subdirectory.

1. Run `./gradlew downloadJLex -Dorg.gradle.caching.debug=true` again. Make a note of the final build cache key computed for task `:com.ibm.wala.cast.java.test.data:downloadJLex`.

Observe that the build cache keys computed during both builds are *identical*. However, the second build did not retrieve the task outputs from the build cache. Rather, it recomputed (re-downloaded) the task outputs from scratch.

For the tiny `JLex` download, this does’t matter much. However, some other downloads used by this project are much larger, taking up to tens of minutes to download. Consistently missing the build cache is making rebuilds take far longer than they should.

### Your Environment

 * Build scan URL: [first build](https://scans.gradle.com/s/faxy7kogsylyo/timeline?showCache&task=sc3m56t5pbcmg) contrasted with [second build](https://scans.gradle.com/s/umfa742v2tnrm/timeline?showCache&task=sc3m56t5pbcmg) showing that the second build had an identical build cache key but missed in the build cache instead of hitting

**Comment by wolfs** [comment] 2019-02-22 07:22
@liblit Your task is using `upToDateWhen { getDest().exists() }`. When calling `upToDateWhen(false)`, loading from the build cache is disabled since this effectively means that there is an input the build cache cannot track. You can remove the call to `upToDateWhen` and everything should work as expected.

Is there a reason you added the call to `upToDateWhen` since checking if the output file exists should already be handled by the normal up-to-date checks?

**Comment by liblit** [comment] 2019-02-22 16:11
Thank you for digging down into our build code to find that suspicious `upToDateWhen` call, @wolfs. I greatly appreciate the effort you went to, as well as the speed of your reply.

Looking back at [my own commit message](https://github.com/wala/WALA/commit/10d3adf3245d4de29909bfbb259147f334e514da), I see that I added this call because:
> Under some circumstances, Gradle seems to decide that the destination file being absent is the download task's expected outcome. It caches this state, and refuses to retry the download in the future since it thinks the task is up-to-date.

I found [a post about a similar problem in the Gradle Forums](https://discuss.gradle.org/t/task-up-to-date-but-outputfile-not-created/17568), and applied [the suggested solution](https://discuss.gradle.org/t/task-up-to-date-but-outputfile-not-created/17568/2?u=liblit). Maybe that was not the right approach after all. I can certainly remove the `upToDateWhen` call, but I am concerned that this will leave be back in the “Gradle thinks the file being absent is the expected outcome” situation.

I should also mention that these download tasks fail quite regularly due to timeouts, transient network outages, etc. A failed download could easily lead to a missing output file. Perhaps the original problem arose due to a download failing (and creating no output file) but the download _task_ claiming to have completed successfully. If Gradle thinks that the download task succeeded, then of course it is fair for Gradle to record the absent file as the expected outcome. So I need to make sure that failing the download consistently leads to the task itself being treated as a failed task. If failing a download does not mean failing the download task, then that seems like a bug in [the third-party download task plugin](https://github.com/michel-kraemer/gradle-download-task/).

**Comment by wolfs** [comment] 2019-02-22 16:21
Yeah, you are right. You need to make sure that the task fails when the download didn't succeed. I wonder how the verification succeeds when the file is not there, since that at least should make the task fail. Under those circumstances, Gradle should never record the missing output file as the legitimate output of the task.

I am closing this issue now. I you have further problems, please re-open or start a discussion on the forums.

**Closed by wolfs** 2019-02-22 16:21 UTC
Labels: from:contributor, in:build-cache

**Comment by liblit** [comment] 2019-02-22 16:33
Removing the questionable `upToDateWhen` call broke things, and had nothing to do with failed downloads. However, I am unable to systematically reproduce the breakage. I will record my steps here to the best of my memory.

1. Remove the questionable `upToDateWhen` call.

1. Run `./gradlew downloadJLex`. Observe that a `com.ibm.wala.cast.java.test.data/src/JLex` directory exists, containing a single `Main.java` file.

1. Remove that `JLex` directory: `rm -r com.ibm.wala.cast.java.test.data/src/JLex`.

1. Run `./gradlew downloadJLex` again. Observe that the task is reported as being up-to-date, but that the `com.ibm.wala.cast.java.test.data/src/JLex` does _not_ exist!

At this point I removed the project’s `.gradle` subdirectory entirely. After that, I am no longer able to reproduce this problem: if I remove `JLex`, then the `downloadJLex` task recreates it when needed, either from the build cache or from a fresh download if the build cache is unavailable. All is working as it should.

Maybe there was some transient leftover junk cached under `.gradle`? Unclear. But the problem is not coming back now, so I will hope that it is indeed gone. I agree that this issue can remain closed.

Thanks again for your help, @wolfs!

**Comment by wolfs** [comment] 2019-02-22 16:37
I guess your initial problem was caused by the file already being there when the task ran the first time. So the output file actually would not change and Gradle would detect that the task didn't have an output. Do you maybe have a build scan of the failing run? Gradle should also detect overlapping outputs (i.e. the unknown file being there) and would disable caching for the task.

**Comment by liblit** [comment] 2019-02-22 16:38
> Do you maybe have a build scan of the failing run?

Alas, I do not. :disappointed:

**Comment by liblit** [comment] 2019-02-22 17:03
Drat, it broke again. After `./gradlew assemble processTestResources` (which is sufficient to trigger all downloads), I then ran `./gradlew clean`. Subsequently rerunning `./gradlew assemble processTestResources` failed due to some missing downlaods.

Investigating more closely, the `downloadOcamlJava` task should be creating `com.ibm.wala.core.testdata/build/tmp/downloadOcamlJava/ocamljava-2.0-alpha1.tar.gz`, but it is not. The directory exists, but is empty. No tarball downloaded, no tarball restored from the build cache.

I will need to invest some more effort into making this reproducible. I will open a new issue once I can make this fail on demand, since this is now a different matter than the questions I originally raised here.
