### ISSUE TITLE
Adding buildscript dependency causing java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ivoadf** [gradle/gradle#23405] opened 2023-01-05 14:33 UTC
### Context

I ran into this while developing a gradle plugin that has this package in the dependency tree. Building and publishing the plugin was not an issue but as soon as I tried to apply the plugin I would run into this exception. 

I was then able to replicate the issue just by including the package as a buildscript dependency.

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 48 out of bounds for length 37	
at org.objectweb.asm.ClassReader.readLabel(ClassReader.java:2679)
```
### Steps to Reproduce 

https://github.com/ivoadf/gradle-bug-reproducer/actions/runs/3847564484/jobs/6554177681#step:4:155
### Your Environment

Build scan URL: https://scans.gradle.com/s/k5ts5ys4hs4xy

**Comment by eskatos** [comment] 2023-01-11 10:00
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by eskatos** [comment] 2023-01-11 10:02
The interesting part of the reproducer can be found here https://github.com/ivoadf/gradle-bug-reproducer/blob/kotlin-dsl/build.gradle.kts

**Comment by mlopatkin** [comment] 2023-01-11 14:02
It looks like the library in question is hitting the [javac bug](https://bugs.openjdk.org/browse/JDK-8187805), and the produced bytecode is in fact invalid. It can be fixed by switching to a more recent JDK (e.g. 11) and compiling the library with `-release 8` to maintain the binary compatibility - but this has to be done by the library maintainers. Alternatively, you can recompile the library yourself and ship the recompiled version alongside the plugin (e.g. by publishing it with different GAV coordinates or by shadowing it into the plugin itself).

Another potential workaround could be to use the [Worker API](https://docs.gradle.org/current/userguide/worker_api.html#changing_the_isolation_mode) with the classloader isolation to separate the build script from the library, and only touch the library classes inside the worker action.

Some background - Gradle instruments bytecode of build scripts and their dependencies in order to detect build configuration inputs for the configuration cache. However, the code is instrumented even if the configuration cache is disabled. This instrumentation is not applied to the worker classpaths, hence the workaround.

I'm leaving this open for a while to think about potential improvements to how Gradle handles such broken bytecode. We already have a similar issue #18024 that covers non-bytecode use case, but the desired behavior there might be different, as we don't actually want to instrument data.

**Comment by NikolayMetchev** [comment] 2023-01-11 15:56
@mlopatkin Thank you for that explanation. The javac bug states that this only happens if you have un unused local variable. Do you know where this unused variable is in the library?

**Comment by mlopatkin** [comment] 2023-01-11 20:15
> @mlopatkin Thank you for that explanation. The javac bug states that this only happens if you have an unused local variable. Do you know where this unused variable is in the library?

Maybe the referenced issue is not the one, just similar. It looks like [the nested lambdas](https://github.com/OpenHFT/Chronicle-Network/blob/6f3daa371731949c7411283e5914d36cbcad28c9/src/main/java/net/openhft/chronicle/network/connection/AbstractStatelessClient.java#L108-L116) with type-annotated locals trip the compiler over.

It looks like handling of type annotations underwent a significant update for Java 9, and the issue is no longer reproducible even with 9. I'm not familiar enough with javac to figure out why the issue was fixed in the end.

**Comment by ivoadf** [comment] 2023-01-16 09:35
The library maintainers fixed the lambda causing the error in https://github.com/OpenHFT/Chronicle-Network/commit/09dc790925d97b7689f2431883fe9bc81556a2ad 

FYI I [updated the reproducer repo](https://github.com/ivoadf/gradle-bug-reproducer/actions/runs/3928977096/jobs/6717219353) to use the newly published version and got a successful build

**Comment by bamboo** [comment] 2023-08-02 12:32
Do we need to take any action here?

**Comment by NikolayMetchev** [comment] 2023-08-02 12:36
Not sure you can do much. This is no longer a problem for us.

**Closed** 2023-08-28 15:27 UTC
Labels: a:bug, in:configuration-cache, has:reproducer
