### ISSUE TITLE
Unable to make progress running work. There are items queued for execution but none of them can be started

### ISSUE THREAD

**Issue by IGR2014** [gradle/gradle#25747] opened 2023-07-12 17:13 UTC
### Expected Behavior

Build completed

### Current Behavior

Unable to make progress running work. There are items queued for execution but none of them can be started

### Context (optional)

Updated gradle:
 was: 8.1.1
 now: 8.2.1

### Steps to Reproduce

Rebuild a project with two subprojects in it

### Gradle version

8.2.1

### Gradle version that used to work

8.1.1

**Comment by IGR2014** [comment] 2023-07-12 17:20
Hmmm, might be related to latest Android Studio Canary...
Works fine from console (PowerShell)

**Comment by ov7a** [comment] 2023-07-13 06:49
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

**Comment by natros** [comment] 2023-07-13 09:00
I'm having this problem with IntelliJ IDEA 2023.2 Beta when running tests and include builds. Works fines from command line

**Comment by natros** [comment] 2023-07-14 09:57
Already did that. 

In my case, the problem was that I was using an unsupported IntelliJ feature, namely the `gradle.testLauncherAPI.enabled=true` flag with configuration cache. But , in my case, the message alternates between this and "Included builds are not yet available for this build"

https://youtrack.jetbrains.com/issue/IDEA-325181/Included-builds-are-not-yet-available-for-this-build

**Comment by ov7a** [comment] 2023-07-14 10:09
Given that it's most probably an IntelliJ Idea issue and it is reproduced by the JetBrains team, I'm closing this.

**Closed by ov7a** 2023-07-14 10:09 UTC
Labels: closed:idea

**Comment by DamienLevel** [comment] 2023-07-19 08:36
An issue was created on Google IssueTracker but the status changed to _Won't fix (Infeasible)_ yesterday...
https://issuetracker.google.com/issues/290954881

> This is a very interesting bug but I would file it against Gradle directly if you have done so already. this seems to be an issue with the Gradle's execution engine.

**Comment by ov7a** [comment] 2023-07-19 09:01
@DamienLevel Thanks for the feedback!

I think any further discussion should happen in 
* #21325

**Comment by gibo77** [comment] 2024-08-14 04:14
Mine works when I downgraded the buildToolsversion from 35 to 34. See code setting below in build.gradle. Same with compileSDK and target SDK version to 34. I am using Koala Android Studio with Android gradle plugin: 8.2.1 and Gradle: 8.6.
Looks like the 8.2.1 is only tested up to 34.
```
buildscript {
    ext {
        buildToolsVersion = "34.0.0"
        minSdkVersion = 23
        compileSdkVersion = 34
        targetSdkVersion = 34
        ndkVersion = "26.1.10909125"
        kotlinVersion = "1.9.22"
    }
    repositories {
        google()
        mavenCentral()
```

**Comment by ShubhamSKadam** [comment] 2024-09-14 07:53
@gibo77 I'm using the exact same version as yours, still I'm facing the same issue.

**Comment by saeid-elio** [comment] 2024-12-11 13:02
Why is this solution not implemented in React Native's latest version by default so we don't need to waste half a day chasing after a solution?
