### ISSUE TITLE
bootRun fails on 6.4.-rc.1

### ISSUE THREAD

**Issue by prachiN48** [gradle/gradle#12847] opened 2020-04-20 11:35 UTC
### Expected Behavior
After upgrading from gradle 6.3 to 6.4-rc-1, bootRun should startup the spring application as usual

### Current Behavior
bootRun fails with error
```
Execution failed for task ':bootRun'.
> No main class specified and classpath is not an executable jar.
```

### Context
unable to run the spring application

### Steps to Reproduce 
1. upgrade gradle version from 6.3 to 6.4-rc-1
2. run gradle bootRun

### Your Environment
building with Kotlin version - 1.3.72
java version - 13.0.2
OS - MacOS Catalina - 10.15.4

**Comment by ljacomet** [comment] 2020-04-20 12:17
This is a duplicate of #12834

**Closed by ljacomet** 2020-04-20 12:17 UTC
Labels: a:bug, closed:duplicate, from:contributor
