### ISSUE TITLE
Gradle 4.4: Included build 'buildSrc' cannot have included builds.

### ISSUE THREAD

**Issue by VenelinPetkov** [gradle/gradle#3736] opened 2017-12-06 14:18 UTC
Cannot set includedBuild in Gradle 4.4 in buildSrc.

### Expected Behavior
In Gradle 4.3.1 buildSrc settings were allowed to have includedBuilds

### Current Behavior
In Gradle 4.4 the build sync is throwing an error:
Included build 'buildSrc' cannot have included builds.

### Context
composite build

**Comment by oehme** [comment] 2017-12-06 14:59
@bigdaz I assume this is intended behavior, as nested composites are not allowed in general. Can you verify that's the intention?

**Comment by bigdaz** [comment] 2017-12-06 22:51
Yep, if this was working in 4.3.1, that was by coincidence.

**Comment by oehme** [comment] 2017-12-07 09:53
Thanks Daz, closing as expected behavior.

**Closed by oehme** 2017-12-07 09:53 UTC
Labels: from:contributor
