### ISSUE TITLE
Suppressed Exceptions dropped when converting to PlaceholderException

### ISSUE THREAD

**Issue by 91wzhang** [gradle/gradle#12985] opened 2020-04-30 15:56 UTC
When running tests, if exceptions are thrown, Gradle is seemingly trying to serialise it before printing the stack trace. Some custom exceptions are however not being printed directly but will be transformed into PlaceholderException where most of the information is copied over. However suppressed exceptions from the original exceptions are lost in the process. 

### Expected Behavior
All exceptions' suppressed exceptions should be preserved and be printed out.

### Current Behavior
Specifically, JUnit5's important new feature, i.e, Assertions.assertAll will throw opentest4j's MultipleFailuresError (extends AssertionError). It will append exceptions thrown by the individual assertions as suppressed exceptions. And then those very useful messages will be dropped by Gradle test tool. I have tried AssertionError itself will not be transformed and suppressed exceptions are preserved.

### Context
assertAll is one of the very important new feature from JUnit5 where it will not exit the test case immediately when one of the many assertions failed but instead will run all of them and report results together. However, because of how Java exception works it cannot dump all stack traces for all the assertions' exceptions together. Instead, stack traces are appended as suppressed exceptions. They are very useful because the stack trace of the wrapping exception, MultipleFailuresError, only contains the assertions' results and most useful debugging information are in the suppressed exceptions. 

### Steps to Reproduce 
Create a JUnit 5 test case, use the assertAll assertions and any number of sub assertions. Throw exceptions in any of the sub assertions. No stack trace of that exception is appended. Originally it's an issue in JUnit side, but it's been fixed in 2018 (https://github.com/junit-team/junit5/issues/1602)

### Your Environment
Java 8/11, Gradle 6.0.1, JUnit 5.6.2

Build scan URL:
NA

**Comment by ljacomet** [comment] 2020-04-30 15:59
Thanks for the report and detailed explanation.

#12302 is an issue with a similar cause.

**Comment by marcphilipp** [comment] 2020-05-01 08:35
I think this can be closed as duplicate of #9487.

**Comment by ljacomet** [comment] 2020-05-04 08:54
Closing as duplicate indeed.

**Closed by ljacomet** 2020-05-04 08:54 UTC
Labels: @jvm, a:bug, closed:duplicate, from:contributor, in:testing
