### ISSUE TITLE
Consider a flag to fail a build if deprecation warnings are present

### ISSUE THREAD

**Issue by rpalcolea** [gradle/gradle#7991] opened 2018-12-10 17:17 UTC
### Expected Behavior
Have a flag, perhaps `--fail-with-deprecations`, that fails the build if deprecation warnings are detected with all of them in the output

### Current Behavior
There is nothing for this right now

### Context
Historically, we have prevented our teams from using deprecated APIs in Gradle, specially if they use Nebula. However, this behavior is usually implemented around deprecation warning messages which change often due to output enhancing in gradle.

It would be ideal if we could have a flag like the one above to fail the build on these cases.

**Comment by marcphilipp** [comment] 2018-12-12 07:06
I wonder whether `--warning-mode=fail` would be confusing. Thoughts?

**Comment by rpalcolea** [comment] 2018-12-14 18:16
Hi @marcphilipp, 

I think `--warning-mode=fail` would make a lot of sense, at least for us.

**Comment by ljacomet** [comment] 2019-07-02 13:40
Closing as duplicate of #6491

**Closed by ljacomet** 2019-07-02 13:40 UTC
Labels: a:feature, from:contributor, in:core
