### ISSUE TITLE
Edit this page does not link on new sample pages

### ISSUE THREAD

**Issue by pioterj** [gradle/gradle#11270] opened 2019-11-08 08:39 UTC
Steps to reproduce:

- Open a new sample page e.g. https://docs.gradle.org/nightly/samples/groovyBasicApplication/
- Click "edit this page"
- The browser goes to https://github.com/gradle/gradle/tree/master/subprojects/docs/src/docs/userguide

**Comment by lacasseio** [comment] 2019-11-08 14:21
Duplicate of https://github.com/gradle/gradle-private/issues/2828

**Closed by lacasseio** 2019-11-08 14:21 UTC
Labels: a:bug, a:sample, from:member
