### ISSUE TITLE
Inconsistent `Dependency.contentEquals` results when comparing dependencies created via string, Version Catalog, and typesafe project accessors

### ISSUE THREAD

**Issue by adam-enko** [gradle/gradle#29859] opened 2024-07-09 10:43 UTC
### Current Behavior

`Dependency.contentEquals` has inconsistent results when comparing dependencies created via string, Version Catalog, and typesafe project accessors.

### Expected Behavior

Ideally `Dependency.contentEquals()` is updated to be able to compare dependencies of different types.

Alternatively, the Javadoc of `Dependency.contentEquals()` is updated to document the limitations, and a new utility method is added for comparing dependencies for effective equality.

### Context (optional)

As a plugin author I need to be able to compare declared dependencies to determine if they are effectively the same. I am not able to determine how those dependencies are defined.

KGP needs to be able to determine whether a dependency in one Configuration is present in another. This works as expected for regular dependencies, but not for dependencies created via Version Catalog or typesafe project accessors.

https://youtrack.jetbrains.com/issue/KT-69759/KMP-compileOnly-dependency-warning-triggered-by-typesafe-project-accessors

### Steps to Reproduce

I expected that dependencies created using string coordinates should have the same content as dependencies created using Version Catalog, but they do not.

```toml
# gradle/libs.versions.toml
[libraries]
atomicfu = "org.jetbrains.kotlinx:atomicfu:latest.release"
```

```kotlin
// build.gradle.kts
val atomicfuLibs: Dependency = libs.atomicfu.get()
val atomicfuString: Dependency = dependencies.create("org.jetbrains.kotlinx:atomicfu:latest.release")

println("atomicfuLibs.contentEquals(atomicfuString) ${atomicfuLibs.contentEquals(atomicfuString)}")
println("atomicfuString.contentEquals(atomicfuLibs) ${atomicfuString.contentEquals(atomicfuLibs)}")

println("atomicfuLibs.contentEquals(atomicfuLibs) ${atomicfuLibs.contentEquals(atomicfuLibs)}")
println("atomicfuString.contentEquals(atomicfuString) ${atomicfuString.contentEquals(atomicfuString)}")
```

Result:

```text
atomicfuLibs.contentEquals(atomicfuString) false  // expected `true`, but was `false`
atomicfuString.contentEquals(atomicfuLibs) false  // expected `true`, but was `false`
atomicfuLibs.contentEquals(atomicfuLibs) true     // expected `true`
atomicfuString.contentEquals(atomicfuString) true // expected `true`
```

I expected that dependencies created using `project(":path:to:project")` should have the same content as dependencies created using typesafe project accessors, but they do not.

```kotlin
// settings.gradle.kts
rootProject.name = "my-foo-project"

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")
```

```kotlin
// build.gradle.kts

val stringBased = dependencies.create(project(":"))
val typesafe = dependencies.create(projects.myFooProject)

println("stringBased.contentEquals(typesafe) ${stringBased.contentEquals(typesafe)}")
```

Result:

```text
stringBased.contentEquals(typesafe) false // expected `true`, but was `false`
```

### Gradle version

8.8

**Comment by alllex** [comment] 2024-07-09 12:27
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

The [current contract](https://docs.gradle.org/8.8/javadoc/org/gradle/api/artifacts/Dependency.html#contentEquals(org.gradle.api.artifacts.Dependency)) for `contentEquals` is not trivial:
> Returns whether two dependencies have identical values for their properties. A dependency is an entity with a key. Therefore dependencies might be equal and yet have different properties.

The observed behavior may be considered to satisfy the contract. However, there is a question of whether the contract needs to be improved by itself.

**Comment by big-guy** [comment] 2024-07-15 16:30
@adam-enko This looks like unintended behavior on our side. 

Could you describe what you're doing with contentEquals a little more?  Why do you want to check for identical dependencies in multiple Configurations? We might be able to suggest something else.

**Comment by adam-enko** [comment] 2024-07-22 10:13
> Could you describe what you're doing with contentEquals a little more? Why do you want to check for identical dependencies in multiple Configurations? We might be able to suggest something else.

KGP needs to determine if a `compileOnly()` dependency is also declared as `api()`, to help align KLib and Gradle metadata. https://youtrack.jetbrains.com/issue/KT-64109/

It turns out that even if `Dependency.contentEquals()` could compare dependencies ignoring the class, we couldn't use it, because we need to ignore the versions of dependencies.

Here's what we're using instead: https://github.com/JetBrains/kotlin/blob/4e273a37734bc40a9012872b9744bac65746d039/libraries/tools/kotlin-gradle-plugin/src/common/kotlin/org/jetbrains/kotlin/gradle/plugin/diagnostics/checkers/IncorrectCompileOnlyDependenciesChecker.kt#L121-L138

And yes, comparing declared dependencies like this isn't ideal, because they might be resolved to be different. But this is just a quick check, and a refactor to resolve dependencies would be significant. And the KGP DSL should be updated to prevent such invalid dependencies being declared https://youtrack.jetbrains.com/issue/KT-58976/Design-better-scoped-dependencies.

**Comment by big-guy** [comment] 2024-07-29 16:17
@adam-enko given that contentEquals won't fix your use case, is this issue still relevant? 

Comparing declared dependencies like that has other issues, for instance, it makes your check reliant on a particular order of evaluation.  Dependencies added "too late" will not be checked.  There are also ways for declared dependencies to be replaced with other dependencies that will not be considered with your check.  Finally, there are ways for declared dependencies to be equivalent without having the same group and name.

**Comment by adam-enko** [comment] 2024-08-01 08:05
> @adam-enko given that contentEquals won't fix your use case, is this issue still relevant?

Yes, I think it's still relevant of this issue is that the behaviour of `contentEquals()` doesn't match the Javadoc. I would hope that either the function would be fixed, or the Javadoc updated to clarify that the behaviour depends on not just the properties of the dependency, but also how it was declared (and there's no way of determining this).

The use-case above was an example that the GitHub issue template suggested I fill in. It's described as optional.

**Comment by jvandort** [comment] 2024-08-05 16:57
We decided to deprecate this method instead of fixing its behavior: https://github.com/gradle/gradle/issues/30094

**Closed by jvandort** 2024-08-05 16:57 UTC
Labels: a:bug, in:dependency-version-catalog, in:dependency-declarations, :wave: team-triage
