### ISSUE TITLE
User can include optional features of upstream libraries

### ISSUE THREAD

**Issue by jevgeniv** [gradle/gradle#1253] opened 2017-01-25 11:32 UTC
Quoting earlier issue https://issues.gradle.org/browse/GRADLE-1293:
> I have a dependency to log4j.
dependencies {
compile group: 'log4j', name: 'log4j', version: '1.2.+'
}
The log4j has an optional dependency to javax.mail.
ivy-1.2.16.xml: 
`<dependency org="javax.mail" name="mail" rev="1.4.1" force="true" conf="optional->compile,master"/>`

> I defined a runtime dependency, because we need the mail.
dependencies {
compile group: 'log4j', name: 'log4j', version: '1.2.+'
runtime group: 'javax.mail', name: 'mail', version: '1.+'
}
I do not want to define the version ('1.+'). But without the version I 
get an error.

### Expected Behavior
Another example: `spring-web:4.3.5.RELEASE` declares an optional dependency on `jackson-databind:2.8.5`.
There could be a way to tell to include that particular dependency with version specified by the `spring-web` module itself, e.g. something like 
```gradle
    compile (group: 'org.springframework', name: 'spring-web', version: '4.3.5.RELEASE') {
        include 'com.fasterxml.jackson.core:jackson-databind' //  wishful thinking here
    }
```

### Context
This feature would seem to have supported general usage pattern of transient dependencies. That it, as long as version of a transient dependency is not that important, one does not need to manually specify it.

### Your Environment
Gradle 3.3

**Comment by oehme** [comment] 2017-09-20 17:46
Duplicate of #867

**Comment by mkalb** [comment] 2017-10-18 07:48
@oehme Why is this a duplicate of #867 ? They can be fixed together, but this is not a duplicate. Please reopen this issue.
I created the original issue 7 years ago and there is still no solution.

**Comment by oehme** [comment] 2017-10-18 09:02
You're right, this is not a duplicate, I misjudged it based on the title.

**Comment by jjohannes** [comment] 2018-02-14 14:34
This will be supported in Gradle 4.6 using this opt-in in _settings.gradle_:

`enableFeaturePreview('IMPROVED_POM_SUPPORT')`

It will be supported by default with Gradle 5.0.

Feel free to try this with the current nightly and provide feedback.

**Closed** 2018-02-14 15:03 UTC
Labels: a:feature, from:contributor, in:dependency-management

**Comment by oehme** [comment] 2018-02-14 15:05
@jjohannes I think a bit more explanation is necessary here: @jevgeniv originally asked for this syntax to turn an optional dependency into a hard one:

```
 compile (group: 'org.springframework', name: 'spring-web', version: '4.3.5.RELEASE') {
    include 'com.fasterxml.jackson.core:jackson-databind' //  wishful thinking here
  }
```

With the new feature this will instead look like this:


```
 compile (group: 'org.springframework', name: 'spring-web', version: '4.3.5.RELEASE')
 compile 'com.fasterxml.jackson.core:jackson-databind' //version comes from the optional dependency in spring-web
```

**Comment by mkalb** [comment] 2018-02-20 16:59
Thank you. It works.

```
dependencies {
    implementation 'log4j:log4j:1.2.17'
    runtimeOnly 'javax.mail:mail'
}
```

```
runtimeClasspath - Runtime classpath of source set 'main'.
+--- log4j:log4j:1.2.17
|    \--- javax.mail:mail:1.4.3
|         \--- javax.activation:activation:1.1
\--- javax.mail:mail -> 1.4.3 (*)

```
