### ISSUE TITLE
Version catalog does not support resolving specific artifacts

### ISSUE THREAD

**Issue by aasitnikov** [gradle/gradle#19576] opened 2022-01-14 13:04 UTC
Gradle version: 7.3.3

Gradle dependency notation supports specifying artifacts, as discribed [here](https://docs.gradle.org/current/userguide/declaring_dependencies.html#sec:resolve_specific_artifacts_from_dependency). But if some library in version catalog contains artifact, then dependency won't resolve.

For example:
```
// libs.versions.toml
[libraries]
appsflyer = "com.appsflyer:af-android-sdk-beta:6.3.2-rc3@aar"

// build.gradle
dependencies {
    implementation("com.appsflyer:af-android-sdk-beta:6.3.2-rc3@aar") // works as expected
    implementation(libs.appsflyer) // configures, but dependency is not resolved, can be easily seen by calling :dependencies task
}
```

**Comment by ljacomet** [comment] 2022-01-14 13:56
Closing as duplicate of #17169

**Closed by ljacomet** 2022-01-14 13:56 UTC
Labels: a:bug, in:dependency-version-catalog
