### ISSUE TITLE
Improve javadoc api

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#31422] opened 2024-11-26 15:17 UTC
### Expected Behavior

I'm going to make this 1 issue talk about 3 api issues, we can split into 3 issues if you want

1. `docletpath()` should take a provider and/or a file collection, current workaround `docletpath(*asciiDoclet.get().files.toTypedArray())` see PR in context for more context
2. javadoc doesn't take generated sources as an input and so documentation for them would not be bundled, and using `{@link SomeGeneratedClass}` would not work. current workaround `tasks.withType<Javadoc>().configureEach { dependsOn(tasks.classes)`. This becomes a serious issue when a written class relies on generated code and vice versa. Javadoc should correctly have generated sources as an input. See linked repo

### Context

1. https://github.com/asciidoctor/asciidoclet/pull/143/files#diff-1194561cbea346acb1bea37d81fdf5c70def982dcbb0c64eca2a96bc51941124R174
2. https://github.com/xenoterracide/spring-app-commons/blob/main/module/security-model/src/main/java/com/xenoterracide/model/security/user/User.java#L66 UserBuilder is generated by immutables, I spent many hours trying to figure out how to get javadoc to generate. It's been a while, but I'm not certain that it even would generate at all without the workaround, at the very least there was a warning and the documentation for the published api would have been incorrect.

**Comment by ov7a** [comment] 2024-11-28 13:09
We appreciate the effort, but we must ask for more information so that we can triage it. 

We do not see an immediate root cause, and we need a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) for the triage. If we have a reproducer project, we may be also able to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer project is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project.

This issue will be closed after 7 days unless you provide more information.

***

The first point will be addressed by provider API migration in 9.0.

Regarding the second point. It depends on what is happening exactly. Can you please provide an minimal, isolated reproducer to demonstrate the issue?

**Closed** 2024-12-05 14:00 UTC
Labels: a:bug, to-triage, closed:unreproducible, pending:reproducer
