### ISSUE TITLE
Gradle 3.4 Scala plugin cannot find symbol for annotations.

### ISSUE THREAD

**Issue by charlesxucheng** [gradle/gradle#1498] opened 2017-03-03 06:23 UTC
I have code in Scala that is used by Java code (domain logic in Scala, MVC layer in Spring Boot). I was able to use Gradle Scala plugin to compile the code up to Gradle 3.3, by setting the following:
 sourceSets.main.scala.srcDir "src/main/java"
 sourceSets.main.java.srcDirs = []

Ref: https://chrismarks.wordpress.com/2013/07/31/compiling-a-mixed-scala-project-with-gradle/

However with Gradle 3.4 this no longer works. References to objects flagged out as "cannot find symbol" for annotations, such as Lombok @Slf4j and Spring @RequestBody.

### Expected Behavior

Should behave in the same way as before. Everything should compile.

### Current Behavior

As described above.

### Your Environment

 * Build scan URL: 
Gradle 3.4, Scala lib 2.12.1, Java 8u111.

**Comment by melix** [comment] 2017-03-03 15:04
Hi,

Can you setup a minimal test project showing the problem? It would help us diagnose and determine if it's a bug or not.

Thanks!

**Comment by charlesxucheng** [comment] 2017-03-06 01:26
Please take a look at https://github.com/charlesxucheng/gradle-issue-1498.
I tried Gradle 3.1, Gradle 3.3 (Wrapper) and Gradle 3.4. Compilation fails with 3.4 only and works fine in other versions.

Thanks.

**Comment by charlesxucheng** [comment] 2017-03-27 04:04
Any update on this? It is a breaking change for our project.

**Comment by blendmaster** [comment] 2017-04-06 00:29
I made a minimal reproduction here: https://github.com/blendmaster/gradle-1498 .

I tried a couple different permutations of gradle scalac options and lombok/scala versions. Only the gradle version seems to affect it.

**Comment by butlermh** [comment] 2017-04-11 00:09
I have exactly the same issue. When doing mixed Scala / Java compilation, it's necessary to set empty the Java source path:
```
sourceSets.main.java.srcDirs = []
```
I suspect consequently the annotation processor has nothing to process?

**Comment by butlermh** [comment] 2017-04-11 18:17
So specifically I think the problem is the annotation processors get set for Java compilation - see [JavaCompile](https://github.com/gradle/gradle/blob/v3.4.0/subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java#L221) but they don't get set for Scala compilation - see [AbstractScalaCompile](https://github.com/gradle/gradle/blob/v3.4.0/subprojects/language-scala/src/main/java/org/gradle/language/scala/tasks/AbstractScalaCompile.java#L82) so consequently because the `annotationProcessorPath` is empty then the `-proc:none` argument gets added to the Java compiler.

**Comment by butlermh** [comment] 2017-05-16 18:23
The problem is the [Java compiler is setting the annotation processor path](https://github.com/gradle/gradle/blob/7f0fc51180ada1c9255afff73098e9cf7c7da253/subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java#L209) but the [Scala compiler does not](https://github.com/gradle/gradle/blob/0dd25191ca4d2d930430436ed99686fe22c55f81/subprojects/language-scala/src/main/java/org/gradle/language/scala/tasks/AbstractScalaCompile.java#L85).

**Comment by krro** [comment] 2017-06-12 07:02
hey, I've created a fix and unit tested it
I've also run the fix against the charlesxucheng's repository and the code has been compiling fine :)

**Comment by bmuschko** [comment] 2017-07-12 18:34
Fixed with https://github.com/gradle/gradle/pull/2281.

**Closed by bmuschko** 2017-07-12 18:34 UTC
Labels: a:bug, affects-version:3.4, from:contributor, in:scala-plugin

**Comment by bmuschko** [comment] 2017-07-14 12:43
I'd appreciate if you could test out a nightly build on your project to verify the fix: https://services.gradle.org/distributions-snapshots/gradle-4.1-20170714074750+0000-bin.zip

**Comment by charlesxucheng** [comment] 2017-07-14 14:01
Hi Benjamin,

I tested the nightly build against my project that has issue with Gradle.
It works fine. The whole build is successful.

**Comment by bmuschko** [comment] 2017-07-14 15:05
@charlesxucheng Thanks for checking!
