### ISSUE TITLE
Upgrade Gradle wrapper task on Windows missing chars

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [gradle/gradle#18618] opened 2021-10-13 08:10 UTC
### Expected Behavior (left) - Current Behavior (right)

![image](https://user-images.githubusercontent.com/7463564/137093555-6ef98e7c-375f-4d55-bca4-71073f44a2d5.png)

![image](https://user-images.githubusercontent.com/7463564/137093221-10fd0d59-31a5-4093-8cf5-94c3ff76e9ac.png)

### Steps to Reproduce 
Just upgrade running two times the Gradle wrapper task:

```shell
./gradlew wrapper --gradle-version=7.2
```

This happens with every Gradle version (or at least 7.1+, including 7.3-rc-1).

### Your Environment
Windows 10

**Comment by JavierSegoviaCordoba** [comment] 2021-10-20 08:24
@jbartok I am using Windows 10 with Powershell, for checking the content of the files I am using IntelliJ IDEA.

Steps:

- No changes in the project
- Run two times in a row the Gradle wrapper task
- To possibilities when you open all files that have changed:
	- Diff should show that only the version has changed in `gradle-wrapper.properties`
	- Version is the same so there should be no changes
- But it is changing those files that were updated in a macOS machine setting unknown characters.

**Comment by jbartok** [comment] 2021-11-05 09:39
See "possible root cause" in #18860, maybe that's the problem. Will investigate.

**Comment by jbartok** [comment] 2021-11-29 15:43
@JavierSegoviaCordoba I was not able to reproduce this issue on my Windows machine. In the end, I've attempted a blind fix (the above mentioned PR) and I would like to kindly ask you to try it out. You can do so, by using the next nightly build from here: https://gradle.org/nightly/ (so the one from 29 Nov 2021 or later). Pls. let me know if that fixes your problem or not.

**Comment by JavierSegoviaCordoba** [comment] 2021-11-29 15:56
@jbartok maybe can be related I am using LF on Windows instead of the default one?

**Comment by jbartok** [comment] 2021-12-02 08:08
@JavierSegoviaCordoba any luck/improvement?

**Comment by JavierSegoviaCordoba** [comment] 2021-12-02 08:51
Yesterday I tried and get same issue. Not sure if it is related to the fact I am using lf in Windows.

Thank you for your try :)

**Comment by KENNYSOFT** [comment] 2021-12-09 02:55
Occurred when upgrading 7.2 to 7.3 in Windows 11, PowerShell, with Korean.

https://github.com/jshiell/checkstyle-idea/pull/542/files#diff-e9721dc750619a21053ddea8a5d04929a608877d8c5daec1b57d243d3424e745R4

**Comment by KENNYSOFT** [comment] 2021-12-09 03:17
I've tried multiple combinations and result to:

|current version in `gradle.properties`|towards to `wrapper --gradle-version`|broken or correct|
|-|-|-|
|7.4-20211128231053+0000|7.4-20211128231053+0000|broken|
|7.4-20211128231053+0000|**7.4-20211129230932+0000**|broken|
|**7.4-20211129230932+0000**|7.4-20211128231053+0000|correct|
|**7.4-20211129230932+0000**|**7.4-20211129230932+0000**|correct|

So it's not applied when the upgrade destination version is 20211129+ but the currently using wrapper version is 20211129+.

@JavierSegoviaCordoba Can you re-run with 7.4-20211129230932+0000 in the `gradle.properties`?

**Comment by smoothreggae** [comment] 2021-12-15 21:03
I use Git Bash (via Git for Windows) and saw this problem with the generated `gradlew` after upgrading to Gradle `7.2`. I believe this is because of changes that came from PR #17666, which introduced guillemets and the rich copyright symbol to `subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt`. The file was previously ASCII text, but now **needs** to be both read and written using the UTF-8 encoding. This happens on Unix-like systems, but on Windows, from what I can tell based on a brief examination of the source code, the file is *not* being read using the UTF-8 encoding. This gives me an ISO-8859-encoded file with strange characters. I worked around this by using a copy of `gradlew` generated on a Linux machine.
Changing the code to ensure that this file is both read and written using the UTF-8 is one way to fix this. Alternatively, you could get rid the guillemets and the rich copyright symbol from `subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt`.  No such changes were made to `subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/windowsStartScript.txt`, which is why `gradlew.bat` remains unaffected.

**Comment by jonathan-meier** [comment] 2022-02-01 19:00
@jbartok I just ran into this issue with Gradle version `7.3.3` on the Windows command line (`cmd.exe`). I tried `7.4-rc-1` and that has fixed it for me, so it looks like your blind fix works, at least in my case.

**Comment by ljacomet** [comment] 2022-02-02 09:12
Closing then, thanks for following up

**Closed by ljacomet** 2022-02-02 09:12 UTC
Labels: in:wrapper, a:bug, windows, @support
