### ISSUE TITLE
Task with a doLast block using a lambda is never up-to-date

### ISSUE THREAD

**Issue by sayniv** [gradle/gradle#5510] opened 2018-05-23 23:03 UTC
### Expected Behavior

Gradle should allow plugins to add doLast blocks to tasks with a lambda.

### Current Behavior

Using lambdas in plugin to add doLast block to tasks breaks cacheability.

### Context

I am working with a plugin that adds a doLast block to tasks of type checkStyle. This plugin is written in Java and is compiled separately and used as a dependency. In the plugin we add a doLast block with something like this:
<code>
   task.doLast(t -> { //do something })
</code>

I notice that checkStyle task is not cacheable due to the doLast block being defined as a Lambda.

During execution with debug turned on, I see the following log output:

```
_Task myCustomCheckstyle
Appending .....
Appending actionType to build cache key: com.myorg.MyCustomPlugin$$Lambda$188/376495921
...
Build cache key for task 'myCustomCheckstyle' is b869c161eb63f4507d850045047ee9aa_

```
The actionType is different on each invocation because the part after the **$$Lambda$188/** changes with each invocation.

When I replace the lambda with an Action, like
```
   task.doLast(new MyCustomDoLastAction())
```

 caching works as expected since the _actionType_ resolves to **_com.myorg.MyCustomPlugin.$MyCustomDoLastAction_**

### Steps to Reproduce (for bugs)

1. Create a java project on which checkstyle plugin is applied
2. Create a project to house a plugin that scans the project on which it is applied, to find checkstyle tasks and adds a doLast block to each checkstyle task it finds. Make sure the doLast block is added with a closure block and not an explicit Action implementation.
3. Compile the plugin and apply it to the java project created in step one.
4. Run checkstyle task with -Dorg.gradle.caching.debug=true flag.
5. Notice the debug log with a message of the kind: 
```
Appending actionType to build cache key: com.myorg.MyCustomPlugin$$Lambda$188/376495921
```
6. Run the checkstyle task again, notice that the task is not cacheable because the the actionType corresponding to the lambda is different, and therefore the cache key is different.
7. Now replace the closure defining the action block in the plugin with an implementation of the action. Compile the plugin again and apply to the project.
8. Run checkstyle task twice and notice that it is not cacheable.

### Your Environment

OS: macOS High Sierra
Java Version: 1.8.0_121
Gradle Version: 4.6

**Comment by wolfs** [comment] 2018-05-24 06:41
@sayniv Thank you for reporting. I am surprised by the bug report, given that the underlying problem should have been fixed in Java 8u40 (see the [JDK bug](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8067422)).

I guess this is something different, right? So the code of the plugin does not change (it is compiled separately) and still the class name of the lambda changes?

**Comment by oehme** [comment] 2018-05-24 07:29
Independently of this bug, don't we deactivate the cache with custom actions anyway? After all they can introduce new, untracked outputs that could break caching.

**Comment by lptr** [comment] 2018-05-24 09:27
There is no major difference between task actions declared via `@TaskAction` and `doLast()`. For each action we assume that inputs and outputs are properly declared (either via `@Input` annotations or via the runtime API). It's not an air-tight system by any means, as we simply trust that things are set up properly.

**Comment by tjni** [comment] 2018-08-03 18:37
It looks like the JVM will add an unstable hash code to the end of the lambda class name when calling `getClass().getName()` on a lambda.

I've been thinking a bit about this and wanted to run this by everyone. If indeed the assumption is that inputs and outputs are properly declared, then shouldn't the action name not be part of the cache key?

**Comment by lptr** [comment] 2018-08-06 07:34
Can you please share a reproducible test or some results we can look at?

**Comment by david-noel** [comment] 2018-08-13 21:10
I'm seeing similar behavior when using the spring boot plugin with gradle 4.9.  It appears the spring boot plugin applies an action when the JavaPlugin is also present on a project.

https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/main/java/org/springframework/boot/gradle/plugin/JavaPluginAction.java

I notice this on the compileJava task when I have org.gradle.caching.debug=true

`Appending actionType to build cache key: org.springframework.boot.gradle.plugin.JavaPluginAction$$Lambda$33/67053257`

Running in Jenkins, on linux with java 1.8.0_181, every build produces a different number for the 67053257 part and I get a cache miss.

The strange part is this works fine on my Mac.  The number stays the same from build to build.

Even more strange is when I run the build on my machine(Docker for Mac) with the same container used by Jenkins, the number stays the same.

**Comment by wilkinsona** [comment] 2018-08-14 10:36
[Here is a sample project](https://github.com/wilkinsona/lambda-task-action) that will hopefully reproduce the problem, or at least a variant of it.

You can see the type name of the lambda task action change depending on the presence of `--info`:

Without `--info`:

```
$ GRADLE_OPTS=-verbose:class ./gradlew compileJava --no-daemon --console=plain | grep ExamplePlugin
[Loaded com.example.ExamplePlugin from file:/Users/awilkinson/.gradle/caches/jars-3/d2a9372c2f68ba34f55fb0a07a3b11d1/buildSrc.jar]
[Loaded com.example.ExamplePlugin$$Lambda$1/837790893 from com.example.ExamplePlugin]
[Loaded com.example.ExamplePlugin$$Lambda$2/1111413685 from com.example.ExamplePlugin]
```

Without `--info` again. Names are unchanged:

```
$ GRADLE_OPTS=-verbose:class ./gradlew compileJava --no-daemon --console=plain | grep ExamplePlugin
[Loaded com.example.ExamplePlugin from file:/Users/awilkinson/.gradle/caches/jars-3/d2a9372c2f68ba34f55fb0a07a3b11d1/buildSrc.jar]
[Loaded com.example.ExamplePlugin$$Lambda$1/837790893 from com.example.ExamplePlugin]
[Loaded com.example.ExamplePlugin$$Lambda$2/1111413685 from com.example.ExamplePlugin]
```

With `--info`. The names have changed:

```
$ GRADLE_OPTS=-verbose:class ./gradlew compileJava --no-daemon --console=plain --info | grep ExamplePlugin
[Loaded com.example.ExamplePlugin from file:/Users/awilkinson/.gradle/caches/jars-3/d2a9372c2f68ba34f55fb0a07a3b11d1/buildSrc.jar]
[Loaded com.example.ExamplePlugin$$Lambda$1/1938374337 from com.example.ExamplePlugin]
[Loaded com.example.ExamplePlugin$$Lambda$2/1728266914 from com.example.ExamplePlugin]
```

With `--info` again. The names have remained the same:

```
$ GRADLE_OPTS=-verbose:class ./gradlew compileJava --no-daemon --console=plain --info | grep ExamplePlugin
[Loaded com.example.ExamplePlugin from file:/Users/awilkinson/.gradle/caches/jars-3/d2a9372c2f68ba34f55fb0a07a3b11d1/buildSrc.jar]
[Loaded com.example.ExamplePlugin$$Lambda$1/1938374337 from com.example.ExamplePlugin]
[Loaded com.example.ExamplePlugin$$Lambda$2/1728266914 from com.example.ExamplePlugin]
```

Without `--info`. The names are back to what they were originally:

```
$ GRADLE_OPTS=-verbose:class ./gradlew compileJava --no-daemon --console=plain | grep ExamplePlugin
[Loaded com.example.ExamplePlugin from file:/Users/awilkinson/.gradle/caches/jars-3/d2a9372c2f68ba34f55fb0a07a3b11d1/buildSrc.jar]
[Loaded com.example.ExamplePlugin$$Lambda$1/837790893 from com.example.ExamplePlugin]
[Loaded com.example.ExamplePlugin$$Lambda$2/1111413685 from com.example.ExamplePlugin]
```

**Comment by david-noel** [comment] 2018-08-14 15:25
The --no-daemon option explains why I'm seeing different behavior between my local and Jenkins builds.  My Jenkins build uses --no-daemon.  When I use --no-daemon on my local build I get a different value from run to run.  Using or not using --info seems to make no difference in my build.  The numbers are always different.

**Comment by wolfs** [comment] 2018-08-15 20:05
IIUC correctly, then the lambda classes are created at execution time and are not created at compilation time by the compiler. The class name consists of the call site (`com.example.ExamplePlugin$$Lambda$1`), which seems to be stable, and a counter `/837790893`, which doesn't seem to be stable between different JVM runs.

The class is only created once per JVM, which explains why using the same daemon leaves the task up-to-date.

Would it make sense to drop the `/837790893` suffix from the class name for up-to-date checks and build cache keys when the class comes from a lambda? Would that cause any changes to be missed, e.g. lead to wrong cache hits? It seems to be not the case...

**Comment by wilkinsona** [comment] 2018-08-16 11:49
Unfortunately, the `1` in `com.example.ExamplePlugin$$Lambda$1` means that it's the first lambda that's been created in the JVM, not that it's the first lambda in `ExamplePlugin`. If some code that uses a lambda runs first the number will change. For example:

```
[Loaded com.example.AnotherPlugin from file:/Users/awilkinson/.gradle/caches/jars-3/5b588771d431b79ceec34f122c58b6e8/buildSrc.jar]
[Loaded com.example.AnotherPlugin$$Lambda$1/322100932 from com.example.AnotherPlugin]
[Loaded com.example.AnotherPlugin$$Lambda$2/604480364 from com.example.AnotherPlugin]
[Loaded com.example.ExamplePlugin from file:/Users/awilkinson/.gradle/caches/jars-3/5b588771d431b79ceec34f122c58b6e8/buildSrc.jar]
[Loaded com.example.ExamplePlugin$$Lambda$3/1174599796 from com.example.ExamplePlugin]
[Loaded com.example.ExamplePlugin$$Lambda$4/893152673 from com.example.ExamplePlugin]
```

If you swap the order in which the plugins are applied, the numbers change:

```
[Loaded com.example.ExamplePlugin from file:/Users/awilkinson/.gradle/caches/jars-3/5b588771d431b79ceec34f122c58b6e8/buildSrc.jar]
[Loaded com.example.ExamplePlugin$$Lambda$1/836371508 from com.example.ExamplePlugin]
[Loaded com.example.ExamplePlugin$$Lambda$2/1073862849 from com.example.ExamplePlugin]
[Loaded com.example.AnotherPlugin from file:/Users/awilkinson/.gradle/caches/jars-3/5b588771d431b79ceec34f122c58b6e8/buildSrc.jar]
[Loaded com.example.AnotherPlugin$$Lambda$3/2091160281 from com.example.AnotherPlugin]
[Loaded com.example.AnotherPlugin$$Lambda$4/2127862399 from com.example.AnotherPlugin]
```

I can't see a way to derive a name from a lambda that will be stable across builds.

**Comment by wolfs** [comment] 2018-08-16 12:40
@wilkinsona What Java version are you using? IIUC, there was a `javac` bug which was fixed and now the counter is per class: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8067422.

In your example it seems that the jar which contains the lambdas is not changing (`buildSrc.jar`). So maybe the Java bug above is something else. I saw the following code in `InnerClassLambdaMetafactory`:
```
lambdaClassName = targetClass.getName().replace('.', '/') + "$$Lambda$" + counter.incrementAndGet();
```

`counter` is a static field, so it would depend on the order the lambdas are loaded. That means that as there is change to the build file, the class name is stable (at least the part before the `/`).

**Comment by wilkinsona** [comment] 2018-08-16 14:43
> `counter` is a static field, so it would depend on the order the lambdas are loaded.

Yeah, that's the problem.

> That means that as there is change to the build file, the class name is stable (at least the part before the /).

I don't think it is stable even with an unchanged build.gradle. For example, the order in which lambdas are loaded or the number of lambdas that are loaded could vary depending on some conditional logic and properties that have been passed into the build.

**Comment by ldaley** [comment] 2018-08-16 21:42
configure-on-demand and composites are two other mechanics that can influence load order of configuration code.

Also, just adding a new plugin/script upstream of the lambda.

**Comment by wolfs** [comment] 2018-08-21 11:53
If the target class of the lambda is serializable, we can obtain a `SerializedLambda`, which contains the actual method which will be invoked:
```
interface SerializableConsumer extends Consumer<String>, Serializable {}
SerializableConsumer serializableConsumer = (String x) -> System.out.println(x);
Method method = serializableConsumer.getClass().getDeclaredMethod("writeReplace");
method.setAccessible(true);
SerializedLambda serializedLambda = (SerializedLambda) method.invoke(serializableConsumer);
```

`SerializedLambda` has `implClass` and `implMethodName` as fields - those would be enough to track changes.

If the target class is not serializable, then a simpler form of the lambda is created.

**Comment by wolfs** [comment] 2018-08-21 12:10
I guess we could parse the SAM method of the generated class for the lambda with asm and find out the actual invoked method.

**Comment by wolfs** [comment] 2018-08-23 16:13
So it is possible to write a Java agent which changes `LambdaMetaFactory` to add an annotation to each generated lambda class with the necessary information. Here is a spike for the implementation: https://github.com/wolfs/lambda-meta-information-java-agent

Here is a test verifying that it works:  https://github.com/wolfs/lambda-meta-information-java-agent/blob/master/instrumented-code/src/test/java/EnhancedLambdas.java#L17-L22

**Comment by lptr** [comment] 2018-08-24 07:10
Is your suggestion to drop the last part of the lambda class name include using the agent or without it? 

Just to be sure, you suggest that we retain only `<DeclaringClass>$$Lambda` from `<DeclaringClass>$$Lambda$154/00000000082FF1F0`? What if there are multiple lambdas declared by the same class?

**Comment by lptr** [comment] 2018-08-24 07:30
IIUC, your argument is that the only code that would result in different behavior without a change in cache key would need to look something like this:

```java
if (condition) {
    doLast(/* lambda #1 */);
} else {
    doLast(/* lambda #2 */);
}
```

...and in this case `condition` should somehow be represented as an input anyway.

That makes sense I think. I definitely prefer the simplicity this solution offers.

**Comment by lptr** [comment] 2018-08-24 08:50
Actually, this is not correct. The code with the condition could be inside the plugin configuring the task, and then `condition` itself is not an input to the task anymore. Yet Gradle should still be able to figure out the difference between using `lambda #1` and `lambda #2`.

**Comment by wolfs** [comment] 2018-08-29 07:53
For Gradle 5.0 we decided to disable up-to-date checks and caching when a lambda is used as a task action. There is currently no way to track the implementation of such an action reliably: https://github.com/gradle/gradle/pull/6503

**Closed by wolfs** 2018-08-29 07:53 UTC
Labels: a:bug, from:contributor, in:build-cache, in:incremental-build

**Comment by mockitoguy** [comment] 2018-09-07 15:26
In effect, in Gradle 5.0, if someone adds a doLast action in "build.gradle" that just prints a debug statement, it renders the entire task non-incremental and non cacheable. This makes the build slower and the team may not even notice. I am surprised the Gradle team considers this solution as viable. At LinkedIn we are finding it really hard to leverage distributed cache because it so easy to break cacheability of tasks and hard to track why tasks are not cacheable.

**Comment by wolfs** [comment] 2018-09-07 15:35
@mockitoguy Adding a `doLast` action in a build script will not disable caching/incremental build for the task. Only when the `doLast` action is implemented via a Java lambda. Groovy and Kotlin lambdas work just fine.

The reason why the task is not cacheable is shown in build scans. You can filter for non-cacheable tasks. The reason why the task is not up-to-date is also shown in build scans. Both things are printed on the info log. Where else would you expect that information to be shown?

**Comment by rgoldberg** [comment] 2019-09-21 09:57
> @mockitoguy Adding a `doLast` action in a build script will not disable caching/incremental build for the task. Only when the `doLast` action is implemented via a Java lambda. Groovy and Kotlin lambdas work just fine.

@wolfs: are you sure that Kotlin lambdas work just fine?

I have a plugin implemented completely in Kotlin that uses lambdas as arguments to `doFirst()` & `doLast()`.

When including the plugin in a composite build, and applying that plugin to another included build, `:common`, running:

```
./gradlew --info --warning-mode all --console=plain build
```

Outputs the following to the console:

```
> Task :common:compileJava
Caching disabled for task ':common:compileJava' because:
  Build cache is disabled
Task ':common:compileJava' is not up-to-date because:
  Additional action for task ':common:compileJava': was implemented by the Java lambda 'org.gradle.java.taskconfigurer.JavaCompileTaskConfigurer$$Lambda$1406/0x0000000801ffb440'. Using Java lambdas is not supported, use an (anonymous) inner class instead.
All input files are considered out-of-date for incremental task ':common:compileJava'.
Full recompilation is required because no incremental change information is available. This is usually caused by clean builds or changing compiler arguments.
Compiling with JDK Java compiler API.
Created classpath snapshot for incremental compilation in 0.035 secs.
:common:compileJava (Thread[Execution worker for ':common',5,main]) completed. Took 1.773 secs.
```

`org.gradle.java.taskconfigurer.JavaCompileTaskConfigurer` is implemented in Kotlin, as are all the other classes in the plugin.

I'm running using:

macOS 10.14.6 + all updates
Java 13: OpenJDK 64-Bit Server VM (build 13+33, mixed mode, sharing)
Gradle Wrapper 5.6.2 Kotlin DSL
Kotlin 1.3.50

With the following in my `build.gradle.kts` for the plugin:

```
tasks.withType<KotlinCompile>().configureEach {
    kotlinOptions {
        javaParameters = true
        jvmTarget      = VERSION_1_9.majorVersion
        verbose        = true
    }
}
```

**Comment by wolfs** [comment] 2019-10-07 08:23
Kotlin lambdas work fine, see https://github.com/gradle/gradle/issues/10854#issuecomment-535826639.
