### ISSUE TITLE
Maven-publish plugin doesn’t work with Gradle 4.0-rc-1

### ISSUE THREAD

**Issue by Egorand** [gradle/gradle#2228] opened 2017-06-01 11:25 UTC
Build fails with the following error:

```
A problem occurred configuring project ':android-standalone'.
> Could not resolve all dependencies for configuration ':android-standalone:alphaReleaseRuntimeClasspath'.
    > Exception thrown while executing model rule: PublishingPlugin.Rules#publishing(ExtensionContainer)
        > Could not get unknown property 'java' for SoftwareComponentInternal set of type org.gradle.api.internal.component.DefaultSoftwareComponentContainer.
```

In the build file, this happens in the following block:

```groovy
publishing {
    ...

    publications {
        libraryJar(MavenPublication) {
            def name = 'library'
            from project(":$name").components.java
```

The error suggests that components.java can't be resolved, in fact, when I log `components` I get `[]`. This works fine with Gradle 3.5.

**Comment by bmuschko** [comment] 2017-06-01 11:39
The following works fine for me:

```
apply plugin: 'java'
apply plugin: 'maven-publish'


group = 'com.example'
version = '1.0'

publishing {
    publications {
        libraryJar(MavenPublication) {
            from components.java
        }
    }

    repositories {
        maven {
            name 'fileBased'
            url "$buildDir/repo"
        }
    }
}
```

Why can't use just use `components.java` instead of `project(":$name").components.java`? Maybe your path is incorrect there and the project that is resolved doesn't apply the Java plugin.

**Comment by Egorand** [comment] 2017-06-01 11:52
Yes, I will definitely re-check the setup. It's a multi-module project, and the main module tries to publish all its dependency modules and itself.

**Comment by bmuschko** [comment] 2017-06-02 12:04
@Egorand Do you have any additional feedback here? I'd like to close the issue as I can't reproduce the problem.

**Comment by Egorand** [comment] 2017-06-02 12:10
@bmuschko haven't managed to investigate it further, but I'm pretty sure this is the problem with my configuration, which apparently was working in Gradle 3. Please feel free to close the issue.

**Comment by bmuschko** [comment] 2017-06-02 12:13
Cool, fell free to open a discussion on the forum if you need further help.

**Closed by bmuschko** 2017-06-02 12:13 UTC
Labels: a:question, from:contributor, in:publishing-plugin
