### ISSUE TITLE
Gradle 7.0 --illegal-access=permit in kotlin.daemon.jvm.options

### ISSUE THREAD

**Issue by kuFEAR** [gradle/gradle#17209] opened 2021-05-17 17:28 UTC
gradle 7.0+ doesn't receive custom jvm.options from org.gradle.jvmargs for kotlin daemon

### Expected Behavior
org.gradle.jvmargs=-Xms2g -Xmx4g -Dkotlin.daemon.jvm.options\="-Xmx1600M"
Kotlin's daemon should be configured with custom kotlin.daemon.jvm.options

### Current Behavior
![Screenshot 2021-05-17 at 20 23 22](https://user-images.githubusercontent.com/4124981/118531563-a3e5a380-b74e-11eb-8cb4-7bc424a3a1c7.png)

![Screenshot 2021-05-17 at 20 23 33](https://user-images.githubusercontent.com/4124981/118530953-f07caf00-b74d-11eb-9956-c32fec872291.png)

### Context
After update to gradle 7.0+ doesn't receive custom jvm.options from org.gradle.jvmargs for kotlin daemon
also https://github.com/gradle/gradle/issues/16843 there is a good point to add ability to customize it on startup

### Steps to Reproduce 
add to gradle.properties org.gradle.jvmargs=-Xms2g -Xmx4g -Dkotlin.daemon.jvm.options\="-Xmx1600M" and check system parameters (e.g. VisualVM)

### Your Environment
osx
gradle 7.0.1
OpenJdk 11
Kotlin 1.5.0

**Comment by kuFEAR** [comment] 2021-05-17 20:31
https://github.com/gradle/gradle/issues/17075 looks same

**Comment by kuFEAR** [comment] 2021-05-18 07:07
but if I put the prop via ./gradlew app:assembleDebug -Dkotlin.daemon.jvm.options=-Xmx2g it works fine and produce jvm options to kotlin daemons

**Comment by donat** [comment] 2021-06-10 16:18
There's a workaround in the JPMS support that causes this: https://github.com/gradle/gradle/blob/d6383fa764b5be77ff17a2ec468a4c72c10f6734/subprojects/base-services/src/main/java/org/gradle/internal/jvm/JpmsConfiguration.java#L58-L60

**Comment by donat** [comment] 2021-06-10 16:20
Duplicate of #17075

**Closed by donat** 2021-06-10 16:20 UTC
Labels: a:regression, to-triage
