### ISSUE TITLE
IDE/Eclipse plugin: incorrect versions in generated org.eclipse.jdt.core.prefs for Java 9

### ISSUE THREAD

**Issue by Nimlhug** [gradle/gradle#3376] opened 2017-11-04 14:28 UTC
### Expected Behavior
`# gradle eclipse`
.settings/org.eclipse.jdt.core.prefs platform/source/compliance settings should look like this:
    org.eclipse.jdt.core.compiler.codegen.targetPlatform=9
    org.eclipse.jdt.core.compiler.source=9
    org.eclipse.jdt.core.compiler.compliance=9

### Current Behavior
`# gradle eclipse`
.settings/org.eclipse.jdt.core.prefs platform/source/compliance settings look like this:
    org.eclipse.jdt.core.compiler.codegen.targetPlatform=1.9
    org.eclipse.jdt.core.compiler.source=1.9
    org.eclipse.jdt.core.compiler.compliance=1.9

### Context
When platform/source/compliance is set to 1.9, eclipse won't build. Java 9 no longer uses the 1.x versioning, but instead uses 9.x.x. 

### Steps to Reproduce (for bugs)
Create a Java project with the java and eclipse plugins. Set gradle sourceCompatibility to 9 (or 1.9...). Run gradle eclipse. Check  .settings/org.eclipse.jdt.core.prefs or try to build the project in eclipse using "new" features such as annotations or enums. This won't work.

### Your Environment
Eclipse Oxygen 1a, Oracle JDK 9.0.1, Gradle 4.3

**Comment by Unh0lyTigg** [comment] 2017-11-06 01:45
I have come up with a way to workaround this issue until it is fixed:

```groovy
eclipse.jdt.file.withProperties { props ->
    props.put('org.eclipse.jdt.core.compiler.codegen.targetPlatform', '9')
    props.put('org.eclipse.jdt.core.compiler.source', '9')
    props.put('org.eclipse.jdt.core.compiler.compliance', '9')
}
```

which can be inserted into your build.gradle file, as `withProperties` occurs after the `eclipseJdt` task has set the properties to store in `.settings/org.eclipse.jdt.core.prefs` but before they are written to file.

**Comment by donat** [comment] 2017-11-06 13:30
Duplicate of #3046

**Comment by Unh0lyTigg** [comment] 2017-11-06 23:14
This is not a direct duplicate of #3046. Although they stem from the same cause (how org.gradle.api.JavaVersion behaves regarding major java versions from Java 9 and on), this issue focuses on [org.gradle.plugins.ide.eclipse.model.Jdt.store(Properties)](https://github.com/gradle/gradle/blob/master/subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/model/Jdt.java#L60-L74) specifically, how it handles `sourceCompatibility` and `targetCompatibility`.

**Comment by Unh0lyTigg** [comment] 2017-11-06 23:20
I will also note, that this issue can also be mitigated by configuring the Execution Environments for 'JavaSE-9' or 'JavaSE-1.9' (it showed as the latter before I configured it) by selecting a compatible installed JRE.

**Comment by donat** [comment] 2017-11-07 03:12
@Unh0lyTigg you are correct. I closed it because I fixed the problem in Eclipse but not in Gradle itself. I'll provide a fix soon.

**Comment by donat** [comment] 2017-11-08 06:24
The fix has been merged to master.

**Closed** 2017-11-08 06:24 UTC
Labels: a:bug, from:contributor, in:eclipse-plugin
