### ISSUE TITLE
Sync task hangs when output directory contains a named pipe

### ISSUE THREAD

**Issue by robinverduijn** [gradle/gradle#2552] opened 2017-07-21 01:06 UTC
### Expected Behavior
The Sync task should remove any unexpected files from the destination directory when it runs, even if one of them is a named pipe.

### Current Behavior
When a named pipe exists in the output directory the Sync task gets blocked trying to read from it in order to determine its hash and just hangs indefinitely.

### Context
We have a complicated build with a step where a payload from a given source folder is synced to the application's runtime folder. Under certain circumstances, it is possible for the application to not shut down properly and leave a named pipe around in the destination folder. When the build runs and tries to ensure the runtime folder is up to date, the entire build will hang while Gradle attempts to read from the now-defunct named pipe.

Connecting a debugger to the build at that point indicates it is hanging in the following call stack:

```
Thread [Task worker Thread 5] (Suspended)
    FileInputStream.open0(String) line: not available [native method]
    FileInputStream.open(String) line: 195
    FileInputStream.<init>(File) line: 138
    DefaultFileHasher.hash(File) line: 57
    CachingFileHasher.snapshot(File, long, long) line: 104
    CachingFileHasher.snapshot(FileTreeElement) line: 91
    CachingFileHasher.hash(FileTreeElement) line: 77
    DefaultFileSystemSnapshotter.fileSnapshot(FileTreeElement) line: 189
    DefaultFileSystemSnapshotter.access$600(DefaultFileSystemSnapshotter, FileTreeElement) line: 53
    DefaultFileSystemSnapshotter$FileVisitorImpl.visitFile(FileVisitDetails) line: 223
    Jdk7DirectoryWalker$1.visitFile(Path, BasicFileAttributes) line: 85
    Jdk7DirectoryWalker$1.visitFile(Object, BasicFileAttributes) line: 58
    Files.walkFileTree(Path, Set<FileVisitOption>, int, FileVisitor<Path>) line: 2670
    Jdk7DirectoryWalker.walkDir(File, RelativePath, FileVisitor, Spec<FileTreeElement>, AtomicBoolean, boolean) line: 58
    DirectoryFileTree.walkDir(File, RelativePath, FileVisitor, Spec<FileTreeElement>, AtomicBoolean) line: 155
    DirectoryFileTree.visitFrom(FileVisitor, File, RelativePath) line: 133
    DirectoryFileTree.visit(FileVisitor) line: 118
    DefaultFileSystemSnapshotter.doSnapshot(DirectoryFileTree) line: 165
    DefaultFileSystemSnapshotter.access$500(DefaultFileSystemSnapshotter, DirectoryFileTree) line: 53
    DefaultFileSystemSnapshotter$4.create() line: 147
    DefaultFileSystemSnapshotter$4.create() line: 141
    DefaultProducerGuard<T>.guardByKey(T, Factory<V>) line: 51
    DefaultFileSystemSnapshotter.snapshotDirectoryTree(DirectoryFileTree) line: 141
    AbstractFileCollectionSnapshotter$FileCollectionVisitorImpl.visitDirectoryTree(DirectoryFileTree) line: 95
    AbstractFileCollectionSnapshotter$FileCollectionVisitorImpl.visitCollection(FileCollectionInternal) line: 80
    FileCollectionAdapter(AbstractFileCollection).visitRootElements(FileCollectionVisitor) line: 234
    TaskPropertyFileCollection(CompositeFileCollection).visitRootElements(FileCollectionVisitor) line: 185
    DefaultGenericFileCollectionSnapshotter(AbstractFileCollectionSnapshotter).snapshot(FileCollection, FileCollectionSnapshotBuilder) line: 51
    DefaultGenericFileCollectionSnapshotter.snapshot(FileCollection, TaskFilePropertyCompareStrategy, SnapshotNormalizationStrategy, InputNormalizationStrategy) line: 36
    OutputFilesTaskStateChanges(AbstractNamedFileSnapshotTaskStateChanges).buildSnapshots(String, FileCollectionSnapshotterRegistry, String, SortedSet<TaskFilePropertySpec>) line: 91
    OutputFilesTaskStateChanges(AbstractNamedFileSnapshotTaskStateChanges).<init>(String, TaskExecution, TaskExecution, FileCollectionSnapshotterRegistry, String, ImmutableSortedSet<TaskFilePropertySpec>, InputNormalizationStrategy) line: 58
    OutputFilesTaskStateChanges.<init>(TaskExecution, TaskExecution, TaskInternal, FileCollectionSnapshotterRegistry, OutputFilesSnapshotter, InputNormalizationStrategy) line: 36
    TaskUpToDateState.<init>(TaskInternal, TaskHistoryRepository$History, OutputFilesSnapshotter, FileCollectionSnapshotterRegistry, FileCollectionFactory, ClassLoaderHierarchyHasher, ValueSnapshotter) line: 57
    DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.getStates() line: 178
    DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.isUpToDate(Collection<String>) line: 88
    SkipUpToDateTaskExecuter.execute(TaskInternal, TaskStateInternal, TaskExecutionContext) line: 53
    ResolveTaskOutputCachingStateExecuter.execute(TaskInternal, TaskStateInternal, TaskExecutionContext) line: 54
    ValidatingTaskExecuter.execute(TaskInternal, TaskStateInternal, TaskExecutionContext) line: 58
    SkipEmptySourceFilesTaskExecuter.execute(TaskInternal, TaskStateInternal, TaskExecutionContext) line: 88
    ResolveTaskArtifactStateTaskExecuter.execute(TaskInternal, TaskStateInternal, TaskExecutionContext) line: 52
    SkipTaskWithNoActionsExecuter.execute(TaskInternal, TaskStateInternal, TaskExecutionContext) line: 52
    SkipOnlyIfTaskExecuter.execute(TaskInternal, TaskStateInternal, TaskExecutionContext) line: 54
    ExecuteAtMostOnceTaskExecuter.execute(TaskInternal, TaskStateInternal, TaskExecutionContext) line: 43
    CatchExceptionTaskExecuter.execute(TaskInternal, TaskStateInternal, TaskExecutionContext) line: 34
    DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(BuildOperationContext) line: 242
    DefaultBuildOperationExecutor$RunnableBuildOperationWorker<O>.execute(O, BuildOperationContext) line: 317
    DefaultBuildOperationExecutor$RunnableBuildOperationWorker<O>.execute(BuildOperation, BuildOperationContext) line: 309
    DefaultBuildOperationExecutor.execute(O, BuildOperationWorker<O>, DefaultBuildOperationState) line: 185
    DefaultBuildOperationExecutor.run(RunnableBuildOperation) line: 95
    DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(TaskInternal) line: 235
    DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(Object) line: 224
    DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(TaskInfo) line: 121
    DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor$TaskExecutorWorker, TaskInfo) line: 77
    DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(TaskInfo) line: 102
    DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(Object) line: 96
    DefaultTaskExecutionPlan.execute(TaskInfo, WorkerLease, Action<TaskInfo>) line: 612
    DefaultTaskExecutionPlan.executeWithTask(WorkerLease, Action<TaskInfo>) line: 567
    DefaultTaskPlanExecutor$TaskExecutorWorker.run() line: 96
    ExecutorPolicy$CatchAndRecordFailures.onExecute(Runnable) line: 63
    StoppableExecutorImpl$1.run() line: 46
    ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) line: 1142
    ThreadPoolExecutor$Worker.run() line: 617
    ThreadFactoryImpl$ManagedThreadRunnable.run() line: 55
    Thread.run() line: 745
```

Looking at some similar questions on StackOverflow, it appears that the hang-on-open behaviour is expected even if it does cause some people to scratch their head over it:

- https://stackoverflow.com/questions/6408099/fileinputstream-blocks-on-the-constructor-when-opening-a-named-pipe
- https://stackoverflow.com/questions/5782279/why-does-a-read-only-open-of-a-named-pipe-block

In the specific case of Gradle's Sync task and given the behaviour of Java when it is asked to read a named pipe which has nothing on the other end writing anything, I wonder if it would be more appropriate to avoid hashing the file. Technically, it isn't even a proper file so perhaps it should be skipped entirely (left alone or outright deleted during the sync).

### Steps to Reproduce (for bugs)

1. Use this `build.gradle` file:

```
task syncTask( type: Sync ) {
  from 'src'
  into 'dest'
}
```

2. Create this `test.sh` file to perform the necessary setup and invoke Gradle:

```
#!/bin/sh

set -e

rm -rf src dest
mkdir -p src dest
touch src/foo.txt

set -x

# Run sync task without the presence of a named pipe
gdl syncTask

# Create a named pipe in the output folder of the sync task
mkdir -p dest/temp
mkfifo dest/temp/named-pipe

# Run the sync task and watch it hang trying to open the named pipe
gdl syncTask
```

3. Invoke `test.sh` and observe it hanging when Gradle is invoked with a destination directory containing a named pipe.

### Workaround

As I was testing this out I found some behaviour I could not explain, but which avoided the I/O blocking entirely. If you use a build.gradle file with a (bogus) `exclude` stanza, no hanging is observed. I.e.:

```
task syncTask( type: Sync ) {
  from 'src'
  into 'dest'
  exclude {
    'non-existent'
  }
}
```

The exclusion pattern doesn't even have to match the name of the pipe; just its presence in the task definition is sufficient to change the Sync behaviour.

With the above build.gradle file, the named pipe under `dest/temp/named-pipe` is left alone by the Sync task and remains under the destination folder. I don't know if that is truly the proper behaviour under those circumstances -- one could argue it should be removed since no such file exists under the `from` folder -- but at least the build does not get blocked trying to scan the destination folder.

**Comment by big-guy** [comment] 2017-07-21 01:45
Thanks @robinverduijn 

Your workaround works because it excludes all files. I don't think this is what you want.

`exclude { 'non-existent' }` is the same as `exclude { true }` because Groovy treats any non-empty string as "true".

I haven't tried this, but you could try something like:

```
import java.nio.file.attribute.BasicFileAttributes
import java.nio.file.Files

task syncTask( type: Sync ) {
  from 'src'
  into 'dest'
  exclude { fte ->
    if (!fte.isDirectory() && fte.getSize() == 0) {
      def attrs = Files.readAttributes(fte.getFile().toPath(), BasicFileAttributes)
      return attrs.isOther()
    }
    return false
  }
}
```

The idea being that if the file isn't a directory and is zero-length (like pipes will be), you can use NIO2 apis to see if the file is an unusual file.  If it is, you can exclude it.  I fear this may only work on the source side and not on the destination side though.

**Comment by robinverduijn** [comment] 2017-07-21 02:27
Ah, that would explain why the workaround appeared to "work" for. Thanks for clearing that up; I had mixed up the `exclude` closure with the Ant-style exclude pattern.

Unfortunately, the pipes will be present on the destination side, so checking for unusual files in the `exclude` closure using NIO, as you said, will not really work.

**Comment by robinverduijn** [comment] 2017-08-10 20:50
I have created a pull request that fixes the issue reported here: https://github.com/gradle/gradle/pull/2691

**Comment by lptr** [comment] 2017-09-14 14:16
@big-guy's workaround sounds like the way to go to make this work for you.

However, Gradle should not just hang when encountering such a file, and instead fail with a proper error message that lets you discover what the problem is.

**Comment by robinverduijn** [comment] 2017-09-14 18:19
Thanks for the feedback! I appreciate it.

The workaround won't work on named pipes in the destination folder, though, and that's where my particular problem is.

For the broader issue in this ticket, if Gradle failed whenever a named pipe was encountered then I'd still be not much closer to having things work properly. Our current workaround is to delete any named pipes from the output folder before running the build but I was looking for a solution that would allow this to be handled gracefully from within Gradle itself. Failing, rather than being able to handle whatever is encountered in a destination folder, would seem to be suboptimal.

I agree that hanging indefinitely would be even worse, but would it make sense to have a task property for Sync (and Copy) that tells them to skip over or delete any named pipes encountered?

**Comment by lptr** [comment] 2017-09-14 21:15
I think that'd be overly specific. What we could do instead is to do something like `sync.outputs.upToDateWhen { false }` to prevent Gradle from snapshotting the outputs at all. This is not the case currently, and we _will_ snapshot the outputs even if `upToDateWhen()` is `false`, but this can be changed. I haven't thought this through completely yet, and if it's not a possibility, we can add a separate kill-switch for any kind of caching for the task, which would mean we never need to snapshot it, ever, and hence we wouldn't care about named pipes or other weird stuff in the output directory (or among the inputs for that matter).

Just curious: how do you end up with named pipes in your output that you are okay with deleting before the build?

**Comment by robinverduijn** [comment] 2017-09-14 22:05
Our application uses Amazon's Kinesis, and under certain circumstances when a clean shutdown is not possible, Kinesis leaves a named pipe around on the filesystem. We know we don't need those pipes since the next startup would use a different one, and the old one is defunct since the process behind it would no longer be running anyway.

The named pipe is always under a folder in the destination we don't care about anyway (e.g. `${destination}/temp/`), but I didn't think there was a way to exclude certain entries in the destination folder from the Sync task entirely. If there was, we could just configure that temp folder to be skipped.

As you said, if `sync.outputs.upToDateWhen { false }` avoided snapshotting the outputs altogether, that would probably also work, though at the expense of some performance I suppose since it would always copy everything over even if some files had not changed?

**Comment by lptr** [comment] 2017-09-15 06:51
Right, we would be basically killing the sync nature of `Sync` by not snapshotting outputs. Another way to deal with this would be to acknowledge that sometimes we know there are files on disk we explicitly want to prevent from snapshotting. We already have a way to declare files to be ignored when snapshotting runtime classpath inputs:

```groovy
normalization {
  runtimeClasspath {
    ignore '**/some-other-file.txt'
  }
}
```

We have plans to extend this behavior for other inputs. We could also have something for outputs. I can't say when we are going to do this, though. Until then deleting the pipes seems to be the best solution.

**Comment by robinverduijn** [comment] 2017-11-23 23:54
Just pinging to see if there are any more concrete plans around dealing with named pipes. Or is there a thread or feature request ticket somewhere I can follow to find out more?

**Comment by robinverduijn** [comment] 2019-06-18 01:54
Updated test files (attached) to properly verify the first `Sync` task worked successfully. This avoids my initial misconception about the supposed `exclude` fix.

To run, unzip the build.gradle and test.sh files in an empty folder and run `gradle init` (or `gradle init --type basic --dsl groovy --project-name test-2552` for Gradle 5 and above) to initialize the Gradle wrapper.

- [test-2552.tar.gz](https://github.com/gradle/gradle/files/3299469/test-2552.tar.gz)

Expected output while this issue is still reproducible:

```
$ ./test.sh
+ ./gradlew syncTask

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
+ test -e dest/foo.txt
+ mkdir -p dest/temp
+ mkfifo dest/temp/named-pipe
+ ./gradlew syncTask
<-------------> 0% EXECUTING [10s]
> :syncTask
```

**Comment by lptr** [comment] 2019-06-25 13:46
@paplorinc can you please check whether https://github.com/gradle/gradle/pull/9746 also fixes the use case here?

**Comment by paplorinc** [comment] 2019-07-05 10:39
Yes, it's fixed in [latest master](https://github.com/gradle/gradle/pull/9878) and added tests for it in https://github.com/gradle/gradle/pull/9884

**Closed** 2019-07-05 13:31 UTC
Labels: @build-cache, a:bug, affects-version:3.0, affects-version:3.1, affects-version:3.2, affects-version:3.3, affects-version:3.4, affects-version:3.5, affects-version:4.0, affects-version:4.1, from:contributor, in:core

**Comment by robinverduijn** [comment] 2019-07-06 00:38
Also confirmed that this works now (with latest mainline). Thanks for the fixes, and the added testcases!
