### ISSUE TITLE
maven-publish: publishToMavenLocal should detect up-to-date status

### ISSUE THREAD

**Issue by eekboom** [gradle/gradle#6532] opened 2018-08-27 16:27 UTC
Using gradle 4.9 and the maven-publish plugin, the publishToMavenLocal task publishes each artifact to the local repo again and again even if there have been no changes since the last invocation.

As a general rule, we strive to have all tasks in status "up-to-date' when invoked a second time without changes.
Also with a large project with many subproject only the changed subproject's publications should be published again.

It should be quite easy to detect whether the task is up-to-date, right?
At least if I add inputs/outputs manually it works fine.

For testing you can just do `gradle init --type=java-library` then add the plugin and the publishing configuration:
```
plugins {
    // Apply the java-library plugin to add support for Java Library
    id 'java-library'
    id 'maven-publish'
}

group = 'com.foo.bar'
version = '0.0.1-SNAPSHOT'

publishing {
    publications {
        jarModule(MavenPublication) {
            from components.java
        }
    }
}
```
Consecutive invocations always result in
```4 actionable tasks: 2 executed, 2 up-to-date```

**Comment by jjohannes** [comment] 2019-10-18 12:58
This is a duplicate of: #6925

**Closed by jjohannes** 2019-10-18 12:58 UTC
Labels: in:publishing-plugin
