### ISSUE TITLE
ClasspathUtil#getClasspath throws when URI scheme is not 'file'

### ISSUE THREAD

**Issue by DPUkyle** [gradle/gradle#3223] opened 2017-10-17 19:30 UTC
I'm working on an enterprise applications which registers custom URI schemes on the classpath. `o.g.i.classloader.ClasspathUtil#getClasspath(j.l.ClassLoader)` assumes that all URLs on the classpath start with the `file://`, and an IllegalArgumentException will bubble up when it tries to add new File refs to the `implementationClassPath`.

I will share a breaking unit test and a fix shortly.

**Comment by bmuschko** [comment] 2017-10-17 20:48
The class `org.gradle.internal.classloader.ClasspathUtil` is an internal API and is meant for internal consumption only. I don't think we'll want to make it a public API. Given that internal tooling depends on some of the method I'd like to avoid making any changes to it now.

Why exactly do you need to this in your build script or plugin? I think it would be totally feasible to implement it yourself.

**Comment by DPUkyle** [comment] 2017-10-17 21:55
Hi Ben, thanks for replying.

I should clarify - I am not calling ClasspathUtil anywhere. Rather, I am working to convert a library from maven to Gradle and this library registers custom URI schemes on the classpath. So while I am not directly invoking ClasspathUtil, its expectation that the classloader's URLs all use the file scheme causes failures during test compilation and test execution.

I am not quite ready to share the library I'm working on as the Gradle build is still a work in progress. Once I iron out some bugs, though, I will be happy to share.

For now, here's a preview of the stack trace; note that all namespaces are either from the JDK or Gradle APIs:

```
URI scheme is not "file"
java.lang.IllegalArgumentException: URI scheme is not "file"
        at java.io.File.<init>(File.java:421)
        at org.gradle.internal.classloader.ClasspathUtil$1.visitClassPath(ClasspathUtil.java:63)
        at org.gradle.internal.classloader.VisitableURLClassLoader.visit(VisitableURLClassLoader.java:48)
        at org.gradle.internal.classloader.ClassLoaderVisitor.visit(ClassLoaderVisitor.java:38)
        at org.gradle.internal.classloader.ClasspathUtil.getClasspath(ClasspathUtil.java:58)
        at org.gradle.process.internal.worker.DefaultWorkerProcessFactory.create(DefaultWorkerProcessFactory.java:67)
        at org.gradle.api.internal.tasks.testing.worker.ForkingTestClassProcessor.forkProcess(ForkingTestClassProcessor.java:76)
        at org.gradle.api.internal.tasks.testing.worker.ForkingTestClassProcessor.processTestClass(ForkingTestClassProcessor.java:69)
        at org.gradle.api.internal.tasks.testing.processors.RestartEveryNTestClassProcessor.processTestClass(RestartEveryNTestClassProcessor.java:47)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:29)
        at org.gradle.internal.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:133)
        at org.gradle.internal.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:34)
        at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:73)
        at org.gradle.internal.operations.BuildOperationIdentifierPreservingRunnable.run(BuildOperationIdentifierPreservingRunnable.java:39)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by bmuschko** [comment] 2017-10-17 22:43
Thanks for the additional information. For now I am going to close this issue as the use case is unclear to me. We can reopen once you provide a sample that explains why you'd need the behavior.

**Comment by DPUkyle** [comment] 2017-10-18 00:06
Hi Ben. I can reliably reproduce this issue using these instructions:

1. `$ git clone https://github.com/manifold-systems/manifold.git`
2. `$ git checkout gradlefy`
3. `$ ./gradlew check`

To apply my fix and remedy the problem, I take the following steps from my fork of gradle/gradle:
1. `$ ./gradlew install -Pgradle_installPath=/tmp/customGradle`
2. Change directories to the clone of `manifold-systems/manifold` above
3. `$ /tmp/customGradle/bin/gradle clean check`

**Comment by bmuschko** [comment] 2017-10-18 15:00
@DPUkyle Could you please condense your example project to a minimum? I am really only looking for the portion that produces the issue to get a better picture.

**Comment by DPUkyle** [comment] 2017-10-18 15:15
Hi Ben, good morning. I should be clear: I think this is a bug and not a feature request.

The simplest way to illustrate the behavior is the test I added: https://github.com/gradle/gradle/pull/3224/commits/b97d2dd459b5be09438de0f544b9a6378bdfb6b9

Of course in the real world, I am never calling `ClasspathUtil#getClasspath` directly. Rather, the `test` task, in the act of isolating the testing work in a separate classloader, invokes ClasspathUtil. But at this point, my application has already injected its custom URI scheme into the classpath. ClasspathUtil fails because it assumes all URIs are using the `file://` scheme.

**Comment by bmuschko** [comment] 2017-10-18 15:25
@DPUkyle Hi Kyle, understood. What I am looking for is a project with a build script a single test that reproduces this issue then. It's unclear to me what code makes this happen. The test you provided tests a class in Gradle core but how does this happen in a user-based project?

> But at this point, my application has already injected its custom URI scheme into the classpath. 

Show me some code demonstrates the need for doing that in that sample project.

**Comment by DPUkyle** [comment] 2017-10-18 15:51
Thanks Ben. I'll share an example project sometime later today.

**Comment by DPUkyle** [comment] 2017-10-19 04:09
Hi team. Sorry this took so long. Here's the most concise example I can share: https://github.com/DPUkyle/manifold-example

Note that the `test` task will hang. I don't know why the `java.lang.IllegalArgumentException: URI scheme is not "file"` exception does not bubble-up, but when testing with my own version of Gradle patched with https://github.com/DPUkyle/gradle/commit/3dac87593259168f17590792ca091f0936467d48, the build is fine.

**Comment by big-guy** [comment] 2017-10-19 04:48
I think the safest thing to do is to fork Java compilation.  By default, Gradle tries to run the Java compilation in-process, but if the compiler plugin is injecting things into the javac classloader, that's no longer safe (because I think it's also polluting Gradle's classloader).

I would try:
```
tasks.withType(JavaCompile) {
    options.compilerArgs += '-Xplugin:Manifold'
    options.fork = true
    options.incremental = false
}
```
[This doesn't hang for me](https://scans.gradle.com/s/2evvp2q4h25u4).

I set `incremental=false` because I'm not sure our incremental compilation detection is valid with the Manifold plugin applied.

**Comment by DPUkyle** [comment] 2017-10-19 05:01
Thanks Sterling. There is definitely some non-determinism happening. But I do not believe the problem is related to compilation; rather, the build should hang during the `test` execution. AFAIK the test task assigns workers to disposable, isolated classloaders. I agree more investigation would be required to see how this library works with the new incremental compiler.

FWIW, I speculate the non-determinism is caused by the static initialization block the manifold plugin inserts into the class files.

I would love to be able to share a build scan, but once the build fails it just hangs and won't finish.

We really, really want to be able to build [manifold](http://manifold.systems/) with Gradle and, even more important, make sure it can be consumed by Gradle projects! I'm kind of stumped.

<img width="664" alt="screen shot 2017-10-18 at 21 56 52" src="https://user-images.githubusercontent.com/2841209/31754912-a4d0cc94-b44f-11e7-9b49-9ac381786b61.png">

If nothing else, my PR's unit test shows that it's possible to get a non-`file://` URI scheme into the classpath. My fix does nothing more than do a safety check and filter those values out before instantiating a File using an unexpected scheme.

**Comment by DPUkyle** [comment] 2017-10-19 05:08
OK, I see. I applied your suggestion and the build no longer hangs. Thank you for the workaround!

**Comment by DPUkyle** [comment] 2017-10-19 05:13
Thanks again guys. Here's a successful scan for me after applying the workaround: https://gradle.com/s/4hzhdnbiiu2pe

**Comment by bmuschko** [comment] 2017-11-09 23:42
Duplicate of https://github.com/gradle/gradle/issues/2483.

**Closed by bmuschko** 2017-11-09 23:42 UTC
Labels: a:feature, from:contributor, in:core

**Comment by bmuschko** [comment] 2017-11-13 16:19
@DPUkyle We fixed this issue. I'd appreciate your feedback by trying out a nightly build of Gradle (`https://services.gradle.org/distributions-snapshots/gradle-4.4-20171112235945+0000-bin.zip`).

**Comment by DPUkyle** [comment] 2017-11-13 21:06
Hi @bmuschko . I applied the nightly (https://github.com/manifold-systems/manifold/commit/ba415d969230e20f87e9593b7a9106433b8636ed) and reverted the workaround and everything passes as expected. Thank you!

**Comment by bmuschko** [comment] 2017-11-13 21:20
@DPUkyle Awesome, thanks for checking!
