### ISSUE TITLE
Add @InputDirectories annotation

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#5756] opened 2018-06-22 00:25 UTC
`@InputDirectory` and `@InputFiles` serve different purposes for incremental compilation. `@InputFiles` will only return the files inputted for `IncrementalTaskInputs`, but `@InputDirectory` will perform a deep search. It would be nice to have `@InputDirectories` to perform the same deep search on each file. This behavior can be emulated at runtime by doing something like this:
```kt
for (dir in resSrcDirs) inputs.dir(dir)
```

**Comment by wolfs** [comment] 2018-06-22 07:00
@SUPERCILEX Could you elaborate a little bit more? `@InputFiles` and `@InputDirectory`/`@InputDirectories` should have (nearly) the same effect on `IncrementalTaskInputs`. Could you provide an example what you mean by "deep search" and how that is different between the two annotations?

**Comment by SUPERCILEX** [comment] 2018-06-22 07:16
Maybe it's a bug? Say I have directories `foo` and `bar` with example structures like so:
```
root
├── foo
│   ├── file1
│   └── file2
└── bar
    └── file3
```

Now say I give `@InputFiles` the args `[foo, bar]`. It will spit those same "files" back at me in the `IncrementalTaskInputs`. On the other hand, if I use those args with `@InputDirectories` (currently at runtime as show above), it would compute these files in the `IncrementalTaskInputs`: [file1, file2, file3]. I much prefer the latter result, hence asking for an `@InputDirectories` annotation.

**Comment by wolfs** [comment] 2018-06-22 07:19
I guess this issue is a duplicate of https://github.com/gradle/gradle/issues/4166, right? The different reporting currently only happens when `IncrementalTaskInputs.isIncremental() == false`, right?

**Comment by SUPERCILEX** [comment] 2018-06-22 07:21
Oh yeah, I think so. So `@InputFiles` _is_ supposed to do a deep search if the file is a directory?

**Comment by wolfs** [comment] 2018-06-22 07:23
For reporting changed files it is. We just currently don't when the task is not incremental.

Closing this issue as a duplicate of #4166.

**Closed by wolfs** 2018-06-22 07:23 UTC
Labels: a:feature, from:contributor, in:core, in:incremental-build

**Comment by SUPERCILEX** [comment] 2018-06-22 07:28
SGTM 👍
