### ISSUE TITLE
Idea plugin can generate directory-based project files

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1366] opened 2017-02-08 14:51 UTC
Original issue: https://issues.gradle.org/browse/GRADLE-1041

**Highly voted issue: 41**

### Expected Behavior

The Idea plugin provides an option to generate [directory-based project files](https://www.jetbrains.com/help/idea/2016.3/project.html#newProjectFormat). Alternatively, a separate plugin could be created.

### Current Behavior

Only [file-based project files](https://www.jetbrains.com/help/idea/2016.3/project.html#file_based_format) can be generated.

### Context

Directory-based project files is going to be the future direction for Idea. The file-based format will likely go away in future versions of Idea.

**Comment by guai** [comment] 2017-02-08 14:59
I think this task should also include adding support of new IDEA's hierarchical modules, which they made for their own gradle support. Now we can have individual idea submodule for each gradle's source set.

**Comment by guai** [comment] 2017-02-09 11:01
It seems they have more dir types now. Dir can be marked as "test resources root" now, and gradle plugin have only testSourceDirs collection in org.gradle.plugins.ide.idea.model.IdeaModule

**Comment by guai** [comment] 2017-02-09 11:16
In my company we also added some options into generated idea project via direct xml manipulation. Some of them may be useful as part of that plugin. They are:
- generated run configurations (ProjectRunConfigurationManager component)
- annotationProcessing flag (CompilerConfiguration component)
- native2AsciiForPropertiesFiles flag & defaultCharsetForPropertiesFiles (Encoding component's attrs)
- idea to recognize this project as gradle project. It shows the tree of gradle tasks in the sidebar (GradleSettings component)
- autoscrollFromSource flag (iws's ProjectView component)

**Comment by guai** [comment] 2017-02-09 11:20
I think plugin can also attempt to detect idea.project.vcs param. Like if .hg/.git dir is present

**Comment by redi-wassere** [comment] 2017-07-24 12:47
Any updates on this? Or expected in what future version?

**Comment by oehme** [comment] 2017-08-07 11:36
We are currently in the design phase for an overhauled `idea` plugin, working closely with JetBrains. I can't give you a timeline at this point, but will update this issue when we have a better idea of what we plan to do.

**Comment by zmitrok** [comment] 2017-12-25 21:55
It would be nice to have Gradle and IntelliJ to keep the java compiler flags in sync or at least avoid direct XML manipulation in order to generate an IntelliJ project with custom java compiler flags. Java 9 migration will require a lot of '--add-modules' and '--add-open' flags next year.

**Comment by rgoldberg** [comment] 2018-05-03 17:32
The JetBrains PoC link is giving me a 404

**Comment by oehme** [comment] 2018-05-03 18:31
Seems like the Github repo is still private. I've changed the link to the plugin portal entry instead.

**Comment by bric3** [comment] 2018-05-04 08:47
@oehme Yes could you share the estimate time of availability of this new way, 3month, 1year. Or gradle 4.10, gradle 5.0, gradle 5.10, etc...

I know the gradle team is working on many topics, but this is another area that is kinda frustrating.

**Comment by oehme** [comment] 2018-05-04 09:00
I can't share a target date yet, but the above plugin already works. @eskatos is this something that users could give a shot to provide feedback or should they wait? Is there some documentation on it?

**Comment by bric3** [comment] 2018-05-04 09:14
@oehme Yes could you share the estimate time of availability of this new way, 3month, 1year. Or gradle 4.10, gradle 5.0, gradle 5.10, etc...

I know the gradle team is working on many topics, but this is another area that is kinda frustrating.

**Comment by bric3** [comment] 2018-05-04 09:15
@oehme Is there some documentation out there, on how to use it

**Comment by nskvortsov** [comment] 2018-05-10 10:37
@bric3 @oehme @eskatos  JFYI the repo was made public, a documentation for first public version `v0.1` is [available](https://github.com/JetBrains/gradle-idea-ext-plugin/wiki/DSL-spec-v.-0.1)

**Comment by bric3** [comment] 2018-05-12 13:06
@nskvortsov great thanks, I'll give it a try !

**Comment by canthony** [comment] 2018-05-23 07:49
@oehme IDEA's native importer, though, doesn't allow us to customise the modules at all. 

https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000575470-IntelliJ-2018-Gradle-Sync?page=1#community_comment_360000195270

**Comment by oehme** [comment] 2018-05-23 08:42
@canthony That's not true, have you followed the discussion above? It is highly customizable, taking input both from Gradle's built-in idea-DSL as well as from the additional DSL added by the plugin that @nskvortsov wrote.

**Comment by canthony** [comment] 2018-05-23 08:51
@oehme I did try the extended plugin on a big IntelliJ/Gradle project, and the DSL for the ideal modules did not appear to be called when synchronised from inside IntelliJ, but was when called from the original gradle plugin. This h appears to follow what the reply on the forum in previous comment said. 

I shall retry with a smaller and simpler test case.

I apologise if I appeared to be overly critical.

**Comment by nskvortsov** [comment] 2018-05-23 09:22
@canthony the idea dsl extension plugin is at a very early stages at the moment and not much customization is implemented for idea module. Would you mind opening an issue that describes your requirements here https://github.com/JetBrains/gradle-idea-ext-plugin/issues ?

**Comment by canthony** [comment] 2018-05-23 09:56
@nskvortsov I will give it a go - but, essentially and ideally, I'd simply want the DSL in the existing idea plugin to apply when synced from within the IDE! 

FWIW, I can confirm that currently it *isn't*. My simple test case below - based on the unit test in the extension, and then adding a directory dependency to a module - only works when the idea task is called directly, and that generated IDEA Module *isn't* the one used in the Synced IDEA Project.

```
import org.gradle.plugins.ide.idea.model.SingleEntryModuleLibrary
import org.jetbrains.gradle.ext.*

plugins {
  id "org.jetbrains.gradle.plugin.idea-ext" version "0.1"
}

idea {
  project {
    settings {
      compiler.resourcePatterns '!*.java;!*.class'
      inspections {
        "some" { enabled = true }
      }
      runConfigurations {
        "Run my app"(Application) {
          mainClass = 'foo.App'
          workingDirectory = "\$projectDir"
          moduleName = getProject().idea.module.name
        }
        defaults(Application) {
          jvmArgs = '-DmyKey=myVal'
        }
      }
    }
  }

  module { im ->
    def pf = im.pathFactory
    iml {
      whenMerged { module ->
        def path = pf.path(file("/tmp/example"))
        module.dependencies.add(new SingleEntryModuleLibrary(path, "compile"))
      }
    }
  }

}


task printSettings {
  doLast {
    println(projectDir)
    println(project.idea.project.settings)
  }
}
```

**Comment by nskvortsov** [comment] 2018-05-23 10:58
@canthony when idea performs the import, actual `iml` files are created by the IDE and not passed back to Gradle execution. So, no content manipulations (`beforeMerged`, `afterMerged` and `withXml`) clauses will be executed.

What Idea Extended DSL aims for, is providing additional configuration options to cover existing content manipulation cases. That is why I would really appreciate, if you could describe your use case in [Idea Ext DSL tracker]( https://github.com/JetBrains/gradle-idea-ext-plugin/issues )

**Comment by oehme** [comment] 2018-05-23 11:42
Instead of synthesizing module dependencies in a content hook, just add a normal dependency to a custom Configuration and add that Configuration to the appropriate scope in the module configuration DSL.

**Comment by oehme** [comment] 2018-05-23 11:47
Actually Gradle could make the `whenMerged` hook work since it doesn't require an actual XML file. We can open another issue for that. But your use case would be better modeled as described above.

**Comment by canthony** [comment] 2018-05-23 13:42
@oehme @nskvortsov I can confirm that custom config + tweaking the idea module scopes does exactly what I want it to. Thank you!.

**Comment by oehme** [comment] 2018-12-21 17:14
The `idea-ext` plugin and IDEA's importer work really well, even for our own complex build. For that reason I'm closing this issue and we will no longer make big investments into the `idea` task.

**Closed by oehme** 2018-12-21 17:14 UTC
Labels: a:feature, from:contributor, in:idea-plugin

**Comment by AndrewTasso** [comment] 2019-03-04 17:45
@oehme , I agree that JetBrains would best be suited to develop a plugin to configure Idea. However, stopping investment on a well-establish, widely-used, and stable plugin in favor of one that is still a work-in-progress seems very short-sighted.

**Comment by benweizhu** [comment] 2019-07-19 08:55
And the documentation is still there. (a little bit misleading people)

https://docs.gradle.org/current/dsl/org.gradle.plugins.ide.idea.model.IdeaModule.html

**Comment by patkovskyi** [comment] 2019-10-25 14:11
Would it make sense to update Idea plugin documentation to clearly state that it should only be applied if you want to use file-based (*.iml *.ipr *.iws) instead of a directory-based (.idea/) project structure?

My team uses directory-based projects and I see that people keep adding 'idea' plugin to their build.gradle even though it makes no sense and adds no value.

**Comment by lacasseio** [comment] 2019-10-28 12:40
Thanks for the comment @patkovskyi. We are having discussion if we would just upstream the entire plugin to JetBrains and deprecate our plugin. These days, there is no need for applying the plugin to have IDE support in IntelliJ. We are more likely to keep moving toward the native importer than support generating the IDE files.

**Comment by 62mkv** [comment] 2023-03-21 07:24
At least the bit about documentation on the [gradle.org page](https://docs.gradle.org/current/userguide/idea_plugin.html#sec:idea_configuration) is still very much relevant - not a single word about that plugin being useless for "directory-based format" projects and "idea-ext" plugin existing. Maybe at least a disclaimer could be added on top of that page? thanks a lot!
