### ISSUE TITLE
buildSrc + Cmake in Android Studio break incremental builds

### ISSUE THREAD

**Issue by Petrakeas** [gradle/gradle#19811] opened 2022-02-02 18:53 UTC
Consecutive builds in Android Studio are not as fast as they can be under the following circumstances:

- having a `buildSrc` directory with a `build.gradle` or `build.gradle.kts`  (even with no code inside)
- using a module with `externalNativeBuild` and `cmake` block
- using the "play/run" button of Android Studio to build and deploy on a device.

If any of the previous 3 requirements is not met, the issue is not reproduced and the build is fast.

The cause of this issue could be related to [this one](https://github.com/gradle/gradle/issues/19266#issuecomment-1021088057), regarding kotlin and 'filteredArgumentsMap'.

### Expected Behavior

Hitting the play button a second or third time without making any changes, should result in a faster build.

Logging using `--debug` should show that all tasks are already `UP-TO-DATE`.

Running with `--profile`, then visiting `"build/reports/profile"`, opening the last `"profileXXX.html*` file and going to the "Artifact Transforms" tab, should show no transformed artifacts.

### Current Behavior

Hitting the play button a second or third time, takes some time (2 seconds in the test project).

The logs (when run with `--debug`) show: 

```
Task ':buildSrc:compileKotlin' is not up-to-date because:
  Value of input property 'filteredArgumentsMap' has changed for task ':buildSrc:compileKotlin'
```

This causes other tasks to take a longer time than usual. For example all artifacts are transformed from scratch. This can be seen by running with `--profile`, visiting `"build/reports/profile"`, opening the last `"profileXXX.html*` file and going to the "Artifact Transforms" tab. 

Note that deleting the `buildSrc` directory resolves the issue and the expected behavior is shown.

### Context

When adding `buildSrc` in my project (which always uses R8 minification), I noticed significantly longer consecutive build times. After testing, I noticed that `buildSrc` , `cmake` and Android's play button don't play well together.

### Steps to Reproduce 

https://github.com/Petrakeas/buildSrc-issue

### Your Environment

Gradle 7.0.2
AGP 7.0.4
Android Studio 2020.3.1 Patch 4

**Comment by ljacomet** [comment] 2024-09-05 13:40
Sorry for the late reply!

Trying the reproducer on the CLI shows a normal behaviour:
* First execution of `./gradlew assembleDebug` after touching the `.kt` file in `buildSrc` takes 15+ seconds
* Second execution finishes in less than a second

This indicates that the problem is not in Gradle but might be in AndroidStudio itself.

Given the time that has passed, I would recommend to verify with a recent version of AS if the problem persists. If it does, file an issue on the [Android issue tracker](https://source.android.com/docs/setup/contribute/report-bugs#filing-a-bug).

Closing this as there is no core Gradle issue.

**Closed by ljacomet** 2024-09-05 13:40 UTC
Labels: a:bug, in:execution-engine, to-triage
