### ISSUE TITLE
Provide support for declaring repositories on a per-artifact basis

### ISSUE THREAD

**Issue by Ricket** [gradle/gradle#1207] opened 2017-01-18 23:37 UTC
### Expected Behavior
User should be able to declare which repository an artifact should come from. Then gradle won't search all the repositories in order; it will only search the given repository for the artifact.

### Current Behavior
Every repository is searched for every artifact.

### Context
Often a repository will be added to a gradle configuration to resolve just one artifact in the build. It would be nice to specify that repository inline with the dependency that needs it. This adds clarity for everyone involved, and should shorten build times because Ivy will not have to query that repository for every other dependency.

This was originally tracked in [GRADLE-1066](https://issues.gradle.org/browse/GRADLE-1066), opened by Chris Beams.

**Comment by pioterj** [comment] 2017-03-24 15:58
Closing as duplicate of https://github.com/gradle/gradle/issues/1369.

**Closed by pioterj** 2017-03-24 15:58 UTC
Labels: a:feature, from:contributor, in:dependency-management
