### ISSUE TITLE
Variant dependency resolution failing with printing list of variants including correct one.

### ISSUE THREAD

**Issue by adLuk** [gradle/gradle#31321] opened 2024-11-16 07:47 UTC
### Current Behavior

As result of registering new feature into java extension and using capabilities configuration in feature registration, value of used version is undefined at time when is used for capability. This leads to problem in resolving variant specific dependencies between modules and resulting output message about missing variant contains also variant which should be validly resolved. This creates really misleading error message and it is really problematic to find what is wrong. 
As workaround to this problem is possible to use gradle.properties files to define group and version properties and ensure values are available in time when they are needed. 
[more details can be find here](https://discuss.gradle.org/t/multi-jdk-distribution-plugin/) 

### Expected Behavior

1. Error message missing variant with valid variant in output is not appearing. 
2. project properties group, name and version are lazy and properly evaluated from build.gradle so workaround with property files is not needed

### Context (optional)

I have attempted to create simple plugin providing release version of jar for multiple type of selected JDKs and as result of that I was facing this issue. However with help on forum we have been able to find workaround to make it work. Unfortunately error message was so confusing it made process of problem location nearly impossible for me and without that help I would not have solution for my problem. 

### Self-contained Reproducer Project

branch where workaround was removed to provide easy way to reproduce. I will keep this branch in current state so you can use it as use case for reproduction. Plugin code is defined in buildSrc folder. 

[https://github.com/adLuk/cz.a-d.java.tools/tree/gradle-error](https://github.com/adLuk/cz.a-d.java.tools/tree/gradle-error)

### Gradle version

8.10.2

### Build scan URL (optional)

https://gradle.com/s/af7vdpcmyy3zk

### Your Environment (optional)

OpenSuse Leap Linux

**Comment by Vampire** [comment] 2024-11-16 17:12
Just a small clarification, as I recommended to create this issue but was majorly misunderstood it seems.
This issues should actually complain that in the error message - which probably is valid - the capability is not mentioned.
From the error message it reads "A needed variant B of project C, here are the variants of project C" which included the variant A was after.
The problem was that the group and / or version of the capability did not match as group and version were prematurely read before set to their final value, but the error message did not mention the capability at all.

**Comment by adLuk** [comment] 2024-11-17 04:22
Thank you for clarification. I was to focus on part of problem I could clearly describe and help to reproduce so I did not really properly describe what you mention in that thread.

**Comment by reinsch82** [comment] 2024-11-19 13:44
This issue will be closed as a duplicate of
 - https://github.com/gradle/gradle/issues/23827

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

related:
 - https://github.com/gradle/gradle/issues/31075

**Closed by reinsch82** 2024-11-19 13:44 UTC
Labels: a:bug, to-triage
