### ISSUE TITLE
Unable to upgrade past gradle 6.4.1 on NetBSD - Could not load compiled classes for build file '.../build.gradle' from cache

### ISSUE THREAD

**Issue by abs0** [gradle/gradle#16568] opened 2021-03-17 23:16 UTC
### Expected Behavior
Running `./gradlew wrapper --gradle-version 6.5` should complete without errors

### Current Behavior
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'trainasone'.
> Could not load compiled classes for build file '.../build.gradle' from cache. Expected class file /home/abs/.gradle/caches/jars-8/c8bdd7c8f7209e20b5547e5b6f8e07e8/cp_proj.jar/build_a7t5iqlwta50b1yt6rudtcn7a.class does not exist.
```

### Context
Unable to upgrade past gradle 6.4.1. Tested with 6.5, 6.8.3 and various versions in between.

### Steps to Reproduce 
Try to run any version of gradle higher than 6.4.1 on NetBSD
(Absolutely expecting this to be closed with a "WONTFIX_USE_A_LESS_OBSCURE_OS", but wanted to submit so its here for anyone else falling into the same hole -- thanks)
[log.txt](https://github.com/gradle/gradle/files/6160302/log.txt)

### Your Environment

Tested with directory just containing scratch build.gradle
```
task hello {
  doLast {
    println 'world'
  }
}
```

Stracktrace ends:

```
Caused by: java.lang.ClassNotFoundException: build_8fzelqap9qhfyga82kl5n2c17                                                                                   
        at org.gradle.groovy.scripts.internal.DefaultScriptCompilationHandler$ScriptClassLoader.loadClass(DefaultScriptCompilationHandler.java:383)
        at org.gradle.groovy.scripts.internal.DefaultScriptCompilationHandler$ClassesDirCompiledScript.loadClass(DefaultScriptCompilationHandler.java:340)
        ... 141 more                                                                                                                                           
Caused by: java.io.EOFException: Detect premature EOF                                                                                                          
        at java.base/jdk.internal.loader.Resource.getBytes(Resource.java:131)                                                                                  
        ... 143 more                                                                                                                                           
```

Working version:
```
./gradlew --version                   

------------------------------------------------------------
Gradle 6.4.1
------------------------------------------------------------

Build time:   2020-05-15 19:43:40 UTC
Revision:     1a04183c502614b5c80e33d603074e0b4a2777c5

Kotlin:       1.3.71
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.10-internal (Oracle Corporation 11.0.10-internal+0-adhoc.pkgsrc.openjdk-jdk11u-jdk-11.0.10-9-1)
OS:           NetBSD 9.99.81 amd64
```

Failing version:
```
./gradlew --version

------------------------------------------------------------
Gradle 6.5
------------------------------------------------------------

Build time:   2020-06-02 20:46:21 UTC
Revision:     a27f41e4ae5e8a41ab9b19f8dd6d86d7b384dad4

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.10-internal (Oracle Corporation 11.0.10-internal+0-adhoc.pkgsrc.openjdk-jdk11u-jdk-11.0.10-9-1)
OS:           NetBSD 9.99.81 amd64
```

Build scan URL: build scan fails with
```
An exception occurred applying plugin request [id: 'com.gradle.enterprise', version: '3.5', artifact: 'com.gradle:gradle-enterprise-gradle-plugin:3.5']
> Could not find implementation class 'com.gradle.enterprise.gradleplugin.GradleEnterprisePlugin' for plugin 'com.gradle.enterprise' specified in jar:file:/home/abs/.gradle/caches/jars-8/359a3903d392cf7b7f1750e93aa55cab/gradle-enterprise-gradle-plugin-3.5.jar!/META-INF/gradle-plugins/com.gradle.enterprise.properties.

```

**Comment by ljacomet** [comment] 2021-03-18 08:27
A few things you can try:
* Run with `--rerun-tasks`
* Nuke the folder `/home/abs/.gradle/caches/jars-8/c8bdd7c8f7209e20b5547e5b6f8e07e8`

In short,  I want to know whether this happens just all the time or if it is a bad case of cache corruption.

**Comment by abs0** [comment] 2021-03-18 09:58
Still occurs with --rerun-tasks and after nuking entire .gradle dir
(run with --no-daemon to try to reduce dependencies)

[typescript.txt](https://github.com/gradle/gradle/files/6162985/typescript.txt)

Thanks

**Comment by ljacomet** [comment] 2021-07-14 09:05
@gradle/execution This is again a file system related issue which shows up in Gradle 6.5 when the native libraries were updated. Could you take a look?

**Comment by wolfs** [comment] 2021-07-14 10:46
@abs0 Thank you for reporting. Does the problem also happen with Java 8?

**Comment by wolfs** [comment] 2021-07-14 11:21
@abs0 Some more context: Gradle uses some native integration for supported operating systems for stating files or manipulating the environment. This native integration supports FreeBSD but not NetBSD. You can find the OS detection here: https://github.com/gradle/native-platform/blob/197f81c5b76659cf6a7a8a0a16ef825ff6ab703a/native-platform/src/main/java/net/rubygrapefruit/platform/internal/Platform.java#L71

Given that NetBSD is not supported, Gradle falls back to using the JDK methods for doing the file operations and various other things. This should work, though it seems like it doesn't in your case. It may be that this is a problem on our side with some assumption that the native integration is always available.

**Comment by wolfs** [comment] 2021-07-14 11:48
@abs0 And finally, it would be great if you could share the Daemon log file. You can find this in the `/home/abs/.gradle/daemon/<gradle-version>/daemon-<PID>.out.log`.

**Comment by abs0** [comment] 2021-07-27 14:26
> @abs0 And finally, it would be great if you could share the Daemon log file. You can find this in the `/home/abs/.gradle/daemon/<gradle-version>/daemon-<PID>.out.log`.

Tested a './gradlew hello' with a build.gradle as below, with logs from 6.4.1 and 7.1.1:

Is there an option to bypass the native integration on a supported platform to run a test to cross check? 

Thanks

```
task hello {
  doLast {
    println 'world'
  }
}
```

[7.1.1-daemon.out.log](https://github.com/gradle/gradle/files/6886233/7.1.1-daemon.out.log)
[6.4.1-daemon.out.log](https://github.com/gradle/gradle/files/6886234/6.4.1-daemon.out.log)

**Comment by abs0** [comment] 2021-07-27 14:34
Matching log from openjdk8, gradle 7.1.1

[7.1.1-openjdk8-daemon.out.log](https://github.com/gradle/gradle/files/6886344/7.1.1-openjdk8-daemon.out.log)

**Comment by wolfs** [comment] 2021-07-28 17:17
I still don't know what is going on :( I somewhat expect that [NioFileMetadataAccessor](https://github.com/gradle/gradle/blob/30cab53062b32ad61d48031c4faec6756bd115da/subprojects/native/src/main/java/org/gradle/internal/nativeintegration/filesystem/jdk7/NioFileMetadataAccessor.java#L31) is broken somehow on NetBSD. Which is strange, because it works on other operating systems.

I wonder if you could run [NioFileMetadataAccessorTest](https://github.com/gradle/gradle/blob/30cab53062b32ad61d48031c4faec6756bd115da/subprojects/native/src/test/groovy/org/gradle/internal/nativeintegration/filesystem/services/NioFileMetadataAccessorTest.groovy#L29) on NetBSD. In order to do so, I suppose you need to check out older Gradle version (like Gradle 6.4) and then replace `NioFileMetadataAccessor` and `NioFileMetadataAccessorTest` with the new contents. Or create a completely new project which only contains the few classes required for running the test.

**Comment by vladp** [comment] 2021-08-24 20:26
this is also being tracked in NetBSD GNAT bug tracking

https://gnats.netbsd.org/56140

**Comment by wolfs** [comment] 2021-11-18 14:19
@abs0 It would be helpful to provide the results of running the above test on NetBSD. Without that feedback we are going to close the issue since we currently don't have the time to investigate the NetBSD problem.

**Comment by abs0** [comment] 2021-11-19 23:33
> @abs0 It would be helpful to provide the results of running the above test on NetBSD. Without that feedback we are going to close the issue since we currently don't have the time to investigate the NetBSD problem.

That would be checking out 6.4 and running with NioFileMetadataAccessor and NioFileMetadataAccessorTest from 6.5 or later? I'll look at it this weekend

**Comment by abs0** [comment] 2021-11-25 18:36
So I tried to build v6.4.0 and it failed with the following on NetBSD (both via openjdk8 and openjdk11)

Could not open cache directory 529dubpf4zsftrqyud8uwks9d (/home/abs/.gradle/caches/6.4-rc-4/gradle-kotlin-dsl/529dubpf4zsftrqyud8uwks9d).

I then scripted up building pretty much every tag, and excluding those that fail downloading missing assets it looks like:
4.10 - 7.3 fail with that "Could not open cache directory" error
4.5 - 4.9 fail with "unresolved supertypes: org.gradle.api.initialization.Settings"
4.0 - 4.4 fail with "unable to access file: corrupted zip file"
2.14 - 3.51 fail with "General error during conversion: java.lang.NoClassDefFoundError: org/gradle/api/internal/AbstractTask"
2.10 built successfully

I'll retest on a Linux box with openjdk8 to confirm if these are all NetBSD specific, something seems very odd here

**Comment by wolfs** [comment] 2021-11-26 14:51
Thank you for trying it out!

It seems like all versions since 2.14 are broken on NetBSD :( I really wonder what is going on there. It seems like the implementation of the local caches/file locking may be broken. Can you reproduce the problem in Gradle 6.x when using a project with some Kotlin build scripts?

**Comment by 2nex** [comment] 2022-08-15 08:22
am also facing this challenge
Could not load compiled classes for settings file 'C:\Users\user\Desktop\top2\flutter_application\android\settings.gradle' from cache.       
> settings_40bag1r29t3wdmkm1uuelbobr

**Comment by dressupgeekout** [comment] 2022-12-30 01:01
FWIW -- I'm also seeing this on NetBSD/amd64 9.99.97 with Gradle 7.5.1.

**Comment by abs0** [comment] 2022-12-30 13:16
I've just upgraded to NetBSD-10_BETA, and recompiled all packages including openjdk11, and gradle > 6.4.1 seems to be working fine for me (now using gradle 7.6)

Note I was previously using openjdk11 built on netbsd-9 on netbsd-9 and netbsd-current, so I suspect its more likely the compiling with more recent gcc/NetBSD which resolved the issue...

**Comment by wolfs** [comment] 2023-01-11 10:39
@abs0 So this seems to be fixed now? Do you use a Gradle distribution pre-built by us? I'll close the issue, please comment if it isn't fixed yet on newer NetBSD versions.

**Closed by wolfs** 2023-01-11 10:39 UTC
Labels: a:bug, @execution

**Comment by 2nex** [comment] 2023-01-11 17:09
Good day.. Am having this challenge. Expo> Configure project :expo
Error: Autolinking is not set up in `settings.gradle`: expo modules won't
be autolinked.

> Configure project :expo-modules-core
Warning: Mapping new ns
http://schemas.android.com/repository/android/common/02 to old ns
http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns
http://schemas.android.com/repository/android/generic/02 to old ns
http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns
http://schemas.android.com/sdk/android/repo/addon2/02 to old ns
http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns
http://schemas.android.com/sdk/android/repo/repository2/02 to old ns
http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns
http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns
http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns
http://schemas.android.com/repository/android/common/02 to old ns
http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns
http://schemas.android.com/repository/android/generic/02 to old ns
http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns
http://schemas.android.com/sdk/android/repo/addon2/02 to old ns
http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns
http://schemas.android.com/sdk/android/repo/repository2/02 to old ns
http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns
http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns
http://schemas.android.com/sdk/android/repo/sys-img2/01

> Configure project :react-native-reanimated
AAR for react-native-reanimated has been found
C:\Users\user\Desktop\mec\allfiles\FindMechanic\node_modules\react-native-reanimated\android\react-native-reanimated-69-jsc.aar
Warning: Mapping new ns
http://schemas.android.com/repository/android/common/02 to old ns
http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns
http://schemas.android.com/repository/android/generic/02 to old ns
http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns
http://schemas.android.com/sdk/android/repo/addon2/02 to old ns
http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns
http://schemas.android.com/sdk/android/repo/addon2/03 to old ns
http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns
http://schemas.android.com/sdk/android/repo/repository2/02 to old ns
http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns
http://schemas.android.com/sdk/android/repo/repository2/03 to old ns
http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns
http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns
http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns
http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns
http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns
http://schemas.android.com/repository/android/common/02 to old ns
http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns
http://schemas.android.com/repository/android/generic/02 to old ns
http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns
http://schemas.android.com/sdk/android/repo/addon2/02 to old ns
http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns
http://schemas.android.com/sdk/android/repo/addon2/03 to old ns
http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns
http://schemas.android.com/sdk/android/repo/repository2/02 to old ns
http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns
http://schemas.android.com/sdk/android/repo/repository2/03 to old ns
http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns
http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns
http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns
http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns
http://schemas.android.com/sdk/android/repo/sys-img2/01
<=============> 100% CONFIGURING [10m 19s]

The Kotlin Gradle plugin was loaded multiple times in different
subprojects, which is not supported and may break the build.
This might happen in subprojects that apply the Kotlin plugins with the
Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the
versions are eq
ual.
Please add the Kotlin plugin to the common parent project or the root
project, then remove the versions in the subprojects.
If the parent project does not need the plugin, add 'apply false' to the
plugin line.
See:
https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
The Kotlin plugin was loaded in the following projects:
':react-native-gesture-handler', ':react-native-screens'

> Task :expo-constants:createDebugExpoConfig
Execution optimizations have been disabled for task
':expo-constants:createDebugExpoConfig' to ensure correctness due to the
following reasons:
  - Gradle detected a problem with the following location:
'C:\Users\user\Desktop\mec\allfiles\FindMechanic\android'. Reason: Task
':expo-constants:createDebugExpo
Config' uses this output of task ':app:compileDebugAidl' without declaring
an explicit or implicit dependency. This can lead to incorrect results
being produced, d
epending on what order the tasks are executed. Please refer to
https://docs.gradle.org/7.6/userguide/validation_problems.html#implicit_dependency
for more details
about this problem.
  - Gradle detected a problem with the following location:
'C:\Users\user\Desktop\mec\allfiles\FindMechanic\android'. Reason: Task
':expo-constants:createDebugExpo
Config' uses this output of task ':app:compileDebugRenderscript' without
declaring an explicit or implicit dependency. This can lead to incorrect
results being pro
duced, depending on what order the tasks are executed. Please refer to
https://docs.gradle.org/7.6/userguide/validation_problems.html#implicit_dependency
for more
details about this problem.
  - Gradle detected a problem with the following location:
'C:\Users\user\Desktop\mec\allfiles\FindMechanic\android'. Reason: Task
':expo-constants:createDebugExpo
Config' uses this output of task ':app:generateDebugBuildConfig' without
declaring an explicit or implicit dependency. This can lead to incorrect
results being pro
duced, depending on what order the tasks are executed. Please refer to
https://docs.gradle.org/7.6/userguide/validation_problems.html#implicit_dependency
for more
details about this problem.
  - Gradle detected a problem with the following location:
'C:\Users\user\Desktop\mec\allfiles\FindMechanic\android'. Reason: Task
':expo-constants:createDebugExpo
Config' uses this output of task ':app:checkDebugAarMetadata' without
declaring an explicit or implicit dependency. This can lead to incorrect
results being produc
ed, depending on what order the tasks are executed. Please refer to
https://docs.gradle.org/7.6/userguide/validation_problems.html#implicit_dependency
for more det
ails about this problem.
  - Gradle detected a problem with the following location:
'C:\Users\user\Desktop\mec\allfiles\FindMechanic\android'. Reason: Task
':expo-constants:createDebugExpo
Config' uses this output of task ':app:javaPreCompileDebug' without
declaring an explicit or implicit dependency. This can lead to incorrect
results being produced
, depending on what order the tasks are executed. Please refer to
https://docs.gradle.org/7.6/userguide/validation_problems.html#implicit_dependency
for more detai
ls about this problem.
  - Gradle detected a problem with the following location:
'C:\Users\user\Desktop\mec\allfiles\FindMechanic\android'. Reason: Task
':expo-constants:createDebugExpo
Config' uses this output of task ':app:mergeDebugShaders' without declaring
an explicit or implicit dependency. This can lead to incorrect results
being produced,
depending on what order the tasks are executed. Please refer to
https://docs.gradle.org/7.6/userguide/validation_problems.html#implicit_dependency
for more details
 about this problem.
  - Gradle detected a problem with the following location:
'C:\Users\user\Desktop\mec\allfiles\FindMechanic\android'. Reason: Task
':expo-constants:createDebugExpo
Config' uses this output of task ':app:compileDebugShaders' without
declaring an explicit or implicit dependency. This can lead to incorrect
results being produced
, depending on what order the tasks are executed. Please refer to
https://docs.gradle.org/7.6/userguide/validation_problems.html#implicit_dependency
for more detai
ls about this problem.
***@***.***\config-plugins\build\plugins\withStaticPlugin.js:149
        throw error;
        ^

PluginError: Failed to resolve plugin for module "expo-build-properties"
relative to "C:\Users\user\Desktop\mec\allfiles\FindMechanic"
    at resolvePluginForModule
***@***.***\config-plugins\build\utils\plugin-resolver.js:98:11)
    at resolveConfigPluginFunctionWithInfo
***@***.***\config-plugins\build\utils\plugin-resolver.js:188:7)
    at resolveConfigPluginFunction
***@***.***\config-plugins\build\utils\plugin-resolver.js:179:7)

    at withStaticPlugin
***@***.***\config-plugins\build\plugins\withStaticPlugin.js:108:70)
    at
***@***.***\config-plugins\build\plugins\withPlugins.js:38:84
    at Array.reduce (<anonymous>)
    at withPlugins
***@***.***\config-plugins\build\plugins\withPlugins.js:38:18)
    at withConfigPlugins
***@***.***\config\build\plugins\withConfigPlugins.js:45:47)
    at fillAndReturnConfig
***@***.***\config\build\Config.js:315:78)
    at getConfig
***@***.***\config\build\Config.js:382:10)
{
  code: 'PLUGIN_NOT_FOUND',
  cause: undefined,
  isPluginError: true
}

> Task :expo-constants:createDebugExpoConfig FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo-constants:createDebugExpoConfig'.
> Process 'command 'cmd'' finished with non-zero exit value 1

* Try:
Execution optimizations have been disabled for 1 invalid unit(s) of work
during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD FAILED in 20m 24s
54 actionable tasks: 4 executed, 50 up-to-date
react-native
