### ISSUE TITLE
Read version catalogue in `buildSrc` conventions files

### ISSUE THREAD

**Issue by bartekbluestone** [gradle/gradle#31676] opened 2024-12-11 14:42 UTC
### Expected Behavior

It should be possible to use version catalogue reference in `buildSrc`, and in conventions files. It would help add custom dependecies in multi project repository.

### Current Behavior (optional)

It cannot read data in conventions files.

### Context

I would like to set 2 boms as deps for projects of given type. Currently i use subproject section in root directory.

**Comment by ov7a** [comment] 2024-12-12 12:51
This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/15383

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

****

Related:
* https://github.com/gradle/gradle/issues/28063

**Closed** 2024-12-12 12:52 UTC
Labels: closed:duplicate
