### ISSUE TITLE
Signing publications should be idempotent

### ISSUE THREAD

**Issue by jbartok** [gradle/gradle#22375] opened 2022-10-12 06:37 UTC
Signing a publication more than once causes the following error:

```
Caused by: org.gradle.api.internal.tasks.DefaultTaskContainer$DuplicateTaskException: Cannot add task 'signMavenJavaPublication' as a task with that name already exists.
```

The plugin should be idempotent for this situation and potentially other cases (e.g. configuration signing).

**Comment by vlsi** [comment] 2022-10-12 10:05
This is a duplicate of https://github.com/gradle/gradle/issues/21857

**Comment by jbartok** [comment] 2022-10-13 06:09
> This is a duplicate of #21857

@vlsi , thank you for pointing that out.

**Closed** 2022-11-03 12:04 UTC
Labels: a:feature, to-triage
