### ISSUE TITLE
After udpate to  8.0.1 gradle, publish  credentials not working

### ISSUE THREAD

**Issue by Rollczi** [gradle/gradle#24107] opened 2023-03-02 03:25 UTC
### Expected Behavior

Publish snapshot

### Current Behavior

logs:
https://github.com/Rollczi/LiteCommands/actions/runs/4309905971/jobs/7517808240#step:5:613
problem:
<img width="881" alt="image" src="https://user-images.githubusercontent.com/49173834/222320069-5324c199-448d-48b7-b64c-c1791efa9f0b.png">

### Context
I'm trying to update gradle 8.0.1

### Steps to Reproduce 
Repo: https://github.com/Rollczi/LiteCommands
Changes: https://github.com/Rollczi/LiteCommands/commit/4b785b912e2e63c8e266d5e3ad66e6d86ef3ede6
Gradle conventions file with credentials: https://github.com/Rollczi/LiteCommands/blob/master/buildSrc/src/main/kotlin/litecommands.java-conventions.gradle.kts#L84

### Your Environment
Also not working on my PC:
Gradle 8.0.1,Gradle Enterprise plugin 3.12.3
Windows 11 10.0 (amd64)
Java runtime: Amazon Corretto OpenJDK Runtime Environment 17.0.5+8-LTS
Java VM: Amazon Corretto OpenJDK 64-Bit Server VM 17.0.5+8-LTS (mixed mode)
Max JVM memory heap size: 2 GiB

**Comment by ljacomet** [comment] 2023-03-02 09:10
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #24040 

Please add your use case and 👍 to that issue.

***

Note that [this comment](https://github.com/gradle/gradle/issues/24040#issuecomment-1446526136) contains a workaround for now.

**Closed by ljacomet** 2023-03-02 09:10 UTC
Labels: closed:duplicate
