### ISSUE TITLE
Gradle Test case Failure

### ISSUE THREAD

**Issue by tsprasath** [gradle/gradle#4977] opened 2018-04-09 09:04 UTC
While the running the below script for build the gradle project

sh 'gradle wrapper'
sh './gradlew --refresh-dependencies build'

Below is the error while building Gradle build and test cases.

:compileTestJava NO-SOURCE
:processTestResources
:testClasses
:testJava HotSpot(TM) 64-Bit Server VM warning: You have loaded library /usr/lib/libz.so.1.2.7 which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.

com.*******Test > testStandardOperations FAILED
    java.lang.AssertionError at FlightChangeProcessorITest.kt:127
2018-04-04 13:03:56.398  WARN 111690 --- [read-1-producer] org.apache.kafka.clients.NetworkClient   : [Producer clientId=flight-processor-1-test-StreamThread-1-producer] Connection to node 0 could not be established. Broker may not be available.
2018-04-04 13:03:56.495  WARN 111690 --- [ndardOperations] org.apache.kafka.clients.NetworkClient   : [Consumer clientId=consumer-1, groupId=testStandardOperations] Connection to node 0 could not be established. Broker may not be available.
2018-04-04 13:03:56.500  INFO 111690 --- [ SessionTracker] o.a.zookeeper.server.SessionTrackerImpl  : SessionTrackerImpl exited loop!

1 test completed, 1 failed
:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: ***/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.5.1/userguide/command_line_interface.html#sec:command_line_warnings

**Comment by blindpirate** [comment] 2018-04-09 11:12
I'm sorry but I don't quite understand, is the test case supposed to pass? Have you checked the test report  `***/tests/test/index.html`?

**Comment by oehme** [comment] 2018-04-09 13:00
Closing as this does not follow our issue template.

This looks like a problem in your code/tests, not like a problem in Gradle. Please only open issues when you are convinced that the problem is on the Gradle side and provide a reproducible sample project.

**Closed by oehme** 2018-04-09 13:00 UTC

**Comment by tsprasath** [comment] 2018-04-09 14:57
Can i know the below error why am i getting

:testJava HotSpot(TM) 64-Bit Server VM warning: You have loaded library /usr/lib/libz.so.1.2.7 which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c ', or link it with '-z noexecstack'.Can i know the below error why am i getting

:testJava HotSpot(TM) 64-Bit Server VM warning: You have loaded library /usr/lib/libz.so.1.2.7 which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c ', or link it with '-z noexecstack'.

**Comment by blindpirate** [comment] 2018-04-09 15:01
That has nothing to do with Gradle. If you compile your code with `javac` manually you'll still get these warnings. Seems like your own code/environment issues.

**Comment by tsprasath** [comment] 2018-04-10 07:25
Thank you for the quick response.
