### ISSUE TITLE
Allow to change Transform logs log level

### ISSUE THREAD

**Issue by gildor** [gradle/gradle#10112] opened 2019-07-30 06:57 UTC
I have an Android project with 124 modules and use Jetifier that used Artifact transform API, so essentially all Android modules use it (more than 100 in my case) and I see multiple logs per each artifact (because there are multiple transormation:

```
Transforming artifact core-runtime.aar (androidx.arch.core:core-runtime:2.0.0) with JetifyTransform
Transforming artifact core-runtime.aar (androidx.arch.core:core-runtime:2.0.0) with ExtractAarTransform
Transforming artifact core-runtime.aar (androidx.arch.core:core-runtime:2.0.0) with AarTransform
Transforming artifact core-runtime.aar (androidx.arch.core:core-runtime:2.0.0) with JetifyTransform
Transforming artifact core-runtime.aar (androidx.arch.core:core-runtime:2.0.0) with ExtractAarTransform
Transforming artifact core-runtime.aar (androidx.arch.core:core-runtime:2.0.0) with AarTransform
```

During build with --info I'm getting 34 thousands of such lines in Gradle logs from Jetifier and whole log is 38 thousands of lines, so Jetifier is almost 90% of completely useless logs because it's not even clean build, all dependencies are already transformed, so it's like up-to-date transform and the same for every Android module

I propose to have some GRADLE flag that allows change log level of those transformations logs, so it would be possible appear them only on debug or completely disable because it makes impossible to use info logs from the command line and very hard to use them even from logs viewer

**Comment by hungvietnguyen** [comment] 2019-08-07 09:53
Another idea is to not log a transform (or push it to --debug) if it is up-to-date, cached, or maybe also no-op. (A no-op transform is one where the output file is not written.)

**Comment by gildor** [comment] 2020-10-07 14:48
It's still a valid request, we need some way to control Transforming logs

**Comment by cobexer** [comment] 2024-01-25 13:48
Sorry for the late reply.

The issue is in the backlog of the relevant team and is prioritized by them.
***
Transformed to a bug because we would like to change the level it is logged at and not make it configurable.

**Comment by asodja** [comment] 2024-01-25 14:10
Note: There are some tests that rely on this output. We should check change tests to use build operations instead of log output.

**Comment by mihalyr** [comment] 2024-08-15 13:58
I was hit with this today as well, on the most recent 8.10 Gradle version this is still an issue. It makes looking at info output very very painful as I need to scroll through a useless dump of transform logs to see the action info logs. Moving this to debug would be fine too, but they have not much INFO value.

**Closed** 2024-10-28 08:39 UTC
Labels: a:bug, in:artifact-transforms
