### ISSUE TITLE
SourceDistributionResolver will break with Gradle 9.0

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#16491] opened 2021-03-10 14:52 UTC
When importing a Kotlin DSL project into IDEA:

The configuration `:myproject:detachedConfiguration1` was resolved without accessing the project in a safe manner. This may happen when a configuration is resolved from a different project. This behaviour has been deprecated and is scheduled to be removed in Gradle 9.0.

```
at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:594) |  
-- | --
  |   | at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1900(DefaultConfiguration.java:149) |  
  |   | at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$SelectedArtifactsProvider.getValue(DefaultConfiguration.java:1328) |  
  |   | at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$SelectedArtifactsProvider.getValue(DefaultConfiguration.java:1318) |  
  |   | at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getSelectedArtifacts(DefaultConfiguration.java:1390) |  
  |   | at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.visitContents(DefaultConfiguration.java:1377) |  
  |   | at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.visitContents(DefaultConfiguration.java:497) |  
  |   | at org.gradle.api.internal.file.AbstractFileCollection.getFiles(AbstractFileCollection.java:126) |  
  |   | at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getFiles(Unknown Source) |  
  |   | at org.gradle.kotlin.dsl.resolver.SourceDistributionResolver$sourceDirs$2.invoke(SourceDistributionProvider.kt:59) |  
  |   | at org.gradle.kotlin.dsl.resolver.SourceDistributionResolver$sourceDirs$2.invoke(SourceDistributionProvider.kt:38) |  
  |   | at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) |  
  |   | at org.gradle.kotlin.dsl.resolver.SourceDistributionResolver.getSourceDirs(SourceDistributionProvider.kt) |  
  |   | at org.gradle.kotlin.dsl.resolver.SourceDistributionResolver.sourceDirs(SourceDistributionProvider.kt:49) |  
  |   | at org.gradle.kotlin.dsl.resolver.SourcePathProvider.downloadedSources(SourcePathProvider.kt:72) |  
  |   | at org.gradle.kotlin.dsl.resolver.SourcePathProvider.sourceRootsOf(SourcePathProvider.kt:64) |  
  |   | at org.gradle.kotlin.dsl.resolver.SourcePathProvider.sourcePathFor(SourcePathProvider.kt:42) |  
  |   | at org.gradle.kotlin.dsl.tooling.builders.KotlinScriptTargetModelBuilder.gradleSource(KotlinBuildScriptModelBuilder.kt:426) |  
  |   | at org.gradle.kotlin.dsl.tooling.builders.KotlinScriptTargetModelBuilder.buildModel(KotlinBuildScriptModelBuilder.kt:416) |  
  |   | at org.gradle.kotlin.dsl.tooling.builders.KotlinBuildScriptModelBuilder.kotlinBuildScriptModelFor$kotlin_dsl_tooling_builders(KotlinBuildScriptModelBuilder.kt:118) |  
  |   | at org.gradle.kotlin.dsl.tooling.builders.KotlinDslScriptsModelBuilder.buildFor(KotlinDslScriptsModelBuilder.kt:137) |  
  |   | at org.gradle.kotlin.dsl.tooling.builders.KotlinDslScriptsModelBuilder.buildAll(KotlinDslScriptsModelBuilder.kt:119) |  
  |   | at org.gradle.kotlin.dsl.tooling.builders.KotlinDslScriptsModelBuilder.buildAll(KotlinDslScriptsModelBuilder.kt:109)

```

**Comment by ljacomet** [comment] 2021-03-10 14:55
#15522 has been postponed to Gradle 8

**Comment by lestephane** [comment] 2021-03-29 13:30
Can somebody explain exacty what do do to remove this warning?

```
The configuration :xxx:detachedConfiguration1 was resolved without accessing the project in a safe manner.
This may happen when a configuration is resolved from a different project. This behaviour has been deprecated
and is scheduled to be removed in Gradle 7.0.
See
https://docs.gradle.org/6.8.3/userguide/viewing_debugging_dependencies.html#sub:resolving-unsafe-configuration-resolution-errors for more details.
```

I'm being told by the warning that I need to change something because I'm doing something wrong. I want to oblige,
but the link that it points to does not give more details, and rather raises more questions:

```
If your build has an unsafe access deprecation warning, it needs to be fixed. It’s a symptom of these bad practices
and can cause strange and indeterminate errors.

In most cases, this issue can be resolved by creating a cross-project dependency on the other project.
```

I have a 'standard' java-conventions plugin that was created by gradle init, and every other submodule uses it as a plugin.

I did make some changes to the java-conventions plugin, but it's mainly setting compiler options, nothing fancy.

When I run gradlew build from the CLI, no warnings. I get the warnings when refreshing in IDEA.

**Comment by oehme** [comment] 2021-03-29 13:32
There's nothing you can do, the problem is in Gradle/IDEA integration.

**Comment by lestephane** [comment] 2021-03-30 07:57
@oehme I see, thanks for the clarification.

**Comment by eskatos** [comment] 2023-06-01 14:48
Relates to
* https://github.com/gradle/gradle/issues/15522
* https://github.com/gradle/gradle/issues/21492

**Comment by eskatos** [comment] 2023-07-05 15:01
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/21492

Please add your use case and 👍 to that issue.

**Closed by eskatos** 2023-07-05 15:01 UTC
Labels: a:bug, in:kotlin-dsl
