### ISSUE TITLE
137 exit code randomly when JUnit tests are run

### ISSUE THREAD

**Issue by vldF** [gradle/gradle#21259] opened 2022-07-14 17:07 UTC
### Expected Behavior
Tests pass successfully 

### Current Behavior
I got the next error:
```
2022-07-14T19:49:12.684+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
2022-07-14T19:49:12.684+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':test'.
2022-07-14T19:49:12.684+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:147)
2022-07-14T19:49:12.684+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
2022-07-14T19:49:12.684+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:145)
2022-07-14T19:49:12.684+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:133)
2022-07-14T19:49:12.684+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
2022-07-14T19:49:12.684+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
2022-07-14T19:49:12.684+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
2022-07-14T19:49:12.684+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
2022-07-14T19:49:12.684+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
2022-07-14T19:49:12.684+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
2022-07-14T19:49:12.684+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
2022-07-14T19:49:12.684+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
2022-07-14T19:49:12.684+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
2022-07-14T19:49:12.684+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
2022-07-14T19:49:12.685+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
2022-07-14T19:49:12.685+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
2022-07-14T19:49:12.685+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
2022-07-14T19:49:12.685+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
2022-07-14T19:49:12.685+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
2022-07-14T19:49:12.685+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
2022-07-14T19:49:12.685+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
2022-07-14T19:49:12.685+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
2022-07-14T19:49:12.685+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)
2022-07-14T19:49:12.685+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:333)
2022-07-14T19:49:12.685+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:320)
2022-07-14T19:49:12.685+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:313)
2022-07-14T19:49:12.685+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:299)
2022-07-14T19:49:12.685+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:143)
2022-07-14T19:49:12.685+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:227)
2022-07-14T19:49:12.685+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:218)
2022-07-14T19:49:12.685+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:140)
2022-07-14T19:49:12.685+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
2022-07-14T19:49:12.685+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
2022-07-14T19:49:12.685+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 1' finished with non-zero exit value 139
2022-07-14T19:49:12.685+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] This problem might be caused by incorrect test process configuration.
2022-07-14T19:49:12.685+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Please refer to the test execution section in the User Manual at https://docs.gradle.org/7.4.2/userguide/java_testing.html#sec:test_execution
2022-07-14T19:49:12.685+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.testing.worker.ForkingTestClassProcessor.stop(ForkingTestClassProcessor.java:186)
2022-07-14T19:49:12.686+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.testing.processors.RestartEveryNTestClassProcessor.endBatch(RestartEveryNTestClassProcessor.java:77)
2022-07-14T19:49:12.686+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.testing.processors.RestartEveryNTestClassProcessor.stop(RestartEveryNTestClassProcessor.java:62)
2022-07-14T19:49:12.686+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-07-14T19:49:12.686+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-07-14T19:49:12.686+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-07-14T19:49:12.686+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
2022-07-14T19:49:12.686+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
2022-07-14T19:49:12.686+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:30)
2022-07-14T19:49:12.686+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:87)
2022-07-14T19:49:12.686+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:36)
2022-07-14T19:49:12.686+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:71)
2022-07-14T19:49:12.686+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.InterruptibleRunnable.run(InterruptibleRunnable.java:42)
2022-07-14T19:49:12.686+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
2022-07-14T19:49:12.686+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
2022-07-14T19:49:12.686+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
```

### Context
I run tests on my CI and randomly (about 2 times in 5 runs) get this error. Also, tests are UI tests for IntelliJ Idea. So, I run an IDE with task `:runIdeForUiTests`, wait some time (5 mins) and run `./gradlew test --debug --stacktrace --no-parallel --tests 'my.tests'`. I tried to disable parallel running (with `--no-parallel`) and increase gradle's heap size (with `org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8`). Also, previously I used older gradle version (6.*) and update it now. Non one variant didn't make any impact. 

My CI isn't connect to Internet, only to internal company's network. So, can I get scan without internet connection? 

### Your Environment
Gradle 7.4.2
Dependencies:
```
    implementation("commons-io:commons-io:2.8.0")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.0.0-RC2")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-protobuf:1.0.0-RC2")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.0")
    implementation("org.msgpack:jackson-dataformat-msgpack:0.8.15")
    implementation("io.ktor:ktor-client-core:1.6.0")
    implementation("io.ktor:ktor-network:1.4.2")
    implementation("io.ktor:ktor-client-cio:1.4.2")
    implementation("com.github.oshi:oshi-core:5.8.2")
    testImplementation("org.mockito.kotlin:mockito-kotlin:4.0.0")
    testImplementation("org.mockito:mockito-inline:4.0.0")
    testImplementation("org.powermock:powermock-core:2.0.9")
    testImplementation("org.powermock:powermock-module-junit4:2.0.9")
    testImplementation("junit:junit:4.13")
    testImplementation("pl.pragmatists:JUnitParams:1.1.1")
    testImplementation("com.intellij.remoterobot:remote-robot:0.11.14")
    testImplementation("com.intellij.remoterobot:remote-fixtures:0.11.14")
    implementation("io.ktor:ktor-client-serialization:1.4.2")
    implementation("io.ktor:ktor-client-serialization-jvm:1.4.2")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.3")
```
Kotlin version 1.6.0
JVM version java-13-openjdk-amd64

**Comment by donat** [comment] 2022-07-20 08:40
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

This issue will be closed after 7 days, unless you can provide more information.



---

This might be a problem with your CI setup. The CI machines usually have some safeguard to kill processes before running out of system memory. The exit code indicates that the test worker process was killed abruptly from an external source.

**Comment by donat** [comment] 2022-07-20 08:42
You can find the documentation for configuring memory settings for test workers here:
https://docs.gradle.org/current/userguide/build_environment.html#sec:configuring_jvm_memory

**Comment by vldF** [comment] 2022-07-20 09:14
Yep, I knew it. Also, today I found one of potential reason: I' using [this](https://automation-remarks.com/video-recorder-java/) library to record my tests. I have disabled this library and my tests doesn't fall now

**Comment by donat** [comment] 2022-08-24 17:54
So IIUC the problem was with the third-party library. I'm closing the issues as "not Gradle", but let me know if we should continue investigating.

**Closed by donat** 2022-08-24 17:54 UTC
Labels: in:testing, to-triage
