### ISSUE TITLE
idea task not compatible with Configuration Caching

### ISSUE THREAD

**Issue by vicky17d** [gradle/gradle#24681] opened 2023-04-07 06:41 UTC
`idea` task to create project files for IntelliJ IDEA fails with configuration caching on in Gradle

### Expected Behavior
Task should be successful

### Current Behavior
```
27 problems were found storing the configuration cache, 8 of which seem unique.
- Task `:ideaModule` of type `org.gradle.plugins.ide.idea.GenerateIdeaModule`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
```

### Context
We still use old style IntelliJ project files and hence need to run the idea task. A large number of projects are impacted by it.

### Steps to Reproduce 
Take any project using with idea plugin on Gradle 7, enable configuration cache and run idea task

**Comment by jbartok** [comment] 2023-04-07 09:14
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #13480

**Closed by jbartok** 2023-04-07 09:14 UTC
Labels: a:bug, to-triage
