### ISSUE TITLE
Build-wide command-line options

### ISSUE THREAD

**Issue by rjbell4** [gradle/gradle#5572] opened 2018-05-29 20:06 UTC
This is not a bug report, but rather a feature request (is this a good place for that?)

I would like to be able to control command-line options that impact the entire execution, rather than are just specific to a particular task.

The `@Option` decoration has the ability to provide a custom command-line option for a task. The downside of this functionality is that is requires a specific task to be named (it does not work with just an unmentioned default task), and the scope of what’s been declared applies to just the specific task.

What I’d really like is for the ability to provide a command-line option that would allow me to set a property across multiple tasks, or even multiple projects. For example, the ability to control the build flavor (e.g., “debug” or “release”), which could impact the compilation of many things, not just a singular task.

I can control this as a project property (e.g, `-Pflavor=debug`), but I really like the functionality provided by `@Option`, such as making it an `enum`, and the documentation and validation that is baked in when I use it.

I suppose I could potentially make it a task-specific `@Option`, and then do something like `gradle.ext.flavor = flavor` in the setter for the option, but that seems a little hack-ish. It also still doesn’t work without explicitly specifying the task first, and I’d really love it if a user could just run `./gradlew --flavor=release`.

--

This was first reported [in the Gradle Forums](https://discuss.gradle.org/t/command-line-option-for-build-wide-properties/27000), where a few users have liked it (@gerhard6), so I must not be alone in this desire.

**Comment by oehme** [comment] 2018-05-30 10:04
Duplicate of https://github.com/gradle/gradle/issues/2885

**Closed by oehme** 2018-05-30 10:04 UTC
