### ISSUE TITLE
System.console() is null from Gradle 8.1 even with --no-daemon

### ISSUE THREAD

**Issue by andrewparmet** [gradle/gradle#25445] opened 2023-06-20 19:03 UTC
### Expected Behavior

`System.console()` should not be null.

### Current Behavior

System.console() is null.

### Context (optional)

Started happening in Gradle 8.1 and is still happening in 8.2-rc2.

### Steps to Reproduce

Call System.console() in a Gradle project.

### Gradle version

8.2-rc2

### Gradle version that used to work

8.0.2

**Comment by ljacomet** [comment] 2023-06-21 12:08
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

**Comment by eskatos** [comment] 2023-06-23 08:23
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/1251

Please add your use case and 👍 to that issue.


----

`--no-daemon` means no long-lived daemon but not necessarily no forked process as the following message from your output shows:

```
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/8.0.1/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build
```

**Closed by eskatos** 2023-06-23 08:23 UTC
Labels: in:daemon, closed:duplicate
