### ISSUE TITLE
Unverifyable statements regarding configuration cache inputs

### ISSUE THREAD

**Issue by TheGoesen** [gradle/gradle#31466] opened 2024-11-30 15:24 UTC
### Issue type

Wrong or misleading information

### Problem description

I think the documentation describes a feature which is currently impossible due to some bugs/limitations.

```
Build configuration inputs include:

- Gradle properties used during the configuration phase
```

So gradle properties are often set in your gradle.properties. However any change to a gradle.properties in the project root or user home will always invalidate the configuration-cache, it does not matter if its used during the configuration phase or not. (even adding a blank line will invalidate the configuration cache)
An alternative could be to set gradle properties using the commandline or  maybe using a module gradle.properties..
However properties that are set in such way can not be seen using `project.properties` or `providers.gradleProperty() `, so they cant be used during the configuration phase.

so there isnt really a way to validate this statement from an enduser perspective, I think?

### Page with the problem

https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:intro:how_does_it_work

**Comment by TheGoesen** [comment] 2024-11-30 15:49
https://github.com/gradle/gradle/issues/23572

**Comment by ljacomet** [comment] 2024-12-02 09:55
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by mlopatkin** [comment] 2024-12-03 12:18
This issue will be closed as a duplicate of

* #20969

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

Technically, the documentation isn't wrong, it just doesn't mention that all other property sources are inputs. We plan to add fine-grained tracking of used properties in the future, and the issue is linked from "Not yet implemented" section of the CC docs.

**Closed by mlopatkin** 2024-12-03 12:18 UTC
Labels: in:configuration-cache, a:documentation, :wave: team-triage, in:build-environment, re:comprehensibility
