### ISSUE TITLE
work offline

### ISSUE THREAD

**Issue by LinWanCen** [gradle/gradle#19958] opened 2022-02-18 01:30 UTC
It is hoped that each version can be tested offline for availability. 

for example,

In an environment without Internet, 
kotlin-dsl Searched in Gradle Central Plugin Repositiories in the build.gradle.kts file of buildSrc,

`gradle init` converts the maven project using https://repo.maven.apache.org and init.d/init.gradle is not effective.

**Comment by ljacomet** [comment] 2022-02-18 09:30
Duplicate of #19884

**Closed by ljacomet** 2022-02-18 09:30 UTC
Labels: in:build-init-plugin, a:regression, closed:duplicate
