### ISSUE TITLE
Support JDK 17

### ISSUE THREAD

**Issue by mmoayyed** [gradle/gradle#16857] opened 2021-04-15 18:06 UTC
### Expected Behavior

Gradle should be able to build using JDK 17.

### Current Behavior

Expectedly so, Gradle 7 reports:

```
> Could not open proj generic class cache for build file '/home/runner/work/cas/cas/build.gradle' (/home/runner/.gradle/caches/7.0/scripts/7svr5eftu6yyc0wrrcr0ex12d).
   > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 61
```

### Context

[Apereo CAS](https://github.com/apereo/cas) is part of the Oracle JDK Compatibility program, and we are trying to help the JDK ecosystem by trying out latest versions of JDK to report feedback, issues, etc. This is no blocker at all and we can continue with JDK 16 builds. I did not see a relevant issue to track support for JDK 17, so thought to open one here.

**Comment by ljacomet** [comment] 2021-04-21 09:50
Release schedule for JDK 17: https://openjdk.java.net/projects/jdk/17/

**Comment by mbcoder** [comment] 2021-05-12 17:26
This would be a good issue to address fairly soon as Java 17EA (with JEP391) is the only easy way to currently start to work on M1 based macOS platforms.  A temporary workaround is to use a maven build script, but Gradle would be preferred.

**Comment by KengoTODA** [comment] 2021-06-01 03:55
In my understanding, we need a Groovy version depending on [ObjectWeb ASM version 9.1](https://asm.ow2.io/versions.html#9.1) supporting Java 17. 

And Groovy 3.0.8 [depends on this release](https://github.com/apache/groovy/commit/d27994ea1f516894423980c958b65c8c02fb9395).
So I think Gradle needs to bump up Groovy from 3.0.7 to 3.0.8.

At this moment, both Gradle 7.0.2 and 7.1-rc-1 depend on Groovy 3.0.7.

**Comment by KengoTODA** [comment] 2021-06-01 04:15
> c541589 introduced Groovy 3.0.8, so I assume next release (7.1-rc-2?) will support enhance the support for Java 17.

I tried the latest nightly build version 7.2-20210531220051+0000, and it [failed to build with JDK 17-ea](https://github.com/spotbugs/spotbugs/runs/2715138682#step:7:42) because it still depends on Groovy 3.0.7.

**Comment by Siedlerchr** [comment] 2021-06-30 18:26
Unfortunately, still groovy 3.0.7 in Gradle 7.2-20210629235357+0000  :(

**Comment by dreis2211** [comment] 2021-07-09 17:59
Apart from the Groovy update, there is one additional thing that's not working on JDK 17.

The following is failing:
```
Project project = ProjectBuilder.builder().withProjectDir(projectDir).build();
```
The stacktrace is as follows:
```
org.gradle.api.GradleException: Could not inject synthetic classes.
	at org.gradle.initialization.DefaultLegacyTypesSupport.injectEmptyInterfacesIntoClassLoader(DefaultLegacyTypesSupport.java:91)
	at org.gradle.testfixtures.internal.ProjectBuilderImpl.getGlobalServices(ProjectBuilderImpl.java:183)
	at org.gradle.testfixtures.internal.ProjectBuilderImpl.createProject(ProjectBuilderImpl.java:111)
	at org.gradle.testfixtures.ProjectBuilder.build(ProjectBuilder.java:120)
...
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessException: module java.base does not open java.lang to unnamed module @5d11afe5
	at org.gradle.internal.classloader.ClassLoaderUtils$AbstractClassLoaderLookuper.invoke(ClassLoaderUtils.java:150)
	at org.gradle.internal.classloader.ClassLoaderUtils$LookupClassDefiner.defineClass(ClassLoaderUtils.java:206)
	at org.gradle.internal.classloader.ClassLoaderUtils.define(ClassLoaderUtils.java:77)
	at org.gradle.initialization.DefaultLegacyTypesSupport.injectEmptyInterfacesIntoClassLoader(DefaultLegacyTypesSupport.java:88)
	... 98 more
Caused by: java.lang.IllegalAccessException: module java.base does not open java.lang to unnamed module @5d11afe5
	at java.base/java.lang.invoke.MethodHandles.privateLookupIn(MethodHandles.java:259)
	at org.gradle.internal.classloader.ClassLoaderUtils$AbstractClassLoaderLookuper.getLookupForClassLoader(ClassLoaderUtils.java:159)
	at org.gradle.internal.classloader.ClassLoaderUtils$AbstractClassLoaderLookuper.invoke(ClassLoaderUtils.java:146)
	... 101 more
```

I can hack around this, but I'm accessing Gradle internals here which is not really cool.
```
File userHome = new File(projectDir, "userHome");
ProjectBuilder builder = ProjectBuilder.builder().withProjectDir(projectDir).withGradleUserHomeDir(userHome);
NativeServices.initialize(userHome);
try {
	ProjectBuilderImpl.getGlobalServices();
} catch (Throwable ignore) {
	// Fails on JDK 17
}
Project project = builder.build();
```

**Comment by Siedlerchr** [comment] 2021-07-16 18:24
The latest nightly compiles: https://github.com/JabRef/jabref/pull/7862
` ./gradlew wrapper --gradle-version=7.2-20210715231856+0000 `

**Comment by kevinrushforth** [comment] 2021-07-16 20:56
I was able to build [openjdk/jfx](https://github.com/openjdk/jfx) with the latest nightly build of gradle `7.2-20210715231856+0000` and the latest JDK 17 ea build, `17-ea+31-2664`.

**Comment by yschimke** [comment] 2021-07-17 11:54
I'm getting a kapt failure https://github.com/square/okhttp/pull/6697/checks?check_run_id=3092889438

```
Execution failed for task ':samples:guide:kaptKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)
```

Getting a stacktrace now.

**Comment by rieske** [comment] 2021-07-19 12:35
This will be related as well: https://youtrack.jetbrains.com/issue/KT-47152

**Comment by rieske** [comment] 2021-07-28 09:55
This is also related (Kapt does not work on Java 17): https://youtrack.jetbrains.com/issue/KT-47583
This prevents Gradle's Android plugin smoke tests from running on Java 17.

**Comment by dreis2211** [comment] 2021-07-30 09:24
@rieske Do you have any possible solution for the ProjectBuilder problem already?

**Comment by danielsun1106** [comment] 2021-08-07 15:48
FYI. The upcoming groovy 4.0.0 beta-1 will support Java16+(including Java17). All tests are green now:
https://app.travis-ci.com/github/apache/groovy/builds/234763056

**Comment by ice1000** [comment] 2021-08-12 05:01
> The latest nightly compiles: [JabRef/jabref#7862](https://github.com/JabRef/jabref/pull/7862)
> `./gradlew wrapper --gradle-version=7.2-20210715231856+0000`

Does that mean gradle 7.2 will support Java 17?

**Comment by ice1000** [comment] 2021-08-15 16:54
Is there an RC version of gradle that will support Java 17?

**Comment by KengoTODA** [comment] 2021-08-18 08:37
Gradle 7.2 depends on Groovy 3.0.8, and it solved my problem caused by old ObjectWeb ASM version.

```
------------------------------------------------------------
Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
```

**Comment by iNikem** [comment] 2021-09-14 16:39
JDK 17 was released today. Any plans for Gradle to support it?

**Comment by flenzi** [comment] 2021-09-14 17:17
@iNikem have you tried with Gradle 7.2 ?

**Comment by ryanmkurtz** [comment] 2021-09-14 18:33
7.2 give the error:
```
Unsupported class file major version 61
```

**Comment by iNikem** [comment] 2021-09-14 20:20
> @iNikem have you tried with Gradle 7.2 ?

First quick run was successful. But still would like to see an official support claim.

**Comment by flenzi** [comment] 2021-09-14 21:26
> > @iNikem have you tried with Gradle 7.2 ?
> 
> First quick run was successful. But still would like to see an official support claim.

Yes sure but it's working....

**Comment by ice1000** [comment] 2021-09-14 23:31
Worked for me

**Comment by surajtambe** [comment] 2021-09-15 05:39
Working for me as well 

```
Jdk17
Gradle 7.2
```

**Comment by asarkar** [comment] 2021-09-15 07:36
“Working for me” doesn’t necessarily mean officially certified, or that it’ll work for any other project until the Gradle team comes through.

**Comment by ljacomet** [comment] 2021-09-15 09:04
Gradle is looking to support JDK 17 in Gradle 7.3, to be released later in September - early October (dates may vary, software, etc...)

However support might not be 100% because the underlying Kotlin version does not support Java 17 100%, so there will be gaps until Gradle can embed a Kotlin version that is fully JDK 17 compatible.
Details will be in the release notes of Gradle 7.3.

**Comment by pditommaso** [comment] 2021-09-16 05:36
No joy here, using Gradle 7.2 buildSrc compilation fails 

```
> Task :buildSrc:compileGroovy
startup failed:
General error during instruction selection: PermittedSubclasses requires ASM9

java.lang.UnsupportedOperationException: PermittedSubclasses requires ASM9
        at groovyjarjarasm.asm.ClassVisitor.visitPermittedSubclass(ClassVisitor.java:266)
        at groovyjarjarasm.asm.ClassReader.accept(ClassReader.java:683)
        at groovyjarjarasm.asm.ClassReader.accept(ClassReader.java:401)
        at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
        at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:251)
        at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:189)
        at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:169)
        at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:125)
        at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveClassNullable(AsmReferenceResolver.java:57)
        at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveClass(AsmReferenceResolver.java:44)
        at org.codehaus.groovy.ast.decompiled.TypeSignatureParser.visitEnd(TypeSignatureParser.java:110)
        at groovyjarjarasm.asm.signature.SignatureReader.parseType(SignatureReader.java:206)
        at groovyjarjarasm.asm.signature.SignatureReader.parseType(SignatureReader.java:235)
        at groovyjarjarasm.asm.signature.SignatureReader.accept(SignatureReader.java:114)
        at org.codehaus.groovy.ast.decompiled.MemberSignatureParser.createMethodNode(MemberSignatureParser.java:97)
        at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.lambda$createMethodNode$1(DecompiledClassNode.java:230)
        at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.createMethodNode(DecompiledClassNode.java:236)
        at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.lazyInitMembers(DecompiledClassNode.java:203)
        at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.getDeclaredMethods(DecompiledClassNode.java:122)
        at org.codehaus.groovy.ast.ClassNode.getGetterMethod(ClassNode.java:1123)
        at org.codehaus.groovy.ast.ClassNode.getGetterMethod(ClassNode.java:1117)
        at org.codehaus.groovy.classgen.asm.sc.StaticTypesCallSiteWriter.makeGetPropertyWithGetter(StaticTypesCallSiteWriter.java:444)
        at org.codehaus.groovy.classgen.asm.sc.StaticTypesCallSiteWriter.makeGetPropertyWithGetter(StaticTypesCallSiteWriter.java:492)
        at org.codehaus.groovy.classgen.asm.sc.StaticTypesCallSiteWriter.makeGetPropertyWithGetter(StaticTypesCallSiteWriter.java:499)
        at org.codehaus.groovy.classgen.asm.sc.StaticTypesCallSiteWriter.makeGetPropertySite(StaticTypesCallSiteWriter.java:166)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitAttributeOrProperty(AsmClassGenerator.java:986)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitPropertyExpression(AsmClassGenerator.java:1134)
        at org.codehaus.groovy.ast.expr.PropertyExpression.visit(PropertyExpression.java:63)
        at org.codehaus.groovy.classgen.asm.sc.StaticInvocationWriter.visitArgument(StaticInvocationWriter.java:514)
        at org.codehaus.groovy.classgen.asm.sc.StaticInvocationWriter.loadArguments(StaticInvocationWriter.java:461)
        at org.codehaus.groovy.classgen.asm.InvocationWriter.writeDirectMethodCall(InvocationWriter.java:208)
        at org.codehaus.groovy.classgen.asm.sc.StaticInvocationWriter.writeDirectMethodCall(StaticInvocationWriter.java:387)
        at org.codehaus.groovy.classgen.asm.InvocationWriter.makeDirectCall(InvocationWriter.java:299)
        at org.codehaus.groovy.classgen.asm.sc.StaticInvocationWriter.makeDirectCall(StaticInvocationWriter.java:133)
        at org.codehaus.groovy.classgen.asm.InvocationWriter.makeCall(InvocationWriter.java:381)
        at org.codehaus.groovy.classgen.asm.InvocationWriter.makeCall(InvocationWriter.java:121)
        at org.codehaus.groovy.classgen.asm.sc.StaticInvocationWriter.makeCall(StaticInvocationWriter.java:649)
        at org.codehaus.groovy.classgen.asm.InvocationWriter.writeInvokeMethod(InvocationWriter.java:456)
        at org.codehaus.groovy.classgen.asm.sc.StaticInvocationWriter.writeInvokeMethod(StaticInvocationWriter.java:140)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitMethodCallExpression(AsmClassGenerator.java:844)
        at org.codehaus.groovy.ast.expr.MethodCallExpression.visit(MethodCallExpression.java:76)
        at org.codehaus.groovy.classgen.asm.StatementWriter.writeExpressionStatement(StatementWriter.java:635)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitExpressionStatement(AsmClassGenerator.java:686)
        at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:40)
        at org.codehaus.groovy.classgen.asm.StatementWriter.writeIfElse(StatementWriter.java:323)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitIfElse(AsmClassGenerator.java:637)
        at org.codehaus.groovy.ast.stmt.IfStatement.visit(IfStatement.java:41)
        at org.codehaus.groovy.classgen.asm.StatementWriter.writeBlockStatement(StatementWriter.java:94)
        at org.codehaus.groovy.classgen.asm.sc.StaticTypesStatementWriter.writeBlockStatement(StaticTypesStatementWriter.java:78)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitBlockStatement(AsmClassGenerator.java:617)
        at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:69)
        at org.codehaus.groovy.classgen.asm.StatementWriter.writeIfElse(StatementWriter.java:333)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitIfElse(AsmClassGenerator.java:637)
        at org.codehaus.groovy.ast.stmt.IfStatement.visit(IfStatement.java:41)
        at org.codehaus.groovy.classgen.asm.StatementWriter.writeBlockStatement(StatementWriter.java:94)
        at org.codehaus.groovy.classgen.asm.sc.StaticTypesStatementWriter.writeBlockStatement(StaticTypesStatementWriter.java:78)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitBlockStatement(AsmClassGenerator.java:617)
        at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:69)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClassCodeContainer(ClassCodeVisitorSupport.java:138)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructorOrMethod(ClassCodeVisitorSupport.java:111)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitStdMethod(AsmClassGenerator.java:461)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitConstructorOrMethod(AsmClassGenerator.java:408)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitMethod(ClassCodeVisitorSupport.java:106)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitMethod(AsmClassGenerator.java:556)
        at org.codehaus.groovy.ast.ClassNode.visitMethods(ClassNode.java:1099)
        at org.codehaus.groovy.ast.ClassNode.visitContents(ClassNode.java:1092)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClass(ClassCodeVisitorSupport.java:52)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitClass(AsmClassGenerator.java:271)
        at org.codehaus.groovy.control.CompilationUnit$3.call(CompilationUnit.java:797)
        at org.codehaus.groovy.control.CompilationUnit$IPrimaryClassNodeOperation.doPhaseOperation(CompilationUnit.java:942)
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:671)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:635)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:610)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:262)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:64)
        at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:97)
        at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:76)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkAction.execute(AbstractDaemonCompiler.java:135)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
        at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:43)
        at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:49)
        at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:30)
        at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:85)
        at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:55)
        at org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:138)
        at org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:135)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
        at java.base/java.lang.Thread.run(Thread.java:833)

1 error
```

**Comment by ZacSweers** [comment] 2021-09-21 19:15
Separately - I notice that toolchains do not correctly recognize available JDK 17 distributions like Azul's zulu distro. Should I file a separate issue for that?

```
* What went wrong:
Execution failed for task ':moshi-sealed:java-sealed-reflect:compileJava'.
> Error while evaluating property 'javaCompiler' of task ':moshi-sealed:java-sealed-reflect:compileJava'
   > Failed to calculate the value of task ':moshi-sealed:java-sealed-reflect:compileJava' property 'javaCompiler'.
      > No compatible toolchains found for request filter: {languageVersion=17, vendor=AZUL, implementation=vendor-specific} (auto-detect true, auto-download true)

```

**Comment by ljacomet** [comment] 2021-09-22 07:25
@ZacSweers Yes, but could you please check if this is related to #18111

**Comment by Fempter** [comment] 2021-09-24 20:35
> Gradle is looking to support JDK 17 in Gradle 7.3, to be released later in September - early October (dates may vary, software, etc...)
> 
> However support might not be 100% because the underlying Kotlin version does not support Java 17 100%, so there will be gaps until Gradle can embed a Kotlin version that is fully JDK 17 compatible.
> Details will be in the release notes of Gradle 7.3.

Does your Gradle 7.3 snapshot version support Java 17?

**Comment by ljacomet** [comment] 2021-09-27 15:46
It should - see https://gradle.org/release-nightly/

**Closed** 2021-09-30 17:25 UTC
Labels: in:core, a:feature, in:jvm-ecosystem, @core

**Comment by big-guy** [comment] 2021-09-30 19:40
Gradle 7.3 will add support for running Gradle with Java 17, but you can also try running Gradle 7.2 with Java 17 by using Java toolchains:
```
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
```

**Comment by huehnerlady** [comment] 2021-10-04 07:18
@big-guy could you give an estimate when gradle 7.3 will be released?

**Comment by AshwaniPandey-calypso** [comment] 2021-10-04 20:24
@big-guy I tried providing toolchain option as mentioned in workaround above, but getting below error:
![image](https://user-images.githubusercontent.com/91870995/135919302-cfb07c31-b283-4fdc-b743-e0605196c291.png)
gradle version: 7.2
java version: 17
debug logs attached:
[debug.log](https://github.com/gradle/gradle/files/7281103/debug.log)

**Comment by mattwelke** [comment] 2021-10-09 18:07
I noticed this when I was trying to use IntelliJ IDEA to build my Gradle app. I had to set the Gradle JVM for 16 for it to work, even though my goal was to take my built JAR and run it in a JDK 17 runtime. That worked fine. Gradle was able to build the app with:

```gradle
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}
```

And I was able to run the JAR in a container where I built a runtime using jlink with a JDK 17 base image:

```Dockerfile
# Example of custom Java runtime using jlink in a multi-stage container build
FROM mcr.microsoft.com/openjdk/jdk:17-ubuntu as runtime-build

# Install binutils to enable --stri-debug for jlink
RUN apt-get update && apt-get install -y binutils

# Create a custom Java runtime
RUN $JAVA_HOME/bin/jlink \
         --add-modules java.base,java.logging \
         --strip-debug \
         --no-man-pages \
         --no-header-files \
         --compress=2 \
         --output /javaruntime

# Define your base image. You may use any base OS and version of your choice.
FROM debian:buster-slim
ENV JAVA_HOME /usr/lib/jvm/msopenjdk-17-amd64
ENV PATH "${JAVA_HOME}/bin:${PATH}"
COPY --from=runtime-build /javaruntime $JAVA_HOME

# Continue with your application deployment
RUN mkdir /opt/app
COPY app/build/libs/app-all.jar /opt/app/japp.jar
CMD ["java", "-jar", "/opt/app/japp.jar", "-XX:+UseZGC"]
```

Does that pattern make sense? Or is it normal to make sure the version of Java you use to invoke Gradle is exactly the same as the JVM that will run your app?

**Comment by massenz** [comment] 2021-10-10 01:51
Any updates as to when Gradle 7.3 will be released?
Currently build fails for me on 7.2 with `Unsupported Java` error.

thanks.

**Comment by mattwelke** [comment] 2021-10-10 04:07
@massenz I was able to use Gradle with Java 17 earlier today. I was using GitHub Actions with the setup-java action, configuring it to install Temurin version 17.

My workflow file is here: https://github.com/mattwelke/gcma/blob/alpha/.github/workflows/docker-publish.yml

I'm not sure if this makes a difference but I was setting the language level to 17 using the toolchains Gradle feature too, and a commenter above mentioned that doing that can also help if you want to run Gradle with Java 17:

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

Maybe this technique will help.

**Comment by pp-lucaal-sportsbet** [comment] 2021-10-13 03:54
How about on oracle jdk 17

**Comment by rpalcolea** [comment] 2021-10-14 16:26
I found the following Today: https://github.com/gradle/gradle/issues/18647

org.gradle.testfixtures.ProjectBuilder + Test Distribution are not compatible with JDK 17 and Gradle 7.3-rc.1

**Comment by DPUkyle** [comment] 2021-10-29 21:03
> Trying out 7.3 RC3 with Java 17.
> 
> Seems to be an issue with the included groovy plugin when using a Java class compiled with JDK17 in a groovy file. Failes to compile groovy code with an error:
> 

Thanks for reporting, @Romanow88. Can you provide any more details to reproduce the issue?

**Comment by DPUkyle** [comment] 2021-10-29 21:11
> Trying out 7.3 RC3 with Java 17.
> 
> Seems to be an issue with the included groovy plugin when using a Java class compiled with JDK17 in a groovy file. Failes to compile groovy code with an error:
> 
> ```
> startup failed:
> General error during conversion: Unsupported class file major version 61
> 
> java.lang.IllegalArgumentException: Unsupported class file major version 61
> 	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)
> 	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)
> 	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:163)
> 	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:284)
> 	at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
> 	at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:251)
> 	at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:189)
> 	at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:169)
> 	at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:125)
> 	at org.codehaus.groovy.control.ResolveVisitor.resolveToOuter(ResolveVisitor.java:853)
> 	at org.codehaus.groovy.control.ResolveVisitor.resolve(ResolveVisitor.java:467)
> 	at org.codehaus.groovy.control.ResolveVisitor.visitClass(ResolveVisitor.java:1418)
> 	at org.codehaus.groovy.control.ResolveVisitor.startResolving(ResolveVisitor.java:230)
> 	at org.codehaus.groovy.tools.javac.JavaAwareCompilationUnit$1.call(JavaAwareCompilationUnit.java:74)
> 	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1084)
> 	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:640)
> 	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:618)
> 	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:595)
> 	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:574)
> 	at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:265)
> 	at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:64)
> 	at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:97)
> 	at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:76)
> 	at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkAction.execute(AbstractDaemonCompiler.java:135)
> 	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
> 	at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
> 	at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
> 	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
> 	at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:43)
> 	at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:49)
> 	at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:30)
> 	at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:85)
> 	at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:55)
> 	at org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:138)
> 	at org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
> 	at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:135)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
> 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
> 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
> 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
> 	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
> 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
> 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
> ```

 @Romanow88 is the above report a non-issue?

**Comment by Romanow88** [comment] 2021-10-29 21:20
@DPUkyle correct, we had some code that pinned groovy at a specific version lover than 3.0.8. Apparently that determines what compiler is being used (and not the version bundled in gradle). I had the false assumption that the versions were independent (like the koltin plugin and kotlin std-lib). 

After the update to 3.0.9 everything worked. Sorry for the false positive.

**Comment by DPUkyle** [comment] 2021-10-29 21:24
> Sorry for the false positive.

No worries and thanks for confirming!

**Comment by mozhuanzuojing** [comment] 2021-10-30 00:17
@Romanow88 

> can you test a task by JDK17 and groovy-3.0.9 and gradle-7.3-rc-3?

```gradle
import org.apache.groovy.json.internal.JsonParserLax

task testJSON(){
    group "json-test"
    doLast {
        def jsontext = """
            {
                "files.encoding": "utf8"
            }
        """
        def jpl = new JsonParserLax(true, false, false, true)
        def res = jpl.parse(jsontext)
        println(res)
    }
}
```

**Comment by Romanow88** [comment] 2021-10-30 01:48
@mozhuanzuojing could not import the JsonParserLax (compile fail) but worked with the usuall groovy.json.JsonSlurper

**Comment by sschuberth** [comment] 2022-01-13 10:31
Is there a way for Gradle < 7.3 to work with JDK 17 by somehow telling Gradle to target a lower bytecode level when compiling its Groovy build scripts?
