### ISSUE TITLE
NullPointerException without message just on start

### ISSUE THREAD

**Issue by kuFEAR** [gradle/gradle#16804] opened 2021-04-13 07:09 UTC
Hi, After updating on gradle 7.0, a build on CI become crashing on start. 
But it works fine on local machines with osx/linux/win configurations.

### Expected Behavior
Success finishing build

### Current Behavior
[npe_on_start.log](https://github.com/gradle/gradle/files/6301695/npe_on_start.log)

### Steps to Reproduce 
Simple update gradle from 6.8.3 to 7.0 on same configuration and project

### Your Environment
ci teamcity
docker, image based on openJdk 11
linux agents

gradle.properties:
org.gradle.jvmargs=-Xms2g -Xmx4g -Dfile.encoding=UTF8 -Dkotlin.daemon.jvm.options\="-Xmx1600M"
org.gradle.configureondemand=true
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.parallel=true

**Comment by big-guy** [comment] 2021-04-13 13:48
@kuFEAR do you have an init script on CI?

**Comment by kuFEAR** [comment] 2021-04-13 14:33
<img width="700" alt="Screenshot 2021-04-13 at 17 22 03" src="https://user-images.githubusercontent.com/4124981/114568495-d8140300-9c7c-11eb-9a5b-07a59d75e3fc.png">
yes it is, as we use teamcity gradle runner, it create some initScript, but if i switch to commandLine runner and start build as ./gradlew app:assemble, so it runs well

**Comment by kuFEAR** [comment] 2021-04-13 14:36
so looks our init script on teamcity:
[init.gradle.txt](https://github.com/gradle/gradle/files/6304495/init.gradle.txt)

**Comment by kuFEAR** [comment] 2021-04-13 14:53
when I switch on command line runner it become failed with error
```
* What went wrong:
[17:29:58]	org.gradle.api.InvalidUserDataException: Cannot generate project dependency accessors:
[17:29:58]	  - Cannot generate project dependency accessors because project '2b0df1bb2775dc3c' doesn't follow the naming convention: [a-zA-Z]([A-Za-z0-9\-_])*
[17:29:58]	> Cannot generate project dependency accessors:
[17:29:58]	    - Cannot generate project dependency accessors because project '2b0df1bb2775dc3c' doesn't follow the naming convention: [a-zA-Z]([A-Za-z0-9\-_])*
```
looks like root project name inherited from root folder name with vcs revision and can't be use new centralized dependencies feature with *.toml file

**Comment by ljacomet** [comment] 2021-04-19 09:30
Is there anything to handle here given that #16815 is the root cause?

If not, I would close this one and follow up on #16815.

**Comment by kuFEAR** [comment] 2021-04-19 10:25
Sure, as I see it is the root cause. can close

**Closed** 2021-04-19 10:25 UTC
Labels: a:bug, to-triage
