### ISSUE TITLE
Gradle 4.1 M1 break Android local aar import

### ISSUE THREAD

**Issue by mymbrooks** [gradle/gradle#2370] opened 2017-07-01 02:13 UTC
When I update Android Studio to 3.0 Canary 5, it use gradle 4.1 m1.
I use a local aar developed myself and I used it before:

    repositories {
        flatDir {
            dirs 'libs'
        }
    }

...

compile(name: 'ruibulibrary', ext: 'aar')

now the build task is failed:
Gradle sync failed: java.lang.AssertionError: ':ruibulibrary:@aar' is not a valid maven coordinate. (3s 91ms)

### Expected Behavior

before gradle 4.1 m1(3.x -- 4.x) worked fine

### Your Environment

 * Build scan URL: https://gradle.com/s/dhvmvse2timlo

Windows 10 Creators Update 15063 Enterprise x64
Android Studio 3.0 Canary 5 x64
gradle-4.1-milestone-1

**Comment by pepperonas** [comment] 2017-07-02 02:09
Same  here. iMac macOS Sierra (so this time not win-related)

**Comment by xorander00** [comment] 2017-07-02 06:24
I'm seeing this issue as well.

**Comment by sinistance** [comment] 2017-07-02 07:00
i'm getting the same issue and defining the full coordinate seems fixed the issue. 

i.e 
from
`debugCompile(name:'stetho_realm-release', ext:'aar')`
to
`debugCompile "com.uphyca:stetho_realm-release:2.0.1@aar"`

**Comment by pantos27** [comment] 2017-07-02 09:34
Here too,
This could also be the gradle android plugin (3.0.0-alpha5)

**Comment by ZinoKader** [comment] 2017-07-02 16:58
Same issue - defining full coordinate does not fix it for me. MacOS Sierra, latest gradle android plugin (3.0.0-alpha5).

**Comment by xorander00** [comment] 2017-07-02 16:59
Confirmed.  Does not work even with defining with the full coordinate.  I'm going to continue investigating.

**Comment by thalesbm** [comment] 2017-07-02 17:55
same problem here guys, I will try to investigate that

**Comment by duckinferno** [comment] 2017-07-02 21:11
Same here, sierra w/ android plugin 3.0.0-alpha 5.

**Comment by jtietema** [comment] 2017-07-03 01:42
Building from the command line still works for me, so I think this might actually be an Android Studio bug?

**Comment by jtietema** [comment] 2017-07-03 01:45
AS bug is here: https://issuetracker.google.com/issues/63232245

**Comment by FioneraGH** [comment] 2017-07-03 01:48
same here, its a AS bug, see it here [Known Issues](https://developer.android.com/studio/build/gradle-plugin-3-0-0.html)

**Comment by pantos27** [comment] 2017-07-03 09:06
What works in the meantime is to add the aar file as a module in the same project and referring to it like so:
`    compile project(':library_module')`

**Comment by Defuera** [comment] 2017-07-03 20:58
@pantos27 worked for me, thank you!

**Comment by FioneraGH** [comment] 2017-07-04 04:25
@pantos27 worked, thanks. Have you ever met  .so files in aar are not built into apk file.

**Comment by mymbrooks** [comment] 2017-07-05 06:30
I tried more solution and i found it's not gradle's bug. On on Android Studio Canary 5  : )

I found another way to import my aar library:
1、File -- New -- New Module -- Import .JAR/.AAR Package
2、remove this from app/build.gradle
repositories {
        flatDir {
            dirs 'libs'
        }
    }

...

compile(name: 'ruibulibrary', ext: 'aar')

3、add this to app/build.gradle
compile project(":ruibulibrary")

finally gradle works fine.

**Comment by bmuschko** [comment] 2017-07-05 20:27
> AS bug is here: https://issuetracker.google.com/issues/63232245

Thanks for opening the issue. It will need to be fixed in Android Studio. Closing the issue here.

**Closed by bmuschko** 2017-07-05 20:27 UTC
Labels: from:contributor

**Comment by luckcoolla** [comment] 2018-03-22 13:20
Guys, how do you import complex .aar which are depends on other ones and on other remote libraries?
