### ISSUE TITLE
Up-to-date check is slow in continues build for large project

### ISSUE THREAD

**Issue by lixiangconan** [gradle/gradle#6421] opened 2018-08-18 01:24 UTC
Up-to-date check is slow in continues build for large project

### Expected Behavior
Up-to-date check is fast in continues build

### Current Behavior
Up-to-date could take more than 1 seconds for a single task in continues build mode when the project is large.

### Context
I am working on a service built on Play and Gradle. A common pattern during my work is I start my service using runPlayBinary, hit an endpoint, modify a few lines of code, and hit the endpoint again. The continues build time is very important for my productivity. The project is pretty large, as it has more than 1000 external dependency jars, and a lot of tasks to execute during the build. 

One fact I have realized is that a lot of time is spent on the up-to-date check during continues build. For example, I did a simple experiment by modifying one line code, and the build spent 113 seconds on up-to-date check (271 tasks) and 71 seconds on task execution (169 tasks) according to build scan. Note that I run Gradle with 4 workers and the time is the sum of the times spent on each worker.

I did more investigations by myself (by printing out timestamps in Gradle code), and found that the time was mainly spent on setting up file watchers for the continues build. In specific, file watchers are set up by [SkipEmptySourceFilesTaskExecuter](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/SkipEmptySourceFilesTaskExecuter.java#L99), which mainly uses the logics in [WatchServiceRegistrar](https://github.com/gradle/gradle/blob/482e146fb715183811a8c14abf84e5a57af8049a/subprojects/core/src/main/java/org/gradle/internal/filewatch/jdk7/WatchServiceRegistrar.java#L91). While the the logic of WatchServiceRegistrar is pretty complicated, I found two important things. First, the whole watch method is protected by a lock, therefore using multiple workers won't speed up the process. Second, a lot of time is spent on one method, which is the [FileUtils.calculateRoots](https://github.com/gradle/gradle/blob/74cebee40393f8f76e762e2a1fa7daaa5f3dfb2c/subprojects/base-services/src/main/java/org/gradle/internal/FileUtils.java#L74) method. According to may profiling using YourKit on Gradle Daemon, this method uses 10% of the CPU time during a continues build.

### Steps to Reproduce
I don't have a sample project to reproduce the slowness of the up-to-date check. I have a test to demonstrate the slowness of the FileUtils.calculateRoots method:
```java
def "perfTest"() {
        int prefixLength = 200
        int fileCount = 1000
        int warmUpCount = 100
        int testCount = 1000

        // Prepare file names
        StringBuffer sb = new StringBuffer()
        prefixLength.times {
            sb.append('a')
        }
        String prefix = sb.toString()
        String[] fileNames = new String[fileCount]
        0.step fileCount, 1,{
            fileNames[it] = prefix + '/' + it + '/testFile.jar'
        }

        println "start warmup"
        0.step warmUpCount, 1, {
            toRoots(files(fileNames))
        }
        println "start test"
        long start = System.currentTimeMillis()
        0.step testCount, 1, {
            toRoots(files(fileNames))
            if (it % 100 == 0) {
                println "finish test " + it
            }
        }
        long end = System.currentTimeMillis()
        expect:
        println "average time in ms: " + (end - start)/(double)testCount
        true
}
```
When executed on my machine, the test shows that each execution of the FileUtils.calculateRoots method takes 150ms with the setup above. While the file naming pattern in the test may look weird, it is actually similar to the naming pattern of external jars in gradle cache which are the input files of compile tasks.

### Your Environment
I use a MacBook Pro (15-inch, 2017) with 3.1 GHz CPU and 16 GB memory. I did the tests on Gradle 4.9.

**Comment by lixiangconan** [comment] 2018-08-18 03:05
I don't know what is the best way to improve the performance. One simple way I can think about is to optimize the performance of FileUtils.calculateRoots without changing its behavior. I wrote my idea in a pull request gradle/gradle#6422.

**Comment by oehme** [comment] 2018-08-18 13:26
Duplicate of https://github.com/gradle/gradle/issues/5939

**Closed by oehme** 2018-08-18 13:26 UTC
