### ISSUE TITLE
Inconsistent up-to-date checks when using fileTree for task outputs

### ISSUE THREAD

**Issue by Loffe** [gradle/gradle#2180] opened 2017-05-30 06:38 UTC
### Expected Behavior
When declaring task outputs I'd expect to be able to use `fileTree()` with include/exclude patterns.

### Current Behavior
After removing an output file and running the first time, the up-to-date check is "false" and the task is executed, as expected. However, sometimes when running the task again, the up-to-date check still considers the task to be out of date.

### Steps to Reproduce
The following tasks have been used to reproduce the problem:
```
task myTask1 {
    group 'build'
    inputs.file file('input.txt')
    outputs.file file('output1.txt')
    doLast {
        new File('output1.txt').text = new File('input.txt').text
    }
}

task myTask2 {
    group 'build'
    inputs.file file('input.txt')
    outputs.files fileTree(dir: '/', include: 'output2.txt')
    doLast {
        new File('output2.txt').text = new File('input.txt').text
    }
}

task myTask3 {
    group 'build'
    inputs.file file('input.txt')
    def outputFiles = fileTree(dir: '/', include: 'output3.txt').files
    outputs.files outputFiles
    doLast {
        new File('output3.txt').text = new File('input.txt').text
    }
}
```

`myTask1` that uses `file()`

 to specify the output never experiences the problem.
`myTask2` experiences the problem ~5-10% of the time.
`myTask3` also experiences the problem ~5-10% of the time, but _only_ when using the gradle daemon.

Simple do this to reproduce:
```
rm output2.txt
./gradlew myTask2
./gradlew myTask2
````

### Environment
Windows 7
git-bash
gradle 3.5
JVM 1.8.0_40 (Oracle)

**Comment by Loffe** [comment] 2017-05-30 06:50
Attaching a small project with a script `test.sh` to run the task several times.
[gradletest-2180.tar.gz](https://github.com/gradle/gradle/files/1037448/gradletest-2180.tar.gz)

**Comment by wolfs** [comment] 2017-05-30 08:35
@Loffe Thank you for your bug report.
Could you describe your use case for using fileTrees as output files? Couldn't you just have each of the tasks generate the output into its own directory and then have one `Sync` task which would copy the outputs to the destination?

**Comment by Loffe** [comment] 2017-05-30 08:54
Sure! I'm trying to integrate with a legacy CMake project.

I have a gradle task `generateCmakeProject`, which executes the CMake generator and the output (a VisualStudio project) is generated into a separate directory `build/cmake_project`. However, this output directory will also contain for example log files. A change to a log file shouldn't make the `generateCmakeProject` out-of-date.

Unfortunately, I cannot `Sync` the directory to somewhere else, since many of the generated files contains absolute paths

**Comment by wolfs** [comment] 2017-05-30 10:18
Are you able to describe the exact file outputs to Gradle? Like adding some single output files and a few output directories which do not contain any log files? What does the generated project structure look like?

**Comment by Loffe** [comment] 2017-05-30 10:51
Unfortunately, the file output structure from CMake is quite messy: ~100 directories and ~700 files.
The log files end up quite deep in a nested structure, and many of the other files and directories must be included.
Our current `fileTree` excludes most files based on file extension and some whole directories.
Is is most likely _possible_ to list all outputs to gradle, but that would not be fun to maintain.

Is it supported to specify output files with `fileTree`?

**Comment by wolfs** [comment] 2017-05-30 11:39
@Loffe Regarding your example: It seems like you declare `/` as an output while putting the output file in the current working directory. Is this a problem in your example or of your real build?

**Comment by Loffe** [comment] 2017-05-30 11:43
The dir: '/' is only part of the example. However, it seems to expand in the current dir only, at least on Windows.
In the real build we use a subdirectory to the `projectDir`.

**Comment by Loffe** [comment] 2017-05-30 11:51
I changed `dir: '/'` to `dir: '.'` and it made no difference to the observed behavior

**Comment by wolfs** [comment] 2017-06-12 13:58
@Loffe This problem should be fixed in `master` and will be included in `4.1`. Could you try out with a nightly build which will be released tonight?

**Comment by Loffe** [comment] 2017-06-13 08:59
@wolfs Thanks, I will try to verify the bugfix soon-ish :)

**Comment by jordfras** [comment] 2017-06-20 10:41
I am a colleague of @Loffe and we actually reported this issue together. I tested this again using the nightly build, 4.2-20170619235828+0000 and I am happy to report that I was not able to reproduce the issue. I have done a few hundred builds with a similar shell script to the one attached to the original report.

Just to be sure I also tested with gradle 3.5 again and experienced the problem with similar frequency as originally reported.

Many thanks for looking into this!

**Comment by jordfras** [comment] 2017-06-20 10:51
Just to be clear, I tested this with our product gradle script where I switched back to using `fileTree` where we changed to several `file`s. This is where we originally experienced the problem and later tried to minimize the example as in the bug report.

We still use `fileTree` for the CMake case mentioned by @Loffe so it will be nice to get this fix into our build system.

**Closed** 2017-06-20 11:43 UTC
Labels: a:question, affects-version:2.13, from:contributor, in:incremental-build
