### ISSUE TITLE
Plugin without version specified doesn't apply via `plugin { alias(...) }`

### ISSUE THREAD

**Issue by unshare** [gradle/gradle#27203] opened 2023-11-29 15:43 UTC
### Current Behavior

If a plugin is brought by an included build (incl. `buildSrc`), there is no point to specify plugin version.
(There are other cases when plugin version is also not required or even not allowed. See additional considerations in #27200)
If such a plugin is listed in `libs.versions.toml`, one can't apply it via generated DSL accessor and `alias(...)` due to null or empty version.
 
`settings.gradle.kts`
```kotlin
pluginManagement {
  includeBuild("path/to/a/gradle/plugin/project")
}
```

`libs.versions.toml`
```toml
[plugins]
my-custom-plugin-from-an-included-build = { id = "org.example.gradle.plugin" }
```

`build.gradle.kts`
```kotlin
plugins {
  id("org.example.gradle.plugin") // works
  alias(libs.plugins.my.custom.plugin.from.an.included.build) // fails due to null or empty version
  id(libs.plugins.my.custom.plugin.from.an.included.build.get().pluginId) // works, but looks ugly
}
```

### Expected Behavior

`alias(...)` should not pass null or empty version

### Context (optional)

Possibly fixed in #27200 (it'll take me a while to verify).

### Steps to Reproduce

See "Current Behavior"

### Gradle version

8.5

**Comment by cobexer** [comment] 2023-11-30 13:29
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #17968

Please add your use case and 👍 to that issue.
***
Thank you for the linked PR, we are going to have a look at that later.
Please review the original issue discussion and update your PR if needed.

**Closed by cobexer** 2023-11-30 13:29 UTC
Labels: a:bug, to-triage
