### ISSUE TITLE
Build fails with NPE following 'Received a completed event for test with unknown id' error w/ JUnit Platform and TestNG

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#20670] opened 2022-05-05 02:21 UTC
I'm migrating a project to Java 17, and need to move to JUnit Platform due to Spock tests. After a success event for o one particular TestNG test, the build fails with:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':nccp-common:test'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:147)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:145)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:133)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:333)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:320)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:313)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:299)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:143)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:227)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:218)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:140)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
Caused by: java.lang.NullPointerException
        at org.gradle.api.internal.tasks.testing.results.StateTrackingTestResultProcessor.started(StateTrackingTestResultProcessor.java:45)
        at org.gradle.api.internal.tasks.testing.results.AttachParentTestResultProcessor.started(AttachParentTestResultProcessor.java:38)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:30)
        at org.gradle.internal.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:87)
        at org.gradle.internal.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:36)
        at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:71)
        at org.gradle.internal.concurrent.InterruptibleRunnable.run(InterruptibleRunnable.java:42)
        at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
```

This is preceded by an 
```
Received a completed event for test with unknown id '3.4'. Registered test ids: '[:nccp-common:test, 3.1]'
java.lang.IllegalArgumentException: Received a completed event for test with unknown id '3.4'. Registered test ids: '[:nccp-common:test, 3.1]'
        at org.gradle.api.internal.tasks.testing.results.StateTrackingTestResultProcessor.completed(StateTrackingTestResultProcessor.java:79)
        at org.gradle.api.internal.tasks.testing.results.AttachParentTestResultProcessor.completed(AttachParentTestResultProcessor.java:56)
        at sun.reflect.GeneratedMethodAccessor216.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:30)
        at org.gradle.internal.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:87)
        at org.gradle.internal.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:36)
        at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:71)
        at org.gradle.internal.concurrent.InterruptibleRunnable.run(InterruptibleRunnable.java:42)
        at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
```

### Context
It's blocking the Java 17 migration.

### Steps to Reproduce 
This test uses a `@Factory` annotation, and I bet that's related. We have other tests that are fine. I'll rewrite this test for now to avoid the bug. Reach out privately on Netflix Slack if you want the test source.

### Your Environment
Gradle 7.4.2

```
2022-05-05T12:09:43.618+1000 [DEBUG] [org.gradle.process.internal.ExecHandleRunner] waiting until streams are handled...
2022-05-05T12:09:44.419+1000 [DEBUG] [TestEventLogger]
2022-05-05T12:09:44.419+1000 [DEBUG] [TestEventLogger] Gradle Test Executor 3 STARTED
2022-05-05T12:09:44.893+1000 [DEBUG] [TestEventLogger]
2022-05-05T12:09:44.893+1000 [DEBUG] [TestEventLogger] ParameterizedNccpRequestTest STARTED
2022-05-05T12:09:44.894+1000 [DEBUG] [TestEventLogger]
2022-05-05T12:09:44.894+1000 [DEBUG] [TestEventLogger] ParameterizedNccpRequestTest > testNamespaceExtraction STARTED
2022-05-05T12:09:44.901+1000 [DEBUG] [TestEventLogger]
2022-05-05T12:09:44.901+1000 [DEBUG] [TestEventLogger] ParameterizedNccpRequestTest > testNamespaceExtraction PASSED
2022-05-05T12:09:44.901+1000 [DEBUG] [TestEventLogger]
2022-05-05T12:09:44.901+1000 [DEBUG] [TestEventLogger] ParameterizedNccpRequestTest PASSED
2022-05-05T12:09:44.902+1000 [ERROR] [org.gradle.internal.actor.internal.DefaultActorFactory$NonBlockingActor] Received a completed event for test with unknown id '3.4'. Registered test ids: '[:nccp-common:test, 3.1]'
java.lang.IllegalArgumentException: Received a completed event for test with unknown id '3.4'. Registered test ids: '[:nccp-common:test, 3.1]'
        at org.gradle.api.internal.tasks.testing.results.StateTrackingTestResultProcessor.completed(StateTrackingTestResultProcessor.java:79)
        at org.gradle.api.internal.tasks.testing.results.AttachParentTestResultProcessor.completed(AttachParentTestResultProcessor.java:56)
        at sun.reflect.GeneratedMethodAccessor216.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:30)
        at org.gradle.internal.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:87)
        at org.gradle.internal.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:36)
        at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:71)
        at org.gradle.internal.concurrent.InterruptibleRunnable.run(InterruptibleRunnable.java:42)
        at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
2022-05-05T12:09:44.908+1000 [DEBUG] [TestEventLogger]
2022-05-05T12:09:44.908+1000 [DEBUG] [TestEventLogger] Gradle Test Executor 3 STANDARD_ERROR
2022-05-05T12:09:44.908+1000 [DEBUG] [TestEventLogger]     May 05, 2022 12:09:44 PM org.junit.platform.launcher.core.CompositeTestExecutionListener lambda$notifyEach$19
2022-05-05T12:09:44.908+1000 [DEBUG] [TestEventLogger]     WARNING: TestExecutionListener [org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestExecutionListener] threw exception for method: executionFinished(TestIdentifier [uniqueId = [engine:testng]/[class:com.netflix.eds.server.nccprequests.ParameterizedNccpRequestTest], parentId = [engine:testng], displayName = 'ParameterizedNccpRequestTest', legacyReportingName = 'com.netflix.eds.server.nccprequests.ParameterizedNccpRequestTest', source = ClassSource [className = 'com.netflix.eds.server.nccprequests.ParameterizedNccpRequestTest', filePosition = null], tags = [], type = CONTAINER], TestExecutionResult [status = SUCCESSFUL, throwable = null])
2022-05-05T12:09:44.908+1000 [DEBUG] [TestEventLogger]     java.lang.AssertionError
2022-05-05T12:09:44.908+1000 [DEBUG] [TestEventLogger]          at org.gradle.api.internal.tasks.testing.processors.TestOutputRedirector.setOutputOwner(TestOutputRedirector.java:49)
2022-05-05T12:09:44.908+1000 [DEBUG] [TestEventLogger]          at org.gradle.api.internal.tasks.testing.processors.CaptureTestOutputTestResultProcessor.completed(CaptureTestOutputTestResultProcessor.java:80)
2022-05-05T12:09:44.908+1000 [DEBUG] [TestEventLogger]          at org.gradle.api.internal.tasks.testing.results.AttachParentTestResultProcessor.completed(AttachParentTestResultProcessor.java:56)
2022-05-05T12:09:44.908+1000 [DEBUG] [TestEventLogger]          at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-05-05T12:09:44.908+1000 [DEBUG] [TestEventLogger]          at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-05-05T12:09:44.908+1000 [DEBUG] [TestEventLogger]          at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-05-05T12:09:44.908+1000 [DEBUG] [TestEventLogger]          at java.lang.reflect.Method.invoke(Method.java:498)
2022-05-05T12:09:44.908+1000 [DEBUG] [TestEventLogger]          at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
2022-05-05T12:09:44.908+1000 [DEBUG] [TestEventLogger]          at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
2022-05-05T12:09:44.908+1000 [DEBUG] [TestEventLogger]          at org.gradle.internal.actor.internal.DefaultActorFactory$BlockingActor.dispatch(DefaultActorFactory.java:128)
2022-05-05T12:09:44.908+1000 [DEBUG] [TestEventLogger]          at org.gradle.internal.actor.internal.DefaultActorFactory$BlockingActor.dispatch(DefaultActorFactory.java:100)
2022-05-05T12:09:44.909+1000 [DEBUG] [TestEventLogger]          at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
2022-05-05T12:09:44.909+1000 [DEBUG] [TestEventLogger]          at com.sun.proxy.$Proxy3.completed(Unknown Source)
2022-05-05T12:09:44.909+1000 [DEBUG] [TestEventLogger]          at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestExecutionListener.executionFinished(JUnitPlatformTestExecutionListener.java:113)
2022-05-05T12:09:44.909+1000 [DEBUG] [TestEventLogger]          at org.junit.platform.launcher.core.CompositeTestExecutionListener.lambda$executionFinished$10(CompositeTestExecutionListener.java:69)
2022-05-05T12:09:44.909+1000 [DEBUG] [TestEventLogger]          at org.junit.platform.launcher.core.CompositeTestExecutionListener.lambda$notifyEach$19(CompositeTestExecutionListener.java:95)
2022-05-05T12:09:44.909+1000 [DEBUG] [TestEventLogger]          at java.util.ArrayList.forEach(ArrayList.java:1259)
2022-05-05T12:09:44.909+1000 [DEBUG] [TestEventLogger]          at org.junit.platform.launcher.core.CompositeTestExecutionListener.notifyEach(CompositeTestExecutionListener.java:93)
2022-05-05T12:09:44.909+1000 [DEBUG] [TestEventLogger]          at org.junit.platform.launcher.core.CompositeTestExecutionListener.executionFinished(CompositeTestExecutionListener.java:69)
2022-05-05T12:09:44.909+1000 [DEBUG] [TestEventLogger]          at org.junit.platform.launcher.core.ExecutionListenerAdapter.executionFinished(ExecutionListenerAdapter.java:56)
2022-05-05T12:09:44.909+1000 [DEBUG] [TestEventLogger]          at org.junit.platform.launcher.core.DelegatingEngineExecutionListener.executionFinished(DelegatingEngineExecutionListener.java:46)
2022-05-05T12:09:44.909+1000 [DEBUG] [TestEventLogger]          at org.junit.platform.launcher.core.OutcomeDelayingEngineExecutionListener.executionFinished(OutcomeDelayingEngineExecutionListener.java:63)
2022-05-05T12:09:44.909+1000 [DEBUG] [TestEventLogger]          at org.junit.support.testng.engine.ExecutionListener.lambda$onAfterClass$2(ExecutionListener.java:81)
2022-05-05T12:09:44.909+1000 [DEBUG] [TestEventLogger]          at org.junit.support.testng.engine.TestClassRegistry.lambda$finish$2(TestClassRegistry.java:52)
2022-05-05T12:09:44.909+1000 [DEBUG] [TestEventLogger]          at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1877)
2022-05-05T12:09:44.909+1000 [DEBUG] [TestEventLogger]          at org.junit.support.testng.engine.TestClassRegistry.finish(TestClassRegistry.java:46)
2022-05-05T12:09:44.909+1000 [DEBUG] [TestEventLogger]          at org.junit.support.testng.engine.ExecutionListener.onAfterClass(ExecutionListener.java:78)
2022-05-05T12:09:44.909+1000 [DEBUG] [TestEventLogger]          at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:207)
2022-05-05T12:09:44.909+1000 [DEBUG] [TestEventLogger]          at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:130)
2022-05-05T12:09:44.909+1000 [DEBUG] [TestEventLogger]          at java.util.ArrayList.forEach(ArrayList.java:1259)
2022-05-05T12:09:44.910+1000 [DEBUG] [TestEventLogger]          at org.testng.TestRunner.privateRun(TestRunner.java:770)
2022-05-05T12:09:44.910+1000 [DEBUG] [TestEventLogger]          at org.testng.TestRunner.run(TestRunner.java:591)
2022-05-05T12:09:44.910+1000 [DEBUG] [TestEventLogger]          at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
2022-05-05T12:09:44.910+1000 [DEBUG] [TestEventLogger]          at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
2022-05-05T12:09:44.910+1000 [DEBUG] [TestEventLogger]          at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
2022-05-05T12:09:44.910+1000 [DEBUG] [TestEventLogger]          at org.testng.SuiteRunner.run(SuiteRunner.java:304)
2022-05-05T12:09:44.910+1000 [DEBUG] [TestEventLogger]          at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
2022-05-05T12:09:44.910+1000 [DEBUG] [TestEventLogger]          at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
2022-05-05T12:09:44.910+1000 [DEBUG] [TestEventLogger]          at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
2022-05-05T12:09:44.910+1000 [DEBUG] [TestEventLogger]          at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
2022-05-05T12:09:44.910+1000 [DEBUG] [TestEventLogger]          at org.testng.TestNG.runSuites(TestNG.java:1032)
2022-05-05T12:09:44.910+1000 [DEBUG] [TestEventLogger]          at org.testng.TestNG.run(TestNG.java:1000)
2022-05-05T12:09:44.910+1000 [DEBUG] [TestEventLogger]          at org.junit.support.testng.engine.TestNGTestEngine.configureAndRun(TestNGTestEngine.java:182)
2022-05-05T12:09:44.910+1000 [DEBUG] [TestEventLogger]          at org.junit.support.testng.engine.TestNGTestEngine.execute(TestNGTestEngine.java:162)
2022-05-05T12:09:44.910+1000 [DEBUG] [TestEventLogger]          at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
2022-05-05T12:09:44.910+1000 [DEBUG] [TestEventLogger]          at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
2022-05-05T12:09:44.910+1000 [DEBUG] [TestEventLogger]          at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
2022-05-05T12:09:44.910+1000 [DEBUG] [TestEventLogger]          at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
2022-05-05T12:09:44.910+1000 [DEBUG] [TestEventLogger]          at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
2022-05-05T12:09:44.910+1000 [DEBUG] [TestEventLogger]          at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
2022-05-05T12:09:44.910+1000 [DEBUG] [TestEventLogger]          at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
2022-05-05T12:09:44.910+1000 [DEBUG] [TestEventLogger]          at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
2022-05-05T12:09:44.910+1000 [DEBUG] [TestEventLogger]          at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
2022-05-05T12:09:44.910+1000 [DEBUG] [TestEventLogger]          at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
2022-05-05T12:09:44.911+1000 [DEBUG] [TestEventLogger]          at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
2022-05-05T12:09:44.911+1000 [DEBUG] [TestEventLogger]          at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
2022-05-05T12:09:44.911+1000 [DEBUG] [TestEventLogger]          at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
2022-05-05T12:09:44.911+1000 [DEBUG] [TestEventLogger]          at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-05-05T12:09:44.911+1000 [DEBUG] [TestEventLogger]          at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-05-05T12:09:44.911+1000 [DEBUG] [TestEventLogger]          at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-05-05T12:09:44.911+1000 [DEBUG] [TestEventLogger]          at java.lang.reflect.Method.invoke(Method.java:498)
2022-05-05T12:09:44.911+1000 [DEBUG] [TestEventLogger]          at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
2022-05-05T12:09:44.911+1000 [DEBUG] [TestEventLogger]          at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
2022-05-05T12:09:44.911+1000 [DEBUG] [TestEventLogger]          at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
2022-05-05T12:09:44.911+1000 [DEBUG] [TestEventLogger]          at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
2022-05-05T12:09:44.911+1000 [DEBUG] [TestEventLogger]          at com.sun.proxy.$Proxy2.stop(Unknown Source)
2022-05-05T12:09:44.911+1000 [DEBUG] [TestEventLogger]          at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
2022-05-05T12:09:44.911+1000 [DEBUG] [TestEventLogger]          at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
2022-05-05T12:09:44.911+1000 [DEBUG] [TestEventLogger]          at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
2022-05-05T12:09:44.911+1000 [DEBUG] [TestEventLogger]          at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
2022-05-05T12:09:44.911+1000 [DEBUG] [TestEventLogger]          at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
2022-05-05T12:09:44.911+1000 [DEBUG] [TestEventLogger]          at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
2022-05-05T12:09:44.911+1000 [DEBUG] [TestEventLogger]          at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
2022-05-05T12:09:44.911+1000 [DEBUG] [TestEventLogger]          at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
2022-05-05T12:09:44.911+1000 [DEBUG] [TestEventLogger]          at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
2022-05-05T12:09:44.911+1000 [DEBUG] [TestEventLogger]
2022-05-05T12:09:44.957+1000 [DEBUG] [TestEventLogger]
2022-05-05T12:09:44.957+1000 [DEBUG] [TestEventLogger] Gradle Test Executor 3 PASSED
2022-05-05T12:09:44.992+1000 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: SUCCEEDED
2022-05-05T12:09:44.992+1000 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'Gradle Test Executor 3' finished with exit value 0 (state: SUCCEEDED)
```

**Comment by marcphilipp** [comment] 2022-05-05 14:47
This is caused by a bug in testng-engine that should be fixed by https://github.com/junit-team/testng-engine/pull/19.

**Closed** 2022-05-05 18:50 UTC
Labels: a:investigation
