### ISSUE TITLE
Idea plugin generates incorrect dependencies list

### ISSUE THREAD

**Issue by vitgorbunov** [gradle/gradle#2101] opened 2017-05-20 21:08 UTC
After migration from gradle 3.2.1 to 3.5 I've noticed that dependencies list in generated idea project changed.

The following file can be used as example
```
apply plugin: 'java'
apply plugin: 'idea'

repositories {
  mavenLocal()
  mavenCentral()
}

dependencies {
  compile group:'org.eclipse.persistence', name:'eclipselink', version: "2.6.4" 
  testCompile group:'junit', name:'junit', version:"4.11"
}

idea {
  module {
    name = 'gradletest'
  }
}
```

### Expected Behavior
According to https://docs.gradle.org/current/dsl/org.gradle.plugins.ide.idea.model.IdeaModule.html#org.gradle.plugins.ide.idea.model.IdeaModule:scopes defaults should be the following:

> Default with idea and java plugin:
> COMPILE -> project.configurations.compile
> RUNTIME -> project.configurations.runtime - project.configurations.compile
> TEST -> project.configurations.testRuntime - project.configurations.runtime
> PROVIDED
>

This is what I had with gradle 3.2.1 
![gradle321](https://cloud.githubusercontent.com/assets/895422/26279311/ead8aee0-3db8-11e7-8f6f-8e8e7fa50c6a.png)

### Current Behavior
It seems that in gradle 3.5 result is actually the following

> COMPILE
> RUNTIME -> project.configurations.runtime // merged with- project.configurations.compile
> TEST -> project.configurations.testCompile // merged with project.configurations.compile
> PROVIDED -> project.configuration.compile

project.configurations.testRuntime is not even added to the list

![gradle35](https://cloud.githubusercontent.com/assets/895422/26279312/f38f629a-3db8-11e7-8948-5e2cff73935c.png)

**Comment by bmuschko** [comment] 2017-05-22 12:47
I believe that was a bug in an earlier version of IntelliJ. Can you please upgrade to the latest version and try again?

**Comment by vitgorbunov** [comment] 2017-05-22 17:17
I used idea 2017.1.3.
Does it even depend on idea version? Considering that project is generated by gradle plugin and everything was fine with gradle 3.2.1

**Comment by vitgorbunov** [comment] 2017-05-22 17:20
To clarify - I didn't mean gradle project imported by idea here. I mean gradle plugin that allows to generate idea project with `gradle idea `

**Comment by vitgorbunov** [comment] 2017-05-25 05:43
Is there any details I should add to label it as a bug?

For now I'm using workaround

```
scopes.COMPILE.plus = [configurations.compile]
scopes.TEST.plus = [configurations.testCompile]
scopes.RUNTIME.plus = [configurations.runtime]
scopes.RUNTIME.plus = [configurations.testRuntime]

scopes.TEST.minus = [configurations.compile]
scopes.RUNTIME.minus = [configurations.compile]
scopes.RUNTIME.minus = [configurations.testCompile]
scopes.PROVIDED.minus = [configurations.compile]
```

**Comment by vitgorbunov** [comment] 2017-06-17 10:54
Still reproduced in 4.0.
Could you mark it as a bug?

**Comment by oehme** [comment] 2017-07-06 20:48
This is a duplicate of https://github.com/gradle/gradle/issues/1276

**Closed by oehme** 2017-07-06 20:48 UTC
Labels: a:question, from:contributor, in:idea-plugin

**Comment by oehme** [comment] 2017-07-07 06:40
For the record, I used your example project and the dependencies are in the right scope, no matter if I use Idea's importer or if I run `gradle idea´.

**Comment by oehme** [comment] 2017-07-07 06:55
Is there an actual behavioural problem you were facing or were you just wondering about the dependency scopes? We changed the scopes to make Gradle's implementation much simpler, but everything should still work as before (which I verified using your example).

**Comment by vitgorbunov** [comment] 2017-07-07 17:51
To me the problem is that dependencies are not generated in the way it's described in official documentation - https://docs.gradle.org/current/dsl/org.gradle.plugins.ide.idea.model.IdeaModule.html#org.gradle.plugins.ide.idea.model.IdeaModule:scopes
So I have to add workaround to bypass it.

Weird that you don't have this problem. I still don't know how idea version related here, but what gradle version did you use for `gradle idea`?
I just tried it with both gradle 3.5 and 4.0 and idea 2017.1.5 - still the same problem

**Comment by oehme** [comment] 2017-07-07 18:24
Can you please explain what the problem is? I.e. what does not work?
