### ISSUE TITLE
Gradle downloads excluded transitive dependencies

### ISSUE THREAD

**Issue by tenor-dev** [gradle/gradle#23182] opened 2022-12-15 15:07 UTC
### Expected Behavior
When depending on a library that has some of it's own dependencies of dependencies excluded, they should not be downloaded.

### Current Behavior
Dependening on klite-liquibase, which depends on liquibase-core with it's dependencies excluded still downloads liquibase-core's dependencies.

E.g. this version:
https://jitpack.io/com/github/codeborne/klite/klite-liquibase/c974b4e0/klite-liquibase-c974b4e0.pom

Source:
https://github.com/codeborne/klite/blob/master/liquibase/build.gradle.kts

### Steps to Reproduce 

build.gradle.kts
```
plugins {
  kotlin("jvm") version "1.7.20"
}

allprojects {
  repositories {
    mavenCentral()
    maven { url = uri("https://jitpack.io") }
  }
}

dependencies {
  implementation("com.github.codeborne.klite:klite-liquibase:c974b4e0")
}
```

Then run `./gradlew dependencies`

Includes the following output:
```
+--- org.liquibase:liquibase-core:4.18.0
     |    +--- javax.xml.bind:jaxb-api:2.3.1
     |    |    \--- javax.activation:javax.activation-api:1.2.0
     |    +--- org.yaml:snakeyaml:1.33
     |    \--- com.opencsv:opencsv:5.7.1
     |         +--- org.apache.commons:commons-lang3:3.12.0
     |         +--- org.apache.commons:commons-text:1.10.0
     |         |    \--- org.apache.commons:commons-lang3:3.12.0
     |         \--- org.apache.commons:commons-collections4:4.4
```

But the pom.xml of klite-liquibase linked about has the following:
```
<dependency>
  <groupId>org.liquibase</groupId>
  <artifactId>liquibase-core</artifactId>
  <version>4.18.0</version>
  <scope>compile</scope>
  <exclusions>
    <exclusion>
      <artifactId>*</artifactId>
      <groupId>com.opencsv</groupId>
    </exclusion>
    <exclusion>
      <artifactId>*</artifactId>
      <groupId>org.yaml</groupId>
    </exclusion>
    <exclusion>
      <artifactId>*</artifactId>
      <groupId>javax.xml.bind</groupId>
    </exclusion>
  </exclusions>
</dependency>
```

which should exclude `org.yaml:*` and friends.

### Your Environment
Build scan URL: https://scans.gradle.com/s/i2o6xoogiaf34

**Comment by xaviarias** [comment] 2022-12-19 09:59
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and prioritized by them.

---

The workaround is to redeclare the exclusions in the Gradle file.

**Comment by xaviarias** [comment] 2022-12-21 15:05
Hi, the issue seems related to the [JSON module file](https://jitpack.io/com/github/codeborne/klite/klite-liquibase/c974b4e0/klite-liquibase-c974b4e0.module) in the Jitpack repository.

As you can see, the Liquibase dependency lacks the `excludes` section, whereas publishing Klite locally generates the module file with the expected exclusions:

<details><summary><code>klite-liquibase-1.0-SNAPSHOT.module</code></summary>
<p>

```json
{
  "formatVersion": "1.1",
  "component": {
    "group": "klite",
    "module": "klite-liquibase",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.liquibase",
          "module": "liquibase-core",
          "version": {
            "requires": "4.18.0"
          },
          "excludes": [
            {
              "group": "com.opencsv",
              "module": "*"
            },
            {
              "group": "org.yaml",
              "module": "*"
            },
            {
              "group": "javax.xml.bind",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "klite-liquibase-1.0-SNAPSHOT.jar",
          "url": "klite-liquibase-1.0-SNAPSHOT.jar",
          "size": 7526,
          "sha512": "61b5522837b5b32bddfc0531bd4f8c5f3495eb9285f0fc9688133e80d1ca0df435d8669a242034305e4816f1ca0690c08f139df85cca662da98c7bf104916b82",
          "sha256": "7873c977df6275a47dc3c3913f2762d2f5cc8a262a8ccf35fc86e94f9caf00db",
          "sha1": "11cf40059418a0b2668f00bc352708efdf71768e",
          "md5": "57e3112ed67aa562e96bf20d4c811f33"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "klite",
          "module": "klite-server",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "klite",
          "module": "klite-slf4j",
          "version": {
            "requires": "1.0-SNAPSHOT"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "org.liquibase",
          "module": "liquibase-core",
          "version": {
            "requires": "4.18.0"
          },
          "excludes": [
            {
              "group": "com.opencsv",
              "module": "*"
            },
            {
              "group": "org.yaml",
              "module": "*"
            },
            {
              "group": "javax.xml.bind",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "klite-liquibase-1.0-SNAPSHOT.jar",
          "url": "klite-liquibase-1.0-SNAPSHOT.jar",
          "size": 7526,
          "sha512": "61b5522837b5b32bddfc0531bd4f8c5f3495eb9285f0fc9688133e80d1ca0df435d8669a242034305e4816f1ca0690c08f139df85cca662da98c7bf104916b82",
          "sha256": "7873c977df6275a47dc3c3913f2762d2f5cc8a262a8ccf35fc86e94f9caf00db",
          "sha1": "11cf40059418a0b2668f00bc352708efdf71768e",
          "md5": "57e3112ed67aa562e96bf20d4c811f33"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "klite-liquibase-1.0-SNAPSHOT-sources.jar",
          "url": "klite-liquibase-1.0-SNAPSHOT-sources.jar",
          "size": 1269,
          "sha512": "50b66647a9ebf95bbfcff0f8062b4e8933c42aa5416e55ff35d2c1cb1bb31593c4083fe0877f1813ee9d65a451bf76d5bdef5659f34708c6a374630184ec5af1",
          "sha256": "5041ff15925e98800a337e59402f06d2d87e0bcffa056ce3ce7a2470a245563c",
          "sha1": "6db27a9178422420ddd3a7438b1063453c9342f0",
          "md5": "bdf8128058dea2a72a38b08d39b33a4f"
        }
      ]
    }
  ]
}
```

</p>
</details>

Not sure how the file ended-up in the Jitpack repository missing this part, but Gradle uses this file and not the POM so this is the expected behavior.

I'm closing the issue, if I missed something please re-poen it and provide more information on the issue.

**Closed by xaviarias** 2022-12-21 15:05 UTC
Labels: a:bug, in:dependency-resolution, in:maven-integration, has:reproducer, has:workaround

**Comment by angryziber** [comment] 2022-12-24 09:13
@xaviarias thanks a lot for pointing it out, I didn't even know about json module files.

However, the file above is generated by Gradle as well. Do you have any idea why Gradle did not add excludes there?
The excludes are defined in the dependencies section: https://github.com/codeborne/klite/blob/master/liquibase/build.gradle.kts

**Comment by angryziber** [comment] 2022-12-24 11:17
OK, it seems when running `./gradlew publishToMavenLocal` actually produces correct exclusions in module file.
The actual problem seems to be Jitpack related: https://github.com/jitpack/jitpack.io/issues/5349
