### ISSUE TITLE
First configuration to resolve determines effective dynamic version cache policy

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#3019] opened 2017-09-25 21:55 UTC
When a dynamic version is first resolved, that version list cached for the duration of the build. However, if the first configuration to resolve doesn't carry the desired `cacheDynamicVersionsFor` setting (as is the case for detached configurations), that will lead to stale dependencies being selected.

### Expected Behavior
The individual cache TTL is honored.

### Current Behavior
The cache TTL of the first configuration to resolve determines the staleness of dynamic dependencies.

### Context
When we update dependency locks, we set changing/dynamic caching to `0`, however plugins like Spring Dependency Management use detached configurations as part of dependency resolution, causing that configuration to be ignored.

#### Build

Run `gw resolve --debug | grep DynamicVersion -A5` against the following build:

	plugins {
		id 'java'
	}

	repositories {
		mavenCentral()
	}

	dependencies {
		compile 'com.google.guava:guava:latest.release'
	}

	configurations.all {
		resolutionStrategy {
		 	cacheDynamicVersionsFor 0, 'seconds'
		}
	}

	task resolve() {
		doFirst {
			// Resolve a configuration that doesn't have the desired dynamic TTL
			configurations.detachedConfiguration(dependencies.create('com.google.guava:guava:latest.release')).files

			// Resolve the desired configuration
			configurations.compile.files
		}
	}

#### Observation

Note that the first dynamic version lookup indicates `Using cached module metadata` and the following requests perform no lookup:

	14:48:42.749 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.DynamicVersionResolver] Attempting to resolve version for com.google.guava:guava:latest.release using repositories [MavenRepo]
	14:48:42.749 [INFO] [org.gradle.cache.internal.DefaultCacheAccess] Creating new cache for metadata-2.23/module-versions, path /Users/dannyt/.gradle/caches/modules-2/metadata-2.23/module-versions.bin, access org.gradle.cache.internal.DefaultCacheAccess@1d5f484
	14:48:42.750 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Opening cache module-versions.bin (/Users/dannyt/.gradle/caches/modules-2/metadata-2.23/module-versions.bin)
	14:48:42.750 [INFO] [org.gradle.cache.internal.DefaultCacheAccess] Creating new cache for metadata-2.23/module-metadata, path /Users/dannyt/.gradle/caches/modules-2/metadata-2.23/module-metadata.bin, access org.gradle.cache.internal.DefaultCacheAccess@1d5f484
	14:48:42.750 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Opening cache module-metadata.bin (/Users/dannyt/.gradle/caches/modules-2/metadata-2.23/module-metadata.bin)
	14:48:42.751 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Using cached module metadata for module 'com.google.guava:guava:23.0' in 'MavenRepo'
	--
	14:48:42.751 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.DynamicVersionResolver] Using com.google.guava:guava:23.0 from Maven repository 'MavenRepo'
	14:48:42.751 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder] Selecting new module version com.google.guava:guava:23.0
	14:48:42.751 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder] Visiting configuration com.google.guava:guava:23.0(default).
	14:48:42.751 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder] Visiting dependency com.google.guava:guava:23.0(default) -> dependency: com.google.code.findbugs:jsr305:1.3.9, scope: Compile, optional: false
	14:48:42.751 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder] Selecting new module version com.google.code.findbugs:jsr305:1.3.9
	14:48:42.751 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver] Attempting to resolve component for com.google.code.findbugs:jsr305:1.3.9 using repositories [MavenRepo]
	--
	14:48:42.757 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.DynamicVersionResolver] Attempting to resolve version for com.google.guava:guava:latest.release using repositories [MavenRepo]
	14:48:42.758 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.DynamicVersionResolver] Using com.google.guava:guava:23.0 from Maven repository 'MavenRepo'
	14:48:42.758 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder] Selecting new module version com.google.guava:guava:23.0
	14:48:42.758 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder] Visiting configuration com.google.guava:guava:23.0(default).
	14:48:42.758 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder] Visiting dependency com.google.guava:guava:23.0(default) -> dependency: com.google.code.findbugs:jsr305:1.3.9, scope: Compile, optional: false
	14:48:42.758 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder] Selecting new module version com.google.code.findbugs:jsr305:1.3.9
	14:48:42.758 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver] Attempting to resolve component for com.google.code.findbugs:jsr305:1.3.9 using repositories [MavenRepo]

### Your Environment
Gradle 3.5.1

**Comment by bigdaz** [comment] 2017-12-24 03:39
Thanks @DanielThomas for tracking this down.

This is a pretty nasty issue, caused by our in-memory resolution cache not respecting the different cache expiry settings for different configurations.
A similar problem exists where Maven SNAPSHOT modules will not be updated when they are first resolved by a detached configuration (that misses any cache expiry settings).

I hope to have a fix ready for 4.5.

**Closed** 2018-02-06 02:06 UTC
Labels: a:bug, from:contributor, in:dependency-management
