### ISSUE TITLE
Compiling Issue with Flutter Code.  

### ISSUE THREAD

**Issue by codeagarwal** [gradle/gradle#17924] opened 2021-08-03 10:41 UTC
### This is Bug in Android Studio Arctic Fox version 2020.3.1

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':path_provider:compileDebugJavaWithJavac'.
java.lang.IllegalAccessError: class org.gradle.internal.compiler.java.ClassNameCollector (in unnamed module @0x6353cddf) cannot access class com.sun.tools.javac.code.Symbol$TypeSymbol (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.code to unnamed module @0x6353cddf

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by mlopatkin** [comment] 2021-08-03 10:50
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it. In particular: what version of Java, Gradle, and Android Gradle Plugin are you using? Does your project work with a previous version of the Android Studio? Can the error be reproduced when building from the command line or is it specific to the build within the IDE?

This issue will be closed after 7 days unless you can provide more information.

**Comment by codeagarwal** [comment] 2021-08-04 10:21
You can check the Code Repo below. H ere is the complete source code.

[Here is the REPOSITORY which includes the code.](https://github.com/codeagarwal/flutter_30_days/tree/Day20)


Please help me with this error. I'm facing this Error after **Arctic Fox 2020.3.1** Update of Android Studio.

**Comment by mlopatkin** [comment] 2021-08-04 14:06
Thanks for the reproducer. I suspect that your flutter build is using too recent JDK (like JDK 16). You can confirm it by running `flutter doctor -v`:
```
$ flutter doctor -v
...

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ...   
    • Java version OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)    
...
```

The safe bet is probably to use the JDK 11 embedded into the Android Studio. The Gradle build tool supports JDK 16 since version 6.9, so you can try to upgrade the Gradle version in your build (flutter uses 6.7 by default) but this approach can cause errors further down.

Sorry, but I'm not familiar with flutter enough to advise how to change its default JDK.

In the end, this isn't a problem with Gradle, so I'm closing the issue.

**Closed by mlopatkin** 2021-08-04 14:06 UTC
Labels: a:bug, to-triage

**Comment by codeagarwal** [comment] 2021-08-05 15:24
Thanks for your guidance, but I'm still facing the same issue. Can you please guide me again to solve this issue.

**Comment by codeagarwal** [comment] 2021-08-05 15:28
Please help me with this. I'm requesting you to help me sort this error, it lags me for some important projects.

please help me.

**Comment by mlopatkin** [comment] 2021-08-05 15:28
I'm sorry but this isn't a support forum. I suggest you try Stackoverflow or more specialized Flutter resources.

**Comment by codeagarwal** [comment] 2021-08-05 15:30
but the issue is related to gradle.

**Comment by mlopatkin** [comment] 2021-08-05 15:37
You are using a combination of Gradle and JDK that isn't supported. You can either update Gradle version to at least 6.9 (that may break something if Flutter doesn't support a newer version) or downgrade the JDK Flutter uses (I don't know how to do that, maybe uninstall all but the JDK embedded into Android Studio). For the former you can try to do something along the lines of
https://github.com/gradle/gradle/issues/17363#issuecomment-863213136, changing the version in the `gradle.properties` file to 6.9. You may or may not need to update the Android Gradle plugin version too.
