### ISSUE TITLE
Build produces INFO log "Script 'build.gradle.kts' is not supposed to be used along with regular Kotlin sources, and will be ignored in the future versions by default."

### ISSUE THREAD

**Issue by Tapchicoma** [gradle/gradle#23491] opened 2023-01-11 16:23 UTC
### Expected Behavior

No warning in INFO logs for Kotlin DSL scripts when running build with Gradle 8.0-rc-1+ version.

### Current Behavior

Warning is printed in INFO level logs for any `*.gradle.kts` file.

### Steps to Reproduce 

Check repro project from this [Kotlin issue](https://youtrack.jetbrains.com/issue/KT-55880)

**Comment by eskatos** [comment] 2023-01-14 08:18
The reproducer shows that what is displayed by the Kotlin Gradle Plugin is not a warning anymore since the addition of `isStandalone(false)` in the Gradle script templates. It is not emited to the info logger.

Waiting for confirmation from the Kotlin team that this is expected.

**Comment by eskatos** [comment] 2023-01-17 16:48
* Fixed in https://github.com/gradle/gradle/pull/23558

This will ship in Gradle 8.0

**Closed by eskatos** 2023-01-17 16:48 UTC
Labels: a:bug, in:kotlin-dsl, affects-version:8.0
