### ISSUE TITLE
There are a few problems that make me have to give up gradle

### ISSUE THREAD

**Issue by love-learning-hjk** [gradle/gradle#9901] opened 2019-07-09 02:35 UTC
During the process of using gradle, I encountered several problems.
1.Changing a java file with a constant triggers a full compilation.
2.After gradle is upgraded to version 5.4.1 or 5.5, the jar package org.apache.commons.lang3 cannot be found, and this jar package is passed by other jar packages.
3.The most serious problem is that when I modify a class, the incremental compilation triggered will not only compile the error, but also be several times slower than the full compilation. However, the full compilation does not compile the error.

The above problem is based on the project of our company. I am sorry because the company requested that there is no way to share the project.

As a Chinese programmer, I still like gradle so much that I will take some time to study it in recent weeks, but the domestic information is really too little, so I sincerely hope that everyone can help me solve these problems.

Java version is 1.8

**Comment by blindpirate** [comment] 2019-07-09 02:52
Sorry to hear that.

> Changing a java file with a constant triggers a full compilation.

This is expected [behavior](https://docs.gradle.org/current/userguide/java_plugin.html#sec:incremental_compile). You can change to static accessor method or modulize your project.

> After gradle is upgraded to version 5.4.1 or 5.5, the jar package org.apache.commons.lang3 cannot be found, and this jar package is passed by other jar packages.

I don't quite understand the sentence. I understand your can't share your project, but without a minimum reproducible sample we can't do anything.

> The most serious problem is that when I modify a class, the incremental compilation triggered will not only compile the error, but also be several times slower than the full compilation. However, the full compilation does not compile the error.

What's `compile the error`? If you don't like incremental compilation, just disable it with `options.incremental=false` so we don't do anything magic for you.

> As a Chinese programmer, I still like gradle so much that I will take some time to study it in recent weeks, but the domestic information is really too little, so I sincerely hope that everyone can help me solve these problems.

I'm also a Chinese developer. I'm afraid you'd better start reading English documenations, not only for Gradle, but also for every state-of-the-art technique in the future.

Closing due to not actionable.

**Closed by blindpirate** 2019-07-09 02:52 UTC
Labels: a:bug, from:contributor

**Comment by love-learning-hjk** [comment] 2019-07-09 07:43
@blindpirate Thank you for your answer.
The official document I found the first time, but there is no answer I want.
Let's discuss these issues in order.
In the first question, I know that this phenomenon is what you expected. But I think there should be any way to deal with this kind of problem. For example, before compiling, changing the constant in the java file to static will return a constant method. After all, there is no good way to constrain everyone's use of the gradle team. There is no constant in the code format. Of course, there is a way to provide that is better.

**Comment by blindpirate** [comment] 2019-07-09 09:06
> But I think there should be any way to deal with this kind of problem.

No we really don't have a better solution. If you don't like the incremental compilation, just disable it.

> After all, there is no good way to constrain everyone's use of the gradle team. There is no constant in the code format. Of course, there is a way to provide that is better.

I don't understand these two sentences....

**Comment by love-learning-hjk** [comment] 2019-07-09 09:25
Incremental compilation is what our project needs, because our project updates are more frequent, and if we compile it all at once, it will be terrible.
There is no practical way for gradle to compile with this kind of hidden rules for every developer to follow, so I prefer to modify the constants in the java file to the static method you want before compiling to avoid full compilation. For example, rocker, this is what I found when I was browsing gradle related information, https://github.com/fizzed/rocker. I don't know if I can use rocker to modify the constants in the java file, but the rocker has less information.

**Comment by blindpirate** [comment] 2019-07-10 02:41
If you take a deep look at [the blog](https://blog.gradle.org/incremental-compiler-avoidance) an the code, you probably would have different opinions. If not, that's fine - anyway we're opensource - everything you need is opensource - just implement whatever you think better. We're happy to accept PRs.

**Comment by love-learning-hjk** [comment] 2019-07-14 12:49
Ok, I understand the specific situation. I will continue the practice here, thank you for your answer.

**Comment by love-learning-hjk** [comment] 2019-07-14 13:18
Finally, I want to know if gradle will optimize for this compilation problem. After all, it is ok to know which classes reference these variables.
