### ISSUE TITLE
Gradle does not support connecting to maven repositories with SNI

### ISSUE THREAD

**Issue by lbguilherme** [gradle/gradle#1868] opened 2017-04-21 09:19 UTC
Currently Gradle is unable to fetch artifacts from a maven repository if its server requires SNI to work.
 Pretty much every client support SNI nowadays, so why gradle doesn't? My usecase is that I'm creating a private maven repo with my server, but I don't want to "waste" a entire IP address just for this maven server. Using virtual servers is fairly common.
Serving using plain HTTP also doesn't look like a solution for this.

How to fix: Upgrade to a newer HTTPClient.

**Comment by mikroskeem** [comment] 2017-04-27 14:26
Confirmed. Unable to upload archives into my maven repository, hosted on vhost & Let's Encrypt

**Comment by mw9** [comment] 2017-06-05 16:49
I seem to be unable build a "Gradle" based project. It fails while fetching a resource from a repository hosted at raw.github.com:

> Could not GET 'https://raw.github.com/path/to/a.pom'.
> peer not authenticated

raw.github.com is being redirected to raw.githubuser.com, and that does require SNI to work (today, anyway).

Same problem ?

I have no experience of Gradle to draw on, but, to me, it seems rather likely to me that SNI is the root cause of the failure.

Gradle version 2.4

**Comment by Rocks360** [comment] 2017-06-30 12:19
By me too. I also can't upload a archive to maven repository

**Comment by mikroskeem** [comment] 2017-07-14 14:19
Any updates on this?

**Comment by bmuschko** [comment] 2017-07-14 15:11
Currently, we don't have fixing this issue lined up in the short term. Would you be interested in providing a pull request for the functionality?

**Comment by dajudge** [comment] 2017-07-20 13:52
Confirmed with 4.0.1. Unable to upload archives into my maven repository, also hosted on a vhost with letsencrypt  certificates.

I found a rather old thread about a similar issue https://discuss.gradle.org/t/maven-repository-on-ssl-with-sni/12808 which points to https://issues.gradle.org/browse/GRADLE-3250 which is supposed to be fixed since 2.11

Are we facing a regression here?

I am using the following gradle version:

    ------------------------------------------------------------
    Gradle 4.0.1
    ------------------------------------------------------------

    Build time:   2017-07-07 14:02:41 UTC
    Revision:     38e5dc0f772daecca1d2681885d3d85414eb6826

    Groovy:       2.4.11
    Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
    JVM:          1.8.0_131 (Oracle Corporation 25.131-b11)
    OS:           Windows 10 10.0 amd64

The entire debug output (~1.3MB) of `gradle uploadArchives -Djavax.net.debug=all --no-daemon --debug` can be found here:
https://filebin.ca/3U1hvVYflKP3/debug.txt

The relevant part is I think in lines 7189-7197 where you can see that there is in deed no SNI extension sent:

    15:37:17.281 [INFO] [system.out] *** ClientHello, TLSv1.2
    15:37:17.281 [INFO] [system.out] RandomCookie:  GMT: 1500492301 bytes = { 171, 70, 139, 245, 50, 218, 78, 229, 181, 123, 40, 239, 124, 217, 162, 38, 213, 82, 91, 31, 227, 158, 225, 114, 174, 221, 101, 200 }
    15:37:17.281 [INFO] [system.out] Session ID:  {}
    15:37:17.281 [INFO] [system.out] Cipher Suites: [TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_DSS_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA, TLS_EMPTY_RENEGOTIATION_INFO_SCSV]
    15:37:17.281 [INFO] [system.out] Compression Methods:  { 0 }
    15:37:17.281 [INFO] [system.out] Extension elliptic_curves, curve names: {secp256r1, secp384r1, secp521r1, sect283k1, sect283r1, sect409k1, sect409r1, sect571k1, sect571r1, secp256k1}
    15:37:17.281 [INFO] [system.out] Extension ec_point_formats, formats: [uncompressed]
    15:37:17.281 [INFO] [system.out] Extension signature_algorithms, signature_algorithms: SHA512withECDSA, SHA512withRSA, SHA384withECDSA, SHA384withRSA, SHA256withECDSA, SHA256withRSA, SHA256withDSA, SHA1withECDSA, SHA1withRSA, SHA1withDSA
    15:37:17.281 [INFO] [system.out] ***

**Comment by Rocks360** [comment] 2017-07-29 13:02
How much is the workload to fix this, if I haven't knowledge in how SNI works in gradle? one, three or five days?

**Comment by hansschtedke** [comment] 2017-09-19 08:17
Upgrading to newer java (1.8.0_144) worked for me with SNI.

**Comment by Rocks360** [comment] 2017-09-20 11:52
@hansschtedke  Worked for me too. (macOS). But only from the terminal. With STS it's not working!

**Comment by jbq** [comment] 2018-01-30 10:33
I'm facing exactly the same issue.  I can't believe it can be such a PITA to use HTTPS in a Java environment in 2018 :-|

**Comment by jbq** [comment] 2018-01-30 10:36
Workaround: after installing Java 9 with `brew cask install java` the problem goes away.  I wonder where this might be documented.

**Comment by jjohannes** [comment] 2019-12-06 11:13
It sounds like this is working well nowadays. Does anyone still encounter an issue here with Gradle 6+ and current Java versions (11+)?

**Comment by mikroskeem** [comment] 2019-12-06 15:41
I've long forgotten about this, but I haven't encountered the issue with Gradle 5.0+ and recent Java 1.8.0_2xx+/11 release.

**Comment by jjohannes** [comment] 2019-12-12 08:47
Thanks @mikroskeem. I am closing thins issue.

If someone still encounters a problem like this with Gradle 6+, please open a separate issue with a reproducible example.

**Closed by jjohannes** 2019-12-12 08:47 UTC
Labels: a:feature, from:contributor, in:dependency-management
