### ISSUE TITLE
Publishing build scan failed due to network error 'java.net.SocketTimeoutException: connect timed out (with proxy settings)

### ISSUE THREAD

**Issue by markus-wa** [gradle/gradle#11384] opened 2019-11-15 14:11 UTC
### Expected Behavior
build scan should be published

### Current Behavior

```
BUILD SUCCESSFUL in 14m 18s
1128 actionable tasks: 689 executed, 439 up-to-date

Publishing a build scan to scans.gradle.com requires accepting the Gradle Terms of Service defined at https://gradle.com/teryGradle Terms of Service accepted.

Publishing build scan...
Publishing build scan failed due to network error 'java.net.SocketTimeoutException: connect timed out' (2 retries remaining).Publishing build scan failed due to network error 'java.net.SocketTimeoutException: connect timed out' (1 retry remaining)...
<
A network error occurred.

If you require assistance with this problem, please report it via https://gradle.com/scans/help/plugin and include the following information via copy/paste.
```

### Context
- I'm behind a corporate proxy.
- It worked in 4.x

### Steps to Reproduce 
`./gradlew build --scan`

### Your Environment
```
----------
Gradle version: 5.6.4
Plugin version: 2.4.2
Request URL: https://scans-in.gradle.com/in/5.6.4/2.4.2
Request ID: 9e1b4110-f45c-47ae-9571-46e62993d771
Exception: java.net.SocketTimeoutException: connect timed out
----------

http_proxy=http://my-proxy:port
https_proxy=http://my-proxy:port
```

`$ cat gradle.properties`
```properties
systemProp.http.proxyHost=my-proxy
systemProp.http.proxyPort=port
systemProp.http.nonProxyHosts=*.my-company.com
systemProp.https.proxyHost=my-proxy
systemProp.https.proxyPort=port
systemProp.https.nonProxyHosts=*.my-company.com
# -Dfile.encoding=CP1252 is needed to avoid 'error: unmappable character for encoding UTF8' :(
org.gradle.jvmargs=-Xmx4096m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=CP1252
```

**Comment by lacasseio** [comment] 2019-12-09 14:02
@ldaley Would you mind taking ownership of this issue?

**Comment by nddipiazza** [comment] 2020-03-28 19:23
happens to me now. help!

**Comment by ldaley** [comment] 2020-03-29 02:21
The latest version of the plugin (3.2) now respects the proxy settings configured for Gradle. Please try with that version.

**Comment by ntkoopman** [comment] 2020-05-20 06:53
It doesn't seem to respect the proxyUser / proxyPassword settings, because I get

```
----------
Gradle version: 6.4
Plugin version: 3.3
Request URL: https://scans-in.gradle.com/scans/publish/gradle/3.3/token
Request ID: 8b522fab-f1c2-4bb4-8907-8424e60ea92f
Exception: java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"
----------
```

even though I have `systemProp.https.proxyUser` and `systemProp.https.proxyPassword` (also for http using `systemProp.http.proxy*`) in `gradle.properties`

**Comment by felipefzdz** [comment] 2020-05-21 16:09
@ntkoopman we have some automated tests covering that, but I tried to reproduce it with a couple of repos. [This repo](https://github.com/felipefzdz/authenticated-proxy/blob/master/src/main/java/org/example/Main.java#L13) sets a proxy listening on 5003 expecting authentication on user:password.

This other repo sets the right properties [here](https://github.com/felipefzdz/scan-proxy/blob/master/gradle.properties). As we're using a http proxy, and not https, I'm sending the build scan to a missing http server, just for the sake of the example.

`./gradlew help -Dcom.gradle.scan.server=http://localhost:8080`

With the right creds it passes the proxy, failing with a 502 (as there's no server in the other side of the proxy) 

```
----------
Gradle version: 6.5-20200518140455+0000
Plugin version: 3.3.1
Request URL: http://localhost:5050/scans/publish/gradle/3.3.1/token
Request ID: 8fa06a2b-9372-40fd-bafa-f11bcf8c25ed
Response status code: 502
Response content type: text/html; charset=utf-8
----------
```

When changing the password on the `gradle.properties` file, I get 407 as expected:


```
----------
Gradle version: 6.5-20200518140455+0000
Plugin version: 3.3.1
Request URL: http://localhost:5050/scans/publish/gradle/3.3.1/token
Request ID: 365fa311-0c28-4825-a1b9-3ca91e580339
Response status code: 407
Response content type: text/html; charset=utf-8
----------
```

So I can imagine that:

- The creds on your side are not correct
- Your proxy is not expecting a header such as `Proxy-Authorization", "Basic ...`

**Comment by ntkoopman** [comment] 2020-05-25 05:39
@felipefzdz It's definitely not sending any headers, when I monitor with Wireshark I get:

```
CONNECT scans-in.gradle.com:443 HTTP/1.1
User-Agent: Java/11.0.6
Host: scans-in.gradle.com
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
```
If I use your `scan-proxy` repository, it's not connecting to the proxy at all, because you are setting `http.proxyHost` instead of `https.proxyHost`. If I change the configuration to https, I get the same message.

```
----------
Gradle version: 6.5-20200518140455+0000
Plugin version: 3.3.1
Request URL: https://scans-in.gradle.com/scans/publish/gradle/3.3.1/token
Request ID: ea20ca64-3b85-4878-bb55-977510f72294
Exception: java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"
----------
```

**Comment by felipefzdz** [comment] 2020-06-04 09:48
@ntkoopman, thanks for your constancy. We have confirmed that there's an issue with https proxies plus basic authentication. We have a fix ready to be shipped soon. I'll let you know here when that's released.

**Comment by felipefzdz** [comment] 2020-06-05 10:27
@ntkoopman [3.3.4](https://docs.gradle.com/enterprise/gradle-plugin/#release_history) version of the gradle enterprise plugin has been released with `Add support for basic authentication for HTTPS proxying`

**Comment by wlnirvana** [comment] 2021-02-03 01:55
I tried setting proxy in `gradle.properties` but still got the error with the latest versions:

```
----------                                                                                                                                                                                    
Gradle version: 6.7                                                                                                                                                                           
Plugin version: 3.4.1                                                                                                                                                                         
Request URL: https://scans-in.gradle.com/scans/publish/gradle/3.4.1/token                                                                                                                     
Request ID: c4144223-55e6-4ad1-a080-cb78b6eb124e                                                                                                                                              
Exception: java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 400 Bad Request"                                                                                      
----------  
```

**Comment by felipefzdz** [comment] 2021-02-03 11:18
@wlnirvana can you please share your `gradle.properties`? With the values redacted, of course.

This would be an example of a valid one: 

```
systemProp.https.proxyHost=localhost
systemProp.https.proxyPort=55388
systemProp.https.proxyUser=proxyUser
systemProp.https.proxyPassword=foobar123
```

**Comment by wlnirvana** [comment] 2021-02-04 00:40
@felipefzdz Sure. Below is my configuration. But it does not seem to work.

```
~/p/p/g/H/t/c/a/g/android_project (master|✚1) $ cat gradle.properties
android.useAndroidX=true
android.enableJetifier=true
org.gradle.daemon=false
org.gradle.jvmargs=-Xms512M -Xmx4g -XX:MaxPermSize=1024m -XX:MaxMetaspaceSize=1g -Dkotlin.daemon.jvm.options="-Xmx1g"
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=8001



~/p/p/g/H/t/c/a/g/android_project (master|✚1) $ ./gradlew --scan assembleDebug
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.4.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Configure project :
Repository https://jcenter.bintray.com/ replaced by https://maven.aliyun.com/repository/jcenter/.
Repository https://jcenter.bintray.com/ replaced by https://maven.aliyun.com/repository/jcenter/.

> Task :app:stripDebugDebugSymbols UP-TO-DATE
WARNING: No version of NDK matched the required version 21.1.6352462. Versions available locally: 22.0.7026061
No version of NDK matched the required version 21.1.6352462. Versions available locally: 22.0.7026061

BUILD SUCCESSFUL in 4s
25 actionable tasks: 25 up-to-date

Publishing a build scan to scans.gradle.com requires accepting the Gradle Terms of Service defined at https://gradle.com/terms-of-service. Do you accept these terms? [yes, no] yes

Gradle Terms of Service accepted.

Publishing build scan...

A network error occurred.

If you require assistance with this problem, please report it via https://gradle.com/help/plugin and include the following information via copy/paste.

----------
Gradle version: 6.4.1
Plugin version: 3.3.1
Request URL: https://scans-in.gradle.com/scans/publish/gradle/3.3.1/token
Request ID: e000fda4-789a-4df1-98fb-c0a4a5d1d632
Exception: java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 400 Bad Request"




~/p/p/g/H/t/c/a/g/android_project (master|✚1) $ all_proxy=127.0.0.1:8001 curl https://scans-in.gradle.com/scans/publish/gradle/3.3.1/token
<!DOCTYPE html>
<html>
<head>
    <!-- Google Analytics -->
<script src="/cdn-cgi/apps/head/mT371IMKRtEtJHJl9q67D-hCq88.js"></script><script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
ga('create', "UA-4207603-1", 'auto', "default", {'allowLinker': true});
ga("default.require", "linker");
ga("default.linker:autoLink", ['gradle.org'], false, true);
ga("default.set", 'transport', "beacon");
ga("default.require", "urlChangeTracker");
ga("default.send", 'pageview');
</script>
<!-- End Google Analytics -->
<!-- Start Google Analytics AutoTrack Plugin -->
<script>
(function(){var f="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){if(d.get||d.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=d.value)},g="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function h(){h=function(){};g.Symbol||(g.Symbol=k)}var m=0;function k(a){return"jscomp_symbol_"+(a||"")+m++}
function n(){h();var a=g.Symbol.iterator;a||(a=g.Symbol.iterator=g.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&f(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return q(this)}});n=function(){}}function q(a){var b=0;return r(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function r(a){n();a={next:a};a[g.Symbol.iterator]=function(){return this};return a}
function t(a){if(!(a instanceof Array)){n();var b=a[Symbol.iterator];a=b?b.call(a):q(a);for(var d=[];!(b=a.next()).done;)d.push(b.value);a=d}return a}var u=[];function v(a,b){var d=this;this.context=a;this.h=b;this.f=(this.c=/Task$/.test(b))?a.get(b):a[b];this.a=[];this.b=[];this.g=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];return d.b[d.b.length-1].apply(null,[].concat(t(b)))};this.c?a.set(b,this.g):a[b]=this.g}
function w(a,b){b=a.a.indexOf(b);-1<b&&(a.a.splice(b,1),0<a.a.length?x(a):(b=u.indexOf(a),-1<b&&(u.splice(b,1),a.c?a.context.set(a.h,a.f):a.context[a.h]=a.f)))}function x(a){a.b=[];for(var b,d=0;b=a.a[d];d++){var c=a.b[d-1]||a.f.bind(a.context);a.b.push(b(c))}}function y(a){var b=history,d=u.filter(function(c){return c.context==b&&c.h==a})[0];d||(d=new v(b,a),u.push(d));return d}
function z(a,b,d){var c={transport:"beacon"};if("function"==typeof d){var e=b.get("buildHitTask");return{buildHitTask:function(b){b.set(c,null,!0);b.set(a,null,!0);d(b,void 0,void 0);e(b)}}}return A({},c,a)}var A=Object.assign||function(a,b){for(var d=[],c=1;c<arguments.length;++c)d[c-1]=arguments[c];for(var c=0,e=d.length;c<e;c++){var p=Object(d[c]),l;for(l in p)Object.prototype.hasOwnProperty.call(p,l)&&(a[l]=p[l])}return a},B={l:1,m:2,o:3,u:4,v:5,w:6,A:7,B:8,j:9,s:10},C=Object.keys(B).length;
function D(a,b){var d=B.j;a.set("\x26_av","2.4.1");var c=a.get("\x26_au"),c=parseInt(c||"0",16).toString(2);if(c.length<C)for(var e=C-c.length;e;)c="0"+c,e--;d=C-d;c=c.substr(0,d)+1+c.substr(d+1);a.set("\x26_au",parseInt(c||"0",2).toString(16));history.pushState&&window.addEventListener&&(this.b=A({shouldTrackUrlChange:this.shouldTrackUrlChange,trackReplaceState:!1,fieldsObj:{},hitFilter:null},b),this.g=a,this.i=location.pathname+location.search,this.c=this.c.bind(this),this.f=this.f.bind(this),this.a=
this.a.bind(this),a=this.c,b=y("pushState"),b.a.push(a),x(b),a=this.f,b=y("replaceState"),b.a.push(a),x(b),window.addEventListener("popstate",this.a))}D.prototype.c=function(a){var b=this;return function(d){for(var c=[],e=0;e<arguments.length;++e)c[e-0]=arguments[e];a.apply(null,[].concat(t(c)));E(b,!0)}};D.prototype.f=function(a){var b=this;return function(d){for(var c=[],e=0;e<arguments.length;++e)c[e-0]=arguments[e];a.apply(null,[].concat(t(c)));E(b,!1)}};D.prototype.a=function(){E(this,!0)};
function E(a,b){setTimeout(function(){var d=a.i,c=location.pathname+location.search;d!=c&&a.b.shouldTrackUrlChange.call(a,c,d)&&(a.i=c,a.g.set({page:c,title:document.title}),(b||a.b.trackReplaceState)&&a.g.send("pageview",z(a.b.fieldsObj,a.g,a.b.hitFilter)))},0)}D.prototype.shouldTrackUrlChange=function(a,b){return!(!a||!b)};D.prototype.remove=function(){var a=this.c;w(y("pushState"),a);a=this.f;w(y("replaceState"),a);window.removeEventListener("popstate",this.a)};
(function(a,b){var d=window.GoogleAnalyticsObject||"ga";window[d]=window[d]||function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];(window[d].q=window[d].q||[]).push(b)};window.gaDevIds=window.gaDevIds||[];0>window.gaDevIds.indexOf("i5iSjo")&&window.gaDevIds.push("i5iSjo");window[d]("provide",a,b);window.gaplugins=window.gaplugins||{};window.gaplugins[a.charAt(0).toUpperCase()+a.slice(1)]=b})("urlChangeTracker",D);})();
</script>
<!-- End Google Analytics AutoTrack Plugin -->
    <meta charset='utf-8'/>
    <title>Error | Gradle Cloud Services</title>
    <link rel="apple-touch-icon" sizes="180x180" href="/assets/img/216d50437b0ca4b2d2852fcf7e754757.apple-touch-icon.png">
    <link rel="icon" type="image/png" href="/assets/img/eb275f050f669f691822c5b657861c72.favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="/assets/img/1799de37f8d14a00a55eec1686614ddf.favicon-16x16.png" sizes="16x16">
    <link rel="mask-icon" href="/assets/img/3e76c2c7632f0618cf0662f28cb39ab8.safari-pinned-tab.svg" color="#02303a">
    <link rel="preload" href="/assets/fonts/bd03a2cc277bbbc338d464e679fe9942.Lato-Regular.woff2" as="font" type="font/woff2" crossorigin>
    <link rel="preload" href="/assets/fonts/8b4f872c5de19974857328d06d3fe48f.Lato-Semibold.woff2" as="font" type="font/woff2" crossorigin>
    <link rel="preload" href="/assets/fonts/7244318390cc4d36aac4a613ff42d308.Lato-Light.woff2" as="font" type="font/woff2" crossorigin>
    <link rel="preload" href="/assets/fonts/4eb103b4d12be57cb1d040ed5e162e9d.Lato-Italic.woff2" as="font" type="font/woff2" crossorigin>
    <link rel="preload" href="/assets/fonts/9061f067797ab85c05f6c64b729fc2af.inconsolata.woff" as="font" type="font/woff" crossorigin>
    <link rel="preload" href="/assets/ui/bd9d39f64ac0e442047a.errorPage.css" as="style">
    <link rel="stylesheet" href="/assets/ui/bd9d39f64ac0e442047a.errorPage.css">

    <style>
        @font-face {
            font-family: 'Lato';
            src: url("/assets/fonts/7244318390cc4d36aac4a613ff42d308.Lato-Light.woff2") format('woff2');
            font-weight: 300;
            font-style: normal;
        }
        @font-face {
            font-family: 'Lato';
            src: url("/assets/fonts/bd03a2cc277bbbc338d464e679fe9942.Lato-Regular.woff2") format('woff2');
            font-weight: 400;
            font-style: normal;
        }
        @font-face {
            font-family: 'Lato';
            src: url("/assets/fonts/4eb103b4d12be57cb1d040ed5e162e9d.Lato-Italic.woff2") format('woff2');
            font-weight: 400;
            font-style: italic;
        }
        @font-face {
            font-family: 'Lato';
            src: url("/assets/fonts/8b4f872c5de19974857328d06d3fe48f.Lato-Semibold.woff2") format('woff2');
            font-weight: 500;
            font-style: normal;
        }
        @font-face {
            font-family: 'Inconsolata';
            src: url("/assets/fonts/9061f067797ab85c05f6c64b729fc2af.inconsolata.woff") format('woff');
            font-weight: normal;
            font-style: normal;
        }
    </style>

    <meta name="apple-mobile-web-app-title" content="Gradle Enterprise">
    <meta name="application-name" content="Gradle Enterprise">
    <meta name="msapplication-config" content="/assets/img/1bb58e83257ef3ca724b345793eaf050.browserconfig.xml">
    <meta name="theme-color" content="#f7f7f8">
    <script>
        window['com.gradle.error.fallback'] = '/error';
        window.pageData = {"errorMessage":"Something was wrong with your request.","helpPageUrl":"https://gradle.com/help","csrfToken":"umkalsblvivdrg5nchip54dmum","features":{"testDashboard":false,"buildDeletionRequest":{"enabled":true,"tokenTtl":1800000},"mavenIngest":true,"slowData":false,"profileRequest":false,"downloadRequestProfile":false,"showFocusId":false,"useRequestAnimationFrame":true,"developerWarnings":false,"testUi":false,"crossScan":false,"showGradleEnterpriseAd":true,"showGradleEnterpriseSplashScreen":false,"comparisonView":false,"showApplicationVersionInFooter":false,"showTermsOfServiceLinkInFooter":true,"showStatusPageLinkInFooter":true,"profileEventStreamProcessingIndividualEvent":false,"segment":{"enabled":true,"baseUrl":"https://api.segment.io/","throttle":10,"readTimeout":5000},"healthCheckAlert":false},"applicationVersion":"2020.5.2","contactName":"","contactEmail":""};
    </script>

    <script>
  function cbCallback(reveal) {
    window.cbReveal = reveal;
    if ('ga' in window) {
      ga('set', 'dimension1', reveal.company?.name);
      ga('set', 'dimension2', reveal.domain);
      ga('set', 'dimension3', reveal.company?.tags);
      ga('set', 'dimension4', reveal.company?.category.sector);
      ga('set', 'dimension5', reveal.company?.category.industryGroup);
      ga('set', 'dimension6', reveal.company?.category.industry);
      ga('set', 'dimension7', reveal.company?.category.subIndustry);
      ga('set', 'dimension8', reveal.company?.type);
      ga('set', 'dimension9', reveal.company?.metrics.employeesRange);
      ga('set', 'dimension10', reveal.company?.metrics.alexaGlobalRank);
      ga('set', 'dimension11', reveal.company?.geo.city);
      ga('set', 'dimension12', reveal.company?.geo.stateCode);
      ga('set', 'dimension13', reveal.company?.geo.countryCode);
      ga('set', 'dimension14', reveal.company?.metrics.raised);
      ga('set', 'dimension15', reveal.company?.tech);
      ga('set', 'dimension16', reveal.type);
      ga('send', 'event', 'Clearbit', 'Enriched', 'Clearbit Enriched', {nonInteraction: true});
    }
    return true;
  }
</script>
<script src="https://reveal.clearbit.com/v1/companies/reveal?authorization=pk_067c93c26f8959abd1943501094c424f&callback=cbCallback">
</script>
    <script type="text/javascript" src="https://assets.gradle.com/js/segment-page-tracker.js"></script>
    <script type="text/javascript">
        !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="3.1.0";
            analytics.load("mZvEgwUY2gJaoQ9JXcm9b2j4qtBbrhYY");
            segmentPageTracker.trackUrlChanges("scans");
            analytics.page("Client Error",{"App name":"scans"},{"context":{"app":{"name":"scans"}}})
        }}();
    </script>
</head>
<body>
    <div id='ui' class="errorPage"></div>
    
    <script type='text/javascript' src='/assets/ui/58f25e30a2d72c5f5e12.commons.bundle.js'></script>
    <script type='text/javascript' src='/assets/ui/bd9d39f64ac0e442047a.errorPage.bundle.js'></script>
    
    
    <script type="text/javascript">
piAId = "69052";
piCId = "50982";

(function() {
	function async_load(){
		var s = document.createElement('script'); s.type = 'text/javascript';
		s.src = ('https:' == document.location.protocol ? 'https://pi' : 'http://cdn') + '.pardot.com/pd.js';
		var c = document.getElementsByTagName('script')[0]; c.parentNode.insertBefore(s, c);
	}
	if(window.attachEvent) { window.attachEvent('onload', async_load); }
	else { window.addEventListener('load', async_load, false); }
})();
</script>
</body>
</html>
```

**Comment by felipefzdz** [comment] 2021-02-05 10:30
@wlnirvana The plugin simply forwards those headers to the jdk. When those headers are not passed through, the jdk code returns `407 Proxy Authentication Required`. That was one of the original reports that led us to fix the plugin.

I searched for references of `Proxy returns "HTTP/1.1 400 Bad Request` on the jdk code and there's nothing there more than a test that showcases that that's the result when the [proxy returns 400](https://github.com/openjdk/jdk/blob/master/test/jdk/sun/net/www/protocol/https/HttpsURLConnection/B6226610.java#L162). You could confirm that your proxy is returning 400 by using that [jdk test](https://github.com/openjdk/jdk/blob/master/test/jdk/sun/net/www/protocol/https/HttpsURLConnection/B6226610.java#L45).

**Comment by wlnirvana** [comment] 2021-02-20 03:01
@felipefzdz Problem resolved. There was indeed something wrong previously with my proxy.

**Comment by ljacomet** [comment] 2021-07-06 08:46
Closing as this has been resolved by fixing the issue in the scan plugin and in proxy configuration.

**Closed by ljacomet** 2021-07-06 08:46 UTC
Labels: a:bug, in:build-scan
