### ISSUE TITLE
Project.buildscript.dependencyHandler should support ID based and Version Catalog aliased plugins

### ISSUE THREAD

**Issue by jdochez** [gradle/gradle#26435] opened 2023-09-19 17:21 UTC
### Current Behavior

To add plugins dynamically to a project's buildscript classpath, one can do 

```
project.buildscript.dependencyHandler.add(
     CLASSPATH_CONFIGURATION,
     "com.foo:bar:1.0.0"
)
```

However, this only work for published plugins and there is no easy way to inject a Plugin using an id (with the marker file) or a version catalog alias. 

### Expected Behavior

The current API is too restrictive and should support all possible ways of specifying a plugin. 

In particular, we should support things like : 

settings.gradle : 
```
pluginManagement { 
    includeBuild("build-logic")
}
```

build-logic has plugins with the id : "com.foo.plugin"

I should be able to do : 

project.buildscript.dependencyHandler.add(
   CLASSPATH_CONFIGURATION, 
  "id: com.foo.plugin"
)

there are other possible resolution using different APIs, this is just a suggestion.

### Steps to Reproduce

Try to use 

```
project.buildscript.dependencyHandler.add(
     CLASSPATH_CONFIGURATION,
     "com.foo:bar:1.0.0"
)
```

with a plugin id from included builds or a version catalog reference.

### Gradle version

8.3

**Comment by ov7a** [comment] 2023-09-20 12:59
Thank you for your interest in Gradle!

Could you please provide more details about your use case and what are you trying to achieve?

**Comment by eskatos** [comment] 2023-09-25 08:33
@jdochez, could please take a look?

**Comment by jdochez** [comment] 2023-09-25 15:30
I am trying to add included build plugins to the buildscript classpath, basically instead of relying on a published plugin, and do something like this : 

```
project.buildscript.dependencyHandler.add(
     CLASSPATH_CONFIGURATION,
     "com.foo:bar:1.0.0" <---- this has to be a published plugin
)
```
In a project where there is a 'build-logic' module (indentified in settings.gradle),
I want to do : 

```
project.buildscript.dependencyHandler.add(
     CLASSPATH_CONFIGURATION,
     "id: com.foo.bar"
)
```

where the id can be identified by a plugin marker file present in the 'build-logic' included build : 
META-INF/gradle-plugins/com.foo.bar.properties 

let me know if something is unclear.

**Comment by jdochez** [comment] 2023-09-25 15:34
I also think you should support the case : 
```
project.buildscript.dependencyHandler.add(
     CLASSPATH_CONFIGURATION,
     "alias: lib.plugins.com.foo.bar"
)
```

where the alias is defined in a version catalog.

**Comment by jbartok** [comment] 2023-09-27 12:37
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/18620

Please add your use case and 👍 to that issue.

***

See also: https://github.com/gradle/gradle/issues/17963

Regarding the use of Version Catalog entries, if you use the `DependencyHandler`, you can't use `add`; you have to use either `addProvider` or `addProviderConvertible`.

**Closed by jbartok** 2023-09-27 12:37 UTC
Labels: a:bug, to-triage
