### ISSUE TITLE
CopySpec.filter scope is not intuitive

### ISSUE THREAD

**Issue by AlexeyTsvetkov** [gradle/gradle#28799] opened 2024-04-12 10:24 UTC
### Current Behavior

In copy action or copy task it is possible to define multiple "from" specs:
```
copy {
    into(dest)
    from(src1)
    from(src2)
}
```
The documentation says that `CopySpec#from`:
```
Specifies the source files or directories for a copy and creates a child CopySpec
```
So intuitively it feels like in the following case:
```
copy {
    into(dest)
    from(src1)
    from(src2).filter { it.replace(...) }
}
```
The filter should only be applied to files copied from `src2`.
However, that's not the case. In reality the filter is applied to all copied files.

### Expected Behavior

The filter should only be applied to files copied from the child copy spec.

### Steps to Reproduce

Run `./gradlew copyData` with the following `build.gradle.kts` script:
```
val inputDir1 = project.layout.buildDirectory.dir("inputDir1")
val inputDir2 = project.layout.buildDirectory.dir("inputDir2")
val finalDir = project.layout.buildDirectory.dir("finalDir")

val createInitialData = tasks.register("createInitialData") {
    doFirst {
        val dir1 = inputDir1.get().asFile
        dir1.mkdirs()
        dir1.resolve("file1.txt").writeText(
            """
                file1.txt
                ##TEST_PLACEHOLDER##
            """.trimIndent()
        )
        val dir2 = inputDir2.get().asFile
        dir2.mkdirs()
        dir2.resolve("file2.txt").writeText(
            """
                file2.txt
                ##TEST_PLACEHOLDER##
            """.trimIndent()
        )
    }
}

tasks.register("copyData") {
    dependsOn(createInitialData)
    doFirst {
        delete(finalDir)
        copy {
            into(finalDir)
            from(inputDir1)
            from(inputDir2).filter {
                it.replace("##TEST_PLACEHOLDER##", "REPLACED")
            }
        }
    }
}
```

Check `file1.txt` and `file2.txt` from `build/finalDir/`.
`##TEST_PLACEHOLDER##` is replaced in both files.

### Gradle version

8.4

**Comment by ov7a** [comment] 2024-04-15 08:35
This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/27220

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

**Closed by ov7a** 2024-04-15 08:35 UTC
Labels: a:bug, to-triage
