### ISSUE TITLE
Introduce a consistent set of convention plugins for developing build logic in Java, Groovy and Kotlin

### ISSUE THREAD

**Issue by rieske** [gradle/gradle#14072] opened 2020-08-10 05:18 UTC

**Comment by big-guy** [comment] 2020-09-08 13:13
`java-gradle-plugin`
`groovy-gradle-plugin`
`kotlin-dsl` -> `kotlin-gradle-plugin`?

Should be able to apply the Kotlin plugin in Groovy scripts too.

**Comment by bamboo** [comment] 2020-09-14 12:29
_Kotlin Gradle plugin_ is how the Kotlin team [refers to their Kotlin Gradle plugin](https://kotlinlang.org/docs/reference/using-gradle.html). Using the same term here would be confusing.

**Comment by jjohannes** [comment] 2020-11-20 10:17
Duplicate of #15219

**Closed** 2020-11-20 10:18 UTC
Labels: @idiomatic, closed:duplicate, from:member
