### ISSUE TITLE
Clean API for discovering IDE

### ISSUE THREAD

**Issue by yschimke** [gradle/gradle#15662] opened 2020-12-28 11:20 UTC
Some exotic build configurations are effectively unworkable in IDEs.  For example, having an Android test launcher that also builds test paths from other modules.

Having a clean API to detect when running in an IDE and make decisions would help. 

### Expected Behavior

Either support an API, or publish clear documentation on the System properties to reliably detect IDE.

### Current Behavior

https://github.com/square/okio/commit/f14edb72f70b7e0be51dab444e1f2a2c0d1b4fa3

andrdoi-test.gradle

```
 def isIDE = properties.containsKey('android.injected.invoked.from.ide') ||
   (System.getenv("XPC_SERVICE_NAME") ?: "").contains("intellij") ||
   System.getenv("IDEA_INITIAL_DIRECTORY") != null
...
  if (!isIDE) {
     sourceSets {
       named("androidTest") {
         it.java.srcDirs += [
           project.file("../okio-testing/src/commonMain/kotlin"),
           project.file("../okio/src/commonMain/kotlin"),
           project.file("../okio/src/commonTest/java"),
           project.file("../okio/src/commonTest/kotlin"),
           project.file("../okio/src/hashFunctions/kotlin"),
           project.file("../okio/src/jvmMain/kotlin"),
           project.file("../okio/src/jvmTest/java"),
           project.file("../okio/src/jvmTest/kotlin"),
         ]
       }
     }
   }
```

settings.gradle

```
// The Android test module doesn't work in IntelliJ. Use Android Studio or the command line.
 if (properties.containsKey('android.injected.invoked.from.ide') ||
   System.getenv('ANDROID_SDK_ROOT') != null) {
   include ':android-test'
 }
```

**Comment by mlopatkin** [comment] 2021-07-14 16:18
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of #17275. Please see the reasoning there.

**Closed by mlopatkin** 2021-07-14 16:18 UTC
Labels: a:feature, to-triage
