### ISSUE TITLE
Empty changed path is sent from watcher to Java side on Windows

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#12485] opened 2020-03-10 09:31 UTC
After upgrading to a native platform snapshot which includes https://github.com/gradle/native-platform/pull/130, the timeouts are gone though now there are `StringIndexOutOfBoundsException`s on Windows:
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
	at java.base/java.lang.String.charAt(String.java:711)
	at org.gradle.internal.snapshot.VfsRelativePath.normalizeRoot(VfsRelativePath.java:63)
	at org.gradle.internal.snapshot.VfsRelativePath.of(VfsRelativePath.java:50)
	at org.gradle.internal.vfs.impl.DefaultSnapshotHierarchy.invalidate(DefaultSnapshotHierarchy.java:78)
	at org.gradle.internal.vfs.impl.DefaultVirtualFileSystem.lambda$update$18(DefaultVirtualFileSystem.java:169)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
	at org.gradle.internal.vfs.impl.DefaultVirtualFileSystem.update(DefaultVirtualFileSystem.java:166)
	at org.gradle.internal.vfs.impl.AbstractDelegatingVirtualFileSystem.update(AbstractDelegatingVirtualFileSystem.java:52)
	at org.gradle.internal.vfs.impl.DefaultWatchingVirtualFileSystem.update(DefaultWatchingVirtualFileSystem.java:36)
	at org.gradle.internal.vfs.impl.DefaultWatchingVirtualFileSystem$1.handleChange(DefaultWatchingVirtualFileSystem.java:65)
	at org.gradle.internal.vfs.AbstractEventDrivenFileWatcherRegistry.handleEvent(AbstractEventDrivenFileWatcherRegistry.java:76)
	at org.gradle.internal.vfs.AbstractEventDrivenFileWatcherRegistry.access$000(AbstractEventDrivenFileWatcherRegistry.java:38)
	at org.gradle.internal.vfs.AbstractEventDrivenFileWatcherRegistry$1.pathChanged(AbstractEventDrivenFileWatcherRegistry.java:54)
	at net.rubygrapefruit.platform.internal.jni.AbstractFileEventFunctions$NativeFileWatcherCallback.pathChanged(AbstractFileEventFunctions.java:23)
```

After receiving the exception, the daemon also seems to crash:
```
The message received from the daemon indicates that the daemon has disappeared.
```

See https://e.grdev.net/s/lcs2xzumrh7uy/tests/6utchinnfsma6-c26hgo5wdfzkm.

---
cc: @gradle/build-cache

**Comment by wolfs** [comment] 2020-03-10 09:33
I did re-run one of the failing test builds ([languageJava_2](https://builds.gradle.org/viewLog.html?buildId=32345608&buildTypeId=Gradle_Check_VfsRetention_30_bucket20)), and the index out of bound exception appeared again, though in a flaky way: https://e.grdev.net/s/lqcas63slcfbm/tests/csvulcw5ltbii-wak3m2s7di6ie

**Comment by wolfs** [comment] 2020-03-10 09:35
This is the build of the VFS retention tests on Windows, which shows errors like the above all over the place: https://builds.gradle.org/viewLog.html?buildId=32345639&tab=buildResultsDiv&buildTypeId=Gradle_Check_VfsRetention_30_Trigger&branch_Gradle_Check_Stage_ExperimentalVFSRetention=wolfs%2Fvfs%2Fclose-fh-windows

And this is the build I did re-run: https://builds.gradle.org/buildConfiguration/Gradle_Check_VfsRetention_30_bucket20/32345608?mode=builds

**Comment by lptr** [comment] 2020-03-10 11:48
I don't yet understand how the changes in https://github.com/gradle/native-platform/pull/130 can introduce the empty changed path. What's even more worrying is I also don't understand how it can cause a crash.

One idea is that we process the string with the wrong encoding, and in some cases it causes an empty string (`\0` first character due to the LE/BE difference), and in other cases causes a crash.

Another potential problem is that we end up receiving events after the `WatchPoint` has been destructed. This could maybe explain the empty string as well as the crash.

What I find strange is that we can't see the debug logs anywhere. Those could indicate how the `WatchPoint` objects are closed/destructed/removed, and if there was any issue with the ordering.

**Comment by lptr** [comment] 2020-03-10 12:56
Seems like if everything is working as intended, I see one place where we could end up with an empty string, and it looks like we are not handling it properly:

https://github.com/gradle/native-platform/blob/master/src/file-events/cpp/win_fsnotifier.cpp#L168-L175

```cpp
void Server::handleEvent(JNIEnv* env, const u16string& path, FILE_NOTIFY_INFORMATION* info) {
    wstring changedPathW = wstring(info->FileName, 0, info->FileNameLength / sizeof(wchar_t));
    u16string changedPath(changedPathW.begin(), changedPathW.end());
    // TODO Do we ever get an empty path?
    if (!changedPath.empty()) {
        changedPath.insert(0, 1, u'\\');
        changedPath.insert(0, path);
    }
```

It looks logical that a notification _could_ come in with an empty `FileName`, i.e. when the notification is about the watched directory itself. In that case we currently pass an empty string to Java, whereas we should pass the path of the `WatchPoint`.

What I don't understand is why we get these events now, and not before. Nothing should have changed about the events we get, so..?

Anyway, I'll fix the handling of this case.

**Comment by lptr** [comment] 2020-03-11 10:23
Should be handled by this: https://github.com/gradle/native-platform/pull/132 (merged).

**Comment by wolfs** [comment] 2020-03-12 08:16
This happens in the soak test as well: https://builds.gradle.org/viewLog.html?buildId=32445003&buildTypeId=Gradle_Check_Soak_9_0

**Closed** 2020-03-17 09:24 UTC
Labels: @build-cache, a:bug, from:member
