### ISSUE TITLE
cannot select version

### ISSUE THREAD

**Issue by iptton** [gradle/gradle#28646] opened 2024-04-01 09:14 UTC
### Issue type

Styling or Accessibility

### Problem description

mouse over the version, it will disappear

![gradle-page-issue](https://github.com/gradle/gradle/assets/97447/f9d91453-310a-4d5f-b71c-d29359534077)

### Page with the problem

https://docs.gradle.org/current/userguide/userguide.html

**Comment by ov7a** [comment] 2024-04-01 09:22
This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/24864

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

See the second comment
* https://github.com/gradle/gradle/issues/24864#issuecomment-1841126425

**Closed** 2024-04-01 14:42 UTC
Labels: closed:duplicate, to-triage
