### ISSUE TITLE
maybe add an operator overloading for Property#set for kotlin-dsl

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#9147] opened 2019-04-16 22:22 UTC
Currently if some plugin chooses to use the property/provider mechanism (which is the proper way to do lazy binding currently, right?) you always have to set it like `draft.set(true)`.
This is imho a bit ugly and certainly uglier than necessary.
The plugin author can of course add a `draft(boolean draft)` method that does `this.draft.set(draft)`, but the kotlin-dsl could easily enable either this syntax or some other operator generically for all properties like

```java
operator fun <T> Property<T>.remAssign(value: T) = set(value)
operator fun <T> Property<T>.divAssign(value: T) = set(value)
operator fun <T> Property<T>.timesAssign(value: T) = set(value)
operator fun <T> Property<T>.invoke(value: T) = set(value)

tasks.githubPublish {
    prerelease.set(true)
    repositoryName %= githubRepositoryName
    tagName /= releaseTagName
    releaseName *= releaseTagName
    draft(true)
}
```

**Comment by eskatos** [comment] 2019-04-25 16:10
Related to #9268

**Comment by Vampire** [comment] 2019-04-25 16:42
@eskatos is this just releated, not a duplicate? :-)

**Comment by eskatos** [comment] 2019-04-25 16:53
@Vampire I wasn't sure yet, but your recent comment there made it clear :) closing as a duplicate of #9268

**Closed by eskatos** 2019-04-25 16:53 UTC
Labels: a:feature, from:contributor, in:kotlin-dsl
