### ISSUE TITLE
Parallel resolution of artifacts

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1309] opened 2017-02-03 00:08 UTC
Original issue: https://issues.gradle.org/browse/GRADLE-2582

[The feature is already speced out.](https://github.com/gradle/gradle/tree/master/design-docs/features/faster-builds/faster-remote-dependencies)

### Expected Behavior

Dependencies are resolved and downloaded in parallel which should result in a significantly better build performance for large enterprise builds.

### Current Behavior

Gradle resolves dependencies serially, which can be time consuming if the repository is slow.

**Comment by oehme** [comment] 2017-04-08 11:20
This has been merged to master

**Closed by oehme** 2017-04-08 11:20 UTC
Labels: a:feature, affects-version:3.4, from:contributor, in:dependency-management

**Comment by ben-manes** [comment] 2017-04-08 15:14
Is parallel metadata resolution planned? That would greatly improve performance of the versions plugin (dependency updates) which was one of the reasons I opened the original ticket.

P.S. Thanks for tackling this.

**Comment by oehme** [comment] 2017-04-08 15:42
Yes parallel metadata resolution is in progress.

**Comment by gocursor** [comment] 2017-04-27 22:53
The issue is marked "Closed". Is this feature already in the latest release (3.5)? If yes: how can I turn it on? With --parallel?

**Comment by bigdaz** [comment] 2017-04-27 23:18
You'll see this issue has the Milestone set to `4.0 RC1`. That means the feature will be first available in Gradle 4.0. Expect to see the first release candidate in the next couple of weeks.

**Comment by ben-manes** [comment] 2017-06-07 19:21
@bigdaz 

I don't see the improvement in 4.0-rc-2 when running the [gradle-versions-plugin](https://github.com/ben-manes/gradle-versions-plugin). The plugin to shows possible updates by querying with a dynamic version to build its report.  For example using `gradle dependencyUpdates --refresh-dependencies` (to force not hitting the cache) executed in 3m 15s on one of my projects.

The release notes say that the resolution is now run in parallel with support for both the artifact and metadata. So this should be quick, but appears to behave the same as the sequential resolution in 3.5.

**Comment by bigdaz** [comment] 2017-06-07 19:53
Thanks for trying out the RC, @ben-manes. Since your plugin does a bunch of funky stuff with configurations, it would be useful to know where most of the time is being spent. You might want to add some timing to see, or even running up your build with https://github.com/gradle/gradle-profiler

**Comment by adammurdoch** [comment] 2017-06-07 20:19
The release notes aren't entirely correct. Gradle only downloads metadata in parallel during resolution of the dependency graph. It still does version selection sequentially, and this will include the network requests to determine the versions that are available to match a particular dynamic version. So in your case I would expect everything to still happen sequentially. This is something we will improve later.

**Comment by ben-manes** [comment] 2017-06-07 21:47
There isn't really much complexity in the configuration hacking ([Resolver](https://github.com/ben-manes/gradle-versions-plugin/blob/master/src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy)). Its mostly a normal resolution with version munging, cloning configurations to not modify the build, backwards compatibility when `latest.x` was the only Gradle option, and resolution rules support. I'm pretty sure the approach came from a random comment @adammurdoch made once.

Here is the [profile-out.zip](https://github.com/gradle/gradle/files/1059401/profile-out.zip) results. My guess is that the time is spent on `Configuration#getFirstLevelModuleDependencies()` since there's not much plugin work. Of course once the Gradle cache is warmed the subsequent calls are speedy.

If this is to be expected and can be improved later, then that's great. Ideally we'd roll this feature directly into Gradle someday.
