### ISSUE TITLE
Failure when using dependency verification with a composite build

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#11999] opened 2020-01-24 12:45 UTC
I am trying to use composite build to develop [native-platform](https://github.com/adammurdoch/native-platform) and [gradle/gradle](https://github.com/gradle/gradle) together.

### Expected Behavior
The build works and dependency verification for composite build dependencies is disabled.

### Current Behavior
The build fails with
```
Multiple entries with same key: b801e2f8ef035068ec1139cc29579f18fa8fd93b=org.gradle.api.internal.artifacts.verification.verifier.SignatureVerificationFailure$SignatureError@59628339 and b801e2f8ef035068ec1139cc29579f18fa8fd93b=org.gradle.api.internal.artifacts.verification.verifier.SignatureVerificationFailure$SignatureError@17719dd3
> Multiple entries with same key: b801e2f8ef035068ec1139cc29579f18fa8fd93b=org.gradle.api.internal.artifacts.verification.verifier.SignatureVerificationFailure$SignatureError@59628339 and b801e2f8ef035068ec1139cc29579f18fa8fd93b=org.gradle.api.internal.artifacts.verification.verifier.SignatureVerificationFailure$SignatureError@17719dd3
```

### Context
See https://e.grdev.net/s/tnoavsoiwoeok/failure?openFailures=WzBd&openStackTraces=WzIsMF0#top=0

### Steps to Reproduce 
Run `./gradlew --include-build ../native-platform help` on `gradle/gradle`, including `native-platform`.

### Your Environment
Build scan URL: https://e.grdev.net/s/tnoavsoiwoeok/failure?openFailures=WzBd&openStackTraces=WzIsMF0#top=0

**Comment by melix** [comment] 2020-01-24 16:20
Are you using an old branch? I can't reproduce using `master`.

**Comment by melix** [comment] 2020-01-24 16:21
Here's a scan using the command you pasted above: https://gradle.com/s/bkw3wfsmeufw6

It fails, but because `native-platform` doesn't support building on JDK 11, which is a different issue (and you will probably not be able to use a composite build because of this)

**Comment by wolfs** [comment] 2020-01-24 16:39
I removed the restriction from `native-platform`, and I set the source compatibility to Java 6, so the composite can work. Looks like now I am getting a different error: https://e.grdev.net/s/v5rp5qtrgb5wi/failure?openFailures=WzBd&openStackTraces=WzFd#top=0

Note that I am using the changes from https://github.com/gradle/gradle/pull/12001, maybe the problem with selecting the right variant caused the error.

**Comment by ljacomet** [comment] 2020-01-27 09:38
Closing as this cannot be reproduced as-is. Please re-open an issue if you face the problem again

**Comment by wolfs** [comment] 2020-01-27 16:18
Looks like I am facing the issue again :(
See https://e.grdev.net/s/wptfhs7bpkhqu

I am using the `master` branch of `gradle/gradle` and the https://github.com/adammurdoch/native-platform/pull/68 branch of `native-platform`.

**Comment by melix** [comment] 2020-01-27 16:59
This time I could reproduce, will let you know :+1:

**Comment by melix** [comment] 2020-01-27 19:25
So this pb is actually unrelated to composite builds. It seems to happen whenever a keyring contains the same key twice. I'm unsure in which conditions this can happen, but since it's simple to bake custom keyrings, this could very well happen on other builds. The easy fix is just not to use an `ImmutableMap` here (because unfortunately `PGPPublicKey` is not comparable).

**Closed** 2020-01-28 12:09 UTC
Labels: a:bug, from:member, in:dependency-management

**Comment by wolfs** [comment] 2020-01-30 12:30
@melix Why is the duplicate key there in the first place? Is the same verification file picked up twice?

**Comment by melix** [comment] 2020-01-30 12:33
As the commit message explains it's possible that a public keyring contains the same key multiple times.

**Comment by wolfs** [comment] 2020-01-30 12:46
What I don't understand why validation doesn't fail when I am not using the composite build and it fails when I use the composite build.

**Comment by melix** [comment] 2020-01-30 12:56
Dependency verification applies to the included build. So a dependency of the included build is verified, and requires signature verification. In this case the artifact we verify causes the verification of the same key twice.
