### ISSUE TITLE
Introduce `maybeRegister` to register task if not already

### ISSUE THREAD

**Issue by tasomaniac** [gradle/gradle#8106] opened 2018-12-22 06:11 UTC
### Context

Just like maybeCreate, this could be useful for task configuration avoidance to add maybeRegister.

During plugin configuration, there are cases where we are not sure if a task is there or not. Since `named` is kind of lazy, there is no good way to check if there is a task already created and register if not. One way to do this is to catch `UnknownDomainObjectException` which is not so pretty. 

Adding maybeRegister would be really beneficial in cases where we want to create the task conditionally and also configure them lazily.

**Comment by big-guy** [comment] 2018-12-22 18:51
Dupe of https://github.com/gradle/gradle/issues/6243 

If you can provide an example of where this is useful on the issue above, we're happy to take a look.

**Closed by big-guy** 2018-12-22 18:51 UTC

**Comment by big-guy** [comment] 2018-12-22 21:14
I don't see where they're "not lazy any more".  Can you point me to the line?
