### ISSUE TITLE
Annoying "To honour the JVM settings for this build a new JVM will be forked" message 

### ISSUE THREAD

**Issue by sharkman** [gradle/gradle#29307] opened 2024-05-25 15:27 UTC
### Current Behavior

If the user provided `org.gradle.daemon=false` property or `--no-daemon` flag gradle displays the annoying and misleading message:
```
To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.6/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
Daemon will be stopped at the end of the build
```

Following the documentation does not disable the message, just increases confusion.

### Expected Behavior

If the user provided the `org.gradle.daemon=false` property or the `--no-daemon` flag gradle must not start any daemon in any circumstances. That's what uses is asked for. Disregard any JVM flags mismatch.
If you really really want to warn the user about JVM flags mismatch, instead of a generic and misleading RTFM message directly tell user what flags they should set and why (you have the flags anyway, why not show that to the user?).
The user may not know why they should do any of this, since the user did not set _any_ JVM flags at all (the usual case, btw) and the JVM flags mismatch is caused by gradle itself.

### Steps to Reproduce

-

### Gradle version

8.6

**Comment by sharkman** [comment] 2024-05-25 15:27
continuation of #11517

**Comment by ljacomet** [comment] 2024-05-30 12:21
This issue will be closed as a duplicate of

* #16110

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

Note that we added a comment on that other issue following your report.

**Closed by ljacomet** 2024-05-30 12:21 UTC
Labels: in:daemon, a:bug
