### ISSUE TITLE
configuration cache not reusable when build directory removed by clean task

### ISSUE THREAD

**Issue by tnielens** [gradle/gradle#30476] opened 2024-09-10 14:01 UTC
### Current Behavior

When `clean` is run as part of a multi task gradle command, the configuration cache is not reusable. Relevant log line is `Calculating task graph as configuration cache cannot be reused because directory '.' has changed.`.

### Expected Behavior

The configuration cache should support the `clean` task.

### Context (optional)

This seems to be due to the clean task and the removal of the `build` directory. This modifies the root directory which is an input to the `plugin class 'com.restore.gradle.HelpPlugin'` according to the configuration cache report.

### Self-contained Reproducer Project

Run `./gradlew clean compileJava --configuration-cache` on your favorite java project.

### Gradle version

8.10.1

**Comment by ljacomet** [comment] 2024-09-11 08:37
Most probably your issue is caused by an external Gradle plugin, which cannot be addressed in the Gradle Build Tool project. We cannot just move the issue.

We recommend you open an issue on its issue tracker.

We have some integration tests with major plugins to catch potential problems early, but we don't have the capacity to cover all plugins available.

If you think you have come across a Gradle bug, please provide a reproducer project for this issue without the plugin, and we’ll consider reopening it.


***

Running `./gradlew clean compileJava --configuration-cache` on a project that does not have a task using the project directory as an input works fine.

As you stated, this is caused by `com.restore.gradle.HelpPlugin` and not something to be fixed in Gradle.

**Closed by ljacomet** 2024-09-11 08:37 UTC
Labels: a:bug, to-triage

**Comment by tnielens** [comment] 2024-09-11 11:10
Right, I misread the HelpPlugin namespace which is indeed ours and not gradle's. Thank you for handling the issue.

**Comment by matejdro** [comment] 2025-09-09 10:49
How would one find out which plugin causes this? We also experience this warning sporadically.
