### ISSUE TITLE
support test fixtures per test suite

### ISSUE THREAD

**Issue by dgeissl** [gradle/gradle#29359] opened 2024-05-30 09:35 UTC
### Expected Behavior

I'd like the java-test-fixtures plugin to be able to create test fixtures for different kinds of test suites.
e.g. have a testFixture for unit tests and a integrationTestFixture for a integrationTest test suite.

```groovy
testFixtures {
    suites = ['test', 'integrationTest']
}
````
resulting in an `integrationTestFixture` configuration, source set and the output will automatically be added to the `integrationTestImplementation` configuration.

Syntactically it's probably challenging to come up with a proper syntax to use those fixtures as dependencies in other projects, but anyways I think its rather usual that you'll have different fixtures for your integration and unit tests.
```groovy
dependencies {
    integrationTestImplementation testFixture(':otherProject','integrationTest')
}
```

### Current Behavior (optional)

the java-test-fixtures plugin creates test fixtures in the way mentioned for the unit test suite only and it's not able to be configured otherwise.

### Context

We have a lot of projects that have both, unit tests and integration tests. They differ heavily in structure and dependencies but we often want to share some common classes between projects.

Currently we can share common unit test implementations via testFixtures, but for integration tests we have to either depend on all integration tests (and the fixtures are implemented directly in the integration test source set) or we have to setup a separate project to share common implementations separately.

**Comment by ljacomet** [comment] 2024-06-03 09:02
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by big-guy** [comment] 2024-06-03 17:03
This is similar to our existing feature variants (test fixtures is built on top of this already). I'm going to close this as a dupe of https://github.com/gradle/gradle/issues/25629

**Closed by big-guy** 2024-06-03 17:03 UTC
Labels: a:feature, in:java-plugins, in:test-suites, :wave: team-triage

**Comment by dgeissl** [comment] 2024-12-18 09:17
@big-guy as I understand it, the mentioned #25629 provides the necessary implementation for the consumer. But then we'll still have to deal with configuring the SourceSets add dependencies for the Tasks and classpaths and probably more.

Wouldn't a convenient implementation still be useful? And I don't see it covered by the referenced issue.
