### ISSUE TITLE
Stop printing "Encryption of the configuration cache is enabled." at warn level

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#25543] opened 2023-06-28 16:47 UTC
### Expected Behavior

There is no message about `Encryption of the configuration cache is enabled.` as it has little use to developers.

### Current Behavior

`Encryption of the configuration cache is enabled.` is logged at warn level

### Steps to Reproduce

Use Gradle 8.1+ and enable configuration caching.

### Gradle version

8.1

**Comment by ov7a** [comment] 2023-07-03 08:27
Thank you for providing a valid description.

The issue is in the backlog of the relevant team and is prioritized by them.

Related:
* #24248

**Comment by bamboo** [comment] 2023-07-24 19:02
Fixed in 9a65f0542b83dc7f94d09fd1f50a34e31cda6481

**Closed by bamboo** 2023-07-24 19:02 UTC
Labels: a:bug, in:configuration-cache
