### ISSUE TITLE
Incorrect dependency cycle with include-builds with modules

### ISSUE THREAD

**Issue by meonlol** [gradle/gradle#6229] opened 2018-08-07 15:47 UTC
In our system have multiple projects, with each project containing multiple modules, that together are packaged into a distribution via a single 'root' project. Something like this:

```
▾ team1/
  ▸ team1-api/
  ▸ team1-bl/
▾ team2/
  ▸ team2-api/
  ▸ team2-bl/
root
```

Now we have a problem with non-cyclical dependencies causing build failures.

### Expected Behavior

We expected that, as we have separated api and business logic, that we can depend on any api-module in any bl-modules, as long as we don't create a cyclical dependency between the individual modules.

### Current Behavior

However, we have an unexpected error when we define the dependencies in the respective build.gradle files like below. When we build both `team1` and `team2` projects including the other, it all works fine. But when we add a dependency on each `-bl` project under the `root` project we get an error claiming cyclical dependencies.

```
▾ team1/
  ▸ team1-api/
  ▸ team1-bl/
    build.gradle
    >   dependencies {
    >     api project(":team1-api")
    >     implementation("org.sample:team2-api")
    >   }
▾ team2/
  ▸ team2-api/
  ▸ team2-bl/
    build.gradle
    >   dependencies {
    >     api project(":team2-api")
    >     implementation("org.sample:team1-api")
    >   }
root
  build.gradle
  >   dependencies {
  >     implementation("org.sample:team1-bl")   // Causes 'dependency cycle' failure
  >     implementation("org.sample:team2-bl")   // Causes 'dependency cycle' failure
  >   }
```

```
FAILURE: Build failed with an exception.

* What went wrong:
Included build dependency cycle: build 'team1' -> build 'team2' -> build 'team1'
```

### Context

If we reference the api modules under root, it will work without a cycle failure, but as our root project builds a distribution, it has to depend on all implementation modules as well.

### Steps to Reproduce

See example project:

https://github.com/meonlol/bug-gradle-include-dependency-cycle

And run `./gradlew build` from the `root` project (`includeBuild`s are in `root/settings.gradle`).

**Comment by meonlol** [comment] 2018-08-30 09:31
Tested with 4.10. The bug sadly still persists.

**Comment by big-guy** [comment] 2019-02-14 05:32
@adammurdoch I can reproduce this with a 5.3-nightly. https://scans.gradle.com/s/bqjwd7q3g7y44/failure?openFailures=WzBd#top=0

We configure the root build, then team1 build and then team2 build. We then re-enter the team1 build (due to the dependency between team2 and team1) and fail.

I suppose the workaround is to forward declare the potential substitutions from one of the builds.

**Comment by SergejIsbrecht** [comment] 2019-07-26 09:04
@big-guy , what do you mean by "forward declare the potential substitutions from one of the builds". Could you please give an example, how you would solve it in given case? Thanks

**Comment by meonlol** [comment] 2019-11-06 15:51
I can still reproduce this in 5.4, but I figured out a [workaround that seems to work as intended](https://github.com/meonlol/bug-gradle-include-dependency-cycle/tree/workaround).

Basically, every api module is treated as a separate project and included in the repo's settings. Gradle then performs an `includeBuild()` from the `--include-build`. It's not ideal, but it appears to work.

**Comment by lhotari** [comment] 2020-03-04 08:14
I came across a problem with composite builds that might be related to this issue. What seems to happen is that with composite builds and dependency substitution, all "implementation" configuration dependencies become transitive dependencies. The expectation is that only the "api" configuration is transitive. This is happening in my case with Gradle 6.1.1

**Comment by Vampire** [comment] 2020-10-30 15:15
Is this fixed now with #14950 being merged?

**Comment by jjohannes** [comment] 2020-10-30 16:13
There are still some edge case. But most things should work with the next 6.8 nightly. We'll give an update here once everything is in.

**Comment by jjohannes** [comment] 2020-11-20 10:53
The cycle detection between tasks of composite builds has been reworked for 6.8. The case reported in this issue, and others, are fixed.

**Closed by jjohannes** 2020-11-20 10:53 UTC
Labels: @idiomatic, a:bug, from:contributor, in:composite-builds
