### ISSUE TITLE
When local maven cache has a pom file and unclassified jar present, gradle cannot find a classifier jar

### ISSUE THREAD

**Issue by jeremydyoung** [gradle/gradle#23169] opened 2022-12-15 03:25 UTC
### Expected Behavior
When maven local cache has a pom file and an unclassified jar, but no classified jar, continue searching additional repositories instead of declaring that the artifact could not be found.

### Current Behavior
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find netty-transport-native-epoll-4.1.86.Final-linux-x86_64.jar (io.netty:netty-transport-native-epoll:4.1.86.Final).
     Searched in the following locations:
         file:/home/jyoung/.m2/repository/io/netty/netty-transport-native-epoll/4.1.86.Final/netty-transport-native-epoll-4.1.86.Final-linux-x86_64.jar
```

### Context
Trying to build a project with a classified jar

### Steps to Reproduce 
https://github.com/jeremydyoung/classifier-sample

`./mvnw clean install`

`./gradlew clean build`

The maven build should be successful and store the non-classified version of the netty-transport-native-epoll file in the local maven cache.

The gradle build is expected to fail if the bug is present because it will check the mavenLocal cache and find the needed pom file, but the classified jar will be missing.

The desired outcome is that gradle should choose to search additional repositories when mavenLocal is only partially complete.

A workaround is to delete the netty-transport-native-epoll folders in the mavenLocal file structure, but this is undesirable.

### Your Environment
Reproducing the error: 

https://scans.gradle.com/s/7fxf42b2ervjo

Note that the dependency is marked as resolved, but the build still fails.

When clearing the maven local cache, the following build scan happens:

https://scans.gradle.com/s/sbrwk5jyrdav6

**Comment by ljacomet** [comment] 2022-12-19 13:34
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #17144

---

There is no plan to change this behavior. See [this explanation](https://docs.gradle.org/7.6/userguide/declaring_repositories.html#sec:case-for-maven-local) in the documentation.

**Closed** 2023-06-30 12:07 UTC
Labels: closed:duplicate, in:maven-integration
