### ISSUE TITLE
Gradle not running all tests

### ISSUE THREAD

**Issue by Ankit-Laddha** [gradle/gradle#19481] opened 2022-01-04 07:59 UTC
I'm using gradle to run our kotest tests in prow job. But gradle doesn't run all the tests everytime. for e.g. if there are 3 tests A, B, C and B failed in the run. And later if the job (and hence underlying gradle command) is ran again then B is never run. Nor there is consistency on when A & C are run. And this make the prow job (under which this command is ran) to pass even though it should fail.

How do i make sure gradle runs all the tests everytime OR atleast run failing tests everytime (if somehow it is still caching that info)?
 
gradle version = 6.9
current command = ./gradlew clean --rerun-tasks test -Dkotest.tags="AB"
kotest version = 4.6.2
Gradle Build cache is disabled

### Expected Behavior

Gradle should run all the tests everytime

### Current Behavior

Gradle randomly runs only selected tests

### Context

I want to run N smoke kotest tests using gradle everytime a PR is ran. If one of the Test fails, the prow job fails and hence makes PR not mergeable.

### Steps to Reproduce 

N/A
 
### Your Environment

Build scan URL:

**Comment by donat** [comment] 2022-01-05 10:02
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

This issue will be closed after 7 days, unless you can provide more information.

**Comment by Ankit-Laddha** [comment] 2022-01-05 13:55
Hi @donat Thanks for responding.
Here is my repo you can clone: https://github.com/Ankit-Laddha/kotest-sample

Command i'm using is : `./gradlew clean --rerun-tasks test -Dkotest.tags="AB"`

On local, all the test runs fine, but on CI we see sometimes not all test are run

**Comment by Ankit-Laddha** [comment] 2022-01-06 09:49
@donat : i dont see anything in logs (even with --info flag) that could be a problem. Did you got chance to look into this? Is there anything i should do to narrow down to the problem.

**Comment by donat** [comment] 2022-01-07 08:44
I cannot reproduce the problem locally: https://scans.gradle.com/s/k2bdm2cwz5m4c/tests/
Is there a chance you can publish a build scan from a build that you suspect is problematic?
Alternatively, you could use GitHub Actions to create a reproducer. You can see a sample here: https://github.com/gradle/gradle-issue-reproducer

**Comment by Ankit-Laddha** [comment] 2022-01-10 07:25
I created here: https://github.com/Ankit-Laddha/gradle-kotest-reproducer
but i don't think i ll be able to reproduce it here. Is there some settings/configuration i can enable to get some more information about probable root cause?

**Comment by donat** [comment] 2022-01-17 15:28
I think running the tests in debug mode and checking the test execution information could provide some clues. Aside, build scans could help with the analysis.

**Comment by donat** [comment] 2022-03-22 16:48
I'm closing this as non-actionable. If you find a way to reproduce the issue later, I'm happy to continue the investigation.

**Closed by donat** 2022-03-22 16:48 UTC
Labels: a:bug, to-triage

**Comment by Yanislavcore** [comment] 2024-11-07 18:16
Recently I've run into the same problem. @Ankit-Laddha , did you manage to root cause or fix this problem?
