### ISSUE TITLE
8.1 RC1: JavaExec.jvmArgs was null

### ISSUE THREAD

**Issue by ben-manes** [gradle/gradle#24412] opened 2023-03-21 06:07 UTC
When upgrading, I received a NullPointerException on JavaExec’s `jvmArgs` instead of defaulting to an empty list, e.g. `jvmArgs += [...]`. This passed after replacing this with a loop to add items individually. Then reverting to reproduce the problem and it no longer occurs. Was this perhaps a stale cache between gradle versions?

**Comment by ben-manes** [comment] 2023-03-21 06:37
oh, I mistyped my reproducer to forget the `+=`. If it is `jvmArgs [...]` then it seems to work. Otherwise I get an error like,
```console
> Could not create task ':caffeine:generateNodes'.
   > Cannot execute null+[--add-exports, jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED, --add-exports, jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED, --add-exports, jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED, --add-exports, jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED, --add-exports, jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED, --add-exports, jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED, --add-exports, jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED, --add-exports, jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED, --add-opens, jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED, --add-opens, jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED, --add-opens, jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED]
```

**Comment by ov7a** [comment] 2023-03-21 09:52
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) can really help us track down and fix your problem. We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

We request you to provide a reproducer because we need to be sure we are looking at the exact problem you are facing.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).

This issue will be closed after 7 days unless you can provide more information.

***
Then reverting to reproduce the problem and it no longer occurs.
Can you please try to start again from a clean gradle user home and provide a reproducer with step-by-step instructions?

**Comment by abstratt** [comment] 2023-03-21 18:41
Seems related/duplicate of https://github.com/gradle/gradle/issues/24413

**Comment by abstratt** [comment] 2023-03-21 20:18
Possibly related as well: #24403

**Comment by ben-manes** [comment] 2023-03-21 21:32
For my use-cases, I switched from assignment to the method which initializes and appends (e.g. `jvmArgs(...)` instead of `jvmArgs += ...`). Ideally this wouldn't leak via assignment, but made resolving it easy. It may be that this can be closed if the upgrade notes mention the problem and workaround.

**Comment by TWiStErRob** [comment] 2023-03-21 21:36
If the behavior changed, it could affect published plugins that use the `+=` syntax, because the end user cannot really fix it simply.

**Comment by davidburstromspotify** [comment] 2023-03-21 21:58
@TWiStErRob Precisely, the Pitest plugin breaks, as one example. I haven't looked into the possibility with a workaround where one would first set the jvmArgs to an empty array. Maybe it's not feasible.

**Closed** 2023-03-22 12:37 UTC
Labels: a:regression, to-triage, pending:reproducer

**Comment by 6hundreds** [comment] 2023-03-22 17:17
@ben-manes Does `jvmArgs += [...]` worked for you before 8.1? Could you show a snippet?

**Comment by ben-manes** [comment] 2023-03-22 17:30
@6hundreds yes, you can see my gradle upgrade [commit](https://github.com/ben-manes/caffeine/commit/c8ed5e816ca56c3bb5952d2c1c93b7a5b67e16e6#diff-4d1b335a898978461fc351e4093810580d8be3d6777b0a7de0a8c679c618b347). For example,

```gradle
tasks.register('memoryOverhead', JavaExec) {
  group = 'Benchmarks'
  description = 'Evaluates cache overhead'
  classpath sourceSets.jmh.runtimeClasspath
  classpath sourceSets.codeGen.runtimeClasspath
  mainClass = 'com.github.benmanes.caffeine.cache.MemoryBenchmark'
  jvmArgs += [
    '--add-opens', 'java.base/java.util.concurrent.atomic=ALL-UNNAMED',
    '--add-opens', 'java.base/java.util.concurrent.locks=ALL-UNNAMED',
    '--add-opens', 'java.base/java.util.concurrent=ALL-UNNAMED',
    '--add-opens', 'java.base/java.lang.ref=ALL-UNNAMED',
    '--add-opens', 'java.base/java.lang=ALL-UNNAMED',
    '--add-opens', 'java.base/java.util=ALL-UNNAMED',
    "-javaagent:${configurations.javaAgent.singleFile}",
  ]
}
```
