### ISSUE TITLE
Version selection differs from Maven, but also doesn't use latest

### ISSUE THREAD

**Issue by uklance** [gradle/gradle#2212] opened 2017-05-31 08:04 UTC
When using `org.wildfly.swarm:undertow:2017.5.0` in Maven, the transitive dependency version of `io.undertow:undertow-servlet` is correctly resolved as version `1.4.11.Final`.

When using `org.wildfly.swarm:undertow:2017.5.0` in Gradle, the transitive dependency version of `io.undertow:undertow-servlet` is incorrectly resolved as version `1.2.9.Final`.

### Expected Behavior
Gradle should resolve the transitive dependency `io.undertow:undertow-servlet` to the same version as Maven

### Current Behavior
Gradle somehow resolves to an old version of `io.undertow:undertow-servlet`

### Context
https://discuss.gradle.org/t/strange-problem-of-gradle-compare-with-maven/22807/10

### Steps to Reproduce (for bugs)
1. Create a Maven `pom.xml` with the following dependencies

```
    <dependencies>
        <dependency>
            <groupId>org.wildfly.swarm</groupId>
            <artifactId>undertow</artifactId>
            <version>2017.5.0</version>
			<exclusions>
				<exclusion>
					<groupId>org.glassfish</groupId>
					<artifactId>javax.el-impl</artifactId>
				</exclusion>
			</exclusions>
        </dependency>
    </dependencies>
```

2. Run `mvn dependency:tree`

```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ bar ---
[INFO] foo:bar:jar:1.0-SNAPSHOT
[INFO] \- org.wildfly.swarm:undertow:jar:2017.5.0:compile
[INFO]    +- org.wildfly.swarm:container:jar:2017.5.0:compile
[INFO]    |  +- org.wildfly.swarm:spi:jar:2017.5.0:compile
[INFO]    |  |  +- org.jboss.shrinkwrap:shrinkwrap-api:jar:1.2.6:compile
[INFO]    |  |  +- org.jboss.shrinkwrap:shrinkwrap-impl-base:jar:1.2.6:compile
[INFO]    |  |  |  \- org.jboss.shrinkwrap:shrinkwrap-spi:jar:1.2.6:compile
[INFO]    |  |  \- org.jboss:jandex:jar:2.0.2.Final:compile
[INFO]    |  +- org.wildfly.swarm:bootstrap:jar:2017.5.0:compile
[INFO]    |  |  +- org.jboss.modules:jboss-modules:jar:1.5.2.Final:compile
[INFO]    |  |  \- org.yaml:snakeyaml:jar:1.17:compile
[INFO]    |  +- org.wildfly.swarm:config-api:jar:1.0.3.Final:compile
[INFO]    |  |  \- org.wildfly.swarm:config-api-runtime:jar:1.0.3.Final:compile
[INFO]    |  \- org.jboss.logging:jboss-logging:jar:3.3.0.Final:compile
[INFO]    +- org.wildfly.swarm:io:jar:2017.5.0:compile
[INFO]    +- org.wildfly.swarm:logging:jar:2017.5.0:compile
[INFO]    +- org.wildfly.swarm:ee:jar:2017.5.0:compile
[INFO]    |  +- org.wildfly.swarm:naming:jar:2017.5.0:compile
[INFO]    |  +- org.jboss.spec.javax.enterprise.concurrent:jboss-concurrency-api_1.0_spec:jar:1.0.0.Final:compile
[INFO]    |  +- org.jboss.spec.javax.interceptor:jboss-interceptors-api_1.2_spec:jar:1.0.0.Final:compile
[INFO]    |  \- org.jboss.spec.javax.el:jboss-el-api_3.0_spec:jar:1.0.7.Final:compile
[INFO]    +- org.wildfly.swarm:request-controller:jar:2017.5.0:compile
[INFO]    +- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-api-jboss:jar:2.0.0-alpha-9:compile
[INFO]    +- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-impl-jboss:jar:2.0.0-alpha-9:compile
[INFO]    +- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-api-javaee:jar:2.0.0-alpha-9:compile
[INFO]    |  \- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-api-base:jar:2.0.0-alpha-9:compile
[INFO]    +- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-impl-javaee:jar:2.0.0-alpha-9:compile
[INFO]    |  \- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-impl-base:jar:2.0.0-alpha-9:compile
[INFO]    |     \- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-spi:jar:2.0.0-alpha-9:compile
[INFO]    +- org.ow2.asm:asm-all:jar:5.0.4:compile
[INFO]    +- org.jboss.spec.javax.servlet:jboss-servlet-api_3.1_spec:jar:1.0.0.Final:compile
[INFO]    +- org.jboss.spec.javax.websocket:jboss-websocket-api_1.1_spec:jar:1.1.1.Final:compile
[INFO]    +- io.undertow:undertow-servlet:jar:1.4.11.Final:compile
[INFO]    |  +- io.undertow:undertow-core:jar:1.4.11.Final:compile
[INFO]    |  |  +- org.jboss.xnio:xnio-api:jar:3.3.6.Final:compile
[INFO]    |  |  \- org.jboss.xnio:xnio-nio:jar:3.3.6.Final:runtime
[INFO]    |  \- org.jboss.spec.javax.annotation:jboss-annotations-api_1.2_spec:jar:1.0.0.Final:compile
[INFO]    \- org.wildfly.swarm:meta-spi:jar:2017.5.0:compile
```

3. Create a `build.gradle` with the following dependency

```
dependencies {
	compile("org.wildfly.swarm:undertow:2017.5.0") {
		exclude module: 'javax.el-impl'
	}
}
```

4. Run `gradle dependencies --configuration compile`

```
compile - Dependencies for source set 'main'.
\--- org.wildfly.swarm:undertow:2017.5.0
     +--- org.wildfly.swarm:container:2017.5.0
     |    +--- org.wildfly.swarm:spi:2017.5.0
     |    |    +--- org.wildfly.swarm:bootstrap:2017.5.0
     |    |    |    +--- org.jboss.modules:jboss-modules:1.4.3.Final
     |    |    |    \--- org.yaml:snakeyaml:1.17
     |    |    +--- org.jboss.shrinkwrap:shrinkwrap-api:1.2.6
     |    |    +--- org.jboss.shrinkwrap:shrinkwrap-impl-base:1.2.6
     |    |    |    +--- org.jboss.shrinkwrap:shrinkwrap-api:1.2.6
     |    |    |    \--- org.jboss.shrinkwrap:shrinkwrap-spi:1.2.6
     |    |    |         \--- org.jboss.shrinkwrap:shrinkwrap-api:1.2.6
     |    |    +--- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-api-jboss:2.0.0-alpha-9
     |    |    |    \--- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-api-javaee:2.0.0-alpha-9
     |    |    |         \--- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-api-base:2.0.0-alpha-9
     |    |    +--- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-impl-jboss:2.0.0-alpha-9
     |    |    |    +--- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-api-jboss:2.0.0-alpha-9 (*)
     |    |    |    \--- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-impl-javaee:2.0.0-alpha-9
     |    |    |         +--- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-api-javaee:2.0.0-alpha-9 (*)
     |    |    |         \--- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-impl-base:2.0.0-alpha-9
     |    |    |              \--- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-spi:2.0.0-alpha-9
     |    |    |                   \--- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-api-base:2.0.0-alpha-9
     |    |    \--- org.jboss:jandex:2.0.2.Final
     |    +--- org.wildfly.swarm:bootstrap:2017.5.0 (*)
     |    +--- org.wildfly.swarm:config-api:1.0.3.Final
     |    |    \--- org.wildfly.swarm:config-api-runtime:1.0.3.Final
     |    +--- org.ow2.asm:asm-all:5.0.4
     |    \--- org.jboss.logging:jboss-logging:3.2.1.Final
     +--- org.wildfly.swarm:io:2017.5.0
     |    +--- org.wildfly.swarm:container:2017.5.0 (*)
     |    \--- org.wildfly.swarm:logging:2017.5.0
     |         +--- org.wildfly.swarm:container:2017.5.0 (*)
     |         \--- org.jboss.logging:jboss-logging:3.2.1.Final
     +--- org.wildfly.swarm:logging:2017.5.0 (*)
     +--- org.wildfly.swarm:ee:2017.5.0
     |    +--- org.wildfly.swarm:container:2017.5.0 (*)
     |    +--- org.wildfly.swarm:logging:2017.5.0 (*)
     |    +--- org.wildfly.swarm:naming:2017.5.0
     |    |    +--- org.wildfly.swarm:spi:2017.5.0 (*)
     |    |    +--- org.wildfly.swarm:container:2017.5.0 (*)
     |    |    \--- org.wildfly.swarm:logging:2017.5.0 (*)
     |    +--- org.jboss.spec.javax.enterprise.concurrent:jboss-concurrency-api_1.0_spec:1.0.0.Final
     |    +--- org.jboss.spec.javax.interceptor:jboss-interceptors-api_1.2_spec:1.0.0.Final
     |    \--- org.jboss.spec.javax.el:jboss-el-api_3.0_spec:1.0.7.Final
     +--- org.wildfly.swarm:request-controller:2017.5.0
     |    +--- org.wildfly.swarm:container:2017.5.0 (*)
     |    \--- org.wildfly.swarm:logging:2017.5.0 (*)
     +--- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-api-jboss:2.0.0-alpha-9 (*)
     +--- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-impl-jboss:2.0.0-alpha-9 (*)
     +--- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-api-javaee:2.0.0-alpha-9 (*)
     +--- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-impl-javaee:2.0.0-alpha-9 (*)
     +--- org.ow2.asm:asm-all:5.0.4
     +--- org.jboss.spec.javax.servlet:jboss-servlet-api_3.1_spec:1.0.0.Final
     +--- org.jboss.spec.javax.websocket:jboss-websocket-api_1.1_spec:1.1.1.Final
     +--- io.undertow:undertow-servlet:1.2.9.Final
     |    +--- io.undertow:undertow-core:1.2.9.Final
     |    |    +--- org.jboss.logging:jboss-logging:3.1.4.GA -> 3.2.1.Final
     |    |    +--- org.jboss.xnio:xnio-api:3.3.1.Final
     |    |    \--- org.jboss.xnio:xnio-nio:3.3.1.Final
     |    |         \--- org.jboss.xnio:xnio-api:3.3.1.Final
     |    +--- org.jboss.spec.javax.servlet:jboss-servlet-api_3.1_spec:1.0.0.Final
     |    \--- org.jboss.spec.javax.annotation:jboss-annotations-api_1.2_spec:1.0.0.Final
     \--- org.wildfly.swarm:meta-spi:2017.5.0
          \--- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-impl-javaee:2.0.0-alpha-9 (*)
```

5. Compare the versions of `io.undertow:undertow-servlet` 

### Your Environment
```
------------------------------------------------------------
Gradle 3.0
------------------------------------------------------------

Build time:   2016-08-15 13:15:01 UTC
Revision:     ad76ba00f59ecb287bd3c037bd25fc3df13ca558

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_121 (Oracle Corporation 25.121-b13)
OS:           Windows 7 6.1 amd64
```

**Comment by SetoKaiba** [comment] 2017-05-31 15:03
Currently. It's the blocking issue of the migration of WildFly Plugin. Really love to see a solution for this.

**Comment by bmuschko** [comment] 2017-05-31 21:53
@SetoKaiba I am not sure we'll tackle this issue in the next couple of weeks. We'd be happy to accept pull requests from the community though. Would you be interested in contributing a fix?

**Comment by uklance** [comment] 2017-05-31 22:00
I created a [gradle aether plugin](https://github.com/uklance/gradle-aether) to workaround the issue which resolves transitive dependencies in Aether instead of Gradle

**Comment by melix** [comment] 2017-06-01 07:48
You don't need to use a plugin to solve this problem. I think it's related to the fact that the `pom.xml` file for `undertow` has this (note that it doesn't provide any version number, neither does the parent pom):

```
<dependency>
   <groupId>io.undertow</groupId>
   <artifactId>undertow-servlet</artifactId>
</dependency>
```

You have several options to fix this. First, force the transitive dependency version number:

```
configurations.all {
  resolutionStrategy.force 'io.undertow:undertow-servlet:1.4.11.Final'
}
```

Another option is just to add an explicit dependency:

```
dependencies {
    compile 'io.undertow:undertow-servlet:1.4.11.Final'
}
```

Another thing would be to fix the wildfly pom to avoid it to leak Maven specific details, so that other consumers (Gradle, Ivy, Sbt, ...) can use correct metadata.

**Comment by uklance** [comment] 2017-06-01 08:10
See the discussion at https://discuss.gradle.org/t/strange-problem-of-gradle-compare-with-maven/22807/10. @SetoKaiba doesn't want to hard code the version in the `build.gradle` because it may be wrong next time they increase the wildfly version.

I was trying to follow it through by eye and I found the declaration without the `<version>`. I searched up the parent hierarchy and couldn't see the `<dependencyManagement>` section. Surely Maven should have failed to build if the version was not provided? How come Maven (and Aether) can resolve the version to `1.4.11.Final`? How does gradle resolve the version to `1.2.9.Final`?

I'm still confused to what's going on with this (quite complex) pom hierarchy

**Comment by melix** [comment] 2017-06-01 08:18
I _think_ Maven will choose `latest` here, whereas Gradle will resolve to the version explicitly provided by a transitive dependency, which it finds here. I reckon putting an explicit version number in the build file to fix this is problematic, but on the other hand, you have a conflict to solve here.

An option would be to use:

```
dependencies {
    compile 'io.undertow:undertow-servlet:1+'
}
```

It would somehow behave like Maven (even though here it resolves to `1.4.15.Final`, but it would behave _wrong_ because you get away with reproducible builds, which is a very bad idea.

**Comment by uklance** [comment] 2017-06-01 08:32
See [here](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html)

> Dependency mediation - this determines what version of a dependency will be used when multiple versions of an artifact are encountered. Currently, Maven 2.0 only supports using the "nearest definition" which means that it will use the version of the closest dependency to your project in the tree of dependencies. You can always guarantee a version by declaring it explicitly in your project's POM. Note that if two dependency versions are at the same depth in the dependency tree, until Maven 2.0.8 it was not defined which one would win, but since Maven 2.0.9 it's the order in the declaration that counts: the first declaration wins. 

So maven will choose the "nearest" and then pick the first if two different declarations at the same "level". The trouble is, I can't see a version anywhere in the hierarchy?

**Comment by melix** [comment] 2017-06-01 08:36
Yeah I know about the nearest strategy (which is, well, arguable...), but that's when you have version numbers at hand, which we don't have here, like you said. I'm in the dark too, I don't know where Maven gets that version number from either..

**Comment by uklance** [comment] 2017-06-01 09:47
W

**Comment by SetoKaiba** [comment] 2017-06-01 09:55
I'll try uklance plugin this evening. I can use force the version. But the module developer will ensure their nearest version correctly resolved.

There's a version conflict resolving for overridden dependencies transitive dependencies as well. I didn't take serious look at it before.

WildFly Swam is a project similar with Spring Boot. And it will generate a fatjar for the project. WildFly is with JBoss Modules with isolated modular class loader system. I can't even find out cause without comparing Maven plugin output and Gradle's. That's why I can't simply use the force version for it.

**Comment by uklance** [comment] 2017-06-01 12:16
If you use it, let me know and I'll publish the plugin to the [gradle plugin portal](https://plugins.gradle.org/)

**Comment by SetoKaiba** [comment] 2017-06-01 13:54
When I try to use it, I found it incompatible with "io.spring.dependency-management" plugin. The dependency management won't work. And due to it's a self implement dependency handler. It doesn't support the syntax as "group: , name:, version: ".

I'm trying to see whether I can implement like the spring dependency plugin does to override the version.

**Comment by uklance** [comment] 2017-06-01 14:21
See [here](https://github.com/uklance/gradle-aether/blob/master/gradle-aether/src/main/groovy/com/lazan/gradle/aether/AetherDependencyHandler.groovy#L79) where it creates the `Dependency` from a `String`. That could easily be changed to a `Map` instead

```
Artifact current = artifactResult.getArtifact();
String resultNotation = String.format("%s:%s:%s", current.getGroupId(), current.getArtifactId(), current.getVersion());
if (current.getClassifier() != null) {
	resultNotation = String.format("%s:%s", resultNotation, current.getClassifier());
}
if (current.getExtension() != null && current.getExtension().isEmpty() && !"jar".equals(current.getExtension())) {
	resultNotation = String.format("%s@%s", resultNotation, current.getExtension());
}				
ModuleDependency dependency = (ModuleDependency) project.getDependencies().create(resultNotation);
```

**Comment by SetoKaiba** [comment] 2017-06-01 14:28
![image](https://cloud.githubusercontent.com/assets/159540/26684380/6a0421f4-4719-11e7-829a-67e9f0fce84e.png)

I did see this. But since it‘s outside the normal dependency handler. My the artifact without version managed by bom with spring dependency management plugin is not working. 

So I prefer to use the same method as spring dependency management plugin to resolve the version from aether and override it.

**Comment by uklance** [comment] 2017-06-01 14:45
Of course you'd prefer gradle to resolve the dependency but unfortunately that can't happen without

1. A change to gradle's dependency resolution to match maven
2. Hardcoding the `undertow-servlet` version
3. A change to the wildfly pom's so they aren't being stupid

My plugin is a workaround to resolve the transitive dependencies using aether instead of gradle. Unfortunately that means it'll be done slightly differently to the other dependencies

**Comment by SetoKaiba** [comment] 2017-06-01 14:56
https://github.com/spring-gradle-plugins/dependency-management-plugin/blob/master/src/main/java/io/spring/gradle/dependencymanagement/internal/DependencyManagementApplier.java#L71-L84

Still use aether, I mean. But to override the version in this way. Is it better?

**Comment by SetoKaiba** [comment] 2017-06-03 10:49
I still can't get your plugin working with "io.spring.dependency-management". I wrote a new plugin for it only to retrieve the module version from aether. And it doesn't resolve the dependencies but only collect. And it's much faster than your method. It will solve transitive dependencies only.

**Comment by SetoKaiba** [comment] 2017-06-03 11:40
https://github.com/SetoKaiba/aether-gradle-plugin
Here's I wrote a plugin. Without the need to define any extension. Just apply it. And it will use Aether to resolve transitive dependencies instead of Gradle.
No need to modify anything. And it's working with "io.spring.dependency-management".

**Comment by SetoKaiba** [comment] 2017-06-08 08:43
> Yeah I know about the nearest strategy (which is, well, arguable...), but that's when you have version numbers at hand, which we don't have here, like you said. I'm in the dark too, I don't know where Maven gets that version number from either..

@melix No. There're versions declared. You can follow my post. It's get from the import scope dependency management.
 https://discuss.gradle.org/t/strange-problem-of-gradle-compare-with-maven/22807/15

**Comment by oehme** [comment] 2017-06-08 09:20
So this basically comes down to #1162

**Comment by SetoKaiba** [comment] 2017-06-08 09:42
The bom is not used directly by Gradle. For BOM to directly use with Gradle, I use spring plugin.
If it doesn't support BOM, how does it solve the version?

**Comment by uklance** [comment] 2017-06-08 09:55
Surely gradle already has support for `<dependencyManagement>` section in a dependency pom? Otherwise importing maven dependencies would never have worked. 

This issue is not for native bom support in gradle projects. This issue is an edge case in a complex maven pom hierarchy where maven and gradle are resolving transitive dependencies to different versions

**Comment by SetoKaiba** [comment] 2017-06-08 11:13
I agreed with uklance. If it doesn't support dependency management. And it will never work.

**Comment by oehme** [comment] 2017-06-08 12:08
Gradle supports dependency management via parent POMs, but as far as I'm aware we don't support management via <import> scope, a.k.a. BOMs.

**Comment by uklance** [comment] 2017-06-08 12:30
So far, no-one's shown me how the version is resolved in either gradle or maven. If someone has figured it out I'd love a walk-through. My eyeballing of the pom hierarchy couldn't find a version

**Comment by SetoKaiba** [comment] 2017-06-08 12:41
@oehme Maybe you misunderstand the case. We're not talking about to use BOM directly. But instead, use a module with BOM imported inside.

And here's an example for it.
https://gist.github.com/SetoKaiba/fe70e383464c7ada02dcb9d1572730dc
test-gradle depends on test-maven-child. And test-maven-child is with test-maven parent with dependency management with imported BOM. But as you can see, the version of org.wildfly.swarm:cdi is successfully resolved.
It's the same case as the project with problem. The project with problem depends on org.wildfly.swarm:undertow. And org.wildfly.swarm:undertow is with org.wildlfy.swarm:wildfly-swarm parent with dependency management with imported BOM. But as you can see, the version of org.wildfly.swarm:undertow is sucessfully resolved.  But the problem is the transitive dependency version of io.undertow:undertow-servlet.

**Comment by SetoKaiba** [comment] 2017-06-08 12:45
@uklance 
https://discuss.gradle.org/t/strange-problem-of-gradle-compare-with-maven/22807/15
In this post, I make a brief description of how the version is resolved. And I described how is the 1.4.11.Final is got by Maven. org.wildfly-swarm:undertow -> org.wildfly-swarm:wildfly-swarm(import the next in the dependency management) -> org.wildfly-swarm:wildfly-core-parent -> 1.4.11.Final is here.

**Comment by uklance** [comment] 2017-06-08 12:58
I've seen that and don't follow it. Please start lower down and start with `org.wildfly.swarm:undertow:2017.5.0` and tell me how you get either `1.4.11.Final` or `1.2.9.Final` for `io.undertow:undertow-servlet`

**Comment by oehme** [comment] 2017-06-08 13:29
Nevermind, I checked and we [do process](https://github.com/gradle/gradle/blob/d4b9413320cf6e712de9f2dbc1ca6544855741cd/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/parser/GradlePomModuleDescriptorParser.java#L173-L173) `<import>` statements in <dependencyManagement> blocks, so this is not the issue. There must be some other problem here.

One thing I vaguely remember was that Maven just uses "latest" when it encounters a version that it cannot parse. So if the POM is broken as @uklance supects, then that would explain the different behavior. In that case it needs to be fixed on the publisher side.

**Comment by oehme** [comment] 2017-06-08 14:24
I think I found the reason: `wildfly-swarm` imports `wildfly-core-parent:2.2.1.Final` which imports `wildfly-parent:10.1.0.Final` which imports `wildfly-arquillian-parent:1.0.2.Final`, which imports the old `wildfly-core-parent:1.0.1.Final` which then references `undertow-servlet:1.2.9`.

**Comment by oehme** [comment] 2017-06-08 14:44
I did a spike of letting the first BOM win instead of overwriting it, which seems to be what Maven is doing. I won't have time to verify that this is correct in other cases or write tests, but if someone wants to pick this up, this might be useful: https://github.com/gradle/gradle/commit/9e385a0adaaeb3daf086e4e3c61cfc4720a5a4f4

This fixes the specific issue mentioned here.

**Comment by SetoKaiba** [comment] 2017-06-08 15:54
Ah, it may solve my problems. Is there any nightly build for this fix?

**Comment by oehme** [comment] 2017-06-08 16:08
No, but you can build the branch from source (`gradlew install`).

**Comment by SetoKaiba** [comment] 2017-06-09 01:50
@oehme I'm using IDEA with Gradle wrapper. How can I use it with the fix? Previous I'm using gradle wrapper properties to specify the version. And it will solve all the stuffs for me.

**Comment by oehme** [comment] 2017-06-09 07:25
You can point the wrapper to the local installation that you created with `gradle install`.

**Comment by uklance** [comment] 2017-06-09 08:12
Looks like there was a gap in my knowledge of how dependencies are resolved in maven. I was not aware of `<scope>import</scope>` usage within `<dependencyManagement>`

**Comment by uklance** [comment] 2017-06-09 08:23
@oehme I think the maven behaviour is

> if two dependency versions are at the same depth in the dependency tree, until Maven 2.0.8 it was not defined which one would win, but since Maven 2.0.9 it's the order in the declaration that counts: the first declaration wins

See [here](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html)

**Comment by oehme** [comment] 2017-06-09 08:32
Thanks @uklance, that would be in line with the spike above. If any of you'd like to add some tests to it and send a PR, that would be greatly appreciated.

**Comment by uklance** [comment] 2017-06-09 08:44
I'm guessing that a test referencing `org.wildfly.swarm:undertow:2017.5.0` from `mavenCentral()` won't cut it?

If I get some time I'll try to write a test which populates a file based maven repo using two `<scope>import</scope>` dependencies with conflicting versions and then attempts resolution. It should fail before your changes and pass after.

**Comment by oehme** [comment] 2017-06-09 09:06
I think the former would be okay, given that Maven Central has a no change/no removal policy.

**Comment by SetoKaiba** [comment] 2017-06-09 15:18
@oehme And I found a small difference between Maven as well. But it doesn't matter. I'm not sure which one is better. If a project depends on another project which is with compileOnly dependency.  And it depends on a module that with transitive dependency which is the compileOnly dependency. Then the version in the compileOnly project won't be used. It will be used if the compileOnly is changed to compile. For maven, it will use the project's version.

I'm not sure which one is better.

**Comment by uklance** [comment] 2017-06-11 20:05
I created two tests [here]https://github.com/uklance/gradle/commit/54ce033c4338faa5cd374f3695607eddeabcc07a) but I'm not seeing the behaviour I expected

The first includes `org.wildfly.swarm:undertow:2017.5.0` and ensures that `org.wildfly.swarm:undertow:2017.5.0` is included. Strangely this test passes with or without the changes from [here](https://github.com/gradle/gradle/commit/9e385a0adaaeb3daf086e4e3c61cfc4720a5a4f4)

The second test creates maven dependencies from scratch and passes with the changes and fails when I comment them out as expected

**Comment by oehme** [comment] 2017-06-12 06:50
@uklance You'll need to clean the `intTestHome`, otherwise you'll be getting cached results from previous resolves. The tests work fine for me - they fail without the change and pass with the change.

**Comment by uklance** [comment] 2017-06-12 09:21
I created a pul request [here](https://github.com/gradle/gradle/pull/2282)

**Comment by oehme** [comment] 2017-07-23 16:39
This has been fixed thanks to @uklance

**Closed by oehme** 2017-07-23 16:39 UTC
Labels: a:bug, from:contributor, help-wanted, in:dependency-management
