### ISSUE TITLE
NPE in Gradle annotation processor handling

### ISSUE THREAD

**Issue by hrstoyanov** [gradle/gradle#26147] opened 2023-08-20 19:46 UTC
### Current Behavior

Gradle annotation processor generates NullPointException (NPE) when annotation is placed at the module level (very legitimate use case) which causes annotation based code generators such as (JStachio)[https://github.com/jstachio/jstachio]  to crash. 

### Expected Behavior

well, not crashing with NPE would be a good start...

### Context (optional)

@agentgt and myself discussed the issue in depth here:
https://github.com/jstachio/jstachio/issues/223

and the faulty code seem to be this:
https://github.com/jstachio/jstachio/issues/223#issuecomment-1685321532

This very much appears to be a poor null-check analysis prior to Gradle releases, which resulted in a few hours of wasted time to others.

### Steps to Reproduce

https://github.com/hrstoyanov/gradleIssue 
https://github.com/jstachio/jstachio/issues/223#issuecomment-1685240694
This small sample project shows the issue with JStachio 1.3.1 and Gradle 8.3 in Java 20 environment. 

### Gradle version

8.3, 8.2.1 ..possibly older too.

### Your Environment (optional)

Java 20

**Comment by jjohannes** [comment] 2023-08-21 20:35
Should be fixed by this https://github.com/gradle/gradle/pull/25644

(Don't know why it wasn't merged yet)

**Comment by hrstoyanov** [comment] 2023-08-21 20:54
Hm strange ... looks like [https://github.com/gradle/gradle/pull/25644](https://github.com/gradle/gradle/pull/25644) was created about about 40 days ago, but was not included in Gradle 8.3, scheduled for Gradle 8.4?

fyi: @agentgt

**Comment by jbartok** [comment] 2023-08-22 09:58
Thank you for providing a valid report.

The issue is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before a fix is made.

***

As discussed above fix is scheduled for `8.4`.

**Closed** 2023-08-30 05:49 UTC
Labels: a:bug, in:modular-java, in:annotation-processing, has:reproducer
