### ISSUE TITLE
Failure while populating the build operation queue: Value for unknown value has not been calculated yet.

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#23116] opened 2022-12-12 14:12 UTC
Version: `8.0-milestone-5`

Using the attached project [build-queue-failure.zip](https://github.com/gradle/gradle/files/10208748/build-queue-failure.zip) and running
```
rm -rf .gradle/configuration-cache/ && gw --stop && gw clean --configuration-cache &&   gw asDeb asDAT --configuration-cache
```

fails with
```
Caused by: java.lang.IllegalStateException: Value for unknown value has not been calculated yet.
        at org.gradle.internal.model.CalculatedValueContainer.getValue(CalculatedValueContainer.java:101)
        at org.gradle.internal.model.CalculatedValueContainer.get(CalculatedValueContainer.java:84)
        at org.gradle.api.internal.artifacts.transform.DefaultTransformer.getSecondaryInputHash(DefaultTransformer.java:261)
        at org.gradle.internal.execution.impl.DefaultInputFingerprinter$InputCollectingVisitor.visitInputProperty(DefaultInputFingerprinter.java:103)
        at org.gradle.api.internal.artifacts.transform.DefaultTransformerInvocationFactory$AbstractTransformerExecution.visitIdentityInputs(DefaultTransformerInvocationFactory.java:364)
        at org.gradle.api.internal.artifacts.transform.DefaultTransformerInvocationFactory$ImmutableTransformerExecution.visitIdentityInputs(DefaultTransformerInvocationFactory.java:190)
        at org.gradle.internal.execution.impl.DefaultInputFingerprinter.fingerprintInputProperties(DefaultInputFingerprinter.java:63)
        at org.gradle.internal.execution.steps.IdentifyStep.createIdentityContext(IdentifyStep.java:52)
        at org.gradle.internal.execution.steps.IdentifyStep.executeDeferred(IdentifyStep.java:47)
        at org.gradle.internal.execution.steps.IdentifyStep.executeDeferred(IdentifyStep.java:31)
        at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.executeDeferred(DefaultExecutionEngine.java:69)
```

Using Gradle versions `7.5` and `8.0-milestone-4` results in a successful build.

**Comment by eskatos** [comment] 2022-12-12 14:54
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and prioritized by them.

----

I can confirm the regression.
https://scans.gradle.com/s/wfyp5qi2iiq7u
With 8.0-m5, once the CC entry is stored, reusing doesn't fail the build.

**Comment by adammurdoch** [comment] 2022-12-16 03:45
This is fix now, via https://github.com/gradle/gradle/pull/23188

**Comment by eskatos** [comment] 2022-12-16 11:14
Fix confirmed by @gavra0, closing

**Closed by eskatos** 2022-12-16 11:14 UTC
Labels: a:regression, in:configuration-cache, @configuration-cache, in:artifact-transforms
