### ISSUE TITLE
maven-publish does not include dependencies when access properties via 'project.properties.<propName>'

### ISSUE THREAD

**Issue by EarthCitizen** [gradle/gradle#2110] opened 2017-05-22 17:58 UTC
**maven-publish** does not include project dependencies in the POM, when a property from `gradle.properties` is accessed via `project.properties.<propName>`. But DOES include dependencies when a property from `gradle.properties` is accessed via `project.<propName>`.

### Expected Behavior
The dependencies should not be excluded from the POM if I access project properties via `project.properties.<propName>`.

### Current Behavior
Dependencies are not included unless I access project properties via `project.<propName>`.

### Context
N/A

### Steps to Reproduce (for bugs)
https://github.com/EarthCitizen/maven-publish-issue

### Your Environment
OS: macOS
Gradle: 3.5

**Comment by w25r** [comment] 2017-05-22 18:06
Hi @EarthCitizen,

I'm not sure I fully understand the problem, so I'd like to reproduce it.  Would you mind pushing a sample repo to Github and sharing it?  Perhaps two build files, `working.gradle` and `broken.gradle` to illustrate the problem.

**Comment by EarthCitizen** [comment] 2017-05-22 18:09
@w25r Yes.

**Comment by EarthCitizen** [comment] 2017-05-22 22:05
@w25r 

The issue turned out to NOT be **maven-publish** getting applied by a plugin. Strangely, I found that there are no dependencies when I access a project property via `project.properties.<propName>` rather than `project.<propName>`:

https://github.com/EarthCitizen/maven-publish-issue

`project.properties.<propName>` - No dependencies in POM
`project.<propName>` - HAS dependencies in POM

**Comment by w25r** [comment] 2017-05-22 22:57
@EarthCitizen I've confirmed the behavior you are seeing and it is the same all the way back to at least version 2.14.1.  I'm glad you have a workaround for now, I'll continue to look at what's happening.

**Comment by oehme** [comment] 2017-09-06 13:20
Duplicate of #2496

**Closed by oehme** 2017-09-06 13:20 UTC
Labels: a:bug, from:contributor, in:publishing-plugin, waiting-for:gradle-team
