### ISSUE TITLE
Timeout waiting to lock journal cache   It is currently in use by another Gradle

### ISSUE THREAD

**Issue by ajaiswal595** [gradle/gradle#31655] opened 2024-12-10 16:25 UTC
### Current Behavior

Every time gradle build is failing 

### Expected Behavior

It should smoothly run every thing and even multiple build parallel also 

### Self-contained Reproducer Project

Using below jdk

openjdk version "17.0.13" 2024-10-15
OpenJDK Runtime Environment Temurin-17.0.13+11 (build 17.0.13+11)
OpenJDK 64-Bit Server VM Temurin-17.0.13+11 (build 17.0.13+11, mixed mode)

Cannot create service of type BuildSessionActionExecutor using method LauncherServices$ToolingBuildSessionScopeServices.createActionExecutor() as there is a problem with parameter #21 of type BuildLifecycleAwareVirtualFileSystem.
   > Cannot create service of type BuildLifecycleAwareVirtualFileSystem using method VirtualFileSystemServices$GradleUserHomeServices.createVirtualFileSystem() as there is a problem with parameter #1 of type FileWatchingFilter.
      > Cannot create service of type FileWatchingFilter using method VirtualFileSystemServices$GradleUserHomeServices.createFileWatchingFilter() as there is a problem with parameter #1 of type GlobalCacheLocations.
         > Cannot create service of type GlobalCacheLocations using method GradleUserHomeScopeServices.createGlobalCacheLocations() as there is a problem with parameter #1 of type List<GlobalCache>.
            > Could not create service of type FileAccessTimeJournal using GradleUserHomeScopeServices.createFileAccessTimeJournal().
               > Timeout waiting to lock journal cache (/Users/ajaykumarjaiswal/.gradle/caches/journal-1). It is currently in use by another Gradle instance.
                 Owner PID: 23571
                 Our PID: 32441
                 Owner Operation: 
                 Our operation: 
                 Lock file: /Users/ajaykumarjaiswal/.gradle/caches/journal-1/journal-1.lock

This is very time consuming and irritating that every other time we need to kill the process 

### Gradle version

8.11.1

**Comment by ov7a** [comment] 2024-12-11 09:49
This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/30135
* https://github.com/gradle/gradle/issues/8750

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

**Closed by ov7a** 2024-12-11 09:49 UTC
Labels: a:bug, to-triage

**Comment by GabeK0** [comment] 2024-12-30 17:02
Also wanted to flag this related issue: https://github.com/gradle/gradle/issues/31245

It's possible that your issue is caused by the firewall software listed in the above issue, and disabling said software can be a potential workaround!

**Comment by ajaiswal595** [comment] 2025-01-08 06:55
I'm using macbook 
2.3 GHz 8-Core Intel Core i9
Sonoma 14.7 (23H124)

Disabling the firewall doesn't help.
