### ISSUE TITLE
Do you have a reliable Gradle only Maven Repository?

### ISSUE THREAD

**Issue by lkishalmi** [gradle/gradle#18951] opened 2021-11-11 17:40 UTC
Dear Gradle Team,

Do you have a repository configuration on your Artifactory where only your artifacts are available?
Something like [libs-releases-local](https://repo.gradle.org/ui/native/libs-releases-local/).Though on that repository the releases only available up to 7.2-rc-2.

The reason for asking: Currently NetBeans build process is using Maven Central and an NB specific site to download third party binaries from. As Gradle binaries are not available on Maven Central, we have to download the artifacts (wrapper jar, Gradle binary distribution and the Tooling API jar) manually then upload them to our specific site.

It is possible to add additional repositories to our build system (we are still on Ant), though we would like to add one which only contains released artifacts by Gradle. Your [libs-releases](https://repo.gradle.org/ui/native/libs-releases/) has the artifacts we need, but it has other ones as well.

**Comment by lkishalmi** [comment] 2021-11-11 21:24
That's what we are planning to use for the Gradle binary distibution. Maybe we can use that to retrieve the wrapper (from the binary zip package).
The big question is the gradle-tooling-api jar. the one which is in the zip distribution is not that which we need and published at: https://repo.gradle.org/ui/native/libs-releases/org/gradle/gradle-tooling-api/7.3 (That one has all the Gradle Tooling dependencies, the one in the zip cannot be used alone).
And at the end it would more fit into our build to have maven style coordinates for the wrapper and the tooling API.
It would be nice to create a virtual repository in your JFrog with libs-release-local and your new repo where you  publish since 7.2.
(Yeah, as I do not know the underlying infrastructure, it may be not that easy...)

**Comment by matthiasblaesing** [comment] 2021-11-12 19:01
The optimal case would be: Distribute gradle from maven central. For OSS code OSSRH exists and can be used for snapshots and releases and releases are mirrored to central. To my knowledge other arrangements are possible when talking with Sonatype.

**Comment by ljacomet** [comment] 2021-11-15 11:00
Hey @lkishalmi,

Could you use https://repo.gradle.org/artifactory/public/?
It should have what you need.

If not, please share what's missing.

**Comment by lkishalmi** [comment] 2021-11-15 15:35
Thank you @ljacomet !

It seems to be fine at first sight. I'll give that a try!

**Comment by lkishalmi** [comment] 2021-11-15 22:56
@ljacomet It seems gradle-tooling-api jar can be downloaded from there, however the wrapper jar is missing. We need to download the wrapper jar as well, as Apache does not allow to store that in the source repository.

**Comment by ljacomet** [comment] 2021-11-16 08:42
🤔 I am not aware of Gradle ever publishing the wrapper JAR independently before. Did you have a solution to get it in the past?

**Comment by vlsi** [comment] 2021-11-16 09:18
@ljacomet , I've no idea why Gradle refuses to publish `gradle-wrapper.jar`, however, it would help bootstrapping Gradle:
* https://github.com/gradle/gradle/issues/14537

**Comment by vlsi** [comment] 2021-11-16 09:23
For instance, tools like https://github.com/kordamp/gm (/cc @aalmiray ), and https://github.com/gdubw/gng could then automatically retrieve `gradle-wrapper.jar` in case it is missing or differs from the authentic one.

Just in case: no way I think that removal of `gradle-wrapper.jar` from Git makes the repository more secure.
However, I just admit there are lots of people who remove jars because of lawyers (e.g. https://issues.apache.org/jira/browse/LEGAL-570).

So publishing the wrapper at OSSRH would help people to bootstrap Gradle, and they would stop using ugly hacks like https://github.com/gradle/gradle/raw/v7.3.0/gradle/wrapper/gradle-wrapper.jar

**Comment by vlsi** [comment] 2021-11-16 09:32
>as Apache does not allow to store that in the source repository.

@lkishalmi , Apache **allows** having `gradle-wrapper.jar` in a Git repository, and please keep the file there.
Apache forbids including `gradle-wrapper.jar` in a source release (that is the file at https://dist.apache.org/repos/dist/dev/ when you do a release vote)

The typical Apache way™️  is to keep `gradle-wrapper.jar` in git, exclude `gradle-wrapper.jar` from source release artifacts, and suffer™️. Every project adds its own steps to "build the project from source taking into account that `gradle-wrapper.jar` is not there".

---

Frankly speaking, I've spent a [lot of time on convincing ASF](https://issues.apache.org/jira/browse/LEGAL-570), however, they don't hear 😭 
Of course, it would be great if Gradle could bootstrap itself from text-only scripts without JDK installed in a consistent, fast, and compatible with different OS way. However, that is not in my priorities now, so I'm not blaming Gradle for "not implementing no-jar no-java bootstrap right now" 😉

**Comment by aalmiray** [comment] 2021-11-16 09:34
The Takari Maven wrapper and the upcoming Maven4 wrapper can bootstrap from source. Just saying Gradle could do the same if they really wanted to.

**Comment by vlsi** [comment] 2021-11-16 09:40
> The Takari Maven wrapper and the upcoming Maven4 wrapper can bootstrap from source

1) Maven does not perform the verification of the received jar.
In other words, it could download and execute a random jar at the developer machine, and the developer won't really realize that.
2) There is a cache invalidation issue: how do you know you must re-download the wrapper? I have not checked, however, I assume Maven would not re-download the wrapper, so it might result in stale/invalid builds if the developer keeps the jar for a long time. Of course, Maven users know they must `clean` often, however, I believe, that is not how the build system should behave 😉 

With Gradle, the recommendation is to keep `gradle-wrapper.jar` under source control, so you can trust the file (and verify it via https://github.com/gradle/wrapper-validation-action.

**Comment by aalmiray** [comment] 2021-11-16 09:41
Yes, Maven does not perform verification. Gradele does. That's not an excuse to not provide a source file that can bootstrap Gradle, like the Maven wrapper does.

**Comment by vlsi** [comment] 2021-11-16 09:45
> Yes, Maven does not perform verification. Gradle does

I'm afraid you got it wrong.
Gradle does not do the verification.

Gradle suggests that everybody should commit the file under source control for security, reproducibility, and performance reasons.

I see you suggest that "Gradle should offer an out-of-the box way to automatically receive the proper `gradle-wrapper.jar`". In other words, you suggest resolving https://github.com/gradle/gradle/issues/14537
That is open source, pull requests are welcome.
The solution is not as easy as `curl ..` because, well, there are different operating systems, `curl` can be missing, `https`, Power Shell in Windows is weird, then you need to verify the checksum of the received file, and so on.
It is solvable, however, I would refrain from pushing a half-baked solution in such a security-sensitive area.

The users won't understand, and they would start blindly removing `gradle-wrapper.jar` "because they don't like jars in Git".

**Comment by aalmiray** [comment] 2021-11-16 09:53
> That is open source, pull requests are welcome.

Good luck with that.

**Comment by jbartok** [comment] 2023-09-06 12:20
For the wrapper publication, follow the issue 
#14537

The repository question was answered above.

**Closed by jbartok** 2023-09-06 12:20 UTC
Labels: in:wrapper, in:tooling-api, to-triage
