### ISSUE TITLE
Use SwingBuilder in customize task on Android studio throw java.awt.HeadlessException.

### ISSUE THREAD

**Issue by jinai6682039** [gradle/gradle#2826] opened 2017-08-30 12:22 UTC
When I start to use SwingBuilder to fix the problem happened at used System.console() get null in gradle, it seem to be right at build.gradle file.But when I run the task, it throw a  java.awt.HeadlessException.
I used the SwingBuilder like this [method](http://stackoverflow.com/a/43414467/937715).

### Expected Behavior
Like link show before, it may show a dialog, allow to input something.

### Current Behavior
The terminal throw a java.awt.HeadlessException when run the task.

### Your Environment
gradle build tool version :  2.3.2
gradle version : 3.3

### My task
`tasks.create(name: "getPrivate.properties") {

    def headless = System.properties['java.awt.headless']
    if (headless == 'true') {
        System.setProperty("java.awt.headless", "true");
    }

    doLast {
        def password = '';
        def console = System.console();

        if (rootProject.file('local.properties').exists()) {
            Properties properties = new Properties()
            properties.load(rootProject.file('local.properties').newDataInputStream())
            password = properties.getProperty("release.password")
        }

        println 'password = ' + password
        if (!password?.trim()) {
            if (console) {
                password = new String(console.readPassword("\nKeystore password: "))
            } else {
                new SwingBuilder().edt {
                    dialog(modal: true,
                            title: 'Enter credentials',
                            alwaysOnTop: true,
                            resizable: true,
                            locationRelativeTo: null,
                            pack: true,
                            show: true) {
                        vbox {
                            label(text: "Keystore passphrase:")
                            textField id: "storeText", input = passwordField()
                            button(defaultButton: true, text: 'OK', actionPerformed: {
                                password = storeText.text;
                                dispose();
                            })
                        }
                    }
                }
            }
        }
        return password
    }
}`

I tried many ways to fix this problem, like `System.setProperty("java.awt.headless", "true")` or run task with option `-Djava.awt.headless=false`,but it seem no effect. 
But, when I change my gradle version to 2.14.1 and gradle build tool version to 2.2.1, the task run completely no error.

**Comment by blindpirate** [comment] 2017-08-30 13:10
Could you please paste the detailed stack trace? You can get it by command line option `--stacktrace`.

**Comment by jinai6682039** [comment] 2017-08-31 02:33
@blindpirate 
Yesterday ,its only show a message 'throw a java.awt.HeadlessException' without other information.


Like this `
    Error:(65, 1) Failed to create component for 'dialog' reason: java.awt.HeadlessException
        java.awt.HeadlessException
`


But today after reopen and rebuild my project, the task can work no error with gradle version 3.3.
I dont know why,  but it is strange .

**Comment by blindpirate** [comment] 2017-08-31 02:36
Okay, good to know that. Next time you can always append an option `--stacktrace` to get detailed stacktrace and it would help us to dig into it. 

I'll close this since you've got problem solved. Feel free to reopen it if necessary.

**Comment by filol** [comment] 2017-09-07 15:59
I have the same error. There is the stacktrace : 

* What went wrong:
Failed to create component for 'dialog' reason: java.awt.HeadlessException
> java.awt.HeadlessException (no error message)

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
java.lang.RuntimeException: Failed to create component for 'dialog' reason: java.awt.HeadlessException
	at build_5h7tcexao8tvdyyf1xu960lcz$_run_closure1$_closure6.doCall(C:\Users\fdex2\AndroidStudioProjects\CompteurdepointTarot\app\build.gradle:19)
	at build_5h7tcexao8tvdyyf1xu960lcz$_run_closure1.doCall(C:\Users\fdex2\AndroidStudioProjects\CompteurdepointTarot\app\build.gradle:18)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy104.graphPopulated(Unknown Source)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:126)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:46)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$ExecuteTasks.run(DefaultGradleLauncher.java:311)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.initialization.DefaultGradleLauncher.runTasks(DefaultGradleLauncher.java:202)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:132)
	at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:107)
	at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:78)
	at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:75)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:152)
	at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:100)
	at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:75)
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:53)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$1.run(RunAsBuildOperationBuildActionRunner.java:43)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:40)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:45)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:29)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:71)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:45)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:51)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:32)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:64)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:29)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:55)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:42)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:58)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:33)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.awt.HeadlessException
	... 91 more


* Get more help at https://help.gradle.org

BUILD FAILED in 8s

**Comment by SamehMahmoud** [comment] 2017-09-07 17:20
Same here

**Comment by blindpirate** [comment] 2017-09-07 23:07
@SamehMahmoud I slightly formatted your stacktrace. I'm not an expert in awt, but looks like it has nothing to do with Gradle. Could you take a look at [this](https://www.ibm.com/developerworks/community/blogs/738b7897-cd38-4f24-9f05-48dd69116837/entry/how_to_resolve_java_exceptions_java_awt_headlessexception7?lang=zh) and figure out the reason of this issue?

**Comment by filol** [comment] 2017-09-08 05:25
@blindpirate I think you fail your mention and you talk to me. I will look your link but I use the same code that the report and I if I downgrade grade it's working

**Comment by blindpirate** [comment] 2017-09-08 05:27
@filol Oh yes, sorry. Could you provide us a simple reproducible sample to help us dig into this? That would be great.

**Comment by filol** [comment] 2017-09-09 10:51
I just created an empty project and I added the code you that you will find in the build.gradle https://github.com/filol/MyApplication

**Comment by blindpirate** [comment] 2017-09-09 11:14
@filol Thanks a lot! Just to clarify, how can I trigger this issue with your sample? Looks like you didn't define any task in `build.gradle`.

**Comment by filol** [comment] 2017-09-09 11:17
@blindpirate you just need do Make Project with android studio result with a crash. 
![image](https://user-images.githubusercontent.com/9217516/30239617-2ad2a618-9561-11e7-98fd-7cbce3f22ca3.png)

**Comment by blindpirate** [comment] 2017-09-09 12:35
Try to add `System.setProperty("java.awt.headless", "false");` at this line: https://github.com/filol/MyApplication/blob/master/app/build.gradle#L4

Kill all gradle daemons on your machine and retry. I reproduced your issue and solve it via this approach.

**Closed** 2017-09-09 12:41 UTC
Labels: a:bug, affects-version:4.1, from:contributor

**Comment by filol** [comment] 2017-09-09 12:51
Thanks, it works for me, I had already tried to do this but I did not killer the daemon

**Comment by punksta** [comment] 2017-12-15 10:28
Hello! I have a same issue.
debian 9, gradle 4.1

```
// top level of app/build.gradle

import groovy.swing.SwingBuilder
System.setProperty('java.awt.headless', 'false')

def readPassword(hint) {
    def console = System.console()
    if (console) {
        return new String(System.console().readPassword(hint))
    } else {
         def keyPassPhrase;

          new SwingBuilder().edt {
                     dialog(modal: true, title: 'Enter credentials', alwaysOnTop: true, resizable: true,
                             locationRelativeTo: null, pack: true, show: true
                     ) {
                         vbox {
                             label(text: hint)
                             textField id: "storeText", input = passwordField()
                             button(defaultButton: true, text: 'OK', actionPerformed: {
                                 keyPassPhrase = storeText.text;
                                 dispose();
                             })
                         }
                     }
         }
          return  keyPassPhrase;
    }
}
```

```
// android block of app/build.gradle
 signingConfigs {
        if (System.env.STORE_FILE != null) {
          fromEnv {
             storeFile new File(System.env.STORE_FILE)
             storePassword System.env.STORE_PASSWORD ?: readPassword("store password: ")
             keyAlias System.env.KEY_ALIAS ?: readPassword("keyAlias: ")
             keyPassword System.env.KEY_PASSWORD ?: readPassword("keyPassword: ")
          }
        }
     }
```

**Comment by barbeau** [comment] 2018-02-01 22:04
@filol @blindpirate Does the above solution still work for you? I can't get it to work with `com.android.tools.build:gradle:3.0.1` exactly as you have written when using `gradlew assembleObaGoogleRelease` on https://github.com/CUTR-at-USF/onebusaway-android/tree/release-builds-broken.
