### ISSUE TITLE
Accessing an output DirectoryProperty from a running task should be reported better

### ISSUE THREAD

**Issue by britter** [gradle/gradle#13046] opened 2020-05-07 06:49 UTC
If a running task accesses it's own output DirectoryProperty gradle will emit this [deprectation warning](https://docs.gradle.org/6.3/userguide/upgrading_version_6.html#querying_a_mapped_output_property_of_a_task_before_the_task_has_completed). However there are two problems with this:

1. it's hard to understand what's going on because gradle does not explicitly report that the output was accessed from the task that is running.
2. the deprecation documentation does not document how to mitigate this problem.

### Expected Behavior

Gradle should emit a deprecation warning telling the user that accessing an output property from the currently running task is deprecated. It should furthermore explain to the user how to mitigate this, e.g. by using `FileSystemLocationProperty#locationOnly`

### Current Behavior

Gradle emits [this deprecation](https://docs.gradle.org/6.3/userguide/upgrading_version_6.html#querying_a_mapped_output_property_of_a_task_before_the_task_has_completed).

### Context

This affected my while writing a buildSrc plugin that writes some files to it's output directory. I was looking for a way to easily create a File object from the output DirectoryProperty, see below.

### Steps to Reproduce 

Given the following task:

```java
abstract class MyTask extends DefaultTask {

  @OutputDirectory
  abstract DirectoryProperty getOutputDirectory();

  @TaskAction
  public void run() throws Exception {
    getProject().delete(getOutputDirectory())

    Files.writeString(
      getOutputFile().toPath(),
      "Some text",
      StandardCharsets.UTF_8,
      StandardOpenOption.CREATE
    );
  }

  private File getOutputFile() {
    return getOutputDirectory().dir("someDir").map(d -> d.file("out.txt")).get().asFile();
  }
}
```

If this task is executed it will emit the said deprecation warning. The problem here is that the output file is created using `dir` and then `map`. The correct way of creating the output file would be

```java
new File(getOutputDirectory().getLocationOnly().get().asFile(), "someDir/out.txt")
```

However for a user this is hard to see, because `dir()` and `file()` seem like natrual ways to create stuff inside an `Directory`. For this reason it would be good if the deprecation warning could more clearly indicate what the problem is and how to fix it.

### Your Environment

Build scan URL:

**Comment by adammurdoch** [comment] 2020-05-07 06:53
It might be better to un-deprecate that case and allow a task action to do what it likes with its properties. The task author would be responsible for using the properties at the correct time, after the task has generated the outputs.

**Comment by britter** [comment] 2022-04-19 08:09
@adammurdoch I think this is still valid.

**Comment by mlopatkin** [comment] 2024-07-04 16:56
This issue will be closed as a duplicate of

* #26340

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

**Closed by mlopatkin** 2024-07-04 16:56 UTC
Labels: a:bug, in:configuration-model
