### ISSUE TITLE
`notCompatibleWithConfigurationCache` fails the build on CC issues rather than disable CC in 7.4-rc-1

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle#19765] opened 2022-01-31 02:40 UTC
### Expected Behavior
The documentation implies that if a task denoted with `notCompatibleWithConfigurationCache` is scheduled for execution, configuration cache will be automatically disabled. I expect that to be the case.

### Current Behavior

It fails the build anyway upon encountering such a task if it's set via `configureEach`.

### Context

We can't opt-out of non-compliant tasks without this API working as intended

### Steps to Reproduce 

Disable a problematic task like so and then try to configure

```kotlin
tasks.withType<SomeProblematicTask>().configureEach {
  notCompatibleWithConfigurationCache("Testing")
}
```

Or a more concrete example from our repo with the Microsoft intune gradle plugin

![image](https://user-images.githubusercontent.com/1361086/151731802-1d52fc92-e6a8-4621-b65d-495cecef6e14.png)

Then run `./gradlew problematicTask --dry-run` and observe it fails the build anyway like so

```
1 problem was found storing the configuration cache.
- Task `:app:transformClassesWithMamifyTransformForIntuneRelease` of type `com.android.build.gradle.internal.pipeline.TransformTask`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
  See https://docs.gradle.org/7.4-rc-1/userguide/configuration_cache.html#config_cache:requirements:disallowed_types

See the complete report at file:///Users/zsweers/dev/slack/android3/build/reports/configuration-cache/75mg9pggd0y9brklyefbmeyal/7kbj64fszuuzeq6o3mlywy094/configuration-cache-report.html

FAILURE: Build failed with an exception.

* What went wrong:
Configuration cache state could not be cached: input property '$3' of ':app:transformClassesWithMamifyTransformForIntuneRelease': error writing value of type 'org.gradle.api.internal.file.FilteredFileTree'
> Querying the mapped value of provider(interface java.util.Set) before task ':app:compileIntuneReleaseKotlin' has completed is not supported

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4-rc-1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 10s

```

### Your Environment

Build scan URL:

**Comment by eskatos** [comment] 2022-02-01 11:10
Hi Zac,
Thanks for the report.

The following works as expected:

```groovy
tasks.register("incompatibleTask") {
    doLast {
        println(project.file("test.txt"))
    }
}

tasks.matching { it.name == "incompatibleTask" }.configureEach {
    notCompatibleWithConfigurationCache("broken")
}
```

It seems that in your case, the reported problem (`cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported`) is not what makes the build fail as `notCompatibleWithConfigurationCache()` takes care of this.

What makes the build fail is `> Querying the mapped value of provider(interface java.util.Set) before task ':app:compileIntuneReleaseKotlin' has completed is not supported`.

It happens with the configuration cache enabled because task input handling is more strict. This is not covered by `notCompatibleWithConfigurationCache()`.

To fix this you'd need to find what is consuming that input too soon. The build failure stacktrace should provide some pointers.

**Comment by ZacSweers** [comment] 2022-02-01 14:16
Thanks, I'll take a look

**Comment by DanielThomas** [comment] 2022-02-24 03:09
We're seeing this with Test Distribution and even with `notCompatibleWithConfigurationCache()` the build fails on 7.4. See Enterprise Support case #3785.

```
13:15:43 - Task `:nebula-artifactory-integration-tests:test` of type `org.gradle.api.tasks.testing.Test`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
13:15:43   See https://docs.gradle.org/7.4/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
13:15:43 - Task `:nebula-code-quality:test` of type `org.gradle.api.tasks.testing.Test`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
13:15:43   See https://docs.gradle.org/7.4/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
13:15:43 - Task `:nebula-common:test` of type `org.gradle.api.tasks.testing.Test`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
13:15:43   See https://docs.gradle.org/7.4/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
13:15:43 - Task `:nebula-publish:test` of type `org.gradle.api.tasks.testing.Test`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
13:15:43   See https://docs.gradle.org/7.4/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
13:15:43 - Task `:nebula-repos:test` of type `org.gradle.api.tasks.testing.Test`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
13:15:43   See https://docs.gradle.org/7.4/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
13:15:43 - Task `:nebula:test` of type `org.gradle.api.tasks.testing.Test`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
13:15:43   See https://docs.gradle.org/7.4/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
13:15:43 
13:15:43 See the complete report at file:///mnt/data/agent/workspace/NEBULA-nebula/build/reports/configuration-cache/7pk955cacj42a77dyi3l84lha/e83pi59nxb3jdnipvh9u5kf1y/configuration-cache-report.html
13:15:43 	at org.gradle.configurationcache.problems.ConfigurationCacheProblems.report(ConfigurationCacheProblems.kt:160)
13:15:43 	at org.gradle.internal.buildtree.ProblemReportingBuildActionRunner.reportProblems(ProblemReportingBuildActionRunner.java:61)
13:15:43 	at org.gradle.internal.buildtree.ProblemReportingBuildActionRunner.run(ProblemReportingBuildActionRunner.java:52)
13:15:43 	at org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:69)
13:15:43 	at org.gradle.tooling.internal.provider.FileSystemWatchingBuildActionRunner.run(FileSystemWatchingBuildActionRunner.java:119)
13:15:43 	at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:41)
13:15:43 	at org.gradle.launcher.exec.RootBuildLifecycleBuildActionExecutor.lambda$execute$0(RootBuildLifecycleBuildActionExecutor.java:40)
13:15:43 	at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:128)
13:15:43 	at org.gradle.launcher.exec.RootBuildLifecycleBuildActionExecutor.execute(RootBuildLifecycleBuildActionExecutor.java:40)
13:15:43 	at org.gradle.internal.buildtree.DefaultBuildTreeContext.execute(DefaultBuildTreeContext.java:40)
13:15:43 	at org.gradle.launcher.exec.BuildTreeLifecycleBuildActionExecutor.lambda$execute$0(BuildTreeLifecycleBuildActionExecutor.java:65)
13:15:43 	at org.gradle.internal.buildtree.BuildTreeState.run(BuildTreeState.java:53)
13:15:43 	at org.gradle.launcher.exec.BuildTreeLifecycleBuildActionExecutor.execute(BuildTreeLifecycleBuildActionExecutor.java:65)
13:15:43 	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor$3.call(RunAsBuildOperationBuildActionExecutor.java:61)
13:15:43 	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor$3.call(RunAsBuildOperationBuildActionExecutor.java:57)
13:15:43 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
13:15:43 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
13:15:43 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
13:15:43 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
13:15:43 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
13:15:43 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
13:15:43 	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
13:15:43 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
13:15:43 	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor.execute(RunAsBuildOperationBuildActionExecutor.java:57)
13:15:43 	at org.gradle.launcher.exec.RunAsWorkerThreadBuildActionExecutor.lambda$execute$0(RunAsWorkerThreadBuildActionExecutor.java:36)
13:15:43 	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:270)
13:15:43 	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:119)
13:15:43 	at org.gradle.launcher.exec.RunAsWorkerThreadBuildActionExecutor.execute(RunAsWorkerThreadBuildActionExecutor.java:36)
13:15:43 	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecutor.execute(ContinuousBuildActionExecutor.java:103)
13:15:43 	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecutor.execute(SubscribableBuildActionExecutor.java:64)
13:15:43 	at org.gradle.internal.session.DefaultBuildSessionContext.execute(DefaultBuildSessionContext.java:46)
13:15:43 	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter$ActionImpl.apply(BuildSessionLifecycleBuildActionExecuter.java:100)
13:15:43 	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter$ActionImpl.apply(BuildSessionLifecycleBuildActionExecuter.java:88)
13:15:43 	at org.gradle.internal.session.BuildSessionState.run(BuildSessionState.java:69)
13:15:43 	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter.execute(BuildSessionLifecycleBuildActionExecuter.java:62)
13:15:43 	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter.execute(BuildSessionLifecycleBuildActionExecuter.java:41)
13:15:43 	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:63)
13:15:43 	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
13:15:43 	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:58)
13:15:43 	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:42)
13:15:43 	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:47)
13:15:43 	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:31)
13:15:43 	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:65)
13:15:43 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
13:15:43 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
13:15:43 	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
13:15:43 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
13:15:43 	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:29)
13:15:43 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
13:15:43 	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
13:15:43 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
13:15:43 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
13:15:43 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
13:15:43 	at org.gradle.util.internal.Swapper.swap(Swapper.java:38)
13:15:43 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
13:15:43 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
13:15:43 	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
13:15:43 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
13:15:43 	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
13:15:43 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
13:15:43 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
13:15:43 	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:84)
13:15:43 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
13:15:43 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
13:15:43 	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
13:15:43 	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
13:15:43 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
13:15:43 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
```

**Comment by Goooler** [comment] 2022-03-18 09:59
Already skipped impracticable tasks, but still fails, see https://github.com/zhaobozhen/LibChecker/pull/203#discussion_r829851011

**Comment by bingranl** [comment] 2022-03-24 00:06
Any updates on this bug? We are seeing similar things. @eskatos , is there a way to know the actual property name mentioned from the error message "Configuration cache state could not be cached: input property '$3' " From our message, it says "xxxx property '$1' xxxxxxx".

**Comment by bingranl** [comment] 2022-04-06 21:40
FYI the problem should be caused by incompatibility between `PatternSet` matching and `FileTree`([reference](https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:build-system/gradle-core/src/main/java/com/android/build/gradle/internal/pipeline/TransformStream.java;l=138?q=transformstream.java)) and there is a similar issue here https://github.com/gradle/gradle/issues/19780 which is fixed in Gradle 7.5

I tested with 7.5 nightly and our test passes so @ZacSweers I guess the upgrade would also work for you

**Comment by ZacSweers** [comment] 2022-04-06 22:31
Nice. We can't test 7.5 easily yet due to some other changes but good to hear

**Comment by bamboo** [comment] 2022-04-27 14:08
With https://github.com/gradle/gradle/issues/19959 and https://github.com/gradle/gradle/issues/19780 fixed it seems this issue is no longer actionable from our side.

Is there a reason to keep this issue open?

**Comment by chrisjenx** [comment] 2022-06-09 15:30
7.5-rc-1 fixed this issue for me too

**Comment by bamboo** [comment] 2022-06-09 16:08
Thanks for the update, @chrisjenx, great to hear.

**Comment by bamboo** [comment] 2022-08-02 08:05
Closing as fixed.

**Closed by bamboo** 2022-08-02 08:05 UTC
Labels: a:bug, in:configuration-cache, @configuration-cache
