### ISSUE TITLE
Use Gradle generate jacocoUnitTestReport is not up-to-date

### ISSUE THREAD

**Issue by ldw5821cn** [gradle/gradle#7665] opened 2018-11-08 07:34 UTC
### Expected Behavior

jacocoUnitTestReport  is up-to-date

### Current Behavior

```
 jacocoUnitTestReport is not up-to-date
 Output property 'reports.enabledReports.html.destination' file /app/build/reports/jacoco/jacocoUnitTestReport/html has been removed.
  Output property 'reports.enabledReports.html.destination' file /app/build/reports/jacoco/jacocoUnitTestReport/html/com.android.internal.telephony has been removed.
  Output property 'reports.enabledReports.html.destination' file /app/build/reports/jacoco/jacocoUnitTestReport/html/com.android.internal.telephony/ITelephony$Stub$Proxy.html
```
### Context
Use Gradle Task
```
task jacocoUnitTestReport(type: JacocoReport, dependsOn: ['testDebugUnitTest']) {
    buildDir =  '../app/build'

    def coverageSourceDirs = [
            "src/main/java"
    ]
    File file = new File("$projectDir/unitTestFilter.txt")
    def fileFilter = file.readLines()
    def javaClasses = fileTree(//修改此处路径为编译输出的的class路径
            dir: "$buildDir/intermediates/javac/debug/compileDebugJavaWithJavac/classes",
            excludes: fileFilter
    )
    classDirectories = files([ javaClasses ])
    additionalSourceDirs = files(coverageSourceDirs)
    sourceDirectories = files(coverageSourceDirs)
    executionData = fileTree(dir: "$buildDir", includes: [
            "jacoco/testDebugUnitTest.exec"
    ])
     reports {
        xml.enabled = true
        html.enabled = true
    }

```
### Steps to Reproduce (for bugs)

gradlew jacocoUnitTestReport --info
### Your Environment
JaCoCo version: 0.8.2
Operating system: Mac OS 10.12.6
Tool integration: Android Studio Gradle 4.10.2

**Comment by sattha** [comment] 2019-04-12 16:31
+1

**Comment by bmuskalla** [comment] 2020-03-24 14:47
So far I'm unable to reproduce this. Closing this for now. If you're able to reproduce this with a more recent version, please provide a small project to reproduce this. Thanks for your time!

**Closed by bmuskalla** 2020-03-24 14:47 UTC
Labels: from:contributor, in:jacoco-plugin

**Comment by hpatel123** [comment] 2022-04-19 14:51
@bmuskalla Facing the same issue.

Jacoco version: 0.8.8
