### ISSUE TITLE
More Problems API Feedback

### ISSUE THREAD

**Issue by Arthurm1** [gradle/gradle#28999] opened 2024-04-29 17:21 UTC
### Expected Behavior

Some feedback on the Problems API which would make it easier to use from an IDE perspective...

1) For Java errors/warnings, the `ProblemAggregationEvent#getProblemAggregation#.getProblemContext#get(XX)#getLocations` used to contain a `TaskPathLocation` (I think it was in Gradle 8.6?).  It no longer does (Gradle 8.8)
Could this be put back in?
It allows me to work out exactly what Project/SourceSet the problem relates to.  E.g. if I can see the TaskPath is something like `:foo:compileTestJava` then I know it's project `Foo` sourceSet `test`.
My only other way of working this out is to extract the `FileLocation#getPath` and then iterate through all projects/sourcesets' source directories and see if they are parent paths of the `FileLocation` which is very slow when there's a large number of projects and/or large number of warnings/errors.

2) Could the `AggregatingProblemConsumer#thresholdForIntermediateSummary ` be set from some Gradle/Project/System property?  Currently it's set to 10_000.  If I can set it to 1 (so it's effectively turned off) then I wouldn't have to handle `ProblemAggregationEvent` at all, only `SingleProblemEvent`.
The advantage to me is that I get problems as the projects are compiled, rather than at the end.  The IDE has a nicer feel when you're compiling and you see errors/warnings appear as you go rather than getting no feedback until after compilation is finished.
It also means that I don't have to worry about any changes to the `ProblemAggregation` API.
Also - `SingleProblemEvents` are sent before the `FinishEvent` is sent which makes it easier to know when to create summary information about problems (e.g. total warning/error count per project/sourceset) whereas `ProblemAggregationEvents` are sent after the taskpath they are reporting on has already sent a `FinishEvent`
Why does the Problem Aggregation exist?  For performance reasons?

### Context

Trying to give the best IDE experience to the user when reporting info from the Problems API.

**Comment by ov7a** [comment] 2024-04-30 06:23
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by donat** [comment] 2024-05-09 13:11
@Arthurm1 Thank you for the feedback, we really appreciate it! 

Regarding, `TaskPathLocation`, we had to remove this feature because it introduced a major performance regression in Gradle. It should be possible to get the same information on Tooling API client side from the progress events. Nonetheless I'll create an issue to capture that information in a more convenient way. 

The problem aggregation is very similar story. It was introduced to deal with large quantities of problems reported. The intention is also to provide a smooth experience: provide a few problems to the client while the build is running, and send the rest at the end. How many compiler warnings is too little or too much is something we can reconsider.  I'm interested in your feedback here.

Also, seems like you are vested in this topic but I cannot seem to find you on the Gradle Community slack channel. I encourage you to join. You can get an invite [here](https://gradle.org/slack-invite). With that, we'd have a directly line of communication.

**Comment by donat** [comment] 2024-05-09 13:15
I'll close this issue in favour of the new reports.

**Closed by donat** 2024-05-09 13:15 UTC
Labels: a:feature, in:problems, :wave: team-triage
