### ISSUE TITLE
Gradle 6.0+ version has Conflict with win10 WiFi hotspot function

### ISSUE THREAD

**Issue by zhu071011** [gradle/gradle#16496] opened 2021-03-11 07:08 UTC
I use AndroidStudio build android project with gradle.
But when I update gradle to 6.5 ,there is a very confuse thing happen.when I open a new project,I need cut off wifi hotspot everytime,because Gradle 6.0+ version has Conflict with win10 WiFi hotspot function.
the error content is :Gradle sync failed: 你的主机中的软件中止了一个已建立的连接（Software in your host has terminated a established connection）。 (5 s 590 ms)
but in version 4.10,don't have this problem.

**Comment by big-guy** [comment] 2021-03-12 01:56
@zhu071011 Does this happen for you on the command-line too or just through the IDE/AS?

**Comment by jjohannes** [comment] 2021-03-30 07:12
Closing this issue due to lack of information on how to reproduce the problem for investigation.

**Closed by jjohannes** 2021-03-30 07:12 UTC

**Comment by wolfs** [comment] 2021-03-30 07:17
This is a duplicate of https://github.com/gradle/gradle/issues/14958.
