### ISSUE TITLE
gradle fails to start with JDK 11

### ISSUE THREAD

**Issue by kevinrushforth** [gradle/gradle#4591] opened 2018-03-05 23:08 UTC
### Expected Behavior
gradle should run with JDK 11

### Current Behavior
gradle fails immediately with an error indicating that the Java version is unrecognized

### Context
This blocks JavaFX from building and testing using the current JDK 11 ea builds.

### Steps to Reproduce (for bugs)
To reproduce this:

1. Download a recent JDK 11 ea build from here:

http://jdk.java.net/11/

2. Set your JAVA_HOME and/or PATH to point to the jdk-11 ea build, and verify that you are running jdk-11:

$ java -version
java version "11-ea" 2018-09-18
Java(TM) SE Runtime Environment 18.9 (build 11-ea+3)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11-ea+3, mixed mode)

3. Try to run gradle using jdk-11:

$ gradle -version

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '11-ea'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

### Your Environment
Ubuntu 16.04, but this is a platform-independent bug.

**Comment by kevinrushforth** [comment] 2018-03-05 23:10
I note that this issue was raised when JDK 10 was first under development. I think it would be best if gradle were to issue a warning upon seeing an unrecognized version, but then tried to run anyway, assuming the behavior of the highest JDK version currently expected and known.

**Comment by oehme** [comment] 2018-03-06 09:44
Duplicate of #4515

**Closed by oehme** 2018-03-06 09:44 UTC

**Comment by stanislavdimov** [comment] 2018-12-03 17:04
gradle -4.6 do not want to work with JDK 11, only gradle -4.5 working!

**Comment by dheart5** [comment] 2019-01-14 22:49
I had this issue while installing/running Tron Studio. My solution: revert to JDK 1.8.
Here is the command:

`export JAVA_HOME=`/usr/libexec/java_home -v 1.8``

You must redo this every time you run your terminal.
