### ISSUE TITLE
war plugin may fail with custom project layout

### ISSUE THREAD

**Issue by Treverix** [gradle/gradle#8791] opened 2019-03-15 18:01 UTC
### Expected Behavior
Given a project layout like this

    web
    modules
       + module-a
            + api
            + impl
            + web
       + module-b
            + api
            + impl
            + web

The six nested projects contain the code of a webapplication and all build `jar`s, the top level `web` project shall build the `war`.

now when doing something like

    project(':web') {
        apply plugin: 'war'
        dependencies { 
            runtime project(':modules:module-a:web')
            runtime project(':modules:module-b:web')
        }
    }

and having the two nested web projects configured to depend on their api and impl, then I expect all six jars to be added to the war file.

### Current Behavior
Only the jar files from module-a are added. The jar files for web, api and impl of module-b are not added to the war.

It works if I rename the folders inside module-a and module-b to unique names.

Please find a minimal multi project build that shows the issue in this github repository: [https://github.com/Treverix/gradle-war-issue](https://github.com/Treverix/gradle-war-issue)

### Context
This is actually a show-stopper for an activity to convert the build for a large scale application from maven to gradle.

### Your Environment
gradle 5.2.1 on windows 10 environment

 * Build scan URL:

**Comment by big-guy** [comment] 2019-03-15 21:59
The issue here is that the two subprojects have the same publication coordinates (de.dolk:web:1.0-SNAPSHOT), so they appear to be the same dependency.

Any suggestions @gradle/dependency-management ?

**Comment by ljacomet** [comment] 2019-03-18 08:03
That is indeed the issue, the solution is to make sure that each project have distinct coordinates between their `group` and `name`.

On the Gradle side, maybe the tool should be less lenient when such issues exist inside a multi project build.

**Comment by Treverix** [comment] 2019-03-18 08:50
Not knowing if there's a reason for these 'short' coordinates: truly unique coordinates like `de.dolk:modules:module-a:web:1.0-SNAPSHOT` or just based on the common group/artifact/version tuple would prevent from excluding artifacts from the war. 
I'm not a gradle expert yet: is there an easy workaround for this? Changing the project layout is out of reach, I currently plan to make the war task depend on an `install` task that would write the artifacts to a local maven repository and add them to the war based on the maven coordinates.

**Comment by ljacomet** [comment] 2019-03-18 09:37
The root of the problem is the way Gradle handles a project name when it is composed, like `:modules:module-a:api`.

This name implies a hierarchy: you are looking for the project `api` inside the project `module-a` inside `modules`. And so that first project is simply named `api` which conflicts with `:modules:module-b:api` which is also a project named `api`. And it happens that Gradle matches that hierarchy to an equivalent folder hierarchy on disk.

While this naming difference allows Gradle to differentiate between the projects for things like tasks identity, when dependency resolution kicks-in, projects are brought back to have `group:name` identity to enable matching / differentiating external artifacts from project ones.

And what you did, renaming the jar files, does not influence that project identity.

The solution is simply to name the projects differently, leveraging the fact that you can decouple project name from disk location.

Something like the following in your `settings.gradle`:
```
rootProject.name = 'gradle-war-issue'

include 'web-app'
include 'module-a-api'
include 'module-a-impl'
include 'module-a-web'
include 'module-b-api'
include 'module-b-impl'
include 'module-b-web'


project(':module-a-api').projectDir = file('modules/module-a/api')
project(':module-a-impl').projectDir = file('modules/module-a/impl')
project(':module-a-web').projectDir = file('modules/module-a/web')

project(':module-b-api').projectDir = file('modules/module-b/api')
project(':module-b-impl').projectDir = file('modules/module-b/impl')
project(':module-b-web').projectDir = file('modules/module-b/web')
```

Of course, that also means that in order to declare dependencies between projects, you have to use the names `:module-a-api` and others.

@pledbrook I could not find a section in the documentation that clearly states this. Maybe that's an addition we need to think of.

**Comment by Treverix** [comment] 2019-03-18 13:36
@ljacomet Thank you for this tip! Using custom project names based on the directories is a more then acceptable solution to my problem. That was beyond my current gradle skills -  I carry on with that!
I doubt that a lot of people have that problem but the risk is quite high for large scale java web apps (that use the war plugin). I agree that it should be considered to add this solution the documentation, may to the documentation of the war plugin.

**Comment by pledbrook** [comment] 2019-03-18 15:16
@ljacomet Sure. Could I prevail on you to raise an issue for it? :smile:

**Comment by ljacomet** [comment] 2019-03-18 15:56
Done and closing this issue since the documentation will be tracked elsewhere

**Closed by ljacomet** 2019-03-18 15:56 UTC
Labels: from:contributor, in:dependency-management

**Comment by Treverix** [comment] 2019-03-19 11:06
I'm not convinced yet that this issue can only be solved with documentation. I consider renaming the projects as a workaround, because this flattens the project structure and we loose the parent/child project hierarchy which gives us the very convenient and absolutely wanted builds for all subprojects. In my example: I can build 'module-a' which is in fact a build of that impl, api and web. 

Flattening the project layout as a workaround for the war tasks issues requires another workaround to recreate or simulate the hierarchical project structure that we just lost.

I still think that the war task should be updated to properly work with all multi module builds and all project layouts.

**Comment by ljacomet** [comment] 2019-03-19 11:23
> gives us the very convenient and absolutely wanted builds for all subprojects. In my example: I can build 'module-a' which is in fact a build of that impl, api and web.

Can you explain how you achieve that?
Running `./gradlew modules:module-a:build` only results in an empty jar being produced for the `module-a` project. It does not trigger the run of api / web / impl underneath it.

> Flattening the project layout as a workaround for the war tasks issues requires another workaround to recreate or simulate the hierarchical project structure that we just lost.

Again interested in having more specific information as I do not make sense of it in this form.

> I still think that the war task should be updated to properly work with all multi module builds and all project layouts.

There is an issue with regard to _project identity_ in the setup as it stands in your sample. If you were to try to publish those to an external repository, it would fail as you would get overlapping project duos.

However I agree that aside documentation, Gradle could let you know this kind of setup causes issue.

**Comment by Treverix** [comment] 2019-03-19 13:43
> Can you explain how you achieve that?

I used gradle on intellij. When I import my dummy project, I see entries for ':modules', ':modules:module-a' and ':modules:module-b' in the tool window and each entry gives access to all tasks. Now, if I choose the build task from ':modules:module-a' it does a build on all sub projects:

```
14:28:31: Executing task 'build'...

> Task :modules:module-a:compileJava NO-SOURCE
> Task :modules:module-a:processResources NO-SOURCE
> Task :modules:module-a:classes UP-TO-DATE
> Task :modules:module-a:jar
> Task :modules:module-a:assemble
> Task :modules:module-a:compileTestJava NO-SOURCE
> Task :modules:module-a:processTestResources NO-SOURCE
> Task :modules:module-a:testClasses UP-TO-DATE
> Task :modules:module-a:test NO-SOURCE
> Task :modules:module-a:check UP-TO-DATE
> Task :modules:module-a:build
> Task :modules:module-a:api:compileJava
> Task :modules:module-a:api:processResources NO-SOURCE
> Task :modules:module-a:api:classes
> Task :modules:module-a:api:jar
> Task :modules:module-a:api:assemble
> Task :modules:module-a:api:compileTestJava NO-SOURCE
> Task :modules:module-a:api:processTestResources NO-SOURCE
> Task :modules:module-a:api:testClasses UP-TO-DATE
> Task :modules:module-a:api:test NO-SOURCE
> Task :modules:module-a:api:check UP-TO-DATE
> Task :modules:module-a:api:build
> Task :modules:module-a:impl:compileJava
> Task :modules:module-a:impl:processResources NO-SOURCE
> Task :modules:module-a:impl:classes
> Task :modules:module-a:impl:jar
> Task :modules:module-a:impl:assemble
> Task :modules:module-a:impl:compileTestJava NO-SOURCE
> Task :modules:module-a:impl:processTestResources NO-SOURCE
> Task :modules:module-a:impl:testClasses UP-TO-DATE
> Task :modules:module-a:impl:test NO-SOURCE
> Task :modules:module-a:impl:check UP-TO-DATE
> Task :modules:module-a:impl:build
> Task :modules:module-a:web:compileJava
> Task :modules:module-a:web:processResources NO-SOURCE
> Task :modules:module-a:web:classes
> Task :modules:module-a:web:jar
> Task :modules:module-a:web:assemble
> Task :modules:module-a:web:compileTestJava NO-SOURCE
> Task :modules:module-a:web:processTestResources NO-SOURCE
> Task :modules:module-a:web:testClasses UP-TO-DATE
> Task :modules:module-a:web:test NO-SOURCE
> Task :modules:module-a:web:check UP-TO-DATE
> Task :modules:module-a:web:build

BUILD SUCCESSFUL in 0s
7 actionable tasks: 7 executed
14:28:31: Task execution finished 'build'.
```

It also works when I navigate into modules/module-a and do a `gradle build` there. 

> Flattening

I used that word to describe that I included a hierarchical project layout before and the included project layout is flat after including and creating the projects based on the file paths. The folder structure is still the same - only that we have no parent/sub-projects anymore from gradle's point of view. At least that's how I understood the recommendation above (and it works on my real project, that's for sure: the war file is not complete)

> Publishing

Good point, I haven't tried that yet. I now think that I have to set the project names to what I used as maven artifact names before to keep compatibility. In maven we defined the group and artifact name on the pom. Here we only define the group and, is it correct to say that the 'artifact' name (from a maven perspective) is by default the name of the project folder?

**Comment by ljacomet** [comment] 2019-03-19 14:01
Thanks for taking the time to answer.

I was not aware of the grouping done by the IDE. And I was not aware of that command line trick. And I checked that "flattening" the projects indeed breaks that.

That's another thing to add to the documentation.

And you are perfectly right, by default the published Maven `artifactId` is equal to the project name.

I have another solution that should lift most of these issues, you can rename the projects in the `settings.gradle` file, by adding the following:

```
project(':modules:module-a:api').name = "module-a-api"
project(':modules:module-a:impl').name = "module-a-impl"
project(':modules:module-a:web').name = "module-a-web"
project(':modules:module-b:api').name = "module-b-api"
project(':modules:module-b:impl').name = "module-b-impl"
project(':modules:module-b:web').name = "module-b-web"
```

Note that this means you have to update all names in the root `build.gradle` file, where `:modules:module-a:api` needs to become `:modules:module-a:module-a-api`.

I believe this solution preserves the hierarchy and makes the project functional as well.

**Comment by Treverix** [comment] 2019-03-19 15:39
Thank YOU for taking your time! The last solution is just brilliant. The war is complete, the setup in settings even simpler and easier to communicate, at least in my case: the name is simply what we now has as the artifact name and that is used as the project name - and we can find the artifact in the maven repository by that name too. Great!

The war is complete after a war build with that setup and I can still - or again - do the convenient 'module builds' (the real project has ~30 such sub modules so this is really an asset).

Many thanks again and I hope other users will thank you for this too!

![war-build](https://user-images.githubusercontent.com/1685275/54619790-76fdaf00-4a65-11e9-8ce4-999756b2ca35.PNG)

**Comment by dsilvasc** [comment] 2019-04-15 08:14
@Treverix @ljacomet another option is to change the archivesBaseName:

```kotlin
// Keeping jar files unique works around https://github.com/gradle/gradle/issues/8791

// Use the project path instead of name for archivesBaseName
// This will generate jars like `module-a-web.jar` for `:module-a:web`
if (property("archivesBaseName") == name && rootProject != project) {
  setProperty("archivesBaseName", project.path.replace(':', '-').trim('-'))
}
// Do the same for the published artifact id.
// This will generate maven coordinates like `$group:module-a-web:$version` for `:module-a:web`
with(extensions.getByType(PublishingExtension::class.java)) {
  publications.withType(MavenPublication::class).configureEach {
    afterEvaluate {
      artifactId = project.property("archivesBaseName").toString()
    }
  }
}
```

The only problem with the second part (changing the artifactId) is that Gradle doesn't recognize it for composite builds: https://github.com/gradle/gradle/issues/8741
