### ISSUE TITLE
Passing a -- prefixed argument to JavaExec with --args is rather fragile

### ISSUE THREAD

**Issue by wilkinsona** [gradle/gradle#6644] opened 2018-09-05 16:52 UTC
### Expected Behavior

A `--` prefixed argument can be passed to `JavaExec` using `--args` reliably.

### Current Behavior

When a `--` prefixed argument is provided, `CommandLineParser` fails to notice it:

```
Caused by: org.gradle.cli.CommandLineArgumentException: No argument was provided for command-line option '--args'.
        at org.gradle.cli.CommandLineParser$KnownOptionParserState.onComplete(CommandLineParser.java:445)
        at org.gradle.cli.CommandLineParser$MissingOptionArgState.onStartOption(CommandLineParser.java:379)
        at org.gradle.cli.CommandLineParser.parse(CommandLineParser.java:92)
        at org.gradle.execution.commandline.CommandLineTaskConfigurer.configureTasksNow(CommandLineTaskConfigurer.java:61)
        ... 87 more
```

The problem can be avoided by adding a space before the `--` prefixed argument:

```
./gradlew exampleExec --args ' --foo'
```

Or `=` has to be used:

```
./gradlew exampleExec --args='--foo'
```

### Context

https://github.com/spring-projects/spring-boot/issues/1176#issuecomment-415100435

### Steps to Reproduce (for bugs)

Please see above.

### Your Environment

------------------------------------------------------------
Gradle 4.10
------------------------------------------------------------

Build time:   2018-08-27 18:35:06 UTC
Revision:     ee3751ed9f2034effc1f0072c2b2ee74b5dce67d

Kotlin DSL:   1.0-rc-3
Kotlin:       1.2.60
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_181 (Oracle Corporation 25.181-b13)
OS:           Mac OS X 10.13.6 x86_64

**Comment by oehme** [comment] 2018-09-06 07:42
I checked our tests and this could be changed, but there is a test that actually asserts the behavior reported above, i.e. "No argument specified for option --args". The question is really: What behavior is more confusing? An argument accidentally interpreted as an option or an option accidentally interpreted as an argument?

**Comment by wilkinsona** [comment] 2018-09-06 11:50
> But something like --args '--help' still won't work, because our parser will always prefer the interpretation "You're calling gradle --help".

That's a very compelling reason for requiring `=`. I'll make that recommendation in Spring Boot's documentation. Thanks for the guidance.

**Comment by oehme** [comment] 2018-09-07 08:45
Turns out we had adjusted our documentation already, based on a similar report: https://github.com/gradle/gradle/pull/5994/files

I'm gonna close this as "works as designed", since every alternative has some confusing corner cases.

**Closed by oehme** 2018-09-07 08:45 UTC

**Comment by cmacfarl** [comment] 2021-08-03 16:13
The JavaExec documentation should also be updated.  https://docs.gradle.org/current/dsl/org.gradle.api.tasks.JavaExec.html

It took me an embarrassingly long time to determine why ```args = [ '--foo bar' ]``` failed so miserably from gradle when ```--foo bar``` worked just fine from a bash shell.
