### ISSUE TITLE
Designate attributes as required

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#28076] opened 2024-02-14 15:40 UTC
[@ov7a asked me to make a new issue](https://github.com/gradle/gradle/issues/27991#issuecomment-1943432162), so here it is.

### Expected Behavior

I can designate attributes as required

```diff
 val myPluginResourcesResolver by configurations.registering {
   resolvable()
   extendsFrom(myPluginResources.get())
   attributes {
-    attribute(MyPluginResources, "foo-resources")
+    attribute(MyPluginResources, "foo-resources", required = true)
   }
 }
```

### Current Behavior (optional)

I cannot designate attributes as required.

### Context

I have a plugin. It has a custom setup of Configurations for sharing some resources between subprojects

```kotlin
// buildSrc/src/main/kotlin/my-plugin.gradle.kts

val MyPluginResources = Attribute.of("my-plugin", String::class.java)

val myPluginResources by configurations.registering {
  declarable()
}

val myPluginResourcesResolver by configurations.registering {
  resolvable()
  extendsFrom(myPluginResources.get())
  attributes {
    attribute(MyPluginResources, "foo-resources")
  }
}

val myPluginResourcesConsumable by configurations.registering {
  consumable()
  extendsFrom(myPluginResources.get())
  attributes {
    attribute(MyPluginResources, "foo-resources")
  }
}

fun Configuration.resolvable() { isCanBeResolved = true;  isCanBeConsumed = false; isCanBeDeclared = false; }
fun Configuration.consumable() { isCanBeResolved = false; isCanBeConsumed = true;  isCanBeDeclared = false; }
fun Configuration.declarable() { isCanBeResolved = false; isCanBeConsumed = false; isCanBeDeclared = true;  }
```

Resources are dynamically added to the Configuration in `:library`

```kotlin
// library/build.gradle.kts

plugins {
  id("my-plugin")
}

if (someCondition == true) {
  myPluginResources.configure {
    dependencies.add(project.dependencies.create("org.example:blah:1.2.3"))
  }
}
```

`:application` depends on `:library` 

```kotlin
// application/build.gradle.kts

plugins {
  id("my-plugin")
}

dependencies {
  myPluginResources(project(":library"))
}
```

What happens is extremely bizarre behaviour.

* If `someCondition == true` then `:application`'s `myPluginResourcesResolver` will correctly retrieve the defined files. This is expected.

* But if `someCondition ==false` then application's `myPluginResourcesResolver` will contain random files, depending on whatever other plugins `:library` has or hasn't defined. This is unexpected, confusing, and undesired.

   There's no reasonable way for `:application` to determine whether the resolved files are correct.

   Additionally, if another subproject `:ultra-application` depends on `:application` and resolves `myPluginResourcesResolver` then those random files from `:library` will be forwarded again, further exacerbating the problem while obscuring the cause.

### Artifact View

Using artifactView and filtering based on the resolved artifacts is insufficient for a few reasons

1. The Javadoc for `artifactView {}` says that it will "_only_" use the defined attributes, but it doesn't, and it will forget about attributes that have been defined (related: https://github.com/gradle/gradle/issues/26007)
2. it requires setting `lenient(true)` which hides other errors
3. it can trigger tasks in the other projects that provide the unwanted files, which can be slow and wasteful
4. it's verbose and tedious and boilerplatey

**Comment by ov7a** [comment] 2024-02-15 06:23
Closing as a duplicate of
* https://github.com/gradle/gradle/issues/28076

**Closed by ov7a** 2024-02-15 06:23 UTC
Labels: a:feature, to-triage

**Comment by aSemy** [comment] 2024-02-16 16:59
@ov7a Why did you ask me to make a new issue? Why do you think this issue is duplicating itself?

**Comment by ljacomet** [comment] 2024-02-19 09:39
That was a typo.

It is a duplicate of:
* #27991

See for an additional answer there.
