### ISSUE TITLE
Unable to start the daemon process with Gradle 3.5

### ISSUE THREAD

**Issue by sabkrish** [gradle/gradle#1910] opened 2017-04-28 11:36 UTC
I'm trying to build a Java 9 based modular project using Gradle 3.5. But, it fails with "Unable to start the gradle daemon process" message.

**Expected Behavior**
build should succeed

**Current Behavior**
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/3.5/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------

FAILURE: Build failed with an exception.

* What went wrong:
java.lang.ExceptionInInitializerError (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Steps to Reproduce (for bugs)**
1. export PATH to OpenJDK b160 build.
2. export PATH to Gradle 3.5 downloaded from https://gradle.org.
3. export GRADLE_OPTS="--add-opens java.base/java.lang=ALL-UNNAMED"
4. gradle build

It's enough to have only "apply plugin: 'java'" in the build.gradle to reproduce this problem.

As a work around, currently, i'm disabling the daemon by adding -Dorg.gradle.daemon=false option to GRADLE_OPTS.

**Your Environment**
------------------------------------------------------------
Gradle 3.5
------------------------------------------------------------
Build time:   2017-04-10 13:37:25 UTC
Revision:     b762622a185d59ce0cfc9cbc6ab5dd22469e18a6
Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          9-internal (Oracle Corporation 9-internal+0-adhoc.jenkins.openjdk.jdk9.master.build.espresso.linux.x8664)
OS:           Linux 4.4.0-66-generic amd64

**Comment by eriwen** [comment] 2017-05-01 18:00
Thanks for the well written issue @sabkrish. This is a duplicate of https://github.com/gradle/gradle/issues/1549. We plan on working on improved Java 9 support for Gradle 4.1.

**Closed by eriwen** 2017-05-01 18:00 UTC
