### ISSUE TITLE
Do not print configuration cache report location if there are 0 configuration cache issues

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#25501] opened 2023-06-23 23:09 UTC
### Expected Behavior

If a user enables configuration caching feature and it has 0 issues, there is no logging about configuration report or that there are 0 issues.

### Current Behavior (optional)

If a user enables configuration caching feature, every time there is a cache miss there is a lot about configuration cache report.

```
0 problems were found storing the configuration cache.

See the complete report at file:///ssd/ssd5/metalava-main/out/metalava/reports/configuration-cache/9abx1jq915e5vy7pkd4mmq9ik/8dcfnw97x71rm8qemh375ewz9/configuration-cache-report.html
```

ideally, none of it is printed, especially when you have 0 problems

### Context

These logs are noisy and provide little to no help when everything is good.

**Comment by jbartok** [comment] 2023-06-26 08:27
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #24248

Please add your use case and 👍 to that issue.

**Closed by jbartok** 2023-06-26 08:27 UTC
Labels: a:feature, in:console, in:configuration-cache, closed:duplicate
