### ISSUE TITLE
buildSrc precompiled script plugin named `init.gradle.kts` causes obscure error: Failed to apply plugin class, Char sequence is empty

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#23804] opened 2023-02-07 10:00 UTC
### Expected Behavior

Creating a script `./buildSrc/src/main/kotlin/init.gradle.kts` either works, or fails with an understandable error.

### Current Behavior

Creating a script `./buildSrc/src/main/kotlin/init.gradle.kts` doesn't work works and fails with a non-understandable error.

### Context

Because IntelliJ has problems editing init scripts https://youtrack.jetbrains.com/issue/KTIJ-20694 I thought I would try creating one in buildSrc, because I hoped that IDE support would be available. 

However, when I create an empty file `./buildSrc/src/main/kotlin/init.gradle.kts` Gradle fails with a strange error:

```bash
$ ./gradlew assemble

FAILURE: Build failed with an exception.

* Where:
Build file '.../buildsrc-init/buildSrc/build.gradle.kts' line: 1

* What went wrong:
An exception occurred applying plugin request [id: 'org.gradle.kotlin.kotlin-dsl', version: '2.3.3']
> Failed to apply plugin class 'org.gradle.kotlin.dsl.plugins.precompiled.PrecompiledScriptPlugins'.
   > Char sequence is empty.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
```

### Steps to Reproduce 

1. create an empty file `./buildSrc/src/main/kotlin/init.gradle.kts`
2. `./gradlew assemble`

Sample project: [buildsrc-init.zip](https://github.com/gradle/gradle/files/10673783/buildsrc-init.zip)

### Your Environment

* Gradle 7.6

### Related

* similar error message: https://github.com/gradle/gradle/issues/17831

**Comment by eskatos** [comment] 2023-02-07 16:50
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/17831

----

This has already been fixed in

* https://github.com/gradle/gradle/pull/23706

The fix will ship with Gradle 8.1

**Closed by eskatos** 2023-02-07 16:50 UTC
Labels: in:kotlin-dsl, closed:duplicate
