### ISSUE TITLE
Build fails if there are exclusiveContent repository declaration and a plugin which adds dependency

### ISSUE THREAD

**Issue by naftalmm** [gradle/gradle#14232] opened 2020-08-20 13:50 UTC
I wrote a plugin containing following codeline in the `apply` method:
```kotlin
project.dependencies.add("unojar", "com.needhamsoftware.unojar:core:+")
```

When I'm applying this plugin to buildscript of my another project containing the following repository: 

```kotlin 
repositories {
    exclusiveContent {
        forRepository {
            ivy {
                isAllowInsecureProtocol = true
                url = uri("http://anonsvn.icesoft.org/repo/maven2/releases/")
                patternLayout {
                    setM2compatible(true)
                    //http://anonsvn.icesoft.org/repo/maven2/releases/org/icepdf/os/icepdf-core/6.3.0/icepdf-core-6.3.0.jar
                    artifact("[organization]/[module]/[revision]/[artifact]-[revision].[ext]")
                    artifact("[organization]/[module]/[revision]/[artifact]-[revision]-[type].[ext]")
                    metadataSources { artifact() }
                }
            }
        }
        filter {
            includeGroup("org.icepdf.os")
        }
    }
}
```

`tasks` task (and any other) fails with error:

```
Cannot mutate content repository descriptor 'BintrayJCenter' after repository has been used
```

pointing at line 
```
   includeGroup("org.icepdf.os")
```

in my buildscript.

Everything works fine if I:

a) comment out that line in plugin.
OR
b) replace `exclusiveContent` repository declaration with the simple one:

```kotlin 
repositories {
            ivy {
                isAllowInsecureProtocol = true
                url = uri("http://anonsvn.icesoft.org/repo/maven2/releases/")
                patternLayout {
                    setM2compatible(true)
                    //http://anonsvn.icesoft.org/repo/maven2/releases/org/icepdf/os/icepdf-core/6.3.0/icepdf-core-6.3.0.jar
                    artifact("[organization]/[module]/[revision]/[artifact]-[revision].[ext]")
                    artifact("[organization]/[module]/[revision]/[artifact]-[revision]-[type].[ext]")
                    metadataSources { artifact() }
                }
            }
}
```

Build scan URL:
https://scans.gradle.com/s/cz5tk4vo2ddeu

**Comment by naftalmm** [comment] 2020-09-01 13:20
Manage to construct minimal example for this issue reproduction (only 4 lines of plugin code).
Actually there is one more line in `apply` method of plugin, removing of which (or moving it inside `tasks.register` closure) makes everything work fine:
```kotlin
val unoJarCoreContents = project.configurations.getByName("unojar").map { project.zipTree(it) }
```
[GradlePluginIssue.zip](https://github.com/gradle/gradle/files/5156421/GradlePluginIssue.zip)

**Comment by melix** [comment] 2020-09-08 15:41
This isn't a Gradle bug but the expected behavior. When you apply your plugin, the line you copied above will be executed _before_ the repositories block in your build script is called.

This:

```
project.configurations.getByName("unojar").map { ... }
```

Will trigger resolution, which will in turn use the repositories. This means that when the `repositories { ... }` block is called after, you're trying to mutate a repository which has already been used.

Depending on why you need the `unoJarCoreContents` for, you might want to defer resolution later.

**Comment by naftalmm** [comment] 2020-09-08 16:04
Yes, in the end I've managed to workaround this problem by deferring configuration resolution.
But for me it seems as a very strange behavior (and/or very confusing error message):
1. Repository used by plugin is `project.repositories.jcenter()`
2. This repository is not even mensioned in the `repositories { ... }` block of buildscript. So it is not mutated.
3. There is no error if `repositories { ... }` block of buildscript contains simple (non-exclusiveContent) repositories declaration.

**Comment by melix** [comment] 2020-09-08 16:10
There's no difference between the repositories used by your plugin and the repositories declared in the script. There's no isolation: the point of a plugin is that it can interact with the project, mutate it, ... So the "repositories" you see in the plugin _are_ the same as the ones in the build script.

Because your plugin eagerly triggers resolution, it's using the "repositories" block of the build script. For consistency, the repositories _must not_ be mutated after resolution happens (because otherwise depending on _when_ something is resolved, you could get artifacts from different repositories). Therefore we have to prevent you from mutating any repository.

**Comment by naftalmm** [comment] 2020-09-08 16:23
What is the difference between repository _mutation_ and _declaration_?

Maybe I don't understand something, but for me it seems that the only thing that mutates here is _repositories list_, but both _repositories_ (jcenter and the one in buildscript) are just declared.
And as there is no error if repositories { ... } block of buildscript contains simple (non-exclusiveContent) repositories declaration, it seems that mutation of _repositories list_ is not prohibited...

**Comment by naftalmm** [comment] 2020-09-08 16:28
It looks like declarartion of exclusiveContent repository mutates other repositories...

**Comment by melix** [comment] 2020-09-08 16:29
Yes sorry I wasn't clear, that's the missing piece. Because you're declaring an _exclusive_ filter, it has to know about all other repositories. So mutating _one_ repository is equivalent to mutating _any of them_ in practice.

**Comment by ljacomet** [comment] 2020-09-08 16:32
To be complete:
* Adding repositories is kind of OK because any resolution prior to the addition will not be impacted since a result was found, which means it must be in the repositories defined before the addition.
* Ideally Gradle should disable all repositories mutation once resolution has happened. But that is a breaking change, so hard to enforce in practice without a long deprecation warning phase.

My first point is only half correct because adding a repository could change the result of using dynamic versions.

**Comment by ljacomet** [comment] 2020-09-09 09:27
Closing as there is no fix to be done on the Gradle side

**Closed by ljacomet** 2020-09-09 09:27 UTC
Labels: @jvm, from:contributor, in:dependency-management
