### ISSUE TITLE
Transitive dependencies from custom configuration type are not being pulled 

### ISSUE THREAD

**Issue by joao-borges** [gradle/gradle#9494] opened 2019-05-21 21:52 UTC
Hello,

I have a custom plugin that creates a custom configuration type named `bundle`.
Bundles in my case are text files with xml content on it. Doing this I could manage to add those files as artifact dependencies to other projects.

This works as expected. But when the `bundle` projects are published together with a POM file to any repository, I can add the dependency as well to any other project, but at this point the transitive dependencies are not being pulled and packaged in the secondary project.

Digging a little with debug logs I can see messages saying that my `bundle` dependency was being processed and there was no jar file for it, so its pom was ignored. And yes, there is no jar file because the artifact is only a text file, but the project configuration could have other files or jars as dependencies (that are required for some content of my bundle xml files) and I wanted to have those dependencies pulled together, which are not happening.

```
14:41:12.971 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.MavenResolver] POM file found for module 'com.ca.apim.otk:apim-otk-poc:5.0.0-SNAPSHOT' in repository 'MavenLocal' but no artifact found. Ignoring.
```

Looking to this log seems like gradle is ignoring the fact that my artifact is a file and not a package, and I can ensure that it is there in the local maven repository.

This is my plugin source code definition:
https://github.com/ca-api-gateway/gateway-developer-plugin/blob/master/gateway-developer-plugin/src/main/java/com/ca/apim/gateway/cagatewayconfig/CAGatewayDeveloper.java

And my project A is publishing this pom:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.ca.apim.otk</groupId>
  <artifactId>apim-otk-poc</artifactId>
  <version>5.0.0-SNAPSHOT</version>
  <packaging>bundle</packaging>
  <name>apim-otk-poc</name>
  <organization>
    <name>CA API Management</name>
  </organization>
  <dependencies>
    <dependency>
      <groupId>otk-assertions</groupId>
      <artifactId>otk-assertions</artifactId>
      <version>1</version>
      <classifier>bundle</classifier>
    </dependency>
    <dependency>
      <groupId>com.ca.apim.otk</groupId>
      <artifactId>OTKDatabaseAssertion</artifactId>
      <version>1.0.0-SNAPSHOT</version>
      <classifier>assertion</classifier>
    </dependency>
  </dependencies>
</project>
```

And my project B has this artifact as dependency:

```
dependencies {
    bundle group: 'com.ca.apim.otk', name: 'apim-otk-poc', version: '5.0.0-SNAPSHOT', ext: 'bundle'
}
```

But I miss the transitive dependencies when looking into project B.

Please advise, thank you.

**Comment by ljacomet** [comment] 2019-06-04 14:25
This is a use case where [Gradle Module Metadata](https://blog.gradle.org/gradle-metadata-1.0) could help. I strongly recommend looking into it as a way to resolve the problem.

By leveraging Maven metadata, for non standard POM packaging, and relying on the Maven - Gradle integration, you are bound to encounter issues that can come from different sources:
* Effectively abusing the POM format
* Non supported cases in the POM support in Gradle itself

Because the Gradle Module Metadata by design has a much more open format, you should not encounter the same limitations.

**Comment by joao-borges** [comment] 2019-06-06 16:48
Hi @ljacomet, thank you for the answer. 
However, upgrading my project to gradle 5 or 6 is not an option at the moment. Do you know if there is any workaround for this using gradle 4.10.x?

Thank you

**Comment by jjohannes** [comment] 2019-10-01 16:01
@joao-borges in case this is still an issue for you:

If you can use another extension as `bundle`, I think it should work with POMs, because Gradle (and Maven) would look at an artifact with an extension matching the `packaging` in the pom. Only, for some extensions it does not work, because they are "special" packagings which are reserved for JARs with a certain structure (see full list of these extensions [here](https://github.com/gradle/gradle/blob/080a178ee9683c8e40cbe1b113e2d18c8ae43959/subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/maven/DefaultMavenModuleResolveMetadata.java#L57)). `bundle` is in that list.

I am closing this, as there is nothing we can do for already released versions.

If you have further questions, please start a discussion in the [forum](https://discuss.gradle.org/).

**Closed by jjohannes** 2019-10-01 16:01 UTC
Labels: from:contributor, in:dependency-management
