### ISSUE TITLE
Deprecation warnings when calling getResolvedConfiguration()

### ISSUE THREAD

**Issue by martin-linha** [gradle/gradle#1407] opened 2017-02-15 08:24 UTC
### Expected Behavior
No warnings should be printed when calling getResolvedConfiguration()

### Current Behavior
In my build.gradle script I use

`configurations.runtime.resolvedConfiguration
`
to work with resolved artifacts. As soon as I add a compile dependency to some project with notation

`compile project('project')`

I get warnings in my output similar to

`The ProjectDependency.getProjectConfiguration() method has been deprecated and is scheduled to be removed in Gradle 4.0.
	at build_egfxhkqkkdf06ne62q4y2xw1r$_run_closure12$_closure36$_closure37.doCall(xxx/build.gradle)
ModuleDependency.getConfiguration() has been deprecated and is scheduled to be removed in Gradle 4.0. Use ModuleDependency.getTargetConfiguration() instead.
	at build_egfxhkqkkdf06ne62q4y2xw1r$_run_closure12$_closure36$_closure37.doCall(xxx/build.gradle)`

Looks like you call these two methods internally and then it causes the warning to be printed out.

### Steps to Reproduce (for bugs)
Use the following

`
apply plugin: 'java'
dependencies {
    compile project(':second.project')
}

configurations.runtime.resolvedConfiguration
`

### Your Environment
Gradle 3.3

**Comment by eriwen** [comment] 2017-02-15 18:29
This seems to be a duplicate of https://github.com/gradle/gradle/issues/1311. As mentioned in that issue, I believe you ought to get the `targetConfiguration` instead. Please read the resolution of #1311 for more info.

**Comment by martin-linha** [comment] 2017-02-16 12:51
Hi eriwen

I don't think it's a duplicate. I tried to change my script to use 

`compile project(path: ':second.project', configuration: 'default')`

Please note that this line:

`configurations.runtime.resolvedConfiguration`

causes the depreciation warning to be printed out. Looks like this is different issue then #1311. For me it looks like you are internally in `getResolvedConfiguration()` calling `ProjectDependency.getProjectConfiguration()` instead of `ModuleDependency.getTargetConfiguration()`

**Comment by bmuschko** [comment] 2017-07-31 22:09
@martin-linha I believe the deprecation has been removed with Gradle 4.0. Can you please check again?

**Comment by oehme** [comment] 2017-08-16 12:43
This method no longer exists.

**Closed by oehme** 2017-08-16 12:43 UTC
Labels: a:bug, from:contributor
