### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by sunshixiong789** [gradle/gradle#6535] opened 2018-08-28 02:46 UTC
### Context

![image](https://user-images.githubusercontent.com/31101988/44697699-801a3500-aaaf-11e8-9e5a-136f784b0a5e.png)
I hope your can resolve it
### Your Environment

 * Build scan URL:

**Comment by trevjonez** [comment] 2018-08-28 03:38
https://github.com/gradle/gradle/issues/3118#issuecomment-415960625

**Comment by oehme** [comment] 2018-08-28 07:12
Duplicate of #3118

**Closed by oehme** 2018-08-28 07:12 UTC
