### ISSUE TITLE
Native + GoogleTest: Working directory inside tests is not workingDir set by RunTestExecutable

### ISSUE THREAD

**Issue by philmcardle** [gradle/gradle#920] opened 2016-11-24 15:41 UTC
The working directory in which the test code runs is not the working directory specified by the task in Gradle.

### Expected Behavior
The working directory for the test code should be `workingDir` as set in the RunTestExecutable / AbstractExecTask task, which by default is the `projectDir`.

### Current Behavior
The working directory for the test code is `buildDir/test-results/<test>/<flavor>/`

### Context
When running tests from the Gradle command-line, the working directory is not what we expect, nor do we appear to have any control over it from within Gradle.

### Steps to Reproduce (for bugs)
https://github.com/gradle/gradle/tree/master/subprojects/docs/src/samples/native-binaries/google-test

See that the `workingDir` of all tasks withType RunTestExecutable is the `projectDir`, e.g.

    tasks.withType(RunTestExecutable) {
        println "* ${workingDir}"
    }

See that the actual working directory of the test code being run is the task's `outputDir`

	int main(int argc, char **argv) {
	    printf("* CWD: %s\n", _getcwd(nullptr, 0));
	    ...

### Your Environment
Windows 10 1607, MSVC 2013, Gradle 3.2.1

**Comment by lacasseio** [comment] 2016-11-25 18:03
Thanks @philmcardle for the high-quality issue. There is effectively unexpected behavior around the working directory. The issue comes from [this line](https://github.com/gradle/gradle/blob/master/subprojects/testing-native/src/main/java/org/gradle/nativeplatform/test/tasks/RunTestExecutable.java#L50).

Some history always helps understand the problem. The first test framework to be supported in Gradle was CUnit. This test framework is extremely inflexible. You basically have to do everything yourself. Gradle tries to output a sensible `main()` to create a more enjoyable experience with that test framework.

When Google Test was contributed to Gradle, the CUnit foundation was duplicated. Google Test has been a much more advanced testing framework, it still has to live with the limitation imposed by CUnit.

That been said, we will consider your use case when improving the native testing.

**Comment by ddresser** [comment] 2016-12-01 15:30
FWIW, I just ran into this same bug.  Thanks for pointing out that it is actually the outputDir that is currently being forced.

**Comment by lacasseio** [comment] 2019-09-11 19:02
No additional work will be done on the software model plugins unless it's a blocker for current users. This is not a blocker so I'm closing this issue. Reopen on [gradle/gradle-native](https://github.com/gradle/gradle-native).

The Google Test support will be reintroduce at some point in the future. At the moment, the `cpp-unit-test` plugin for the new native plugins gives more or less the same benefit.

**Closed by lacasseio** 2019-09-11 19:02 UTC
Labels: a:bug, from:contributor, in:native-platform

**Comment by rrrooommmaaa** [comment] 2019-11-11 21:30
@lacasseio I'm trying to run tests in gdb debugger on Linux starting googletest generated executable and it's a problem because the program is looking for test files and can't find them. Should I specify some parameter or debug it differently?
