### ISSUE TITLE
A Suggestion about your China CDN

### ISSUE THREAD

**Issue by BROBIRD** [gradle/gradle#9291] opened 2019-04-25 18:31 UTC
### Expected Behavior
An automated redirection from `https://services.gradle.org/distributions/<something>.zip` or `https://downloads.gradle.org/distributions/<something>.zip` to China CDN `https://downloads.gradle-dn.com/distributions/<something>.zip`

### Current Behavior
Just a Cloudflare CDN, very slow in China.

### Context
I think it's better to redirect the download links to China CDN for users in China.
Cloudflare provides a function named `IP Geolocation`, so I think you can set some redirect rules using the header `CF-IpCountry` so that we users will not need to modify the file `gradle\wrappers\gradle-wrapper.properties` or download the `.zip` files manually.

I think there are two options:

0. Configure redirection rules on your original server.
1. Use the Workers function provided by Cloudflare.

**example code:**
```
addEventListener('fetch', event => {
event.respondWith(handleRequest(event.request))
})

async function handleRequest(request) {
  let url = new URL(request.url)
  if (url.pathname == "/") {
    let country = request.headers.get("CF-IpCountry")
    if(country=="CN"){
      url.host = "test.example.com"
    }
    return Response.redirect(url, 302)
  }
}
```

**Comment by wusatosi** [comment] 2019-07-21 14:30
agree!

**Comment by ldaley** [comment] 2019-07-29 02:06
The redirect was not in place due to a regression. It is now fixed. Please try again.

**Comment by wusatosi** [comment] 2019-07-29 02:38
> The redirect was not in place due to a regression. It is now fixed. Please try again.

![image](https://user-images.githubusercontent.com/26424577/62018087-cdd17d00-b1eb-11e9-9f23-4c7f39e5caef.png)
![image](https://user-images.githubusercontent.com/26424577/62018232-68ca5700-b1ec-11e9-91a7-4a692bf0285c.png)

I can confirm the redirect and downloads.gradle-dn.com is working and serving within China! 

The cache is cold though, I think Cloudflare will handle it soon 😄 
![image](https://user-images.githubusercontent.com/26424577/62018303-bcd53b80-b1ec-11e9-9393-013b362f156f.png)

Thanks for the excellent work

**Comment by ldaley** [comment] 2019-07-29 02:44
Thanks for confirming.

**Closed by ldaley** 2019-07-29 02:44 UTC
Labels: a:feature

**Comment by wusatosi** [comment] 2019-07-29 02:55
> Thanks for confirming.

Thanks for you guys' great work
