### ISSUE TITLE
Configuration cache entry discarded but 0 problems were found

### ISSUE THREAD

**Issue by Goooler** [gradle/gradle#22868] opened 2022-11-27 17:26 UTC
### Expected Behavior
Configuration cache entry stored or reused.

### Current Behavior
Configuration cache entry discarded.

### Context
Ref the [CC doc](https://docs.gradle.org/current/userguide/configuration_cache.html), configuration cache entry was discarded due to some problems, but in my case, no problem found.

### Steps to Reproduce 
Enable stable config cache, see this issue.

You can repro this issue on https://github.com/LawnchairLauncher/lawnchair/pull/3134.
### Your Environment

Java 19 & Gradle 7.6 & Kotlin 1.7.20 & AGP 7.3.1

Build scan URL: https://scans.gradle.com/s/conan2vso6dzq

**Comment by Goooler** [comment] 2022-11-27 17:28
I've retried, this issue happened without stable CC enabling.

**Comment by mlopatkin** [comment] 2022-11-29 10:38
Thank you for the report! This is an instance of #21290: the build has tasks declared as `notCompatibleWithConfigurationCache`, but Gradle provides no information about this. FWIW, the offending task is one of google/play-services-plugins#206.

I'm closing this issue as a duplicate of #21290.

**Closed by mlopatkin** 2022-11-29 10:38 UTC
Labels: a:bug, to-triage
