### ISSUE TITLE
Allow user to rerun only failed tests

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#4068] opened 2018-01-17 22:59 UTC
### Expected Behavior
Like SBT, I'd like to optionally execute only the tests that failed. Like https://github.com/gradle/gradle/pull/2036, but also supporting the `check` task. 

We might implement this on the `Test` task first to avoid the complexity of trying to implement for all ecosystems at once. 

### Current Behavior
As of Gradle 4.5, Gradle always runs all tests when a `Test` task is executed.

### Context
This has been asked for a few times on twitter, and I think would be a nice UX compliment to #1310 if we are able to deliver there.

**Comment by oehme** [comment] 2018-01-18 08:36
Duplicate of #2644

**Closed by oehme** 2018-01-18 08:36 UTC
Labels: a:feature, from:member, in:testing
