### ISSUE TITLE
SystemPropertyCallSite.call regression in Gradle 6.5.1

### ISSUE THREAD

**Issue by rpalcolea** [gradle/gradle#13701] opened 2020-07-07 01:09 UTC
Hi folks,

Giving this build file:

```
task printMyHost {
    doFirst {
        def myHost = System.getProperty('myhost', findProperty('myhost'))
        println "MY HOST: " + myHost
    }
}

```

When executing the task in `6.5`, we can see the following:

```
./gradlew myTask                                                                                                                                ✔  took 9s   10338  at 18:05:39   11.0.7+10 

> Task :myTask
MY HOST: null

BUILD SUCCESSFUL in 738ms
1 actionable task: 1 executed
```

However, with Gradle 6.5.1, we get the following exception:

```
* Where:
Build file '/Users/rperezalcolea/Projects/github/nebula-plugins/gradle-nebula-integration/system-property-issue/build.gradle' line: 3

* What went wrong:
Execution failed for task ':myTask'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Caused by: java.lang.NullPointerException
        at org.gradle.internal.classpath.Instrumented$SystemPropertyCallSite.call(Instrumented.java:435)
        at build_ez40ldtqk6rt0k1epnvu1r9ev$_run_closure1$_closure2.doCall(/Users/rperezalcolea/Projects/github/nebula-plugins/gradle-nebula-integration/system-property-issue/build.gradle:3)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:669)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:642)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.run(ExecuteActionsTaskExecuter.java:569)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:395)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:387)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:84)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
```

I suspect this is related to this change introduced in 6.5.1: https://github.com/gradle/gradle/pull/13585/files

**Comment by bmuskalla** [comment] 2020-07-07 06:56
I currently can't find it but I believe @adammurdoch was already working on this.

**Comment by ljacomet** [comment] 2020-07-07 07:28
Duplicate of #13652

**Closed by ljacomet** 2020-07-07 07:28 UTC
Labels: a:bug, from:contributor
