### ISSUE TITLE
Cannot create service of type DefaultBuildEventsListenerRegistry

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#17783] opened 2021-07-20 17:48 UTC
Context: https://issuetracker.google.com/193859160

Using the [MyApplication.zip](https://github.com/gradle/gradle/files/6850261/MyApplication.zip) and running `cd buildSrc && gw test`, this fails with `Caused by: org.gradle.internal.service.ServiceCreationException: Cannot create service of type DefaultBuildEventsListenerRegistry using DefaultBuildEventsListenerRegistry constructor as required service of type BuildEventListenerFactory for parameter #1 is not available.`

It seems that when using the `ProjectBuilder` to create a test project, not all services are created. This is an issue because plugins applying AGP in tests will fail as AGP registers an `OperationCompletionListener` instance during application.

**Comment by th-jtullgren** [comment] 2021-08-14 01:25
Hi is there any workaround for this issue?  Half of our unit tests for our Gradle plugin (which depends on the Android Gradle Plugin) now fail.

Thanks!

**Comment by donat** [comment] 2021-08-17 09:10
@th-jtullgren issuetracker.google.com/193859160 contains a workaround.

**Comment by donat** [comment] 2021-08-17 09:10
The issue is still present in Gradle 7.1.1.

**Comment by th-jtullgren** [comment] 2021-08-17 16:04
The workaround found in issuetracker.google.com/193859160 worked for me. thanks

**Comment by sdeleuze** [comment] 2021-11-17 13:23
This bug impacts likely any project testing Kotlin Gradle plugin as of version 1.6.0, see https://youtrack.jetbrains.com/issue/KT-49547 for more details, Spring is impacted.

**Comment by eskatos** [comment] 2021-11-17 14:55
Duplicate of https://github.com/gradle/gradle/issues/16774

**Closed by eskatos** 2021-11-17 14:55 UTC
Labels: a:bug, @configuration-cache, 🌱 onboarding, in:invoking-gradle
