### ISSUE TITLE
UP-TO-DATE check ignores empty directory in 7.4-rc-1

### ISSUE THREAD

**Issue by bingranl** [gradle/gradle#19633] opened 2022-01-20 00:47 UTC
Given the android library project attached
[UpToDateCheckRepo.tar.gz](https://github.com/gradle/gradle/files/7901402/UpToDateCheckRepo.tar.gz)

1. Run `gradle lib:bundleLibResDebug`
2. Add a empty directory `testDir` under `UpToDateCheckRepo/lib/src/main/resources/`(there is already a dummy file `foo.txt` under resources directory)
3. Run `gradle lib:bundleLibResDebug --console=plain` and check the status of `> Task :lib:bundleLibResDebug`

### Expected Behavior

`:lib:bundleLibResDebug` should be executed when running with gradle 7.3.3 and 7.4-rc-1

### Current Behavior

`:lib:bundleLibResDebug` is UP-TO-DATE when running with 7.4-rc-1(it got executed with 7.3.3)

### Context

Android Gradle Plugin is trying to upgrade gradle version from 7.3.3 to 7.4-rc-1.

**Comment by wolfs** [comment] 2022-01-20 09:11
I am pretty sure this is this (intentional) change: https://docs.gradle.org/7.4-rc-1/userguide/upgrading_version_7.html#empty_directories_file_tree

What kind of input does `bundleLibResDebug` declare, is it using `@InputDirectory`? Is this a problem for the task or is it fine for it to ignore empty directories?

**Comment by wolfs** [comment] 2022-01-21 10:51
This is the class which declares the inputs: https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:build-system/gradle-core/src/main/java/com/android/build/gradle/internal/tasks/BundleLibraryJavaRes.kt;l=143?q=BundleLibraryJavaRes

The relevant sections there are:
```kotlin
    // We cannot use @Classpath as it ignores empty directories which may be used as Java resources.
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    @get:SkipWhenEmpty
    @get:Optional
    abstract val resources: ConfigurableFileCollection
```

```kotlin
        private fun computeResourcesForTaskInput(projectJavaRes: FileCollection): Any {
            return projectJavaRes.elements.map {
                it.flatMap { fsLocation ->
                    fsLocation.asFile.walk().filter { f ->
                        if (f.isDirectory && f == fsLocation.asFile) return@filter false
                        MergeJavaResourceTask.predicate.test(f.extension)
                    }.sortedBy(File::invariantSeparatorsPath)
                }
            }
        }
```

So the problem is that `computeResourcesForTaskInput` basically flattens the hierarchy, so there is only a list of files and directories, each being at the root. The change in Gradle 7.4 is that for relative path sensitivity, we ignore directories at the root completely. In 7.3 we already ignored the name of the directory. So for example renaming a resource directory already didn't mark the task as out-of-date.

As a solution, you can register the input via the runtime API using `ignoreEmptyDirectories(false)`:
```kotlin
val resources = project.files()
resources.from(projectJavaRes)
inputs
    .files(
        resources.filter { isNotEmptyDirectory(it) }
            .asFileTree
            .matching(MergeJavaResourcesTask.patternSet)
    )
    .withPropertyName("resources")
    .skipWhenEmpty()
    .ignoreEmptyDirectories(false)
    .withPathSensitivity(PathSensitivity.RELATIVE)
```

**Comment by wolfs** [comment] 2022-01-27 10:41
I am closing the issue now. If this is still a problem, please re-open.

**Closed by wolfs** 2022-01-27 10:41 UTC
Labels: a:bug, @execution, in:execution-engine
