### ISSUE TITLE
Build of Gradle 7.4 requires --no-configuration-cache option

### ISSUE THREAD

**Issue by freswa** [gradle/gradle#19845] opened 2022-02-08 12:20 UTC
### Expected Behavior
Build from souce succeeds

### Current Behavior
Build from source fails. Adding `--no-configuration-cache` fixes the issue.

```
0 problems were found storing the configuration cache.

See the complete report at file:///build/gradle/src/gradle-7.4/build/reports/configuration-cache/eq7vw1q31zmmfanwxxuw4r5o2/9k8wuqcgeyhe169umm9b13qb8/configuration-cache-report.html

FAILURE: Build failed with an exception.

* What went wrong:
Tasks unsupported with the configuration cache were scheduled: :docs:docs, :docs:stageDocs, :docs:userguide, :docs:userguideSinglePagePdf, :docs:userguideSinglePageHtml and more...

  The gradle/gradle build enables the configuration cache as an experiment.
  It seems you are using a feature of this build that is not yet supported.

  You can disable the configuration cache with `--no-configuration-cache`.
  You can ignore problems with `--configuration-cache-problems=warn`.

  Please see further instructions in CONTRIBUTING.md
```

### Context
We're building the ArchLinux package

### Steps to Reproduce 
Build Gradle 7.4 with `./gradlew installAll -PfinalRelease=true -Pgradle_installPath="$(pwd)/dist"`

### Your Environment
ArchLinux;
openjdk 11

**Comment by ljacomet** [comment] 2022-02-09 09:37
This is caused by the Gradle build dogfooding features early and a fix for this exists on the main branch.

As you found out, you need to add that flag for some tasks.

**Closed by ljacomet** 2022-02-09 09:37 UTC
Labels: in:configuration-cache
