### ISSUE TITLE
`settingsEvaluated {}` doesn't run

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#27741] opened 2024-01-18 13:57 UTC
### Current Behavior

`settingsEvaluated {}` does not work as per the documentation: Does not add an action to be called when the build settings have been loaded and evaluated.

### Expected Behavior

`settingsEvaluated {}` works as per the documentation: Adds an action to be called when the build settings have been loaded and evaluated.

### Steps to Reproduce

```kotlin
// build.gradle.kts

project.gradle.settingsEvaluated {
  error("why isn't settings evaluated?")
}
```

When running any task the error is not triggered. 

### Gradle version

8.5

**Comment by rpalcolea** [comment] 2024-01-19 19:52
I believe this is because you are registering the closure after the `Project` object has been created which might be already late. Per https://docs.gradle.org/current/userguide/build_lifecycle.html#sec:build_phases , the `settingsEvaluated` closure will be used before a `Project` object is created. 

Typically you want to register a `settingsEvaluated` closure at `settings.gradle` file or when creating `Settings` or `Gradle` plugins, not a Project level ones or build scripts

https://github.com/gradle/gradle/issues/17914#issue-957953303 talks more about this

**Comment by cobexer** [comment] 2024-01-23 13:17
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #17914

Please add your use case and 👍 to that issue.

**Closed by cobexer** 2024-01-23 13:17 UTC
Labels: a:bug, to-triage
