### ISSUE TITLE
DefaultTaskCollection#configureEach(Action) on task set cannot be executed in the current context since 8.10.1

### ISSUE THREAD

**Issue by tom-mi** [gradle/gradle#30497] opened 2024-09-11 14:50 UTC
### Current Behavior

We experience sporadic build failures with error messages like this:
```
Could not determine the dependencies of task ':foo:compileKotlin'.
> Could not create task ':foo:checkKotlinGradlePluginConfigurationErrors'.
   > DefaultTaskCollection#configureEach(Action) on task set cannot be executed in the current context.
```
This started when upgrading from version `8.10.0` to `8.10.1`.

The error occurs in our pipelines & locally and seems to go away when running the build a second (or third, or fourth) time.
The error also does not occur always, but only sometimes, so it is very much fun to reproduce :(

When running `./gradlew build` directly after the error occured, the build succeeds.

### Expected Behavior

Successful build

### Self-contained Reproducer Project

https://github.com/tom-mi/gradle-8.10.1-build-issue-demo

### Gradle version

8.10.1

### Your Environment (optional)

We run this on corretto21 on AWS CodeBuild. But the error also occurs when building locally, also with corretto21, at least on thefollowing operating systems:
* ArchLinux
* AmazonLinux
* MacOS

**Comment by ganadist** [comment] 2024-09-12 01:40
I got same build failure with following stacktrace since Gradle 8.10.1

```
Could not create task ':xxxxxx:checkKotlinGradlePluginConfigurationErrors'.
> DefaultTaskCollection#configureEach(Action) on task set cannot be executed in the current context.
  Exception
  org.gradle.api.internal.tasks.TaskDependencyResolveException: Could not determine the dependencies of task ':camera:compileDebugKotlin'.    
    at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:70)    
    •••
    Caused by: org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreationException: Could not create task ':camera:checkKotlinGradlePluginConfigurationErrors'.    
at org.gradle.api.internal.tasks.DefaultTaskContainer.taskCreationException(DefaultTaskContainer.java:722)    
      •••
      Caused by: org.gradle.api.internal.AbstractMutationGuard$IllegalMutationException: DefaultTaskCollection#configureEach(Action) on task set cannot be executed in the current context.    
        at org.gradle.api.internal.AbstractMutationGuard.createIllegalStateException(AbstractMutationGuard.java:39)    
        •••
        at org.jetbrains.kotlin.gradle.plugin.VariantImplementationFactories$Companion$getProvider$2$1.invoke(VariantImplementationFactories.kt:107)    
        at org.jetbrains.kotlin.gradle.plugin.VariantImplementationFactories$Companion$getProvider$2$1.invoke(VariantImplementationFactories.kt:106)    
        at org.jetbrains.kotlin.gradle.utils.SingleAction.run(singleAction.kt:30)    
        at org.jetbrains.kotlin.gradle.plugin.VariantImplementationFactories$Companion.getProvider(VariantImplementationFactories.kt:106)    
        at org.jetbrains.kotlin.gradle.plugin.VariantImplementationFactories$Companion.get(VariantImplementationFactories.kt:113)    
        at org.jetbrains.kotlin.gradle.internal.IdeaKt.isInIdeaSync(idea.kt:16)    
        at org.jetbrains.kotlin.gradle.plugin.diagnostics.ToolingDiagnosticRenderingOptions$Companion.forProject(ToolingDiagnosticRenderingOptions.kt:28)    
        at org.jetbrains.kotlin.gradle.plugin.diagnostics.CheckKotlinGradlePluginConfigurationErrorsKt$locateOrRegisterCheckKotlinGradlePluginErrorsTask$taskProvider$1.execute(CheckKotlinGradlePluginConfigurationErrors.kt:59)    
        at org.jetbrains.kotlin.gradle.plugin.diagnostics.CheckKotlinGradlePluginConfigurationErrorsKt$locateOrRegisterCheckKotlinGradlePluginErrorsTask$taskProvider$1.execute(CheckKotlinGradlePluginConfigurationErrors.kt:47) 
```

**Comment by Jankaz2** [comment] 2024-09-12 07:06
My project builds successfully after running the `./gradlew --stop` command

**Comment by mkondratek** [comment] 2024-09-12 11:26
I have encountered the same issue. I work with gradle intellij platform plugin v2 and gradle 8.10.1. I am going to downgrade gradle.

**Comment by Jankaz2** [comment] 2024-09-12 11:28
stopping gradle's deamon before building the projects helps 
`./gradlew --stop`
`./gradlew build`

**Comment by ov7a** [comment] 2024-09-12 12:50
This is a regression, that relates to:
* https://github.com/gradle/gradle/issues/30472

A workaround is to run with `--no-daemon`. We're working on fixing it.

**Comment by EdGue42** [comment] 2024-09-18 13:33
> A workaround is to run with `--no-daemon`. We're working on fixing it.

I updated our gradle build to move from 8.9 to 8.10.1; and 2 out of 3 attempted verification builds failed.
Our verification builds are explicitly configured to **not** run as daemon by default.

We can wait for 8.11, just saying that the workaround proposed here doesn't seem to help in our setup.

**Comment by ljacomet** [comment] 2024-09-20 07:35
Hello @tom-mi, @ganadist, @mkondratek and @EdGue42,

Could you try version `8.10.2-milestone-1` and report the results?

`./gradlew wrapper --gradle-version 8.10.2-milestone-1`

**Comment by EdGue42** [comment] 2024-09-20 08:03
Changed our setup to use gradle-8.10.2-milestone-1-bin.zip ... and pushed a PR to invoke our verification build.
I can restart that a few times and hopefully remember to provide feedback by the end of my day.

**Comment by EtherealLich** [comment] 2024-09-20 09:40
Looks like version `8.10.2-milestone-1` solves issue, error is gone

**Comment by bric3** [comment] 2024-09-20 14:01
This looks fixed with gradle-8.10.2-milestone-1

https://github.com/bric3/excalidraw-jetbrains-plugin/pull/340

**Closed** 2024-09-23 08:00 UTC
Labels: in:configuration-model, a:regression, has:release-notes-decision, affects-version:8.10.1

**Comment by EdGue42** [comment] 2025-10-08 07:57
It looks like the regression ... came back again: see [35253](https://github.com/gradle/gradle/issues/35253)

**Comment by 6hundreds** [comment] 2025-10-08 09:05
FTR, fixed by https://github.com/gradle/gradle/pull/30523
