### ISSUE TITLE
Error extracting downloaded toolchain for `JvmImplementation.J9`

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#19382] opened 2021-12-21 21:37 UTC
When choosing the "Open J9" Java Toolchain implementation [as described in the docs](https://docs.gradle.org/current/userguide/toolchains.html#selecting_toolchains_by_their_virtual_machine_implementation), there is an error extracting the the downloaded Toolchain distribution, resulting in a build failure.

### Expected Behavior
The J9 toolchain distribution should be successfully downloaded, provisioned and used.

### Current Behavior
The build fails with this error occurring when extracting the toolchain:
```
* What went wrong:
Execution failed for task ':compileJava'.
> Error while evaluating property 'javaCompiler' of task ':compileJava'
   > Failed to calculate the value of task ':compileJava' property 'javaCompiler'.
      > Unable to download toolchain matching these requirements: {languageVersion=11, vendor=ADOPTOPENJDK, implementation=J9}
         > Could not copy tar entry /Users/daz/dev/playground/java-tool/HOME/jdks/adoptopenjdk-11-x64-mac.tar.gz!1413453464414134534642/./ to '/Users/daz/dev/playground/java-tool/HOME/.tmp/expandedArchives/adoptopenjdk-11-x64-mac.tar.gz_09fc3ceb3762da51449cb5292ffc4737/1413453464414134534642/.'.
            > Failed to create parent directory '/Users/daz/dev/playground/java-tool/HOME/.tmp/expandedArchives/adoptopenjdk-11-x64-mac.tar.gz_09fc3ceb3762da51449cb5292ffc4737/1413453464414134534642' when creating directory '/Users/daz/dev/playground/java-tool/HOME/.tmp/expandedArchives/adoptopenjdk-11-x64-mac.tar.gz_09fc3ceb3762da51449cb5292ffc4737/1413453464414134534642/.'
```

### Steps to Reproduce 
1. Checkout the `main` branch of https://github.com/bigdaz/gradle-toolchain-issues
2. `./gradlew -g HOME build`

Build scan URL: https://scans.gradle.com/s/ri37b7rtrdmf6/failure#1

**Comment by bigdaz** [comment] 2021-12-21 22:01
Interesting: looking at the build scan there are a bunch of Unicode `[U+0000]` characters in the Tar entry name: https://scans.gradle.com/s/ri37b7rtrdmf6/failure?anchor=e30&focused-exception-line=0-1-2-3-4-5-0#1

**Comment by jbartok** [comment] 2021-12-23 13:20
Conclusions so far:

- when servicing the toolchain spec in the reproducer (languageVersion **11**, vendor **ADOPTOPENJDK**, implementation **J9**), our auto-provisioning system requests a download from here: https://api.adoptopenjdk.net/v3/binary/latest/11/ga/mac/x64/jdk/openj9/normal/adoptopenjdk
- the actual response we get is: https://github.com/ibmruntimes/semeru11-binaries/releases/download/jdk-11.0.13%2B8_openj9-0.29.0/ibm-semeru-open-jdk_x64_mac_11.0.13_8_openj9-0.29.0.tar.gz
- our code for extracting such archives, basically [TarFileTree](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/api/internal/file/archive/TarFileTree.java), fails to do so on this particular archive (the `org.apache.tools.tar` code we use produces some `TarEntry` instances with corrupted names, ie. String with lots of zero bytes in them, which then get turned into file names and things just go bye-bye from there); this is the case with all relatively recent versions of our codebase
- something is very weird with this jar, but the actual `tar` utility from MacOS can handle it... which makes it even weirder...
- btw. if we don't request the J9 implementation, then we get a completely different jar and none of these problems happen
- things work with other J9 implementation jars too properly, for example if the language level is 16
- so there is something about this particular Jar, but so far I fail to realize what exaclty

**Comment by jbartok** [comment] 2021-12-27 13:31
I've tracked this down to [the exact change](https://github.com/apache/ant/commit/2e5b53fa106b848646493cb6f6ea74616973aca0) in Ant that introduces the code which is broken. It was introduced when they switched from `1.8` to `1.9`. 

The buggy code is [this prefix shenanigans](https://github.com/apache/ant/blob/711132a7dd66b2e18c09c9dcae2aba94b0ff798c/src/main/org/apache/tools/tar/TarEntry.java#L1019) which wasn't there until then and in case of this particular compressed tar archive doesn't behave as expected.

I think that the tar.gz has some fault too, it probably has some header values which aren't correct and lead to the manifestation of the Ant bug. 

What to do about it... The whole Ant project, as it's set up, in my opinion, just screams "we don't really need your contribution", I got a bit discouraged when even contemplating submitting a bug report, but that's probably what we'll need to do. 

Or switch to some other tool for decompressing tars. I'm sure we can find something a bit more modern. 

Let's discuss it internally.

**Comment by jbartok** [comment] 2021-12-27 13:44
We have decided to try to report this to Adoptium, maybe they'll fix the archive.

**Comment by bigdaz** [comment] 2021-12-29 01:52
> things work with other J9 implementation jars too properly, for example if the language level is 16

@jbartok This doesn't match my experience: I've tested with various `languageVersion` settings and get the same failure for some other versions.
- `11`: FAIL https://scans.gradle.com/s/dvz6wphf3clkk
- `14`: SUCCESS https://scans.gradle.com/s/wydezhdpw7sgk/performance/network-activity
- `15`: SUCCESS https://scans.gradle.com/s/wqsomyc7e5uni/performance/network-activity
- `16`: FAIL https://scans.gradle.com/s/26jtwv3g56z2u
- `17`: FAIL https://scans.gradle.com/s/xdd72zurio4vq

Note that I start with an empty Gradle User Home in each case, to avoid getting false positives/negatives due to https://github.com/gradle/gradle/issues/19383

**Comment by jbartok** [comment] 2021-12-29 10:47
Ok, good to know. I've only tried with 11 and 16. I will double-check and report those to Adoptium too.

**Comment by jbartok** [comment] 2022-01-06 09:33
@bigdaz Turns out that the archives that are NOT ok are the regular IBM Semeru Runtime ones (`ibm-semeru-open-jdk_x64_mac_xxx.tar.gz`). 

The ones that work, are different somehow, IBM doesn't provide Semeru archives for Java 14 & 15. What Adoptium provides are some kind of OpenJDK ones, called `OpenJDK14U-jdk_x64_mac_openj9_14.0.2_12_openj9-0.21.0.tar.gz` and `OpenJDK15U-jdk_x64_mac_openj9_15.0.2_7_openj9-0.24.0.tar.gz`. Anyways, these work just fine, we can ignore them for now.

I'm trying to contact IBM, let's see if they are willing to look into and do something about their Semeru archives. But, just as Ant, they really don't make it easy... Let's see if I can get anywhere with them.

**Comment by jbartok** [comment] 2022-01-07 07:39
Finally found the right place to submit the issue: https://github.com/ibmruntimes/Semeru-Runtimes/issues/15

**Comment by jbartok** [comment] 2022-01-12 09:26
Note to myself: in the meantime I should come up with a PR for replacing the Ant code when uncompressing the archives.

**Comment by ljacomet** [comment] 2022-01-17 13:23
This turns out to be somewhat tricky to fix, so will not be done for 7.4

**Comment by gabrieljones** [comment] 2022-01-17 15:14
I just hit this with
```build.gradle.kts
java {
  toolchain {
    languageVersion.set(JavaLanguageVersion.of(17))
  }
}
```

Works fine on my MacBook, but breaks on our Jenkins build servers.
Anyone have a workaround yet?

**Comment by gabrieljones** [comment] 2022-01-17 16:13
Unable to reproduce in Github Actions:
```
Downloading https://api.adoptopenjdk.net/v3/binary/latest/17/ga/linux/x64/jdk/hotspot/normal/adoptopenjdk to /home/runner/.gradle/jdks/adoptopenjdk-17-x64-linux.tar.gz
Installed adoptopenjdk-17-x64-linux.tar.gz into /home/runner/.gradle/jdks/jdk-17.0.1+12
```
-- https://github.com/gabrieljones/gradle-toolchain-issues/runs/4843169424

**Comment by jbartok** [comment] 2022-03-09 10:28
> I just hit this in gradle v7.3.3 with:
> 
> `build.gradle.kts`
> 
> ```kotlin
> // ...
> java {
>   toolchain {
>     languageVersion.set(JavaLanguageVersion.of(17))
>   }
> }
> // ...
> ```
> 
> Works fine on my MacBook, but breaks on our Jenkins build servers.
> 
> `build log`
> 
> ```
> Downloading https://<corp proxy>/v3/binary/latest/17/ga/linux/x64/jdk/hotspot/normal/adoptopenjdk to /XXXXX/jenkins/.gradle/jdks/adoptopenjdk-17-x64-linux.tar.gz
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring root project 'pipeline-template'.
> > Failed to calculate the value of task ':compileJava' property 'javaCompiler'.
>    > Unable to download toolchain matching these requirements: {languageVersion=17, vendor=any, implementation=vendor-specific}
>        > Could not copy tar entry /XXXXX/jenkins/.gradle/jdks/adoptopenjdk-17-x64-linux.tar.gz!jdk-17.0.1+12/lib/server/classes.jsa to '/XXXXX/jenkins/.gradle/jdks/jdk-17.0.1+12/lib/server/classes.jsa'.
>           > /XXXXX/jenkins/.gradle/jdks/jdk-17.0.1+12/lib/server/classes.jsa (No such file or directory)
> ```
> 
> Anyone have a workaround yet?
> 
> Edit: My current workaround is to predownload and install with curl and tar shell commands like so:
> 
> `Jenkinsfile`
> 
> ```
> // ...
>     stage('pre download toolchain') {
>       steps {
>         sh 'curl https://<corp proxy>/v3/binary/latest/17/ga/linux/x64/jdk/hotspot/normal/adoptopenjdk --create-dirs -fsSLo ~/.gradle/jdks/adoptopenjdk-17-x64-linux.tar.gz'
>         sh 'tar -xf ~/.gradle/jdks/adoptopenjdk-17-x64-linux.tar.gz -C ~/.gradle/jdks/'
>       }
>     }
> // ...
> ```

@gabrieljones this has nothing to do with this current issue; pls. file a separate issue for it and we'll try to investigate.

**Comment by EdGue42** [comment] 2022-05-13 07:03
What is the reason that this has been moved out to Gradle 8?

Why do we have to wait for the next major version update?

Gradle 8 is really problematic, as A) who knows when it will be coming and B) there might be various issues preventing us to moving to gradle 8.

**Comment by jbartok** [comment] 2022-07-22 07:44
@amankr55 changing the archive decompression library will only happen in Gradle 8, no sooner; it's too big of a change for us to do in a non-major release

**Closed** 2022-10-28 09:51 UTC
Labels: a:bug, in:toolchains, affects-version:7.4
