### ISSUE TITLE
Could not set the value of environment variable '': could not putenv() (errno 22: Invalid argument)

### ISSUE THREAD

**Issue by kongxiangxin** [gradle/gradle#19082] opened 2021-11-23 04:06 UTC
I am dealing a strange problem with gradle wrapper 5.3.1 and macOS Big Sur.

```text
./gradlew clean apiServer --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
Could not set the value of environment variable '': could not putenv() (errno 22: Invalid argument)

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
net.rubygrapefruit.platform.NativeException: Could not set the value of environment variable '': could not putenv() (errno 22: Invalid argument)
        at net.rubygrapefruit.platform.internal.DefaultProcess.setEnvironmentVariable(DefaultProcess.java:71)
        at net.rubygrapefruit.platform.internal.WrapperProcess.setEnvironmentVariable(WrapperProcess.java:81)
        at org.gradle.internal.nativeintegration.processenvironment.NativePlatformBackedProcessEnvironment.removeNativeEnvironmentVariable(NativePlatformBackedProcessEnvironment.java:31)
        at org.gradle.internal.nativeintegration.processenvironment.AbstractProcessEnvironment.removeEnvironmentVariable(AbstractProcessEnvironment.java:48)
        at org.gradle.internal.nativeintegration.processenvironment.AbstractProcessEnvironment.maybeSetEnvironment(AbstractProcessEnvironment.java:38)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:65)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)


* Get more help at https://help.gradle.org
```

It seems like there is an environment variable '', but I have no idea where does it come from.

And,  which is more strange,  some times this exception may disappear if I reboot my os, and it appeared again once I restart my IntelliJ IDEA.

I have to reboot my os again and again until it disappeared and keep my IntelliJ open.

**Comment by ljacomet** [comment] 2021-11-24 09:40
Thanks for the report.
This will be hard to analyze without a reproducer.
One thing that can be recommended: upgrade to a more recent Gradle version.

**Comment by JimmyDeemo** [comment] 2021-12-02 16:45
I have this problem too. Gradle version is 5.1.1. Started randomly, now happens all the time on our build machines. Can't reproduce locally. Any ideas on where to look and possible workarounds would be appreciated as we are bound by the gradle version due to restrictions from [Unity](https://docs.unity3d.com/Manual/android-gradle-overview.html).

**Comment by kongxiangxin** [comment] 2021-12-05 02:59
I found that if the GradleDaemon was started by the IntelliJ IDEA, there was an empty environment variable like this:
<img width="1434" alt="wecom-temp-29c7711bcc0ba5b1208cfe7024397db3" src="https://user-images.githubusercontent.com/1704567/144731682-b552c8ba-513c-43c8-92df-f3c08b53ca74.png">

My solution is modify the source code in NativePlatformBackedProcessEnvironment class and ignore the empty environment variable:
<img width="997" alt="wecom-temp-13fe0b522d62ca48775c23bbe9a8725e" src="https://user-images.githubusercontent.com/1704567/144731719-e098a210-d037-4398-9b78-34e840f622d5.png">

**Comment by kongxiangxin** [comment] 2021-12-05 03:07
> Thanks for the report. This will be hard to analyze without a reproducer. One thing that can be recommended: upgrade to a more recent Gradle version.

It seems that even the new version of Gradle would not ignore the environment variable with empty key. See NativePlatformBackedProcessEnvironment.removeNativeEnvironmentVariable method:
`@Override
    protected void removeNativeEnvironmentVariable(String name) {
        process.setEnvironmentVariable(name, null);
    }`
I think it will be better if it can ignore the empty one.

**Comment by lptr** [comment] 2024-02-26 08:50
This sounds like a problem with how IntelliJ invokes Gradle, and should be fixed there.

**Closed by lptr** 2024-02-26 08:50 UTC
Labels: a:bug, in:internal-native-libraries
