### ISSUE TITLE
tasks.withType(ScalaCompile::class.java).configureEach fails on multi-project builds

### ISSUE THREAD

**Issue by dsilva** [gradle/gradle#6558] opened 2018-08-29 11:46 UTC
On a multi-project build, using `tasks.withType(ScalaCompile::class.java).configureEach` leads to a ConcurrentModificationException in the `compileScala` task.

Here's a git repository that reproduces the issue: https://github.com/dsilva/repro-tasks-withtype-ScalaCompile-configureEach

### Expected Behavior

Build should succeed.

### Current Behavior

Gradle crashes.

### Context

I'm trying to use the new tasks API:

https://blog.gradle.org/preview-avoiding-task-configuration-time
https://docs.gradle.org/current/userguide/task_configuration_avoidance.html

### Steps to Reproduce (for bugs)

See https://github.com/dsilva/repro-tasks-withtype-ScalaCompile-configureEach

```bash
git clone https://github.com/dsilva/repro-tasks-withtype-ScalaCompile-configureEach.git
while ./gradlew clean :a:classes --no-build-cache -S; do sleep 1; done
```

### Your Environment

 * Build scan URL:

**Comment by lacasseio** [comment] 2018-08-29 16:32
I can confirm this is still an issue on latest master. So most likely an issue for as well 4.10 since the wrapper of the repo is 4.9.

**Comment by wolfs** [comment] 2018-09-12 09:56
This is fixed in 4.10.1

**Closed by wolfs** 2018-09-12 09:56 UTC
Labels: a:bug, from:contributor, in:core

**Comment by drujd** [comment] 2018-09-13 13:58
This 'fix' breaks our build which worked flawlessly on 4.10.
Every scala project:
`Cannot choose between the following variants of project XXX
about:blank
          - apiElements
          - incrementalScalaAnalysisElements
          - runtimeElements
        All of them match the consumer attributes:
          - Variant 'apiElements': Found org.gradle.usage 'java-api' but wasn't required.
          - Variant 'incrementalScalaAnalysisElements': Found org.gradle.usage 'incremental-analysis' but wasn't required.
          - Variant 'runtimeElements': Found org.gradle.usage 'java-runtime-jars' but wasn't required.`

**Comment by big-guy** [comment] 2018-09-13 18:03
@drujd can you describe a bit more about how your build is setup?  Could you share a [build scan](https://scans.gradle.com/)?

Do you have a mixture of Scala and Java projects or just Scala projects or something else?

Thanks!

**Comment by big-guy** [comment] 2018-09-14 21:29
@drujd I think this is what you're running into: https://github.com/gradle/gradle/issues/6750

I'll have a nightly for you to try out early next week and we'll put out a 4.10.2.

**Comment by drujd** [comment] 2018-09-15 18:06
That's great! I unfortunately cannot share a build scan, but I will try out the nightly - if it does not work, I will try to create a sample project that replciates the issue.
