### ISSUE TITLE
"Strictly" dependency not that strict

### ISSUE THREAD

**Issue by kvainer** [gradle/gradle#18017] opened 2021-08-12 17:34 UTC
I have a library that depends on a particular version of a dependency, so I use strictly to say I must have that version. Then I have an app that also depends on that dependency, but it wants a different version.

Here's an (abridged) example:
```gradle
project('lib') {
    apply plugin: 'java-library'
    dependencies {
        implementation('com.google.guava:guava') {
            version {
                strictly '30.0-jre'
            }
        }
    }
}

project('main') {
    apply plugin: 'java'
    apply plugin: 'application'
    dependencies {
        implementation project(':lib')
        implementation('com.google.guava:guava') {
            version {
                strictly '27.0-jre'
            }
        }
    }
}
```

The way I interpret strictly is to mean "I must have this version, no other version is acceptable for me". When the lib says it _strictly_ wants version 30 of Guava, it basically says "I cannot work with any other version, so don't even bother with anything else, it won't work"

Despite this, version 27 is still chosen, and no error or warning is emitted:
```
$ ./gradlew main:dependencyInsight --configuration runtimeClasspath --dependency com.google.guava:guava
com.google.guava:guava:{strictly 27.0-jre} -> 27.0-jre
\--- runtimeClasspath

com.google.guava:guava:{strictly 30.0-jre} -> 27.0-jre
\--- project :lib
     \--- runtimeClasspath
```

Naturally, when the lib is used by the app, it crashes and the whole app goes down. 

### Expected Behavior
Gradle should say that dependency resolution cannot complete due to incompatible versions

### Current Behavior
Gradle chose an incompatible dependency version with no warning or error

### Context
My app was shipped to production and then promptly crashed. I had to rollback my release.

### Steps to Reproduce 
[gradle-bug.zip](https://github.com/gradle/gradle/files/6977363/gradle-bug.zip)

### Your Environment

```
------------------------------------------------------------
Gradle 7.1.1
------------------------------------------------------------

Build time:   2021-07-02 12:16:43 UTC
Revision:     774525a055494e0ece39f522ac7ad17498ce032c

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          1.8.0_292 (Private Build 25.292-b10)
OS:           Linux 5.11.0-25-generic amd64
```

Build scan URL: https://scans.gradle.com/s/x6hbxmansouqw

**Comment by jbartok** [comment] 2021-08-19 07:43
@kvainer FYI the rules governing this behaviour are described in [this part of the Gradle manual](https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html#sec:strict-version-consequences).

Your example however does not seem to behave according to these rules. Since your 'main' subproject is a consumer, it should consider strict versions globally and fail to resolve them, just like you expect. 

At least that's what I think atm... Let us investigate further!

**Comment by jbartok** [comment] 2021-08-19 10:28
@kvainer I now have a better understanding of this mechanism and the conclusion is that the behaviour is as expected. Let me explain. 

In your case let's say that library is completely external, you have no say about what transitive dependencies it has, be they strict or not (reasonable assumption for libraries in general). Let's say you want your main to use version 27 of guava and you realise that you aren't even using the parts of the library which were the reason of it depending strictly on guava 30. How would you make this happen? Well, like your example, by declaring your dependency in main as strict. 

The direct strict dependency is basically an override, that's why it's not conflicting with the transitive strict dependency.  It's a feature of Gradle, not a bug. 

An example of a conflict would be if you would use two libraries, both having strict and different dependencies of their own on guava. Then resolution would fail and one way you could resolve it would be to set a direct and strict dependency in your app, thus overriding the transitive ones (ie. stating an explicit decision). 

Another example of conflict I can think of is if you would declare multiple direct, strict dependencies with different versions. This could maybe happen as a mistake, when you have modular build script assembled from multiple files. 

We will think about ways to make this clearer in the documentation, but as for this issue, it's not an issue, so I will close it.

**Closed by jbartok** 2021-08-19 10:28 UTC
Labels: a:bug, in:dependency-resolution, to-triage

**Comment by kvainer** [comment] 2021-08-19 16:35
Thanks for the explanation @jbartok 

I did guess that this was in fact intended behavior.

Perhaps my concern is that there's a syntax here where a library can convey it's wishes regarding which dependency versions it's compatible with and can use, but it is being used for two different purposes.

One is to override versions for a dependency regardless of anything else, and another as a suggestions to the dependency resolution system as to what version to use given the specified constraints.

In one case, we trust the words of one entity completely and ignore all others, and in the other, we give equal trust to all entities and try to find a consensus between the voices.

What I'm trying to say is, I think those two purposes should not use the same syntax.
