### ISSUE TITLE
Written file is not detected by Gradle and so not packaged in the final APK

### ISSUE THREAD

**Issue by marandaneto** [gradle/gradle#15134] opened 2020-11-12 09:15 UTC
I'm not fully sure if it's a Gradle or Android Gradle plugin issue, but as I can reproduce using Gradle 6.7 and not upgrading the AGP, I'll give it a try here, please point me out if it's not the case.

We've written a Gradle plugin that writes a file to the build folder (assets) so this file is gonna be packaged in the final APK (Android App), this file contains a hash of the mappings file for stack traces symbolization on the server.

So this file needs to be written in the build folder after the AGP `minifyReleaseWithR8` task as we need to compute the hash first, but before the AGP `packageRelease` task, as the file needs to be packaged in the final APK.

All the tasks seem to be executed in the right order.

I'd guess that this is something related to incremental tasks and its caching system (input/output etc...).

### Expected Behavior
The written file makes it to the final APK

### Current Behavior
The file doesn't make it to the final APK, only after the 2nd run (assembleRelease), but If I do `clean assembeRelease`, it doesn't work sometimes.

### Context
This used to work on AGP <= 4.0.x and Gradle <= 6.6.x, and now either upgrading Gradle to 6.7.x or AGP to 4.1.x looks like the file is written to the build folder correctly but not in the final APK.

Also, this is the original issue: https://github.com/getsentry/sentry-android-gradle-plugin/issues/37 with more context of my findings

### Steps to Reproduce 
A demo is available https://github.com/mrrobot97/SentryGradlePluginIssueDemo

./gradlew clean assembleRelease -> the file is not written in the assets folder in the final APK
once more ./gradlew assembleRelease -> the file is written in the assets folder in the final APK

### Your Environment

Build scan URL:
1st run: clean assembleRelease https://scans.gradle.com/s/a6usdxgw62kpu
2nd run: assembleRelease https://scans.gradle.com/s/mzq33uilc4rpk

<img width="1086" alt="Screenshot 2020-11-12 at 10 12 17" src="https://user-images.githubusercontent.com/5731772/98919861-a7624e80-24cf-11eb-8f3b-14fad1c14de9.png">

**Comment by marandaneto** [comment] 2021-01-04 14:58
any update on this? thanks :)

**Comment by ceggert87** [comment] 2021-01-21 10:42
I am experiencing something similar starting with Gradle 6.7. Gradle 6.6 still works fine.

The use-case is having a script that pushes files into the intermediates/merged_assets/<buildvariant>/out path.
The task copying of the file has a setup as follows:

```
copyStuff.dependsOn {
    tasks.matching { task -> task.name.startsWith('merge') && task.name.endsWith('Assets') }
}

tasks.withType(JavaCompile) {
    compileTask -> compileTask.dependsOn copyStuff
}

copyStuff
```
With gradle 6.6 and lower, this leads to a file in the specified path and it also ending up in the apk under the assets.
With gradle 6.7+ (also tried 6.8), the file is present in the intermediates, but does not end up in the apk.

If there is any specific change that makes this behavior obvious, please let me know.

**Comment by wanggaohui** [comment] 2021-01-28 09:14
I also encountered the same problem. Our business is the newly generated file in the compilation stage, which will be copied to the asset directory and finally packaged into the apk. But after upgrading to gradle 6.7, it was found that the files compiled and copied to the build directory were not packaged into the apk.

**Comment by runningcode** [comment] 2021-02-12 16:26
Hi there, please make sure that the sentry plugin and task are declaring the output files in the task.
Here is how you can do that: https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:task_input_output_annotations

**Comment by ansman** [comment] 2021-02-13 21:03
This is not a bug on Gradle's part. There are a couple of things missing from the Sentry plugin:
* It does not register the file as an output
* It does not depend on the correct task (the correct one would be `merge<variant>Assets`)
* It does not add the file to the source set

**Comment by runningcode** [comment] 2021-02-15 10:45
Thanks @ansman for investigating this. I will close this out.

**Closed by runningcode** 2021-02-15 10:45 UTC
Labels: a:regression, from:contributor

**Comment by marandaneto** [comment] 2021-02-15 11:31
> Hi there, please make sure that the sentry plugin and task are declaring the output files in the task.
> Here is how you can do that: https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:task_input_output_annotations

Hey :) thanks for your message, yep we've noticed that and we're already planning a full rewrite of this plugin using the newest AGP and Gradle APIs, what I'm missing here is only why this used to work and now it does not anymore.

Looking at https://docs.gradle.org/6.7/userguide/upgrading_version_6.html#changes_6.7 I also don't see any explicit breaking changes.
