### ISSUE TITLE
ClasspathSnapshotMaker logs module-info as duplicate class

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle#10839] opened 2019-09-24 06:44 UTC
`ClasspathSnapshotMaker` logs `module-info`s as duplicate classes.

Please have whatever determines that classes are duplicates ignore `module-info` class files.

**Comment by ljacomet** [comment] 2020-06-02 08:27
Could you provide indications on how to reproduce this?

**Comment by rgoldberg** [comment] 2020-06-02 23:51
It was before builtin module support from Gradle, when I was using a plugin to support modules. It might not occur with the builtin support. I’ll try to investigate this later by upgrading to the builtin support, but it might take me some time to get to it.

**Comment by jjohannes** [comment] 2020-12-22 08:28
Closing as this seems to be fixed.

**Closed by jjohannes** 2020-12-22 08:28 UTC
Labels: @jvm, a:bug, from:contributor, in:jvm-ecosystem, in:modular-java
