### ISSUE TITLE
Publish valid Maven POM for library with dependency on Maven BOM

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#3722] opened 2017-12-05 17:12 UTC
To support publishing a POM for a javaLibrary that depends on a BOM:

- Since Maven doesn't support a dependency on a BOM, we need a way to map this to an import scoped entry in <dependencyManagement>
- We can't do this automatically, since we don't resolve the dependencies before publishing, so we don't known when to map to 'import'.
- Instead, we can provide a DSL for users to define an 'import' for their MavenPublication.pom.

**Comment by ljacomet** [comment] 2018-08-21 15:44
Closing as a duplicate of #4543 which has a better description of the current issue(s)

**Closed by ljacomet** 2018-08-21 15:44 UTC
Labels: a:feature, from:member, in:dependency-management
