### ISSUE TITLE
error running gradle init --incubating=false

### ISSUE THREAD

**Issue by radopas** [gradle/gradle#24837] opened 2023-04-20 12:56 UTC
### Expected Behavior

When running gradle init on command line, the argument --incubating=false should be accepted and the question "Generate build using new APIs and behavior (some features may change in the next minor release)? (default: no) [yes, no]" must not be asked.

https://docs.gradle.org/current/userguide/command_line_interface.html suggests to use --no- prefix but running --no-incubating generates error "Unknown command-line option '--no-incubating'."

### Current Behavior

running command line 
gradle init --incubating=false
generates error "Command-line option '--incubating' does not take an argument."

### Steps to Reproduce

execute on command line
gradle init --incubating=false

### Gradle version

Gradle 8.0.2

**Comment by ljacomet** [comment] 2023-04-21 08:44
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #4311

***

Note that the fix for this will be available in Gradle 8.2

**Closed by ljacomet** 2023-04-21 08:44 UTC
Labels: a:bug, to-triage
