### ISSUE TITLE
allow Provider::orElse to take a `Callable`

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#31104] opened 2024-10-31 17:55 UTC
### Expected Behavior

this seems silly
```
someProperty.orElse(() -> providerFactory.getProvider(() -> ...) )...
```

instead allow, which just makes the other provider under the hood.

```
someProvider.orElse(() -> ...)
```

### Context

I just want to write less and sometimes more functional code. The reality in my use case even having a fully fledge provider seems silly (but maybe isn't). I just want it to orElse call that function at the end.

**Comment by ljacomet** [comment] 2024-11-04 09:50
This issue will be closed as a duplicate of

* #29358

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

**Closed by ljacomet** 2024-11-04 09:50 UTC
Labels: a:feature, closed:duplicate, in:provider-api
