### ISSUE TITLE
Build scan adds significant overhead

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#5108] opened 2018-04-19 13:39 UTC
Gradle version: 4.7
Profile information differs significantly when running with --profile and --scan.

Cleanup task is `./gradlew clean`
Profiled task is `./gradlew :app:assDeb  -Pandroid.enableBuildCache=false -PdevBuild`

Using the [Robot-Scouter](https://github.com/SUPERCILEX/Robot-Scouter/blob/master/README.md#environment-setup-) project (SHA: 9e73eaec4c5d52a8b0115d86f76aeae686b517fb), Gradle version has been updated to 4.7.

[profile.zip](https://github.com/gradle/gradle/files/1928286/profile.zip) has been generated with --profile. For the same project, using --scan produces https://scans.gradle.com/s/bjkerez4httoe/performance/execution.

In the first, dexing takes 9 seconds, while in the second one it takes 24 seconds.

**Comment by oehme** [comment] 2018-04-19 14:28
@ldaley You might wanna take a look at this one.

**Comment by breskeby** [comment] 2018-04-24 21:12
I used https://github.com/gradle/gradle-profiler to profile this issue. See the results attached. From the profiling I cannot reproduce this significant difference in build execution. 
However I see that the dex task is quite volatile in how much time it takes. On my machine when running with or without build scans I saw execution times of ~10 up to ~35 seconds.

I'm tempted to close this issue as not reproducible. 

[benchmarkResults.zip](https://github.com/gradle/gradle/files/1944620/benchmarkResults.zip)

**Comment by breskeby** [comment] 2018-04-25 07:05
@gavra0 As described in my comment above I struggle to reproduce the significant difference you experience. It would be great if you can help me and profile your build using the `gradle-profiler` project (https://github.com/gradle/gradle-profiler) and share your results?

my `gradle-profiler` scenario file looks like that:

```# Scenarios are run in alphabetical order

clean_build_withNoScan {
    tasks = [":app:assDeb"]
    gradle-args = ["-Pandroid.enableBuildCache=false", "-PdevBuild"]
    cleanup-tasks = ["clean"]
    run-using = cli // value can be "cli", "no-daemon" or "tooling-api"

    warm-ups = 5
}

clean_build_withScan {
    tasks = [":app:assDeb"]
    gradle-args = ["-Pandroid.enableBuildCache=false", "-PdevBuild", "--scan"]
    system-properties {
        scan.dump = "true"
    }
    cleanup-tasks = ["clean"]
    run-using = cli // value can be "cli", "no-daemon" or "tooling-api"

    warm-ups = 5
}
``` 

you can run the benchmarking by executing 

`gradle-profiler --benchmark --project-dir <PATH TO ROBOT SCOUTER> --scenario-file performance.scenario`

If your profiling demoes the problem you initially reported, it would be great to run the `gradle-profiler` with `--profile jfr` and share those profiling information here to help us narrow down the isue.

Thanks a lot. 

cheers,
René

**Comment by gavra0** [comment] 2018-04-25 20:08
@breskeby When using gradle-profiler, numbers with and without --scan look similar, around 30 seconds. However, if I run a simple bash script, I see the difference.

```
# without --scan
./gradlew --stop

# warmup
for i in {0..3}
do
  ./gradlew clean && ./gradlew :app:assDeb -PdevBuild -Pandroid.enableBuildCache=false
done

echo "Timed runs without --scan"
./gradlew clean && time ./gradlew :app:assDeb -PdevBuild -Pandroid.enableBuildCache=false
./gradlew clean && time ./gradlew :app:assDeb -PdevBuild -Pandroid.enableBuildCache=false
./gradlew clean && time ./gradlew :app:assDeb -PdevBuild -Pandroid.enableBuildCache=false


# with --scan
./gradlew --stop

# warmup
for i in {0..3}
do
  ./gradlew clean && ./gradlew :app:assDeb -PdevBuild -Pandroid.enableBuildCache=false -Dscan.dump=true --scan
done

echo "Timed runs with --scan"
./gradlew clean && time ./gradlew :app:assDeb -PdevBuild -Pandroid.enableBuildCache=false -Dscan.dump=true --scan
./gradlew clean && time ./gradlew :app:assDeb -PdevBuild -Pandroid.enableBuildCache=false -Dscan.dump=true --scan
./gradlew clean && time ./gradlew :app:assDeb -PdevBuild -Pandroid.enableBuildCache=false -Dscan.dump=true --scan
```

On my laptop, without --scan takes 30 sec, with 50 sec. Can you please try to repro with this script? Also, do you have any idea why there is such a big difference when running with gradle-profiler and when running this bash script?

Thanks!

**Comment by oehme** [comment] 2018-04-25 20:27
@gavra0 The Gradle profiler uses an isolated user home, so my hunch is that you have some init script that adds additional work when build scans are enabled? Can you check that?

**Comment by gavra0** [comment] 2018-04-25 21:17
@oehme Great idea, using a temporary GRADLE_USER_HOME makes builds with and without --scan completely the same 😀 

I looked a bit more, and the issues was some state in ~/.gradle/build-scan-data/. After removing only that directory, overhead of running with --scan has disappeared (when using my default GRADLE_USER_HOME). Unfortunately I failed to save the content, but it contained: 1.12.1, 1.13,	1.13.1, 1.8 directories. Could this be some issue between different BuildScan versions?

**Comment by ldaley** [comment] 2018-04-30 01:38
@gavra0 whether that directory is empty or not should have no impact. Regardless, we'll do some stress testing and get back to you.

**Comment by ldaley** [comment] 2018-05-15 08:53
@gavra0 We are unable to reproduce the results, nor find any reason as to why a number of files in `~/.gradle/build-scan-data` would blow out build times.

Have you experienced this again since?

**Comment by gavra0** [comment] 2018-05-15 10:31
@ldaley There were no issues since. Feel free to close the issue, and in case I managed to reproduce again, I'll update the bug. Thanks!

**Comment by etiennestuder** [comment] 2018-05-15 11:11
Thanks for the feedback, @gavra0. Closing this issue now.

**Closed by etiennestuder** 2018-05-15 11:11 UTC
Labels: a:bug, from:contributor
