### ISSUE TITLE
gradle 3.4.1 fails to start on Sles10

### ISSUE THREAD

**Issue by aflat** [gradle/gradle#1520] opened 2017-03-06 17:55 UTC
os: sles10 
gradle: 3.4.1
java: (build 1.8.0_121-b13

```
~/>build/gradlew --help

FAILURE: Build failed with an exception.

* What went wrong:
Failed to load native library 'libnative-platform.so' for Linux amd64.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by aflat** [comment] 2017-03-06 18:00
3.4 fails with the same error. 3.3 doesn't have this issue.

**Comment by bmuschko** [comment] 2017-03-07 14:36
Closing as duplicate of https://github.com/gradle/gradle/issues/1493

**Closed by bmuschko** 2017-03-07 14:36 UTC
Labels: a:bug, affects-version:3.4, from:contributor, in:core
