### ISSUE TITLE
Java Plugin documentation has outdated/incorrect information in "Dependency configurations" section

### ISSUE THREAD

**Issue by jcttrll** [gradle/gradle#5681] opened 2018-06-09 22:14 UTC
I believe there are a couple issues with the section [Dependency configurations](https://docs.gradle.org/current/userguide/java_plugin.html#tab:configurations) in the docs for the Java Plugin.

1. `testRuntime` and `testRuntimeOnly` contain the description, "Used by task test." `testRuntimeClasspath` does not say this. The diagram below the textual descriptions also shows the `test` task using `testRuntime` (but not `testRuntimeOnly`), rather than just using `testRuntimeClasspath`. Empirically, the `test` task uses `testRuntimeClasspath`. Removing "Used by task test" from the other two descriptions and adding it to `testRuntimeClasspath` seems correct (and also mirrors the descriptions of `testCompile`, `testCompileOnly`, and `testCompileClasspath`, which share a similar relationship). The diagram would need a similar update.
1. There are two `testImplementation` symbols in the diagram. One needs to be removed, and its arrows moved to the other, for the diagram to be correct.

If you agree that the documentation needs to be changed, I'd be happy to submit a PR for it. (I can't do anything with the diagram, since I don't have a Mac/OmniGraffle.)

**Comment by marcphilipp** [comment] 2018-06-18 11:42
@pledbrook Could you please take a look?

**Comment by pledbrook** [comment] 2018-06-18 13:56
I think this section needs more work than proposed. If you take a look at the Java Library Plugin chapter, it takes greater pains to distinguish between the different types of configuration: those that the build author should declare dependencies against — e.g. `testImplementation` and `testRuntimeOnly` — and those configurations that should be resolved to configure tasks and other use cases, such as `testRuntimeClasspath`. The documentation seems to indicate that one should declare dependencies against `testRuntimeClasspath`, but that's not the case as far as I understand.

I need to ask around to confirm the intention behind each of the configurations. Once I have some answers, I'll get back with the skeleton of a proposal.

BTW, you don't need OmniGraffle for that diagram as it's a DOT file: _subprojects/docs/src/docs/userguide/img/java-configurations.dot_ — a text editor works just fine.

**Comment by pledbrook** [comment] 2018-06-20 12:49
So I've had it confirmed that build authors should not be declaring dependencies using `runtimeClasspath` or `testRuntimeClasspath`. We should bring this section of the docs in line with the Java Library Plugin chapter. @jcttrll if you'd like to take a stab at that, I'd be happy to review. And answer any questions you might have. Otherwise, it may be a while before we get round to it as the current wording isn't inaccurate as such.

**Comment by mrmeszaros** [comment] 2018-07-17 13:08
@jcttrll The diagram error is caused by a typo:
* one is `testImplementation` and the other is `testImplementaion` (the last `t` is missing)

![Java plugin - dependency configurations](https://docs.gradle.org/current/userguide/img/javaPluginConfigurations.png)

**Comment by pledbrook** [comment] 2018-07-18 10:57
@mrmeszaros Please create a pull request from that. I may not be able to merge it myself, but if that's the case, I'll get someone else to do it. Thanks!

**Comment by lacasseio** [comment] 2018-07-18 12:05
The PR fixing the image was merged in master. @pledbrook is there anything left to act on this issue?

**Comment by pledbrook** [comment] 2018-07-18 13:20
@lacasseio Yes. The configurations section should either remove the `*Classpath` entries or make it clear that dependencies should not be declared under them. So the issue should remain open.

**Comment by mrmeszaros** [comment] 2018-07-18 15:06
I have been fiddling with this graph, and I came up with an idea that makes more sense to me:
* recoloring the **classpath** configurations, since they should not be used manually
* and inverting changing `used by` to `uses` since the layout reflects then more the information flow:
![javapluginconfigurations](https://user-images.githubusercontent.com/15245298/42889855-abe8d52a-8aab-11e8-93d8-6932e7469694.png)

Now that poses a few questions:
* what task uses the `runtimeClasspath`? I would assume that this is used by the jar task to put in the Manifest

**Comment by pledbrook** [comment] 2018-07-20 08:41
The colouring should ideally be consistent with the [_Java Library Plugin_ chapter](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_configurations_graph). I also think we should split the diagram up as it's just too confusing in its current incarnation.

`runtimeClasspath` is used by tasks like `war` and `appRun`, both provided by other plugins. I'm pretty sure it's not used by the `jar` task. However, it _would_ be used by a task that creates a fat JAR. See the [_Working with files_ chapter](https://docs.gradle.org/current/userguide/working_with_files.html#sec:creating_uber_jar_example) for an example.

As for `runtimeOnly`, it's for runtime-only dependencies, i.e. those that aren't required for compilation. However, `runtime` actually extends `compile`, so having `runtimeOnly` extend `runtime` would implicitly break the contract for `runtimeOnly`.

Remember that `runtimeClasspath` is the configuration that's actually used by tasks, so that's the one that needs to include `runtime`. `runtimeOnly` is explicitly for declaring dependencies.

**Comment by pledbrook** [comment] 2018-09-24 10:55
I have implemented my suggested changes in [this pull request](https://github.com/gradle/gradle/pull/6870). Just need it reviewed and merged.

**Comment by ghale** [comment] 2019-02-08 21:04
@pledbrook Is there more to do on this issue or can we go ahead and close it?

**Comment by pledbrook** [comment] 2019-02-11 09:39
@jcttrll 's first point hasn't been dealt with yet. The `testRuntime*` entries in the list of configurations should be updated to match the approach used for `testCompile*`. I'll close once that's done.

**Comment by ljacomet** [comment] 2019-03-14 09:38
Closing since #8511 was merged

**Closed by ljacomet** 2019-03-14 09:38 UTC
Labels: from:contributor, in:dependency-management, in:docs
