### ISSUE TITLE
Build Init plugin should create project files only when all questions are answered

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#9534] opened 2019-05-24 08:47 UTC
### Expected Behavior

Cancelling the init process (via ctrl-c) will leave wrapper and build script behind.

### Current Behavior

The build init process is eager and will create the wrapper (by depending on the wrapper task) and update the build script as the questions are answered.

**Comment by lacasseio** [comment] 2019-05-24 08:48
The init task should invoke the wrapper generation implementation instead of depending on the wrapper task to allow cleanup.

**Comment by dean-burdaky** [comment] 2020-02-22 11:37
I've taken a look at the issue and code on the master branch (I assume that the issue isn't stale).

I suggest that the BuildInit class be separated into its own task like "initLayout" since it seems to only generate the layout, and have a "wrapper must come after initLayout" relation. Then the init task can be an empty/null task (or if there is a special composite task type) that depends on both the wrapper and initLayout tasks.

This allows build layout generation to be invoked separately and would solve the issue above. One caveat is that a .gradle directory (and its containing files and directories) will still be generated before the questions are answered but these files and directories are generated first for all tasks invoked.

In terms of testing, some of the existing tests will need tweaking to account for the new task and structure. I also propose an additional test to be created to ensure that no files (bar the .gradle directory) are created before the last question is answered. I assume there is already a test that ensures that all the files are created once the init task is complete.

**Comment by dean-burdaky** [comment] 2020-02-28 16:50
Actually, the problem could be simply solved by changing dependsOn with finalizedBy on line 56 of the BuildInitPlugin class. Only one test needs to be changed, which is the "applies plugin" test in BuildInitPluginSpec to account for the use of finalizedBy rather than dependsOn.

**Comment by ov7a** [comment] 2024-12-12 14:27
Sorry for the late reply.

This is a duplicate of
* https://github.com/gradle/gradle/issues/18080
And it was fixed in 8.6 via
* https://github.com/gradle/gradle/pull/27408

**Closed** 2024-12-12 14:27 UTC
Labels: in:build-init-plugin, a:feature, has:release-notes
