### ISSUE TITLE
Race condition with included builds, precompiled script plugins and GradleRunner: `Accessing unreadable inputs or outputs is not supported.` and `Failed to create MD5 hash for file`

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#27591] opened 2024-01-04 21:37 UTC
### Current Behavior

When multiple nested included builds used in a multiple parallel `GradleRunner` tests, there are intermittent test flakes.

`build-logic` is an included build that has `GradleRunner` tests, and those tests use `build-logic/meta/gradle-test-kit/` and `build-logic/settings/version-catalog` as separate included builds.

AND build-logic itself relies on `build-logic/meta/gradle-test-kit/` and `build-logic/settings/version-catalog` as separate included builds.

This only happens on CI and is very intermittent (works fine 98% of the time).

it fails with a message like this:
```
  > Task :detekt:test
  
  FileExistsValueSourceTest > when detekt config file is deleted, then config cache is invalidated$detekt_test() FAILED
      org.gradle.testkit.runner.UnexpectedBuildFailure: Unexpected build execution failure in /tmp/junit1543424342434243424 with arguments [detekt, --configuration-cache, -Dorg.gradle.kotlin.dsl.precompiled.accessors.strict=true]
  
      Output:
      Calculating task graph as no cached configuration is available for tasks: detekt
      Caught exception: Already watching path: /tmp/junit1543424342434243424
      Type-safe project accessors is an incubating feature.
      > Task :settings:my-precompiled-script:checkKotlinGradlePluginConfigurationErrors
      > Task :settings:my-precompiled-script:generateExternalPluginSpecBuilders UP-TO-DATE
      > Task :settings:my-precompiled-script:extractPrecompiledScriptPluginPlugins UP-TO-DATE
      > Task :settings:my-precompiled-script:compilePluginsBlocks UP-TO-DATE
      > Task :settings:my-precompiled-script:generatePrecompiledScriptPluginAccessors UP-TO-DATE
      > Task :settings:my-precompiled-script:generateScriptPluginAdapters UP-TO-DATE
      > Task :settings:my-precompiled-script:pluginDescriptors UP-TO-DATE
      > Task :settings:my-precompiled-script:processResources UP-TO-DATE
      > Task :settings:my-precompiled-script:compileKotlin
      > Task :settings:my-precompiled-script:compileJava NO-SOURCE
      > Task :settings:my-precompiled-script:classes UP-TO-DATE
      > Task :settings:my-precompiled-script:jar UP-TO-DATE
      > Task :gradle-test-kit:checkKotlinGradlePluginConfigurationErrors
      > Task :gradle-test-kit:generateExternalPluginSpecBuilders UP-TO-DATE
      > Task :gradle-test-kit:extractPrecompiledScriptPluginPlugins UP-TO-DATE
      > Task :gradle-test-kit:compilePluginsBlocks UP-TO-DATE
      > Task :gradle-test-kit:generatePrecompiledScriptPluginAccessors UP-TO-DATE
      > Task :gradle-test-kit:generateScriptPluginAdapters UP-TO-DATE
      > Task :gradle-test-kit:pluginDescriptors UP-TO-DATE
      > Task :gradle-test-kit:processResources UP-TO-DATE
      > Task :gradle-test-kit:compileKotlin
      > Task :gradle-test-kit:compileKotlin FAILED
  
      FAILURE: Build failed with an exception.
  
      * Where:
      Settings file '/tmp/junit1543424342434243424/settings.gradle.kts' line: 12
  
      * What went wrong:
      Error resolving plugin [id: 'mycorp.repositories', version: 'unspecified']
      > A problem occurred configuring project ':settings:version-catalog'.
         > Execution failed for task ':gradle-test-kit:compileKotlin'.
            > Cannot access output property 'destinationDirectory' of task ':gradle-test-kit:compileKotlin'. Accessing unreadable inputs or outputs is not supported. Declare the task as untracked by using Task.doNotTrackState(). For more information, please refer to https://docs.gradle.org/8.5/userguide/incremental_build.html#disable-state-tracking in the Gradle documentation.
               > Failed to create MD5 hash for file '/home/runner/work/android/android/build-logic/meta/gradle-test-kit/build/classes/kotlin/main/gradle/kotlin/dsl/plugins/_09c2bbe1a08ebe8aad6ab1d54452f31c/OrgJetbrainsKotlinPluginPluginGroup.class' as it does not exist.
  
      * Try:
      > Run with --stacktrace option to get the stack trace.
      > Run with --info or --debug option to get more log output.
      > Run with --scan to get full insights.
      > Get more help at https://help.gradle.org.
  
      Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
  
      You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
  
      For more on this, please refer to https://docs.gradle.org/8.5/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
  
      BUILD FAILED in 2m 36s
      19 actionable tasks: 4 executed, 15 up-to-date
      Configuration cache entry stored.
          at app//org.gradle.testkit.runner.internal.DefaultGradleRunner.lambda$build$2(DefaultGradleRunner.java:269)
          at app//org.gradle.testkit.runner.internal.DefaultGradleRunner.run(DefaultGradleRunner.java:362)
          at app//org.gradle.testkit.runner.internal.DefaultGradleRunner.build(DefaultGradleRunner.java:267)
          at app//mycorp.FileExistsValueSourceTest.when detekt config file is deleted, then config cache is invalidated$detekt_test(FileExistsValueSourceTest.kt:35)
  Finished generating test XML results (0.01 secs) into: /home/runner/work/android/android/build-logic/detekt/build/test-results/test
  Generating HTML test report...
  Finished generating test html results (0.005 secs) into: /home/runner/work/android/android/build-logic/detekt/build/reports/tests/test
  
  > Task :detekt:test FAILED
  
  1 test completed, 1 failed
  Gradle Test Executor 8 finished executing tests.
```

### Expected Behavior

Doesn't fail because of a race condition.

### Context (optional)

possibly related to: 
- https://github.com/gradle/gradle/issues/27588
- https://github.com/gradle/gradle/issues/25204

### Steps to Reproduce

Can't reproduce, only happens on CI and only intermittently. 

### Gradle version

8.5

### Your Environment (optional)

Github Actions linux runners.

**Comment by cobexer** [comment] 2024-01-11 13:13
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.
***
Hey folks, is there enough information to start an investigation?

**Comment by mlopatkin** [comment] 2024-01-23 12:36
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #27588

Please add your use case and 👍 to that issue.

***

Both issues stems from the fact that multiple builds including the same one run concurrently and Gradle doesn't support this use case well.

**Closed by mlopatkin** 2024-01-23 12:36 UTC
Labels: a:bug, in:composite-builds, :wave: team-triage
