### ISSUE TITLE
Nondeterministic deprecation warnings caused by inconsistent, errornous task calculation in multi project build

### ISSUE THREAD

**Issue by breskeby** [gradle/gradle#16207] opened 2021-02-18 09:46 UTC
While testing the elasticsearch build against gradle `7.0-milestone-1` we run into this severe 
looking issue when calculating task dependencies.

We have a task named `JarHell` that takes filecollection as task input classpath:

```
...
...
private FileCollection classpath;
@CompileClasspath
public FileCollection getClasspath() {
    return classpath.filter(File::exists);
}

public void setClasspath(FileCollection classpath) {
    this.classpath = classpath;
}
...
...
```

See https://github.com/breskeby/elasticsearch/blob/wrong-task-dependencies-bug-repro/buildSrc/src/main/java/org/elasticsearch/gradle/precommit/JarHellTask.java#L44-L53

We configure that classpath as following in a plugin:

```
...

Configuration jarHellConfig = project.getConfigurations().create("jarHell");
  if (BuildParams.isInternal() && project.getPath().equals(":libs:elasticsearch-core") == false) {
  // ideally we would configure this as a default dependency. But Default dependencies do not work correctly
  // with gradle project dependencies as they're resolved to late in the build and don't setup according task
  // dependencies properly
            project.getDependencies().add("jarHell", project.project(":libs:elasticsearch-core"));
}
TaskProvider<JarHellTask> jarHell = project.getTasks().register("jarHell", JarHellTask.class);
jarHell.configure(t -> {
    SourceSet testSourceSet = Util.getJavaTestSourceSet(project).get();
    t.setClasspath(testSourceSet.getRuntimeClasspath().plus(jarHellConfig));
});
...
...
```
See https://github.com/breskeby/elasticsearch/blob/wrong-task-dependencies-bug-repro/buildSrc/src/main/java/org/elasticsearch/gradle/precommit/JarHellPrecommitPlugin.java#L29-L33

when running `./gradlew precommit` we see deprecation warnings like this: 

```
Validation failed for task ':example-plugins:custom-suggester:jarHell', disabling optimizations:
  - Task ':example-plugins:custom-suggester:jarHell' uses the output of task ':example-plugins:custom-suggester:compileJava', without declaring an exp
```  
Which doesn't make sense as we clearly declare the output as input. 

This made me suspicious and I digged deeper: 

1. Running `:example-plugins:custom-suggester:precommit` directly doesn't produce the deprecation warning above and the according build scan also shows that the task dependencies are set correctly

<img width="636" alt="Screenshot 2021-02-18 at 10 14 06" src="https://user-images.githubusercontent.com/77300/108338249-5486ea00-71d6-11eb-8adb-794ce9cc5ba3.png">

2. Running `gw precommit` multiple times from the example plugins project folder in `plugins/examples/` produces nondeterministic results with varying deprecation warnings. If such a deprecation warning appears, it seems to be in line in the actual task input calculation which seems off in those cases. 
In the following build scan screenshot you can see the dependency on the projects compile output is missing in those cases.

<img width="1163" alt="Screenshot 2021-02-18 at 10 11 50" src="https://user-images.githubusercontent.com/77300/108338318-69637d80-71d6-11eb-83f5-74c7eede7b41.png">
<img width="1317" alt="Screenshot 2021-02-18 at 10 10 21" src="https://user-images.githubusercontent.com/77300/108338330-6cf70480-71d6-11eb-9b4c-56bdc276f4ab.png">
<img width="675" alt="Screenshot 2021-02-18 at 10 12 18" src="https://user-images.githubusercontent.com/77300/108338348-73857c00-71d6-11eb-925a-2d669d10ec50.png">

A few times the build succeeds with no warning but mostly it fails for warnings on different subprojects. 

### Expected Behavior

Task dependencies should be calculated correctly when running a full multi project build with no deprecation warnings about missing task dependencies shown.

### Current Behavior

Currently we see the above described inconsistent errornous build output when running the full build with gradle. The task dependency bug itself is already reproducible
with Gradle 6.8.2 but was shadowed by some `shouldRunAfter` declarations we have in our build so this was only brought to our attention with 7.0-milestone-1 producing these
deprecation warnings.

### Steps to Reproduce 

1. Clone https://github.com/breskeby/elasticsearch/
2. Checkout branch `wrong-task-dependencies-bug-repro`
3. Go to the repo subproject folder `plugins/examples`
4. Run `gradle precommit --scan` multiple times and observe nondeterministtic errornous behavour

**Comment by wolfs** [comment] 2021-02-18 10:06
@breskeby This is very strange. Can you try out `7.0-20210217230314+0000` if you can reproduce the behavior?

**Comment by breskeby** [comment] 2021-02-18 10:25
@wolfs I can still reproduce the problem. The wording of the deprecation message has changed but the general behaviour is the same. 

Here are three build scans with different behaviour but same invocation just after each other:

- https://scans.gradle.com/s/5qc43hxfkfrfq
- https://scans.gradle.com/s/u6sj75ljt4jzw
- https://scans.gradle.com/s/idzuwgjvqpy2m

**Comment by wolfs** [comment] 2021-02-18 12:50
@breskeby So for clarification: The problem is not the deprecation warning, but that sometimes there is a task dependency and sometimes there is not? And that problem was already present in 6.8.1?

**Comment by breskeby** [comment] 2021-02-18 12:52
Yes. If there is a deprecation warning, the actual task dependency is indeed missing. 
I can reproduce this with 6.8.2 (without the deprecation warning obviously)

**Comment by breskeby** [comment] 2021-02-18 12:54
You can see that in the build Scans provided above

**Comment by bigdaz** [comment] 2021-02-18 17:06
@breskeby Can you attempt without `--parallel`? It would be interesting to know if the behaviour persists (with either 6.8.2 or 7.0)

**Comment by bigdaz** [comment] 2021-02-18 17:15
I'd also be interested to see if there's something different about `testSourceSet.getRuntimeClasspath()` when the different `jarHell` tasks are configured.
e.g. between these lines: 
```
    SourceSet testSourceSet = Util.getJavaTestSourceSet(project).get();
    t.setClasspath(testSourceSet.getRuntimeClasspath().plus(jarHellConfig));
```

One suspicion I have is that the `jarHell` task is realized at different points for different projects, and that this impacts whether the `testSourceSet` has been fully configured at that time. Perhaps it has an empty classpath for the cases where the tasks now fail in Gradle 7.

**Comment by breskeby** [comment] 2021-02-18 19:41
Hmm. But shouldn't runtimeClassparh be ultimately a buildable filecollection and the order of realization here shouldn't matter? I can add some debug output to see the order of realization here. Also I attached the description on how to reproduce this issue in case you missed it :-)

**Comment by breskeby** [comment] 2021-02-18 20:14
I've added the output of the `JarHellTask.classpath` in a doFirst block. I see the correct files on the classpath. I see the warning but the classpath has the output on its classpath:

```
> Task :example-plugins:rest-handler:jarHell
Validation failed for task ':example-plugins:rest-handler:jarHell', disabling optimizations:
  - Task ':example-plugins:rest-handler:jarHell' uses the output of task ':example-plugins:rest-handler:compileJava', without declaring an explicit dependency (using Task.dependsOn() or Task.mustRunAfter()) or an implicit dependency (declaring task ':example-plugins:rest-handler:compileJava' as an input). This can lead to incorrect results being produced, depending on what order the tasks are executed.
  - Task ':example-plugins:rest-handler:jarHell' uses the output of task ':example-plugins:rest-handler:pluginProperties', without declaring an explicit dependency (using Task.dependsOn() or Task.mustRunAfter()) or an implicit dependency (declaring task ':example-plugins:rest-handler:pluginProperties' as an input). This can lead to incorrect results being produced, depending on what order the tasks are executed.
Task ':example-plugins:rest-handler:jarHell' uses the output of task ':example-plugins:rest-handler:compileJava', without declaring an explicit dependency (using Task.dependsOn() or Task.mustRunAfter()) or an implicit dependency (declaring task ':example-plugins:rest-handler:compileJava' as an input). This can lead to incorrect results being produced, depending on what order the tasks are executed. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. Execution optimizations are disabled due to the failed validation. See https://docs.gradle.org/7.0-milestone-1/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
Task ':example-plugins:rest-handler:jarHell' uses the output of task ':example-plugins:rest-handler:pluginProperties', without declaring an explicit dependency (using Task.dependsOn() or Task.mustRunAfter()) or an implicit dependency (declaring task ':example-plugins:rest-handler:pluginProperties' as an input). This can lead to incorrect results being produced, depending on what order the tasks are executed. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. Execution optimizations are disabled due to the failed validation. See https://docs.gradle.org/7.0-milestone-1/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
configuring jarhell :example-plugins:rest-handler:jarHell
jarHellTask classpath file = /Users/rene/dev/elasticsearch-master/plugins/examples/rest-handler/build/generated-resources
jarHellTask classpath file = /Users/rene/dev/elasticsearch-master/plugins/examples/rest-handler/build/classes/java/main
jarHellTask classpath file = /Users/rene/dev/elasticsearch-master/test/framework/build/distributions/framework-8.0.0-SNAPSHOT.jar
jarHellTask classpath file = /Users/rene/dev/elasticsearch-master/server/build/distributions/elasticsearch-8.0.0-SNAPSHOT.jar
...
```

**Comment by bigdaz** [comment] 2021-02-18 21:58
> Also I attached the description on how to reproduce this issue in case you missed it :-)
Yes I did indeed. Reading is hard.

**Comment by ljacomet** [comment] 2021-02-19 13:54
@breskeby Could you identify a version of Gradle where this works?
I attempted to test it out on older version but that requires quite some changes to the build which made me stop 😉

**Comment by breskeby** [comment] 2021-02-19 21:26
@ljacomet I bisected our build today and the first gradle version we see this behaviour is wit Gradle 6.5. But not immediately when updating but by this change here: https://github.com/elastic/elasticsearch/commit/9526c7a4b340782892a2e4a57238f990c2ca2f42 I don't know yet why that introduced the causing the behaviour. One theory I have is that we use runtimeClasspath at some places where we probably shouldn't ¯\_(ツ)_/¯

**Comment by breskeby** [comment] 2021-02-20 18:52
@bigdaz @ljacomet I narrowed the problem further down and made another observation that might help narrowing down the problem:

If in my demo branch I change this line from @Classpath  to _@Internal_ (which I avoids calling it while calculating the task graph I guess) I cannot reproduce the issue anymore:  https://github.com/breskeby/elasticsearch/blob/wrong-task-dependencies-bug-repro/buildSrc/src/main/java/org/elasticsearch/gradle/internal/precommit/TestingConventionsTasks.java#L346  

I don't understand what's wrong with this. Do you have an idea what's going on or why that is a problem?

**Comment by bigdaz** [comment] 2021-02-20 20:15
That's an interesting finding @breskeby. I've been playing around with this too, and it seems to be related to the use of `.plus` to construct the input `FileCollection`.

Even without the separate `jarHell` configuration, if you change [these lines](https://github.com/breskeby/elasticsearch/blob/wrong-task-dependencies-bug-repro/buildSrc/src/main/java/org/elasticsearch/gradle/precommit/JarHellPrecommitPlugin.java#L31-L32) you can see if fail with this:
```
SourceSet testSourceSet = Util.getJavaTestSourceSet(project).get();
t.setClasspath(testSourceSet.getRuntimeClasspath().plus(project.files()));
```

but the task dependencies are always wired correctly without the `.plus(project.files())`:
```
t.setClasspath(testSourceSet.getRuntimeClasspath());
```
I find this issue intriguing and will keep digging :).

**Comment by breskeby** [comment] 2021-02-20 20:23
@bigdaz Interesting indeed. I had something like that under suspicion. By Coincident I have that PR that splits the setting of our JarHellTask up (see https://github.com/elastic/elasticsearch/pull/69261 ) which would solve our problem I guess, but the question remains what the root problem is here.

**Comment by breskeby** [comment] 2021-02-20 20:32
I'm not sure though this is the only place where we run into this issue in our build

**Comment by bigdaz** [comment] 2021-02-21 07:28
@gradle/execution  I'm pretty sure this comes down to a bug in the way we build the execution graph. We seem to be doing some invalid caching/clearing which produces different results based on the order of tasks added. It's quite easy to reliably reproduce this issue with the `wrong-task-dependencies-bug-repro` branch:

```
cd plugins/examples/custom-settings

# This always works
../../../gradlew jarHell testingConventions

# This always fails with a task validation error due to missing task dependencies
../../../gradlew testingConventions jarHell
```

This bug was quite difficult to nail down, and is going to be hard to explain. It is related to how we "roll up" the node values from a child into a parent node [here](https://github.com/gradle/gradle/blob/ad8c7c993bda8c2660ddd36584b2d2a035cc2e8c/subprojects/base-services/src/main/java/org/gradle/internal/graph/CachingDirectedGraphWalker.java#L155-L160). What I believe is happening is that while walking all of the edges from a top-level task dependency, we find a second node in the graph that has a direct edge to the "rolled up" child node, but not via the parent. Since the child node has had its values cleared, this secondary node is missing the required values. 

In this case, the "bad" node is produced when resolving the task dependencies of the `testingConventions` task. Now it seems that this "bad" secondary nodes does not impact the `testingConventions` task itself, but it is cached in the `CachingDirectedGraphWalker`. When resolving the task dependencies for the `jarHell` task, the bad node is taken from cache and the required task dependencies are missing.

**Comment by bigdaz** [comment] 2021-03-03 04:08
I realize that ☝️ isn't very clear.
Here’s a much simplified explanation of what I think is happening:
- When we build the execution graph, sometimes we have long chains like this: `A->B->C->[D,E]`
- For efficiency, we sometimes think it’s safe to “collapse” these chains to something like `A->B->[C,D,E]`
- The `CachingDirectedGraphWalker` will then cache the node values for `A->[B]`, `B->[CDE]`, `C->[]` , `D->[]`
- When we enter the `CachingDirectedGraphWalker` a second time to process a later requested task, we have a chain that should look like `X->C->[D,E]`. But we incorrectly get `C->[]` (no dependencies) from the cache, resulting in a chain `X->C` with D & E missing from the graph.

To map this explanation to the code here: https://github.com/gradle/gradle/blob/ad8c7c993bda8c2660ddd36584b2d2a035cc2e8c/subprojects/base-services/src/main/java/org/gradle/internal/graph/CachingDirectedGraphWalker.java#L155-L160
- `rootDetails` is `B`
- `details` is `C`
- `details.values` is `[D,E]`

You'll note the `details.values.clear()` which sets up `C` to be incorrectly cached.

**Comment by lptr** [comment] 2023-07-10 12:47
A lot has changed in scheduling since this issue was filed. Does this still happen with recent Gradle versions? If you could provide a reproducer (even if needs to be executed many times), that'd be a good step forward. Otherwise I think it's okay to close this issue.

**Comment by bigdaz** [comment] 2023-07-12 01:02
@lptr From memory, I don't think I was able to create a standalone reproducer for this issue. But it was easy to reproduce within the branch created by @breskeby . Unfortunately things have moved on and I don't think it will be easy/possible to update the reproducer to Gradle 8.

I'm conflicted about simply closing this issue as fixed:
- The [code at fault](https://github.com/gradle/gradle/blob/master/subprojects/base-services/src/main/java/org/gradle/internal/graph/CachingDirectedGraphWalker.java#L155-L160) has not changed since this issue was raised, so it's likely this issue still exists.
- If this was impacting many other projects, you'd think we'd have heard about it!

In the end, I'm OK if you want to close it.

**Comment by lptr** [comment] 2023-08-11 12:13
Let's close this, and if it comes up again with a newer version we can investigate.

**Closed by lptr** 2023-08-11 12:13 UTC
Labels: a:bug, @execution, in:scheduler, :wave: team-triage
