### ISSUE TITLE
Convert `buildSrc` to be an implicit, included build

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#2532] opened 2017-07-19 19:02 UTC
@bigdaz commented on [Wed Aug 24 2016](https://github.com/gradle/composite-builds/issues/66)

Note that if `buildSrc` is included within `gradle.includedBuilds`, then the BuildScan plugin will no longer have a way to identify a composite build.

---

@hansd commented on [Wed Aug 24 2016](https://github.com/gradle/composite-builds/issues/66#issuecomment-242275214)

This is exciting. How would we implement it. What kind of dependency is substituted?

---

@adammurdoch commented on [Thu Aug 25 2016](https://github.com/gradle/composite-builds/issues/66#issuecomment-242562932)

There wouldn't be any substitution as such. Instead, this would be making the existing cross build dependency explicit to pick up all the other good stuff that composite builds provides (or will provide): visibility in the IDE model and events, sharing configuration between the main build and buildSrc build through configuration injection (or whatever mechanism), addressing the tasks of the buildSrc build from the main build and command-line, visibility in build scans, being able to lifecycle buildSrc outputs (publish them for example) and so on.

It would also open the door to dependency substitution in build logic classpaths (eg use a plugin instance built locally instead of from a binary repo).

---

@oehme commented on [Fri Aug 26 2016](https://github.com/gradle/composite-builds/issues/66#issuecomment-242695126)

I think plugin dependencies are already substituted when you have the plugin locally in your composite.

---

@big-guy commented on [Mon Mar 27 2017](https://github.com/gradle/composite-builds/issues/66#issuecomment-289506977)

And this would hopefully remove the need for nasty hacks like this: https://github.com/gradle/gradle/pull/1622

---

@adammurdoch commented on [Mon Apr 17 2017](https://github.com/gradle/composite-builds/issues/66#issuecomment-294620766)

Rather than treat this as a single large piece of work (which we'll probably never do), we should instead make sure that each feature we implement for composite builds works with all _nested_ builds rather than just _included_ child builds, where it makes sense for that feature. Given that `buildSrc` and included builds are different kinds of nested builds, this means that we'll incrementally close the gap between `buildSrc` and composite builds.

For example, IDE integration or configuration injection or dependency substitution or addressing tasks from the command-line would all make sense for nested builds.

---

@adammurdoch commented on [Mon Apr 17 2017](https://github.com/gradle/composite-builds/issues/66#issuecomment-294620983)

Of course, another approach would be to leave `buildSrc` alone and deprecate it as a thing, once an included build can contribute to the build script classpath of another build.

---

@oehme commented on [Mon Apr 17 2017](https://github.com/gradle/composite-builds/issues/66#issuecomment-294678973)

@adammurdoch included builds can already contribute to the buildscript classpath of other builds.

---

@adammurdoch commented on [Tue Apr 18 2017](https://github.com/gradle/composite-builds/issues/66#issuecomment-295027130)

Perhaps we should think about a soft deprecation of `buildSrc` then, for example by starting to change the guides/user guide/samples to use a composite build instead of `buildSrc`.

---

@bigdaz commented on [Wed Jul 19 2017](https://github.com/gradle/composite-builds/issues/66#issuecomment-316485061)

Issue moved to [gradle/gradle #2531](https://github.com/gradle/gradle/issues/2531) via [**ZenHub**](https://www.zenhub.com/)

**Comment by oehme** [comment] 2017-09-06 13:07
Duplicate of #2531

**Closed by oehme** 2017-09-06 13:07 UTC
Labels: a:feature, from:member, in:composite-builds
