### ISSUE TITLE
External Dependencies downloaded but not pulled in IntelliJ even after clearing gradle cache

### ISSUE THREAD

**Issue by natty4GitHub** [gradle/gradle#2400] opened 2017-07-06 16:43 UTC
###Summary
Generated project with  gradle file from Spring.io. 

I added few dependencies like okhttp and following that i had add gson dependency to prettify json and gemfire for inmemory. but the last dependencies never appears in the project compilation in IntelliJ. I can't use the library. Infact can't use any latest library. However i see them being pulled when i run the commands below. I have tried clearing the gradle cache etc.

rm -rf $HOME/.gradle/caches/
./gradlew clean build

buildscript {
ext {
springBootVersion = '1.5.3.RELEASE'
}
repositories {
mavenCentral()
}
dependencies {
classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
}
}

apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'org.springframework.boot'

jar{
baseName = 'xxxxx-rest-service'
version = '0.1.0'
}

version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
mavenCentral()
}

dependencies {
compile('com.google.code.gson:gson:2.2.4')
compile('org.apache.cxf:cxf-spring-boot-starter-jaxrs:3.1.11')
compile ('com.squareup.okhttp3:okhttp:3.8.0')
//compile('org.springframework.boot:spring-boot-starter-data-gemfire')
compile('org.springframework.boot:spring-boot-starter-jersey')
compile('org.springframework.kafka:spring-kafka')
compile('org.springframework.boot:spring-boot-starter-web')
runtime('org.springframework.boot:spring-boot-devtools')
runtime('org.postgresql:postgresql')
testCompile('org.springframework.boot:spring-boot-starter-test')
}

### Expected Behavior
dependencies{
compile('com.google.code.gson:gson:2.2.4')
compile('org.springframework.boot:spring-boot-starter-data-gemfire')
}

Adding above dependencies to build.gradle. I should expect the Gradle:com.google.code.gson:2.2.4 or gemstone.gemfire appear in the External Libraries of Project windows in IntelliJ.

### Current Behavior

Initial gradle version was 3.3. I have upgraded to 4.0. I still couldn't see the external dependencies importable into Intellij after clean build following cache reset.
for instance 
dependencies{
compile('com.google.code.gson:gson:2.2.4')
compile('org.springframework.boot:spring-boot-starter-data-gemfire')
}

Appending above dependencies to build.gradle.
Then after i run ./gradlew build. The build is successful however the External Libraries in Intellij does not display Gradle:com.google.code.gson:2.2.4 or gemstone.gemfire also happened with okhttp3 dependency. This is happened after a gradle upgrade from 3.3.

I have even updated to 4 using brew and did do ./gradlew clean build yet no dependencies reappear. I can't import/use the libraries.

### Context

I am unable to add new libraries such as new dependencies like new http client or prettyprint or in-memory database etc. 

rm -rf $HOME/.gradle/caches/
./gradlew clean build
./gradlew idea

https://discuss.gradle.org/t/external-dependencies-not-pulled-after-clearing-gradle-cache/23137/4

### Steps to Reproduce (for bugs)
Download a new springbootproject from spring.io

use the following build.gradle.
buildscript {
ext {
springBootVersion = '1.5.3.RELEASE'
}
repositories {
mavenCentral()
}
dependencies {
classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
}
}

apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'org.springframework.boot'

jar{
baseName = 'xxxxx-rest-service'
version = '0.1.0'
}

version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
mavenCentral()
}

dependencies {
compile('com.google.code.gson:gson:2.2.4')
compile('org.apache.cxf:cxf-spring-boot-starter-jaxrs:3.1.11')
compile ('com.squareup.okhttp3:okhttp:3.8.0')
//compile('org.springframework.boot:spring-boot-starter-data-gemfire')
compile('org.springframework.boot:spring-boot-starter-jersey')
compile('org.springframework.kafka:spring-kafka')
compile('org.springframework.boot:spring-boot-starter-web')
runtime('org.springframework.boot:spring-boot-devtools')
runtime('org.postgresql:postgresql')
testCompile('org.springframework.boot:spring-boot-starter-test')
}

### Your Environment

macoS Sierra, JVM 8. Gradle 2.14, 3.5 and 4.

**P.S:** Started seeing the issues after i upgraded the gradle from 3.3 to 3.5

 * Build scan URL: 
https://gradle.com/s/xgad7ogceyfsu
Looking forward to a fix or response.

**Comment by bmuschko** [comment] 2017-07-10 20:05
You will need to click the "refresh the dependencies options" in IntelliJ whenever you change the list of dependencies or activate the "auto-import" function.

**Comment by oehme** [comment] 2017-07-14 17:55
This is a duplicate of https://github.com/gradle/gradle/issues/1276. Please upgrade to the latest IntelliJ version.

**Closed by oehme** 2017-07-14 17:55 UTC
Labels: a:question, from:contributor, in:idea-plugin
