### ISSUE TITLE
Not able to download dependency metadata into custom directory

### ISSUE THREAD

**Issue by ylu36** [gradle/gradle#20783] opened 2022-05-13 19:44 UTC
Not able to download dependency metadata into custom directory

### Expected Behavior
Able to pass an env var `GRADLE_USER_HOME=` and have dependency metadata downloaded into it

### Current Behavior
A `.cache` is created under user-specified `GRADLE_USER_HOME` but no `files-2.1/` under `.gradle/caches/modules-2/`

### Context

gradle 7.4.2 is what I'm using and having the issue

I'm trying to compile a list of dependencies in order to build a gradle project. I'd like to obtain package metadata from examining *.pom files.

### Steps to Reproduce 

Use a simple `build.gradle`, and run `gradle  -g <dir> build`

### Your Environment
```
 gradle -v

------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Build time:   2022-03-31 15:25:29 UTC
Revision:     540473b8118064efcc264694cbcaa4b677f61041

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          18.0.1 (Homebrew 18.0.1+0)
OS:           Mac OS X 12.3.1 x86_64

```
Build scan URL:

**Comment by hegyibalint** [comment] 2022-05-16 14:53
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

This issue will be closed after 7 days, unless you can provide more information.

---

We are pretty sure that this works, as we have integration tests that rely on this behavior.
You marked this as a regression. Do you have a version, where this was working?

**Comment by ylu36** [comment] 2022-05-16 16:32
@hegyibalint sorry if I haven't explained well.

Basically, for any `build.gradle` such as [this one](https://docs.gradle.org/current/samples/sample_building_android_apps.html), I'm trying to run a `gradle build`.  I would like to specify a flag `GRADLE_USER_HOME` to point to a location on my file system (e.g. `-g /var/gradle`). I would  be able to see a `caches/` directory created under it and has layout same as https://docs.gradle.org/current/userguide/directory_layout.html, but I don't see any downloaded cache (i.e. package jars and their .pom)

I added the `regression` tag because I've seen people saying the flag worked for them in the past, so I don't know if the version I'm using (7.4.2) has a regression or if I'm doing something wrong myself (hopefully latter)

**Comment by ov7a** [comment] 2023-08-08 10:10
Sorry for the late reply.

I can't reproduce this issue. This works as expected.

P.S. Please, don't abuse the `regression` label. It should only be used for cases when a newer version breaks something that worked in previous versions.

**Closed by ov7a** 2023-08-08 10:10 UTC
Labels: a:regression
