### ISSUE TITLE
Make a decision wrt staying on Kotlin 1.7 with language 1.5 or moving to Kotlin 1.8 with language 1.8 for 8.0

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#23130] opened 2022-12-13 11:13 UTC
Moving to 1.8.0 with language 1.8 is the desired goal. Kotlin 1.7.x contains regressions in the IR backend with language/api >= 1.6 that currently block us on language/api 1.5. Kotlin 1.8.0-RC2 will have the fixes for the ones we identified so far ([KT-55065](https://youtrack.jetbrains.com/issue/KT-55065), [KT-55068](https://youtrack.jetbrains.com/issue/KT-55068)).

**Comment by efemoney** [comment] 2022-12-18 03:39
I know this is not a poll but I personally vote for Kotlin 1.8 with language 1.8. There is literally **no reason** to lag behind Kotlin in this case (at least none that is immediately obvious to me)

**Comment by ZacSweers** [comment] 2022-12-18 03:59
Move to 1.8. There is no reason to target such low kotlin versions and not moving to latest even at major version updates would be hard to understand.

If the fear is that it is too big of a jump, then perhaps gradle should start following kotlin versions more closely between major releases rather than only updating once a year (when kotlin itself updates minor versions 2x/year). Otherwise this will continue to happen.

**Comment by eskatos** [comment] 2022-12-18 09:19
Moving to 1.8.0 with language 1.8 is the desired goal or course. Kotlin 1.7.x contain regressions in the IR backend with language >= 1.6 that currently prevent us from using it. Kotlin 1.8.0-RC2 will have the fixes for the ones we identified so far ([KT-55065](https://youtrack.jetbrains.com/issue/KT-55065), [KT-55068](https://youtrack.jetbrains.com/issue/KT-55068))

Sorry for not adding the above to the issue description in the first place.

@ZacSweers, we always upgrade Kotlin on minor versions when this is possible (no functional regression and no significant performance regression). What we don't change in minor releases is the Kotlin language/api level). This can be seen in our [compatibility matrix](https://docs.gradle.org/current/userguide/compatibility.html#kotlin).

* PR draft https://github.com/gradle/gradle/pull/23214

**Comment by ljacomet** [comment] 2022-12-21 17:19
RC2 of Kotlin 1.8.0 landed today and seems to be good to go on our side, reported regressions are confirmed fixed.
With the given calendar for Kotlin 1.8.0 and Gradle 8.0, we should be able to release in time even if the Kotlin release slips.

So Gradle 8.0 will embark Kotlin 1.8.0 and use Kotlin language level 1.8.

**Closed by ljacomet** 2022-12-21 17:19 UTC
Labels: in:kotlin-dsl, a:investigation

**Comment by ZacSweers** [comment] 2022-12-21 17:35
Glad to see this, though I'd still recommend considering raising the language/api level more frequently. Going from 1.4 -> 1.8 is a significant jump.
