### ISSUE TITLE
Allow custom JvmInstallationMetadataMatcher.test

### ISSUE THREAD

**Issue by cmcm-devel** [gradle/gradle#31000] opened 2024-10-23 16:55 UTC
### Expected Behavior

Allow defining a downloaded toolchain as valid, override **org.gradle.jvm.toolchain.internal.JvmInstallationMetadataMatcher.test** method in some way.

### Current Behavior (optional)

The class **org.gradle.jvm.toolchain.internal.JvmInstallationMetadataMatcher** is used, it is not possible to extend it and use a custom one

### Context

This would allow more flexibility when designing a **JavaToolchainResolver**.

I made one to download toolchain from a parameterized url with variables like:
   https://download.oracle.com/graalvm/${ver}/latest/graalvm-jdk-${ver}_${os}-${arch}_bin.tar.gz
but I use **JavaToolchainRequest** **vendor** to pass url, and finally it can't pass the final check even though I download it

Thank you very much for your work. Regards

**Comment by abstratt** [comment] 2024-10-24 13:04
This issue will be closed as a duplicate of

* #18896

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

There are no plans to allow disabling validation of JVM installations.

**Closed by abstratt** 2024-10-24 13:04 UTC
Labels: closed:duplicate, in:toolchains, to-triage
