### ISSUE TITLE
Gradle cannot snapshot classes in icu4j

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#1305] opened 2017-02-02 22:31 UTC
### Expected Behavior

Compilation does not fail.

### Current Behavior

com.ibm.icu:icu4j:2.6.1 has classes compiled with Java 1.1 and Java 1.2. When this jar is on the classpath, the incremental snapshotter fails with a ArrayIndexOutOfBoundsException deep down in ASM code. I tried splitting this jar into 1.1 classes and 1.2 classes. 1.1-only jar works. 1.2-only jar does not.

### Context

Two problems this is causing:
https://discuss.gradle.org/t/could-not-calculate-the-signature-for-jar-file-icu4j/21452
https://discuss.gradle.org/t/could-not-expand-zip-error-while-using-incremental-java-compilation/15689

### Steps to Reproduce (for bugs)

https://github.com/gradle/gradle/blob/master/subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/SourceIncrementalJavaCompilationIntegrationTest.groovy#L489-L500

Migrated from: https://issues.gradle.org/browse/GRADLE-3426

**Comment by big-guy** [comment] 2017-02-02 22:40
Looking at the icu4j jar a bit more, I think it's not Java 1.2 but something particular with the class `com/ibm/icu/impl/data/LocaleElements_zh__PINYIN.class`

**Comment by big-guy** [comment] 2017-02-02 23:14
@melix I looked to see if there was something simple we could do for this.  Even `javap` barfs on `com/ibm/icu/impl/data/LocaleElements_zh__PINYIN` from the icu4j jar.

**Comment by melix** [comment] 2017-02-03 07:28
This looks more like a corrupt class file. So far we've said "fail early" on this case. Would using a different version of ICU be an option?

**Comment by big-guy** [comment] 2017-02-03 20:42
It looks like this is the newest version for the 2.x line on Maven Central.  Is there any kind of workaround for this if you can't upgrade?  This happens with or without the incremental compiler.

I wonder if this is a valid class file on a IBM JVM?

@adammurdoch do you still want this behavior fixed in another 3.4 RC?

**Comment by adammurdoch** [comment] 2017-02-03 22:13
Not if it's a badly formed class file. Note that "badly formed class file" here means "badly formed according to the JVM spec" not "some tools can't read it".

**Comment by idlsoft** [comment] 2017-02-06 05:06
I'm having a very similar issue. A different jar, also started with 3.4-rc-1:

            at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
            at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
            at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
            at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
    Caused by: org.gradle.api.UncheckedIOException: Could not calculate the signature for Jar file C:\Users\-----\.gradle\caches\modules-2\files-2.1\net.sf.ehcache\ehcac
    7433b483b9d485fe\ehcache-2.6.0.pom
            at org.gradle.api.internal.changedetection.state.JvmClassHasher.hashJarFile(JvmClassHasher.java:115)
            at org.gradle.api.internal.changedetection.state.DefaultCompileClasspathSnapshotter.normaliseFileElement(DefaultCompileClasspathSnapshotter.java:72)
            at org.gradle.api.internal.changedetection.state.AbstractFileCollectionSnapshotter$FileCollectionVisitorImpl.visitCollection(AbstractFileCollectionSnapshotter.
            at org.gradle.api.internal.file.AbstractFileCollection.visitRootElements(AbstractFileCollection.java:234)
            at org.gradle.api.internal.file.CompositeFileCollection.visitRootElements(CompositeFileCollection.java:185)
            at org.gradle.api.internal.changedetection.state.AbstractFileCollectionSnapshotter.snapshot(AbstractFileCollectionSnapshotter.java:71)
            at org.gradle.api.internal.changedetection.rules.AbstractNamedFileSnapshotTaskStateChanges.buildSnapshots(AbstractNamedFileSnapshotTaskStateChanges.java:87)
            ... 74 more
    Caused by: java.util.zip.ZipException: error in opening zip file
            at org.gradle.api.internal.changedetection.state.JvmClassHasher.hashJarFile(JvmClassHasher.java:101)
            ... 80 more

**Comment by melix** [comment] 2017-02-06 08:54
@idlsoft This looks like a different issue. It says it cannot calculate the hash of a jar file, but what shows up in the logs is the POM file, which should never be hashed. We've seen a similar cache corruption issue in the past, but never managed to reproduce. Do you by chance have a build scan of this failing build?

**Comment by idlsoft** [comment] 2017-02-06 14:58
@melix That may not be so easy, I'm behind a firewall.

**Comment by melix** [comment] 2017-02-06 15:03
No worries, in any case once the cache is corrupt you won't get the same stack trace.

**Comment by idlsoft** [comment] 2017-02-06 15:15
@melix What's interesting about this dependency is that none of our modules declare it, it's only mentioned in excludes.
So perhaps what may have changed is the order of operations - analysis before exclusion.

**Comment by oehme** [comment] 2017-02-16 11:10
This has been fixed by https://github.com/gradle/gradle/pull/1359

**Closed by oehme** 2017-02-16 11:10 UTC
Labels: a:bug, affects-version:3.4, from:contributor, in:core

**Comment by aesteve** [comment] 2017-06-30 06:51
I've got the exact same issue with `options.incremental = true` in Gradle 4.0.

If I remove this option, the project is compiling well.

Sorry to raise this issue from the dead, maybe I should open a new one ?

**Comment by oehme** [comment] 2017-06-30 11:00
@aesteve please open a new issue with a reproducible example attached.
