### ISSUE TITLE
Mistakenly recognized 0.7.0+26 as maven incompatible

### ISSUE THREAD

**Issue by elect86** [gradle/gradle#16555] opened 2021-03-16 17:31 UTC
Snapshot versions in the format of `${last tag}+${number of commits since that tag}` would be mistakenly identified as dynamic versions and then declared as maven incompatible

This is too blunt (thanks @Vampire for finding this out)

    private boolean isVersionMavenIncompatible(String version) {
        if (version == null) {
            return false;
        }
        if (version.contains("+")) {
            return true;
        }
        if (version.contains("latest")) {
            return !MavenVersionSelectorScheme.isSubstituableLatest(version);
        }
        return false;
    }

### Expected Behavior
no warning

### Current Behavior

> Maven publication 'maven' pom metadata warnings (silence with 'suppressPomMetadataWarningsFor(variant)'):
  - Variant runtimeElements:
      -  contains dependencies that will produce a pom file that cannot be consumed by a Maven client.
          - kotlin.graphics.build-logic:platform-source:0.7.0+26 declared with a Maven incompatible version notation
These issues indicate information that is lost in the published 'pom' metadata file, which may be an issue if the published library is consumed by an old Gradle version or Apache Maven.
The 'module' metadata file, which is used by Gradle 6+ is not affected.

### Context
I was declaring a dependency with the following GAV
`kotlin.graphics.build-logic:platform-source:0.7.0+26`

### Steps to Reproduce 
I can provide a repo in a moment, if needed

### Your Environment
same as with the build scan
Gradle 7.0 M3

**Comment by Vampire** [comment] 2021-03-16 17:37
`+` is also a valid character in version following the semver specification.
Imho also having `.contains("latest")` is too blunt.
It should probably be `.endsWith(".+")` and `.startsWith("latest.")`.

**Comment by ljacomet** [comment] 2021-03-17 09:49
Thanks for reporting this. I agree with @Vampire for the fixes.

That looks like a good candidate for a contributed fix if anyone is interested.

**Comment by elect86** [comment] 2021-03-17 10:52
Given the simplicity of the fix, would you still like to have test regarding this?

**Comment by ljacomet** [comment] 2021-03-17 11:06
Yes please, makes sure it never regresses.

**Comment by stephengold** [comment] 2021-04-23 06:08
I've encountered this issue in the 7.0 release. Can it please be fixed in 7.0.1?

**Comment by ljacomet** [comment] 2021-04-23 08:06
Added to 7.0.1 for consideration. Taking community contribution for this one 😉

**Comment by stephengold** [comment] 2021-04-23 17:23
Perhaps @elect86 could submit their PR without providing any new tests.

**Comment by elect86** [comment] 2021-04-25 08:04
Done

**Comment by ljacomet** [comment] 2021-04-29 13:24
This will not be done for 7.0.1 as this is not a regression from 7.0.

The team has also limited bandwidth to tackle this right now.

Thanks for the initial PR, let's keep the discussion there but as mentioned earlier, it will require tests to be merged.

**Comment by stephengold** [comment] 2021-04-29 16:50
Since 6.8.3 did not generate warnings for "cannot be consumed by a Maven client", the messages appearing in 7.0 sure looked like a regression to the end user.

**Comment by buzmeg** [comment] 2021-05-22 01:30
Does this fix actually fix these issues where Gradle is barfing on various version numbers with strange characters?

https://github.com/cossacklabs/themis/pull/824
https://github.com/flutter/flutter/issues/75600

**Comment by Vampire** [comment] 2021-05-22 09:02
No, this PR just fixes a false warning when publishing.

What you link to has nothing to do with Gradle itself, even if the people like to blame Gradle or call it "rot" or whatever. That just shows they cannot read. :-D
The stack trace of the error clearly shows that this happens in `com.android.` classes, so this seems to be a problem in the Android Gradle plugin and is nothing that could be fixed within Gradle. Instead a report has to be done to Google if there is none yet.

**Comment by buzmeg** [comment] 2021-05-22 09:58
If you point me at the appropriate spot, I will *happily* harass the relevant Google people.  Unfortunately, apparently none of us (including Flutter folks!) seem to be able to hit anyone in Google with the correct authority to, you know, fix the stupid bug.

**Comment by Vampire** [comment] 2021-05-22 23:50
I'm not an android dev. But this page seems to list known issues of AS and AGP and then also links to how to properly report new bugs: https://developer.android.com/studio/known-issues

**Comment by Vampire** [comment] 2021-05-22 23:53
Btw. I'm **not** on the Gradle team like you stated in that flutter issue. I'm just a user, contributor and fellow (https://blog.gradle.org/gradle-fellowship), so I don't do any official statements or similar.

**Comment by buzmeg** [comment] 2021-05-23 00:16
My fault for my imprecise language.  I just meant that someone who actually does some coding on Gradle looked at it.

I certainly wasn't trying to imply anything "official".  My apologies.

Sorry, for accidentally causing you grief.

**Closed** 2021-05-27 08:51 UTC
Labels: @core, a:bug, in:dependency-management
