### ISSUE TITLE
A quite odd configuration cache problem

### ISSUE THREAD

**Issue by tg-freigmbh** [gradle/gradle#31361] opened 2024-11-20 14:18 UTC
### Current Behavior

Put this in your settings.gradle.kts

```
val value = "world"
gradle.lifecycle.beforeProject {
    project.extra["hello"] = value
}
```
This will fail:

```
* What went wrong:
Failed to notify build listener.
> Failed to isolate 'GradleLifecycle' action: cannot serialize Gradle script object references as these are not supported with the configuration cache
```
However there is an intresting workaround:

```
if (true) {
    val value = "world"
    gradle.lifecycle.beforeProject {
        project.extra["hello"] = value
    }
}
```
Surround the offending code using if (true) and gradle will stop complaining... 

### Expected Behavior

Well this should be fixed or if it cant be fixed the error message could be more helpfull... 

### Self-contained Reproducer Project

[intellijBug.zip](https://github.com/user-attachments/files/17831944/intellijBug.zip)

### Gradle version

8.11

**Comment by reinsch82** [comment] 2024-11-21 12:53
The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by mlopatkin** [comment] 2024-11-22 17:37
This issue will be closed as a duplicate of

* #22879

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

This is a known peculiarity of the Kotlin script compilation, which we'll eventually address.

**Closed by mlopatkin** 2024-11-22 17:37 UTC
Labels: a:bug, in:configuration-cache, closed:duplicate, has:workaround
