### ISSUE TITLE
NoMatchingTestsReporter should not fail build if it would fail anyway

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#12366] opened 2020-02-27 09:56 UTC
If you unpack the [attached example project](https://github.com/gradle/gradle/files/4260881/bar.zip) the following behavior can be observed:

`./gradlew test -P failOnNoMatchingTests=false` => build failed with "failing tests"
`./gradlew test -P failOnNoMatchingTests=false --tests foo` => build successful, because no matching tests found
`./gradlew test -P failOnNoMatchingTests=false --tests bar.Engine` => build failed with "failing tests"
`./gradlew test -P failOnNoMatchingTests=true` => build failed with "failing tests"
`./gradlew test -P failOnNoMatchingTests=true --tests foo` => build failed with "no tests found"
`./gradlew test -P failOnNoMatchingTests=true --tests bar.Engine` => build failed with "no tests found"

All is ok, except for the last one.
Imho this should fail.
I think the problem is in `NoMatchingTestsReporter` that relies on the `testCount` of the result.
But as there was an exception in the class, Gradle did not increase the test count, so the result type is `FAILURE`, but the `testCount` is 0.
So either the `testCount` should not be `0`, or (/ and) the `NoMatchingTestsReporter` should only operate if the result type is `SUCCESS`.

**Comment by marcphilipp** [comment] 2020-02-28 08:20
I think this is a duplicate of #12073 but adds a good analysis of where in the implementation it goes wrong.

**Closed** 2020-02-28 09:14 UTC
Labels: a:bug, from:contributor
