### ISSUE TITLE
Gradle throws/catches a lot of exceptions in AttributeMatchingVariantSelector

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#24103] opened 2023-03-01 20:50 UTC
During a profiling of [androidx](https://github.com/androidx/androidx) project I found that Gradle is throwing/catching around 290K instances of `org.gradle.internal.component.NoMatchingVariantSelectionException`

### Expected Behavior
No `org.gradle.internal.component.NoMatchingVariantSelectionException`

### Current Behavior
290K instances of `org.gradle.internal.component.NoMatchingVariantSelectionException`

It seems to happen here
```
org.gradle.api.internal.artifacts.transform.AttributeMatchingVariantSelector.doSelect(AttributeMatchingVariantSelector.java)
org.gradle.api.internal.artifacts.transform.AttributeMatchingVariantSelector.select(AttributeMatchingVariantSelector.java:93)
org.gradle.configurationcache.serialization.codecs.LocalFileDependencyBackedArtifactSetCodec$encode$3.accept(LocalFileDependencyBackedArtifactSetCodec.kt:113)
org.gradle.configurationcache.serialization.codecs.LocalFileDependencyBackedArtifactSetCodec$encode$3.accept(LocalFileDependencyBackedArtifactSetCodec.kt:111)
org.gradle.api.internal.artifacts.type.DefaultArtifactTypeRegistry.visitArtifactTypes(DefaultArtifactTypeRegistry.java:73)
org.gradle.configurationcache.serialization.codecs.LocalFileDependencyBackedArtifactSetCodec.encode(LocalFileDependencyBackedArtifactSetCodec.kt:111)
org.gradle.configurationcache.serialization.codecs.LocalFileDependencyBackedArtifactSetCodec.encode(LocalFileDependencyBackedArtifactSetCodec.kt:75)
org.gradle.configurationcache.serialization.codecs.BindingsBackedCodec.encode(BindingsBackedCodec.kt:52)
org.gradle.configurationcache.serialization.DefaultWriteContext.write(Contexts.kt:86)
org.gradle.configurationcache.serialization.CombinatorsKt.writeCollection(Combinators.kt:232)
org.gradle.configurationcache.serialization.codecs.FileCollectionCodec.encodeContents(FileCollectionCodec.kt:64)
org.gradle.configurationcache.serialization.codecs.FileCollectionCodec.encode(FileCollectionCodec.kt:57)
org.gradle.configurationcache.serialization.codecs.FileCollectionCodec.encode(FileCollectionCodec.kt:49)
org.gradle.configurationcache.serialization.codecs.BindingsBackedCodec.encode(BindingsBackedCodec.kt:52)
org.gradle.configurationcache.serialization.DefaultWriteContext.write(Contexts.kt:86)
org.gradle.configurationcache.serialization.codecs.transform.TransformStepSpecCodec.encode(Transforms.kt:57)
org.gradle.configurationcache.serialization.codecs.transform.TransformStepSpecCodec.encode(Transforms.kt:52)
org.gradle.configurationcache.serialization.codecs.BindingsBackedCodec.encode(BindingsBackedCodec.kt:52)
org.gradle.configurationcache.serialization.DefaultWriteContext.write(Contexts.kt:86)
org.gradle.configurationcache.serialization.codecs.transform.InitialTransformationNodeCodec.doEncode(InitialTransformationNode...
```

### Context
Profiling using YourKit

### Steps to Reproduce 
```
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/yourkit/bin/linux-x86-64/ ./gradlew zipTestConfigsWithApks zipConstrainedTestConfigsWithApks zipOwnersFiles createModuleInfo --dry-run -Pandroidx.profile.yourkitAgentPath=/usr/local/google/home/aurimas/yourkit/bin/linux-x86-64/libyjpagent.so
```
in androidx checkout.

![image](https://user-images.githubusercontent.com/1418185/222261691-19325a0d-5b5c-42b3-9248-a5d6268f3dd0.png)

**Comment by liutikas** [comment] 2023-03-01 20:51
Using Gradle 8.0, Android Gradle Plugin 8.0.0-beta03

**Comment by eskatos** [comment] 2023-03-03 08:36
Thank you for your interest in Gradle!

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by adammurdoch** [comment] 2023-03-09 21:35
Fixed via https://github.com/gradle/gradle/pull/24242

**Closed by adammurdoch** 2023-03-09 21:35 UTC
Labels: a:bug, in:configuration-cache, in:artifact-transforms
