### ISSUE TITLE
Configuration cache fails when Kotlin delegated properties are used

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#23092] opened 2022-12-10 09:07 UTC
Given the following example project on the latest Gradle 8 snapshot:

```
val fizz by configurations.creating

tasks {
  val foo by registering {
  }

  val bar by registering {
    dependsOn(foo)
    inputs.files(fizz)
    doFirst {
       val baz = fizz.files
    }
  }
}
```

When I run `gradlew bar --configuration-cache`, it fails with

```
Configuration cache state could not be cached: field `value` of `kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal` bean found in field `_descriptor` of `kotlin.reflect.jvm.internal.KProperty0Impl` bean found in field `$foo$metadata` of `Build_gradle$$special$$inlined$invoke$lambda$1` bean found in field `this$0` of `Build_gradle$$special$$inlined$invoke$lambda$1$1` bean found in field `action` of `org.gradle.api.internal.AbstractTask$TaskActionWrapper` bean found in field `actions` of task `:bar` of type `org.gradle.api.DefaultTask`: error writing value of type 'java.lang.ref.SoftReference'
> Unable to make field private long java.lang.ref.SoftReference.timestamp accessible: module java.base does not "opens java.lang.ref" to unnamed module @4c87224b
```

It succeeds if I either remove the `dependsOn(foo)` line or the `val baz = fizz.files` line. The underlying issue seems to be that the `doFirst` lambda captures the `KProperty` holding `foo` and Gradle tries to serialize that.

**Comment by xaviarias** [comment] 2022-12-14 08:58
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and prioritized by them.

---

As a workaround please don't use delegated properties.

**Comment by eskatos** [comment] 2022-12-14 09:05
This was already failing with Gradle 7.5 and 7.6. But it makes both fail with OOMEs!
https://scans.gradle.com/s/rt327imceowzi

BTW the provided reproducer also fails to build without CC because the configuration is invalid
https://gradle.com/s/i7pv2k6ktn3rq
But this doesn't make the behaviour with CC enabled good anyway.

**Comment by oehme** [comment] 2022-12-14 09:45
@eskatos right, I had made a type (file instead of files). The real code that's suffering from this CC issue was using `files`.

@xaviarias Removing delegated properties is not an option for me. It would mean making a lot of build scripts non-idiomatic Kotlin. I'll just wait for this bug to be fixed before trying CC again.

**Comment by oehme** [comment] 2022-12-30 14:30
@eskatos is this planned for 8.0, given that RC1 was just released?

**Comment by bamboo** [comment] 2023-01-03 13:02
Hi @oehme, this is not planned for 8.0.

**Comment by mlopatkin** [comment] 2023-08-28 11:39
This particular issue is no longer reproducible as of Gradle 8.0. Instead a correct `cannot serialize Gradle script object references as these are not supported with the configuration cache` is reported, because of the `fizz` reference in the `doFirst` action. The latter is a [known issue](https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:not_yet_implemented:accessing_top_level_at_execution), and can be fixed by narrowing the scope:
```kotlin
tasks {
  val bar by registering {
    // ...
    val fizz: FileCollection = fizz
    doFirst {
       val baz = fizz.files
    }
  }
}
```

The fix comes from the Kotlin compiler updated to 1.8, and, likely, the new compilation backend being used. The generated property-related code is completely different.

**Comment by mlopatkin** [comment] 2023-09-19 07:53
Please reply here or open a new issue if similar problems occur in a newer version of Gradle.

**Closed by mlopatkin** 2023-09-19 07:53 UTC
Labels: a:bug, in:configuration-cache, has:reproducer, has:workaround
