### ISSUE TITLE
Provide a public API to access host OS and architecture

### ISSUE THREAD

**Issue by urdak** [gradle/gradle#16598] opened 2021-03-20 23:06 UTC
### Expected Behavior
A public API should be available to access the host OS and architecture.

### Current Behavior
Currently the functionality exists as an internal implementation class, which is part of the native platform support:
```kotlin
import org.gradle.nativeplatform.internal.DefaultTargetMachineFactory
val host = gradle.serviceOf<DefaultTargetMachineFactory>().host()
```
### Context

Gradle provides a public API to build a "native machine variant" via the [TargetMachineFactory](https://github.com/gradle/gradle/blob/master/subprojects/platform-native/src/main/java/org/gradle/nativeplatform/TargetMachineFactory.java) service and the corresponding [OperatingSystemFamily](https://github.com/gradle/gradle/blob/master/subprojects/platform-native/src/main/java/org/gradle/nativeplatform/OperatingSystemFamily.java)/[MachineArchitecture](https://github.com/gradle/gradle/blob/master/subprojects/platform-native/src/main/java/org/gradle/nativeplatform/MachineArchitecture.java) classes. While these seem to be specifically created for configuring native plugins, it is also used in [Fixing metadata rules](https://docs.gradle.org/current/userguide/component_metadata_rules.html#adding_variants_for_native_jars) documentation to add and resolve native variants for os/arch-specific publications. Since this is not really related to building native code, I would consider this a core issue instead of a native-specific issue.

Originally the `TargetMachineFactory` class contained a `host()` method, that provided access to the current os/arch, but that functionality was [made internal](https://github.com/gradle/gradle-native/issues/928) to make the API to specify native build variants more obvious.
While it is still possible to get host information by casting the `TargetMachineFactory` class to its default implementation, it would be convenient to be able to get that as an independent public service for resolving host information. This would enable writing os/arch independent scripts to resolve artifacts with host attributes without relying on an internal API.

With this addition, the metadata rule example (_Example 14. Applying and utilising rule for LWGJ metadata_) can be improved like this:
```kotlin
val host = gradle.serviceOf<HostMachine>()
configurations["runtimeClasspath"].attributes {
    attribute(OperatingSystemFamily.OPERATING_SYSTEM_ATTRIBUTE, host.operatingSystemFamily)
    attribute(MachineArchitecture.ARCHITECTURE_ATTRIBUTE, host.architecture)
dependencies {
    components {
        withModule<LwjglRule>("org.lwjgl:lwjgl")
    }
    implementation("org.lwjgl:lwjgl:3.2.3")
}
```

**Comment by ljacomet** [comment] 2021-04-01 10:17
Can you explain why using the information provided by the JVM running Gradle through system properties is not enough?

**Comment by urdak** [comment] 2021-04-01 16:51
`System.getProperty("os.arch")` can return different values for the same architecture. For example, x86_64 could be "x86-64", "x86_64", "amd64", "x64". If some artifact is published with attribute `"org.gradle.native.architecture": "x86-64"`, it won't be resolvable on a system where `os.arch` returns "amd64", even though it is the same architecture.
This API fixes this issue by converting all known `os.arch` values to a "canonical name" that will be used as the attribute value.
Known architectures are defined [here](https://github.com/gradle/gradle/blob/master/subprojects/platform-native/src/main/java/org/gradle/nativeplatform/platform/internal/Architectures.java).

**Comment by ljacomet** [comment] 2021-04-13 13:52
Thanks for detailing further why this is needed.

**Comment by ljacomet** [comment] 2021-11-29 10:01
Closing as duplicate of #7735

**Closed by ljacomet** 2021-11-29 10:01 UTC
Labels: in:native-platform, a:feature, closed:duplicate, in:writing-tasks
