### ISSUE TITLE
Gradle 4.1+ executes tasks in the wrong order

### ISSUE THREAD

**Issue by idlsoft** [gradle/gradle#3300] opened 2017-10-27 16:16 UTC
I have a composite build, and I want some tasks to propagate to subbuilds: `clean, test, build`.
I also have a task that creates a binary distribution, which includes jars and other artifacts (scripts, etc).

Everything worked fine in Gradle 4.0, but now if I run `clean distro`, `clean` runs last.

### Expected Behavior
`clean` runs first, then `distro`

### Current Behavior
`clean` runs after `distro`

### Steps to Reproduce (for bugs)
I managed to create a little project to reproduce the problem here [gradle-4.1-task-order-bug](https://github.com/idlsoft/gradle-4.1-task-order-bug).

CD to `main` and run:
`./gradlew clean distro`
You'll see the distro under `build/distributions/main-distro`

Than modify `gradle/wrapper/gradle.properties` to use a 4.1+ version.
Run it again.
The `build` directory will be removed.

**Comment by ghale** [comment] 2017-10-27 17:55
You're running into the same problem as reported here: https://github.com/gradle/gradle/issues/2488

**Comment by idlsoft** [comment] 2017-10-27 18:10
Seems very similar, yes.
I do have other side-effects in my original build, like additional artifacts not being built before the `distro` task, essentially ignoring the `dependsOn` (again, works in 4.0), but I thought it's all related.

**Comment by ghale** [comment] 2017-10-29 12:58
If modeled task relationships (such as `dependsOn` or `mustRunAfter`) are not being honored, then that's likely a different (and more serious) problem.  Does your example project above exhibit this behavior in some way?

**Comment by bartoszwilk** [comment] 2017-10-29 22:50
I have a similar problem.
I need to run my build with tasks in specified order: clean, assemble, crashlyticsUpload.
This configuration always results in build failure due to missing apk file.
In fact, crashlyticsUpload is always performed before assemble and after clean task.

**Comment by idlsoft** [comment] 2017-10-29 22:57
My original build does indeed seem to mess up dependencies. If I call only distro it calls lib:clean right before it. However I was unable to reproduce it in my example.

**Comment by bartoszwilk** [comment] 2017-11-08 09:13
Any updates on this?

**Comment by oehme** [comment] 2017-11-14 15:01
@bartoszwilk does `crahslyticsUpload` have proper dependencies in place? If that task needs the APK, then it should depend on the task that creates it.

**Comment by idlsoft** [comment] 2018-01-11 00:02
FWIW `git bisect` points to https://github.com/gradle/gradle/commit/ea6c002b071495058d9a1df93b859709d35016c7

**Comment by solikhver** [comment] 2018-04-24 10:43
I have the same problem. I run command: `gradlew clean  assembleRelease crashlyticsUploadDistributionRelease` and see next order:

1.  clean
2. crashlyticsUploadDistributionRelease
3. assembleRelease

**Comment by idlsoft** [comment] 2018-04-24 16:53
Just tried it, adding `--max-workers=1` doesn't do the trick here.

**Comment by kapfab** [comment] 2018-06-28 15:51
OK, thanks.
With Gradle 2.x and 3.x, were the tasks run in the order they were stated on the command line?

**Comment by idlsoft** [comment] 2018-06-28 15:57
This particular example used to work until 4.0.2, and git bisect points to ea6c002

**Comment by idlsoft** [comment] 2018-07-02 13:50
You probably don't want to declare dependencies in `clean` though.
Perhaps have a `mustRunAfter`, but it's pretty annoying to have to put that everywhere.

**Comment by oehme** [comment] 2018-07-02 15:04
@idlsoft I wasn't talking about your issue, which is the reason this ticket exists. I was explaining to the others that they are not facing this issue, but a faulty plugin.

**Comment by idlsoft** [comment] 2018-07-02 15:12
@oehme you're right, the two are unrelated.

**Comment by thevolcanomanishere** [comment] 2018-07-12 13:38
This format used to work great for me on Gradle 3

```
task cleanAssembleBuildPublish(type: GradleBuild) {
    tasks = ['clean', 'assembleRelease', 'publish', 'anotherTask', 'lastTask']
}
```

Gradle 4+ ruined this simplicity. Seems crazy that ordering tasks isn't just a case of lining them up like above. I guess a quick work around is to just write a bash script that calls each gradle task in sequence.

**Comment by oehme** [comment] 2018-07-12 13:41
@thevolcanomanishere Can you please provide a reproducible example project? This should work just fine, there is only a corner case with composite builds.

**Comment by big-guy** [comment] 2019-04-16 23:03
Closing this as a dupe of https://github.com/gradle/gradle/issues/2488

**Closed by big-guy** 2019-04-16 23:03 UTC
Labels: a:bug, from:contributor, in:composite-builds
