### ISSUE TITLE
MapProperty loses state, when a value with not-present-provider gets added

### ISSUE THREAD

**Issue by Phlegethon90** [gradle/gradle#25357] opened 2023-06-12 07:06 UTC
### Expected Behavior

```kotlin
val m: MapProperty<String, Any> = objects.mapProperty()
println(m.isPresent)
m.put("foo", providers.provider { "bar" })
println(m.isPresent)
m.put("ci", providers.provider { null })
println(m.isPresent)
```

should return:

```kotlin
true
true
true
```

### Current Behavior

```kotlin
true
true
false
```

### Steps to Reproduce

See above code.

### Gradle version

8.1.1

**Comment by ljacomet** [comment] 2023-06-12 08:54
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #20266

Please add your use case and 👍 to that issue.

**Closed by ljacomet** 2023-06-12 08:54 UTC
Labels: a:bug, to-triage

**Comment by Phlegethon90** [comment] 2023-06-12 08:56
Oh, sorry! I will add my use case there. Thank you!
