### ISSUE TITLE
Possibility to query system properties and environment variables without influencing configuration cache

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#19942] opened 2022-02-16 22:21 UTC
Plugins like https://plugins.gradle.org/plugin/net.saliman.properties get all environment variables and all system properties to search for a certain pattern in the name. Only those matching the pattern are actually used and are actual inputs for the configuration potentially.

Now with the auto-detection of read system properties and environment variables - which is great per-se - each and every system property and environment variable is considered an input for the configuration cache.

It would be nice if there was a way for such plugins to circumvent that, for example specifying that the usage should not be auto-detected, or special methods to get the values based on some naming pattern, or something similar.

**Comment by eskatos** [comment] 2022-02-17 08:29
This looks like a duplicate of https://github.com/gradle/gradle/issues/13819, doesn't it?

**Comment by Vampire** [comment] 2022-02-17 08:56
Regarding the system properties indeed, if that one does not get closed because one of the requested alternatives is to safely get all of them and that works now.

But it doesn't mention environment variables. How do we progress? Adding environment variables to that request? Modifying this to just request for environment variables? ...?

**Comment by eskatos** [comment] 2022-02-17 09:22
I changed the title of https://github.com/gradle/gradle/issues/13819 to cover both system properties and environment variables given the discussion there is already covering both.

Querying _all_ sys props or env vars will always be problematic as it will detect all of them as inputs and lead to lots of cache misses if not not cache hits at all.

**Closed** 2022-02-17 13:39 UTC
Labels: closed:duplicate
