### ISSUE TITLE
"Failed to map supported failure" message when using JUnit `Assertions.fail`

### ISSUE THREAD

**Issue by DavidGregory084** [gradle/gradle#27871] opened 2024-01-30 12:57 UTC
### Current Behavior

When using `Assertions.fail` in my code, I receive the following message in the Gradle test output:

> Failed to map supported failure 'org.opentest4j.AssertionFailedError: - sample failure' with mapper 'org.gradle.api.internal.tasks.testing.failure.mappers.OpenTestAssertionFailedMapper@2d9df336': Cannot invoke "Object.getClass()" because "obj" is null

The `OpenTestAssertionFailedMapper` assumes that any `AssertionFailedError` must have `actual` and `expected` values, so it throws an NPE when [calling getClass](https://github.com/gradle/gradle/blob/master/platforms/jvm/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/failure/mappers/OpenTestAssertionFailedMapper.java#L50) on the expected value.

### Expected Behavior

No mapping error message should be printed to the output.

### Context (optional)

`AssertionFailedError` can have no `expected` or `actual` value when using several of the JUnit assertions e.g. `assertDoesNotThrow`, `assertTimeout`.

### Steps to Reproduce

Use `Assertions.fail` or one of the other affected assertions in a JUnit 5 test.

### Gradle version

8.5

**Comment by cobexer** [comment] 2024-01-30 14:00
Thank you for providing a valid report.

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by donat** [comment] 2024-01-30 14:25
@DavidGregory084 I've created an integration test to check your report but it seems I cannot reproduce the problem. Do you thing this test class would be enough of a reproducer? 

```
file('src/test/java/org/gradle/JUnitTest.java') << """
            package org.gradle;

            import org.junit.jupiter.api.Test;

            public class JUnitTest {
                @Test
                void test() {
                    org.junit.jupiter.api.Assertions.fail("it did fail");
                }
            }
        """
```

**Comment by DavidGregory084** [comment] 2024-01-30 14:29
Hmm interesting @donat - if it makes any difference I did this as part of a `DynamicTest`? Let me see if I can provide a reproducer project

**Comment by donat** [comment] 2024-01-30 15:30
Using DynamicTest does not seem to have an effect. This particular test works well on my end:
```
            package org.gradle;
            import java.util.*;
            import org.junit.jupiter.api.*;

            public class JUnitTest {

                @TestFactory
                Collection<DynamicTest> test() {
                    return Arrays.asList(
                        DynamicTest.dynamicTest("Add test",
                            () -> org.junit.jupiter.api.Assertions.fail("it did fail")));
                }
            }
```

**Comment by ljacomet** [comment] 2024-01-30 17:37
The missing condition is to run that test from the IDE, you then get the following error in the output:
`Failed to map supported failure 'org.opentest4j.AssertionFailedError: someLibraryMethod should return 'true'' with mapper 'org.gradle.api.internal.tasks.testing.failure.mappers.OpenTestAssertionFailedMapper@53f6fd09': null`

However this is a bug that has been introduced with this feature and it reproduces with Gradle 8.3 and 8.4. Moving this to a bug instead of a regression.

**Comment by DavidGregory084** [comment] 2024-01-30 17:40
> The missing condition is to run that test from the IDE, you then get the following error in the output: `Failed to map supported failure 'org.opentest4j.AssertionFailedError: someLibraryMethod should return 'true'' with mapper 'org.gradle.api.internal.tasks.testing.failure.mappers.OpenTestAssertionFailedMapper@53f6fd09': null`

Ohh that's weird - I was seeing this on the command line, could it be because that Gradle daemon was started by IntelliJ?

**Comment by prdoyle** [comment] 2024-02-08 13:26
I still get this error on the command line after `./gradlew --stop`. I think this means it's not due to a daemon started by my IDE.

**Comment by hegyibalint** [comment] 2024-02-09 10:19
Finally had some time to look at this: looking at my code, it's pretty clear that I've (mistakenly) made the assumption of both values to be non-null. I expect that we can still do this in 8.8.

**Comment by hegyibalint** [comment] 2024-02-09 10:20
Also I think it's unrelated to the IDE case, assertion mapping is a feature of test execution, so this should fail under any circumstances.

**Comment by hegyibalint** [comment] 2024-02-09 10:26
Going to expand on the tests, but already this is enough to break the code:

https://github.com/gradle/gradle/pull/28016/files#diff-ad3c155ae9588012093c9f031ee2ee55ec3e31b23c580c8a988bb2906c4a1f97R31

**Comment by hegyibalint** [comment] 2024-02-09 15:04
@DavidGregory084 feel free to take a look at the PR.
If you don't want to take a look at the whole thing, you can have a peek at the [new test's expectations](https://github.com/gradle/gradle/pull/28016/files#diff-ad3c155ae9588012093c9f031ee2ee55ec3e31b23c580c8a988bb2906c4a1f97R56-R74) to see if you agree. Thanks!

**Closed** 2024-02-14 09:16 UTC
Labels: a:bug, in:testing-junit5, affects-version:8.5
