### ISSUE TITLE
Gradle 7.3 take 30 seconds trying to unpack JDK 17 during configuration every time it runs

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#18413] opened 2021-09-25 05:00 UTC
### Current Behavior

With this config: 
```kotlin
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
        vendor.set(JvmVendorSpec.ADOPTOPENJDK)
    }
}
```

Gradle takes 30 seconds to do try to provision JDK 17 EVERY TIME. It eventually succeeds, but the next build (with no changes) will take another 30 seconds during config, in the same spot.  

It is stuck on this for 30 seconds: 
```
> Provisioning toolchain adoptopenjdk-17-x64-mac.tar.gz > Unpacking toolchain archive
```

### Context

Adds 30 seconds to every configuration

### Your Environment
Kotlin project using Kotlin DSL

Gradle 7.3-20210924141637+0000
Adoptium JDK 17_35 or Adoptium JDK 11

(also, seems to happen on Gradle 7.2 as well)

**Comment by ljacomet** [comment] 2021-09-27 08:50
Closing as duplicate of #18027

**Closed by ljacomet** 2021-09-27 08:50 UTC
Labels: a:bug, in:toolchains, to-triage
