### ISSUE TITLE
Cannot accept connection from remote address

### ISSUE THREAD

**Issue by dummys** [gradle/gradle#12731] opened 2020-04-06 17:24 UTC
Hi,

I'm on arch linux, but test on xenial, same problem :

```
------------------------------------------------------------
Gradle 6.3
------------------------------------------------------------

Build time:   2020-03-24 22:12:49 UTC
Revision:     <unknown>

Kotlin:       1.3.70
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          13.0.2 (Oracle Corporation 13.0.2+8)
OS:           Linux 5.5.13-arch2-1 amd64
```
when doing simple `gradle init` I got an infinite loop crashing my computer, because of missing ram. Gradle launch ton of useless daemon.
in the log I found this: 2020-04-06T19:16:04.949+0200 [ERROR] [org.gradle.internal.remote.internal.inet.TcpIncomingConnector] Cannot accept connection from remote address /192.168.2.131.
Just for test `gradle-5.0` is working I just tested the release version. Starting from 6.0 it's broken.

Which is the ip address of the computer.  I tried to use the gradle from release, same problem, tried to delete everything in `~/.gradle` same problem.

Here is the full `daemon.log`:
```
2020-04-06T19:16:04.737+0200 [DEBUG] [org.gradle.launcher.daemon.bootstrap.DaemonMain] Assuming the daemon was started with following jvm opts: [--add-opens, java.base/java.util=ALL-UNNAMED, --add-opens, java.base/java.lang=ALL-UNNAMED, --add-opens, java.base/java.lang.invoke=ALL-UNNAMED, --add-opens, java.prefs/java.util.prefs=ALL-UNNAMED, -XX:MaxMetaspaceSize=256m, -XX:+HeapDumpOnOutOfMemoryError, -Xms256m, -Xmx512m, -Dfile.encoding=UTF-8, -Duser.country=US, -Duser.language=en, -Duser.variant]
2020-04-06T19:16:04.873+0200 [INFO] [org.gradle.launcher.daemon.server.Daemon] start() called on daemon - DefaultDaemonContext[uid=d65e79fe-1041-43d2-a432-5f2a3aecf79e,javaHome=/usr/lib/jvm/java-13-openjdk,daemonRegistryDir=/home/dummys/.gradle/daemon,pid=21982,idleTimeout=120000,priority=NORMAL,daemonOpts=--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]
2020-04-06T19:16:04.891+0200 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding IP addresses for network interface vmnet8
2020-04-06T19:16:04.891+0200 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Is this a loopback interface? false
2020-04-06T19:16:04.892+0200 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding remote address /fe80:0:0:0:250:56ff:fec0:8%vmnet8
2020-04-06T19:16:04.892+0200 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding remote address /172.16.224.1
2020-04-06T19:16:04.892+0200 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding IP addresses for network interface vmnet1
2020-04-06T19:16:04.894+0200 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Is this a loopback interface? false
2020-04-06T19:16:04.894+0200 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding remote address /fe80:0:0:0:250:56ff:fec0:1%vmnet1
2020-04-06T19:16:04.895+0200 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding remote address /172.16.81.1
2020-04-06T19:16:04.895+0200 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding IP addresses for network interface usb0
2020-04-06T19:16:04.895+0200 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Is this a loopback interface? false
2020-04-06T19:16:04.895+0200 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding remote address /fe80:0:0:0:d238:80a2:6b42:252c%usb0
2020-04-06T19:16:04.896+0200 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding remote address /192.168.2.131
2020-04-06T19:16:04.896+0200 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding IP addresses for network interface lo
2020-04-06T19:16:04.896+0200 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Is this a loopback interface? true
2020-04-06T19:16:04.896+0200 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding loopback address /0:0:0:0:0:0:0:1%lo
2020-04-06T19:16:04.896+0200 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding loopback address /127.0.0.1
2020-04-06T19:16:04.899+0200 [DEBUG] [org.gradle.internal.remote.internal.inet.TcpIncomingConnector] Listening on [ddcf3323-9f59-4859-a8ac-a2bc9e8f3ac2 port:38423, addresses:[localhost/127.0.0.1]].
2020-04-06T19:16:04.906+0200 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] Daemon starting at: Mon Apr 06 19:16:04 CEST 2020, with address: [ddcf3323-9f59-4859-a8ac-a2bc9e8f3ac2 port:38423, addresses:[localhost/127.0.0.1]]
2020-04-06T19:16:04.906+0200 [INFO] [org.gradle.launcher.daemon.server.DaemonRegistryUpdater] Advertising the daemon address to the clients: [ddcf3323-9f59-4859-a8ac-a2bc9e8f3ac2 port:38423, addresses:[localhost/127.0.0.1]]
2020-04-06T19:16:04.907+0200 [DEBUG] [org.gradle.launcher.daemon.server.DaemonRegistryUpdater] Advertised daemon context: DefaultDaemonContext[uid=d65e79fe-1041-43d2-a432-5f2a3aecf79e,javaHome=/usr/lib/jvm/java-13-openjdk,daemonRegistryDir=/home/dummys/.gradle/daemon,pid=21982,idleTimeout=120000,priority=NORMAL,daemonOpts=--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]
2020-04-06T19:16:04.908+0200 [DEBUG] [org.gradle.launcher.daemon.registry.PersistentDaemonRegistry] Storing daemon address: [ddcf3323-9f59-4859-a8ac-a2bc9e8f3ac2 port:38423, addresses:[localhost/127.0.0.1]], context: DefaultDaemonContext[uid=d65e79fe-1041-43d2-a432-5f2a3aecf79e,javaHome=/usr/lib/jvm/java-13-openjdk,daemonRegistryDir=/home/dummys/.gradle/daemon,pid=21982,idleTimeout=120000,priority=NORMAL,daemonOpts=--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]
2020-04-06T19:16:04.916+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on daemon addresses registry.
2020-04-06T19:16:04.918+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2020-04-06T19:16:04.918+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2020-04-06T19:16:04.919+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on daemon addresses registry.
2020-04-06T19:16:04.919+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2020-04-06T19:16:04.923+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2020-04-06T19:16:04.923+0200 [LIFECYCLE] [org.gradle.launcher.daemon.server.Daemon] Daemon server started.
2020-04-06T19:16:04.924+0200 [DEBUG] [org.gradle.launcher.daemon.bootstrap.DaemonStartupCommunication] Completed writing the daemon greeting. Closing streams...
2020-04-06T19:16:04.928+0200 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] stopOnExpiration() called on daemon
2020-04-06T19:16:04.929+0200 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] awaitExpiration() called on daemon
2020-04-06T19:16:04.929+0200 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] daemon is running. Sleeping until state changes.
2020-04-06T19:16:04.949+0200 [ERROR] [org.gradle.internal.remote.internal.inet.TcpIncomingConnector] Cannot accept connection from remote address /192.168.2.131.
2020-04-06T19:16:14.941+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2020-04-06T19:16:14.942+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2020-04-06T19:16:14.945+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2020-04-06T19:16:14.946+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2020-04-06T19:16:14.947+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2020-04-06T19:16:14.948+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2020-04-06T19:16:14.948+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2020-04-06T19:16:14.949+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2020-04-06T19:16:14.950+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2020-04-06T19:16:24.930+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2020-04-06T19:16:24.930+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2020-04-06T19:16:24.931+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2020-04-06T19:16:24.932+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2020-04-06T19:16:24.933+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2020-04-06T19:16:24.933+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2020-04-06T19:16:24.934+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2020-04-06T19:16:24.935+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2020-04-06T19:16:24.935+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2020-04-06T19:16:34.929+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2020-04-06T19:16:34.930+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2020-04-06T19:16:34.931+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2020-04-06T19:16:34.932+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2020-04-06T19:16:34.932+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2020-04-06T19:16:34.933+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2020-04-06T19:16:34.933+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2020-04-06T19:16:34.934+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2020-04-06T19:16:34.934+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
```

**Comment by dummys** [comment] 2020-04-08 14:40
Am I the only one to have this ?

**Comment by etheriau** [comment] 2020-04-18 22:12
No, you are not the only one -- I am also having this issue in any release since 6.0 but have yet to find a workaround.

**Comment by soucekv** [comment] 2020-10-13 12:38
I can see similar output just by running `gradlew compileJava`, when switching from Gradle 6.0.1 to 6.5.1+ (including latest 6.6.1 release). I'm running the build on MacOS with JDK 11. It gets stuck in infinite loop.

```
20-10-13T14:36:08.422+0200 [INFO] [org.gradle.api.internal.tasks.compile.JdkJavaCompiler] Compiling with JDK Java compiler API.
2020-10-13T14:36:13.294+0200 [LIFECYCLE] [org.gradle.cache.internal.DefaultFileLockManager] 
2020-10-13T14:36:13.294+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2020-10-13T14:36:13.295+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2020-10-13T14:36:13.295+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2020-10-13T14:36:13.295+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2020-10-13T14:36:13.295+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2020-10-13T14:36:13.296+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2020-10-13T14:36:23.296+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2020-10-13T14:36:23.296+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2020-10-13T14:36:23.296+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2020-10-13T14:36:23.296+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2020-10-13T14:36:23.297+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2020-10-13T14:36:23.297+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2020-10-13T14:36:10.177+0200 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] 
2020-10-13T14:36:10.177+0200 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :simphony:compileJava
2020-10-13T14:36:25.136+0200 [ERROR] [system.err] Note: Hibernate JPA 2 Static-Metamodel Generator 5.3.10.Final
2020-10-13T14:36:33.287+0200 [LIFECYCLE] [org.gradle.cache.internal.DefaultFileLockManager] 
2020-10-13T14:36:33.287+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2020-10-13T14:36:33.287+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2020-10-13T14:36:33.287+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2020-10-13T14:36:33.287+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2020-10-13T14:36:33.287+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2020-10-13T14:36:33.288+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2020-10-13T14:36:35.122+0200 [DEBUG] [sun.rmi.transport.tcp] RMI Scheduler(0): close connection
2020-10-13T14:36:35.163+0200 [DEBUG] [sun.rmi.transport.tcp] RMI Scheduler(0): close connection
2020-10-13T14:36:35.224+0200 [DEBUG] [sun.rmi.transport.tcp] RMI TCP Connection(1)-127.0.0.1: (port 63463) connection closed
2020-10-13T14:36:35.224+0200 [DEBUG] [sun.rmi.transport.tcp] RMI TCP Connection(1)-127.0.0.1: close connection
2020-10-13T14:36:43.288+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2020-10-13T14:36:43.288+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2020-10-13T14:36:43.288+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2020-10-13T14:36:43.289+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2020-10-13T14:36:43.289+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2020-10-13T14:36:43.289+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2020-10-13T14:36:53.290+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2020-10-13T14:36:53.290+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2020-10-13T14:36:53.291+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2020-10-13T14:36:53.291+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2020-10-13T14:36:53.291+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2020-10-13T14:36:53.291+0200 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
```

**Comment by BrokoGily** [comment] 2020-11-02 13:40
I had same issue, but real problem was with my antivirus.

**Comment by adultmalehuman** [comment] 2020-12-13 18:57
Same problem here when running on Windows 10. My build starts normally, then an error message in the console output about 'Cannot accept connection from remote address /127.0.0.1', then the 'test' task just hangs and eventually times out and fails the build process.

```
> Task :app-springboot:startScripts UP-TO-DATE
> Task :app-springboot:distTar UP-TO-DATE
> Task :app-springboot:distZip UP-TO-DATE
> Task :app-springboot:assemble UP-TO-DATE
> Task :app-springboot:compileTestJava UP-TO-DATE
> Task :app-springboot:processTestResources NO-SOURCE
> Task :app-springboot:testClasses UP-TO-DATE
Cannot accept connection from remote address /127.0.0.1.
> Task :app-springboot:test
```

I tried downgrading as far back as Gradle 6.3, but they all seem to have the same problem. Current version as I write this is Gradle 6.7.1. I'm using Java 8 JDK.

**Comment by tudyoctav** [comment] 2020-12-13 22:50
I have the same problem on Windows 10, running Gradle 6.7 and Java 11. 
All the other tasks run successfully, but 'test' gets stuck and keeps creating instances until all of them time out and the build fails:
```
> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :compileTestJava UP-TO-DATE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
Cannot accept connection from remote address /127.0.0.1.
> Task :test
Cannot accept connection from remote address /127.0.0.1.
> Task :test
Unable to connect to the child process 'Gradle Test Executor 5'.
It is likely that the child process have crashed - please find the stack trace in the build log.
This exception might occur when the build machine is extremely loaded.
The connection attempt hit a timeout after 120.0 seconds (last known process state: STARTED, running: true).
org.gradle.process.internal.ExecException: Unable to connect to the child process 'Gradle Test Executor 5'.
It is likely that the child process have crashed - please find the stack trace in the build log.
This exception might occur when the build machine is extremely loaded.
The connection attempt hit a timeout after 120.0 seconds (last known process state: STARTED, running: true).
	at org.gradle.process.internal.worker.DefaultWorkerProcess.doStart(DefaultWorkerProcess.java:192)
	at org.gradle.process.internal.worker.DefaultWorkerProcess.start(DefaultWorkerProcess.java:168)
	at org.gradle.process.internal.worker.DefaultWorkerProcessBuilder$MemoryRequestingWorkerProcess.start(DefaultWorkerProcessBuilder.java:251)
	at org.gradle.api.internal.tasks.testing.worker.ForkingTestClassProcessor.forkProcess(ForkingTestClassProcessor.java:118)
	at org.gradle.api.internal.tasks.testing.worker.ForkingTestClassProcessor.processTestClass(ForkingTestClassProcessor.java:91)
	at org.gradle.api.internal.tasks.testing.processors.RestartEveryNTestClassProcessor.processTestClass(RestartEveryNTestClassProcessor.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:30)
	at org.gradle.internal.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:87)
	at org.gradle.internal.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:36)
	at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:71)
	at org.gradle.internal.concurrent.InterruptibleRunnable.run(InterruptibleRunnable.java:42)
	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:832)
Cannot accept connection from remote address /127.0.0.1.
> Task :test FAILED 
...
```
This goes on for quite some time:
```
Cannot accept connection from remote address /127.0.0.1.
> Task :test FAILED
Unable to connect to the child process 'Gradle Test Executor 6'.
...
Execution failed for task ':test'.
> Unable to connect to the child process 'Gradle Test Executor 4'.
...
BUILD FAILED in 6m 3s
```

**Comment by qwertzguy** [comment] 2021-01-08 03:52
As a workaround, it is possible to add the IP that is being considered "remote" (because of masquerading) to the environment variable `OPENSHIFT_IP` and gradle daemons will then allow it (https://github.com/gradle/gradle/blob/master/subprojects/messaging/src/main/java/org/gradle/internal/remote/internal/inet/InetAddressFactory.java#L136).

To find the IP being blocked, you'll need to look at the output log of one of the daemons in `~/.gradle/daemon/X.X.X/daemon-XXXXXXX.out.log`

**Comment by joshuafc** [comment] 2021-09-22 02:53
I use Ubuntu, and my dev environment which use vpn as a soft router has enabled ip_forward use follow commands:

```
iptables -t nat -A POSTROUTING -j MASQUERADE
echo 1 > /proc/sys/net/ipv4/ip_forward
```

received the error msg: `Cannot accept connection from remote address /192.168.0.xxx`

@qwertzguy `OPENSHIFT_IP` solved my probles.

**Comment by big-guy** [comment] 2021-09-27 15:33
dupe of #14528

**Closed by big-guy** 2021-09-27 15:33 UTC
Labels: a:bug, to-triage
