### ISSUE TITLE
8.1 RC1: Optional task input being incorrectly coerced to a ListProperty

### ISSUE THREAD

**Issue by ben-manes** [gradle/gradle#24413] opened 2023-03-21 06:26 UTC
The property is somehow being forced into a ListProperty, which breaks the script when it tries to perform a String.split operation.

```gradle
class Simulate extends DefaultTask {
  @Input @Optional @Option(option = 'jvmArgs', description = 'The jvm arguments')
  String jvmArguments
```

```console
$ gradle simulate --maximumSize=500 --no-configuration-cache
...
Build file '/Users/ben/projects/caffeine/simulator/build.gradle' line: 129

* What went wrong:
Execution failed for task ':simulator:simulate'.
> No signature of method: org.gradle.api.internal.provider.DefaultListProperty.split() is applicable for argument types: (String) values: [,]
  Possible solutions: split(groovy.lang.Closure), wait(), wait(long), set(java.lang.Iterable), set(org.gradle.api.provider.Provider), print(java.io.PrintWriter)
```

**Comment by ov7a** [comment] 2023-03-21 09:59
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) can really help us track down and fix your problem. We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

We request you to provide a reproducer because we need to be sure we are looking at the exact problem you are facing.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).

This issue will be closed after 7 days unless you can provide more information.

***

We're investigating this, but if you provide us a complete reproducer, it would be a lot quicker for us.

**Comment by ben-manes** [comment] 2023-03-21 16:12
This is a really quirky one, so for the moment please try this [commit](https://github.com/ben-manes/caffeine/commit/25d82e84e4c5275581b9d03e7e8f9801b46fab95). Then run `simulate --maximumSize=500`. I'll look into a minimal reproducer.

**Comment by ben-manes** [comment] 2023-03-21 16:55
This appears to be a name clash where the script's property is shadowed by the `javaexec` call. If I rename the option then it resolves to a string. That is fine, but it would be nice if shadowing could be more explicit such as a warning, as this changes the behavior by leaking this.

```gradle
class Simulate extends DefaultTask {
  @Input @Optional @Option(option = 'jvmArgs', description = 'The jvm arguments')
  String jvmArguments

  @TaskAction def run() {
    println "Task: " + jvmArguments.getClass()
    project.javaexec {
      mainClass = 'HelloWorld'
      println "JavaExec: " + jvmArguments.getClass()
    }
  }
}
tasks.register('simulate', Simulate) {
  outputs.upToDateWhen { false }
}
```

```console
> Task :simulate FAILED
Task: class org.codehaus.groovy.runtime.NullObject
JavaExec: class org.gradle.api.internal.provider.DefaultListProperty
```

**Comment by abstratt** [comment] 2023-03-21 20:55
Thanks, closing.

**Closed by abstratt** 2023-03-21 20:55 UTC
Labels: a:regression, to-triage, pending:reproducer

**Comment by abstratt** [comment] 2023-03-22 14:26
Reopening as we decided to document this.
