### ISSUE TITLE
`kotlin-dsl` overrides the Kotlin apiVersion specified in build script

### ISSUE THREAD

**Issue by hsz** [gradle/gradle#18928] opened 2021-11-10 12:06 UTC
When migrating the Gradle IntelliJ Plugin from the `java-gradle-plugin` to `kotlin-dsl`, I faced an issue specifying the target Kotlin API version.

In my code, I use method references, like:
```
val decompressor = when {
    name.endsWith(".zip") || name.endsWith(".sit") -> archiveOperations::zipTree
    name.endsWith(".tar.gz") -> archiveOperations::tarTree
    else -> throw IllegalArgumentException("Unknown type archive type: $name")
}

fileSystemOperations.copy {
    from(decompressor.invoke(archiveFile))
    into(targetDirectory)
}
```

Because I’m also targeting Gradle `6.6.1`, I set the Kotlin’s `apiVersion = "1.3"`:
```
withType<KotlinCompile> {
    kotlinOptions {
        jvmTarget = "11"
        apiVersion = "1.3"
    }
}
```

That was working with `java-gradle-plugin` but after the switch, it’s ignored and my plugin fails in `6.6.1` (which has Kotlin `1.3` bundled) with:
```
Caused by: java.lang.NoSuchMethodError: 'void kotlin.jvm.internal.FunctionReferenceImpl.<init>(int, java.lang.Object, java.lang.Class, java.lang.String, java.lang.String, int)'
```

### Expected Behavior
Allow for specifying Kotlin API version when using `kotlin-dsl`.

### Current Behavior
`kotlin-dsl` ignores and overrides the `apiVersion` to the one that is currently bundled in the used Gradle.

### Context
When trying to provide plugin for older Gradle versions, I need to compile the code targeting the Kotlin API in the `1.3` version.

### Steps to Reproduce 
In Project using Gradle `7.3`, use method references (`::foo`), build, and use in a project that uses Gradle `6.6.1`.

**Comment by vlsi** [comment] 2021-11-10 12:46
It looks like a duplicate of https://github.com/gradle/gradle/issues/16781 and https://github.com/gradle/gradle/issues/16345 🤷‍♂️

**Comment by octylFractal** [comment] 2021-11-10 16:39
Duplicate of #16781

**Closed by octylFractal** 2021-11-10 16:39 UTC
Labels: a:bug, in:kotlin-dsl, to-triage
