### ISSUE TITLE
Conflict between Maven local repository and Gradle

### ISSUE THREAD

**Issue by valepakh** [gradle/gradle#30601] opened 2024-09-18 10:04 UTC
### Current Behavior

When a dependency is declared for a classified artifact in the build.gradle, let's say `com.fasterxml.jackson.core:jackson-databind:2.17.2:sources` and the non-classified artifact is present in the Maven local repository, Gradle can't resolve the classified artifact with an error: 
```
> Could not resolve all files for configuration ':download'.
   > Could not find jackson-databind-2.17.2-sources.jar (com.fasterxml.jackson.core:jackson-databind:2.17.2).
     Searched in the following locations:
         file:/C:/Users/Admin/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.17.2/jackson-databind-2.17.2-sources.jar
```

This can be reproduced by manually downloading non-classifed artifact using `mvn dependency:get -Dartifact=com.fasterxml.jackson.core:jackson-databind:2.17.2` and then running any gradle task which depends on the classified artifact:

```
configurations { download }

dependencies { download 'com.fasterxml.jackson.core:jackson-databind:2.17.2:sources' }

repositories {
  mavenLocal()
  mavenCentral()
}

task download(type: Copy) {
  from configurations.download
  into 'download'
}
```

If I delete the artifact from the maven local repository, the build succeeds.

### Expected Behavior

Gradle should properly resolve the classified artifact even if it's not present in the Maven local repository.

### Context (optional)

Initially I encountered this error when downloading sources for libraries from the IDEA. I had a project with maven build and a project with gradle build both depending on the same libraries. So the local maven repository had the library downloaded and when I tried to download sources for this library from the gradle project I've got an error. When .m2 was cleaned, the download succeeded.
Then the same issue started to appear on the TeamCity agents. Again, several different projects were built on the same agents and .m2 was populated with the non-classified artifact from the maven build but gradle build with dependency on the classified artifact failed.

### Self-contained Reproducer Project

[download.zip](https://github.com/user-attachments/files/17041928/download.zip)
In addition to the gradle project attached, in order to reproduce the issue one has to pollute the local maven repository.
First make sure there's no classified artifact in the local repo: `mvn dependency:purge-local-repository -DmanualInclude=com.fasterxml.jackson.core:jackson-databind:2.17.2`
Then get only the non-classified artifact: `mvn dependency:get -Dartifact=com.fasterxml.jackson.core:jackson-databind:2.17.2`.
After that run the attached project `./gradlew download` and observe an error.
After purging the local repository again: `mvn dependency:purge-local-repository -DmanualInclude=com.fasterxml.jackson.core:jackson-databind:2.17.2`
Subsequent `./gradlew download` task completes successfully.

It seems that the Maven dependency plugin works properly only in the sufficiently recent version so make sure you have the latest version of the Maven.

### Gradle version

8.10.1

### Your Environment (optional)

I experienced it first on Windows but similar problems started to appear on our Linux build agents.

**Comment by ov7a** [comment] 2024-09-19 12:42
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***
This is the expected behavior, and it's documented [here](https://docs.gradle.org/current/userguide/declaring_repositories_adv.html#sec:case-for-maven-local).

The use of mavenLocal is discouraged because of that; please consider using maven with a dedicated directory or a local HTTP instance instead.

**Closed by ov7a** 2024-09-19 12:42 UTC
Labels: a:bug, to-triage
