### ISSUE TITLE
[3.2.1]"null value in entry: destinationDir=null" when building apache/groovy under Windows7

### ISSUE THREAD

**Issue by danielsun1106** [gradle/gradle#968] opened 2016-12-05 11:43 UTC
### Expected Behavior
`gradlew clean test --stacktrace` succeeds to execute under all OS

### Current Behavior
`gradlew clean test --stacktrace` fails under `Windows 7`(but succeeds under Linux, e.g. travis-ci)

### Context
I did not find any workaround for the issue.

### Steps to Reproduce (for bugs)
1) git clone the parrot branch of apache/groovy
2) execute `gradlew clean test --stacktrace`
3) fails and get the error message: `null value in entry: destinationDir=null`

### Your Environment
Windows 7
Java 1.8.0_102
Gradle 3.2.1

**Comment by lacasseio** [comment] 2016-12-05 13:34
This issue seems to be the same as #933. Could you confirm?

**Comment by danielsun1106** [comment] 2016-12-05 13:43
OK. Do you mean that I can use the following workaround to bypass the issue?

https://github.com/apache/groovy/commit/78918eb1d91bcfaeb8d02258d26e7ac53ceb4cff

**Comment by lacasseio** [comment] 2016-12-05 14:01
Try it again with that fix and see if you get the same error. If you do then it is most likely the same issue and will close this one as a duplicate. Also, if it is the same error, you will need to delete the `.gradle` folder containing the local cache. The corruption left the cache in a bad state.

**Comment by danielsun1106** [comment] 2016-12-05 15:10
I deleted `.gradle` folder, patched the fix( apache/groovy@78918eb ), but the error `null value in entry: destinationDir=null` still occurred...

```
Download https://jcenter.bintray.com/org/codehaus/groovy/groovy-all/2.4.4/groovy
-all-2.4.4.pom
Download https://jcenter.bintray.com/org/codehaus/groovy/groovy-all/2.4.4/groovy
-all-2.4.4.jar
[buildinfo] Properties file path was not found! (Relevant only for builds runnin
g on a CI Server)
:clean UP-TO-DATE
:groovy-ant:clean UP-TO-DATE
:groovy-bsf:clean UP-TO-DATE
:groovy-console:clean UP-TO-DATE
:groovy-docgenerator:clean UP-TO-DATE
:groovy-groovydoc:clean UP-TO-DATE
:groovy-groovysh:clean UP-TO-DATE
:groovy-jmx:clean UP-TO-DATE
:groovy-json:clean UP-TO-DATE
:groovy-jsr223:clean UP-TO-DATE
:groovy-macro:clean UP-TO-DATE
:groovy-nio:clean UP-TO-DATE
:groovy-servlet:clean UP-TO-DATE
:groovy-sql:clean UP-TO-DATE
:groovy-swing:clean UP-TO-DATE
:groovy-templates:clean UP-TO-DATE
:groovy-test:clean UP-TO-DATE
:groovy-testng:clean UP-TO-DATE
:groovy-xml:clean UP-TO-DATE
:performance:clean UP-TO-DATE
:copyResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
null value in entry: destinationDir=null

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
java.lang.NullPointerException: null value in entry: destinationDir=null
        at com.google.common.collect.CollectPreconditions.checkEntryNotNull(Coll
ectPreconditions.java:33)
        at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:135)

        at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:
206)
        at com.google.common.collect.ImmutableSortedMap$Builder.put(ImmutableSor
tedMap.java:371)
        at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryR
epository$LazyTaskExecution.getOutputFilesSnapshot(CacheBackedTaskHistoryReposit
ory.java:299)
        at org.gradle.api.internal.changedetection.rules.OutputFilesTaskStateCha
nges.getPrevious(OutputFilesTaskStateChanges.java:36)
        at org.gradle.api.internal.changedetection.rules.AbstractNamedFileSnapsh
otTaskStateChanges.iterator(AbstractNamedFileSnapshotTaskStateChanges.java:96)
        at org.gradle.api.internal.changedetection.rules.OutputFilesTaskStateCha
nges.iterator(OutputFilesTaskStateChanges.java:29)
        at org.gradle.api.internal.changedetection.rules.CachingTaskStateChanges
.reset(CachingTaskStateChanges.java:79)
        at org.gradle.api.internal.changedetection.rules.CachingTaskStateChanges
.iterator(CachingTaskStateChanges.java:44)
        at org.gradle.api.internal.changedetection.rules.SummaryTaskStateChanges
.firstDirtyIterator(SummaryTaskStateChanges.java:63)
        at org.gradle.api.internal.changedetection.rules.SummaryTaskStateChanges
.access$000(SummaryTaskStateChanges.java:25)
        at org.gradle.api.internal.changedetection.rules.SummaryTaskStateChanges
$1.computeNext(SummaryTaskStateChanges.java:49)
        at org.gradle.api.internal.changedetection.rules.SummaryTaskStateChanges
$1.computeNext(SummaryTaskStateChanges.java:42)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractI
terator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.j
ava:138)
        at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactSt
ateRepository$TaskArtifactStateImpl.collectChangedMessages(DefaultTaskArtifactSt
ateRepository.java:88)
        at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactSt
ateRepository$TaskArtifactStateImpl.isUpToDate(DefaultTaskArtifactStateRepositor
y.java:79)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.exec
ute(SkipUpToDateTaskExecuter.java:50)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execut
e(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecu
ter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskE
xecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:45)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter
.execute(SkipTaskWithNoActionsExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execut
e(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter
.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.ex
ecute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTa
skWorker.execute(DefaultTaskGraphExecuter.java:233)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTa
skWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
orker.processTask(AbstractTaskPlanExecutor.java:74)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
orker.run(AbstractTaskPlanExecutor.java:55)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(Defaul
tTaskPlanExecutor.java:32)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(Defau
ltTaskGraphExecuter.java:113)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTask
ExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
r.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExec
uter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecu
ter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildEx
ecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
r.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
r.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLa
uncher.java:197)
        at org.gradle.internal.Factories$1.create(Factories.java:25)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
tBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
tBuildOperationExecutor.java:53)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(Default
GradleLauncher.java:194)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGra
dleLauncher.java:36)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradl
eLauncher.java:118)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradl
eLauncher.java:112)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
tBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
tBuildOperationExecutor.java:63)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradle
Launcher.java:112)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLaun
cher.java:98)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildControl
ler.java:66)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(Exe
cuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildA
ctionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
ssBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
ssBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.ex
ecute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.ex
ecute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter
.execute(ServicesSetupBuildActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter
.execute(ServicesSetupBuildActionExecuter.java:29)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBu
ild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(Build
CommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(
WatchForDisconnection.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute
(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.
execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(Forw
ardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(Forw
ardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(For
wardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogA
ndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClien
t.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(Build
CommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBu
ild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(Build
CommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.
run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(Daemon
StateCoordinator.java:293)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.
onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableE
xecutorImpl.java:40)


BUILD FAILED

Total time: 11 mins 13.001 secs

```

**Comment by lacasseio** [comment] 2016-12-07 16:11
The call stack looks the same as https://github.com/gradle/gradle/issues/933. I will advise once we have a fix for that one.

**Comment by danielsun1106** [comment] 2016-12-07 16:52
Thanks for your looking into the issue :)

**Comment by eriwen** [comment] 2016-12-08 17:31
Assigning to you @lacasseio to follow up since you're working on #933

**Comment by lacasseio** [comment] 2016-12-19 20:12
@danielsun1106 We rolled out a fix for what we think is the root cause for this issue in [Gradle 3.3 RC1](https://gradle.org/release-candidate/), could you give it a try and see if that fix your problem?

**Comment by danielsun1106** [comment] 2016-12-20 01:33
@lacasseio  Thanks for your fixing the issue. I'll verify it tonight ;)

**Comment by danielsun1106** [comment] 2016-12-20 14:54
The fix works :-)

**Comment by lacasseio** [comment] 2016-12-20 15:25
Thanks for confirming.

**Closed by lacasseio** 2016-12-20 15:25 UTC
Labels: a:bug, affects-version:3.2, in:core

**Comment by idrisbohra** [comment] 2017-05-16 10:29
Hello, i am encountering the same issue. can you please provide solution. link in the comment is not working provided by @lacasseio.

**Comment by lacasseio** [comment] 2017-05-16 14:57
@idrisbohra Please open an issue and fill as much information so we can track your issue.

**Comment by jugutier** [comment] 2017-09-11 21:09
Just came across this issue, running:

MacOS Sierra: 10.12.6
Java: 1.8
Gradle: 3.3

I was in the middle of building when the computer shut down because the battery died. Went back and docked at my desk, so moved the USB port in the phone to a hub I have, not sure if that had anything to do.


Trace:

```
* Exception is:
java.lang.NullPointerException: null value in entry: destinationDir=null
        at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:33)
        at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:135)
        at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:206)
        at com.google.common.collect.ImmutableSortedMap$Builder.put(ImmutableSortedMap.java:371)
        at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository$LazyTaskExecution.getOutputFilesSnapshot(CacheBackedTaskHistoryRepository.java:327)
        at org.gradle.api.internal.changedetection.rules.OutputFilesTaskStateChanges.getSnapshotAfterPreviousExecution(OutputFilesTaskStateChanges.java:61)
        at org.gradle.api.internal.changedetection.rules.OutputFilesTaskStateChanges.saveCurrent(OutputFilesTaskStateChanges.java:51)
        at org.gradle.api.internal.changedetection.rules.AbstractNamedFileSnapshotTaskStateChanges.snapshotAfterTask(AbstractNamedFileSnapshotTaskStateChanges.java:136)
        at org.gradle.api.internal.changedetection.rules.OutputFilesTaskStateChanges.snapshotAfterTask(OutputFilesTaskStateChanges.java:29)
        at org.gradle.api.internal.changedetection.rules.CachingTaskStateChanges.snapshotAfterTask(CachingTaskStateChanges.java:84)
        at org.gradle.api.internal.changedetection.rules.SummaryTaskStateChanges.snapshotAfterTask(SummaryTaskStateChanges.java:73)
        at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.afterTask(DefaultTaskArtifactStateRepository.java:154)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:196)
        at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:193)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:193)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
```

**Comment by wolfs** [comment] 2017-09-12 20:26
@jugutier: That might be related to #2827. I think this should be fixed in 4.2 - but I am not 100% sure. So you experienced this problem with 3.3?
I guess you cannot reproduce the problem, right?

**Comment by jugutier** [comment] 2017-09-12 20:33
I couldn't reproduce it after rebooting the computer, running the gradle
clean task and invalidating caches and restart. Yes, experienced in gradle
3.3.

Will certainly let you know if it comes up again.
