### ISSUE TITLE
gradle does not write module version attribute for modules with zero dependencies

### ISSUE THREAD

**Issue by dweiss** [gradle/gradle#19138] opened 2021-11-26 18:25 UTC
Original bug report: https://issues.apache.org/jira/browse/LUCENE-10267

Gradle uses javac's "--module-version" option to embed module version passed via options.javaModuleVersion. But this option is not passed to the compile unless there is at least one dependency (classpath/ module path entry). This is easily demonstrated by a simple attached project. If you run it out of the box, it shows module version embedded in the output:
```
>gradlew clean jar && java --module-path build\libs --describe-module foo

> Task :compileJava
Setting module version to: 1.0.0

BUILD SUCCESSFUL in 972ms
3 actionable tasks: 3 executed
foo@1.0.0 file:///C:/_tmp/test/build/libs/test-1.0.0.jar       // << VERSION HERE: foo@1.0.0
exports foo
requires java.base mandated
```

but if you comment out the single dependency:
```
dependencies {
  // api "org.slf4j:slf4j-api:2.0.0-alpha5"
}
```

and re-run it, the version is gone:
```
>gradlew clean jar && java --module-path build\libs --describe-module foo

> Task :compileJava
Setting module version to: 1.0.0

BUILD SUCCESSFUL in 1s
3 actionable tasks: 3 executed
foo file:///C:/_tmp/test/build/libs/test-1.0.0.jar  // << VERSION HERE IS MISSING
exports foo
requires java.base mandated
```

The problem is here in gradle sources:
https://github.com/gradle/gradle/blob/master/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JavaCompilerArgumentsBuilder.java#L277-L284

I think the condition there should actually look at inferModulePath and, if module version is set, always add that option to javac.

**Comment by dweiss** [comment] 2021-11-26 18:26
[mod-version-repro.zip](https://github.com/gradle/gradle/files/7610292/mod-version-repro.zip)

**Comment by ljacomet** [comment] 2021-11-29 09:42
Duplicate of #17484

**Closed by ljacomet** 2021-11-29 09:42 UTC
Labels: a:bug, in:modular-java, closed:duplicate
