### ISSUE TITLE
API to modify variant in generated module metadata

### ISSUE THREAD

**Issue by JakeWharton** [gradle/gradle#18862] opened 2021-11-04 13:32 UTC
I am building a Kotlin Multiplatform version of an existing Kotlin-based binary. In order to prevent duplicate classes from appearing on the consumer's classpath, I would like to modify the module metadata such that the variant for Android points to the existing dependency coordinates rather than the ones which I have built. All other variants in the module metadata should be unchanged.

As present I can create this behavior as the consumer of a dependency with metadata rules and the like, but as the publisher there does not seem to be any way to hook into the outgoing JSON.

Currently I am hooking into the task which generates the module metadata and doing a brittle-but-effective text-based replacement:
```groovy
tasks.named("generateMetadataFileForKotlinMultiplatformPublication").configure {
  doLast {
    String find = file('module_find.txt').text
    String replace = file('module_replace.txt').text

    File file = outputFile.get().getAsFile()
    String text = file.text

    int start = text.indexOf(find)
    if (start == -1) {
      throw new RuntimeException("Unable to locate module_find.txt contents in module JSON ($file)")
    }
    int end = start + find.length()

    String newText = text.substring(0, start) + replace + text.substring(end)
    file.text = newText
  }
}
```

This allows me to alter the metadata JSON to point at an external artifact for particular variants.

```diff
 {
   "name": "releaseApiElements-published",
   "attributes": {
     "org.gradle.usage": "java-api",
     "org.jetbrains.kotlin.platform.type": "androidJvm"
   },
-  "available-at": {
-    "url": "../../compose-runtime-android/0.1.0-square.15/compose-runtime-android-0.1.0-square.15.module",
-    "group": "app.cash.redwood",
-    "module": "compose-runtime-android",
-    "version": "0.1.0-square.15"
-  }
+  "dependencies": [
+    {
+      "group": "androidx.compose.runtime",
+      "module": "runtime",
+      "version": {
+        "prefers": "1.0.4"
+      }
+    }
+  ]
 }
```

This feature request is for the use case, not the result. I would be happy with some kind of dependency substitution-like API for the outgoing module metadata which allowed me to express this replacement at a very high level. However, I also would be happy with a lower-level hook into the JSON generation that even was a low as providing mutable access to a JSON object tree.

I could maintain the module metadata file by hand and publish the file as part of my Maven upload rather than allowing Gradle to generate it, but this is arduous since it is based on so much of the project structure and its properties whereas all I want to do is replace a small part.

I previously asked about this on the Gradle slack (https://gradle-community.slack.com/archives/CA7UM03V3/p1625167565381100) and have also searched the Gradle source looking for a solution but so far have found none.

**Comment by ljacomet** [comment] 2021-11-05 09:35
Hey,

Could you share more around why you cannot express that in the build itself?
We are really not keen on opening up an API for mutating the produced file. Instead we believe that use cases should be supported from the build itself.

**Comment by melix** [comment] 2021-11-09 13:21
So I mentioned this to Jake on Twitter, I think that what he's trying to do can be done with the standard APIs. If you put yourself into the "how I modify Module Metadata" mindset, or "I get this pom.xml, how do I patch it?", then it doesn't really fit the Gradle model. Instead, you should think "how do I create a publication which contains what I need". And therefore, the question isn't "how to mutate" anymore, but "how to build custom components" and you can find the docs here: https://docs.gradle.org/current/userguide/publishing_customization.html#sec:publishing-custom-components

I would then suggest to add a cross-reference in the docs, so that people looking for "how to mutate POM/Gradle Module Metadata" would have a hint that they should instead create a custom publication.

**Comment by JakeWharton** [comment] 2021-11-09 13:28
Thanks Cédric. Yes I am still trying to get it to work (been short on time).

**Comment by ScottPierce** [comment] 2021-12-05 22:18
Not an ideal scenario, but it seems like `compileOnly` dependencies could work in the short term for this as well.

**Comment by ljacomet** [comment] 2022-03-11 19:57
Closing this as without more details, there is no plan to have an API to mutate the generated Gradle module metadata. Instead you should have public APIs to modify what is to be published to get the right output generated.

**Closed by ljacomet** 2022-03-11 19:57 UTC
Labels: a:feature, closed:not-fixed, in:gradle-module-metadata

**Comment by SamB** [comment] 2023-07-16 19:13
@JakeWharton Perhaps you actually want <https://docs.gradle.org/current/userguide/component_capabilities.html>? You could declare that your `app.cash.redwood:compose-runtime` provides capability `androidx.compose.runtime:runtime`.

It might be tricky/impossible to get resolution to automatically prefer the androidx library for downstream builds, though. So perhaps that's not quite what you want.

@melix I couldn't sniff out any trail starting on https://docs.gradle.org/current/userguide/publishing_customization.html#sec:publishing-custom-components that lead to information that would help with this; see https://jakewharton.com/multiplatform-compose-and-gradle-module-metadata-abuse/ for the actual goal. There might *be* a trail, but it's not well marked and seemingly involves many clicks through types in method signatures in API docs.

<details>

<summary>Side rant</summary>

I have this problem a lot with Gradle API docs, but I'm not sure what would help with that. I suppose the root cause is that Java doesn't have a tradition of grouping many things (including multiple types) that get used together into reasonably-sized "modules" like, say, Haskell does, but just treats each type as an island, and the documentation tools reflect this, so you end up having to cross-reference between oodles of doc pages when an API has oodles of often-small types like Gradle's does in order to get any idea how the pieces are supposed to fit together.

I guess one thing that could help would be a way to generate "quick reference" pages that would basically collect copies of the summary material (mostly the Method Summary tables) from the doc pages for selected types. I wonder if javadoc can be extended to generate custom page types ...
</details>

**Comment by JakeWharton** [comment] 2023-07-17 17:40
To close the loop, I got out of this business.

However, JetBrains and Google are still in this business and they apparently have chosen to use internal Gradle APIs to manipulate the existing components: https://github.com/JetBrains/compose-multiplatform-core/blob/d9aec78d04bf59f82c5ae82ce0f662e3f9b7b9c9/buildSrc/private/src/main/kotlin/androidx/build/AndroidXComposeMultiplatformExtensionImpl.kt#L228-L302.

I was very happy to switch to be a consumer of this artifact rather than a publisher having to worry about creating it!
