### ISSUE TITLE
"Malformed class file" reported for valid class

### ISSUE THREAD

**Issue by stovocor** [gradle/gradle#1849] opened 2017-04-19 08:39 UTC
A warning is logged during compilation of Java classes when a local variable is annotated with ```@NotNull```.

### Expected Behavior
There should be no warning message since the class is valid.

### Current Behavior
When a local variable is annotated with "org.jetbrains.annotations.NotNull", a warning is written during compilation:

```Malformed class file [.../ClassName.class] found on compile classpath, which means that this class will cause a compile error if referenced in a source file. Gradle 5.0 will no longer allow malformed classes on compile classpath.```

The head of the stacktrace looks like this:

```
:myProject:compileJavajava.lang.ArrayIndexOutOfBoundsException: 12
	at org.objectweb.asm.ClassReader.readLabel(Unknown Source)
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.b(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.gradle.api.internal.tasks.compile.ApiClassExtractor.extractApiClassFrom(ApiClassExtractor.java:80)
	at org.gradle.api.internal.changedetection.state.AbiExtractingClasspathContentHasher.hashClassBytes(AbiExtractingClasspathContentHasher.java:41)
	at org.gradle.api.internal.changedetection.state.AbiExtractingClasspathContentHasher.appendContent(AbiExtractingClasspathContentHasher.java:53)
	at org.gradle.api.internal.changedetection.state.DefaultClasspathEntryHasher.hashZipEntry(DefaultClasspathEntryHasher.java:113)
	at org.gradle.api.internal.changedetection.state.DefaultClasspathEntryHasher.hashJar(DefaultClasspathEntryHasher.java:77)
	at org.gradle.api.internal.changedetection.state.DefaultClasspathEntryHasher.hash(DefaultClasspathEntryHasher.java:59)
	at org.gradle.api.internal.changedetection.state.CachingClasspathEntryHasher.hash(CachingClasspathEntryHasher.java:46)
	at org.gradle.api.internal.changedetection.state.DefaultCompileClasspathSnapshotter.normaliseFileElement(DefaultCompileClasspathSnapshotter.java:78)
	at org.gradle.api.internal.changedetection.state.AbstractFileCollectionSnapshotter$FileCollectionVisitorImpl.visitCollection(AbstractFileCollectionSnapshotter.java:144)
	at org.gradle.api.internal.file.AbstractFileCollection.visitRootElements(AbstractFileCollection.java:234)
	at org.gradle.api.internal.file.CompositeFileCollection.visitRootElements(CompositeFileCollection.java:185)
...
```

### Steps to Reproduce (for bugs)
Add a class with a line like

```
@NotNull final String str = new String("");
```

The warning is not displayed when there is no constructor used, e.g. ```str = "";``` works as expected.

### Your Environment
Gradle Wrapper 3.5, Oracle Java 1.8.0_121 (x64), Arch Linux

**Comment by bmuschko** [comment] 2017-04-19 12:20
Thanks for reporting. Do you see the same issue with 3.4?

**Comment by stovocor** [comment] 2017-04-19 13:40
Yes, it also happens with 3.4.1.

**Comment by oehme** [comment] 2017-04-19 13:46
Can you please provide a small reproducible example on GitHub?

**Comment by stovocor** [comment] 2017-04-19 13:58
Hm. Interesting. I cannot reproduce it in a minimal example. It seems that there is more to it than just the annotation and the constructor.

I will come back to you when I have a working minimal example.

**Comment by stovocor** [comment] 2017-04-20 14:54
I am sorry, but I am unable to pinpoint the problem in a reasonable amount of time. Uploading the original source is not an option because of legal issues.

Until now I experimented with Generics, implementation of an interface and adding inter-module dependencies. Sometimes the error disappears while other changes have no effect.

One possibility might be the usage of the Spring Boot plugin or its dependencies, those bring another version of ASM into play.

Since our problem could be solved by just removing the annotation of the variable, this bug may be closed as unreproducable.

**Comment by oehme** [comment] 2017-04-20 15:15
Does the exception happen while analysing one of your classes? If so, it would be in a downstream project depending on that class. Can you confirm that? In general we should be able to read any valid byte code back in. So there might be several causes:

- an ASM bug
- some tool in your build generating invalid bytecode
- some upstream dependency containing invalid bytecode (but then the error message should point at that dependency class, not at one of your classes)

**Comment by wolfs** [comment] 2017-04-20 15:36
This could be related to http://stackoverflow.com/a/26496604/2137015.

**Comment by stovocor** [comment] 2017-05-07 07:12
> some tool in your build generating invalid bytecode

This seems to be the solution. We detected other issues and were able to pinpoint those to the automatic generation of assertions for @Nullable/@Notnull by IntelliJ IDEA.

**Comment by oehme** [comment] 2017-05-08 14:33
Thanks for verifying, closing this as "working as designed" then :) Can you please paste a link to the IntelliJ bug once you've opened one?

**Closed by oehme** 2017-05-08 14:33 UTC
Labels: a:bug, affects-version:3.5, from:contributor, in:core, in:jvm-platform

**Comment by stovocor** [comment] 2017-05-08 18:00
IMO there is no need for a bug report, since the behavior of IntelliJ can be disabled in the options.

**Comment by oehme** [comment] 2017-05-08 18:01
Well, it's still a bug for those users that activate it :)

**Comment by eprst** [comment] 2017-06-01 21:19
Looks like I've hit the same problem: getting 'malformed class' errors with Gradle 3.5 for classes annotated with IntelliJ's `@Nullable/@NotNull`. Removing annotations fixes the warnings. The problem is that I don't use IntelliJ for compiling and there are no assertions generated in the bytecode (checked with disassembler).

To reproduce:
```
git clone git@github.com:SumoLogic/epigraph.git
cd epigraph
gradle -c settings-bootstrap.gradle clean :epigraph-java-data-processing:build
```

any ideas?

**Comment by yborovikov** [comment] 2017-06-01 23:33
might be related to http://forge.ow2.org/tracker/?func=detail&atid=100023&aid=317778&group_id=23

**Comment by ChristianCiach** [comment] 2017-10-11 11:06
Same problem here with Gradle 4.2.1 when using the `@Nullable` and `@NonNull`annotations of Eclipse. Altough we use them all over our projects, but gradle only complains about two class files (out of thousands).

**Comment by TriPhoenix** [comment] 2018-01-19 13:17
For others that keep hunting this one, in our project we actually seem to have encountered this due to a JDK bug (https://bugs.openjdk.java.net/browse/JDK-8144185) which apparently has been fixed only in JDK 10, the (currently dead link) by yborovikov points to the same issue in the end IIRC. 
Specifically the JDK compiler generates invalid class content that trips up asm and other code analysis tools because the class file actually is invalid. An issue could be however, that this may affect more and more users if they switch to JDK 8+ and Gradle 5.0 (currently the only options seem to be to either switch to the eclipse compiler or to remove annotations from the offending classes if they can be identified; which both can be no-gos)
