### ISSUE TITLE
Checkstyle plugin side effects by copy task for checkstyle.xml

### ISSUE THREAD

**Issue by d1ss0nanz** [gradle/gradle#4000] opened 2018-01-09 12:05 UTC
I use a custom task to copy the checkstyle.xml file from a dependcy JAR into the config/checkstyle directory.

The checkstyle.xml is valid and when I remove the custom task from build.gradle and run checkstyleMain everything works as expected.

But with the custom task Checkstyle is behaving strange: The ImportControl module runs amok and classifies hundreds of imports as disallowed.

The same config file is processed fine when I pass it to checkstyle on the command line.

I think that the custom task is somehow messing with the Checkstyle Plugin config.

### Expected Behavior
The outcome of the checkstyleMain task should not depend on the presence of a custom copy task for checkstyle.xml

### Current Behavior
When the task extractCheckstyleDependency (see Context) is present, checkstyle is reporting all kinds of violations. The config on disk is not the issue. When I run checkstyle from the command line, or remove the task extractCheckstyleDependency, it's working as expected.

### Context
I'd like to use a dependency JAR file to providde the checkstyle.xml and copy it to 'config/checkstyle/' before the checkstyle plugin runs. 

### Steps to Reproduce (for bugs)
```
 dependencies {
      checkstyleDependency group: 'com.xxx.yyy', name: 'yyy-commons', version: '0.0.3-SNAPSHOT'
 }
 
 configurations {
     checkstyleDependency
 }
 
 task extractCheckstyleDependency(type: Copy, dependsOn: configurations.checkstyleDependency) {
    from zipTree(configurations.checkstyleDependency[0]), {include "checkstyle/*"}
    into 'config/checkstyle'
    eachFile {
        f -> f.path = f.path.replaceFirst('checkstyle/', '')
    }
    includeEmptyDirs false
}

checkstyle {
    toolVersion = "8.7"   
    maxWarnings = 0
}

tasks.withType(Checkstyle) {
	dependsOn extractCheckstyleDependency
    reports {
        xml.enabled true    // needed by jenkins
        html.enabled true
    }
}
```

### Your Environment
Gradle 4.4.1, checkstyle 8.7

**Comment by bigdaz** [comment] 2018-01-09 13:37
There's a chance that this is the same issue as #3908,  but it's hard to tell from this bug report.
Ways that you can confirm this:
1. Run your build with Gradle 4.3.1 and see if the problem remains. If so, it's a different issue.
2. Run your build with a Gradle nightly snapshot >= Jan 10. (The fix for #3908 is not in the Jan 9 nightly)

**Comment by d1ss0nanz** [comment] 2018-01-10 19:04
Ok, I'm waiting for the next nightly and will try to reproduce the issue.

**Comment by d1ss0nanz** [comment] 2018-01-11 10:18
Problem also gone in 4.6-20180110235838+0000.

What is the schedule for Gradle 4.6?

**Comment by bmuschko** [comment] 2018-01-11 15:51
We should release the 4.6 final version in 4-6 weeks.

**Comment by bigdaz** [comment] 2018-01-11 18:17
Thanks for confirming @d1ss0nanz. Closing as a duplicate of #3908

**Closed by bigdaz** 2018-01-11 18:17 UTC
