### ISSUE TITLE
Detect JDKs provisioned by Github actions automatically

### ISSUE THREAD

**Issue by bmuskalla** [gradle/gradle#14903] opened 2020-10-19 10:37 UTC
We should have a look at common actions on GitHub actions that provision JDKs.
If we can find a pattern, we may be able to automatically detect those without additional setup

Example: `actions/setup-java@v1`

**Comment by evpaassen** [comment] 2021-05-03 15:30
This feature would be very useful to me.

The runners hosted by GitHub seem to have a *[Hosted Tool Cache](https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#hosted-tool-cache)* with some JDKs preinstalled.

An example path to a JDK in the cache is:
```
/opt/hostedtoolcache/Java_Adopt_jdk/16.0.1-9/x64
```
So the pattern seems to be something like:
```
/opt/hostedtoolcache/<distribution>/<version>/<architecture>
```

However, the `setup-java` action also [allows to provision JDKs that are not in the cache](https://github.com/actions/setup-java#basic) and I don't know where those would be installed. actions/setup-java#44 contains some relevant information on this topic.

Please let me know if I can help in any way.

**Comment by joffrey-bion** [comment] 2023-06-09 23:00
Are there any plans to move this forward? This is what makes me reluctant to use JVM toolchains.

Note that the setup-java action is instant when using the `temurin` distribution because this distribution is *already* on the runner. If Gradle could find those pre-installed distributions automatically, we wouldn't even need the setup-java action!

**Comment by joffrey-bion** [comment] 2023-08-11 09:16
Ok thanks for providing a status, I'm looking forward to this! 🙏

**Comment by joffrey-bion** [comment] 2023-08-11 09:19
About this:

> The path to the tool cache directory resides in the environment variable RUNNER_TOOL_CACHE.
> 
> However, the setup-java action also [allows to provision JDKs that are not in the cache](https://github.com/actions/setup-java#basic) and I don't know where those would be installed. https://github.com/actions/setup-java/issues/44 contains some relevant information on this topic. B.t.w. notice that setup-java@v2 allows selecting the JDK distribution, while v1 did not.

It looks like those are 2 different features. I believe Gradle could by default look into the default hosted tool cache of GitHub runners, but not necessarily be aware of specific GitHub actions (like setup-java) and where they place things (as this path is technically dynamic and can be retrieved as an output of the setup-java action).

**Comment by joffrey-bion** [comment] 2023-08-11 09:26
As a workaround, GitHub currently provides 3 env variables for the Java home of the 3 current LTS versions: `JAVA_HOME_8_X64`, `JAVA_HOME_11_X64`, and `JAVA_HOME_17_X64`. So I believe we could provide those env variables as JDK installation dirs in a project's `gradle.properties` like this:

```
org.gradle.java.installations.fromEnv=JAVA_HOME_8_X64,JAVA_HOME_11_X64,JAVA_HOME_17_X64
```

Now that I think of it maybe GitHub could provide such a default `gradle.properties` (in the home dir or gradle installation dir?), but the current precedence order could mean that users can no longer use this Gradle property themselves at the project level. Is this correct? Why is the order of precedence this way?

**Comment by ov7a** [comment] 2023-08-11 09:54
@joffrey-bion That's a great idea! If it can be resolved at the action level, it would be nice.

>  users can no longer use this Gradle property themselves at the project level

Yes, that is correct, however, it can be overridden again by a command line. I don't think it's a big problem.

> If GitHub pre-installed some Gradle (not the case now) and put this property in the Gradle installation dir, would this affect projects that use the Gradle wrapper? (it might be worth clarifying this in the docs, by the way)

It shouldn't matter how Gradle is invoked: as local `./gradlew` or global `gradle` in that context.

**Comment by ov7a** [comment] 2023-08-11 09:55
Regarding the gradle action, PTAL at the [issue](https://github.com/gradle/gradle-build-action/issues/561) there

**Comment by ov7a** [comment] 2023-08-11 09:59
> Why is the order of precedence this way?

The idea here is user preferences should have higher priority than project preferences. So CLI has a clear intent, then users preferences, project preferences, and lastly, "system" preferences.

**Comment by joffrey-bion** [comment] 2023-08-11 10:13
> Yes, that is correct, however, it can be overridden again by a command line. I don't think it's a big problem.

Well it is definitely a problem if GitHub were to define some properties in the home dir of the runners, because users setting `gradle.properties` in their project would see their settings ignored and might not understand why.

> > Why is the order of precedence this way?
>
> The idea here is user preferences should have higher priority than project preferences. So CLI has a clear intent, then user preferences, project preferences, and lastly, "system" preferences.

While I see the point, I never ever needed to express it this way. But every single time I wanted to express user *defaults*, hoping to override them in a per-project basis... and it doesn't work this way.

> > If GitHub pre-installed some Gradle (not the case now) and put this property in the Gradle installation dir, would this affect projects that use the Gradle wrapper? (it might be worth clarifying this in the docs, by the way)
>
> It shouldn't matter how Gradle is invoked: as local ./gradlew or global gradle in that context.

If it doesn't matter how Gradle is run, does that mean that my `C:\gradle\gradle.properties` affect a `./gradlew build` run from projects that don't use this gradle installation at all? That would be insane, wouldn't it?
If it *does* matter how Gradle is run, what constitutes the "gradle properties in the installation dir" in case of gradle wrapper? And more importantly how can I specify *default values* of Gradle properties for a given machine (e..g memory or JDK locations), but overridable per project?

Anyway, this whole topic is out of scope for this discussion, sorry for the off topic, I just wanted to confirm that GitHub cannot and thus shouldn't try to do this.

**Comment by joffrey-bion** [comment] 2023-08-11 10:14
> Regarding the gradle action, PTAL at the https://github.com/gradle/gradle-build-action/issues/561 there

Oh, I forgot about this action. It could definitely be provided as an extra CLI argument by default in this GitHub action, I'll head over to that issue. Thanks!

**Comment by ov7a** [comment] 2023-08-11 12:54
> users setting gradle.properties in their project would see their settings ignored and might not understand why.

No, they would be overridden, not ignored. And it only applies to settings set by action, not all settings.

As for your use case - let's jump into a separate issue. I think there is a clear need to have better documentation in this area. Would you like to create a documentation issue with a list of stuff that should be clarified in that area?

**Comment by joffrey-bion** [comment] 2023-08-14 15:13
> No, they would be overridden, not ignored. And it only applies to settings set by action, not all settings.

Yes, I was unclear about this. The problem is still there, though. GitHub cannot set this property as a default without overriding the same property defined at the project level by some users.

> Would you like to create a documentation issue with a list of stuff that should be clarified in that area?

I opened the following:

* https://github.com/gradle/gradle/issues/26107
* https://github.com/gradle/gradle/issues/26088

**Comment by bigdaz** [comment] 2023-08-20 00:02
I've done some testing, and toolchain detection is now _mostly_ working on GitHub Actions runners, without any special handling in the `gradle-build-action`.

There are 2 types of JDKs that can be detected on a runner:
1. Pre-installed JDKs, that exist without any use of `setup-java`
2. JDKs that are downloaded and installed on demand with `setup-java`

On `ubuntu-latest` and `macos-latest`, both of these types are automatically detected. The pre-installed JDKs are symlinked into standard locations, and the `setup-java` JDKS are detected because the action is updating the Maven Toolchains file.

On `windows-latest`, only the second type are detected, via the Maven Toolchains mechanism. Unfortunately the pre-installed JDKs are not found in a standard location and are not detected.

So as long as `setup-java` is used to provision all of the required JDKs, then these will be detected by Gradle and not re-downloaded.

I will attempt to update the `gradle-build-action` so that the pre-installed JDKs are detected on Windows as well, by supplying the env var names as suggested.

I think it's safe to close this issue, since this is something that should be fixed in the GitHub Runner (or the `gradle-build-action`).

**Closed by bigdaz** 2023-08-20 00:02 UTC
Labels: a:feature, in:toolchains, has:workaround
