### ISSUE TITLE
Build failures when using Spock with JUnit Vintage starting with Gradle 5.1

### ISSUE THREAD

**Issue by tomekgajdos** [gradle/gradle#8787] opened 2019-03-15 10:25 UTC
### Expected Behavior
Gradle build does not fail with gradle 5.1 or higher.

### Current Behavior
Gradle build fails with gradle 5.1 or higher.

`Received a completed event for test with unknown id '2.5'. Registered test ids: '[2.2, 2.1, :test]'
java.lang.IllegalArgumentException: Received a completed event for test with unknown id '2.5'. Registered test ids: '[2.2, 2.1, :test]'
        at org.gradle.api.internal.tasks.testing.results.StateTrackingTestResultProcessor.completed(StateTrackingTestResultProcessor.java:79)
        at org.gradle.api.internal.tasks.testing.results.AttachParentTestResultProcessor.completed(AttachParentTestResultProcessor.java:56)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:29)
        at org.gradle.internal.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:87)
        at org.gradle.internal.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:36)
        at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:71)
        at org.gradle.internal.concurrent.InterruptibleRunnable.run(InterruptibleRunnable.java:42)
        at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)`

### Context
After gradle upgrade from 5.0 to 5.1 the build fails.

### Steps to Reproduce (for bugs)
Demo gradle project [tmp-test-lib-a](https://github.com/tomekgajdos/tmp-test-lib-a) is provided and below are commands for reproduction:
`./gradlew wrapper --gradle-version 5.0 && ./gradlew clean build -Dtest.single=AbcTestSuite` -> WORKS.
`./gradlew wrapper --gradle-version 5.1 && ./gradlew clean build -Dtest.single=AbcTestSuite` -> DOES NOT WORK.

**Comment by big-guy** [comment] 2019-03-15 23:14
@marcphilipp does this look familiar?  I can reproduce this with 5.3-rc-3

**Comment by marcphilipp** [comment] 2019-03-16 12:43
@tomekgajdos Thanks for reporting this issue!

These are the events sent by the JUnit Vintage engine:
```
Started:     JUnit Jupiter ([engine:junit-jupiter])
Finished:    JUnit Jupiter ([engine:junit-jupiter])
Started:     JUnit Vintage ([engine:junit-vintage])
Started:     AbcTestSuite ([engine:junit-vintage]/[runner:AbcTestSuite])
Started:     AbcTest ([engine:junit-vintage]/[runner:AbcTestSuite]/[test:AbcTest])
Started:     simple ([engine:junit-vintage]/[runner:AbcTestSuite]/[test:AbcTest]/[test:simple(AbcTest)])
Finished:    simple ([engine:junit-vintage]/[runner:AbcTestSuite]/[test:AbcTest]/[test:simple(AbcTest)])
Finished:    AbcTest ([engine:junit-vintage]/[runner:AbcTestSuite]/[test:AbcTest])
Test registered:   aaa 1 ([engine:junit-vintage]/[runner:AbcTestSuite]/[test:AbcTest]/[dynamic:aaa 1(AbcTest)])
Started:     aaa 1 ([engine:junit-vintage]/[runner:AbcTestSuite]/[test:AbcTest]/[dynamic:aaa 1(AbcTest)])
Finished:    aaa 1 ([engine:junit-vintage]/[runner:AbcTestSuite]/[test:AbcTest]/[dynamic:aaa 1(AbcTest)])
Finished:    AbcTestSuite ([engine:junit-vintage]/[runner:AbcTestSuite])
Started:     AbcTest ([engine:junit-vintage]/[runner:AbcTest])
Started:     simple ([engine:junit-vintage]/[runner:AbcTest]/[test:simple(AbcTest)])
Finished:    simple ([engine:junit-vintage]/[runner:AbcTest]/[test:simple(AbcTest)])
Test registered:   aaa 1 ([engine:junit-vintage]/[runner:AbcTest]/[dynamic:aaa 1(AbcTest)])
Started:     aaa 1 ([engine:junit-vintage]/[runner:AbcTest]/[dynamic:aaa 1(AbcTest)])
Finished:    aaa 1 ([engine:junit-vintage]/[runner:AbcTest]/[dynamic:aaa 1(AbcTest)])
Finished:    AbcTest ([engine:junit-vintage]/[runner:AbcTest])
Finished:    JUnit Vintage ([engine:junit-vintage])
```

So, apparently it reports the test class (`[engine:junit-vintage]/[runner:AbcTestSuite]/[test:AbcTest]`) as finished before starting the unrolled test (`[engine:junit-vintage]/[runner:AbcTestSuite]/[test:AbcTest]/[dynamic:aaa 1(AbcTest)]`) when it is executed in a suite.

A proper fix should go into JUnit Vintage and I'll open an issue there momentarily.

@tomekgajdos In your sample project `AbcTest` is executed twice: once by the suite and once because it's discovered by Gradle when scanning the classpath. Is that on purpose?

As a workaround, you can exclude all suite classes using the following snippet.

```gradle
test {
    exclude('**/*Suite.class')
}
```

**Comment by tomekgajdos** [comment] 2019-03-16 14:58
@marcphilipp: It is not real usecase, it is just a demo project for reproducing the issue. We have a lot of spock tests (without test suites) and we have the same issue. Everything works fine with gradle 5.0 but after gradle upgrade to 5.1 or higher it does not work. We have three possible workarrounds: 1) Use gradle ‘5.0’. OR 2) Remove all spock @Unroll annotations. OR 3) Fork each test.

**Comment by marcphilipp** [comment] 2019-03-16 20:42
I've fixed this in JUnit Vintage 5.4.1-SNAPSHOT. Could you please give the latest snapshot a try? Repo is https://oss.sonatype.org/content/repositories/snapshots

**Comment by marcphilipp** [comment] 2019-03-17 19:57
The bugfix has been released in JUnit 5.4.1.

@tomekgajdos Could you please give that a try?

**Comment by tomekgajdos** [comment] 2019-03-17 20:21
I'll check it, I'll inform you.

**Comment by tomekgajdos** [comment] 2019-03-18 12:40
It seems the fix works for simple demo project but it does not work for our complex project:

`Received a failure event for test with unknown id '2.160'. Registered test ids: '[2.1, :moduleA-test:moduleB-bt:test, 2.158]'`

**Comment by marcphilipp** [comment] 2019-03-18 16:33
@tomekgajdos Can you try to update the sample project with a test that reproduces the issue?

**Comment by tomekgajdos** [comment] 2019-03-20 08:28
I will investigate this but I am not sure when ... we have now something else with higher priority.

**Comment by harshSE** [comment] 2020-04-02 14:40
@marcphilipp 

I am getting below exception when running integration tests which cause problem in generating test-report. 

```
* Exception is:
Caused by: java.lang.IllegalArgumentException: Received a failure event for test with unknown id '7.194'. Registered test ids: '[8.104, 5.423, 8.107, 5.1, 5.385, 7.1, 9.1, 8.1, :mobiledoc:integrationTest, 9.82, 9.84, 7.185]'
	at org.gradle.api.internal.tasks.testing.results.StateTrackingTestResultProcessor.failure(StateTrackingTestResultProcessor.java:103)
	at org.gradle.api.internal.tasks.testing.results.AttachParentTestResultProcessor.failure(AttachParentTestResultProcessor.java:43)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:30)
	at org.gradle.internal.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:87)
	at org.gradle.internal.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:36)
	at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:71)
	at org.gradle.internal.concurrent.InterruptibleRunnable.run(InterruptibleRunnable.java:42)
	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
	... 3 more
```



### Expected Behavior

Gradle should create test-report.

### Current Behavior

We have Spock 1.X test cases, JUnit 4 test cases.
All the test cases are passing but gradle is not able to generate report due to above exception.
We are using junit5 with vintage engine and most of our test cases are written in junit4.

### Context



For one of our task, We use junit5 listener. For that purpose, we run out test cases with JUnit5 while most of our test cases are in JUnit4. With this upgrade, we are not able to generate test result when we run test cases in parallel. This affects us in CI process. 

Before upgrade with JUnit 5, All are working fine.

 **We cannot degrade to Junit4 because we are dependent on JUnit 5 test listener interface, which we are using to listen to Spock @Unroll test names.**

We are using gradle parallel forking with a  batch size=50. Build script snippet is attached below.

We referred this issue #6453, which referes to the same problem but it conclueded that problem is reproduced when Junit parallel execution is enabled.

**We are not using JUnti5 parallel execution but still we are able to reproduce the issue.**

### Steps to Reproduce 



Below are the tasks and dependencies.
```

integrationTestCompile(
            'org.codehaus.groovy:groovy-all:2.4.8',
            'org.spockframework:spock-core:1.0-groovy-2.4',
            'junit:junit:4.12',
            'org.junit.jupiter:junit-jupiter-api:5.6.0'
    )

integrationTestRuntime(
            'org.junit.platform:junit-platform-launcher:1.6.0',
            'org.junit.vintage:junit-vintage-engine:5.6.0',
            'org.junit.jupiter:junit-jupiter-engine:5.6.0')

task integrationTest(type:Test){

	maxParallelForks=Runtime.runtime.availableProcessors().intdiv(2)
	forkEvery=50
        useJUnitPlatform()
	testLogging { showStandardStreams = true }

      description = 'Runs integration tests.'
      group = 'verification'

      testClassesDirs = sourceSets.integrationTest.output.classesDirs
      classpath = sourceSets.integrationTest.runtimeClasspath
      testLogging.showStandardStreams = true
}
```

The issue doesn't sufrface if test set is small. It is reproduced when run with larger test set size. In my case the test cases are 1100+.

### Your Environment
OS: Windos 10
Gradle Version: 5.6.4
JUnit5-platform: 1.6.0
Junit5-Vintage-Engine:5.6.0
Junit4 Version: 4.12
Spock: 1.0-Groovy-2.4
Java Version: 1.8.0_202(openjdk)

**Comment by harshSE** [comment] 2020-04-02 16:03
@marcphilipp there were able to pin point the issue down to Unroll test case with duplicate name. Check out above comment and please help us out with solution or workaround. It's blocker for us.

**Comment by marcphilipp** [comment] 2020-04-03 11:47
@harshSE Please make sure you use unique names within one specification class.

**Comment by harshSE** [comment] 2020-04-13 05:42
@marcphilipp we have done the same. We have identified specification which contains duplicate test name and apply id for unique ness

**Comment by marcphilipp** [comment] 2020-04-14 13:22
So it's no longer a blocker, is it?

**Comment by harshSE** [comment] 2020-04-16 10:57
For now Yes. After changing the test code to have unique name, we have not face any problem. 
But It my occure in future, in case some developers write test cases which generate duplicate name.

**Comment by blindpirate** [comment] 2020-05-11 01:46
This workaround works. Closing.

**Closed by blindpirate** 2020-05-11 01:46 UTC
Labels: from:contributor, in:testing
