### ISSUE TITLE
Cancelling the build should kill blocking Exec tasks

### ISSUE THREAD

**Issue by KIC** [gradle/gradle#4035] opened 2018-01-15 11:40 UTC
For some tasks it is difficult to notice when the user has stopped it i.e. by the use of Ctrl + c. Becasue the daemon is still running the task keps as well running in the background. But if this task is using resources or starting a server then the resources like files or ports are blocked and te task fails. The only way to actually stop the task is killing the gradle daemon using OS tools (gradle --stop is interestingly not enough). 

Currently the only workaround is to provide the --no-daemon flag as command line argument. But it would be very handy if one could indicate this via annotation i.e.:

```
@NoDaemon
task start(type: YarnTask) {
  args = ['start']
}

```
### Expected Behavior
As a result of the NoDaemon annotation we expect the gradle task to behave the same way as it does with the provieded --no-daemon command line switch.

### Current Behavior
Currently the only workaround is to provide the --no-daemon flag as command line argument.
https://github.com/srs/gradle-node-plugin/issues/143

### Context
it would be very handy if one could annotate tasks with `@NoDaemon` to not start a daemon. Obviously thiss is true if another task depends an such a task. As an example take a look at the gradle node plugin.

### Steps to Reproduce (for bugs)
Just apply the gradle node plugin and start the node server using the start task. Stop the node server by stopping the gradle task (i.e. use ctrl + c). Restart the task, it will fail. To make it work one has to use the --no-daemon flag like indicated in this bug: https://github.com/srs/gradle-node-plugin/issues/143

### Your Environment

 * Build scan URL:

**Comment by oehme** [comment] 2018-01-15 14:24
Every task should work with the daemon. Working without the daemon is way too slow. What you describe is a bug - the build cancellation should be forwarded to the task that was running instead of leaving it around in a zombie state.

**Comment by oehme** [comment] 2018-01-15 14:42
I'm closing this as a duplicate of #1128

**Closed by oehme** 2018-01-15 14:43 UTC
Labels: a:bug, from:contributor, in:daemon
