### ISSUE TITLE
runtime dependency is erroneously also added as a testCompile dependency

### ISSUE THREAD

**Issue by trejkaz** [gradle/gradle#1739] opened 2017-04-03 04:44 UTC
Given the following build file:

```
apply plugin: 'java'
apply plugin: 'idea'

repositories {
    jcenter()
}

dependencies {
    runtime 'org.slf4j:slf4j-api:1.7.21'
}
```

When I run:

```
gradle idea
```

The resulting project should contain a `scope="RUNTIME"` dependency for slf4j-api.

What I actually get is:

```
    <orderEntry type="module-library" scope="RUNTIME">
      <library>
        <CLASSES>
          <root url="jar:///Users/daniel/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.21/139535a69a4239db087de9bab0bee568bf8e0b70/slf4j-api-1.7.21.jar!/"/>
        </CLASSES>
        <JAVADOC/>
        <SOURCES>
          <root url="jar:///Users/daniel/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.21/f285ac123f201fb4b028bac556928d7cf527ef48/slf4j-api-1.7.21-sources.jar!/"/>
        </SOURCES>
      </library>
    </orderEntry>
    <orderEntry type="module-library" scope="TEST">
      <library>
        <CLASSES>
          <root url="jar:///Users/daniel/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.21/139535a69a4239db087de9bab0bee568bf8e0b70/slf4j-api-1.7.21.jar!/"/>
        </CLASSES>
        <JAVADOC/>
        <SOURCES>
          <root url="jar:///Users/daniel/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.21/f285ac123f201fb4b028bac556928d7cf527ef48/slf4j-api-1.7.21-sources.jar!/"/>
        </SOURCES>
      </library>
    </orderEntry>
```

The second of these, the `scope="TEST"`, should not be here, as I did not ask for it as a compile dependency.

I can reproduce this both under Gradle 3.4 (where I found it) and 3.4.1.

**Comment by oehme** [comment] 2017-04-08 11:08
TEST contains both the test compile and test runtime dependencies in Idea, so there is bo way for us to distinguish the two. Any runtime dependency is transitively also a testRuntime dependency.

I'm closing this as working as intended, as this doesn't change idea's behavior. It's a purely cosmetic concern in the .iml file.

**Closed by oehme** 2017-04-08 11:08 UTC

**Comment by trejkaz** [comment] 2017-04-08 12:10
Not actually true, because it does change IDEA's behaviour.

In particular, transient dependencies which you only had in runtime are now allowed in compile-time for tests, allowing people to call classes they're not supposed to be calling. If you remove the extraneous "TEST" element, IDEA goes back to not allowing these classes to be used in the code.

**Comment by trejkaz** [comment] 2017-04-08 12:13
Demonstration:

1. Create a file which uses a class which should not be on the compile classpath:

```
$ cat src/test/java/TestClass.java 
import org.slf4j.Logger;

public class TestClass {
    Logger logger;
}
```

2. Run `gradle idea` (in case you didn't have the `src/test/java` dir before doing this)

3. Go to IDEA and hit compile - notice that compilation succeeds, when it should not.

4. Go back to the terminal. Hand-edit the .iml file to remove the "TEST" dependency.

5. Re-run `gradle idea`

6. Go to IDEA and hit compile - notice that compilation now (correctly) fails.

**Comment by oehme** [comment] 2017-04-08 12:56
I encourage you to use IDEA's importer with the "Module per SourceSet" option instead of running `gradle idea`. Additionally, @vladsoroka is planning to bring this feature to Gradle's `idea` plugin, making you able to further customize how a single project is mapped to multiple IDEA modules.

We have no plans to make the mapping to a single IDEA module any more complex than it is now. The fact that runtime and compile are not separated for tests is not going to change in IDEA. Instead, the way forward is generating separate modules.

**Comment by trejkaz** [comment] 2017-04-08 12:58
The problem at the moment doesn't seem to be entirely IDEA lacking a place to put "testRuntime" stuff, but rather Gradle putting dependencies into "test" which weren't in "test" or "testRuntime" in the first place. In the example build, I only put it into "compile", so really in the IDEA project, it should only be in "compile"...

**Comment by oehme** [comment] 2017-04-08 13:03
> I only put it into "compile", so really in the IDEA project, it should only be in "compile"...

That would require complex hardcoded addition/subtraction rules, which place a large maintenance burden on us. We've been there and it significantly slowed down any improvement to our IDEA plugin.

Please give the IDEA importer a spin, it should work just fine unless your build has some fancy .iml-postprocessing rules.
