### ISSUE TITLE
processResources not up-to-date when adding directory that contains no relevant files

### ISSUE THREAD

**Issue by pyrocks** [gradle/gradle#7550] opened 2018-10-28 15:17 UTC
When doing 
```
sourceSets {
        main {
            resources {
                srcDirs += 'someDir'
            }
        }
    }
```
the processResources task automatically becomes not up-to-date - even though someDir contains no resource files (or all files within this folders are excluded using an 'exclude' pattern).
See real use case below.

### Expected Behavior

Adding the folder on its own does not cause processResources to be not up-to-date as the inputs of the tasks should be the matched contents of the srcDirs and not the srcDirs themselves.
Logically speaking - if I added no resource files - the task should not run. The same behavior is expected from any task respecting up-to-date checks.

### Current Behavior

The processResources task is not up-to-date even if adding:
1.  an empty folder
2. a folder with no relevant files (i.e no resources files or files are excluded using an 'exclude' pattern

### Context

Our resources are under source folders - not separate like a standard gradle project. When we generate code and resource files to build/generated/<type> we also add the folder to java.srcDir. In afterEvaluate - we add all java.srcDirs to resources.srcDirs with exclude filter on specific folders.
Since the tasks generating code are not depending on prcoessResources - the addition of a new folder added by first build is causing processResources to always run on 2nd build, even if we only generated code and not resource files.

### Steps to Reproduce (for bugs)

with this build:
```
plugins {
    id 'java'
}

def extraResourceDir = "$buildDir/generated"

tasks.register('generateAlways') {
    def genDir = "$extraResourceDir/genAlways"
    def generatedResource = "$genDir/always.cfg"
    outputs.file generatedResource
    sourceSets {
        main {
            resources {
                srcDirs += genDir
            }
        }
    }
    doLast {
        file(generatedResource).text = "generated by ${it.name}"
    }
}

tasks.register('generate1') {
    def genDir = "$extraResourceDir/gen1"
    def generatedResource = "$genDir/something.txt"
    outputs.file generatedResource
    sourceSets {
        main {
            resources {
                srcDirs += genDir
            }
        }
    }
    doLast {
        file(generatedResource).text = "generated by ${it.name}"
    }
}

processResources.mustRunAfter generate1
processResources.dependsOn generateAlways

sourceSets {
    main {
        resources {
            exclude '**/*.txt'
        }
    }
}
```
first run "gradle processResources"
then run "gradle generate1 processResources" - even though generate1 adds a folder to resources - .txt files are excluded and it should not affect processResources - yet it still runs.

### Your Environment

gradle 4.10.2

**update: I cannot seem to reproduce this in gradle 4.9 - processResources seems up-to-date on 2nd run**

**Comment by pyrocks** [comment] 2018-10-28 15:19
p.s I know our use-case is weak - we are working on adding the folder to java.srcDir and resources.srcDir per task and per need and not in afterEvaluate like mentioned above.
Still - I believe the inputs of prcoessResources should be the matched contents of the directories rather than list of directories themselves - hence I do believe it to be a bug.

**Comment by wolfs** [comment] 2019-05-20 08:05
Duplicate of #9081

**Closed by wolfs** 2019-05-20 08:05 UTC
Labels: @build-cache, from:member
