### ISSUE TITLE
Cannot create configuration with older artifacts from project

### ISSUE THREAD

**Issue by mnlipp** [gradle/gradle#8717] opened 2019-03-08 11:18 UTC
### Expected Behavior

The use case is baselining against a configuration with an older version of a projects artifact. This *should* be very simple:
```
configurations {
    baseline
}

dependencies {
    baseline("de.mnl.osgi:de.mnl.osgi.coreutils:1.0.0")
}
```
(Defined in build build.gradle of the project with groupId "de.mnl.osgi" and name "de.mnl.osgi.coreutils".)

`baseline.singleFile`  should then return the jar with that version.

### Current Behavior

`baseline.singleFile` returns the jar currently build by the project (so baselining does not work).

### Context

Until gradle 4.7 the expected behavior could be enforced with `force true` (see [here](https://discuss.gradle.org/t/gradle-always-resolves-my-local-artifact-as-a-dependency-even-when-the-version-is-wrong/2200/6)). The culprit in the current code base is [here](https://github.com/gradle/gradle/blob/df82803c0a8f541975d93a1eca5dc41bb6d79cec/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/selectors/SelectorStateResolver.java#L63), where the "the root component [is added] into the mix" without taking into account if version restrictions are met or not. While I can understand that resolving to the project's current version may make sense under certain circumstances, this behavior is completely undocumented (I've read through the manual pages&mdash;starting [here](https://docs.gradle.org/current/userguide/introduction_dependency_management.html) and going through all the detail pages&mdash;for several times in the last few days and couldn't find a single mentioning).

This "enforcement" takes place *after* all those nice [well documented](https://docs.gradle.org/current/userguide/customizing_dependency_resolution_behavior.html) tunings, so these don't help.

Considering the tunings, the observed behavior is even more inexplicable, because you'd expect that [`preferProjectModules`](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html#org.gradle.api.artifacts.ResolutionStrategy:preferProjectModules()) is required to get this behavior.

### Approaches for fixing 

* Provide (yet another) flag for the resolver that prevents the insertion of the project's current artifacts in the set of candidates

* Add the project's current artifacts *before* the evaluation of the rules defined by the resolution strategy so that it can be ruled out.

### Notes

This seems to be a long standing topic. Apart from the discussion mentioned before, I found several more such as [this one](https://discuss.gradle.org/t/how-can-i-grab-the-previous-version-of-a-projects-jar/6411).

Currently the only feasible work-around seems to be to [resolve with a modified project group](https://discuss.gradle.org/t/is-the-default-configuration-leaking-into-independent-configurations/2088/6).

**Comment by ljacomet** [comment] 2019-03-08 12:51
Duplicate of #7706

**Closed** 2019-03-15 23:15 UTC
Labels: from:contributor, in:dependency-management
