### ISSUE TITLE
Daemon selection logic doesn't consider distribution

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#5161] opened 2018-04-24 23:10 UTC
When mixing a custom Gradle distribution with stock Gradle in open source projects, a daemon running a distribution without the custom distribution `init.d` scripts will be selected.

For instance, after running a Gradle 4.7 on an OSS project, I get a failure on an internal build with:
```
 * What went wrong:
 A problem occurred evaluating root project 'test'.
	 > Plugin with id 'nebula' not found.
```

That's due to the daemon selection logic not considering the distribution when selecting a daemon:

```
501 40103     1   0  4:04PM ??         0:22.91 /Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/bin/java -XX:+HeapDumpOnOutOfMemoryError -Xmx1024m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /Users/dannyt/.gradle/wrapper/dists/gradle-4.7-bin/73xux3q4721jgr4pjvqf9o30/gradle-4.7/lib/gradle-launcher-4.7.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 4.7
```

```
16:05:00.582 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClient] Connected to daemon DaemonInfo{pid=40103, address=[500c90e4-f0bb-434a-af69-e4dfb71307fe port:49238, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], state=Idle, lastBusy=1524611073286, context=DefaultDaemonContext[uid=82b35016-cf58-4aa8-9811-d049ef638182,javaHome=/Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home,daemonRegistryDir=/Users/dannyt/.gradle/daemon,pid=40103,idleTimeout=10800000,daemonOpts=-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]}. Dispatching request Build{id=e505c864-e425-4b76-b7a5-907b4dd49ea9, currentDir=/private/tmp/test}.
```

This project should have started a new daemon that looked like this:

```
501 40318 40269   0  4:05PM ttys000    0:00.04 /Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/bin/java -XX:+HeapDumpOnOutOfMemoryError -Xmx1024m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /Users/dannyt/.gradle/wrapper/dists/nebula-gradle-5.2.0-all/91apuj6ixz44yk2rgo5dio46e/gradle-4.7/lib/gradle-launcher-4.7.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 4.7
```

```
16:05:22.819 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClient] Connected to daemon DaemonInfo{pid=40318, address=[33f0a3b9-f814-4146-a3ee-2efe7fd16999 port:49293, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], state=Busy, lastBusy=1524611122779, context=DefaultDaemonContext[uid=1f71c965-8908-41ba-a9d0-4ba2065b3a3f,javaHome=/Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home,daemonRegistryDir=/Users/dannyt/.gradle/daemon,pid=40318,idleTimeout=10800000,daemonOpts=-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]}. Dispatching request Build{id=23fdb6e2-7900-4b40-8e72-439937923f30, currentDir=/private/tmp/test}.
```

### Expected Behavior
The distribution URL/name should be considered when selecting a daemon to run a build.

### Current Behavior
The distribution is not considered, and can lead to build failures.

### Context
Engineers that work on OSS and internal projects frequently encounter failures.

### Steps to Reproduce (for bugs)
Create a custom distribution with an `init.d` file. Run a build with a stock distribution of that version, then again with the custom distribution. Note that `init.d` files are not run.

### Your Environment
Gradle 4.7. But affects all previous releases as far as I can tell.

**Comment by oehme** [comment] 2018-04-25 07:32
The distribution shouldn't be an input, as the init script does not affect the daemon itself, but only individual builds in it. The `init.d` scripts of the custom distribution should be executed and I remember that working. Can you check whether this broke recently? Maybe we're missing some test coverage here.

**Comment by oehme** [comment] 2018-04-25 07:36
Duplicate of https://github.com/gradle/gradle/issues/5090

**Closed by oehme** 2018-04-25 07:36 UTC
Labels: a:bug, affects-version:4.7, from:contributor, in:core
