### ISSUE TITLE
Property is wrongly queried before content is available when using configuration cache

### ISSUE THREAD

**Issue by SgtSilvio** [gradle/gradle#30732] opened 2024-09-29 16:21 UTC
### Current Behavior

Let `foo` be a task with an output file property `output`, so that `fileProvider = foo.flatMap { it.output }`.
Let `bar` be a task with a string input property and set this property to `fileProvider.map { it.asFile.readText() }`.
Let `fileProperty` be a file property (for example in an extension) and set it to `fileProvider`.
Let `baz` be a task with a string input property and set this property to `fileProperty.map { it.asFile.readText() }`.
Both `bar` and `baz` tasks are basically the same, the only difference is how the string input property is configured.

When using the configuration cache, task `bar` works: the map function on the `fileProvider` is not called during the configuration phase because the content is only available after task `foo` has executed.
When using the configuration cache, task `baz` fails: the map function on the `fileProperty` is wrongly called during the configuration phase. As the file will only be present after task `foo` has run, this results in a file not found exception. Although the configuration fails, a (corrupt) configuration cache entry is stored.

### Expected Behavior

Task `baz` should behave the same as task `bar`. Assigning the `fileProvider` to an additional property should not make a difference.

### Self-contained Reproducer Project

https://github.com/SgtSilvio/gradle-reproducers/tree/main/wrongly-queried-property-with-configuration-cache

### Gradle version

8.10.2

**Comment by ov7a** [comment] 2024-10-02 13:24
This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/27842

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

Also might related to:
* https://github.com/gradle/gradle/issues/26340
* https://github.com/gradle/gradle/issues/26363
* https://github.com/gradle/gradle/issues/25645

**Closed by ov7a** 2024-10-02 13:24 UTC
Labels: a:bug, to-triage
