### ISSUE TITLE
Add lazy property style APIs for `project.version` and `project.group`

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#15088] opened 2020-11-06 23:54 UTC
Add lazy property style APIs for `project.version` and `project.group`. We are trying to clean up our tasks to be fully lazy, but we find that use of `project.version` and `project.group` causes us issues.

### Expected Behavior
Add `project.versionProperty` and `project.groupProperty` 

### Current Behavior
APIs don't exist

### Context
We are trying to move the calculation of our project version and group to be lazy (done at task execution time)

**Comment by lacasseio** [comment] 2020-11-07 00:34
In theory, both properties are toString() lazy, meaning you can set any object that would and will only be evaluated when used within Gradle by calling toString(). Mapping them to a Provider API is just a matter of wrapping the toString() call inside a Callable passed to the ProviderFactory#provider(Callable). It's not a 100% convenient but it works in the majority of. cases.

Another aspect important to mention for context is the usefulness of having both of these properties on the Project object. There was some discussion where these properties belong to the publishing extension. However there is some hesitation given how deeply they are wire within Gradle and its usage within the plugins. I'm not aware of any decision on how to move forward. The Gradle team will have to make a call.

**Comment by ajoberstar** [comment] 2022-02-15 00:47
I believe this is a duplicate of #13672.

**Comment by wolfs** [comment] 2022-03-14 12:01
Thank you for your interest in Gradle!

This issue is a duplicate of #13672 and will be closed as such.

**Closed by wolfs** 2022-03-14 12:01 UTC
Labels: a:feature, in:configuration-model, in:provider-api, p:lazy-migration
