### ISSUE TITLE
Gradle toolchain does not unpack jdk after download when using Alpine

### ISSUE THREAD

**Issue by aleksanderlech** [gradle/gradle#27214] opened 2023-11-30 09:47 UTC
### Current Behavior

Hello,

I am trying to use the javaToolchains in one of my projects that require JDK8 and I noticed that Gradle successfully downloads an expected JDK archive into /root/.gradle/jdks/ but does not extract it and therefore later fails during running the desired java process.

The build fails with the following root Exception:
```
Caused by: java.io.IOException: Cannot run program "/root/.gradle/jdks/OpenJDK8U-jdk_x64_linux_hotspot_8u392b08/jdk8u392-b08/bin/java" (in directory "/root/.gradle/.tmp/tmp-jvm15478520384333416046probe"): error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1170)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
```

These are the files that I see after the build fails:

```
/prj # ls /root/.gradle/jdks/ -l
total 100600
-rw-r--r--    1 root     root     103005424 Nov 30 09:33 OpenJDK8U-jdk_x64_linux_hotspot_8u392b08.tar.gz
-rw-r--r--    1 root     root            17 Nov 30 09:33 OpenJDK8U-jdk_x64_linux_hotspot_8u392b08.tar.gz.lock
```

I am attaching the full debug.log output for further details. I would be grateful for support.
[debug.log](https://github.com/gradle/gradle/files/13511119/debug.log)

### Expected Behavior

Gradle toolchain successfully downloads matching JDK, unpacks it and uses it to build.

### Steps to Reproduce

Consider the following project: 

[gradle-jdk-download-issue-poc.zip](https://github.com/gradle/gradle/files/13556834/gradle-jdk-download-issue-poc.zip)

settings.gradle
```
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.7.0'
}
rootProject.name = 'test-project'
```

build.gradle (fragment)
```
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}
```

1) Unpack the sample project
2) CD into the project root
3) Run the following command

```
docker run -it --rm  -v $PWD:/prj   eclipse-temurin:21-jdk-alpine bash
```

And within the docker container run the following:

```
cd /prj
./gradlew build
```

### Gradle version

8.4, 8.5

### Your Environment (optional)

Docker version 20.10.7, build f0df350
Docker image: eclipse-temurin:21-jdk-alpine

NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.18.5
PRETTY_NAME="Alpine Linux v3.18"

**Comment by aleksanderlech** [comment] 2023-12-05 07:05
Hello,

I understand, I will try to come up by something soon. Meanwhile answering the other concerns:

1. Tested with the newest foojay resolver plugin (0.7.0) and the issue still persists
2. Gradle/Java has access to both /prj and /root (these are just docker build image mounts). It is able to access the /root/.gradle/jdks as it is able to download JDK into this directory, it only fails when it comes to unpacking.
3. Additional observation: tried with JDK9 and 15 and have the same result

**Comment by aleksanderlech** [comment] 2023-12-05 08:10
Hello, attaching the sample project and updated the reproduce steps. User has a write access to this directory as it is able to download the bundle there. I updated to the newest Foojay plugin as well with the same result (0.7.0).

After the investigation it turns out this problem only occurs on Alpine.

**Comment by ov7a** [comment] 2023-12-05 13:18
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/24300

Please add your use case and 👍 to that issue.

***

It's a known issue and [documented](https://docs.gradle.org/current/userguide/toolchains.html#sec:limitations) issue with Alpine containers. Consider switching to another container type.

**Closed by ov7a** 2023-12-05 13:18 UTC
Labels: a:bug, to-triage
