### ISSUE TITLE
Progress indicator is not shown properly and messes up console output

### ISSUE THREAD

**Issue by papanito** [gradle/gradle#3219] opened 2017-10-17 15:15 UTC
Since latest update to 4.2.1 on my Windows environment the "progress" indicator (0% EXECUTING [5s]) is not properly displayed and instead is written out to the console every second. This behavior can be observed when calling Gradle from a standard Command Prompt and from Powershell.

### Expected Behavior
Progress indicator shall be shown once and not mess up the console.

### Current Behavior
Each update of the progress indicator prints out a string every second as shown below:
```←[2A←[1B←[1m> Starting Daemon←[m←[17D←[1B←[1A←[1m> Starting Daemon←[m←[17D←[1B←[1A←[1m> Starting Daemon←[m←[17D←[1B←[1A←[1m> Starting Daemon←[m←[17D←[1B←[1A←[1m> Starting Daemon←[m←[17D←[1B←[1A←[1m> Startin
g Daemon←[m←[17D←[1B←[1A←[1m> Starting Daemon←[m←[17D←[1B←[1A←[1m> Starting Daemon←[m←[17D←[1B←[1A←[1m> Starting Daemon←[m←[17D←[1B←[1A←[1m> Starting Daemon←[m←[17D←[1B←[1A←[1m> Starting Daemon←[m←[17D←[1B←
[1A←[1m> Starting Daemon←[m←[17D←[1B←[1A←[1m> Starting Daemon←[m←[17D←[1B←[1A←[1m> Starting Daemon←[m←[17D←[1B←[1A←[1m> Starting Daemon←[m←[17D←[1B←[1A←[1m> Starting Daemon←[m←[17D←[1B←[1A←[1m> Starting Dae
mon←[m←[17D←[1B←[1A←[1m> Starting Daemon←[m←[17D←[1B←[1A←[1m> Starting Daemon←[m←[17D←[1B←[1A←[1m> Starting Daemon←[m←[17D←[1B←[1A←[1m> Starting Daemon←[m←[17D←[1B←[1A←[1m> Starting Daemon←[m←[17D←[1B←[1A←[
1m> Starting Daemon←[m←[17D←[1B←[1A←[1m> Starting Daemon←[m←[17D←[1B←[1A←[1m> Starting Daemon←[m←[17D←[1B←[1A←[1m> Starting Daemon←[m←[17D←[1B←[1A←[1m> Starting Daemon←[m←[17D←[1B←[1A←[1m> Starting Daemon←[
m←[17D←[1B←[1A←[1m> Starting Daemon←[m←[17D←[1B←[1A←[1m> Starting Daemon←[m←[17D←[1B←[1A←[
```

### Context
I just try to execute a build script with `gradle build`

### Steps to Reproduce (for bugs)
https://github.com/papanito/packer-vagrant/blob/master/build.gradle

### Your Environment
```
PS D:\Workspaces\> gradle --version
------------------------------------------------------------
Gradle 4.2.1
------------------------------------------------------------

Build time:   2017-10-02 15:36:21 UTC
Revision:     a88ebd6be7840c2e59ae4782eb0f27fbe3405ddf

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
OS:           Windows 7 6.1 amd64
```

**Comment by bmuschko** [comment] 2017-10-17 21:07
Thanks for reporting. Was this working for you properly with Gradle 4.1?

**Comment by blindpirate** [comment] 2017-10-18 00:36
And a workaround can be found in #3128.

**Comment by papanito** [comment] 2017-10-18 05:56
@bmuschko: Can't tell as I was using an older version of gradle.
 @blindpirate: Thanks, workaround works well

**Comment by oehme** [comment] 2017-10-19 16:46
Duplicate of #3128

**Closed by oehme** 2017-10-19 16:46 UTC
Labels: a:bug, from:contributor, in:cli
