### ISSUE TITLE
Gradle daemon binds to unavailable address

### ISSUE THREAD

**Issue by evik42** [gradle/gradle#14528] opened 2020-09-16 19:55 UTC
### Expected Behavior
Bind to the detected available address and IP version, send the correct information to clients.

### Current Behavior
The daemon identified /127.0.0.1 as unreachable but /0:0:0:0:0:0:0:1 as an available loopback address. Then it logged that it is listening on 127.0.0.1 and that is what will be sent to clients.
```
2020-09-16T16:21:41.348+0200 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding IP addresses for network interface Software Loopback Interface 1
2020-09-16T16:21:41.352+0200 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Is this a loopback interface? true
2020-09-16T16:21:42.294+0200 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Ignoring unreachable local address on loopback interface /127.0.0.1
2020-09-16T16:21:42.295+0200 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding loopback address /0:0:0:0:0:0:0:1
...
2020-09-16T16:21:42.752+0200 [DEBUG] [org.gradle.internal.remote.internal.inet.TcpIncomingConnector] Listening on [e43ecb9d-8168-4589-992c-a3e2c7ff4014 port:53556, addresses:[localhost/127.0.0.1]].
2020-09-16T16:21:42.758+0200 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] Daemon starting at: Wed Sep 16 16:21:42 CEST 2020, with address: [e43ecb9d-8168-4589-992c-a3e2c7ff4014 port:53556, addresses:[localhost/127.0.0.1]]
2020-09-16T16:21:42.758+0200 [INFO] [org.gradle.launcher.daemon.server.DaemonRegistryUpdater] Advertising the daemon address to the clients: [e43ecb9d-8168-4589-992c-a3e2c7ff4014 port:53556, addresses:[localhost/127.0.0.1]]
...
2020-09-16T16:21:42.770+0200 [LIFECYCLE] [org.gradle.launcher.daemon.server.Daemon] Daemon server started.
2020-09-16T16:21:42.771+0200 [DEBUG] [org.gradle.launcher.daemon.bootstrap.DaemonStartupCommunication] Completed writing the daemon greeting. Closing streams...
2020-09-16T16:21:42.773+0200 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] stopOnExpiration() called on daemon
2020-09-16T16:21:42.774+0200 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] awaitExpiration() called on daemon
2020-09-16T16:21:42.774+0200 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] daemon is running. Sleeping until state changes.
2020-09-16T16:21:42.783+0200 [ERROR] [org.gradle.internal.remote.internal.inet.TcpIncomingConnector] Cannot accept connection from remote address /127.0.0.1.
```

Omitted the logs for all the other interfaces as I have a few, but all of them were identified correctly as not being loopback interfaces.

### Context
The daemon could not communicate with gradle so a new daemon was started and it is repeated in a loop until memory is exhausted. Gradle identifies the running daemons as busy.

### Steps to Reproduce 
I changed which of my network connection is shared via the mobile hotspot and that might have caused the loopback interface to not have the IPv4 address working correctly. Restart of Windows fixed the issue.
The bug is that the daemon identified that the address is not working and still tried to communicate via it instead of using the IPv6 one.

### Your Environment
Windows 10 Pro - 20H2 (19042.508), Amazon Corretto JDK 11.0.8.10.1 64bit
gradle-wrapper.properties:
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions-snapshots/gradle-6.7-20200812220226+0000-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

**Comment by XMitja** [comment] 2020-10-13 06:45
confirmed, when mobile hotspot is running on my win10 it prevents ping to 127.0.0.1 while ping to ::1 works (even though TCP connects normally on both localhosts), this makes gradle daemon unwilling to accept connections from 127.0.0.1
gradlew --stop to fail too 

 > gradlew --stop
 Stopping Daemon(s)
 Unable to stop one of the daemons. The daemon may have crashed.
 Unable to stop one of the daemons. The daemon may have crashed

6.8-20201012220053 is still bugged while 6.1.1 works

**Comment by XMitja** [comment] 2020-10-13 11:59
the problem seems to be partially caused by the isReachable check in this commit:
https://github.com/gradle/gradle/commit/490d43b1dab537f1ab5df8974b14329b8da2d397
maybe it's unnecessary to check if a loopback address is reachable? InetAdress.isReachable is not so reliable anyway

**Comment by Mikanoshi** [comment] 2020-11-09 16:59
Is this going to be fixed? Every version of gradle daemon since 6.4.1 refuses to work if 127.0.0.1 seems unavailable.
Android Studio starts daemon, cannot connect to it, starts another one in a couple of seconds, and repeats this forever!
Adding `-Djava.net.preferIPv4Stack=false -Djava.net.preferIPv6Addresses=true` to vmoptions or to org.gradle.jvmargs does not work, Android Studio just ignores all -D params and replaces them with some default ones. So no way to switch to IPv6 loopback.

**Comment by XMitja** [comment] 2020-11-09 17:53
yeah I just rolled my own gradle with isReachable check reverted, works fine now
[a.txt](https://github.com/gradle/gradle/files/5512384/a.txt)

**Comment by nomis** [comment] 2020-11-23 11:34
I had this problem last week but it has now gone away, on Windows 10 (1909, 18363.1139) with the Sophos virus installed.

Java was unable to ping 127.0.0.1 (Wireshark shows echo requests with no echo response). Other apps were not affected and it was possible to ping ::1. A reboot did not fix the problem. The firewall is configured to allow echo requests/responses.

Some reports of problems pinging localhost claim an issue with the `hosts` file, but this is most likely to be a result of `localhost` resolving to ::1 while an application is listening on 127.0.0.1. My `hosts` file does not contain entries for `localhost`.

From reading the code, it's not clear why Gradle considers 127.0.0.1 unusable and the decides that it's listening on 127.0.0.1, it looks like it should use ::1 consistently in this scenario.

**Comment by adultmalehuman** [comment] 2020-12-13 19:00
Same problem here when running on Windows 10. My build starts normally, then an error message in the console output about 'Cannot accept connection from remote address /127.0.0.1', then the 'test' task just hangs and eventually times out and fails the build process.

```
> Task :app-springboot:startScripts UP-TO-DATE
> Task :app-springboot:distTar UP-TO-DATE
> Task :app-springboot:distZip UP-TO-DATE
> Task :app-springboot:assemble UP-TO-DATE
> Task :app-springboot:compileTestJava UP-TO-DATE
> Task :app-springboot:processTestResources NO-SOURCE
> Task :app-springboot:testClasses UP-TO-DATE
Cannot accept connection from remote address /127.0.0.1.
> Task :app-springboot:test
```

This was the final output in the console:
```
Execution failed for task ':app-springboot:test'.
> Unable to connect to the child process 'Gradle Test Executor 5'.
  It is likely that the child process have crashed - please find the stack trace in the build log.
  This exception might occur when the build machine is extremely loaded.
  The connection attempt hit a timeout after 120.0 seconds (last known process state: STARTED, running: true).
```

I tried downgrading as far back as Gradle 6.3, but they all seem to have the same problem. Current version as I write this is Gradle 6.7.1. I'm using Java 8 JDK.

**Comment by icnahom** [comment] 2021-02-06 09:30
So I can't connect my device wirelessly and debug my app now? 
Please fix this.

**Comment by HenryPirot** [comment] 2021-03-08 06:01
Is there any way to fix this? We can't downgrade Gradle if we use the new Android Studio version.

**Comment by NotNotMarshall** [comment] 2021-03-12 12:01
> Is there any way to fix this? We can't downgrade Gradle if we use the new Android Studio version.

Happens with me too, the only option I found for now is to downgrade to Gradle 6.1.1 or lower.

**Comment by NotNotMarshall** [comment] 2021-03-12 12:02
> confirmed, when mobile hotspot is running on my win10 it prevents ping to 127.0.0.1 while ping to ::1 works (even though TCP connects normally on both localhosts), this makes gradle daemon unwilling to accept connections from 127.0.0.1
> gradlew --stop will fail too
> 
> > gradlew --stop
> > Stopping Daemon(s)
> > Unable to stop one of the daemons. The daemon may have crashed.
> > Unable to stop one of the daemons. The daemon may have crashed
> 
> 6.8-20201012220053 is still bugged while 6.1.1 works

For whoever is looking for a dirty fix, this is one for now.

**Comment by NotNotMarshall** [comment] 2021-03-12 12:07
The only solution for now is to either:
1. Downgrade to Gradle 6.1.1.
2. Do not use a WiFi hotspot on Windows 10.
3. Do not start a program which listens on the localhost address of your PC, e.g. a Node or an Apache webserver, or whatever that binds to your loopback address.
4. Set Android Studio to use ipv6.
5. If you're sharing your network adapter's connection with another adapter, or you're bridging 2 network adapter connections (like I do), give them a static IP outside the range of your default gateway. For example if your main network's gateway is 192.168.1.x then when you Bridge or Share connections, set the Receiver adapter (the one which the internet is shared to) to use a static IP in a range like 192.168.0.x (trust me it will work).

**Comment by Mikanoshi** [comment] 2021-03-12 12:10
You can downgrade to 6.4, first broken version is 6.4.1.

**Comment by maxxx** [comment] 2021-06-11 08:16
Confirm this. The minimal Gradle wrapper version for the current Android Studio is 6.5 so can't downgrade. preferIPv4Stack=true option doesn't help

**Comment by mlopatkin** [comment] 2021-07-23 16:12
Could you please check Gradle 7+? There were changes in this area, in particular, the reachability check was removed.

**Comment by nikitph** [comment] 2021-08-04 05:21
unreachable local address on loopback interface /127.0.0.1

Is there an update on this?

**Comment by mlopatkin** [comment] 2021-08-04 08:13
@nikitph could you please share daemon logs (usually located in `$GRADLE_USER_HOME/daemon/<gradle_version>/daemon-<PID>.out.log` where `<PID>` is a PID of the daemon process)?

**Comment by donat** [comment] 2021-09-20 14:32
So according to @nomis the problem was solved in a recent Windows update.

> I had this problem last week but it has now gone away, on Windows 10 (1909, 18363.1139)

Since there has been no recent activity on this issue I'm closing it now. I'll reopen it if required.

**Closed by donat** 2021-09-20 14:32 UTC
Labels: in:daemon, a:bug

**Comment by vishnuagbly** [comment] 2021-12-23 17:24
I'm having the same issue.

**Comment by shahoob** [comment] 2022-05-01 11:11
any updates?
i'm having the same issue as well

**Comment by FMorschel** [comment] 2024-05-09 03:42
> After a more recent Windows update the issue has reappeared. It looks like gradle is using some undocumented WinAPI behavior.
> 
> @donat please reopen.

Reopened more than two years ago, has any progress towards solving this been made? I've seen this issue with hotspot or when my VPN is on.

**Comment by Duna** [comment] 2024-10-01 11:45
Just disable the firewall and then works
