### ISSUE TITLE
Unable to get a Build scoped service injected in a settings plugin written as a precompiled Kotlin script

### ISSUE THREAD

**Issue by jbartok** [gradle/gradle#21837] opened 2022-09-02 08:38 UTC
When trying to write a Toolchain Download SPI settings plugin in Kotlin, getting the registry service injected, which is a build scoped service (recently introduced by https://github.com/gradle/gradle/pull/21082), doesn't work.

For reference, the precompiled script used was:
```
import org.gradle.api.internal.SettingsInternal
import org.gradle.internal.reflect.Instantiator
import java.net.URI
import java.util.Optional

settings.plugins.apply("jdk-toolchains")

val objects = (settings as SettingsInternal).services.get(Instantiator::class.java)
val registry = objects.newInstance(Registry::class.java).registry
registry.register("fancy-jdk-repo", MyToolchainRepository::class)

abstract class Registry @Inject constructor(
    val registry: JavaToolchainRepositoryRegistry
)

abstract class MyToolchainRepository : JavaToolchainRepository {
    override fun toUri(spec: JavaToolchainSpec): Optional<URI> {
        return Optional.empty<URI>()
    }

    override fun getToolchainSpecCompatibility(): JavaToolchainSpecVersion {
        return JavaToolchainSpecVersion.V1
    }
}
```

**Comment by jbartok** [comment] 2022-09-02 09:00
Note to me, try:
- inline Kotlin
- inline Groovy
- precompiled Groovy

**Comment by ljacomet** [comment] 2022-09-06 08:31
See possible workaround in #14171

**Comment by eskatos** [comment] 2022-09-16 14:37
The workaround of using an inline plugin class works.

Note that the snippet in the issue description is using internals.

Here's a minimized reproducer, the problem is present in a simple `settings.gradle.kts` script (not a precompiled one).

```kotlin
// settings.gradle.kts
plugins {
    id("jvm-toolchains")
}

abstract class Registry @Inject constructor(
    val registry: JavaToolchainRepositoryRegistry
)

val objects = (settings as org.gradle.api.internal.SettingsInternal).services.get(ObjectFactory::class.java)
val registry = objects.newInstance(Registry::class.java).registry
```

It fails with:

```
FAILURE: Build failed with an exception.

* Where:
Settings file 'settings.gradle.kts' line: 10

* What went wrong:
Could not create an instance of type Settings_gradle$Registry.
> Unable to determine constructor argument #1: missing parameter of type JavaToolchainRepositoryRegistry, or no service of type JavaToolchainRepositoryRegistry.
```

The same in Groovy also fails:

```groovy
// settings.gradle
plugins {
    id("jvm-toolchains")
}

abstract class Registry {
    @Inject abstract JavaToolchainRepositoryRegistry getRegistry()
}

def objects = (settings as org.gradle.api.internal.SettingsInternal).services.get(ObjectFactory)
def registry = objects.newInstance(Registry).registry
```

with:

```
FAILURE: Build failed with an exception.

* Where:
Settings file '/home/paul/src/local/gradle/gradle-21837/settings.gradle' line: 10

* What went wrong:
A problem occurred evaluating settings 'gradle-21837'.
> No service of type JavaToolchainRepositoryRegistry available in DaemonServices.
```

The error message is slightly different but the behaviour is the same.

----

For not using internals it would need access to an `ObjectFactory` from `Settings`. Which is currently unsupported, see:
* https://github.com/gradle/gradle/issues/14171

I think this issue is a duplicate of https://github.com/gradle/gradle/issues/14171 in the sense that in order to implement the user facing value of https://github.com/gradle/gradle/issues/14171 we'd need to figure out why such a service can't be looked up at this point and fix it.

**Comment by eskatos** [comment] 2022-09-16 14:38
Closing as a duplicate of https://github.com/gradle/gradle/issues/14171

**Closed by eskatos** 2022-09-16 14:38 UTC
Labels: a:feature, @support, in:precompiled-script-plugin
