### ISSUE TITLE
major bug: gradle 4.x.x does not compile classes in big package directory tree "sourceSet has no files"

### ISSUE THREAD

**Issue by davidghiurco** [gradle/gradle#5321] opened 2018-05-08 20:18 UTC
### Expected Behavior
when I run gradle compileJava, I expect my java classes to be compiled and put into the build directory.

### Current Behavior
Using gradle 4.x.x, when I run gradle compileJava with sourcesets that have a long directory tree, (note that the directory structure is 100% default compliant, meaning, sources in src/main/java, tests in src/test/java for each module) gradle says "Skipping task ':my-module:compileJava' as it has no source files and no previous output files."

This happens when the source files are in long directory trees. For example:
Folder containing java sourcces: "src/main/java/com/this/is/a/very/long/directory/tree
Folder containing java tests: "src/test/java/com/this/is/a/very/long/directory/tree

Note that the long directory tree follows the packaging scheme at my organization (I'm not just putting stuff in a lot of folders because I feel like it. It is necessary.)

### Context
I was unable to compile my application and run unit tests for the simple reason that my packaging scheme has a lot of information. This was pretty frustrating because I read the documentation in depth and was told that anything under the default sourceSet "src/main/java" will be picked up. This was not true.

I finally went against my better judgement which told me to trust the documentation, and i manually set the sourceset to from "src/main/java" to "src/main/java/com/this/is/a/very/long/directory/tree. I also tried setting the sourceSet directory to something like "src/main/java/com/this/is/a/very/long/" and that also worked. So removing a couple of directories from the sourceSet spec was fine, but once I removed all the sub-packages under "src/main/java", I was no longer able to compile my classes because gradle would find no sourceSet

### Steps to Reproduce (for bugs)
Attaching a sample project that mimics my real project in terms of directory structure. 

[gradle-multip-project-example.zip](https://github.com/gradle/gradle/files/1985491/gradle-multip-project-example.zip)

Just run 

$ gradle compileJava -i

with either gradle 4.7 or gradle 4.5.1 and the resulting task will not compile anything, as I've said above.

you can also cd into a particular module and run gradle compileJava -i just on that module, and the issue will persist.

### Your Environment
I experienced this issue first with the latest currently available version of Gradle (4.7). I then tried downgrading to 4.5.1, issue persisted. Finally I downgraded to 3.5.1 and it worked properly. I will be using this release until this issue is fixed - it is extremely inconvenient to have to set the sourceSet directory depending on the packaging scheme, not to mention it is incorrect behavior according to the documentation.

My suspicion is that the filesystem parser gives up after a pre-defined number of directory recursions after not finding any source files. That was probably meant to be an optimization, but in the words of a wise man "Premature optimization is the root of all evil."

**Comment by davidghiurco** [comment] 2018-05-09 14:15
@big-guy good catch You are correct, since when I change the directory structure to just be something bogous, without the package structure from my organization (which must have cvs), it works as expected.

This is confirmed by the fact that if I do:
`
sourceSets {
 main.java { srcDirs "src/main/java/com/here/cvs"}
}
`
then the sourceSet will be included as expected. , but if it's only "src/main/java/com/here" then sure enough, it fails :) 

Feel free to update the issue description to accurately reflect the correct cause, if you think it's necessary

**Comment by big-guy** [comment] 2018-05-09 15:28
@oehme I don't think we changed anything intentionally with this in mind, but I'm guessing it has something to do with all of the changes made around snapshotting that may have caused us to incorporate the default excludes everywhere.

**Comment by oehme** [comment] 2018-05-09 16:26
Closing as duplicate of https://github.com/gradle/gradle/issues/2986. Let's continue the discussion there.

**Closed by oehme** 2018-05-09 16:26 UTC

**Comment by davidghiurco** [comment] 2018-05-09 16:28
I will rename the issue description myself, so it's accurate for book-keeping purposes
