### ISSUE TITLE
`providers::gradleProperties` should check current project `gradle.properties` and not only CLI and root file

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [gradle/gradle#24296] opened 2023-03-11 12:20 UTC
Due to https://github.com/gradle/gradle/issues/21485, `providers::gradleProperties` is not enough to replace a way to override root `gradle.properties` properties on a specific subproject.

### Expected Behavior
`providers::gradleProperties` should have similar behavior to `properties(...)`

### Current Behavior
It only gets CLI properties and root `gradle.properties` properties

### Context
I need to override a root property on a specific subproject.

**Comment by JavierSegoviaCordoba** [comment] 2023-03-11 12:32
Currently I have to manually do:

```kotlin
private fun Project.getSemverProperty(semverProperty: SemverProperty): Provider<String> =
    if (isRootProject) {
        providers.gradleProperty(semverProperty.key)
    } else {
        val isOnStartParameter: Boolean =
            gradle.startParameter.projectProperties.containsKey(semverProperty.key)
        if (isOnStartParameter) {
            providers.systemProperty(semverProperty.key)
        } else {
            val gradlePropertiesFile = projectDir.resolve("gradle.properties")
            if (gradlePropertiesFile.exists()) {
                val stream = gradlePropertiesFile.inputStream()
                val properties = Properties().apply { stream.use { load(it) } }
                val property: String? = properties.getProperty(semverProperty.key)
                provider { property }
            } else {
                providers.gradleProperty(semverProperty.key)
            }
        }
    }
```

**Comment by ov7a** [comment] 2023-03-17 10:16
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed, response time may vary.

***

This is either should be documented better because provider service is root-project scoped (it only sees root project related properties) OR implemented as a feature (the service should be scoped for subproject).

**Comment by JavierSegoviaCordoba** [comment] 2023-03-17 10:30
AFAIK this behavior is something new and it was not working in that way in previous versions.

After talking with @Vampire on Slack, he has seen this change too.

**Comment by Vampire** [comment] 2023-03-17 10:38
No, I did not see a change.
But it is not following the documented logic that was and is followed by the old way to access Gradle properties.
https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties defines:
> The final configuration taken into account by Gradle is a combination of all Gradle properties set on the command line and your gradle.properties files. If an option is configured in multiple locations, the first one found in any of these locations wins:

> - command line, as set using -D.

> - gradle.properties in [GRADLE_USER_HOME](https://docs.gradle.org/current/userguide/directory_layout.html#dir:gradle_user_home) directory.

> - gradle.properties in the project’s directory, then its parent project’s directory up to the build’s root directory.

> - gradle.properties in Gradle installation directory.

The third bullet-point is, what is not properly followed by the new `providers.gradleProperty`.

And there is not really a work-around, as anything that uses `gradleProperty` suffers from this.
So if some 3rd party plugin uses `gradleProperty` to get a property, you cannot work-around this issue.

**Comment by 6hundreds** [comment] 2023-03-17 11:20
Duplicate of https://github.com/gradle/gradle/issues/23572

**Closed** 2023-05-26 12:47 UTC
Labels: a:feature, in:configuration-model, in:configuration-cache, :wave: team-triage, has:workaround
