### ISSUE TITLE
stackoverflow for `./gradlew dependencies`

### ISSUE THREAD

**Issue by nkiesel** [gradle/gradle#10332] opened 2019-08-21 20:09 UTC
Hi,

I get a stackoverflow when running `./gradlew dependencies` on a minimal setup.  This uses a private repo.  The project to reproduce including the resulting log file showing that stack trace is attached.

This is running on Debian Linux using Java 8 and Gradle 5.6.  I saw the same problem with other Gradle releases.

[stackoverflow3.zip](https://github.com/gradle/gradle/files/3527105/stackoverflow3.zip)

**Comment by big-guy** [comment] 2019-08-21 23:03
Could you provide a copy of http://msjenkins:8081/artifactory/ext-release-local/org/opensaml/opensaml/2.6.5/opensaml-2.6.5.pom?

**Comment by big-guy** [comment] 2019-08-21 23:05
Could you also try running with `--stacktrace` to see if you get a stacktrace?

**Comment by nkiesel** [comment] 2019-08-22 18:58
Attached is a version of the same project with the pom file and the stacktrace log included.

[stackoverflow3a.zip](https://github.com/gradle/gradle/files/3531531/stackoverflow3a.zip)

**Comment by big-guy** [comment] 2019-09-04 22:16
I think this is a dupe of https://github.com/gradle/gradle/issues/1084.  The POM you included references itself as a parent.  I'm not sure if there's anything that can be done at the build level if that's a valid POM.  /cc @ljacomet

**Closed by big-guy** 2019-09-04 22:16 UTC
Labels: a:bug, from:contributor

**Comment by ljacomet** [comment] 2019-09-05 06:54
We may be able to do something to detect such cases in Gradle, so that we simply ignore `parent` information when it matches current POM coordinates.

However what is concerning to me is that the provided POM does not match the one found at https://build.shibboleth.net/nexus/content/groups/public/org/opensaml/opensaml/2.6.5/opensaml-2.6.5.pom.

**Comment by nkiesel** [comment] 2019-09-06 17:24
Yes, I share the concern about the POM discrepancy. I will investigate internally how we ended up with this file.

Detecting this misconfiguration (or generally circles in the parent graph) would still be nice.
