### ISSUE TITLE
[Gradle 5.3] Cannot convert relative path . to an absolute file

### ISSUE THREAD

**Issue by MaximPestryakov** [gradle/gradle#8840] opened 2019-03-22 12:04 UTC
### Expected Behavior
```
➜  gradle-issue gradle wrapper --distribution-type=all --gradle-version=5.2.1

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
➜  gradle-issue ./gradlew help
Hello World

> Task :help

Welcome to Gradle 5.2.1.

To run a build, run gradlew <task> ...

To see a list of available tasks, run gradlew tasks

To see a list of command-line options, run gradlew --help

To see more detail about a task, run gradlew help --task <task>

For troubleshooting, visit https://help.gradle.org

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
```

### Current Behavior
```
➜  gradle-issue gradle wrapper --distribution-type=all --gradle-version=5.3

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
➜  gradle-issue ./gradlew help

FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/m.pestryakov/gradle-issue/settings.gradle' line: 1

* What went wrong:
A problem occurred evaluating settings 'gradle-issue'.
> Cannot convert relative path . to an absolute file.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

### Steps to Reproduce (for bugs)

1. Use Gradle 5.3
2. Create settings.gradle:
```
exec {
    commandLine 'echo', 'Hello, World!'
}
```
3. Run any task (for example `./gradlew help`)

**Comment by big-guy** [comment] 2019-03-22 17:10
Thanks @MaximPestryakov - I can reproduce this locally.  As a workaround, you can set `workingDir = rootDir` in your `exec {}`.  

What are you running in the exec? This can potentially make your Gradle build much slower since Gradle needs to fork a process every time you run any task.

**Comment by MaximPestryakov** [comment] 2019-03-22 17:44
I use it to add .githooks folder to git config:
```
exec {
    commandLine 'git', 'config', 'core.hooksPath', '.githooks'
}
```

**Comment by big-guy** [comment] 2019-03-22 17:53
OK, but why do you need to set that every time you run Gradle? IOW, if you run `gradle help`, you're also running that command.  

If this is part of a "developer setup" step, you could move this into a task and it would only run when a developer asked for it.

**Comment by MaximPestryakov** [comment] 2019-03-22 18:04
Yeah, I know that it's evaluates every time 🙃. But I need new developers not to forget to do it...

**Comment by donat** [comment] 2019-03-27 15:12
I've managed to locate the commit that introduced the regression: https://github.com/gradle/gradle/commit/62a84d817e9371358688f2e2f6d2d943c063d336

**Comment by donat** [comment] 2019-03-27 15:59
It seems the refactoring commit ⬆️ passes a different file resolver to `ExecFactory.forContext(...)` which causes the problem. The change is part of a larger refactoring and I don't quite understand the whole picture. @adammurdoch since you made the change, can you please have a quick look?

**Comment by big-guy** [comment] 2019-03-30 05:07
I think this is fixed in https://github.com/gradle/gradle/commit/badc9af8a42d17b7652b2cc13557bc84e76aab3c -- basically, `FileOperations` used to be cast to `ProcessOperations` and we'd use a file resolver relative to rootDir from that.   Now that ProcessOperations is implemented by something else, we were using the wrong FileResolver.

**Closed by big-guy** 2019-03-30 05:07 UTC
Labels: @core, in:core

**Comment by donat** [comment] 2019-04-01 08:30
Thanks, @big-guy for fixing this!
