### ISSUE TITLE
Instant execution fails on Java Compile Task (no source) when there are only kotlin files in src/main/java

### ISSUE THREAD

**Issue by stephanenicolas** [gradle/gradle#11841] opened 2020-01-08 17:24 UTC
Hi there, 

I am working closely with people from Gradle and JetBrains. While testing instant execution for Android projects I found the following bug. 

This is a bug report for 
* Gradle latest nightly: gradle-6.2-20200106230036+0000
* Kotlin versions tested: 1.4.0-dev-74 + latest nightly 1.4.0-dev-589 
* AGP versions used (it should not matter here, the build fails in modules *not* using AGP): 3.5.3, 3.6-rc01, 4.0 alpha 6&7.

The build fails on the second run (both of them are launched using : `-Dorg.gradle.unsafe.instant-execution=true` , so only the second one actually uses instant execution.
The second build fails for all modules that uses both the java-library *and* the kotlin plugin *when* there is no java source files in such modules, but only kotlin source files.

```
> Task :moduleA:compileJava FAILED
> Task :moduleB:compileJava FAILED

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':moduleA:compileJava'.
> no source files
```

The problem should be quite easy to reproduce. I use the command line `./gradlew :module:assembleDebug` on an android app module that uses modules A and B as dependencies. Module A and B are both using the java-library plugin + the kotlin plugin and both have only kotlin source files (stored in src/main/java). They don't use any other plugins, especially *not* the android plugin.
The problem also fully reproduces when calling ``./gradlew :module<A or B>:compileJava`.  A simple mono-module sample should be enough to reproduce the problem.

**Comment by eskatos** [comment] 2020-01-17 11:01
Thanks for the report @stephanenicolas 

I couldn't reproduce with a single project build with just the `java-library` plugin, nor with a project with both the `java-library` and `kotlin-jvm` plugins applied. I then tried a multi-project build with pure Kotlin `:moduleA` and `:moduleB` with an Android library `:moduleC` that depends on the other two without being able to reproduce either.

I properly get the following on both first and second run with instant execution:
```
> Task :moduleB:compileJava NO-SOURCE
> Task :moduleA:compileJava NO-SOURCE
```

I tried latest Gradle 6.2 nightly, Kotlin plugins version `1.3.70-eap-42` and `1.4.0-dev-830`, AGP `4.0.0-alpha08`.

Please find my reproducer attempt here [kotlin-no-java-sources.zip](https://github.com/gradle/gradle/files/4076498/kotlin-no-java-sources.zip)


Could you please try to extract a reproducer from your build?

**Comment by stephanenicolas** [comment] 2020-01-27 22:23
I managed to repro the issue: 
URL : https://github.com/stephanenicolas/bugs-instant-execution/
Commit: f4c3df3fa260398cda9ac2378b7506faf645c475
the problem is when a pure kotlin module has no java source files.

I get the error for 
`./gradlew :app:assembleRelease -Dorg.gradle.unsafe.instant-execution=true`

```
Reusing instant execution cache. This is not guaranteed to work in any way.
> Task :lib1:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lib1:compileJava'.
> no source files
```

**Comment by eskatos** [comment] 2020-01-28 08:17
Thanks @stephanenicolas!
So, the trick to trigger the problem was to put the Kotlin sources into `src/main/java`.

**Comment by stephanenicolas** [comment] 2020-02-03 22:42
Is it something you intend to fix @eskatos ? I am checking with my team and I am not sure we can easily move our code to a different layout (`src/main/java` --> `src/main/kotlin`) as we have some internal tooling that has the path hard-coded apparently.

**Comment by adammurdoch** [comment] 2020-02-03 22:55
@stephanenicolas yes, definitely. We'll fix it soon.

**Comment by stephanenicolas** [comment] 2020-02-03 22:57
Thx @adammurdoch

**Comment by adammurdoch** [comment] 2020-02-04 05:33
This is fixed via https://github.com/gradle/gradle/pull/12113.

**Closed by adammurdoch** 2020-02-04 05:33 UTC
Labels: @instant-execution, a:bug, from:contributor
