### ISSUE TITLE
Maven Publishing that worked with 6.0 does no longer in 6.1

### ISSUE THREAD

**Issue by cdietrich** [gradle/gradle#11862] opened 2020-01-10 07:32 UTC
gradle build fails with 6.1 that was working with 6.0

```
08:13:18  * What went wrong:
08:13:18  Execution failed for task ':org.eclipse.xtext.xbase.lib:generateMetadataFileForLocalMavenRepoPublication'.
08:13:18  > Invalid publication 'LocalMavenRepo':
08:13:18      - Publication only contains dependencies and/or constraints without a version. You need to add minimal version information, publish resolved versions (https://docs.gradle.org/6.1-rc-2/userguide/publishing_maven.html#publishing_maven:resolved_dependencies) or reference a platform (https://docs.gradle.org/6.1-rc-2/userguide/platforms.html)
```

### Expected Behavior

Build still works

### Current Behavior

Build fails

### Context

gradle 6.0 works
https://github.com/eclipse/xtext-lib/tree/cd_gradle60
gradle 6.1.rc2 does not work
https://github.com/eclipse/xtext-lib/tree/cd_gradle61
gradle 6.1 with gradle platform instead of spring deps: works
https://github.com/eclipse/xtext-lib/tree/cd_javaPlatformExperimentsGradle61

so there seems to be a combination of the spring dep mgmt plugin and gradle 6.1 that breaks

(using platform with the maven defined bom seems to work too)
https://github.com/eclipse/xtext-lib/tree/cd_gradle61moreExperiments

### Steps to Reproduce 

clone each of the branches. in the cases we use spring we define the bom in maven so
```
./1-install-bom.sh
./2-gradle-build.sh -x test
```

### Your Environment

Build scan URL: https://scans.gradle.com/s/7ctwjdwq6l7nq

**Comment by cdietrich** [comment] 2020-01-10 07:52
interestingly https://github.com/eclipse/xtext-core/tree/cd_gradle61
does not seem to be affected although we use the spring dependency mgmt plugin there too.

**Comment by ljacomet** [comment] 2020-01-10 08:17
This change was introduced by #11388 in reaction to spring-gradle-plugins/dependency-management-plugin#262

The problem is that the Spring dependency management plugin resorts to POM level manipulation for setting the BOM information. This means that the matching Gradle Module Metadata misses all of that.
Instead of letting users publish invalid Gradle Module Metadata, we decided it was better to be explicit about this issue.

While we try very hard to not make breaking changes in minor versions, in this case it prevents broken metadata to be published which is worse as it can break your consumers.

You have two options:
* Update your project to properly leverage the `java-platform` and other Gradle core features to obtain the same result as with the Spring dependency management plugin - see an example in the linked issue. This will result in the production of correct Gradle Module Metadata.
* Skip the production of Gradle Module Metadata for now - see [the documentation](https://docs.gradle.org/6.0.1/userguide/publishing_gradle_module_metadata.html#sub:disabling-gmm-publication) on how to do this.

**Comment by cdietrich** [comment] 2020-01-10 09:13
thanks. we will look into that. unfortunately buildship/composite builds seems to substitute the artifacts into gradle plugins as well so it fails cause it wont find the bom.

**Comment by cdietrich** [comment] 2020-01-10 09:16
hmmm the issue is independent from buildship. happens with normal composite builds too.
is it intended that parts of the composite are substituted into  plugins as well using a platform?

**Comment by cdietrich** [comment] 2020-01-10 09:16
```
* What went wrong:
A problem occurred configuring project ':xtext-extras'.
> Could not resolve all artifacts for configuration ':xtext-extras:classpath'.
   > Could not find org.eclipse.xtext:xtext-dev-bom:2.21.0-SNAPSHOT.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/eclipse/xtext/xtext-dev-bom/2.21.0-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/org/eclipse/xtext/xtext-dev-bom/2.21.0-SNAPSHOT/xtext-dev-bom-2.21.0-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/org/eclipse/xtext/xtext-dev-bom/2.21.0-SNAPSHOT/xtext-dev-bom-2.21.0-SNAPSHOT.jar
       - https://plugins.gradle.org/m2/org/eclipse/xtext/xtext-dev-bom/2.21.0-SNAPSHOT/maven-metadata.xml
       - https://plugins.gradle.org/m2/org/eclipse/xtext/xtext-dev-bom/2.21.0-SNAPSHOT/xtext-dev-bom-2.21.0-SNAPSHOT.pom
     Required by:
         project :xtext-extras > org.xtext:xtext-gradle-plugin:2.0.8 > project :xtext-lib:org.eclipse.xtend.lib
         project :xtext-extras > org.xtext:xtext-gradle-plugin:2.0.8 > project :xtext-lib:org.eclipse.xtend.lib > project :xtext-lib:org.eclipse.xtext.xbase.lib
         project :xtext-extras > org.xtext:xtext-gradle-plugin:2.0.8 > project :xtext-lib:org.eclipse.xtend.lib > project :xtext-lib:org.eclipse.xtend.lib.macro
```

**Comment by cdietrich** [comment] 2020-01-10 09:34
```
git clone git@github.com:eclipse/xtext-umbrella.git
cd xtext-umbrella
git checkout cd_xtext_issue1644
cd ..
git clone git@github.com:eclipse/xtext-lib.git
cd xtext-lib
git checkout cd_xtext_issue1644
cd ..
git clone git@github.com:eclipse/xtext-core.git
cd xtext-core
git checkout cd_xtext_issue1644
cd ..
cd xtext-umbrella/releng/gradle-composite/
./gradlew generatePrefs
```

**Comment by cdietrich** [comment] 2020-01-10 09:41
when switching to the branch cd_javaPlatformExperiments in xtext-lib it works fine.
but i assume substitution still happens for the plugin, but the bom can be found now as it is part of the composite

**Comment by cdietrich** [comment] 2020-01-10 09:44
could be https://github.com/gradle/gradle/issues/4343

**Comment by ljacomet** [comment] 2020-01-10 10:00
Sorry, but you lost me there 😉 
Substitutions, which is what composite use behind the scene, can effectively apply to all dependency resolution, whether it is for plugin or regular dependencies.

I fell like what you are discussing now is unrelated to the initial report, though caused by attempting to fix the situation.
If that's right, could you open (if relevant) another issue indicating what you expect to happen and what happens?

**Comment by cdietrich** [comment] 2020-01-10 10:01
well i want to have my problem solved but it looks like just using platform does not help / leads to new problems unfortunately

**Comment by ljacomet** [comment] 2020-01-10 10:15
I understand you want it to work. But I admit being lost with what you are trying, tried and changed. Too much context that I miss, so hard to provide further guidance.

**Comment by cdietrich** [comment] 2020-01-10 10:23
i simply switched from spring dependency management to java platform.
now the composite build fails as it tries to substitute modules from one composite into plugins of other parts of the composite. (this seems to be intended)
unfortunately it therefore does not use the repository list of the module it substitutes but the one that it uses the substittute

* my composite
  * build a
     * defines module a
     * uses platform defined (in a local maven repo)
  * build b
     * uses a gradle plugin that has a dependency to a
     * buildscript has no dependency to repo that defines the platform
     * module b (has dependency to a and the build has the platform repo visible too)

**Comment by ljacomet** [comment] 2020-01-10 10:28
The dependency yes, the repositories no. For security reasons, Gradle does not consult repositories defined in dependencies.
So the fix is probably to add the missing repository when the build is used in a composite.

**Comment by cdietrich** [comment] 2020-01-10 10:29
yes that does work. but we have to do some rework as the repo contains way to may stuff

**Comment by ljacomet** [comment] 2020-01-10 10:30
Reminder that Gradle has a feature to limit the scope of a repository with [content filtering](https://docs.gradle.org/6.0.1/userguide/declaring_repositories.html#sec:repository-content-filtering).

**Comment by ljacomet** [comment] 2020-02-18 09:15
Closing as this behaves as desired.

**Closed by ljacomet** 2020-02-18 09:15 UTC
Labels: @jvm, a:regression, from:contributor, in:dependency-management
