### ISSUE TITLE
Gradle 5.0 regression in IncrementalTaskInputs

### ISSUE THREAD

**Issue by staffanf** [gradle/gradle#8374] opened 2019-01-30 17:20 UTC
A Task with IncrementalTaskInputs supplied via a Task.inputs.files fileTree(dir: "somedir", include: 'somefilepattern') fails in 5.0+ due to the dir being sent to the task instead of of the actual files changed.

### Expected Behavior
Same behavior as in gradle 4.10, the change.file in incrementalInputs.outOfDate should be the actual input file changed.

### Current Behavior
In 5.0+ the change.file in the incrementalInputs.outOfDate event contains 'somedir', the path specified as the fileTree dir.

### Context
We have some tasks that used IncrementalTaskInputs that stopped working since we used a fileTree for inputs to filter away version numbers in input file names.

### Steps to Reproduce (for bugs)

```
git clone https://github.com/staffanf/gradle-5.0-incremental-task-inputs-error.git
./gradlew test
```
IncrementalTaskSpec will fail for gradle 5+ and succeed for 4.10

### Your Environment
linux

**Comment by wolfs** [comment] 2019-01-30 21:12
Thank you for reporting. This is a duplicate of https://github.com/gradle/gradle/issues/7732.

Note that directories always have been reported, the difference now is that the root directory is also reported as changed, consistent with the other non-matching directories.

See also https://discuss.gradle.org/t/filetree-as-incremental-task-input-includes-added-directories/18877.

**Closed by wolfs** 2019-01-30 21:12 UTC
Labels: from:contributor, in:incremental-build

**Comment by wolfs** [comment] 2019-01-30 21:19
Duplicate of #7732.

**Comment by staffanf** [comment] 2019-01-31 09:15
@wolfs Ok, I have read through #7732,  #4204 and #4166. I see why there has been a change.
I still do not see a reason why the directory would be reported a changed input to my incremental task, since the name of the directory does not match the include filter of the fileTree.
This is inconsistent with normal tasks.
I updated my tests and added a test for normal tasks that shows this inconsistency, see https://github.com/staffanf/gradle-5.0-incremental-task-inputs-error/commit/0d19e3646d608fa8f974c66719ced21945a1d207

**Comment by staffanf** [comment] 2019-01-31 13:30
@wolfs I looked at this a bit more and I **really** feel that there is a bug here.
If I remove ```assert change.file.isFile()``` in [IncrementalTask.groovy](https://github.com/staffanf/gradle-5.0-incremental-task-inputs-error/blob/master/src/main/groovy/inctaskinputs/error/IncrementalTask.groovy) it will get the root dir as a input on first run in IncrementalTaskSpec.groovy, but the task is UP-TO-DATE on the second execution when I have added sub-directory.
Neither the root dir or the subdirectory should be reported to the task since they do not match the include filter, but just reporting the root dir is not even consistent with the sub-directories.

**Comment by wolfs** [comment] 2019-02-01 11:06
Let's assume you have the following structure:
```
root
\ -- dir
```

So there is only an empty directory in the root directory.

Then you have this behavior for different include patters:

| Pattern        | fileTree().files  | incremental changes  |
|----------------|-------------------|----------------------|
|  `**`          | `dir`             | `root`, `dir`        |
| `root.txt`     | empty             | `root`               |
|  `dir/sub.txt` | `dir`             | `root`, `dir`        |

As you see, it is not the case that the file tree only returns the matching files. It also returns all the directories on the way. The difference between the incremental changes and the return value of `fileTree().files` is that the root directory is always included in the incremental changes.

The table above also explains why the empty subdirectory is ignored for your type of include and the task is up-to-date on the second run.

Does this make things clearer?

**Comment by staffanf** [comment] 2019-02-04 21:24
Hmmm, it's clearer what you mean but I can't see that your table is correct for these patterns.
I created a test matching your table (https://github.com/staffanf/gradle-5.0-incremental-task-inputs-error/commit/557d537c207336e41ade0694d5ae206f88c8ff86) and I don't see the results that you write in your table.
fileTree.files and fileTree.each does not include dirs while fileTree.visit{} seems iterate over them.

Looking at https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/util/PatternFilterable.html I would actually expect your table to be

Pattern | fileTree().files
-- | -- 
** | dir 
root.txt | empty
dir/sub.txt | empty

with regards to fileTree. But the first line does not happen since fileTree.files does not seem to contain dirs.
Run the tests in [FileTreeSpec.groovy](https://github.com/staffanf/gradle-5.0-incremental-task-inputs-error/blob/557d537c207336e41ade0694d5ae206f88c8ff86/src/test/groovy/inctaskinputs/error/FileTreeSpec.groovy) and tell me why I'm wrong.

**Comment by wolfs** [comment] 2019-02-05 07:38
@staffanf Yes, you are right: `fileTree().files` doesn't include the directories, they are only seen when using `fileTree.visit`. That still means that the directories are part of the file tree.

FTR: I am not trying to argue if it is good or bad if the file tree contains directories. I think it would be better if declaring a file tree meant that the implementation only cares about files.

The problem here is that this currently is not the case: The `Copy` task for example uses a file tree as an input and creates empty directories when copying by default. So we can't just remove the empty directories (or directories in general) from the up-to-date checks for file trees. And since they are part of the up-to-date checks we also need to report them for incremental changes. The only difference between 4.x and 5.x is that we now also report the root directory additionally to the other (possibly empty) directories. And that was done to be more consistent when adding an input directory in two different ways (https://github.com/gradle/gradle/issues/4204).

**Comment by staffanf** [comment] 2019-02-06 09:50
I kinda see some of the reasoning behind it but I can't really see in the apidocs that it should be behave this way. 
I'm guessing I will not be the last one thinking it is odd that the dirs are reported when they clearly do not match the input pattern. 

I've rewritten my tasks now to either normal tasks or checking for dirs in the incremental inputs.
I will transition the last IncrementalTasks to using the WorkerAPI or just normal tasks in the future.
