### ISSUE TITLE
Gradle ignores org.gradle.internal.http.socketTimeout, org.gradle.internal.http.connectionTimeout when daemon is set to false (org.gradle.daemon=false)

### ISSUE THREAD

**Issue by pbanka-17** [gradle/gradle#19930] opened 2022-02-16 03:12 UTC
When we are running Gradle with daemon disabled it, errors out with `Read timed out` while downloading Gradle wrapper. Even when we tried by adding `org.gradle.internal.http.socketTimeout` and `org.gradle.internal.http.connectionTimeout` flags it was timing out. 
Only when we ran Gradle with daemon enabled and with the timeout flags set, it worked for us.

Since we are running the builds in CI env, we would probably don't want to run with daemon enabled, but unless we do so we are running into intermittent issue of `Read timed out` while downloading gradle wrapper. Below is the stack trace, 

```
06:13:58  Exception in thread "main" java.io.IOException: Downloading from <internal nexus repo>/nexus/content/repositories/gradle-distributions/gradle-6.8.3-bin.zip failed: timeout
06:13:58  	at org.gradle.wrapper.Download.downloadInternal(Download.java:110)
06:13:58  	at org.gradle.wrapper.Download.download(Download.java:67)
06:13:58  	at org.gradle.wrapper.Install$1.call(Install.java:68)
06:13:58  	at org.gradle.wrapper.Install$1.call(Install.java:48)
06:13:58  	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
06:13:58  	at org.gradle.wrapper.Install.createDist(Install.java:48)
06:13:58  	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
06:13:58  	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
06:13:58  Caused by: java.net.SocketTimeoutException: Read timed out
06:13:58  	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
06:13:58  	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
06:13:58  	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
06:13:58  	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
06:13:58  	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
06:13:58  	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
06:13:58  	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
06:13:58  	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1374)
06:13:58  	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:985)
06:13:58  	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
06:13:58  	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
06:13:58  	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
06:13:58  	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:754)
06:13:58  	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
06:13:58  	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1615)
06:13:58  	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
06:13:58  	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
06:13:58  	at org.gradle.wrapper.Download.downloadInternal(Download.java:87)
```

### Expected Behavior
With daemon disabled, `socketTimeout` and `connectionTimeout` should have been honored and it should have been been able to download Gradle wrapper.

### Current Behavior
Only with daemon enabled and with the timeout flags set, it worked for us.

### Context
We are running the builds in CI env and would probably don't want to run builds with daemon enabled.

### Steps to Reproduce 
Running Gradle builds in CI env, by disabling daemon and not setting `org.gradle.internal.http.socketTimeout, org.gradle.internal.http.connectionTimeout` flags.

### Your Environment
Running Gradle versions 6.8.3 and 7.2

**Comment by ljacomet** [comment] 2022-02-16 09:46
These internal properties might have to be set differently when the wrapper JVM and the Gradle JVM are the same.

Note that the easiest is to use the daemon on CI.

**Comment by dbyron-sf** [comment] 2022-02-16 16:25
Given the code [here for 7.4.0](https://github.com/gradle/gradle/blob/v7.4.0/subprojects/wrapper/src/main/java/org/gradle/wrapper/Download.java#L98-L99) (same for [6.8.3](https://github.com/gradle/gradle/blob/v6.8.3/subprojects/wrapper/src/main/java/org/gradle/wrapper/Download.java#L85-L86), [7.2.0](https://github.com/gradle/gradle/blob/v7.2.0/subprojects/wrapper/src/main/java/org/gradle/wrapper/Download.java#L98-L99) and the [current HEAD of master](https://github.com/gradle/gradle/blob/fea8c70d22452656911c9a3ce7da1ef804665d23/subprojects/wrapper-shared/src/main/java/org/gradle/wrapper/Download.java#L98-L99), aren't the timeouts the wrapper uses to download gradle constant, independent of system properties and whether there's a daemon running or not?

**Comment by ljacomet** [comment] 2022-02-16 16:40
@dbyron-sf You are perfectly right. This is a duplicate of #17575

Closing as such.

**Closed by ljacomet** 2022-02-16 16:40 UTC
Labels: a:bug, in:remoting

**Comment by pbanka-17** [comment] 2022-02-17 06:09
@ljacomet so we are concluding that the wrapper downloader doesn't depend on Gradle daemon in anyway?
I am not sure, why I got such behaviour in our builds.

**Comment by ljacomet** [comment] 2022-02-17 08:32
I have no idea either, but as you can see in the code, the timeout value there is currently hard coded.
