### ISSUE TITLE
Update Exec Task to be compatible with the Provider API

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#24267] opened 2023-03-09 19:30 UTC
I want to set up the Exec task to use Gradle Providers as inputs to configure 

* Environment variables
* System properties

When I try and use providers as inputs, the Exec task will accept them, but it will not correctly compute the values, and will instead just call `toString()` on the provider.

### Example

```kotlin
// build.gradle.kts

val someInputFile = objects.fileProperty()

someInputFile.set(file("build.gradle.kts"))

val myExecTask by tasks.registering(Exec::class) {
    workingDir(projectDir)
    commandLine("echo", "\$SOME_INPUT_FILE")
    // windows
    //commandLine("cmd", "/c", "echo %SOME_INPUT_FILE%")
    environment("SOME_INPUT_FILE", someInputFile.map { it.asFile.invariantSeparatorsPath })
}
```

Expected output:

```
/path/to/my/project/build.gradle.kts
```

### Current Behavior

Actual output shows that the value is not unwrapped.

```
map(property(org.gradle.api.file.RegularFile, fixed(class org.gradle.api.internal.file.DefaultFilePropertyFactory$FixedFile, path/to/my/project/build.gradle.kts)))
```

### Context

Reproduced on Gradle 7.6 and 8.0.2

These issues are related:

* https://github.com/gradle/gradle/issues/11534
* https://github.com/gradle/gradle/issues/15168

### Workaround 

As a workaround I have to compute the property in a `doFirst {}` block. This is unintuitive and confusing.

```kotlin
// build.gradle.kts

val someInputFile = objects.fileProperty()

someInputFile.set(file("build.gradle.kts"))

val myExecTask by tasks.registering(Exec::class) {
    workingDir(projectDir)
    commandLine("cmd", "/c", "echo %SOME_INPUT_FILE%")

    doFirst {
        environment("SOME_INPUT_FILE", someInputFile.get().asFile.invariantSeparatorsPath)
    }
}
```

This produces the correct result

```
/path/to/my/project/build.gradle.kts
```

**Comment by eskatos** [comment] 2023-03-09 19:33
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/12247

Please add your use case and 👍 to that issue.

**Closed by eskatos** 2023-03-09 19:33 UTC
Labels: in:configuration-model, closed:duplicate
