### ISSUE TITLE
publishing is really really slow

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#30682] opened 2024-09-24 14:29 UTC
### Current Behavior

publishing takes ~60 seconds. In general, even when cache's should be hit the publishing part of the step takes ~60 seconds. 

### Expected Behavior

publishing should probably take no more than 10 seconds. I

### Context (optional)

My build was failing to publish and I couldn't understand it, and I looked and found that a whole minute was just CI publishing to github and so I separated the build/publish step. Now it seems that publish takes 2 minutes by itself, I guess it doesn't hit any cache's of the build workflow, even after all the context is created pushing 6 tiny to githubs internal repository jars still takes 60 seconds.

part (most?) of this bug is arguably just to get gradle to give me enough information to diagnose why. The scans aren't really saying why (IMO) that just the publish step takes so long after the configuration and classes have been built.

https://github.com/xenoterracide/spring-app-commons/actions/runs/10868033227

### Self-contained Reproducer Project

Not minimal, but since the main goal here is to provide more information to make the root cause easier to track down, maybe that's a good thing.

https://github.com/xenoterracide/spring-app-commons

at least some of this is almost certainly the lack of lazy configuration regarding versions, and so that version number is changing with every sha for me causing problems.

 cache invalidation because having changing credentials invalidates the configuration cache.

### Gradle version

8.10.1

### Build scan URL (optional)

https://scans.gradle.com/s/dlxt7ooaphzeo

### Your Environment (optional)

```
------------------------------------------------------------
Gradle 8.10.1
------------------------------------------------------------

Build time:    2024-09-09 07:42:56 UTC
Revision:      8716158d3ec8c59e38f87a67f1f311f297b79576

Kotlin:        1.9.24
Groovy:        3.0.22
Ant:           Apache Ant(TM) version 1.10.14 compiled on August 16 2023
Launcher JVM:  21.0.4 (Eclipse Adoptium 21.0.4+7-LTS)
Daemon JVM:    /home/xeno/.asdf/installs/java/temurin-21.0.4+7.0.LTS (no JDK specified, using current Java home)
OS:            Linux 6.6.47-1-MANJARO amd64
```

**Comment by xenoterracide** [comment] 2024-09-26 19:41
> We don't know if it's an environmental issue like GitHub being slow at taking uploads or if it is the publishing tasks doing unreasonable work during action execution.
> Build scans appear to not show uploads in network activity :/

I'm hoping that at the very least the outcome of this ticket is improvements to providing the information required to diagnose this issue. I have confirmed that the publishing is succeeding. At the very least more timings of the publishing tasks and actually showing the network upload speeds would be good.

 I also confirmed that if all task configurations are hit locally `publishToMavenLocal` takes ~10 seconds. However, I do know that `publishToMavenLocal` does not do the exact same thing locally as it does when publishing to a remote server. https://gradle.com/s/qfznakct36srq

In grand total the total upload size is 1.1Mb (presuming no signficant additional data is publish to the server)

```
$ du -h
152K	./security-controller/0.0.1-alpha.0.248+a4389ef2
156K	./security-controller
220K	./commons-jpa/0.0.1-alpha.0.248+a4389ef2
224K	./commons-jpa
148K	./commons-model/0.0.1-alpha.0.248+a4389ef2

152K	./commons-model
212K	./security-model/0.0.1-alpha.0.248+a4389ef2
216K	./security-model
44K	./app-core/0.0.1-alpha.0.248+a4389ef2
48K	./app-core
40K	./test-app-core/0.0.1-alpha.0.248+a4389ef2
44K	./test-app-core
60K	./authn-controller/0.0.1-alpha.0.248+a4389ef2
64K	./authn-controller
144K	./test-authorization-server/0.0.1-alpha.0.248+a4389ef2
148K	./test-authorization-server
1.1M	.
```

> If feasible you could try with 8.9 to rule out a regression or 8.10.2 to rule out it has already been fixed.

| | |
|--------|------------------------------------------|
| 8.10.2 | https://scans.gradle.com/s/i3bnd7m7ldp7g |
| 8.9    | https://scans.gradle.com/s/7inr2z22qilt4 |

**Comment by ov7a** [comment] 2024-09-30 09:20
> I also confirmed that if all task configurations are hit locally publishToMavenLocal takes ~10 seconds

It's actually [less than 0.03 second](https://scans.gradle.com/s/qfznakct36srq/timeline?details=6txjbv7cx6tqa&expanded=WyI3Il0)

> However, I do know that publishToMavenLocal does not do the exact same thing locally as it does when publishing to a remote server

Does it matter in that case? If you want a clean test, you can set up a local instance of Maven repository, such as Nexus or Artifactory.

Currently, I think it's safe to assume that this is a networking issue.

> I'm hoping that at the very least the outcome of this ticket is improvements to providing the information required to diagnose this issue.

We gave the feedback to the Develocity team.

**Comment by xenoterracide** [comment] 2024-09-30 13:14
It still wouldn't be the same case. Publishing to Nexus for example uses straight credentials that don't change. Githubs on the other hand changes every single time and so invalidates part of the cache every single time. It's probably not that part of the code that's doing this though. Gradle has documented performance bugs along this path.

I suppose if I were feeling non lazy I could build the artifacts and then push them with something other than Gradle... Although that's challenging because I have to fetch and parse the metadata...

**Comment by xenoterracide** [comment] 2024-09-30 16:21
ok, this is the result of pushing to a local nexus running in a docker container clean build 

* clean build https://scans.gradle.com/s/lntnpcipcix5g
* after build https://gradle.com/s/qwduhslzbam6q (seems to prove network)


this is uploading to github from my laptop 

* clean build https://gradle.com/s/s56ctnnoqoc4m
* after build https://gradle.com/s/74j5xv4g4io6q 

results are still curious, but I guess. I'm not certain why there's not a bigger cache it on the publish job since the prior job ran build. Unless that build cache is not restored in the subsequent job by gradle setup.

 If feedback to develocity was given should close then?

**Comment by ov7a** [comment] 2024-10-01 13:24
Thanks for the feedback.

Since it's confirmed that the issue was related to the networking, I'm closing this issue.

Regarding the blocking requests - Gradle uses Apache HTTP client under the hood - you can take a look at the wiring code starting from [here](https://github.com/gradle/gradle/tree/master/platforms/software/resources-http). If you test it and find some issues with the networking part - please open a new issue.

Regarding build cache - currently, publishing tasks [are not cachable](https://github.com/gradle/gradle/blob/f4b67991d9c0e119946b340d08e8e77702f09399/platforms/software/maven/src/main/java/org/gradle/api/publish/maven/tasks/PublishToMavenRepository.java#L56). This can potentially be improved, but it's out of scope for now.

**Closed by ov7a** 2024-10-01 13:24 UTC
Labels: a:bug, to-triage
