### ISSUE TITLE
Incremental Gradle builds are noticeably slower for small project after switching to kotlin script gradle

### ISSUE THREAD

**Issue by ScottPierce** [gradle/gradle#11857] opened 2020-01-09 16:16 UTC
After switching to Kotlin Script Gradle, the incremental builds are noticeably slower, taking almost a full second for a no-op build on a fairly small project. When I look at a build scan, it shows that nothing is happening most of the time, and the actual time that it spends executing is very fast.

### Expected Behavior

The build would happen much faster, and that the overhead of using gradle wouldn't be so costly.

Build scan URL: https://scans.gradle.com/s/cf2cgud5rqw5m/timeline

**Comment by ldaley** [comment] 2020-01-09 23:53
@ScottPierce the total build time was .89s: https://scans.gradle.com/s/cf2cgud5rqw5m/performance/build#build-time-total

Do you have a before to compare with? What kind of time are you expecting?

**Comment by ScottPierce** [comment] 2020-01-10 00:48
This is for a no-op build that does nothing, to emphasize the gradle overhead. 

The extra time is pretty annoying when you are doing several small UI changes. Incremental changes are ~3 seconds, but that had more to do with the kotlin compiler. Again, this is a very small project.

Look at then actual time that the tasks are running. The majority of the time no tasks are running. The actual tasks are taking up less than 20% of the build. Prior to moving files to Kotlin I was getting ~300 Millis no-op builds. Surely it's not expected that gradle has a 600+ Millis overhead to invoke the daemon on a project with 4 gradle modules?

**Comment by ldaley** [comment] 2020-01-10 00:50
@lptr Can you please take a look.

**Comment by eskatos** [comment] 2020-01-10 11:12
Hi Scott,

It seems that [startup](https://scans.gradle.com/s/cf2cgud5rqw5m/performance/build#build-time-startup) is dominating at ~500ms, close to the overhead you observed. From the command line, startup time is mostly about launching the gradle client cold jvm. From IDEs the client is running in the IDE hot jvm so startup almost vanish. Startup shouldn't involve the Kotlin DSL runtime except its presence in Gradle classpaths.

I tried to reproduce with a sample build we have with both groovy dsl and kotlin dsl variants that seemed close to your build ([groovy](https://github.com/gradle/gradle/tree/master/subprojects/docs/src/samples/jvm-multi-project-build/groovy) / [kotlin](https://github.com/gradle/gradle/tree/master/subprojects/docs/src/samples/jvm-multi-project-build/kotlin)). Here are the build scans for fully up-to-date `assemble`: [groovy](https://scans.gradle.com/s/liaglsukcyz44/performance/build) / [kotlin](https://scans.gradle.com/s/zvfddtybcrvom/performance/build). Performance looks similar with the same ~500ms startup time. Configuration and execution time are tiny because the sample doesn't contain much custom build logic or sources.

Is the build environment different? Same JVM?  Having before/after records would help understand further where is the overhead you can observe. It could be some difference in startup but also in other areas, build scans would be great if you can't share the reproducer build.

**Comment by ScottPierce** [comment] 2020-01-10 14:58
Thanks for your response @eskatos. It appears that I'm not getting that benefit from using the `IntelliJ` `gradle`configuration.

<img width="1183" alt="Screen Shot 2020-01-10 at 9 50 49 AM" src="https://user-images.githubusercontent.com/871169/72162050-3e7de780-338f-11ea-9f53-6145731f2541.png">

I realize this is now an IntelliJ question, but the ktor server I have running is watching for class file changes. How should I trigger a `compileKotlin` command to use the already started hot daemon in the IDE?

**Comment by eskatos** [comment] 2020-01-10 17:53
I was referring to a cold *client* jvm, not the daemon. Comparable records would be nice to understand the difference you see between a Groovy DSL based build and a Kotlin DSL based build doing the same thing.

About ktor and reloading classes, what you could do is run `compileKotlin` in `--continuous` mode, that way you'd pay startup and configuration time only once.

**Comment by eskatos** [comment] 2022-12-05 10:38
Closing this as unreproducible

**Closed by eskatos** 2022-12-05 10:38 UTC
Labels: in:kotlin-dsl, closed:unreproducible
