### ISSUE TITLE
Refresh problem when using Buildship

### ISSUE THREAD

**Issue by UdoW** [gradle/gradle#8654] opened 2019-02-28 14:19 UTC
I use Eclipse 2018-12 and Buildship 3.0.1 and Gradle 5.2.1.

I use a gradle project which uses our Gradle plugin.

In the plugin we define that the "provided" configuration should ignore the artifacts cache.

We do this like that (Kotlin):

private val provided: Configuration
....
provided = project.configurations.getOrCreate("provided")

and then

provided.resolutionStrategy.cacheDynamicVersionsFor(0, TimeUnit.SECONDS)
provided.resolutionStrategy.cacheChangingModulesFor(0, TimeUnit.SECONDS)

When the SNAPSHOT depency is changed then after a simple Gradle project refresh the new SNAPSHOT version should be immediatelly visible. 

This works in IntelliJ but not in Eclipse Buildship.

In Buildship it only works, if the "provided" configuration is repeated in the build.gradle.

Why is there a difference? What is Buildship doing wrong? Or is IntelliJ doing something extra which is not a standard process?

**Comment by big-guy** [comment] 2019-02-28 17:58
Hi @UdoW 

I'm not sure what you mean by "repeated in the build.gradle". Do you mean that when you put `
provided.resolutionStrategy.cacheDynamicVersionsFor(0, TimeUnit.SECONDS)` (and other lines) in the build.gradle things work from Buildship?

**Comment by UdoW** [comment] 2019-03-01 05:04
In the build.gradle we use this notation:
`
configurations.provided {
   resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}
`
Only with this notation Buildship refreshes the SNAPSHOT dependencies every time. 

If this notation is missed (but still included in the plugin) then Buildship does not refresh the SNAPSHOT dependencies "every" time (only after the standard timeout which is far too long for us).

**Comment by oehme** [comment] 2019-03-03 16:30
A general clarification first: The resolutionStrategy only applies when resolving your `provided` Configuration directly. As soon as you resolve a different Configuration that extends from yours (e.g. `compileClasspath`, which is used by the `compileJava` task and Eclipse), Gradle will instead use the resolution strategy of that Configuration, which still has the default timeout. For most practical purposes you therefor need to change the timeout on *all* Configurations to get consistent behavior across all tasks. The only exception to this rule is when you have a Configuration that's only intended to be used by one specific task. In that case you can get away with setting the timeout only on that one.

So my guess is that you wired that Configuration into the build in a way that causes IntellIJ to resolve it directly by accident. This gives you the behavior you expected, but for the wrong reason :)

I'll need a full reproducible example project (attached as a zip or a Github project) to tell you more :)

**Comment by Tschasmine** [comment] 2019-03-04 07:43
Hi @oehme, so basically you are saying because we use `configurations { compile.extendsFrom provided }` we get the `compile` resolution strategy instead of the one we configured for `provided`? 

The biggest problem we experienced was when using Eclipse for Linux. We weren't able to retrieve the new SNAPSHOT versions at all, not even by running `--refresh-dependencies` on `compileJava` and refreshing the Gradle project. On the command line it was fine.

A full reproducible example is difficult, since we can't give you access to our Docker registry without clarifying with management first, and the build depends on it. You can have a look at a [full example](https://github.com/esdk/g30l0) though. We experience the issue after [this commit](https://github.com/esdk/g30l0/commit/54a6eb3f18282a1113d98da920bf87d1a10fa7f2). This is when we change one of the JARs resolved from here `maven { url "http://$NEXUS_HOST:$NEXUS_PORT/nexus/content/repositories/$NEXUS_NAME-SNAPSHOT" }` ([build.gradle](https://github.com/esdk/g30l0/blob/master/build.gradle)). The dependency is actually configured in our plugin directly:
```kotlin
project.afterEvaluate {
	parseClasspathFile()
	project.configurations.getByName("testCompile").allDependencies.forEach {
		integTestCompile.dependencies.add(it)
		integTestImplementation.dependencies.add(it)
	}
	project.configurations.getByName("testRuntime").allDependencies.forEach {
		integTestRuntime.dependencies.add(it)
	}
	if (homedirDeps.isEmpty()) {
		addFallbackHomedirDeps()
	}
	homedirDeps.forEach {
		provided.dependencies.add(project.dependencies.create("de.abas.homedir", it, "1.0.0", "provided"))
	}
	if (clientdirDeps.isEmpty()) {
		addFallbackClientdirDeps()
	}
	clientdirDeps.forEach {
		provided.dependencies.add(project.dependencies.create("de.abas.clientdir", it, "1.0.0-SNAPSHOT", "provided"))
	}
}
```

**Comment by oehme** [comment] 2019-03-04 08:14
> so basically you are saying because we use configurations { compile.extendsFrom provided } we get the compile resolution strategy instead of the one we configured for provided?

Almost :) `compile` is also never resolved directly. It's `compileClasspath` for compilation and `runtimeClasspath` for execution. Eclipse and IDEA use the same configurations. So from this example I can't see why it would work in any of them, because none of them are looking at your provided configuration directly.

By the way the code above can be simplified/improved a lot, no `afterEvaluate` necessary. This will make your code much more robust when combined with other plugins/build scripts:

```
integTestCompile.extendsFrom(configurations.getByName("testCompile"))
integTestRuntime.extendsFrom(configurations.getByName("testRuntime"))
provided. withDependencies {
  //add client and homedir deps
}
```

**Comment by Tschasmine** [comment] 2019-03-05 17:03
Thanks, yes, you can close it as "works as designed".

Also thanks for the improvement hints, one more question though: 
In the `parseClasspathFile` method in the above example I need to access values defined in an extension as follows: 
```
val esdkConfig = project.extensions.create("esdk", EsdkConfig::class.java)
esdkConfig.baseOutputdir = File(project.buildDir, "abas")

esdkConfig.app = (esdkConfig as ExtensionAware).extensions.create("app", AppConfig::class.java)
esdkConfig.nexus = (esdkConfig as ExtensionAware).extensions.create("nexus", NexusConfig::class.java)
esdkConfig.abas = (esdkConfig as ExtensionAware).extensions.create("abas", AbasConfig::class.java)
esdkConfig.ssh = (esdkConfig as ExtensionAware).extensions.create("ssh", SSHConfig::class.java)
```
I found that if I execute above example without `project.afterEvaluate` the accessed values from the extension e.g. `(project.extensions.getByName("esdk") as EsdkConfig).abas.clientDir` are not initialized.

Is this due to an error during declaration of the extension or do we need the `project.afterEvaluate` after all?

**Comment by oehme** [comment] 2019-03-05 18:10
I don't have the full context, but if you put that code inside `withDependencies` it will also only be called when necessary instead of on every build invocation.

**Closed by oehme** 2019-03-05 18:10 UTC
Labels: @core, from:contributor
