### ISSUE TITLE
It's not possible to report problems to the Tooling API from a Worker API task

### ISSUE THREAD

**Issue by DavidGregory084** [gradle/gradle#30147] opened 2024-08-10 13:54 UTC
### Current Behavior

When problems are reported from a [WorkAction](https://docs.gradle.org/current/javadoc/org/gradle/workers/WorkAction.html), they do not seem to be received by Tooling API connections.

It does not seem to be significant whether the Worker uses class loader isolation or process isolation - problems are not reported in either case.

This issue has existed since the introduction of the Problems API in Gradle 8.6 because that is the version I was using when I first encountered this issue, but it can still be reproduced on main.

### Expected Behavior

Problems reported via Worker API tasks should be exposed to Tooling API progress listeners.

It may be that these events are unreported to other problem reporting mechanisms too but I haven't investigated that personally. 

### Context (optional)

I am trying to integrate Gradle with a JVM compiler whose Gradle plugin [uses the Worker API](https://codeberg.org/mina-lang/mina/src/branch/main/gradle-plugin/src/main/java/org/mina_lang/gradle/MinaCompileAction.java) for its compilation tasks.

I have [hooked](https://codeberg.org/mina-lang/mina/src/branch/main/gradle-plugin/src/main/java/org/mina_lang/gradle/diagnostics/MinaProblemReporter.java#L73) the compiler's diagnostic reporting mechanisms to the Problems API and I am [prototyping a solution](https://github.com/opencastsoftware/gradle-bsp/tree/main/server/src/main/java/com/opencastsoftware/gradle/bsp/server) that connects to a Gradle build and acts as a [Build Server](https://build-server-protocol.github.io/), which would enable such diagnostics to be [reported](https://codeberg.org/mina-lang/mina/src/branch/main/lang-server/src/main/java/org/mina_lang/langserver/bsp/MinaBuildClient.java#L127) through the compiler's language server to editors like VS Code.

### Steps to Reproduce

https://github.com/DavidGregory084/gradle-problems-api-worker-issue-repro

The reproduction project above is based upon the Problems API Usage sample from the Gradle repository.

In order to reproduce the issue, use the `./gradlew :sample-ide:importBuild` task and note that the new `adhoc-worker-deprecation` Problem that is created in the [WorkerApiAction](https://github.com/DavidGregory084/gradle-problems-api-worker-issue-repro/blob/main/reporters/worker-api-plugin/src/main/java/reporters/WorkerApiAction.java) is never reported.

If the commented code in [WorkerApiTask](https://github.com/DavidGregory084/gradle-problems-api-worker-issue-repro/blob/main/reporters/worker-api-plugin/src/main/java/reporters/WorkerApiTask.java#L29) is uncommented so that the problem is reported there and not through the `WorkAction` then the problem is reported.

### Gradle version

Tried on 8.6 - 8.11 snapshots (main)

### Build scan URL (optional)

https://scans.gradle.com/s/kwyxggbiawneo

**Comment by cobexer** [comment] 2024-08-13 13:08
The issue is in the backlog of the relevant team and is prioritized by them.

***
Someone from the team will need to have a look at the reproducer.

**Comment by hegyibalint** [comment] 2024-10-28 11:41
Hey @DavidGregory084, sorry about the extremely long response time.
We've been in a pickle with the workers API ourselves, and it took considerable effort to make problem reporting [working from there](https://github.com/gradle/gradle/pull/27222).

I've fixed up your repro with our API changes, and now I can see in the report the worker-side problems.

![Image](https://github.com/user-attachments/assets/fb1f8b4a-198f-40f6-8b9b-fca5e52d2e88)

PTAL yourself, but I would close this issue preemptively and reopen it if needed.

**Closed by hegyibalint** 2024-10-28 11:41 UTC
Labels: a:bug, in:workers, in:problems

**Comment by DavidGregory084** [comment] 2024-10-28 15:09
This is awesome news, thanks @hegyibalint, I will take a look as soon as I can!

Is this fixed only for Gradle 8.11.x or will it be backported?

I'm using this in a [Gradle plugin](https://codeberg.org/mina-lang/mina/src/branch/main/gradle-plugin) so it would be really helpful to understand the lowest Gradle version that I can support.

**Comment by hegyibalint** [comment] 2024-10-29 17:35
I think I found the issue: in the sample, I've used the following:

```java
@Override
public void statusChanged(ProgressEvent progressEvent) {
    if (progressEvent instanceof SingleProblemEvent)
        prettyPrint((SingleProblemEvent) progressEvent);
}
```

The issue with this is that the code expect `SingleProblemEvent`, which is a special type of problem (it's an aggregated problem, a concept which we will probably abandon soon).
I'm not certain based on what PR, but some versions send a `DefaultProblemEvent`, which only implements `ProblemEvent`

You could do two things to verify this:
 - You can take the reproducer, and modify the code there.
 - Also, you can use this new project: https://github.com/hegyibalint/gradle-problem-reporting-sample. I just wrote, where I tried to reduce the scope and make clearer what is applied where.

### How to setup `gradle-problem-reporting-sample`

If you want to run it, check it out, and run `:test-ide:run`. 
Currently the approach is a bit crude, but the setup is the following:
 - TAPI is the latest release or snapshot (at the time of writing 8.11-rc1), done by a plus version[^1]
 - The Gradle version executed is controlled in `SampleIde`.
You can adjust these parameters to see any combination [^2]

[^1]: I'm sorry
[^2]: We are doing this in a much more refined way here: https://github.com/gradle/gradle/tree/master/platforms/ide/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling. Though we don't have exactly a test like this, which I might fix retroactively by putting it into `r86`

**Comment by DavidGregory084** [comment] 2024-11-15 12:56
> Also, you can use this new project: https://github.com/hegyibalint/gradle-problem-reporting-sample. I just wrote, where I tried to reduce the scope and make clearer what is applied where.

Hmm unfortunately this project 404s for me, perhaps it is a private repository?
