### ISSUE TITLE
Eclipse classpath should be able to use test fixtures in implementation dependencies

### ISSUE THREAD

**Issue by dgeissl** [gradle/gradle#18138] opened 2021-08-27 13:16 UTC
Similar to https://github.com/gradle/gradle/issues/14932 I have a project with test-fixtures providing utlility classes for testing with certain classes of this module. While I can define a dependency to this fixture and use the classes in other projects tests (inside the same multi project setup) - it is currently not possible to reuse these fixtures as a "production" dependency in Eclipse.

This might seem a bit strange in the first place, but the point is to provide a project that works as a test-framework compiling different test-fixtures and providing additional convenience features for foreign projects that want to do testing with this framework.
For this projects test framework the fixtures are a production dependencies and not something that is going to be used for testing the module.

### Expected Behavior

Declared test artifacts / test fixtures should be available in a dependent projects main `SourceSet`.

### Current Behavior

Test fixtures are only available in the dependent test `SourceSet`s even though the dependency might be declared as implementation.
Either the eclipse plugin should detect usage of the java-test-fixtures out of the box or a configuration should be available to mark SourceSets as "production" code even though it is called "test<something".

### Context

Bundling test-fixtures to be compiled in a convenience test framework.

While I am not familiar with the current limitations and caveats of the eclipse production and test code handling it might be enough to have a option to treat a specific SourceSet as produktion code even though it might be called "test". This would also help in other usecases where the Eclipse project does not allow to have multiple artifacts created by one project.

I've attached a reproducer that works in Intellij and on the command line, while Eclipse fails to compile it.
[eclipse-test-fixtures.zip](https://github.com/gradle/gradle/files/7067086/eclipse-test-fixtures.zip)

**Comment by donat** [comment] 2021-12-01 18:08
You are right, this use-case should work in Eclipse.

Eclipse has a certain limitation on how to represent projects and dependencies. More precisely it has a one-classpath-per-project structure, which cannot be precisely mapped to Gradle source sets. Because of this, Buildship uses some heuristics that work with the majority of the use-cases. 

Here, the problem is that Eclipse marks the source directories from the `testFixture` source set as a `test` source set, which makes the contained types inaccessible from downstream projects, unless the project dependency declaration has the `without_test_code=true` classpath attribute set (which is [correctly set for test fixture dependencies](https://github.com/gradle/gradle/pull/15198)) and the call site is a test source directory.

A workaround could be to remove the `test` classpath attribute from the eclipse source directory in the test fixture project. Here's a snippet for the reproducer project:

```groovy
// base/build.gradle

plugins {
  id 'eclipse'
}

eclipse {
  classpath { 
    file {
      whenMerged {
      	entries.find { it.path?.equals('src/testFixtures/java') }.entryAttributes["test"] = "false"
      }
	}
  }
}
```

Problem is, this will cause another problem as the fixtures' own dependencies are also marked as test dependencies and thus will be unavailable for the fixtures. You'd need to remove the `test` classpath attribute from those dependencies with a script similar to the one above.

**Comment by dgeissl** [comment] 2021-12-02 06:47
Thank you for the hint donat, we actually did that already only for another use-case where the test classes had tto be treated as production code to be able to publish then into a application server. To be able to get the right dependencies we actually created a dummy `configuration` called `eclipseIntTst`  (to avoid having `test` in the name) and add this as `plusConfiguration`.

That's why I asked if it would be possible to add a optional feature to mark a specific SourceSet as "production" code no matter what the heuristic might think.

**Comment by donat** [comment] 2021-12-02 11:15
I've drafted a new API in the Gradle eclipse plugin DSL, that can potentially solve the issue: https://github.com/gradle/gradle/pull/19197
With that merged you can do the following in the build script:
```groovy
eclipse {
  classpath { 
   testSourceSetNamePattern = "test" // unlike default .*test.*, this doesn't match to testFixtures 
   testDependencyConfigurationNamePattern = "test(Compile|Runtime)Classpath"
  }
}
```
What do you think?

**Comment by dgeissl** [comment] 2021-12-03 11:21
Looks promising, not sure if one would need the separation of classpath and sourceSet name patterns as they are usually linked together and we need to make sure to remember those patterns are not the same. 

But it is for sure much more convenient and controllable than what we have now.

**Comment by dgeissl** [comment] 2021-12-03 11:27
Looks promising, not sure if one would need the separation of classpath and sourceSet name patterns as they are usually linked together and we need to make sure to remember those patterns are not the same. 

But it is for sure much more convenient and controllable than what we have now.

**Comment by donat** [comment] 2021-12-23 12:50
@dgeissl Would you mind trying https://github.com/gradle/gradle/pull/19310? Any feedback is appreciated?

You can evaluate my changes by using this snapshot release: https://services.gradle.org/distributions-snapshots/gradle-7.4-branch-donat_eclipse_test_sources_and_deps_take_2-20211222124805+0000-bin.zip

**Closed** 2022-01-07 11:50 UTC
Labels: in:testing, a:feature, in:eclipse-plugin
