### ISSUE TITLE
Gradle 8.8 crash on MAC OS

### ISSUE THREAD

**Issue by theyoz** [gradle/gradle#29482] opened 2024-06-10 13:01 UTC
### Current Behavior

Crash

`
 FAILURE: Build failed with an exception.
15:26:35  
15:26:35  * What went wrong:
15:26:35  Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
`

### Expected Behavior

Not to crash

### Context (optional)

MAC OS 

### Steps to Reproduce

`./gradlew assembleRelease  --scan --info --stacktrace`

### Gradle version

8.8

### Your Environment (optional)

MAC OS, JAVA 17 and GRADLE 8.8

**Comment by theyoz** [comment] 2024-06-10 13:01
[hs_err_pid16601.log](https://github.com/user-attachments/files/15766523/hs_err_pid16601.log)
[gradle.log](https://github.com/user-attachments/files/15766524/gradle.log)

**Comment by hegyibalint** [comment] 2024-06-11 12:16
This issue will be closed as a duplicate of

* #29476

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

**Closed by hegyibalint** 2024-06-11 12:16 UTC
Labels: a:bug, closed:duplicate, in:internal-native-libraries
