### ISSUE TITLE
Removing project .gradle directory disproportionately degrades buildSrc performance

### ISSUE THREAD

**Issue by ldaley** [gradle/gradle#5091] opened 2018-04-19 04:41 UTC
### Expected Behavior

Using a “clean” checkout strategy for CI builds, where the Daemon is in use, should not always impose surprising performance penalties for the `buildSrc` component of builds.

### Current Behavior

In this scenario, it can be observed that snapshotting the inputs for buildSrc takes a surprisingly long time (several seconds, vs sub second if not using a clean checkout). The same phenomenon is not noticed for the non `buildSrc` component.

### Context

After quick discussion, the issue seems to be that the file snapshots for buildSrc are cached in the checkout's .gradle directory, whereas the snapshots for the non buildSrc are under GRADLE_USER_HOME (and therefore survive clean checkouts).

From @wolfs:

> Looks like we have two hash caches, one in the Gradle user home and one in the project directory. But you are right, the one which is used for buildSrc compilation is the one in the project directory.

**Comment by wolfs** [comment] 2018-04-19 07:06
@ldaley Let me clarify my statement a little bit. We have different cache directories for different kinds of caches.

1. There is a `.gradle` directory in the root project directory which stores the task history and file hashes for inputs and outputs of tasks.
2. there is also a `caches` directory in the GRADLE_USER_HOME which stores file hashes, this time for classpaths of build scripts and tasks

When doing a clean checkout, everything from 1. is discarded - that means all the file hashes of the task's inputs and outputs are gone. Moreover, in a project with `buildSrc` we also have a `buildSrc/.gradle` directory. I guess we do have a `.gradle` directory for every included build, too. All these would be lost on clean checkout.

So the issue is not about doing something different for `buildSrc` and non-`buildSrc`, but if we want to keep more snapshots in the GRADLE_USER_HOME to reuse them between builds.

**Comment by adrian-baker** [comment] 2018-04-24 19:58
See https://github.com/gradle/gradle/issues/4447

**Comment by ldaley** [comment] 2018-04-25 21:14
@wolfs thanks for clarifying. I'll have to recreate the scenario and check whether it was only `buildSrc` that was affected, as I thought was the case.

**Comment by oehme** [comment] 2018-05-17 21:57
I've profiled this and the main problem is that we often throw away project-independent analysis. For instance, even for the simplest `buildSrc` project we go through the huge `gradleApi` jar and

- calculate a plain hash
- calculate a `@Classpath` hash
- calculate a `@CompileClasspath` hash
- analyze it for incremental compilation
- see if it contains annotation processors

The in-memory parts of this are mostly lost on the next build and the persistent parts are mostly lost on a clean checkout. Both should be kept across invocations and checkouts.

This is also heavily affecting our integration tests, because many of them use `buildSrc` (even if it just contains a single file). I have several ideas on how to improve this:

- Consider files in the Gradle distribution immutable (just like we already do for the depenency cache). That means they are only snapshotted once for the lifetime of a daemon. This only affects our embedded test executer, as it directly runs from the classpath rather than generating a gradleApi jar
- Consider only the relative path of files in Gradle distribution instead of snapshotting the actual file. The Gradle version is already an input to every cache key, so hashing those files is redundant. Again, this only affects our embedded executor.
- Make sure the generated gradleApi jar is treated as immutable, just like files in the dependency cache. This affects all builds that use gradleApi(), e.g. buildSrc.
- Keep in-memory file content caches (e.g. annotation processor analysis, incremental compile analysis) for immutable files across builds
- Keep the persistent caches for immutable files in the user home instead of the project directory. They don't change, so they can be reused across projects and across daemons.

I'd like to tackle the above improvements as time allows to improve our integration test turnarounds (and make user builds faster too). Do the above steps sound reasonable @lptr @wolfs?

**Comment by oehme** [comment] 2018-05-18 12:53
There also is a bit of the opposite going on: For instance, we seem to be storing `@CompileClasspath` snapshots in the user home, no matter for what file. So a lot of the snapshots in the user home will be project-specific ones. The same is true for compiled build scripts or Kotlin DSL accessors. They are project-specific, yet stored in the user home. Right now I don't see a clear pattern what goes where. I feel like we should either

- clearly separate global and project-specific caches or
- move all the caches to the global cache for maximum potential reuse

**Comment by oehme** [comment] 2018-05-20 09:06
1. Is now on master
2. Is in this [PR](https://github.com/gradle/gradle/pull/5463)
3. and 4. are mostly done in these two PRs: https://github.com/gradle/gradle/pull/5472, https://github.com/gradle/gradle/pull/5465

I still have to apply the same solution to the incremental compile jar analysis. But already I can see big benefits. `core:integTest` is twice as fast with the PRs above.

**Comment by oehme** [comment] 2018-05-26 14:11
After merging the changes above, the "clean checkout" performance test is [42% faster](https://builds.gradle.org/viewLog.html?buildId=13233411&buildTypeId=Gradle_Util_Performance_AdHocPerformanceScenarioLinux&tab=artifacts#!-1o4yfzkjpc80h). The only missing piece is caching incremental compile analysis.

**Comment by ldaley** [comment] 2018-05-28 23:53
Excellent work.

**Comment by oehme** [comment] 2018-05-29 14:13
I'm closing this since the incremental compilation caches are tracked by https://github.com/gradle/gradle/issues/4447 and I might not have time to do this in 4.9.

**Comment by oehme** [comment] 2018-05-29 14:14
@ldaley Did you redo your experiment and see the improvement?

**Closed by oehme** 2018-05-29 14:13 UTC
Labels: a:bug, from:member, in:build-cache
