### ISSUE TITLE
Rich console output is broken in 3.5 on Arch Linux

### ISSUE THREAD

**Issue by dead10ck** [gradle/gradle#2039] opened 2017-05-15 16:43 UTC
### Expected Behavior

The rich console output should move right and left as it's doing things, and print out progress of the current task.

### Current Behavior

After upgrading to 3.5, the rich output does not work any more.

```sh
[I] ~/s/i/accessors (master ± ) ∫ /usr/bin/gradle --console rich clean test
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
Executing tests with 4 processes
:clean
:compileJava
:processResources NO-SOURCE
:classes
:compileTestJava
:processTestResources
:testClasses
<===========--> 87% EXECUTING

```
It just sits and looks exactly like this until all unit tests are finished executing.

### Context

The project I am working on has hundreds of unit tests, so not seeing progress is a huge setback.

### Your Environment

Running Arch Linux, 

```
[I] ~/s/i/accessors (master ± ) ∫ uname -a                                                                        [09:27:01] 
Linux opendns-arch-x1 4.10.13-1-ARCH #1 SMP PREEMPT Thu Apr 27 12:15:09 CEST 2017 x86_64 GNU/Linux
[I] ~/s/i/accessors (master ± ) ∫ gradle --version                                                                [09:41:17] 

------------------------------------------------------------
Gradle 3.5
------------------------------------------------------------

Build time:   2017-04-10 13:37:25 UTC
Revision:     b762622a185d59ce0cfc9cbc6ab5dd22469e18a6

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_121 (Oracle Corporation 25.121-b13)
OS:           Linux 4.10.13-1-ARCH amd64
```

This behavior happens on both the fish shell v2.5.0 as well as bash v4.4.12, on GNOME Terminal 3.24.2.

**Comment by bmuschko** [comment] 2017-05-16 13:39
I am not sure if you intended to use `:testClasses` as example that that task only compiles classes and does not run tests. The task that actually runs the tests is `:test`. In the long run we also want to provide more fine-grained information on compiled classes but that wasn't part of 3.5.

> The rich console output should move right and left as it's doing things

Could you please clarify this sentence? I don't quite understand what you are expecting here. The progress bar will only move from left to right.

> The project I am working on has hundreds of unit tests, so not seeing progress is a huge setback.

The executed tests statistics (failed, successful, skipped) should be shown in the lines underneath the progress bar while tests are being executed. Or are you asking about test log events here?

**Comment by dead10ck** [comment] 2017-05-16 14:15
> I am not sure if you intended to use :testClasses as example that that task only compiles classes and does not run tests. The task that actually runs the tests is :test.

Yes, if you'll notice, the task I ran was `test`. The output I posted is what it looks like while it is executing the unit tests.

> Could you please clarify this sentence? I don't quite understand what you are expecting here. The progress bar will only move from left to right.
>
> The executed tests statistics (failed, successful, skipped) should be shown in the lines underneath the progress bar while tests are being executed. Or are you asking about test log events here?

I'm sorry if my description was too vague; it's a mode of output that is unique to Gradle, in my experience, so I'm not quite sure how to describe it. But the progress bar is working fine, it's the line underneath that normally prints the status of the current executing task. Normally it looks like

```
<===========--> 87% EXECUTING
foo > bar > baz
```

As a task executes, the second line moves from left to right and right to left as it does the individual actions of a task. For the `test` task, it normally prints out how many tests have run, and how many there are total. But after upgrading, that second line that's supposed to be under the progress bar just doesn't print at all. The `test` task in particular just looks exactly how I pasted it until the entire `test` task finishes.

**Comment by bmuschko** [comment] 2017-05-16 14:43
Thanks for the information. I am still having trouble imagining what you are seeing on your screen. Would you mind providing us with a [Ascii screencast](https://asciinema.org/)?

**Comment by dead10ck** [comment] 2017-05-16 15:45
Excellent idea! This is how it should look (taken on a Mac with iTerm 2, fish v2.5.0):

[![asciicast](https://asciinema.org/a/73hvg5d4lgkhavgmzkzo12d7o.png)](https://asciinema.org/a/73hvg5d4lgkhavgmzkzo12d7o)

This is how it looks on Arch, with GNOME Terminal:

[![asciicast](https://asciinema.org/a/9v4sltxd4hwa87cfk39lyqrt7.png)](https://asciinema.org/a/9v4sltxd4hwa87cfk39lyqrt7)

This same behavior is exhibited in bash too, so I don't think it's the shell emulator.

**Comment by bmuschko** [comment] 2017-05-16 15:56
Fantastic! That makes it perfectly clear on what's going on. We'll look into it.

**Comment by eriwen** [comment] 2017-05-16 16:04
@dead10ck Thanks for the very useful asciicasts. Would you be willing to test out our latest nightly and see how the behavior differs?

`./gradlew wrapper --gradle-version=4.0-20170516093342+0000`

**Comment by dead10ck** [comment] 2017-05-16 16:14
@eriwen it looks like this version is even worse! :/

[![asciicast](https://asciinema.org/a/bsywz7e7z1umokpwik8k1gi90.png)](https://asciinema.org/a/bsywz7e7z1umokpwik8k1gi90)

**Comment by dead10ck** [comment] 2017-05-16 16:16
It's also worth mentioning that it doesn't default to `--console rich` on Arch (I have to alias `gradle` to `gradle --console rich`).

**Comment by eriwen** [comment] 2017-05-16 16:20
> It's also worth mentioning that it doesn't default to --console rich on Arch
Presumably it's always been this way, or is this a regression in 4.0?

@dead10ck Thanks very much for the cast again. I'm marking this to be investigated for 4.0.

**Comment by dead10ck** [comment] 2017-05-16 16:21
> Presumably it's always been this way, or is this a regression in 4.0?

Yeah, it's been that way for me since I've used Gradle on this setup.

**Comment by big-guy** [comment] 2017-05-24 19:40
@dead10ck we've done a bit more work on this.

Could you give `4.0-20170524135845+0000` a try?

WRT why Gradle doesn't automatically use `--console=rich`, I found a couple of problems with the underlying native integration library we use: 
- https://github.com/adammurdoch/native-platform/issues/24
- https://github.com/adammurdoch/native-platform/issues/25

Could you post the output of these commands to confirm you're running into the same issues?
- `ls -l /usr/lib/libncurses*`
- `ls -l /usr/lib/libtinfo*` 

Thanks!

**Comment by dead10ck** [comment] 2017-05-26 00:35
@big-guy here's a new asciicast. It looks better! Though for some reason, at the end, it seems that some `DEBUG` level logs printed out.

[![asciicast](https://asciinema.org/a/0vr0m8jz37d678r7pxi3c6nl0.png)](https://asciinema.org/a/0vr0m8jz37d678r7pxi3c6nl0)

As for the commands you requested:

```sh
[I] ~/s/i/accessors (master ± u-5) ∫ ls -l /usr/lib/libncurses*
-rw-r--r-- 1 root root     18 May  2 22:17 /usr/lib/libncurses.so
-rw-r--r-- 1 root root     20 May  2 22:17 /usr/lib/libncurses++.so
lrwxrwxrwx 1 root root     18 May  2 22:17 /usr/lib/libncurses++w.so -> libncurses++w.so.6*
lrwxrwxrwx 1 root root     16 May  2 22:17 /usr/lib/libncursesw.so -> libncursesw.so.6*
lrwxrwxrwx 1 root root     20 May  2 22:17 /usr/lib/libncurses++w.so.6 -> libncurses++w.so.6.0*
lrwxrwxrwx 1 root root     18 May  2 22:17 /usr/lib/libncursesw.so.6 -> libncursesw.so.6.0*
-rwxr-xr-x 1 root root  77336 May  2 22:17 /usr/lib/libncurses++w.so.6.0*
-rwxr-xr-x 1 root root 448944 May  2 22:17 /usr/lib/libncursesw.so.6.0*
```

And it looks like there were no files that match `libtinfo*` on my system. I noticed a `libtinfo` package in the AUR, so I tried installing that, but doing so did not make gradle default to `--console rich`.

After installing:

```sh
[I] ~/s/i/accessors (master ± u-5) ∫ ls -l /usr/lib/libtinfo*
lrwxrwxrwx 1 root root 22 May 25 17:31 /usr/lib/libtinfo.so -> /usr/lib/libtinfo.so.6*
lrwxrwxrwx 1 root root 27 May 25 17:31 /usr/lib/libtinfo.so.6 -> /usr/lib/libncursesw.so.6.0*
```

**Comment by big-guy** [comment] 2017-05-26 17:02
Thanks @dead10ck 

If you symlink `/usr/lib/libncurses.so.6.0` to `/usr/lib/libncursesw.so.6.0`, I think Gradle will automatically use the rich console then, but I'm not sure if that's safe to do. 

Those debug logs seem to be from your tests.  Are those definitely not seen on the console in 3.5, but show up in the test report?

**Comment by dead10ck** [comment] 2017-05-26 18:22
> Those debug logs seem to be from your tests. Are those definitely not seen on the console in 3.5, but show up in the test report?

That is correct. These do not get printed in 3.5.

**Comment by big-guy** [comment] 2017-05-26 21:05
OK, I'm trying to reproduce that behavior...

Do you know which logging framework the tests are using? 
Can you check if the Gradle test report contains the debug in standard output/standard error for the test?
Do you have any special configuration for the `test` task to listen for output from the tests?

**Comment by dead10ck** [comment] 2017-06-08 16:06
@big-guy  Sorry for the late response.

> Do you know which logging framework the tests are using?

This repo uses log4j.

> Can you check if the Gradle test report contains the debug in standard output/standard error for the test?

It does not appear that the output is tied to any specific test, that I can tell from the output. It does not appear anywhere in the generated test reports. I did also notice that the standard output that *was* in the test report contained lots of `DEBUG` output (that is separate from the debug lines printed to the console at the end), where it did not before.

> Do you have any special configuration for the test task to listen for output from the tests?

The only modification to the `test` task is:

```groovy
test {
  maxParallelForks=Runtime.runtime.availableProcessors()
  logger.lifecycle("Executing tests with $maxParallelForks processes")
}
```

**Comment by dead10ck** [comment] 2017-08-22 16:44
Hey guys, I wanted to give an update on the 4.1 release. This release is supposed to display which test is running in each test process, which is great. But unfortunately, it does not look like it works quite right.

[![asciicast](https://asciinema.org/a/Kl7LSXx1wJOTGFgSZsR9AhDU5.png)](https://asciinema.org/a/Kl7LSXx1wJOTGFgSZsR9AhDU5)

There are a couple of problems to notice:

* There are 4 test executors, but this output displays only 3.
* It doesn't look like the currently-executing test is being updated as often as it should. If you look at the number of tests passing, sometimes you'll see bursts of short tests fly by, but none of the output changes. Some of these tests are genuinely long-running, though, so it's unfortunately hard to tell which executors are actually stuck on one test for a long time, and which are just not being updated by Gradle.

You can also see at ~2:30 the debug output problem I mentioned above is still persisting.

**Comment by eriwen** [comment] 2017-08-22 17:25
@dead10ck Regarding the first issue, IIRC we respect `org.gradle.workers.max` property even in test executors, so I wonder if you don't have that value set to `3` and truly only 3 test executers are used.

The count of tests completed is, I think, counting the number of test methods (I forget the technical name of it here, we're incrementing from events fired by the test runner, I think), and the "work in progress" section is only updates based on events fired for test classes. It's possible that a bunch of test methods were run successfully within one class (which isn't done) which would cause the test counter to increment but the test classes in progress not to change. 

Note that all of the "executers" you see are all updated together, every 100ms or so. It's possible we're not handling the test events quite right which might cause incorrect display. @bmuschko would know more. I suspect we'd have an answer to this if you used a source build of Gradle that was configured to print test names as well as the classes.

**Comment by dead10ck** [comment] 2017-08-22 17:48
> Regarding the first issue, IIRC we respect `org.gradle.workers.max` property even in test executors, so I wonder if you don't have that value set to `3` and truly only 3 test executers are used.

Hmm, well I tried explicitly setting this to 4 by invoking with `--max-workers=4` and putting `org.gradle.workers.max=4` in my `gradle.properties` and it still only shows 3. Plus, I think that property gets set to the number of available processors by default, which is 4 in my case.

> The count of tests completed is, I think, counting the number of test methods (I forget the technical name of it here, we're incrementing from events fired by the test runner, I think), and the "work in progress" section is only updates based on events fired for test classes. It's possible that a bunch of test methods were run successfully within one class (which isn't done) which would cause the test counter to increment but the test classes in progress not to change.

Oh, I see! Yes, that might be what's happening. Apologies, I didn't look at this close enough, and I didn't realize that it was only printing the test class, and not each test name.

**Comment by bmuschko** [comment] 2017-08-23 22:02
I tried to reproduce the issue you are seeing but it was behaving correctly on my machine. Maybe you could put together a test project that reproduces it? Can you please also open a new issue for this topic if you want to proceed. It's not really the same root cause as the one reported originally.

**Comment by dead10ck** [comment] 2017-08-24 15:38
@bmuschko I very much suspect that the problem is not project-specific, but platform-specific. Is testing on Linux part of the normal development process?

I also very much suspect that most of the issues in this thread (the original issue, the console type not defaulting to `rich`, and now this one) are related in some way (my first guess being ncurses), so I've been keeping them in the same issue. I can make a separate one if that will help you, though.

**Comment by dead10ck** [comment] 2017-09-28 23:23
Turns out the problem with debug logging was specific to a conflict with multiple SLF4J bindings in my project.

However, @bmuschko is there any news on the rich console output issue? Were you able to test this on a Linux box?

**Comment by trustin** [comment] 2018-01-17 21:44
I can reproduce this issue reliably with this project: https://github.com/line/armeria and the following command:

   ./gradlew --console rich --parallel clean check

At some point, it stops updating the progress, especially the test progress.

The problem does not show up if I remove the `--parallel` option.

**Comment by trustin** [comment] 2018-02-01 00:36
Problem is solved after installing the `ncurses5-compat-libs`. Arch Linux uses ncurses 6 and it seems like Gradle doesn't work well with ncurses 6.

https://discuss.gradle.org/t/how-do-i-always-force-console-auto-in-a-gradle-properties-or-environment-variable/12039/11

**Comment by dead10ck** [comment] 2018-02-01 18:03
@trustin you are correct, nice find! That completely fixes the output issues. So @bmuschko @big-guy I guess the real issue, then, is compatibility with ncurses 6.

**Comment by trustin** [comment] 2018-02-05 03:21
According to https://github.com/adammurdoch/native-platform, ncurses 6 support has been included in 0.13 already. However, Gradle uses native-platform 0.14 already. Probably we should file a bug there?

**Comment by adammurdoch** [comment] 2019-10-21 23:40
There's a fix in native-platform now, which will be released soon.

**Comment by adammurdoch** [comment] 2019-11-06 00:16
Should be fixed in Gradle now.

**Closed by adammurdoch** 2019-11-06 00:16 UTC
Labels: a:bug, affects-version:3.5, from:contributor, in:console, in:logging
