### ISSUE TITLE
Dependency constraint that provides a version will cause other dependency exclusions to be ignored

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#4609] opened 2018-03-06 15:21 UTC
When a dependency constraint is 'realized' into a hard dependency, it provides an additional path to the target module, one that has no exclusions defined. As a result, any dependency exclusions defined on other dependencies will be ignored.

Dependency constraints are not dependencies, and should not invalidate excludes defined on dependencies.

### Expected Behavior

When a dependency constraint is provided (from a Maven BOM or Gradle build), then existing exclusions on dependencies should be honoured.

### Current Behavior

When any dependency constraint references a target module, all exclusions are ignored for that module.

### Steps to Reproduce (for bugs)

318b23f05cbb0fb4c84cb4e3b76390eb873cf2ee

**Comment by oehme** [comment] 2018-03-06 15:38
Looks like a duplicate of https://github.com/gradle/gradle/issues/4567

**Closed** 2018-05-02 15:28 UTC
Labels: a:bug, from:member, in:dependency-management
