### ISSUE TITLE
Running Java application with Gradle incorrectly creates strings containing the `MIDDLE DOT` character

### ISSUE THREAD

**Issue by kevin-nadeau** [gradle/gradle#3296] opened 2017-10-26 19:57 UTC
### Expected Behavior

The `MIDDLE DOT` character, set to a String variable should be equivalent to a String variable created using the Unicode representation of that character.
``` java
public class StringConversionBug {
    private static final String EXPECTED_S1 = "\u00B7";
    private static final String ACTUAL_S1 = "·";
    private static final String EXPECTED_S2 = "abc \u00B7 123";
    private static final String ACTUAL_S2 = "abc · 123";

    public static void main(String[] args){
        System.out.println("Expected S1: " + EXPECTED_S1);
        System.out.println("Actual S1  : " + ACTUAL_S1);
        System.out.println("Expected S2: " + EXPECTED_S2);
        System.out.println("Actual S2  : " + ACTUAL_S2);
    }
}
```

``` java
import org.junit.Test;
import static org.junit.Assert.assertEquals;

public class StringConversionBugTest {
    private static final String EXPECTED_S1 = "\u00B7";
    private static final String ACTUAL_S1 = "·";
    private static final String EXPECTED_S2 = "abc \u00B7 123";
    private static final String ACTUAL_S2 = "abc · 123";
    
    @Test
    public void testS1() {
        assertEquals(EXPECTED_S1, ACTUAL_S1);
    }

    @Test
    public void testS2() {
        assertEquals(EXPECTED_S2, ACTUAL_S2);
    }
}
```

### Current Behavior

1. Running the first class above from java the print line statements are the same for `EXPECTED_S1`/`ACTUAL_S1` and `EXPECTED_S1`/`ACTUAL_S2`.
1. Running the first class above from Gradle the print line statements are not the same. An extra character is inserted in the string before the MIDDLE DOT character. 
   * The string generated from `"·"` becomes `"Â·"` when ran from Gradle.

1. All tests from the 2nd class above pass when executed directly from Java .
   * Method used to execute the tests from Java: In intelliJ just click the Run icon next to the tests.
1. When ran from Gradle using the "test" task the tests fail. See output below.
```cmd 
Testing started at 15:06 ...
15:06:00: Executing external task 'test'...
:compileJava UP-TO-DATE
:processResources NO-SOURCE
:classes UP-TO-DATE
:compileTestJava
:processTestResources NO-SOURCE
:testClasses
:test

expected:<[]·> but was:<[Â]·>
Expected :·
Actual   :Â·
 <Click to see difference>

org.junit.ComparisonFailure: expected:<[]·> but was:<[Â]·>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.stringconversionbug.StringConversionBugTest.testS1(StringConversionBugTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	...

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)

com.stringconversionbug.StringConversionBugTest > testS1 FAILED
    org.junit.ComparisonFailure at StringConversionBugTest.java:17
com.stringconversionbug.StringConversionBugTest > testS2 FAILED
    org.junit.ComparisonFailure at StringConversionBugTest.java:22

expected:<abc []· 123> but was:<abc [Â]· 123>
Expected :abc · 123
Actual   :abc Â· 123
 <Click to see difference>

org.junit.ComparisonFailure: expected:<abc []· 123> but was:<abc [Â]· 123>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.stringconversionbug.StringConversionBugTest.testS2(StringConversionBugTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	...

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)

2 tests completed, 2 failed
:test FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///REDACTED/build/reports/tests/test/index.html
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
* Get more help at https://help.gradle.org
BUILD FAILED in 1s
3 actionable tasks: 2 executed, 1 up-to-date
There were failing tests. See the report at: file:///REDACTED/build/reports/tests/test/index.html
```

### Context

I ran into this bug developing tests using Selenium. The web page I am testing contains the `MIDDLE DOT` character in the title of various pages. GitHub and GitLab also use this character in their titles. 

I check that the test has navigated to the correct page by asserting the title matches an expected title. I have a list of CONSTANTS defining the various page titles I expect to hit throughout the test. However, the tests are failing because of the additional character inexplicably showing up in the CONSTANTS value.

### Steps to Reproduce (for bugs)

[demo.zip](https://github.com/gradle/gradle/files/1419830/demo.zip)
1. Run the attached application and the tests from Java for the expected behavior.
1. Run the attached application using the gradle tasks `run` and `test` for the incorrect behavior.

### Your Environment

* OS: Windows 10
* Java version:
``` cmd
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```
* Gradle version:
```cmd
------------------------------------------------------------
Gradle 4.1
------------------------------------------------------------

Build time:   2017-08-07 14:38:48 UTC
Revision:     941559e020f6c357ebb08d5c67acdb858a3defc2

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
OS:           Windows 10 10.0 amd64
```

**Comment by bmuschko** [comment] 2017-10-27 23:09
I tried out running `./gradlew test` with Gradle 4.2.1, JDK 1.8.0_60 on MacOSX and it works for me. Maybe it's related to your JDK version or OS. You might want to play around with that a bit. Also try to run your project on a public CI e.g. Travis to see if it fails there.

**Comment by bmuschko** [comment] 2017-10-30 20:38
I am going to close this issue for now as I can't reproduce it on my machine. Please report back after being able to reproduce the issue on a public CI e.g. Travis.

BTW: The Wrapper you had checked in was broken. Please also fix that.

**Closed by bmuschko** 2017-10-30 20:38 UTC
Labels: from:contributor, in:core, in:testing
