### ISSUE TITLE
Add configureEach<T> shortcut for withType<T>().configureEach {

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#12266] opened 2020-02-18 11:37 UTC
### Expected Behavior

```kotlin
tasks.configureEach<JavaCompile> {
    // set JavaCompile parameters
}
```

It should lazily configure tasks that have `JavaCompile` type.

### Current Behavior

```kotlin
tasks.withType<JavaCompile>().configureEach {
    // This works, however, I find it is duplicated quite often
}
```

```kotlin
tasks.withType<JavaCompile> {
    // This works, however, it causes eager task creation :(
    // In other words, this pattern is error-prone :-/
}
```

```kotlin
tasks.configureEach {
    // this configures ALL the tasks :(
}
```

### Context

I find that lots of my Kotlin DSL scripts have `withType<X>().configureEach {` pattern, and it looks like `tasks.configureEach<T> {` might be helpful for core Gradle.

Taking into account that `configureEach` already exists, adding an extension like `tasks.configureEach<T> { ... }` makes perfect sense for me from the user perpsective.

**Comment by vlsi** [comment] 2020-02-18 11:48
Just in case, I know `withType<T>().configureEach {` [is considered to be the current best bet](https://github.com/gradle/gradle/issues/9832#issuecomment-507114952), however, it looks like that is a very common use case that might justify its own shortcut.

**Comment by big-guy** [comment] 2020-02-18 16:19
I think you're suggesting that we add a Kotlin DSL specific extension instead of adding a new method to DomainObjectCollection (what's suggested in #9832).  We do not want to do that sort of thing (special APIs for Kotlin and not for everything).

I'm going to close this as a dupe of #9832.  We were being cautious to add a bunch of new APIs at the time, but I agree that `withType(T).configureEach(Action)` could be shortened to `configureEach(T, Action)`.   I think this should use the same type parameters as we do `withType`.  I don't think we need to solve the problem that Paul raised. 

If you want to take a stab at a PR for adding this to `DomainObjectCollection`, I'm happy to take a look.

Thanks!

**Closed by big-guy** 2020-02-18 16:19 UTC
Labels: a:feature, from:contributor
