### ISSUE TITLE
Gradle 4.6-rc1 won't run TestEngines defined in the project itself

### ISSUE THREAD

**Issue by mvysny** [gradle/gradle#4418] opened 2018-02-17 20:07 UTC
It appears that Gradle 4.6 built-in support for JUnit5 only considers TestEngines from dependencies that are actually packaged as jars. If the TestEngine is on the classpath either as a `compile project(":foo")` dependency or defined directly in that very project itself, the test engine is not discovered by Gradle. The JUnit5 Gradle plugin also covers this case and correctly registers such TestEngines.

### Expected Behavior
All test engines should be considered and run.

### Current Behavior
Only test engines in jar dependencies are considered.

### Context
I'm building this project: https://github.com/mvysny/dynatest ; I define a TestEngine in the project itself and then I'm trying to run it with JUnit5 runner in tests. With Gradle JUnit5 plugin this worked; after upgrade to Gradle 4.6 this stopped working and Gradle will only detect the jupiter engine.

However, in a different project where dynatest is a jar dependency, this works flawlessly with Gradle 4.6 and the DynaTest TestEngine is detected and run.

### Steps to Reproduce (for bugs)
1. git clone https://github.com/mvysny/dynatest
2. `./gradlew`
3. Only the jupiter engine tests were run; since the DynaTest TestEngine is not discovered and used, CalculatorTest and other tests are not run.

### Your Environment
openjdk version "1.8.0_151"; ubuntu 17.10 x86-64

**Comment by blindpirate** [comment] 2018-02-18 12:39
Thanks for reporting. I strongly suspect it's due to JUnit 5's service loading mechanism. According to the [userguide](https://junit.org/junit5/docs/current/user-guide/#launcher-api-engines-custom):

> Engine registration is currently supported via Java’s java.util.ServiceLoader mechanism

And [JDK doc](https://docs.oracle.com/javase/7/docs/api/java/util/ServiceLoader.html) says:

> Service providers can be installed in an implementation of the Java platform in the form of extensions, that is, jar files placed into any of the usual extension directories.

Currently, we provide the project classpath as a directory, I think that's where this issue comes from. @marcphilipp could you please confirm my speculation?

On the other side, I think it's pretty reasonable for a `TestEngine` to be implemented as a separated project. Would you like to try [composite build](https://docs.gradle.org/current/userguide/composite_builds.html), which I think suitable for your case.

**Comment by marcphilipp** [comment] 2018-02-18 14:17
Running with `--debug` shows the root cause:

```
15:08:47.078 [DEBUG] [TestEventLogger] Gradle Test Executor 3 STANDARD_ERROR
15:08:47.079 [DEBUG] [TestEventLogger]     Feb 18, 2018 3:08:47 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
15:08:47.079 [DEBUG] [TestEventLogger]     WARNING: TestEngine with ID 'DynaTest' failed to discover tests
15:08:47.079 [DEBUG] [TestEventLogger]     java.lang.ClassCastException: com.github.mvysny.dynatest.Calculator cannot be cast to com.github.mvysny.dynatest.DynaTest
15:08:47.079 [DEBUG] [TestEventLogger]          at com.github.mvysny.dynatest.DynaTestEngine.discover(DynaTestEngine.kt:51)
15:08:47.079 [DEBUG] [TestEventLogger]          at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:130)
15:08:47.079 [DEBUG] [TestEventLogger]          at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:117)
15:08:47.080 [DEBUG] [TestEventLogger]          at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
15:08:47.080 [DEBUG] [TestEventLogger]          at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:94)
15:08:47.080 [DEBUG] [TestEventLogger]          at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$100(JUnitPlatformTestClassProcessor.java:80)
15:08:47.080 [DEBUG] [TestEventLogger]          at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:71)
15:08:47.080 [DEBUG] [TestEventLogger]          at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
15:08:47.081 [DEBUG] [TestEventLogger]          at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:08:47.081 [DEBUG] [TestEventLogger]          at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:08:47.081 [DEBUG] [TestEventLogger]          at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:08:47.081 [DEBUG] [TestEventLogger]          at java.base/java.lang.reflect.Method.invoke(Method.java:564)
15:08:47.081 [DEBUG] [TestEventLogger]          at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
15:08:47.081 [DEBUG] [TestEventLogger]          at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
15:08:47.081 [DEBUG] [TestEventLogger]          at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
15:08:47.082 [DEBUG] [TestEventLogger]          at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
15:08:47.082 [DEBUG] [TestEventLogger]          at com.sun.proxy.$Proxy3.stop(Unknown Source)
15:08:47.082 [DEBUG] [TestEventLogger]          at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:123)
15:08:47.082 [DEBUG] [TestEventLogger]          at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:08:47.082 [DEBUG] [TestEventLogger]          at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:08:47.083 [DEBUG] [TestEventLogger]          at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:08:47.083 [DEBUG] [TestEventLogger]          at java.base/java.lang.reflect.Method.invoke(Method.java:564)
15:08:47.083 [DEBUG] [TestEventLogger]          at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
15:08:47.083 [DEBUG] [TestEventLogger]          at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
15:08:47.083 [DEBUG] [TestEventLogger]          at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
15:08:47.083 [DEBUG] [TestEventLogger]          at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
15:08:47.083 [DEBUG] [TestEventLogger]          at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
15:08:47.084 [DEBUG] [TestEventLogger]          at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
15:08:47.084 [DEBUG] [TestEventLogger]          at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
15:08:47.084 [DEBUG] [TestEventLogger]          at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
15:08:47.084 [DEBUG] [TestEventLogger]          at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
15:08:47.084 [DEBUG] [TestEventLogger]          at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
15:08:47.084 [DEBUG] [TestEventLogger]          at java.base/java.lang.Thread.run(Thread.java:844)
```

This shows that the DynaTest TestEngine is in fact registered and asked to discover tests. However, it does not handle the case of a `ClassSelector` that is not an instance of `DynaTest` (it should just ignore those).

The difference between the JUnit5 Gradle plugin and the Gradle's built-in support is that the former uses a class name pattern of `.*Tests?$` by default and thus did not create a `ClassSelector` for the `Calculator` class.

Thus, this is not an issue with Gradle's built-in support but needs to be fixed in the DynaTest TestEngine.

**Comment by blindpirate** [comment] 2018-02-18 14:24
Thanks @marcphilipp for the excellent analysis. I'll close this and please feel free to reopen.

**Closed by blindpirate** 2018-02-18 14:24 UTC
Labels: a:bug, from:contributor

**Comment by mvysny** [comment] 2018-02-18 19:11
I have just recently realized that JUnit5 crashes when there are no TestEngines; since it doesn't then that means that DynaTest TestEngine is in fact discovered. But @marcphilipp was faster...

I'm very sorry to waste your time, I should have figured this out. I just thought that if there would be any Exception then Gradle would fail...
