### ISSUE TITLE
Annotation processor handling does not support preview enabled, Java 14 JAR

### ISSUE THREAD

**Issue by Randgalt** [gradle/gradle#12680] opened 2020-03-31 02:21 UTC
### Expected Behavior

Gradle should not throw an error on a valid Java 14, preview enabled, annotation processor JAR.

### Current Behavior

Build fails with message:

```
Preview features are not enabled for io/soabase/recordbuilder/processor/RecordBuilderProcessor (class file version 58.65535). Try running with '--enable-preview'
```

### Context

I have an annotation processor library that I would like to have work with Grade. It works with Maven.

### Steps to Reproduce 

Here's a build file. Use Gradle 6.3 and Java 14.

```gradle
plugins {
    // Apply the java plugin to add support for Java
    id 'java'
}

repositories {
    mavenCentral()
}

sourceCompatibility = 14

dependencies {
    annotationProcessor 'io.soabase.record-builder:record-builder-processor:1.6.ea'
    implementation 'io.soabase.record-builder:record-builder-core:1.6.ea'
}

tasks.withType(JavaCompile) {
    options.compilerArgs += '--enable-preview'
}
tasks.withType(Test) {
    jvmArgs += "--enable-preview"
}
```

### Your Environment

Build scan URL: https://gradle.com/s/mz25nvnx2mkcm

**Comment by melix** [comment] 2020-04-30 15:16
This isn't an easy fix. Basically the problem is classloading. The annotation processor class you're using is indeed using preview features (which, IMO, is not such a good idea because as you can see, it leaks to consumers which are then forced to use feature preview themselves).

However, when we load the Java compiler, we're doing that within a Java process itself: either the Gradle daemon (if, like in your example, not using forking), or using a compiler daemon. In both cases, because the annotation processor is going to be loaded in the _same_ process, it's this process which has to set `--enable-preview`, not the `JavaCompile` task.

As a consequence, a workaround is to add `--enable-preview` to the Gradle daemon options, for example in your `gradle.properties` file:

```
org.gradle.jvmargs=--enable-preview
```

**Comment by melix** [comment] 2020-04-30 15:31
Moving to the icebox as there's a simple workaround.

**Closed** 2020-04-30 15:56 UTC
Labels: @jvm, a:bug, from:contributor, in:jvm-ecosystem
