### ISSUE TITLE
Configuration hangs with FIle watcher. 

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#13754] opened 2020-07-10 16:06 UTC
### Current Behavior

Configuration took 15m+ until I killed it. 

Then on next gradle invocation I got this: 

```
> Could not create service of type FileAccessTimeJournal using GradleUserHomeScopeServices.createFileAccessTimeJournal().
   > Timeout waiting to lock journal cache (~/.gradle/caches/journal-1). It is currently in use by another Gradle instance.
```

I killed the gradle deamons and I rm'd the lock file, then it worked on the next try. 

### Steps to Reproduce 
Can't reproduce.

### Your Environment

macOS 10.14.6 (18G4032)
Gradle 6.5
AGP 4.0.0

org.gradle.unsafe.watch-fs=true

**Comment by wolfs** [comment] 2020-07-10 16:17
@yogurtearl Thank you for reporting.

So you ran three builds:
1. a build which did hang for 15m+ which you killed
2. a build which ran into `Timeout waiting to lock journal cache`
3. subsequent builds which worked

Which of those builds had file system watching enabled? All of them?

It also seems like you couldn't reproduce the problem afterwards, is that correct?

**Comment by yogurtearl** [comment] 2020-07-10 16:31
Yes, all of them had file watching enabled.
And the issue hasn't come back yet.

**Comment by wolfs** [comment] 2020-07-10 16:37
If you run into the problem again, could you please create a stack trace of the Gradle daemon process via `jstack`, so we see what is going on?

**Comment by lptr** [comment] 2020-07-14 21:40
@yogurtearl it would be best if you could reproduce with a recent Gradle nightly, too, especially since we are refactoring the whole macOS watcher in https://github.com/gradle/gradle/issues/13785. I'm going to close this now, please feel free to reopen if the problem comes back.

**Closed by lptr** 2020-07-14 21:40 UTC
Labels: @execution, a:bug, from:contributor
