### ISSUE TITLE
plugin maven-publish, Skipping task ':publishToMavenLocal' as it has no actions.

### ISSUE THREAD

**Issue by 785172550** [gradle/gradle#11436] opened 2019-11-21 05:46 UTC
### Expected Behavior
run Task :publishToMavenLocal and the artifact will be install to Maven Local Repository
($USER_HOME/.m2/repository)

### Current Behavior
$USER_HOME/.m2/repository can't find the artifact and the gradle log shows 
```
> Task :publishMavenPublicationToMavenLocal
Caching disabled for task ':publishMavenPublicationToMavenLocal' because:
  Build cache is disabled
Task ':publishMavenPublicationToMavenLocal' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Publishing to maven local repository
:publishMavenPublicationToMavenLocal (Thread[Execution worker for ':' Thread 3,5,main]) completed. Took 0.025 secs.
:publishToMavenLocal (Thread[Daemon worker Thread 28,5,main]) started.

> Task :publishToMavenLocal
Skipping task ':publishToMavenLocal' as it has no actions.
:publishToMavenLocal (Thread[Daemon worker Thread 28,5,main]) completed. Took 0.0 secs.
```

besides, I can find it only creates a file in  build/publications/maven/pom-default.xml

### Steps to Reproduce 
1. config this

```
apply plugin: 'maven-publish'

publishing {
  publications {
    maven(MavenPublication) {
      from components.java
    }
  }
}

```
2. run gradle -i publishToMavenLocal

### Your Environment
gradle 5.5.1 
windows
intellj idea

**Comment by ljacomet** [comment] 2019-11-21 10:28
I cannot reproduce this. Even without a repository defined in the `publishing` block, publication to Maven local should work.
The fact that `publishToMavenLocal` logs 
> Skipping task ':publishToMavenLocal' as it has no actions.

is perfectly normal. It simply indicates this is a lifecycle task, used to anchor dependent tasks, not a task that performs work itself.

Note that for Gradle, the location of Maven local is determined the same way it is in Maven. So if you have a `settings.xml` that relocates it, Gradle will find and use that information.

Also the included snippet is incomplete since without applying a Java plugin, there would not be a `components.java` to use.

**Comment by ljacomet** [comment] 2020-02-18 09:18
Closing as no further information was provided and issue cannot be reproduced.

**Closed by ljacomet** 2020-02-18 09:18 UTC
Labels: @jvm, from:contributor, in:dependency-management

**Comment by wuwu2000** [comment] 2020-07-03 09:44
https://stackoverflow.com/questions/26577614/gradles-publishtomavenlocal-task-is-not-executed-correctly

**Comment by gulyas-istvan-netlock-hu** [comment] 2022-04-05 07:49
I have the same issue: the gradle publish stops refreshing my snapshot in local repo. It had worked in a past year, but local publish stopped working a week ago.

I have a multirepo, we cannot support the monorepo, so local publish is mandatory.

It say:
```
> Task :publishMavenJavaPublicationToMavenLocal
Caching disabled for task ':publishMavenJavaPublicationToMavenLocal' because:
  Build cache is disabled
Task ':publishMavenJavaPublicationToMavenLocal' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Publishing to maven local repository
:publishMavenJavaPublicationToMavenLocal (Thread[Execution worker for ':',5,main]) completed. Took 0.016 secs.
:publishToMavenLocal (Thread[Execution worker for ':',5,main]) started.

> Task :publishToMavenLocal
Skipping task ':publishToMavenLocal' as it has no actions.
:publishToMavenLocal (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:build (Thread[Execution worker for ':',5,main]) started.
```

The maven local repository contains the old version of snapshot jars only.

**Comment by sgammon** [comment] 2023-08-30 00:08
this happened to us because, for some reason, the `maven` publication wasn't being created before it was used/configured. just a hint to anyone stumbling across this -- you can halt the Gradle build in a debugger and inspect the set of publications; if it's empty, there will be "no actions" on the publish step.
