### ISSUE TITLE
New Catalogue API Feedback

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle#15674] opened 2021-01-03 04:36 UTC
Hey! I'm not sure where the right place is for this, so I hope this is ok. I've been tinkering with the upcoming catalogue API in 7.0 nightlies and wanted to share some feedback. Some of these might be bugs and one is a feature request

So far:
* Why do catalogues have to start with a lowercase letter? I know they are properties, but considering it's accessing a structured container it feels a bit of a superficial limitation.
* Failures to load are not super well-defined in the IDE. If it fails, it appears successful unless I go searching in IDE build logs
* While the top-level eventually indexes, none of the generated internals are deemed as accessible (see screenshot)

![image](https://user-images.githubusercontent.com/1361086/103471841-462e5d00-4d53-11eb-9c85-f1242aff1b0e.png)

* A common case we've solved is a library with a common group and multiple artifacts that are not all necessarily used together, but I don't see a way to describe this in dependencies toml files currently. Basically - we want a bundle but where you define them together and can consume a-la-carte. Some syntax ideas below:

```toml
# Currently requires this, which has a lot of duplication and potentially verbose
[versions]
retrofit = "2.9.0"

[dependencies]
retrofit = { group = "com.squareup.retrofit2", version.ref = "retrofit", name = "retrofit" }
retrofit-moshi = { group = "com.squareup.retrofit2", version.ref = "retrofit", name = "converter-moshi" }
retrofit-wire = { group = "com.squareup.retrofit2", version.ref = "retrofit", name = "converter-wire" }
retrofit-scalars = { group = "com.squareup.retrofit2", version.ref = "retrofit", name = "converter-scalars" }

# Option 1 - Works with existing syntax but can result in long lines due to inline map requirements in toml
[dependencies]
retrofit = { group = "com.squareup.retrofit2", version = "2.9.0", artifacts = { retrofit = "retrofit", moshi = "converter-moshi", wire = "converter-wire", scalars = "converter-scalars" } }

# Option 2 - Array of nested tables
[[dependencies.retrofit]]
group = "com.squareup.retrofit2"
version = "2.9.0"
  # 'name' is optional - use the key as the name if absent, in this case "retrofit"
  [dependencies.retrofit.retrofit]
  [dependencies.retrofit.moshi]
    name = "converter-moshi"
  [dependencies.retrofit.wire]
    name = "converter-wire"
  [dependencies.retrofit.scalars]
    name = "converter-scalars"

# Option 3 - Array of nested tables but properties are top-level
[dependencies.retrofit]
group = "com.squareup.retrofit2"
version = "2.9.0"
# Remaining keys are artifact names
retrofit = "retrofit"
moshi = "converter-moshi"
wire = "converter-wire"
scalars = "converter-scalars"
```

**Comment by ZacSweers** [comment] 2021-01-04 07:46
I should say - I think I'm personally partial to option 3. It's similar to option 1 but no top-level "artifacts" name (since that would require a separate block in toml I think

**Comment by madisp** [comment] 2021-01-11 19:30
Suggestion for "Option 3", having the "remaining keys" as artifact names feels a bit weird (sort of like at the wrong level of hierarchy). What about separating them out under a single sub-level? Something like a mix between Option 2 and Option 3:

```
[dependencies.retrofit]
group = "com.squareup.retrofit2"
version = "2.9.0"

[dependencies.retrofit.artifacts]
retrofit = "retrofit"
moshi = "converter-moshi"
wire = "converter-wire"
scalars = "converter-scalars"
```

**Comment by ZacSweers** [comment] 2021-03-08 01:27
@ljacomet should this maybe get the `affects-version:7.0` label?

**Comment by ljacomet** [comment] 2021-03-08 09:37
We are still looking into this feature. Its inclusion in 7.0 is not yet guaranteed. I've added the label.

Note that the IDE support is a known issue, see https://youtrack.jetbrains.com/issue/KTIJ-873

**Comment by ljacomet** [comment] 2021-03-18 14:58
Thanks for the feedback. The good news is that the feature will be part of 7.0!

Some answers on the different items:
* There is no plan to relax the current naming limitations on the different components of the feature
* Is this similar to #16250? If yes, we are looking into making it better.
* Answered in my previous message already
* We have no plans to make the content of the TOML file more structured. We are aiming for the right balance between readability and convenience. For example, extracting versions is a critical feature. Suppressing repetition for groups declaration is not. However based on this feedback, there might be later improvements to the API in `Settings`.

**Comment by JavierSegoviaCordoba** [comment] 2021-03-18 15:11
@ljacomet Is it documented?

**Comment by ljacomet** [comment] 2021-03-18 15:27
The documentation is available in the 7.0 milestones, or even the nightlies. For example: https://docs.gradle.org/7.0-milestone-3/userguide/platforms.html

Note that this is still being reviewed and fixed / improved for the release.

**Comment by shekibobo** [comment] 2021-04-01 18:29
I'm not sure if it's okay to add to this discussion here, but I have a bit of input on bundles.

 I like the idea of bundles, but would be better if I could say what the dependency should be included with, i.e. kapt, implementation, api, etc. If I want to bundle dagger, I’d like to be able to just do that and have all the things imported with the right protocol. If there's somewhere else I should put this, or I should create a new issue, let me know.

**Comment by ljacomet** [comment] 2021-04-02 07:34
Thanks for the feedback. It is by design that the version catalog only deals with coordinates and versions and not with usage or variants (includes legacy classifier).

**Comment by ljacomet** [comment] 2021-11-03 09:58
Closing as the version catalog feature has evolved but some of the requests made here did not make it in and we are looking at stabilization for Gradle 7.4

**Closed by ljacomet** 2021-11-03 09:58 UTC
Labels: a:feature, affects-version:7.0, in:dependency-version-catalog
