### ISSUE TITLE
Configuration Cache fails to load after Dynamic Version TTL expires.

### ISSUE THREAD

**Issue by eliottgray2** [gradle/gradle#17563] opened 2021-06-28 18:05 UTC
### Expected Behavior
* After the [TTL expires for a dependency with a Dynamic Version](https://docs.gradle.org/current/userguide/dynamic_versions.html#sec:controlling_dependency_caching_programmatically), the configuration cache should be updated with the newly-resolved-version, and should subsequently function. 

### Current Behavior
* After TTL expires, the current configuration cache may never again successfully load, resulting in the following message: `Calculating task graph as configuration cache cannot be reused because cached version information for <foo> has expired.`

### Context
I work with code that has the following properties:
* Dynamic versions
* Many dependencies
* Multiple repositories to resolve
* Long configuration

As a consequence of the above, enabling the configuration cache is a high priority.

### Steps to Reproduce 
1) Add a dependency with a dynamic version.  Can be a transitive dependency or not.
2) Add a repository to the build script that does not contain that dependency.
3) Enable the configuration cache for builds.
4) Wait for the TTL to expire for dynamic versions.
5) (Optional) Lower the TTL to speed up the expiration of the version.

Toy script that causes this bug:
```
plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.5.10'
}
group 'org.example'
version '1.0-SNAPSHOT'
repositories {
    mavenCentral()
    maven { url 'https://oss.jfrog.org/artifactory/oss-snapshot-local' } // ENABLE THIS LINE TO TRIGGER BUG
}
configurations.all {
    resolutionStrategy.cacheDynamicVersionsFor(1, "minutes")  // TIMEOUT QUICKLY TO TRIGGER BUG
}
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
    implementation "io.sentry:sentry:1.7.+"  // DYNAMIC DEPENDENCY TO TRIGGER BUG
}
```

Subsequent builds will succeed with the configuration cache, until the TTL expires, after which the cache will never load:
```
eliottgray@ip-192-168-86-49 testGradle % ./gradlew build --configuration-cache --refresh-dependencies
Configuration cache is an incubating feature.
Calculating task graph as configuration cache cannot be reused due to --refresh-dependencies

BUILD SUCCESSFUL in 9s
2 actionable tasks: 2 up-to-date
Configuration cache entry stored.

eliottgray@ip-192-168-86-49 testGradle % ./gradlew build --configuration-cache
Configuration cache is an incubating feature.
Reusing configuration cache.

BUILD SUCCESSFUL in 684ms
2 actionable tasks: 2 up-to-date
Configuration cache entry reused.

eliottgray@ip-192-168-86-49 testGradle % sleep 60

eliottgray@ip-192-168-86-49 testGradle % ./gradlew build --configuration-cache
Configuration cache is an incubating feature.
Calculating task graph as configuration cache cannot be reused because cached version information for io.sentry:sentry:1.7.+ has expired.

BUILD SUCCESSFUL in 1s
2 actionable tasks: 2 up-to-date
Configuration cache entry stored.

eliottgray@ip-192-168-86-49 testGradle % ./gradlew build --configuration-cache
Configuration cache is an incubating feature.
Calculating task graph as configuration cache cannot be reused because cached version information for io.sentry:sentry:1.7.+ has expired.

BUILD SUCCESSFUL in 771ms
2 actionable tasks: 2 up-to-date
Configuration cache entry stored.

eliottgray@ip-192-168-86-49 testGradle % 

```

### Your Environment
Gradle 6.8, 6.9, 7.1

Build scan URL:
https://gradle.com/s/z2yae4ay3uawa

**Comment by bamboo** [comment] 2021-08-13 17:39
Thanks for the report, @eliottgray2, this will be fixed in Gradle 7.3. 

Until then, a suitable workaround would be to specify repository `content` rules as to avoid having modules with dynamic versions resolved against the wrong repositories. For example, the `repositories` block in the provided reproducer script could be changed to something like the following:
```groovy
            repositories {
                mavenCentral()
                maven {
                    url 'https://oss.jfrog.org/artifactory/oss-snapshot-local'
                    content {
                        excludeGroup 'io.sentry' // COMMENT THIS LINE TO TRIGGER BUG
                    }
                }
            }
```

**Closed** 2021-08-18 19:33 UTC
Labels: a:bug, in:configuration-cache, @configuration-cache

**Comment by bric3** [comment] 2022-12-01 10:50
@bamboo Is it fixed, I'm using Gradle 7.6

```properties
org.gradle.unsafe.configuration-cache=true
org.gradle.unsafe.configuration-cache-problems=warn
```

```
$ ./gradlew buildPlugin
Configuration cache is an incubating feature.
Calculating task graph as configuration cache cannot be reused because cached artifact information for io.github.bric3.fireplace:fireplace-swing:0.0.1-SNAPSHOT has expired.
```

**Comment by bamboo** [comment] 2022-12-05 14:56
Hi, @bric3.

If I get your message correctly, everything seems to be working as expected. `*-SNAPSHOT` versions are treated by Gradle as _changing modules_ so setting `resolutionStrategy.cacheChangingModulesFor(0, TimeUnit.SECONDS)` will cause the configuration cache entry to expire immediately.

Did you expect different behavior?

**Comment by bric3** [comment] 2022-12-07 09:25
Hi @bamboo 

Thanks for the reply I think my mental model of the configuration cache was leading me to think that _snapshot versions_ (as `0.0.1-SNAPSHOT` does not change) were not supposed to "change" the configuration as it's just downloading a new jar and dropping the whole configuration was not needed. 
So the configuration cache also requires the resolved jar to be the same?

**Comment by bric3** [comment] 2022-12-07 16:22
Ok makes sense. Again thanks for taking the time to reply!

Much appreciated
