### ISSUE TITLE
Subproject tasks don't run when Configuration Cache is enabled

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#27594] opened 2024-01-05 00:13 UTC
### Current Behavior

Subproject tasks don't run when Configuration Cache is enabled

### Expected Behavior

Subproject tasks ~don't~ run when Configuration Cache is enabled

### Context (optional)

I have a multimodule project

```
Root project 'cmr-tests'
+--- Project ':sp-with-html'
+--- Project ':sp-with-html-and-markdown'
+--- Project ':sp-with-markdown'
\--- Project ':sp-without-plugin'
```

I've set up a custom plugin in buildSrc that should aggregate the subprojects into the root project using a nightmarish amalgamation of Configurations/Attributes/Outgoing variants/artifact views/etc, AKA 'Gradle best practices'.

Aggregating works unless configuration cache is enabled.

Sometimes if I run the aggregating task repeatedly it will eventually make the tasks in the subprojects run!

### Steps to Reproduce

1. download [project.zip](https://github.com/gradle/gradle/files/13836584/project.zip)
2. Run `./gradlew :aggregateHtmlModules`
3. observe subproject tasks don't run, resulting in an error
    ```shell
    $ ./gradlew :aggregateHtmlModules --console=plain
    Reusing configuration cache.
    > Task :aggregateHtmlModules FAILED
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':aggregateHtmlModules'.
    > ////tmp/gradle-not-adding-dependency/sp-with-html/build/tmp/generatedHtmlRenderedFiles doesn't exist!
    
    * Try:
    > Run with --stacktrace option to get the stack trace.
    > Run with --info or --debug option to get more log output.
    > Run with --scan to get full insights.
    > Get more help at https://help.gradle.org.
    
    BUILD FAILED in 323ms
    1 actionable task: 1 executed
    Configuration cache entry reused.
    ```
4. Disable config cache `./gradlew :aggregateHtmlModules --no-configuration-cache`
5. Observe no error
    ```shell
    $ ./gradlew :aggregateHtmlModules --no-configuration-cache --console=plain --rerun 
    Type-safe project accessors is an incubating feature.
    > Task :buildSrc:checkKotlinGradlePluginConfigurationErrors
    > Task :buildSrc:generateExternalPluginSpecBuilders UP-TO-DATE
    > Task :buildSrc:extractPrecompiledScriptPluginPlugins UP-TO-DATE
    > Task :buildSrc:compilePluginsBlocks UP-TO-DATE
    > Task :buildSrc:generatePrecompiledScriptPluginAccessors UP-TO-DATE
    > Task :buildSrc:generateScriptPluginAdapters UP-TO-DATE
    > Task :buildSrc:compileKotlin UP-TO-DATE
    > Task :buildSrc:compileJava NO-SOURCE
    > Task :buildSrc:compileGroovy NO-SOURCE
    > Task :buildSrc:pluginDescriptors UP-TO-DATE
    > Task :buildSrc:processResources UP-TO-DATE
    > Task :buildSrc:classes UP-TO-DATE
    > Task :buildSrc:jar UP-TO-DATE
    > Task :aggregateHtmlModules
    
    Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
    
    You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
    
    For more on this, please refer to https://docs.gradle.org/8.6-rc-1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
    
    BUILD SUCCESSFUL in 381ms
    11 actionable tasks: 2 executed, 9 up-to-date
    ```

   And observe files correctly generated in the build dir
    
    ```shell
    $ tree build
    build
    └── tmp
      └── aggregateHtmlModules
          ├── _sp_with_html
          └── _sp_with_html_and_markdown
    ```

### Gradle version

8.6-rc-1

**Comment by cobexer** [comment] 2024-01-11 13:32
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.
***
Your provided reproducer does not reproduce 8.3, 8.4, 8.5 or 8.6-RC1

**Comment by aSemy** [comment] 2024-01-16 23:43
Thanks for checking @cobexer. I've tried again and for some reason the error didn't trigger. Something weird with Config Cache.

Try running `./gradlew :aggregateHtmlModules` with the attached project

[project.zip](https://github.com/gradle/gradle/files/13956723/project.zip)

Even though the task `aggregateHtmlModules` depends on the output from some subprojects, the subproject tasks don't run.


```
./gradlew :aggregateHtmlModules --console=plain
Calculating task graph as configuration cache cannot be reused because file 'gradle.properties' has changed.
Type-safe project accessors is an incubating feature.
> Task :buildSrc:checkKotlinGradlePluginConfigurationErrors
> Task :buildSrc:generateExternalPluginSpecBuilders UP-TO-DATE
> Task :buildSrc:extractPrecompiledScriptPluginPlugins UP-TO-DATE
> Task :buildSrc:compilePluginsBlocks UP-TO-DATE
> Task :buildSrc:generatePrecompiledScriptPluginAccessors UP-TO-DATE
> Task :buildSrc:generateScriptPluginAdapters UP-TO-DATE
> Task :buildSrc:compileKotlin UP-TO-DATE
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources UP-TO-DATE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :aggregateHtmlModules UP-TO-DATE

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.6-rc-1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 776ms
11 actionable tasks: 1 executed, 10 up-to-date
Configuration cache entry stored.
```

If you uncomment the manual task dependencies in the root project, then the task runs correctly.


```
  // uncomment these lines
  dependsOn(":sp-with-html:generatedHtmlRenderedFiles")
  dependsOn(":sp-with-html-and-markdown:generatedHtmlRenderedFiles")
```



```text
./gradlew :aggregateHtmlModules --console=plain
Calculating task graph as configuration cache cannot be reused because file 'build.gradle.kts' has changed.
Type-safe project accessors is an incubating feature.
> Task :buildSrc:checkKotlinGradlePluginConfigurationErrors
> Task :buildSrc:generateExternalPluginSpecBuilders UP-TO-DATE
> Task :buildSrc:extractPrecompiledScriptPluginPlugins UP-TO-DATE
> Task :buildSrc:compilePluginsBlocks UP-TO-DATE
> Task :buildSrc:generatePrecompiledScriptPluginAccessors UP-TO-DATE
> Task :buildSrc:generateScriptPluginAdapters UP-TO-DATE
> Task :buildSrc:compileKotlin UP-TO-DATE
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources UP-TO-DATE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE

> Task :aggregateHtmlModules
[:aggregateHtmlModules] got module modules.CoolModuleSpec_Decorated@28e476a4
[:aggregateHtmlModules] got module modules.CoolModuleSpec_Decorated@6de6fddc

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.6-rc-1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 748ms
11 actionable tasks: 2 executed, 9 up-to-date
Configuration cache entry stored.
```

**Comment by cobexer** [comment] 2024-01-18 13:43
> Even though the task aggregateHtmlModules depends on the output from some subprojects, the subproject tasks don't run.

Can you point us to how you set up that relation?
Please check the documentation for [sharing outputs](https://docs.gradle.org/current/userguide/cross_project_publications.html#header)
Also please help us help you by providing minimal reproducers so there is no unrelated code in the reproducer!
Currently your project contains dead code, commented out code, ...

**Comment by aSemy** [comment] 2024-01-18 16:08
> Can you point us to how you set up that relation? 

The subprojects add outputs to the configurations, for example

```kotlin
// sp-with-html/build.gradle.kts

// ...

coolDependenciesHtml
  .variantRenderedFiles
  .outgoing
  .artifact(generatedHtmlRenderedFiles) {
    type = "directory"
  }
```


> Please check the documentation for [sharing outputs](https://docs.gradle.org/current/userguide/cross_project_publications.html#header)

Thanks for the suggestion but unfortunately I don't find that documentation page very helpful https://github.com/gradle/gradle/issues/18846.

While it is technically possible to share files between subprojects, the limitations are surprising and it's a minefield of bugs and undocumented/flaky behaviour. The point of the reproducer is to try and discover ways to workaround these problems. 

I did remove as much of the unrelated code as possible, but usually when I remove more then it fix the problem at hand, but it causes other problems, or not provide a way to achieve the behaviour that Gradle is supposed to support (sharing files between subprojects).

**Comment by ov7a** [comment] 2024-04-08 08:25
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by abstratt** [comment] 2024-04-10 20:26
One issue here is that the aggregating task does not depend on the subprojects tasks, so the subprojects tasks do not actually run. 

The main difference between running with the configuration cache and without the configuration cache, is that the task graph with CC only contains the tasks that are actually going to execute. 

The reason the output directory required by the aggregating task only exists when CC is off is because `FormatRendererTask` declares a property as `@OutputDirectory`,  and that alone is enough for the directory to be created for free,  even if the task is not executed.

I "addressed" the problem by making `AggregateModulesTask` depend on `FormatRendererTask`.  

@aSemy Please let me know if my analysis is off.

**Comment by abstratt** [comment] 2024-04-12 04:10
I ended up taking back some of what I wrote above. I left the bits that I believe still apply. This does not seem to be about whether tasks in subprojects are not being executed (they are never executed as far as I could tell). That is true no matter the configuration cache is enabled or not. 

Instead, the issue seems to be about whether a tasks' temporary directory (which is provisioned when `getTemporaryDir()` is invoked) is being created or not, and that (the task's private temporary directory not being created sometimes) seems to be reproducible only when the configuration cache is enabled.

In the project attached here, `getTemporaryDir()` is used to set the convention location for `outputDir` property in `FormatRendererTask` tasks:

https://github.com/abstratt/reproducer-27594/blob/main/buildSrc/src/main/kotlin/cool-plugin-base.gradle.kts#L17

```
tasks.withType<tasks.FormatRendererTask>().configureEach {
  outputDir.convention(layout.dir(provider { temporaryDir }))
}
```

**Comment by bamboo** [comment] 2024-04-12 10:27
That difference in behavior makes more sense now since `provider { temporaryDir }` would be executed at Configuration Cache store time when CC is on and at task execution time when CC is off.

I'm not sure `temporaryDir` is supposed to be used like that 🤔

**Comment by abstratt** [comment] 2024-04-12 14:48
I think I found reproducible steps:

```
./gradlew clean
rm -Rf .gradle/
./gradlew aggregateHtmlModules
./gradlew clean
./gradlew aggregateHtmlModules
```

**Comment by aSemy** [comment] 2024-04-16 14:12
Thank you for your efforts so far, I appreciate your updates.

I'm not sure how related `temporaryDir` is, but in case it helps I also see the same behaviour when not using `temporaryDir`:


```kotlin
tasks.withType<tasks.FormatRendererTask>().configureEach {
  val customTemp = File("build/blah/$name")
  customTemp.mkdirs()
  outputDir.convention(layout.dir(provider { customTemp }))
  doFirst {
    customTemp.mkdirs()
  }
}
```


```
Calculating task graph as configuration cache cannot be reused because an input to plugin class 'org.gradle.kotlin.dsl.plugins.precompiled.PrecompiledScriptPlugins' has changed.
Type-safe project accessors is an incubating feature.
> Task :buildSrc:checkKotlinGradlePluginConfigurationErrors
> Task :buildSrc:generateExternalPluginSpecBuilders UP-TO-DATE
> Task :buildSrc:extractPrecompiledScriptPluginPlugins
> Task :buildSrc:compilePluginsBlocks UP-TO-DATE
> Task :buildSrc:generatePrecompiledScriptPluginAccessors
> Task :buildSrc:generateScriptPluginAdapters
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources UP-TO-DATE
> Task :buildSrc:compileKotlin
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar

> Task :aggregateHtmlModules FAILED
[:aggregateHtmlModules] got module modules.CoolModuleSpec_Decorated@3ad7501e

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.6-rc-1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
11 actionable tasks: 7 executed, 4 up-to-date
Configuration cache entry stored.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':aggregateHtmlModules'.
> /dev/project/sp-with-html/build/blah/generatedHtmlRenderedFiles doesn't exist!

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 2s
16:10:29: Execution finished 'aggregateHtmlModules'.
```

**Comment by abstratt** [comment] 2024-04-16 22:21
@aSemy You are right, the issue with `getTemporaryDir()` is a different matter. 

We tweaked a bit your project, like here:

<img width="1591" alt="Screenshot 2024-04-16 at 19 10 30" src="https://github.com/gradle/gradle/assets/2187522/cdc64dcb-14c5-439b-aca4-dabfe666aeff">

The call to `filter()` in `ArtifactCollection` resolves to Kotlin's standard `Iterable.filter()` extension, which is eager is defeats dependency tracking.

`printHtmlRenderedFiles` and `printMarkdownRenderedFiles` where adapted like this:

<img width="1627" alt="Screenshot 2024-04-16 at 19 15 19" src="https://github.com/gradle/gradle/assets/2187522/85d484f6-03b4-4d33-a59e-122a597246af">

That shows dependencies being correctly tracked:

```
./gradlew :clean :printHtmlRenderedFiles --console=plain --configuration-cache
Calculating task graph as no cached configuration is available for tasks: :clean :printHtmlRenderedFiles
Type-safe project accessors is an incubating feature.
> Task :buildSrc:checkKotlinGradlePluginConfigurationErrors
> Task :buildSrc:generateExternalPluginSpecBuilders UP-TO-DATE
> Task :buildSrc:extractPrecompiledScriptPluginPlugins UP-TO-DATE
> Task :buildSrc:compilePluginsBlocks UP-TO-DATE
> Task :buildSrc:generatePrecompiledScriptPluginAccessors UP-TO-DATE
> Task :buildSrc:generateScriptPluginAdapters UP-TO-DATE
> Task :buildSrc:compileKotlin UP-TO-DATE
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources UP-TO-DATE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :clean
> Task :sp-with-html-and-markdown:generatedHtmlRenderedFiles
> Task :sp-with-html:generatedHtmlRenderedFiles

> Task :printHtmlRenderedFiles
got 2 files:
 - /Users/rafael/sources/repros/reproducer-27594b/sp-with-html/build/tmp/generatedHtmlRenderedFiles
 - /Users/rafael/sources/repros/reproducer-27594b/sp-with-html-and-markdown/build/tmp/generatedHtmlRenderedFiles

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.6-rc-1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 954ms
14 actionable tasks: 5 executed, 9 up-to-date
Configuration cache entry stored.
``` 

For `aggregateHtmlModules`, you should be able to follow the same approach.

**Comment by aSemy** [comment] 2024-04-23 07:48
Hi @abstratt. Thanks again for your efforts.

It's not clear from your screenshot, but I think you commented out the `.filter { artifact -> ... }` section?

If so, I tried modifying the code as suggested, but then `gradle aggregateHtmlModules` fails.

```
* What went wrong:
Could not determine the dependencies of task ':aggregateHtmlModules'.
> missing PROJECT_PATH attribute in resources (project :sp-without-plugin)
```

This is because in some random situations Gradle will ignore the attributes, and fetch files that don't match the requested attributes. The filtering is necessary, because Gradle doesn't provide any other way of making attributes required. I did request this functionality https://github.com/gradle/gradle/issues/27991, but it was refused.

**Comment by abstratt** [comment] 2024-04-23 13:03
Hi @aSemy, sorry if my response was too vague.

The main point I intended to convey is that as long as you stay clear from using API that causes the eager realization of providers, task dependencies should be preserved. If some filtering or transformation/mapping needs to be done, it is important to use dependency-preserving API (for instance, `Provider.map` or `Provider.filter`).

> This is because in some random situations Gradle will ignore the attributes, and fetch files that don't match the requested attributes.

Is there an issue reported for this specific behavior? This seems to be what needs to be addressed. Does that behave differently w.r.t. configuration cache being enabled or not?

**Comment by aSemy** [comment] 2024-04-23 22:19
> Hi @aSemy, sorry if my response was too vague.
> 
> The main point I intended to convey is that as long as you stay clear from using API that causes the eager realization of providers, task dependencies should be preserved. If some filtering or transformation/mapping needs to be done, it is important to use dependency-preserving API (for instance, `Provider.map` or `Provider.filter`).

That makes sense, but the situation is confusing because the code does use `Provider.map {}`. I had expected that would be enough, even if Kotlin's `Collection.filter {}` is apparently incompatible with the Provider API.

> > This is because in some random situations Gradle will ignore the attributes, and fetch files that don't match the requested attributes.
> 
> Is there an issue reported for this specific behavior? This seems to be what needs to be addressed. Does that behave differently w.r.t. configuration cache being enabled or not?

Yes, it would be really nice if the actual functionality was addressed, and there wasn't any need for these bug-triggering workarounds.

I don't think it's related to CC.

Dokkatoo has two open issues relating to this

* https://github.com/adamko-dev/dokkatoo/issues/165
* https://github.com/adamko-dev/dokkatoo/issues/170

I've tried reporting it a few times.

* https://github.com/gradle/gradle/issues/23776
* https://github.com/gradle/gradle/issues/28053

There's also a reproducer project here: https://github.com/martinbonnin/reproducer-attributes

And, as I mentioned above, I tried asking for a feature https://github.com/gradle/gradle/issues/27991, but frankly I don't think it was taken seriously.  Apparently a 'category' attribute is treated as a required attribute..?? It's patently not, and doesn't help with the reproducer in this issue.

Thanks again, I really appreciate you engaging with this.

**Comment by abstratt** [comment] 2024-04-25 14:01
> That makes sense, but the situation is confusing because the code does use Provider.map {}. I had expected that would be enough, even if Kotlin's Collection.filter {} is apparently incompatible with the Provider API.

The tricky bit is that some Gradle types are also Java collections or `Iterable`. For instance, `FileCollection` extends `Iterable`. `FileCollection`'s own `filter(Closure)` or `filter(Spec)` produce live views. `FileTree` also provide `matching` methods for filtering. Now, the `Iterable` protocol (and any `Iterable`-based extension functions Kotlin provides), or `FileCollection.files` or `FileCollection.elements` provide you with a snapshot of the current contents of the collection.

**Comment by abstratt** [comment] 2024-04-25 15:34
@aSemy If you could provide an example of using the Gradle API in that model is not preserving task dependencies, please provide a reproducer that is as small as possible and will look into it. Otherwise, there is not much purpose left for this issue. 

Regarding issues that require installing your plugin to be reproduced, I suggest you try to find the exact revision of the plugin that causes the problem to appear, hopefully its diff will allow you to pinpoint a change in the way the Gradle API was being used that introduced the unexpected behavior.

**Comment by aSemy** [comment] 2024-05-01 18:23
@abstratt From what I understand from your explanation, this is the relevant part of the above reproducer that isn't preserving task dependencies:

```kotlin
// buildSrc/src/main/kotlin/CoolDependencyContainer.kt

// ...

    val incomingArtifacts =
      baseIncomingResolver.map { incoming ->
        incoming.incoming
          .artifactView {
            withVariantReselection()
            attributes {
              attribute(USAGE_ATTRIBUTE, coolPluginUsage)
              attribute(COOL_TYPE, type)
              attribute(COOL_VARIANT, variantAttribute)
            }
            lenient(true)
          }
          .artifacts
          .filter { artifact ->
            val valid = artifact.variant.attributes.getAttribute(COOL_VARIANT) == variantAttribute
            when {
              !valid -> logger.info("warning - got invalid type ${artifact.id} ${artifact.id::class.simpleName}  | attributes:${artifact.variant.attributes.toMap()} ")
              else   -> logger.info("got valid type ${artifact.id} ${artifact.id::class.simpleName}  | attributes:${artifact.variant.attributes.toMap()} ")
            }
            valid
          }
      }
```

The docs [here](https://docs.gradle.org/8.7/userguide/lazy_configuration.html) indicate that `.map {}` preserves task dependencies, but it seems some situations it's possible to break this behaviour. Usually it's possible to work around it. However, when using `map {}` + `artifactView {}` there is no workaround.

It's also not clear to me why the reproducer works when configuration cache is disabled.

**Comment by abstratt** [comment] 2024-05-07 12:17
@aSemy The loss of dependencies should not be due to `artifactView`, but due to invoking `Iterable.filter()` on  the `ArtifactCollection` returned by `ArtifactView.getArtifacts()`.

**Comment by abstratt** [comment] 2024-05-21 13:18
This issue will be closed as a duplicate of

* #29238

I already included the present issue as a use case there, please 👍 to that issue. It a fairly general one, and may not cover all that is needed your specific use case (say, can't do X in a lazy way), so please feel free to open a specific feature request for API that would allow you to write code that behaves correctly (without resorting to eager realization).

If you think our analysis is wrong, please provide us with more detailed information explaining why.

Regarding enablement of configuration caching being required to reproduce the present issue, the Configuration Cache does affect the actual behavior of existing code (timing of execution, for one - for instance, most providers are automatically resolved at configuration store time, whereas without the configuration cache, they would be resolved during execution, and only if requested).

**Comment by abstratt** [comment] 2024-05-21 13:19
Duplicate of #29238

**Closed** 2024-05-21 13:20 UTC
Labels: a:bug, in:configuration-cache, in:multi-projects
