### ISSUE TITLE
The default encoding for gradle6.7 is not utf8

### ISSUE THREAD

**Issue by LY1806620741** [gradle/gradle#16514] opened 2021-03-14 01:30 UTC
### Expected Behavior

I didn't add any configuration. Expect it to default on utf8

### Current Behavior

groovy:
```groovy
//tasks.withType(JavaCompile) { options.encoding = "UTF-8" }
test {
    System.getProperties().findAll{k,v -> k.contains("encoding")}.forEach{k,v -> println(k+" "+v)}
    println(System.getProperties().getProperty("file.encoding",""))
    println(getDefaultCharacterEncoding())
//    setDefaultCharacterEncoding("utf-8")
    useJUnitPlatform()
}
```
output:
```
> Configure project :jdk8
file.encoding GBK
sun.jnu.encoding GBK
sun.io.unicode.encoding UnicodeLittle
GBK
GBK
```

### Steps to Reproduce 

1. run a java application with idea+gradle
2. and it compile error

### Your Environment

Build scan URL:
https://gradle.com/s/lrx2bu5xfyg3s

**Comment by bmuskalla** [comment] 2021-04-09 13:17
Agreed. This isn't quite easy without breaking too many people but certainly something we're interested in. For now, I'll mark this as a duplicate of #16763

**Closed by bmuskalla** 2021-04-09 13:17 UTC
Labels: a:bug
