### ISSUE TITLE
Upgrade Bouncy Castle dependency

### ISSUE THREAD

**Issue by aalmiray** [gradle/gradle#16585] opened 2021-03-19 14:21 UTC
### Expected Behavior
Gradle provides the latest version (currently at `1.68`) of the Bouncy Castle JARs it requires in core plugins.

### Current Behavior
Gradle provides version `1.64` of the Bouncy Castle JARs.

### Context
Encountered `java.lang.NoSuchMethodError: 'void org.bouncycastle.openpgp.PGPSignatureSubpacketGenerator.addSignerUserID(boolean, java.lang.String)` when testing a plugin that relies on `bcpg-jdk15on-1.68.jar` however the wrong class file was loaded because Gradle brings in `bcpg-jdk15on-1.64.jar`.

**WARNING**: binary compatibility between versions `1.64` and `1.68`.

**Comment by melix** [comment] 2021-03-19 14:35
Would you mind sharing instructions about how to reproduce the `NoSuchMethodError`? My understanding of plugin classloading is the following (this is quite complex because of the classloader caching strategies we have to avoid loading the same classes multiple times when different projects have the same classpath):

- we isolate the dependencies used by Gradle itself from the build scripts. For example, it's not possible to use types from Bouncycastle in a build script unless you add the dependency to BC in your build script
- same for a plugin, you can't use Bouncycastle in a plugin without adding an explicit version of BC on your plugin dependencies

That is to say I would expect that your plugin can load whatever version of BC it needs.

What wouldn't work, however, is if you have 2 different plugins asking for different versions of BC. Then usual conflict resolution should kick in. There is a reason for this because all in all, in the context of the execution of a build script, a single class should be visible. For example a build script should see types declared in plugins or dependencies of plugins, so it must be able to unequivocally refer to a single class.

Use of the `plugins { ... }` block vs `buildscript {...}` _may_ be at play there too.

All in all, dependencies that Gradle use _internally_ shouldn't have an influence on what you want to use (except for Groovy, because that's the language of the build scripts).

This test, for example, shows that we can use a different Guava version in a plugin, than the one Gradle bundles: https://github.com/gradle/gradle/blob/d798519c4f13f91fb6192cae3a87d51234f34955/subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/impldeps/GradleImplDepsVisibilityIntegrationTest.groovy#L49-L73

It seems you have an example proving that something doesn't quite work.

**Comment by ljacomet** [comment] 2021-03-19 14:48
As a side note, bouncycastle is updated to 1.68 for Gradle 7.0.

**Comment by aalmiray** [comment] 2021-03-19 14:52
@ljacomet thanks for confirming the upgrade. I searched for a version number before raising this issue however I got lost in the build and could not find it.

**Comment by melix** [comment] 2021-03-19 14:56
> however I got lost in the build and could not find it.

version catalogs FTW \o/ (brace yourselves, 7.0 is coming!)

**Comment by aalmiray** [comment] 2021-03-19 15:05
@melix the specific plugin is `jreleaser-gradle-plugin`. It consumes a sibling project the normal way

https://github.com/kordamp/jreleaser/blob/main/plugins/jreleaser-gradle-plugin/jreleaser-gradle-plugin.gradle

The sibling defines a dependency on BC also in a typical way

https://github.com/kordamp/jreleaser/blob/main/core/jreleaser-signer/jreleaser-signer.gradle

A sample project configured as:

*settings.gradle*
```groovy
pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenLocal()
    }
    plugins {
        id 'org.kordamp.gradle.java-project' version kordampPluginVersion
        id 'org.jreleaser'                   version '0.1.0-SNAPSHOT'
    }
}
```

*build.gradle*
```groovy
plugins {
    id 'java-library'
    id 'application'
    id 'org.kordamp.gradle.java-project'
    id 'org.jreleaser'
}

config {
    info {
        name          = rootProject.name
        description   = 'App'
        inceptionYear = '2021'

        specification { enabled = false }
    }

    bintray {
        enabled = false
    }
}

repositories {
    mavenCentral()
    mavenLocal()
}

jreleaser {
    project {
        longDescription = 'Sample app'
        website         = 'https://kordamp.org/app'
    }
  
    release {
        github {
            repoOwner = 'aalmiray'
            repoName  = 'app'
            overwrite = true
        }
    }

    announcers {
        sdkman {
            enabled = true
        }
        twitter {
            enabled = true
        }
        zulip {
            enabled = true
            account = 'announce-bot@kordamp.zulipchat.com'
            apiHost = 'https://kordamp.zulipchat.com/api/v1'
        }
    }
  
    sign {
        enabled = true
        armored = true
        keyRingFile = rootProject.layout.projectDirectory.file('/Users/aalmiray/.gnupg2/secring.gpg')
    }
}
```

This means the `org.jreleaser` plugin is resolved from Maven Local at the moment.

**Comment by melix** [comment] 2021-03-19 15:16
Thanks. There's indeed nothing suspicious here. I'd just expect it to work OOTB.

**Comment by aalmiray** [comment] 2021-03-19 15:26
I do recall that Gradle setups the BC provider with an utility class that registers it using a static initializer. Perhaps the old BC is loaded ahead of time. The code looks similar to

```java
    static {
        if (Security.getProvider(BouncyCastleProvider.PROVIDER_NAME) == null) {
            Security.setProperty("crypto.policy", "unlimited");
            Security.addProvider(new BouncyCastleProvider());
        }
    }
```

**Comment by big-guy** [comment] 2021-03-19 21:52
I'm going to close this (since we've updated BC in 7.0). @melix If there's something wrong here where we're leaking internal dependencies, let's open a new issue for it.

**Closed by big-guy** 2021-03-19 21:52 UTC
Labels: a:feature, from:contributor

**Comment by melix** [comment] 2021-03-22 09:03
Follow-up : https://github.com/gradle/gradle/issues/16605
