### ISSUE TITLE
Compilation Freezes on compileDebugUnitTestKotlin

### ISSUE THREAD

**Issue by herriojr** [gradle/gradle#17701] opened 2021-07-13 18:31 UTC
### Expected Behavior
It should successfully compile or fail, not freeze up.

### Current Behavior
It seems to freeze on compilation

### Context

This is an Android application, however, I don't believe this is something Android-specific. Someone modified a class and added arguments to its constructor. They forgot to add these arguments to the tests. Instead of compilation of the tests failing, it just tries to compile forever. For a step that generally takes two minutes, I can literally wait over an hour and it will still say it is compiling.

The step it is stuck on is :mobile:compileDebugUnitTestKotlin

### Steps to Reproduce 
I have been unable to identify the root cause of the issue so I am unable to provide steps to reproduce, however, this appears to happen when

1. mockk is in use
2. there is a large unit test file
3. the class under test had arguments added to its constructor, and a large number of arguments, but someone forgot to add new arguments to the the tests

If I could get instructions on adding logging from the compilation of the kotlin sources, that would help, however, I've been unsuccessful in getting any further output from kotlin. I attempted adding:
```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
        kotlinOptions {
            jvmTarget = '1.8'
            freeCompilerArgs += '-verbose'
        }
    }
```

I understand this isn't enough to go on, however, any help at obtaining more information about what's going on at this time when it freezes up will help me diagnose it further.

### Your Environment
OS X
gradle 6.7.1 (and 7.0)
java 11
kotlin 1.5.20 (verified all kotlin libraries are on the same version, reflect, stdlib, etc)

**Comment by mlopatkin** [comment] 2021-07-14 12:04
@herriojr could you please try to capture thread dumps of the Gradle daemon and the Kotlin compiler daemon when the freezing happens?

You can get PIDs of processes with `jps -l` - you'll see something like
```
27287 jdk.jcmd/sun.tools.jps.Jps
26764 org.jetbrains.kotlin.daemon.KotlinCompileDaemon
26893 org.jetbrains.kotlin.daemon.KotlinCompileDaemon
26559 org.gradle.launcher.daemon.bootstrap.GradleDaemon
```
Then you can capture thread dumps with `jstack -l -e PID > PID.txt` for each PID from the previous step. `KotlinCompileDaemon` and `GradleDaemon` are of interest.

Without this information, it might be too difficult to proceed with the investigation.

You may also try upgrading Kotlin to 1.5.21, there were some issues with 1.5.20 that may be resolved in the newer version.

**Comment by herriojr** [comment] 2021-07-14 16:05
@mlopatkin yes, I'll get it today, I just had no idea how to obtain useful information in this case, thanks for the help!

**Comment by herriojr** [comment] 2021-07-14 16:56
I've attached the requested files.

[39156.txt](https://github.com/gradle/gradle/files/6817735/39156.txt)
[93916.txt](https://github.com/gradle/gradle/files/6817736/93916.txt)
[93934.txt](https://github.com/gradle/gradle/files/6817737/93934.txt)
[94029.txt](https://github.com/gradle/gradle/files/6817738/94029.txt)

**Comment by herriojr** [comment] 2021-07-14 17:16
Also, unfortuantely, it is not fixed w/ kotlin 1.5.21

**Comment by mlopatkin** [comment] 2021-07-14 18:03
Thanks for the update! I don't see any blockings so the issue seems to be related to https://youtrack.jetbrains.com/issue/KT-47545. We cannot do much on the Gradle side because the issue is in the Kotlin compiler.

**Closed by mlopatkin** 2021-07-14 18:03 UTC
Labels: a:bug, to-triage

**Comment by herriojr** [comment] 2021-07-14 18:16
@mlopatkin awesome, thanks for the help! I'll go bug them instead :P
