### ISSUE TITLE
ClassCastException when verifying SSL certificates: `[B cannot be cast to java.lang.String`

### ISSUE THREAD

**Issue by ugrave** [gradle/gradle#3663] opened 2017-11-30 09:49 UTC
I update our gradle version from 4.3.1 to 4.4-rc-4. WIth the new version is not possible anymore to resolve dependencies from our nexus.

I found also an bug ticket for the apache http client:
https://issues.apache.org/jira/browse/HTTPCLIENT-1851

### Expected Behavior
Gradle resolved dependencies

### Current Behavior
Gradle throws exception on dependecy resolving the below:

   > Could not resolve org.asciidoctor:asciidoctor-gradle-plugin:1.5.6.
     Required by:
         project :
      > Could not resolve org.asciidoctor:asciidoctor-gradle-plugin:1.5.6.
         > Could not get resource 'https://MY_MAVEN_REPRO_URL/repository/maven-public/org/asciidoctor/asciidoctor-gradle-plugin/1.5.6/asciidoctor-gradle-plugin-1.5.6.pom'.
            > [B cannot be cast to java.lang.String

Stacktrace:
```
Caused by: org.gradle.api.resources.ResourceException: Could not get resource 'https://MY_MAVEN_REPRO_URL/repository/maven-public/io/spring/gradle/dependency-management-plugin/1.0.3.RELEASE/dependency-management-plugin-1.0.3.RELEASE.pom'.
        at org.gradle.internal.resource.ResourceExceptions.failure(ResourceExceptions.java:74)
        at org.gradle.internal.resource.ResourceExceptions.getFailed(ResourceExceptions.java:57)
        at org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver.downloadByCoords(DefaultExternalResourceArtifactResolver.java:138)
        at org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver.downloadStaticResource(DefaultExternalResourceArtifactResolver.java:95)
        at org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver.resolveArtifact(DefaultExternalResourceArtifactResolver.java:65)
        at org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver.parseMetaDataFromArtifact(ExternalResourceResolver.java:216)
        at org.gradle.api.internal.artifacts.repositories.resolver.MavenResolver.parseMetaDataFromArtifact(MavenResolver.java:170)
        at org.gradle.api.internal.artifacts.repositories.resolver.MavenResolver.parseMetaDataFromArtifact(MavenResolver.java:65)
        at org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver.resolveStaticDependency(ExternalResourceResolver.java:193)
        at org.gradle.api.internal.artifacts.repositories.resolver.MavenResolver.doResolveComponentMetaData(MavenResolver.java:145)
        at org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver$RemoteRepositoryAccess.resolveComponentMetaData(ExternalResourceResolver.java:467)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository$ResolveAndCacheRepositoryAccess.resolveComponentMetaData(CachingModuleComponentRepository.java:363)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.BaseModuleComponentRepositoryAccess.resolveComponentMetaData(BaseModuleComponentRepositoryAccess.java:50)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.memcache.InMemoryCachedModuleComponentRepository$CachedAccess.resolveComponentMetaData(InMemoryCachedModuleComponentRepository.java:95)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.resolveComponentMetaData(ErrorHandlingModuleComponentRepository.java:126)
        ... 143 more
Caused by: java.lang.ClassCastException: [B cannot be cast to java.lang.String
        at org.apache.http.conn.ssl.DefaultHostnameVerifier.getSubjectAltNames(DefaultHostnameVerifier.java:309)
        at org.apache.http.conn.ssl.DefaultHostnameVerifier.verify(DefaultHostnameVerifier.java:112)
        at org.apache.http.conn.ssl.DefaultHostnameVerifier.verify(DefaultHostnameVerifier.java:99)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:463)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:397)

```

### Steps to Reproduce (for bugs)
Use gradle wrapper in version 4.4-rc-4 and call gradlew build

### Your Environment
------------------------------------------------------------
Gradle 4.4-rc-4
------------------------------------------------------------
Build time:   2017-11-28 12:36:59 UTC
Revision:     f0a427cdb7eaa95779c9ccd8147878970fbb53fb
Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_91 (Oracle Corporation 25.91-b14)
OS:           Linux 4.10.0-37-generic amd64

**Comment by blindpirate** [comment] 2017-11-30 10:03
Thank you very much for reporting, we'll fix it soon.

**Comment by jjohannes** [comment] 2017-11-30 10:06
This may be caused by the upgrade of the `httpclient` library from `4.4.1` to `4.5.3`.

**Comment by wolfs** [comment] 2017-11-30 12:30
Re-opened: Let's find the root cause of the problem and verify that an `httpclient` downgrade fixes the issue.

**Comment by wolfs** [comment] 2017-11-30 12:39
This seems to be [this bug](https://issues.apache.org/jira/browse/HTTPCLIENT-1836) in httpclient 4.5.3. It seems like the bug will be fixed in 4.5.4.

**Comment by wolfs** [comment] 2017-11-30 12:56
@ugrave Could you try out the snapshot 4.4-20171130123424+0000 and see if this resolves your problem?

**Comment by ugrave** [comment] 2017-11-30 14:09
New version 4.4-20171130123424+0000 resolve the problem.

**Closed** 2017-11-30 14:46 UTC
Labels: a:bug, in:dependency-management
