### ISSUE TITLE
Ctrl-C when running Spring Application get no shutdown hooks

### ISSUE THREAD

**Issue by z0mb1ek** [gradle/gradle#1109] opened 2017-01-06 00:31 UTC
There is discuss there https://discuss.gradle.org/t/how-do-i-clean-up-an-application-when-sending-an-interrupt-ctrl-c-when-using-the-application-plugin/4880/3
I have a problem: when i SIGINT my application starting with application plugin - it not gracefully shutdown it(spring in my case), there is no any shutdown hooks, it term it! What can I do to use my spring application with shutdown hooks with gradle?

**Comment by pkubowicz** [comment] 2017-01-06 15:42
gradle run skips shutdown hooks when daemon enabled

### Expected Behavior
Shutdown hooks are executed like when I execute the JAR directly instead of calling 'gradle run'

### Current Behavior
`gradle run --daemon` never executes shutdown hooks after Ctrl+C is pressed. They are executed much later.

`gradle run --no-daemon` always executes shutdown hooks, but sometimes an exception is printed:
```
> Could not read standard output of: command '/usr/lib/jvm/jdk1.8.0_112/bin/java'.
java.io.IOException: Stream closed
        at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:291)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at java.io.FilterInputStream.read(FilterInputStream.java:107)
        at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:51)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

and no output printed by shutdown hooks is visible.

### Context
According to [documentation of Runtime#addShutdownHook()](https://docs.oracle.com/javase/8/docs/api/java/lang/Runtime.html#addShutdownHook-java.lang.Thread-) the JVM is obliged to execute registered shutdown hooks. Many libraries rely on it, for example they may perform some cleanup. Gradle breaks the contract.

Note that in current Gradle versions daemon is enabled by default, so the default behaviour of `gradle run` is an incorrect one.

I think this is not just the problem with 'application' plugin, but rather with the daemon itself. The same buggy behaviour happens with the third-party [shadow plugin](https://plugins.gradle.org/plugin/com.github.johnrengelman.shadow) and its 'shadowRun' task.

### Steps to Reproduce
build.gradle:
```
apply plugin: 'java'
apply plugin: 'application'

mainClassName = 'Runner'

jar.manifest {
    attributes('Main-Class': 'Runner')
}
```

src/main/java/Runner.java
```
import java.io.File;
import java.util.Random;
import java.util.concurrent.CompletableFuture;

public class Runner {
    public static void main(String[] args) throws Exception {
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            System.out.println("Clean shutdown");
        }));
        File lock = new File("LOCK" + new Random().nextInt(20));
        lock.createNewFile();
        lock.deleteOnExit();
        System.out.println("Created lock");
        new CompletableFuture<Void>().get();
    }
}
```

Run `gradle jar && java -jar build/libs/*.jar` and press Ctrl+C to see the expected behaviour. Now try `gradle run` - `LOCK` file will remain.

Try `gradle run --no-daemon` and Ctrl+C several times until you see the exception above - `Clean shutdown` won't be printed then, but the lock file will be deleted.

### Your Environment
Gradle 3.3 on Linux with Oracle Java 1.8.0_112-b15
 * Build scan URL: https://scans.gradle.com/s/bv2aziktystui#summary

**Comment by pkubowicz** [comment] 2017-01-06 15:45
A related StackOverflow question: http://stackoverflow.com/questions/22671927/shutdown-hook-of-java-process-doesnt-trigger-in-gradle-daemon

**Comment by z0mb1ek** [comment] 2017-01-06 15:47
I want to get some jvm arg on task, thats why --no-daemon is not the decision. I use spring boot plugin on maven projects and its work very well.

**Comment by lacasseio** [comment] 2017-01-06 18:33
I don't have an exact solution for this, but I can pitch in as to why you don't see the call to your shutdown hook. When the daemon is enabled, Gradle executes your build inside a remote process (not the process started from the command line called the launcher). This process is kept alive in between build to minimize the impact of the JVM startup and warmup. It means Ctrl-C executes on the launcher where your user code isn't running.

Two different possible solutions to explore:
1. Use a worker process to achieve what is required. A public API is in development for the worker process.
2. Use the internal build cancel event. It can be made public given enough interest from the community.

I hope this help your specific case.

**Comment by pkubowicz** [comment] 2017-01-06 19:20
My opinion is that this is a bug that needs to be fixed by the Gradle team. You tagged this issue as a 'question'. Application plugin is a core plugin embedded in the Gradle distribution and has to work correctly on default settings of Gradle, which enable daemon.

**Comment by lacasseio** [comment] 2017-01-06 21:51
Thanks @pkubowicz that make sense. I retagged it appropriately.

**Comment by pkubowicz** [comment] 2017-01-06 22:09
Thank you. Please note an another thing: if I develop a server application, I may use `gradle run` very frequently to test it locally. Currently when I press Ctrl+C during `gradle run`, not only are shutdown hooks not fired, but also the daemon is lost (`gradle --status` shows `CANCELED`). When I call gradle again, it will create a new daemon, which requires much time.

Ideally, Ctrl+C should only terminate the app, not the daemon. This is how continuous build option works and it is great.

**Comment by lacasseio** [comment] 2017-01-09 12:32
Thanks @pkubowicz for the additional information. I tried the code from this issue, and the behavior seems to follow what is expected with two minor details:
1. There is a, up to, 10 seconds delay between Ctrl-C and the execution of the shutdown hook.
2. The `System.out` output isn't piped to the console.

A Ctrl-C in the launcher causes the daemon to be `CANCELED` and killed which in turn will kill any child process. The `application` plugin use `JavaExec` task to run the application which in turn use the `Exec` task. The stream handler (stdout/stderr) is piped through the daemon to the launcher and finally to the console. When executing the Ctrl-C, the launcher is killed and cancel the daemon. At this point, nothing can be printed to the console from the daemon as the launcher is now gone. The delay between the Ctrl-C and the application shutdown hook is due to the amount of time the daemon takes to gracefully shutdown.

I understand those are not the expected behavior from a user's perspective, but those are what Gradle is supposed to be doing. How the continuous mode recover from a cancel build is by using Ctrl-D and interpreting that differently inside Gradle. At the present moment, `JavaExec` won't behave differently in continuous mode and doesn't support Ctrl-D behavior.

The solution to this problem would be to support Ctrl-D behavior in both normal and continuous mode to shut down the Java application without canceling the daemon. It would also correctly pipe the `System.{out|err}` to the console as well as bring the delay down to something more acceptable to the user.

As this is not a bug but rather a feature request, I have opened this issue https://github.com/gradle/gradle/issues/1128 to reflect the discussion. I will close this issue as not actionable in its present form. Work will continue in supporting cancellation on the `JavaExec` task. Feel free to comment any alternate scenario here to consider (and possibly reopen in the event we missed something) or comment/+1 the feature request at https://github.com/gradle/gradle/issues/1128.

**Closed by lacasseio** 2017-01-09 12:32 UTC
Labels: a:bug, from:contributor, in:daemon

**Comment by coder82** [comment] 2018-09-06 23:51
This problem is still happening..., I am on version 4.10 and Windows 7.

**Comment by jose-solorzano** [comment] 2019-08-22 18:10
Still happening with gradle 5.6.

**Comment by Bravo555** [comment] 2020-05-27 15:10
Problem still present in gradle 6.1.1

**Comment by spyro2000** [comment] 2021-02-08 13:06
Same problem here (Gradle 6.9 with Spring Boot not shut down when gradle process is stopped)
