### ISSUE TITLE
Publishing artifact with programmatically changed version does not work as intended

### ISSUE THREAD

**Issue by msevcenko** [gradle/gradle#11052] opened 2019-10-16 05:52 UTC
When build version is changed programmatically, such as in the [example](https://docs.gradle.org/current/userguide/tutorial_using_tasks.html#configure-by-dag), _and_ the build is java multiproject with project dependencies, _and_ the result is published (at least with the ivy plugin), the resulting published ivy descriptor should correctly reflect the changed version, but it does not.

### Expected Behavior

When running "gradle uploadArchives", the resulting ivy-1.0-SNAPSHOT.xml should be something like this:

```

<ivy-module version="2.0" xmlns:m="http://ant.apache.org/ivy/maven">
  <info ... />
  <configurations>...
  </configurations>
  <publications>
    <artifact name="a" type="jar" ext="jar" conf="apiElements,archives,runtime,runtimeElements"/>
  </publications>
  <dependencies>
    <dependency org="test" name="b" rev="1.0-SNAPSHOT" conf="compile-&gt;default"/>
  </dependencies>
</ivy-module>

```

### Current Behavior
The dependency declaration is:
```
    <dependency org="test" name="b" rev="1.0" conf="compile-&gt;default"/>
```
That is, the change in version in the build script is not reflected.

### Context
This code worked in Gradle 3.5.1, it does not work in Gradle 5.5.1.

### Steps to Reproduce 
Git repo with example to reproduce, includes reproduce instructions in readme: https://github.com/msevcenko/gradle-11052

### Your Environment
Environment: windows 10, Java 8 AdoptOpenJDK. The repository we use is Artifactory version 3.3.0.

**Comment by ljacomet** [comment] 2019-10-16 06:34
While Gradle works hard to preserve compatibility, jumping from 3.x to 5.x is bound to have an impact, especially as work on lazy evaluation and configuration continues.

Take a look at [the migration guide](https://docs.gradle.org/5.6.2/userguide/upgrading_version_4.html) to see if something could explain your issue. You may need to perform that programmatic mutation at a different stage of the build.

**Comment by msevcenko** [comment] 2019-10-16 07:26
Yes, I understand. It is a rough range, I can spend some more time to locate the regression more precisely if it helps (I suspect the regression is present in the version 4.x already).

My point is that since this technique is demonstrated in official example, it is something recommended and should work (and used to work).

I found a workaround - in my setup I actually don´t need access to configured tasks, so I can change the version directly in the configuration phase (which I thought is not possible but it is).

But I still think this is a regression bug.

**Comment by xkacer** [comment] 2019-10-17 12:52
We happen to have run into the same issue.
@ljacomet Thanks for the recommendation but unfortunately it is not possible to change the version (suffix) "at a different stage of the build", because we need the information whether a particular task ("`release`", in this case) is going to be executed or not. As far as I know, this information is not known at any earlier stage than `taskGraph.whenReady`. Or is it?

**Comment by ljacomet** [comment] 2019-10-17 13:19
Well, thanks for the pointer to the documentation.
That's clearly not an ideal sample, as it no longer seems to compose with publication.

I do not think locating the exact regression matters, it is very unlikely to come back from current behavior to this old one.
Note that in upcoming Gradle 6.0 the `uploadArchives` is deprecated, replaced by the new `*-publish` plugins.

I can only recommend that you find a way to configure the `version` early enough that the tasks reading it eagerly are not yet configured. It might mean reversing the pattern: instead of driving the version from a task being part of the graph, to using the version as an indicator of the type of release, as shown in [that documentation](https://docs.gradle.org/5.6.2/userguide/signing_plugin.html#sec:conditional_signing).

**Comment by ljacomet** [comment] 2019-10-24 07:29
Yes, I fully understand the pain when a behavior change can break things _and_ be silent. We are trying very hard to no longer do changes that way.

**Comment by xkacer** [comment] 2019-11-14 11:05
Thanks for your responses. @ljacomet 
I'm not excited about having to reverse the usage pattern but, as a developer, I understand the reasons behind.

I had the idea before (reversing the usage) but hesitated to implement it, because it was quite convenient for users to automatically decide whether we're doing a release based on whether the `release` task actually gets executed or not.

So, we are ready to accept the behavior change is permanent, despite the exact example being used in the documentation for years (as far as I can tell).

Just please consider the following:
* Changing the documentation fragment accordingly. (I'm guessing this is why you left this issue open)
* I'd like to fully second @msevcenko's suggestion to generate some warning or error when I try to do things like that. Because the current behavior is quite nasty and difficult to catch. Maybe you could somehow "lock" the version attribute at some stage (at the latest point it can be modified) and then make it read-only and throw an exception if someone tries to re-set it? Something like already-existing `You can’t change configuration ‘xxx’ because it is already resolved!`

**Comment by ljacomet** [comment] 2019-11-14 11:32
* Regarding the documentation, [a note has been added](https://docs.gradle.org/6.0/userguide/tutorial_using_tasks.html#configure-by-dag) to that example on _why_ it works and thus _what_ can break it in other situations.
* As for the _breaking and silent_ change, yes, +💯 to what you are saying, like I said in my previous comment.

As for the reason for leaving the issue open, it was because of the ongoing conversation.
I consider your statement to be a closing though and will indeed close it then.

Thanks for your understanding in this matter.

**Closed by ljacomet** 2019-11-14 11:32 UTC
Labels: a:regression, from:contributor, in:dependency-management

**Comment by xkacer** [comment] 2019-11-14 12:03
I'm not sure if I would understand the full impact of that documentation note, if I was not participating in this discussion. In particular, it is not obvious that "reading eagerly during configuration" includes automatically calculated dependencies in artefacts generated during the build.

Also, shouldn't we keep this open to implement the warning? Or is there a different issue for that?

**Comment by ljacomet** [comment] 2019-11-14 13:05
The problem about implementing the warning is that the breakage happened a while ago already, so no chance to have a warning for all versions that are broken until now. In addition Gradle 6.0 deprecates `uploadArchives` which also means no more work is prioritized there.

**Comment by xkacer** [comment] 2019-11-14 15:12
I can't find the deprecation notice, so I'm not sure what is the new recommended way to publish artefacts. Whatever it is, isn't it affected by the same issue?

I totally understand that it is not quite reasonable to patch older versions/branches - not arguing about that.

**Comment by ljacomet** [comment] 2019-11-15 17:20
@xkacer Thanks for checking that, it was missed in the upgrade notes. The upcoming 6.0.1 release will fix that.
The [new system](https://docs.gradle.org/6.0/userguide/publishing_setup.html) should work better in that regard because it will do things more lazily.

**Comment by xkacer** [comment] 2019-11-18 22:15
Thanks for the link.
I'll eventually check the new system out and if there is a similar problem (hopefully not), will report that separately.
