### ISSUE TITLE
Signing plugin fails build with multiple publications of the same artifacts

### ISSUE THREAD

**Issue by ALikhachev** [gradle/gradle#30720] opened 2024-09-26 18:29 UTC
### Current Behavior

Signing fails if project has more than one publication of the same artifacts:
```
A problem was found with the configuration of task ':signPub2Publication' (type 'Sign').
  - Gradle detected a problem with the following location: '<path-to-project>/build/libs/signing-plugin-inputs-problem-1.0-SNAPSHOT.jar.asc'.
    
    Reason: Task ':publishPub1PublicationToMavenRepository' uses this output of task ':signPub2Publication' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':signPub2Publication' as an input of ':publishPub1PublicationToMavenRepository'.
      2. Declare an explicit dependency on ':signPub2Publication' from ':publishPub1PublicationToMavenRepository' using Task#dependsOn.
      3. Declare an explicit dependency on ':signPub2Publication' from ':publishPub1PublicationToMavenRepository' using Task#mustRunAfter.
    
    For more information, please refer to https://docs.gradle.org/8.10.2/userguide/validation_problems.html#implicit_dependency in the Gradle documentation.

```

### Expected Behavior

Signing plugin works fine with any number of publications within a project.

### Context (optional)

Perhaps, the signing plugin should be able to detect that it's requested to sign the same artifact twice and reuse the same task/output.
Another solution could be to separate output files per signing task.

### Self-contained Reproducer Project

https://github.com/ALikhachev/signing-plugin-inputs-problem-repro

### Gradle version

8.10.2

**Comment by ov7a** [comment] 2024-10-02 13:13
This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/15568

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

The root cause is that we generate the files in the same place, which is what the related issue is about.

**Closed as not planned by ov7a** 2024-10-02 13:13 UTC
Labels: closed:duplicate
