### ISSUE TITLE
`notCompatibleWithConfigurationCache` and `org.gradle.unsafe.configuration-cache-problems=warn`

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [gradle/gradle#19622] opened 2022-01-19 15:01 UTC
If `org.gradle.unsafe.configuration-cache-problems` is set to `warn`, `notCompatibleWithConfigurationCache` doesn't work and the cache is stored when the task is executed.

Repro: https://github.com/Reproducers/configuration-cache-repro

Task marked as not compatible: `./gradlew spotlessCheck`

**Comment by bamboo** [comment] 2022-01-27 21:47
Thanks for the report, @JavierSegoviaCordoba but that's working as designed. We are [updating the docs](https://github.com/gradle/gradle/pull/19742) to make the implications of the marker clearer.

The marker is mainly intended to be used in the default `fail` mode as a way to explicitly ignore problems in specific tasks. 

Would it work for you to change the mode to `fail` in your build and explicitly mark the offending tasks?

**Comment by bamboo** [comment] 2022-01-27 21:48
Closing as _by design_.

**Closed by bamboo** 2022-01-27 21:48 UTC
Labels: a:bug, in:configuration-cache

**Comment by JavierSegoviaCordoba** [comment] 2022-01-27 21:55
> Thanks for the report, @JavierSegoviaCordoba but that's working as designed. We are [updating the docs](https://github.com/gradle/gradle/pull/19742) to make the implications of the marker clearer.
> 
> The marker is mainly intended to be used in the default `fail` mode as a way to explicitly ignore problems in specific tasks.
> 
> Would it work for you to change the mode to `fail` in your build and explicitly mark the offending tasks?

No, that is the problem, the build without `warn` is not working, so only the combination of both works... is it not possible to add one more property?

**Comment by JavierSegoviaCordoba** [comment] 2022-01-27 22:19
@bamboo the plugin which is blocking me is this one (one plugin I use, uses it): https://github.com/ajoberstar/grgit/issues/322

And it is not an incompatible task I think, it is just how the plugin is built.

**Comment by bamboo** [comment] 2022-01-28 19:20
I see the problem now, @JavierSegoviaCordoba, thanks. 

We will introduce API to better deal with that particular scenario (having a mix of problems from callbacks and incompatible tasks) but I'm afraid that will have to wait for the next Gradle release. :/

**Comment by JavierSegoviaCordoba** [comment] 2022-02-08 11:10
@bamboo is there any open issue to follow this one?

**Comment by bamboo** [comment] 2022-05-05 17:19
> @bamboo any new info about this one?

Thanks for the friendly ping, @JavierSegoviaCordoba, please take a look at https://github.com/gradle/gradle/issues/20673.

**Comment by mlopatkin** [comment] 2026-06-23 08:45
We've revisited the design in https://github.com/gradle/gradle/issues/32451, and Gradle no longer saves CC entry when incompatible-marked task is present,
