### ISSUE TITLE
Sidebar covers the text when using Firefox 121.0

### ISSUE THREAD

**Issue by pjonsson** [gradle/gradle#27541] opened 2023-12-28 13:50 UTC
### Issue type

Missing information

### Problem description

With Chromium version 120.0.6099.71 on Ubuntu 22.04, the documentation site looks as expected. With Firefox 121.0 on Ubuntu 22.04, the sidebar covers the text, as shown in the screenshot.

Another layout issue that might be related is that the "Decline" button in the dialog box in the lower right corner ends up outside the visible area on screen.

![image](https://github.com/gradle/gradle/assets/2082449/24c55eef-c9d8-4c53-809f-4dea99090e59)

### Page with the problem

https://docs.gradle.org/8.5/userguide/upgrading_version_7.html#invalid_toolchain_specification_deprecation

**Comment by pjonsson** [comment] 2024-01-10 10:44
Hi @oleg-nenashev. I'm running what I believe to be a nearly stock Firefox 121.0 from snap in Ubuntu 22.04 LTS. It's possible I have enabled some do-not-track-me kind of options that are not on by default, but I do not have any non-default accessibility features enabled as far as I know. The enhanced privacy protection groups are still at the default values. I also don't have any plugins/addons in this Firefox.

I have restarted Firefox since I reported this issue so I just tested the link again and the webpage looks the same with the hidden text. I also tried opening the link in a private window, and that also hides the text. Chromium in a private window still shows the site as intended.

The only "odd" thing I can think of with my setup is that my browser window is not in full-screen mode, it covers roughly half of my (wide-)screen (so roughly the same size as a full-screen window on a 24" 1080p-monitor). My screen resolution is 2560×1080.

Having written this, I tested reducing the width of my browser window, and that re-renders the page so the text is visible. The section-navigation within the page ends up outside the screen when I do that though, attaching new screenshot of how the site looks post-width-reduction. I have scrollbars for up/down, but not left/right, so the section navigation to the right of my window is effectively disabled.

![image](https://github.com/gradle/gradle/assets/2082449/89cf9062-a9a6-42dd-94a4-2a78db93fec3)

**Comment by lkasso** [comment] 2024-02-05 19:00
Hey @pjonsson,

This looks to be isolated as I cannot reproduce it either:
![Screenshot 2024-02-05 at 10 58 11 AM](https://github.com/gradle/gradle/assets/5684849/9e677443-cef4-4c3c-a25b-c2bdff379ad3)
![Screenshot 2024-02-05 at 10 59 46 AM](https://github.com/gradle/gradle/assets/5684849/f377ccce-61c5-4c17-9296-b5121feac280)

I'm closing this as no other users have reported the issue and it's not reproducible.

**Closed by lkasso** 2024-02-05 19:00 UTC
Labels: a:documentation, to-triage
