### ISSUE TITLE
Gradle incremental annotation processing fails with "Attempt to recreate a file" when a new file is included

### ISSUE THREAD

**Issue by graemerocher** [gradle/gradle#13767] opened 2020-07-13 12:48 UTC
Currently when a new file is added to a project the `Filer` object used by Gradle is somehow in an illegal state which results in compilation errors when an annotation processor tries to create a file. This is manifesting in Micronaut's support for incremental compilation in Gradle. For example:

```
> Task :compileTestJava FAILED
Note: Creating bean classes for 2 type elements
error: Unexpected error: Attempt to recreate a file for type incremental.$FooControllerTestDefinition
error: Unexpected error: Attempt to recreate a file for type incremental.$IncrementalTestDefinition
2 error
```

The compilation error can be resolved by simply running `./gradlew cTJ` again so it seems that Gradle's `Filer` object is in an illegal state at the daemon level. I have reviewed what Micronaut is doing and we are definitely not calling `file.createClassFile(..)` multiple times which is what would trigger this error under normal circumstances and since the problem only manifests when incremental compilation is enabled this seems to be a Gradle bug.

### Expected Behavior

Incremental compilation should consistently work regardless if new files are added.

### Current Behavior

Incremental compilation fails when a new file is added.

### Context

Micronaut users using Gradle incremental compilation receive a hard to understand error message when adding a new source file.

### Steps to Reproduce 

```
$ sdk install micronaut 2.0.0
$ sdk use micronaut 2.0.0
$ mn create-app incremental
$ cd incremental
$ mn create-controller foo
$ mn create-bean bar
$ mn create-bean baz
$ ./gradlew cTJ
$ mn create-bean other
$ ./gradlew cTJ

> Task :compileJava
Note: Creating bean classes for 1 type elements

> Task :compileTestJava FAILED
Note: Creating bean classes for 2 type elements
error: Unexpected error: Attempt to recreate a file for type incremental.$FooControllerTestDefinition
error: Unexpected error: Attempt to recreate a file for type incremental.$IncrementalTestDefinition
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileTestJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

### Your Environment

```
------------------------------------------------------------
Gradle 6.5
------------------------------------------------------------

Build time:   2020-06-02 20:46:21 UTC
Revision:     a27f41e4ae5e8a41ab9b19f8dd6d86d7b384dad4

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          14 (Oracle Corporation 14+36-1461)
OS:           Mac OS X 10.15.5 x86_64
```

**Comment by melix** [comment] 2020-07-17 08:17
Initial research seems to indicate it's not a problem with the Gradle Filer or keeping state in the daemon. It rather seems related to the fact that the `incremental.$IncrementalTestDefinition` and `incremental.$FooControllerTestDefinition` are added as classes to be compiled, probably because they are a dependency of the previous compilation round.

**Comment by graemerocher** [comment] 2020-07-17 08:34
I'm not sure I follow. `incremental.$IncrementalTestDefinition` and `incremental.$FooControllerTestDefinition` are classes generated by Micronaut (via ASM) through the annotation processors. When incremental compilation is not enabled this problem doesn't exist. 

If this is the case what is the suggested fix, to not write these classes again? If so how does one know when and when not to write these classes when incremental is enabled? 

Separately for Kotlin we are also seeing issues where sometimes files are not generated when incremental annotation processing is enabled https://github.com/micronaut-projects/micronaut-core/issues/3742

This again seems to be an issue with the interaction between Gradle and Micronaut's processors, but to fix it we would need guidance on what exactly we have to do.

**Comment by melix** [comment] 2020-07-17 08:37
I can't tell yet what the fix is, there are multiple processors involved, but it feels like Gradle shouldn't add as input a class which doesn't have associated source files. Which at the point where it happens is not trivial to figure out.

**Comment by graemerocher** [comment] 2020-07-17 08:43
Gotcha. Thanks again for looking into this and if there is anything we can change on our side, happy to do so. I spent quite a while debugging and couldn't figure out what we could do differently 🤔

**Comment by graemerocher** [comment] 2020-07-17 08:45
Should I raise a separate issue for micronaut-projects/micronaut-core#3742 ? Or do you think that would be more likely related to KAPT?

**Comment by melix** [comment] 2020-07-17 09:45
I'm not familiar with KAPT, but it looks independent from the Java incremental annotation processing that Gradle does, isn't it?

**Comment by graemerocher** [comment] 2020-07-17 10:17
Good question, may well be.

**Comment by melix** [comment] 2020-07-17 12:07
I have a tentative fix for this issue. It seems to work in the sense it doesn't break any test (and I have to write one to prove it's ok) but I would appreciate @oehme 's point of view on this. It feels weird to me that we add as input to compilation files which have _no source_. It would make sense if the Micronaut AP generated another source file to be compiled by Java, in which case our analysis is right, but here it's directly generating bytecode, so it _feels_ like this is the right fix.

**Comment by graemerocher** [comment] 2020-07-17 12:51
Awesome, yes I agree this seems right. Thoughts @oehme ?

**Comment by oehme** [comment] 2020-07-17 13:16
Yes, that sounds like the right solution :+1:

**Closed** 2020-08-11 15:03 UTC
Labels: @jvm, a:bug, from:contributor, in:jvm-ecosystem

**Comment by graemerocher** [comment] 2020-08-11 15:08
Thanks @melix !

**Comment by jameskleeh** [comment] 2020-09-29 18:20
@melix It appears this change is causing us to see:

```
Caused by: java.lang.NoClassDefFoundError: com/sun/tools/javac/code/Symbol$ClassSymbol
        at org.gradle.api.internal.tasks.compile.processing.AggregatingProcessingStrategy.namesOfElementsWithSource(AggregatingProcessingStrategy.java:79)
        at org.gradle.api.internal.tasks.compile.processing.AggregatingProcessingStrategy.recordAggregatedTypes(AggregatingProcessingStrategy.java:66)
        at org.gradle.api.internal.tasks.compile.processing.AggregatingProcessingStrategy.recordProcessingInputs(AggregatingProcessingStrategy.java:49)
        at org.gradle.api.internal.tasks.compile.processing.DynamicProcessingStrategy.recordProcessingInputs(DynamicProcessingStrategy.java:52)
        at org.gradle.api.internal.tasks.compile.processing.DynamicProcessor.process(DynamicProcessor.java:51)
        at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.process(DelegatingProcessor.java:62)
```

**Comment by melix** [comment] 2020-09-29 18:33
May I ask what JDK you are using?

**Comment by jameskleeh** [comment] 2020-09-29 18:35
@melix I was told openjdk 1.8.0_265. Working to get an example up on github now

**Comment by jameskleeh** [comment] 2020-09-29 19:08
@melix https://github.com/wetted/gradle56rc2bug - just run `./gradlew run` to see the error

**Comment by graemerocher** [comment] 2020-09-29 19:50
Maybe soft loading the class is needed after all 🤔

**Comment by wetted** [comment] 2020-09-30 01:32
I only see the problem when I enable the extra vm options for the `JavaCompile` task – to enable some extra annotation processing – in the build.gradle file. I made some comments in the build file to that effect.

**Comment by graemerocher** [comment] 2020-09-30 06:30
Seems forking the compiler is key. Missing tools.jar?

**Comment by wetted** [comment] 2020-09-30 14:01
I tried adding `files(org.gradle.internal.jvm.Jvm.current().toolsJar)` to `dependencies{}` (both annotationProcessor, and implementation or compileOnly). That didn't help. You are right that fork is the key part.

**Comment by natros** [comment] 2020-09-30 21:13
The last time I had this same problem (`java.lang.NoClassDefFoundError: com/sun/tools/javac/code/Symbol$ClassSymbol`) was because I was using a transitive dependency on the annotation processor that was compiled for java 11, and I was using java 8 for the project.

**Comment by wetted** [comment] 2020-10-01 17:24
Confirming this is still a problem with 6.7-rc-3 (not that anyone claimed otherwise)

**Comment by ljacomet** [comment] 2020-10-01 18:52
Thanks for the report. There is indeed a nasty classloading issue in there that only affects Java 8. A tentative fix is going through CI.

**Comment by ljacomet** [comment] 2020-10-05 13:27
Tracking this issue in #14737

**Comment by nbrugger-tgm** [comment] 2022-04-15 19:58
I have the same issue using Gradle 7.4

**Comment by ljacomet** [comment] 2022-04-26 09:29
@nbrugger-tgm Please open a new issue with a full reproducer
