### ISSUE TITLE
project.version not used as task input by default

### ISSUE THREAD

**Issue by patrick-dedication** [gradle/gradle#28280] opened 2024-02-28 10:28 UTC
### Current Behavior

A task which uses project version is up-to-date even when the project version is changed.

### Expected Behavior

The task should respect the project version as an input when I use it in the task body.

### Context (optional)

We use ORG_GRADLE_PROJECT_version=2 in tag pipelines to build a distribution for that tag.
The version is added to a version info file which might not always be generated at the moment.

### Steps to Reproduce

The task copyMessageBroken is always up-to-date even when I change the project version.
The task copyMessageWorking works due to the explicit input declaration. Is there a better way to do this?
https://github.com/dedication-dev/project-version-input

### Gradle version

8.5

**Comment by ov7a** [comment] 2024-02-29 14:02
This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/1191

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

**Closed by ov7a** 2024-02-29 14:02 UTC
Labels: a:bug, to-triage
