### ISSUE TITLE
Gradle 4.2.0 (distUrl: 6.7.1) fails with 'buildConfigFields', 'versionNameOverride', 'versionCodeOverride'

### ISSUE THREAD

**Issue by rahulr4** [gradle/gradle#17416] opened 2021-06-10 12:41 UTC
I am getting this exception when executing below groovy plugin code.
```
java.lang.IllegalStateException: The value for property 'buildConfigFields' cannot be changed any further.
	at org.gradle.api.internal.provider.AbstractProperty$NonFinalizedValue.beforeMutate(AbstractProperty.java:386)
	at org.gradle.api.internal.provider.AbstractProperty.assertCanMutate(AbstractProperty.java:263)
	at org.gradle.api.internal.provider.DefaultMapProperty.addCollector(DefaultMapProperty.java:176)
	at org.gradle.api.internal.provider.DefaultMapProperty.put(DefaultMapProperty.java:149)
	at com.android.build.api.variant.impl.VariantImpl.addBuildConfigField(VariantImpl.kt:93)
	at com.android.build.gradle.internal.api.BaseVariantImpl.buildConfigField(BaseVariantImpl.java:634)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

Similar errors are coming for versionCode and versionName:
`at com.android.build.gradle.internal.api.ApkVariantOutputImpl.setVersionNameOverride(ApkVariantOutputImpl.java:128)`

when i am trying to set:
`output.versionNameOverride = versionName
                    output.versionCodeOverride = versionCode
`

```
[        project.gradle.taskGraph.whenReady { graph ->
            project.android.applicationVariants.all { variant ->
                def versionName
                if (variant.buildType.name != "release") {
                    versionName = extension.appVersion.compoundVersion
                } else {
                    versionName = extension.appVersion.commercialVersion
                }
                project.version = versionName
                variant.outputs.each { output ->
                    //Getting this error when building on gradle 4.2.0 => The value for this property cannot be changed any further.
                    //Commenting below 2 lines to resolve this error
                    //
                    output.versionNameOverride = versionName
                    output.versionCodeOverride = versionCode
                }
            }
        }
]
```

### Expected Behavior
The exception should not come like it was not coming for previous gradle versions. Below 4.2.0 it was working just fine

### Current Behavior
Getting exception: `java.lang.IllegalStateException: The value for property 'buildConfigFields' cannot be changed any further.`

### Context
We have a releaes plugin for our android projects and we use this configuration to set overriden version name and code in BuildConfig file

**Comment by mlopatkin** [comment] 2021-06-11 07:27
Thank you for your interest in Gradle!

Gradle 4.2.0 is quite old. Do you mean Android Gradle plugin 4.2.0 (Gradle Build Tool and Android Gradle plugin are different products with different versioning)? I suspect that the problem is that you are trying to adjust version information in the `whenReady` callback. It is likely too late, you have to do it during [the configuration phase](https://docs.gradle.org/current/userguide/build_lifecycle.html#sec:build_phases).

Overall, this is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the core of the Gradle Build Tool.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/source/report-bugs

**Closed by mlopatkin** 2021-06-11 07:27 UTC
Labels: a:bug, to-triage

**Comment by rahulr4** [comment] 2021-06-11 11:12
`java.lang.IllegalStateException: The value for this property cannot be changed any further.
	at org.gradle.api.internal.provider.AbstractProperty$NonFinalizedValue.beforeMutate(AbstractProperty.java:386)
	at org.gradle.api.internal.provider.AbstractProperty.assertCanMutate(AbstractProperty.java:263)
	at org.gradle.api.internal.provider.AbstractProperty.setSupplier(AbstractProperty.java:212)
	at org.gradle.api.internal.provider.DefaultProperty.set(DefaultProperty.java:70)
	at com.android.build.gradle.internal.api.ApkVariantOutputImpl.setVersionNameOverride(ApkVariantOutputImpl.java:128)
`

This exception is not of your gradle plugin?

**Comment by mlopatkin** [comment] 2021-06-11 11:30
The exception is coming from `com.android.build.gradle` which is the Android Gradle Plugin. But the root cause is that you are trying to modify the variant configuration after it was finalized. The exception indicates that you are using the plugin in the wrong way. Why are you trying to change the configuration in the `whenReady` callback?

**Comment by rahulr4** [comment] 2021-06-11 11:32
This was working just fine in android gradle version 4.0.1. It is when i updated to 4.2.0, it is throwing this error.,
I have multiple build flavors and if i comment this line, then no version name or code gets set in BuildConfig.

**Comment by mlopatkin** [comment] 2021-06-11 11:46
In any case, this issue has nothing to do with the Gradle build tool itself, as we don't develop the Android plugin. I would suggest you ask a question about how to properly modify BuildConfig on StackOverflow.

**Comment by FadiAboMsalam** [comment] 2021-08-19 10:12
same issue happens with gradle-6.9-all
