### ISSUE TITLE
Custom Integration Test Source Set Results In "No tests found for given includes"

### ISSUE THREAD

**Issue by lingocoder** [gradle/gradle#26647] opened 2023-10-05 13:34 UTC
### Current Behavior

&hellip;

```
$ ./gradlew :integrationTest --tests mr.jar.LibrarianTest
> Task :compileJava UP-TO-DATE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :compileIntTestJava UP-TO-DATE
> Task :processIntTestResources NO-SOURCE
> Task :intTestClasses UP-TO-DATE
> Task :integrationTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':integrationTest'.
> No tests found for given includes: [mr.jar.LibrarianTest](--tests filter)
…
BUILD FAILED in 2s
3 actionable tasks: 1 executed, 2 up-to-date
```

### Expected Behavior

&hellip;

```
$ ./gradlew :integrationTest --tests mr.jar.LibrarianTest
> Task :compileJava UP-TO-DATE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :compileIntTestJava UP-TO-DATE
> Task :processIntTestResources NO-SOURCE
> Task :intTestClasses UP-TO-DATE
> Task :integrationTest

LibrarianTest > testSomeLibraryMethod() FAILED
    org.opentest4j.AssertionFailedError at LibrarianTest.java:12

1 test completed, 1 failed

> Task :integrationTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':integrationTest'.
> There were failing tests. See the report at: file:///…
…
BUILD FAILED in 2s
3 actionable tasks: 1 executed, 2 up-to-date
```

### Context (optional)

I'm trying to accomplish a separation of unit tests, integration tests and functional tests in a basic Java library project. I need to use Gradle 6.9.4. So I need to accomplish that separation WITHOUT [_The JVM Test Suite Plugin_](https://bit.ly/JvmTestSuitePlugin).

I followed, verbatim, [_these steps prescribed in version 6.9.4's user guide_](https://bit.ly/simpleIntTestSteps).

### Steps to Reproduce

1. Follow [_these steps in version 6.9.4's user guide_](https://bit.ly/simpleIntTestSteps)
    - Alternatively, download and decompress [_this reproducer project_](https://bit.ly/issue26647Reproducer)
2. In the project root, run `./gradlew :integrationTest --tests mr.jar.LibrarianTest
3. Observe the `No tests found for given includes: [mr.jar.LibrarianTest](--tests filter) result in the console

### Gradle version

6.9.4

### Your Environment (optional)

------------------------------------------------------------
Gradle 6.9.4
------------------------------------------------------------

Build time:   2023-02-22 08:43:12 UTC
Revision:     7f9380f27d6dc6a1ee6dfc466b834b0408d0b0c4

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          13 (Oracle Corporation 13+33)
OS:           Windows 10 10..0 amd64

**Comment by lingocoder** [comment] 2023-10-06 19:05
> …_Yes, this is the very same issue: when you run a test from IDEA like I did, it actually uses `--tests` and the fact Gradle tells you that **the test you just started doesn't exist** is... frustrating_… — _Originally posted by @melix in https://github.com/gradle/gradle/issues/16029#issuecomment-774001969_

Also frustrating is the "_nonexistence__" of the same test in which it has no problem detecting and reporting compilation errors in like it does in this issue.

**Comment by lingocoder** [comment] 2023-10-08 00:50
I eventually remembered from using [_TestKit_](https://TestKitIntro) a couple years ago that the [`java-gradle-plugin`](https://bmushkoVid) puts the finishing touches on making separate custom source sets and custom test tasks actually work.

I expected to be able do what I wanted ***without*** the `java-gradle-plugin`. But go with what you know, I guess ¯\\\_(ツ)_/¯

**Comment by ov7a** [comment] 2023-10-09 08:19
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/16029#issuecomment-774001969

Please add your use case and 👍 to that issue.

***

6.x branch is no longer maintained and it's unlikely to get any update. Also, you should follow the manual completely without skipping any steps (it's a bit fragile in that version).

**Closed by ov7a** 2023-10-09 08:19 UTC
Labels: a:bug, to-triage

**Comment by ov7a** [comment] 2023-10-09 09:37
@lingocoder 
Sorry that my message is confusing. By "fragile" I meant the Gradle implementation, meaning that minor errors may lead to unwanted behavior. It's one of the reasons why Test Suites Plugin was introduced. 

I haven't invested much time in investigating your issue though, so I can't pinpoint the exact problem, sorry. Given it's a pretty old version, it's unlikely the issue would get attention from the team because our capacity is limited. Perhaps you can find the solution with the help of the community in Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/)

**Comment by lingocoder** [comment] 2023-10-09 10:20
> …_I haven't invested much time in investigating your issue though, so I can't pinpoint the exact problem, sorry_…

I appreciate your feedback anyway, @ov7a.

> …_Perhaps you can find the solution with the help of the community in Slack or forums_…

Thanks. But I've [_already found a solution_](https://github.com/gradle/gradle/issues/26647#issuecomment-1751879119) (_a round of applause for the super excellent former-Gradler, @bmuschko!_ 👏).

For such a basic project, my [_java-gradle-plugin_](https://bmushkovid/) workaround is sort of like using a pile driver on a thumb tack haha. But probably no more so than the no doubt equally super excellent Test Suite Plugin.


> …_Given it's a pretty old version, it's unlikely the issue would get attention from the team_…

Say the exact same issue is reproducible in the latest Gradle, Am I correct that [_your advice would be to also add that_](https://github.com/gradle/gradle/issues/26647#issuecomment-1752541167) to @melix's UX issue? TIA.

**Comment by ov7a** [comment] 2023-10-09 10:26
Thanks for the clarifications, @lingocoder!

> Say the exact same issue is reproducible in the latest Gradle, Am I correct that https://github.com/gradle/gradle/issues/26647#issuecomment-1752541167 to @melix's UX issue? TIA.

Yes, please add a comment there with your case (a reproducer is appreciated too)!
