### ISSUE TITLE
Allow plugins to register new types of projects to init

### ISSUE THREAD

**Issue by tresat** [gradle/gradle#29690] opened 2024-06-25 20:49 UTC
WIP: More detail coming soon.

**Comment by ov7a** [comment] 2024-06-26 08:32
Is it a duplicate of 
* https://github.com/gradle/gradle/issues/1686
?

**Comment by tresat** [comment] 2024-06-26 11:58
@ov7a - Thanks for posting that.  I created this issue to link from my WIP Spec.  #1686 is not quite a duplicate, as it is one specific possible solution to a more general problem, that we only _need_ to solve in the context of Delcarative Gradle _for now_.  I'll link it from the Spec.

In other news: I specifically removed the `to-triage` tag to avoid bothering anyone with this issue and the bot re-added it.  What's with that?

**Comment by ov7a** [comment] 2024-06-26 12:01
> In other news: I specifically removed the to-triage tag to avoid bothering anyone with this issue and the bot re-added it. What's with that?

That's because this issue does not have any `in:*` label (meaning it would be less searchable)

**Comment by big-guy** [comment] 2024-12-03 19:34
We're not advertising this in the release notes.

**Closed by big-guy** 2024-12-03 19:34 UTC
Labels: in:build-init-plugin, a:feature, has:release-notes-decision
