### ISSUE TITLE
Provider cannot be `map`-ed to a nullable type in Kotlin DSL outside of buildscripts

### ISSUE THREAD

**Issue by joshfriend** [gradle/gradle#25341] opened 2023-06-09 02:08 UTC
### Expected Behavior

`Provider.map` should be able to return a null value in Kotlin

### Current Behavior

A type mismatch is thrown by kotlin:

<img width="196" alt="image" src="https://github.com/gradle/gradle/assets/885137/4133c38b-141e-416d-b062-b6e0638e59ed">

I was able to suppress this before under Gradle 7.5 with `@Suppress("NULLABILITY_MISMATCH_BASED_ON_JAVA_ANNOTATIONS")` but this no longer works.

### Context (optional)

This was reported  in #12388 and supposedly fixed in #23164, however the reproducer still doesn't compile.

### Steps to Reproduce

The following wont compile:

```kotlin
val example = provider { File("doesntexist") }
  .map { if (it.exists()) it else null }
```

but this does, like the original issue says:

```kotlin
val example = provider { File("doesntexist") }
  .flatMap { provider { if (it.exists()) it else null } }
```

### Gradle version

8.1.1

### Your Environment (optional)

macOS, JDK 17, jvmTarget 11, kotlin 1.8.10

**Comment by eskatos** [comment] 2023-08-08 12:58
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/24767

Please add your use case and 👍 to that issue.

**Closed by eskatos** 2023-08-08 12:58 UTC
Labels: closed:duplicate
