### ISSUE TITLE
Replace the need for POM rewriting in other ecosystems

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#25806] opened 2023-07-18 15:39 UTC
Gradle Module Metadata provides a rich metadata format for expressing metadata for components that have multiple variants. While GMM works well for Gradle consumers, other build tools like Maven cannot currently consume GMM. As a result, Gradle publishes POMs alongside the GMM files it publishes. 

Currently, the POMs that Gradle publishes are incorrect. They do not correctly represent components that are published to multiple coordinates -- such as those published by the Native plugins. KMP gets around this by manually editing the XML of Gradle's generated POMs, while Android simply does nothing and publishes incorrect POMs. 

Since it will take time to get other build tools to integrate GMM support, we should update Gradle so that it is able to publish multi-coordinate components in a Maven-compatible way.

**Comment by jvandort** [comment] 2023-08-22 03:40
Duplicate of: https://github.com/gradle/gradle/issues/12324

**Closed by jvandort** 2023-08-22 03:40 UTC
Labels: in:publishing-plugins, a:feature
