### ISSUE TITLE
ExecException: Process 'Gradle Test Executor XX' finished with non-zero exit value 10

### ISSUE THREAD

**Issue by clhols** [gradle/gradle#16397] opened 2021-03-03 12:35 UTC
After updating our JDK from 1.8.0_271 to 15.0.2 we started experiencing issue then running Android unit tests.
The Gradle task running the tests often fail with the provided exception. But it is possible that the task completes if you just keep running it enough times.
The stacktrace doesn't contain any Android classes, so therefore the issue is created here.

### Expected Behavior
Gradle Task Executor shouldn't finish with non-zero exit value.

### Current Behavior
This exception happens when running the testDebugUnitTest task:
```
2021-03-03T13:07:42.600+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
2021-03-03T13:07:42.600+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:testPersonalDkDebugUnitTest'.
2021-03-03T13:07:42.600+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$3(ExecuteActionsTaskExecuter.java:186)
2021-03-03T13:07:42.601+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:268)
2021-03-03T13:07:42.601+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:184)
2021-03-03T13:07:42.601+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:173)
2021-03-03T13:07:42.601+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
2021-03-03T13:07:42.601+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
2021-03-03T13:07:42.601+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
2021-03-03T13:07:42.601+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
2021-03-03T13:07:42.601+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
2021-03-03T13:07:42.602+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
2021-03-03T13:07:42.602+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
2021-03-03T13:07:42.602+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
2021-03-03T13:07:42.602+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
2021-03-03T13:07:42.603+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
2021-03-03T13:07:42.603+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
2021-03-03T13:07:42.603+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
2021-03-03T13:07:42.603+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
2021-03-03T13:07:42.603+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
2021-03-03T13:07:42.603+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
2021-03-03T13:07:42.603+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
2021-03-03T13:07:42.603+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
2021-03-03T13:07:42.603+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
2021-03-03T13:07:42.604+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
2021-03-03T13:07:42.604+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
2021-03-03T13:07:42.604+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
2021-03-03T13:07:42.604+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:411)
2021-03-03T13:07:42.604+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:398)
2021-03-03T13:07:42.604+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:391)
2021-03-03T13:07:42.604+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:377)
2021-03-03T13:07:42.604+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
2021-03-03T13:07:42.605+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
2021-03-03T13:07:42.605+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
2021-03-03T13:07:42.605+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
2021-03-03T13:07:42.605+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
2021-03-03T13:07:42.605+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
2021-03-03T13:07:42.605+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
2021-03-03T13:07:42.605+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 3' finished with non-zero exit value 10
2021-03-03T13:07:42.605+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] This problem might be caused by incorrect test process configuration.
2021-03-03T13:07:42.605+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Please refer to the test execution section in the User Manual at https://docs.gradle.org/6.8.3/userguide/java_testing.html#sec:test_execution
2021-03-03T13:07:42.605+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.testing.worker.ForkingTestClassProcessor.stop(ForkingTestClassProcessor.java:182)
2021-03-03T13:07:42.605+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.testing.processors.RestartEveryNTestClassProcessor.endBatch(RestartEveryNTestClassProcessor.java:77)
2021-03-03T13:07:42.605+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.testing.processors.RestartEveryNTestClassProcessor.stop(RestartEveryNTestClassProcessor.java:62)
2021-03-03T13:07:42.605+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-03-03T13:07:42.606+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
2021-03-03T13:07:42.606+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-03-03T13:07:42.606+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
2021-03-03T13:07:42.606+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
2021-03-03T13:07:42.606+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:30)
2021-03-03T13:07:42.606+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:87)
2021-03-03T13:07:42.606+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:36)
2021-03-03T13:07:42.606+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:71)
2021-03-03T13:07:42.606+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.InterruptibleRunnable.run(InterruptibleRunnable.java:42)
2021-03-03T13:07:42.606+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
2021-03-03T13:07:42.607+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
2021-03-03T13:07:42.607+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
2021-03-03T13:07:42.607+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
2021-03-03T13:07:42.607+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
2021-03-03T13:07:42.607+0100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
```

An alternative stacktrace with the same cause is:
```
03-Mar-2021 13:04:12 | Could not stop org.gradle.internal.actor.internal.DefaultActorFactory$NonBlockingActor@1f3c6487.
-- | --
03-Mar-2021 13:04:12 | org.gradle.internal.dispatch.DispatchException: Could not dispatch message [MethodInvocation method: stop()].
03-Mar-2021 13:04:12 | at org.gradle.internal.dispatch.ExceptionTrackingFailureHandler.dispatchFailed(ExceptionTrackingFailureHandler.java:35)
03-Mar-2021 13:04:12 | at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:32)
03-Mar-2021 13:04:12 | at org.gradle.internal.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:87)
03-Mar-2021 13:04:12 | at org.gradle.internal.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:36)
03-Mar-2021 13:04:12 | at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:71)
03-Mar-2021 13:04:12 | at org.gradle.internal.concurrent.InterruptibleRunnable.run(InterruptibleRunnable.java:42)
03-Mar-2021 13:04:12 | at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
03-Mar-2021 13:04:12 | at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
03-Mar-2021 13:04:12 | at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
03-Mar-2021 13:04:12 | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
03-Mar-2021 13:04:12 | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
03-Mar-2021 13:04:12 | at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
03-Mar-2021 13:04:12 | at java.base/java.lang.Thread.run(Thread.java:832)
03-Mar-2021 13:04:12 | Caused by: org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 12' finished with non-zero exit value 10
03-Mar-2021 13:04:12 | This problem might be caused by incorrect test process configuration.
03-Mar-2021 13:04:12 | Please refer to the test execution section in the User Manual at https://docs.gradle.org/6.8.3/userguide/java_testing.html#sec:test_execution
03-Mar-2021 13:04:12 | at org.gradle.api.internal.tasks.testing.worker.ForkingTestClassProcessor.stop(ForkingTestClassProcessor.java:182)
03-Mar-2021 13:04:12 | at org.gradle.api.internal.tasks.testing.processors.RestartEveryNTestClassProcessor.endBatch(RestartEveryNTestClassProcessor.java:77)
03-Mar-2021 13:04:12 | at org.gradle.api.internal.tasks.testing.processors.RestartEveryNTestClassProcessor.stop(RestartEveryNTestClassProcessor.java:62)
03-Mar-2021 13:04:12 | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03-Mar-2021 13:04:12 | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
03-Mar-2021 13:04:12 | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03-Mar-2021 13:04:12 | at java.base/java.lang.reflect.Method.invoke(Method.java:564)
03-Mar-2021 13:04:12 | at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
03-Mar-2021 13:04:12 | at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
03-Mar-2021 13:04:12 | at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:30)
03-Mar-2021 13:04:12 | ... 11 more
```

### Context
It doesn't seem to be a memory related issue as monitoring with VirtualVM doesn'y reveal anything.
Maybe you can provide info on what exit code 10 means?
The tests are running with maxParallelForks = 4, but also fails without setting it.

### Your Environment
MacOS 10.15.7
JDK 15.0.2
Gradle wrapper 6.8.3

**Comment by clhols** [comment] 2021-03-04 08:31
We have narrowed it down and discovered that it is caused by the Robolectric tests. At least disabling all the robo tests is a workaround for us.

**Comment by bmuskalla** [comment] 2021-04-07 15:17
I believe this is some test/fixture code calling system exit that confuses [the test runner](https://github.com/gradle/gradle/issues/3610). I'm closing this in favor of #3610 - let me know if you find this has a different root cause that needs extra handling on the Gradle side.

**Closed by bmuskalla** 2021-04-07 15:17 UTC
Labels: a:bug
