### ISSUE TITLE
Dependency Locking Issue with Spring Dependency Management and Test-Fixtures

### ISSUE THREAD

**Issue by pfhartma** [gradle/gradle#27947] opened 2024-02-05 09:26 UTC
### Current Behavior

After update to Gradle 8.5, running the tests results in error: "Could not resolve all files for configuration ':testRuntimeClasspath'."

### Expected Behavior

After fixing the dependency versions with "./gradlew dependencies --write-locks", gradle should execute the tests with "./gradlew test".

### Context (optional)

Unable to run the tests when using the following features at once:
* dependency locking
* explicit versions for some (selected) dependencies
* spring dependency management
* test-fixtures

### Steps to Reproduce

Call
```
./gradlew dependencies --write-locks
./gradlew test
```
with the following `build.gradle` file:
```groovy
plugins {
	id 'java'
	id 'io.spring.dependency-management' version '1.1.4'
	id 'java-test-fixtures'
}

java {
	sourceCompatibility = '17'
}

repositories {
	mavenCentral()
}

dependencyLocking {
	lockAllConfigurations()
}

dependencies {
	implementation 'org.keycloak:keycloak-admin-client:22.0.5'
}
```

==>

```
$ ./gradlew test
> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> Could not resolve all files for configuration ':testRuntimeClasspath'.
   > Resolved 'com.github.java-json-tools:jackson-coreutils:2.0' which is not part of the dependency lock state
   > Resolved 'com.sun.activation:jakarta.activation:2.0.1' which is not part of the dependency lock state
   > Resolved 'com.github.java-json-tools:msg-simple:1.2' which is not part of the dependency lock state
   > Resolved 'com.github.java-json-tools:btf:1.3' which is not part of the dependency lock state
```

Observations:
* It does work, when removing the line `id 'java-test-fixtures'` (not used in the minimal example, but I do need it)
* It does work, when removing the line `id 'io.spring.dependency-management' version '1.1.4'` (not used in the minimal example, but I do need it)
* Where are the dependencies from the error message coming from? They are resolved, when running without the spring dependency plugin

### Gradle version

8.5

### Gradle version that used to work

8.4

### Your Environment (optional)

OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)
Linux

**Comment by ov7a** [comment] 2024-02-05 10:31
Sorry that you're having trouble with Gradle!

Most probably your issue is caused by an external Gradle plugin, which cannot be addressed in the Gradle Build Tool project.

We recommend you open an issue on its issue tracker.

We have some integration tests with major plugins to catch potential problems early, but we don't have the capacity to cover all plugins available.

If you think you have come across a Gradle bug, please provide a reproducer for this issue without the plugin and we’ll consider reopening it.

***

The behavior you observing is most probably caused by `io.spring.dependency-management`.

**Comment by fp7** [comment] 2024-02-23 10:22
I stumbled across the same problem and build a reproducer without the spring dep man plugin: https://github.com/fp7/gradle-locking-repro

**Comment by ov7a** [comment] 2024-02-26 10:35
@fp7 thank you for providing a reproducer!

**Comment by jvandort** [comment] 2024-06-07 03:11
This was likely fixed in by https://github.com/gradle/gradle/pull/29193

We should not close this issue until we add a regression test. 

After digging into what is going on, the following test should reproduce the core issue.
```
    def "test2"() {
        mavenRepo.module("org", "direct")
            .dependsOn(mavenRepo.module("org", "transitive").publish())
            .publish()

        buildFile << """
            plugins {
                id("java-library")
            }

            ${mavenTestRepository()}

            configurations.testRuntimeClasspath.incoming.beforeResolve {
                dependencies.find { it instanceof ExternalModuleDependency && it.name.contains("direct") }
                            .exclude(group: "org", module: "transitive")
            }

            dependencies {
                testImplementation(project)
                implementation 'org:direct:1.0'
            }

            task resolve {
                dependsOn(configurations.testRuntimeClasspath)
                def files = configurations.testRuntimeClasspath
                doLast {
                    assert(!files*.name.contains("transitive-1.0.jar"))
                }
            }
        """

        expect:
        executer.noDeprecationChecks()
        succeeds("resolve")
    }
```

It could still use some slimming (like not applying the java plugin), but this test now passes after the linked PR was merged. 

Would you be able to verify with the latest Gradle nightly that this issue is resolved?

**Closed** 2024-06-20 03:09 UTC
Labels: a:regression, in:dependency-locking, has:reproducer
