### ISSUE TITLE
Make sure generated Gradle jars don't contain duplicate entries

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#10038] opened 2019-07-22 07:49 UTC
All the JARs generated and used Gradle (`gradleApi`, etc.) shouldn't contain duplicate entries, so they are not flagged as "grossly invalid ZIPs" (see #9990).

Related to https://github.com/gradle/gradle-groovy-all/pull/5

---
cc: @gradle/build-cache

**Comment by wolfs** [comment] 2019-07-22 07:50
@eskatos fixed the kotlin DSL jar in #10002.

**Comment by paplorinc** [comment] 2019-07-22 19:25
Checking the final distribution zip with the patched `unzip_6.0-24` for gradle 5.5.x, I can confirm the the following files are invalid:
* groovy-all-1.0-2.5.4.jar
* gradle-kotlin-dsl-provider-plugins-5.5.1.jar
* gradle-kotlin-dsl-tooling-builders-5.5.1.jar
* gradle-kotlin-dsl-5.6.jar

Note, that our packaged ASM 7.1 version is safe.

I can also confirm that running against the latest nightly (`5.7-20190721220031+0000`) the kotlin-dsl problems were fixed (🥇@eskatos)
Only the groovy-all dependency remains, where the duplicate-keeping strategy was a [deliberate choice](https://github.com/gradle/gradle-groovy-all/blob/master/build.gradle#L110) to keep every license and ExtensionModule - we'll decide how to handle that exactly.

**Comment by lptr** [comment] 2019-07-22 20:45
Thanks for checking @paplorinc. We also need to check the Gradle API JAR and the TestKit JAR we generate during first use. Can you please take a look at those, too?

**Comment by paplorinc** [comment] 2019-07-22 21:47
Will do, thanks - may need some info about where to find them.

Running an assemble on the whole project and checking all jars, the following also showed up:
`gradle-instant-execution-report-5.7.jar`
Where could I add an integration test that could catch this as well?

**Comment by eskatos** [comment] 2019-07-23 06:47
@paplorinc 
The `:distributions` subproject might be a good fit for integration testing shipped jars.
The generated API jars can be found in `~/.gradle/caches/<version>/generated-gradle-jars`

**Comment by paplorinc** [comment] 2019-07-23 07:28
Thanks @eskatos, that's what I did in https://github.com/gradle/gradle/pull/10049/files

Manually checking the complete `~/.gradle/caches` folder I found a few other `-sources` archives as well, like `asm-6-0-sources.jar` and `kotlin-stdlib-1.1.3-2-sources.jar` (why do we even have sources in the caches folder?)

**Comment by lptr** [comment] 2019-07-23 08:31
Looks like I was wrong, and the JVM won't load multiple resources with the same name for the same JAR: https://github.com/lptr/duplicate-resource-in-jar

I think this means that we can safely make `FAIL` the default for duplicate entries in 6.0, and we should remove all duplicate entries in our JARs.

**Comment by paplorinc** [comment] 2019-07-23 08:36
Great, thanks for investigating!

**Comment by paplorinc** [comment] 2019-07-23 10:19
For the `groovy-all` the case seems to be a bit more difficult.
* `groovy-release-info.properties` - is the exact same, added numerous times. This could be solved with `duplicatesStrategy = DuplicatesStrategy.EXCLUDE`
* `INDEX.LIST` - contains 22 distinct indexed jar folder structures. I would just exclude these completely (see https://bugs.java.com/bugdatabase/view_bug.do?bug_id=7100860)
* `LICENSE` - it may be important to keep every version here (all of them have the Apache License as basis, suffixed with ANTLR, JSR223 and NORMALIZE.CSS licenses). We should either merge these (append with redundancy) or rename them or move them to a folder named like the originating jar.
* `NOTICE` - same as with `LICENSE`
* `MANIFEST.MF` - all of these are completely different, no idea how to deduplicate these
* `org.apache.groovy.plugin.GroovyRunner` - junit vs testng, can be excluded, I think
* `org.codehaus.groovy.runtime.ExtensionModule` - all of these are different and if we need these metaprogramming extensions we can merge them, according to http://docs.groovy-lang.org/docs/groovy-2.5.4/html/documentation/core-metaprogramming.html#module-descriptor
* `org.codehaus.groovy.transform.ASTTransformation` - these should probably be merged, too

What do you think @wolfs, @lptr, @melix?

**Comment by melix** [comment] 2019-07-23 10:21
Ideally we shouldn't build our own jar but use Groovy as is. Now, I think your plan is ok. For merging the module descriptors, this is necessary. You could look at how Groovy used to do this (look back in the git history). AST transformations need to be merged too, yes.

**Comment by lptr** [comment] 2019-07-23 11:02
Your plan sounds good. For `LICENSE` and `NOTICE` files we could try manually merging the contents instead. We could add a test to check if every line from every original `LICENSE` file ends up represented in the merged `LICENSE` file and vice versa if we want to be extra careful. However, it would probably be better to invest this time into fixing Gradle so we don't need to generate a `groovy-all.jar` at all.

**Comment by paplorinc** [comment] 2019-07-23 11:03
>  invest this time into fixing Gradle so we don't need to generate a groovy-all.jar at all

Could you please point us to the resources that explain what lead to this need?

**Comment by lptr** [comment] 2019-07-23 11:07
@paplorinc see https://github.com/gradle/gradle/pull/6682 and linked issues.

**Comment by lptr** [comment] 2019-07-23 11:07
BTW, removing the need for `groovy-all.jar` should help us move to Groovy 3.0, too.

**Comment by paplorinc** [comment] 2019-07-23 11:11
Okay, since the deduplication is urgent for the 5.6 RC 1, I'll attempt it in two steps:

1) create a custom merge strategy, as described above
2) see if we can get rid of the custom Groovy completely

Does that sound reasonable?

**Comment by lptr** [comment] 2019-07-23 11:33
Yes, please separate those two. We should make a decision whether fixing `groovy-all` is a priority now.

**Comment by bamboo** [comment] 2019-07-23 13:51
> 
> Running an assemble on the whole project and checking all jars, the following also showed up:
> `gradle-instant-execution-report-5.7.jar`
> Where could I add an integration test that could catch this as well?

`gradle-instant-execution-report-5.7.jar` is never used, it is only built by convention. In any case, the following PR fixes the configuration not to include duplicate entries: https://github.com/gradle/gradle/pull/10055

**Comment by paplorinc** [comment] 2019-07-23 16:53
Thanks for the inputs!
@lptr, @melix, @wolfs, please review https://github.com/gradle/gradle-groovy-all/pull/5

**Comment by bamboo** [comment] 2019-07-23 17:55
`gradle-instant-execution-report` fix merged to master (#10055).

**Comment by lptr** [comment] 2019-07-29 10:18
I don't think we should close this via `groovy-all`. Is this issue closed yet for good? Is for example the new `groovy-all` merged yet to `master`?

**Comment by lptr** [comment] 2019-07-29 10:22
I see, this was fixed via https://github.com/gradle/gradle/pull/10049, too, which also upgraded `groovy-all` (though GitHub does mention it).

**Closed** 2019-07-29 10:22 UTC
Labels: @build-cache, a:bug, from:member
