### ISSUE TITLE
Tooling API cannot be packaged in an UberJar

### ISSUE THREAD

**Issue by coney** [gradle/gradle#2483] opened 2017-07-17 01:55 UTC
### Expected Behavior
gradle tooling api works well with spring boot application.

### Current Behavior
gradle tooling api can't initialize with in jar of spring boot application 

### Context
I wrote a demo application to reproduce this issue, check the next section

### Steps to Reproduce (for bugs)
I am using gradle tooling api alone with spring boot, but seems that gradle tooling api doesn't work well with spring boot application which packaged in jar. there is a demo app to reproduce this issue:

https://github.com/coney/tooling-api-demo

#### execute gradle task from command line
``` bash
$ ./gradlew hello
Configure project :

> Task :hello
hello world


BUILD SUCCESSFUL in 4s
1 actionable task: 1 executed
```

#### execute gradle task from spring boot application(not packaged)

``` bash
$ ./gradlew bootRun
> Configure project :
> Task :findMainClass
> Task :bootRun
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.4.RELEASE)

2017-07-17 09:34:47.106  INFO 85959 --- [           main] c.e.t.ToolingApiDemoApplication          : Starting ToolingApiDemoApplication on Coney-Laptop-L with PID 85959 (/Users/coney/tooling-api-demo/build/classes/java/main started by coney in /Users/coney/tooling-api-demo)
2017-07-17 09:34:47.109  INFO 85959 --- [           main] c.e.t.ToolingApiDemoApplication          : No active profile set, falling back to default profiles: default
2017-07-17 09:34:47.170  INFO 85959 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@5579bb86: startup date [Mon Jul 17 09:34:47 CST 2017]; root of context hierarchy
2017-07-17 09:34:47.722  INFO 85959 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_arjak7tf28meqfy2ftvpbvxs2.run(/Users/coney/tooling-api-demo/build.gradle:35)
:hello
hello world

BUILD SUCCESSFUL in 2s
1 actionable task: 1 executed

2017-07-17 09:34:49.835  INFO 85959 --- [           main] c.e.t.ToolingApiDemoApplication          : Started ToolingApiDemoApplication in 3.123 seconds (JVM running for 3.54)
2017-07-17 09:34:49.836  INFO 85959 --- [       Thread-2] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@5579bb86: startup date [Mon Jul 17 09:34:47 CST 2017]; root of context hierarchy
2017-07-17 09:34:49.837  INFO 85959 --- [       Thread-2] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown


BUILD SUCCESSFUL in 9s
4 actionable tasks: 2 executed, 2 up-to-date
```

#### execute gradle task from spring boot application(packaged in jar)
- package spring boot application in jar
``` bash
$ ./gradlew bootRepackage 
> Configure project :
> Task :findMainClass
BUILD SUCCESSFUL in 5s
5 actionable tasks: 3 executed, 2 up-to-date
```
- execute jar
``` bash
$ java -jar ./build/libs/tooling-api-demo-0.0.1-SNAPSHOT.jar

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.4.RELEASE)

2017-07-17 09:37:50.334  INFO 86024 --- [           main] c.e.t.ToolingApiDemoApplication          : Starting ToolingApiDemoApplication on Coney-Laptop-L with PID 86024 (/Users/coney/tooling-api-demo/build/libs/tooling-api-demo-0.0.1-SNAPSHOT.jar started by coney in /Users/coney/tooling-api-demo)
2017-07-17 09:37:50.339  INFO 86024 --- [           main] c.e.t.ToolingApiDemoApplication          : No active profile set, falling back to default profiles: default
2017-07-17 09:37:50.441  INFO 86024 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@255316f2: startup date [Mon Jul 17 09:37:50 CST 2017]; root of context hierarchy
2017-07-17 09:37:51.269  INFO 86024 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2017-07-17 09:37:51.738  INFO 86024 --- [           main] utoConfigurationReportLoggingInitializer :

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-07-17 09:37:51.756 ERROR 86024 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:735) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	at com.example.toolingapidemo.ToolingApiDemoApplication.main(ToolingApiDemoApplication.java:10) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_102]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [tooling-api-demo-0.0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [tooling-api-demo-0.0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [tooling-api-demo-0.0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [tooling-api-demo-0.0.1-SNAPSHOT.jar:na]
Caused by: org.gradle.tooling.GradleConnectionException: Could not create an instance of Tooling API implementation using the specified Gradle distribution 'https://services.gradle.org/distributions/gradle-4.0.1-bin.zip'.
	at org.gradle.tooling.internal.consumer.loader.DefaultToolingImplementationLoader.create(DefaultToolingImplementationLoader.java:110) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.tooling.internal.consumer.loader.CachingToolingImplementationLoader.create(CachingToolingImplementationLoader.java:44) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.tooling.internal.consumer.loader.SynchronizedToolingImplementationLoader.create(SynchronizedToolingImplementationLoader.java:43) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.onStartAction(LazyConsumerActionExecutor.java:101) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:83) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_102]
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]
	at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.tooling.internal.consumer.DefaultBuildLauncher.run(DefaultBuildLauncher.java:77) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at com.example.toolingapidemo.GradleRunner.run(GradleRunner.java:24) ~[classes!/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	... 14 common frames omitted
Caused by: org.gradle.internal.service.ServiceLookupException: Could not configure services using ConnectionScopeServices.configure().
	at org.gradle.internal.service.DefaultServiceRegistry.applyConfigureMethod(DefaultServiceRegistry.java:205) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.service.DefaultServiceRegistry.findProviderMethods(DefaultServiceRegistry.java:180) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.service.DefaultServiceRegistry.addProvider(DefaultServiceRegistry.java:255) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.service.ServiceRegistryBuilder.build(ServiceRegistryBuilder.java:52) ~[na:na]
	at org.gradle.tooling.internal.provider.DefaultConnection.initializeServices(DefaultConnection.java:103) ~[na:na]
	at org.gradle.tooling.internal.provider.DefaultConnection.configure(DefaultConnection.java:94) ~[na:na]
	at org.gradle.tooling.internal.consumer.connection.AbstractPost12ConsumerConnection.configure(AbstractPost12ConsumerConnection.java:37) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.tooling.internal.consumer.loader.DefaultToolingImplementationLoader.create(DefaultToolingImplementationLoader.java:102) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.tooling.internal.consumer.loader.CachingToolingImplementationLoader.create(CachingToolingImplementationLoader.java:44) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.tooling.internal.consumer.loader.SynchronizedToolingImplementationLoader.create(SynchronizedToolingImplementationLoader.java:43) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.onStartAction(LazyConsumerActionExecutor.java:101) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:83) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_102]
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]
Caused by: org.gradle.internal.service.ServiceCreationException: Could not create service of type ModuleRegistry using GlobalScopeServices.createModuleRegistry().
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:797) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:748) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectProvider.getInstance(DefaultServiceRegistry.java:574) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:623) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:761) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:747) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectProvider.getInstance(DefaultServiceRegistry.java:574) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:623) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:761) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:747) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectProvider.getInstance(DefaultServiceRegistry.java:574) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:623) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.service.DefaultServiceRegistry.applyConfigureMethod(DefaultServiceRegistry.java:199) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.service.DefaultServiceRegistry.findProviderMethods(DefaultServiceRegistry.java:180) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.service.DefaultServiceRegistry.addProvider(DefaultServiceRegistry.java:255) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.service.DefaultServiceRegistry$1.addProvider(DefaultServiceRegistry.java:236) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.tooling.internal.provider.ConnectionScopeServices.configure(ConnectionScopeServices.java:51) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_102]
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.service.ReflectionBasedServiceMethod.invoke(ReflectionBasedServiceMethod.java:35) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.service.DefaultServiceRegistry.applyConfigureMethod(DefaultServiceRegistry.java:203) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	... 21 common frames omitted
Caused by: java.lang.IllegalArgumentException: URI is not hierarchical
	at java.io.File.<init>(File.java:418) ~[na:1.8.0_102]
	at org.gradle.internal.classloader.ClasspathUtil$1.visitClassPath(ClasspathUtil.java:63) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.classloader.ClassLoaderVisitor.visit(ClassLoaderVisitor.java:41) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.classloader.ClassLoaderVisitor.visitParent(ClassLoaderVisitor.java:82) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.classloader.ClassLoaderVisitor.visit(ClassLoaderVisitor.java:46) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.classloader.ClassLoaderVisitor.visitParent(ClassLoaderVisitor.java:82) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.classloader.ClassLoaderVisitor.visit(ClassLoaderVisitor.java:46) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.classloader.ClasspathUtil.getClasspath(ClasspathUtil.java:58) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.api.internal.classpath.EffectiveClassPath.findAvailableClasspathFiles(EffectiveClassPath.java:36) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.api.internal.classpath.EffectiveClassPath.<init>(EffectiveClassPath.java:32) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.api.internal.classpath.DefaultModuleRegistry.<init>(DefaultModuleRegistry.java:53) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.api.internal.classpath.DefaultModuleRegistry.<init>(DefaultModuleRegistry.java:47) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.service.scopes.GlobalScopeServices.createModuleRegistry(GlobalScopeServices.java:194) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_102]
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.service.ReflectionBasedServiceMethod.invoke(ReflectionBasedServiceMethod.java:35) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:795) ~[gradle-tooling-api-4.0.1.jar!/:4.0.1]
	... 44 common frames omitted

2017-07-17 09:37:51.974  INFO 86024 --- [           main] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@255316f2: startup date [Mon Jul 17 09:37:50 CST 2017]; root of context hierarchy
2017-07-17 09:37:51.976  INFO 86024 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
```

I put a break point in `File.java:418`, try to find out the invalid URI address, and I got these URLs from `org.gradle.internal.classloader.ClasspathUtil#getClasspath`:
``` java
    public static ClassPath getClasspath(ClassLoader classLoader) {
        final List<File> implementationClassPath = new ArrayList<File>();
        new ClassLoaderVisitor() {
            @Override
            public void visitClassPath(URL[] classPath) {
                for (URL url : classPath) {
                    try {
                        implementationClassPath.add(new File(toURI(url)));
                    } catch (URISyntaxException e) {
                        throw new UncheckedException(e);
                    }
                }
            }
        }.visit(classLoader);
        return DefaultClassPath.of(implementationClassPath);
    }
```

exception throwed in the try block, when creating File object with given `classPath`, which has urls like:
```
[jar:file:/Users/coney/tooling-api-demo/build/libs/tooling-api-demo-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes!/, jar:file:/Users/coney/tooling-api-demo/build/libs/tooling-api-demo-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-boot-starter-1.5.4.RELEASE.jar!/, jar:file:/Users/coney/tooling-api-demo/build/libs/tooling-api-demo-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/gradle-tooling-api-4.0.1.jar!/, jar:file:/Users/coney/tooling-api-demo/build/libs/tooling-api-demo-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-boot-autoconfigure-1.5.4.RELEASE.jar!/, jar:file:/Users/coney/tooling-api-demo/build/libs/tooling-api-demo-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-boot-1.5.4.RELEASE.jar!/, jar:file:/Users/coney/tooling-api-demo/build/libs/tooling-api-demo-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-boot-starter-logging-1.5.4.RELEASE.jar!/, jar:file:/Users/coney/tooling-api-demo/build/libs/tooling-api-demo-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-context-4.3.9.RELEASE.jar!/, jar:file:/Users/coney/tooling-api-demo/build/libs/tooling-api-demo-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-aop-4.3.9.RELEASE.jar!/, jar:file:/Users/coney/tooling-api-demo/build/libs/tooling-api-demo-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-beans-4.3.9.RELEASE.jar!/, jar:file:/Users/coney/tooling-api-demo/build/libs/tooling-api-demo-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-expression-4.3.9.RELEASE.jar!/, jar:file:/Users/coney/tooling-api-demo/build/libs/tooling-api-demo-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-core-4.3.9.RELEASE.jar!/, jar:file:/Users/coney/tooling-api-demo/build/libs/tooling-api-demo-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/snakeyaml-1.17.jar!/, jar:file:/Users/coney/tooling-api-demo/build/libs/tooling-api-demo-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/logback-classic-1.1.11.jar!/, jar:file:/Users/coney/tooling-api-demo/build/libs/tooling-api-demo-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/jcl-over-slf4j-1.7.25.jar!/, jar:file:/Users/coney/tooling-api-demo/build/libs/tooling-api-demo-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/jul-to-slf4j-1.7.25.jar!/, jar:file:/Users/coney/tooling-api-demo/build/libs/tooling-api-demo-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/log4j-over-slf4j-1.7.25.jar!/, jar:file:/Users/coney/tooling-api-demo/build/libs/tooling-api-demo-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/slf4j-api-1.7.25.jar!/, jar:file:/Users/coney/tooling-api-demo/build/libs/tooling-api-demo-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/commons-logging-1.2.jar!/, jar:file:/Users/coney/tooling-api-demo/build/libs/tooling-api-demo-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/logback-core-1.1.11.jar!/]
```

seems that gradle tooling api is not compitable with spring boot in jar, any ideas?

### Your Environment
https://gradle.com/s/fn3bhx5dvw6kc

**Comment by eriwen** [comment] 2017-07-17 23:42
@coney Thank you for the example project and the build scan.

Quick question: Is the behavior the same with Gradle 3.5.1?

**Comment by oehme** [comment] 2017-09-20 15:31
The TAPI currently doesn't support being packaged in a jar containing other jars. Would you be interested to improve this with a pull request?

**Comment by BoykoAlex** [comment] 2017-11-03 15:32
@oehme wonder if we could put a small temporary fix for this issue... for example check URL for `file` protocol before converting URL to File in `ClasspathUtil#getClasspath(ClassLoader)` Would you be willing to accept such PR for now?

**Comment by oehme** [comment] 2017-11-03 15:41
If it does unblock this use case, then yes such a change would be welcome.

**Comment by BoykoAlex** [comment] 2017-11-04 15:13
@oehme here is PR https://github.com/gradle/gradle/pull/3377 and seems to unblock us

**Comment by martinlippert** [comment] 2017-11-04 17:44
Hey Stefan ( @oehme  ), it would indeed be awesome if we could get this in as soon as possible to unblock us, would be so much appreciated... :-)

**Comment by BoykoAlex** [comment] 2017-11-05 05:21
@oehme @martinlippert perhaps we should hold off merging this PR... The classpath seems correct but looks like JDT cannot resolve `java.security.Principal`... not sure how that happened... feels like side effect of "fat jar"... if I launch our tooling in debug mode without "fat jar" it's resolved correctly.
Think it's early merging this, since I'm not 100% it helps rather then opens a can of worms...

**Comment by BoykoAlex** [comment] 2017-11-05 06:05
@oehme @martinlippert i think the PR is fine (the difference was Java 9 and 8, 9 needs module included to have `java.security.Principal`). Otherwise the PR seems to work alright.

**Comment by bmuschko** [comment] 2017-11-09 23:41
Thanks for reporting. I am going to provide you a link to a nightly soon so you can try out the fix.

**Closed by bmuschko** 2017-11-09 23:41 UTC
Labels: a:feature, affects-version:4.0, from:contributor, in:tooling-api

**Comment by BoykoAlex** [comment] 2017-11-10 04:38
@oehme @bmuschko sounds great! Thanks very much!-)

**Comment by bmuschko** [comment] 2017-11-13 16:14
@coney We fixed this issue. I'd appreciate your feedback by trying out a nightly build of Gradle (`https://services.gradle.org/distributions-snapshots/gradle-4.4-20171112235945+0000-bin.zip`).

You can get the Tooling API from the following repo:

```
repositories {
    maven {
        url 'https://repo.gradle.org/gradle/libs-snapshots-local/'
    }
}

dependencies {
    compile 'org.gradle:gradle-tooling-api:4.4-20171112235945+0000'
```

**Comment by thinstripe** [comment] 2018-01-22 23:50
This isn't working for me.  I observe the same issue as @coney.  I have tried the nightly build you suggested (4.4-20171112235945+0000) and also 4.4.1, 4.5-rc-2 - all are reproducing the same stacktrace.

**Comment by oehme** [comment] 2018-01-23 08:38
@thinstripe can you please provide a reproducible example project? It seems to work for both @DPUkyle and @BoykoAlex, so maybe you are hitting a different issue.

**Comment by thinstripe** [comment] 2018-01-23 22:01
I have cloned coney's project and updated the gradle tooling api to version 4.4-20171112235945+0000 at https://github.com/thinstripe/tooling-api-demo.  Kindly follow the provided README.md instructions to easily reproduce the issue.

**Comment by DPUkyle** [comment] 2018-01-23 22:22
@thinstripe your repo's wrapper is using Gradle 4.0.1. Please update to 4.4.1 and this issue goes away.

**Comment by thinstripe** [comment] 2018-01-24 12:10
Ok that now is working for me.  Thank you!
