### ISSUE TITLE
Prevent community plugins using internal Reporting APIs from breaking with Gradle 6.1

### ISSUE THREAD

**Issue by rpalcolea** [gradle/gradle#11189] opened 2019-10-30 17:24 UTC
Hi folks, something around `TaskGeneratedSingleFileReport` we found a few compilation issues when running with latest nightly

```
The class 'org.gradle.api.plugins.quality.internal.FindBugsXmlReportImpl' must be declared abstract or the method 'org.gradle.api.provider.Property getActivated()' must be implemented.
Abstract method 'org.gradle.api.file.RegularFileProperty getOutputLocation()' is not implemented but a method of the same name but different return type is defined: method 'org.gradle.api.provider.Provider getOutputLocation()'
Abstract method 'org.gradle.api.file.FileSystemLocationProperty getOutputLocation()' is not implemented but a method of the same name but different return type is defined: method 'org.gradle.api.provider.Provider getOutputLocation()'
```

We know that `TaskGeneratedSingleFileReport` is an internal API and we can react to that internally, quickly. However other plugins such as spotbugs, do the same (https://github.com/spotbugs/spotbugs-gradle-plugin/blob/master/src/main/java/com/github/spotbugs/internal/spotbugs/SpotBugsXmlReportImpl.java). What I’ve seen is that:

• most plugins that require reporting, do the same approach as they followed the practice from other Gradle provided ones
• plugin authors are hesitant to adopt new Gradle versions because on this case it would require a breaking change that will break backwards compatibility (this assumes they have to implement the missing methods)

Is there any guidance or public APIs to accomplish the same these days? It seems that we would like to at least reach out plugin authors of the most used like spotbugs and see if they can rewrite that portion, which might not be ideal for some maintainers. Or is it possible for Gradle to introduce some abstract classes in between with noop implementations so folks don’t break?

We believe this is the change https://github.com/gradle/gradle/commit/f95870253382f9f7812e51a1245735b61a7619c5#diff-e2867b54f3dc4e85d12c37a5e0c94646

**Comment by big-guy** [comment] 2019-11-05 06:55
@rpalcolea There are a couple of options...

1. Stop using the Reporting APIs completely.  This means reimplementing some of the functionality with public APIs (or as few internal APIs as possible). This gives up the "feature" of being able to find any Reporting-type tasks.  I think this is only really used by the build-dashboard plugin and nothing else. 
2. Help define what the public Reporting API should have/be. This doesn't just mean "make the internal things public", but more about what use cases should the Reporting APIs solve. I think this is where the current Reporting APIs have stalled.  

Looking at the changes introduced in 6.1, it might be possible to fix the plugins by just making the classes abstract and rely on the decoration that Gradle provides when instantiating the report classes.  The classes in Gradle don't implement the methods that were added either.  We have a smoke test against spotbugs and that's not failing with 6.1 at the moment.

**Comment by melix** [comment] 2019-11-05 10:13
We should probably restore the removed methods, even if internal, in 6.1, add a smoke test for spotbugs, and possibly propose a replacement. I'm not sure anyone _really_ need internal reporting APIs.

**Comment by rpalcolea** [comment] 2019-11-12 18:56
hi folks, number 2 is what we did internally and suggested in https://github.com/spotbugs/spotbugs-gradle-plugin/pull/174

Agree, it would be great to have public APIs for this.

**Comment by lacasseio** [comment] 2019-12-11 13:35
We decided to no change anything for 6.1 regarding this issue. The reason being the API is clearly marked as internal and it seems to be affecting a small number of plugins which have since corrected the implementation to account for the changes. The code has also being heavily refactored which would take us a non-negligible engineering effort to restore enough of the old behavior to prevent the breakage. If the issue is more widely spread than originally assumed, we can revisit the issue. For now, we will close it.

**Closed** 2019-12-11 13:35 UTC
Labels: a:feature, from:contributor
