### ISSUE TITLE
Flaky dependency verification on gradle/gradle

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#16508] opened 2021-03-12 13:50 UTC
Roughly every second time I build `gradle/gradle`, I get the following error:

```
> Task :spotlessInternalRegisterDependencies FAILED
You probably need to add a repository containing the '[com.google.googlejavaformat:google-java-format:1.9]' artifact in the 'build.gradle' of your root project.
E.g.: 'buildscript { repositories { mavenCentral() }}'
org.gradle.api.InvalidUserDataException: Dependency verification failed for configuration ':detachedConfiguration1'
One artifact failed verification: error_prone_annotations-2.3.2.jar (com.google.errorprone:error_prone_annotations:2.3.2) from repository Gradle Central Plugin Repository
If the artifacts are trustworthy, you will need to update the gradle/verification-metadata.xml file by following the instructions at https://docs.gradle.org/7.0-20210309210224+0000/userguide/dependency_verification.html#sec:troubleshooting-verification
``` 

Any idea what the issue might be?

**Comment by wolfs** [comment] 2021-03-12 13:53
@oehme I suppose this is similar to what @lptr has experienced: https://github.com/gradle/gradle/pull/16478/commits/f9afaf6186d2bce74d09101a78dd195ef23450b2

**Comment by melix** [comment] 2021-03-12 14:13
This is indeed a duplicate of https://github.com/gradle/gradle/issues/16500

**Closed by melix** 2021-03-12 14:13 UTC
Labels: a:bug, from:contributor

**Comment by oehme** [comment] 2021-03-12 14:29
Thanks!
