### ISSUE TITLE
settings.gradle is ignored when a custom build file is called using the -b switch on command line

### ISSUE THREAD

**Issue by bcorne** [gradle/gradle#3828] opened 2017-12-15 14:59 UTC
### Current Behavior
I have two gradle scripts in the same folder both building the same project, one is called build.gradle and the other one is called build_jdk8.gradle. There's a settings.gradle file in which I set the project name.

When I build the project using the default build file calling:

./gradlew clean build

The project has the right name defined in the settings.gradle

When I build the project using the custom build calling:

./gradlew -b build_jdk8.gradle
or
./gradlew -c settings.gradle -b build_jdk8.gradle

The project's name is the name of the root directory (as if the config file were ignored) 

### Expected Behavior
I would have expected that any custom gradle script would use the settings file (at least when you force point it using the command line option) 

### Context

I need to compile the project using various kind of bytecode level

**Comment by moley** [comment] 2019-08-13 06:28
Hi, any changes on this issue? I also have the problem that I have to create a custom buildfile, which should use settings.gradle. But even when I tell gradle with --settings-file to use the settings file it fails with an error bla.gradle is not part of the build defined by settings file settings.gradle.If this is an unrelated build, it must have its own settings file. Can I somehow work around this?

**Comment by DmitriyMX** [comment] 2020-04-27 14:20
The problem is still relevant. Has anyone found a solution in the last year? In the last three years? Nobody?

**Comment by pditommaso** [comment] 2020-05-30 11:43
Same here

**Comment by arioco** [comment] 2020-08-31 14:30
Same problem:

I have this structure:

 .
├── myProject
│   ├── build.gradle
│   ├── real-build.gradle 
│   └── settings.gradle
└── myUtil
    ├── build.gradle
    └── settings.gradle

myProject/build.gradle is a copy of myProject/real-build.gradle (the important one), only for this example.

myProject/settings.gradle is this:

rootProject.name = 'myProject'
include 'myUtil'
project(':myUtil').projectDir = file('../myUtil')

In terminal, on ./myProject folder, I try these commands:

**gradle build** -> OK

**gradle -b build.gradle build** -> OK

**gradle -b real-build.gradle build** -> ERROR: Project with path ':myUtil' could not be found in root project 'myProject'.

**gradle -b real-build.gradle -c settings.gradle build** -> ERROR: Build file './real-build.gradle' is not part of the build defined by settings file './settings.gradle'. If this is an unrelated build, it must have its own settings file.

Please help!!!

**Comment by jimshowalter** [comment] 2021-02-20 20:48
Exact same problem, and this bug was filed more than three years ago.
Is there a workaround? For example, some way to perhaps make a copy of the settings.gradle and modify it to make Gradle happy?

**Comment by sickhead** [comment] 2021-03-05 08:46
settings_ignore.gradle :
#new line
**rootProject.buildFileName = 'build_ignore.gradle'**   

rootProject.name = 'myProject'
include 'myUtil'
project(':myUtil').projectDir = file('../myUtil')

**gradle -b build_ignore.gradle -c settings_ignore.gradle bootRun** -> OK

**Comment by jimshowalter** [comment] 2021-03-05 19:36
Very nice! I didn't know about setting the buildFileName.

https://stackoverflow.com/questions/12246215/gradle-multi-project-change-default-build-filename-build-gradle

It turns out I also need to use a non-default gradle.properties file. Is there some way to do that?

**Comment by bmuskalla** [comment] 2021-04-08 12:48
Given we're about to deprecate `-b`, I'll close this bug as wontfix. See #16402 for details

**Closed by bmuskalla** 2021-04-08 12:48 UTC
Labels: a:bug
