### ISSUE TITLE
Start including .asc signature files for jars in the distribution zip

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#21932] opened 2022-09-08 16:28 UTC
Gradle distribution zip includes over a hundred jars that are third-party and fetched from maven as binaries. During the bundling process, all of the .asc signatures files are dropped, making the lib/* directory only contain jars.

### Expected Behavior
Be able to verify that the external jars have not been modified and match signatures.

### Current Behavior
Signatures are missing and validation is very difficult

### Context
Our team is trying to strengthen our build toolchain security. We are able to build gradle itself from source to verify it is the same as Gradle published version. However, the included 3p jars are currently difficult to validate.

As a bonus, it would be awesome that in addition to the signatures distribution would also include a list of URLs where each jar was downloaded from.

**Comment by vlsi** [comment] 2022-09-08 19:06
I guess it would be better start using sigstore signatures rather than invest time in PGP

**Comment by liutikas** [comment] 2022-09-09 03:18
> I guess it would be better start using sigstore signatures rather than invest time in PGP

This is not about Gradle doing any signing. This is about copying over existing ASC files that are maven standard and exists for most of these artifacts

**Comment by liutikas** [comment] 2022-09-09 03:19
> I guess it would be better start using sigstore signatures rather than invest time in PGP

This is not about Gradle doing any signing. This is about copying over existing ASC files that are maven standard and exists for most of these artifacts

**Comment by liutikas** [comment] 2022-09-09 03:19
> I guess it would be better start using sigstore signatures rather than invest time in PGP

This is not about Gradle doing any signing. This is about copying over existing ASC files that are maven standard and exists for most of these artifacts

**Comment by vlsi** [comment] 2022-09-09 04:36
>existing ASC files that are maven standard

PGP signatures are not Maven standard, and it is likely Central will remove .asc requirement soon.

**Comment by ov7a** [comment] 2024-03-19 13:59
This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/13778

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

**Closed by ov7a** 2024-03-19 13:59 UTC
Labels: a:feature, in:building-gradle
