### ISSUE TITLE
Outgoing artifacts as provider of a task output cause the failure

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#19044] opened 2021-11-18 18:28 UTC
### Expected Behavior

Using the output property of a task as outgoing artifacts is allowed. For example:
```
def jarTask = tasks.register('jar', Jar)

def config = configuration.create('potato') { /* configure as consumable */ }
config.outgoing.artifact(jarTask.flatMap { it.archiveFile })
```

### Current Behavior

Using such a task output provider will cause a crash because of the "query provider before task executes" check. The `Configuration` seems to be queried internally for the artifact file which happens to be done before the task graph is computed or executed. There are two ways to work around it which simply hide the issue: 1) create a temporary provider to fool the check or, in this particular case, use the `TaskProvider<Jar>` instead of a `Provider<RegularFile>` as internally archive task have special handling. Both solution are pretty bad as they rely on internal behavior of Gradle.

### Context

Similar but not exactly this other issue: https://github.com/gradle/gradle/issues/15146

### Your Environment

Build scan URL:

**Comment by vlsi** [comment] 2021-11-18 19:31
Just wondering, @lacasseio , do you think it is a duplicate of https://github.com/gradle/gradle/issues/16777#issuecomment-817303964 ?

**Comment by lacasseio** [comment] 2021-11-18 19:49
It's close but not exactly the same. If I'm not mistaken,. it's possible to add a provider as artifact on a consumable configuration and if that provide has task dependencies, it will be pickup properly. The issue here is if the provider in question refers to a task output then the check will trigger because the provider is queried to figure out what's kind of provider it is. Creating a provider with task dependency that is not a task output if tricky. Archives task (zip, jar, tar, etc) have a special handling mostly for legacy reason where you can just pass the task provider and it will work. In the past, I did work around by creating an archive task just so I could defer the resolution but it's assume the final file is an archive file. 🙃

**Comment by vlsi** [comment] 2021-11-18 20:25
Please add the stacktrace :)

**Comment by lacasseio** [comment] 2022-11-29 07:11
I believe this is still valid.

**Comment by jvandort** [comment] 2023-10-17 21:57
Can you provide a full reproducer for this? I have attempted to reproduce but this, but it seems to be working fine for me:

```
    def "test"() {
        given:
        settingsFile << "include 'producer'"

        file("producer/src/Foo.txt") << "Hello!"
        file("producer/build.gradle") << """
            plugins {
                id("base")
            }

            def jarTask = tasks.register('jar', Jar) {
                from(layout.projectDirectory.dir("src"))
            }

            configurations {
                consumable("potato") {
                    outgoing {
                        artifact(jarTask.flatMap { it.archiveFile })
                    }
                    attributes {
                        attribute(Category.CATEGORY_ATTRIBUTE, objects.named(Category, "foo"))
                    }
                }
            }
        """

        buildFile << """
            configurations {
                dependencyScope("conf")
                resolvable("res") {
                    extendsFrom conf
                    attributes {
                        attribute(Category.CATEGORY_ATTRIBUTE, objects.named(Category, "foo"))
                    }
                }
            }

            dependencies {
                conf project(":producer")
            }

            task copy(type: Copy) {
                dependsOn configurations.res
                from {
                    zipTree(configurations.res.incoming.files.singleFile)
                }
                into layout.buildDirectory.dir("unzip")
            }

            task verify {
                dependsOn tasks.copy
                doLast {
                    assert file("build/unzip/Foo.txt").exists()
                    assert file("build/unzip/Foo.txt").text == "Hello!"
                }
            }
        """

        expect:
        succeeds ":verify"
    }
```

**Comment by ghale** [comment] 2023-10-25 19:38
I've also tried to reproduce this in a number of ways and using various versions of Gradle and I've not been able to recreate the behavior.  I suspect there's some detail missing with respect to what will trigger the behavior, but I haven't been able to find it.  I'm closing this for now, but happy to revisit if there's a good reproducer available.

**Closed by ghale** 2023-10-25 19:38 UTC
Labels: a:bug, in:configuration-model, in:dependency-declarations, in:provider-api, p:lazy-migration
