### ISSUE TITLE
Support ABI-detection for source files in JavaCompile

### ISSUE THREAD

**Issue by yissachar** [gradle/gradle#24934] opened 2023-04-27 21:24 UTC
### Expected Behavior

I expect incremental compile to only compile classes that changed directly, or that depend on public interfaces that have changed. Internal implementation details in a class that change should only trigger recompilation of that class itself, not classes that depend on it.

### Current Behavior

If a class A references class B then class A will also be recompiled whenever class B changes, even if the change does not actually affect class A.

### Context (optional)

We have a large repo where compilation is very slow. Incremental compilation should make this better and limit compilation to only what has changed but due to this bug results in thousands of classes needing to be compiled whenever any sort of change is made. 

### Steps to Reproduce

Using https://github.com/yissachar/incremental-compile-test, run `compileJava`, then in FooBar.java change the "foo" String to "oof", and run `compileJava` again. Both FooBar.java and Main.java will be recompiled, even though Main.java shouldn't be affected.

### Gradle version

8.1.1

### Your Environment (optional)

MacOS

**Comment by jbartok** [comment] 2023-05-03 08:57
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by octylFractal** [comment] 2023-05-06 03:11
I don't think this is a bug, but rather a spot currently lacking in our incremental compilation analysis between source files. We cannot know what the exact resulting class file changes will be without compiling it first. The set of classes that need compiling currently must be known ahead of time, and that means that we have to assume that any change could change the ABI. Quoting from the [docs](https://docs.gradle.org/8.1.1/userguide/java_plugin.html#sec:incremental_compile):
> A class’s dependencies are determined from type references in its bytecode or symbol analysis via a compiler plugin.

Which is correct, we _only_ look at if the previous class used the type name in its bytecode, not if the changed class only changed by implementation. So in your reproducer, we see that `Main` refers to `FooBar`, and must recompile `Main` if `FooBar`'s source changes. 

For a workaround, the recommendation given by the docs is applicable here:
> You can improve incremental compilation performance by applying good software design principles like loose coupling. For instance, if you put an interface between a concrete class and its dependents, the dependent classes are only recompiled when the interface changes, but not when the implementation changes.

Changing `Main` to rely on a theoretical `FooBarifier` interface that `FooBar` implements would prevent recompiling `Main` on changes to `FooBar`. This workaround isn't possible or desirable in all cases though, so I'll leave this open for future work to improve the granularity of what we track for source-file changes.

**Comment by yissachar** [comment] 2023-05-07 03:56
Thanks, that's helpful context. However, I'm a bit confused because some changes I make in my real project do seem to track ABI changes. I have a class A that is referenced by many other classes, and making changes directly to this class will result in 2000+ classes being recompiled. However A instantiates class B (and is the only class referencing class B) and making changes to class B will only result in 5 classes being recompiled. From my understanding of what you wrote, changes to B should trigger a recompile of A and then all classes referencing A, so I would expect this to be 2000+ classes being recompiled, not just 5.

I haven't been able to create a reproducer for this case unfortunately.

**Comment by asodja** [comment] 2023-05-07 10:01
Since only source of B has changed Gradle can do normal compile avoidance for classes that has B as reference in next steps, e.g. for A: 
- if A depends on B's ABI (e.g. A extends B), then also all classes referencing A has to recompile
- if A just uses B privately, then just A has to be recompiled

Additional note: due to current limitation of source ABI changes detection one strategy to improve compile times can also be to split your project in multiple smaller projects. Since projects are compiled with different compile task, Gradle can distinguish between ABI/non-ABI changes for classes that depend on classes from other project.

**Comment by yissachar** [comment] 2023-05-08 15:55
@asodja That doesn't seem to be the case, or at least the only factor. Many of the classes using A are using A privately, and still need to be recompiled, so I'm not sure what the difference is in the relationship between classes using A privately and the fact that A uses B privately.

We are trying to split the project in multiple smaller modules, but both this and the interface approach require some contortions from us.

**Comment by ljacomet** [comment] 2023-05-12 09:17
Given the conversation, closing this as there are:
* no plans to improve what Gradle does at this stage
* possible workarounds if you have pathological behaviors in your code base

**Closed by ljacomet** 2023-05-12 09:17 UTC
Labels: a:feature, in:java-plugins
