### ISSUE TITLE
Android incremental build times are worse in 6.8.1 from 6.7.1

### ISSUE THREAD

**Issue by elihart** [gradle/gradle#15919] opened 2021-01-23 00:53 UTC
### Expected Behavior
I'd expect build times to stay the same or get better with a new release.

### Current Behavior
Some incremental builds in our Android project are roughly 12% slower in 6.8.1 than in 6.7.1 as measured with the Gradle Profiler tool.

### Context
I ran routine profiling when updating to 6.8 hoping to see potential improvements to build speeds. I was surprised to see that 6.8.1 was actually slower than 6.7.1.

### Steps to Reproduce 
I unfortunately cannot provide a sample project that reproduces it, as my results are from our large internal Android app.

However, I can say that I measured the build speeds using version 0.15.0 of the gradle profiler (https://github.com/gradle/gradle-profiler/releases/tag/v0.15.0), and the scenario I am profiling makes an ABI change to a class in a base module that many other modules depend on.

It is run with the command
```
gradle-profiler-0.15.0/bin/gradle-profiler --benchmark --profile buildscan --gradle-user-home=$HOME/.gradle --project-dir=/jorb/repo/android --output-dir=/jorb/repo/android/build/profiling/MyFlavorIncrementalBaseAbiChange --scenario-file /tmp/myflavor_assembledebug_with_base_abi_change.scenarios
```

and the scenario in the scenario file is
```
default-scenarios = ["myflavor_assembledebug_with_base_abi_change"]
"myflavor_assembledebug_with_base_abi_change" {
    apply-abi-change-to="base/src/main/java/com/airbnb/android/base/BaseDagger.kt"
    git-checkout {
        build=e3738fe8addc02b110db811453f32ac4b3baa176
    }
    tasks=[
        "flavor.myflavor:assembleDebug"
    ]
    title="myflavor assembleDebug with base abi change"
}
```

This uses 6 warm up iterations and 10 build iterations (the default). I ran this multiple times where the only difference between commits was the gradle version, and the result consistently showed slower builds in 6.8.1

This zip contains the csv and html result files of two runs with the different gradle versions.
[benchmark_results.zip](https://github.com/gradle/gradle/files/5859321/benchmark_results.zip)

### Your Environment
We are using Android Gradle Plugin 4.1.1 and Kotlin 1.4.20. The project has several dozen modules.

**Comment by lptr** [comment] 2021-01-25 12:16
Hi @elihart! Thanks for sharing this. We are doing some quite intensive performance regression testing on Android projects, and we've been actively working on improving Android incremental build performance, so this finding is quite surprising to me. Could you help me investigate?

Could you use Gradle Profiler to capture an async profiler flame graph for 6.7.1 and 6.8.1? This should not expose sensitive information. We could also get in touch on the community Slack: https://gradle-community.slack.com/ if that also works for you.

**Comment by elihart** [comment] 2021-01-25 20:50
Thanks for the quick response, yes I would be happy to help investigate. I am working on getting those flame graphs for you, but dealing with some trouble getting it enabled in our CI (https://github.com/gradle/gradle-profiler/issues/151). 

Slack works for me to communicate more easily; I think I may need an invite to create an account?

Also, a few more details I realized may be helpful:
- We currently have incremental kotlin disabled due to some incremental KAPT bugs. We heavily use Kotlin and KAPT contributes to our longest tasks
- I am running the profiling on linux CI machines

**Comment by lptr** [comment] 2021-01-26 08:45
Thanks again @elihart. I believe you can create an account on Slack by clicking in the top-right corner on this:

![image](https://user-images.githubusercontent.com/495366/105821435-23424200-5fbb-11eb-8dae-8c8246d2949a.png)

Could you also capture some build scans of the builds with the two different Gradle versions?

**Comment by lptr** [comment] 2021-01-26 14:18
We've been able to reproduce a significant regression with a mockup of Uber's large Android build: https://github.com/uber-common/android-build-eval

It is likely that we will release a fix in 6.8.2.

**Comment by elihart** [comment] 2021-01-26 15:26
Great to hear you were able to reproduce a regression. Do you still need me to provide flame graphs? Our build scans go to our own hosted server, so I'm not sure the best way to share them.

The gradle community slack seems to require an @gradle.com email address to sign up, or an invite.

![image](https://user-images.githubusercontent.com/2739242/105865411-87173b80-5fb8-11eb-905b-aca2305f26ae.png)

**Comment by wolfs** [comment] 2021-01-26 15:28
@elihart Do you have file system watching enabled in your builds?

**Comment by elihart** [comment] 2021-01-26 15:29
yes, we have file system watching enabled

**Comment by lptr** [comment] 2021-01-26 17:49
I found the forum post that describes how to join Slack: https://discuss.gradle.org/t/introducing-gradle-community-slack/26731

Unfortunately the link on the login page is not the right one. I asked Slack for advice on how to update that.

**Comment by wolfs** [comment] 2021-01-27 09:12
@elihart We found a regression which may be related and made a fix for it. Can you try out if things are better with `6.8.1-branch-wolfs_vfs_early_exit_hasDescendants-20210126175840+0000`? If they aren't, please send us the async profiler flame graphs generated by `--profiler async-profiler`.

One thing which could influence/cause the performance regression is when you run `gradle-profiler` in the project directory, since then the Gradle user home is in the project directory as well, and Gradle will start watching things in the Gradle user home as well - which it doesn't if the Gradle user home is outside of the project directory as normally. I suggest running `gradle-profiler` from a parent or sibling of the project directory and using `--project-dir`.

**Comment by elihart** [comment] 2021-01-27 18:40
Yes, I will try that and report back.

I may be missing something simple... but how do I actually use `6.8.1-branch-wolfs_vfs_early_exit_hasDescendants-20210126175840+0000` ? If I simply try to set that as the gradle version in our project it is not found. Do I need to add a special repository or something?

**Comment by lptr** [comment] 2021-02-01 11:09
FTR, it looks like this is a different regression to https://github.com/gradle/gradle/pull/15948 that affects Linux instead of macOS/Windows. Trying to reproduce with the Uber mockup https://github.com/uber-common/android-build-eval.

**Comment by lptr** [comment] 2021-02-02 09:47
I was unsuccessful in reproducing the problem on Linux with the Uber mockup:

![image](https://user-images.githubusercontent.com/495366/106582052-da066b00-6543-11eb-913b-226204920af4.png)

I was running:

```console
$ gradle-profiler --benchmark --gradle-version 6.7.1 --gradle-version=6.8.2-20210128010010+0000 --iterations=10 --warmups=2 --scenario-file mobile_app1/performance.scenarios --project-dir mobile_app1 abiChangeWithMaxLeafLocalCache
```

**Comment by lptr** [comment] 2021-02-02 16:34
@elihart's results look like this:

![image](https://user-images.githubusercontent.com/495366/106631235-d5aa7400-657c-11eb-9f46-9281abd3ceed.png)


version | Gradle 6.7.1 | Gradle 6.8 nightly
-- | -- | --
warm-up build 1 | 209,347 | 332,374
warm-up build 2 | 62,536 | 65,706
warm-up build 3 | 55,014 | 62,535
measured build 1 | 59,069 | 70,409
measured build 2 | 67,791 | 78,594
measured build 3 | 62,233 | 74,076

**Comment by BoD** [comment] 2021-02-12 15:00
Just to clarify, as this is open, but 6.8.2 has been released, and this doesn't have the label "affects-version-6.8.2": this is still unresolved on 6.8.2, right?

**Comment by wolfs** [comment] 2021-02-12 15:11
@BoD: You are right. I created the `affects-version:6.8.2` label and assigned it to this issue.

**Comment by deejay1** [comment] 2021-02-23 07:57
I don't see this as a known issue in 6.8.3 - did the build cache fix also affect this?

**Comment by wolfs** [comment] 2021-03-09 14:14
I looked at a chrome trace of 6.7.1 vs 6.8.3. It seems like the `KaptExecution` (worker item) take longer. The cumulative time (482s vs. 363s) as well as the wall clock time (60s vs 50s) seems to indicate that these in-process work items with no-isolation became slower. That may mean that classloading for the Worker items became slower, since this is what a lot of time of Kapt is spent on. Classloading for the in-process work items will probably go through the whole Gradle infrastructure, so maybe that became slower. I wonder if out-of-process kapt execution is affected as well, or if there wouldn't be a regression between Gradle 6.8.3 and 6.7.1.

**Comment by wolfs** [comment] 2021-03-19 08:44
We didn't find out the root cause of this problem. I had a hunch that the Kotlin plugin version was different on the two runs, though that doesn't seem to be the case. Finally it seems that incremental KAPT is faster with Gradle 6.8.3, so there isn't a performance regression for that case. I'll close this issue now since I won't be doing more investigations here. If somebody else is experiencing similar problems, then please comment on this issue.

**Closed by wolfs** 2021-03-19 08:44 UTC
Labels: @execution, a:regression, affects-version:6.8, affects-version:6.8.1, affects-version:6.8.2, affects-version:6.8.3, from:contributor
