### ISSUE TITLE
Full JaCoCo support for JVM test suites

### ISSUE THREAD

**Issue by rkrisztian** [gradle/gradle#19217] opened 2021-12-04 17:48 UTC
In a Groovy project of mine, I tried to migrate from the [org.unbroken-dome.test-sets](https://github.com/unbroken-dome/gradle-testsets-plugin) plugin to [the JVM Test Suite Plugin](https://docs.gradle.org/current/userguide/jvm_test_suite_plugin.html). And here is my current way of doing it:

https://github.com/rkrisztian/search/commit/a62afd9f364a7902029c6451612e0c24c508ef78

As you can see, it's not perfect yet:

* No JacocoReport task is created for each test task. The test-sets plugin does it ([see source](https://github.com/unbroken-dome/gradle-testsets-plugin/blob/v4.0.0/src/main/kotlin/org/unbrokendome/gradle/plugins/testsets/TestSetsPlugin.kt#L184)).
* It has always been [a manual effort](https://github.com/gradle/gradle/issues/12912) to also aggregate the coverage results, but even if I don't create a JacocoReport task for each test task and just make the `jacocoTestReport` task do the aggregation as the ticket suggested, setting `jacocoTestReport.reports.executionData testing.suites.integrationTest` won't work because it's not a supported syntax); and `jacocoTestReport.reports.executionData 'integrationTest'` results in a failure `Unable to read execution data file /home/rkrisztian/projects/search/build/test-results/integrationTest/binary`.
* I shouldn't be needed to add `implementation configurations.testCompileClasspath` to the `integrationTest` suite, but if I don't do, then Gradle won't be able to find `XmlSlurper`, which is part of the `groovy-xml` jar, which is a transitive dependency of `groovy-all`, which is a project dependency, which I already included into the suite.

So what I'm asking is:

* for the linked user guide to include examples for the use of the Jacoco plugin as well.
* examples for inheriting dependencies from the `test` suite, just as how the test-sets plugin did.
* So far I never needed to use `jacocoTestCoverageVerification`, but we should probably document how it can work together with the test suites plugin...

**Comment by ljacomet** [comment] 2021-12-06 09:41
Have a look at 7.4 nightlies - improved support for Jacoco aggregation, combined with test suites, is coming. However looks like the docs still need to be done. #19068 should give you some ideas on APIs.

**Comment by ljacomet** [comment] 2021-12-06 09:42
Closing as duplicate of #18914

**Closed by ljacomet** 2021-12-06 09:42 UTC
Labels: a:feature, in:jacoco-plugin, closed:duplicate, in:test-suites

**Comment by rkrisztian** [comment] 2022-03-05 11:45
@ljacomet , I've tested Gradle release 7.4 and the `jacoco-report-aggregation` plugin, but **it solved nothing for me**, is it possible to reopen this issue?

The problem is that I don't have multiple subprojects to work with, **I just have multiple test suites in the same project**, and the JaCoCo reports of those are not aggregated at all.

According to the documentation:

> The JaCoCo Report Aggregation plugin (plugin id: jacoco-report-aggregation) provides the ability to aggregate the results of multiple JaCoCo code coverage reports (potentially spanning multiple Gradle projects) into a single HTML report.

Despite that, I can't configure a report task that combines all test types. The API simply does not allow such a thing.

=> It would help if the aggregation plugin could support both dimensions (multiple projects × multiple tasks per project).

**Comment by rkrisztian** [comment] 2022-04-02 08:48
@ljacomet, would it be possible to support JaCoCo aggregation for each test task in the same subproject too?

**Comment by praveen-em** [comment] 2022-04-22 14:32
> @ljacomet , I've tested Gradle release 7.4 and the `jacoco-report-aggregation` plugin, but **it solved nothing for me** (except: "No JacocoReport task is created for each test task."), is it possible to reopen this issue?
> 
> The problem is that I don't have multiple subprojects to work with, **I just have multiple test suites in the same project**, and the JaCoCo reports of those are not aggregated at all.
> 
> According to the documentation:
> 
> > The JaCoCo Report Aggregation plugin (plugin id: jacoco-report-aggregation) provides the ability to aggregate the results of multiple JaCoCo code coverage reports (potentially spanning multiple Gradle projects) into a single HTML report.
> 
> Despite that, I can't configure a report task that combines all test types. The API simply does not allow such a thing.
> 
> => It would help if the aggregation plugin could support both dimensions (multiple projects × multiple test suites per project).
> 
> _Edit:_ So all I could do was: [rkrisztian/search@ec93a56](https://github.com/rkrisztian/search/commit/ec93a56c6d01f5398fcb626a0fbefc8c18bbc267)

@rkrisztian , I am trying to do the same thing (i.e., multiple test suites per project) but no luck so far. just wondering if you managed to get this working?

**Comment by ljacomet** [comment] 2022-04-22 15:27
@gradle/bt-core Can you talk a look and answer / re-open?

**Comment by tresat** [comment] 2022-04-25 20:45
This is not something we currently support.  Each aggregation is for a specific test type, and you cannot have more than one test suite of a given type in the same project.

Why do you want to do this, vs. splitting the test suites with the same type amongst multiple sub-projects?  Why have 2 different groups of say, integration tests?  What would distinguish them programmatically?  Any information you can give us about your use case can help inform our discussions.

**Comment by rkrisztian** [comment] 2022-04-25 21:04
Example project structure:

```none
fullStackAppProject
|- microservice1Subproject
|  |- unit tests
|  `- integration tests
|- microservice2Subproject
|  |- unit tests
|  `- integration tests
`- frontendSubproject
    |- unit tests
    |- integration tests
    `- end-to-end tests
```
Questions I might ask:

* *What is the total whitebox coverage for the whole project?* (Do we test enough?)
* *What is the total whitebox coverage for the whole project per test type (unit, integration)?* (Does our testing pyramid look like a pyramid or an ice-cream cone?)
* *What is the total whitebox coverage for each subproject?* (E.g., in which subproject should we need to focus on writing more/better tests?)

Something like that.

Additionally, on the root level I prefer seeing the test results of all modules for each test type. This allows easy reporting in CI tools that consume HTML reports.

**Comment by rkrisztian** [comment] 2022-04-25 21:07
So by now it should be clear that when I talk about `testing.suites`, I just take over Gradle's terminology for different test types like unit, integration... It looks like the Gradle API is confusing in this regard, and "suites" is probably not the right term. Or I completely misunderstood what it should be about. Regardless, I've been looking for an option to replace the Gradle test-sets plugin. Was I looking at the wrong direction?

**Comment by tresat** [comment] 2022-04-26 13:41
@rkrisztian - The JVM Test Suite Plugin is definitely what you should be looking at to replace [the test-sets plugin](https://github.com/unbroken-dome/gradle-testsets-plugin).  It's not a complete replacement for the functionality offered there (yet), but is still under active development and we have a lot of ideas for interesting things we want to do with it soon.  It is our goal to make the test suites plugin the idiomatic solution for most use cases involving dividing a projects' tests into different groups.

I think aggregating across multiple test suite types within the same project **is** something we want to support, and the discussions we've been having are more about how we want to implement this.  As a temporary workaround, you could always customize the report task used by the `JacocoReportAggregationPlugin` to add additional execution data from other test types to the collection in a `doFirst` block, so that the report would run using all of them.  The plugin does this using dependency resolution, but ultimately all that matters is that the `*.exec` files make it into that collection prior to the report running (and make sure all the classes/source are in the other task collections, but it seems like they already would be, most of the time).

Thank you for the example.  One more question: Why do this the Gradle API, or the term "suites" is confusing here?

**Comment by tresat** [comment] 2022-04-26 13:42
@big-guy - Do you have anything to add?

**Comment by rkrisztian** [comment] 2022-04-26 18:19
@tresat , good question, it's just that recently I recognized that meanings of the following terms get confusing to me when it comes to understanding the JVM Test Suites plugin:

* *Test types:* what are our goals? (smoke, regression, performance, functional, etc.), or in what kind of granularity do we want to test the SUT (functional testing pyramid levels). (In detail: https://www.applause.com/blog/functional-testing-types-examples)
* *Test suites:* a collection of test cases, used to group similar test cases together (smoke tests, or testing specific features of the system, etc.), and they can be of any type. (In detail: https://www.tutorialspoint.com/software_testing_dictionary/test_suite.htm)

Although there is some intersection where the two may be interchangeable for the same set of tests, I wouldn't go there, because I lost it already when I read:

> you cannot have more than one test suite of a given type in the same project
