### ISSUE TITLE
Exceptions thrown by user code in Kotlin scripts is ignored during IDEA sync

### ISSUE THREAD

**Issue by ldaley** [gradle/gradle#17833] opened 2021-07-26 01:55 UTC
In my case, I wanted to have the build fail-fast if a critical condition was not met. I added logic to `settings.gradle.kts` to throw an exception if the condition was not met. This worked, except for when performing “sync” in IDEA. There, the exception was silently thrown.

### Expected Behavior

The exception should have caused the build to fail fast, as it does when performing any other kind of “non sync” build.

### Current Behavior

The exception is silently swallowed.

### Context

I have a hunch that IDEA is doing this intentionally in order to sidestep compilation problems in scripts. That is, it tries to degrade gracefully when there are problems with scripts.

### Steps to Reproduce 

- Ensure your settings script is written in Kotlin (i.e. `settings.gradle.kts`). 
- Add `throw Exception("!")` to a path that will be executed. 
- Invoke a build directly (e.g. via CLI) - should fail
- Import/sync the project in IDEA, does not fail

Note: if the script is Groovy, the exception propagates.

Confirmed with 7.1 and 7.2-20210702002720+0000.

**Comment by bamboo** [comment] 2021-07-26 18:43
I suspect this might be related to the Kotlin DSL model builder's leniency, https://github.com/gradle/gradle/blob/3f46045c68ec2db839c0b5c7239590f68a00dedf/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/provider/KotlinDslProviderMode.kt#L28-L29.

**Comment by big-guy** [comment] 2021-12-17 18:15
dupe of #18637

**Closed by big-guy** 2021-12-17 18:15 UTC
Labels: a:bug, in:kotlin-dsl, in:ide
