### ISSUE TITLE
Single lock file changes on generation without external change

### ISSUE THREAD

**Issue by lewiscog** [gradle/gradle#12973] opened 2020-04-30 07:13 UTC
### Expected Behavior
The order of configurations should be consistent upon write.

### Current Behavior
Executing --write-locks causes a change in the order of configurations, resulting in a diff on the entire file.

### Context
Clutters diffs.

### Steps to Reproduce 
1. Add some dependencies.
2. Enable preview for `ONE_LOCKFILE_PER_PROJECT`.
3. Lock all configurations.
4. Capture lock file(s).
5. Lock all configurations again (without changing any configurations/dependencies).
6. Diff against previous locks.

### Your Environment
Gradle 6.4-rc-3.
Parallel & cache enabled.
Java 11.

**Comment by ljacomet** [comment] 2020-04-30 09:20
Thanks for the report. There is indeed no explicit sorting and thus the configurations are not in alphabetical order, which should be corrected.
However, on a simple single project, I cannot change the order, even when writing locks and resolving configurations one by one in different order.

Any chance you can craft a reproducer?

**Comment by lwis** [comment] 2020-04-30 09:40
@ljacomet Sure, please see https://github.com/lwis/gradle-12973 - minimum I could do to reproduce it.

Execute `./gradlew dependencies --write-locks` and observe the lockfile change, execute again and it changes back due to the ordering.

I also observed that an empty `dependency-locks` directory is being generated in the `gradle` directory during generation of locks.

**Comment by lwis** [comment] 2020-04-30 09:43
Maybe more concerning is the fact that it's still writing configurations to the lockfile that no longer exist...

**Comment by ljacomet** [comment] 2020-04-30 10:03
@lwis Thanks for the reproducer, did not think about testing with empty configurations only. The fix I have, that will sort configurations, resolves that issue so all good there 😉 

For the empty directory, will have a look as well.

As for the question of configurations that no longer exist ... that's an existing issue with locking and the way you can have very dynamic configurations in a build.
When writing the single lock file, there is no way to know if configurations not resolved during the build no longer exist or were simply not needed by tasks.
So pruning configurations is tricky. Maybe with the single lock file, there should be a special flag for pruning specific configurations.

Note that the issue existed with one lock file per configuration. Except that the pruning by hand was much easier: just delete the file.

**Comment by lwis** [comment] 2020-04-30 10:20
@ljacomet Brilliant. Thanks that makes sense, I was aware of the issue but hoped it may have been resolved somehow with the new approach.

**Closed** 2020-04-30 13:44 UTC
Labels: @jvm, a:bug, from:contributor, in:dependency-management

**Comment by ljacomet** [comment] 2020-05-05 09:20
as an FYI, created #13024 for the stale configurations topic.

**Comment by lwis** [comment] 2020-05-05 09:35
Watching, thanks!
