### ISSUE TITLE
Unsupported characters on artifact versions

### ISSUE THREAD

**Issue by ignasi35** [gradle/gradle#13445] opened 2020-06-16 17:13 UTC
Despite being listed as a valid version in the [catalog](https://plugins.gradle.org/plugin/com.lightbend.akka.grpc.gradle/1.0.0-M1+37-732f2dee) the plugin `  id "com.lightbend.akka.grpc.gradle" version "1.0.0-M1+37-732f2dee"` is unusable.

The problem seems to be the `+` character in the version. The version ID above is produced using [`sbt-dynver`](https://github.com/dwijnand/sbt-dynver/) combining the latest tag, the number of commits since that tag and the SHA1 of the actual commit that produced the artifact.

The problem seems to be resolving the metadata of the plugin. After a first hit to https://plugins.gradle.org/m2/com/lightbend/akka/grpc/akka-grpc-gradle-plugin/1.0.0-M1+37-732f2dee/akka-grpc-gradle-plugin-1.0.0-M1+37-732f2dee.pom the server returns an HTTP status `303` with a new `Location:` header pointing to a new URL:

```
$ curl -v https://plugins.gradle.org/m2/com/lightbend/akka/grpc/akka-grpc-gradle-plugin/1.0.0-M1+37-732f2dee/akka-grpc-gradle-plugin-1.0.0-M1+37-732f2dee.pom
... 
< HTTP/1.1 303 See Other
< Date: Tue, 16 Jun 2020 17:07:50 GMT
< Content-Length: 0
< Connection: keep-alive
< Set-Cookie: __cfduid=d81a5e9cf9b5b631535bc2982f3f56be81592327269; expires=Thu, 16-Jul-20 17:07:49 GMT; path=/; domain=.gradle.org; HttpOnly; SameSite=Lax; Secure
< Location: https://plugins-artifacts.gradle.org/com.lightbend.akka.grpc/akka-grpc-gradle-plugin/1.0.0-M1%2B37-732f2dee/15059b4dd56e2ae9c8bcc9ad09d757020d20e1849a4442cb81b23dfc564fdd13/akka-grpc-gradle-plugin-1.0.0-M1%2B37-732f2dee.pom
< Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
< X-Frame-Options: DENY
...
```

The new URL is properly escaped (at least on the output produced by `curl` above). 

When running even a simple `./gradlew clean` on a project with:

```
plugins {
  id "com.lightbend.akka.grpc.gradle" version "1.0.0-M1+37-732f2dee"
}
```

the operation fails:

```
❯ ./gradlew clean

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'akka-grpc-quickstart-scala'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.lightbend.akka.grpc:akka-grpc-gradle-plugin:1.0.0-M1+37-732f2dee.
     Searched in the following locations:
       - file:/Users/ignasi/.m2/repository/com/lightbend/akka/grpc/akka-grpc-gradle-plugin/1.0.0-M1+37-732f2dee/akka-grpc-gradle-plugin-1.0.0-M1+37-732f2dee.pom
       - https://plugins.gradle.org/m2/com/lightbend/akka/grpc/akka-grpc-gradle-plugin/1.0.0-M1+37-732f2dee/akka-grpc-gradle-plugin-1.0.0-M1+37-732f2dee.pom
     Required by:
         project : > com.lightbend.akka.grpc.gradle:com.lightbend.akka.grpc.gradle.gradle.plugin:1.0.0-M1+37-732f2dee

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
```

Running with debug seems to provide more information about the cause:

<details>
<summary>`Resource missing. [HTTP HEAD: https://plugins-artifacts.gradle.org/com.lightbend.akka.grpc/akka-grpc-gradle-plugin/1.0.0-M1+37-732f2dee/15059b4dd56e2ae9c8bcc9ad09d757020d20e1849a4442cb81b23dfc564fdd13/akka-grpc-gradle-plugin-1.0.0-M1+37-732f2dee.pom]`</summary>

```
2020-06-16T18:56:44.216+0200 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection [id: 95][route: {s}->https://plugins-artifacts.gradle.org:443] can be kept alive indefinitely
2020-06-16T18:56:44.216+0200 [DEBUG] [org.apache.http.impl.conn.DefaultManagedHttpClientConnection] http-outgoing-95: set socket timeout to 0
2020-06-16T18:56:44.216+0200 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection released: [id: 95][route: {s}->https://plugins-artifacts.gradle.org:443][total kept alive: 2; route allocated: 1 of 20; total allocated: 2 of 20]
2020-06-16T18:56:44.216+0200 [INFO] [org.gradle.internal.resource.transport.http.HttpClientHelper] Resource missing. [HTTP HEAD: https://plugins-artifacts.gradle.org/com.lightbend.akka.grpc/akka-grpc-gradle-plugin/1.0.0-M1+37-732f2dee/15059b4dd56e2ae9c8bcc9ad09d757020d20e1849a4442cb81b23dfc564fdd13/akka-grpc-gradle-plugin-1.0.0-M1+37-732f2dee.pom]
2020-06-16T18:56:44.216+0200 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Metadata of https://plugins.gradle.org/m2/com/lightbend/akka/grpc/akka-grpc-gradle-plugin/1.0.0-M1+37-732f2dee/akka-grpc-gradle-plugin-1.0.0-M1+37-732f2dee.pom'
2020-06-16T18:56:44.216+0200 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Metadata of https://plugins.gradle.org/m2/com/lightbend/akka/grpc/akka-grpc-gradle-plugin/1.0.0-M1+37-732f2dee/akka-grpc-gradle-plugin-1.0.0-M1+37-732f2dee.pom' completed
2020-06-16T18:56:44.216+0200 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver] No meta-data file or artifact found for module 'com.lightbend.akka.grpc:akka-grpc-gradle-plugin:1.0.0-M1+37-732f2dee' in repository 'Gradle Central Plugin Repository'.
2020-06-16T18:56:44.216+0200 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.modulecache.PersistentModuleMetadataCache] Recording absence of module descriptor in cache: com.lightbend.akka.grpc:akka-grpc-gradle-plugin:1.0.0-M1+37-732f2dee [changing = false]
2020-06-16T18:56:44.217+0200 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.oldresult.TransientConfigurationResultsBuilder] Flushing resolved configuration data in Binary store in /private/var/folders/n7/tvkd2b5j6sgd0x5w63j14ld40000gn/T/gradle3151587546369520193.bin. Wrote root 2.
2020-06-16T18:56:44.217+0200 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Resolve dependencies of :classpath'
2020-06-16T18:56:44.217+0200 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Resolve dependencies of :classpath' completed
```

</details>

### Expected Behavior

The internal client can follow `30x` redirects.

### Steps to Reproduce 

Create a blank project and add the plugin:

```
plugins {
  id "com.lightbend.akka.grpc.gradle" version "1.0.0-M1+37-732f2dee"
}
```

(edit: using `id "com.lightbend.akka.grpc.gradle" version "1.0.0-M1"` the download completes as expected)

**Comment by ignasi35** [comment] 2020-06-17 07:54
UPDATE: this has a low impact on our publishing of snapshots as we're already [removing the `+` character from the version string](https://github.com/akka/akka-grpc/pull/1019).

**Comment by octylFractal** [comment] 2021-11-11 04:49
Duplicate of #12873

**Closed by octylFractal** 2021-11-11 04:49 UTC
Labels: a:bug, closed:duplicate, in:dependency-resolution
