### ISSUE TITLE
buildSrc code instrumentation breaks code signing

### ISSUE THREAD

**Issue by stovocor** [gradle/gradle#14130] opened 2020-08-13 13:09 UTC
### Expected Behavior
For any libraries specified in the buildSrc project, the code signing information (`Class.getSigners()`) should be left intact.

### Current Behavior
With Gradle 6.5, code signing information is erased.

### Context
Our Gradle tasks create a connection to a third-party system, so those libraries are added to the buildSrc project. Upon creating the connection, those classes check if their code signature is still valid. This worked perfectly with Gradle 6.4.1, but with 6.5 and later the code signing information is gone.

This might be related to #13874

**Comment by glward** [comment] 2020-09-24 14:17
This also completely breaks the ability to use libraries which do self-verification as plugin dependencies (in our case, the BouncyCastle FIPS library).

Until this is fixed, is it possible to completely disable instrumentation? If not, we will be unable to upgrade our builds past 6.4.1.

**Comment by glward** [comment] 2020-09-25 13:18
I've uploaded a simple test project demonstrating an aspect of the problem: https://github.com/glward/gradle-bc-test 

`gradlew test` will show the test passing in 6.4.1 and 6.5.1 but failing in 6.6.1, since the JCE framework can no longer verify the signature of BouncyCastle.

**Comment by eskatos** [comment] 2020-10-15 12:31
Hi @glward,

Acknowledged that the build logic instrumentation discards the code signatures and this needs to be fixed.
I tried to use your repository but failed to reproduce the problem with it, tried several different JVMs:

https://scans.gradle.com/s/qdjhm74f3u4my/tests
https://scans.gradle.com/s/lt4gsctdfes7e/tests
https://scans.gradle.com/s/miidwq7hkucce/tests
https://scans.gradle.com/s/7qppi5diowci2/tests

Could you please share what JVM you used and if you added JCE policy files to it?

**Comment by glward** [comment] 2020-10-15 16:09
@eskatos We're using the Oracle Java 8 JDK as we still have a support contract for it. None of the JCE policy information has been changed

```
glward@ares:src/gradle-bc-test$ java -version
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode
```

I've run a build scan on the project showing the failure on my end:

https://scans.gradle.com/s/b7fylgc5y2brs/tests

**Comment by stovocor** [comment] 2020-10-16 11:24
The test project shows no error for OpenJDK 11.0.8.

I am not convinced that we are talking about the same bug here. Our tasks stopped working with Gradle 6.5 and later, but @glward  mentioned that 6.5.1 still works for him.

**Comment by glward** [comment] 2020-10-16 14:22
I'm happy to split mine out into a separate bug -- I suspect they are different, but have the same root cause. I'm also curious if my specific bug is only present on the Oracle JVM as they may be the only vendor enforcing signature checks on this particular use of a JCE provider. 

I did have another case that failed in 6.5.1 and 6.6.1, but I don't know that I can provide that as it depends on the bc-fips library, which is not generally available without a paid support contract as far as I'm aware -- it does the same sort of self-verification as the original issue reported, relying on a special signature file in META-INF. I'm happy to provide a similar minimal example if the Gradle team has access to bc-fips, though.

**Comment by eskatos** [comment] 2020-10-16 15:59
Thanks for the details @glward, @stovocor.

Could you both give `6.8-branch-eskatos_cc_instrument_skip_signed_jars-20201016154557+0000` a try?
It isn't a proper fix but more a prototype of a strategy.

Part of it is to detect that a jar is signed. @glward, could you share a listing of the content of `META-INF/` in the fips jar?

**Comment by glward** [comment] 2020-10-19 10:46
@eskatos Sure:

```
glward@ares:1.0.2/4fb5db5f03d00f6a94e43b78d097978190e4abb2$ unzip -l bc-fips-1.0.2.jar| grep META-INF 
   406383  2019-04-25 10:06   META-INF/MANIFEST.MF
   398318  2019-04-25 10:06   META-INF/BC1024KE.SF
     2230  2019-04-25 10:06   META-INF/BC1024KE.DSA
   398318  2019-04-25 10:06   META-INF/BC2048KE.SF
     6525  2019-04-25 10:06   META-INF/BC2048KE.DSA
        0  2019-04-25 10:06   META-INF/
       65  2019-04-25 10:06   META-INF/HMAC.SHA256
        0  2019-04-25 10:06   META-INF/services/
       58  2019-04-25 10:04   META-INF/services/java.security.Provider
        0  2019-04-25 10:06   META-INF/versions/9/
     3807  2019-04-25 10:06   META-INF/versions/9/module-info.class
```

I can give the branch a try as well but it might be a few days before I have time.

**Comment by stovocor** [comment] 2020-10-20 11:17
The branch version works perfectly for me, the signature validation error is gone.

**Comment by glward** [comment] 2020-10-20 13:29
Yep, the branch version solves our problems with BouncyCastle as well. I have not tried it with bc-fips -- we've found that we can just use the normal BC jars to accomplish what we need in our Gradle plugins, so I'm not particularly worried about bc-fips support tbh.

**Comment by eskatos** [comment] 2020-10-20 13:50
Thank you both!

The listing above confirms that the strategy in the branch would also work with the FIPS jar.

**Comment by eskatos** [comment] 2020-10-29 16:19
Fixed in https://github.com/gradle/gradle/pull/14940.
This will be in 6.8

**Closed by eskatos** 2020-10-29 16:19 UTC
Labels: @configuration-cache, a:bug, from:contributor
