### ISSUE TITLE
Fallback to first open superclass when generating Kotlin DSL typesafe accessors

### ISSUE THREAD

**Issue by efemoney** [gradle/gradle#9258] opened 2019-01-21 06:56 UTC
The `compileKotlin` task is not accessible in a type safe manner and requires explicitly importing the `KotlinCompile` task and defining the task using a *less pleasant* syntax.

### Expected Behavior

For instance developers should be able to use the generated `compileKotlin` task accessor in the following *build.gradle.kts* just like other accessors but this is not the case.
```kotlin
plugins {
  kotlin("jvm")
}

tasks {
  compileKotlin { 
    dependsOn(...) // error, task type is **Any**
  }
}
```
### Current Behavior

The generated javadoc for the task accessor above notes that 

> compileKotlin is not accessible in a type safe way because: org.jetbrains.kotlin.gradle.tasks.KotlinCompileWithWorkers is not public

forcing developers to instead use one of the syntax below which is slightly less pleasant

```kotlin
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
  kotlin("jvm")
}

tasks {
  val compileKotlin by existing(KotlinCompile::class) {
    dependsOn(...)
  }
  // OR
  named<KotlinCompile>("compileKotlin") { 
    dependsOn(...)
  }
}
```
Looking at the kotlin gradle plugin source, `KotlinCompileWithWorkers` is indeed *internal* but its immediate superclass, `KotlinCompile`, is open and feels like a better candidate for the task type than `Any`.

Is it possible to fallback to using the first open superclass when generating accessors?

### Your Environment

Gradle 5.1-rc-3

Build time:   2018-12-21 23:03:45 UTC
Revision:     bf267654ac894c160b5b6c5e5c06d72f1ecaa23c

Kotlin DSL:   1.1.0
Kotlin:       1.3.11
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_172 (Oracle Corporation 25.172-b11)
OS:           Mac OS X 10.14.3 x86_64

Android Studio 3.5 Canary 1
Build #AI-183.4886.37.35.5215047, built on January 8, 2019
JRE: 1.8.0_152-release-1248-b22 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3

Kotlin Plugin 1.3.20-eap-100-Studio3.4-1

**Comment by gildor** [comment] 2019-05-17 07:35
Looks that I reported duplicate of this issue:
https://github.com/gradle/gradle/issues/9420

> The compileKotlin task type is now correctly exposed
@eskator It exposed correctly only if you do not use new worker-based tasks API of Kotlin Gradle plugin, you can see issue #9420 I add some detail about this, to reproduce you should enable option `kotlin.parallel.tasks.in.project` which soon will be enabled by default and it will break all usages of type-safe accessors for `compileKotlin` and `compileTestKotlin` tasks

**Comment by eskatos** [comment] 2019-07-17 08:55
@gildor, you're right!

Closing this one as a duplicate of https://github.com/gradle/gradle/issues/9420

**Closed by eskatos** 2019-07-17 08:55 UTC
Labels: a:feature, from:contributor, in:kotlin-dsl
