### ISSUE TITLE
jacoco-report-aggregation does not agregate reports when using jvm-test-suits integration test module

### ISSUE THREAD

**Issue by Marek00Malik** [gradle/gradle#31114] opened 2024-11-02 21:24 UTC
### Current Behavior

I have a project with multi-modules using the `jvm-test-suite` plugin for testing purposes (integration tests module). 
Tests are executed correctly, and I see all the tests in the reports folder. 

I'm using Jacoco `jacoco-report-aggregation` to join my reports from multiple modules. 
The problem is that reports show only 'test' source. 

Below is my `gradle.build.kts` file: 
```
plugins {
    java
    idea
    jacoco
    `jvm-test-suite`
    `jacoco-report-aggregation`
    id("org.springframework.boot") version "3.3.3"
    id("io.spring.dependency-management") version "1.1.6"
}

group = "pl.codehouse.restaurant"
version = "0.0.1-SNAPSHOT"
val junitVersion = "5.10.2"
val junitPlatformVersion = "1.10.2"
val cucumberVersion = "7.15.0"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

idea {
    module {
        testSources.from(file("src/integrationTest/java"), file("src/test/java"))
        testResources.from(file("src/integrationTest/resources"), file("src/test/resources"))
    }
}

dependencies {
    runtimeOnly("org.postgresql:postgresql")
    runtimeOnly("org.postgresql:r2dbc-postgresql")

    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-data-r2dbc")
    implementation("org.springframework.boot:spring-boot-starter-validation")
    implementation("org.springframework.boot:spring-boot-starter-webflux")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")

    implementation("org.flywaydb:flyway-core")
    implementation("org.flywaydb:flyway-database-postgresql")

    implementation("org.springframework.kafka:spring-kafka")
    developmentOnly("org.springframework.boot:spring-boot-devtools")

    implementation("org.apache.commons:commons-lang3:3.14.0")

    annotationProcessor("org.springframework.boot:spring-boot-configuration-processor")
}

testing {
    suites {
        withType<JvmTestSuite> {
            useJUnitJupiter(junitVersion)
            dependencies {
                implementation("io.projectreactor:reactor-test")

                implementation("org.springframework.boot:spring-boot-starter-test") {
                    exclude(group = "org.junit.vintage", module = "junit-vintage-engine")
                }
                implementation("org.springframework.boot:spring-boot-starter-webflux")
                implementation("org.springframework.boot:spring-boot-starter-data-jpa")
                implementation("org.springframework.boot:spring-boot-starter-data-r2dbc")
                implementation("org.springframework.kafka:spring-kafka-test")

                implementation("org.junit.jupiter:junit-jupiter:$junitVersion")
                implementation("org.junit.platform:junit-platform-suite:$junitPlatformVersion")
                implementation("org.junit.platform:junit-platform-launcher:$junitPlatformVersion")

                implementation("io.cucumber:cucumber-java:$cucumberVersion")
                implementation("io.cucumber:cucumber-junit:$cucumberVersion")
                implementation("io.cucumber:cucumber-spring:$cucumberVersion")
                implementation("io.cucumber:cucumber-junit-platform-engine:$cucumberVersion")

                runtimeOnly("org.junit.platform:junit-platform-launcher:$junitPlatformVersion")
            }
        }

        val integrationTest by registering(JvmTestSuite::class) {
            testType.set(TestSuiteType.INTEGRATION_TEST)
            sources {
                java {
                    setSrcDirs(listOf("src/integrationTest/java"))
                }
                resources {
                    setSrcDirs(listOf("src/integrationTest/resources", "src/test/resources"))
                }
            }
            dependencies {
                implementation(project())
                implementation(sourceSets.test.get().output)
                implementation(sourceSets.test.get().runtimeClasspath)
                implementation(project.dependencies.platform("org.springframework.boot:spring-boot-dependencies:3.2.3"))

                implementation("org.flywaydb:flyway-core")
                implementation("org.flywaydb:flyway-database-postgresql")

                implementation("org.springframework.boot:spring-boot-testcontainers")

                implementation("org.testcontainers:junit-jupiter")
                implementation("org.testcontainers:kafka")
                implementation("org.testcontainers:postgresql")
                implementation("org.testcontainers:r2dbc")

                implementation("io.rest-assured:rest-assured:5.4.0")
                implementation("io.rest-assured:json-path:5.4.0")
                implementation("io.rest-assured:json-schema-validator:5.4.0")
                implementation("io.rest-assured:spring-web-test-client:5.4.0")
            }
        }
    }
}

tasks.withType<Test> {
    useJUnitPlatform()
    systemProperty("cucumber.junit-platform.naming-strategy", "long")
    finalizedBy(tasks.jacocoTestReport)

    testLogging {
        events("passed", "skipped", "failed")
    }
}

tasks.named<Test>("integrationTest") {
    useJUnitPlatform()
    systemProperty("cucumber.junit-platform.naming-strategy", "long")
    finalizedBy(tasks.jacocoTestReport)
}

tasks.jacocoTestReport {
    reports {
        xml.required = true
        csv.required = true
        html.outputLocation = layout.buildDirectory.dir("jacocoHtml")
    }
}

tasks.withType<Test>().configureEach {
    maxParallelForks = (Runtime.getRuntime().availableProcessors() / 2).takeIf { it > 0 } ?: 1
    setForkEvery(100)
    reports.html.required.set(true)
}

```

As it is the reports folder: 
![Image](https://github.com/user-attachments/assets/14687d37-f566-4903-a745-1d6d0903a20b)

What should I do to make this report work ?

### Expected Behavior

I would like to have the Jacoco reports contain all testing modules. 

### Self-contained Reproducer Project

https://github.com/C0deH0use/restaurant-requests

### Gradle version

8.10.2

**Comment by ov7a** [comment] 2024-11-05 13:47
This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/30445

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

Related:
* https://github.com/gradle/gradle/issues/23223
* https://github.com/gradle/gradle/issues/30445

**Closed by ov7a** 2024-11-05 13:47 UTC
Labels: a:bug, to-triage
