### ISSUE TITLE
A corrupted repository sends the Gradle resolver in infinite loop

### ISSUE THREAD

**Issue by ddimtirov** [gradle/gradle#4043] opened 2018-01-16 01:46 UTC
### Expected Behavior
When a POM does not match its repo location, Gradle should fail the resolution with clean error message, ideally outputting a snippet showing how to use manual metadata (client module) to paper over the faulty repository.

### Current Behavior
Gradle falls in endless recursion until it exhausts the memory and then prints a huge trace of "Ivy resolver failed to initialize" errors. There is no clear indication what triggered the error.

### Context
We used Artifactory to deploy a vendor-provided uberjar that contained the pom for `commons-math`. 

Although we entered the correct metadata in the Artifactory dialog, it ended up using the pom from the jar (following up with JFrog support for that).

When a developer tried to use the jar, their Gradle build froze for a minute and then spilled its guts. They had no idea where to start from investigating.

### Steps to Reproduce (for bugs)
This is what actually happened:
1. Download [Jide demo](http://www.jidesoft.com/products/1.4/jide_demo.zip)
2. Get Artifactory 4.15.0
3. Deploy the jar at coordinates `com.jidesoft:jide_demo:20180116`
4. Create a simple Gradle project with the Artifactory the Java plugins and add the uploaded jar as compile dependency

Alternatively:

1. In a test repository, replace the pom of an existing artifact with the pom of different artifact  (i.e. overwrite the `commons-logging` POM with `commons-math`)
2. Try to use the corrupted artifact

### Your Environment
Gradle 4.2, Artifactory 4.15.0, Artifactory Plugin for Gradle 4.4.17

**Comment by bigdaz** [comment] 2018-01-16 23:37
Thanks for reporting @ddimtirov. Unfortunately,  I can't reproduce this failure using the second set of instructions you provided. Here's my attempt: https://github.com/bigdaz/gradle-4043

When I execute `gradle -g home resolve`, the build works fine.

Can you please confirm that you can see this failure using a simple file repository?

**Comment by jjohannes** [comment] 2018-03-01 21:10
Closing this until we have a reproducible example.

**Closed by jjohannes** 2018-03-01 21:10 UTC
Labels: a:bug, from:contributor, in:dependency-management
