### ISSUE TITLE
Couldn't move cache entry into local cache due to AccessDeniedException when many identical input files exist

### ISSUE THREAD

**Issue by lukasgraef** [gradle/gradle#31257] opened 2024-11-12 13:54 UTC
### Current Behavior

In a big Multi-Project Build that has build caching enabled, when re-running certain tasks (i.e. running with `--rerun-tasks`), the following Exception occurs:

```> Failed to store cache entry 81741d9bffc40e4a3d0284190b101737 for task ':project20:collision': Couldn't move cache entry '81741d9bffc40e4a3d0284190b101737' into local cache: java.nio.file.AccessDeniedException: D:\dev\.gradle\caches\build-cache-1\81741d9bffc40e4a3d0284190b101737-9494561490260573834.part -> D:\dev\.gradle\caches\build-cache-1\81741d9bffc40e4a3d0284190b101737```

This happens with tasks which reference a subproject's `about.html` file (marked as `@InputFile` with `PathSensitivity.NONE`), which is duplicated across many subprojects. Having many of these tasks, that each have identical input files, seems to create some sort of collision when writing to the local build cache.

I was able to reproduce this issue for Gradle 8.8 to Gradle 8.11.
On Gradle 8.7, this AccessDeniedException doesn't occur and the build cache entry can be stored.

 

### Expected Behavior

The exception doesn't occur and the build cache entry can be stored.

### Context (optional)

Our workaround (and probably the right setting for this task) was to annotate the problematic task with `@DisableCachingByDefault`.

### Self-contained Reproducer Project

For a reproducer project, see: https://github.com/lukasgraef/build-cache-collision-reproducer

Run `gradlew collision` and then `gradlew collision --rerun-tasks` to reproduce.

### Gradle version

8.11

### Gradle version that used to work

8.7

### Your Environment (optional)

Windows 11
Amazon Corretto OpenJDK 21

**Comment by ov7a** [comment] 2024-11-12 14:59
Sorry, I wasn't able to reproduce your issue on Windows or MacOS.

Can you make sure that there are no external entities (e.g., anti-virus software) in play? Can you check if it's reproducible in a different environment, please (GitHub action could be a good candidate; see an example [here](https://github.com/gradle/gradle-issue-reproducer)).

**Comment by lukasgraef** [comment] 2024-11-13 09:05
Hi, I tried to reproduce this issue using the gradle/gradle-issue-reproducer project (see [build-cache-collision](https://github.com/lukasgraef/build-cache-collision)), but also had no luck.

It seems that you're right regarding the external entities, because I've shared the reproducer with some of my colleagues and they all could reproduce the issue. So it's most likely caused by our setup.

However, there's one thing that still makes me sceptical whether this is entirely a problem of our setup: When switching back to Gradle 8.7, neither me nor my colleagues could reproduce this problem anymore. The problems for us only started with Gradle 8.8.

**Comment by ov7a** [comment] 2024-11-13 11:02
I think the most relevant change was introduced in this PR:

* https://github.com/gradle/gradle/pull/28535

The solution would be to update the configuration of the security software.

Given the above, I'm closing this issue. 

I understand that this might be frustrating for some users to have broken builds because of AV software, but I don't think there's something we can do on the Gradle side if something prevents Gradle from moving/creating files. Caching is an internal detail and may change. FTR, we had similar issues related to security software in the past.

Related:
* https://github.com/gradle/gradle/issues/28948

**Closed by ov7a** 2024-11-13 11:02 UTC
Labels: a:regression, to-triage
