### ISSUE TITLE
Deprecated warning about non-existing project directory even when explicitly setting dir

### ISSUE THREAD

**Issue by arlampin** [gradle/gradle#27239] opened 2023-12-01 12:54 UTC
### Current Behavior

Using something like this in `settings.gradle`

```
include('myorg:app')
project(':myorg:app').projectDir = file('app')
```

Prints deprecation warning
    
> Configuring project ':myorg' without an existing directory is deprecated. The configured projectDirectory '/foo/bar/baz/myorg' does not exist, can't be written to or is not a directory.

The directory `app` exists and everything otherwise works correctly. Removing `myorg` from project name also causes the warning to disappear.

### Expected Behavior

There shouldn't be a warning if directory is manually configured.

Or so I assume. Or is there something in multi-part project name that would require intermediate directories to exists?

### Steps to Reproduce

Create new multi-project application project with `gradle init`, edit `settings.gradle` to above.

### Gradle version

8.5

**Comment by ov7a** [comment] 2023-12-21 12:46
Closing this as unreproducible since there is no feedback.

**Closed as not planned by ov7a** 2023-12-21 12:46 UTC
Labels: closed:unreproducible
