### ISSUE TITLE
ArtifactNotFound causing build to fail if classifier is missing from repo

### ISSUE THREAD

**Issue by ThadHouse** [gradle/gradle#12748] opened 2020-04-07 20:08 UTC
We use classifiers to differentiate between platforms in an artifact. As a result of publishing the way we do, we have these classifiers split across different repositories. So 1 repo will have Windows, another Linux Arm, etc. During development, this worked, because we did pretty much everything on windows. However we noticed that as we started trying to work on Linux platforms, builds would just unconditionally fail. By our best guess, it seems like Gradle just dies if it sees that a repo has some classifiers but not others. This is not good in this case, and it should act exactly like if the artifact isn't found. Can reproduce on Gradle 6.2 and Gradle 6.

**Comment by ljacomet** [comment] 2020-04-08 07:21
Can you explain "it seems like Gradle just dies"? Maybe by sharing a stacktrace.

Note that it is 100% expected to fail in the scenario you explained. Once a module `<group>:<artifact>:<version>` is found in _one_ repository, _all_ its files are fetched from that same repository.
Gradle does not support publications that are spread across repositories _for downloading files_, it only works for searching versions.

**Comment by ThadHouse** [comment] 2020-04-08 07:27
By just dies I meant an ArtifactNotFound exception. Which an artifact isn't expected to be found, and I know its not expected to be found. It won't be there at all. 

Thats really bad behavior, and definitely a bug. Classifiers are extremely useful for separating artifacts in the native world, and each repo might not have every artifact. 

For a more concrete example, we build a 32 bit version of JavaFX. I had forgotten to open an issue at the time, but we had to completely change the group of that 32 bit build, because it would error if we tried to put it in the same group as upstream JavaFX, since they don't publish 32 bit builds.

**Comment by ljacomet** [comment] 2020-04-08 07:32
I understand the behavior does not help your use case, but Gradle considers this a feature and not a bug, mostly for reproducibility.

Maybe you could fix the situation by leveraging [repository content filtering](https://docs.gradle.org/6.3/userguide/declaring_repositories.html#sec:repository-content-filtering), in particular because you could filter based on attributes.

Another option would be to consolidate your repositories behind a single proxy.

**Comment by ThadHouse** [comment] 2020-04-08 07:36
How can you filter based on attributes? The docs show nothing about doing that.

I do think Gradle could be made much better by allowing reproducibility to be a configurable option, rather then forced. We've ran into countless issues all in the name of "reproducibility ", which our use case honestly doesn't care about at all, and needs to Just Work.

**Comment by ThadHouse** [comment] 2020-04-08 07:48
We could make the proxy work easily enough, but our build and release setup also has a local offline cache of artifacts, because offline builds are extremely important to our users. This offline cache doesn't contain all the classifiers available, as that would about 6x times the download size, and would only be used for platforms like the Raspberry Pi if cross compilations were needed. We can't use gradles caching because it deletes artifacts, which is unacceptable to our users. We list this first, as we want the offline cache to be used if possible, but this isn't guaranteed to contain all the classifiers. We've ran into this as well with mavenLocal during development, and even though I understand the behavior for actual remotes if reproducibility does matter, local repos shouldn't be expected to always contain all classifiers.

**Comment by ljacomet** [comment] 2020-04-08 10:08
For the filtering, have a look at the [javadoc of `RepositoryContentDescriptor`](https://docs.gradle.org/6.3/javadoc/org/gradle/api/artifacts/repositories/RepositoryContentDescriptor.html#onlyForAttribute-org.gradle.api.attributes.Attribute-T...-)

I'll go over the documentation once more, it should be referenced from there at least.

**Comment by ljacomet** [comment] 2020-11-17 17:41
Clarification has been added to the documentation.

Closing as there is no plan to change the way Gradle locates artifact in a repository.

**Closed by ljacomet** 2020-11-17 17:41 UTC
Labels: @jvm, a:bug, from:contributor, in:dependency-management
