### ISSUE TITLE
nested buildSrc and included buildSrc builds build paths don't respect the buildSrc root project name

### ISSUE THREAD

**Issue by facewindu** [gradle/gradle#5333] opened 2018-05-09 12:17 UTC
I expect the build path of buildSrc builds in which the root project name was changed to be updated accordingly.

### Expected Behavior
build path should respect root project name for all buildSrc builds.

### Current Behavior
build path seems hard-coded and to not respect the root project name.

### Context
N/A

### Steps to Reproduce (for bugs)
See [composite-with-buildSrc-builds.zip](https://github.com/gradle/gradle/files/1987714/composite-with-buildSrc-builds.zip)
It's a build with
- a buildSrc renamed 'rootBuildSrc', with a nested buildSrc named 'nested'
- an included build named 'included', with a buildSrc renamed 'includedBuildSrc', with a nested buildSrc named 'nested'

Output is
```
./gradlew build --console=plain
> Task :buildSrc:buildSrc:compileJava NO-SOURCE
> Task :buildSrc:buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:buildSrc:processResources NO-SOURCE
> Task :buildSrc:buildSrc:classes UP-TO-DATE
> Task :buildSrc:buildSrc:jar UP-TO-DATE
> Task :buildSrc:buildSrc:assemble UP-TO-DATE
> Task :buildSrc:buildSrc:compileTestJava NO-SOURCE
> Task :buildSrc:buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:buildSrc:test NO-SOURCE
> Task :buildSrc:buildSrc:check UP-TO-DATE
> Task :buildSrc:buildSrc:build UP-TO-DATE
> Task :rootBuildSrc:compileJava NO-SOURCE
> Task :rootBuildSrc:compileGroovy NO-SOURCE
> Task :rootBuildSrc:processResources NO-SOURCE
> Task :rootBuildSrc:classes UP-TO-DATE
> Task :rootBuildSrc:jar UP-TO-DATE
> Task :rootBuildSrc:assemble UP-TO-DATE
> Task :rootBuildSrc:compileTestJava NO-SOURCE
> Task :rootBuildSrc:compileTestGroovy NO-SOURCE
> Task :rootBuildSrc:processTestResources NO-SOURCE
> Task :rootBuildSrc:testClasses UP-TO-DATE
> Task :rootBuildSrc:test NO-SOURCE
> Task :rootBuildSrc:check UP-TO-DATE
> Task :rootBuildSrc:build UP-TO-DATE
> Task :included-build:buildSrc:nested:compileJava NO-SOURCE
> Task :included-build:buildSrc:nested:compileGroovy NO-SOURCE
> Task :included-build:buildSrc:nested:processResources NO-SOURCE
> Task :included-build:buildSrc:nested:classes UP-TO-DATE
> Task :included-build:buildSrc:nested:jar
> Task :included-build:buildSrc:nested:assemble
> Task :included-build:buildSrc:nested:compileTestJava NO-SOURCE
> Task :included-build:buildSrc:nested:compileTestGroovy NO-SOURCE
> Task :included-build:buildSrc:nested:processTestResources NO-SOURCE
> Task :included-build:buildSrc:nested:testClasses UP-TO-DATE
> Task :included-build:buildSrc:nested:test NO-SOURCE
> Task :included-build:buildSrc:nested:check UP-TO-DATE
> Task :included-build:buildSrc:nested:build
> Task :included-build:buildSrc:compileJava NO-SOURCE
> Task :included-build:buildSrc:compileGroovy NO-SOURCE
> Task :included-build:buildSrc:processResources NO-SOURCE
> Task :included-build:buildSrc:classes UP-TO-DATE
> Task :included-build:buildSrc:jar
> Task :included-build:buildSrc:assemble
> Task :included-build:buildSrc:compileTestJava NO-SOURCE
> Task :included-build:buildSrc:compileTestGroovy NO-SOURCE
> Task :included-build:buildSrc:processTestResources NO-SOURCE
> Task :included-build:buildSrc:testClasses UP-TO-DATE
> Task :included-build:buildSrc:test NO-SOURCE
> Task :included-build:buildSrc:check UP-TO-DATE
> Task :included-build:buildSrc:build
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :jar
> Task :assemble
> Task :compileTestJava NO-SOURCE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :test NO-SOURCE
> Task :check UP-TO-DATE
> Task :build
```

Execute `./gradlew build --console=plain`

The console output contains tasks like
- `:rootBuildSrc:compileJava`: OK
- `:buildSrc:buildSrc:compileJava`: NOK. I would have expected `:rootBuildSrc:nested:compileJava`
- `:included:buildSrc:compileJava`: NOK. I would have expected `:includedBuildSrc:compileJava`
- `:included:buildSrc:nested:compileJava`: NOK. I would have expected `:includedBuildSrc:nested:compileJava`

### Your Environment
No build scan yet, as I'm working on providing build scan support for buildSrc builds.

**Comment by ldaley** [comment] 2018-05-10 02:08
The root cause here is that the `buildSrc` of a project must be built before evaluating that `settings.gradle` for that project, and therefore before the root project name can be known. This is so that the logic from `buildSrc` can be used in the `settings.gradle` file. This is not the first time this has caused problems.

It's hard to see how this can be fixed without changing that fundamental aspect.

**Comment by tomdcc** [comment] 2020-01-10 05:57
The behaviour has deliberately changed here - it will always use the included build dir name and not the project name, so that we have a consistent build path, even if that path does not match the included build root project name.

**Closed by tomdcc** 2020-01-10 05:57 UTC
Labels: from:member, in:composite-builds
