### ISSUE TITLE
Gradle Kotlin JPMS issues - Unnamed module reads package from both ... and

### ISSUE THREAD

**Issue by NicklasWallgren** [gradle/gradle#27526] opened 2023-12-27 11:54 UTC
### Current Behavior

Error while compiling library with JPMS support using Gradle and Kotlin DSL.

It works fine if I temporary remove the "module-info.java" file.

Link to sample
https://github.com/NicklasWallgren/bankid-java-sdk/tree/gradle-compilation-errors

Actual error
```
error: the unnamed module reads package org.codehaus.groovy.runtime from both org.codehaus.groovy and org.codehaus.groovy.test
error: the unnamed module reads package groovy.util from both org.codehaus.groovy and org.codehaus.groovy.test
error: the unnamed module reads package groovy.transform from both org.codehaus.groovy and org.codehaus.groovy.test
error: the unnamed module reads package groovy.lang from both org.codehaus.groovy and org.codehaus.groovy.test
error: the unnamed module reads package org.apache.groovy.antlr from both org.codehaus.groovy and org.codehaus.groovy.groovydoc
error: the unnamed module reads package groovy.ui from both org.codehaus.groovy and org.codehaus.groovy.console
error: the unnamed module reads package groovy.inspect from both org.codehaus.groovy and org.codehaus.groovy.console
error: the unnamed module reads package org.codehaus.groovy.runtime from both org.codehaus.groovy and org.codehaus.groovy.nio
error: the unnamed module reads package groovy.util from both org.codehaus.groovy and org.codehaus.groovy.ant
error: the unnamed module reads package org.codehaus.groovy.runtime from both org.codehaus.groovy and org.codehaus.groovy.xml
error: the unnamed module reads package groovy.xml from both org.codehaus.groovy and org.codehaus.groovy.xml
```

### Expected Behavior

Should compile successfully.

### Steps to Reproduce

1. Clone https://github.com/NicklasWallgren/bankid-java-sdk/tree/gradle-compilation-errors
2. Run ./gradlew compileJava

### Gradle version

8.5

**Comment by cobexer** [comment] 2024-01-08 09:56
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***
At first glance this doesn't look like a Gradle issue, but more like a JPMS/Groovy compatibility issue.

Please update the reproducer steps to point us at a specific problem with Gradle otherwise this issue will be closed in seven days.

**Comment by NicklasWallgren** [comment] 2024-02-10 13:27
@ov7a @cobexer 
> If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.

The sample/reproduceable that I provided above comes with a set of custom gradle plugins implemented using the kotlin-dsl. It seems as the compilation of those plugins takes the `module-info.java` from the `src/main/java` into account, which I think it shouldn't. 

The kotlin-dsl plugin should compile without regard to the `module-info.java` for the `dev.nicklasw.bankid`-module.

I do think this is a bug in gradle, please correct me if I'm wrong.

**Comment by ov7a** [comment] 2024-02-12 09:55
Looking at your [CI run](https://github.com/e-identification/bankid-java-sdk/actions/runs/7337988099/job/19979779290), the error is produced during the `:errorProne` and `:generateEffectiveLombokConfig`. Note also that `:quality:compileJava` has `NO-SOURCE` status. Can you verify that the issues you are experiencing are caused by the Gradle, not ErrorProne and Lombok? Can you provide a reproducer without them?

**Closed** 2024-02-19 10:01 UTC
Labels: a:bug, to-triage, pending:feedback, closed:missing-feedback
