### ISSUE TITLE
Checkstyle compile classpath not marked as compile classpath

### ISSUE THREAD

**Issue by scramados** [gradle/gradle#17096] opened 2021-05-06 07:32 UTC
The Checkstyle task classpath input is not marked as a compile classpath. This causes cache misses when one of the jars it depends on changes manifest data in a module it depends on.
This is inconsistent with the compile check. Meaning the checkstyle plugin will run even though Gradle does not recompile the source code of the module.

### Expected Behavior
The checkstyle task classpath up-to-date check is the same as for the java compile task.

### Current Behavior
The checkstyle task will stay up to date and cache if the classpath does not change according to the same standard as the java compile classpath.

### Context
I'm trying to cache the checkstyle task in our CI server. This is currently not possible because the manifest file contains the build number so every build has a change in the classpath that breaks the up-to-date check.

### Steps to Reproduce 
- Clone: https://github.com/scramados/checkstyle-up-to-date
- Run twice: `./gradlew checkstyleMain`
- The second time the upper-layer javaCompile and checkstyleMain task stay up to date
- Change the version in build.gradle.kts
- Run: `./gradlew checkstyleMain`
- The compile task will stay up to date but not the checkstyleMain task

### Your Environment
https://scans.gradle.com/s/7rwd4bxo6i3ek

**Comment by lptr** [comment] 2022-01-20 09:39
Let's reopen this. There is no reason why `Checkstyle.classpath` should be a runtime `@Classpath` instead of a `@CompileClasspath`. There are only a few Checkstyle rules that consume the binary class files like `JavadocMethod` (see https://stackoverflow.com/a/24495543/104894), but they only care about the API of the dependencies.

As for why it is this way now, I think it's because we've marked the property with `@Classpath` in Gradle 3.2, while `@CompileClasspath` was introduced in Gradle 3.4. https://github.com/gradle/gradle/commit/1809f380ffc582d63886c4d7a08305f807212271

**Comment by lptr** [comment] 2022-01-31 14:12
@vlsi's comment here makes sense: https://github.com/gradle/gradle/issues/14227#issuecomment-1017309945

This is actually a duplicate of that issue.

**Closed by lptr** 2022-01-31 14:12 UTC
Labels: in:checkstyle-plugin, @execution
