### ISSUE TITLE
UnsupportedOperationException when merging exclude rules

### ISSUE THREAD

**Issue by wang2nd** [gradle/gradle#1563] opened 2017-03-12 23:44 UTC
I suddenly had a dependency error as following. But the debug log and stacktrace didn't reveal what is this unresolved dependency. I might miss or misunderstand something here. An confirmation or hint from my log is highly appreciated.

FAILURE: Build failed with an exception.
17:24:46.077 [ERROR] [org.gradle.BuildExceptionReporter] 
17:24:46.077 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
17:24:46.077 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':subscription-repository:dependencies'.
17:24:46.077 [ERROR] [org.gradle.BuildExceptionReporter] > Could not resolve all dependencies for configuration ':subscription-repository:compile'.
17:24:46.078 [ERROR] [org.gradle.BuildExceptionReporter]    > java.lang.UnsupportedOperationException (no error message)
17:24:46.078 [ERROR] [org.gradle.BuildExceptionReporter] 
17:24:46.078 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
17:24:46.079 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':subscription-repository:dependencies'.

### Expected Behavior
I am expecting to see the log exactly which dependency is not resolved.

### Current Behavior
Only some missing warnings.

### Context
Teamcity build starts to fail due to this dependency issue

### Steps to Reproduce (for bugs)
I specified 2 internal repositories and MavenLocal
    repositories {
        mavenLocal()
        maven { url "http://{our internal repo server}/nexus/content/groups/public/"; }
        maven { url "http://{our internal repo server}/nexus/content/repositories/sre-releases"}
    }
I execute the following command to minimize the issue.
gradle :subscription-repository:dependencies --refresh-dependencies --info --debug --stacktrace > ee8

Here is the stacktrace, for the actual debug info, please see the attachment ee8.txt, where I could not nail down the root cause.
[ee8.txt](https://github.com/gradle/gradle/files/836995/ee8.txt)

17:24:46.076 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
17:24:46.077 [ERROR] [org.gradle.BuildExceptionReporter] 
17:24:46.077 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
17:24:46.077 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':subscription-repository:dependencies'.
17:24:46.077 [ERROR] [org.gradle.BuildExceptionReporter] > Could not resolve all dependencies for configuration ':subscription-repository:compile'.
17:24:46.078 [ERROR] [org.gradle.BuildExceptionReporter]    > java.lang.UnsupportedOperationException (no error message)
17:24:46.078 [ERROR] [org.gradle.BuildExceptionReporter] 
17:24:46.078 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
17:24:46.079 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':subscription-repository:dependencies'.
17:24:46.079 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
17:24:46.079 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
17:24:46.095 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
17:24:46.095 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
17:24:46.095 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
17:24:46.096 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
17:24:46.096 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
17:24:46.096 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
17:24:46.096 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
17:24:46.097 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:306)
17:24:46.097 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
17:24:46.097 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
17:24:46.097 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
17:24:46.097 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
17:24:46.098 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
17:24:46.098 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
17:24:46.098 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
17:24:46.098 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
17:24:46.099 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
17:24:46.099 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
17:24:46.099 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
17:24:46.099 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
17:24:46.099 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
17:24:46.100 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
17:24:46.100 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
17:24:46.100 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
17:24:46.100 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
17:24:46.100 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
17:24:46.101 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
17:24:46.101 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
17:24:46.101 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
17:24:46.101 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
17:24:46.101 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
17:24:46.102 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
17:24:46.123 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
17:24:46.124 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
17:24:46.124 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
17:24:46.124 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
17:24:46.124 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
17:24:46.124 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
17:24:46.124 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.Main.doAction(Main.java:33)
17:24:46.124 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
17:24:46.125 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
17:24:46.125 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
17:24:46.125 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
17:24:46.125 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':subscription-repository:compile'.
17:24:46.125 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingArtifactDependencyResolver.wrapException(ErrorHandlingArtifactDependencyResolver.java:61)
17:24:46.125 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingArtifactDependencyResolver.resolve(ErrorHandlingArtifactDependencyResolver.java:49)
17:24:46.126 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.DefaultConfigurationResolver.resolve(DefaultConfigurationResolver.java:46)
17:24:46.126 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveNow(DefaultConfiguration.java:250)
17:24:46.126 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$800(DefaultConfiguration.java:46)
17:24:46.126 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationResolvableDependencies.getResolutionResult(DefaultConfiguration.java:547)
17:24:46.126 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.tasks.diagnostics.internal.dependencies.AsciiDependencyReportRenderer.render(AsciiDependencyReportRenderer.java:82)
17:24:46.127 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.tasks.diagnostics.DependencyReportTask.generate(DependencyReportTask.java:58)
17:24:46.127 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.tasks.diagnostics.AbstractReportTask.generate(AbstractReportTask.java:80)
17:24:46.127 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
17:24:46.127 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
17:24:46.127 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
17:24:46.128 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
17:24:46.128 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
17:24:46.128 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
17:24:46.128 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
17:24:46.128 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
17:24:46.128 [ERROR] [org.gradle.BuildExceptionReporter]        ... 44 more
17:24:46.129 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.UnsupportedOperationException
17:24:46.129 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultModuleResolutionFilter$ExcludeRuleBackedSpec.intersect(DefaultModuleResolutionFilter.java:387)
17:24:46.154 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultModuleResolutionFilter$ExcludeRuleBackedSpec.doUnion(DefaultModuleResolutionFilter.java:358)
17:24:46.154 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultModuleResolutionFilter.union(DefaultModuleResolutionFilter.java:93)
17:24:46.155 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$ConfigurationNode.getSelector(DependencyGraphBuilder.java:767)
17:24:46.155 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$ConfigurationNode.visitOutgoingDependencies(DependencyGraphBuilder.java:713)
17:24:46.155 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.traverseGraph(DependencyGraphBuilder.java:109)
17:24:46.155 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.resolveDependencyGraph(DependencyGraphBuilder.java:90)
17:24:46.155 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.resolve(DependencyGraphBuilder.java:80)
17:24:46.155 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultDependencyResolver$1.execute(DefaultDependencyResolver.java:122)
17:24:46.156 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultDependencyResolver$1.execute(DefaultDependencyResolver.java:88)
17:24:46.156 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.Transformers$4.transform(Transformers.java:137)
17:24:46.156 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyContextManager.withIvy(DefaultIvyContextManager.java:61)
17:24:46.156 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyContextManager.withIvy(DefaultIvyContextManager.java:39)
17:24:46.156 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultDependencyResolver.resolve(DefaultDependencyResolver.java:88)
17:24:46.156 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.CacheLockingArtifactDependencyResolver$1.run(CacheLockingArtifactDependencyResolver.java:42)
17:24:46.156 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.Factories$1.create(Factories.java:22)
17:24:46.156 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:192)
17:24:46.156 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:175)
17:24:46.156 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.cache.internal.DefaultPersistentDirectoryStore.useCache(DefaultPersistentDirectoryStore.java:106)
17:24:46.157 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.useCache(DefaultCacheFactory.java:187)
17:24:46.183 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.DefaultCacheLockingManager.useCache(DefaultCacheLockingManager.java:64)
17:24:46.183 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.CacheLockingArtifactDependencyResolver.resolve(CacheLockingArtifactDependencyResolver.java:40)
17:24:46.183 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.SelfResolvingDependencyResolver.resolve(SelfResolvingDependencyResolver.java:45)
17:24:46.183 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.ShortcircuitEmptyConfigsArtifactDependencyResolver.resolve(ShortcircuitEmptyConfigsArtifactDependencyResolver.java:55)
17:24:46.183 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingArtifactDependencyResolver.resolve(ErrorHandlingArtifactDependencyResolver.java:47)
17:24:46.183 [ERROR] [org.gradle.BuildExceptionReporter]        ... 59 more
17:24:46.184 [ERROR] [org.gradle.BuildExceptionReporter] 

### Mac OS(Dev Machine) or Linux(Teamcity)

 * Build scan URL:

**Comment by wang2nd** [comment] 2017-03-12 23:58
Here is the log file with --info enabled only for a short reading.
[ee9_info_only.txt](https://github.com/gradle/gradle/files/837001/ee9_info_only.txt)


All the "Resource missing" files in one repo will be found in another repo we listed. So I didn't see any unresovled dependency

**Comment by bmuschko** [comment] 2017-03-15 16:13
If you run just the task `dependencies` without any other command line logging option you should see which dependency is failing. Maybe you can start from there. Why do you depend on `mavenLocal()`? Gradle uses its own cache.

**Comment by wang2nd** [comment] 2017-03-18 21:04
Thanks for the info. Will hv a try n report back. Based on testing, the
trouble is caused by one of our internal library published to our own
repository. It has nothing to do with Maven cache.

The weird thing is that the library published by Teamcity Linux build agent
is causing the trouble, while the one built n uploaded on my mac is
recognized without any issue. Will dig into more and report back.

Will see the difference between these two outputs, but the team city one
used to work.

**Comment by wang2nd** [comment] 2017-03-21 18:51
@bmuschko just fyi. no matter I execute "gradle :subscription-repository:dependencies" or "gradle clean :subscription-repository:dependencies --refresh-dependencies", the output is always the followings. As I mentioned above, we found our internal lib that published in our internal cache is the root cause of the trouble but have not figure out why. I have other high priority task on hand and have to hold this task a little bit. I will continue the investigation in one or two weeks and then report you back. Thanks for the help!

:subscription-repository:dependencies

------------------------------------------------------------
Project :subscription-repository
------------------------------------------------------------

archives - Configuration for archive artifacts.
No dependencies

checkstyle - The Checkstyle libraries to be used for this project.
\--- com.github.sevntu.checkstyle:sevntu-checks:1.7.0
     \--- com.puppycrawl.tools:checkstyle:5.6
          +--- antlr:antlr:2.7.7
          +--- commons-beanutils:commons-beanutils-core:1.8.3
          +--- commons-cli:commons-cli:1.2
          \--- com.google.collections:google-collections:1.0

compile - Compile classpath for source set 'main'.
:subscription-repository:dependencies FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':subscription-repository:dependencies'.
> Could not resolve all dependencies for configuration ':subscription-repository:compile'.
   > java.lang.UnsupportedOperationException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.315 secs

**Comment by oehme** [comment] 2017-09-06 12:28
> java.lang.UnsupportedOperationException (no error message)

That means there's a programming error in Gradle, not some unresolved dependency. The class mentioned in the error message doesn't exist anymore. Can you please check with Gradle 4.1 whether the problem still exists @wang2nd ?

**Comment by bigdaz** [comment] 2017-12-21 19:30
Hi @wang2nd. We've had a few reports of this issue, but we've never been able to reproduce it ourselves. We've tried to analyze the stacktrace, but it doesn't help us work out what's going wrong.

I'm going to close this issue as "could not reproduce". If the problem persists with the latest version of Gradle, please re-open this and we can work with you to try to reproduce.

**Closed by bigdaz** 2017-12-21 19:30 UTC
Labels: a:bug, from:contributor, in:dependency-management
