### ISSUE TITLE
Project::files should accept kotlin.jvm.functions.Function0<Any>

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/gradle#7637] opened 2018-11-06 04:48 UTC
When the Gradle Kotlin DSL was originally being developed the following code wasn't valid Kotlin because the Kotlin compiler couldn't infer the types.
```kotlin
files({ java.sourceSets["main"].allSource.srcDirs })
```
However, now in `1.3` the Kotlin compiler generates the correct types.

### Expected Behavior
`files` should accept the type `kotlin.jvm.functions.Function0<Any>`.

I am aware that `files` will accept a `Callable`, however, accepting `Function0<Any` will create parity with Groovy.
In the Groovy DSL you can just do the following:
```
files({ java.sourceSets.main.allSource.srcDirs })
```

### Current Behavior
Passing the above `kotlin.jvm.functions.Function0<Any>`  throws this exception:
```
Cannot convert the provided notation to a File or URI: () -> kotlin.collections.(Mutable)Set<java.io.File!>!.
  The following types/formats are supported:
    - A String or CharSequence path, for example 'src/main/java' or '/usr/include'.
    - A String or CharSequence URI, for example 'file:/usr/include'.
    - A File instance.
    - A Path instance.
    - A Directory instance.
    - A RegularFile instance.
    - A URI or URL instance.

```

### Context
Groovy parity and API simplicity from the Kotlin DSL perspective.

### Your Environment
```
------------------------------------------------------------
Gradle 5.0-rc-1
------------------------------------------------------------

Build time:   2018-10-30 13:59:22 UTC
Revision:     0b94d7e5908d1d96b8a353d1f28d9c443d767327

Kotlin DSL:   1.0-rc-14
Kotlin:       1.3.0
Groovy:       2.5.3
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          10.0.1 ("Oracle Corporation" 10.0.1+10)
OS:           Mac OS X 10.14 x86_64
```

**Comment by big-guy** [comment] 2018-11-06 05:37
In this particular instance, the `Function0` is unnecessary, just use `java.sourceSets.main.allSource.sourceDirectories`.

In general, we should be trying to avoid introducing more special casing of things like this and making sure the appropriate abstractions are available. 

In the Groovy DSL, `{}` is creating a `Callable`.  So it's not unreasonable that Kotlin DSL could look slightly different with `Callable {}`.  Sprinkling `{}` around is a smell and usually points to a missing API somewhere else.

@eskatos @bamboo WDYT?

**Comment by bamboo** [comment] 2018-11-06 16:31
@big-guy I agree with everything you said except that in the interest of reducing the confusion around the usage of lambdas across DSLs we (@eskatos, @adammurdoch and I) have agreed to also accept Kotlin lambdas (`Function0` instances) as deferred computations.

This is a duplicate of https://github.com/gradle/kotlin-dsl/issues/1077

**Comment by big-guy** [comment] 2018-11-06 17:03
SGTM @bamboo

**Comment by JLLeitschuh** [comment] 2018-11-07 03:07
Sorry about opening the duplicate.

**Closed** 2019-02-25 14:34 UTC
