### ISSUE TITLE
Restoring from build cache breaks Kotlin incremental compilation

### ISSUE THREAD

**Issue by jrodbx** [gradle/gradle#11316] opened 2019-11-11 21:03 UTC
@egorand and I have been conducting a series of experiments around Kotlin compilation and we believe we've uncovered a scenario where incremental compilation breaks when restoring from the build cache.  I'm opening this issue on both Gradle and Kotlin trackers to start a discussion in hopes of finding a solution.

Test project: https://github.com/Egorand/dcto19-cash-app/tree/654598d2090c5257a9397cd1b86eb9f3ac11e24d
Gradle version: 6.0 final
Kotlin Gradle Plugin version: 1.3.60-eap-143
Android Gradle Plugin version: com.android.tools.build:gradle:3.5.2

### Expected Behavior
Fetching results from the build cache should not break incremental compilation.

### Current Behavior
Fetching results from the build cache breaks incremental compilation.

### Context

This experiment shows that retrieving build state from the build cache breaks further incremental compilation and conversely that disabling caching restores incremental compilation behavior.

It's common for developers to switch between branches resulting in different build states, all of which should be recoverable from the build cache to keep developer productivity high.  I'm not sure if this is a Kotlin plugin or Gradle issue, so filing in both issue trackers.

### Steps to Reproduce 
Setup (first time only):

```
git clone https://github.com/Egorand/dcto19-cash-app
cd dcto19-cash-app
git checkout 654598d
```

Add the following properties to `~/.gradle/gradle.properties`
```
kotlin.build.report.enable=true
kotlin.build.report.verbose=true
```
Repeat as needed:

1) Clear caches and app/build
```
rm -rf ~/.gradle/caches/build-cache-1/
rm -rf app/build
```

2) Start with empty state and run `./gradlew app:aDebug`

Open kotlin build report and confirmed expected state -> non-incremental is actual (since first build)

3) Add hello method to `app/src/main/java/com/squareup/dcto19/cashapp/MainActivity.kt` and run `./gradlew app:aDebug`

Open kotlin build report and confirmed expected state -> incremental is actual

4) Remove hello method from 3) and run `./gradlew app:aDebug`

Open kotlin build report and confirmed expected state -> cached is actual

5) Add hello2 method to same file as 3) and run `./gradlew app:aDebug`

Open kotlin build report and not that expected state -> incremental, but actual state -> non-incremental

Workaround:

1) Repeat steps 1-3 as before
2) Remove hello method from 3) and run `./gradlew app:aDebug` --no-build-cache

Open kotlin build report and confirmed expected state -> incremental is actual (!)

3) Add hello2 method to same file as 3) and run `./gradlew app:aDebug`

Open kotlin build report and confirmed expected state -> incremental is actual

---
cc: @gradle/build-cache

**Comment by jrodbx** [comment] 2019-11-11 21:06
Paired with Kotlin issue: https://youtrack.jetbrains.com/issue/KT-34862

**Comment by lptr** [comment] 2019-11-11 21:36
This is by design, at least on the Gradle side. We actually added the `@LocalState` feature because of the Kotlin compiler.

The Kotlin compiler stores data about its incremental compilation state in files that are not reusable between different machines, as they contain references to the compiled files via absolute paths. Because of this Gradle explicitly cleans up incremental compilation state when loading from cache.

The solution is on the Kotlin side. The Kotlin compiler should store its incremental state is without absolute paths (using relative paths instead). With that the state can be reused between machines, and thus can be marked as an `@OutputFile` instead of `@LocalState`, and then it will be shared using the build cache.

**Closed by lptr** 2019-11-11 21:36 UTC
Labels: @build-cache, a:bug, from:contributor

**Comment by jrodbx** [comment] 2019-11-11 23:39
Awesome, thanks for the quick response @lptr.

**Comment by Egorand** [comment] 2019-11-12 13:53
@lptr thanks! Would love some clarification on this part:

> The Kotlin compiler stores data about its incremental compilation state in files that are not reusable between different machines, as they contain references to the compiled files via absolute paths. Because of this Gradle explicitly cleans up incremental compilation state when loading from cache.

Even though this behavior by the Kotlin compiler would clearly break a remote cache, this should presumably work fine with a local cache. Is there any way to instruct Gradle to not delete the incremental compilation state, to benefit from incremental builds + local build cache?

**Comment by lptr** [comment] 2019-11-12 16:49
We don't currently have the ability to mark something safe for local caching, but not to be shared. We don't plan to add it, because in most cases it's straightforward to fix the incremental state; in the meantime `@LocalState` can be used to enable remote caching without incremental state.

**Comment by wolfs** [comment] 2019-11-12 16:55
Note that even for local caching, it is not safe to share the state, since the incremental analysis could be for another task in the same project or for a different project, and then the absolute paths would be different.
