### ISSUE TITLE
Gradle 4.10: Illegal reflective access to method java.lang.Object.finalize()

### ISSUE THREAD

**Issue by bentolor** [gradle/gradle#6725] opened 2018-09-12 11:12 UTC
I'm running `gradle -version` and receive the following warning. Browsing the issues here it seems that the current assumption is that with bundled groovy-version this should no happen any longer

### Expected Behavior
Gradle should not spill out warnings the user cannot provide

### Current Behavior
```
 $ gradle --version -s
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/srv/private/Development/gradle-4.10/lib/groovy-all-2.4.15.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

------------------------------------------------------------
Gradle 4.10
------------------------------------------------------------

Build time:   2018-08-27 18:35:06 UTC
Revision:     ee3751ed9f2034effc1f0072c2b2ee74b5dce67d

Kotlin DSL:   1.0-rc-3
Kotlin:       1.2.60
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          10.0.2 (Oracle Corporation 10.0.2+13-Ubuntu-1ubuntu0.18.04.1)
OS:           Linux 4.15.0-33-generic amd64
```

### Steps to Reproduce (for bugs)
Start `gradle --version` in the aforementioned environemnt

**Comment by oehme** [comment] 2018-09-12 20:33
As stated in the other issue, this is a Groovy problem that we can't fix. What I'm probably gonna do is filter out the warning, as neither we nor our users can do anything about it.

**Comment by oehme** [comment] 2018-10-05 12:46
Unfortunately these warnings never go through our logging infrastructure, because the IllegalAccessLogger is set up during the early boot phase of the JVM and uses System.err before we can replace it. We can't fix that without causing an illegal access warning ourselves.

We can avoid the warning when running `gradle -version` by not using `GroovySystem`. For the daemon we could open up certain JVM modules to ALL_UNNAMED to allow Groovy (and everyone else) to access them. But then we will also miss out on other, valid warnings.

**Comment by oehme** [comment] 2018-10-05 14:12
@marcphilipp Given the explanation above I'm tempted to close this, as we have fixed the one instance where we could prevent the warning (which was also the one that most users complained about). Suppressing the warnings for other usages of Groovy (e.g. compiling Groovy code in your own project) seems like a bad idea to me, as it could hide other issues.

**Comment by bigdaz** [comment] 2018-10-05 14:50
FYI : it was trivial to avoid the warning for `gradle -v`, just by switching to calling a static method on `ReleaseInfo` rather than `GroovySystem`.

**Comment by bigdaz** [comment] 2018-10-05 14:54
I don't think we should underestimate how annoying this message is to users, and how bad it makes Gradle look. I'd be tempted to use the nuclear option to suppress all warnings and then prioritize helping get this fixed in Groovy before we remove that option.

**Comment by bigdaz** [comment] 2018-10-05 21:07
To follow up on this. The warning is displayed whenever we compile groovy sources (because that's always done in a separate JVM) and whenever we execute tests that use groovy. So for a project generated with `gradle init --dsl groovy --type java-library --test-framework spock` will generate the warning twice for `gradle build`: https://e.grdev.net/s/qg3hxalyeke7i/console-log

I don't think the argument about hiding other issues holds water, since my understanding is that the JVM will only report the first illegal access warning, and hide the rest. Assuming that user code is doing this _after_ Groovy, then the warnings will be hidden anyway. If this is the case, then we are just scaring users with a nasty warning with no benefit.

I can see a few options:
1) When launching compiler and test processes, supply the relevant `--allow-opens` so that this warning doesn't show up. (See below)
2) Do some sort of hackery when launching the compiler and test processes, as described here: https://stackoverflow.com/questions/46454995/how-to-hide-warning-illegal-reflective-access-in-java-9-without-jvm-argument
3) Print a big disclaimer before the JVM reported message, informing users that it's really not our fault and to please ignore the warning. We'd need to intentionally load `GroovySystem` or similar to ensure that our disclaimer came right before the warning.
4) I tried adding `--illegal-access=deny` to the jvmargs for the groovy compile and test processes: this actually suppressed the warnings. I'll admit that I have no idea what Groovy is doing in these cases, however. If this "just works" then we could make it the default, providing a mechanism to permit illegal access if they really need to.

Of these, the first seems safest and least likely to cause other, unexpected issues.

For option 1 this is sufficient for the `Test` task that uses Spock:
```
test {
    jvmArgs('--add-opens', 'java.base/java.lang=ALL-UNNAMED')
    jvmArgs('--add-opens', 'java.base/java.lang.invoke=ALL-UNNAMED')
}
```
However, for `GroovyCompile`, it's not possible due to #7045.

**Comment by oehme** [comment] 2018-10-06 07:31
> I don't think the argument about hiding other issues holds water, since my understanding is that the JVM will only report the first illegal access warning, and hide the rest. 

The JVM de-duplicates them like our deprecation logger does, i.e. it won't report the same access twice. But there can be many different illegal accesses, all of which will be reported.

The problem is that you can't just give access to Groovy. You have to give access to all ALL-UNNAMED, which in the unmodularized case is *everything*. So any problems in the user's own code will be hidden.

**Comment by bigdaz** [comment] 2018-10-06 13:59
> The JVM de-duplicates them like our deprecation logger does, i.e. it won't report the same access twice. But there can be many different illegal accesses, all of which will be reported.

You sound confident of that, but it hasn't been my experience. Without any `--illegal-access` parameter, I only see a single illegal access reported per-jvm. I've tried various combinations of loading Groovy and code that performs illegal access, and I've been unable to see multiple issues reported.

If I use `--illegal-access=warn`, then I see all illegal reflective access, de-duplicated.

**Comment by oehme** [comment] 2018-10-06 14:11
Ah right, I had `warn` in my jvm args from some earlier experiment. The default is `oneshot`, as you said.

In that case I wonder what the value of that singular warning is if everything else is hidden from the user. We might as well pass `--illegal-access=permit` until Groovy is fixed then, since Groovy will always be the first warning. As long as we allow the user to overwrite that default, it should be fine.

**Comment by bigdaz** [comment] 2018-10-06 15:36
I think `--illegal-access=permit` is the default, and will result in the current behaviour. This is why I [recommend using `--allow-open` to avoid these warnings](https://github.com/gradle/gradle/issues/6725#issuecomment-427499018).

**Comment by oehme** [comment] 2018-10-06 16:45
Right, I had assumed that "permit" and "oneshot" were different, but they're actually different names for the same mode. So `--add-opens` it is.

**Comment by oehme** [comment] 2018-10-12 08:16
We opened up the two commonly accessed packages for the daemon and the GroovyCompile task. 

We didn't do it for `Test`, because depending on what code you run, the list of illegal accesses is almost endless. Users can try for themselves by passing `--illegal-access=deny` and then adding the relevant `--add-opens` till their tests pass. For some it may only require 1 or 2, for others it may be 20. For instance, CodeNarc uses so many JVM internals that I gave up at some point.

**Closed by oehme** 2018-10-12 08:16 UTC
Labels: a:bug, from:contributor, in:logging

**Comment by csaltos** [comment] 2020-06-28 23:10
If you want to go with the add-open option, here's a command to find which module provides which package ->

`java --list-modules | tr @ " " | awk '{ print $1 }' | xargs -n1 java -d`

the name of the module will be shown with the @ while the name of the packages without it

NOTE: tested with JDK 11

IMPORTANT: obviously is better not to do the illegal access in the first place, but until the transition is done, it is an alternative.
