### ISSUE TITLE
Gradle assumes that TaskDependency can be cast into TaskDependencyInternal

### ISSUE THREAD

**Issue by Loffe** [gradle/gradle#7932] opened 2018-12-05 14:49 UTC
### Expected Behavior
I expect to be able to create a custom task that can be used directly in publishing, by implementing the public interface `PublishArtifact`. In Gradle 4.4 we could implement the `getBuildDependencies()` function like this:

```
  @Override
  TaskDependency getBuildDependencies() {
    return new TaskDependency() {
      @Override
      Set<? extends Task> getDependencies(Task task) {
        return Collections.singleton(MyTask.this)
      }
    }
  }
```

### Current Behavior
In Gradle 5.0, the example fails with the following error:

```
$ ./gradlew publishToMavenLocal

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':publishDataPublicationToMavenLocal'.
> MyTask$1 cannot be cast to org.gradle.api.internal.tasks.TaskDependencyInternal

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

We can change our example to return a `TaskDepencencyInternal` which seems to work. However, it seems like a bug that we have to work with a class that is internal rather than in the public API.

### Steps to Reproduce (for bugs)
[gradle-taskdependency-internal.zip](https://github.com/gradle/gradle/files/2649228/gradle-taskdependency-internal.zip)

```
$ ./gradlew myTask
$ ./gradlew publishToMavenLocal
```

**Comment by oehme** [comment] 2018-12-05 14:53
This type, like almost every interface in Gradle, is not meant for user extension. Only a few like `Action`, `Task` or `Plugin` are. We will do a better job of documenting these in the future. Instead, there is usually a solution that either uses composition or that already works out of the box.

@lacasseio I remember we wanted to make it easy to publish tasks with a single output property, which fits exactly the use case mentioned by @Loffe. Did we already implement that?

**Comment by big-guy** [comment] 2018-12-05 15:05
@oehme We're trying to finish something for that in 5.1

**Comment by oehme** [comment] 2018-12-05 15:08
Is there already an issue for that or should we just use this one?

**Comment by Loffe** [comment] 2018-12-13 07:50
I found another way to solve the original use case :)

By using a `Property` instead of a just a `File`, gradle will understand the task dependency, and there is no need to implement the interface `PublishArtifact`.

```gradle
class MyTask extends DefaultTask {
  @OutputFile
  RegularFileProperty outputFile = project.objects.fileProperty()

  // ... snip ...
}

task myTask(type: MyTask) {
  outputFile = file("$buildDir/my-data.txt")
}

publishing {
  publications {
    data(MavenPublication) {
      groupId = 'com.example.data'
      artifactId = 'my-data'
      version = '1.0'
      artifact myTask.outputFile
    }
  }
}

```

**Comment by oehme** [comment] 2018-12-13 09:03
That's the way it's supposed to be done - I thought this didn't work yet, based on @big-guy's comment.

**Comment by marcphilipp** [comment] 2018-12-13 09:19
There's a related issue about passing a task provider for an archive task: #7958.

**Comment by oehme** [comment] 2018-12-13 10:59
Let's close this one as a duplicate of that.

**Closed by oehme** 2018-12-13 10:59 UTC
Labels: a:feature, from:contributor, in:publishing-plugin
