### ISSUE TITLE
gradle-api-8.5.jar contains JUnit classes and resources

### ISSUE THREAD

**Issue by adam-enko** [gradle/gradle#27571] opened 2024-01-02 16:03 UTC
### Current Behavior

gradle-api-8.5.jar contains JUnit classes and resources

### Expected Behavior

gradle-api-8.5.jar should not contain JUnit classes or resources

### Context (optional)

It's confusing and weird that Gradle includes test-specific classes, and indicates that test code is leaking into gradle-api-8.5.jar.

I discovered this when I wanted to ignore a task input. I annotated it with `@get:Ignore`. My IDE automatically imported the incorrect class. I intended to use `@get:Internal` (which has a less intuitive name).

### Steps to Reproduce

This build file compiles using Gradle 8.5:

```kotlin
// build.gradle.kts

import org.gradle.internal.impldep.org.junit.Ignore
import org.gradle.internal.impldep.org.junit.Test


@Ignore
@Test
fun x() {

}
```

JUnit logos are also visible in gradle-api-8.5.jar

<img width="672" alt="image" src="https://github.com/gradle/gradle/assets/152864218/aa31e60b-46ea-4449-9407-517e1ac26e8b">

### Gradle version

8.5

**Comment by cobexer** [comment] 2024-01-10 09:59
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #13501

Please add your use case and 👍 to that issue.
***
Gradle uses repackaged JUnit classes for its internal implementation and unfortunately, the current gradle-api is really the entire Gradle runtime.

**Closed by cobexer** 2024-01-10 09:59 UTC
Labels: a:bug, to-triage
