### ISSUE TITLE
Inconsistent text / snippet in the "Implementing Custom Tasks"

### ISSUE THREAD

**Issue by madhead** [gradle/gradle#30085] opened 2024-08-04 00:37 UTC
### Issue type

Wrong or misleading information

### Problem description

In the ["Implementing Custom Tasks"](https://docs.gradle.org/current/userguide/implementing_custom_tasks.html#task_implementation_by_extending_defaulttask) there is an inconsistency between the text and the code snippet.

The doc says

> For the input of our task, we use a DirectoryProperty from Gradle. We annotate it with @InputDirectory to indicate that it is an input to the task:

and

>Similarly, for the output, we use a RegularFileProperty and annotate it with @OutputFile.

while the snippet uses a regular `File`s for both:

![image](https://github.com/user-attachments/assets/20fd3992-56ef-4cae-a527-9edf142ea310)

Should the docs be fixed to mention `File` instead?

### Page with the problem

https://docs.gradle.org/current/userguide/implementing_custom_tasks.html#task_implementation_by_extending_defaulttask

**Comment by cobexer** [comment] 2024-08-06 13:41
The issue is in the backlog of the relevant team and is prioritized by them.

***

It looks like the documentation was updated to document lazy types already, but the snippet still needs to be updated.

**Comment by MGaetan89** [comment] 2024-10-14 14:13
Shouldn't this be in the 8.11 RC1 milestone, with #30591 and #30235 being merged there?

**Closed** 2024-10-14 21:05 UTC
Labels: a:documentation, in:writing-tasks, p:lazy-migration
