### ISSUE TITLE
Can't add signatures to a Maven publication

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#20934] opened 2022-06-04 13:09 UTC
I've tried for a long time to get signatures working, but it doesn't work

1. The signing plugin either adds tasks too late or too early, so it misses artifacts or adds the signatures too late to be included in the publication
2. The signing plugin's API for generating signatures is not easy to use. It randomly generates tasks, or causes errors because nothing it produces is serializable and so Gradle crashes
3. The API for adding signatures manually is internal. Why?? https://github.com/gradle/gradle/blob/016b7d517de858ba8b2567b026872a32651256f2/subprojects/publish/src/main/java/org/gradle/api/publish/internal/PublicationInternal.java#L60 
4. There's no option to add signature files to a `MavenPublication`.
5. If I try and add signatures then I'll randomly get `Cannot publish module metadata where component artifacts are modified.` I don't know why. There's no useful information.

Please re-implement the Signing plugin so it's possible to add a signature.

See also

* https://github.com/gradle/gradle/issues/13470

### Your Environment

Build scan URL:

**Comment by vlsi** [comment] 2022-06-05 05:38
Would you please provide a sample that reproduces the issue?
It is clear you have issues with signing, however, it is not clear what do you do to make them appear.

**Comment by aSemy** [comment] 2022-06-05 07:48
@vlsi Here's a demo project https://github.com/aSemy/examples-gradle-signing-bugged

**Comment by ov7a** [comment] 2023-10-17 12:56
Sorry for the late reply.

@aSemy Could you please try with the latest version of Gradle?

**Comment by aSemy** [comment] 2023-10-17 23:09
Hi @ov7a, unfortunately I don't have the time or resources to update the reproducer I provided. Please could you do it? I would appreciate it.

**Comment by ov7a** [comment] 2023-10-18 06:37
Hey, @aSemy. It's unclear to me if this problem is caused by Gradle, KMP, or some misconfiguration. Since this issue is no longer relevant to you, I'm closing this.

**Closed by ov7a** 2023-10-18 06:37 UTC
Labels: a:bug, to-triage

**Comment by vlsi** [comment] 2023-10-18 06:54
@ov7a , the issue is relevant in context of sigstore (see https://github.com/gradle/gradle/issues/21715)

The current sigstore plugin uses a bunch of internal APIs, and I would love to have a public replacements for them.
Would you please reopen the issue?

See:
* https://github.com/sigstore/sigstore-java/blob/68498f295f5bc29d1da92c65d305de048e90ee64/sigstore-gradle/sigstore-gradle-sign-base-plugin/src/main/kotlin/dev/sigstore/sign/SigstoreSignExtension.kt#L91-L94
* https://github.com/sigstore/sigstore-java/blob/68498f295f5bc29d1da92c65d305de048e90ee64/sigstore-gradle/sigstore-gradle-sign-base-plugin/src/main/kotlin/dev/sigstore/sign/SigstoreSignExtension.kt#L28C40-L28C59
* https://github.com/sigstore/sigstore-java/blob/68498f295f5bc29d1da92c65d305de048e90ee64/sigstore-gradle/sigstore-gradle-sign-base-plugin/src/main/kotlin/dev/sigstore/sign/DefaultDerivedArtifactFile.kt#L32

**Comment by ov7a** [comment] 2023-10-18 07:04
@vlsi Thanks for providing the context. Do I understand correctly that your comment is mostly about 3rd point of the original post?

**Comment by vlsi** [comment] 2023-10-18 07:48
You are right. However, I'm not quite sure if `addDerivedArtifact` is the intended API at all.
I guess, `sigstore-gradle-plugin` is the only plugin that generates Sigstore signatures, and I modeled the plugin after Gradle's signing plugin.

I have no explicit requirements for `addDerivedArtifact` method. What I need is the ability to add signatures that would sign artifacts (==subject of the current issue) and I wish the signatures to be published to the same repositories as the artifacts

**Comment by vlsi** [comment] 2023-10-18 07:50
In other words, the description of the current issue looks more like "someone struggles to add a signature", however, it would probably be better to rephrase it as "a need for API for adding signatures". WDYT?

**Comment by ov7a** [comment] 2023-10-18 07:58
Honestly, I think it would be better to open a separate issue for that with a proper description. Since you are having a great knowledge of this area and the context, I'd appreciate it if you do it.

**Comment by vlsi** [comment] 2023-10-18 08:52
I've created https://github.com/gradle/gradle/issues/26760

**Comment by ov7a** [comment] 2023-10-18 08:55
Thank you!
