### ISSUE TITLE
5.0 rc-[1-3]: running `clean check` together causes resources to be missing at test runtime

### ISSUE THREAD

**Issue by marshallpierce** [gradle/gradle#7747] opened 2018-11-15 18:41 UTC
In a multiproject Kotlin build, running `./gradlew clean check` with 4.10.2 works perfectly, and with 5.0 rc-[1-3], has test failures because a particular resource file (in `src/main/resources`) is not present in the classpath. However, with any version, running `./gradlew check` by itself succeeds.

### Expected Behavior
Running `clean check` together should produce the same behavior as `clean`, `check` separately.

### Current Behavior
`SomeClass::class.java.getResourceAsStream(path)` returns null for paths that are most definitely in `src/main/resources` on 5.0 rc's when using `clean check` as one invocation, causing tests to understandably fail.

### Steps to Reproduce (for bugs)

*I haven't been able to isolate this in a simple test case (yet). Let me know if the info below doesn't produce any insight, and I'll give it some further effort.*

In this project, one particular subproject (`svc`) is the subproject where the tests load resources and fail as mentioned above. `svc` also has the most build customization; the other subprojects are very simple kotlin projects with a few dependencies specified.

`svc` has db-related logic and uses the [jooq plugin](https://github.com/etiennestuder/gradle-jooq-plugin) to generate jOOQ sources, which adds a task called `generateApiSvcJooqSchemaSource`. 

It also uses the [flyway plugin](https://flywaydb.org/documentation/gradle/), which adds `flywayClean`, `flywayMigrate`, and other tasks I don't use.

These are hooked in like so:

```
tasks.compileKotlin.dependsOn(generateApiSvcJooqSchemaSource)
tasks.generateApiSvcJooqSchemaSource.dependsOn(flywayMigrate)
tasks.generateApiSvcJooqSchemaSource.mustRunAfter(clean)
```

For test db usage, I also have these to allow tests to use their own database and Flyway tasks:

```
task(makeTestDb) {
  doLast {
    // do some plain sql stuff to make a test user and database, if they're not present
  }
}

task(migrateTestDb, type: FlywayMigrateTask, dependsOn: makeTestDb) {
  url = testJdbcUrl
  user = testDbUser
  password = testDbPass
}

task(cleanTestDb, type: FlywayCleanTask, dependsOn: makeTestDb) {
  url = testJdbcUrl
  user = testDbUser
  password = testDbPass
}
```

and some more wiring

```
tasks.migrateTestDb.mustRunAfter(cleanTestDb)
tasks.flywayMigrate.mustRunAfter(flywayClean)

tasks.test.dependsOn(migrateTestDb)
tasks.clean.dependsOn(cleanTestDb)
```

In the above setup, the erroneous behavior is observed. 

However, if this line `tasks.generateApiSvcJooqSchemaSource.mustRunAfter(clean)` is removed, `./gradlew clean check` works correctly on 5.0 rc3 (didn't test other rcs). 

I don't recall exactly what usage pattern needed that task ordering, but it doesn't occur in my day to day usage, so I'm ok with removing that line. However, it seems like it's probably undesirable that the behavior changed in 5.0... I don't see why that task ordering should cause resources to not show up for tests, at the very least.

### Your Environment
openjdk 11.0.1
x64 Linux 4.14

**Comment by big-guy** [comment] 2018-11-21 22:21
@marshallpierce Could you create a [build scan](https://scans.gradle.com/) when it doesn't work?

If you can't do that, could you post the log of the build?  I'm trying to tell if clean tasks are running in the middle of the build.

Thanks!

**Comment by jjohannes** [comment] 2018-11-22 09:55
@marshallpierce we have not been able to reproduce this issue. Do you still experience it? Could it be an issue with your build specifically? It would be really helpful if you could provide a reproducible example or at least a build scan.

**Comment by jjohannes** [comment] 2018-11-22 10:59
Removed 5.0 RC5 as target since there is no indication that this is a regression so far.

**Comment by marshallpierce** [comment] 2018-11-22 12:39
Here's a scan of the build failing with 5.0 rc3: https://scans.gradle.com/s/3hlp7bwex33wi/

And, with the exact same project succeeding, having run `./gradlew wrapper --gradle-version=4.10.2` first: https://scans.gradle.com/s/irj2czdcgp3qs

**Comment by marshallpierce** [comment] 2018-11-22 12:43
It appears that with 5.0rc3, `processTestResources` and other similar tasks run before `clean` and therefore are not very useful, whereas with 4.10, it's the other way.

It looks like 5 is interleaving dependency tasks of `check` with those of `clean`, leading to a situation where part of the work of `check` is done, and then cleaned.

**Comment by marshallpierce** [comment] 2018-11-22 13:32
Tests pass if run without parallel.
The task wiring is described in the first comment in the issue. If you need more detail it shouldn't be a big deal on my end to get you NDA'd so you can access the real project.

**Comment by jjohannes** [comment] 2018-11-22 13:51
Sorry I missed a part of that original description. 

This might be related to https://github.com/gradle/gradle/issues/2488.

Although you do not have a `clean` task depending on something else but only something else (`generateApiSvcJooqSchemaSource`) depend on `clean`, right?

Independent of this issue, I don't see why you would need something like `tasks.generateApiSvcJooqSchemaSource.mustRunAfter(clean)`. If removing this fixes the problem for you in 5.0, you should do that.

We still should explore why the beavior here changed with 5.0. Maybe @big-guy can make some sense of it.

**Comment by marshallpierce** [comment] 2018-11-22 14:18
Clean must also clean the test database: `tasks.clean.dependsOn(cleanTestDb)`

`tasks.generateApiSvcJooqSchemaSource.mustRunAfter(clean)` was an attempt to solve an issue where the generated source wasn't present by the time compilation tasks ran. I don't remember which combination of tasks I was specifying on the command line at the time I added that, though. With the `mustRunAfter` removed (so `clean check` now at least has its resources present at test runtime), there are still task ordering issues that mean I need to run more than one `./gradlew` invocation to successfully clean everything, have jooq generate sources again, and compile / test everything successfully. That may well be simply more cases of #2488 causing problems, and that's what the `mustRunAfter` was trying to address.

**Comment by big-guy** [comment] 2019-04-16 23:03
Closing this as a dupe of https://github.com/gradle/gradle/issues/2488

**Closed by big-guy** 2019-04-16 23:03 UTC
