### ISSUE TITLE
Support platforms in version catalog bundles

### ISSUE THREAD

**Issue by pranjalvachaspati-toast** [gradle/gradle#23100] opened 2022-12-10 22:31 UTC
### Expected Behavior
I use bundles in my `libs.versions.toml` to handle essentially all my dependency management. I have a `common` bundle, as well as a bundle for each subproject. Then in my `build.gradle.kts` files, I can just do

```
my-subproject/build.gradle.kts

dependencies {
    implementation(libs.bundles.common)
    implementation(libs.bundles.mySubproject)
}
```

```
libs.versions.toml

[versions]
...

[libraries]
foo = {...}
bar = {...}
baz = {...}

[bundles]
common = ["foo"]
mySubproject = ["bar", "baz]
```

This way, when I need to add a dependency or understand the dependencies in my project, I can do all the work in the `libs.versions.toml` file.

### Current Behavior

The problem is that this doesn't work well with platforms. If I want to use a BOM from another source, I have to do 

```
my-subproject/build.gradle.kts

dependencies {
    implementation(libs.bundles.common)
    implementation(libs.bundles.mySubproject)
    implementation(platform(libs.myOtherBom))
}
```

```
libs.versions.toml

[versions]
...

[libraries]
foo = {...}
bar = {...}
baz = {...}
myOtherBom = {...}

[bundles]
common = ["foo"]
mySubproject = ["bar", "baz]
```

If I could specify in my `libs.versions.toml` file that `myOtherBom` should always be a platform, then I could just include it in my bundle.

Something like 

```
myOtherBom = { module = "...", version.ref = "...", variant.type = "platform" }
```

would be great.

### Context

I often end up with a number of BOMs in my projects. My options are currently:
- import them individually into my subprojects. This is fine but inelegant, and it's easy to miss a subproject when adding or removing a BOM.
- put the dependencies in my convention plugin. This is again fine, but using version catalogs from convention plugins is much less convenient than using them in my project's build files.

Also, both of these options don't have the advantage of putting all my dependency information in one place.

**Comment by pranjalvachaspati-toast** [comment] 2022-12-16 01:47
What is this a duplicate of?

**Comment by ljacomet** [comment] 2023-03-03 15:30
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #17169

***

Sorry, the issue was marked as duplicate and should have been closed and linked.

**Closed by ljacomet** 2023-03-03 15:30 UTC
Labels: a:feature, closed:duplicate, in:dependency-version-catalog

**Comment by ChristianCiach** [comment] 2023-05-31 01:46
Sorry, I fail to see how this issue is a duplicate to the issue it has been closed for.

This issue is about adding `platform` dependencies to a `bundle` of a version catalog. How does that relate to maven dependency classifiers? When I do something like `implementation(platform(...))` I don't state the classifier of the dependency.

**Comment by vaibhavrdbhat** [comment] 2023-09-29 03:36
+1, this is NOT a duplicate of that issue.

**Comment by mortenholmgaard** [comment] 2023-10-10 09:18
Please look at this @ljacomet. The purpose of the bundles is missed a bit here with this feature missing as in this case with firebase bom where we can't include the bom in the bundle.

Example:

```
[versions]
firebase = "32.3.1"

[libraries]
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase" }
firebase-pref = { group = "com.google.firebase", name = "firebase-perf-ktx" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging-ktx" }

[bundles]
firebase = ["firebase-pref", "firebase-analytics", "firebase-crashlytics", "firebase-messaging"]

implementation(libs.bundles.firebase)
implementation(platform(libs.firebase.bom))
```

**Comment by austinarbor** [comment] 2023-12-16 18:19
I created a settings plugin which makes using BOMs with version catalogs easier and less repetitive, let me know if it is helpful https://github.com/austinarbor/version-catalog-generator
