### ISSUE TITLE
Init command creates files after CTRL+C

### ISSUE THREAD

**Issue by arthursmel** [gradle/gradle#22800] opened 2022-11-20 22:12 UTC
The `gradle init` command allows users to create a gradle project within the current directory. If a user runs this task and uses `CTRL+C` to cancel the project creation prematurely, files will be created or overwritten. The set of files that are created will depend on which stage of the `init` the user cancels at. The default option will be chosen as the user input for any successive stages of the `init`. Existing files of the same name within the directory will be overwritten.

### Expected Behavior
If the user cancels the `gradle init` before completion, the folder should remain in the same state. Only if the user reaches `BUILD SUCCESSFUL` should any files within the folder be created or modified. 

### Current Behavior / Steps to Reproduce 
Executing `gradle init` in an empty directory. Cancelling after the first question - i.e where the user realises their mistake, yet the files are created. 
```
➜  init-gradle ll
total 0
➜  init-gradle gradle init

Select type of project to generate:
  1: basic
  2: application
  3: library
  4: Gradle plugin
Enter selection (default: basic) [1..4] ^C%
➜  init-gradle ll
total 40
-rw-r--r--  1 mel  staff   200B 20 Nov 20:23 build.gradle
drwxr-xr-x  3 mel  staff    96B 20 Nov 20:23 gradle
-rwxr-xr-x  1 mel  staff   8.0K 20 Nov 20:23 gradlew
-rw-r--r--  1 mel  staff   2.8K 20 Nov 20:23 gradlew.bat
-rw-r--r--  1 mel  staff   360B 20 Nov 20:23 settings.gradle
```

The task will be skipped with the `settings.gradle` or `build.gradle` already exist in the folder. 

```
➜  init-gradle gradle init

> Task :init SKIPPED
The build file 'build.gradle' already exists. Skipping build initialization.

BUILD SUCCESSFUL in 560ms
```
```
➜  init-gradle gradle init

> Task :init SKIPPED
The settings file 'settings.gradle' already exists. Skipping build initialization.

BUILD SUCCESSFUL in 310ms
```

However, there is no check if the wrapper files and folder exists. These could potentially get overwritten. 

### Context

From @6hundreds as part of #21867: 
> The problem from the initial issue is that you think you're in one directory or you're not sure what gradle init is going to do, so you run it in a directory you don't want to put a build in. When you see init's questions, you do ctrl+C and then you find that Gradle has written some files unexpectedly. This can overwrite wrapper files too.
If #21867 we can deal with the issue of `init` overwriting existing files. This issue should be addressed beforehand.

### Your Environment

Build scan URL: N/A

**Comment by eskatos** [comment] 2022-11-23 09:02
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of https://github.com/gradle/gradle/issues/18080. Please add your 👍 to that issue.

**Closed by eskatos** 2022-11-23 09:02 UTC
Labels: a:bug, to-triage
