### ISSUE TITLE
Using a Provider<String> for Project.version does not work for "maven-publish" plugin

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#25971] opened 2023-07-31 23:36 UTC
### Expected Behavior

Set `Project.version` to be a `Provider<String>`, maven-publish plugin understands that and calls `get()` so everything published has a reasonable version.

### Current Behavior

maven-publish plugin simply calls toString on `Provider<String>`

### Steps to Reproduce

1. clone https://github.com/liutikas/gradle-publish-provider-version
2. ./gradlew lib:publish
3. check lib/build/repo, see that version is `map(valueOf(FileTextValue)))`

### Gradle version

8.2.1

**Comment by liutikas** [comment] 2023-07-31 23:38
The current workaround for it is to add a wrapper around `Provider<String>`

```
class Wrapper(private val version: Provider<String>) {
    override fun toString(): String {
        return version.get()
    }
}

version = Wrapper(getMyVersion())
```

**Comment by ov7a** [comment] 2023-08-02 12:42
Thank you for providing a valid report.

The issue is in the backlog of the relevant team, but the existence of a workaround makes it non-critical, so it might take a while before a fix is made.

**Comment by pbielicki** [comment] 2023-08-30 13:54
The workaround provided isn't working when someone wants the version to be actually lazy.
In our case we have a version that is a `Provider<String>` but its value is unknown during the configuration time. This way 
```gradle
publishing {
  publications {
    create<MavenPublication>("somePublication") {
      version = versionProvider
      ...
```

We'd like the publishing plugin start accepting lazy providers that are evaluated lazily at the publishing tasks execution time.

**Comment by big-guy** [comment] 2023-09-13 16:19
Dupe of https://github.com/gradle/gradle/issues/13672

**Closed by big-guy** 2023-09-13 16:19 UTC
Labels: in:publishing-plugins, a:bug, in:configuration-model, in:provider-api, has:workaround

**Comment by jvandort** [comment] 2023-09-13 16:23
@pbielicki Your issue is valid, but separate from this one. Please open another issue

**Comment by pbielicki** [comment] 2023-09-14 08:45
@jvandort https://github.com/gradle/gradle/issues/26374
