### ISSUE TITLE
Remove or fix "Edit on GitHub" button for samples

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#10940] opened 2019-10-03 15:37 UTC

**Comment by lacasseio** [comment] 2019-10-03 15:37
And sample index.

**Comment by lacasseio** [comment] 2019-10-09 15:26
We should fix it with docinfo: https://mrhaki.blogspot.com/2015/04/awesome-asciidoctor-adding-custom.html

**Comment by lacasseio** [comment] 2019-10-09 18:26
We can [specify `:docinfodir:`](https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/_includes/docinfo.adoc) so the docinfo.html files can be relocated. For this, I suggest introducing some sort of content `FileCollection` or expose the `AsciidoctorTask`. Both serve the purpose of attaching a dependency to the `AsciidoctorTask`. I'm leaning toward exposing the AsciidoctorTask so the code on `gradle/gradle` configuring the `AsciidoctorTask` wouldn't really depends on the implementation of the plugin.

**Comment by bric3** [comment] 2019-10-11 12:25
Duplicate of #10487 ?

**Comment by lacasseio** [comment] 2019-10-11 13:37
Not really, the symptom are the same but this is related to the new sample portal. The other issue is related to the fact that some adoc files are moved and renamed which cause older links to point at 404 location.

**Comment by lacasseio** [comment] 2019-10-11 13:38
A fix was push for the yet-to-be release sample plugin. I'm waiting to solve the issue with the release of the plugin.

**Comment by lacasseio** [comment] 2019-10-14 11:59
This should be fixed except for the sample index. See https://github.com/gradle/gradle/issues/11020 instead.

**Closed** 2019-10-14 11:59 UTC
Labels: @core, from:member, in:docs
