### ISSUE TITLE
`./gradlew wrapper` fails if the project has configuration errors

### ISSUE THREAD

**Issue by bric3** [gradle/gradle#25832] opened 2023-07-20 09:47 UTC
### Expected Behavior

Wrapper works without configuring Gradle build, and changes the version without error.

### Current Behavior

```shell
$ ./gradlew wrapper --gradle-version=8.2.1
Configuration on demand is an incubating feature.
Type-safe project accessors is an incubating feature.

> Configure project :conventions
ATTENTION: 'kotlin.experimental.tryK2' is an experimental option enabled in the project for trying out the new Kotlin K2 compiler only.
Please refrain from using it in production code and provide feedback to the Kotlin team for any issues encountered via https://kotl.in/issue

> Configure project :
The plugin 'org.barfuin.gradle.taskinfo' does not support composite builds at this time.
You can still run it by adding -Ptaskinfo.disableSafeguard=true to your Gradle invocation.In that case, tasks from the included builds will be executed.

> Configure project :jdk11
Kotlin DSL property assignment is an incubating feature.

> Configure project :jmh-panama
Directory '/Users/brice.dutheil/opensource/jdk/build/macosx-x86_64-server-release/jdk' (Gradle property 'org.gradle.java.installations.paths') used for java installations does not exist

> Configure project :kotlin
ATTENTION: 'kotlin.experimental.tryK2' is an experimental option enabled in the project for trying out the new Kotlin K2 compiler only.
Please refrain from using it in production code and provide feedback to the Kotlin team for any issues encountered via https://kotl.in/issue
##### 'kotlin.experimental.tryK2' results (Kotlin/Native not checked) #####
No Kotlin compilation tasks have been run
#####
##### 'kotlin.experimental.tryK2' results (Kotlin/Native not checked) #####
No Kotlin compilation tasks have been run
#####

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/brice.dutheil/opensource/sandbox/native/cmem/build.gradle.kts' line: 11

* What went wrong:
An exception occurred applying plugin request [id: 'dev.nokee.c-application', artifact: 'dev.nokee.c-application:dev.nokee.c-application.gradle.plugin:0.4.3129-202303171612.d413fb13']
> Failed to apply plugin 'dev.nokee.c-application'.
   > Could not create domain object 'implementation' (Configuration)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.3-rc-1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 6s
9 actionable tasks: 9 up-to-date
```

### Context (optional)

I was trying Gradle 8.3 RC1 (project was on Gradle 8.2.1). But a Nokee plugin (for native compilation) don't support this yet and as such fails the configuration.

Ref: https://github.com/nokeedev/gradle-native/issues/853

So I wanted to change the version using the wrapper task, but Gradle tries to configure the build thus failing the wrapper task.

I believe the wrapper task should be able to run without configuring the build.

--

Note, I know I can change the version in the `gradle-wrapper.properties`, it just that using the `wrapper` command felt more natural from command line.

### Steps to Reproduce

You can simulate a configuration exception, by throwing an exception in the configuration phase.

Run the wrapper task should fail due to this exception.

### Gradle version

8.3 RC1

**Comment by ov7a** [comment] 2023-07-21 09:23
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/19809

Please add your use case and 👍 to that issue.

**Closed by ov7a** 2023-07-21 09:23 UTC
Labels: a:bug, to-triage
