### ISSUE TITLE
Add support for GPG2 and exported GPG2 keys

### ISSUE THREAD

**Issue by LamborghiniVeneno** [gradle/gradle#1918] opened 2017-05-01 13:26 UTC
Unlike GPG 1, GPG 2 does not have a _secring_ file.

> In gnupg version 2, all key operations are performed by gpg-agent in response to commands issued to its socket. So your program has to be changed to use gpg-agent's public API.
> 
> See "removal of the secret keyring" at https://www.gnupg.org/faq/whats-new-in-2.1.html for more information.

However it is still possible to export private/public GPG keys. Even so, the private keys have Key IDs that are 16 characters long and due to this code in the signing key plugin, even exported GPG 2 keys won't work:

```java
    // org.gradle.plugins.signing.signatory.pgp.PgpKeyId
    private static String normaliseKeyId(String keyId) {
        String keyIdUpped = keyId.toUpperCase();
        switch (keyIdUpped.length()) {
            case 10:
                if (!keyIdUpped.startsWith("0X")) {
                    throw new IllegalArgumentException("10 character key IDs must start with 0x (given value: " + keyId + ")");
                }
                return keyIdUpped.substring(2);
            case 8:
                if (keyId.startsWith("0X")) {
                    throw new IllegalArgumentException("8 character key IDs must not start with 0x (given value: " + keyId + ")");
                }
                return keyIdUpped;
            default:
                throw new IllegalStateException("The key ID must be in a valid form (eg 00B5050F or 0x00B5050F), given value: " + keyId);
        }
    }
```

### Expected Behavior

Support GP2 via the agent as well as through exported private keys.

### Current Behavior

Signing fails with this error:

    The key ID must be in a valid form (eg 00B5050F or 0x00B5050F), given value: ABCDABCDABCDABCD

### Context

I can't publish to Maven Central using my GPG2 keys.

The workarounds on StackOverflow don't work. The code in Gradle Signing plugin clearly prevents 16-char key IDs to be used. If and when GPG 2 keys are supported, the docs should be updated to show how that can be done.

### Steps to Reproduce (for bugs)

* Create a GPG2 key
* Export its secret key by issuing `gpg --export-secret-keys -o ~/secret.gpg`
* Configure `~/.gradle/gradle.properties`:

```
ossrhUsername=foo
ossrhPassword=bar

signing.keyId=ABCEABCEABCEABCE
signing.password=baz
signing.secretKeyRingFile=secret.gpg
```

* Configure the signing plugin in your project
* Build and sign your artifacts
* The build fails with this error:

> `The key ID must be in a valid form (eg 00B5050F or 0x00B5050F), given value: ABCDABCDABCDABCD`

### Your Environment

* Ubuntu 17.04
* GPG 2.1.15
* OpenJDK 1.8.0_121
* Gradle 3.5

**Comment by Antediluvian** [comment] 2017-05-18 03:24
A simple workaround that bypasses the length limitation is that use the last 8 bytes of your signing.keyId。For example if your full keyId is "ABCDEFGHIJKLMNOP", you can use the "IJKLMNOP" as the value of "signing.keyId" and it should be just fine.

**Comment by emlun** [comment] 2017-08-18 07:24
A currently available solution to this is to use the (currently in alpha) [gpg-signing][gpg-signing] plugin. It requires a slightly patched Gradle to work, though - see the README for details.

[gpg-signing]: https://github.com/Yubico/gradle-gpg-signing-plugin

**Comment by OlgaMaciaszek** [comment] 2017-11-15 12:01
As a workaround, you can just use the following command `gpg2 --list-keys  --keyid-format SHORT`. You will get the key ids listed in the format that plugin accepts.

**Comment by grv87** [comment] 2018-09-10 21:53
It seems to be duplicate of #888

**Comment by marcphilipp** [comment] 2018-09-11 14:48
Thanks, @grv87!

**Comment by marcphilipp** [comment] 2018-09-11 14:48
Duplicate of #888

**Closed by marcphilipp** 2018-09-11 14:48 UTC
Labels: a:feature, from:contributor, in:signing-plugin
