### ISSUE TITLE
Expose the ability to look up the task standard and error output in the Gradle Task API

### ISSUE THREAD

**Issue by cesar1000** [gradle/gradle#7694] opened 2018-11-12 04:06 UTC
Tasks that delegate their operation to external processes occasionally report results in the standard or error output. This is the case with the Java or Kotlin compiler, or the AAPT Android tool. The `Task` API does not currently offer any facilities for capturing the output of a single task reliably, and the output capture functionality currently in `TaskInternal` captures all output. Build scan capture the output reliably, but the information is not available programmatically in Gradle.

It's not unreasonable to plugins to expect access to this information. For example, we have a plugin that collects task results and formats them for presenting them to the user (either at the console or through an external integrations with our code review tool), and would need the ability to capture the individual output of these tasks.

I feel that the ideal solution would be for the `Task` API to expose streams for the standard and error output of the task. Alternatively, it would be convenient if the information in the build scan could be queries programmatically through a standard interface.

For context, this is what the summaries look like:
![image](https://user-images.githubusercontent.com/2517200/48326233-0e04b700-e5ed-11e8-9f0d-0778d3faa39d.png)
![image](https://user-images.githubusercontent.com/2517200/48326250-1eb52d00-e5ed-11e8-8e35-a10028b01253.png)

**Comment by ldaley** [comment] 2018-11-12 07:55
Duplicate of #6068.

**Closed by ldaley** 2018-11-12 07:55 UTC
