### ISSUE TITLE
Project + version catalog accessors don't work in subprojects block if subprojects exist

### ISSUE THREAD

**Issue by 01111111111111111** [gradle/gradle#16856] opened 2021-04-15 17:55 UTC
Using type safe project accessors inside an `allprojects` or `subprojects` block breaks if the project has a subproject, unable to find extensions. 

### Expected Behavior
Able to use project and version catalogs inside `subproject` and `allprojects` block.

### Current Behavior
Gradle build fails (can't find extensions) when attempting to use project accessor or version catalog accessors inside `subproject` and `allprojects` blocks ONLY if said project has subproject belonging to it. In the example below, if I remove subproject `b` from project `a` than it builds. 

### Steps to Reproduce 
settings.gradle.kts
```
enableFeaturePreview("VERSION_CATALOGS")
enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

include("a:b")
include("c")
```

build.gradle.kts for `a`
```
subprojects {
    dependencies {
        implementation(projects.c)
    }
}
```
Result of gradle build
```
* Where:
Build file '!/Projects/test/a/build.gradle.kts' line: 3

* What went wrong:
Extension with name 'projects' does not exist. Currently registered extension names: [ext, kotlin, kotlinTestRegistry, defaultArtifacts, sourceSets, reporting, java, javaToolchains]
```
![image](https://user-images.githubusercontent.com/18277475/114914679-9c01af00-9df0-11eb-96df-de7fb9024383.png)

### Your Environment
IntelliJ IDEA 2021.1
Gradle 7.0
JDK 15
Kotlin 1.4.32

**Comment by melix** [comment] 2021-04-16 09:24
Closing as duplicate of #16636

Please look at the issue comments for details.

**Closed by melix** 2021-04-16 09:24 UTC
Labels: a:bug, to-triage
