### ISSUE TITLE
No version of NDK matched the requested version 20.0.5594570. Versions available locally: 21.0.6113669

### ISSUE THREAD

**Issue by Mister-Hope** [gradle/gradle#12440] opened 2020-03-05 12:25 UTC
I and some guys in this [link](https://stackoverflow.com/questions/60404457/android-no-version-of-ndk-matched-the-requested-version) trigged error when upgrading to 3.6.0 and above.

Our project works fine under 3.6.0, and at least my project do not require NDK, since No C files in my project. But we all trigged the same issue

```
No version of NDK matched the requested version 20.0.5594570. Versions available locally: 21.0.6113669
```

I wonder if you could check it out.

The fact is the project works pretty fine when 

```
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
```

And trigged error when 

```
    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.1' (also can be 3.6.0)
```

And if I do add the ndk 20.0, the build apk increased 10MB from 7.1MB to 17.0MB, which obviously not the way it should have been built

**Comment by benibela** [comment] 2020-03-10 13:35
I also have this problem. For me, it is happening [on Travis](https://travis-ci.org/benibela/videlibri/jobs/660186729?utm_medium=notification&utm_source=github_status), not locally. Do I need to install something on travis?

**Comment by zkhan93** [comment] 2020-03-16 10:46
same behavior on GitHub workflows, [this](https://github.com/zVolt/familyfinance-android/pull/7/checks) is the log

**Comment by deathofshit** [comment] 2020-03-16 14:26
me too

**Comment by prsolucoes** [comment] 2020-03-18 17:53
Me too. It was solved?

```
No version of NDK matched the requested version 20.0.5594570. Versions available locally: 21.0.6113669
```

Log:
https://github.com/ezored/ezored/runs/517098191?check_suite_focus=true#step:14:46

**Comment by Jbz797** [comment] 2020-03-18 18:11
Same here

**Comment by Mister-Hope** [comment] 2020-03-19 06:05
😢 Half a month pasted, while no one responds. Sad.

At least it has a work around which using 3.5.0 instead.

Let's wait for the offical.

**Comment by zhbzhbzhbz** [comment] 2020-03-19 06:51
Same here

**Comment by davidmartin1860** [comment] 2020-03-19 14:36
Can you check if there is any ndk-data locally in your sdk-directory? My SDK-Manager didn't show an installed version but there were a "ndk" and "ndk-bundle" folder.

For MacOS, check via Terminal:
`cd ~/Library/Android/sdk`
`ls`

If you see "ndk" and/or "ndk-bundle", delete them:
`sudo rm -r ndk/`
`sudo rm -r ndk-bundle/`

After deleting those folders, everything worked fine for me.

**Comment by absimas** [comment] 2020-03-19 15:11
What worked for me was installing the missing NDK version. Now I have 2 versions but at least the issue is gone.

**Comment by prsolucoes** [comment] 2020-03-19 16:09
Hi,

Github team give me a command that work for me:
https://github.com/ezored/ezored/runs/519656838?check_suite_focus=true

Issue:
https://github.com/actions/virtual-environments/issues/578#issuecomment-601160655

Thanks.

**Comment by hpsaturn** [comment] 2020-03-19 20:52
I have the same issue, my project has a CMake file, Github workflows reported it, my only change was update gradle tools and android tools. Sounds like that is a default on Github workflows? because in my project I dont have any NDK version definition.

workflow output:
https://github.com/kike-canaries/android-hpma115s0/pull/41/checks

**Comment by Mister-Hope** [comment] 2020-03-20 01:59
> Can you check if there is any ndk-data locally in your sdk-directory? My SDK-Manager didn't show an installed version but there were a "ndk" and "ndk-bundle" folder.
> 
> For MacOS, check via Terminal:
> `cd ~/Library/Android/sdk`
> `ls`
> 
> If you see "ndk" and/or "ndk-bundle", delete them:
> `sudo rm -r ndk/`
> `sudo rm -r ndk-bundle/`
> 
> After deleting those folders, everything worked fine for me.

What? Are you kidding? What about my other project which requires NDK, besides others are meating problems in CI?

**Comment by Mister-Hope** [comment] 2020-03-20 02:01
> Hi,
> 
> Github team give me a command that work for me:
> https://github.com/ezored/ezored/runs/519656838?check_suite_focus=true
> 
> Issue:
> [actions/virtual-environments#578 (comment)](https://github.com/actions/virtual-environments/issues/578#issuecomment-601160655)
> 
> Thanks.

But it doesn't mean there isn't an issue here. Some of our projects do not need NDK at all.

**Comment by Mister-Hope** [comment] 2020-03-20 02:05
I have the issue that

> And if I do add the ndk 20.0, the build apk increased 10MB from 7.1MB to 17.0MB, which obviously not the way it should have been built

Do you have the same issue?

**Comment by shah-nishant** [comment] 2020-03-24 05:54
Was anyone able to find the solution? We are also facing the same issue with GitHub workflows

**Comment by prsolucoes** [comment] 2020-03-24 13:14
> Was anyone able to find the solution? We are also facing the same issue with GitHub workflows

Github team give me a command that work for me:
https://github.com/ezored/ezored/runs/519656838?check_suite_focus=true

**Comment by rngadam** [comment] 2020-03-26 18:06
@prsolucoes 

```
    - name: Install NDK
      run: echo "y" | sudo /usr/local/lib/android/tools/bin/sdkmanager --install "ndk;20.0.5594570" --sdk_root=${ANDROID_SDK_ROOT}
```

fails with:

```
Run echo "y" | sudo /usr/local/lib/android/tools/bin/sdkmanager --install "ndk;20.0.5594570" --sdk_root=${ANDROID_SDK_ROOT}
sudo: /usr/local/lib/android/tools/bin/sdkmanager: command not found
##[error]Process completed with exit code 1.
```

**Comment by shah-nishant** [comment] 2020-03-29 22:30
@prsolucoes @rngadam That fixed our issue. Thanks a lot!

**Comment by marinomeneghel** [comment] 2020-03-30 15:48
> If you see "ndk" and/or "ndk-bundle", delete them:
> `sudo rm -r ndk/`
> `sudo rm -r ndk-bundle/`
> 
> After deleting those folders, everything worked fine for me.

**Comment by friederbluemle** [comment] 2020-03-30 19:14
This appears to be a bug (?) in the **Android Gradle plugin** starting with version `3.6.0`. It can also be observed with `3.6.1` (the latest stable version as of 2020-03-30).

See this StackOverflow question for some additional info:
https://stackoverflow.com/questions/60404457/android-no-version-of-ndk-matched-the-requested-version

It can easily be reproduced locally with a project the does **not** require the NDK to build.

With **no NDK** installed, you may see the following _warning_ in the build log:

```
WARNING: Compatible side by side NDK version was not found. Default is 20.0.5594570.
```

The build will succeed.

However, just by installing the `ndk-bundle`, the build now starts to fail:

```
FAILURE: Build failed with an exception.
No version of NDK matched the requested version 20.0.5594570. Versions available locally: 21.0.6113669
```

The three workarounds I know of are:

1. Install the **older** NDK it is looking for (side-by-side): `sdkmanager 'ndk;20.0.5594570'`
2. Manually specify the **newer** version in `build.gradle`:
    ```groovy
    android {
        compileSdkVersion 29
        ndkVersion "21.0.6113669"
    
        //...
    }
    ```
3. **Uninstall** the NDK (if you don't need it for other projects): `sdkmanager --uninstall 'ndk-bundle'` This is essentially the same as deleting the NDK folder(s) as others have suggested in this thread.

The best option of course would be a proper fix in the Android Gradle plugin.

**Comment by benjaminuggla** [comment] 2020-04-15 07:35
Problem was solved for me by setting latest gradle version (6.3) in the distributionUrl in the gradle-wrapper.properties file. I'm using gradle:3.6.2 in buildscript/dependencies in build.gradle.

**Comment by friederbluemle** [comment] 2020-04-15 07:43
@benjaminuggla - Just tried this locally, unfortunately it did not work for me.

**Comment by benjaminuggla** [comment] 2020-04-15 07:53
@friederbluemle 

> @benjaminuggla - Just tried this locally, unfortunately it did not work for me.

Sorry, you are right. It's still the same for me. I don't know why the compiler did not catch this in first sight. But now it does.

**Comment by n13** [comment] 2020-05-26 13:59
We just had this error pop up on GitHub -is that checkin above the cause, or the fix?  (https://github.com/magnusja/libaums/commit/dc7af5459e811ec89d44ca52749fc04149471973)

Asking because the bug popped up around the same time as that checkin, just happened.

```
Execution failed for task ':app:stripDebugDebugSymbols'.
182

183
> No version of NDK matched the requested version 20.0.5594570. Versions available locally: 21.1.6352462
184

```

**Comment by ljacomet** [comment] 2020-05-27 08:56
As @samtstern [commented](https://github.com/gradle/gradle/issues/12440#issuecomment-617779851), this is an Android issue which cannot be solved by core Gradle. I can only encourage you all to go up-vote the issue on the Android side.

Also @friederbluemle [provided workarounds](https://github.com/gradle/gradle/issues/12440#issuecomment-606188282).

**Comment by euthribeiro** [comment] 2020-06-18 13:33
![Capturar](https://user-images.githubusercontent.com/36652917/85026329-ea054200-b14e-11ea-9233-36dcbfab8955.PNG)


Open the Android Studio SDK Manager, go to the SDK Tools tab and install the required version of the NDK. Hope this helps.

**Comment by eduardodoria** [comment] 2020-06-19 14:45
> This appears to be a bug (?) in the **Android Gradle plugin** starting with version `3.6.0`. It can also be observed with `3.6.1` (the latest stable version as of 2020-03-30). EDIT: Still not fixed in `3.6.2`.
> 
> See this StackOverflow question for some additional info:
> https://stackoverflow.com/questions/60404457/android-no-version-of-ndk-matched-the-requested-version
> 
> It can easily be reproduced locally with a project the does **not** require the NDK to build.
> 
> With **no NDK** installed, you may see the following _warning_ in the build log:
> 
> ```
> WARNING: Compatible side by side NDK version was not found. Default is 20.0.5594570.
> ```
> 
> The build will succeed.
> 
> However, just by installing the `ndk-bundle`, the build now starts to fail:
> 
> ```
> FAILURE: Build failed with an exception.
> No version of NDK matched the requested version 20.0.5594570. Versions available locally: 21.0.6113669
> ```
> 
> The three workarounds I know of are:
> 
> 1. Install the **older** NDK it is looking for (side-by-side): `sdkmanager 'ndk;20.0.5594570'`
> 2. Manually specify the **newer** version in `build.gradle`:
>    ```groovy
>    android {
>        compileSdkVersion 29
>        ndkVersion "21.0.6113669"
>    
>        //...
>    }
>    ```
> 3. **Uninstall** the NDK (if you don't need it for other projects): `sdkmanager --uninstall 'ndk-bundle'` This is essentially the same as deleting the NDK folder(s) as others have suggested in this thread.
> 
> The best option of course would be a proper fix in the Android Gradle plugin.

Also worked for me:

`echo "ndk.dir=${ANDROID_HOME}/ndk-bundle" > local.properties`

**Comment by benjaminuggla** [comment] 2020-06-22 07:53
> ![Capturar](https://user-images.githubusercontent.com/36652917/85026329-ea054200-b14e-11ea-9233-36dcbfab8955.PNG)
> 
> Open the Android Studio SDK Manager, go to the SDK Tools tab and install the required version of the NDK. Hope this helps.

Thank you! Now it's working for me.

**Comment by runningcode** [comment] 2020-06-22 11:09
Thank you for your interest in Gradle and for reporting this.

This is an issue with the Gradle Android Plugin which is developed by Google and cannot be addressed in the core of the Gradle Build Tool.

For more information on this issue and how the relevant team at Google is resolving it, you can follow this issue: https://issuetracker.google.com/issues/144111441

In the future, issues with the Android Gradle Plugin should be filed on the Android Issue Tracker at https://source.android.com/source/report-bugs

**Closed by runningcode** 2020-06-22 11:09 UTC
Labels: @jvm, a:bug, from:contributor

**Comment by imannms** [comment] 2020-07-01 11:43
I have the same issue: `No version of NDK matched the requested version 20.0.5594570. Versions available locally: 21.3.6528147`

I fix it by adding `ndkVersion "21.3.6528147"` inside gradle.app

Example:
```
gradle.app:

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.3"
    ndkVersion "21.3.6528147"
}
```

**Comment by bestkid1234** [comment] 2020-07-27 16:46
> Can you check if there is any ndk-data locally in your sdk-directory? My SDK-Manager didn't show an installed version but there were a "ndk" and "ndk-bundle" folder.
> 
> For MacOS, check via Terminal:
> `cd ~/Library/Android/sdk`
> `ls`
> 
> If you see "ndk" and/or "ndk-bundle", delete them:
> `sudo rm -r ndk/`
> `sudo rm -r ndk-bundle/`
> 
> After deleting those folders, everything worked fine for me.

Same problem on Windows. Same solution:

Go to **C:\Users\YourUser\AppData\Local\Android\Sdk** and delete **ndk** and **ndk-bundle** folders.

**Comment by junaid5546** [comment] 2020-08-07 06:46
just go to build.gradle (PROJECT LEVEL)

ERROR: In my case I was using 3.5.3 and when I upgraded It was 4.somthing and it generated ndk error.
how I resolve => I checked my GitHub repo and saw that my Gradle version in GitHub is build.gradle is 3.5.3 so I changed it from 4.something to 3.5.3 and problem gone.
dependencies {
        classpath('com.android.tools.build:gradle:3.5.3') // 
        classpath ('com.google.gms:google-services:4.3.3')

    }

**Comment by mertceyhan** [comment] 2020-09-07 21:03
Same here. I'm not getting this error on local but on [Bitrise](https://www.bitrise.io/).

`No version of NDK matched the requested version 21.2.6472646. Versions available locally: 21.3.6528147`

**Comment by Anuskhan** [comment] 2020-11-18 06:10
dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
}

**Comment by kasim121** [comment] 2020-11-18 13:36
Open  Android Studio IDE  select  Tools --> SDK Manager --> SDK Tools --> Show Packages --> NDK(Side by Side) --> Download (Installed) 21.0.6113669
Also write this  inside ( app gradle)

android {
 compileSdkVersion 29
    ndkVersion "21.0.6113669"
}
 I hope this will help you.

**Comment by Hasham24** [comment] 2022-06-17 11:40
I faced this issue in the app center while making the build, but I tried these solutions but it didn't solve in the app center. little help would be appreciated.

**Comment by swapnilgaikwad1507** [comment] 2022-08-04 09:47
@Hasham24 
Hey did you find any solution?
I am also facing the same issue in AppCenter while building it for Android.

**Comment by Hasham24** [comment] 2022-08-04 09:56
> @Hasham24 Hey did you find any solution? I am also facing the same issue in AppCenter while building it for Android.

@swapnilgaikwad1507 yes I just change the ndk version to this "21.4.7075529". I found no other solution.

**Comment by swapnilgaikwad1507** [comment] 2022-08-04 09:59
Where exactly did you change the version?

**Comment by Hasham24** [comment] 2022-08-04 10:04
> @Hasham24 Where exactly did you change the version?

I just go android/app/buildgradle and update the ndk version. if you don't found there then just look at the android/buildgradle.

**Comment by swapnilgaikwad1507** [comment] 2022-08-04 10:05
@Hasham24  If you don't mind, could you please post your gradle file here.

**Comment by Hasham24** [comment] 2022-08-04 10:07
> @Hasham24 If you don't mind, could you please post your gradle file here.

I can't you can approach me on LinkedIn. I share the link to my profile.  
https://www.linkedin.com/in/ahmad-hasham-6a70a5104/

**Comment by itzyashh** [comment] 2023-08-28 16:42
> Can you check if there is any ndk-data locally in your sdk-directory? My SDK-Manager didn't show an installed version but there were a "ndk" and "ndk-bundle" folder.
> 
> For MacOS, check via Terminal: `cd ~/Library/Android/sdk` `ls`
> 
> If you see "ndk" and/or "ndk-bundle", delete them: `sudo rm -r ndk/` `sudo rm -r ndk-bundle/`
> 
> After deleting those folders, everything worked fine for me.

this happened with me when i ctrl + c when building process was installing ndk 
Checking the license for package NDK (Side by side) 20.1.5948944 in /Users/yash/Library/Android/sdk/licenses
License for package NDK (Side by side) 20.1.5948944 accepted.
Preparing "Install NDK (Side by side) 20.1.5948944 (revision: 20.1.5948944)".
<==========---> 79% CONFIGURING [49s]
> :react-native-reanimated
So dont stop this process this can corrupt your ndk
