### ISSUE TITLE
Gradle-Junit4 integration doesn't support junit parametrized tests with dot in the parameter name

### ISSUE THREAD

**Issue by HackerMadCat** [gradle/gradle#27572] opened 2024-01-02 16:54 UTC
### Current Behavior

```
./gradlew :test --tests "com.intellij.JunitParametrizedTest.parametrized_test[first.com]"
> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> No tests found for given includes: [com.intellij.JunitParametrizedTest.parametrized_test[first.com]](--tests filter)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 299ms
2 actionable tasks: 1 executed, 1 up-to-date
```

### Expected Behavior

`com.intellij.JunitParametrizedTest.parametrized_test` test should be successfully executed with the parameter `"first.com"`.

### Context (optional)

I need to execute Junit 4 tests with specific parameters. But it fails, because Gradle cannot find tests by test filter `com.intellij.JunitParametrizedTest.parametrized_test[first.com]`.
During debugging of Gradle, I found that Gradle tries to identify which class can pass my filter `org.gradle.api.internal.tasks.testing.filter.TestSelectionMatcher#mayIncludeClass`. But here for some reason, Gradle checks the size of the filter and the fully qualified class name. In the simple case, the filter has segments of class and the last segment is the method name. But in my case, the last segment isn't the method name, it is part of the test parameter.

Therefore, Gradle rejects my filter, but shouldn't.

### Steps to Reproduce

1. Download sample project [untitled65.zip](https://github.com/gradle/gradle/files/13811996/untitled65.zip)
2. Execute this command line in the project root `:test --tests "com.intellij.JunitParametrizedTest.parametrized_test[first.com]"`

### Gradle version

8.4

**Comment by cobexer** [comment] 2024-01-10 10:04
Thank you for providing a valid report.

The issue is in the backlog of the relevant team, but the existence of a workaround makes it non-critical, so it might take a while before a fix is made.
***
The workaround is to not use dots in the parameter names.

**Comment by cobexer** [comment] 2024-01-10 10:05
This issue is a good choice for first-time contributors to Gradle, it is actionable and ready for contribution.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.

**Comment by piotrtomiak** [comment] 2024-01-10 11:05
> The workaround is to not use dots in the parameter names.

@cobexer - it is a difficult thing to workaround if the parameter is a file name ;)

**Comment by mahdikhashan** [comment] 2024-02-29 15:25
@ka1amita hey, have you already started working on it, if not I'd like to pick it up.

**Comment by ka1amita** [comment] 2024-02-29 20:50
Hello,
 feel free. I have got a job and had change priorities 😅

Cheers

Matěj

**Comment by mahdikhashan** [comment] 2024-02-29 23:06
@cobexer Just pinged to kindly let you know I started working on this, would you reassign it to me to prevent any double work?

**Closed** 2024-03-19 14:21 UTC
Labels: a:bug, in:testing-junit4, has:reproducer, has:workaround, good first issue
