### ISSUE TITLE
Upgrading to Gradle 4.5 causes Dokka Gradle plugin to crash

### ISSUE THREAD

**Issue by edeandrea** [gradle/gradle#4171] opened 2018-01-26 19:07 UTC
When moving from Gradle 4.4.1 to 4.5 our projects which use the Dokka Gradle plugin crash. There is Kotlin/dokka#265 open as well on the Dokka side that describes the issue. I'm not sure where the issue lies - either with Gradle or with Dokka. In any event this will prevent upgrades to Gradle 4.5 until its resolved. I'm uploading the same sample project here as I uploaded there.

 * Build scan URL: https://scans.gradle.com/s/stwrdyj2emkmq

When running `clean build` of a project that uses Dokka (see attached sample) we get

```
:clean
:compileKotlin
:compileJava NO-SOURCE
:processResources NO-SOURCE
:classes UP-TO-DATE
:jar

FAILURE: Build failed with an exception.

* What went wrong:
kotlin.reflect.jvm.internal.KClassImpl.getMembers(Lkotlin/reflect/jvm/internal/impl/resolve/scopes/MemberScope;ZZZ)Lkotlin/sequences/Sequence;

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
java.lang.NoSuchMethodError: kotlin.reflect.jvm.internal.KClassImpl.getMembers(Lkotlin/reflect/jvm/internal/impl/resolve/scopes/MemberScope;ZZZ)Lkotlin/sequences/Sequence;
	at kotlin.reflect.KClasses.getMemberProperties(KClasses.kt:140)
	at org.jetbrains.dokka.ReflectDsl$CallOrPropAccess$prop$2.invoke(ReflectDsl.kt:22)
	at org.jetbrains.dokka.ReflectDsl$CallOrPropAccess$prop$2.invoke(ReflectDsl.kt:8)
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
	at org.jetbrains.dokka.ReflectDsl$CallOrPropAccess.getProp(ReflectDsl.kt)
	at org.jetbrains.dokka.ReflectDsl$CallOrPropAccess.v(ReflectDsl.kt:30)
	at org.jetbrains.dokka.ReflectDsl$CallOrPropAccess.get(ReflectDsl.kt:18)
	at org.jetbrains.dokka.gradle.DokkaTask.extractClasspathAndSourceRootsFromKotlinTasks(main.kt:216)
	at org.jetbrains.dokka.gradle.DokkaTask.access$extractClasspathAndSourceRootsFromKotlinTasks(main.kt:54)
	at org.jetbrains.dokka.gradle.DokkaTask$kotlinCompileBasedClasspathAndSourceRoots$2.invoke(main.kt:116)
	at org.jetbrains.dokka.gradle.DokkaTask$kotlinCompileBasedClasspathAndSourceRoots$2.invoke(main.kt:54)
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
	at org.jetbrains.dokka.gradle.DokkaTask.getKotlinCompileBasedClasspathAndSourceRoots$gradle_plugin_main(main.kt)
	at org.gradle.api.internal.tasks.properties.DefaultPropertyWalker$DefaultPropertyValue$1$1.create(DefaultPropertyWalker.java:138)
	at org.gradle.util.SingleMessageLogger.whileDisabled(SingleMessageLogger.java:240)
	at org.gradle.api.internal.tasks.properties.DefaultPropertyWalker$DefaultPropertyValue$1.get(DefaultPropertyWalker.java:135)
	at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:125)
	at org.gradle.api.internal.tasks.properties.DefaultPropertyWalker$DefaultPropertyValue.getValue(DefaultPropertyWalker.java:187)
	at org.gradle.api.internal.tasks.properties.DefaultPropertyWalker$DefaultPropertyValue.validate(DefaultPropertyWalker.java:198)
	at org.gradle.api.internal.tasks.DefaultTaskInputPropertySpec.validate(DefaultTaskInputPropertySpec.java:61)
	at org.gradle.api.internal.tasks.execution.DefaultTaskProperties.validate(DefaultTaskProperties.java:193)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:47)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:623)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:578)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
```

[kotlin-test.zip](https://github.com/gradle/gradle/files/1668848/kotlin-test.zip)

**Comment by eriwen** [comment] 2018-01-26 20:27
In this case, Dokka seems to be using a Kotlin-internal API from kotlin-reflect, which was removed in Kotlin 1.2.

Kotlin minor releases are considered to be generally backward-compatible; it just so happens that Gradle 4.5 upgrades the version of Kotlin used to compile plugins to Kotlin 1.2 (which _should_ be a safe move). 

In this case, I would say Kotlin and Dokka are expected to adhere to proper versioning/avoidance of internal APIs, and Dokka 0.9.16 should address this (I hope). I'd say it's fair of the Kotlin project to remove an internal API in a minor release.

Were this kind of thing to become more frequent, well we'd have to work with the Kotlin team closer and avoid upgrading the Kotlin compiler used by Gradle for breaking changes.

Anything you'd like to add @gradle/kotlin-dsl team?

**Comment by bamboo** [comment] 2018-01-29 11:07
I'd just like to share our current Kotlin upgrade policy:

> Until the release of Gradle Kotlin DSL v1.0 our policy will be to ship with the latest stable Kotlin version available at the time.

From [Kotlin versions and the Gradle Kotlin DSL](https://github.com/gradle/kotlin-dsl/blob/develop/doc/getting-started/Kotlin-Versions.md).

**Comment by edeandrea** [comment] 2018-01-29 12:22
Shouldn't whatever version of kotlin that the Gradle Kotlin dsl uses be invisible to the project - similar to how the Groovy version is? The fact that the Kotlin version is visible to the project seems to be the cause of this issue. This is shown by the simple fact that upgrading Gradle from 4.4.1 to 4.5 without modification to the project or it's dependencies causes it to break.

**Comment by oehme** [comment] 2018-01-29 14:17
> Shouldn't whatever version of kotlin that the Gradle Kotlin dsl uses be invisible to the project - similar to how the Groovy version is?

The problem is in the dokka plugin, not in your code. The plugin needs to see the same Kotlin version as Gradle, otherwise it couldn't interact with the Gradle DSL. The same is true for Groovy. Every plugin sees the same Groovy version - the one that Gradle ships with. We just don't do breaking Groovy upgrades in minor releases. We do it for Kotlin, because we're still in 0.x.

**Comment by edeandrea** [comment] 2018-01-29 14:20
Thank you @oehme for the explanation. So just to be clear with the outcome here - those of us who use Dokka are stuck with Gradle 4.4.1 until the Dokka folks fix their problem?

**Comment by oehme** [comment] 2018-01-29 14:20
I'm afraid so.

**Comment by edeandrea** [comment] 2018-01-29 14:26
Do you guys have any leverage with them? Seems from their issue tracker activity that they aren't very active.

**Comment by eskatos** [comment] 2018-01-30 09:13
The upstream issue just got assigned and lined up for the upcoming Dokka 0.9.16.

**Comment by oehme** [comment] 2018-01-30 09:52
Closing since there is nothing else to do on the Gradle side.

**Closed by oehme** 2018-01-30 09:52 UTC
Labels: from:contributor

**Comment by Snorri1986** [comment] 2020-12-28 11:42
Hi
Is Dokka 0.9.16 available for updating ?
