### ISSUE TITLE
gradle platform not recognized by annotationProcessor by project reference

### ISSUE THREAD

**Issue by swyfok** [gradle/gradle#12519] opened 2020-03-13 15:24 UTC
I have BOM module 'common-bom' using  java-platform, here is the excerpt

```
plugins {
    id 'java-platform'
    id 'maven-publish'
}

javaPlatform {
    allowDependencies()
}

dependencies {
    api platform('org.springframework.boot:spring-boot-dependencies:2.2.4.RELEASE')
    api platform('org.springframework.cloud:spring-cloud-dependencies:Hoxton.SR1')
    constraints {
        api 'org.slf4j:slf4j-api:1.7.30'
...
}
```

when other modules try to reference it within the same root project, it cannot resolve it:
```
dependencies {
    api platform(project(':commons-bom'))
    annotationProcessor platform(project(':commons-bom'))

    implementation 'org.springframework:spring-context'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
}
```

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':commons-utils:compileJava'.
> Could not resolve all task dependencies for configuration ':commons-utils:annotationProcessor'.
   > Could not resolve project :commons-bom.
     Required by:
         project :commons-utils
      > Cannot choose between the following variants of project :commons-bom:
          - apiElements
          - runtimeElements
        All of them match the consumer attributes:
          - Variant 'apiElements':
              - Required org.gradle.component.category 'platform' and found compatible value 'platform'.
              - Found org.gradle.usage 'java-api' but wasn't required.
          - Variant 'runtimeElements':
              - Required org.gradle.component.category 'platform' and found compatible value 'platform'.
              - Found org.gradle.usage 'java-runtime' but wasn't required.
```

But if i referenced the bom from the repository after the build it works:
from
```
    annotationProcessor platform(project(':commons-bom'))
```
to
```
    annotationProcessor platform('com.xxx:commons-bom:1.0.0-SNAPSHOT')
```

**Comment by ljacomet** [comment] 2020-03-13 15:35
What are the plugins applied in your `:commons-utils` project?

**Comment by Raniz85** [comment] 2020-03-24 13:40
I had this issue in 5.2.1 but when upgrading to 6.2.2 it went away

**Comment by melix** [comment] 2020-04-15 17:33
Closing as fixed.

**Closed by melix** 2020-04-15 17:33 UTC
Labels: @jvm, a:bug, from:contributor, in:dependency-management

**Comment by xiemeilong** [comment] 2020-12-09 06:33
@melix I am using gradle-6.7.1 , this issue still exists.  only annotationProcessor not works.

**Comment by Vincent9101** [comment] 2021-04-14 04:55
> @melix I am using [gradle-6](https://issues.gradle.org/browse/GRADLE-6).7.1 , this issue still exists. only annotationProcessor not works

I  am using 6.8.3  by includeBuild my-Bom ,the  issue still exists ,

**Comment by melix** [comment] 2021-04-14 06:46
Would you mind providing a minimal reproducer?

**Comment by scottresnik** [comment] 2021-04-21 22:33
I got bit by a similar issue to this with a single project.
Let me know if this repo is good enough: https://github.com/scottresnik/gradle-gh-12519

Thanks.

**Comment by scottresnik** [comment] 2021-04-21 23:30
> I got bit by a similar issue to this with a single project.
> Let me know if this repo is good enough: https://github.com/scottresnik/gradle-gh-12519
> 
> Thanks.

Adding `annotationProcessor platform(org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES)` to the `build.gradle` in the sample resolves the issue.

**Comment by brunopessanha** [comment] 2021-05-03 14:24
That's a nice workaround @scottresnik! Thank you for that! 😃 

However, I still feel that the `annotationProcessor` should respect what has been declared inside the `constraints` block from `java-platform`. 

I also had the same issue with Gradle 7.0 both with `annotationProcessor` and with `developmentOnly` depedencies. I basically applied the workaround above:
```kotlin
developmentOnly(platform(org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES))
```

**Comment by trixoflow** [comment] 2021-05-25 05:25
Why is this closed? Is it not a bug @melix ?

**Comment by alexanderankin** [comment] 2022-07-08 18:11
original dependencies block

```gradle
dependencies {
    api platform('org.springframework.boot:spring-boot-dependencies:2.2.4.RELEASE')
    api platform('org.springframework.cloud:spring-cloud-dependencies:Hoxton.SR1')
    constraints {
...
}
```
should become:

```gradle
dependencies {
    api platform('org.springframework.boot:spring-boot-dependencies:2.2.4.RELEASE')
    annotationProcessor platform('org.springframework.boot:spring-boot-dependencies:2.2.4.RELEASE')
    api platform('org.springframework.cloud:spring-cloud-dependencies:Hoxton.SR1')
    constraints {
...
}
```
