### ISSUE TITLE
Transitive dependency resolution non-repeatable with version ranges

### ISSUE THREAD

**Issue by rocketraman** [gradle/gradle#759] opened 2016-10-26 16:00 UTC
A third-party library uses an open-ended version range to resolve a dependency (in this case, on `jackson-databind`).

Recently, a 2.9.0-SNAPSHOT was released for `jackson-databind`, which in combination with the third-party library above, made previously working builds non-repeatable, because the same build was now pulling in a -SNAPSHOT dependency to a non-binary compatible version.

I don't believe the third-party library should be defining their transitive dependencies this way (see https://github.com/maxmind/GeoIP2-java/issues/77 for my discussion with them -- perhaps someone from the gradle team could weigh in with their thoughts). However, I think Gradle could do more in this type of situation to ensure build repeatability (I don't know what).

I also don't think this issue is limited to snapshots. Even if my build did not enable snapshots, as soon as jackson 2.9.0 was released, I would have run into the same issue.

The third-party lib POM is:

https://github.com/maxmind/MaxMind-DB-Reader-java/blob/master/pom.xml#L40

which pulls in Jackson-databind with a version range `[2.7.0,)`.
### Expected Behavior
- Builds should be repeatable
### Current Behavior
- Builds are not repeatable if a transitive dependency uses a version range that may cause different deps to be included depending on external releases
### Context
- My build was working. Then a build of the same code version stopped working, with failing tests due to binary incompatibility. Upon further investigation using the dependencyAnalysis tool, it was determined that a new non-binary compatible snapshot build was being pulled in.
### Steps to Reproduce (for bugs)

Here is a simple `build.gradle` for reproduction:

```
repositories {
  mavenCentral()
  maven {
    url "https://oss.sonatype.org/content/repositories/snapshots"
  }
}

apply plugin: 'java'

dependencies {
  compile("com.maxmind.geoip2:geoip2:2.8.0") {
    // workaround https://github.com/maxmind/GeoIP2-java/issues/77
    //exclude group: 'com.fasterxml.jackson.core'
  }
}

task wrapper(type: Wrapper) {
  gradleVersion = '3.1'
}
```
### Your Environment
- Build scan URL:  https://scans.gradle.com/s/jjq3xdqmhhd6i

**Comment by oehme** [comment] 2016-10-29 19:57
@eriwen I wouldn't classify this as a bug. Repeatable builds in the face of version ranges is a missing feature, which could e.g. be solved with a lock file or something similar.

@rocketraman For the time being, you can force the version of the transitive dependency to a stable one. You can also write some code which makes your build fail if any dynamic or changing dependencies are used. See the [ResolutionStrategy](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html) documentation for further details.

**Comment by rocketraman** [comment] 2016-10-31 17:59
> For the time being, you can force the version of the transitive dependency to a stable one.

Agreed, this is an ok solution until builds can be repeatable by handling this situation.

> You can also write some code which makes your build fail if any dynamic or changing dependencies are used. See the ResolutionStrategy documentation for further details.

This would be useful, so that the build can fail-fast when one needs to apply the workaround above. I know this is not a support forum, but can you provide an example of this? The documentation does not have one.

**Comment by oehme** [comment] 2016-10-31 18:15
You can use ResolutionStrategy.eachDependency() and inspect the version of the requested module. If it contains things like ( or + or -SNAPSHOT, you fail the build. Hope that helps :)

**Comment by eriwen** [comment] 2016-11-01 20:26
Thanks @oehme. We are aware of the need to make transitive dependencies deterministic, and I'd like to track that somewhere else than this issue. 

Given that there's a workaround here, I will close this. Please reopen @rocketraman if you desire further discussion.

**Closed by eriwen** 2016-11-01 20:26 UTC
Labels: contributed

**Comment by rocketraman** [comment] 2016-11-01 20:33
For future reference, can you provide a link to whichever issue was created to track deterministic dependencies?

**Comment by rocketraman** [comment] 2017-02-22 14:39
> For future reference, can you provide a link to whichever issue was created to track deterministic dependencies?

@eriwen Ping

**Comment by eriwen** [comment] 2017-02-22 15:58
@rocketraman I'm sorry, I wish I could, but I'm legally not allowed to under the particular open-source partnership this is a part of. Will let you know once we can announce it.

**Comment by samrocketman** [comment] 2017-03-05 20:55
^^ that seems lame and opaque.  I've not heard of such a partnership which claims to be "open source" and legally forbids transparency of viewing issues.  Seems kind of mental to me.

**Comment by oehme** [comment] 2017-03-06 08:45
> ^^ that seems lame and opaque. 

I agree that this comment was vague. In fact there is no such partnership, the comment was intended for a different issue. 

> I've not heard of such a partnership which claims to be "open source" and legally forbids transparency of viewing issues. Seems kind of mental to me.

There are partners who pay us for improving Gradle for everyone, but don't want to be named or don't want us to make a big fuss about it before it is ready. These partnerships are improving the tool that you are using for free. So your comment of such a partnership being "mental" is odd, to say the least. 

I'd appreciate if you'd drop the needlessly rude and hurtful language in the future.

> I'm still trying to figure out why my build isn't repeatable without any code changes.

GroovyDoc puts timestamps into its output by default. You can [disable](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/javadoc/Groovydoc.html#setNoTimestamp(boolean)) that.

**Comment by samrocketman** [comment] 2017-03-07 01:05
@oehme thanks for the tip on timestamps, I didn't mean to come off as rude.  I was only making an observation.  Your statement can apply to pretty much all popular freely licensed and open sourced software.  I still think it's unwise to keep an issue relating to a desired open source feature in a closed and opaque issue tracker.  It makes me not want to contribute if that's how this project operates in general (i.e. all open issues are closed in favor of a "private" issue tracker).  I encourage you as maintainers to develop and track issues more in the open.

**Comment by oehme** [comment] 2017-03-07 10:18
We didn't close this issue in favor of some internal one. We closed it because it was not a bug and because there was a workaround for the issue described. There is no ticket for the broader topic of "repeatable dynamic versions" yet, but you are very welcome to open one. We did not open one ourselves because we don't have the capacity to work on it or discuss it at this point.

That being said, there is a great [community plugin](https://github.com/nebula-plugins/gradle-dependency-lock-plugin) for dependency locking (which is one way to solve "repeatable dynamic versions").

**Comment by rocketraman** [comment] 2017-03-07 14:21
> We didn't close this issue in favor of some internal one. We closed it because it was not a bug and because there was a workaround for the issue described.

@oehme  As far as I know, no one was asking why this issue was closed. That was clear. @eriwen stated:

> I'd like to track that somewhere else than this issue.

So would we. This is what we were asking for. Now that its clear this place does not currently exist, we can move forward :-)

Thanks for the link to the community plugin also.

**Comment by rocketraman** [comment] 2017-03-07 14:47
FYI - I think this is a relevant issue for the community plugin:

https://github.com/nebula-plugins/gradle-dependency-lock-plugin/issues/78

**Comment by rocketraman** [comment] 2019-03-05 16:10
And for future Google searchers, this was eventually implemented in Gradle core: https://docs.gradle.org/current/userguide/dependency_locking.html.
