### ISSUE TITLE
Increased memory usage (with -p option)

### ISSUE THREAD

**Issue by tomasAlabes** [gradle/gradle#22688] opened 2022-11-11 14:40 UTC
### Expected Behavior
We should be able to build a project in the multimodule project by specifying the `-p <project>` option.

### Current Behavior

~**This isn't reproducible with Gradle 7.5.1, only with 7.6**~:
Using [gradle's sample project](https://docs.gradle.org/current/samples/sample_structuring_software_projects.html) and updating gradle with:

```shell
./gradlew wrapper --gradle-version=7.6-rc-2
```

```shell
./gradlew -p server-application/ build
> Task :build-logic:commons:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':build-logic:commons:compileKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Could not isolate value org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkParameters_Decorated@fa8c669 of type GradleCompilerRunnerWithWorkers.GradleKotlinCompilerWorkParameters
      > Java heap space

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.6-rc-2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 4s
6 actionable tasks: 6 executed

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':build-logic:commons:compileKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Could not isolate value org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkParameters_Decorated@fa8c669 of type GradleCompilerRunnerWithWorkers.GradleKotlinCompilerWorkParameters
      > Java heap space

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Java heap space

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.6-rc-2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 4s

FAILURE: Build failed with an exception.

* What went wrong:
Could not receive a message from the daemon.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

### Context

In my own project, I can't do this either. I stopped all Gradle daemons, but it didn't help. I created a similar bug for 7.6, maybe it is related: https://github.com/gradle/gradle/issues/21708

### Steps to Reproduce 

Download gradle's sample project: https://docs.gradle.org/current/samples/zips/sample_structuring_software_projects-kotlin-dsl.zip
And run `./gradlew wrapper --gradle-version=7.6-rc-2 && ./gradlew -p server-application/ build`

### Your Environment

Gradle: 7.6-rc2
Kotlin: 1.6.21 / 1.7.10
OS: MacOS Monterey 12.5 (M1 Pro)

**Comment by jbartok** [comment] 2022-11-14 09:35
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

You can use the following as a base for your reproducer: https://github.com/gradle/gradle-issue-reproducer

This issue will be closed after 7 days, unless you can provide more information.

*** 

The current steps to reproduce don't reproduce it for us and it seems more like a memory setting problem, so pls. check those.

**Comment by tomasAlabes** [comment] 2022-11-15 16:07
Indeed I tried it on another machine and it worked. Will re-open it if I can reproduce it again with the template.
Thanks!

**Comment by tomasAlabes** [comment] 2022-11-15 17:04
Sorry, actually I tested it in the wrong branch. I'm still able to reproduce it in my project, and only on 7.6 (7.5.1 runs perfectly). It might be a problem with big multi-project modules (~80 subprojects). Do you have one to test it on? I can't share my project, and the reproducer isn't big enough. This is a blocker for us.

- I increased the java heap space from 4g to 6g, but didn't work, it might signal a problem on memory management.
- I use the `-p myProject/ --parallel` options
- Not reproducible with colon notation `:myProject:build --parallel`

I can share the pictures of the heap dump on error, to see if it helps:

<img width="645" alt="Screenshot 2022-11-15 at 17 34 46" src="https://user-images.githubusercontent.com/699432/201975732-6dfc9d96-2514-4bce-81a2-dc2aeaed431d.png">
<img width="643" alt="Screenshot 2022-11-15 at 17 34 52" src="https://user-images.githubusercontent.com/699432/201975742-99428976-6cb9-4ef8-9d69-518ff3eae2f4.png">

<img width="887" alt="Screenshot 2022-11-15 at 17 36 01" src="https://user-images.githubusercontent.com/699432/201975647-f4c5c3d6-f636-4ddc-aa58-41749d8d28aa.png">
<img width="892" alt="Screenshot 2022-11-15 at 17 35 25" src="https://user-images.githubusercontent.com/699432/201975652-620caabe-b570-4a1f-9235-422581238853.png">

**Comment by tomasAlabes** [comment] 2022-11-15 17:23
Ok, I was able to reproduce it with 7.5.1. The regression label can be taken off. I'll leave it open in case the screenshots help to figure out the problem.

**Comment by ljacomet** [comment] 2022-11-17 08:22
I renamed the issue to remove the link with 7.6 RCs

**Comment by xaviarias** [comment] 2022-11-21 09:56
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team but the existence of a workaround makes it non-critical so it might take a while before a fix is made.

---
Workaround is to increase the memory given to Gradle.

**Comment by tomasAlabes** [comment] 2022-11-21 13:37
In my project I increased it from 4g to 8g, and it wasn't enough.

**Comment by eskatos** [comment] 2022-11-25 09:00
Thank you for the provided information.
Unfortunately we're still not able to reproduce.
In order to make it actionable for us you would need to provide a reproducer build.

Another thing to try would be to use this Gradle version which contains an attempt at reducing memory usage:
```
gradle wrapper --gradle-version=7.6-branch-sg_76_memory_tweak-20221122202632+0000
````

**Comment by tomasAlabes** [comment] 2022-11-25 12:33
Thanks for trying @eskatos. I tried again with that build and I reproduced it again. I'm attaching some reports: 
[java_pid3371_Leak_Suspects.zip](https://github.com/gradle/gradle/files/10092719/java_pid3371_Leak_Suspects.zip)
[java_pid3371_Top_Components.zip](https://github.com/gradle/gradle/files/10092773/java_pid3371_Top_Components.zip)
[java_pid3371_Top_Consumers.zip](https://github.com/gradle/gradle/files/10092774/java_pid3371_Top_Consumers.zip)

To see if I can help with these details:

- It's a big multi-modules project with around ~80 subprojects, and includedBuilds
- Mixes Java and Kotlin
- It's based on the [gradle's sample project](https://docs.gradle.org/current/samples/sample_structuring_software_projects.html), so we generate plugins to reuse configurations
- It's using Version Catalogs

**Comment by eskatos** [comment] 2022-11-25 13:36
Thanks @tomasAlabes. Still hard to reproduce with just the above instructions. Please provide a complete reproducer

**Comment by tomasAlabes** [comment] 2022-12-06 20:04
I don't think I will be able to give you the reproducer, it's a pretty big project. If you don't have one in your suite, then you can close this or leave it open in case someone can. I will have to go back to the colon syntax to make it work. Although it's annoying because the commands become larger

```shell
./gradlew -p myProject/ clean build -x test -x check
# vs
./gradlew :myProject:clean :myProject:build -x :myProject:test -x :myProject:check
```

**Comment by AlanMasciangelo** [comment] 2023-01-11 18:40
I'm seeing similar symptoms with a large multiproject build after upgrading from 7.5.1 to 7.6.

Attaching a profiling shows a huge increase in instances of `org.gradle.internal.component.external.model.ConfigurationBoundExternalDependencyMetadata` which only accounts for <1% of heap at any time in previous versions

![image](https://user-images.githubusercontent.com/5660390/211889781-ede5a358-59fa-4da2-9f5e-c3c6fd660ba6.png)

**Comment by mikethecalamity** [comment] 2023-01-15 18:44
I am also seeing this in very large multiproject builds (~50 subprojects). In `7.4.2`, things work ok. In `7.5.1`, it gets a bit worse, had to bump up Gradle's memory. But then in `7.6`, it really hits the fan, the build need over 12gb of memory to run, which seems insane.

**Comment by ParanoidUser** [comment] 2023-01-17 02:22
Came here to say the same thing as @mikethecalamity pointed out. In my case, it hits the OOM through the Gradle plugin for IntelliJ. If any changes are made to the project the IDE asks to reload the project to rebuild the structure. With the extended JVM args in `gradle.properties`:
> org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError

it used to work on Gradle 7.4.2 / 7.5.1, but crashes constanly on Gradle 7.6.0. 

```
> Task :prepareKotlinBuildScriptModel UP-TO-DATE

FAILURE: Build failed with an exception.

* What went wrong:
Java heap space

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 53s
```

**Note:** stretching out the heap size to 3GB helps to bring it back to work. But, it would be nice to have constant memory utilization across the builds.

**Comment by big-guy** [comment] 2023-01-18 01:12
Could some of the reporters here try `7.6.1-branch-sg_761_reduce_memory_consumption-20230118002823+0000`? This is a nightly build based off a branch. If this looks better, I'll get it merged for 7.6.1

**Comment by ParanoidUser** [comment] 2023-01-18 20:53
@big-guy, thank you for looking at this! In my tests, the night build looks very promising. Here is a quick summary of the durations it took to rebuild the structure:

| Build                            |      -Xmx2g |      -Xmx3g |
|-------------------------|--------------|-------------|
| 7.6.1-reduce_memory | ✔ 1m 59s | ✔ 1m 28s |
| 7.6.0                            | ❌ OOM    | ✔ 1m 47s |
| 7.5.1                            | ✔ 1m 41s | ✔ 1m 17s |

**Comment by big-guy** [comment] 2023-01-23 04:48
@AlanMasciangelo @mikethecalamity @tomasAlabes Could you give `7.6.1-branch-sg_761_reduce_memory_consumption_2-20230123043022+0000` a try? This has the previous changes plus a few more.

**Comment by ParanoidUser** [comment] 2023-02-14 03:01
@big-guy, do you know if these memory optimizations made it into 8.0?

**Closed** 2023-02-17 17:47 UTC
Labels: a:bug, a:regression, has:workaround, in:memory-usage

**Comment by mikethecalamity** [comment] 2023-05-15 06:26
@big-guy @ljacomet I tried running with `8.1.1` recently, it's definitely significantly better but there are still some cases that fail compared to `7.5.1`.

In the example below, we have 85 total projects and 36 of those are Quarkus services using `-Xmx4g`. The first was run as `gradlew -p projects build` (building everything) and the second is `gradlew -p projects quarkusBuild` (only building the services).

<html>
<body>


Build | build | quarkusBuild
-- | -- | --
8.1.1 | ❌ OOM  | ✔ 10:03
7.6.0 | ❌ OOM | ❌ OOM 
7.5.1 | ✔ 37:25  | ✔ 10:17


</body>
</html>

You'll note that even in `8.1.1` the full build still fails, even though it succeeds in `7.5.1` with `4GB` of memory.

**Comment by ljacomet** [comment] 2023-05-15 08:06
@mikethecalamity Could you try 8.2-milestone-1?

There are further improvements in there.

**Comment by mikethecalamity** [comment] 2023-05-15 17:55
@ljacomet It worked with `8.2-milestone-1` and it was faster!
