### ISSUE TITLE
Tutorial contains Groovy instructions for Kotlin files. 

### ISSUE THREAD

**Issue by jacksonbrim** [gradle/gradle#26962] opened 2023-11-07 05:04 UTC
### Issue type

Wrong or misleading information

### Problem description

Incorrect instructions for the build.gradle.kts section in the gradle tutorial. 

[part4 gradle plugins](https://docs.gradle.org/current/userguide/part4_gradle_plugins.html#part4_begin)

The error is at the following section:
Step 3. Configuring the Plugin
Add the publishing information to your build.gradle.kts file:
```
publishing {
    publications {
        mavenJava(MavenPublication)("maven") {
            groupId = "org.gradle.tutorial"
            artifactId = "tutorial"
            version = "1.0"

            from(components["java"])
        }
    }
}
```
./gradlew :app:tasks yields an error:

FAILURE: Build failed with an exception.

* Where:
Build file '/home/tutorial/app/build.gradle.kts' line: 48

* What went wrong:
Script compilation errors:

There is an identical tutorial elsewhere confirming this to be a Groovy example rather than a Kotlin example.
[Publishing Maven](https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven)

The correct build.gradle.kts:
```
publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = "org.gradle.tutorial"
            artifactId = "tutorial"
            version = "1.0"

            from(components["java"])
        }
    }
}
```

This compiles successfully.

### Context (optional)

I was trying to go through the tutorial and there was an error at the  publish plugins part. 

It seems that the instructions for the build.gradle.kts file are in Groovy instead of Kotlin. 

Fortunately, there were almost identical instructions at the following link confirming this to be the case:

https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven

### Page with the problem

https://docs.gradle.org/current/userguide/part4_gradle_plugins.html#part4_begin

**Comment by cobexer** [comment] 2023-11-07 13:18
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #26861

***
This will be fixed in 8.5

**Closed by cobexer** 2023-11-07 13:18 UTC
Labels: a:documentation, to-triage
