### ISSUE TITLE
The Callable of a Provider get called multiple times when set to an Property in a Task

### ISSUE THREAD

**Issue by StefMa** [gradle/gradle#6787] opened 2018-09-17 14:01 UTC
When a custom implementation of a `DefaultTask` have a `Property` and I set this via `set(project.provider {})` the callable from the `Provider` will be called multiple times before the `Task` use it.

### Expected Behavior
The Callable should only be called *once* when I call `get()`.

### Current Behavior
The `Callable` will be called exactly three times before I call `get()`. Or even without calling `get()` anytime.

### Context
I want to create a Task with a lazily `Property` because they value may be not used in the `Task`. So there is no need to set the `String` (the Property-value) directly. 
The Property `Callable` should only be called once because it may create a heavy calculation.

### Steps to Reproduce (for bugs)
This is my CustomTask:
```groovy
class FastTask extends DefaultTask {

    @Input
    Property<String> someInput = project.objects.property(String)

    @Input
    def anotherInput = "AnotherInput"

    @OutputFile
    File output =
            project.file("${project.buildDir}/output.txt").with { file ->
                parentFile.mkdirs()
                createNewFile()
                file
            }

    @TaskAction
    void action() {
        if (anotherInput != "AnotherInput") {
            println("Hey")
            def input = someInput.get()
            output.write(input)
            println("Wrote '$input' to ${output.absolutePath}")
        }
    }

}
```
And this is how I create it:
```groovy
tasks.register("fastTask", FastTask) {
    anotherInput = "NotAnotherInput"
    someInput.set(project.provider({
        println("stuff")
        return "Input"
    }))
}
```

When I execute this `Task` the output is:
```
$ gradle fastTask

> Task :fastTask
stuff
stuff
stuff
Hey
stuff
Wrote 'Input' to /Users/stefan/Desktop/osgi/build/output.txt

BUILD SUCCESSFUL in 0s
```

The first three "stuff" shouldn't be there.

**Comment by StefMa** [comment] 2018-09-17 14:29
For testing purpuse I've taken the `greeting` sample from the [documentation](https://docs.gradle.org/4.10.1/userguide/lazy_configuration.html#sec:lazy_configuration_faqs) and changed the message to:
```
message = provider { println("Stuff"); "Hi" }
```
This will have the same output:
```
$ ./gradlew greeting

> Task :greeting
Stuff
Stuff
Stuff
Hi from Gradle

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
```

See also the attachment example:
[stuff.zip](https://github.com/gradle/gradle/files/2388932/stuff.zip)

**Comment by thc202** [comment] 2018-09-17 14:32
I guess that's because of up-to-date checks, at the very least it would have to call it twice not just once?

**Comment by StefMa** [comment] 2018-09-17 14:52
Yep, you are right.
When I remove the `@Input` annotation from the `Property` it print it only once.
So according to the @Input documentation and the [Authoring Task doc](https://docs.gradle.org/4.10.1/userguide/more_about_tasks.html) an Property can't be an an **Input** value. But then the [Lazy Configuration doc](https://docs.gradle.org/4.10.1/userguide/lazy_configuration.html) is wrong.

Would be good if one of the Gradle members can bring some light in here 🙃

**Comment by adammurdoch** [comment] 2018-09-17 23:33
Thanks for the reproduction steps, this is very useful.

`Property` can be used with `@Input`, the "authoring tasks" chapter is not up-to-date yet. I've added https://github.com/gradle/gradle/issues/6792 for this.

The closure is called several times because the value of the input property is used a few times during task execution: once to validate the value, once to snapshot the value for incremental builds and caching and once when the task action runs and calls `get()`. The plan is to improve the `Property` implementations so that the closure is called only once at the start of task execution and the value that it returns is reused for each of these things.

**Comment by StefMa** [comment] 2018-09-18 06:46
Thanks for the information.
Yeah, calling the `Callable` multiple times makes for the `Provider` no sense.
The value is read only and can be "cached" after the first time it was called.
On the other hand a `Property` needs to call it again - if its know that `set` was called meanwhile. Otherwise it could also just return the already emitted value...

**Comment by adammurdoch** [comment] 2018-10-14 21:10
This is fixed via https://github.com/gradle/gradle/pull/7371.

**Closed by adammurdoch** 2018-10-14 21:10 UTC
Labels: dogfood:provider-api

**Comment by grv87** [comment] 2018-11-11 18:52
[Current documentation](https://docs.gradle.org/4.10.2/javadoc/org/gradle/api/provider/Provider.html) says:
> A provider may not always provide the same value. Although there are no methods on this interface to change the value, the provider implementation may be mutable or use values from some changing source.

It makes sense to call `Callable` as much needed.

Also, isn't this related to #5301?

**Comment by adammurdoch** [comment] 2018-11-12 23:30
The `Callable` is still called each time the task property value is queried, as we don't know what kind of calculation it represents and what inputs it might have. What has changed is that when a task starts to execute, the values of all of its properties are finalized. From this point on, the property value is fixed and the `Callable` is no longer queried when the task property is queried.

Over time, the plan is add better ways to declare what the calculation represents, so that we know whether the value may have changed since last time it was calculated, and also to gradually move all queries so that they happen after the value is finalized.
