### ISSUE TITLE
Dependency resolving fails the whole build on 503 from repository server

### ISSUE THREAD

**Issue by frankbregulla1111** [gradle/gradle#12108] opened 2020-02-03 15:48 UTC
### Expected Behavior
If dependency resolving fails towards one of the configured repositories with *any* HTTP status code !=200, I would expect that Gradle resolves the dependency from other repositories in the build configuration.

### Current Behavior
When Gradle gets a 503 response code from my Nexus behind a proxy, it simply fails the whole build without trying to request the other configured repositories.
Interestingly the fallback works as expected when I pull out my network cable: In that case, of course, resolving the dependency from my Nexus fails as well, but all other repositories are requested, too.

### Context
I want my build to succeed even when my Nexus is not available.

### Steps to Reproduce

1. Add a custom Nexus server to the repositories section. After that, add another repository like mavenCentral().
2. Let the custom Nexus return a 503 status code on any request.
3. Run the build: The whole build will fail without trying to request mavenCentral() after the failing Nexus server.

```
/o/my-project ❯❯❯ ./gradlew build
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve com.nimbusds:lang-tag:[1.4.3,).
     Required by:
         project : > org.springframework.security:spring-security-oauth2-client:5.2.0.RELEASE > com.nimbusds:oauth2-oidc-sdk:6.14
      > Skipped due to earlier error
      > Failed to list versions for com.nimbusds:lang-tag.
         > Unable to load Maven meta-data from https://nexus.example.com/repository/jcenter/com/nimbusds/lang-tag/maven-metadata.xml.
            > Could not HEAD 'https://nexus.example.com/repository/jcenter/com/nimbusds/lang-tag/maven-metadata.xml'. Received status code 503 from server: Service Unavailable: Back-end server is at capacity
```

When I disable all network connectivity on my computer, the output will change to this, as expected:

```
~/o/my-project ❯❯❯ ./gradlew build
> Task :compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve com.nimbusds:lang-tag:[1.4.3,).
     Required by:
         project : > org.springframework.security:spring-security-oauth2-client:5.2.0.RELEASE > com.nimbusds:oauth2-oidc-sdk:6.14
      > Failed to list versions for com.nimbusds:lang-tag.
         > Unable to load Maven meta-data from https://nexus.example.com/repository/maven-central/com/nimbusds/lang-tag/maven-metadata.xml.
            > Could not HEAD 'https://nexus.example.com/repository/maven-central/com/nimbusds/lang-tag/maven-metadata.xml'.
               > nexus.example.com
      > Failed to list versions for com.nimbusds:lang-tag.
         > Unable to load Maven meta-data from https://repo.maven.apache.org/maven2/com/nimbusds/lang-tag/maven-metadata.xml.
            > Could not HEAD 'https://repo.maven.apache.org/maven2/com/nimbusds/lang-tag/maven-metadata.xml'.
               > repo.maven.apache.org
```

### Your Environment
Tested with gradle 5.6.4

Repositories section is as follows:

```
    repositories {
        maven {
            url "https://nexus.example.com/repository/maven-central/"
        }
        mavenCentral()
    }
```

**Comment by ljacomet** [comment] 2020-02-03 16:01
All of this is by design and can be explained by the following:
* Failing a build once a repository cannot be reached is done for the sake of reproducibility. If that was not the case, you and your colleague could end up with different results for your build, just because some repositories were not available.
* When you pull your network cable, the first request that Gradle makes is for a _dynamic_ version. In that case, Gradle will look at _all_ repositories to attempt to find the best matching version. But even in that case, the build would have failed after trying them all since one of them could not return any valid information and caching a resolved version from a subset of repositories also breaks reproducibility.

**Comment by ljacomet** [comment] 2020-02-08 14:09
Closing this as there is no plan to change the behavior there.

**Closed by ljacomet** 2020-02-08 14:09 UTC
Labels: a:bug, from:contributor, in:dependency-management
