### ISSUE TITLE
TestKit does not pass environment variables for older Gradle versions when running on M1 mac

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#22012] opened 2022-09-14 20:18 UTC
When executing a build using Gradle TestKit, the `withEnvironment()` method can be used to set environment variables for the target build. On an M1 mac, the environment is only correctly setup when targeting a Gradle version >= 6.9. (These are also the versions that have native support for Mac `aarch64`).

On another operating system (non-M1 mac), the environment is correctly set up for all target versions of Gradle >= 3.5.

### Expected Behavior
TestKit `withEnvironment()` will set environment variables when targeting all supported Gradle versions.

### Current Behavior
TestKit `withEnvironment()` does not set environment variables when targeting Gradle < 6.9 on M1 macs.

### Steps to Reproduce 
Clone this repository and follow the simple instructions in the README: https://github.com/bigdaz/test-kit-env-var

Successful run on Intel Mac: https://ge.solutions-team.gradle.com/s/iv5rbzfxausbi/tests/overview
Failing run on M1 Mac: https://ge.solutions-team.gradle.com/s/vmjwxo7dv3kle/tests/overview

**Comment by bigdaz** [comment] 2022-09-19 14:11
After the initial report I did some further digging, and I'm not sure if there's an easy fix for this. I suspect that the underlying issue comes down to lack of "native integration" support on M1 Macs for Gradle < 6.9.

When this issue occurs, we see an error like this in the daemon log: 
```
Warning: Unable able to set daemon's environment variables to match the client because:
There is no native integration with this operating environment.
If the daemon was started with a significantly different environment from the client, and your build 
relies on environment variables, you may experience unexpected behavior.
```

Which is emitted [from here](https://github.com/gradle/gradle/blob/1084061fe07a8f880ee383945d41b48ebb81721c/subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/exec/EstablishBuildEnvironment.java#L68-L77).

**Comment by ljacomet** [comment] 2022-09-19 14:34
Confirmed that the issue is not in how the test kit run is setup but how the older Gradle version and its daemon can process the request.
M1 architecture support would need to be backported, which is unlikely to happen at this stage.

Closing as "Won't fix"

**Closed by ljacomet** 2022-09-19 14:34 UTC
Labels: a:bug, in:test-kit, affects-version:5.1, affects-version:5.0, affects-version:5.2, affects-version:5.3, affects-version:5.4, affects-version:5.6, affects-version:5.5, affects-version:6.0, affects-version:6.1, closed:not-fixed, affects-version:6.2, affects-version:6.3, affects-version:6.4, affects-version:6.5, affects-version:6.6, affects-version:6.7, affects-version:6.8.3

**Comment by big-guy** [comment] 2022-09-19 23:20
Does this work when running tests through Rosetta2 on < 6.9?

**Comment by clayburn** [comment] 2022-09-20 13:11
It does pass with Rosetta2: https://ge.solutions-team.gradle.com/s/gxltyqezcvoo2/tests/overview
