### ISSUE TITLE
dependsOn doesn't trigger the task when used in afterEvaluate and withType

### ISSUE THREAD

**Issue by purpleP** [gradle/gradle#14105] opened 2020-08-12 07:16 UTC
gradle 5.6.4

I'm writing gradle plugin which is doing the task similar to protobuf - generate sources from other type of files (it's proprietary). In pseudocode it looks like this.

I have two types of tasks one for code generation which depends on the presence of a binary dependency. One for unzipping this binary dependency with symlinks. I've tried to link them with dependsOn, but I don't unzip isn't' executed. I can't share full source code, but maybe I'm doing something obviously wrong or you could point me to examples how to do something similar to this?

```
class CustomUnzipTask : AbstractCopyTask {
}

class Plugin : Plugin<Project> {
    dependencies.add("some:binary:dependencies")
    dependencies.add("some:binary:dependencies")
    afterEvaluate {
        val unzipTasks = conf.dependencies.map {
            tasks.register("unzip_$it.name", CustomUnzipTask::class.java) {
            }
        }
        tasks.withType(GenerateTask::class.java).configureEach {
             dependsOn(*unzipTasks)
        }
    }
}

class GenerateTask {
}
```
Is that a bug or it supposed to be this way? Also even if it's normal it should raise error.

**Comment by hegyibalint** [comment] 2022-03-02 10:44
Could not reproduce under Gradle 7.4.
I know that this issue by far not fresh, but feel free to comment.
For the time being, I will close this.

## Plugin
From the pseudocode, I've created this plugin, which should mimic the description:
```java
public class TestPlugin implements Plugin<Project> {

    private void configureAfterEvaluate(Project project) {
        System.out.println("After test evaluate");

        final List<TaskProvider<TransformTask>> tasks = project
                .getConfigurations()
                .getByName("runtimeClasspath")
                .getFiles()
                .stream()
                .map(dep -> {
                    final String name = String.format("transform-%s", dep.getName());
                    System.out.println(name);

                    return project.getTasks().register(
                            name,
                            TransformTask.class
                    );
                })
                .collect(Collectors.toList());

        System.out.println(tasks.size());

        project.getTasks().withType(GenerationTask.class).configureEach(task -> {
            task.dependsOn(tasks);
        });
    }

    @Override
    public void apply(Project project) {
        project.afterEvaluate(this::configureAfterEvaluate);
    }

}
```

## Tasks
Tasks are just default tasks, just printing either "Generating" or "Transforming".
E.g. the test task is:
```java
public class TransformTask extends DefaultTask {

    @TaskAction
    public void doSomething() {
        System.out.println("Transforming");
    }

}
```

## Build file
```kotlin
plugins {
    `java-library`
    id("org.gradle.test.plugin")
}

repositories {
    mavenCentral()
}

dependencies {
    // Bit arbitrary dependencies, but needed something non-trivial
    implementation("org.asciidoctor:asciidoctorj:2.5.2")
    implementation("org.asciidoctor:asciidoctorj-pdf:1.6.0")
}

tasks {
    val generationTask by registering(org.gradle.test.GenerationTask::class)
}
```

## Output
```
11:35:22 AM: Executing 'generationTask'...

Configuration cache is an incubating feature.
Calculating task graph as configuration cache cannot be reused because an input to task ':build-logic:compileJava' has changed.
> Task :build-logic:compileJava UP-TO-DATE
> Task :build-logic:pluginDescriptors UP-TO-DATE
> Task :build-logic:processResources UP-TO-DATE
> Task :build-logic:classes UP-TO-DATE
> Task :build-logic:jar UP-TO-DATE

> Configure project :gradle-kotlin-project
After test evaluate
transform-asciidoctorj-2.5.2.jar
transform-asciidoctorj-pdf-1.6.0.jar
transform-jcommander-1.72.jar
transform-asciidoctorj-api-2.5.2.jar
transform-jruby-9.2.17.0.jar
transform-jruby-core-9.2.17.0.jar
transform-jruby-stdlib-9.2.17.0.jar
transform-jnr-netdb-1.2.0.jar
transform-jnr-unixsocket-0.38.5.jar
transform-jnr-enxio-0.32.3.jar
transform-jnr-posix-3.1.4.jar
transform-jnr-constants-0.10.1.jar
transform-jffi-1.3.1.jar
transform-jffi-1.3.1-native.jar
transform-joni-2.1.31.jar
transform-jcodings-1.0.46.jar
transform-dirgra-0.3.jar
transform-invokebinder-1.11.jar
transform-options-1.4.jar
transform-jzlib-1.1.3.jar
transform-nailgun-server-0.9.1.jar
transform-joda-time-2.10.5.jar
transform-backport9-1.8.jar
transform-javax.annotation-api-1.3.1.jar
24

> Task :gradle-kotlin-project:transform-asciidoctorj-2.5.2.jar
Transforming

> Task :gradle-kotlin-project:transform-asciidoctorj-api-2.5.2.jar
Transforming

> Task :gradle-kotlin-project:transform-asciidoctorj-pdf-1.6.0.jar
Transforming

> Task :gradle-kotlin-project:transform-backport9-1.8.jar
Transforming

> Task :gradle-kotlin-project:transform-dirgra-0.3.jar
Transforming

> Task :gradle-kotlin-project:transform-invokebinder-1.11.jar
Transforming

> Task :gradle-kotlin-project:transform-javax.annotation-api-1.3.1.jar
Transforming

> Task :gradle-kotlin-project:transform-jcodings-1.0.46.jar
Transforming

> Task :gradle-kotlin-project:transform-jcommander-1.72.jar
Transforming

> Task :gradle-kotlin-project:transform-jffi-1.3.1-native.jar
Transforming

> Task :gradle-kotlin-project:transform-jffi-1.3.1.jar
Transforming

> Task :gradle-kotlin-project:transform-jnr-constants-0.10.1.jar
Transforming

> Task :gradle-kotlin-project:transform-jnr-enxio-0.32.3.jar
Transforming

> Task :gradle-kotlin-project:transform-jnr-netdb-1.2.0.jar
Transforming

> Task :gradle-kotlin-project:transform-jnr-posix-3.1.4.jar
Transforming

> Task :gradle-kotlin-project:transform-jnr-unixsocket-0.38.5.jar
Transforming

> Task :gradle-kotlin-project:transform-joda-time-2.10.5.jar
Transforming

> Task :gradle-kotlin-project:transform-joni-2.1.31.jar
Transforming

> Task :gradle-kotlin-project:transform-jruby-9.2.17.0.jar
Transforming

> Task :gradle-kotlin-project:transform-jruby-core-9.2.17.0.jar
Transforming

> Task :gradle-kotlin-project:transform-jruby-stdlib-9.2.17.0.jar
Transforming

> Task :gradle-kotlin-project:transform-jzlib-1.1.3.jar
Transforming

> Task :gradle-kotlin-project:transform-nailgun-server-0.9.1.jar
Transforming

> Task :gradle-kotlin-project:transform-options-1.4.jar
Transforming

> Task :gradle-kotlin-project:generationTask
Generating

BUILD SUCCESSFUL in 199ms
29 actionable tasks: 25 executed, 4 up-to-date
Configuration cache entry stored.
11:35:22 AM: Execution finished 'generationTask'.
```

**Closed by hegyibalint** 2022-03-02 10:44 UTC
Labels: a:bug, in:writing-tasks, @support
