### ISSUE TITLE
Unexpected task invalidation when using `--scan` flag

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#15290] opened 2020-11-23 23:01 UTC
### Expected Behavior

The `--scan` flag nicely hides the boilerplate for using build scan, and it should also be hidden from the build classpath snapshot. Using the `--scan` flag should not cause the build classpath to be invalidated, causing each task added by plugins to be out of date.

### Current Behavior

Using the `--scan` flag changes the build classpath as the enterprise JAR is added, and the plugin is applied. This change causes every single task from plugins to be invalidated and executed again.

### Context

Every external plugin is affected by this.

### Your Environment

Build scan URL: https://scans.gradle.com/s/stupfancgrpnc/timeline?details=7jvlcnnrb7svy&hideTimeline (external plugin) vs https://scans.gradle.com/s/bs5xpislxvpnw/timeline?details=itlazqtrs3zqi (core plugin)
  - In both cases, the daemon was warmed by executing `clean assemble` twice. On the third `clean assemble` invocation, only the flag `--scan` was added. We can see that for a core plugin, the incremental compilation kicks in. For the external plugin, the classpath changes, which force a full recompile.

**Comment by ldaley** [comment] 2020-11-27 06:02
Thanks @lacasseio.

Closing as a duplicate of https://github.com/gradle/gradle/issues/8161.

**Closed by ldaley** 2020-11-27 06:02 UTC
Labels: a:bug, closed:duplicate, from:contributor
