### ISSUE TITLE
Allow a shared build service to be held alive until the end of the build

### ISSUE THREAD

**Issue by ThadHouse** [gradle/gradle#22837] opened 2022-11-23 17:22 UTC
Based on some comments in https://github.com/gradle/gradle/issues/20151 one of the recommendations to work around the removal was to use a shared build service. This is a great replacement in some cases, however sometimes it can be invasive to add the build service dependency to a bunch of tasks (You could probably use either the task graph completed callback, or just tasks.all). However, it'd be really nice if there was an easy way to mark a build service so that it should stay alive until the end of the build. Then you could just set that flag, and you'd now have a guaranteed marker for the end of the build. That would solve a few issues in that thread fairly easily.

**Comment by eskatos** [comment] 2022-11-30 09:40
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/20151

**Closed by eskatos** 2022-11-30 09:40 UTC
Labels: a:feature, to-triage
