### ISSUE TITLE
Inconsistent name in TOML vs API. [libraries] versus findDependencies

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#18097] opened 2021-08-20 22:55 UTC
The names of the items in the TOML file all match the `VersionsCatalog.find*` functions except one, which is `[libraries]` versus `findDependencies`. 

`[versions]` -> `VersionCatalog::findVersion`
`[bundles]` -> `VersionCatalog::findBundle`
`[plugins]` -> `VersionCatalog::findPlugin`

but this doesn't match: 

`[libraries]` -> `VersionCatalog::findDependency`

Is it not a dependency until it is added to a configuration in a `dependencies {}` block, until then it is just a library in a catalog. :) 

I propose renaming it to match: 

`[libraries]` -> `VersionCatalog::findLibrary`

**Comment by octylFractal** [comment] 2021-11-01 22:07
I have an alternative proposal, what if we renamed the TOML entry to `dependencies` instead? The term "libraries" is even technically incorrect here, you can define a dependency on anything in a repository, and that's not limited to just libraries, some plugins and applications are published there. I think changing the TOML key would make more sense, and it would also solve the inconsistency.

**Comment by yogurtearl** [comment] 2021-11-01 23:22
>  what if we renamed the TOML entry to `dependencies` instead?

Yeah, that probably does make more sense.

**Comment by melix** [comment] 2021-11-02 08:04
It's not a `dependency` either in the TOML file: it's a _library_ definition: it's a model which helps building a library. It's even more obvious if you realize that the model actually has references to versions. A dependency is a reified view of a library, so it's a different beast: it's once the catalog is built that you get this. I am strongly against any rename in this area since renames were _already_ made to make this more consistent with the model.

**Comment by octylFractal** [comment] 2021-11-10 17:33
Should we rename `[plugins]` to `[pluginLibraries]` then? And `VersionCatalog::findPluginDependency`? It _also_ uses this same mechanism where you can have references to versions, but it does not have this odd split. I don't think that the minor difference of having a "reference" is important enough to warrant this inconsistency (speaking of, do you have an issue/PR/commit where this was previously discussed? maybe I'm missing something brought up previously.).

**Comment by melix** [comment] 2021-11-11 11:04
There were quite a few discussions, I tried to summarize all of them here: https://gradle.cloud.xwiki.com/xwiki/bin/view/Main/Design%20specs/Dependency%20management/Version%20catalog/ (see 2 pages below).

The TOML file is a compromise between verbosity `e.g `[pluginLibraries]` and semantics. I am honestly not convinced than any rename is worth the effort at this stage. Of course you can say that I'm biased and I'm ready to accept this, but given that the API is out in the wild, I would be annoyed by breaking changes: as a plugin author it makes it painful to support multiple Gradle versions. This goes off topic into the "incubating" vs "stable" API discussion of course...

**Comment by ljacomet** [comment] 2021-11-16 17:37
Interestingly enough, the spec still says `dependencies`.
This got changed through #15328 and now that I look, I do not see the relationship between renaming the file - which was the right thing ™️  - and renaming that block in the TOML.

Thinking some more about it, I would advocate for:
* renaming `libraries` to `dependencies` in TOML. This will align the names, preserving the semantic of what is retrieved in the build. This alignment will help feature understandability. We could still allow Gradle to parse the old style but warn about it.
* Moving generated dependencies accessors under a `deps` top level, which would reduce even more naming conflicts and make future evolution easier if needed. I understand this is a breaking change, but that's our last chance for that. Again, we could actually generate both for a while with a deprecation warning on the old style.
* Modify the settings API so that you declare `dependencyAlias` and `pluginAlias` to be explicit from the start about what you define. This again could be done with deprecation / addition.

**Comment by melix** [comment] 2021-11-16 21:52
> renaming libraries to dependencies in TOML. This will align the names, preserving the semantic of what is retrieved in the build. This alignment will help feature understandability. We could still allow Gradle to parse the old style but warn about it.

I must say I don't really understand why we would need changes. We moved from `dependencies` to `libraries` precisely because `dependencies` is _not_ the right thing. I don't think it helps to reintroduce the confusion.

> Moving generated dependencies accessors under a deps top level, which would reduce even more naming conflicts and make future evolution easier if needed.

We actually considered it during the design and I agree from the evolution standpoint, however I think it would be a big regression in usability. Most of the use cases are only about libraries. Consider that you'd have to write `libs.deps.` as a prefix for every single dependency. IMHO, this is not worth the change.

> Modify the settings API so that you declare dependencyAlias and pluginAlias to be explicit from the start about what you define. This again could be done with deprecation / addition.

It's a _library_ alias, not a _dependency_ alias.

**Comment by octylFractal** [comment] 2021-11-18 16:51
> I'm creating a dependency on the library Micronaut Core. I'm not creating a dependency on the dependency Micronaut Core.

I would argue that you _are_ creating a dependency on a dependency here. Either that, or we need a more generic term like "dependency", as "library" simply does not work in things like:
```
annotationProcessor libs.dagger
```
Dagger _isn't a library_, it feels weird to call it such. It is an application or annotation processor. Similarly, there are things like Checkstyle which are also not libraries.

>  I don't think Gradle has to break APIs, it can support both, even if they are incubating.

Was that not implied by "This again could be done with deprecation / addition."? If not, I don't understand what you mean. If changed, we would deprecate through possibly 8.0.

**Comment by melix** [comment] 2021-11-18 17:34
> I would argue that you are creating a dependency on a dependency here

I'm sorry but we'll have to disagree :) I'm creating a _dependency_, via a declaration found in a catalog. A dependency is a _realized_ view. Things declared in a catalog are everything but dependencies. Calling them dependencies would re-create the confusion which originally triggered the change, which is that things declared in a catalog are _not_ added as dependencies, so the catalog file is _not_ a central place to put all your dependencies.

**Comment by ljacomet** [comment] 2021-12-07 21:10
Sharing here what we are looking at doing:

* Add `findLibrary` and deprecate `findDependency`
* Add `PluginAliasBuilder plugin(String alias, String id)`, `LibraryAliasBuilder library(String alias, String group, String name)` and `void library(String alias, String groupArtifactVersion)` to `VersionCatalogBuilder` which aligns with the sections in the TOML
* Deprecate `VersionCatalogBuilder.alias` in favor of the above

In the long run, these changes make the TOML, creation and query APIs more consistent with each other, which we believe is more important than pure semantics.

**Comment by octylFractal** [comment] 2021-12-23 22:51
Fixed by #19369.

**Closed by octylFractal** 2021-12-23 22:51 UTC
Labels: a:feature, @core, in:dependency-version-catalog
