### ISSUE TITLE
Test fixtures dependencies not possible in dependency block of test suite plugin

### ISSUE THREAD

**Issue by toerni** [gradle/gradle#19066] opened 2021-11-19 18:12 UTC
While testing the new test-suite plugin, I tried to add a dependency to the test-fixtures of another project in the new dependency block using kotlin dsl

### Expected Behavior

Expecting the dependency below to compile

```
testing {
    suites {

        val integrationtest by registering(JvmTestSuite::class) {
            this.useJUnitJupiter()


            dependencies {
                implementation(platform(testfixtures(":myProject")))
            }
            
            targets {
                all {
                    testTask.configure {
                        shouldRunAfter(tasks.named("test"))
                        testLogging {
                            events(FAILED, SKIPPED)
                            exceptionFormat = TestExceptionFormat.FULL
                        }
                    }
                }
            }
        }
    }
}
```

### Current Behavior

testfixtures dependency does not compile in script plugin in buildSrc

### Your Environment
* gradle 7.3
* jvm-test-suite plugin

**Comment by unredundant** [comment] 2021-12-23 18:45
any update on this? kind of a blocker for larger projects wanting to use the test suite API :(

**Comment by unredundant** [comment] 2021-12-23 18:53
Also kinda curious... beyond the need for being able to import external fixtures, it seems weird that even for the fixtures in the same module, this still doesn't work.  

From the fixtures docs here

> This will automatically create a testFixtures source set, in which you can write your test fixtures. Test fixtures are configured so that:
they can see the main source set classes 
test sources can see the test fixtures classes

Shouldn't new test suites fall under the category of `test sources`?

**Comment by unredundant** [comment] 2021-12-23 19:11
A quick test seems to indicate that this is a viable work around, but it feels... wrong

```kotlin
testing {
  suites {
    val testIntegration by creating(JvmTestSuite::class) {
      useJUnitJupiter()
      dependencies {
        // Project
        implementation(project)
        implementation(project.dependencies.testFixtures(project))
        // ...

**Comment by Vampire** [comment] 2022-01-16 17:15
Actually it is probably the same issue as https://github.com/gradle/gradle/issues/19065 and the same work-arounds should apply, just that the other ticket is about `platform` and this about `testFixtures´. But in both cases the problem is, that the type is different in this `dependencies` block and that the extensions functions are only defined for the other type.

**Comment by SgtSilvio** [comment] 2022-02-22 16:07
The same applies for `annotationProcessor`

**Comment by tresat** [comment] 2022-03-08 13:23
I'm closing this issue, as it is covered by: https://github.com/gradle/gradle/pull/19472

**Closed by tresat** 2022-03-08 13:23 UTC
Labels: a:bug, in:test-suites

**Comment by SgtSilvio** [comment] 2022-03-12 10:18
@tresat what about `annotationProcessor` dependencies, should I create a new issue for that?

**Comment by tresat** [comment] 2022-03-12 14:02
No need, see: https://github.com/gradle/gradle/pull/20115
