### ISSUE TITLE
Output from buildEnvironment does not include runtime dependencies from buildSrc

### ISSUE THREAD

**Issue by mnlipp** [gradle/gradle#19041] opened 2021-11-18 16:25 UTC
### Expected Behavior
`./gradlew buildEnvironment` outputs the plugins used in the project and their dependencies. 

It should also output the runtime dependencies declared in buildSrc as those become part of gradle's execution classpath, too.

### Current Behavior
Outputs plugins and their dependencies only.

### Context
I was trying to get an idea of gradle's execution classpath and failed because it was incomplete.

**Comment by rpalcolea** [comment] 2021-11-18 17:47
Potential duplicate of https://github.com/gradle/gradle/issues/8301

**Comment by donat** [comment] 2021-11-19 09:42
Duplicate of #8301.

**Closed by donat** 2021-11-19 09:42 UTC
Labels: a:bug, to-triage
