### ISSUE TITLE
Regression in task creation / service injection

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#8344] opened 2019-01-25 16:12 UTC
In the context of #8099 we have received [a reproducer](https://github.com/gradle/gradle/issues/8099#issuecomment-457616910) using Gradle 5.1.1.

However trying to investigate the issue with Gradle from `release` or `master` branch causes the following error:
```
> Could not create task ':client-config:compileJava'.
    > Could not create an instance of type net.ltgt.gradle.errorprone.ErrorProneOptions.
        > Class net.ltgt.gradle.errorprone.ErrorProneOptions has no constructor that is annotated with @Inject.
```

which is not the expected failure of this reproducer.

It seems to indicate that changes done for 5.2 break builds that _work_ fine with 5.1.1.

**Comment by bigdaz** [comment] 2019-01-27 21:07
I've further narrowed this down:
- Behaviour that is consistent between 5.1 and 5.2:
    - When instantiating a type with `ObjectFactory.newInstance`, we are strict with regard to requiring `@Inject` to choose a constructor.
    - When instantiating a type with `project.extensions.create`, we are lenient with regard to constructors having `@Inject`
- Behaviour that has changed between 5.1 and 5.2
    - An instance created using `ObjectFactory.newInstance` is `ExtensionAware`. In Gradle 5.1 the extension container exposed by such an instance used lenient constructor selection. In Gradle 5.2 this has changed to use strict constructor selection (constructor must be annotated with `@Inject`)

[Here's a test demonstrating the change](https://github.com/gradle/gradle/pull/8349/files#diff-71a3b7a3350f8370dca3a45445c404bb). This test passes with Gradle 5.1 and fails with 5.2.

[Here's a quick fix for this issue](https://github.com/gradle/gradle/pull/8349/commits/c4c94429f34ec0d955f9621a55c576c8aea1757e): forcing the extension container to always use lenient constructor selection when instantiating.

@adammurdoch since you've been making changes in this area, do you have a preference for how to proceed? Accept the regression? Make a change something like the fix above? Something else?

**Closed** 2019-01-28 22:31 UTC
Labels: a:bug, from:member, in:core
