### ISSUE TITLE
Some User Guide "Edit this page" links result in 404

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle#10487] opened 2019-09-06 12:34 UTC
Some User Guide "Edit this page" links result in 404, e.g., the links on:

https://docs.gradle.org/current/userguide/feature_variants.html
https://docs.gradle.org/current/userguide/dependency_locking.html

**Comment by blindpirate** [comment] 2019-09-09 02:47
@gradle/dependency-management Seems like your team adjusted the doc structure at some point, can you please take care of this?

**Comment by jjohannes** [comment] 2019-09-24 14:17
Thanks again for bringing this to our attention @rgoldberg.

Once the next nightly is deployed, this should be fixed in the [_nightly docs_](https://docs.gradle.org/nightly/userguide/userguide.html).

Once 6.0 is released, _current_ will be 6.0 and will be fixed then.

We won't fix this in retrospect for (the few) broken links in 5.x versions.

**Comment by jjohannes** [comment] 2019-09-25 06:37
Actually, this is not really solved for old docs and also not always for _current_ docs.

The problem is that we always link to the doc sources on _master_. So once a file is moved or renamed, the old links do not work anymore. This problem always existed. It just got more visible now with the large update of the dependency management docs.

For _old_ docs, I would say we could just remove the button, or always link it to the `src/docs/userguide` folder. But this can also affect _current_ if files are moved on master. Which would give users a `404` for such pages. Which is exactly what the original report is about.

I think the best solution is to dynamically check if the file exists and only link to it if it does, and otherwise default to the `src/docs/userguide` folder. We should do that only when the button is clicked (and not as we do now on page load) to avoid unnecessary requests to GH.

**Comment by ljacomet** [comment] 2019-09-25 07:00
Because this is about easy contributions, we could create a dedicated branch for this, which would be overwritten when a new version is released. Of course it may cause some edits to be out of date because the fix happened already on `master`, but overall it removes the 404 for users which is the worst I think.
And we are not flooded by docs PR, so manually moving them to master and solving conflicts should not be such a chore.

Let's say I am a user finding an issue in docs and I land on the generic `userguide` folder, chances are pretty high I will not take the time to find back the page that has the content I am trying to fix.

**Comment by jjohannes** [comment] 2019-09-25 07:24
That's also an option. But you are only talking about `current` right? Or would you do that for **all** versions of the docs. Because then we would have a lot of branches to keep open (one for each release and each RC/milestone if we want to be complete).
What is a bit problematic, if we have different handling for different versions of the doc, is that we also need to think about RC docs. So for the ongoing release, it would be nice to also have the button in the RC docs. But then we need to have that knowledge when deciding how to handle the button.

So I think if we do it that way, it would really be the easiest to have a branch for every existing release. Or make a cut somewhere (e.g. for every 5+ release and remove the button for older ones).
But we would have to automate creating the branches etc. :)

I feel like this solution, however we concretely implement it, would be quite some effort.

**Comment by ljacomet** [comment] 2019-09-25 07:39
Right, my bad, I forgot to indicate I would apply this only to `current` and the matching release if practical.
I do not think RC should be much of a concern, as I tend to link RC testers with more experienced users, which may be more willing to go one step further in opening a PR.

**Comment by bric3** [comment] 2019-10-11 12:24
Current/older version is not the only issue, some documentation page cannot be edited on master:

As of now the dit button of this page :

> https://docs.gradle.org/current/userguide/build_cache.html 

redirects here :

> https://github.com/gradle/gradle/edit/master/subprojects/docs/src/docs/userguide/build_cache.adoc

while the actual document lives in another sub directory, hence the link should be instead :

> https://github.com/gradle/gradle/edit/master/subprojects/docs/src/docs/userguide/running-builds/build_cache.adoc

The issue seems to be related to the `header.html` file :

https://github.com/gradle/gradle/blob/5b5bc67e23dca833924dc70ea5d2033b8baf1e03/subprojects/docs/src/main/resources/header.html#L304

However I'm not quite sure how the real link is generated.

**Comment by jjohannes** [comment] 2019-10-28 08:10
This is now fixed in the documentation site generation:
- We now generate an index of all documentation that is in the latest nightly
- Only if a file is in the nighty (which is pretty close to current master) we link to it, otherwise, we just go to the `userguide` folder.

The change was tested with `building_java_projects.html` which was just moved (https://github.com/gradle/gradle/commit/5b8645e24669cd1435fa44b1f3dd6833f8e46219#diff-a807034fec47fe35e8a998bcc2b288d7). Currently the change is not in the nightly (one of the rare cases where nightly and master are our of sync).

So this (6.0 RC1) now still give 404, but tomorrow it will link to the folder
https://docs.gradle.org/6.0-rc-1/userguide/building_java_projects.html

This (latest 6.0 nightly) links to the folder now, but tomorrow will link to the new source location:
https://docs.gradle.org/release-nightly/userguide/building_java_projects.html

**Closed by jjohannes** 2019-10-28 08:10 UTC
Labels: a:chore, from:contributor, in:dependency-management, in:docs
