### ISSUE TITLE
8.8-rc-1: Daemon Toolchain Support on Windows: WindowsRegistry is not supported on this operating system.

### ISSUE THREAD

**Issue by hfhbd** [gradle/gradle#29024] opened 2024-05-03 09:07 UTC
### Current Behavior

In IDEA:
![image](https://github.com/gradle/gradle/assets/22521688/a89c11d3-6f28-4a8b-8372-a5b6144e99c9)

Console: 
```stacktrace
org.gradle.tooling.GradleConnectionException: Could not run phased build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-8.8-rc-1-bin.zip'.
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:55)
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:29)
	at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:43)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:69)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.gradle.internal.nativeintegration.NativeIntegrationUnavailableException: WindowsRegistry is not supported on this operating system.
	at org.gradle.internal.nativeintegration.services.NativeServices$BrokenService.invoke(NativeServices.java:543)
	at jdk.proxy36/jdk.proxy36.$Proxy371.getSubkeys(Unknown Source)
	at org.gradle.jvm.toolchain.internal.WindowsInstallationSupplier.getVersions(WindowsInstallationSupplier.java:79)
	at org.gradle.jvm.toolchain.internal.WindowsInstallationSupplier.find(WindowsInstallationSupplier.java:70)
	at org.gradle.jvm.toolchain.internal.WindowsInstallationSupplier.lambda$findOpenJDKs$2(WindowsInstallationSupplier.java:91)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.gradle.jvm.toolchain.internal.WindowsInstallationSupplier.findInstallationsInRegistry(WindowsInstallationSupplier.java:65)
	at org.gradle.jvm.toolchain.internal.WindowsInstallationSupplier.get(WindowsInstallationSupplier.java:49)
	at org.gradle.jvm.toolchain.internal.WindowsInstallationSupplier.get(WindowsInstallationSupplier.java:31)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

### Expected Behavior

Working build

### Context (optional)

Workaround:
Delete the `gradle-daemon-jvm.properties` file

### Steps to Reproduce

0. Use Gradle 8.8-rc-1
1. Run `./gradlew :updateDaemonJvm` on Linux/macOS
2. Checkout the repo on Windows

You can use https://github.com/hfhbd/adventOfCode as a reproducer, but the actual structure/project does not really matter, as long as you use Gradle 8.8-rc-1 with a `gradle-daemon-jvm.properties` file

### Gradle version

8.8-rc-1

### Your Environment (optional)

Windows 10
Java Home: eclipse_adoptium-21-amd64-windows\jdk-21.0.3+9

IntelliJ IDEA 2024.1 (Ultimate Edition)
Build #IU-241.14494.240, built on March 28, 2024
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Kotlin: 241.14494.240-IJ

**Comment by ov7a** [comment] 2024-05-07 11:36
This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/25092

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

****

Since the fix is to ignore Windows installation supplier errors if it can't access WindowsRegistry, the fix for this issue would be the same as for the previous one.

**Comment by big-guy** [comment] 2024-05-08 15:50
This isn't the same thing as https://github.com/gradle/gradle/issues/25092, so I'm reopening this

**Comment by big-guy** [comment] 2024-05-08 19:27
@hfhbd I haven't been able to reproduce with the advent project as-is, but I have a theory.

Could you add this to your root build.gradle.kts:
```
println("org.gradle.native="+System.getProperty("org.gradle.native"))
```
And then delete gradle-daemon-jvm.properties and try to sync your project.  Does this print `org.gradle.native=null`,`org.gradle.native=true` or `org.gradle.native=false`?

If this prints `org.gradle.native=false`, do you have any custom VM properties set on IntelliJ?

If this prints `org.gradle.native=null`, do Gradle commands work from the IntelliJ console, like `gradle help` when the `gradle-daemon-jvm.properties` file exists?

**Comment by hfhbd** [comment] 2024-05-13 09:40
I can't reproduce this error anymore, but I installed some Windows updates and also IntelliJ 2024.1.1 (IU-241.15989.150).
I added the `gradle-daemon-jvm.properties` back and restarted the daemon and Windows multiple times.

Output of the property is `org.gradle.native=null`, but I am able to sync the project with IntelliJ and I can run `help` from IDE as well as the console now.

**Comment by big-guy** [comment] 2024-05-13 15:53
OK, there's some new defensive code for 8.8 RC2 (not released yet) to make this not fail, but I still don't know what's causing the native integration to be disabled.

**Closed by big-guy** 2024-05-13 15:53 UTC
Labels: in:daemon, a:bug, in:toolchains

**Comment by hfhbd** [comment] 2024-05-13 16:04
In the tests you explicitly check for `WindowsRegistry.Key.HKEY_LOCAL_MACHINE, "SOFTWARE\\AdoptOpenJDK\\JDK"` which is not available on my system (because I don't installed JDK using the installer but using IntelliJ/Gradle toolchains).

> but I still don't know what's causing the native integration to be disabled.

Do you need some build scans with some logging enabled?
