### ISSUE TITLE
Jenkins Artifactory Publish plugin  is not working anymore

### ISSUE THREAD

**Issue by VitaliyKulikov** [gradle/gradle#29720] opened 2024-06-27 09:15 UTC
### Current Behavior

During Junkins build `artifactoryPublish` task is executing with the following output:
```
> Task :generateEffectiveLombokConfig UP-TO-DATE
> Task :extractIncludeProto UP-TO-DATE
> Task :extractProto UP-TO-DATE
> Task :generateProto UP-TO-DATE
> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :jar UP-TO-DATE
> Task :generateMetadataFileForMavenJavaPublication
> Task :generatePomFileForMavenJavaPublication
> Task :artifactoryPublish

> Task :extractModuleInfo
No publisher config found for project: dbs5-proto

> Task :artifactoryDeploy

```

### Expected Behavior

Here is expected output for prev version:

```> Task :extractIncludeProto UP-TO-DATE
> Task :extractProto UP-TO-DATE
> Task :generateProto UP-TO-DATE
> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :jar UP-TO-DATE
> Task :generateMetadataFileForMavenJavaPublication
> Task :generatePomFileForMavenJavaPublication
> Task :artifactoryPublish
> Task :extractModuleInfo
[pool-1-thread-1] Deploying artifact: https://artifactory.int.openbet.com/artifactory/dbs-candidate-local/com/donbest/dbs5/dbs5-proto/1.0-SNAPSHOT/dbs5-proto-1.0-SNAPSHOT.jar
[pool-1-thread-1] Deploying artifact: https://artifactory.int.openbet.com/artifactory/dbs-candidate-local/com/donbest/dbs5/dbs5-proto/1.0-SNAPSHOT/dbs5-proto-1.0-SNAPSHOT.module
[pool-1-thread-1] Deploying artifact: https://artifactory.int.openbet.com/artifactory/dbs-candidate-local/com/donbest/dbs5/dbs5-proto/1.0-SNAPSHOT/dbs5-proto-1.0-SNAPSHOT.pom
> Task :artifactoryDeploy
```

### Steps to Reproduce

nothing special 

build.gradle.kts
```
  plugins {
    `java-library`
    `maven-publish`
  }
  
  publishing {
    publications { create<MavenPublication>("mavenJava") { from(components["java"]) } }
  }
```
Jenkinsfile
```
  // artifactory
  def server = Artifactory.server 'artifactory'
  def rtGradle = Artifactory.newGradleBuild()
  
  rtGradle.resolver server: server, repo: 'openbet-repository'
  rtGradle.deployer server: server, repo: 'dbs-candidate-local'
  
  rtGradle.useWrapper = true
  rtGradle.usesPlugin = false
  
  def buildInfo = rtGradle.run tasks: 'artifactoryPublish', rootDir: env.WORKSPACE
  server.publishBuildInfo buildInfo
```

### Gradle version

8.8

### Gradle version that used to work

8.7

**Comment by ljacomet** [comment] 2024-06-27 12:14
Most probably your issue is caused by an external Gradle plugin, which cannot be addressed in the Gradle Build Tool project. We cannot just move the issue.

We recommend you open an issue on its issue tracker.

We have some integration tests with major plugins to catch potential problems early, but we don't have the capacity to cover all plugins available.

If you think you have come across a Gradle bug, please provide a reproducer for this issue without the plugin, and we’ll consider reopening it.


***

Given the executed tasks and the applied plugins, the Jenkins configuration seems to be injecting yet another plugin for Artifactory interactions. [Here is one such plugin](https://github.com/jfrog/artifactory-gradle-plugin).

You will need to enquire about this issue on the Jenkins plugin itself and possibly follow up with the Artifactory one.

**Closed by ljacomet** 2024-06-27 12:14 UTC
Labels: closed:plugin

**Comment by VitaliyKulikov** [comment] 2024-06-27 12:48
@ljacomet, do you have any ideas on Gradle changes from 8.7 and 8.8 regression as nothing has been changed on the project and Jenkins plugin at all?
