### ISSUE TITLE
Accessing project.properties before configuring the publishing extension causes failure

### ISSUE THREAD

**Issue by MarkRx** [gradle/gradle#1470] opened 2017-02-27 19:12 UTC
If project properties are accessed before the publishing closure is configured the project will fail with an exception:

```
apply plugin: 'maven-publish'

println properties['some.property']

publishing {
    publications {
        maven(MavenPublication) {
        }   
    }   
}
```

> * Where:
> Build file 'C:\git\gradletest\build.gradle' line: 5
> 
> * What went wrong:
> A problem occurred evaluating root project 'gradletest'.
> > Cannot configure the 'publishing' extension after it has been accessed.

### Expected Behavior
I should be able to access project properties before setting up the publishing closure. I don't see why the publishing closure would resolve if I access project properties.

### Current Behavior
Accessing project properties causes the publishing closure to resolve.

### Context
I was checking the project properties in a plugin to determine what steps should be done when the plugin is applied

### Steps to Reproduce (for bugs)
See above

### Your Environment
Gradle Version: 3.3
Operating System: Windows 7
JVM: 1.8.0_111

Same issue as this: https://discuss.gradle.org/t/accessing-project-properties-before-configuring-publishing-extension-causes-a-strange-error/20328

**Comment by bmuschko** [comment] 2017-02-27 19:30
With the notation `properties['some.property']` you are trying to access the fields of the `Project` instance. `properties` is something that Groovy exposes and not Gradle. I assume you want to ask for the extra property (Gradle concept) named `some.property`?

You'll need to access the extra property via `project.findProperty('some.property')`.

**Comment by oehme** [comment] 2017-09-06 13:36
Duplicate of #2496

**Closed by oehme** 2017-09-06 13:36 UTC
Labels: a:question, from:contributor, in:core, in:publishing-plugin
