### ISSUE TITLE
java.lang.String java.io.File.path accessible: module java.base does not "opens java.

### ISSUE THREAD

**Issue by benedicte69** [gradle/gradle#17495] opened 2021-06-21 02:46 UTC
> Task :app:processDebugMainManifest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @4b4f3f8f

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

### Expected Behavior

gradlew lint should work but I does not!
### Current Behavior

Execution failed for task ':app:processDebugMainManifest'.
### Your Environment

Build scan URL:

**Comment by mlopatkin** [comment] 2021-06-21 11:12
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of #17152. Please add your +1's to that issue.

**Closed by mlopatkin** 2021-06-21 11:12 UTC
Labels: a:regression, to-triage
