### ISSUE TITLE
JacocoDebug task intermittently fails with "java.lang.ExceptionInInitializerError (no error message)" on build

### ISSUE THREAD

**Issue by oxobh** [gradle/gradle#15830] opened 2021-01-18 04:06 UTC
### Expected Behavior
Build should be successful every time
### Current Behavior
Our build intermittently fails on pipelines with this error (3-4 times in 20 builds). We don't get any further message on why this error occurred. We get the following error - 

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':module-name:jacocoDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > java.lang.ExceptionInInitializerError (no error message)
```

### Context

This is an intermittent issue, and since we don't get enough information on why this happens, I am unable to find out the exact cause. Our pipelines and local build randomly fail because of this issue.

I am using Jacoco dependency version as 0.8.6 in our android project and also tried "android.forceJacocoOutOfProcess=true" flag but still getting this issue. 

### Steps to Reproduce 

So far I've unable to reproduce it with exact steps. It's an intermittent error and occurs randomly on local and pipeline builds.

### Your Environment

Java
```
java -version
java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Java HotSpot(TM) Client VM (build 25.271-b09, mixed mode, sharing)
```

Gradle
```
------------------------------------------------------------
Gradle 6.1.1
------------------------------------------------------------

Build time:   2020-01-24 22:30:24 UTC
Revision:     a8c3750babb99d1894378073499d6716a1a1fa5d

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_242-release (JetBrains s.r.o 25.242-b01)
OS:           Windows 10 10.0 amd64
```

**Comment by jobernas** [comment] 2021-01-26 18:02
Same problem ... driving me crazy ... anyone knows reason and/or have a fix for this?

**Comment by bmuskalla** [comment] 2021-04-09 14:53
Thank you for your interest in Gradle!

This is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the core of the Gradle Build Tool.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/source/report-bugs

We've seen reports in the public that this has been fixed in the meantime so it might be worth trying newer versions of AGP/Gradle to see if this persists. If you can still reproduce this, please feel free to create a new issue with steps for us to reproduce/include info or debug logs.

**Closed by bmuskalla** 2021-04-09 14:53 UTC
Labels: a:bug

**Comment by menghanjun001** [comment] 2021-06-04 06:12
is it still not handled?I met this error and I can't upgrade the version of gradle because the main project is not the part of my business.

**Comment by JirkaKrivanek** [comment] 2021-07-19 07:13
Happens to me too :(
