### ISSUE TITLE
Gradle 6.6.1 hangs while executing compileTestJava

### ISSUE THREAD

**Issue by ewirch** [gradle/gradle#14531] opened 2020-09-17 09:03 UTC
Gradle build, which was started this way:
```
./gradlew --no-daemon --exclude-task=test --info --console=plain check
```
hangs in `compileTestJava` task.

### Expected Behavior
Gradle finishes the build.

### Current Behavior
Gradle hangs.

### Context
See attachments for build output and thread dumps of Gradle processes. I could not tell which GradleDeamon started the hanging build, so I attached thread dumps of all three.
[build.txt](https://github.com/gradle/gradle/files/5237594/build.txt)
[GradleDaemon.122147.txt](https://github.com/gradle/gradle/files/5237595/GradleDaemon.122147.txt)
[GradleDaemon.125276.txt](https://github.com/gradle/gradle/files/5237596/GradleDaemon.125276.txt)
[GradleDaemon.133557.txt](https://github.com/gradle/gradle/files/5237597/GradleDaemon.133557.txt)
[GradleWorkerMain.txt](https://github.com/gradle/gradle/files/5237598/GradleWorkerMain.txt)
[GradleWrapperMain.txt](https://github.com/gradle/gradle/files/5237599/GradleWrapperMain.txt)

### Steps to Reproduce 
Since this is a concurrency problem (GradleWorkerMain hangs in `CountDownLatch.await()`) I'm afraid it is not easily reproducible. In fact it happened to me for the first time. 
[...three minutes later...]
At least I thought so. I canceled the build and restarted it. It hang again. Only after I restarted the daemons, the build passed.

### Your Environment
Manjaro Linux, 5.8.6 kernel, 64 bit

Oracle Java JDK:
java 14.0.1 2020-04-14
Java(TM) SE Runtime Environment (build 14.0.1+7)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)

Using Gradle wrapper
```
distributionSha256Sum=11657af6356b7587bfb37287b5992e94a9686d5c8a0a1b60b87b9928a2decde5
distributionUrl=https\://services.gradle.org/distributions/gradle-6.6.1-all.zip
```

Build scan was not recorded, I'm afraid. I recorded a build scan after restarting the daemons: https://scans.gradle.com/s/y2uuodzos4vc2 Just for the reference of plugins and their versions used. The build failure in the scan is not related to the problem.

**Comment by big-guy** [comment] 2020-09-17 20:37
@gradle/execution @gradle/jvm this looks like it's hanging just before task execution starts for the test task?

**Comment by ewirch** [comment] 2020-09-24 07:07
@big-guy: test task is excluded. See Gradle command line.

Happened again today. Last output:
```
> Task :common:compileTestJava
Watching 270 directories to track changes
Watching 271 directories to track changes
Watching 272 directories to track changes
```

**Comment by wolfs** [comment] 2020-10-19 07:52
@ewirch Does this still happen with Gradle 6.7?

**Comment by ewirch** [comment] 2020-10-19 11:45
The issue occurs sporadically. It didn't occur for Gradle 6.6.1 since the 24th of September either. I'll keep an eye on it and comment if it re-occurs.

**Comment by wolfs** [comment] 2020-11-13 17:01
I'll close this now. If it occurs again please re-open or comment.

**Comment by ewirch** [comment] 2021-02-04 09:42
@wolfs 
Occurred again today using Gradle 6.8.1.
Last log line:
```
compileJava (Thread[Daemon worker,5,main]) completed. Took 33.912 secs.
```

As described previously, it would hang over and over again, until I restart the daemon.

Any ideas on how to collect more info, so the next time there is more to reason about, than just "it occurred again"?

**Comment by ewirch** [comment] 2021-02-04 09:54
I hope I promise not too much, but it looks like I can trigger the problem reliably.

Here are thread dumps for starters.

`GraddleWrapperMain` hangs in
```
...
	at org.gradle.launcher.daemon.client.DaemonClientConnection.receive(DaemonClientConnection.java:35)
	at org.gradle.launcher.daemon.client.DaemonClient.monitorBuild(DaemonClient.java:215)
	at org.gradle.launcher.daemon.client.DaemonClient.executeBuild(DaemonClient.java:184)
...
```

`GradleDaemon` hangs in
```
"Daemon worker" #30 prio=5 os_prio=0 cpu=5046,70ms elapsed=223,03s tid=0x00007fa9380081c0 nid=0xd19a in Object.wait()  [0x00007fa9728e0000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@15.0.1/Native Method)
	- waiting on <no object reference available>
	at java.lang.Object.wait(java.base@15.0.1/Object.java:321)
	at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:51)
	- locked <0x00000007008ea830> (a java.lang.Object)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:155)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
	at org.gradle.execution.plan.DefaultPlanExecutor.process(DefaultPlanExecutor.java:72)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.executeWithServices(DefaultTaskExecutionGraph.java:196)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.execute(DefaultTaskExecutionGraph.java:189)
...
```

[GradleDaemon.txt](https://github.com/gradle/gradle/files/5924745/GradleDaemon.txt)
[GradleWrappenMain.txt](https://github.com/gradle/gradle/files/5924746/GradleWrappenMain.txt)

**Comment by wolfs** [comment] 2021-02-04 14:17
@ewirch and myself took a look at the build. It seems like it is adding finalizers to some tasks:
```
allprojects {
    afterEvaluate {
        tasks.matching({ t -> t.name.startsWith('spotbugs') }).each {
            it.finalizedBy 'transform'
        }
    }
}
```

The `transform` task is coming from the [`org.myire.munge` plugin])(https://plugins.gradle.org/plugin/org.myire.munge) and transforms the spotbugs reports.

The hang does not appear when running without `--parallel`.

Looking at the debug log, this is at the end:
```
[org.gradle.execution.plan.DefaultExecutionPlan] Node :importer:transform cannot run with currently running nodes [:importer:transform, :api:compileTestJava]
[org.gradle.execution.plan.DefaultExecutionPlan] No node could be selected, nodes ready: true
[org.gradle.execution.plan.DefaultExecutionPlan] No node could be selected, nodes ready: false
[org.gradle.execution.plan.DefaultExecutionPlan] Node :api:compileTestJava finished executing
[org.gradle.execution.plan.DefaultExecutionPlan] Node :api:compileTestJava completed, executed: true
[org.gradle.execution.plan.Node] Checking if all dependencies are complete for :api:testClasses
[org.gradle.execution.plan.Node] All dependencies are complete for :api:testClasses
[org.gradle.execution.plan.TaskNode] Checking if all must successors are complete for :api:testClasses
[org.gradle.execution.plan.TaskNode] Checking if all finalizing successors are complete for :api:testClasses
[org.gradle.execution.plan.TaskNode] All task dependencies are complete for :api:testClasses
[org.gradle.execution.plan.DefaultExecutionPlan] No node could be selected, nodes ready: false
```

Afterwards, we don't seem to try to select a new node to execute, so their seems to be a bug with using the `nodes ready` flag and finalizers when running in parallel. It is especially strange that we try to run `:importer:transform` when it is already running.

**Comment by ewirch** [comment] 2021-02-05 06:18
@wolfs, would you reopen the issue?

**Comment by oneiros-de** [comment] 2022-04-19 12:19
The root cause is probably lombok: `val` in unit tests can be really slow, replace it with `final var`. See [this issue](https://github.com/projectlombok/lombok/issues/2652).

**Comment by jbartok** [comment] 2023-09-15 12:28
Sorry for the late reply.

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by ov7a** [comment] 2023-10-03 07:28
Closing this as unreproducible.

**Closed by ov7a** 2023-10-03 07:28 UTC
Labels: a:bug, @execution, in:scheduler, closed:unreproducible
