### ISSUE TITLE
Gradle 8.5: Resolving old artifacts of the project

### ISSUE THREAD

**Issue by kiendev98** [gradle/gradle#27735] opened 2024-01-18 04:53 UTC
### Expected Behavior

I want to create a configuration that resolves the old artifact of the project.

### Current Behavior (optional)

When resolving the configuration, Gradle 8 silently adds the current version artifact of the project into the artifact candidate list. After that, it resolves the latest one and rejects the old one.

For example, the current project version is `2.0.0` and I create a configuration to resolve the nearest old artifacts with range version.

```java
project.configurations.findByName("oldArtifacts") ?: project.configurations.create("oldArtifacts") {
			canBeConsumed = false
			transitive = true
			visible = false
			dependencies.add(
					project.dependencies.create("$project.group:$project.name") {
						version {
							strictly "[0.0.0,2.0.0)"
						}
					}
			)
		}
```

Even the range excludes the version `2.0.0`, Gradle 8 always returns the artifact `2.0.0`.

After debugging, I found that these line of code that causes the problem.
```java
        // If the module matches, add the root component into the mix
        if (moduleId.equals(rootModuleId) && !candidates.contains(rootComponent)) {
            candidates = new ArrayList<>(candidates);
            candidates.add(rootComponent);
        }
```
https://github.com/gradle/gradle/blob/master/platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/selectors/SelectorStateResolver.java#L71-L74

With Gradle 7 I could cheat it by changing the project group or project name when resolving the configuration but this data is cached with Gradle 8 now.

### Context

We need to fetch the old artifacts for [revapi](https://revapi.org/revapi-site/main/index.html) to work.
It needs the old artifacts and the new artifacts for comparing and determining the breaking change.

Besides, we also need the old artifacts for analyzing purposes.

**Comment by cobexer** [comment] 2024-01-23 13:12
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #1629

Please add your use case and 👍 to that issue.

**Closed by cobexer** 2024-01-23 13:12 UTC
Labels: a:feature, to-triage
