### ISSUE TITLE
The input line is too long on Windows using gradle distZip

### ISSUE THREAD

**Issue by sinall** [gradle/gradle#2907] opened 2017-09-10 09:05 UTC
Cmd.exe raise '**The input line is too long**' when running the bat file generated by '**gradle distZip**'.

### Expected Behavior

The bat file could be run without error.

### Current Behavior

> The input line is too long.
> The syntax of the command is incorrect.

### Context

I'm not able to run the application built by 'gradle distZip'.
There is also a topic here: https://issues.gradle.org/browse/GRADLE-2992

### Steps to Reproduce (for bugs)

1.  Create a project under C:\Users\yourname\Documents\portfolio-manager
2.  Add dependencies like this:
```
dependencies {
    def springVersion = '4.2.0.RELEASE'
    def tomcatVersion = '7.0.63'
    def cargoVersion = '1.4.5'

    compile(
            'ch.qos.logback:logback-classic:1.1.2',
            'com.belerweb:weibo4j-oauth2:2.1.1-beta2-3',
            'com.fasterxml.jackson.core:jackson-annotations:2.6.4',
            'com.fasterxml.jackson.core:jackson-databind:2.6.4',
            'com.fasterxml.jackson.datatype:jackson-datatype-hibernate4:2.6.4',
            'com.github.jsqlparser:jsqlparser:0.9.3',
            'com.google.guava:guava:18.0',
            'com.sun.faces:jsf-api:2.2.12',
            'com.sun.faces:jsf-impl:2.2.12',
            'commons-beanutils:commons-beanutils:1.9.2',
            'commons-fileupload:commons-fileupload:1.3.1',
            'commons-io:commons-io:2.4',
            'commons-logging:commons-logging:1.2',
            'javax.servlet:jstl:1.2',
            'javax.transaction:javax.transaction-api:1.2',
            'mysql:mysql-connector-java:5.1.40',
            'net.objecthunter:exp4j:0.4.5',
            'org.apache.commons:commons-lang3:3.3.2',
            'org.apache.commons:commons-math3:3.5',
            'org.apache.poi:poi:3.13',
            'org.apache.poi:poi-ooxml:3.13',
            'org.apache.httpcomponents:httpclient:4.5.1',
            'org.apache.solr:solr-solrj:5.3.1',
            'org.aspectj:aspectjrt:1.8.7',
            'org.aspectj:aspectjweaver:1.8.7',
            'org.hibernate:hibernate-entitymanager:5.0.6.Final',
            'org.jfree:jfreechart:1.0.19',
            'org.omnifaces:omnifaces:1.8.3',
            'org.springframework.data:spring-data-jpa:1.9.0.RELEASE',
            'org.springframework.data:spring-data-redis:1.6.1.RELEASE',
            'org.springframework.mobile:spring-mobile-device:1.1.5.RELEASE',
            "org.springframework:spring-context-support:${springVersion}",
            "org.springframework:spring-webmvc:${springVersion}",
            "org.springframework.security:spring-security-web:4.0.2.RELEASE",
            "org.springframework.security:spring-security-config:4.0.2.RELEASE",
            'redis.clients:jedis:2.8.0',
    )

```
3. Run 'gradle distZip'
4. Unzip the zip in build\distributions, run the bat file under the folder, there will be the error
5. But, copy the unzipped folder to D:\, then there's no error at all.

### Your Environment

 * Build scan URL: 

WIndows 10 64bit
Java 8
Gradle 4.1

**Comment by oehme** [comment] 2017-09-11 17:19
Duplicate of #1989

**Closed by oehme** 2017-09-11 17:19 UTC
Labels: a:bug, affects-version:4.1, from:contributor, in:application-plugin
