### ISSUE TITLE
Transitive POM files are included on classpath

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#8582] opened 2019-02-22 01:23 UTC
Transitive POM files are included on the compile classpath.

```
plugins {
	id 'java'
}

repositories {
	mavenCentral()
}

dependencies {
	compile 'com.googlecode.matrix-toolkits-java:mtj:1.0.3'
}

task listCompileClasspath() {
	doFirst {
		configurations.compileClasspath.files.each { println(it) }
	}
}
```

Run `:listCompileClasspath` and note:
```
> Task :listCompileClasspath
/Users/dannyt/.gradle/caches/modules-2/files-2.1/com.googlecode.matrix-toolkits-java/mtj/1.0.3/e18c1ee2c4c278694dfed39104e53c7f92ad048b/mtj-1.0.3.jar
/Users/dannyt/.gradle/caches/modules-2/files-2.1/com.github.fommil.netlib/all/1.1.2/f235011206ac009adad2d6607f222649aba5ca9e/all-1.1.2.pom
/Users/dannyt/.gradle/caches/modules-2/files-2.1/com.github.fommil.netlib/netlib-native_ref-osx-x86_64/1.1/80da53ec862f283dc3b191b9dbd3166ea6671831/netlib-native_ref-osx-x86_64-1.1-natives.jar
```

That causes plugins that expect only to find jars on the classpath to fail. Such as https://github.com/spring-projects/spring-boot/issues/16001 and the FindBugs plugin.

```
------------------------------------------------------------
Gradle 5.1.1
------------------------------------------------------------

Build time:   2019-01-10 23:05:02 UTC
Revision:     3c9abb645fb83932c44e8610642393ad62116807

Kotlin DSL:   1.1.1
Kotlin:       1.3.11
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_202 (Azul Systems, Inc. 25.202-b05)
OS:           Mac OS X 10.14.3 x86_64
```

**Comment by rpalcolea** [comment] 2019-02-23 00:34
Hi folks, is there a workaround for this? Can this be target for 5.1?

**Comment by ljacomet** [comment] 2019-02-25 10:23
Thanks for the report.

I believe this is a compatibility problem and should be fixed.

From Gradle, you would declare the dependency to `com.github.fommil.netlib:all` normally:
```
dependencies {
    implementation "com.github.fommil.netlib:all:1.1.2"
}
```
and that would give you the expected result: no pom on the classpath (runtime or compile) but you effectively have all the transitive dependencies of `com.github.fommil.netlib:all`

And in Gradle, if you really want the `pom` file and not the dependencies, you would do:
```
dependencies {
    pomAccess "com.github.fommil.netlib:all:1.1.2@pom"
}
```
which would allow you to resolve the pom file and access it in your build.

Since Maven _mandates_ that a dependency on such a module be declared as:
```
<dependency>
    <groupId>com.github.fommil.netlib</groupId>
    <artifactId>all</artifactId>
    <version>1.1.2</version>
    <type>pom</type>
</dependency>
```
as omitting the `<type>pom</type>` part is illegal, Gradle should just ignore that precision since it knows how to resolve a module with `<packaging>pom</packaging>` by accessing its dependencies and considering it does not have an artifact.

**Comment by ljacomet** [comment] 2019-02-25 10:24
@rpalcolea It is very unlikely that Gradle will release another 5.1 bugfix at this point, especially with 5.3 being so close.

**Comment by ljacomet** [comment] 2019-02-25 10:32
Well, I should have tested the Maven use case all the way through.

With the following minimal pom file:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.sample</groupId>
  <artifactId>pom-dep</artifactId>
  <version>1.0-SNAPSHOT</version>

  <dependencies>
    <dependency>
      <groupId>com.googlecode.matrix-toolkits-java</groupId>
      <artifactId>mtj</artifactId>
      <version>1.0.3</version>
    </dependency>
  </dependencies>
</project>
```
and running:
```
mvn dependency:build-classpath -Dmdep.includeScope=compile
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------------< org.sample:pom-dep >-------------------------
[INFO] Building pom-dep 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:build-classpath (default-cli) @ pom-dep ---
[INFO] Dependencies classpath:
/Users/ljacomet/.m2/repository/com/googlecode/matrix-toolkits-java/mtj/1.0.3/mtj-1.0.3.jar:/Users/ljacomet/.m2/repository/com/github/fommil/netlib/all/1.1.2/all-1.1.2.pom:/Users/ljacomet/.m2/repository/net/sourceforge/f2j/arpack_combined_all/0.1/arpack_combined_all-0.1.jar:/Users/ljacomet/.m2/repository/com/github/fommil/netlib/core/1.1.2/core-1.1.2.jar:/Users/ljacomet/.m2/repository/com/github/fommil/netlib/netlib-native_ref-osx-x86_64/1.1/netlib-native_ref-osx-x86_64-1.1-natives.jar:/Users/ljacomet/.m2/repository/com/github/fommil/netlib/native_ref-java/1.1/native_ref-java-1.1.jar:/Users/ljacomet/.m2/repository/com/github/fommil/jniloader/1.1/jniloader-1.1.jar:/Users/ljacomet/.m2/repository/com/github/fommil/netlib/netlib-native_ref-linux-x86_64/1.1/netlib-native_ref-linux-x86_64-1.1-natives.jar:/Users/ljacomet/.m2/repository/com/github/fommil/netlib/netlib-native_ref-linux-i686/1.1/netlib-native_ref-linux-i686-1.1-natives.jar:/Users/ljacomet/.m2/repository/com/github/fommil/netlib/netlib-native_ref-win-x86_64/1.1/netlib-native_ref-win-x86_64-1.1-natives.jar:/Users/ljacomet/.m2/repository/com/github/fommil/netlib/netlib-native_ref-win-i686/1.1/netlib-native_ref-win-i686-1.1-natives.jar:/Users/ljacomet/.m2/repository/com/github/fommil/netlib/netlib-native_ref-linux-armhf/1.1/netlib-native_ref-linux-armhf-1.1-natives.jar:/Users/ljacomet/.m2/repository/com/github/fommil/netlib/netlib-native_system-osx-x86_64/1.1/netlib-native_system-osx-x86_64-1.1-natives.jar:/Users/ljacomet/.m2/repository/com/github/fommil/netlib/native_system-java/1.1/native_system-java-1.1.jar:/Users/ljacomet/.m2/repository/com/github/fommil/netlib/netlib-native_system-linux-x86_64/1.1/netlib-native_system-linux-x86_64-1.1-natives.jar:/Users/ljacomet/.m2/repository/com/github/fommil/netlib/netlib-native_system-linux-i686/1.1/netlib-native_system-linux-i686-1.1-natives.jar:/Users/ljacomet/.m2/repository/com/github/fommil/netlib/netlib-native_system-linux-armhf/1.1/netlib-native_system-linux-armhf-1.1-natives.jar:/Users/ljacomet/.m2/repository/com/github/fommil/netlib/netlib-native_system-win-x86_64/1.1/netlib-native_system-win-x86_64-1.1-natives.jar:/Users/ljacomet/.m2/repository/com/github/fommil/netlib/netlib-native_system-win-i686/1.1/netlib-native_system-win-i686-1.1-natives.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.873 s
[INFO] Finished at: 2019-02-25T11:29:30+01:00
[INFO] ------------------------------------------------------------------------
```
we can clearly see that the `com.github.fommil.netlib:all` POM _is on the classpath_.

Where do you source that Maven behaves differently than Gradle?
Are you sure it is not a flaw in the way the plugins handle a Gradle classpath, where they would not ignore poms, compared to how they handle a Maven classpath, where they would ignore poms?

**Comment by MinnDevelopment** [comment] 2019-06-01 10:06
I have noticed another problem with pom dependencies that actually is handled differently with maven. Gradle does not include transitive dependencies on type pom unless specified explicitly. When generating a pom file with `maven-publish` it even explicitly **excludes** the transitive dependencies.

```xml
<groupId>club.minnced</groupId>
<artifactId>opus-java</artifactId>
<version>1.0.4</version>
<type>pom</type>
<scope>runtime</scope>
<exclusions>
  <exclusion>
    <artifactId>*</artifactId>
    <groupId>*</groupId>
  </exclusion>
</exclusions>
``` 

## Gradle

**build.gradle**
```gradle
plugins {
    id 'java'
}

group 'test'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    jcenter()
}

dependencies {
    implementation("club.minnced:opus-java:1.0.4@pom")
}

build.doLast {
    println("Classpath:")
    println(compileJava.classpath.asPath)
}
```

**Output**
```
11:56:40: Executing task 'build'...

Download https://services.gradle.org/distributions/gradle-5.4.1-bin.zip (87.11 MB)
[ 97%] [ =====================================================> ] 84.94 MB
Download https://services.gradle.org/distributions/gradle-5.4.1-bin.zip succeeded, took 14 s 368 ms
Unzipping ...

> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :jar
> Task :assemble
> Task :compileTestJava NO-SOURCE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :test NO-SOURCE
> Task :check UP-TO-DATE

> Task :build
Classpath:
C:\Users\minnced\.gradle\caches\modules-2\files-2.1\club.minnced\opus-java\1.0.4\596995aaf2f5b5091c4d251fdc11fa62680cc59e\opus-java-1.0.4.pom

BUILD SUCCESSFUL in 4s
2 actionable tasks: 2 executed
11:57:01: Task execution finished 'build'.
```

## Maven

**pom.xml**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>test</groupId>
    <artifactId>test</artifactId>
    <version>1.0-SNAPSHOT</version>

    <repositories>
        <repository>
            <id>jcenter</id>
            <url>https://jcenter.bintray.com</url>
        </repository>
    </repositories>
    <dependencies>
        <dependency>
            <groupId>club.minnced</groupId>
            <artifactId>opus-java</artifactId>
            <version>1.0.4</version>
            <type>pom</type>
        </dependency>
    </dependencies>
</project>
```
**Output**
```
"C:\Program Files\AdoptOpenJDK\jdk-11.0.3.7-hotspot\bin\java.exe" -Dmaven.multiModuleProjectDirectory=E:\git\test-maven -Dmaven.home=C:\Users\minnced\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\191.6707.61\plugins\maven\lib\maven3 -Dclassworlds.conf=C:\Users\minnced\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\191.6707.61\plugins\maven\lib\maven3\bin\m2.conf -javaagent:C:\Users\minnced\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\191.6707.61\lib\idea_rt.jar=50683:C:\Users\minnced\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\191.6707.61\bin -Dfile.encoding=UTF-8 -classpath C:\Users\minnced\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\191.6707.61\plugins\maven\lib\maven3\boot\plexus-classworlds-2.5.2.jar org.codehaus.classworlds.Launcher -Didea.version2019.1.1 org.apache.maven.plugins:maven-dependency-plugin:2.9:build-classpath
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building test 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.9:build-classpath (default-cli) @ test ---
[INFO] Dependencies classpath:
C:\Users\minnced\.m2\repository\club\minnced\opus-java\1.0.4\opus-java-1.0.4.pom;C:\Users\minnced\.m2\repository\club\minnced\opus-java-api\1.0.4\opus-java-api-1.0.4.jar;C:\Users\minnced\.m2\repository\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar;C:\Users\minnced\.m2\repository\club\minnced\opus-java-natives\1.0.4\opus-java-natives-1.0.4.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.957 s
[INFO] Finished at: 2019-06-01T11:46:29+02:00
[INFO] Final Memory: 11M/50M
[INFO] ------------------------------------------------------------------------

Process finished with exit code 0
```

**Comment by NHendricks** [comment] 2021-02-22 14:41
We also experience to have pom files in the classpath when we generate it with Gradle (using the Gradle eclipse plugin, with Buildship the problem cannot be reproduced). 
Maven does not put them into the classpath. 

According to the maven documentation at https://maven.apache.org/ref/3.6.3/maven-core/artifact-handlers.html pom files should not be added to the classpath.

**Comment by ljacomet** [comment] 2021-09-09 10:11
This came up in a conversation again. And I dug a bit deeper.
The Maven `dependencies` plugin does not work according to the Maven spec. But compilation classpath building does and indeed ignores POM files.

This means we might want to do something about it in Gradle at some point.

@MinnDevelopment What you experience is expected. That dependency is an _artifact dependency_ for Gradle. It explicitly indicates that you want that specific file, nothing else. And yes, there is no exact translation for this in Maven. So we use what you see.

**Comment by big-guy** [comment] 2023-11-27 17:53
The resolution behavior matches what Maven does in this case.

https://repo1.maven.org/maven2/com/googlecode/matrix-toolkits-java/mtj/1.0.3/mtj-1.0.3.pom has an explicit dependency on a POM artifact:
```
<dependency>
<groupId>com.github.fommil.netlib</groupId>
<artifactId>all</artifactId>
<version>1.1.2</version>
<type>pom</type>
</dependency>
```

I don't think we should special case `pom` here to remove it from the resolution result.  If other tools do not like POM files like this, they will need to adjust or we need an idiomatic pattern to "fix" these kinds of dependencies.

**Closed by big-guy** 2023-11-27 17:53 UTC
Labels: a:bug, in:dependency-resolution
