### ISSUE TITLE
Gradle 8.2 sets incorrect value to boolean `--no-feature` option

### ISSUE THREAD

**Issue by hsz** [gradle/gradle#25658] opened 2023-07-07 08:34 UTC
### Expected Behavior

If a custom task introduces a task option for CLI usage named `--no-feature` of `Boolean` type, it should be set to `true` when invoked.

Example task:

```kotlin
abstract class MyTask : DefaultTask() {

    @get:Input
    @Option(
        option = "no-feature",
        description = "Disable the feature.",
    )
    var noFeature = false

    @TaskAction
    fun run() {
        println("noFeature = $noFeature")
    }
}
```

Calling the `./gradlew myTask --no-feature` should print: `noFeature = true`

### Current Behavior

With Gradle `< 8.2`, the `true` value is printed.

After upgrading Gradle to `8.2`, it started printing `false`.

### Context (optional)

Gradle `8.2` introduced a new feature: _Boolean task options generate opposite option_

References:
- https://docs.gradle.org/8.2/release-notes.html
- https://docs.gradle.org/8.2/userguide/custom_tasks.html#sec:supported_task_option_data_types

### Steps to Reproduce

To reproduce the issue, clone the following project:

> https://github.com/hsz/gradle-82-opposite-option-issue

Then call:

```bash
./gradlew wrapper -PgradleVersion=8.1.1
./gradlew myTask --no-feature
```

It should print the `true` value, as expected:

```
> Task :myTask
noFeature = true
```

After switching to Gradle `8.2`, it prints the `false` value instead, which isn't expected:

```bash
./gradlew wrapper -PgradleVersion=8.2
./gradlew myTask --no-feature
```

Result:

```
> Task :myTask
noFeature = false
```

### Gradle version

8.2

**Comment by Vampire** [comment] 2023-07-07 08:58
Maybe it would also be nice and in line with the new auto `no-` prefix to have automatic `--feature` for the case described here.

**Comment by eskatos** [comment] 2023-07-07 09:11
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by asodja** [comment] 2023-07-07 14:43
Should be fixed with https://github.com/gradle/gradle/pull/25665

**Closed by asodja** 2023-07-07 14:43 UTC
Labels: a:regression, in:writing-tasks, affects-version:8.2

**Comment by hsz** [comment] 2023-07-07 14:48
Thank you, Anže!

**Comment by hsz** [comment] 2023-07-10 13:56
With Gradle `8.2.1`, everything is working again. Thanks for a blazing-fast fix!
