### ISSUE TITLE
Gradle wrapper changelog is being showed even in quiet mode

### ISSUE THREAD

**Issue by jakubhava** [gradle/gradle#6756] opened 2018-09-14 09:03 UTC
## The issue
When you upgrade to new Gradle as `./gradlew wrapper --gradle-version=4.9` and the first task you run depends on stdout such as `export URL=$(./gradlew -q printDownloadUrl)` does not produce correct textual output as it also contains the changelog

This does not occur of you run any subsequent tasks via Gradle wrapper

## The expected behavior
 The changelog should not be showed when running in quite mode

**Comment by marcphilipp** [comment] 2018-09-18 14:30
As a workaround, you could write the download URL to a file or search for `http...`.

**Comment by jakubhava** [comment] 2018-09-18 14:34
Yup, we already run `./gradlew --help` to print the change log at the begging of each test suite so it's not blocking us.

**Comment by marcphilipp** [comment] 2018-09-18 14:47
Here's another workaround:
https://github.com/gradle/gradle/issues/5213#issuecomment-391976595.

**Comment by marcphilipp** [comment] 2018-09-18 14:47
Duplicate of #5213.

**Closed by marcphilipp** 2018-09-18 14:47 UTC
