### ISSUE TITLE
JUnit 5 tests are skipped if MockitoExtension is loaded

### ISSUE THREAD

**Issue by Brutus5000** [gradle/gradle#8536] opened 2019-02-18 09:50 UTC
### Expected Behavior
All @Test annotated methods should run, tests throwing exceptions should make the build fail.

### Current Behavior
Tests in classes annotated with @ExtendWith(MockitoExtension.class) are skipped and the build succeeds.

### Context
As soon as I remove the @ExtendWith line gradle runs the test again and the build fails.
I have tested this with older Mockito versions, older JUnit version and also Gradle 5.1 and 5.2. The result is always the same.

When I run the test from IntelliJ the test fails instantly.
Using debugging we could verify that the tests are not run (no stop at breakpoints). A second test class without the ExtendsWith is properly executed (and stops at breakpoints).

This basically breaks our whole test concept.

### Steps to Reproduce (for bugs)
Sample project containing build.gradle and one JUnit test class.

[sample-project.zip](https://github.com/gradle/gradle/files/2874933/sample-project.zip)

### Your Environment
 * Oracle JDK 8, JUnit 5, Gradle 5.2.1 (locally on MacOS but Gradle docker image is also affected)
 * Build scan URL: https://gradle.com/s/xfcgd727c6izy

**Comment by breucode** [comment] 2019-03-07 09:20
The problem is, that the `org.mockito:mockito-junit-jupiter` dependency has the wrong scope in your build.gradle. When you change it from testCompileOnly to testImplementation, the test fails, as it should. There is at least one class of mockito-junit-jupiter, which is needed at runtime.

The question is, why there is no exception thrown. When I extend the MockitoExtension class (`e.g. TestExtension extends MockitoExtension`)`, I get a `NoClassDefFoundError`.

In IntelliJ, the tests work, because the needed class is available at runtime, even though it should not be available according to your build.gradle file.

**Comment by blindpirate** [comment] 2019-03-09 07:34
@Brutus5000 thanks for reporting. As pointed out by @breucode , you asked Gradle not to put `org.mockito:mockito-core:2.24.0` on test runtime classpath so the failure you encountered is exactly natural. I'm going to close this issue.

> The question is, why there is no exception thrown. When I extend the MockitoExtension class (e.g. TestExtension extends MockitoExtension), I get a NoClassDefFoundError.

I don't understand this sentence. If you have questions, would you please put a code sample so I can understand you quickly?

**Closed by blindpirate** 2019-03-09 07:34 UTC
