### ISSUE TITLE
Type safe project accessor generation fails if root project and subproject names are the same

### ISSUE THREAD

**Issue by dmdashenkov** [gradle/gradle#18461] opened 2021-09-28 15:49 UTC
I've got a multi-project build. The root project is called `mc-java`. One of its direct subprojects is called `mc-java` as well.
When enabling the type-safe project accessors (by adding `enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")` in `settings.gradle.kts`), the build fails with an exception:
```
FAILURE: Build failed with an exception.

* What went wrong:
org.gradle.api.internal.catalog.GeneratedClassCompilationException: Unable to compile generated sources:
  - File RootProjectAccessor.java, line: 39, method getMcJava() is already defined in class org.gradle.accessors.dm.RootProjectAccessor
> Unable to compile generated sources:
    - File RootProjectAccessor.java, line: 39, method getMcJava() is already defined in class org.gradle.accessors.dm.RootProjectAccessor
```

If I change the name of the root project, the build passes.

### Expected Behavior

The build passes and the type-safe project accessors are generated.

### Current Behavior

An exception.

### Your Environment

Gradle v7.2.

**Comment by ljacomet** [comment] 2021-09-29 08:36
Closing as duplicate of #16608

**Closed by ljacomet** 2021-09-29 08:36 UTC
Labels: a:bug, closed:duplicate, in:project-accessors
