### ISSUE TITLE
Unable to use typesafe project accessors with modules having some specific name

### ISSUE THREAD

**Issue by StepByStepler** [gradle/gradle#27150] opened 2023-11-24 08:48 UTC
### Current Behavior

If we enable typesafe project accessors feature via `enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")` while having module named e.g. `version` or `factory`, then sync fails with code generation error:
```
org.gradle.api.internal.catalog.GeneratedClassCompilationException: Unable to compile generated sources:
  - File RootProjectAccessor.java, line: 24, incompatible types: org.gradle.accessors.dm.FactoryProjectDependency cannot be converted to org.gradle.api.internal.catalog.TypeSafeProjectDependencyFactory
  - File RootProjectAccessor.java, line: 29, getFactory() in org.gradle.accessors.dm.RootProjectAccessor cannot override getFactory() in org.gradle.api.internal.catalog.TypeSafeProjectDependencyFactory
      return type org.gradle.accessors.dm.FactoryProjectDependency is not compatible with org.gradle.api.internal.catalog.TypeSafeProjectDependencyFactory
  - File RootProjectAccessor.java, line: 29, incompatible types: org.gradle.accessors.dm.FactoryProjectDependency cannot be converted to org.gradle.api.internal.catalog.TypeSafeProjectDependencyFactory
  - File ProjectAccessorTestProjectDependency.java, line: 23, getFactory() in org.gradle.accessors.dm.ProjectAccessorTestProjectDependency cannot override getFactory() in org.gradle.api.internal.catalog.DelegatingProjectDependency
      return type org.gradle.accessors.dm.FactoryProjectDependency is not compatible with org.gradle.api.internal.catalog.TypeSafeProjectDependencyFactory
  - File ProjectAccessorTestProjectDependency.java, line: 23, incompatible types: org.gradle.accessors.dm.FactoryProjectDependency cannot be converted to org.gradle.api.internal.catalog.TypeSafeProjectDependencyFactory
```

### Expected Behavior

Typesafe project accessors don't break with some specific module names

### Context (optional)

I was trying to migrate my multi-module application from plain string dependencies to typesafe project accessors, and the first Gradle sync failed because I had module named `factory`
Also note that this is duplicate of https://github.com/gradle/gradle/issues/17379, but this issue is closed without being fixed

### Steps to Reproduce

1. Include the following lines into default `settings.gradle.kts`:
```
enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")
include(":factory")
```
2. Try to run `gradle :help` or sync Gradle in IntelliJ IDEA

### Gradle version

8.4

### Build scan URL (optional)

https://scans.gradle.com/s/6z244dtowtt7m

**Comment by cobexer** [comment] 2023-11-27 09:42
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #17379

Please add your use case and 👍 to that issue.
***
Thanks for bringing this to our attention! We reopened the original issue.

**Closed by cobexer** 2023-11-27 09:42 UTC
Labels: a:bug, to-triage
