### ISSUE TITLE
Adding the `--scan` option can produce cache misses due to changed order for the `Settings` buildscript classpath

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#22273] opened 2022-09-30 14:26 UTC
If a build applies a custom settings plugin that transitively applies the `com.gradle.enterprise` plugin with a particular version, then running the build with `--scan` can result in a different ordering of jars in the `Settings` buildscript classpath. This in turn can result in unexpected cache misses, since the classpath hash is different.

Note that this issue is about `--scan` causing cache misses for a build that already has the GE plugin applied. It is a separate issue that using `--scan` on a project _without_ the GE plugin applied will necessarily change the classpath and result in cache misses.

### Expected Behavior
Running a GE-enabled build with `--scan` can result in unexpected cache misses.

### Current Behavior
Running a GE-enabled build with `--scan` should not change build behaviour beyond publishing a build scan.

### Steps to Reproduce 

To see this behaviour, clone https://github.com/bigdaz/duplicate-ge-plugin-application.

##### Custom plugin sourced from included build
- Run `./gradlew noop`: [GE plugin is last in the classpath](https://scans.gradle.com/s/2diabfjvv7z2w/custom-values)
- Run `./gradlew noop --scan`: [GE plugin is 2nd last in the classpath](https://scans.gradle.com/s/tqjoxf2ezrwhw/custom-values)

##### Custom plugin sourced from repository
- Checkout the `published-plugin` branch.
- Publish the plugin to maven local: `./gradlew -p build-src publishToMavenLocal`
- Run the same 2 builds as above: same behaviour

##### Custom plugin applied using `apply: plugin`
- Checkout the `build-script-block` branch.
- If not already done, publish the plugin to maven local: `./gradlew -p build-src publishToMavenLocal`
- Run the same 2 builds as above: same behaviour

**Comment by runningcode** [comment] 2023-06-02 13:46
@bigdaz this has been on our board. Do you know if there is anything here being worked on?

**Comment by etiennestuder** [comment] 2023-06-04 17:20
@bigdaz @wolfs Between the two of you, can someone resolve this in an upcoming version of Gradle?

**Comment by sorin-florea** [comment] 2023-06-14 08:18
# Why
The [AutoAppliedGradleEnterprisePlugin](https://github.com/gradle/gradle/blob/c27c7a385f16f61bdfe4e49b22cb194255198ac5/subprojects/core/src/main/java/org/gradle/plugin/management/internal/autoapply/AutoAppliedGradleEnterprisePlugin.java#L27) (applied when using `--scan`) will be [filtered out](https://github.com/gradle/gradle/blob/ee5955d3c4acbcc6dd34e037514c6813d4195a52/subprojects/plugin-use/src/main/java/org/gradle/plugin/management/internal/autoapply/DefaultAutoAppliedPluginHandler.java#L79) if it is already applied or requested.

The problem is that transitive plugin dependencies are unknown because when the filtering happens, no [dependency resolution](https://github.com/gradle/gradle/blob/ee5955d3c4acbcc6dd34e037514c6813d4195a52/subprojects/plugin-use/src/main/java/org/gradle/plugin/management/internal/autoapply/DefaultAutoAppliedPluginHandler.java#L107) has occurred, yet.
# Workarounds
### Explicitly apply the GE plugin to the target project
This is the way we expect to have consistent plugin versions across all builds and is also the way we recommend applying the GE plugin in our documentation.

```
plugins {
   id("com.gradle.enterprise").version("3.13.3")
}
```


### Explicitly declare the plugin as a classpath buildscript dependency
The GE plugin can be declared as a buildscript classpath dependency without providing the version. Using `--scan` will no longer change the buildscript classpath, and the version of the GE plugin applied will be supplied by the custom plugin that transitively applies the GE plugin.

```
buildscript {
    dependencies {
        classpath "com.gradle:gradle-enterprise-gradle-plugin"
    }
}
```

# Solutions
Resolve buildscript/settings classpath before checking auto applied plugins
Gradle could do a resolution of the buildscript classpath before checking if the auto applied plugin needs to be applied. If it needs applying after resolving the classpath, the classpath would need to be re-resolved.

This will result in the classpath configuration being resolved twice when using `--scan` and a small performance hit.
## Questions
Can the resolution of the buildscript classpath fail and then pass when adding the auto-applied plugin? Is this a problem?

**Comment by etiennestuder** [comment] 2023-06-14 09:19
@sorin-florea // cc @wolfs 

`Explicitly apply the GE plugin to the target project`
I don't find this not feasible in practice since it means whenever you have a transitive dependency on the GE plugin, you also need to specify the GE plugin explicitly on the build _and_ make sure you declare the same GE plugin version in both places (unless I misunderstood the workaround).

`Explicitly declare the plugin as a classpath buildscript dependency`
This workaround does not have the problem that one needs to keep the two plugin versions in sync in the build. But, it seems too much to ask for, that we expect the user to add this declaration to their builds instead of only declaring the usual GE plugin application.

IMO, the problem should be solved on the Gradle side rather than requiring the user to have to go through these extra steps.

But... we should revisit this issue's severity and number of occurrences. It might not be justified to fix it if it does not happen often, and in the cases where it happens, we refer people to the `Explicitly declare the plugin as a classpath buildscript dependency` workaround. Let's collect feedback from @bigdaz and @runningcode on the cases where this happened in practice before a final decision. If we had to make a decision right now, I would suggest we simply add a section in the user manual that describes the workaround (buildscript classpath) and let the Solutions team know about it.

**Comment by runningcode** [comment] 2023-06-16 10:19
This happened once with the Nokee project since they had a set of included builds which included the GE plugin as a dependency. @jprinet spent some time investigating and reproducing it.

@jprinet I seem to recall it also happened with a customer once. Do you remember?

**Comment by jprinet** [comment] 2023-06-16 13:28
I have 2 cases in mind. They were basically applying GE plugin from a convention plugin with a different version than the one provided by the automated scripts if I remember correctly.
I think I was able to get that reproduced by running the automated scripts on [this project](https://github.com/jprinet/gradle-sample-included-build)

**Comment by etiennestuder** [comment] 2023-06-16 14:34
> They were basically applying GE plugin from a convention plugin with a different version than the one provided by the automated scripts if I remember correctly.

The scripts only apply the GE plugin if they are run with `-e`. It's unclear to me why the user of the scripts would use `-e` when the Gradle project already has the GE plugin applied (via convention plugin, composite build, or any other way).

**Comment by jprinet** [comment] 2023-06-16 14:39
They were not using the `-e` option but I think I used it to reproduce it.

**Closed** 2023-07-15 12:29 UTC
Labels: a:bug, in:build-scan
