### ISSUE TITLE
Task is never up-to-date and corrupts the output of the build

### ISSUE THREAD

**Issue by melix** [gradle/gradle#1254] opened 2017-01-25 14:08 UTC
The issue can be seen in the Gradle repository itself, when converting from a project that uses `GroovyCompile` to `JavaCompile`. The result of compilation is corrupted by `GroovyCompile` task, which is never up-to-date: it will delete the result of the `JavaCompile` task, because they share the same output directory (which is bad, but hey). Deleting the task history cache fixes the problem (delete `.gradle`).

### Expected Behavior

When a task has no source, but that files are deleted (state cleanup), we should write a new entry in the task history to make sure that the next time the task is up-to-date. It would not fix the inconsistency for the first run, though, because it would still delete the result of the `compileJava` task for the 1st time, but subsequent runs would be ok.

### Current Behavior

When the `:ide:compileGroovy` task is executed, in `org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter`, we see that some files have been removed, so it deletes the result of the `compileJava` task, which happens to execute _before_. The `deleted` flag is set to true, and the task outcome is set to `EXECUTED`. However, it seems that the task history is never updated, probably because the task will never be executed because it has no source. So the next time we run the build, files are again missing, and we delete the result from the `compileJava` task again. It's an infinite loop until we delete the `.gradle` directory, or disable explicitly the `compileGroovy` task.

### Context

Migrating from a project with Groovy sources to a project with Java sources, while keeping the `groovy` plugin for test sources (so, a `GroovyCompile` task still exists).

### Steps to Reproduce (for bugs)

On the Gradle build:

1. `./gradlew ide:compileGroovy`
2. edit `subprojects/ide/ide.gradle` and comment out the 2 `sourceSets` lines. This should effectively disable Groovy compilation because it doesn't have sources anymore. Only Java compilation should remain, which is fine because we only have `src/main/java`.
3. `./gradlew ide:compileGroovy`. See that the task is not up-to-date.
4. `./gradlew ide:compileGroovy`. See that the `compileJava` task is executed again because its output has been deleted by the `compileGroovy` cleanup. Then see that `compileGroovy` is executed, and deletes the output of `compileJava`.
5. delete `.gradle`
6. `./gradlew ide:compileGroovy` : no-source, everything is back to normal

Warning: the fact the `compileGroovy` task is not up-to-date is confusing. It doesn't execute any task action. So you can add whatever you want in a `doFirst` or `doLast`, it will *never* be executed, because the task has no sources! The only reason it says it has done some work is because it cleaned up the output of the `compileJava` task...

**Comment by Vampire** [comment] 2017-02-01 11:15
Does this mean, the output cleanup is only done if the task was run before according to task history? I'd consider that a bug actually. If you built before, then delete all input files and delete `.gradle` because of some other problem, the cleanup will not be done which is the original problem again that the cleanup should have solved.

Maybe I might suggest a different solution:
- Make compileJava and compileGroovy (and others that would also be affected) compile to dedicated directories
- Always wipe these directories if there is no source files, no matter if execution history exists for the task or not
- Have an additional task that Syncs the dedicated directories to the currently common output folder

**Comment by oehme** [comment] 2017-02-16 11:22
> Does this mean, the output cleanup is only done if the task was run before according to task history? 

No, the problem is that the cleanup does not update the task history. So next time it's gonna think it needs to clean up again.

I'm wondering though why the GroovyCompile task is doing stale cleanup at all. I thought we had moved this responsibility to the stale output cleaner which runs before all tasks. @bmuschko @wolfs can you shed some light on this?

> Make compileJava and compileGroovy (and others that would also be affected) compile to dedicated directories

That's the long term fix, but a breaking change.

**Comment by wolfs** [comment] 2017-02-16 11:27
@oehme We are not at the point of cleaning up stale output files in a generic manner. There is still some work to be done for that epic. See https://github.com/gradle/gradle/issues/821#issuecomment-280004256.

**Comment by Vampire** [comment] 2017-02-17 18:47
> > Does this mean, the output cleanup is only done if the task was run before according to task history?

> No, the problem is that the cleanup does not update the task history. So next time it's gonna think it needs to clean up again.

But why does then deleting `.gradle` work as a workaround here?
As far as I understood here, `.gradle` contains the task history and deleting it stops the task from cleaning up, no?

> > Make compileJava and compileGroovy (and others that would also be affected) compile to dedicated directories

> That's the long term fix, but a breaking change. 

I see.

**Comment by oehme** [comment] 2017-02-17 19:12
It works because after deleting .gradle the task no longer thinks that it used to have sources.

**Comment by Vampire** [comment] 2017-02-17 19:51
So the question to my question is yes, isn't it?
The cleanup is only done if the task knows it had input before.
The task know it had input before because it was executed before with sources.
If the task history is deleted because of some reason, the cleanup will never be done and the original problem is present again.

**Comment by oehme** [comment] 2017-02-17 21:29
If the history is lost the new build scoped stale file clean up will kick in. That's why I thought we had removed the task scoped one. But apparently that story is not completely done.

**Comment by Vampire** [comment] 2017-02-20 14:10
Ah, I see, that's nice then, thanks for the clarification. :-)

**Comment by wolfs** [comment] 2017-07-28 08:00
The reported problem has been fixed, since we now have different output directories for `compileJava` and `compileGroovy`. There may be a problem with detecting what the output files for a task are when having overlapping outputs.
I will close this issue. If there are some other use case where the problem manifests again, please create a new issue or reopen this one.

**Closed by wolfs** 2017-07-28 08:00 UTC
Labels: a:bug, affects-version:3.3, affects-version:3.4, in:incremental-build
