### ISSUE TITLE
Corrupt plugin jars end up in Gradle's local caches

### ISSUE THREAD

**Issue by britter** [gradle/gradle#20830] opened 2022-05-19 11:57 UTC
In some situations when plugins are produced from included builds it occationally happens that corrupt plugin jars end up in Gradle's local caches. These jars do not contain any class files and process ClassNotFoundException very early in the build. The only way to get the project working again is stopping all daemons and deleting all caches.

### Expected Behavior

Corrupt jars should never end up in Gradle's local jar cache. When this happens Gradle produces errors like the following:

```
Build file '/Users/john-does/my-project/module-a.gradle.kts' line: 3
Could not find implementation class 'Some_CustomPlugin' for plugin 'some.custom specified in jar:file:/Users/john-doe/.gradle/caches/jars-9/413b4785410ac2fca3b4c9075b4e8c3c/custom.jar!/META-INF/gradle-plugins/some.custom.properties.
> Some_CustomPlugin
```

### Current Behavior

For some reason Gradle sometimes publishes corrupt jars to the local jar cache.

### Context

We have several theories why this may happen

1. IntelliJ sync process running with a different Gradle version then defined in the Gradle Wrapper. A work around for this is adding a safe guard in the settings script that compares the current Gradle version with the version defined in the wrapper.
2. Switching branches with different wrapper versions on the branches

See also https://github.com/gradle/gradle-private/issues/3532

### Steps to Reproduce 

At this point we don't have a clear way to reproduce this reliably.

### Your Environment

Build scan URL:

**Comment by PerryAJ** [comment] 2022-05-19 17:33
We have hit this issue in our organization a number of times and it's caused some headaches.  We hit this error in both the IDE, as well as the gradle wrapper CLI on occassion.  We generally have success fixing the CLI build by running a clean and build of the included plugin build independently (e.g. `gradlew build --settings-file ./build-config-plugins/settings.gradle.kts`), and then running the project build as usual. However, Intellij often continues to fail in many of the cases where the CLI build was 'fixed'.  IDE version does not seem to be a factor (well, within reason - we have people on various 2021 and 2022

I'll make a note to try changing the gradle wrapper version and/or source (in the IDE config) and see if that offers success next time it happens to someone in our codebase.  Will report results here.

**Comment by hegyibalint** [comment] 2022-05-20 14:34
One workaround is to run the task with `--rerun-tasks`. It's not efficient, but it will solve the problem.

The situation might be improved by #20641.

**Comment by wolfs** [comment] 2022-06-01 09:17
One reason for this to happen on the Gradle build was the following:
This was a weird coincidence where two daemons were running (sync + command-line) and they happened to load `:build-logic:packaging:compileKotlin` from cache roughly at the same time, each deleting the outputs first then loading the files. The :jar task happened to run exactly when the class files were removed by the other daemon for the second time. This was the failure: https://ge.gradle.org/s/lkfyjtft6u5o6/failure#1.

**Comment by wolfs** [comment] 2022-06-29 15:18
This may be related to https://youtrack.jetbrains.com/issue/KT-52669/Full-rebuild-in-IC-exception-recovery-leaves-corrupt-IC-data
So there would be incorrect incremental compilation data if incremental compilation threw an exception. The problem exists for both the new and the  old incremental compilation.

**Comment by silverhammermba** [comment] 2022-11-15 17:11
I'm seeing this issue with our CI build. They are not containerized, so they share a gradle cache, which would be nice if the daemon/cache were at all reliable, but alas.

Running with `--no-daemon` seems to work around it.

**Comment by alllex** [comment] 2023-05-30 15:11
I stumbled upon this again. 

In my case, I just pulled fresh changes from remote and IDE started synching, because those included changes to the build logic. Since I wanted to run a specific Gradle task anyway, I opened the console and ran this task there (while IDEA was still synching).

I ended up fixing it with `--rerun-tasks` after the sync finished (and I killed all daemons just in case).

**Comment by alllex** [comment] 2023-05-30 15:13
Here is one of the other theories why this may be happening:
> This happens when two builds happen in parallel, e.g. you switch the branch, the IDE starts synchronizing and then you start a build from the command line. In this situation there is a chance that the same task is running in both builds at the same time overriding each others outputs. This results in a corrupted state that Gradle can’t recover without help.

**Comment by pbielicki** [comment] 2023-06-19 11:11
We just experienced another instance of (most probably) the same bug:
```
:some-module:some-plugin:inspectClassesForKotlinIC
Cannot access input property 'classFiles$kotlin_some_plugin_common' of task ':some-module:some-plugin:inspectClassesForKotlinIC'. Accessing unreadable inputs or outputs is not supported. Declare the task as untracked by using Task.doNotTrackState()
```
Stopping the Gradle wrapper healed the situation.

**Comment by abstratt** [comment] 2023-07-19 12:22
This PR tackles one of the potential vectors for corrupted JARs: https://github.com/gradle/gradle/pull/25566

**Comment by bamboo** [comment] 2023-10-02 18:36
A tentative fix is available via the `8.5-branch-bamboo_composite_lock_i-20231002175118+0000` Gradle distribution.

**Comment by pbielicki** [comment] 2023-10-20 08:58
This is what I got today? https://e.grdev.net/s/gdglgr7u7tkpo 😬 
`Could not find implementation class 'GebuildLoadTestPlugin' for plugin 'gebuild.load-test'`

@bamboo can you ptal? ☝️

**Comment by bamboo** [comment] 2023-11-07 12:25
Was that the only occurrence so far, @pbielicki?

**Comment by pbielicki** [comment] 2023-11-07 12:40
Yes - I removed the link because it was pointing to the non-public Develocity instance.
I'm not aware of any other instance of this issue and nobody else form the team has reported it.

**Comment by ljacomet** [comment] 2023-11-22 09:45
I was able to consistently reproduce this by updating the wrapper after a Gradle RC release in the terminal of IntelliJ IDEA. But it never happened for the 8.5 release cycle (RC1 to 3).

So for this reproducer, this issue seems to be fixed.

**Comment by alllex** [comment] 2023-11-22 10:51
As the issue does not appear anymore in the known reproducer scenarios, we are closing it.

**Closed by alllex** 2023-11-22 10:51 UTC
Labels: a:bug, in:configuration-cache

**Comment by bamboo** [comment] 2023-11-22 13:26
Thanks. I moved it back to the 8.5 RC1 milestone, when it was fixed.
