### ISSUE TITLE
NPE in `ShortCircuitEmptyConfigurationResolver` when resolving dependencies

### ISSUE THREAD

**Issue by kageiit** [gradle/gradle#5768] opened 2018-06-25 02:24 UTC
Seeing this stacktrace during execution

```
1: Task failed with an exception.
> Could not resolve all dependencies for configuration ':generated:project:runtimeClasspath'.
   > java.lang.NullPointerException (no error message)
* Exception is:
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':generated:project:runtimeClasspath'.
	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.wrapException(ErrorHandlingConfigurationResolver.java:96)
	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolveGraph(ErrorHandlingConfigurationResolver.java:68)
	... 110 more
Caused by: java.lang.NullPointerException
	at org.gradle.api.internal.artifacts.ivyservice.ShortCircuitEmptyConfigurationResolver.resolveGraph(ShortCircuitEmptyConfigurationResolver.java:83)
	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolveGraph(ErrorHandlingConfigurationResolver.java:66)
2: Task failed with an exception.
> Could not resolve all dependencies for configuration ':generated:project:compileClasspath'.
   > java.lang.NullPointerException (no error message)
* Exception is:
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':generated:project:compileClasspath'.
	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.wrapException(ErrorHandlingConfigurationResolver.java:96)
	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolveGraph(ErrorHandlingConfigurationResolver.java:68)
	... 33 more
Caused by: java.lang.NullPointerException
	at org.gradle.api.internal.artifacts.ivyservice.ShortCircuitEmptyConfigurationResolver.resolveGraph(ShortCircuitEmptyConfigurationResolver.java:83)
	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolveGraph(ErrorHandlingConfigurationResolver.java:66)
3: Task failed with an exception.
> Could not resolve all dependencies for configuration ':apps:app:debugRuntimeClasspath'.
   > java.lang.NullPointerException (no error message)
* Exception is:
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':apps:app:debugRuntimeClasspath'.
	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.wrapException(ErrorHandlingConfigurationResolver.java:96)
	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolveGraph(ErrorHandlingConfigurationResolver.java:68)
	... 33 more
Caused by: java.lang.NullPointerException
	at org.gradle.api.internal.artifacts.ivyservice.ShortCircuitEmptyConfigurationResolver.resolveGraph(ShortCircuitEmptyConfigurationResolver.java:83)
	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolveGraph(ErrorHandlingConfigurationResolver.java:66)
```

Does not occur on gradle 4.7. Seems to flakily repro on linux. Does not seem to repro as reliably on darwin.

**Comment by melix** [comment] 2018-06-25 09:19
Hi @kageiit ,

Do you have a link to a build scan? What flags are you using? `--parallel` could be a hint. However currently I don't see how this can be possible, line 83 of ShortCircuitEmptyConfigurationResolver is

```
delegate.resolveGraph(configuration, results);
```

However `delegate` cannot be null since the only place where it's initialized is in the constructor, and this ctor is called only one in `DefaultDependencyManagementServices`, with a non null value. So it could be a race condition where something tries to use a non-fully initialized resolver. However, since you're mentioning this happens during configuration (side note, resolving configurations during the _uh_ configuration phase is likely a performance problem), and that configuration doesn't happen concurrently, it seems unlikely.

**Comment by kageiit** [comment] 2018-06-25 14:39
@melix sorry it actually occurs during task execution

Here are the current flags we are using

```
# Enable parallel build
org.gradle.parallel=true

# Turn on the Daemon
org.gradle.daemon=true
```

Unfortunately we are unable to share a build scan of this as the code is private. Please let us know if we can help with any other info.

**Comment by melix** [comment] 2018-06-25 15:19
Right, thanks. This is extremely curious. At this point I have no clue how this could happen as the resolver instance doesn't escape... What JVMs are you using? Do you have an idea what is the frequency of this happening?

**Comment by kageiit** [comment] 2018-06-25 15:42
using open jdk on linux. orcale jdk on mac osx. It happenly 1 out of 3 times on linux and has happened on macosx only once so far in several tries

**Comment by kageiit** [comment] 2018-06-25 15:42
on linux
```
java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-1~bpo8+1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
```

on darwin
```
java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

**Comment by melix** [comment] 2018-06-25 15:45
Wow, 33% is a very high frequency. I guess you are not using any Java agent, or modified Gradle build?

**Comment by melix** [comment] 2018-06-25 15:46
Would also be nice to know if you are using any particular JVM flag.

**Comment by kageiit** [comment] 2018-06-25 16:20
not using any agents or modified gradle build. No special jvm flags either

**Comment by melix** [comment] 2018-06-26 16:27
Alright @kageiit , I'm lost. 

Unless the line numbers are off in the stack trace, I can't make any sense of this NPE. I tried to reproduce locally but failed (FTR, I'm developing under Linux too). The NPE can be triggered by `delegate` being null, but `delegate` is a final field. The only place where this delegate is set is here:

https://github.com/melix/gradle/blob/0cb4f688c01a8d043e3cb14bfa427fa478936d51/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultDependencyManagementServices.java#L280

And obviously, it's not `null`. So either the stack trace is lying, and the NPE is not where it seems to be, or the code being executed is not the one I'm testing (I'm using the checked out 4.8.1 tag, so unlikely), or the class code has been transformed (you said no).

If you ever manage to reproduce outside of your project and can share some data here, I would be extremely grateful.

**Comment by kageiit** [comment] 2018-06-26 16:49
Will do. We just downgraded to 4.7 for now to mitigate the issue. Might just wait for a later version of gradle to try again as the issue is very hard to repro in an isolated project

**Comment by ljacomet** [comment] 2018-08-22 09:09
Hello @kageiit,

Did you get a chance to try with Gradle 4.9?

**Comment by kageiit** [comment] 2018-08-22 14:09
Since 4.10 rc3 is out, was hoping to try with the latest. Will report back on status with 4.10

**Comment by ljacomet** [comment] 2018-08-28 15:46
@kageiit Gradle 4.10 is now release, please let us know if that makes the problem go away.

**Comment by kageiit** [comment] 2018-10-02 23:49
Same thing is happening on 4.10 as well

**Comment by hzsweers** [comment] 2018-12-09 03:51
Ping on this, as Gradle 5.0 is out now as well

**Comment by big-guy** [comment] 2018-12-09 05:06
@hzsweers are you saying you're still seeing this with 5.0?  If so, could you provide an updated stacktrace with 5.0?

**Comment by kageiit** [comment] 2018-12-09 13:11
Will try 5.0 and report back

**Comment by kageiit** [comment] 2019-01-15 04:51
Im running a staging job on our codebase with gradle 5.1.1 . Will report back in a week hopefully

**Comment by ljacomet** [comment] 2019-09-20 15:35
Just checking if you can confirm the problem disappeared?

**Comment by ljacomet** [comment] 2019-10-10 15:08
Closing as cannot reproduce

**Closed by ljacomet** 2019-10-10 15:08 UTC
Labels: a:bug, from:contributor, in:dependency-management
