### ISSUE TITLE
Task dependencies are ignored when declared in `projectsEvaluated` and `--configure-on-demand` is used

### ISSUE THREAD

**Issue by chali** [gradle/gradle#16707] opened 2021-04-02 21:29 UTC
I have this build file:
```
apply plugin: 'java'
task hello() {
    doLast {
        println("hello")
    }
}
gradle.projectsEvaluated {
    build.dependsOn 'hello'
}
```

I get different result when using `--configure-on-demand` option.

```
./gradlew build --configure-on-demand
Using gradle at '/Users/mchalupa/Projects/local/projects-evaluated/gradlew' to run buildfile '/Users/mchalupa/Projects/local/projects-evaluated/build.gradle':
Configuration on demand is an incubating feature.
BUILD SUCCESSFUL in 611ms
1 actionable task: 1 up-to-date
```

vs

```
./gradlew build
Using gradle at '/Users/mchalupa/Projects/local/projects-evaluated/gradlew' to run buildfile '/Users/mchalupa/Projects/local/projects-evaluated/build.gradle':
> Task :hello
hello
BUILD SUCCESSFUL in 560ms
2 actionable tasks: 1 executed, 1 up-to-date
```

Tested with:
```
------------------------------------------------------------
Gradle 6.8.3
------------------------------------------------------------

Build time:   2021-02-22 16:13:28 UTC
Revision:     9e26b4a9ebb910eaa1b8da8ff8575e514bc61c78

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.10 (Azul Systems, Inc. 11.0.10+9-LTS)
OS:           Mac OS X 10.16 x86_64
```

**Comment by jjohannes** [comment] 2021-04-13 10:33
Duplicate of #9489

**Closed by jjohannes** 2021-04-13 10:33 UTC
Labels: a:bug, in:configure-on-demand
