### ISSUE TITLE
Weird values in IncrementalTaskInputs when class is removed

### ISSUE THREAD

**Issue by alexey-tsvetkov** [gradle/gradle#3051] opened 2017-09-28 23:59 UTC
When a Kotlin class in `main` source set is removed, a `compileTestKotlin` task receives an instance of `IncrementalTaskInputs` containing "changes" of library dependencies (e.g. "guava.jar").

### Steps to reproduce

I have created a simple project to reproduce the issue: [alexey-tsvetkov/gradle-weird-changed-files
](https://github.com/alexey-tsvetkov/gradle-weird-changed-files)

Since no published version of Kotlin plugin logs `IncrementalTaskInputs` values, 
I've added the `pseudoCompile` task that "mirrors" inputs of the `compileTestKotlin` task,
and prints changes in inputs.

1. Run `./gradlew build`.
2. Delete `src/main/kotlin/Dummy.kt`.
3. Run `./gradlew build` again.

The `compileKotlin` task works as expected: it sees the removed `Dummy.kt` in its incremental inputs 
and removes the corresponding class file `Dummy.class`.

However the `pseudoCompile` task receives the following changes in incremental inputs:
```
Modified input files:
    /home/user/projects/gradleChangedFilesAreWeird/build/classes/kotlin/main/demo/DummyUtilKt.class
    /home/user/projects/gradleChangedFilesAreWeird/build/classes/kotlin/main/demo/Greeter.class
    /home/user/projects/gradleChangedFilesAreWeird/build/classes/kotlin/main/demo/KotlinGreetingJoiner.class
    /home/user/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/12.0/5bc66dd95b79db1e437eb08adba124a3e4088dc0/guava-12.0.jar
    /home/user/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.1.50/2bbd56ca7884b4f70db0f1d655d32ee6f205eaa5/kotlin-stdlib-1.1.50.jar
    /home/user/.gradle/caches/modules-2/files-2.1/org.testng/testng/6.8/ad4531b28715d39f73c49a56caf0c456cb34d48c/testng-6.8.jar
    /home/user/.gradle/caches/modules-2/files-2.1/com.google.code.findbugs/jsr305/1.3.9/40719ea6961c0cb6afaeb6a921eaa1f6afd4cfdf/jsr305-1.3.9.jar
    /home/user/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/13.0/919f0dfe192fb4e063e7dacadee7f8bb9a2672a9/annotations-13.0.jar
    /home/user/.gradle/caches/modules-2/files-2.1/junit/junit/4.10/e4f1766ce7404a08f45d859fb9c226fc9e41a861/junit-4.10.jar
    /home/user/.gradle/caches/modules-2/files-2.1/org.beanshell/bsh/2.0b4/a05f0a0feefa8d8467ac80e16e7de071489f0d9c/bsh-2.0b4.jar
    /home/user/.gradle/caches/modules-2/files-2.1/com.beust/jcommander/1.27/58c9cbf0f1fa296f93c712f2cf46de50471920f9/jcommander-1.27.jar
    /home/user/.gradle/caches/modules-2/files-2.1/org.yaml/snakeyaml/1.6/a1e23e31c424d566ee27382e373d73a28fdabd88/snakeyaml-1.6.jar
    /home/user/.gradle/caches/modules-2/files-2.1/org.hamcrest/hamcrest-core/1.1/860340562250678d1a344907ac75754e259cdb14/hamcrest-core-1.1.jar
Removed input files:
    /home/user/projects/gradleChangedFilesAreWeird/build/classes/kotlin/main/demo/Dummy.class
    /home/user/projects/gradleChangedFilesAreWeird/build/classes/kotlin/main/demo/DummyUtilKt.class
    /home/user/projects/gradleChangedFilesAreWeird/build/classes/kotlin/main/demo/Greeter.class
 /home/user/projects/gradleChangedFilesAreWeird/build/classes/kotlin/main/demo/KotlinGreetingJoiner.class
    /home/user/.gradle/caches/modules-2/files-2.1/org.hamcrest/hamcrest-core/1.1/860340562250678d1a344907ac75754e259cdb14/hamcrest-core-1.1.jar
```

None of these files except the `Dummy.class` were changed, so I don't think they should be in `IncrementalTaskInputs` (also they are not present with Gradle 3.0).

### Context

Kotlin incremental compilation relies on incremental inputs from Gradle to detect changes in its inputs.
These irrelevant files in incremental inputs prevent Kotlin from incrementally compiling test files
when source in main is removed, and incremental compilation of tests is extremely important
for Kotlin project developers.

### Environment
 * Build scan after initial build: https://scans.gradle.com/s/kigefo2kvmv2o
 * Build scan after `Dummy.kt` is removed: https://scans.gradle.com/s/nsacqsfxvbzfw/timeline

**Comment by alexey-tsvetkov** [comment] 2017-09-29 01:07
Ok, it seems that the issue is known https://github.com/gradle/gradle/issues/1931

**Comment by oehme** [comment] 2017-09-29 07:46
Duplicate of #1931

**Closed by oehme** 2017-09-29 07:46 UTC
