### ISSUE TITLE
Ability to use a private key for maven-publish plugin.

### ISSUE THREAD

**Issue by dmodoomsirius** [gradle/gradle#1071] opened 2016-12-27 00:25 UTC
### Expected Behavior

As stated on [https://issues.gradle.org/browse/GRADLE-3472](https://issues.gradle.org/browse/GRADLE-3472) it would be great if we could publish to maven using sftp and a private key.  
https://issues.gradle.org/browse/GRADLE-3473

### Current Behavior

As stated by @mark-vieira on the forums it only supports [username and password auth ](https://discuss.gradle.org/t/support-ssh-protocol-for-maven-publish-just-like-maven/17892/2?u=dmodoomsirius)

### Context

Adding this feature would make it so we don't have to put a username and password in a gradle.properties to be able to publish to a remote maven.

### Your Environment

 * Build scan URL:

**Comment by dmodoomsirius** [comment] 2017-03-25 22:24
I can't wait for this to happen. That will make my job easier and I will be able to not allow passwords only keys for users again.

**Comment by dmodoomsirius** [comment] 2017-10-28 02:05
any updates on this feature?

**Comment by damnhandy** [comment] 2019-04-13 18:33
Looks like #1263 is a dupe of this issue and there's a PR associated it with it. Not sure if it's made it into a release build or not yet.

**Comment by bigdaz** [comment] 2019-05-23 20:20
Closing as a duplicate of #1263, which is a little more general but would encompass this use case.

**Closed by bigdaz** 2019-05-23 20:20 UTC
Labels: a:feature, from:contributor, in:publishing-plugin
