### ISSUE TITLE
6.8 uses Project.group instead of MavenPublication.groupId for dependencies in a POM

### ISSUE THREAD

**Issue by anuraaga** [gradle/gradle#15768] opened 2021-01-13 00:53 UTC
### Expected Behavior

Dependency declarations in published POM / module.json should use `MavenPublication.groupId` if set.

### Current Behavior

Dependency declarations in published POM / module.json are using `Project.group`

### Context

To workaround https://github.com/gradle/gradle/issues/847, I have generally been setting project.group to a value different from the desired Maven groupId as per the recommendation in https://github.com/gradle/gradle/issues/847#issuecomment-619950147

That has stopped working in 6.8 it seems, project.group is being used for dependency declarations in POMs (not the actual artifact declaration).

### Steps to Reproduce 

```
git clone https://github.com/open-telemetry/opentelemetry-java/
cd opentelemetry-java
./gradlew publishToMavenLocal
cat api/all/build/publications/mavenPublication/pom-default.xml
```

Note the dependency is

```
<dependencies>
    <dependency>
      <groupId>io.opentelemetry.api</groupId>
      <artifactId>context</artifactId>
      <version>0.12.0-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
```

but it should be

```
<dependencies>
    <dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>context</artifactId>
      <version>0.12.0-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
```

This was working until 6.7

Configuration in

https://github.com/open-telemetry/opentelemetry-java/blob/master/build.gradle#L457
https://github.com/open-telemetry/opentelemetry-java/blob/master/api/build.gradle#L2

### Your Environment

Build scan URL:

**Comment by ljacomet** [comment] 2021-01-13 09:57
Closing as duplicate of #15731

**Closed by ljacomet** 2021-01-13 09:57 UTC
Labels: a:regression, closed:duplicate, from:contributor
