### ISSUE TITLE
Gradle 8.3-rc-1 creates compileJava Task on empty Kotlin project

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#25841] opened 2023-07-20 15:26 UTC
### Expected Behavior

No tasks other than `:help` created.

`gradlew` on the repro will output (on 8.2.1)
```
task ':help' was created for root project 'lazyConfiguration-gradle83_creates_compileJava'.
Task graph ready.
task ':clean' was created for root project 'lazyConfiguration-gradle83_creates_compileJava'.
```

### Current Behavior

`gradlew` on the repro will output (on 8.3-rc-1)
```
task ':compileJava' was created for root project 'lazyConfiguration-gradle83_creates_compileJava'.
task ':help' was created for root project 'lazyConfiguration-gradle83_creates_compileJava'.
Task graph ready.
task ':clean' was created for root project 'lazyConfiguration-gradle83_creates_compileJava'.
```

### Context (optional)

`:clean` task is created because https://github.com/gradle/gradle/issues/20864, that can be ignored.

### Steps to Reproduce

1. Clone https://github.com/TWiStErRob/repros/tree/main/gradle/lazyConfiguration-gradle83_creates_compileJava
2. `gradlew`

### Gradle version

Gradle 8.3-rc-1

### Gradle version that used to work

Gradle 8.2.1

### Build scan URL (optional)

8.2.1: https://gradle.com/s/hzr74ht2bofwo
8.3-rc-1: https://gradle.com/s/f7qm7d776h63g

**Comment by ov7a** [comment] 2023-07-21 08:36
Thank you for reporting this!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by jvandort** [comment] 2023-07-24 21:42
This change in behavior has been caused by this PR: https://github.com/gradle/gradle/pull/25126

The PR removes an internal API, `beforeLocking`, which was used to lazily calculate the attribute value for `org.gradle.jvm.version` on `Configuration`s. Now, we use the built-in provider-based feature of `AttributeContainer`s to achieve laziness. Prior to this PR, the attribute in question was not present in the container until the owning configuration was "locked", either by resolving that Configuration, or consuming the project via a dependency. 

This is relevant since the Kotlin Gradle Plugin relies on _copying_ the attributes of a configuration in order to publish variants. Prior to this change, the `org.gradle.jvm.version` attribute was not present on the copied configuration, meaning it was not visible to their copying mechanism. Now, with this change, the attribute is present in the container at the time of copying. This new behavior is more correct than before, however given that Kotlin is eagerly coping attributes, which sources its value from the `compileJava` task, this new behavior occurs. 

In general, the solution here would be in the Kotlin Gradle Plugin. They will need to perform attribute container copy operation _later_, only upon publication, or otherwise find a method to avoid copying attributes altogether.

**Closed by jvandort** 2023-07-24 21:42 UTC
Labels: a:regression, in:java-plugins, :wave: team-triage

**Comment by wilkinsona** [comment] 2023-07-25 07:16
> In general, the solution here would be in the Kotlin Gradle Plugin. They will need to perform attribute container copy operation later, only upon publication, or otherwise find a method to avoid copying attributes altogether.

Has an issue been opened on the Kotlin side with this recommendation? I'd like to be able to watch it so that we can keep track of when the regression will be fixed.

**Comment by TWiStErRob** [comment] 2023-07-25 09:41
@jvandort thanks a lot for the detailed explanation!

Opened https://youtrack.jetbrains.com/issue/KT-60664 for them.
