### ISSUE TITLE
Rich version constraints degraded when defined via ComponentMetadataHandler

### ISSUE THREAD

**Issue by dansanduleac** [gradle/gradle#12458] opened 2020-03-06 11:08 UTC
I'm using `ComponentMetadataHandler` to add a variant to components that are normally just Maven POMs, via `addVariant`.

I set a custom `Usage `attribute on this variant that I also set on a configuration which I'm using to resolve these dependencies.

In this variant, I only add *dependencies* on other coordinates, all of which will have this variant added in the end by the same code, and these dependencies all have rich constraints of the form `{strictly [$min, $max]; prefer $recommended}`.
I mark all such added dependencies with `DirectDependencyMetadata#endorseStrictVersions`.

### Expected Behavior

Gradle imports all these rich constraints, as if they had been discovered from module metadata files.
There is no extra resolution going on trying to find all modules within a given range, instead the preferred version is directly selected if it satisfies all other constraints.

### Current Behavior

I'm seeing a weird situation where, even though I add rich "strictly" + "prefer" constraints in this variant, in the final resolution I end up with some selectors having the plain version of these constraints.
e.g. if I add a dep on `foo:bar:{strictly [1.0, 1.3[; prefer 1.1}`, I have two lines in my dependencyInsight result, one with the actual constraint I defined, but also another that just says `foo:bar:[1.0, 1.3[`.
**Therefore it seems like these are sometimes treated like plain require constraints, as if imported from a POM metadata.**
This happens even if I call `DirectDependencyMetadata#endorseStrictVersions` on all of the dependencies I add into my variant.
I believe this is then causing gradle to look up all matching versions unnecessarily, as it doesn't know about the preferred version anymore, and so it tries all the possible versions in the range.

### Context

Trying to backfill metadata about [product dependencies](https://github.com/palantir/sls-packaging#product-dependencies) for a bunch of products, where a product is identified as a maven coordinate.
This is a bit domain specific, but broadly speaking, a product publishes:
* a tgz file that contains a `deployment/manifest.yml` where it declares min, max and recommended versions for other product dependencies
* an empty POM, no dependencies

I'm trying to use ComponentMetadataHandler to read these manifest files and create gradle dependencies matching the product dependencies from each product's manifest file.

### Steps to Reproduce 

Can only reproduce internally for now as we don't publish any products externally :(

### Your Environment

Build scan URL:

**Comment by dansanduleac** [comment] 2020-03-06 11:17
Update: here's what a redacted dependencyInsight looks like into one of these.
I've actually tried to add these strictly version constraints via actual constraints (rather than dependencies) but that didn't change the outcome:

```
com.palantir.a:a:0.43.3 FAILED
   Selection reasons:
      - Was requested : From the product dependencies of com.palantir.b:b:0.43.5
   Failures:
      - Could not resolve com.palantir.a:a:0.43.3.
          - Cannot find a version of 'com.palantir.a:a' that satisfies the version constraints:
               Dependency path 'com.palantir.current:current:1.0' --> 'com.palantir.a:a:0.43.6' because of the following reason: belongs to platform com.palantir.a:a_:0.43.6
               Dependency path 'com.palantir.current:current:1.0' --> 'com.palantir.b:b:0.43.5' --> 'com.palantir.a:a:0.43.3' because of the following reason: From the product dependencies of com.palantir.b:b:0.43.5
               Constraint path 'com.palantir.current:current:1.0' --> 'com.palantir.b:b:0.43.5' --> 'com.palantir.a:a:{strictly [0.43.3,0.999.0[; prefer 0.43.3}' because of the following reason: From the product dependencies of com.palantir.b:b:0.43.5
               Dependency path 'com.palantir.current:current:1.0' --> 'com.palantir.b:b:0.43.5' --> 'com.palantir.c:c:2.38.0' --> 'com.palantir.a:a:0.44.4' because of the following reason: From the product dependencies of com.palantir.c:c:2.38.0
               Constraint path 'com.palantir.current:current:1.0' --> 'com.palantir.b:b:0.43.5' --> 'com.palantir.c:c:2.38.0' --> 'com.palantir.a:a:{strictly [0.44.4,0.999.0[; prefer 0.44.4}' because of the following reason: From the product dependencies of com.palantir.c:c:2.38.0
               Dependency path 'com.palantir.current:current:1.0' --> 'com.palantir.a:a_:0.43.6' --> 'com.palantir.a:a:0.43.6' because of the following reason: belongs to platform com.palantir.a:a_:0.43.6

com.palantir.a:a:0.43.3 FAILED
\--- com.palantir.b:b:0.43.5
     \--- devEnv

com.palantir.a:a:0.43.6 FAILED
   Selection reasons:
      - By constraint : belongs to platform com.palantir.a:a_:0.43.6
      - Forced
   Failures:
      - Could not resolve com.palantir.a:a:0.43.6. (already reported)

com.palantir.a:a:0.43.6 FAILED
\--- devEnv

com.palantir.a:a:0.44.4 FAILED
   Selection reasons:
      - Was requested : From the product dependencies of com.palantir.c:c:2.38.0
   Failures:
      - Could not resolve com.palantir.a:a:0.44.4. (already reported)

com.palantir.a:a:0.44.4 FAILED
\--- com.palantir.c:c:2.38.0
     +--- devEnv (requested com.palantir.c:c:2.16.0)
     \--- com.palantir.b:b:0.43.5
          \--- devEnv

com.palantir.a:a:[0.43.3,0.999.0[ FAILED
   Selection reasons:
      - By constraint : From the product dependencies of com.palantir.b:b:0.43.5
   Failures:
      - Could not resolve com.palantir.a:a:{strictly [0.43.3,0.999.0[; prefer 0.43.3}. (already reported)

com.palantir.a:a:{strictly [0.43.3,0.999.0[; prefer 0.43.3} -> [0.43.3,0.999.0[ FAILED
\--- com.palantir.b:b:0.43.5
     \--- devEnv

com.palantir.a:a:[0.44.4,0.999.0[ FAILED
   Selection reasons:
      - By constraint : From the product dependencies of com.palantir.c:c:2.38.0
   Failures:
      - Could not resolve com.palantir.a:a:{strictly [0.44.4,0.999.0[; prefer 0.44.4}. (already reported)

com.palantir.a:a:{strictly [0.44.4,0.999.0[; prefer 0.44.4} -> [0.44.4,0.999.0[ FAILED
\--- com.palantir.c:c:2.38.0
     +--- devEnv (requested com.palantir.c:c:2.16.0)
     \--- com.palantir.b:b:0.43.5
          \--- devEnv
```

**Comment by bmuskalla** [comment] 2020-04-15 09:32
@dansanduleac Can you please share how you set up the rich version constraints in your metadata rule? I'm trying to come up with a simple reproducer for this problem but it looks like the `prefer` version is properly kept around. Maybe you can use this snippet and incorporate changes to make it fail.

$ gradle dependencies
```
foo
\--- junit:junit:4.13
     \--- org.hamcrest:hamcrest-core:{strictly [1.0, 1.3[; prefer 1.1} -> 1.1
```


build.gradle
```
plugins {
    id 'java-library'
}

repositories {
    mavenCentral()
}

class AddVariants implements ComponentMetadataRule {

    void execute(ComponentMetadataContext context) {
        context.details.addVariant("bug", "runtime") {
            attributes {
                attribute(Attribute.of("more", String), "better")
            }
            withDependencies {
                removeIf { it.name ==  "hamcrest-core"}
                add("org.hamcrest:hamcrest-core") {
                    because "bug"
                    version {
                        strictly "[1.0, 1.3["
                        prefer "1.1"
                    }
                    endorseStrictVersions()
                }
            }
        }
    }
}

configurations {
    foo {
        attributes {
            attribute(Attribute.of("more", String), "better")
        }
    }
}


dependencies {
    components {
        withModule("junit:junit", AddVariants)
    }
    foo('junit:junit:4.13')
}
```

**Comment by dansanduleac** [comment] 2020-04-20 16:18
Thanks for looking into it @bmuskalla!
What we had was some of these additional variants adding dependencies onto other such newly-added variants, so it might be that.
That being said, we've worked around it for now so I don't want to waste your time grasping at straws since your example works.

If we end up running into it again, I will come back with an actual reproducible example.

**Comment by bmuskalla** [comment] 2020-04-20 18:30
Thanks @dansanduleac for the feedback. While I'd love to dig into the root cause of this, without much information this may take some time. Let's close this for now. And please, if you encounter this again, I'm more than happy to reopen this with more information.

**Closed by bmuskalla** 2020-04-20 18:30 UTC
Labels: @jvm, a:bug, from:contributor, in:dependency-management
