### ISSUE TITLE
Investigate `Detected overflow` in native logger

### ISSUE THREAD

**Issue by l0rinc** [gradle/gradle#17396] opened 2021-06-09 12:39 UTC
Related to https://gradle.slack.com/archives/C0WTFHWT1/p1618124196122000

Appears regularly, searching Slack I see:

* > Apr 19, 2021 10:46:43 AM net.rubygrapefruit.platform.internal.jni.NativeLogger log
INFO: Detected overflow for /Users/lorinc/IdeaProjects/dotcom
* https://gradle.slack.com/archives/C03A0MT6S/p1617742738187800?thread_ts=1617317203.149000&cid=C03A0MT6S
* https://gradle.slack.com/archives/C09LZKUCB/p1619014298003400?thread_ts=1618970464.001600&cid=C09LZKUCB
* https://gradle.slack.com/archives/C0WTFHWT1/p1615276741042000

---
cc: @gradle/execution

**Comment by wolfs** [comment] 2021-11-18 14:38
Let's close this and re-open when we see this again.

**Comment by Jocce-Nilsson** [comment] 2024-10-22 12:29
We found this issue while [investigating strange time differences](https://github.com/gradle/dv/issues/40705) between TC build time and what DV showed as build time. 
It turns out to be this error, causing stdout logs to grow to over 200MB. 

In the linked issue, there are a few, recent, examples of the error.
@wolfs @lptr

**Comment by lptr** [comment] 2024-10-24 16:27
This is curious. The code emitting the log message is this:

https://github.com/gradle/gradle-fileevents/blob/c1f9aba9cc9f70b282f5c1850b1bb948ce25d1b4/src/main/cpp/generic_fsnotifier.cpp#L37

```cpp
void AbstractServer::reportOverflow(JNIEnv* env, const u16string& path) {
    logToJava(LogLevel::INFO, "Detected overflow for %s", utf16ToUtf8String(path).c_str());
    jstring javaPath = env->NewString((jchar*) path.c_str(), (jsize) path.length());
    env->CallVoidMethod(watcherCallback.get(), watcherReportOverflowMethod, javaPath);
    env->DeleteLocalRef(javaPath);
    getJavaExceptionAndPrintStacktrace(env);
}
```

The `LogLevel::INFO` is ours, and it _should_ get mapped to `java.util.logging`'s `Level.INFO` here:

https://github.com/gradle/gradle-fileevents/blob/8a378f97e20f97a09e3ab6676d7eaa2154cd41e9/src/main/java/org/gradle/fileevents/internal/NativeLogger.java#L11-L35

Which in turn then gets mapped to... I'm not entirely sure what, probably here:

https://github.com/gradle/gradle/blob/eeaaa1a450e2641c887eda2c80ede27338c372f6/platforms/core-runtime/logging/src/main/java/org/gradle/internal/logging/source/JavaUtilLoggingSystem.java#L34-L48

And by default, unless `--info` is specified, these `INFO` logs should never get to `stdout`. Yet it seems at least some of the time they do... 🤔

**Comment by lptr** [comment] 2024-10-24 16:33
To rule out JUL to SLF4J bridging problems, I put the following in a `build.gradle.kts` and ran `gradle help`:

```kotlin
println("Hello from println!")
java.util.logging.Logger.getLogger("main").info("Hello from info log!")
java.util.logging.Logger.getLogger("main").warning("Hello from warning log!")
```

As expected, it printed the following:

```text
Hello from println!
Hello from warning log!
```

So I think logging with `INFO` via JUL works just fine. My suspicion is that the problem is somewhere on the native side, i.e. we are actually not calling JUL with `INFO`, but with something else here:

```java
LOGGER.log(LogLevel.values()[level].getLevel(), message);
```

The lookup doesn't fail, because then we'd be calling `LOGGER.log()` with a `null` level, which would throw. So we know one of the valid values for `level` are passed in, but I strongly suspect it is not corresponding to `LogLevel.INFO`... 🤔

**Comment by lptr** [comment] 2024-10-24 16:43
Hm, we actually see the logged levels on the console for each log message when running tests:

```text
18:40:25.844  FINE    Event flags: 0x11000 (ID 428988109) for '/private/var/folders/mt/w8xt125171b77qvh3q10jhd00000gn/T/spock_can_set_log_level_b_1_tmpDir17679547430312204778/can set log level by #action/root/changed.txt'
18:40:27.582  INFO    Event queue overflow, dropping all events
18:40:27.584  SEVERE  Couldn't queue event: OVERFLOW (EVENT_QUEUE) at null
18:40:27.620  INFO    Event queue overflow, dropping all events
18:40:27.620  SEVERE  Couldn't queue event: OVERFLOW (EVENT_QUEUE) at null
18:40:27.620  SEVERE  Couldn't queue event: TERMINATE
```

Etc. These are all correct. So if the messages logged at `LogLevel::INFO` actually get logged to JUL as `Level.INFO`, and the translation between JUL `Level.INFO` messages actually get handled as SLF4J `Level.INFO` messages in Gradle's bridging, then... where does this thing get printed?

**Comment by lptr** [comment] 2024-10-25 05:44
I looked at the logs from an actual build in TeamCity that did produce 300 MB+ of logs on the console. It's full of messages like this:

```text
[14:36:23]W:	 [Step 8/15] INFO: Detected overflow for /home/tcagent1/agent/work/3ca4d96b62d7bc0e/perfetto-proto/build/protos/perfetto-43.2/src/traced/probes/ftrace/test/data/android_flounder_lte_LRX16F_3.10.40/events/nvmap/nvmap_pin
[14:36:23]W:	 [Step 8/15] Oct 09, 2024 12:31:19 PM net.rubygrapefruit.platform.internal.jni.NativeLogger log
[14:36:23]W:	 [Step 8/15] INFO: Detected overflow for /home/tcagent1/agent/work/3ca4d96b62d7bc0e/gradle/plugins/keycloak-theme/build/classes/kotlin/main/gradle/kotlin/dsl/accessors
[14:36:23]W:	 [Step 8/15] Oct 09, 2024 12:31:19 PM net.rubygrapefruit.platform.internal.jni.NativeLogger log
[14:36:23]W:	 [Step 8/15] INFO: Detected overflow for /home/tcagent1/agent/work/3ca4d96b62d7bc0e/app-lib-object-storage-googlecloud/build/classes/groovy/test/com/gradle
[14:36:23]W:	 [Step 8/15] Oct 09, 2024 12:31:19 PM net.rubygrapefruit.platform.internal.jni.NativeLogger log
```

I think the first `W:` means "warning" by TeamCity, meaining the message came from `stderr`. Then there are two kinds of lines, the first says the name of the logger (`...NativeLogger`) and the method being called (`log`), the second prints the actual message.

This is a weird format that gave me an idea. What if there's a `logging.properties` file on the plugin classpath for this particular build, and it configures JUL messages to go to `stderr`?

**Comment by lptr** [comment] 2024-10-25 05:45
I think the solution should be to use SLF4J for logging. It's a simple change, and the only reason we used JUL in the first place was to avoid adding a new dependency to `native-platform`. But the code now lives in its own repository, and is Gradle-internal, so we can easily do the switch.

**Comment by lptr** [comment] 2024-10-25 09:21
Here we go:

- https://github.com/gradle/gradle-fileevents/issues/20

**Closed** 2024-11-05 15:49 UTC
Labels: closed:unreproducible
