### ISSUE TITLE
Antlr plugin doesn't declare dependencies to sources compatible with sourcesJar

### ISSUE THREAD

**Issue by emmanuelguerin** [gradle/gradle#31800] opened 2024-12-17 17:33 UTC
### Current Behavior

There seems to be a dependency missing in the antlr plugin when combine with sourceJars:
```
plugins {
    id "java-library"
    id "antlr"
}

java {
    withSourcesJar()
}
```

When running:

```
gw assemble

> Task :sourcesJar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':sourcesJar' (type 'Jar').
  - Gradle detected a problem with the following location: '/Users/e.guerin/tmp/gradlebug/build/generated-src/antlr/main'.
    
    Reason: Task ':sourcesJar' uses this output of task ':generateGrammarSource' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':generateGrammarSource' as an input of ':sourcesJar'.
      2. Declare an explicit dependency on ':generateGrammarSource' from ':sourcesJar' using Task#dependsOn.
      3. Declare an explicit dependency on ':generateGrammarSource' from ':sourcesJar' using Task#mustRunAfter.
    
    For more information, please refer to https://docs.gradle.org/8.10.2/userguide/validation_problems.html#implicit_dependency in the Gradle documentation.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 594ms
2 actionable tasks: 1 executed, 1 up-to-date
```

### Expected Behavior

The assemble command should work without error.

### Self-contained Reproducer Project

https://github.com/emmanuelguerin/antlr-gradle-bug

### Gradle version

8.10.2

**Comment by jbartok** [comment] 2024-12-19 13:08
This issue will be closed as a duplicate of

* #19555

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

Please see: 
* https://github.com/gradle/gradle/issues/19555#issuecomment-1593252653

**Closed by jbartok** 2024-12-19 13:08 UTC
Labels: a:bug, to-triage
