### ISSUE TITLE
Gradle 8.7 produces 0% coverage reports with Jacoco for Gradle TestKit tests

### ISSUE THREAD

**Issue by tomkoptel** [gradle/gradle#28734] opened 2024-04-08 18:13 UTC
### Current Behavior

The coverage report produces 0% coverage report.

### Expected Behavior

The coverage report produces 80% coverage report.

## Gradle Slack thread
https://www.linen.dev/s/gradle-community/t/16901231/after-updating-to-gradle-8-7-jacoco-agent-no-longer-instrume#9e5064a2-3e1c-4c1c-b598-54f52063abba

## What are you trying to accomplish?
I want to produce a coverage report for tests implemented with the help of the Gradle Test Kit.

## Possible root cause
> When there is an agent, we should disable instrumentation or fail, see this comment:
[AbstractInjectedClasspathInstrumentationStrategy.kt](https://github.com/gradle/gradle/blob/5b5514c90d99f506f77d0b789b5d38dcf4bafd57/platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/configurationcache/initialization/AbstractInjectedClasspathInstrumentationStrategy.kt#L29-L31). But with changes we don't do that.

### Steps to Reproduce

1. Clone https://github.com/tomkoptel/jacoco-gradle-testkit/
2. Run `./gradlew :jacocoTestCoverageVerification -PdisableFix=false --rerun-tasks`
3. Run `./gradlew :jacocoTestCoverageVerification -PdisableFix=true --rerun-tasks`

### Gradle version

8.7

### Your Environment (optional)

IntelliJ IDEA 2023.3.6 (Community Edition)
Build #IC-233.15026.9, built on March 21, 2024
Runtime version: 17.0.10+1-b1087.23 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.jetbrains.space (233.15026.16)
  com.github.copilot (1.5.1.5285)
Kotlin: 233.15026.9-IJ
Java: 17.0.7

**Comment by tomkoptel** [comment] 2024-04-08 19:23
According to @asodja this one is a duplicate of https://github.com/gradle/gradle/issues/28729

**Comment by ov7a** [comment] 2024-04-09 12:37
This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/28729

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

**Closed by ov7a** 2024-04-09 12:37 UTC
Labels: a:bug, to-triage
