### ISSUE TITLE
Possibility to apply external plugin from init script

### ISSUE THREAD

**Issue by radoslaw-panuszewski** [gradle/gradle#30891] opened 2024-10-13 19:18 UTC
### Expected Behavior

I would like to introduce a callback (something like `buildscriptClasspathAvailable`) that can be used to apply imperative plugins from the init script:

```kotlin
rootProject {
    buildscript {
        dependencies {
            classpath("com.example:my-gradle-plugin:1.0.0")
        }
    }

    buildscriptClasspathAvailable {
        apply(plugin = "com.example.my-plugin")
    }
}
```

### Current Behavior (optional)

Runnable example: https://github.com/radoslaw-panuszewski/apply-plugin-from-init-script-example

The following init script:
```kotlin
rootProject {
    buildscript {
        dependencies {
            classpath("com.example:my-gradle-plugin:1.0.0")
        }
    }

    apply(plugin = "com.example.my-plugin")
}
```
fails with:
```
* What went wrong:
Plugin with id 'com.example.my-plugin' not found.
```

But it works after moving the plugin application to `build.gradle.kts`.

### Context

I have a Gradle plugin that configures other plugins. I want to apply it to all the builds within the enterprise via init script.

Slack thread: https://gradle-community.slack.com/archives/CA745PZHN/p1728315714563879

#### afterEvaluate
We can wrap the plugin application into `afterEvaluate`:
```kotlin
afterEvaluate {
    apply(plugin = "com.example.my-plugin")
}
```
but some plugins need to be applied before evaluation.

#### withPlugin
We can apply the plugin in reaction to other plugin:
```kotlin
pluginManager.withPlugin("base") {
    apply(plugin = "com.example.my-plugin")
}
```
but it needs at least one other plugin to be explicitly applied.

#### init script dependency
We can add external plugin to the init script dependencies:
```kotlin
import com.example.MyPlugin

initscript {
    dependencies {
        classpath("com.example:my-gradle-plugin:1.0.0")
    }
}

rootProject {
    apply<MyPlugin>()
}
```
but:
* transitive dependencies of `my-plugin` do not participate in the buildscript's classpath resolution and conflicts are not handled
* `my-plugin` and all its dependencies are loaded with a different classloaer than plugins applied from `build.gradle.kts`. As a result, the only way to configure other plugins' extensions is to use reflection

**Comment by abstratt** [comment] 2024-10-15 13:22
This issue will be closed as a duplicate of

* #1322

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

**Closed by abstratt** 2024-10-15 13:22 UTC
Labels: a:feature, to-triage
