### ISSUE TITLE
Tooling: NPE in BuildProgressLogger

### ISSUE THREAD

**Issue by vladsoroka** [gradle/gradle#2556] opened 2017-07-21 10:10 UTC
The original request can be found at https://youtrack.jetbrains.com/issue/IDEA-176336

> I have been using IntelliJ with gradle but upgrading IntelliJ to 2017.2 is causing problems. When I try and load the project in IntelliJ with both gradle 4.0 and 4.0.1, I get the following error:

>Error:Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-4.0.1-all.zip'.

>I get this error when I try to do a project refresh.

```
Caused by: org.gradle.internal.exceptions.LocationAwareException
    at org.gradle.initialization.DefaultExceptionAnalyser.transform(DefaultExceptionAnalyser.java:74)
    at org.gradle.initialization.MultipleBuildFailuresExceptionAnalyser.transform(MultipleBuildFailuresExceptionAnalyser.java:47)
    at org.gradle.initialization.StackTraceSanitizingExceptionAnalyser.transform(StackTraceSanitizingExceptionAnalyser.java:30)
    at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:68)
    at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:42)
    at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:50)
    at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
    at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
    at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
    at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
    at org.gradle.util.Swapper.swap(Swapper.java:38)
    at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
    at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
    at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
    at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
    at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
    at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.NullPointerException
    at org.gradle.internal.progress.BuildProgressLogger.beforeComplete(BuildProgressLogger.java:87)
    at org.gradle.internal.progress.BuildProgressFilter.beforeComplete(BuildProgressFilter.java:107)
```

### Your Environment
IntelliJ 2017.2
Gradle 4.0 and 4.0.1

**Comment by vladsoroka** [comment] 2017-07-21 13:10
The OP said that the clean install of IDEA helped: https://youtrack.jetbrains.com/issue/IDEA-176336#comment=27-2334538
So, you can close the issue if you wish.

**Comment by bmuschko** [comment] 2017-07-21 17:42
Hhmm, for now I'd probably close the issue. Please reopen the issue if you see this happening again.

**Closed by bmuschko** 2017-07-21 17:42 UTC

**Comment by sprengerst** [comment] 2017-07-26 07:20
I also have the same problem using gradle wrapper:
Error:Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-4.0.1-all.zip'.

**Comment by jjohannes** [comment] 2017-07-26 07:34
@sprengerst Do you get the same stacktrace (NPE at `BuildProgressLogger.java:87`)?

Is there a chance that you can provide a reproducible example?

**Comment by sprengerst** [comment] 2017-07-26 08:09
@jjohannes 

I'm sorry it's based on company sources, I think it has to do with the update to 4.0.1. 

Now I downgraded back to 3.5 and Intelli Idea asks for:
Error:com/android/builder/model/NativeAndroidProject : Unsupported major.minor version 52.0. Please use JDK 8 or newer.
and interprets my gradle project as Android project. 

It's pretty confusing, because it worked very good with 3.5 for a long time, after updating to 4.0.1 in gradle wrapper it errored. I also reinstalled everything and used a local gradle distribution, with the same result. I will investigate further and post details if I encounter some.

**Comment by jjohannes** [comment] 2017-07-26 08:16
@sprengerst thanks for investigating further. If you have any insights that you can not share here, feel free to send a mail to _jendrik at gradle.com_.

**Comment by sprengerst** [comment] 2017-07-26 08:26
@jjohannes One thing that could be interesting is that "gradlew" is working correctly, this issue happens only at pressing the "Sync" btn in Intellij Idea, so maybe this is could be an Intellij 2017.2 issue. I will try to downgrade Idea.

**Comment by sprengerst** [comment] 2017-07-26 08:43
The idea downgrade did it. Now I'm running at 2017.1.5 instead of 2017.2. I have to work a little bit now, lost too much time on this atm ^^, but maybe this could also be a hint for you @jjohannes. Is gradle plugin working on 2017.2 at all?

**Comment by CrazyCoder** [comment] 2017-07-26 08:50
@sprengerst  it's a different problem: https://youtrack.jetbrains.com/issue/IDEA-176192

**Comment by sprengerst** [comment] 2017-07-26 08:51
@CrazyCoder kk. Thanks for this link.
