### ISSUE TITLE
`implementaion` dependency is leaking onto the consumer/client project 

### ISSUE THREAD

**Issue by RoopGuron** [gradle/gradle#8634] opened 2019-02-27 00:20 UTC
....Gradle version 4.10.2

### Expected Behavior
As per Gradle dependency docs...dependencies declared as `implementation` are **not** added to the client/consumer project classpath...
But I am seeing this happen for me, and is critical as I want to use `@ConditionalClass` annotations.

### Context
I am building a custom `Spring-boot-autoconfigurer` and `starter` and using `@ConditionalClass ` to configure the environment.

### Steps to Reproduce (for bugs)
I have a `project_a` that has the following dependency...
`implementation "io.micrometer:micrometer-registry-prometheus:1.1.2"`
and then there is `project_b` that brings in `project_a` as a dependency.

The project_b always gets the `io.micrometer:micrometer-registry-prometheus:1.1.2` jar.
I tried the `enableFeaturePreview("IMPROVED_POM_SUPPORT")` flag as well.

![image](https://user-images.githubusercontent.com/10160285/53456212-6025e880-39e2-11e9-9b95-03e168925b6b.png)

**Comment by melix** [comment] 2019-02-27 07:59
`implementation` dependencies are not added to the _compile classpath_ of consumers. So I just suspect what you are resolving is _not_ the `compileClasspath` configuration, but something else.

A reproducer would help diagnosing.

**Comment by RoopGuron** [comment] 2019-02-27 18:58
@Melix thanks for the quick response...
**Yes** the _compileClasspath_ does not have the dependency...but it is **leaking** into the `runtime classpath`.
Since I want to turn things on and off based on classpath...this is not good .....
Is this the expected behavior ...If Yes then it really sucks....
Where is the **equivalent** of **maven dependency**` <optional>true</optional>` that **prevents** dependency **leaking** over to the consumer project on any classpath.

Thanks...

**Comment by melix** [comment] 2019-02-27 19:29
Your tone is not acceptable.

This is the expected behavior. An `implementation` dependency is a dependency that is required at compile time, and at runtime, but should not leak to compile of consumers because it's an implementation detail (doesn't leak in the API). If you want something that is _only_ required at compile time, but not required at runtime, you can use `compileOnly`. As for optional dependencies, they are again a different beast, and a (better) solution ships in 5.3.

**Closed by melix** 2019-02-27 19:29 UTC
Labels: from:contributor, in:dependency-management, waiting-for:contributor
