### ISSUE TITLE
Gradle can't parse POM. Unable to resolve version for dependency 'org.springframework:spring-core:jar'

### ISSUE THREAD

**Issue by dengayevskiy** [gradle/gradle#1453] opened 2017-02-23 20:08 UTC
Gradle can't parse one of the pom's my project depends on. 

What I'm importing in my build.gradle:

`compile(group: 'com.services', name: 'social-client', version: "1.25") { transitive = false; force = true }`

**com.services:social-client POM** (where we have dependency on spring-core)

    <parent>
        <artifactId>infra-social-service</artifactId>
        <groupId>com.services</groupId>
        <version>1.25</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>social-client</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.services</groupId>
            <artifactId>social-common</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-eureka</artifactId>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <artifactId>spring-boot-starter-logging</artifactId>
                    <groupId>org.springframework.boot</groupId>
                </exclusion>
            </exclusions>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-feign</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jdk8</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-core</artifactId>
        </dependency>

        <dependency>
            <artifactId>slf4j-api</artifactId>
            <groupId>org.slf4j</groupId>
        </dependency>

        

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.github.tomakehurst</groupId>
            <artifactId>wiremock</artifactId>
        </dependency>

        <dependency>
            <groupId>org.easytesting</groupId>
            <artifactId>fest-assert-core</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-log4j2</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>
</project>

**It's Parent POM header** (where spring-core version is resolved from spring-boot-starter-parent) 

    <groupId>com.services</groupId>
    <artifactId>infra-social-service</artifactId>
    <version>1.25</version>
    <packaging>pom</packaging>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.4.1.RELEASE</version>
    </parent>

When I try to build project I got such error:

21:51:15.603 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Could not resolve all dependencies for configuration ':common:detachedConfiguration5'.

21:51:15.604 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Could not resolve com.playtika.services:social-client:1.25.

21:51:15.605 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   Required by:
21:51:15.606 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]       project :common
21:51:15.606 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > Could not resolve com.playtika.services:social-client:1.25.
21:51:15.606 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]       > Could not parse POM http://artifactory.corp/artifactory/repo/com/playtika/services/social-client/1.25/social-client-1.25.pom
21:51:15.606 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]          > Unable to resolve version for dependency 'org.springframework:spring-core:jar'

### Your Environment

 * Build scan URL: 
https://scans.gradle.com/s/qagzkvzsna2qi

**Comment by bmuschko** [comment] 2017-02-23 22:38
[The dependency `com.playtika.services:social-client:1.25` simply doesn't exist in Maven Central.](https://search.maven.org/#search%7Cga%7C1%7Csocial-client) That's reason why it cannot be resolved. Is that maybe a dependency that is produced by your organization?

**Comment by dengayevskiy** [comment] 2017-02-23 22:49
> Is that maybe a dependency that is produced by your organization?

Yes, it is. And that is why it should't be present in Maven Central.

**Comment by bmuschko** [comment] 2017-02-23 23:06
Oh, I get it. The POM you provide _is_ the one for `social-client`. Did you already run `gradle dependencies -is` to see if you get additional information? My guess is that Spring Boot uses a BOM which we don't support natively at the moment. You might have to apply the [Pivotal Dependency Management](https://github.com/spring-gradle-plugins/dependency-management-plugin) plugin as well. In the long run we want to [support BOMs natively](https://github.com/gradle/gradle/issues/1162).

**Comment by dengayevskiy** [comment] 2017-02-23 23:13
> You might have to apply the Pivotal Dependency Management plugin as well

I did it already through [Spring Boot Gradle plugin](http://docs.spring.io/spring-boot/docs/current/reference/html/build-tool-plugins-gradle-plugin.html) but it doesn't help.

**Comment by bmuschko** [comment] 2017-02-24 00:32
In that case it's hard for me to reproduce the issue as I don't have access your binary repository and the published artifacts. Do you get more information when executing with `-s`?

**Comment by dengayevskiy** [comment] 2017-02-24 10:56
> Do you get more information when executing with -s?

No( The same thing: 

`Caused by: org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser.MetaDataParseException: Could not parse POM http://artifactory.corp/artifactory/repo/com/playtika/services/social-client/1.25/social-client-1.25.pom
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser.AbstractModuleDescriptorParser.parseDescriptor(AbstractModuleDescriptorParser.java:48)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser.AbstractModuleDescriptorParser.parseMetaData(AbstractModuleDescriptorParser.java:39)
        at org.gradle.api.internal.artifacts.repositories.resolver.MavenResolver.parseMetaDataFromResource(MavenResolver.java:212)
        at org.gradle.api.internal.artifacts.repositories.resolver.MavenResolver.parseMetaDataFromResource(MavenResolver.java:56)
        at org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver.parseMetaDataFromArtifact(ExternalResourceResolver.java:204)
        at org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver.resolveStaticDependency(ExternalResourceResolver.java:175)
        at org.gradle.api.internal.artifacts.repositories.resolver.MavenResolver.doResolveComponentMetaData(MavenResolver.java:110)
        at org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver$RemoteRepositoryAccess.resolveComponentMetaData(ExternalResourceResolver.java:455)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CacheLockReleasingModuleComponentsRepository$LockReleasingRepositoryAccess$2.run(CacheLockReleasingModuleComponentsRepository.java:78)
        at org.gradle.internal.Factories$1.create(Factories.java:25)
        at org.gradle.cache.internal.DefaultCacheAccess.longRunningOperation(DefaultCacheAccess.java:239)
        at org.gradle.cache.internal.DefaultCacheAccess.longRunningOperation(DefaultCacheAccess.java:310)
        at org.gradle.cache.internal.DefaultPersistentDirectoryStore.longRunningOperation(DefaultPersistentDirectoryStore.java:137)
        at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.longRunningOperation(DefaultCacheFactory.java:183)
        at org.gradle.api.internal.artifacts.ivyservice.DefaultCacheLockingManager.longRunningOperation(DefaultCacheLockingManager.java:48)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CacheLockReleasingModuleComponentsRepository$LockReleasingRepositoryAccess.resolveComponentMetaData(CacheLockReleasingModuleComponentsRepository.java:76)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository$ResolveAndCacheRepositoryAccess.resolveComponentMetaData(CachingModuleComponentRepository.java:312)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.BaseModuleComponentRepositoryAccess.resolveComponentMetaData(BaseModuleComponentRepositoryAccess.java:49)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.memcache.InMemoryCachedModuleComponentRepository$CachedAccess.resolveComponentMetaData(InMemoryCachedModuleComponentRepository.java:82)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.resolveComponentMetaData(ErrorHandlingModuleComponentRepository.java:94)
        ... 114 more
Caused by: org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser.UnresolvedDependencyVersionException: Unable to resolve version for dependency 'org.springframework:spring-core:jar'
`

I think the problem is close to BOMs. POM that can't be parsed 'social-client-1.25.pom' depends on it's parent POM -> 'infra-social-service-1.25.pom' which has dependency on spring-boot-starter-parent BOM. In previous version of social service(1.24) developers didn't use BOM and everything worked perfectly. 

I've tried to handle this with dependency management plugin but the problem still persists

```
dependencyManagement  {
       overriddenByDependencies = false
       imports  {
            mavenBom 'org.springframework.boot:spring-boot-starter-parent:1.4.3.RELEASE'
       }
       dependencies  {
            dependency 'com.playtika.services:social-client:1.25'
       }
}
```

**Comment by yetanotherion** [comment] 2017-02-24 11:12
Did you try https://github.com/nebula-plugins/nebula-dependency-recommender-plugin ?
With something like 
```
dependencyRecommendations {
        mavenBom module: 'org.springframework.boot:spring-boot-starter-parent:1.4.3.RELEASE'
}
```

**Comment by bmuschko** [comment] 2017-02-24 13:03
I am not very familiar with the Pivotal Dependency Management plugin. You might want to ask over there. I'd help you but I don't really have a reproducible example that I could play around with.

**Comment by dengayevskiy** [comment] 2017-02-24 13:08
Ok, I'll try make reproducible example with public repo.

**Comment by superbobry** [comment] 2017-02-24 14:51
@dengayevskiy JFYI the Pivotal plugin didn't work (crashed) for our internal BOMs, but nebula-dependency-recommender did.

**Comment by bmuschko** [comment] 2017-02-24 17:26
Thanks, @dengayevskiy. I am sure that'll help.

**Comment by dengayevskiy** [comment] 2017-02-24 21:43
@yetanotherion, thanks for your advise but it did not help either ;(

**Comment by wilkinsona** [comment] 2017-02-25 20:54
@superbobry If you could [open an issue](https://github.com/spring-gradle-plugins/dependency-management-plugin/issues) about that, I'd be happy to try and fix it

**Comment by bmuschko** [comment] 2017-02-27 15:13
@dengayevskiy Looks like you opened an issue for the Pivotal Dependency Management plugin. I am going to close this issue for now. Should you determine that the issue is actually a problem of Gradle core then we can reopen.

**Closed by bmuschko** 2017-02-27 15:13 UTC
Labels: a:question, from:contributor, in:dependency-management
