### ISSUE TITLE
Provide a way to read a version catalog from `.toml` and then override some of the values. 

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#26029] opened 2023-08-04 20:54 UTC
### Expected Behavior

Allow overriding values found in a version catalog toml file via the DSL. 

in `settings.gradle.kts` : 
```kotlin
dependencyResolutionManagement {
    versionCatalogs {
        create("myCatalog") {
            from( file("myCatalog.versions.toml"))
            library("alias", "group", "artifact").withoutVersion() // should override anything in myCatalog.versions.toml if present.
        }
  }
}
```

### Current Behavior (optional)

It appears that `from( file(` will always override any local DSL defined versions/libraries.

### Context

This is useful in many scenarios, including writing tests.

**Comment by ov7a** [comment] 2023-08-07 08:43
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

According to our [docs](https://docs.gradle.org/current/userguide/platforms.html#sec:overwriting-catalog-versions), you should be able to override the version (at least) and it shouldn't matter how you import the catalog.

**Comment by big-guy** [comment] 2023-09-11 16:33
dupe of #26104

**Closed by big-guy** 2023-09-11 16:33 UTC
Labels: a:feature, in:dependency-version-catalog
