### ISSUE TITLE
Gradle tasks fail with apparent file locking issue when used with a winsshfs mounted drive.

### ISSUE THREAD

**Issue by mhardin18** [gradle/gradle#2416] opened 2017-07-07 18:31 UTC
### Expected Behavior
Expect tasks to complete as normal, gradle clean for instance fails.

### Current Behavior

```
14:15:59.976 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
14:15:59.976 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
14:15:59.976 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
14:15:59.976 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
14:15:59.977 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] java.io.IOException: Incorrect function
14:15:59.977 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Incorrect function
14:15:59.977 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
14:15:59.977 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
14:15:59.977 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.UncheckedIOException: java.io.IOException: Incorrect function
14:15:59.977 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:43)
```

### Context
Project is located on a winsshfs mounted drive.  I have tried using the wrapper, daemon, no daemon. I have attempted passing osgi.locking=none as vm arg.  

### Steps to Reproduce (for bugs)
Any project will do.
The key to the issue is that it is a winsshfs mounted network drive (this is a necessary evil for my environment at the moment) that the project is located on. Gradle is located locally on my Win 10 hard drive.  Execution via a bash shell or windows command prompt produces same result. 

### Your Environment
https://scans.gradle.com/s/cfmtm53bhcn3w
[fail.txt](https://github.com/gradle/gradle/files/1131954/fail.txt)
[stack.txt](https://github.com/gradle/gradle/files/1131956/stack.txt)

**Comment by bmuschko** [comment] 2017-07-10 20:03
Could you please provide the full stack trace by running with `-s`?

@lacasseio Any chance you can try to reproduce the issue?

**Comment by lacasseio** [comment] 2017-07-11 14:40
@mhardin18 Was it working previously? Or is this the first time and you are getting this error?

I'm under the impression the winsshfs driver may not implement all functions required by Java `FileChannel#tryLock` method. We will keep debugging once we have more information.

**Comment by mhardin18** [comment] 2017-07-11 15:04
@bmuschko I'm not getting any more info out of using the -s option than is already in the stack.txt attachment. If I'm not doing it right please let me know.

@lacasseio This is the first time.  I should point out that I originally ran into this issue with [Buildship ](https://bugs.eclipse.org/bugs/show_bug.cgi?id=519342). But after working with things I began to realize it was a gradle issue, not directly buildship. 

In order to get Eclipse to work with the winsshfs driver it is necessary to add osgi.locking=none to the jvm args. I've attempted this with gradle but it did not have any effect. 

Let me know what else I can provide.

**Comment by bmuschko** [comment] 2017-07-11 15:13
> In order to get Eclipse to work with the winsshfs driver it is necessary to add osgi.locking=none to the jvm args.

Where exactly did you add the JVM args? Please be aware that you are working with at least two different JVM process: the Gradle process and one or many daemon processes.

**Comment by mhardin18** [comment] 2017-07-11 15:34
I've tried multiple different approaches (none of which may be correct), adding it to the command line such as:
$ gradle clean -s --no-daemon -Dosgi.locking=none

Adding it to the task in the build file:
    jvmArgs = ["-Xosgi.locking=none"]

I probably tried a few other ways that I don't recall.

**Comment by bmuschko** [comment] 2017-07-11 15:49
Can you try add it to the environment variable `GRADLE_OPTS`?

**Comment by mhardin18** [comment] 2017-07-11 15:57
Not sure if I did this correctly, I added it as an environment variable and then attempted to execute:

`hardin003@USMCD1OLP122 MINGW64 /m/workspace/master/Kranz/K4_Commons (master)
$ gradle clean
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Unrecognized option: -Xosgi.locking=none

hardin003@USMCD1OLP122 MINGW64 /m/workspace/master/Kranz/K4_Commons (master)
$ declare -x GRADLE_OPTS="-Dosgi.locking=none"

hardin003@USMCD1OLP122 MINGW64 /m/workspace/master/Kranz/K4_Commons (master)
$ gradle clean

FAILURE: Build failed with an exception.

* What went wrong:
java.io.IOException: Incorrect function
> Incorrect function

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.741 secs
`

**Comment by lacasseio** [comment] 2017-07-11 16:04
I have a feeling `osgi.locking` is an Eclipse specific flag and would have no effect on Gradle. The Buildship plugin delegates everything to Gradle. I assume Eclipse have a certain mechanism to skip any locking.

**Comment by lacasseio** [comment] 2017-07-11 17:56
I when down the rabbit hole and looked at the [JDK locking code for Windows](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/windows/native/sun/nio/ch/FileDispatcherImpl.c#l385), [`LockFileEx` code in ReactOS](https://doxygen.reactos.org/d6/df9/dll_2win32_2kernel32_2client_2file_2lock_8c.html#ae3beb7b7854a0265f7f7564b50af8b61), and [`dokany`'s locking code](https://github.com/dokan-dev/dokany/blob/master/sys/lock.c). My feeling is this issue isn't related to Gradle. Instead, it seems to be an issue with `win-sshfs` or `dokany` driver regarding the overlapped IO nature of `LockFileEx` (asynchronous).

I would suggest you provide a stronger case for us to fix this directly in Gradle or raise the issue on [`win-sshfs`](https://github.com/Foreveryone-cz/win-sshfs) or [`dokany`](https://github.com/dokan-dev/dokany) project itself. Note that [locking in `win-sshfs` log an action error and simply return NTSUCCESS](https://github.com/Foreveryone-cz/win-sshfs/blob/devel/Sshfs/Sshfs/SftpFilesystem.cs#L1424-L1428). Either of those won't play well with Gradle as no real locking seems to take place which will cause corruption on concurrent access.

An alternative would be to move all files that could potentially lock to a file system that supports such feature (aka local file system) with the [`--project-cache-dir` flag and possibly the `--gradle-user-home` flag](https://docs.gradle.org/current/userguide/gradle_command_line.html).

I will not proceed with more debugging and will close this issue as not actionable. Feel free to provide more information if required.

**Closed by lacasseio** 2017-07-11 17:56 UTC
Labels: a:bug, from:contributor, in:core

**Comment by xiaopao2014** [comment] 2022-10-08 15:42
It's 2022 i meet same issue when i open an gradle project which in SSHFS mounted file system, i got some error like below.
I found a work round, it works well if we use the "Mapping Network Driver" in Window 10.

```
X:\work5\workspace\rk3588\vendor\ruijie\common\libs\OPSTurbo\.gradle\checksums\checksums.lock is locked by some "unknown" process 

```
