### ISSUE TITLE
Worker executor does not support null values

### ISSUE THREAD

**Issue by alexey-tsvetkov** [gradle/gradle#7573] opened 2018-10-30 02:20 UTC
Consider the following task:
```
// buildSrc/src/main/java/MyCustomTask.java
import org.gradle.api.Action;
import org.gradle.api.DefaultTask;
import org.gradle.api.tasks.*;
import org.gradle.workers.*;

import javax.inject.Inject;

class MyCustomTask extends DefaultTask {
    String myMessage;

    private final WorkerExecutor workerExecutor;

    @Inject
    public MyCustomTask(WorkerExecutor workerExecutor) {
        super();
        this.workerExecutor = workerExecutor;
    }

    @TaskAction
    public void run() {
        workerExecutor.submit(MyCustomRunnable.class, new Action<WorkerConfiguration>() {
            @Override
            public void execute(WorkerConfiguration workerConfiguration) {
                workerConfiguration.params(myMessage);
            }
        });
    }

    public static class MyCustomRunnable implements Runnable {
        private final String message;

        @Inject
        public MyCustomRunnable(String message) {
            super();
            this.message = message;
        }

        @Override
        public void run() {
            System.out.println(message);
        }
    }
}
```

And the following build script:
```
// build.gradle

task printHelloWorld(type: MyCustomTask) {
    myMessage = "Hello, World!"
}

task printNull(type: MyCustomTask) {
    myMessage = null
}

```

Running `printHelloWorld` prints "Hello, World!".
Running `printNull` fails with NPE.

Scan with the stacktrace: https://scans.gradle.com/s/segkpbzwzjdvg/failure?openFailures=WzBd&openStackTraces=WzEse31d#top=0

Expected behaviour: I think null values are useful for passing optional values, and they should be supported.

**Comment by k-mack** [comment] 2018-10-30 04:33
Similar to, if not the same as, #2405.

**Comment by oehme** [comment] 2018-10-30 12:50
Yep, duplicate of #2405

**Closed by oehme** 2018-10-30 12:50 UTC
