### ISSUE TITLE
Stubbed API classes break constant expressions

### ISSUE THREAD

**Issue by ThiporKong** [gradle/gradle#925] opened 2016-11-25 17:45 UTC
`public final` [constant expressions](http://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.28) cannot be used in `switch` statements anymore after stubbing of API classes.

### Steps to Reproduce (for bugs)
```gradle
plugins {
    id 'jvm-component'
    id 'java-lang'
}

model {
    components {
        def aSrc = Files.createTempDirectory("a-src").toFile()
        new File(aSrc, "A.java").text = """
public class A {
    public static final String HALLO = "Hallo";
    public static final int HELLO = 4711;
}
"""

        def bSrc = Files.createTempDirectory("b-src").toFile()
        new File(bSrc, "B.java").text = """
public class B {
    public static void main(String[] args) {
        switch (args[0]) {
        case A.HALLO:
        }
        
        switch (args.length) {
        case A.HELLO:
        }
    }
}
"""

        a(JvmLibrarySpec) {
            sources.java.source.srcDir aSrc
        }
        b(JvmLibrarySpec) {
            sources.java.source.srcDir bSrc
            dependencies.library 'a'
        }
    }
}
```
yields

```
C:\Users\tk09\AppData\Local\Temp\b-src3724112288021808042\B.java:5: error: constant string expression required
        case A.HALLO:
              ^
C:\Users\tk09\AppData\Local\Temp\b-src3724112288021808042\B.java:9: error: constant expression required
        case A.HELLO:
              ^
2 errors
```
### Your Environment
Gradle 3.2.1, JDK 1.8

**Comment by astellingwerf** [comment] 2016-11-27 19:31
Isn't this a duplicate of #819 (as PRed by me in #848)?

**Comment by eriwen** [comment] 2016-11-28 17:00
This looks like a duplicate indeed. Please follow #819.

**Closed by eriwen** 2016-11-28 17:00 UTC
