### ISSUE TITLE
Provider.orElse does not detect task dependency through its orElse argument

### ISSUE THREAD

**Issue by kelemen** [gradle/gradle#27133] opened 2023-11-23 12:22 UTC
### Current Behavior

If  you are setting `myProvider1.orElse(myProvider2)` as an input to task , then tasks required to be run by `myProvider2` are not executed even if `myProvider2` is used causing error when running the task depending on the previously mentioned composite provider.

### Expected Behavior

If the value of `myProvider1` is unavailable, then the task required to run for `myProvider2` should be used as a dependency,

### Context (optional)

My use-case is that I simply want to be able to override some values using Gradle properties (in which case the task for the `orElse` should not run). However, normally those values are not overridden, in which case the task for the `orElse` task must run. That is, my specific case would be solved, if this worked for Gradle properties (including transformed ones) at least.

I tried reproducing this with multiple Gradle versions, and can reproduce it with all of them (8.2.1, 8.4, 8.5-rc-3).

### Steps to Reproduce

See  the simple [build.gradle.kts](https://gist.github.com/kelemen/415443a075dbd728b3dc3dfc6237e06c) (which works with any `settings.gradle.kts`) example for reproduction of the issue, and run `./gradlew clean task2`. The issue can be worked around by replacing `compositeValue` in the script with the expression provided in the comment.

### Gradle version

8.4

**Comment by cobexer** [comment] 2023-11-23 13:50
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #24141

Please add your use case and 👍 to that issue.

**Closed by cobexer** 2023-11-23 13:50 UTC
Labels: a:bug, to-triage
