### ISSUE TITLE
PasswordCredentials are incompatible with configuration cache

### ISSUE THREAD

**Issue by tcrawford-figure** [gradle/gradle#23979] opened 2023-02-20 21:04 UTC
### Expected Behavior
When publishing with configuration-cache in Gradle 8+, `PasswordCredentials` provided via code like the following fails:
```kotlin
credentials {
    username = findProperty("nexusUser")?.toString() ?: System.getenv("NEXUS_USER")
    password = findProperty("nexusPass")?.toString() ?: System.getenv("NEXUS_PASS")
}
```

This fails with the following message which gives no clear indication that the password credentials are incompatible with the configuration cache:
```
* What went wrong:
Execution failed for task ':my-project:publishMavenPublicationToMavenRepository'.
> The following Gradle properties are missing for 'maven' credentials:
    - mavenUsername
    - mavenPassword
```

As far as I can tell, this appears to reverse functionality that was supported in Gradle 7.6. 

### Current Behavior
When publishing with the configuration-cache given `PasswordCredentials` provided via code, the build should succeed or, if this should truly be incompatible with the configuration cache, a better warning or documentation should be provided. I did not see anything in the documentation that warned of publishing incompatibility with the configuration cache in gradle 8 docs.

### Context
I am trying to publish to my company's internal artifact repository and have not been able to with configuration cache enabled. 

#### Assumed temporary workaround
It seems like adding the following allows me to publish with the configuration cache flag enabled for now:

```kotlin
tasks {
    publish {
        notCompatibleWithConfigurationCache(
            "Gradle reports 'The following Gradle properties are missing for 'maven' credentials'"
        )
    }
}
```

### Steps to Reproduce 
Create a project that publishes to a repository that requires `username` and `password` credentials and try running the following command:

```
./gradlew clean build publish --parallel --build-cache --configuration-cache
```

**Comment by eskatos** [comment] 2023-03-01 10:09
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/23979

Please add your use case and 👍 to that issue.

----

See https://github.com/gradle/gradle/issues/24040#issuecomment-1446526136

**Closed by eskatos** 2023-03-01 10:09 UTC
Labels: closed:duplicate

**Comment by abstratt** [comment] 2023-03-01 15:04
Minor point, but the behavior you are seeing is supposed to be in 7.6 as well, @tcrawford-figure. In 7.5, there was no support for Maven publish with configuration cache enabled.
