### ISSUE TITLE
Self-referencing property results in StackOverflowError

### ISSUE THREAD

**Issue by aohanhongzhi** [gradle/gradle#26729] opened 2023-10-13 03:21 UTC
### Current Behavior

![image](https://github.com/gradle/gradle/assets/37319319/0133f081-ad87-46a0-b63f-876cce287213)

![image](https://github.com/gradle/gradle/assets/37319319/02d8fff1-9fb9-4b36-9db3-ac6b6f6dfa5d)

### Expected Behavior

correct

### Context (optional)

https://github.com/aohanhongzhi/JavalinDemo-Kotlin

### Steps to Reproduce

just run `./gradlew build --stacktrace`

### Gradle version

7.4.2 and 8.4

### Build scan URL (optional)

https://gradle.com/s/7443w56vbo65e

### Your Environment (optional)

https://github.com/aohanhongzhi/JavalinDemo-Kotlin

**Comment by aohanhongzhi** [comment] 2023-10-13 12:23
I solve the problem, I found that this issue is due to the definition of two identical variable names

<img width="1435" alt="image" src="https://github.com/gradle/gradle/assets/37319319/b38d1640-86e6-4673-8d80-5abd30fb5005">

**Comment by ov7a** [comment] 2023-10-16 08:35
Thank you for providing a valid report.

The issue is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before a fix is made.

***

The error message should be improved to point at the cyclic dependency.

**Comment by aohanhongzhi** [comment] 2023-10-18 02:49
> Thank you for providing a valid report.感谢您提供有效的报告。
> 
> The issue is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before a fix is made.该问题在相关团队的积压工作中，但 Gradle 的这一领域目前不是重点领域，因此可能需要一段时间才能进行修复。
> 
> The error message should be improved to point at the cyclic dependency.应改进错误消息以指向循环依赖项。

yes , I think so, gradle should give some tips about the error

**Comment by mlopatkin** [comment] 2023-12-05 23:09
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #26729

Please add your use case and 👍 to that issue.

**Closed by mlopatkin** 2023-12-05 23:09 UTC
Labels: a:bug, in:provider-api, re:comprehensibility
