### ISSUE TITLE
Ability to inject custom comandline arguments to TestNG is missing

### ISSUE THREAD

**Issue by itkhanz** [gradle/gradle#29135] opened 2024-05-14 09:29 UTC
### Expected Behavior

I am currently executing my TestNG tests using Gradle provided api as follows:
```
test {
   useTestNG() {
     useDefaultListeners = true
   }
}
```

At the moment, there is no way we could pass this commandline argument to  Class `TestNGOptions` inside package `org.gradle.api.tasks.testing.testng` if we are using default `useTestNG()` inside gradle `test` task.

https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html
https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/testing/Test.html
https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/testing/testng/TestNGOptions.html

I would like to have this feature added to TestNGOptions class so we we can inject this argument `-reporter` with value `org.testng.reporters.XMLReporter:generateTestResultAttributes=true,generateGroupsAttribute=true` to TestNG, so TestNG test task will be executed with these specific options.  It will then enable TestNG to produce XML reprots with additional custom attributes.

### Current Behavior (optional)

As a workaround, the TestNG maintainers suggest to create a custom task of type `JavaExec`, and pass these args to `org.testng.TestNG`

```
task testngTest(type: JavaExec, dependsOn: [classes]) {
    group 'Verification'
    description 'Run TestNG tests'
    mainClass = 'org.testng.TestNG'
    args('testng.xml', '-reporter',
            'org.testng.reporters.XMLReporter:generateTestResultAttributes=true,generateGroupsAttribute=true'
    )
    classpath = sourceSets.test.runtimeClasspath
}
```

https://groups.google.com/g/testng-users/c/CqTNqaPeAQY
https://github.com/Xray-App/xray-testng-extensions?tab=readme-ov-file#2b-configure-gradle-to-use-testng-xmlreporter-and-enable-user-defined-test-attributes
https://github.com/testng-team/testng/discussions/3128

The problem with this approach is that we lose all the featured offered by gradle test task as well as useTestNG() class in gradle API. Therefore having this feature added in TestNGOptions to allow us to pass these commandline arguments to TestNG would be really helpful.
Or alternatively with the suggested approach, I would like to use all the features of gradle test task while having the ability to pass cmd args to TestNG

### Context

I am using [TestNG plugin](https://github.com/Xray-App/xray-testng-extensions) which sets custom attributes on the XMLReporter used by TestNG. Fortunately, TestNG allows this behaviour to be enabled by passing a commandline argument `-reporter org.testng.reporters.XMLReporter:generateTestResultAttributes=true,generateGroupsAttribute=true` to TestNG.
This is described in detail in TestNG documentation:
https://testng.org/#_xml_reports

For your reference, Maven build tool enables this feature already via the use of maven-surefire-plugin as described below:
```
...
    <build>
        <plugins>
            <plugin>

                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.20.1</version>

                <configuration>
                    <testFailureIgnore>true</testFailureIgnore>

                    <suiteXmlFiles>
                      <suiteXmlFile>testng.xml</suiteXmlFile>
                    </suiteXmlFiles>

                    <properties>
                        <property>
                            <name>reporter</name>
                            <value>org.testng.reporters.XMLReporter:generateTestResultAttributes=true</value>
                        </property>
                    </properties>

                </configuration>
             </plugin>

        ...
        </plugins>
    </build>
```

**Comment by ljacomet** [comment] 2024-05-16 12:32
This issue will be closed as a duplicate of

* #18828 

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

**Closed by ljacomet** 2024-05-16 12:32 UTC
Labels: a:feature, closed:duplicate, in:testing-testng

**Comment by itkhanz** [comment] 2024-05-16 13:11
> This issue will be closed as a duplicate of
> 
> * [useTestNg() has limited list of command line args which can be passed to TestNg runner #18828](https://github.com/gradle/gradle/issues/18828)
> 
> Please add your use case and 👍 to that issue.
> 
> If you think our analysis is wrong, please provide us with more detailed information explaining why.

Thank you. i have mentioned this in the other ticket. However I don't see any analysis on it. It currently says that its in the backlog.
