### ISSUE TITLE
Kotlin buildSet, buildMap, etc are not available (compilation error) in gradle.kts

### ISSUE THREAD

**Issue by bric3** [gradle/gradle#22450] opened 2022-10-19 13:51 UTC
I just discovered that some Kotlin stdlib collections methods are not available and provoke a compilation error.

Take this very simple _basic_ project

```kotlin
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.5.1/samples
 */

val set = buildSet {
  add("item")
}

logger.lifecycle(set)
```

This will result in the following error: 

```
> Configure project :
e: /Users/brice.dutheil/tmp/buildset/build.gradle.kts:8:11: Unresolved reference: buildSet
e: /Users/brice.dutheil/tmp/buildset/build.gradle.kts:9:3: Unresolved reference. None of the following candidates is applicable because of receiver type mismatch:
public inline fun DependencyHandler.add(configuration: String, dependencyNotation: String, dependencyConfiguration: ExternalModuleDependency.() -> Unit): ExternalModuleDependency defined in org.gradle.kotlin.dsl

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/brice.dutheil/tmp/buildset/build.gradle.kts' line: 8

* What went wrong:
Script compilation errors:

  Line 8: val set = buildSet {
                    ^ Unresolved reference: buildSet

  Line 9:   add("item")
            ^ Unresolved reference. None of the following candidates is applicable because of receiver type mismatch:
                public inline fun DependencyHandler.add(configuration: String, dependencyNotation: String, dependencyConfiguration: ExternalModuleDependency.() -> Unit): ExternalModuleDependency defined in org.gradle.kotlin.dsl
```

### Expected Behavior

No compilation error with these methods

### Current Behavior

Compilation error.

### Context

I was trying to build a set of elements to pass to a plugin.

### Steps to Reproduce 

Mentioned above

```
gradle init

Select type of project to generate:
  1: basic
  2: application
  3: library
  4: Gradle plugin
Enter selection (default: basic) [1..4] 1

Select build script DSL:
  1: Groovy
  2: Kotlin
Enter selection (default: Groovy) [1..2] 2

Generate build using new APIs and behavior (some features may change in the next minor release)? (default: no) [yes, no] n
Please enter 'yes' or 'no':                                                                                                              no

Project name (default: buildset):

> Task :init
Get more help with your project: Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.5.1/samples

BUILD SUCCESSFUL in 20s
2 actionable tasks: 2 executed
```
Then edit `build.gralde.kts` to use `buildSet`

### Your Environment
Irrelevant to this issue.

**Comment by eskatos** [comment] 2022-10-20 09:25
Hi Brice,
Thank you for the report.

`buildSet` and `buildMap` were introduced in Kotlin language/api 1.6.
Gradle 7.x uses Kotlin language/api 1.4 so it is expected that this isn't available.

Changing this can only happen on major Gradle releases. Gradle 8.0 will bump Kotlin language/api, see
* https://github.com/gradle/gradle/issues/19568

Closing as a duplicate of #19568

**Closed by eskatos** 2022-10-20 09:25 UTC
Labels: a:bug, to-triage

**Comment by bric3** [comment] 2022-10-20 11:58
Ah ok, thanks for the information, I looked for `buildSet` in the issues, that's why I didn't saw #19568.

Thanks for the feedback!
