### ISSUE TITLE
impossible to add source artifact when using java plugin with gradle 5

### ISSUE THREAD

**Issue by rlagoue** [gradle/gradle#8528] opened 2019-02-15 21:46 UTC
Prior to gradle 5 I used to add a custom artifact with classifier "-src" in my ivy-publications.  To achieve it I use to add a new artifact on the publication, after creating manually a configuration named "source" using the method  org.gradle.api.artifacts.ConfigurationContainer:maybeCreate(java.lang.String).

But doing it now delete all other artifacts on the "component.java", so that all the other artifacts presents by default on this components are no more published. 

Since I am using an ivy repository, I need to have binary and sources on different configurations 

Maybe I still don't understand very well the new gradle software model, any help will be appreciated.

Thanks

**Comment by melix** [comment] 2019-02-16 09:16
I don't think we intended to break anything. So to be sure, would you mind setting up an example that shows what used to work in Gradle 4.x and does not in 5?

**Comment by rlagoue** [comment] 2019-02-25 15:40
Sure here is the situation:

`println 'File: publishingRepositorySettings.gradle'

apply plugin: 'ivy-publish'

if (project.hasProperty("isJava") && project.isJava) {
	ext.getCustomManifest =  {
		return manifest {
			attributes("Title": name,
						"Version": version,
						"Vendor": 'BAO SARL',
						"Date": new java.text.SimpleDateFormat("yyyy-MM-dd'T'hh:mm:ss").format(new java.util.Date()),
						"Git-Repository-Version": System.getenv("GIT_COMMIT") != null ? System.getenv("GIT_COMMIT") : "",
						"Build-Number": System.getenv("BUILD_NUMBER") != null ? System.getenv("BUILD_NUMBER") : ""
						)
		}
	}
	jar.manifest = project.getCustomManifest();
}

publishing {
	repositories {
		if (activeBuildProfile["isRunningOnJenkins"]) {
			ivy {
				url "sftp://ivy.bao-sarl.cm:22"
				layout "pattern", {
					ivy "/home/ivymanager/ivysite/repository/[organisation]/[module]/ivys/ivy-[revision].xml"
					artifact "/home/ivymanager/ivysite/repository/[organisation]/[module]/[type]s/[artifact]-[revision](-[classifier]).[ext]"
				}
				credentials {
					username 'ivymanager'
					password 'IManageTheIvyRepository'
				}
			}
		} else {
			ivy {
				url "${System.properties['user.home']}/.ivy2/local"
				patternLayout {
					ivy "[organisation]/[module]/ivys/ivy-[revision].xml"
					artifact "[organisation]/[module]/[type]s/[artifact]-[revision](-[classifier]).[ext]"
				}
			}
		}
	}
	publications {
		ivy(IvyPublication) {
			String shouldBePublishedAsString = System.getenv("shouldBePublished");
			boolean shouldBePublished = shouldBePublishedAsString == null ? false : Boolean.parseBoolean(shouldBePublishedAsString);
			if (project.isControllerBuild && !shouldBePublished) {
				return;
			}
			if (project.hasProperty("isReleaseBuild") && project.isReleaseBuild) {
				descriptor.status = 'release'
			}

			if (project.hasProperty("isJava") && project.isJava)  {
				if (project.hasProperty("isWeb") && project.isWeb ) {
					from project.components.web
				} else if (project.hasProperty("isAndroid") &&project.isAndroid) {
					def apkNature = "release";
					if (project.isControllerBuild || project.isSnapshotBuild) {
						apkNature = "debug";
					}
					artifact("${project.buildDir}/outputs/apk/${apkNature}/${project.name}-${apkNature}.apk") {
						type "apk"
						extension "apk"
					}
				} else {
					from components.java
				}
/*
				configurations.maybeCreate('sources')
				artifact(sourceZip) {
					type "source"
					conf "sources"
					classifier "sources"
				}
*/
			} else if (project.hasProperty("isJavascript") && project.isJavascript) {
	        artifact("${project.outputDir}/${project.name}.zip") {
            type "zip"
            extension "zip"
	        }
			}

			if (project.hasProperty("customConfigurations")) {
				project.customConfigurations.each { customConfigurationName, extensions ->
					def newConfiguration = configurations.create(customConfigurationName);
					extensions.each { extension ->
						newConfiguration.extend(extension)
					}

					descriptor {
						withXml {
							def customConfiguration = project.configurations.getByName(customConfigurationName)
							customConfiguration.resolvedConfiguration.firstLevelModuleDependencies.each {  ResolvedDependency dep ->
								def Map dependencyDetails = new HashMap<>()
								dependencyDetails.put('org', dep.getModuleGroup())
								dependencyDetails.put('name', dep.getModuleName())
								dependencyDetails.put('rev', dep.getModuleVersion())
								dependencyDetails.put('conf', "$customConfigurationName->" +dep.getConfiguration())
								asNode().dependencies[0].appendNode('dependency', dependencyDetails)
							}
						}
					}
				}
			}
		}
	}
}

ext.addConfigurationToPublication = { String configurationsToPublish, List<String> extensions = [], boolean visibility = true ->
	publishing.publications.all {
		println "publication is: " + it;
		def newConfiguration = configurations.create(configurationsToPublish);
		extensions.each { extension ->
			newConfiguration.extend(extension)
		}
	}
}
`

**Comment by melix** [comment] 2019-02-26 10:30
I'm sorry but I don't manage to reproduce. It would _really_ help if you could come with a minimal file which demonstrates the issue. Here's what I did:

```
apply plugin: 'java-library'
apply plugin: 'ivy-publish'

group = 'com.acme'
version = '1.0'

task sourceZip(type:Zip) {
   from sourceSets.main.allSource
   classifier = 'sources'
}

publishing {
    repositories {
        ivy {
           url "$buildDir/ivy2/local"
           patternLayout {
              artifact("[organisation]/[module]/[revision]/[artifact]-[revision](-[classifier]).[ext]")
              m2compatible = true
           }
        }
    }
    publications {
        ivy(IvyPublication) {
                from components.java
                configurations.maybeCreate('sources')
                artifact(sourceZip.archivePath) {
                    type "source"
                    conf "sources"
                    classifier "sources"
                    builtBy sourceZip
                }
        }
    }
}
```

when I publish I can see that everything is published, both sources and jars:

```
$ tree build/ivy2 
build/ivy2
└── local
    └── com
        └── acme
            └── publish
                └── 1.0
                    ├── ivy-1.0.xml
                    ├── ivy-1.0.xml.sha1
                    ├── publish-1.0.jar
                    ├── publish-1.0.jar.sha1
                    ├── publish-1.0-sources.zip
                    └── publish-1.0-sources.zip.sha1

```

**Comment by rlagoue** [comment] 2019-02-26 16:44
Thank you for taking your time trying help me. 

Please could you tell me which version of gradle are you using?
I would also see the content of the generated ivy-file. 

Sincerely

**Comment by melix** [comment] 2019-02-26 16:45
Using latest 5.2.1.

**Comment by rlagoue** [comment] 2019-02-26 16:52
ok... I am still on 5.1.1

But before moving to the latest version, I would like to check something I just found out in your code. A small difference that  could be the source of my headaches

![image](https://user-images.githubusercontent.com/5127870/53430376-aa14cb80-39ee-11e9-8cbb-d14bfa5923ca.png)

There, your are using "artifact(sourceZip.**archivePath**)"

But on my side I wrote the following: 

![image](https://user-images.githubusercontent.com/5127870/53430487-e516ff00-39ee-11e9-83e0-1c65d073c61c.png)

As you can see, on my side i am not using the **archivePath** , could it be the source of my problems?

Could test without passing the **archivePath**  to the "artifact" method? just to see whether you will have the same behavior I had

Sincerely

**Comment by melix** [comment] 2019-02-26 16:58
No, you can use:

```
                artifact(sourceZip) {
                    type "source"
                    conf "sources"
                    classifier "sources"
                }
```
and it will behave exactly the same, that's just I copy/pasted old code.

**Comment by rlagoue** [comment] 2019-02-26 17:05
so will try it with version 5.2.1 and let you know whether it fixed the issue

**Comment by melix** [comment] 2019-02-26 17:07
There shouldn't be any difference between 5.2 and 5.2.1. That's basically why I'm asking if you can create a sample that reproduces the issue you are seeing. I tried to reproduce using the snippet I sent you but I don't see this behavior. So if you can tweak it so that it reproduces your problem, would be nice.

**Comment by rlagoue** [comment] 2019-02-26 18:00
so the problem is solved, it worked with 5.1.1 too.... I don't know what was wrong when I was trying it that time. 

Thank you for your help

**Comment by melix** [comment] 2019-02-26 18:03
Great, thanks!

**Comment by rlagoue** [comment] 2019-02-26 18:30
oups I just found out the real problem :-D

the sources and the binaries are for sure published, but the problem are the dependencies.. There are somehow reset

Here is the ivy.file produced when the sources code are published with gradle 5.1.1
![image](https://user-images.githubusercontent.com/5127870/53436898-7d67b080-39fc-11e9-944d-d533fb713e95.png)

Here is the ivy.file produced when the sources code are published with prior to gradle 5
![image](https://user-images.githubusercontent.com/5127870/53436974-b6a02080-39fc-11e9-9697-b48f157375be.png)

As you can see, the dependencies are completely absent when adding the sources code the following way (on a gradle software component): 
![image](https://user-images.githubusercontent.com/5127870/53437042-e3543800-39fc-11e9-8ff8-857553b296b8.png)

**Comment by melix** [comment] 2019-02-27 08:26
I'm sorry, I wrote another test, the same one, just adding a couple of dependencies and they *are* published in the ivy file:

```
<?xml version="1.0" encoding="UTF-8"?>
<ivy-module version="2.0" xmlns:m="http://ant.apache.org/ivy/maven">
  <!-- This module was also published with a richer model, Gradle metadata,  -->
  <!-- which should be used instead. Do not delete the following line which  -->
  <!-- is to indicate to Gradle or any Gradle module metadata file consumer  -->
  <!-- that they should prefer consuming it instead. -->
  <!-- do-not-remove: published-with-gradle-metadata -->
  <info organisation="com.acme" module="ivyPublish" revision="1.0" status="integration" publication="20190227092543"/>
  <configurations>
    <conf name="compile" visibility="public"/>
    <conf name="default" visibility="public" extends="compile,runtime"/>
    <conf name="runtime" visibility="public"/>
    <conf name="sources" visibility="public"/>
  </configurations>
  <publications>
    <artifact name="ivyPublish" type="jar" ext="jar" conf="compile"/>
    <artifact name="ivyPublish" type="source" ext="zip" conf="sources" m:classifier="sources"/>
  </publications>
  <dependencies>
    <dependency org="org" name="foo" rev="1.0" conf="compile-&gt;default"/>
    <dependency org="org" name="bar" rev="1.9" conf="runtime-&gt;default"/>
  </dependencies>
</ivy-module>
```

Again it's hard to help you if you don't provide a minimal, reproducible example.

**Comment by ljacomet** [comment] 2019-02-27 08:36
@rlagoue To be very clear: screenshots are not a reproducible example.
We understand if you cannot share your whole build, but sharing only images really does not help.

**Comment by rlagoue** [comment] 2019-02-28 00:19
OK I understand. But I have a huge suit of files for my situation. I was thinking that using screenshot is easier for all.

Attached is a zip file with 3 gradle files, I use in my projects.:

1. dependenciesRepositorySettings.gradle: configure the ivy dependencies repositories
2. commonRootProject.gradle: utilities used in all our concrete projects. 
3. publishingRepositorySettings.gradle: configure the publication. The sourceZip task is defined here

A concrete java project applies this 3 scripts in the following order they are listed above. 

The sourceZip is used during the publication by:
- creating a new sources configuration
- adding the source artifact on that configuration.

All this with the confusing result described before. When I create the new configuration named "sources" the dependencies disappear from the generated ivy.xml file. That's why I decided to momentously  comment the piece of code out, that adds the souceZip artifact 

NB: There are some variables used in this script expected to be defined by jenkins, since they are intended to be run locally and on jenkins in CI mode.

[gradle.zip](https://github.com/gradle/gradle/files/2912785/gradle.zip)

Thank you for taking your time to help me on this issue.

**Comment by melix** [comment] 2019-02-28 07:53
The easiest for us is that you trim down your build to the minimal thing that fails. I understand there is a lot of noise, but we receive lots of reports and we just don't have the capacity to create reproducers ourselves. So ideally you should come up with a zip of a _project_ that shows the problem. I think the easiest for you is to start from your project, remove what is not necessary until you have something that minimally reproduces the issue. Thanks for your time!

**Comment by rlagoue** [comment] 2019-02-28 11:32
OK 

I will do it today's evening

sincerely

**Comment by rlagoue** [comment] 2019-02-28 16:41
So I am back.

Attached you find a small project in a zip file reproducing the situation. Here are the steps to reproduce it (I am supposing you are working on linux computer)

1. unzip cm.bao.common.util.zip
2. cd cm.bao.common.util/cm.bao.common.util
3. gradle publish

The repository will done under the directory ~/.ivy2/local

You can then inspect the file ~/.ivy2/local/bao/cm.bao.common.util/ivys/ivy-1.9.0.xml

You will see that the module dependencies are missing in the ivy.xml. If you comment out the code adding the source artifact (in publishingRepositorySetting.gradle), the generated ivy.xml file will have dependencies declared inside. 

[cm.bao.common.util.zip](https://github.com/gradle/gradle/files/2915941/cm.bao.common.util.zip)

**Comment by melix** [comment] 2019-02-28 16:54
Thanks, I downloaded the sample and edited your comment to remove the link since it contained the whole git history and sources you probably to intend to share.

**Comment by rlagoue** [comment] 2019-02-28 17:08
Thanks for this move :-D

**Comment by melix** [comment] 2019-02-28 17:17
Ok so I'm puzzled. I tried your code and... whatever I do (comment, uncomment), using Gradle 5.2.1 or `master`, the situation is the same: dependencies are _never_ visible. If I use 4.10.3 (and change the patternLayout method call), I do see the dependencies in both cases.

So, there is a change, but not the one you are describing... I'll try to understand what is going on.

**Comment by melix** [comment] 2019-02-28 17:39
So I have found the culprit. In Gradle 5+, `publications` is no longer deferred. So when you call `configurations.maybeCreate(...)`, this is calling `getConfigurations`, which is building the software component model. At this point it is assumed that all dependencies have been added, but because you actually call this block _before_ the `dependencies` block is called, when the component is created, they are missing.

An easy workaround is to do:

```
project.afterEvaluate {
   configurations.maybeCreate("sourced")
   ...
}
```

In any case I don't know if it's an intentional change, @marcphilipp may know more about this.

**Comment by rlagoue** [comment] 2019-02-28 21:30
Merci pour le Work around. Je l'éssaye tout de suite.... 

Did you try with gradle 5.1.1 ? Because this is the version I am using right now... I never tested it with gradle 5.2.1 

Maybe the from 5.1.1 to 5.2.1 things became more radicals :-)

So should I consider the issue as closed?

**Comment by melix** [comment] 2019-02-28 22:16
The workaround should work for any 5+ version. Thanks for your time!

**Comment by rlagoue** [comment] 2019-03-01 08:14
I did not mean the workaround, but the behavior. Because you told the behaviour you observed was a little bit different from the one I described.

Therefore I thought that it is related to the exact gradle version, because the behaviour I described was observed with gradle 5.1.1

**Comment by melix** [comment] 2019-03-01 08:16
> I did not mean the workaround, but the behavior. Because you told the behaviour you observed was a little bit different from the one I described.

I see no reason why it would be different in 5.1.1. But in any case you should apply the workaround.

**Comment by rlagoue** [comment] 2019-03-01 08:29
yeah I already applied it, and the workaround is in production right now

Thank you...

**Comment by jotel** [comment] 2019-03-08 12:00
Hey, just to let you know that this also affect Gradle v 4.x with `enableFeaturePreview('STABLE_PUBLISHING')`

and very bare-bone example showing the issue based on project initialised by init task of type `java-library`

```groovy
plugins {
    id 'java-library'
    id 'ivy-publish'
}

group = 'org.test.sample'
version = '0.0.1'

publishing {
  publications {
    ivy(IvyPublication) {
      configurations.create("extended", { extend "default" })

      from components.java
    }
  }
}

repositories {
    jcenter()
}

dependencies {
    api 'org.apache.commons:commons-math3:3.6.1'

    implementation 'com.google.guava:guava:27.0.1-jre'

    testImplementation 'junit:junit:4.12'
}
```
with line `configurations.create("extended", { extend "default" })` the ivy.xml completely misses artefacts and dependencies.. the invalid `ivy.xm` is produced as below:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ivy-module version="2.0">
  <info organisation="org.test.sample" module="test-ivy-publishing" revision="0.0.1" status="integration" publication="20190308110142"/>
  <configurations>
    <conf name="extended" visibility="public" extends="default"/>
  </configurations>
  <publications/>
  <dependencies/>
</ivy-module>
```

whereas a correct one should be:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ivy-module version="2.0">
  <info organisation="org.test.sample" module="test-ivy-publishing" revision="0.0.1" status="integration" publication="20190308115012"/>
  <configurations>
    <conf name="compile" visibility="public"/>
    <conf name="default" visibility="public" extends="compile,runtime"/>
    <conf name="runtime" visibility="public"/>
    <conf name="extended" visibility="public" extends="default"/>
  </configurations>
  <publications>
    <artifact name="test-ivy-publishing" type="jar" ext="jar" conf="compile"/>
  </publications>
  <dependencies>
    <dependency org="org.apache.commons" name="commons-math3" rev="3.6.1" conf="compile-&gt;default"/>
    <dependency org="com.google.guava" name="guava" rev="27.0.1-jre" conf="runtime-&gt;default"/>
  </dependencies>
</ivy-module>
```

another workaround I'd like to mention is to use `descriptor.withXml { ... }`  e.g.

```
publishing {
  publications {
    ivy(IvyPublication) {
      descriptor.withXml { xml ->
        xml.asNode().configurations[0].appendNode('conf', [name: 'extended', visibility: 'public', extends: 'default'])
      }

      from components.java
    }
  }
}
```

**Comment by jotel** [comment] 2019-03-08 12:09
@melix I don't think this issue should be closed as it is still present in Gradle v. 5.2.1 and in IMHO  it's a regression bug.

**Comment by ljacomet** [comment] 2019-03-08 13:48
Indeed, the closing happened when it was believed this was user error - opening again.

**Comment by ljacomet** [comment] 2019-03-08 13:53
Sorry for the noise, changing my mind here. I suggest we use #8707 for tracking this issue as it has a shorter and clearer history.

**Closed by ljacomet** 2019-03-08 13:53 UTC
Labels: from:contributor, in:dependency-management
