### ISSUE TITLE
Dependency of plugin that is sourced from included build is not built before plugin is applied.

### ISSUE THREAD

**Issue by matklad** [gradle/gradle#3119] opened 2017-10-10 08:50 UTC
### Expected Behavior

When substituting a dependency in a composite build with

```groovy
includeBuild('./other-project') {
    dependencySubstitution {
        substitute module('someGroup:someArtifact:someVersion') with project(':')
    }
}
```

the dependent project should be build, and the artifact created.

### Current Behavior

In Gradle 4.2 and Gradle 4.2.1, I get the following error:

```
A problem occurred configuring root project 'my-project`.
> Cannot expand ZIP '/home/user/projects/my-project/other-project/build/distributions/other-project-someVersion.zip' as it does not exist.
```

So it seems like the dependency is substituted correctly, but the build of the included project is not executed, and the artifact is missing. If I go to `other-project` and manually trigger the build to produce the artifact, then the build of the main project starts to work.

Note that it does work as expected with Gradle 4.1 and Gradle 3.5, so this is a **regression** introduced in 4.2.

### Context

I can't share the exact project because it is closed sourced, but if this is not a known issue/expected behavior, I can try to come up with a minimal reproducible example.

A peculiarity of the build is that the dependency I want to substitute comes from a detached configuration which is resolved in configuration phase, from [this line](https://github.com/JetBrains/gradle-intellij-plugin/blob/38f737628aab307d9063bffea769948d1b7c2f01/src/main/groovy/org/jetbrains/intellij/dependency/IdeaDependencyManager.groovy#L47) in intellij gradle plugin.

**Comment by bigdaz** [comment] 2017-10-10 14:35
Thanks for reporting. We didn't make any major changes to composite builds for 4.2, so this isn't a known issue or expected.

If this is indeed a regression in 4.2, it would be great if you could provide a reproducible example. If you can produce one, please resubmit the issue so that we can get it fixed.

**Comment by matklad** [comment] 2017-10-10 15:22
Thank you for quick response!

Here's a small example that reproduces the issue: https://github.com/matklad/gradlebug

**Comment by bigdaz** [comment] 2017-10-10 16:52
Thanks! Turns out I was wrong when I stated "We didn't make any major changes to composite builds for 4.2". While no features were added, we did a bunch of refactoring to consolidate the task execution for a composite build.

In 4.1, tasks for included builds were executed "on demand" when a configuration was resolved. This was problematic for task scheduling and parallelization.
In 4.2, tasks for included builds are scheduled and executed as part of task graph execution, with task dependencies being used for ordering and scheduling. (This make a composite build more similar to a multi-project build).

One of the consequences of this is that the artifacts for an included build are only guaranteed to be available during task execution: they will not be available if a dependency is resolved during the project configuration phase. (This is exactly the same behaviour as a project dependency that is resolved during the configuration phase: the file path is known, but the file may not exist).

We strongly encourage plugin authors to move all work (including dependency resolution) into a task action. Doing work during configuration is a common cause of performance problems in Gradle builds. In this case, `IdeaDependencyManager.resolveRemote()` should likely not be performed when applying the plugin.

Unfortunately, I can't think of a good workaround for this issue.

**Comment by matklad** [comment] 2017-10-11 09:54
@bigdaz unfortunately it's not easy to fix this plugin, given the currently available Gradle APIs. The plugin works by creating a local Ivy repository on the user's hard drive and attaching it to a project in configure phase. But to create this local repository, it has to download that file via `resolveRemote()`.

To fix this, we need either

1) Ability to specify that an Ivy repository is produced by some task. You can do something similar with plain fileTree dependencies, but this approach does not allow to attach sources, which is a deal breaker: 

```
dependencies {
    compile fileTree("somePath") { builtBy 'someTask' }
}
```

2) Ability to define a fully-custom repository implementation.

To my knowledge, neither is possible in Gradle today. Is there any issue for the 2) which I can subscribe to? 

Plugin issue: https://github.com/JetBrains/gradle-intellij-plugin/issues/123

**Comment by bigdaz** [comment] 2017-10-12 17:06
Thanks for the feedback.  This is a bit tricky, and I don't have a great solution for you. We don't currently have any concrete plans to provide a way to provide a custom repository implementation.

What is the purpose of the repository that is generated from `idea.zip`? Is it only your tasks that use this repository, or do users of your plugin create tasks that reference modules in this repository?

**Comment by matklad** [comment] 2017-10-12 19:26
>What is the purpose of the repository that is generated from idea.zip?

The directory, extracted from the `idea.zip`, serves two purposes:

1) First, it is a real installation of IntelliJ IDEA, with multiple JARs, some native dependencies and some other auxilary files. This directory is used by plugin's tasks to launch the IDE for development purposes.

2) Second, it is a ivy repository, which  describes the JARs as a ivy module, which is than added as a dependency to user's project. 

If we needed only 1), we could create a task which extracts the zip, and make it a dependency of other plugin's tasks. 

If we needed only 2), in theory we could have published JARs, and only JARs, from `idea.zip` as a true maven/ivy module somewhere, though it wouldn't be very convenient. But we need both 1) and 2), and we need to make sure that we are running against the same classes that we use for compilation (that is, in theory it is possible to do 1) and 2) separately, but it could lead to compile-time/runtime mismatch).


I think one more thing that would have helped us is the ability to attach sources to `fileTree` dependencies. This perhaps is even the most sensible approach, because what we are trying to do is to add dependencies on some JAR files from a local installation of IntelliJ IDEA, and this sounds like a perfect use case for `fileTree`-style dependencies on JARs.

**Comment by bigdaz** [comment] 2017-10-12 23:54
Thanks for the context. We have 2 unrelated issues here:

- Your plugin needs to do a bunch of work at configuration-time in order to provide a repository from `idea.zip`. This could be addressed by making it possible to provide some sort of initialization action/task for a repository, or by providing a custom repository implementation.
- In a composite build, if a plugin _dependency_ is substituted with an included build, this plugin dependency will not be built before the plugin is used to configure a project.

**Comment by bigdaz** [comment] 2017-10-13 00:05
The composite build issue was particularly confusing since we have a [specific test case for an included build providing a plugin dependency](https://github.com/gradle/gradle/blob/c91d1739016c8838105b9c2425e980edc24320ef/subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildPluginDevelopmentIntegrationTest.groovy#L172-L194).

I'll reopen this issue since it can be easily reproduced. However I don't have the capacity to look into this further at this time.

If you're interested in pushing this forward, here's what you could do:
- Determine why your use case is failing when the linked test case is passing.
- Provide a failing integration test (based on the passing one)
- Provide a PR to fix the issue!

Any of these would be helpful. Thanks for your analysis.

**Comment by oehme** [comment] 2018-01-15 15:15
> A peculiarity of the build is that the dependency I want to substitute comes from a detached configuration which is resolved in configuration phase, from this line in intellij gradle plugin.

This is not a dependency of the plugin (as the issue title says), but instead the plugin creates a detached configuration (which Gradle doesn't know about before applying it) and then tries to resolve that. This only worked "by accident" in earlier Gradle versions because we executed composite builds as part of dependency resolution, which was error prone and not easy to parallelize. It has never worked in a normal multi-project build.

This needs to be moved to the execution phase in order to work.

**Closed by oehme** 2018-01-15 15:15 UTC
Labels: a:bug, affects-version:4.2, from:contributor, in:composite-builds

**Comment by oehme** [comment] 2018-03-12 14:10
@zolotov If I remember correctly you wanted to take the zip and turn it into a set of JARs to put on the compile classpath. This should now be much more convenient using variant transformations. Instead of creating an ivy repository on the fly, you can have a single dependency on the zip and unpack it during artifact resolution.

You can take a look at [this plugin](https://github.com/gradle/gradle/blob/master/buildSrc/subprojects/packaging/src/main/kotlin/org/gradle/gradlebuild/packaging/MinifyPlugin.kt) which does something even more complex: Minfying dependencies as they are resolved. For your use case you can go with something simpler, just registering a transformation from "zip" to "idea-jars" which does a simple unpack operation. Hit me up on Slack if you need some more help.

**Comment by zolotov** [comment] 2018-03-12 14:19
@oehme as it's stated in the issue, this approach doesn't allow me to set sources jar for the dependency. 

Thanks, I'll reach you on Slack, I just want to clarify the status of this issue. It's closed but without any workaround.

**Comment by wheelerlaw** [comment] 2018-04-01 16:29
@oehme @bigdaz 

If Gradle is going to enforce that included builds are no longer executed - and their artifacts made inaccessible - during the configuration phase, then shouldn't Gradle also be changed to make **all** artifacts from dependency resolution inaccessible during the configuration phase? Ideally, working with a dependency should always "just work" (as it did prior to 4.2), regardless of whether that dependency is from a repository or substituted from an included build. 

The difficulty of parallelizing included builds doesn't sounds like a problem with the way included builds worked. Rather, (and as said by yourself), it is the result of stuff being done during the configuration phase that really should be done during the execution phase. So instead of further limiting the usability of composite builds for dependency substitution (and creating greater disparity between the two dependency resolution methods), it would seem logical to try to attack the problem at the source, by encouraging that more build logic be moved into tasks by limiting what can actually be done during the configuration phase across the board (such as dependency resolution). That way, composite builds can retain their on-demand nature (which I would argue is the best part of composite builds) while still being performant (because of their parallelization through concurrent task execution).

At the very least, this big "gotcha" of composite builds absolutely needs to be documented. As it stands, there isn't any of information in the Gradle user manual about the inability for an included build to substitute a dependency during the configuration phase.

**Comment by oehme** [comment] 2018-04-03 05:12
> then shouldn't Gradle also be changed to make all artifacts from dependency resolution inaccessible during the configuration phase

Absolutely, see https://github.com/gradle/gradle/issues/2298
