### ISSUE TITLE
I keep getting this error when I try to run gradle build please help I didn't found anything online.

### ISSUE THREAD

**Issue by sameip1** [gradle/gradle#18303] opened 2021-09-16 19:28 UTC
❯ gradle build

FAILURE: Build failed with an exception.

* Where:
Build file '/home/sameip1/Documents/ClientBase/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating root project 'ClientBase'.
> Failed to apply plugin 'net.minecraftforge.gradle.tweaker-client'.
   > Configuration with name 'compile' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s

I'm on Linux and the code is from this GitHub project: https://github.com/egirlfrosty/ClientBase/

**Comment by sameip1** [comment] 2021-09-16 19:30
And this is the build.gradle script:

buildscript {
    repositories {
        mavenCentral()
        jcenter()
        maven {
            name = "forge"
            url = "https://files.minecraftforge.net/maven"
        }
        maven {
            name = 'sponge'
            url = 'https://repo.spongepowered.org/maven'
        }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.1-SNAPSHOT'
        classpath 'org.spongepowered:mixingradle:0.6-SNAPSHOT'
    }
}

apply plugin: 'net.minecraftforge.gradle.tweaker-client'
apply plugin: 'org.spongepowered.mixin'
apply plugin: 'java'

version = "1.0"
group= "me.frosty"
archivesBaseName = "Client"

sourceCompatibility = targetCompatibility = 1.8
compileJava.options.encoding = 'UTF-8'

minecraft {
    version = "1.8.9"
    tweakClass = "me.frosty.client.mixin.Tweaker"
    runDir = "run"
    mappings = "stable_20"
    makeObfSourceJar = false
}

repositories {
    maven { url "https://jitpack.io" }
    maven {
        name = 'sponge'
        url = 'https://repo.spongepowered.org/maven/'
    }
    mavenCentral()
    jcenter()
}

configurations {
    embed
    compile.extendsFrom(embed)
}

dependencies {
    embed('org.spongepowered:mixin:0.7.11-SNAPSHOT') {
        exclude module: 'launchwrapper'
        exclude module: 'guava'
        exclude module: 'gson'
        exclude module: 'commons-io'
    }

    compileOnly 'org.projectlombok:lombok:1.18.20'
    annotationProcessor 'org.projectlombok:lombok:1.18.20'

    testCompileOnly 'org.projectlombok:lombok:1.18.20'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.20'
    compile('org.spongepowered:mixin:0.7.11-SNAPSHOT')
}

mixin {
    defaultObfuscationEnv notch
    add sourceSets.main, "mixins.tecknix.refmap.json"
}

processResources {
    inputs.files "src/main/resources"
    outputs.dir "build/classes/main"
    copy {
        from("src/main/resources")
        into("build/classes/main")
    }
}

jar {
    dependsOn configurations.compile
    from {
        configurations.embed.collect {
            it.isDirectory() ? it : zipTree(it)
        }
    }
    exclude 'META-INF/*.RSA', 'META-INF/*.SF', 'META-INF/*.DSA'
}

jar {
    manifest.attributes(
            "MixinConfigs": 'mixins.client.json',
            "TweakClass": "me.frosty.client.mixin.Tweaker",
            "TweakOrder": 0,
            "Manifest-Version": 1.0
    )

    configurations.embed.each { dep ->
        from(project.zipTree(dep)) {
            exclude 'META-INF', 'META-INF/**'
        }
    }
}

**Comment by asodja** [comment] 2021-09-16 20:10
The issue is that you use `compile` for setting dependency that was removed in 7.x. So problematic line is:
`compile('org.spongepowered:mixin:0.7.11-SNAPSHOT')`. 

You can replace it with: `implementation("org.spongepowered:mixin:0.7.11-SNAPSHOT")`. 

Check Migration guide:
https://docs.gradle.org/7.0.2/userguide/upgrading_version_6.html#sec:configuration_removal.

I will close the issue. Note that you can also join Gradle community on Slack where people can help you with questions: [slack link](https://gradle.com/slack-invite?_ga=2.67290769.1243850917.1631354044-1419875506.1630512939).

**Closed by asodja** 2021-09-16 20:10 UTC
