### ISSUE TITLE
Project dependency leads to circular dependency problem in case of modules with same names

### ISSUE THREAD

**Issue by h0tk3y** [gradle/gradle#6353] opened 2018-08-13 09:37 UTC
(originally reported as https://github.com/gradle/kotlin-dsl/issues/999)

In a multi project build with a deep structure where several projects have the same short name (in different paths), if project depends on another project, you get a circular dependency error.

Note: this is not related to the Kotlin Gradle plugin, as it can be reproduced with pure Java as well.

### Expected Behavior
Build should be performed without error

### Current Behavior
```
FAILURE: Build failed with an exception.

* What went wrong:
Circular dependency between the following tasks:
:sub:core:classes
\--- :sub:core:compileJava
     \--- :sub:core:jar
          \--- :sub:core:classes (*)
```

### Context
This issue may arise in projects with nested hierarchy using some uniform names for subprojects.

### Steps to Reproduce (for bugs)
1. Checkout this sample: https://github.com/gradle/kotlin-dsl/tree/master/samples/multi-kotlin-project
2. (optionally) Replace the `kotlin("jvm")` plugin usages with `java` in `core` and `cli`
3. `mkdir sub`; `mv cli sub/core`
4. Replace the project name in `settings.gradle.kts`: `include("sub:core", "core")`
5. `./gradlew run`

### Your Environment
 * Build scan URL: https://gradle.com/s/l3sdkoofvdgak

**Comment by marcphilipp** [comment] 2018-09-04 07:46
Duplicate of #847

**Closed by marcphilipp** 2018-09-04 07:46 UTC

**Comment by bersling** [comment] 2018-12-21 15:56
Is this really a duplicate? I also don't see how I could resolve this issue, in my case the error is:
```
\--- :myproject:server:compileJava
     +--- :myproject:server:compileKotlin
     |    \--- :myproject:server:jar
     |         +--- :myproject:server:classes (*)
     |         +--- :myproject:server:compileKotlin (*)
     |         \--- :myproject:server:inspectClassesForKotlinIC
     |              \--- :myproject:server:classes (*)
     \--- :myproject:server:jar (*)

```

**Comment by marcphilipp** [comment] 2019-01-02 09:17
Have you tried the workarounds mentioned in #847?

**Comment by TWiStErRob** [comment] 2019-06-15 09:48
Off-topic, but this is the highest ranking issue by searching.
I simply had `implementation(project(':foo'))` inside `foo/build.gradle`, so there was a real cycle via self-reference.
