### ISSUE TITLE
Build failed for precompiled script plugin when @file:Suppress annotation is used

### ISSUE THREAD

**Issue by WebTiger89** [gradle/gradle#23699] opened 2023-01-29 03:55 UTC
I have two _precompiled script plugin_s (psp) whereas the first one is based on the second one. The first lines of the basic plugin contains:

```
@file:Suppress("UnstableApiUsage")

package de.acme.configuration

plugins {
    id("com.android.application")
    kotlin("android")
}
...
```

When a psp is based on another psp and the basic psp contains a _@file_ annotation, the build breaks:

```
FAILURE: Build failed with an exception.

* Where:
Precompiled script plugin 'D:\dev\android\workspace\dcapps\configuration-plugin\src\main\kotlin\de\acme\configuration\android-application-compose.gradle.kts' line: 1

* What went wrong:
Plugin [id: 'de.acme.configuration.android-application-base'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (plugin dependency must include a version number for this source)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
```

This issue is related to https://github.com/gradle/gradle/issues/20865

**Comment by eskatos** [comment] 2023-02-03 09:52
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/16154

Please add your 👍 to that issue.

**Closed by eskatos** 2023-02-03 09:52 UTC
Labels: in:kotlin-dsl, closed:duplicate, in:precompiled-script-plugin
