### ISSUE TITLE
Deadlock in `BuildInclusionCoordinator` when using Isolated Projects

### ISSUE THREAD

**Issue by joshfriend** [gradle/gradle#31107] opened 2024-11-01 02:38 UTC
### Current Behavior

When isolated projects is enabled, IDE sync on a project with an included build deadlocks inside `BuildInclusionCoordinator`:

[8.11-rc-2-deadlock.txt](https://github.com/user-attachments/files/17595303/8.11-rc-2-deadlock.txt)

If I disable Isolated Projects, the deadlock does not happen

### Expected Behavior

Build should not deadlock

### Context (optional)

Gradle 8.11-rc-2
Android Studio Ladybug Feature Drop Canary 09 is required to sync with isolated projects

### Self-contained Reproducer Project

This is from square's android project, i'm still working on a sample reproducer

### Gradle version

8.11-rc-2

**Comment by alllex** [comment] 2024-11-01 07:35
This issue will be closed as a duplicate of

- https://github.com/gradle/gradle/issues/30402

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

---

We are already working on a fix

**Closed by alllex** 2024-11-01 07:35 UTC
Labels: a:bug, closed:duplicate, in:isolated-projects
