### ISSUE TITLE
Build breaks with --parallel

### ISSUE THREAD

**Issue by eekboom** [gradle/gradle#15938] opened 2021-01-25 23:45 UTC
When running a gradle build, it fails when executed with the "parallel" option and builds fine without it.

### Steps to Reproduce 
Tested on Windows 10 20H2:
* Clone this project: https://github.com/bnorm/kotlin-ir-plugin-template
* Execute `.\gradlew build -Dorg.gradle.parallel=false -Dorg.gradle.configureondemand=false --no-build-cache`
* => build works fine
* To cleanup execute `.\gradlew clean`, `.\gradlew --stop`, `rd /s /q .gradle`
* Execute `.\gradlew build -Dorg.gradle.parallel=true -Dorg.gradle.configureondemand=true --no-build-cache`
=> Bug: Build fails with `kotlin-ir-plugin-template\kotlin-ir-plugin-native\src\main\kotlin\com\bnorm\template\TemplateCommandLineProcessor.kt: (36, 35): Unresolved reference: BuildConfig`

The bug is related to the gradle plugin "com.github.gmazzo.buildconfig".
I don't know enough about gradle plugin mechanisms to decide if the bug is maybe in the plugin itself. Naively, I assume that the gradle plugin API should be safe to use from plugin even for "parallel" builds.

The gradle wrapper is configured to 6.7.1. I tried updating to 6.8.1, but that made no difference.

The bug also happens with `org.gradle.configureondemand=false`

### Your Environment

Build scan URL:
https://scans.gradle.com/s/hl4n4xzkjxace

**Comment by ljacomet** [comment] 2021-01-26 08:32
Depending on what they do, plugins may need to be designed to be parallel safe.
I would start by reporting the issue against the plugin itself. The plugin author could then open a detailed issue if he/she believes there is something that needs to be changed in Gradle itself.

**Comment by mlopatkin** [comment] 2021-07-23 13:33
Judging from the https://github.com/gmazzo/gradle-buildconfig-plugin/issues/10 I assume that the plugin was the culprit and the issue is now resolved, so I'm closing the issue.

**Closed by mlopatkin** 2021-07-23 13:33 UTC
Labels: a:bug, to-triage
