### ISSUE TITLE
Not able to build KMM project Gradle 8.7 =>  java.util.zip.ZipException: invalid entry compressed size 

### ISSUE THREAD

**Issue by theyoz** [gradle/gradle#29269] opened 2024-05-23 08:29 UTC
### Current Behavior

I have a Kotlin Multipaltform project that previously compiled but now does not. Note, I'm using Fedora 40 now, I used to use Ubuntu 22.

` ./gradlew clean  build`

give me the following failure 

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':riscocommons:transformCommonMainDependenciesMetadata'.
> java.util.zip.ZipException: invalid entry compressed size (expected 225 but got 221 bytes)
`

### Expected Behavior

being able to build

### Steps to Reproduce

 ./gradlew clean  build

### Gradle version

8.7

### Your Environment (optional)

Fedora 40

**Comment by theyoz** [comment] 2024-05-23 09:06
https://scans.gradle.com/s/kd2ojpicwk2le/console-log?anchor=414&page=1

**Comment by ov7a** [comment] 2024-05-23 12:12
This is an issue with the Kotlin Gradle Plugin, which is developed by JetBrains, and cannot be addressed in the Gradle Build Tool project. We cannot just move the issue.

Please open such Kotlin-related issues on the JetBrains YouTrack at https://kotl.in/issue.

If you believe this is not a Kotlin plugin issue, please update with a reproducer that does not involve the Kotlin plugin.


***

See 
https://scans.gradle.com/s/kd2ojpicwk2le/console-log?page=1#L261
It can potentially be caused by a corrupted zip file.

**Closed by ov7a** 2024-05-23 12:12 UTC
Labels: a:bug, to-triage

**Comment by theyoz** [comment] 2024-05-24 10:52
Ok I will but note, there was here a similar case no?


https://github.com/gradle/gradle/issues/26740
