### ISSUE TITLE
Make OutputEventRenderer single point emitting threads for rendering pipeline

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#2240] opened 2017-06-02 15:30 UTC
### Expected Behavior

Executor logic e.g. for throttling or task grouping is moved to `OutputEventRenderer`, the top of the rendering pipeline. Synchronization only needs to happen in `OutputEventRenderer` and none of the listeners in the pipeline. 

The central executor is shut down as needed. Part of the work will likely involve identifying all the places that create instances of `OutputEventRenderer` outside of a service registry. To be able to properly shut down, the `OutputEventRenderer` needs have a lifecycle.

### Current Behavior

Synchronization needs to happen at lower levels of the rendering pipeline. This maybe lead to contention and synchronization issues.

### Context

Avoid contention and synchronization issues for rendering pipeline.

Related to #2221

**Comment by oehme** [comment] 2017-08-17 14:50
Duplicate of #2221

**Closed by oehme** 2017-08-17 14:50 UTC
Labels: a:chore, from:member, in:cli, in:core
