### ISSUE TITLE
Gradle 3.x does not resolve artifacts with classifiers for dependency in Ivy repository

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#954] opened 2016-11-30 22:38 UTC
Given the following published Ivy metadata:

```
<info organisation="org.company.a" module="a" revision="1.0"/>
<publications>
    <artifact name="a" type="bundle" ext="jar" conf="default" e:classifier="win32-x86" e:bundleId="org.company.a.win32.x86" e:fragment="true"/>
    <artifact name="a" type="bundle" ext="jar" conf="default" e:bundleId="org.company.a"/>
</publications>
```

And the following build script:

```
configurations {
    myConf
}

dependencies {
    myConf group: 'org.company.a', name: 'a', version: '1.0', configuration: 'default'
}

task assertArtifacts {
    doLast {
        assert configurations.myconf.files.size() == 2
    }
}
```

### Expected Behavior

Executing the task `assertArtifacts` resolves all artifacts independent of the extra attribute `e:classifier`. This is the behavior when executing the build with Gradle 2.14.

### Current Behavior

Starting with Gradle 3.0 the task `assertArtifacts` only resolves a single artifact, the one without an assigned extra attribute `e:classifier`.

```
> assert configurations.myConf.files.size() == 2
         |              |      |     |      |
         |              |      |     1      false
         |              |      [/.../testproject/local-repo/'org.company.a/a/1.0/a-1.0.jar]
         |              configuration ':myConf'
         [configuration ':myConf']
```

### Context

Upgrading from Gradle 2.x to 3.x is non-trivial. Projects would have to spell out explicitly which dependencies they need for a specific configuration.

### Steps to Reproduce (for bugs)

See example above

**Comment by bigdaz** [comment] 2016-12-01 02:36
I can't reproduce this failure. Please provide a fully-formed test case that passes with 2.14 and fails with 3.1.

I suspect that the issue is cause by the `ivy.xml` file using a different namespace for `e:classifier`: this must be bound to the `http://ant.apache.org/ivy/maven` namespace.

**Comment by bmuschko** [comment] 2016-12-01 21:40
Here's a sample project with a pre-existing local Ivy repository:

[classifierresolve.zip](https://github.com/gradle/gradle/files/625807/classifierresolve.zip)

**Comment by venkolino** [comment] 2016-12-02 07:53
Just saw the Daz comment and he is right. I did couple of tests and one more sample project and it seems that the problem is coming from the extra attributes namespaces in the ivy xml. I changed the the classifier in the new attached sample from the ivy extra attributes name space (e:classifier xmlns:e="http://ant.apache.org/ivy/extra") to the maven ones (m:classifier xmlns:m="http://ant.apache.org/ivy/maven") and now the resolving with gradle 3.2.1 works as expected - the same way as with gradle 2.14.1
Is there any change in this direction in gradle 3.0? Did you drop the support for the e: namespace? Is there a way to activate it back? Some hints or workarounds will be appreciated.

Thanks,
Venko

Here is the modified working ivy from the sample project Benjamin attached:

`<?xml version="1.0" encoding="UTF-8"?>
<ivy-module version="2.0" xmlns:e="http://ant.apache.org/ivy/extra" xmlns:m="http://ant.apache.org/ivy/maven">
	<info organisation="org.eclipse.equinox.security" module="equinox-security" revision="1.0.200" status="release" publication="20120503144102" default="true" e:qualifier="v20100503"/>
	<configurations>
		<conf name="default" visibility="public" extends="archives,features,featureRuntime"/>
		<conf name="archives" visibility="public"/>
		<conf name="sources" visibility="public"/>
		<conf name="javadocs" visibility="public"/>
		<conf name="features" visibility="public"/>
		<conf name="compile" visibility="public" extends="featureCompile"/>
		<conf name="runtime" visibility="public" extends="compile,featureRuntime"/>
		<conf name="featureCompile" visibility="public"/>
		<conf name="featureRuntime" visibility="public" extends="featureCompile"/>
	</configurations>
	<publications>
		<artifact name="equinox-security" type="bundle" ext="jar" conf="default" m:classifier="win32-x86" e:bundleId="org.eclipse.equinox.security.win32.x86" e:fragment="true"/>
		<artifact name="equinox-security" type="bundle" ext="jar" conf="default" m:bundleId="org.eclipse.equinox.security"/>
		<artifact name="equinox-security" type="bundle" ext="jar" conf="sources" m:classifier="sources" e:bundleId="org.eclipse.equinox.security.source"/>
		<artifact name="equinox-security" type="bundle" ext="jar" conf="sources" m:classifier="win32-x86-sources" e:bundleId="org.eclipse.equinox.security.win32.x86.source"/>
	</publications>
</ivy-module>`

**Comment by bmuschko** [comment] 2016-12-07 20:51
> Is there any change in this direction in gradle 3.0? Did you drop the support for the e: namespace? Is there a way to activate it back? Some hints or workarounds will be appreciated.

@bigdaz Can you provide some insight here?

**Comment by eriwen** [comment] 2016-12-22 16:13
Given current priorities, we cannot commit to delivering this in the next version of Gradle.

**Comment by bigdaz** [comment] 2016-12-28 15:28
The `classifier` attribute belongs to the `http://ant.apache.org/ivy/maven` namespace, and Gradle uses this value when resolving. I'm not sure that Gradle should not treat a `classifier` attribute from an arbitrary namespace (like  `http://ant.apache.org/ivy/extra`) as meaning the same thing.

The fact that this worked in 2.14 means we need to do _something_:
1. Note this as a "potentially breaking change" for 3.0, and leave the new, stricter behaviour in place
2. Change back to honouring any 'classifier' attribute (regardless of namespace)
3. Like 2, but deprecate this for later removal.

If this was a planned change, I'd vote for 3. But since this change is already in all 3.x releases, I vote for 1.

**Closed** 2017-02-13 17:34 UTC
Labels: a:bug, affects-version:3.0, from:member, in:dependency-management
