### ISSUE TITLE
Gradle TestKit Daemon Idle Timeout

### ISSUE THREAD

**Issue by shanman190** [gradle/gradle#3093] opened 2017-10-05 17:11 UTC
### Current Behavior
Today, the Gradle TestKit sets the daemon idle timeout to 3 minutes which in terms of a CI-based build is quite a long time. 

### Expected Behavior
It would be nice if there was a way to allow user configuration of that timeout through the TestKit public API, so that the idle timeout can be set to a lower value if desired.

### Context
Whether this is the way that it should be done or not is up for debate, but... in our environment we have a couple of Gradle plugins that we want utilize automated testing to ensure functional compatibility across Gradle versions. In order to achieve this, we are utilizing Spockframework for writing the functional test and then utilizing TestKit to open up Gradle daemon's for each of the Gradle versions under test. Because the default timeout is set to 3 minutes when utilizing TestKit, we are getting into a bind of not having enough memory on our CI server's agents to go around for these tests and the other executions going on. As an aside, I know that nebula-plugins/nebula-test supports a memory safe mode -- where they set the timeout to 15 seconds, but it's still not fully user configurable -- so I could utilize that, but the purpose of this issue is rather to see this addition of functionality adopted by Gradle core.

**Comment by oehme** [comment] 2017-10-13 17:50
I wonder why it is 3 minutes by default. If you're running tests, isn't the assumption that the completion of one test method is very quickly followed by another? Maybe the default should be shorter?

**Comment by bmuschko** [comment] 2017-10-13 17:53
[We picked a default and right now it is 3 minutes.](https://github.com/gradle/gradle/blob/master/subprojects/test-kit/src/main/java/org/gradle/testkit/runner/internal/ToolingApiGradleExecutor.java#L185) 1 minute would probably be enough assuming that you might run the build multiple times subsequently. I'd be OK with making the default shorter.

**Comment by shanman190** [comment] 2017-10-13 18:04
When reporting the feature, I wasn't really concerned as much about where the default value was, but rather being able to configure it through the public API, if necessary. In my case, the tests run through pretty quickly, so even 1 minute in my use case would be too long. Looking through the codebase, I think that it wouldn't be too hard to allow the idle timeout to be passed through from the GradleRunner API.

**Comment by bmuschko** [comment] 2017-10-13 18:07
Side note: Providing a configuration option automatically exposes implementation details. At the moment the user of TestKit doesn't need to know that the Tooling API or a daemon is used or what happens if you execute `GradleRunner` in debug mode. While not hard to implement, we'd have to think hard if we really want to expose that knowledge to consumers and how.

**Comment by bmuschko** [comment] 2017-11-09 23:52
@shanman190 Would lowering the default timeout already be of benefit to you? Could you please open a pull request if you are interested in working on it?

**Comment by bmuschko** [comment] 2017-11-16 18:28
I am going to close this for now. Let us know if you'd like to follow up.

**Comment by shanman190** [comment] 2017-11-17 12:47
I don't mind going through the process of making a pill request at all. I'd be more than happy to do that. With that said though, even 1 minute would still result in about 10 online, idle daemons for my situation.

What I've basically done to mitigate was to mirror testkit myself and provide the timeout value, so that I could get by. While not ideal, the attempt was to stay close to the current testkit API contract, so that a change down the road for this wouldn't be a larger amount of effort. With that said I've set the idle timeout in my case to 15 seconds and still have 2, sometimes 3, online and idle daemons, but that's significantly less strain on our CI server.

Would it make sense to expose an idle timeout and not qualify it by the resulting execution type? EG: setIdleTimeout(int, TimeUnit) or setIdleTimeout(Duration). I definitely understand that your group doesn't want to expose internal implementation details, but when thinking about this, would it not be reasonable to see an idle timeout for other implementations to come for testkit? Thinking through the idea of maybe instead of the tooling API your group switches to an on process thread pool, in theory I could see where the idle timeout could still be relavent.

Another option would be to go the other direction and let the user decide the internal execution runtime and then since that is know allow the lower detailed customization as a result.

**Comment by oehme** [comment] 2017-11-17 13:13
We already provide a daemon idle timeout on the tooling API, so I don't see a reason why we wouldn't allow it on TestKit as well.

**Comment by bmuschko** [comment] 2017-11-17 14:57
@oehme The story for the Tooling API is slightly different. The `embedded(boolean)` method is an internal API. To end users the Tooling API can only be operated in daemon mode (except if you call an internal API of course). From that perspective it makes sense to allow setting a daemon idle timeout.

We could certainly discuss how to make the timeout configurable while at the same time avoiding to expose implementation details.

**Comment by oehme** [comment] 2017-11-17 15:11
The daemon is an important aspect of Gradle, so I think we should give users some control over it. We could warn if you use anything that the embedded executor doesn't support.

**Comment by bmuschko** [comment] 2017-11-17 15:59
> We could warn if you use anything that the embedded executor doesn't support.

Yeah, that could be a good compromise.

**Comment by ajoberstar** [comment] 2018-04-09 03:54
I've run into this issue while trying to test gradle-clojure ([CI build](https://circleci.com/gh/gradle-clojure/gradle-clojure/10), [build scan](https://gradle.com/s/bffgjzsx3tawi)).

When running a large (and I doubt ours is particularly large) suite of TestKit tests you start a lot of builds. If each one starts a daemon and some workers, it adds up fast. Having the idle timeout at all doesn't seem particularly helpful. I'm more interested in the daemons/workers just going away when my TestKit `build()`/`buildAndFail()` is over. It seems that none of this gets cleaned up for sure until a [shutdown hook runs](https://github.com/gradle/gradle/blob/3903a7b9f837e8c0ec9b06feac7c0c9fcfc4bbc6/subprojects/test-kit/src/main/java/org/gradle/testkit/runner/internal/ToolingApiGradleExecutor.java#L70) closing out the Tooling API services.

I can understand not wanting to expose implementation details, but the current behavior ultimately leaks that information since it's so difficult to keep from blowing your memory cap (particularly in free SaaS CI environments, which have fairly small memory limits).

To work around this, I broke up one of my large test classes to have fewer builds per class and set the Test tasks to forkEvery 1 class.

**Comment by oehme** [comment] 2018-04-09 06:52
@ajoberstar I'm curious, why do you get so many different daemons? Do your run lots of tests each with different jvm args or Gradle versions?

**Comment by ajoberstar** [comment] 2018-04-09 12:25
@oehme I do test a lot of Gradle versions, but those are all in their own tasks, so everything seems to get cleaned up when one Gradle version's suite is over.

I'm not quite sure how to troubleshoot which processes are getting created and why. Is there any visibility into that or do all of the logs, etc get cleaned up by Test kit. I'm not even seeing them show up in `jps`.

If the daemons are being reused I would expect that the workers are the bulk of the processes. Those aren't as reusable, because the classpath changes. I tried controlling the workers by setting max-workers to 2 on both my gradle-clojure build and as an argument to Test kit for each test, but that didn't seem to help control it.

**Comment by oehme** [comment] 2018-04-09 12:48
The worker API is supposed to kill off existing workers when physical memory is too low to start the next one. Maybe that is not working well in some environments? Can you try it out on your machine by running your test suite and simply requiring more memory per worker to compensate for your machine's larger memory?

**Comment by ajoberstar** [comment] 2018-05-08 01:43
Here's a [test project](https://github.com/ajoberstar/gradle-worker-cleanup/commit/692ca1ac1259012f5fcba1e4a9b6212ad9556541) that just spins up workers and prints when they shutdown. On my laptop (Windows 10), this generally does a good job of shutting down workers, but does encounter the following error after a while. In Circle CI, this test project seemed to have no issues. Maybe I'm missing something basic, but I was trying to force each worker process to be 2 GB, and it seemed to be ending up with way more active worker processes than it should be able to on a Circle CI build.

```
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 1073741824 bytes for Failed to commit area from 0x00000000c0000000 to 0x0000000100000000 of length 1073741824.
# An error report file with more information is saved as:
# C:\Users\andre\.gradle\workers\hs_err_pid53740.log
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000c0000000, 1073741824, 0) failed; error='The paging file is too small for this operation to complete' (DOS error/errno=1455)
Could not write standard input to Gradle Worker Daemon 25.
java.io.IOException: The pipe is being closed
        at java.base/java.io.FileOutputStream.writeBytes(Native Method)
        at java.base/java.io.FileOutputStream.write(FileOutputStream.java:355)
        at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
        at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
        at org.gradle.process.internal.streams.ExecOutputHandleRunner.forwardContent(ExecOutputHandleRunner.java:66)
        at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:51)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.base/java.lang.Thread.run(Thread.java:844)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':worker24'.
> A failure occurred while executing com.example.MyTask$MyWork
   > Failed to run Gradle Worker Daemon
      > Process 'Gradle Worker Daemon 25' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 40s
25 actionable tasks: 25 executed
```

**Comment by ajoberstar** [comment] 2018-05-08 01:51
Sorry to keep spamming this, with `-XX:+AlwaysPreTouch` (to reserve all memory upfront) it seems to cap the workers as I would expect. [Project](https://github.com/ajoberstar/gradle-worker-cleanup/tree/9a075465940bb74fc97279aa976bf695ec906aec) [Output](https://circleci.com/gh/ajoberstar/gradle-worker-cleanup/5).

I probably need a test project that uses TestKit instead to make sure it's not specific to how workers are managed in that context.

**Comment by vlsi** [comment] 2022-09-14 10:16
Gradle daemons pile up for cases when the plugin is tested across several Gradle versions.

I'm inclined that users should have control over how many Gradle daemon processes sit in the background rather than run out of memory and fail the build.

**Comment by vlsi** [comment] 2022-09-14 10:50
I see Stefan writes:

>https://github.com/gradle/gradle/issues/3093#issuecomment-379739923
> The worker API is supposed to kill off existing workers when physical memory is too low to start the next one

It looks like the feature is broken in Windows since both [ajoberstar](https://github.com/ajoberstar) and myself observe "gradle daemons not stopping" issue with Windows.

**Comment by vlsi** [comment] 2022-09-16 16:42
@wolfs , would you please reconsider this?
It does impact users, and it makes it hard to use Gradle TestKit in parameterized tests that might spawn a lot of daemons in quite short period of time.

It is important for the users to support both `--no-daemon`, `-Xmx`, `-XX:MaxMetaspaceSize`, etc.
Even though I think I'm somewhat proficient with "basic gradle plugin development", I spent ~2 days trying to workaround "out of metaspace when running tests" in https://github.com/sigstore/sigstore-java/pull/150

It is unwelcoming if that behaviour is the only way to go.

**Comment by wolfs** [comment] 2022-09-16 16:46
Sure, I'll re-open the issue.

**Comment by jbartok** [comment] 2023-09-15 12:06
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/12535

Please add your use case and 👍 to that issue.

***

We think that being able to manage the daemon's lifecycle instead of trying to find a magic timeout value would be a better solution. That's what the above-linked issue is supposed to accomplish.

**Closed by jbartok** 2023-09-15 12:06 UTC
Labels: a:feature, in:test-kit, to-triage
