### ISSUE TITLE
Allow multiple distribution locations for the gradle wrapper

### ISSUE THREAD

**Issue by ThadHouse** [gradle/gradle#5053] opened 2018-04-15 00:13 UTC
We have a use case where we are distributing gradle projects to over 3000 high school teams and students. We are switching from our current setup using eclipse, and one of our biggest hurdle in making the switch so far is enabling fully offline builds. We have figured out how to do all the dependencies, but are stuck at making the gradle wrapper work both online without any external installs, and offline with an extra installed required. We have tried a few things, like using another project with a specified distributionUrl to install into the cache, but that doesn't seem to work. The right way to do this it seems would be to allow specifying multiple distributionUrls. We do need cross platform working, so having more then 2 would be necessary.

**Comment by marcphilipp** [comment] 2018-04-16 07:26
The purpose of the Gradle wrapper is to download the correct Gradle distribution when it's first run. So it's not really designed for offline use. Can you instead [install Gradle manually](https://gradle.org/install/#install) and not use the wrapper?

Alternatively, you can add the distribution zip to `gradle/wrapper/` and use its filename as `distributionUrl` for both your online and offline use cases.

**Comment by ThadHouse** [comment] 2018-04-16 15:32
Installing gradle manually does not work properly, as tools like buildship immediately see the wrapper, and attempt to use it rather then a manually installed Gradle.

**Comment by oehme** [comment] 2018-04-17 07:01
> offline with an extra installed required

Why not run the build once while online? That's basically your "extra install".

**Comment by oehme** [comment] 2018-04-17 07:45
If everything needs to be on a flash drive, offline and zero setup then that's the only case where I would say: Put the Gradle distribution itself into the project and point the wrapper url to that relative location.

**Comment by ThadHouse** [comment] 2018-04-17 16:53
Ok. For now we will probably just end up forking the wrapper and implementing the needed functionality ourselves, as 70mb in repo is not an option either. 

Looking around, #4463 would do what we need as well, so maybe that one will have a little more traction as well.

**Comment by oehme** [comment] 2018-04-17 17:08
Alright, closing as a duplicate of #4463 in that case.

**Closed by oehme** 2018-04-17 17:08 UTC
Labels: a:chore, from:contributor, in:wrapper

**Comment by ThadHouse** [comment] 2018-04-17 18:16
Ok. Just in case you're curious, here how I implemented this currently. Switch removals and deletions, as I committed the unchanged version to a separate branch.

https://github.com/ThadHouse/frcgradlew/compare/5064aafaca243f7572e88d73e012414fb332d311...91dd583799c56d3df7de6f6ef02d8894620d7abd

**Comment by ThadHouse** [comment] 2018-04-17 18:46
Would that have any chance of being accepted as a PR, with the work already done? Or none at all. It doesn't quite fill out #4463, but it does allow a local location not forced to be a relative path.

**Comment by oehme** [comment] 2018-04-17 19:42
It's unlikely to be accepted like this, as it doesn't match the intention of the wrapper. The wrapper is supposed to ensure that everyone uses the same distribution. If there can be a completely different distribution when working offline, that defeats that purpose. In that case the question is really: Why use the wrapper at all and not use a local installation?

**Comment by ThadHouse** [comment] 2018-04-17 19:53
As said above, a local install doesn't work properly with tools like buildship, as it uses the wrapper. So IDE's like eclipse and vscode don't work properly unless they have connected to the internet, which is not a valid solution for us.

**Comment by ThadHouse** [comment] 2018-04-17 20:00
We want it to automatically support both online and offline scenarios. We work with high school teams who are not always the greatest at modifying settings if something doesn't work properly. And where can I find the setting to instruct buildship to use a local install even if there is a wrapper.properties file? Looking online, all I could find was instructions to just use the wrapper, as its better.

**Comment by ThadHouse** [comment] 2018-04-17 21:29
Would an extra command line parameter passable into the wrapper be acceptable? I think that has a lot more use even out side of our use case, and is a little more universal as well. It would allow external scripts do their own manual wrapper detection if an environment needs that.

**Comment by oehme** [comment] 2018-04-18 07:39
> And where can I find the setting to instruct buildship

On the second page of the import wizard.

> Would an extra command line parameter passable into the wrapper be acceptable? I think that has a lot more use even out side of our use case, and is a little more universal as well. It would allow external scripts do their own manual wrapper detection if an environment needs that.

I don't understand this proposal. Also, how would it help with the "high school teams who are not always the greatest at modifying settings"? 

As I said above, if you want to support people who are completely offline and can't be expected to use custom settings in Eclipse, checking in the distribution is probably the best way to go and requires zero setup by your students.

**Comment by JLLeitschuh** [comment] 2018-04-18 15:42
@oehme The goal here would be to support being able to checkout a repository from the internet and have it just work for you. But also, without changing any configuration, if you already have a local install of Gradle in the right directory, it would work offline.
That way people working offline don't have to have a by hand edited `wrapper.properties` that is different from the one stored in the repository.

**Comment by oehme** [comment] 2018-04-18 15:49
> if you already have a local install of Gradle in the right directory,

What is "the right directory"? The whole discussion above revolved around students who can't be expected to configure things right. So why expect them to install Gradle into some magic location?

If they can be expected to do that, then you can simply instruct them to extract Gradle into the right subdirectory of `.gradle/wrapper`. The folder name is deterministic (the checksum of the distribution URL), so you can just use it on your machine and then copy-paste that location into your instructions.

**Comment by JLLeitschuh** [comment] 2018-04-18 15:56
The WPIlib project already installs a bunch of utilities and other configuration things into the `~/wpilib` directory as a part of a one time (per year) setup. Part of this one time setup would be deploying an instance of the wrapper into this directory.

Gradle then would have a `wrapper.properties` that has something like:
```
distributionUrl=https\://services.gradle.org/distributions/gradle-4.7-all.zip,file://~/wpilib/gradle/gradle-4.7-all.zip
```

**Comment by oehme** [comment] 2018-04-18 16:14
See my comment above. Instead of installing into a custom directory and adding another location to the wrapper.properties, you could just install Gradle to the directory that the wrapper will check to see if it's already there.

**Comment by ThadHouse** [comment] 2018-04-18 16:29
The reason we hadn't attempted to do that is a few weeks ago we tried using another project with the wrapper directory set to a relative path to install the distribution. We had thought that the hash was based on the file, not the actual distribution url. That hadn't worked, so we hadn't explored that further. Thanks for the knowledge that its actually the URL, that we can work with.
