### ISSUE TITLE
[Feature request] add a mode for gradle to fail on depreciation warnings

### ISSUE THREAD

**Issue by dcabasson** [gradle/gradle#6491] opened 2018-08-24 01:19 UTC
I would be interested in an option org.gradle.warning.mode=fail where gradle would fails in case of a depreciation warnings.
This would be useful to fix all depreciation in the build and then enable this mode to prevent any regression on those depreciation from re-entering the codebase.

**Comment by ati90ati** [comment] 2018-10-23 19:36
This feature seems very nice to have, I would be happy if we could have this feature.

**Comment by Lanchon** [comment] 2019-04-24 20:36
i was about to request this feature. besides its obvious usefulness, my motivation for it is that i think it would work around a shortcoming in the way Gradle reports warnings.

right now i've a deprecation warning i can't fix because i've no idea where it is coming from. when i enable `--warning-mode=all` with `--stacktrace` or even `-S`, all i get is an exception chain that is fully within Gradle and Java runtime. there is not a single useful line in there, no mention of the Android plugin code, my plugin code, or build scripts. i don't even know whether i'm to blame. the trace ends with some worker and gives no info on what triggered the work.

i imagine that if an exception is thrown in a worker, it will be marshaled back to the thread blocking on the work (i hope there is one). given that Gradle doesn't seem to track the code that invoked the worker (or is there a mode for that?), possibly the best bet is throwing from the worker and seeing who gets the bad news. just logging the exception is not enough in many cases.

regarding my deprecation, i'll tackle it at some point in the future, i'll find a way. but this common scenario shouldn't be hard to diagnose better. am i missing something?

**Comment by ljacomet** [comment] 2019-07-05 08:38
Feature has been added and will be in Gradle 5.6

**Closed** 2019-07-05 08:37 UTC
Labels: a:feature, from:contributor, in:console

**Comment by Lanchon** [comment] 2019-07-05 09:00
hi, thanks for the fix!

unfortunately it doesn't fix my issue here: https://github.com/gradle/gradle/issues/6491#issuecomment-486415747

> If fail is activated, the build will fail at the end if any deprecation warnings were reported

failing at the end is useless for me. and the logged exception is completely useless too. i need the whole chain of chained exceptions, which will only happen if the root cause exception is actually thrown and not simply logged.

really, im at a point where the only way for me to go forward is patching gradle myself so it throws and make a test build. is this really the kind of "help" you want to give people to fix deprecations? my only other option is to wait for gradle 6.0 to finally get to see the whole exception chain.

the deprecation warning effort in gradle is great. the reporting of deprecations is seriously broken and invalidates de whole system. this needs fixing asap.

do you need a real life example of this? i can point you to a repo, and you tell me what plugin line trigger the deprecation. because i'm getting zero help from gradle 5.5.

my suggestion is to make "fail" fail fast on the spot, instead of finishing the process with exit(1) if the deprecation warning list is not empty.

if for whatever reason fail as-is is desirable (could be, for a more general view of number of issues) the add a fast failing "abort" option.

something is desperately needed. im serious about the sample repo offer. reporting truly doesn't work
