### ISSUE TITLE
Using constraints with POM versionMapping doesn't resolve for 'runtime' configuration

### ISSUE THREAD

**Issue by jfbibeau** [gradle/gradle#8461] opened 2019-02-08 21:45 UTC
### Expected Behavior
When using:
```
            versionMapping {
                usage('java-api') {
                    fromResolutionResult()
                }
                usage('java-runtime') {
                    fromResolutionResult()
                }
            }
```
We would expect both resolved compile and runtime dependency versions to show up in the POM. 

### Current Behavior
However the versions are still missing in the POM for dependencies where `runtime` configuration is used. Switching to `implementation` or `compile` populates the version properly.

### Context
When using `constraints` and declaring no versions in the dependencies, the POM generated doesn't have versions, which is fine. So we started using `versionMapping` introduced in Gradle 5.2. 

### Steps to Reproduce (for bugs)
1. Unzip attached project
2. cd `gradle-playground/projectB`
3. Run `gradlew publishMavenJarPublicationToMavenLocal`
4. `vi ~/.m2/repository/gradle-playground/projectB/1.0.5/projectB-1.0.5.pom`
5. Observe that `httpcomponents` doesn't have a version in the POM
[optional]
6. Modify projectB's build.gradle, change `runtime` to `implementation` -> republish -> version shows up in the POM

### Your Environment
* macOS 10.14.2
* Gradle 5.2

[gradle-repro.zip](https://github.com/gradle/gradle/files/2846983/gradle-repro.zip)

**Comment by ljacomet** [comment] 2019-02-11 09:33
So the reason this does not work is because of the following:
* `apiElements` configuration, which is mapped to Maven `compile` scope extends from the `runtime` configuration, which seems wrong but has been like that for a while.
  * This can be seen because a `runtime` Gradle dependency ends up mapped to the Maven `compile` scope, as is the case for `httpclient` in your reproducer
* When doing version mapping, for the `compile` Maven scoped dependencies, we use the versions provided by the `compileClasspath` resolved configuration. And that one _does not_ contain the `runtime` dependencies and thus cannot find a resolved version to use.

While a fix is discussed, a work around, as indicated in the report, is to use the `implementation` configuration instead.

**Comment by ljacomet** [comment] 2019-02-11 15:54
I got more information on the history behind having `apiElements` extend `runtime`: this is mainly for backwards compatible reasons.
So there will not be a fix on this specific point. Instead you should use `implementation` or `runtimeOnly` depending on the use case. Dependencies in these scope will properly have their resolved version published, in addition of belonging to the proper Maven scope.

**Comment by ljacomet** [comment] 2019-02-26 14:29
Closing since this will not be fixed inside Gradle and can be fixed by adapting the used configuration for declaring the dependency.

**Closed by ljacomet** 2019-02-26 14:29 UTC
Labels: affects-version:5.2, from:contributor, in:dependency-management
