### ISSUE TITLE
gradleTestKit not available in test suite

### ISSUE THREAD

**Issue by unredundant** [gradle/gradle#19232] opened 2021-12-06 23:00 UTC
### Expected Behavior
I should be able to declare gradleTestKit as a dependency in my test suite like so
```kotlin
testing {
  suites {
    val test by getting(JvmTestSuite::class) {
      useJUnitJupiter()
      dependencies {
        val kotestVersion = "4.6.4"
        implementation("io.kotest:kotest-runner-junit5-jvm:$kotestVersion")
        implementation("io.kotest:kotest-assertions-core-jvm:$kotestVersion")
        implementation("io.kotest:kotest-property-jvm:$kotestVersion")
        implementation(gradleTestKit())
      }
    }
  }
}
```

### Current Behavior
Doing so results in an exception `Unresolved reference: gradleTestKit`

there is a work around (assuming you are only using unit testing)

```kotlin
dependencies {
  // my deps
  // ...

  // workaround
  testImplementation(gradleTestKit())
}

testing {
  suites {
    val test by getting(JvmTestSuite::class) {
      useJUnitJupiter()
      dependencies {
        val kotestVersion = "4.6.4"
        implementation("io.kotest:kotest-runner-junit5-jvm:$kotestVersion")
        implementation("io.kotest:kotest-assertions-core-jvm:$kotestVersion")
        implementation("io.kotest:kotest-property-jvm:$kotestVersion")
      }
    }
  }
}
```

### Context

Would block any kind of additional test suites from leveraging the test kit 

### Steps to Reproduce 

1. Try to import gradle test kit directly into test suite 

### Your Environment

MacOS Mojave
Gradle 7.3.1
Java 17

**Comment by IslamKhSh** [comment] 2022-02-08 20:06
Possible workarounds:
- you can implement it using your suite configuration inside `dependencies` block `"functionalTestImplementation"(gradleTestKit())`.
- Inside `gradlePlugin` block you can use `testSourceSet` to add testKit to your suite as follows:
``` kotlin
testSourceSets((testing.suites.named("functionalTest").get() as JvmTestSuite).sources)
```

also, you can follow up on this feature request #19849

**Comment by tresat** [comment] 2022-06-29 12:20
This is a duplicate of #19849 and will be addressed soon.

**Closed by tresat** 2022-06-29 12:20 UTC
Labels: a:bug, in:test-suites
