### ISSUE TITLE
Navigation from the new sample page to user guide chapters does not work

### ISSUE THREAD

**Issue by pioterj** [gradle/gradle#11269] opened 2019-11-08 08:38 UTC
Steps to reproduce:
- Open a sample page e.g. https://docs.gradle.org/nightly/samples/groovyBasicApplication/
- Click on any chapter from the user manual e.g. "Getting started"
- "This page does not exist." page is shown

**Comment by lacasseio** [comment] 2019-11-08 14:21
Duplicate of https://github.com/gradle/gradle/issues/11267

**Closed by lacasseio** 2019-11-08 14:21 UTC
Labels: a:bug, a:sample, from:member
