### ISSUE TITLE
Error:Cause: org.gradle.internal.component.external.model.DefaultModuleComponentSelector

### ISSUE THREAD

**Issue by Huangdongrong** [gradle/gradle#836] opened 2016-11-10 08:39 UTC
I am use gradle-2.13 build java project Error,

Error:Cause: org.gradle.internal.component.external.model.DefaultModuleComponentSelector

how to resolve???

**Comment by eriwen** [comment] 2016-11-10 17:56
Hi @Huangdongrong. Could you please provide more information about your build and environment? We need to know how to reproduce it and how it impacts your build before we can address this.

**Comment by bmuschko** [comment] 2016-11-26 15:58
I am going to close the issue for now as we didn't get sufficient information from the contributor to identify the root cause. If you do provide us with more information in the future, we can reopen the issue.

**Closed by bmuschko** 2016-11-26 15:58 UTC
Labels: from:contributor, is:not-actionable
