### ISSUE TITLE
Cache miss with Gradle 8.0.1 and KGP 1.8.10 

### ISSUE THREAD

**Issue by cdsap** [gradle/gradle#24024] opened 2023-02-23 19:35 UTC
Kotlin Compiler tasks generate different build cache key when building different architectures(aarch64,amd64) 

### Expected Behavior
Both tasks generate the same Build Cache key

### Current Behavior
Tasks generate different build cache key
![Screenshot 2023-02-23 at 11 28 48 AM](https://user-images.githubusercontent.com/475733/221010848-2d11b365-1c10-4d1c-8c7e-3be9b37046ac.png)

Gradle 7.6 generates same Build Cache key

### Steps to Reproduce 
1- Download repository https://github.com/cdsap/kotlin-caching 
2- Execute in MacOs(aarch64) `:lib:compileKotlin`
3- Execute in Linux(amd64) `:lib:compileKotlin`
4- Compare inputs for both tasks

### Your Environment

Build scan comparison 8.0.1:  https://ge.solutions-team.gradle.com/c/r77tmf6f3plo6/ugx5xkgns2rme/task-inputs
Build scan comparison 7.6: https://ge.solutions-team.gradle.com/c/6rcapxnybkaja/kivlrtkxrsxy2/task-inputs

**Comment by lwasyl** [comment] 2023-02-24 08:31
Corresponding bug on Youtrack side for reference: https://youtrack.jetbrains.com/issue/KT-56929/Kotlin-tasks-not-cacheable-between-architectures

**Comment by AndreasTu** [comment] 2023-02-24 19:26
This is maybe the same bug as #24031

**Comment by eskatos** [comment] 2023-02-28 11:46
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/24031

Please add your use case and 👍 to that issue.

**Closed by eskatos** 2023-02-28 11:46 UTC
Labels: in:configuration-cache, closed:duplicate

**Comment by lwasyl** [comment] 2023-02-28 17:19
@eskatos Just to make sure, are you positive this is a duplicate of #24031? That issue is about different cache keys between different Gradle versions, the problem here doesn't involve Gradle 7.6 at all, it's about different cache key different OSes/architectures, and the same Gradle version is used on both of them 🤔

**Comment by eskatos** [comment] 2023-02-28 17:38
@lwasyl yep positive
The issue report has links to 7.6 build scans where this was working, this is what hinted at this being a duplicate.
I could not reproduce with clean systems but could reproduce as soon as I ran builds with 7.6 beforehand.

**Comment by lwasyl** [comment] 2023-03-01 07:49
@eskatos I went ahead and wanted to verify the fix. I downloaded 8.0.2 distribution from https://builds.gradle.org/buildConfiguration/Gradle_Release_Check_BuildDistributions/62294346?buildTab=artifacts#%2Fdistributions%2Fgradle-8.0.2-all.zip!%2Fgradle-8.0.2-20230228125432%2B0000 (grabbed from actions for commit `ff9c83745efb6f9c31d1b8ccec259fae39c7b72c`) and tried it with commit https://github.com/lwasyl/kotlin-caching/commit/5171c56587b88b2ebdedc85f6957483e7073ab6b (you need to manually copy the 8.0.2 artifact to `./gradle/wrapper/`)

I then ran the same commands I did before to test, but this time with a completely fresh Gradle user home to rule out interference of other Gradle versions, I understand this should make it unambiguous.

Results of running the same build on two different machines with different OSes, with a fresh, empty Gradle user home directory:

*Pop_OS! on AMD:*
```
➜ ./gradlew ass -Dorg.gradle.caching.debug=true --gradle-user-home=../fresh-gradle-user-home | grep compileKotlin
> Task :lib:compileKotlin UP-TO-DATE
Build cache key for task ':lib:compileKotlin' is ca8dac44c9d1e0ee36514ff0a99e56f3
```

*macOS 13.2.1 on Intel*
```
➜ ./gradlew ass -Dorg.gradle.caching.debug=true --gradle-user-home=../fresh-gradle-user-home | grep compileKotlin
> Task :lib:compileKotlin UP-TO-DATE
Build cache key for task ':lib:compileKotlin' is 83c8902031498cc3f4fa0a610a781d08
```

is it expected that the cache keys still differ? I'm happy to try with another build if I grabbed a wrong one. 

In any case the results don't really surprise me because previously I could reproduce this issue with completely clean `~/.gradle` directories and I don't really see any way previous versions of Gradle would be involved.
