### ISSUE TITLE
Expose .copySpec() in an injectable interface for use with configuration cache

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#25352] opened 2023-06-10 18:11 UTC
### Expected Behavior

Be able to use child specs in a configuration-cache compatible way.
```kotlin
abstract class MyTask @Inject constructor(
    private val specs: ..., // something non-internal, and not Project
    private val files: FileSystemOperations,
) : DefaultTask() {
    @TaskAction
    fun execute() {
        // Action-taking overload to remove that strange .apply { }
        val spec: CopySpec = specs.copySpec { ... }
        files.copy {
            ...
            with(spec)
        }
        files.copy {
            ...
            with(spec)
        }
```

### Current Behavior (optional)

```kotlin
abstract class MyTask @Inject constructor(
    private val specs: org.gradle.api.internal.file.FileOperations,
    private val files: FileSystemOperations,
) : WorkAction<...> {
    @TaskAction
    fun execute() {
        val spec: CopySpec = specs.copySpec().apply { ... }
        files.copy {
            ...
            with(spec)
        }
        files.copy {
            ...
            with(spec)
        }
```

### Context

I'm trying to write a `WorkAction` that extracts files and wanted to use `CopySpec.with(calculateSpec(parameters))`, i.e. create a CopySpec dynamically. This use-case doesn't really need a new API, because I can just write a `fun CopySpec.configureSomething()` extension function, but if I wanted to use the full capabilities of `.copy { }` or `.sync { }` I wouldn't be able to without injecting internal API.

Note: based on the examples it looks like I can achieve this by doing:
`val spec = project.copySpec { ... }` on the class level, but this only works if the spec doesn't depend on inputs.

**Comment by ljacomet** [comment] 2023-06-12 08:49
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before it gets implemented.

**Comment by mlopatkin** [comment] 2023-07-31 14:48
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #13968

Please add your use case and 👍 to that issue.

**Closed by mlopatkin** 2023-07-31 14:48 UTC
Labels: a:feature, in:configuration-cache, in:file-tasks, in:writing-tasks
