### ISSUE TITLE
False positive for implicit dependency deprecation warning

### ISSUE THREAD

**Issue by octylFractal** [gradle/gradle#16980] opened 2021-04-26 22:00 UTC
### Expected Behavior
The following project should build without warnings.

### Current Behavior
The following is printed:
```
Execution optimizations have been disabled for task ':someSourceProcessor' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/home/octy/Documents/gradle-not-really-a-dependency/build/myGeneratedOutput'. Reason: Task ':someSourceProcessor' uses this output of task ':someCodeGenerator' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```

### Context
This occurs normally when I add some generated output from e.g. [protobuf-gradle-plugin](https://github.com/google/protobuf-gradle-plugin) to the `main` source set. Then I exclude the generated output from my licenser plugin, but Gradle still reports the above warning.

I think this is incorrect behavior because now that I have excluded the elements, the `someSourceProcessor` task does not depend on the `someCodeGenerator` task to work properly.

### Steps to Reproduce 
The following Gist is sufficient to reproduce the problem. Running the `build` task will do it.
https://gist.github.com/octylFractal/a5f0fa0db12324d8b28bf3896ac8e3c9

### Your Environment
Build scan URL: https://scans.gradle.com/s/zqlcff2qryk3i

**Comment by m-koops** [comment] 2021-05-20 07:25
And here I have another small sample demonstrating the false positive.  It turns out the warning is triggered as soon as both tasks foo and bar get a filetree as input, although each task has a different filetree. Without the inputs, no warning.

```
val foo by tasks.registering() {
    description = "Foo"

    inputs.files(fileTree(projectDir) {
        include("**/*.foo")
    })
    val reportPath = "${buildDir}/foo.txt"
    outputs.file(reportPath)

    doLast {
        println("foo")
        file(reportPath).writeText("foo")
    }
}

val bar by tasks.registering() {
    description = "Bar"

    inputs.files(fileTree(projectDir) {
        include("**/*.bar")
    })
    val reportPath = "${buildDir}/bar.txt"
    outputs.file(reportPath)

    doLast {
        println("bar")
        file(reportPath).writeText("bar")
    }
}

val fooBar by tasks.registering {
    dependsOn(foo, bar)
}
```

**Comment by OrangeDog** [comment] 2021-06-25 11:11
Is it possible to suppress these warning, so they don't drown out everything else?

**Comment by wolfs** [comment] 2021-06-25 15:49
@octylFractal Regarding [your reproducer](https://gist.github.com/octylFractal/a5f0fa0db12324d8b28bf3896ac8e3c9):

The problem there is that `FileTree.filter` never filters out the root of the file tree. In your case the root of the file tree is `build/myGeneratedOutput`. You need to filter the `srcDirTrees` instead:

```
tasks.register("someSourceProcessor") {
    inputs.files(sourceSets.main.map { main ->
        project.files(main.allSource.srcDirTrees.filter { !it.dir.absoluteFile.startsWith(project.buildDir.absoluteFile) })
    })
    doLast {
        inputs.files.forEach { println("Processing $it") }
    }
}
```

**Comment by wolfs** [comment] 2021-06-25 16:01
@m-koops The problem in your example is the `**/` kind of include. This include matches all directories. Currently, we consider non-existing files as it would possibly be a directory, so the filter matches. When you run the build a second time in your example, you will see that the warning went away since the output file exists now.

We should probably change the check to assume that the location is a file when it doesn't exist, so there are fewer matches.

**Comment by wolfs** [comment] 2021-06-25 16:02
@OrangeDog There is a way to silence the warning: add a `mustRunAfter` dependency between the two affected tasks. If you think the missing dependency is detected wrongly, then please open an issue with the use-case for it.

**Comment by wolfs** [comment] 2021-06-25 16:23
@m-koops A final remark: Using something like `fileTree(projectDir) { include '**/...' }` is discouraged, since it has quite a bad performance impact: Gradle needs to scan the whole project directory and filter all the files every time it tries to run the task. So that means especially scanning all the files in build as well. Normally, that is not a good idea. If you can restrict your search to some subdirectories or at least exclude the `build` directory you are much better of and your build will be faster.

**Comment by wolfs** [comment] 2021-06-28 12:32
@octylFractal I'll close this issue now with my explanation [above](https://github.com/gradle/gradle/issues/16980#issuecomment-868658379).

Please comment/re-open if you disagree.

**Comment by wolfs** [comment] 2021-06-28 12:32
@m-koops Let's continue the discussion of your problem on https://github.com/gradle/gradle/issues/17561.

**Closed by wolfs** 2021-06-28 12:32 UTC
Labels: @execution, a:bug, to-triage
