### ISSUE TITLE
Gradle kills parent process unexpectedly

### ISSUE THREAD

**Issue by finejustice** [gradle/gradle#28511] opened 2024-03-20 10:41 UTC
### Current Behavior

Gradle kills parent process(i.e. cmd.exe) unexpectedly.

### Expected Behavior

Gradle does not kill parent process.

### Context (optional)

I guess this https://github.com/gradle/gradle/issues/7603 and related PR is the cause.

### Steps to Reproduce

Let's say we have "sample.cmd" like:
```cmd
echo "clean"
gradlew clean

echo "assemble"
gradlew assemble

echo "finish"

```
then open a terminal and run this.

If the task is successful, then the terminal should be end with "finish", however it doesn't. You might see: "Process finished with exit code 0".

### Gradle version

7.6, 7.6.4

## Windows 
Edition	Windows 10 Pro
Version	22H2
OS Build	19045.4046

## Java
OpenJDK Runtime Environment Temurin-11.0.21+9 (build 11.0.21+9)

## gradle
affected versions:
- gradle-7.6-bin
- gradle-7.6.4-all

**Comment by ov7a** [comment] 2024-03-21 08:25
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

I think this is expected behavior with batch files. See, for example, [this](https://stackoverflow.com/questions/23420370/windows-batch-file-batch-file-stops-executing-mid-way-after-a-command-that-tak) SO question. You should use `call`.

**Closed by ov7a** 2024-03-21 08:25 UTC
Labels: a:bug, to-triage

**Comment by finejustice** [comment] 2024-03-22 05:55
@ov7a 
**No, It's not typical behavior of shell script.**
If you write same script above but in .sh(git bash or MINGW in windows), it will run to end.

```sh
echo "clean"
./gradlew clean

echo "assemble"
./gradlew assemble

echo "finish"

```
and its output may like:
```console
clean
BUILD SUCCESSFUL in 7s
1 actionable task: 1 up-to-date

assemble
BUILD SUCCESSFUL in 9s
5 actionable tasks: 5 executed

finish
```
Once again, this is same but **only difference** is earlier one(.cmd) is recognized as windows environment at runtime while the other is recognized as *nix.

---
If you concern, this is not typical behavior of cmd also.

Let's say we have another .cmd like:
```cmd
echo "this exists normally"
java --version

echo "this exists abnormally"
java -jar some_nonexist.jar

echo "end of .cmd"
```
and its output may like:
```console
"this exists normally"
java --version
openjdk 11.0.21 2023-10-17
OpenJDK Runtime Environment Temurin-11.0.21+9 (build 11.0.21+9)
OpenJDK 64-Bit Server VM Temurin-11.0.21+9 (build 11.0.21+9, mixed mode)

java -jar some_nonexist.jar
Error: Unable to access jarfile some_nonexist.jar

"end of .cmd"
```
this file ends with "end of .cmd", because .cmd runs regardless of its child process's result.

**Comment by finejustice** [comment] 2024-03-22 06:04
I added example out to the origianl post for more clarity.

**Comment by ov7a** [comment] 2024-03-22 07:28
@finejustice 
1. (ba)sh and bat are completely different in terms of implementation and behavior, this is expected.
2. The problem is related to including bat stript into bat script. So, the java example does not demonstrate the same situation. `gradlew` is a bat script.

**Comment by finejustice** [comment] 2024-04-02 09:13
@ov7a 
sorry for late reply.
Again, it's not a problem of terminal type: it's a problem of `gradle(w).bat`.

In fact, gradle is a just java application(jar), so I can **run it as a plain java application**(e.g. `java -jar gradle-launcher-7.6.jar clean`, see the file "directly.cmd" in attachments).
if doing so, I **do not experience the issue above**. 
![20240402_180815_34](https://github.com/gradle/gradle/assets/5276596/d0c16a7c-394f-4328-a6aa-e9005a011ca6)


However, If I use **gradle(w).bat, the issue still occurs**:
![20240402_180928_36](https://github.com/gradle/gradle/assets/5276596/c6cfc9ef-78c0-4ba3-9037-030af7b9f135)

not for gradle(w):
![mintty_20240402_180240_33](https://github.com/gradle/gradle/assets/5276596/3664cee3-607b-4793-aac3-fcb72bc27bff)

I attached sample project and screenshots for clarification.
[gradle-bug-28511_9dc067f055eb2bd340d4a66e4a5bf1e22dbd154f.zip](https://github.com/gradle/gradle/files/14834239/gradle-bug-28511_9dc067f055eb2bd340d4a66e4a5bf1e22dbd154f.zip)

**Comment by ov7a** [comment] 2024-04-02 09:31
>  Again, it's not a problem of terminal type: it's a problem of gradle(w).bat.

I still think it's not related to `gradlew.bat`, but to the way `bat` files work. Did you try to use `call` as suggested in SO question I [referenced](https://github.com/gradle/gradle/issues/28511#issuecomment-2011619847)?
