### ISSUE TITLE
Error message when attempting to create a configuration that already exists is confusing

### ISSUE THREAD

**Issue by madorb** [gradle/gradle#26255] opened 2023-09-01 15:44 UTC
### Current Behavior

Given:

```
configurations {
    integrationTestImplementation.extendsFrom testImplementation
    integrationTestRuntime.extendsFrom testRuntime
}
...
sourceSets { 
    integrationTest { // line 127
        java.srcDir "$projectDir/src/integration/java"
        //resources.srcDir "$projectDir/src/integration/resources"
        compileClasspath += main.output + test.output
        runtimeClasspath += main.output + test.output
    }
}
```

Gradle 8.3 reports the following warning:

```
Build file '/Users/me/dev/src/myapp/foo/build.gradle': line 127
The configuration integrationTestImplementation was created explicitly. This configuration name is reserved for creation by Gradle. This behavior has been deprecated. This behavior is scheduled to be removed in Gradle 9.0. Do not create a configuration with this name. Consult the upgrading guide for further information: https://docs.gradle.org/8.3/userguide/upgrading_version_8.html#configurations_allowed_usage
```

This is quite confusing, as the message about the configuration name being reserved is an inaccurate description of the problem, and the linked documentation is also not unrelated. 

As mentioned in [slack](https://gradle-community.slack.com/archives/CAHSN3LDN/p1693516938763389) The real issue seems to be that for the source set, gradle attemps to automatically create `integrationTestImplementation/Runtime` but they were already created previously. 

Reordering to put the `configurations` block below `sourceSets` resolves the issue.

### Expected Behavior

Ideally the error message would be more descriptive, perhaps indicating that the configuration already exists, not that it is using some sort of reserved name. 

### Steps to Reproduce

run `./gradlew build` on this project. 

https://github.com/madorb/gradle-confusing-warning-reproducer/tree/groovy-dsl

### Gradle version

8.3

**Comment by legacycode** [comment] 2023-09-07 04:56
I had exactly the same problem. This entry resolved the issue for me. Thank you very much.

**Comment by tresat** [comment] 2023-10-10 13:53
Please see https://github.com/gradle/gradle/issues/26461 and the PR https://github.com/gradle/gradle/pull/26467, which will address this issue in Gradle 8.5 in a few ways:
- More expressive deprecation warnings.
- Context aware warnings that mention source sets when applicable.
- Expanded documentation explaining the issue.
- Better "Try" suggestions upon related failures.

As this is a subset/duplicate of the issue addressed by that linked PR, I'm going to close this one.  Please followup on the other issue and PR.

**Closed** 2023-10-10 13:55 UTC
Labels: a:bug, in:configuration-model, re:comprehensibility
