### ISSUE TITLE
Zip task is deleting out-dated zip but not creating new one with gradle 4.7

### ISSUE THREAD

**Issue by jwgish** [gradle/gradle#5359] opened 2018-05-10 19:05 UTC
First execution of gradle zip creates zip file in target/distributions directory as expected.
Subsequent execution of gradle zip deletes file as outdated (in SkipEmptySourceFilesTaskExecuter code) (based on debug log), but does not recreate it, causing tasks that depend on zip to fail (such as publish).  In addition, task info output shows NO-SOURCE on subsequent zip task evaluation

### Expected Behavior

zip file should not be deleted with subsequent zip task executions unless they recreate the file

### Current Behavior

As described above.

### Context

Build is broken. Can't upgrade to 4.7 

### Steps to Reproduce (for bugs)

Haven't yet been able to do this.

### Your Environment

build.gradle for impacted subproject:
```
defaultTasks 'zip'

jar.doFirst {
  version null
}

// remove default jar artifact
configurations.archives.artifacts.removeAll { it.archiveTask.is jar }

task zip(type: Zip, dependsOn: 'jar', description: 'Create a zip that contains the jar') {
  archiveName project.archivesBaseName + '.zip'
  from(jar.outputs.files) {
    into('oracle_common/common/templates/wls')
  }
}
assemble.dependsOn(zip)

configurations.runtime.artifacts.removeAll { it.archiveTask.is jar }

// published build manifest POM file needs to have type zip,
// not default jar for this artifact
artifacts {
   runtime zip
}

publishing {
  publications {
    // replace JAR publication with ZIP publication
    mavenJava(MavenPublication) { pub ->
      artifacts = [zip]
    }
  }
}
```

 * Build scan URL:

**Comment by oehme** [comment] 2018-05-11 06:56
@lptr Could you please take a look at this one and decide whether this needs a fix for 4.8?

**Comment by wolfs** [comment] 2018-05-11 08:42
@jwgish Thank you for reporting! For which Gradle version does the build script still work for you? Does it work with Gradle 4.6?

**Comment by wolfs** [comment] 2018-05-11 09:28
@jwgish Looking at the example, the problem seems to be that you set the version of `jar` to `null` in a `doFirst`. That changes the output file of the `jar` task. The output file is used as an input to the `zip` task. The `zip` task only sees the now non-existing original output file or the `jar` task, causing the task to be marked as `NO-SOURCE` and deleting the previous output.

Why don't you just configure the `jar` task at configuration time by doing this:
```
jar.version = null
```

instead of using a `doFirst`?

I will close this issue now since the behaviour is expected. I can also reproduce the problem with Gradle 4.6, so the behaviour did not change recently. Please re-open/comment if you think there still is an issue.

**Closed by wolfs** 2018-05-11 09:28 UTC
Labels: a:bug, from:contributor, in:incremental-build

**Comment by jwgish** [comment] 2018-05-11 15:03
FYI -- it's working as expected (at least the way the build author expected :-)) in 3.5._
