### ISSUE TITLE
Wrong XML Reporting for parameterized Junit 5 tests

### ISSUE THREAD

**Issue by Franziskus1988** [gradle/gradle#28866] opened 2024-04-18 13:39 UTC
### Current Behavior

I have an issue where this test code
```
public class XmlReportingTest {

    @ParameterizedTest
    @DisplayName("parameterizedTest")
    @ValueSource(strings = {"a", "b", "c"})
    void parameterizedTest(String testValue) {
        assertEquals(testValue, testValue);
    }

}
```

will produce this XML output
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="de.tomtec.ci.teamcity.XmlReportingTest" tests="3" skipped="0" failures="0" errors="0" timestamp="2024-04-18T13:38:14" hostname="--" time="0.024">
  <properties/>
  <testcase name="[1] a" classname="de.tomtec.ci.teamcity.XmlReportingTest" time="0.02"/>
  <testcase name="[2] b" classname="de.tomtec.ci.teamcity.XmlReportingTest" time="0.001"/>
  <testcase name="[3] c" classname="de.tomtec.ci.teamcity.XmlReportingTest" time="0.0"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
```

### Expected Behavior

I would expect that the test name is mentioned in the XML report and not only the index of the test and the input value. 

I guess something like this or comparable
```
  <testcase name="parameterizedTest(a)" classname="de.tomtec.ci.teamcity.XmlReportingTest" time="0.011"/>
```

### Steps to Reproduce

Executed a parameterized Junit 5 test with Gradle and check produced XML. 

### Gradle version

7.6.2, 8.7 (tested both)

### Your Environment (optional)

------------------------------------------------------------
Gradle 8.7
------------------------------------------------------------
Kotlin:       1.9.22
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          17.0.8.1 (Amazon.com Inc. 17.0.8.1+8-LTS)
OS:           Windows 11 10.0 amd64

Used Junit version is 5.10.0

**Comment by ov7a** [comment] 2024-04-19 07:32
@Franziskus1988 This can be potentially be fixed in:
* https://github.com/gradle/gradle/issues/24538

which is planned to be included in 8.8

Can you please try a [nightly](https://gradle.org/release-nightly/) build?

If the issue persists, please provide a reproducer. The ideal way to do this is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).

**Comment by ov7a** [comment] 2024-04-19 10:09
@Franziskus1988 I saw your comment in the related issue. Thanks for testing it with the nightly.

Let's continue the discussion here, cause it's a separate issue.
 
I've investigated it a bit more. So the `testcase` names are correct, they are taken directly from the Junit5. The issue here is the fact that the method name is not reflected in the XML report. Potentially, it should be put in some additional property, but it seems like it's [not common](https://github.com/testmoapp/junitxml?tab=readme-ov-file#properties).
 
 Workaround:
 ```
     @ParameterizedTest(name = "{index} ==> the test for ''{0}''")
```
see https://github.com/gradle/gradle/blob/5dff74d62bf1b8817725d80d423d6c2137a4c6de/platforms/ide/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r70/TestDisplayNameJUnit5CrossVersionSpec.groovy#L229

**Comment by ov7a** [comment] 2024-04-19 10:15
I think it can be marked as a duplicate of
* https://github.com/gradle/gradle/issues/23324

And it also loosely related to:
* https://github.com/gradle/gradle/issues/22534

**Closed** 2024-04-22 06:38 UTC
Labels: closed:duplicate, in:testing-junit5

**Comment by Franziskus1988** [comment] 2024-04-23 09:19
@ov7a Thanks for your help. 

The solution with the name parameter is ok, although it would be nice if the default behavior would produce a better output than just using the execution index. Maybe that shall be put into some backlog.
