### ISSUE TITLE
executableDir = "" does not work

### ISSUE THREAD

**Issue by tomas-pluskal** [gradle/gradle#9351] opened 2019-05-06 03:55 UTC
The following setting in build.gradle
```
application {
  executableDir = ''
}
```
correctly places the generated start scripts into the root of the build folder, but the start scripts are unusable.

### Expected Behavior
Produce usable start scripts.

### Current Behavior
Unusable scripts produced.

### Your Environment

```
$ gradle -version

------------------------------------------------------------
Gradle 5.4.1
------------------------------------------------------------

Build time:   2019-04-26 08:14:42 UTC
Revision:     261d171646b36a6a28d5a19a69676cd098a4c19d

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          12.0.1 (Oracle Corporation 12.0.1+12)
OS:           Mac OS X 10.14.4 x86_64
```

**Comment by Vampire** [comment] 2019-05-06 23:06
Duplicate of #4675

**Comment by lacasseio** [comment] 2019-05-14 07:56
It's better to upvote and issue using the reaction then opening new issues for the same problem as it just creates noise. I will close this issue in favour of the other one given more context is captured.

**Closed by lacasseio** 2019-05-14 07:56 UTC

**Comment by tomas-pluskal** [comment] 2019-05-14 13:55
Well, okay, that's true... but wouldn't it be more effective to review the pull request (which is quite a trivial bug fix, by the way), so we can close the original issue, which has been sitting there for over a year..?
