### ISSUE TITLE
Overriding constraints based on the groupId in Java Platform plugin

### ISSUE THREAD

**Issue by kpramesh2212** [gradle/gradle#15789] opened 2021-01-14 10:42 UTC
Is it possible to support overriding constraints based on the groupId in gradle java platform plugin.

For example lets consider a gradle root project called `gradle-platform-demo` it has following 4 sub projects

1. aplatform     - A gradle platform project that is used to share dependency constraints with subprojects (consumer1, consumer2, consumer3)
2. consumer1 - A java project relying on dependencies from aplatform project
3. consumer2 - A java project relying on dependencies from aplatform project
4. consumer3 - A java project relying on dependencies from aplatform project

![image](https://user-images.githubusercontent.com/6614973/104574021-7af0bd00-564d-11eb-81c1-3f6a0e6b5a38.png)

The build file for aplatform project is as follows
![image](https://user-images.githubusercontent.com/6614973/104574227-b25f6980-564d-11eb-8d5a-1004fcea23ed.png)

The build file for consumer1, consumer2, consumer3 is as follows
![image](https://user-images.githubusercontent.com/6614973/104574731-46313580-564e-11eb-91a0-0badd2be08e7.png)

#### Please note the following

1. The aplatform project   is sourcing its constraints from spring-boot-dependencies and spring-cloud-dependencies
    
    spring-boot-dependencies has  enforcedPlatform   -- This is done to ensure that spring cloud dependency bom does not override the spring boot version

2. All the consumer projects have a dependency which is enforcedPlatform on aplatform project -- This is done so that the consumers are not allowed to override any versions and they have to get all the versions from the aplatform project

### Problem:

spring-boot-dependencies bom use kafka version 2.3.1. 

We would like to override all the kafka version to 2.4.1 in our aplatform project by setting a constraint on kafka version.

### Current Behavior

One way to achieve this is as follows (aplatform build file)
 
  Go through the spring boot dependencies bom and find out all the kafka jars being used and do the following in aplatform build file

 
![image](https://user-images.githubusercontent.com/6614973/104578840-1f293280-5653-11eb-8d72-25be8cde6ca0.png)

Running gradle dependencies on the consumer project ( The problem is solved)

![image](https://user-images.githubusercontent.com/6614973/104578993-4e3fa400-5653-11eb-9a72-1b9705b9ec94.png)

However this approach is very bad as we have to look into spring boot bom and find all the artificats and override the version

This might also lead wiered errors if we left out any artifacts or forget to override the version for them

### Expected Behavior

So ask here is to provide a convenient method or some way  to do something like 

![image](https://user-images.githubusercontent.com/6614973/104580118-bfcc2200-5654-11eb-8931-91a9414ee4b0.png)

Or something that would make this more convenient to use.

**Comment by ljacomet** [comment] 2021-01-14 10:44
Closed as duplicate of #15788

**Closed by ljacomet** 2021-01-14 10:44 UTC
Labels: a:feature, closed:duplicate, from:contributor

**Comment by mattca** [comment] 2022-07-01 13:10
Ran into the same issue here. Thanks for the suggestion @ljacomet - I am trying to use alignment rules at the platform level but can't seem to get it to make any impact so far.
Question: can the alignment rule be applied at platform level or would you have to apply the alignment rule in the consumers of the platform?
