### ISSUE TITLE
Gradle subproject build file names

### ISSUE THREAD

**Issue by dumontal** [gradle/gradle#13158] opened 2020-05-18 09:22 UTC
Hello Gradle team, I'd like to clarify one part about build file names for Gradle subprojects. In the [official documentation](https://docs.gradle.org/current/userguide/intro_multi_project_builds.html#sec:structure_of_a_multiproject_build) I've carefully read the following about the structure of a multi project build:

> Another thing to bear in mind is that the build files might not be called build.gradle. Many projects will name the build files after the subproject names, such as api.gradle and services.gradle from the previous example. Such an approach helps a lot in IDEs because it’s tough to work out which build.gradle file out of twenty possibilities is the one you want to open. This little piece of magic is handled by the settings.gradle file, but as a build user you don’t need to know the details of how it’s done. Just have a look through the child project directories to find the files with the .gradle suffix.

By reading this it seems that I can name my subproject build file whatever I want and that the "magic" happens because the subproject has been included in the `settings.gradle` file. However it does not seem to work unless I specify myself the build file name for the subproject using the `ProjectDescriptor::buildFileName` property.

Eg: `project(":custom").buildFileName = "custom.gradle.kts"`

If I refer to the docs, shouldn't Gradle recognize the build file name without extra hints? I might have been misled by the "little piece of magic" in the documentation.

### Context

I wanted to test whether I could name my subproject build files like `"$subproject.gradle.kts"` without extra configuration in my enterprise project.

### Steps to Reproduce 

Please find attached a minimal zip file which reproduces the issue. [gradle-issue.zip](https://github.com/gradle/gradle/files/4643181/gradle-issue.zip)

### Your Environment

Linux 4.15.0-99-generic x86_64
openjdk version "1.8.0_252"

**Comment by jjohannes** [comment] 2020-08-04 14:29
Thanks for bringing this up. The documentation is not very precise. We consider supporting this out of the box in a future Gradle version. We'll update the docs along with it: #14001.

**Comment by dumontal** [comment] 2020-08-10 08:52
Hi, thanks for the feedback. Great news to read. Should I close this issue as it is described in https://github.com/gradle/gradle/issues/14001 ?

**Comment by big-guy** [comment] 2020-08-10 13:47
dupe of #14001

**Closed by big-guy** 2020-08-10 13:47 UTC
Labels: @idiomatic, a:bug, from:contributor

**Comment by jjohannes** [comment] 2020-09-11 06:47
The confusing section has been removed from the user manual in 6.7.

If you want to use custom build script naming. If in doubt, we recommend keeping the files named `build.gradle(.kts)`.

If you want to use custom naming, there is also a plugin for that. See: https://github.com/gradle/gradle/issues/14001#issuecomment-684064291

**Comment by dumontal** [comment] 2020-09-11 07:37
Thank you, this clarifies a lot.
