### ISSUE TITLE
Provide a rich console with all task headers

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#2642] opened 2017-08-02 22:18 UTC
### Expected Behavior
We've received enough feedback from users that really want to see task execution and maybe outcomes in the logs that I believe we should allow this to be opt-in in a not-annoying way. 

### Current Behavior
A bunch of users are using `--console=plain` and `TERM=dumb` to get the "old" console. 

### Context
We must be willing to take a small step to allow this display without having to rework log levels (which would presumably be more painful).

Example feedback
 
* https://discuss.gradle.org/t/make-console-plain-default/23514
* https://twitter.com/DailyGradle/status/892399537838448641
* https://stackoverflow.com/questions/17942819/how-can-i-get-clean-gradle-output-on-travis-ci

**Comment by adammurdoch** [comment] 2017-08-03 03:17
Can we fix the title to get rid of the how ("via Gradle property")?

**Comment by adammurdoch** [comment] 2017-08-03 03:30
It seems to me there are a few separate issues referenced in the description of this issue.

We might consider whether we now show too little by default. We might, for example, always show the header for a task that does some work, regardless of whether that task generated output. Or we might show a better summary at the end of the build.

If we do end up solving some of these use cases by adding some kind of optional thing (which I would try very hard to not do) we should do this by reworking the `--console` command-line option to express this rather than adding more flags. Flags are bad, descriptive values are good. We should also consider removing the 'lifecycle' log level at this point too.

If we want some kind of persistent opt-in for the console behaviour, we should do this by making the console style a 'build option' as per #1946, rather than more ad hoc nastiness.

**Comment by oehme** [comment] 2017-08-17 14:39
We decided to provide a "rich verbose" mode to `--console`, which behaves like the rich console, but always prints task headers.

**Comment by adammurdoch** [comment] 2017-08-17 20:35
We should deprecate lifecycle log level as well. Showing or hiding the task headers is pretty much the use case it was added for, and isn't really required any more.

**Comment by oehme** [comment] 2017-08-18 08:37
Adding some more context to my answer above: I'm fine with adding this new mode, as it is at least better than users switching to plain output, which would be a real shame. If we can also deprecate lifecycle logging in return, we at least don't increase complexity.

I'm really curious about concrete use cases/opinions on why printing all task headers would be useful. On any non-trivial project this quickly drowns out the actual warnings/errors. It concerns me that users might give up the concise, actionable console output to solve issues that could be solved better by other means. Here are some use cases I came up with and what I think would be better tools to solve them:

- I want to debug incremental builds
  - use `--scan`
  - use `--profile` if build scans aren't possible
  - use `--info`
- I left my workstation and coming back don't know what I ran
  - press cursor-up in your terminal
  - We could let Gradle print the requested tasks in the build summary
- Something went wrong and I want to know how far the build came before
  - the only case I see where seeing "what ran before" could really help spot an issue is when something didn't run - that can easily be reproduced
  - use `--scan`
  - use `--profile`
- The [mere exposure effect](https://en.wikipedia.org/wiki/Mere-exposure_effect) made me like the old output, even though it wasn't very useful
  - stick with the new one a bit longer and you'll grow to like it

@aalmiray and @ethankhall I know you were among the users asking for this feature, could you add your thoughts to this?

**Comment by aalmiray** [comment] 2017-08-18 09:33
"In any non-trivial project", agreed. And that's precisely the thing, many of the new features and enhancements added to Gradle recently target big builds. There are strong reasons to do so but I'm afraid these decisions hurt smaller projects. Personally I've got more projects that fit the small to medium scale where a simpler console output is better than the alternative.

I cheer for all the benefits added in recent releases but please keep in mind that not everyone make builds at scale as Gradle's paying customers. I only ask that when permissible keep some of the old behavior that makes sense for smaller project be available somehow, protect under a command flag, or project property setting that's disabled by default.

**Comment by oehme** [comment] 2017-08-18 09:43
> Personally I've got more projects that fit the small to medium scale where a simpler console output is better than the alternative.

I'd like to understand why. Can you please elaborate what makes it better in your opinion?

**Comment by big-guy** [comment] 2017-09-25 20:49
@oehme So I just went through the 3-day training class where we are using the command-line all the time to demonstrate different things.  Some of the labs/demos have tasks that don't print anything out, so to demonstrate concepts and get people used to Gradle, we ended up resorting to `--console=plain` a lot.

When running with the rich console, the result looks a lot like this:

> $ gradle someTask
> BUILD SUCCESSFUL in 0s
> 1 actionable task: 1 executed
> Publishing build scan...
> https://.../url
> $ gradle aDifferentTask
> BUILD SUCCESSFUL in 0s
> 1 actionable task: 1 executed
> Publishing build scan...
> https://.../url
> $ gradle yetAnotherTask
> BUILD SUCCESSFUL in 0s
> 1 actionable task: 1 executed
> Publishing build scan...
> https://.../url

Going to the build scan URL appears to be heavyweight/overkill. When the build is fast enough, it's visually jarring when the console clears the progress bar/workers. I think the minimalistic output was off putting to new people because looking somewhere else (despite that being the more useful option in many cases) felt unnecessary and unless you knew exactly what should have been run, you couldn't confirm that Gradle did what you wanted by what was left over on the screen.

I think you've got the right list--I want to know what just ran and I want to know which tasks did something.

What I saw in the class was something like this over and over:

> gradle tasks
> gradle someTask
> // edit build.gradle to add newTask
> gradle tasks
> gradle someTask (a mistake)
> // confusion because newTask didn't "work"
> gradle clean / rm -rf build / rm -rf .gradle
> gradle tasks
> gradle newTask 
> // success! cleaning things "fixed" the build

I think identifying the command-line with the final build output would help here.  e.g., make it look something like:

> $ gradle yetAnotherTask
> BUILD SUCCESSFUL in 0s
> gradle yetAnotherTask: 1 executed
> Publishing build scan...
> https://.../url

I like the idea of showing a header for a task if it did work, regardless if it has console output.  Maybe this fits into the "verbose" console idea.  I could sort of seeing this work the other way, we default to "verbose" console behavior (when we detect a rich console) and have a "lite" or "expert" or whatever option for a more minimalistic rich console.

**Comment by aalmiray** [comment] 2017-09-25 20:53
Also, sometimes a task is marked as UP-TO-DATE but you expected it do some work. You can't tell if the task ran or not with the rich console, but you can with the old behavior | verbose mode.

**Comment by big-guy** [comment] 2017-09-25 21:02
Unfortunately, you couldn't always really tell with the old behavior either (or --console=plain now) when running with --parallel.  It was common for people to see a task listed twice and think it executed twice or only catch the first instance of a task in the output and think a UP-TO-DATE task was executed.

There's where showing a task's header whenever it does work would make that pretty definitive.

**Comment by oehme** [comment] 2017-09-29 07:13
Reopening since the verbose mode in its current form is missing the status (up-to-date/skipped etc.)

**Closed** 2017-10-02 14:57 UTC
Labels: a:feature, from:member, in:logging
