### ISSUE TITLE
The `GenerateMavenPom` task seems to be incompatible with the configuration cache

### ISSUE THREAD

**Issue by chachako** [gradle/gradle#21926] opened 2022-09-08 09:55 UTC
### Current Behavior
```
61 problems were found storing the configuration cache, 20 of which seem unique.
- Task `:generatePomFileForMyPluginPluginMarkerMavenPublication` of type `org.gradle.api.publish.maven.tasks.GenerateMavenPom`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
  See https://docs.gradle.org/7.6-20220906160000+0000/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:generatePomFileForPluginMavenPublication` of type `org.gradle.api.publish.maven.tasks.GenerateMavenPom`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
```

### Context
Just want to use https://github.com/vanniktech/gradle-maven-publish-plugin to publish a plugin.

### Steps to Reproduce 
Run the `:publishToMavenLocal` task

### Your Environment
- Gradle publishing plugin: com.gradle.plugin-publish:0.21.0
- Gradle version compiled from: <https://github.com/gradle/gradle/tree/release>

---

To my confusion, I see that <https://github.com/gradle/gradle/pull/13391> seems to be supported, so is this related to <https://github.com/gradle/plugin-portal-requests/issues/155>?

**Comment by abstratt** [comment] 2022-09-08 17:57
I cannot reproduce this. What I did:

```
git clone git@github.com:gradle/gradle.git
cd gradle
./gradlew publishToMavenLocal
```

Can you confirm that is what you are doing? You included a link to a third-party plugin, which is not related to Gradle's own Maven Publish plugin - see https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:tasks

**Comment by Goooler** [comment] 2023-02-28 04:52
Still in Gradle 8.0

```
- Task `:generatePomFileForTestPublication` of type `org.gradle.api.publish.maven.tasks.GenerateMavenPom`: cannot serialize object of type 'org.gradle.api.internal.artifacts.DefaultDependencySet', a subtype of 'org.gradle.api.artifacts.DependencySet', as these are not supported with the configuration cache.
```

**Comment by abstratt** [comment] 2023-03-01 15:30
I got confused, the original report here seems not to be about Gradle's own Maven Publish plugin, but about https://github.com/vanniktech/gradle-maven-publish-plugin, and so it should be reported against that project instead.

@Goooler Could any of you provide a reproducer that does not use https://github.com/vanniktech/gradle-maven-publish-plugin ?

If so, could you please open a new bug? This one should be closed as not being a Gradle bug.

**Closed by abstratt** 2023-03-01 15:30 UTC
Labels: a:bug, closed:invalid

**Comment by Goooler** [comment] 2023-03-01 16:12
@abstratt See #24097.
