### ISSUE TITLE
compilePlayBinaryScala has incorrect build cache entry when source files are moved between modules

### ISSUE THREAD

**Issue by devishree90** [gradle/gradle#5769] opened 2018-06-25 06:46 UTC
### Expected Behavior
When source files are moved between module/sub-module, cache entry produced by compilePlayBinaryScala task should have .class with latest file structure.

### Current Behavior
Currently, when source files are moved from sub-module to parent module, compilePlayBinaryScala task detects changes and build the binary files.However, build directory still retains .class from previous build. For example, if i move x.java from module 1 to module 2 build directory has two x.class files under module 1 & module 2 respectively. When build cache is enabled, entire build directory is cached(with duplicate .class file) which results in incorrect behavior. 

### Context
Our organization uses Play framework extensively in products. This issue results in incorrect behavior and entire local cache has to be purged to resolve this issue.

### Steps to Reproduce
Checkout this sample Repo:
[https://github.com/devishree90/gradleBug](https://github.com/devishree90/gradleBug
)
> ~/gradle/gradlew compilePlayBinaryScala --build-cache -i
   ~/gradle/gradlew clean
   ~/gradle/gradlew compilePlayBinaryScala --build-cache -i

(Ensure compilePlayBinary is indeed cached)

> mv app/resources/prototype/class3.java app/resources/

(Update package name in class3.java from resources.prototype to resources. skip the step if you are using IDE)

> rm -rf app/resources/prototype/
~/gradle/gradlew compilePlayBinaryScala --build-cache -i

Here is snapshot of build directory

> $ ls -lR build/playBinary/classes/resources/
build/playBinary/classes/resources/:
total 16
-rw-r--r-- 1 dsridhar eng  509 Jun 25 14:28 class1.class
-rw-r--r-- 1 dsridhar eng  509 Jun 25 14:28 class2.class
-rw-r--r-- 1 dsridhar eng  509 Jun 25 14:29 class3.class
drwxr-xr-x 2 dsridhar eng 4096 Jun 25 14:27 prototype
build/playBinary/classes/resources/prototype:
total 4
-rw-r--r-- 1 dsridhar eng 529 Jun 25 14:28 class3.class

Look at the timestamp of the generated class files. Even after deleting prototype package, classes directory still retains copy of it.

### Your Environment
 * Build scan URL:

**Comment by wolfs** [comment] 2018-06-27 09:33
@devishree90 Thank you for the report.

Scala compilation in Gradle uses the Zinc compiler underneath. That means that the Zinc compiler will do incremental compilation and is also in charge of removing leftover output files. Gradle itself can't do much there since it is not aware of the mapping of source files to `.class` files for Scala compilation.

Could you check if there is some bug regarding the problem you are describing for the Zinc compiler? Can you maybe even reproduce the problem when using SBT?

**Comment by devishree90** [comment] 2018-06-27 18:08
Thanks for the reply @wolfs . This Bug is not reproducible if build-cache is not enabled.(Try the above example without --build-cache). I don't see previous build files. 

 I haven't worked much with SBT, but since SBT doesn't have build cache bug may not be reproducible in SBT. I'll give it a try though.

**Comment by wolfs** [comment] 2018-06-29 14:20
@devishree90 I think I know what is going on. On first compilation Zinc creates its compile analysis.  So it knows which files were compiled to where. As long as the compile analysis is valid, it knows which `.class` files belong to which source files. So it can remove `.class` files in the output whenever a source file is removed.

When running `clean`, the Zinc compile analysis is deleted, too. So when pulling from the cache, Zinc doesn't know anything about the output file. As a consequence, on the next run, it recompiles everything from scratch. Zinc also doesn't seem to clean up the output directory when compiling everything from scratch, so the leftover file stays in the output directory.

In order to fix this, either
1) Zinc needs to clean its output directories when it has no compile analysis
2) Gradle needs to clean the output directories when it knows that Zinc will do a recompile (i.e. when Zinc doesn't have any compile analysis)

For Java compilation, we clean up the outputs and do a clean compile [when we do not have any compile analysis](https://github.com/gradle/gradle/blob/375ad7314ac4fb4713d38c21daf532920c34dc52/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/IncrementalCompilerDecorator.java#L77-L80). That is somewhat easier, since Gradle owns the incremental compiler and the task.

I guess we would need to add some code to Gradle which checks if Zinc has the compile analysis available, and if it doesn't we would need to clean the outputs before running Zinc.

The problem is currently not very high on our list. Do you think you could provide a PR for fixing it?

**Comment by wolfs** [comment] 2018-07-02 16:24
@devishree90 We had another look at the issue and plan to fix it for 4.10. We will ping you if we have a nightly with a fix so you can try it out.

**Comment by devishree90** [comment] 2018-07-09 17:56
@wolfs - Sorry for late reply. I was out on vacation. I'll be happy to submit PR if this issue is still open

**Comment by devishree90** [comment] 2018-07-11 22:32
@wolfs - I looked into the fix. I need suggestion from you on best way to proceed forward.

I think it would be good to verify if analysis file is present or not, when [we create zinc compiler](https://github.com/gradle/gradle/blob/cc0da1bb9b4439658565501aaf464bdb5145d79d/subprojects/language-scala/src/main/java/org/gradle/language/scala/tasks/PlatformScalaCompile.java#L60). I also see [cleaningScalaCompiler](https://github.com/gradle/gradle/blob/f001402c8b7f404c923d972f1bc524b2de7b3fcd/subprojects/scala/src/main/java/org/gradle/api/internal/tasks/scala/CleaningScalaCompiler.java#L27) is present, but its not used anywhere (unlike CleaningJavaCompiler class). Can i use it for this usecase? I see following comment in **cleaningScalaCompiler** class which makes me think if i'm exploring incorrect solution. 

> Cleaning compiler for scala. Not required for compiling with Zinc

If there is better way to fix this, could you share your approach?

**Comment by wolfs** [comment] 2018-07-12 10:17
@devishree90 I think we should check in [AbstractScalaCompile.compile](https://github.com/gradle/gradle/blob/d13ad68fcb8e570b939d0fcb37134f9bf5d3c1a0/subprojects/language-scala/src/main/java/org/gradle/language/scala/tasks/AbstractScalaCompile.java#L92), after we called `getCompiler`, if the analysis file is present or not. That way, both subclasses of `AbstractScalaCompile` would be fixed.

If the analysis file is not present, then the compiler should be wrapped with `CleaningScalaCompiler`. Like you saw, the class is currently unused but it seems that it should still work.

The location of the analysis file can be found here: https://github.com/gradle/gradle/blob/3f1a8cacbab8d70659c03bcd25beb12691c694a3/subprojects/language-scala/src/main/java/org/gradle/api/tasks/scala/IncrementalCompileOptions.java#L36-L42.

Do you need any more information?

**Comment by devishree90** [comment] 2018-07-26 23:59
@wolfs - Could you share nightly build with this change? I would like to test it with my project

**Comment by wolfs** [comment] 2018-07-27 14:36
@devishree90: Please try out `4.10-20180727123547+0000` - this nightly contains the changes.

**Comment by wolfs** [comment] 2018-07-28 20:50
@devshree90: `4.10-20180727235915+0000` contains the changes. Please have a look.

**Comment by wolfs** [comment] 2018-08-03 14:41
@devishree90: I am closing this issue now. Please try out a nightly or 4.10-RC1 and report back if it works for you now.

**Closed by wolfs** 2018-08-03 14:41 UTC
Labels: a:bug, in:incremental-build, in:scala-plugin

**Comment by devishree90** [comment] 2018-08-06 18:14
Thank you @wolfs . I tested with nightly build and it works as expected.
