### ISSUE TITLE
Undocumented behaviour: Configuration secondary variants inherit the primary's attributes

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#28939] opened 2024-04-23 21:50 UTC
### Issue type

Wrong or misleading information

### Current Behaviour

Configuration secondary variants inherit the primary's attributes. This behaviour is unexplained and undocumented.

### Expected Behaviour

Either:

1. The behaviour is a bug, and Configuration secondary variants should not inherit attributes.
2. The behaviour is intentional, and should be documented.

   (Note: It would be much appreciated if the current behaviour should not just be written down, but also explained to give context. For example, by answering these questions: Why should attributes be automatically inherited? Why would this be advantageous? In what situations is this relevant? Apparently, the inherited attributes can be overridden - when should this be done, if at all?)

### Context

Related: https://github.com/gradle/gradle/issues/28149

I reported this previously https://github.com/gradle/gradle/issues/28811, but it was incorrectly closed by @ov7a as a duplicate of an unrelated issue.

### Steps to Reproduce

```kotlin
// build.gradle.kts

group = "x.y.z"
version = "1.2.3"

val myFooAttribute = Attribute.of("FooAttribute", String::class.java)
val myFooVariantAttribute = Attribute.of("FooVariantAttribute", String::class.java)

val fooFiles: Configuration by configurations.creating {
  isCanBeDeclared = false
  isCanBeResolved = false
  isCanBeConsumed = true

  attributes {
    attribute(myFooAttribute, "main")
  }
}

val fooFilesVariant1: ConfigurationVariant by fooFiles.outgoing.variants.creating {
  attributes {
    attribute(myFooVariantAttribute, "variant1")
  }
}

val fooFilesVariant2: ConfigurationVariant by fooFiles.outgoing.variants.creating {
  attributes {
    attribute(myFooAttribute, "secondary")
    attribute(myFooVariantAttribute, "variant2")
  }
}
```

Run `gradle outgoingVariants -q`

```text
--------------------------------------------------
Variant fooFiles
--------------------------------------------------

Capabilities
    - x.y.z:proj:1.2.3 (default capability)
Attributes
    - FooAttribute = main

Secondary Variants (*)

    --------------------------------------------------
    Secondary Variant fooFilesVariant1
    --------------------------------------------------
    
    Attributes
        - FooAttribute        = main
        - FooVariantAttribute = variant1

    --------------------------------------------------
    Secondary Variant fooFilesVariant2
    --------------------------------------------------
    
    Attributes
        - FooAttribute        = secondary
        - FooVariantAttribute = variant2

(*) Secondary variants are variants created via the Configuration#getOutgoing(): ConfigurationPublications API which also participate in selection, in addition to the configuration itself.
```

Observations: 

* `fooFiles` only has `FooAttribute = main`, which is expected.
* `fooFilesVariant1` contains `FooAttribute = main`. This is unexpected behaviour, because it's not documented.
* `fooFilesVariant2` overrides `FooAttribute` to be `FooAttribute = secondary`. Because of the automatic inheritance, I'm now confused. Is overriding the primary's attributes supposed to be allowed? Is it problematic?

### Gradle version

8.7

### Page with the problem

n/a

**Comment by ov7a** [comment] 2024-04-24 07:07
This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/28811

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

Sorry, I don't see this as a constructive behavior. You can dislike our decisions, but spamming like this is a waste of everybody's time.

Regarding the issue - the title of the supposedly unrelated issue is "Please improve variant/attribute documentation / error messages", and your issue is related to secondary variants. They are clearly related.

A kind reminder that this repository is a subject of [CoC](https://gradle.org/conduct/).

**Closed by ov7a** 2024-04-24 07:07 UTC
Labels: a:documentation, to-triage
