### ISSUE TITLE
Configure On Demand behaves wrong when dependencies are declared in parent (but not root)

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/gradle#6254] opened 2018-08-08 21:51 UTC
### Example Project Structure

```
root.gradle.kts
- parentA
    - parent.gradle.kts
    - child
        - child.gradle.kts
- util
    - util.gradle.kts
- someApplication
    - someApplication.gradle.kts
```

```kotlin
// root.gradle.kts
// Pretty much empty
```
```kotlin
// parentA/parentA.gradle.kts
description = "Sub-projects are dedicated some specific cause"

subprojects {
    afterEvaluate {
        dependencies {
           "api"(project(":Util"))
        }
    }
}
```

```kotlin
// parentA/child/child.gradle.kts
plugins {
    `java-library`
}
// Empty other than this
```

```kotlin
// Util/Util.gradle.kts
plugins {
    `java-library`
}
// Empty other than this
```

```kotlin
// someApplication/someApplication.gradle.kts
plugins {
    `java-library`
    `application`
}

dependencies {
    implementation(project(":parentA:child"))
}
```

### Expected Behavior
With the flag `org.gradle.configureondemand=true`, running the following should succeed:
```
./gradlew :someApplication:classes
```

It should do so by evaluating the `:parentA` project before evaluating the `:parentA:child` project.

### Current Behavior
Currently, `:parentA` isn't evaluated.
`parentA/parentA.gradle.kts` isn't evaluated so the additional dependencies that are required aren't added to `:parentA:child`.
This causes the compiler to fail for `:parentA:child`.

### Context
This makes `org.gradle.configureondemand=true` pretty much useless when you want to group logic for sub-projects into project groups.

### Your Environment

```
------------------------------------------------------------
Gradle 4.9
------------------------------------------------------------

Build time:   2018-07-16 08:14:03 UTC
Revision:     efcf8c1cf533b03c70f394f270f46a174c738efc

Kotlin DSL:   0.18.4
Kotlin:       1.2.41
Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_92 (Oracle Corporation 25.92-b14)
OS:           Mac OS X 10.13.5 x86_64
```

**Comment by JLLeitschuh** [comment] 2018-08-08 22:07
Hacky fix that seems to be a stopgap measure.

```kotlin
// root.gradle.kts
subprojects {
    // Make every project depend upon it's parent for evaluation
    parent
        .takeUnless { it == rootProject }
        ?.let { evaluationDependsOn(it.path) }
}
```

Any reason that this fix might come back to bite me?

**Comment by big-guy** [comment] 2018-08-08 23:29
This is the way CoD works, unfortunately. It's hard to use `subprojects {}` or `allprojects {}` because it doesn't work out of the box as you'd expect and it can negate most of the improvement. 

I would seriously consider not using configure on demand unless you see a major difference with it on or off.  You can build a scenario with [gradle-profiler](https://github.com/gradle/gradle-profiler) to measure the difference in a reproducible way. If you do see a difference, there may be something we can suggest (outside of configure-on-demand) that will help or it may identify some low hanging fruit we can fix (JFRs, profiler reports, etc are welcome).

Several things have changed since the flag was introduced that have reduced the impact of configure-on-demand to the point that the downsides aren't really worth it for some builds.

**Comment by oehme** [comment] 2018-08-09 07:14
Closing as we're going to remove CoD as soon as we have an "isolated projects" option, which would completely forbid `subprojects {}`

**Closed by oehme** 2018-08-09 07:14 UTC

**Comment by JLLeitschuh** [comment] 2018-08-09 12:40
@oehme You should add to the build warnings that CoD is deprecated

**Comment by oehme** [comment] 2018-08-09 12:46
It's not. It's just not encouraged.
