### ISSUE TITLE
Included build failure does not break the build

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#4895] opened 2018-03-29 18:57 UTC
I just changed a line in an included build (composite build feature) and did `./gradlew run` in the main build with Gradle 4.6 both.
I then wondered why the change did not have the intended effect.
When I scrolled up I found that the `compileJava` task of the included project failed with error which did not disturb the main build from continuing.

**Comment by GFriedrich** [comment] 2018-04-24 19:49
Just stumbled into the same problem.
I guess this is a known limitation right now for composite builds, but I'm wondering why there is no notice on the documentation page about this.
Is there any known workaround?

**Comment by Vampire** [comment] 2018-04-24 20:17
@blindpirate why is this labeled feature? Doesn't this imply the current behavior is expected and wanted and I request a change of that? 
I cannot believe it is expected and wanted that a failed included build is silently ignored.

**Comment by GFriedrich** [comment] 2018-04-24 21:04
Also this issue is missing the "in:composite-builds" label.

**Comment by adammurdoch** [comment] 2018-05-16 06:01
It's definitely not great to have failures go missing, and not the intended behaviour at all. We'll get this fixed soon.

**Comment by adammurdoch** [comment] 2018-05-22 21:51
This is fixed now. The fix will be in 4.9.

**Closed by adammurdoch** 2018-05-22 21:51 UTC
Labels: a:bug, from:contributor, in:composite-builds
