### ISSUE TITLE
`Gradle 8.0-rc-2` may fail on AS 2022.2.1.12 (Flamingo) and AS 2022.3.1.1 (Giraffe)

### ISSUE THREAD

**Issue by RoarGronmo** [gradle/gradle#23586] opened 2023-01-19 08:13 UTC
If it hasn't landed here, referencing this issue: 

https://issuetracker.google.com/265824780 Upgrade from AS (Flamingo) 2022.2.1.11 -> AS 2022.2.1.12 fails with `Could not create task ':app:compileDebugJavaWithJavac'.

Short term remedy: 
Downgrade to '8.0-rc-1'

**Comment by eskatos** [comment] 2023-01-19 08:48
Thank you for your interest in Gradle!

This is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the Gradle Build Tool project.

***

We and the Android teams are aware of the problem in those Android Studio releases.

FTR, this is due to fixing this regression between RC1 and RC2
* https://github.com/gradle/gradle/issues/23440

**Closed by eskatos** 2023-01-19 08:48 UTC
Labels: closed:android
