### ISSUE TITLE
Support PluginDependency in dependency declarations

### ISSUE THREAD

**Issue by JojOatXGME** [gradle/gradle#28409] opened 2024-03-10 15:16 UTC
### Expected Behavior

I can declare a dependency on a Gradle plugin by using a `PluginDependency` of a version catalog.

```Gradle Kotlin DSL
dependencies {
    implementation(libs.plugins.jetbrains.intellij)
}
```

Alternatively, there should also be some dependency notation which works without version catalogs. For example, a `plugin(…)` method:

```Gradle Kotlin DSL
dependencies {
    implementation(plugin("org.jetbrains.intellij:1.17.2"))
}
```

### Current Behavior (optional)

Gradle does not provide any dependency notation for plugins, and reports an error when I try to use a `PluginDependency` from a version catalog.

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'NixIDEA'.
> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':classpath'.
      > Could not resolve project :plugins.
        Required by:
            project :
         > Cannot convert the provided notation to an object of type Dependency: org.jetbrains.intellij:1.17.2.
           The following types/formats are supported:
             - String or CharSequence values, for example 'org.gradle:gradle-core:1.0'.
             - Maps, for example [group: 'org.gradle', name: 'gradle-core', version: '1.0'].
             - FileCollections, for example files('some.jar', 'someOther.jar').
             - Projects, for example project(':some:project:path').
             - ClassPathNotation, for example gradleApi().
           
           Comprehensive documentation on dependency notations is available in DSL reference for DependencyHandler type.
```

### Context

The templates generated by the [build init plugin](https://docs.gradle.org/current/userguide/build_init_plugin.html) and the page [Sharing build logic between subprojects Sample](https://docs.gradle.org/current/samples/sample_convention_plugins.html) both suggest creating convention plugins as [precompiled script plugins](https://docs.gradle.org/current/userguide/custom_plugins.html#sec:precompiled_plugins). However, in practice, often builds also depends on third-party plugins.

```Gradle Kotlin DSL
plugins {
    `kotlin-dsl`
}

repositories {
    gradlePluginPortal()
}

dependencies {
    // How to specify my dependency here??
}
```

Instead of being able to specify the dependency in any reasonable way, you have to find out the maven coordinates of the plugin, which is usually undocumented.

### Workaround

I was looking through the source code of Gradle to find out how the plugin resolution is working using the marker artifact. It looks like Gradle is usually just adding `ArtifactRepositoriesPluginResolver.getMarkerDependency` as a dependency to the classpath.

https://github.com/gradle/gradle/blob/44dab3ba60df98488624587cd9e7a2bb74acc496/platforms/extensibility/plugin-use/src/main/java/org/gradle/plugin/use/resolve/internal/ArtifactRepositoriesPluginResolver.java#L174-L182

So, it seems like the following solution should work as a workaround is most cases:

```Gradle Kotlin DSL
dependencies {
    implementation(pluginDependency(libs.plugins.jetbrains.intellij))
}

fun pluginDependency(pluginProvider: Provider<PluginDependency>): Provider<Map<String, String>> {
    return pluginProvider.map {
        val id = it.pluginId
        mapOf(
            "group" to id,
            "name" to "$id.gradle.plugin", /* PLUGIN_MARKER_SUFFIX */
            "version" to it.version.requiredVersion,
        )
    }
}
```

**Comment by ov7a** [comment] 2024-03-11 09:53
This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/17963

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

**Closed by ov7a** 2024-03-11 09:53 UTC
Labels: a:feature, to-triage

**Comment by JojOatXGME** [comment] 2024-03-11 11:39
@ov7a Thanks, looks like I did not search well enough.
