### ISSUE TITLE
Dependency exclude rule on a both direct and transitive dependency is discarded

### ISSUE THREAD

**Issue by yetanotherion** [gradle/gradle#4269] opened 2018-02-05 20:35 UTC
When a dependency of a project appears both as
- direct dependency (written explicitly)
- transitive dependency of another direct dependency

The only way to exclude any of the transitive dependencies of the directAndTransitive
dependency consists at putting a global exclude.

### Expected Behavior
A local exclude in either the 
- directAndTransitiveDependency or
- directDependency
filters the jar.

### Current Behavior
The local exclude is discarded.

### Context
This impacts our maven to gradle transition (maven has the expected behavior)

### Steps to Reproduce (for bugs)
The following unit test reproduces the issue
https://github.com/gradle/gradle/compare/master...criteo-forks:discardedExcludeRule?expand=1

**Comment by yetanotherion** [comment] 2018-02-06 15:01
The problem is harder to fix than expected:

- the exclude rules are applied while discovering dependencies.

https://github.com/gradle/gradle/blob/master/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/DependencyGraphBuilder.java#L138

The exclude rule applied computed here
https://github.com/gradle/gradle/blob/master/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/NodeState.java#L156
```
//direct -> directAndTransitive -> foo
dependencies {
    compile directAndTransitive
    compile(direct) {
       exclude foo
    }
}

```
To resolve the configuration compile, gradle browses:
1. directAndTransitive, without any exclude rule and thus adds foo to the configuration.
2. direct, adds directAndTransitive that is already added, and filters foo, without removing it from the configuration (he does not know it came from directAndTransitive)

I'm afraid the fix would require quite a risky refactoring, 
i.e. 
1. first create the dependency graph
2.a. add the jars to the configuration based on the filtering
2.b detect the duplicated/useless dependencies and aggregate exclude rules accordingly, and execute the existing algorithm.

What do you think @bmuschko @bigdaz @melix @jjohannes @oehme  (taking the names from git blame) ?

**Comment by bigdaz** [comment] 2018-02-06 22:06
I'm pretty sure this is a duplicate of #1473, so I'm closing it in favour of that issue. Please see [this comment](https://github.com/gradle/gradle/issues/1473#issuecomment-342938454) to get an understanding of why this isn't going to be easy (or even possible) to fix.

**Closed by bigdaz** 2018-02-06 22:06 UTC
Labels: a:bug, from:contributor, in:dependency-management

**Comment by yetanotherion** [comment] 2018-02-07 09:34
It's indeed pretty close, however I think that the issue is a little bit different.
in
```//direct -> directAndTransitive -> foo
dependencies {
    compile directAndTransitive
    compile(direct) {
       exclude foo
    }
}
```

when visiting directAndTransitive, gradle does not have `direct->directAndTransitive`  in the 
`transitiveIncomingEdges`
 list 
(it only has root->directAndTransitive)

https://github.com/gradle/gradle/blob/master/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/NodeState.java#L142

Thus whether the union or intersection is applied does not affect the output (if I'm not mistaken this union/intersection is computed at
https://github.com/gradle/gradle/blob/master/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/NodeState.java#L269
```private ModuleExclusion getModuleResolutionFilter(List<EdgeState> incomingEdges) {
        ModuleExclusions moduleExclusions = resolveState.getModuleExclusions();
        ModuleExclusion nodeExclusions = moduleExclusions.excludeAny(metaData.getExcludes());
        if (incomingEdges.isEmpty()) {
            return nodeExclusions;
        }
        ModuleExclusion edgeExclusions = incomingEdges.get(0).getExclusions();
        for (int i = 1; i < incomingEdges.size(); i++) {
            EdgeState dependencyEdge = incomingEdges.get(i);
            edgeExclusions = moduleExclusions.union(edgeExclusions, dependencyEdge.getExclusions());
        }
        return moduleExclusions.intersect(edgeExclusions, nodeExclusions);
    }
```

**Comment by bigdaz** [comment] 2018-02-07 16:32
In your example, there are 2 paths to `foo`:
```
root -> direct-and-transitive -> foo
root -> direct -> direct-and-transitive -> foo
```
Unless both of these paths exclude `foo`, then Gradle is going to include `foo` in the result. This is the same use case as described in #1473.

Note that this:
```
    runtime(directAndTransitive) {
        exclude foo
    }
```
does _not_ mean "everywhere in the runtime graph that you see 'directAndTransitive', exclude 'foo'". It means "for this particular dependency on 'directAndTransitive', exclude 'foo'". 

Using an exclude like this is telling Gradle that for this particular `runtime` usage of `directAndTransitive`,  `foo` is not required. But if there's another reason that `directAndTransitive` is required (because it's transitively required as part of the runtime classpath of `direct`), then Gradle will assume that `foo` _is_ required.

If you want to globally exclude `foo` from your runtime classpath, then you don't add the exclude as an attribute of a particular dependency. Instead, you can define an exclude globally for the configuration, or you can use a "Component Metadata Rule" to modify the metadata of `directAndTransitive` so that `foo` is _always_ excluded.

**Comment by yetanotherion** [comment] 2018-02-07 17:51
Thanks for your answers @bigdaz. In case there was a misunderstanding
>Unless both of these paths exclude foo, then Gradle is going to include foo in the result. This is the same use case as described in #1473.

I was just trying to provide a second root cause on why in this particular case foo will be included:
- root cause 1: the one you mentioned in #1473
- root cause 2: the fact that directDependency is not in the transitiveIncoming list (I reproduce the bug by putting union instead of intersect too in getModuleResolutionFilter).

> does not mean "everywhere in the runtime graph that you see 'directAndTransitive', exclude 'foo'". It means "for this particular dependency on 'directAndTransitive', exclude 'foo'". If you want to globally exclude foo from your runtime classpath, then you don't add the exclude as an attribute of a particular dependency. Instead, you can define an exclude globally for the configuration,

As suggested in the issue you linked, gradle and maven have different semantics regarding excludes. I opened the issue hoping that aligning the semantics would be reasonably easy, but I agree with you it is not :(
Our plan B (we're migrating a big maven project to a ~1000 multi project gradle build) consists at modifying our converter to put a global exclude in the configuration as you suggested.
> or you can use a "Component Metadata Rule" to modify the metadata of directAndTransitive so that foo is always excluded.

Thanks for the tip!
