### ISSUE TITLE
GroovyJarFile cannot resolve a symlink location in the classpath

### ISSUE THREAD

**Issue by Alex-Vol-Amz** [gradle/gradle#28664] opened 2024-04-02 21:23 UTC
### Current Behavior

Our build system uses a home grown plugin to inject alternative dependency coordinates for popular libraries managed internally and not aligned with the common public dependency coordinates. It is interesting to note that this system makes heavy use of symlinks in the process and the concrete target files provided retain the expected file names.

One case that is particularly problematic is the Groovy runtime. This is resolved by the GroovyJarFile construct in Gradle and it assumes a File reference is representing the actual JAR file to pattern match for the expected artifact name. The symlink name fails the pattern matching and causes the problems.

### Current Behavior

The error we see when this resolution fails is this:

```
Caused by: org.gradle.api.GradleException: Cannot infer Groovy class path because no Groovy Jar was found on class path:
 at org.gradle.api.tasks.GroovyRuntime$1.inferGroovyClasspath(GroovyRuntime.java:118)
        at org.gradle.api.tasks.GroovyRuntime$1.createDelegate(GroovyRuntime.java:108)
```

### Expected Behavior

The alternative classpath entry does not cause a failure and can be used in place of the public accepted coordinates.

### Context (optional)

We are failing to make use of certain components that rely on Groovy Runtime.

### Potential fix for the issue

The issue can be resolved if [the code found here](https://github.com/gradle/gradle/blob/master/platforms/jvm/plugins-groovy/src/main/java/org/gradle/api/internal/plugins/GroovyJarFile.java#L62-L66) performs a resolution of the real path instead of using the provided File object in raw form.

I performed an experiment adding this code to find that the issue is resolved.

```diff
     @Nullable
     public static GroovyJarFile parse(File file) {
+        try {
+            // Resolve a symlink file to the real location
+            file = file.toPath().toRealPath().toFile();
+        } catch (IOException e) {
+            // Let the code use the original File otherwise
+        }
         Matcher matcher = FILE_NAME_PATTERN.matcher(file.getName());
         return matcher.matches() ? new GroovyJarFile(file, matcher) : null;
     }
```

### Steps to Reproduce

Here is a very small github project that can demonstrate the issue:

https://github.com/Alex-Vol-Amz/groovy-jar-symlink-issue

### Gradle version

7.6.1

### Your Environment (optional)

Currently experiencing this with Gradle 7 and plan to continue using with Gradle 8. Hopefully a fix can be provided in the 8.x time frame for new releases.

**Comment by ov7a** [comment] 2024-04-04 12:35
There is a potential performance problem of requesting a real path, because the method is invoked for every library in the classpath. Probably it can be resolved with two levels of checks, limiting the real path resolution to only something that has `groovy` in its filename. Would it work in your use case?

**Comment by Alex-Vol-Amz** [comment] 2024-04-04 15:02
Good point and yes, that would work. Our naming conventions happen to keep the `groovy` name but other aspects including version numbers and group are twisted. The ideal option is to have the resolved symlink for the names that are likely to be candidates.

**Comment by ov7a** [comment] 2024-04-08 08:27
The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by big-guy** [comment] 2024-04-09 16:49
@Alex-Vol-Amz would you be interested in submitting your change as a PR?

The real fix for this would be to remove the need for GroovyJarFile entirely, but this is a deeper change to the way the Groovy plugin works.

**Comment by big-guy** [comment] 2024-04-16 16:26
@Alex-Vol-Amz we can see if the performance impact as you have it is a big deal with our tests.  You can just submit what you have plus an integ test.

**Comment by Alex-Vol-Amz** [comment] 2024-04-16 20:41
I posted the working PR with unit tests. I have not come up with a clever way to simulate this environment in an integration test yet. If you think an integration test is a must have I will try to work out the detail. I may end up using the mechanism I did for the example project that reproduced the issue on the description of this bug.

**Closed** 2024-04-19 23:54 UTC
Labels: a:bug, in:groovy-plugin
