### ISSUE TITLE
Gradle Incorrectly Assumes Choosing Higher Dependency Major Version Is Safe

### ISSUE THREAD

**Issue by EarthCitizen** [gradle/gradle#6958] opened 2018-09-30 17:25 UTC
When resolving dependencies, Gradle assumes that when there is a major version difference between two dependencies, that taking the higher version is safe.

Take the following two example projects:

*project-a*
```
apply plugin: 'java'

repositories {
  mavenCentral()
}

dependencies {
  compile 'junit:junit:3.7'
  compile 'com.abc:project-b:1.0.0'
}
```

*project-b*
```
apply plugin: 'java'

repositories {
  mavenCentral()
}

group = 'com.abc'
version = '1.0.0'

dependencies {
  compile 'junit:junit:4.12'
}
```
The following dependency tree is generated:
```
project-a $ ./gradlew dependencies --include-build ../project-b --configuration compile

> Task :dependencies

------------------------------------------------------------
Root project
------------------------------------------------------------

compile - Dependencies for source set 'main' (deprecated, use 'implementation' instead).
+--- junit:junit:3.7 -> 4.12
|    \--- org.hamcrest:hamcrest-core:1.3
\--- com.abc:project-b:1.0.0 -> project :project-b
     \--- junit:junit:4.12 (*)

(*) - dependencies omitted (listed previously)

A web-based, searchable dependency report is available by adding the --scan option.

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
```

_NOTE: Using JUnit in this example is an arbitrary choice for demonstration purposes only. This issue is not related specifically to JUnit._

### Expected Behavior
Gradle should not assume that choosing 4.x over 3.x is safe. There is no safe way forward as this point. Gradle should fail. By issuing a new major version, the library owner is clearly stating _"this is most likely not compatible with the previous major version"_.

Taking higher minor versions should continue to be OK. If a minor version upgrade is not backwards compatible, that is the fault of the library owner.

### Current Behavior
Gradle silently accepts a higher major version, likely causing unexpected behavioral differences in the software. This is not the fault of the library owner, this is the fault of Gradle.

### Context
Silently taking higher major versions allows dangerous scenarios of unexpected software behavior. Upgrades in major versions will not always cause compilation errors.

### Steps to Reproduce (for bugs)
See above.

### Your Environment
Gradle 4.10.2

**Comment by melix** [comment] 2018-10-01 11:04
@EarthCitizen Thanks for this report. The good news is that we are very aware of this. In particular, this is on our roadmap. We want library authors, as well as users, to be able to define compatibility rules. In particular, there are lots of libraries which use semantic versioning, and it would be nice to honor this. The problem is not easy, though, and cannot be simplified to "don't upgrade" or "always upgrade". There are assumptions which are sometimes correct (most libraries would upgrade safely), and sometimes not (minor releases shouldn't contain breaking changes). In short, we will allow more flexibility in how you describe the model for different libraries in the future.

**Comment by oehme** [comment] 2018-10-01 15:40
@melix I'm sure we have some issue tracking these future developments already, can we close this as a duplicate?

**Comment by ljacomet** [comment] 2018-10-02 14:48
Will close this and the Gradle team will open specific items once work on supporting a form of semantic versioning happens and its potential impact on resolution strategy.

**Closed by ljacomet** 2018-10-02 14:48 UTC
Labels: in:dependency-management
