### ISSUE TITLE
`./gradlew dependencies` recurse into subprojects

### ISSUE THREAD

**Issue by mathjeff** [gradle/gradle#27728] opened 2024-01-17 17:28 UTC
### Current Behavior

It would be nice if `./gradlew dependencies` would output all dependencies of all subprojects

### Expected Behavior

Currently I'm observing that `./gradlew dependencies` is only outputting the dependencies of the current project (usually the root project)

### Context (optional)

I was validating [a change](https://github.com/gradle/gradle/issues/27407#issuecomment-1896235639) and wanted to see all of the resolved dependencies of the build. The first thing that I tried was `./gradlew dependencies` but that didn't appear to recurse into subprojects.

I was surprised because for other task names, I observe that `./gradlew ${taskName}` searches for the task with that name in the current project and all subprojects

### Steps to Reproduce

This seems to reproduce in the build of Gradle itself too, for example check out https://github.com/gradle/gradle/blob/v8.5.0/ and run `./gradlew dependencies` and see that only one `:dependencies` task runs

### Gradle version

8.6-rc-1

**Comment by cobexer** [comment] 2024-01-22 09:57
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #19289
* #17101

Please add your use case and 👍 to those issues.

**Closed by cobexer** 2024-01-22 09:57 UTC
Labels: a:bug, to-triage

**Comment by mathjeff** [comment] 2024-01-24 21:32
Thanks!
