### ISSUE TITLE
Linux file copy operations fail on read-only files

### ISSUE THREAD

**Issue by vydra** [gradle/gradle#1544] opened 2017-03-09 05:07 UTC
Every Gradle Copy task we have has had to include 'filemode = 0644' to get around the read-only file problem. We've experienced this ever since we adopted Gradle 2.14 all the way up to now in 3.4

### Expected Behavior
File should be writable without providing an explicit mask

### Current Behavior
1. A gradle task copies a file with permissions set to read-only 
2. The destination file preserves the read-only 
3. Sometime later, the same task is invoked again and fails because it cannot overwrite the read-only destination file

### Context
Linux, Perforce

### Your Environment

 * Build scan URL:

**Comment by bmuschko** [comment] 2017-03-09 11:55
I am pretty sure that the issue is Perforce-related and not a Gradle bug. Perforce automatically makes files read-only based on its operation mode. I remember working with a client that had exactly the same issue. We decided to change the `filemode` accordingly.

If you want to fix the issue globally for your project, then you can do the following a multi-project build:

```
allprojects {
    tasks.withType(Copy) {
        filemode = 0644
    }
}
```

**Comment by KidDaedalus** [comment] 2017-03-09 20:56
I've reflexively avoided `allprojects` and `subprojects` as a threat to configure-on-demand. 
I have a commonly applied script-plugin which does the `tasks.withType()` thing but it isn't guaranteed to be applied last so not every copy task may have been added to the DAG at the time `withType()` runs. 

Would your proposed snippet affect configure on demand?

**Comment by bmuschko** [comment] 2017-03-14 11:35
If you put the logic into `allprojects` or `subprojects` in the root project then it should have no effect on configure on demand. For more information please see the [user guide](https://docs.gradle.org/current/userguide/multi_project_builds.html#sec:configuration_on_demand):

> The root project is always configured. This way the typical common configuration is supported (allprojects or subprojects script blocks).

You will probably want to have a look at the root of the issue: Perforce. Is there any way you can configure it to avoid making files read-only?

**Comment by bmuschko** [comment] 2017-03-15 15:24
I am going to close the issue for now. Please let us know if you need further assistance.

**Closed by bmuschko** 2017-03-15 15:24 UTC
Labels: a:question, from:member, in:core

**Comment by jsolomon8080** [comment] 2017-04-03 16:44
I don't think this is a perforce issue at all @bmuschko. Why should a build system assume that all the files its managing are writable? Why can't files be read-only? I think it's completely reasonable that files are read-only. Regardless, how hard would it be for gradle devs to fix this bug? I assume you have one place where you actually perform the update in a copy task. In that one place, why not force the update or just delete the file before hand?

The problem with fileMode=0644 is that the src file we're copying might not be just a read-only file with perms of 0444. What if it's executable? Then when we set the fileMode to 0644 we're actually doing the wrong thing.

**Comment by CoolPrem** [comment] 2017-11-28 18:37
Can we reopen this?

Copy task needs to preserve the file permissions of the source file in the target. If the source file was read only and had execute permissions(Eg: 0555), any subsequent run of the Copy task fails siting lack of permissions to overwrite. In this case fileMode of 0644 does not make any sense as it strips off the execute permissions in the file.

**Comment by ggascoigne** [comment] 2018-05-09 23:46
I'd vote for re-opening this as well.  We  use gradle to layout files for later installation, it is intended that some of them be read-only.  Having to force delete them before re-running a copy task because there's no way to have that copy task overwrite read-only files is very awkward.

**Comment by staffanf** [comment] 2018-10-09 15:38
This is very similar to https://github.com/gradle/gradle/issues/1267. Please +1 that issue if this is not re-opened.
We keep hitting this on regular basis, today one of our devs hit it but adding new test resources , which failed processTestResources.
The workaround by @bmuschko might solve that specific case if we apply in to ProcessResources tasks and add some extra test code to modify permission bits in the tests, but we could not apply it to all Copy tasks since we also want to create release tars with read only permissions.

**Comment by milahu** [comment] 2024-07-11 05:47
expected solution

```
allprojects {
    tasks.withType(Copy) {
        force = true
    }
}
```

like the `cp` command

```sh
cd $(mktemp -d)
echo a > a
echo b > b
chmod -w *
cp a b # cp: cannot create regular file 'b': Permission denied
cp --force a b
cat b # a
```
