### ISSUE TITLE
Zip task with zip64 true produces zip files with headers error

### ISSUE THREAD

**Issue by mfbieber** [gradle/gradle#16811] opened 2021-04-13 13:22 UTC
When creating zip files with the zip task, we observe that zip files with a headers error are created. It seems to us, that this happens when we set `zip64 true`.

### Expected Behavior
Zips are created without headers error.

### Current Behavior
Zips are created with headers error.

### Context
This can lead to all kinds of issues with the created zip files, e.g. when trying to unzip them later.

### Steps to Reproduce 
Here is a working example to reproduce the behavior: https://github.com/mfbieber/gradle-zip-headers-error/blob/main/minimalExample.gradle

This is the relevant code (included in the mentioned repository):
````
task ziptest(type: Zip) {
  archiveName "test.zip"

  destinationDir file(".")
  duplicatesStrategy DuplicatesStrategy.EXCLUDE
  zip64 true
  includeEmptyDirs = false
  
  def buildFile = new File(".", 'test.txt')
  buildFile.text = "test"
  into ('/') { from buildFile }
  
  doLast {
    delete fileTree('.') {
        include '*.txt'
    }
  }
}

````

The error can be seen either by trying to extract the zip file with 7Zip:
![7ziperror](https://user-images.githubusercontent.com/37021266/114559054-a0e92600-9c6b-11eb-9841-d441c181f42a.png)

Or for with other 7Zip versions, we saw it only through the properties:
![7zipproperties](https://user-images.githubusercontent.com/37021266/114559055-a21a5300-9c6b-11eb-9925-d9e8c7ac7bd8.png)

Thanks in advance!

**Comment by bmuskalla** [comment] 2021-04-13 14:53
Thanks, @mfbieber for the great bug report and the reproducer. Would you do me a favor and try a few things as I'm unable to reproduce this on my side:
a) you can try Gradle 7.0 and see if you still encounter this issue?
b) Can you try other zip tools and see if they see similar issues?

Running the reproducer, the resulting zip can be properly unzipped by the tools at my disposal (on macOS, used unarchiver and `unzip`):
```
❯ unzip -t test.zip
Archive:  test.zip
    testing: test.txt                 OK
No errors detected in compressed data of test.zip.
```

**Comment by bmuskalla** [comment] 2021-04-13 14:59
After digging some more, it seems that `7Zip` has issues if `zip64` [headers are not present](https://stackoverflow.com/questions/57557842/how-to-resolve-7-zips-warnings-headers-error-from-zip-created-by-ant-build). The flag in your build script `zip64 true` is not to enable it but to enable it *if needed*. See also `Zip64Mode`. So to workaround 7zips problems dealing with this, it would require a new feature in Gradle to *force* `zip64` (see also DefaultZipCompressor).

**Comment by mfbieber** [comment] 2021-04-13 18:05
> Thanks, @mfbieber for the great bug report and the reproducer. Would you do me a favor and try a few things as I'm unable to reproduce this on my side:
> a) you can try Gradle 7.0 and see if you still encounter this issue?

Yes, I see the same error:
````
mfernandezbi@MFERNANDEZBI-01 MINGW64 ~/Downloads/gradle-zip-headers-error (main)
$ dir
7ziperror.png  7zipproperties.png  build.gradle  gradle  gradlew  gradlew.bat  minimalExample.gradle  settings.gradle  test  test.zip

mfernandezbi@MFERNANDEZBI-01 MINGW64 ~/Downloads/gradle-zip-headers-error (main)
$ gradle --version

Welcome to Gradle 7.0!

Here are the highlights of this release:
 - File system watching enabled by default
 - Support for running with and building Java 16 projects
 - Native support for Apple Silicon processors
 - Dependency catalog feature preview

For more details see https://docs.gradle.org/7.0/release-notes.html


------------------------------------------------------------
Gradle 7.0
------------------------------------------------------------

Build time:   2021-04-09 22:27:31 UTC
Revision:     d5661e3f0e07a8caff705f1badf79fb5df8022c4

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          14.0.2 (AdoptOpenJDK 14.0.2+12)
OS:           Windows 10 10.0 amd64


mfernandezbi@MFERNANDEZBI-01 MINGW64 ~/Downloads/gradle-zip-headers-error (main)
$ gradle ziptest
Starting a Gradle Daemon (subsequent builds will be faster)

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 6s
1 actionable task: 1 executed
````
![gradle7ziperror](https://user-images.githubusercontent.com/37021266/114598932-c178a680-9c92-11eb-9732-fdd7e60ba7a7.png)



> b) Can you try other zip tools and see if they see similar issues?
> 
> Running the reproducer, the resulting zip can be properly unzipped by the tools at my disposal (on macOS, used unarchiver and `unzip`):
> 
> ```
> ❯ unzip -t test.zip
> Archive:  test.zip
>     testing: test.txt                 OK
> No errors detected in compressed data of test.zip.
> ```

The unzip utility shows the same output as yours for the same zip which contains the error visible with 7Zip:
````
mfernandezbi@MFERNANDEZBI-01 MINGW64 ~/Downloads/gradle-zip-headers-error (main)
$ unzip
UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send
bug reports using http://www.info-zip.org/zip-bug.html; see README for details.

Usage: unzip [-Z] [-opts[modifiers]] file[.zip] [list] [-x xlist] [-d exdir]
  Default action is to extract files in list, except those in xlist, to exdir;
  file[.zip] may be a wildcard.  -Z => ZipInfo mode ("unzip -Z" for usage).

  -p  extract files to pipe, no messages     -l  list files (short format)
  -f  freshen existing files, create none    -t  test compressed archive data
  -u  update files, create if necessary      -z  display archive comment only
  -v  list verbosely/show version info       -T  timestamp archive to latest
  -x  exclude files that follow (in xlist)   -d  extract files into exdir
modifiers:
  -n  never overwrite existing files         -q  quiet mode (-qq => quieter)
  -o  overwrite files WITHOUT prompting      -a  auto-convert any text files
  -j  junk paths (do not make directories)   -aa treat ALL files as text
  -U  use escapes for all non-ASCII Unicode  -UU ignore any Unicode fields
  -C  match filenames case-insensitively     -L  make (some) names lowercase
  -X  restore UID/GID info                   -V  retain VMS version numbers
  -K  keep setuid/setgid/tacky permissions   -M  pipe through "more" pager
See "unzip -hh" or unzip.txt for more help.  Examples:
  unzip data1 -x joe   => extract all files except joe from zipfile data1.zip
  unzip -p foo | more  => send contents of foo.zip via pipe into program more
  unzip -fo foo ReadMe => quietly replace existing ReadMe if archive file newer

mfernandezbi@MFERNANDEZBI-01 MINGW64 ~/Downloads/gradle-zip-headers-error (main)
$ unzip -t test.zip
Archive:  test.zip
    testing: test.txt                 OK
No errors detected in compressed data of test.zip.
````

I mentioned it above, but some of our colleagues didn't notice the headers error because 7Zip also did not complain. They could only see it via the properties. So I guess many tools will be able to unzip without complaining. We've seen this behavior before with corrupt zip files, but this lead afterward to corrupt extracted files that caused other errors in our processing pipeline (e.g. MimeType detectors).

**Comment by bmuskalla** [comment] 2021-04-14 09:19
Thanks for checking! Just to clarify, `7zip` only shows `Warnings: header errors` but lets you unzip the file successfully?

**Comment by mfbieber** [comment] 2021-04-14 09:23
> Thanks for checking! Just to clarify, `7zip` only shows `Warnings: header errors` but lets you unzip the file successfully?

Yes, this is what I can observe.

We checked internally and we don't really need the `zip64 true` option anymore, so we will be removing it and thus will not run into the error.

Maybe it is worth it to fix this headers error warning issue anyways - someone will probably need it ;)

**Comment by bmuskalla** [comment] 2021-04-14 09:27
> We checked internally and we don't really need the zip64 true option anymore, so we will be removing it and thus will not run into the error.
Great that this is not blocking you anymore!

Regarding fixing this, I don't really see this as a problem on the Gradle side, to be honest. The archive we produce is valid and only has the metadata it requires. I think this is an issue that needs to be fixed on the 7zip side. Given you're unblocked, I'm going to close this one. Thanks for your time reporting this!

**Closed by bmuskalla** 2021-04-14 09:27 UTC
Labels: a:feature, in:file-tasks

**Comment by mfbieber** [comment] 2021-04-14 09:33
Thanks for your quick replies 👍
