### ISSUE TITLE
New CLI prevents user from opening failed test report by clicking link

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1524] opened 2017-03-06 23:02 UTC
### Expected Behavior

User can click on link. The browser automatically opens and renders failed test report.

### Current Behavior

Hand icon shows up but clicking the link does not result in browser being opened.

There's also some overlapping output from previous rendering of `IDLE`:

```
* What went wrong:
Execution failed for task ':jacoco:integTest'.
> There were failing tests. See the report at: file:///Users/bmuschko/dev/projects/gradle/subprojects/jacoco/build/reports/integTest/index.htmlDLE
```

**Comment by lacasseio** [comment] 2017-03-10 18:04
This has been fixed with commit https://github.com/gradle/gradle/commit/826f3d11165e36c5a165c161a5238801ab572d03. I will close this now. Reopen if the issue is still present.

**Closed by lacasseio** 2017-03-10 18:04 UTC
Labels: a:bug, from:member, in:core
