### ISSUE TITLE
Version catalog error message do not include path to the toml file.

### ISSUE THREAD

**Issue by jdochez** [gradle/gradle#24065] opened 2023-02-28 00:07 UTC
I messed up a toml declaration and got : 
`org.gradle.api.InvalidUserDataException: Invalid TOML catalog definition:
  - Problem: In version catalog libs, parsing failed with 2 errors.
    
    Reason: At line 2, column 26: Unexpected '.', expected a newline or end-of-input
    At line 3, column 13: Unexpected '.', expected a newline or end-of-input.
    
    Possible solution: Fix the TOML file according to the syntax described at https://toml.io.
    
    Please refer to https://docs.gradle.org/8.0/userguide/version_catalog_problems.html#toml_syntax_error for more details about this problem.`

nice message except it would be much better to also include the file path in question...

**Comment by ljacomet** [comment] 2023-03-02 09:17
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #20368

Please add your use case and 👍 to that issue.

**Closed by ljacomet** 2023-03-02 09:17 UTC
Labels: closed:duplicate
