### ISSUE TITLE
Performance issue with the registration of shared build services

### ISSUE THREAD

**Issue by nav-nav** [gradle/gradle#25568] opened 2023-06-30 10:06 UTC
### Expected Behavior

Registration of BuildService/OperationCompletionListener should not affect configuration time.

### Current Behavior

For test purposes I have added and registered simple BuildService in kotlin project and run performance test on https://github.com/duckduckgo/ project with Gradle 7.6 with `./gradlew help` command. Time increased from 1134ms to 1177ms:
![image](https://github.com/gradle/gradle/assets/19590205/8e0fd8f3-3d3d-419d-9b1f-667ba86294f5)

### Context (optional)

There is a performance regression for kotlin 1.9.0 (https://youtrack.jetbrains.com/issue/KT-59363). For this 2 BuildService and 3 OperationCompletionListener were created. So this issue can have an impact on the performance. No impact on small project

### Steps to Reproduce

Add and register BuildService:
```
internal abstract class TestFlowService : BuildService<BuildServiceParameters.None>, AutoCloseable, OperationCompletionListener {
    private var buildFailed: Boolean = false

    companion object {
        private val serviceName = "${TestFlowService::class.simpleName}_${TestFlowService::class.java.classLoader.hashCode()}"

        fun registerIfAbsent(
            project: Project,
        ): Provider<TestFlowService> {

            project.gradle.sharedServices.registrations.findByName(TestFlowService.serviceName)?.let {
                @Suppress("UNCHECKED_CAST")
                return it.service as Provider<TestFlowService>
            }

            return project.gradle.sharedServices.registerIfAbsent(TestFlowService.serviceName, TestFlowService::class.java) {
            }.also { buildService ->
                BuildEventsListenerRegistryHolder.getInstance(project).listenerRegistry.onTaskCompletion(buildService)
            }
        }
    }

    override fun onFinish(event: FinishEvent?) {
        if (event is TaskFinishEvent) {
            if (event.result is TaskFailureResult) {
                buildFailed = true
            }
        }
    }

    override fun close() {
        System.out.println("Service is closed with $buildFailed")
    }
}
```

Compare time for `./gradlew help` on project with applied plugin (with and without additional service )

### Gradle version

7.6

**Comment by abstratt** [comment] 2023-07-11 03:38
@nav-nav I tried to reproduce this with Gradle's own build, since DuckDuckGo's build s still using Gradle 7.3.

Please take a look at the branch for this PR: https://github.com/gradle/gradle/pull/25701

I tested it using:

```
./gradlew help --task simple -DnumberOfServices=10 -DcreationWait=100  --info --no-configuration-cache  
```

I could not introduce any major impact to build time even if I chose a thousand services, or set te creation wait to 1000.

Am I missing something from your test case?

BTW, I tried with Gradle 7.6 as well (3905fe8ac07) and the result was not much different.

**Comment by abstratt** [comment] 2023-07-17 20:27
<img width="1310" alt="Screenshot 2023-07-17 at 16 55 27" src="https://github.com/gradle/gradle/assets/2187522/345335b9-c8d9-4166-a40a-2494b791ea17">

@nav-nav Please see Gradle Profiler report comparing performance between registering 1, 2, 10, 100, 1000 and 10000 services. Only the latter shows a significant difference in the build time, and that is an insanely large (and unrealistic) number of services.

Are these tests failing to capture something from you scenario?

**Comment by abstratt** [comment] 2023-07-20 12:02
@nav-nav Any updates from your side? Thanks!

**Comment by abstratt** [comment] 2023-12-29 15:53
Closing. Please reopen if you have any more information on this.

**Closed by abstratt** 2023-12-29 15:53 UTC
Labels: a:bug, @configuration-cache, in:build-services, to-triage
