### ISSUE TITLE
Gradle sometimes reports that it has been executing for a negative number of milliseconds

### ISSUE THREAD

**Issue by wilkinsona** [gradle/gradle#24054] opened 2023-02-27 11:14 UTC
### Expected Behavior
The execution time reported by Gradle is always positive.

### Current Behavior
The execution time is sometimes negative, and when it is, the unit always appears to be milliseconds:

```
<===----------> 23% EXECUTING [-4067648ms]
…
<===----------> 28% EXECUTING [-4001044ms]
…
<===----------> 29% EXECUTING [-3917532ms]
```

The above shows the execution times copied from the same build while it was in progress.

### Context
At first, I thought the problem was only cosmetic. Unfortunately, it appears to mess up a build scan. For example https://ge.spring.io/s/zqrdqdtey4hao shows incorrect data in the performance and timeline sections. It spent nowhere near the claimed 1h 8m 11.702s in startup.

### Steps to Reproduce 
Unfortunately, I'm not sure how to reproduce the problem but I have seen it with both Gradle 7.5.1 and, more recently, with 7.6. It appears to be related to the daemon as running `./gradlew --stop` fixes it.

### Your Environment
Build scan URL: https://ge.spring.io/s/zqrdqdtey4hao

**Comment by ov7a** [comment] 2023-03-08 09:35
Thanks for reporting this to Gradle. This is not the first time we stumble upon this issue, but we don't have a good reproducer for it. If anyone could provide a reproducer for this issue, it would be very appreciated.

**Comment by ov7a** [comment] 2023-03-17 09:38
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/14439

Please add your use case and 👍 to that issue.

***

Since we have another issue with a reproducer, are you aware of any system time changes in your case?

**Closed by ov7a** 2023-03-17 09:38 UTC
Labels: in:logging, a:bug

**Comment by distinctdan** [comment] 2025-02-28 18:15
I'm also experiencing this. It started happening with no code changes, seemingly for no reason.

**Comment by distinctdan** [comment] 2025-02-28 18:35
Here's my sequence of events. I'm only able to reproduce this intermittently, with no code changes. The negative value appears to be preventing logs from showing in IntelliJ whch is very annoying.
 - Change branches to my current branch and run gradle sync in IntelliJ.
 - Do `./gradlew run`, which builds and works correctly the first time
 - Do `./gradlew run` again, which might displays the negative time. I've seen negative times ranging from -10000ms to -1000000ms.
 - The bug happens both when running in IntelliJ and also from the command line.
