### ISSUE TITLE
No warning/error is present in case of error executing JUnit Platform tests

### ISSUE THREAD

**Issue by baev** [gradle/gradle#8956] opened 2019-04-05 14:56 UTC
In case of JUnit Platform Engine failed to execute tests there is no warning at all, and test task is successful. In our case after updating to JUnit 5.4.1 we missed that fact that all our tests are actually are not executed.

### Expected Behavior

Fail the test task or at least write a huge red warning ⚠️ 

### Current Behavior

There is no signal of test run failure at all.

### Context

The original JUnit 5 issue can be found here https://github.com/junit-team/junit5/issues/1773

### Steps to Reproduce 

Demo project that reproduces the problem https://github.com/baev/gradle-junit5-issue

### Your Environment

Gradle: 5.2.1
Build scan URL: https://scans.gradle.com/s/pofmy43de2qzg/

**Comment by KrauseStefan** [comment] 2019-05-01 11:30
We have also experienced a very similar issue, it would be nice if Gradle would detect that JUnit had failed.
I don't know which project should implement fix this though.

I've posted the full exception stack trace below to try and add some clarity as to how this could fail, I hope you do not consider this spamming.

In our case it was a `testCompileOnly` that should have been a `testCompile` and therefore the annotation processor failed. This happened in relation to a wildfly upgrade of the package `org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:1.0.0.Final`

The result was that we had over 1000 test not running anymore luckily we had an other test that caught this drop in test executions. We had to force the test to run again and add the --info flag to get the stracktrace, since the test execution was reported as successful.

Let me know if I need to work on a reproduction case.

```
Gradle Test Executor 2 STANDARD_ERROR
    May 01, 2019 9:17:43 AM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
    WARNING: TestEngine with ID 'junit-vintage' failed to discover tests
    java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
        at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
        at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
        at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
        at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
        at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
        at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
        at java.lang.Class.createAnnotationData(Class.java:3521)
        at java.lang.Class.annotationData(Class.java:3510)
        at java.lang.Class.getAnnotations(Class.java:3446)
        at org.junit.runner.Description.createSuiteDescription(Description.java:124)
        at org.junit.internal.runners.ErrorReportingRunner.getDescription(ErrorReportingRunner.java:28)
        at org.junit.vintage.engine.descriptor.RunnerTestDescriptor.<init>(RunnerTestDescriptor.java:44)
        at org.junit.vintage.engine.discovery.TestClassRequestResolver.createCompleteRunnerTestDescriptor(TestClassRequestResolver.java:92)
        at org.junit.vintage.engine.discovery.TestClassRequestResolver.determineRunnerTestDescriptor(TestClassRequestResolver.java:64)
        at org.junit.vintage.engine.discovery.TestClassRequestResolver.createRunnerTestDescriptor(TestClassRequestResolver.java:59)
        at org.junit.vintage.engine.discovery.VintageDiscoverer.lambda$discover$0(VintageDiscoverer.java:53)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.junit.vintage.engine.discovery.VintageDiscoverer.discover(VintageDiscoverer.java:55)
        at org.junit.vintage.engine.VintageTestEngine.discover(VintageTestEngine.java:62)
        at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:168)
        at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:155)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:102)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:82)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:78)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy2.stop(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by tinesoft** [comment] 2019-06-30 08:43
Any updates on this?

**Comment by ming13** [comment] 2019-07-14 16:48
@marcphilipp, sorry to ping you on this, but I believe is a dangerous issue. I’ve encountered this personally while writing a custom `TestEngine`. I’m throwing an exception on the discovery phase to block tests with the same name on a hierarchy level. While this works in IJ, it doesn’t with Gradle. Different `TestEngine` might have implemented a similar strategy of failing the discovery but this issue essentially suppresses it.

**Comment by marcphilipp** [comment] 2019-07-15 06:04
@ming13 https://github.com/junit-team/junit5/issues/1944 is another occurrence of the same underlying issue. We're going to make such exceptions an error during execution in an upcoming version (probably 5.6). For now, you can store such validation errors in the `TestDescriptor` returned from your engine in `discover()` and throw an exception when it is passes to `execute()`.

@baev I tried your sample project again and it runs tests for me.

Generally speaking, I think this issue should be solved in JUnit, not Gradle.

**Comment by marcphilipp** [comment] 2019-09-23 11:04
This was fixed by https://github.com/junit-team/junit5/issues/1909 for JUnit Vintage 5.6 (yet to be released).

**Closed by marcphilipp** 2019-09-23 11:04 UTC
