### ISSUE TITLE
executableDir = "" does not work in Windows start script

### ISSUE THREAD

**Issue by tomas-pluskal** [gradle/gradle#10387] opened 2019-08-28 17:49 UTC
I am using Gradle 5.6.1

With the following settings
```
application {
    executableDir = ""
}
```

The unix start script works fine, but the windows start script contains 
`set JAVA_HOME="%~dp0.."` and subsequently fails with this error:

```
ERROR: The directory "C:\Users\plusik\mzmine2\build\MZmine-2.50-win\.." does not contain a valid Java runtime for your platform.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```
despite java.exe being present in the bin directory.

This issue was reported previously as #4675 and supposedly fixed with commit https://github.com/gradle/gradle/commit/e8a1ce60c89899228e03b97adbf4ceddb049f4de, however it seems only the unix script was actually fixed, not the windows script.

**Comment by tomas-pluskal** [comment] 2019-12-10 15:07
This issue still present in version 6.0.1

**Comment by Legion2** [comment] 2020-08-17 15:49
Still present in version 6.6

As a workaround with empty `executableDir`:
```
application {
    executableDir = ""
}
```
Add:
```kotlin
tasks.withType<CreateStartScripts> {
    doLast {
        windowsScript.writeText(windowsScript.readText()
                .replace("set JAVA_HOME=\"%~dp0..\"", "set JAVA_HOME=\"%~dp0\""))
    }
}
```
This is the `.gradle.kts` version based on https://github.com/beryx/badass-runtime-plugin/issues/67#issuecomment-672348355

**Comment by mlopatkin** [comment] 2021-08-11 08:54
I don't see `set JAVA_HOME="%~dp0.."` in the Gradle start script. It doesn't make sense there because there is no bundled JVM in the application built by Gradle's `application` plugin. I suppose the issue is specific to the badass-runtime-plugin because this plugin actually bundles Java runtime into the application and it is reasonable to set up `JAVA_HOME` this way. The badass-runtime-plugin is a third-party plugin so the issue cannot be fixed in the core Gradle (and it seems to be fixed in the plugin already)

I might be missing something so please provide a reproducer if you think the issue is in the Gradle core plugins.

**Closed by mlopatkin** 2021-08-11 08:54 UTC
Labels: in:application-plugin, in:wrapper, a:bug, to-triage
