### ISSUE TITLE
Add option to rerun failed Test

### ISSUE THREAD

**Issue by ugrave** [gradle/gradle#1283] opened 2017-02-01 09:43 UTC
The maven surefire plugin has an option to [rerun failing tests ](https://maven.apache.org/surefire/maven-surefire-plugin/examples/rerun-failing-tests.html). THis can be used for flaky tests.

The test task for gradle should also support such kind of option to retry failed test.

This can for example be  used for the Jenkins [Flaky Test Handler Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Flaky+Test+Handler+Plugin)

### Expected Behavior
The option should allow to set the the count of retries if a test is failing. For example the the value 1 mean retry the test once if failling. The output of a rerun can be put into the test result.

### Current Behavior
Currently a test can only be execute one and the test is marked as failling.

### Context
In my current context i have created some UI tests which somtimes failed and after a retry they works. Reason could be for example a connection timeout.

**Comment by bmuschko** [comment] 2017-02-01 18:20
Having to re-run a test because of flakiness usually exposes an actual issue. Either the source code under test doesn't handle corner cases properly or has a bug or the test method itself is not robust enough. I can definitely identify with the tendency for wanting to re-run a test in those cases as it is the easy way out.

I am not quite sure we want to build in the option in Gradle in general. You should be able to implement this functionality in your own code though depending on the test framework you are using. Some examples:

- JUnit: Use an existing [retry test rule](https://github.com/kevinmost/junit-retry-rule) or write your own.
- Spock: Use an existing [retry extension](https://github.com/anotherchrisberry/spock-retry) or write your own.
- TestNG: Write an implementation of `IRetryAnalyzer`.

**Comment by ugrave** [comment] 2017-02-02 07:09
Todo this with a JUnit rule was also one of my first ideas. The Problem with it, that i cannot the in the test result that i sucessfull test was sucessfull because of a retry. But for the current situation i will use this solution for my problem.

I know that retry a flaky test is not the best solution but i found this option in the maven surefire plugin.

**Comment by bmuschko** [comment] 2017-02-02 15:47
As part of your JUnit retry rule implementation you could additional logging or write those retries to a file to keep track of them. I am going to close the issue for now. We can reopen the discussion in case more people are interested in the feature.

**Closed by bmuschko** 2017-02-02 15:47 UTC
Labels: a:feature, from:contributor, in:core

**Comment by helderfalcao** [comment] 2017-09-14 16:31
bmuschko, I'm using gradle to run my UI tests(espresso), and they are unstable because of the environment, device, service. And we always have some problem. Retry cold be a better way to handle this unexpected behaviors. What you think?

**Comment by bemnet4u** [comment] 2017-09-19 00:41
+1 Having ability to do this in gradle is great cause we can benefit from the standard report generated by gradle...similar to how maven allows this.

**Comment by kjjain77** [comment] 2017-10-16 22:05
@ugrave I implemented the junit retry rule mentioned by bmuschko however curious if you went ahead with only rerunning tests on failure. If so how did you accomplish this?

**Comment by ugrave** [comment] 2017-10-18 07:58
It was only an idea to create this rule, but i never start to create the rule.

**Comment by helderfalcao** [comment] 2017-10-31 11:54
@bemnet4u , tha don't work for you: [rerun testes ](https://stackoverflow.com/questions/8295100/how-to-re-run-failed-junit-tests-immediately) ?

**Comment by sumitgpt** [comment] 2018-04-13 16:33
+1, would like to have this

**Comment by chia7712** [comment] 2018-05-28 02:28
+1. the Junit retry requires us to modify the test code to follow the retry style. If a flag can help us to re-run the flaky without any changes to source code, it can make our life easier.

**Comment by basil** [comment] 2018-09-27 17:00
+1

**Comment by eyal919** [comment] 2018-12-05 09:20
+1 - that will be a great to have gradle to handle the retries and the results.

**Comment by mikhail-g** [comment] 2019-01-17 16:08
+1

**Comment by AndreSand** [comment] 2019-01-24 02:51
+1

**Comment by prasanta-biswas** [comment] 2019-07-04 17:04
+100

**Comment by hemanth-dunzo** [comment] 2019-08-02 04:05
any updates on this?

**Comment by prasanta-biswas** [comment] 2019-08-02 05:25
No update yet on this.

**Comment by Kouroshb26** [comment] 2019-08-13 20:26
+1

I agree that passing flaky tests is bad, but I think it is essential that gradle helps rerun these failed tests to allow the developer to identify where their flaky tests are.

**Comment by Haibo-Zhou** [comment] 2023-07-11 06:51
The flaky instrumented test can fail the CI pipeline, which is why the retry is come to rescue. Imaging you have hundreds of instrumented test and it would takes several hours for CI job run, and 1 single failure failed the whole build.  Xcode has its build-in retry mechanism, which is handy to use. I don't know why gradle cannot have one.

**Comment by ajesh-n** [comment] 2024-07-17 18:45
+1
