### ISSUE TITLE
Better errors for common mistakes

### ISSUE THREAD

**Issue by jimshowalter** [gradle/gradle#17204] opened 2021-05-16 22:41 UTC
We got this error, which wasn't very helpful for debugging the problem:

A problem occurred evaluating script.
> No signature of method: testing_custom_eb4ntcou8yc1oo0lmpwmq9mcy.jacoco() is applicable for argument types: (testing_custom_eb4ntcou8yc1oo0lmpwmq9mcy$_run_closure9) values: [testing_custom_eb4ntcou8yc1oo0lmpwmq9mcy$_run_closure9@5949e48e]
  Possible solutions: copy(groovy.lang.Closure), copy(org.gradle.api.Action), each(groovy.lang.Closure)

This turned out to be caused by this:

end2EndTest { dirName = 'end2end-test' }

not being cased the same as this:

    end2endTest {
        systemProperties['user.dir'] = workingDir
    }

Outputting line numbers might help. Also, outputting the name of the method before it was turned into a closure might help.

**Comment by blindpirate** [comment] 2021-05-17 00:04
Thanks for the request, but I don't think your error message and the code snippet you put here are relevant, I guess the issue was somewhere else. Can you provide the code including `jacoco`? Otherwise we can't help. I'm closing this now, feel free to reopen if you have more details.

**Closed by blindpirate** 2021-05-17 00:04 UTC
Labels: a:feature, to-triage

**Comment by jimshowalter** [comment] 2021-05-17 00:45
This is using org.unbroken-dome.test-sets, but I think you're missing the point.

Two closures, referred to by transient GUIDs, are not very helpful for debugging Gradle configuration problems.

It's not specific to unbroken-dome. It's a generic issue with how Gradle reports errors when closures are involved. At some point there was some Gradle configuration source in the form of a text file, with line numbers, and Gradle/Groovy parsed it, and failed to match "end2EndTest" with "end2endTest', and instead of saying that was the problem, it gave the cryptic error message shown above.

I'm just suggesting Gradle would be more useful as a development tool if it gave better diagnostics.

**Comment by jimshowalter** [comment] 2021-05-17 00:46
I don't see anything that would allow me to reopen this.

**Comment by blindpirate** [comment] 2021-05-17 01:01
> At some point there was some Gradle configuration source in the form of a text file, with line numbers, and Gradle/Groovy parsed it, and failed to match "end2EndTest" with "end2endTest', and instead of saying that was the problem, it gave the cryptic error message shown above.

Thanks for clarifying. Actually the error was emitted by Groovy runtime, and it happened at runtime, not compilation time. I vaguely remember it has line numbers, but I might be wrong (or a difference in compiler options). can you give me a minimal reproducer or sample with `org.unbroken-dome.test-sets` to help the team members better understand this issue? From my experience, I didn't have much trouble in the past, because it was usually enough to debug by reading the stacktrace.
