### ISSUE TITLE
'projectPath' is a hijacked variable name in 3.3-rc-1

### ISSUE THREAD

**Issue by astellingwerf** [gradle/gradle#1072] opened 2016-12-27 10:41 UTC
We have a build script that (since Gradle 0.8) uses the Project Property via command line `-PprojectPath=...`. This used to work just fine till Gradle 3.2.1, but stopped working in 3.3 RC 1.

### Expected Behavior
When invoking Gradle with `-PprojectPath=...` and reading that value, I expect the value to be available and equal to the value provided in the CLI.

### Current Behavior
Instead, a value `:` is returned.

### Context
We are invoking external Gradle scripts, where we need to transfer some of the root build state to child processes.

### Steps to Reproduce
Check out https://github.com/astellingwerf/gradle-3.3-regression-projectPath
Execute the build via the wrapper with Gradle 3.3-rc-1
Observe build failure.
Change the wrapper version (to 3.2.1 or earlier) and generate the wrapper again.
Execute the build once more.
Observe success.

### Your Environment
`Linux 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by astellingwerf** [comment] 2016-12-27 11:29
Could it be that 924ce408394e8a68bced814625261a5e559c37cc broke this?

**Comment by lacasseio** [comment] 2016-12-27 16:55
Thanks @astellingwerf for opening this issue and it sure looks like https://github.com/gradle/gradle/commit/924ce408394e8a68bced814625261a5e559c37cc broke your use case.

@adammurdoch It looks like the change in https://github.com/gradle/gradle/commit/924ce408394e8a68bced814625261a5e559c37cc broke users that were using extended properties with the name `projectPath`. I understand it was a change to improve performance. Should we roll a fix to address this regression or it falls under possible collision with Gradle's internal implementation? As I understand it, a similar scenario could be happening if we add new properties to the internal interface. Should we consider deprecation cycle when introducing such change to allow the user to migrate and get notify about change in behavior?

**Comment by astellingwerf** [comment] 2016-12-28 16:14
I can (and already did) work around this issue by renaming the property. What I dislike is that you only notice the problem at runtime, when the value is used. Would it be possible to get some kind of warning when -P provides unreachable properties?

**Comment by lacasseio** [comment] 2016-12-28 16:50
You are right this is troublesome. I forgot to mention that you could keep the same name property name but access it through [`Project.property`](https://docs.gradle.org/current/javadoc/org/gradle/api/Project.html#property(java.lang.String)). In my opinion, although it is more verbose, this is the safer way to access a project property in order to avoid forward version clash with new properties.

It would be doable to do an additional check in order to know if property name clash with the provided project property. It's a bit tricky to add such feature as accessing the property through `Project.property` wouldn't result in a clash and would provide unnecessary logging. Still, a good place for this feature would be as part of [gradle-lint-plugin](https://github.com/nebula-plugins/gradle-lint-plugin) instead of part of the core distribution.

I see that dynamic property on `Project` is the root cause of this forward compatibility problem. Maybe this dynamic property access could be deprecated in favor of `Project.property`. This would avoid any confusion and unintentional breakage of the user.

**Comment by astellingwerf** [comment] 2016-12-31 12:28
Even with Project.property I can't get the CLI provided value. It also appears to invoke the newly introduced method.

**Comment by lacasseio** [comment] 2017-01-02 14:09
My bad, I wrongly assume the implementation of `Project.property`. You can get the property value through [`StartParameter.getProjectProperties()`](https://docs.gradle.org/current/javadoc/org/gradle/StartParameter.html#getProjectProperties()), however, if there is a possibility to set the value through the build script, there will be no way to look at both place (extended properties and project properties) without coding some kind of abstraction layer. At least with the StartParameter you can write something to avoid CLI facing change. I will discuss this internally to see how we will address this regression.

**Comment by lacasseio** [comment] 2017-01-03 14:54
The outcome of our internal discussion to keep the behavior as it is right now. The impact seems quite low and your build was already adapted to work around this issue. This will be a known limitation for Gradle 3.3 and will work on improving the usability of similar scenario by using `Project` setter for matching property if available or provide a warning if the `Project` property is read-only. This will be addressed as part of another issue. This isn't ideal, however [a workaround can be implemented to keep the same CLI interface](https://github.com/gradle/gradle/issues/1072#issuecomment-269977100).

This issue will be closed as rejected.

**Closed by lacasseio** 2017-01-03 14:54 UTC
Labels: affects-version:3.3, from:contributor, in:core, was:rejected
