### ISSUE TITLE
Multiple successive builds cause daemon problems

### ISSUE THREAD

**Issue by wilhe215** [gradle/gradle#1436] opened 2017-02-21 00:55 UTC
After upgrading to gradle 3.4, it was noticed that doing multiple successive 'gradle builds' caused our gradle daemons performance to drop considerably.  No code was changed in between the successive builds, they were only executed multiple times to verify how Gradle would perform within the context of our project.  We have a multi-project configuration with over 300 projects.  

The daemon appeared to have issues during the configuration stage of the build as it pegged the CPU with short patternistic dips to %75 CPU usage every few seconds.  

I'm not able to provide detailed build data or a build scan due to company policy.  

I could not upgrade to Gradle 3.4 and had to rollback to Gradle 3.3.

**Comment by oehme** [comment] 2017-02-21 15:27
Without additional data there is not much we can do to analyse this and help you.

A drop in CPU usage hints at garbage collection, so I suggest you try giving the build some more memory. If that does not help, you can use the [Gradle Profiler](https://github.com/gradle/gradle-profiler) to create JFR/JProfiler/YourKit snapshots and see where the time is lost.

**Comment by diacone** [comment] 2017-02-23 09:49
I can confirm that our build (164 projects) suffers from the same problems.

Our current configuration (Xmx1536m) is sufficient for the first build. But it will leave daemon with almost full old-gen space. Another build will cause heavy GC activity caused by allocation failures and eventually ends with GC limit exceeded or OOM.

Increasing memory to 3g did not solve the situation.

When incremental compilation is enabled, then the situation is much worse.

Overall it seems that memory requirements are now considerably bigger. At this point we're unable to even generate Idea project with --no-daemon and 600m heap.

I did not notice this with 3.4-rc1.

I'm running some more tests.

**Comment by oehme** [comment] 2017-02-23 10:15
Would you be able to send us a heap dump so we can analyze this problem?

**Comment by diacone** [comment] 2017-02-23 10:24
@oehme I suppose I can upload it somewhere. Do you have any FTP server or someting?

**Comment by oehme** [comment] 2017-02-23 11:42
We don't, unfortunately. Could you upload it to DropBox or a similar service?

**Comment by oehme** [comment] 2017-02-23 16:00
Thank you for the heap dump @diacone. I had a quick look and the largest amount of memory is taken up by 

- `org.gradle.api.tasks.util.internal.CachingPatternSpecFactory`
- class analysis cache
- JAR snapshots
- File Collection snapshots

The first one is surprising, could you check whether this was the same with 3.3?

> The biggest portion of memory is consumed by VisitableURLClassLoader instances.

I could not reproduce this statement, where did you see those?

**Comment by oehme** [comment] 2017-03-06 12:56
@wilhe215 is there any way you could provide us with a heap dump or profiler snapshot (shared privately of course) so we can further diagnose this problem?

**Comment by wilhe215** [comment] 2017-03-07 01:20
@oehme I'm not able to do that.  If you're willing to teach me to fish, I could look for things that you're interested in.  I will send you an email so we don't derail this thread.

**Comment by oehme** [comment] 2017-05-10 08:42
Are there any news here? Have you tried with Gradle 3.5 or the 4.0 nightlies? Without some more data points I'm afraid it's impossible for us to fix this problem. Ideally we'd have a heap dump from when the out of memory error occured (adding ` -XX:+HeapDumpOnOutOfMemoryError` to `org.gradle.jvmargs`).

**Comment by diacone** [comment] 2017-11-21 14:27
I think I have tracked that down to [shadow](https://plugins.gradle.org/plugin/com.github.johnrengelman.shadow) plugin. It somehow holds the CachingPatternSpecFactory objects alive so they survive GC. (with 1.2.3 version it's ~40% of heap and with 2.0.x it's ~15%)

Also one of our plugin use static field to cache things between projects and they took suprisingly large portion of memory as well. It almost looks like gradle loads multiple versions of the class and never unloads them so the old gen occupied by them was never freed. This is just a guess; I can't prove it as the gradle code is so abstract that I usually have no idea what's going on there :)

**Comment by oehme** [comment] 2017-11-21 15:17
Have you reported the problem to the shadow plugin? 

As for your own plugin being loaded multiple times: Is it in `buildSrc`? If so, are all `buildSrc` tasks up-to-date when you run a build?

**Comment by diacone** [comment] 2017-11-21 15:43
> Have you reported the problem to the shadow plugin?

No. Not yet.

> As for your own plugin being loaded multiple times: Is it in buildSrc? If so, are all buildSrc tasks up-to-date when you run a build?

No. It's a standalone plugin.

**Comment by oehme** [comment] 2017-11-21 15:49
Then it shouldn't be loaded multiple times. Is your static state holding on to anything from the previous build execution like `Project` or `Task` objects?

**Comment by wilhe215** [comment] 2017-11-21 16:19
Regarding the shadow plugin - we do not have that plugin installed in our implementation so this problem is independent of the shadow plugin.

**Comment by diacone** [comment] 2017-11-21 16:58
@oehme yes it does, the project reference. It was suspicious, so that's where I changed the implementation not to cache anything like that. Then the problem went away ...

**Comment by johnrengelman** [comment] 2017-11-21 19:56
`shadow` doesn't keep any static state in it's plugin. So unless ASM or something in the Gradle code that `shadow` is calling, is keeping that state, I don't know how it would be holding onto objects.

**Comment by oehme** [comment] 2018-05-09 13:58
Closing this since the issue was partly in user code and the other part seems to be caused by the shadow plugin. @johnrengelman if it turns out that the shadow plugin is triggering a bug in Gradle itself, please let me know and I'll reopen/investigate.

**Closed by oehme** 2018-05-09 13:58 UTC
Labels: a:bug, affects-version:3.4, from:contributor, in:core, in:daemon
