### ISSUE TITLE
7.5.1 gradle version - java.lang.StackOverflowError at org.gradle.execution.plan.FinalizerGroup$FinalizesMembers.getFilteredSuccessorsFor(FinalizerGroup.java:297)

### ISSUE THREAD

**Issue by vramasam** [gradle/gradle#21975] opened 2022-09-12 12:58 UTC
Hello Team,

In one of our projects, when we upgrade from 7.4.2 to 7.5.1 we are facing the below exception,
(Note: Its working fine with 7.4.x version, We also see a similar ticket but in different function that got closed for reference: https://github.com/gradle/gradle/issues/21542)

We are suspecting issue is because of this PR:  https://github.com/gradle/gradle/commit/eab1b22c90c35d2bc311f373374d2fd534f91f87 . 

Please help resolving this issue

* Exception details:
java.lang.StackOverflowError
	at org.gradle.execution.plan.FinalizerGroup$FinalizesMembers.getFilteredSuccessorsFor(FinalizerGroup.java:297)
	at org.gradle.execution.plan.FinalizerGroup$ElementSuccessors.successorsFor(FinalizerGroup.java:250)
	at org.gradle.execution.plan.FinalizerGroup.getSuccessorsFor(FinalizerGroup.java:103)
	at org.gradle.execution.plan.FinalizerGroup.checkSuccessorsCompleteFor(FinalizerGroup.java:170)
	at org.gradle.execution.plan.FinalizerGroup.checkSuccessorsCompleteFor(FinalizerGroup.java:191)
	at org.gradle.execution.plan.FinalizerGroup.isActivated(FinalizerGroup.java:229)
	at org.gradle.execution.plan.FinalizerGroup.checkPeersCompleteFor(FinalizerGroup.java:218)
	at org.gradle.execution.plan.FinalizerGroup.checkSuccessorsCompleteFor(FinalizerGroup.java:173)
	at org.gradle.execution.plan.FinalizerGroup.checkSuccessorsCompleteFor(FinalizerGroup.java:191)
	at org.gradle.execution.plan.FinalizerGroup.isActivated(FinalizerGroup.java:229)
	at org.gradle.execution.plan.FinalizerGroup.checkPeersCompleteFor(FinalizerGroup.java:218)
	at org.gradle.execution.plan.FinalizerGroup.checkSuccessorsCompleteFor(FinalizerGroup.java:173)
	at org.gradle.execution.plan.FinalizerGroup.checkSuccessorsCompleteFor(FinalizerGroup.java:191)
	at org.gradle.execution.plan.FinalizerGroup.isActivated(FinalizerGroup.java:229)
	at org.gradle.execution.plan.FinalizerGroup.checkPeersCompleteFor(FinalizerGroup.java:218)
	at org.gradle.execution.plan.FinalizerGroup.checkSuccessorsCompleteFor(FinalizerGroup.java:173)
	at org.gradle.execution.plan.FinalizerGroup.checkSuccessorsCompleteFor(FinalizerGroup.java:191)
	at org.gradle.execution.plan.FinalizerGroup.isActivated(FinalizerGroup.java:229)
	at org.gradle.execution.plan.FinalizerGroup.checkPeersCompleteFor(FinalizerGroup.java:218)
	at org.gradle.execution.plan.FinalizerGroup.checkSuccessorsCompleteFor(FinalizerGroup.java:173)
	at org.gradle.execution.plan.FinalizerGroup.checkSuccessorsCompleteFor(FinalizerGroup.java:191)
	at org.gradle.execution.plan.FinalizerGroup.isActivated(FinalizerGroup.java:229)
	at org.gradle.execution.plan.FinalizerGroup.checkPeersCompleteFor(FinalizerGroup.java:218)
	at org.gradle.execution.plan.FinalizerGroup.checkSuccessorsCompleteFor(FinalizerGroup.java:173)
	at org.gradle.execution.plan.FinalizerGroup.checkSuccessorsCompleteFor(FinalizerGroup.java:191)
	at org.gradle.execution.plan.FinalizerGroup.isActivated(FinalizerGroup.java:229)
	at org.gradle.execution.plan.FinalizerGroup.checkPeersCompleteFor(FinalizerGroup.java:218)
	at org.gradle.execution.plan.FinalizerGroup.checkSuccessorsCompleteFor(FinalizerGroup.java:173)
	at org.gradle.execution.plan.FinalizerGroup.checkSuccessorsCompleteFor(FinalizerGroup.java:191)
	at org.gradle.execution.plan.FinalizerGroup.isActivated(FinalizerGroup.java:229)

**Comment by TWiStErRob** [comment] 2022-09-13 21:45
Good to see I'm not alone, might be the same root cause: https://github.com/gradle/gradle/issues/21997

**Comment by jbartok** [comment] 2022-09-14 08:34
Could you pls. try with Gradle 7.6 nightly: https://gradle.org/release-nightly/

**Comment by vramasam** [comment] 2022-09-14 09:58
Hello @jbartok  Tried with the above nightly build, still the same issue exist.

**Comment by adammurdoch** [comment] 2022-09-17 10:51
This should be fixed now, via https://github.com/gradle/gradle/pull/22043

**Closed by adammurdoch** 2022-09-17 10:51 UTC
Labels: a:regression, in:scheduler
