### ISSUE TITLE
Environment variable changes are not propagated to the daemon

### ISSUE THREAD

**Issue by goafabric** [gradle/gradle#26453] opened 2023-09-21 06:46 UTC
### Current Behavior

With Gradle 8.3 / 8.4 and up to java20,
Jib and Gradle Exec work as expected, on Macos M1 (ARM)
Jib will pickup the credentials from a docker login

With java21 
- jib =>  produces "com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: Build image failed, perhaps you should make sure your credentials for 'registry-1.docker.io/goafabric/callee-service' are set up correctly"
- gradle exec => "A problem occurred starting process 'command 'docker''

The gradle exec can be fixed by supplying the path to docker => /usr/local/bin/docker

=> So both problems look to like some kind of problem retrieving information from the shell environment. ?

This only happens on Macos, on Github Actions Linux everything works.

To be sure I've also
=> Replaced the JRE from Azul to ORacle => Same Error
=> Using Maven with Java21 + Jib => This works

I've attached an example

[Archiv.zip](https://github.com/gradle/gradle/files/12681189/Archiv.zip)

### Expected Behavior

I would expect both exec and jib to work as with Java20

### Steps to Reproduce

Self contained example is attached.

The docker Problem can be simple reproduced with the Task "dockerRun" on MacOs M1.
But pretty much every exec without path should behave similiar.

The Jib Problem might be a little more complicated to reproduce.

### Gradle version

8.4 RC1 / 8.3

**Comment by jbartok** [comment] 2023-09-22 12:47
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/25574

Please add your use case and 👍 to that issue.

**Comment by octylFractal** [comment] 2023-10-04 16:21
This does not appear to actually be a duplicate of running with Java 21 -- and we could not reproduce the docker issue, it runs fine as-is. As for the jib issue, we obviously reproduce this because we do not have credentials for your repository. Unless you are injecting them into your environment, I do not see how Gradle could affect this -- to my knowledge docker stores login credentials outside of any shell environment.

I would recommend double-checking your setup, and if it's still failing, can you provide a [build scan](https://docs.gradle.org/current/userguide/inspect.html#what_is_a_build_scan) of this project when it is working (as you report, with Java 20), and when it is not working (as you report, with Java 21)?

**Comment by goafabric** [comment] 2023-10-05 12:22
@octylFractal 
I already tripple checked everything and it is definitely related to java21.
If you say that you could not reproduce the docker issue
=> This means you verified this on an apple silicon machine ? Because it only happens there, not on linux

As for jib, i pretty much assume that it will behave the same way,
with any other dockerhub repository ... and i would not know how to provide an example,
With a repo that is not mine

**Comment by goafabric** [comment] 2023-10-06 05:56
upgrade to final gradle 8.4 .. same error.
i will attach the build scans and also asked a friend of mine to verify on his apple silicon

build
https://scans.gradle.com/s/bojikprtmcmus

docker run
https://scans.gradle.com/s/jur7d4djnxrui

**Comment by octylFractal** [comment] 2023-10-10 20:51
Can you reproduce this if you run with `--no-daemon`? This might be unrelated to Java 21, but rather when you use anything that isn't Java 21 to run the build, it creates a fresh daemon which has a `PATH` environment variable that now includes docker, whereas the Java 21 daemon, for whatever reason, doesn't.

**Comment by goafabric** [comment] 2023-10-11 06:26
at least on the command line, yes i confirm that it seems to fix the issue,
also wenn putting 
org.gradle.daemon=false into gradle.settings in home
thx 4 that .. i already suspected some correlation with the deamon
so to be specific " it works on the command line with --no-daemon=false"

inside intellij thats however much harder to reproduce or to fix
it does not seem to care about the gradle.settings in home
and i was not able to apply a command line option .. which would be tedious anyways to configure it for every project

intellij aside, what does this mean ?
could it mean that an incomaptible gradle deamon is running, beeing picked up and this causes the error ?
and can it be solved ?

**Comment by octylFractal** [comment] 2023-10-11 16:11
>  could it mean that an incomaptible gradle deamon is running, beeing picked up and this causes the error ?

Yes.

>  and can it be solved ?

Yes, I will adjust this ticket to be about fixing how environment variables are handled by the daemon. We should either be changing them or starting a new daemon when they change.

**Comment by octylFractal** [comment] 2023-10-11 16:13
And this is actually a duplicate of a much older issue, #10483.

**Closed by octylFractal** 2023-10-11 16:13 UTC
Labels: a:bug, in:java-plugins
