### ISSUE TITLE
Incremental Groovy compilation

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#9617] opened 2019-06-04 07:08 UTC
Similarly to `JavaCompile`, `GroovyCompile` should only compile the classes which need to be recompiled.

**Comment by blindpirate** [comment] 2019-06-04 12:46
Unless AST transformation change is detected.

**Comment by ov7a** [comment] 2023-09-13 13:59
Closing this as a duplicate of 
* #6062

**Closed by ov7a** 2023-09-13 13:59 UTC
Labels: a:epic, @dev-productivity
