### ISSUE TITLE
`gradle init` may provide a way to specify the subprojects to create for multi-module build, or to provide one's own project template to init  

### ISSUE THREAD

**Issue by bushi-go** [gradle/gradle#27686] opened 2024-01-14 10:59 UTC
### Expected Behavior

`gradle init` may provide an option to pass a list of subprojects with type of projects to create at init for multi-module build

For instance, using --subprojects as the option name : 
```gradle init --type java-application \ 
                    --dsl kotlin \
                    --test-framework junit-jupiter \
                    --package my.project \
                    --project-name my-project  \
                    --java-version 17 \
                    --subprojects application/api:java-application domain/domain-core:java-library infrastructure:java-library
```

Each member of the subprojects list string would be then split and generated according to its type

In the example above, the following layout would be generated (content of folders omitted for brevity)

```
my.project/
├─gradle/
│  ├─wrapper/
│  ├─libs.versions.toml
├─ application/
│  ├─ api/
│  │  ├─ src/
│  │  │  ├─ main/
│  │  │  ├─ test/
│  │  ├─ build.gradle.kts
├─ domain/
│  ├─ domain-core/
│  │  ├─ src/
│  │  │  ├─ main/
│  │  │  ├─ test/
│  │  ├─ build.gradle.kts
├─ infrastructure/
│  │  ├─ src/
│  │  │  ├─ main/
│  │  │  ├─ test/
│  │  ├─ build.gradle.kts
├─ build-logic/
│  │  ├─ src/
│  │  │  ├─ main/
│  │  │  ├─ test/
│  │  ├─ build.gradle.kts
│  │  ├─ settings.gradle.kts
├─ build.gradle.kts
├─ settings.gradle.kts
├─ .gitignore
├─ gradle.properties
├─ gradlew
├─ gradlew.bat
├─ .gitattributes
```

This would enhance a bit the init plugin , as there is to my knowledge; no convenient way in gradle to make such initialization easily ; as of right know i tend to do it by hand, which is a bit tedious.

The nec plus ultra would be to be able to provide one's own templates to the init plugin instead of the samples currently in use; which would make one able to init projects having the same set of dependencies/task/etc a breeze

As far as i have seen in the code, it looks like a fair bit of work to be able to achieve one or the other.

I would be quite motivated and ready to contribute, but i might need some guidance about which way to tackle the beast ;p

That is, if the feature is deemed acceptable by the team, of course <3

### Current Behavior (optional)

As of now the init of a multi module project using the following command : 
```
gradle init --type java-application \ 
                    --dsl kotlin \
                    --test-framework junit-jupiter \
                    --package my.project \
                    --project-name my-project  \
                    --java-version 17 \
                    --split-project
```
 always produce the same layout

```
my.project/
├─ app/
│  ├─ src/
│  ├─ build.gradle.kts
├─ build-logic/
│  │  ├─ src/
│  ├─ build.gradle.kts
│  ├─ settings.gradle.kts
├─gradle/
│  ├─wrapper/
│  ├─libs.versions.toml
├─ list/
│  ├─ src/
│  ├─ build.gradle.kts
├─ utilities
│  ├─ src/
│  ├─ build.gradle.kts
├─ .gitattributes
├─ .gitignore
├─ gradle.properties
├─ gradlew
├─ gradlew.bat
├─ settings.gradle.kts
```

The revamp of the inited project to align with the target project layout requires a bit of work ; in the case of projects in which such operations are frequents (like microservices architectures, where one may have to generate a new project every quarter or so) it can quickly become cumbersome

### Context

I have commonly met the case of having an entreprise specific layout to replicate accross multiple, say, microservices.

As of now i have often had to produce ad-hoc, cumbersome solutions based on maven archetypes, or exotic gradle plugins, or other bash-ish scripts and the like to be able to reproduce the project layout in a somewhat coherent fashion.

The ability to specify the subprojects would already go a long way ; one can always work around replacating other bits and pieces (like common build logic and the like, or ci configuration files)

I have tried to give init script a go, but i did not find a convenient way to request a user for its input (for the name of the submodules for example)

If you have a better way to do this that would not involve modifying the init plugin, i'd be happy to give it a go ; although i feel like this would improve the usability of the init plugin by making it more versatile :)

**Comment by cobexer** [comment] 2024-01-18 13:46
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #1686

Please add your use case and 👍 to that issue.

**Closed by cobexer** 2024-01-18 13:46 UTC
Labels: a:feature, to-triage
