### ISSUE TITLE
com.gradle.plugin-publish 1.0.0/1.1.0 puts gradleApi() into shadowed MANIFEST.MF

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#23928] opened 2023-02-16 14:06 UTC
When applying `com.gradle.plugin-publish` and `com.github.johnrengelman.shadow` together, the manifest in `build\libs\fat.jar\META-INF\MANIFEST.MF` will contain the following line:
```
Class-Path: gradle-api-8.0.jar groovy-3.0.13.jar groovy-ant-3.0.13.jar g
 roovy-astbuilder-3.0.13.jar groovy-console-3.0.13.jar groovy-datetime-3
 .0.13.jar groovy-dateutil-3.0.13.jar groovy-groovydoc-3.0.13.jar groovy
 -json-3.0.13.jar groovy-nio-3.0.13.jar groovy-sql-3.0.13.jar groovy-tem
 plates-3.0.13.jar groovy-test-3.0.13.jar groovy-xml-3.0.13.jar javapars
 er-core-3.17.0.jar kotlin-stdlib-1.8.10.jar kotlin-stdlib-common-1.8.10
 .jar kotlin-reflect-1.8.10.jar kotlin-stdlib-jdk7-1.8.10.jar kotlin-std
 lib-jdk8-1.8.10.jar gradle-installation-beacon-8.0.jar
```
which is exactly `gradleApi()`.

### Affected versions
This did not happen before 1.0.0 started interacting with the shadow plugin and therefore anyone updating their plugins could change their manifest and in tandem their runtime behavior. This reproduces with 1.0.0 and 1.1.0, but with 0.21.0 everything is fine; this is why I think it's a regression.

### Steps to Reproduce 
1. Clone https://github.com/TWiStErRob/repros/tree/master/gradle/publishPlugin-manifestClassPath-gradleApi
2. `gradlew shadowJar`
3. Observe contents of `build/libs/publishPlugin-manifestClassPath-gradleApi.jar/META-INF/MANIFEST.MF`

### Current Behavior
The line is in the manifest.

### Expected Behavior
The line mentioned above is not in the manifest.

### Context
I'm working on updating https://github.com/gradle-nexus/publish-plugin to Gradle 8 and latest `plugin-publish` plugin, and while comparing the old and the new published JARs I noticed this unintended change.

### Implementation details
`com.gradle.publish.PublishTaskShadowAction.manipulateDependencies()` forces `shadow(gradlewApi())` dependency and then `com.github.jengelman.gradle.plugins.shadow.ShadowJavaPlugin#configureShadowTask` explicitly excludes it.

### Workaround
Workaround exists, the problem is that there's no failure/warning or anything telling users that their manifests contain extra stuff, and also everyone using these two plugins together should add this workaround to their builds.
```gradle
afterEvaluate {
	configurations.named(com.github.jengelman.gradle.plugins.shadow.ShadowBasePlugin.CONFIGURATION_NAME).configure {
		// Workaround https://github.com/gradle/gradle/issues/23928
		// Undo part of com.gradle.publish.PublishTaskShadowAction.manipulateDependencies()
		//this.dependencies.remove(project.dependencies.gradleApi())
	}
}
```

### Your Environment
Build scan URL: https://gradle.com/s/goidnye4cnjis

**Comment by jbartok** [comment] 2023-02-17 09:38
Thank you for pointing this out. We looked briefly at it, to see if it's a regression in Gradle, but it's not. The behavior is the same with past Gradle versions too. So this is a problem to be fixed in the Plugin Publish plugin. We will schedule it accordingly.

**Comment by TWiStErRob** [comment] 2023-02-17 09:57
Yes, I meant it's a regression between `com.gradle.plugin-publish:0.21.0` and `com.gradle.plugin-publish:1.0.0`.

cc @johnrengelman for visibility.

**Comment by vlsi** [comment] 2023-02-17 14:03
One of the workarounds is

```kotlin
tasks.shadowJar {
    manifest {
        attributes["Implementation-Version"] = project.version
    }
}
```

**Comment by TWiStErRob** [comment] 2023-02-17 15:13
@vlsi that result in this on the repo in OP:
```
Manifest-Version: 1.0
Implementation-Version: unspecified
Class-Path: gradle-api-8.0.jar groovy-3.0.13.jar groovy-ant-3.0.13.jar g
 roovy-astbuilder-3.0.13.jar groovy-console-3.0.13.jar groovy-datetime-3
 .0.13.jar groovy-dateutil-3.0.13.jar groovy-groovydoc-3.0.13.jar groovy
 -json-3.0.13.jar groovy-nio-3.0.13.jar groovy-sql-3.0.13.jar groovy-tem
 plates-3.0.13.jar groovy-test-3.0.13.jar groovy-xml-3.0.13.jar javapars
 er-core-3.17.0.jar kotlin-stdlib-1.8.10.jar kotlin-stdlib-common-1.8.10
 .jar kotlin-reflect-1.8.10.jar kotlin-stdlib-jdk7-1.8.10.jar kotlin-std
 lib-jdk8-1.8.10.jar gradle-installation-beacon-8.0.jar
```
try to experiment with that, it's 7 lines of code only to repro this in a `build.gradle.kts`.

**Comment by vlsi** [comment] 2023-02-17 15:20
Well, it does not fix the reproducer indeed.
However, it looks like the manifest fixed gradle-nexus/publish-plugin for me

**Comment by TWiStErRob** [comment] 2023-02-17 15:25
Let's continue that on the thread in the PR, and report back when we figured it out.

**Closed** 2023-04-06 12:40 UTC
Labels: in:plugin-development, a:regression

**Comment by TWiStErRob** [comment] 2023-04-06 13:21
@ljacomet what does this resolution mean? Is there a change somewhere else that makes this work from now on?

**Comment by ljacomet** [comment] 2023-04-06 13:35
For once Grade auto-closing issues worked a bit too well 😉 

We will be releasing version `1.2.0` of the `plugin-publish` plugin later today. It will contain the fix for this problem.

**Comment by jbartok** [comment] 2023-04-07 05:44
@TWiStErRob I can confirm that [version 1.2.0 of the Plugin Publish plugin](https://plugins.grdev.net/plugin/com.gradle.plugin-publish) (soon to be deployed to the production portal too), fixes the problem.

**Comment by jbartok** [comment] 2023-04-07 05:52
Have filed [an issue](https://github.com/johnrengelman/shadow/issues/852) for a root cause fix in the Shadow plugin.

**Comment by ljacomet** [comment] 2023-04-07 14:33
[Plugin](https://plugins.gradle.org/plugin/com.gradle.plugin-publish) is released

**Comment by TWiStErRob** [comment] 2023-04-07 14:45
Confirmed with discovery origin. Output is clean after removing workaround.

**Comment by TWiStErRob** [comment] 2023-04-07 14:46
Thank you very much for the quick fix and the verbose comms here!
