### ISSUE TITLE
Outdated Isolated Projects documentation page

### ISSUE THREAD

**Issue by oleg-nenashev** [gradle/gradle#29432] opened 2024-06-06 05:42 UTC
### Issue type

Wrong or misleading information

### Problem description

The 8.8 release notes announce major changes to the status of Isolated Projects, but those changes do not seem to be reflected on https://docs.gradle.org/current/userguide/isolated_projects.html or other documentation pages. The doumentation pages still starts from _[Status as of Gradle 8.5](https://docs.gradle.org/current/userguide/isolated_projects.html#status_as_of_gradle_8_5)_

### Page with the problem

https://docs.gradle.org/current/userguide/isolated_projects.html

**Comment by ljacomet** [comment] 2024-06-06 12:33
This is a valid documentation issue.

***

For users: This feature is under active development, and the early adopter documentation is not updated for each release. At the time of writing, its content is focused on Gradle 8.5, for example.

**Comment by mlopatkin** [comment] 2024-06-11 12:41
This issue will be closed as a duplicate of

* #25328

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

**Closed by mlopatkin** 2024-06-11 12:41 UTC
Labels: a:documentation, in:isolated-projects
