### ISSUE TITLE
Deprecate DomainObjectCollection.withType(Class, Action) and the corresponding inline fun

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#21241] opened 2022-07-12 15:30 UTC
### Expected Behavior

Users should understand that the following call would eagerly realize the tasks:

```kotlin
tasks.withType<MyTask> {
   ...
}
```

It is common wisdom that `.configureEach` should be used here:

```kotlin
tasks.withType<MyTask>().configureEach {
    myProperty.set(myvalue)
}
```

Note: I do not suggest removing the method as it would break too many builds.
I suggest just deprecating it so the users know they should refrain from using the method.

### Current Behavior

`withType<...> { . }` works and produces no warning, however, it realizes tasks eagerly without users understanding that.

### Context

https://t.me/gradle/19352

Here's a suggestion to add `configureEach(Class, Action)` alternative: https://github.com/gradle/gradle/issues/9832#issuecomment-587584087
Here's a request to IDEA for an inspection for cases like `tasks.all`, etc: https://youtrack.jetbrains.com/issue/IDEA-297893/Inspection-for-tasksall-taskswithType-prefer-lazy-task-configuration

**Comment by donat** [comment] 2022-07-13 14:42
Duplicate of #15281.

**Closed by donat** 2022-07-13 14:42 UTC
Labels: a:feature, to-triage

**Comment by donat** [comment] 2022-07-13 14:43
The on-boarding label marks issues that are easy to tackle and suited for onboarding Gradle engineers and contributors. This issue is a bit more complex than that :)
