### ISSUE TITLE
Grails Views - Cannot choose between the following variants of project: productionRuntimeClasspath, runtimeElements

### ISSUE THREAD

**Issue by puneetbehl** [gradle/gradle#15721] opened 2021-01-08 15:53 UTC
We started seeing the following error in Grails Views project after we update Spring, Spring Boot, and Apache Groovy. I do not have expertise on the problem to understand if this is related to Gradle or some other bug in the project. 

```
Could not determine the dependencies of task ':views-docs:apidocs'.
> Could not resolve all task dependencies for configuration ':views-docs:documentation'.
   > Could not resolve project :views-json.
     Required by:
         project :views-docs
         project :views-docs > project :views-json-testing-support
      > Cannot choose between the following variants of project :views-json:
          - productionRuntimeClasspath
          - runtimeElements
        All of them match the consumer attributes:
          - Variant 'productionRuntimeClasspath' capability org.grails.plugins:views-json:2.1.0.BUILD-SNAPSHOT:
              - Unmatched attributes:
                  - Provides org.gradle.dependency.bundling 'external' but the consumer didn't ask for it
                  - Provides org.gradle.libraryelements 'jar' but the consumer didn't ask for it
                  - Provides org.gradle.usage 'java-runtime' but the consumer didn't ask for it
          - Variant 'runtimeElements' capability org.grails.plugins:views-json:2.1.0.BUILD-SNAPSHOT:
              - Unmatched attributes:
                  - Provides org.gradle.category 'library' but the consumer didn't ask for it
                  - Provides org.gradle.dependency.bundling 'external' but the consumer didn't ask for it
                  - Provides org.gradle.jvm.version '8' but the consumer didn't ask for it
                  - Provides org.gradle.libraryelements 'jar' but the consumer didn't ask for it
                  - Provides org.gradle.usage 'java-runtime' but the consumer didn't ask for it

```

### Expected Behavior
The `./gradlew :views-docs:apidocs` task should work as earlier. 

### Current Behavior
The `./gradlew :views-docs:apidocs` task is throwing error. 

### Context

This problem started happening after we updated to Grails 4.1.0.M3 which update to the latest Spring 5.3.2, SpringBoot 2.4.1, and Apache Groovy 3.0.7. 

Here is the complete build URL https://github.com/grails/grails-views/runs/1663913493?check_suite_focus=true

### Steps to Reproduce 
* Clone the repository https://github.com/grails/grails-views
* Execute `./gradlew :views-docs:apidocs` 

### Your Environment
* Gradle 6.5
* masOS Big Sur Version 11.1
* openjdk version "1.8.0_252"

Build scan URL: https://scans.gradle.com/s/6fcjgw3kx4v4y

**Comment by melix** [comment] 2021-01-13 07:49
There's a configuration, `productionRuntimeClasspath`, which must be added by a plugin or your build script, and is defined as consumable and also defines attributes. Therefore, it is considered as a candidate for cross-project publications (dependencies). Because it's a runtime classpath, it shouldn't be consumable by other projects. I'm not sure what puts attributes on it, but this looks like the root cause.

**Comment by ljacomet** [comment] 2021-03-23 13:41
I believe that `productionRuntimeClasspath` should be changed in Spring Boot so that is is _resolvable_ but not _consumable_.

The two options you shared are valid to fix the issue. The first one would be the more idiomatic while the other is considered legacy.

I am closing this as there is nothing to be done inside Gradle.

**Closed by ljacomet** 2021-03-23 13:41 UTC
Labels: a:regression, from:contributor

**Comment by wilkinsona** [comment] 2021-03-26 11:32
I've opened https://github.com/spring-projects/spring-boot/issues/25798.
