### ISSUE TITLE
Gradle caches keyserver information even when it is disabled

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#19663] opened 2022-01-21 21:47 UTC
Gradle caches keyserver information even when it is disabled

### Expected Behavior
When the user disables remote keyservers, gradle should invalidate signature verification data and rerun all of it.

### Current Behavior
Gradle caches keychains fetched from previous builds even though keyservers is disabled.

### Context
As part of enabling Gradle signature verification for our build, we ran into this incorrect behavior.

### Steps to Reproduce 

0. Checkout https://github.com/liutikas/gradle-disabled-keyservers
1. `./gradlew jar` <- build succeeds as expected
2. Modify `gradle/verification-metadata.xml` to uncomment `<key-servers enabled="false"/>`
3. `./gradlew jar`

## Expected

Build fails because we are missing keychains that are only available online

## Actual

Builds succeeds

### Your Environment
Linux
Gradle 7.4-rc-1 (same is true for 7.3)

**Comment by liutikas** [comment] 2022-01-21 21:51
Note, this makes the initial boostrapping step https://docs.gradle.org/current/userguide/dependency_verification.html#sec:local-keyring-only really difficult.

The only workaround I found so far is:
```
./gradlew --stop
GRADLE_USER_HOME=/tmp/uniquedir ./gradlew clean jar
```

**Comment by asodja** [comment] 2022-01-24 15:53
So if I understand correctly the expected behavior is, that `gradle` reads keychains (`.keys`) only from the `<project>/gradle/*.keys` right?

**Comment by liutikas** [comment] 2022-01-24 16:23
Documentation for this feature states `To avoid this, Gradle offers the ability to disallow use of key servers altogether: only the local keyring file would be used, and if a key is missing from this file, the build will fail.` This game me the impression that setting key-servers to be false would mean that only gradle/*.keys is read, so yes that would be the expected behavior.

**Comment by asodja** [comment] 2022-01-25 15:04
It looks like removing `.gradle` folder in the project is enough to make this fail. Issue is, that for caching we don't take into account `useKeyservers` flag as assumed. I will provide a fix for it.

Is https://github.com/gradle/gradle/issues/18440 the same issue or is there any specific difference there?

**Comment by liutikas** [comment] 2022-01-25 16:52
That one is a duplicate, yes. Nothing different.

**Comment by asodja** [comment] 2022-01-27 11:13
Fixed with: https://github.com/gradle/gradle/pull/19703.

Note that when using configuration cache this might still be an issue since dependency verification is not fully compatible with configuration cache. I opened https://github.com/gradle/gradle/issues/19716.

**Closed by asodja** 2022-01-27 11:13 UTC
Labels: a:bug, in:dependency-verification
