### ISSUE TITLE
java.lang.IndexOutOfBoundsException at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.onOrderingCycle

### ISSUE THREAD

**Issue by stmlange** [gradle/gradle#4156] opened 2018-01-25 18:45 UTC
Hello,
I have a somewhat complex gradle build project with multiple custom plugins and currently the gradle build keeps reliable crashing with an ``java.lang.IndexOutOfBoundsException at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.onOrderingCycle`` when invoking ``./gradlew clean build``.
I'm not quite sure on how to debug or trace this issue down so I thought I raise an issue to get more insight to be potentially be able to provide a minimal working example. 

### Expected Behavior

No crash.

### Current Behavior

```
./gradlew clean build

FAILURE: Build failed with an exception.

* What went wrong:
Index: 0, Size: 0

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.onOrderingCycle(DefaultTaskExecutionPlan.java:483)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.determineExecutionPlan(DefaultTaskExecutionPlan.java:323)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.ensurePopulated(DefaultTaskGraphExecuter.java:217)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.populate(DefaultTaskGraphExecuter.java:119)
        at org.gradle.initialization.DefaultGradleLauncher$CalculateTaskGraph.run(DefaultGradleLauncher.java:275)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
```

### Context

This looks quite similar to what has been reported for older gradle versions (https://issues.gradle.org/browse/GRADLE-3575, https://issues.gradle.org/browse/GRADLE-2957, https://github.com/gradle/gradle/issues/2293, https://github.com/gradle/gradle/pull/710) but I'm not quite sure what is causing this.

### Steps to Reproduce (for bugs)

Not sure, please advise how to troubleshoot this :-)

### Your Environment

```
------------------------------------------------------------
Gradle 4.2
------------------------------------------------------------

Build time:   2017-09-20 14:48:23 UTC
Revision:     5ba503cc17748671c83ce35d7da1cffd6e24dfbd
```

**Comment by oehme** [comment] 2018-01-26 08:40
Duplicate of #2293

**Closed by oehme** 2018-01-26 08:40 UTC
