### ISSUE TITLE
Gradle has Issues with `exFAT`

### ISSUE THREAD

**Issue by dschiller** [gradle/gradle#20704] opened 2022-05-09 14:33 UTC
### Expected Behavior
Gradle should work

### Current Behavior
Gradle doesn't work

### Context
See this ticket at flutter which leads to this ticket here: https://github.com/flutter/flutter/issues/103311

### Steps to Reproduce 
- Download Flutter SDK
- Run Flutter doctor
- Download and install Android Studio
- Install Android commandline tools
- Install Pixel 2 API 30 Emulator
- Run Out of the Box Flutter App

### Your Environment
Windows 10 / exFAT drive

**Comment by wolfs** [comment] 2022-05-09 15:15
Thank you for your interest in Gradle!

This issue is a duplicate of https://github.com/gradle/gradle/issues/17551 and will be closed as such.

The fix is in Gradle 6.9.1 or 7.2.

**Closed by wolfs** 2022-05-09 15:15 UTC
Labels: a:bug, to-triage

**Comment by dschiller** [comment] 2022-05-09 15:47
Thank you Stefan!
