### ISSUE TITLE
build init doesn't respect --no-incubating

### ISSUE THREAD

**Issue by jgrey4296** [gradle/gradle#23918] opened 2023-02-16 05:32 UTC
Running `gradle init --type basic --dsl kotlin --project-name testProject` insists on user input asking about incubating apis. Passing `--incubating` can silence it, but `--no-incubating` errors.

### Expected Behavior
I expected Gradle to either accept `--no-incubating` as a cli option, 
or it not ask for user input when specifying all options.

The [documenation](https://docs.gradle.org/7.5.1/userguide/command_line_interface.html) says "Options that enable behavior have long-form options with inverses specified with --no-." This is not the case.

### Current Behavior
When *not* passing `--incubating`, Gradle waits for stdin to answer the incubating question.
When passing `--no-incubating`, Gradle Errors with:

```
FAILURE: Build failed with an exception.

* What went wrong:
Problem configuring task :init from command line.
> Unknown command-line option '--no-incubating'.
```

### Context
This behaviour means either I can't create a gradle project as a non-interactive task, or I'm forced to enable incubating features. 

### Steps to Reproduce 
Run variations of:
`gradle init --type basic --dsl kotlin --project-name testProject`
with `--incubating` and `--no-incubating` included, and as an external process.

### Your Environment
Mac OS  10.15.7, tested with Gradle 7.5.1, 7.6 and 8.0

**Comment by eskatos** [comment] 2023-02-23 10:11
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by FrauBoes** [comment] 2023-03-06 15:46
This will be fixed as part of https://github.com/gradle/gradle/issues/4311

**Closed by FrauBoes** 2023-03-06 15:46 UTC
Labels: in:build-init-plugin, a:bug, closed:duplicate
