### ISSUE TITLE
The distribution package cannot run normally under the window system(error info: The input line is too long.The syntax of the command is incorrect.)

### ISSUE THREAD

**Issue by zxuanhong** [gradle/gradle#30508] opened 2024-09-12 02:14 UTC
### Current Behavior

1. The distribution package cannot run normally under the window system. Error info:The input line is too long.The syntax of the command is incorrect.)
2. The input line is too long
<img width="1529" alt="image" src="https://github.com/user-attachments/assets/2fad7fb6-ad6d-48dc-8e0c-a459568d00c7">

### Expected Behavior

The distribution package can run normally in the window

### Context (optional)

1. The 'CLASSPATH' in the window script should not use a full lib path, but a fuzzy path, that is: 'CLASSPATH=% APPHOME%\lib\*'
4. Video

https://github.com/user-attachments/assets/50e49fdd-396e-4421-a944-04773f53a20f

5. this maven appassembler-maven-plugin script
<img width="653" alt="345685574-f7da4def-3937-488e-90c9-93437082a376" src="https://github.com/user-attachments/assets/8ba23a4a-14b7-4b07-83bf-03babc64f32c">

### Self-contained Reproducer Project

[minimal demo:https://github.com/zxuanhong/demo](https://github.com/zxuanhong/demo)

### Gradle version

8.10.1

### Your Environment (optional)

openjdk: 21
system: Windows 11 Pro

**Comment by ov7a** [comment] 2024-09-12 13:01
This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/1989

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

Please take a look at that issue for [workarounds](https://github.com/gradle/gradle/issues/1989#issuecomment-550192866).

**Closed by ov7a** 2024-09-12 13:01 UTC
Labels: a:bug, to-triage
