### ISSUE TITLE
Support incremental builds within buildSrc itself

### ISSUE THREAD

**Issue by ZakTaccardi** [gradle/gradle#2893] opened 2017-09-08 02:13 UTC
I have a field in my `buildSrc` folder. 

```
private static final String versionTail = "2";
```

### Expected Behavior
When bumping the `versionTail` to `"3"`, gradle should build this incrementally.
- it does not affect the public API of the `buildSrc` output, so gradle should be able to build this incrementally

### Current Behavior
Redeploying my android app after bumping the private static field (NOT INCREMENTAL):
```
BUILD SUCCESSFUL in 50s
242 actionable tasks: 239 executed, 3 up-to-date
```

When I do not make any changes in buildSrc and redeploy an already built application:

```
BUILD SUCCESSFUL in 2s
242 actionable tasks: 2 executed, 240 up-to-date
```

**Comment by blindpirate** [comment] 2017-09-08 02:21
Duplicate of #2767

**Comment by blindpirate** [comment] 2017-09-08 02:22
This is expected, because we don't analyze the source code, so we don't know that the constant didn't change. We only have finer grained detection for bytecode changes on the classpath.

Possible workarounds: 

- Make that constant private and expose a static method instead
- Put it in a class that changes less often

**Comment by big-guy** [comment] 2017-09-08 02:25
@blindpirate This is something else.

@ZakTaccardi I think I don't quite understand your example.  `versionTail` is a static field used by a plugin in `buildSrc`?  The build script uses the output of `buildSrc` as a runtime dependency, so even though the API did not change, the implementation did and that can invalidate task execution.

**Comment by blindpirate** [comment] 2017-09-08 02:27
Oops, my fault, reopened. Thanks @big-guy .

**Comment by ZakTaccardi** [comment] 2017-09-08 23:11
@big-guy no, not used by a plugin. for example, I have a method from a class in `buildSrc` that gives me a `versionName` (Required in Android projects). 

the version name varies based on the environment, which I have represented as an enum in the `buildSrc` folder. below is what I would call from my `build.gradle` script. 

```
// internally, this method utilizes the private versionTail field
android.productFlavors.qa.versionName =10 Environment.QA.getVersionName()
```
I can provide a better example next time I'm at my computer, too.

**Comment by oehme** [comment] 2017-09-11 17:17
Your build logic has a runtime dependency on the code in `buildSrc`, so every detail matters, not just the API. The only way to make that incremental would be to track every change to any class in buildSrc and do full runtime instrumentation of your build logic to see when those classes are used. This is prohibitively expensive, so to keep things simple we consider every task out of date if its classpath (which includes buildSrc) has changed.

**Closed by oehme** 2017-09-11 17:17 UTC
Labels: a:question, from:contributor
