### ISSUE TITLE
Signing plugin should have an option to prevent signing derived artifacts created by other plugins

### ISSUE THREAD

**Issue by niandy** [gradle/gradle#27605] opened 2024-01-07 10:22 UTC
### Expected Behavior

there should be an option to ignore derived artifacts. Probably by checking if they are `instanceof DerivedMavenArtifact`

### Current Behavior (optional)

When you're signing publication if it contains some derived artifacts that created by something else than SigningPlugin itself they will also be signed. That no always useful

### Context

signing {
    sign publishing.publications.findAll() as Publication[]
}

**Comment by vlsi** [comment] 2024-01-10 20:07
@niandy , could you clarify why do you want to ignore derived artifacts?

**Comment by cobexer** [comment] 2024-01-11 13:42
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #26760

Please add your use case and 👍 to that issue.
***
We assume by derived artifact you mean an artifact produced by doing something with the publication content, then this is a valid feature request however it's a duplicate of the issue linked above.

**Closed by cobexer** 2024-01-11 13:42 UTC
Labels: a:feature, to-triage
