### ISSUE TITLE
Allow users to run included build tasks from the command-line

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#14046] opened 2020-08-07 02:01 UTC
Make it possible to run tasks from buildSrc from the command-line in the same way as included builds today

**Comment by jjohannes** [comment] 2020-09-21 15:30
Closing as duplicate of #2533

**Comment by jjohannes** [comment] 2020-09-21 15:33
Related to #2533 (run included build tasks directly from command line). We could fix both things together if that makes sense.

**Closed** 2020-10-13 15:02 UTC
Labels: @idiomatic
