### ISSUE TITLE
Gradle 6.4-rc-1 breaks bootRun

### ISSUE THREAD

**Issue by pkubowicz** [gradle/gradle#12834] opened 2020-04-17 12:07 UTC
### Expected Behavior
Running `gradle bootRun` starts Spring boot application.

### Current Behavior
```
Execution failed for task ':bootRun'.
> No main class specified and classpath is not an executable jar.
```

### Steps to Reproduce 
Take any Gradle project using Spring Boot.

src/main/java/com/example/Application.java: 
```
package com.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
```

build.gradle:
```
plugins {
    id 'java'
    id 'org.springframework.boot' version '2.2.6.RELEASE'
}

repositories {
    jcenter()
}

dependencies {
    implementation platform('org.springframework.boot:spring-boot-dependencies:2.2.6.RELEASE')

    implementation 'org.springframework.boot:spring-boot-starter-web'
}
```

### Your Environment
```
------------------------------------------------------------
Gradle 6.4-rc-1
------------------------------------------------------------

Build time:   2020-04-15 20:28:39 UTC
Revision:     4162fd0e34887a8c600495239d421cecaa5f17ff

Kotlin:       1.3.71
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.6 (Ubuntu 11.0.6+10-post-Ubuntu-1ubuntu119.10.1)
OS:           Linux 5.3.0-46-generic amd64
```

**Comment by jjohannes** [comment] 2020-04-17 12:17
Thanks for the detailed report @pkubowicz. This is the root cause of the issue: #12833

**Comment by jjohannes** [comment] 2020-04-17 14:41
Fixed by https://github.com/gradle/gradle/pull/12836

**Closed by jjohannes** 2020-04-17 14:41 UTC
Labels: @jvm, a:regression, from:contributor, in:jvm-ecosystem
