### ISSUE TITLE
project.tasks.withType(MyCustomTask.class) does not find task defined with type MyCustomTask even though there exists at least one task defined of such type

### ISSUE THREAD

**Issue by dknopp** [gradle/gradle#8568] opened 2019-02-20 21:08 UTC
project.tasks.withType(MyCustomTask.class) does not find task defined with type MyCustomTask even though there exists at least one task defined of such type. 

I've executed project.tasks.withType(MyCustomTask.class) in the project.afterEvaluate closure and within a doFirst and doLast action on a DefaultTask.

In all cases my tasks of type MyCustomTask where not returned.

Currently on gradle version 4.10.3, attempted to search issues for known issues in this area against gradle 4.10.3 and didn't see any, hopefully not a duplicate.

### Expected Behavior
I expect in all instances: project.afterEvaluate, task.doFirst and task.doLast that my tasks of type MyCustomTask would be found by project.tasks.withType(MyCustomTask.class)

### Current Behavior
project.tasks.withType(MyCustomTask.class) does not return my defined tasks of that type

For troubleshooting I decided to log the name of the class for each Task returned by project.task. For each task I got a _Decorated type instead of the actual type i.e.

org.gradle.api.DefaultTask_Decorated instead of org.gradle.api.DefaultTask
com.wouldnt.you.like.to.know.MyCustomTask_Decorated instead of com.wouldnt.you.like.to.know.MyCustomTask

### Context
Wanting to find all tasks in a project of a certain type, would like to use project.tasks.withType

I want to process the output(s) of those tasks and publish some results.

### Steps to Reproduce (for bugs)
Not available

### Your Environment
Java 1.8 - 1.8.0_111_x64
Linux (Redhat 7)
Gradle 4.10.3

**Comment by lacasseio** [comment] 2019-02-20 22:44
The decoration `*_Decorated` types are normal as they are instrumented by Gradle for compatibility and such. What isn't normal is not finding your custom type. Two things you could try:
1) Could you show how `MyCustomTask` task is created?
2) Try with latest Gradle (5.2.1 at the time of this comment)

**Comment by dknopp** [comment] 2019-02-21 14:44
Thanks I was wondering if *_Decorated was normal, makes sense.

We're creating MyCustomTask inside a custom plugin, it simply extends the PMD Task without adding too much, the plugin code that's defining the task looks like this:

@Override public void apply(final Project project) {
    project.afterEvaluate(new Action<Project>() {
        @Override public void execute(Project project) {
                if (project.getTasks().withType(MyCustomTask.class).isEmpty()) {		
			CagPmd myPmdTask = project.getTasks().create("myPmdTask", MyCustomTask.class);
			myPmdTask.setDescription("MyCustomTask");
			myPmdTask.setGroup("MyCustomTask");
			
			myPmdTask.setRuleSets(new ArrayList<String>());
			myPmdTask.setIncludes(Arrays.asList("**/*.java", "**/*.xml"));
			myPmdTask.source("src/main/java");
			myPmdTask.source("src/main/resources");
			myPmdTask.setIgnoreFailures(true);		
		}
        }
    }
}

In the build I'm looking for any task of type MyCustomTask expecting to at least find the one named myPmdTask if no others are defined. While I don't find a MyCustomTask I can find a MyCustomTask_Decorated.

Our build has a number of build files but a single project, we're currently looking into that causing issues. Right now the plugin above isn't applied in the top level file, we're going to try and move it to the top level file and see if there's a difference.

**Comment by lacasseio** [comment] 2019-02-21 15:44
I suspect an ordering issue or the plugin isn't applied to the project you expect the task to be create or vice-versa. Given the following build script:
```
class MyCustomTask extends Pmd {

}


class CustomPlugin implements Plugin<Project> {
    @Override
    public void apply(final Project project) {
        project.afterEvaluate(new Action<Project>() {
            @Override
            public void execute(Project proj) {
                if (project.getTasks().withType(MyCustomTask.class).isEmpty()) {
    			    def myPmdTask = project.getTasks().create("myPmdTask", MyCustomTask.class);
    			    myPmdTask.setDescription("MyCustomTask");
    			    myPmdTask.setGroup("MyCustomTask");
    			    
    			    myPmdTask.setRuleSets(new ArrayList<String>());
    			    myPmdTask.setIncludes(Arrays.asList("**/*.java", "**/*.xml"));
    			    myPmdTask.source("src/main/java");
    			    myPmdTask.source("src/main/resources");
    			    myPmdTask.setIgnoreFailures(true);		
    		    }
            }
        });
    }
}

project.afterEvaluate {
    println "[afterEvaluate] Before plugin applied: " + tasks.withType(MyCustomTask).size()
}

apply plugin: CustomPlugin

project.afterEvaluate {
    println "[afterEvaluate] After plugin applied: " + tasks.withType(MyCustomTask).size()
}

tasks.create("verify") {
    doFirst {
        println "[doFirst] During task execution: " + tasks.withType(MyCustomTask).size()
    }
    doLast {
        println "[doLast] During task execution: " + tasks.withType(MyCustomTask).size()
    }
}
```

Executing Gradle 4.10.3 (`./gradlew tasks verify`) the output is as follow:
```
> Configure project :
[afterEvaluate] Before plugin applied: 0
[afterEvaluate] After plugin applied: 1

> Task :tasks

------------------------------------------------------------
All tasks runnable from root project
------------------------------------------------------------

Build Setup tasks
-----------------
init - Initializes a new Gradle build.
wrapper - Generates Gradle wrapper files.

Help tasks
----------
buildEnvironment - Displays all buildscript dependencies declared in root project 'issue-8568'.
components - Displays the components produced by root project 'issue-8568'. [incubating]
dependencies - Displays all dependencies declared in root project 'issue-8568'.
dependencyInsight - Displays the insight into a specific dependency in root project 'issue-8568'.
dependentComponents - Displays the dependent components of components in root project 'issue-8568'. [incubating]
help - Displays a help message.
model - Displays the configuration model of root project 'issue-8568'. [incubating]
projects - Displays the sub-projects of root project 'issue-8568'.
properties - Displays the properties of root project 'issue-8568'.
tasks - Displays the tasks runnable from root project 'issue-8568'.

MyCustomTask tasks
------------------
myPmdTask - MyCustomTask

To see all tasks and more detail, run gradlew tasks --all

To see more detail about a task, run gradlew help --task <task>

> Task :verify
[doFirst] During task execution: 1
[doLast] During task execution: 1
```

There is a different thing to notice, `afterEvaluate` are executed in the order they are registered. The first `afterEvalutate` shows no `MyCustomTask` but the second `afterEvaluate` shows one task as expected. The `doFirst` and `doLast` works as expected given the task is executed within the project the plugin is applied. The issue is in the build logic and not Gradle. I will close this issue. If you have another sample that could point otherwise, reopen the issue and we will look into it some more.

**Closed by lacasseio** 2019-02-21 15:44 UTC

**Comment by dknopp** [comment] 2019-03-06 19:19
@lacasseio thanks for the help, just an update. I verified that we were applying plugins in the correct order but were still encountering the issue.

One thing we were applying plugins in sub-files using the string labels instead of the FQDN(s) of the plugin class(es).

I switched things around to apply plugins in sub-files using FQDN(s) and no longer encountered an issue.

One of my co-workers suggested it as he seemed to recall Gradle having weird issues when plugins where applied in sub-files using the labels instead of FQDN(s).

Anyway just wanted to update you. Is gradle having an issue with plugins in sub-files that are not applied using the FQDN a known or documented issue?

**Comment by mwos-sl** [comment] 2021-12-15 23:16
FWIW I've got similar issue in my setup. In my case I have
```
allprojects {
  apply plugin: "org.scoverage"
}
```
Then I have
```
subprojects {
  afterEvaluate {
     def reportTasks = project.tasks.withType(org.scoverage.ScoverageReport)
   }
}
```
and `reportTasks` is empty. But when I print `project.tasks` the tasks are there. I did similar thing as @dknopp and printed classes, and those have "_Decorated" suffix.

@dknopp what do you exactly mean by applying the plugin via label vs Fully Qualified Domain Name? Could you please provide an example?

**Comment by mwos-sl** [comment] 2021-12-15 23:22
I checked `instanceof org.scoverage.ScoverageReport` on those tasks, and it returns false :( So indeed this "*_Decorated" breaks comparison.
