### ISSUE TITLE
Failure to fetch plugin JAR file by id results in a build failure, no attempts to resolve the plugin POM

### ISSUE THREAD

**Issue by netvl** [gradle/gradle#17594] opened 2021-07-01 18:57 UTC
Suppose your build has a custom plugin dependency like this:
```kotlin
plugins {
    id("com.yourcompany.internal.something") version "1.2.3"
}
```

If the plugin is published via the `java-gradle-plugin` plugin's `gradlePlugin` block, it will produce two artifacts: the "main" POM/JAR pair with the actual implementation and the "plugin" POM, located at the `com.yourcompany.internal.something:com.yourcompany.internal.something.gradle.plugin:1.2.3` coordinates, which contains a dependency on the "main" artifact.

For some reason, Gradle attempts to resolve not only the POM descriptor of the "plugin" artifact, but also its potential JAR file. Since there is no JAR file (I'm not sure when it would be there, actually), it does not work. I believe that in this case, Gradle uses the POM descriptor to locate the "main" artifact and use that.

The problem here, however, is that in some setups of services like Artifactory, it is possible for users to access existing files, but for any non-existent file the service would return not 404 but 403 Forbidden or 401 Unauthorized. Gradle treats this kind of response as an unrecoverable failure and terminates the build, while the "plugin" POM and the "main" artifacts are perfectly accessible to the user.

### Expected Behavior

I would expect Gradle to ignore *any* kinds of failures when attempting to resolve the "plugin" JAR file, because it does not seem like it is the primary means for downloading a plugin. At the very least, it should attempt to go through the POM->"main" artifact route before giving up.

### Current Behavior

As described above, the build fails without trying to locate the "main" artifact via the "plugin" POM.

### Context

This affects users whose repository setup does not return 404 for missing artifacts in all cases. At least in Artifactory, this behavior is not possible to adjust without fully dropping path-based access control.

### Steps to Reproduce 

Unfortunately it is not really possible to create a sample project because the issue depends on the specific environment where the build is run. I believe that the smallest way to reproduce it would be to set up an HTTP server which would serve these three routes with 200 OK and the respective files:
* `/com/yourcompany/internal/something/com.yourcompany.internal.something.gradle.plugin/1.2.3/com.yourcompany.internal.something.gradle.plugin-1.2.3.pom`
* `/com/yourcompany/internal/something-gradle-plugin/1.2.3/something-gradle-plugin-1.2.3.pom`
* `/com/yourcompany/internal/something-gradle-plugin/1.2.3/something-gradle-plugin-1.2.3.jar`

And serve all other routes with 401 Unauthorized or 403 Forbidden. Then the plugin project would look like this:

```kotlin
// settings.gradle.kts
rootProject.name = "something-gradle-plugin"

// build.gradle.kts
plugins {
    java
    `java-gradle-plugin`
}

group = "com.yourcompany.internal"
version = "1.2.3"

gradlePlugin {
    plugins {
        register("internalPlugin") {
            id = "com.yourcompany.internal.something"
            implementationClass = "..."
        }
    }
}
```

I was able to reproduce this with a MITM proxy (like Charles) which rewrites the response for the JAR file to 403 Forbidden.

### Your Environment

This is reproducible both on Gradle 6.9 and Gradle 7.0+.

**Comment by ljacomet** [comment] 2021-07-05 09:27
Marking this as a duplicate of #8754

**Closed by ljacomet** 2021-07-05 09:27 UTC
Labels: a:bug, closed:duplicate, in:plugin-management
