### ISSUE TITLE
toolchain feature fails to use IBM java VM

### ISSUE THREAD

**Issue by aanno** [gradle/gradle#19560] opened 2022-01-12 15:42 UTC
### Expected Behavior
If gradle (7.3.3) lists a VM with `gradle -q javaToolchains`, it should be used when it fits.

### Current Behavior
IBM java VM is listed with `gradle -q javaToolchains` 

```
$ ~/.sdkman/candidates/gradle/current/bin/gradle -q javaToolchains

 + Options
     | Auto-detection:     Enabled
     | Auto-download:      Enabled

 + Eclipse Adoptium JDK 11.0.13+8
     | Location:           C:\dev\jdk-11.0.13+8
     | Language Version:   11
     | Vendor:             Eclipse Adoptium
     | Is JDK:             true
     | Detected by:        environment variable 'JDK11_HOME'

 + Eclipse Adoptium JDK 17.0.1+12
     | Location:           C:\dev\jdk-17.0.1+12
     | Language Version:   17
     | Vendor:             Eclipse Adoptium
     | Is JDK:             true
     | Detected by:        environment variable 'JDK17_HOME'

 + IBM JDK 8.0.7.0 - pwa6480sr7-20211025_01(SR7)
     | Location:           C:\Programme\IBM\WebSphere\AppServer\java\8.0
     | Language Version:   8
     | Vendor:             IBM
     | Is JDK:             true
     | Detected by:        Current JVM

 + Oracle JRE 1.8.0_291-b10
     | Location:           C:\Program Files (x86)\Java\jre1.8.0_291
     | Language Version:   8
     | Vendor:             Oracle
     | Is JDK:             false
     | Detected by:        Windows Registry

 + Temurin JDK 1.8.0_312-b07
     | Location:           C:\dev\jdk8u312-b07
     | Language Version:   8
     | Vendor:             Temurin
     | Is JDK:             true
     | Detected by:        environment variable 'JDK8_HOME_ADOPTIUM'
```

But using it with 

```kotlin
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
        vendor.set(JvmVendorSpec.IBM)
    }
}
```

fails

```
$ gradle build
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Error while evaluating property 'javaCompiler' of task ':compileJava'
   > Failed to calculate the value of task ':compileJava' property 'javaCompiler'.
      > No compatible toolchains found for request filter: {languageVersion=8, vendor=IBM, implementation=vendor-specific} (auto-detect true, auto-download true)
```

### Steps to Reproduce 
Trivial.

```
org.gradle.java.installations.fromEnv=JDK8_HOME,JDK8_HOME_ADOPTIUM,JDK11_HOME,JDK17_HOME
```

where each of the env variable points to a valid Java VM implementation.

### Your Environment
Build scan URL: https://gradle.com/s/xzqki6undf6e6

**Comment by mlopatkin** [comment] 2022-01-13 11:49
AFAIR IBM JVM is J9, isn't it? Then I believe this is a duplicate of #17940.

**Comment by jbartok** [comment] 2022-02-22 09:48
I can confirm that adding `implementation.set(JvmImplementation.J9)` does indeed fix the problem. I can also confirm that the situation is very confusing and we should do something about it. We should also enhance the output of the `javaToolchains` task to list the implementation type.

**Closed by jbartok** 2022-02-22 09:48 UTC
Labels: a:bug, in:toolchains
