### ISSUE TITLE
add jitpack() as repository mirror

### ISSUE THREAD

**Issue by Tjorven-Liebe** [gradle/gradle#27612] opened 2024-01-08 14:09 UTC
### Expected Behavior

this is intended as a replace for 
```groovy
maven { 
  url 'https://jitpack.io' 
}
```
instead of writing this whole code just add it like the mavenCentral() shortcut:
```GROOVY
jitpack()
```

### Current Behavior (optional)

you need to provide a custom repository with url:
```GROOVY
maven {
  url 'https://jitpack.io'
}
```

### Context

More or less I want to reduce the time needed to add a jitpack repository. I think, that this is relevant enough as many repositories are based on jitpack.

**Comment by cobexer** [comment] 2024-01-11 13:51
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #16310

**Closed by cobexer** 2024-01-11 13:51 UTC
Labels: a:feature, to-triage
