### ISSUE TITLE
gradle fails to find files in the cache

### ISSUE THREAD

**Issue by yurivict** [gradle/gradle#7841] opened 2018-11-28 02:25 UTC
I preserve cache after the successful build and leave it in ```$GRADLE_USER_HOME/caches```.

Then, in VM, this cache directory is restored. However, the build now fails:
```
$ gradle --offline --build-cache localJar
...
===>  Building for gatk-4.0.11.0
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'gatk'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not download gradle-download-task.jar (de.undercouch:gradle-download-task:2.1.0): No cached version available for offline mode
   > Could not download shadow.jar (com.github.jengelman.gradle.plugins:shadow:1.2.3): No cached version available for offline mode
```

```GRADLE_USER_HOME``` is set where ```caches``` is located, and these files are in it.
What is wrong? Why can't gradle now can't find ```gradle-download-task-2.1.0.jar``` and ```shadow-1.2.3.jar``` that are in the cache?

gradle-4.6
FereBSD 11.2 amd64

**Comment by yurivict** [comment] 2018-11-28 02:50
After some experimentation, I figured out that gradle memorizes the full cache path location in the cache itself. When the package is built, it has to reuse cache built while at another location.

How to use only relative locations in cache?

**Comment by yurivict** [comment] 2018-11-28 03:20
This has never been solved: https://github.com/gradle/gradle/issues/1338

**Comment by oehme** [comment] 2018-11-28 08:33
Duplicate of #1338

**Closed by oehme** 2018-11-28 08:33 UTC
