### ISSUE TITLE
New directories affect hash of task inputs when using FileTrees that should only match files

### ISSUE THREAD

**Issue by robbie-demuth** [gradle/gradle#3444] opened 2017-11-10 15:21 UTC
### Expected Behavior

When using a FileTree as part of a task's inputs that only matches files with a certain extension, new empty directories within the FileTree's base directory should not affect the hash of the task's inputs. 

### Current Behavior

Suppose I have the following Copy task:

```
task copy(type: Copy) {
  from fileTree('src') {
    include '**/*.txt'
  }
  into 'dst'
  includeEmptyDirs = false
}
```

And suppose I have the following directory structure:

```
src/
  a.txt
```

I run `./gradlew copy` once to populate the task's history. Now, I create a new file called `b.json` in the `src/` directory and re-run `./gradlew copy`. As expected, the task is UP-TO-DATE because `b.json` doesn't match the FileTree's filter. Now, I create an empty directory in `src/` so my directory structure is as follows:

```
src/
  a.txt
  b.json
  subdir/
```

When I run `./gradlew -i copy`, Gradle reports that the task must re-execute because one of the inputs to the task has changed:

```
Executing task ':copy' (up-to-date check took 0.003 secs) due to:
  Input property 'rootSpec$1' file C:\repo\gradle-bugs\src\subdir has been added.
```

### Context

For the purposes of illustrating the bug, I described the issue with a Copy task above, but I actually ran into this issue when attempting to create a cacheable task class because empty directories that were not relevant to the inputs of my task were affecting the cache key. Specifically, my task exposes an `@Internal` property denoting one or more directories that should be used by the task. I've then annotated a method with `@InputFiles` that takes these directories and uses FileTrees to filter out everything but files that end with `*.properties`. I decided to design it this way because some legacy code we're calling expects the actual directories as arguments, but it does the same filtering internally, so empty directories and files with other extensions shouldn't affect affect the task's outputs. Given that some of the directories are actually areas of active development, the cache key ends up being affected by the user's directory structure even when they aren't modifying `*.properties` files.

### Steps to Reproduce (for bugs)

Unzip [bug.zip](https://github.com/gradle/gradle/files/1461782/bug.zip) and follow the instructions above.

### Your Environment

 * Build scan URL: N/A

**Comment by robbie-demuth** [comment] 2017-11-10 15:49
It does seem that using the [`getFiles()`](https://docs.gradle.org/current/javadoc/org/gradle/api/file/FileCollection.html#getFiles()) method solves the issue, but I don't see why it is necessary. If this behavior is expected, it should at the very least be better documented. It seems like this isn't the first time that the behavior has caused confusion: https://discuss.gradle.org/t/filetree-as-incremental-task-input-includes-added-directories/18877/2

**Comment by robbie-demuth** [comment] 2017-12-20 17:28
Discovered something new, so I thought I'd give a quick update. It seems like this only occurs when the task input annotated with `@InputFiles` uses anything other than `@PathSensitive(PathSensitivity.NONE)`. I recently ran into this issue again when updating a task input that was using `PathSensitivity.NONE` to use `PathSensitivity.NAME_ONLY`. I assume this is consistent with the original issue I posted above because I would think that the task inputs to the `Copy` task don't use `PathSensitivity.NONE`

**Comment by robbie-demuth** [comment] 2018-02-05 14:04
@wolfs - Do you have any insight into this issue? Working around the behavior described here is the reason I had to open https://github.com/gradle/gradle/issues/4213

**Comment by Loffe** [comment] 2018-03-13 13:30
I've run into this issue as well.

**Comment by wolfs** [comment] 2018-05-04 09:09
This is very similar (if not the same) as https://github.com/gradle/gradle/issues/2463.

**Comment by wolfs** [comment] 2018-08-28 14:14
Closing as duplicate of #2463.

**Closed by wolfs** 2018-08-28 14:14 UTC
Labels: a:bug, from:contributor, in:incremental-build
