### ISSUE TITLE
Strange JVM target warning from Kotlin DSL in buildSrc

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#18935] opened 2021-11-10 20:37 UTC
### Expected Behavior
No warning, good DX by default.

### Current Behavior
> 'compileJava' task (current target is 11) and 'compileKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.

### Context
This happens because ``plugins { `kotlin-dsl` }`` sets the default to a hard-coded value.

https://github.com/gradle/gradle/blob/1ca4e848c15bde8550fcbc682c8ecb06b1ba34fb/subprojects/kotlin-dsl-plugins/src/main/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslPluginOptions.kt#L41-L43

I'm guessing that ``plugins { java }`` uses the runtime because I'm running on Java 11.
(couldn't find out from DefaultJavaPluginExtension, got lost in ToolChainSpecs and object factory)

This would be a much better default rather than hardcoding:
```kotlin
kotlinDslPluginOptions {
	//jvmTarget.set(java.toolchain.languageVersion.map { it.toString() })
	jvmTarget.set(provider { java.targetCompatibility.toString() })
}
```

#### A sidenote
I tried to centralize the setting with
```kotlin
val javaVersion = JavaVersion.VERSION_11
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
	// Do not use, no effect; will be overridden by kotlinDslPluginOptions.jvmTarget, see KotlinDslCompilerPlugins.
	kotlinOptions.jvmTarget = javaVersion.toString()
}
java {
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
}
```
but this trivial setup (that works in other places) failed me because `KotlinDslCompilerPlugins` is overriding in `afterEvaluate`.

### Steps to Reproduce 
Gradle 7.2 project
buildSrc with only Kotlin code and this in build.gradle.kts
```kotlin
plugins {
	`kotlin-dsl`
	`java-gradle-plugin`
}
```

### Your Environment
Build scan URL: https://gradle.com/s/47jxa3h6uttbq

**Comment by RinOrz** [comment] 2021-11-19 15:03
The same problem, if the script calls the Kotlin extension function compiled by 11 target, `gradle sync` will fail directly.

**Comment by jjohannes** [comment] 2021-11-19 17:09
This is an issue in Kotlin: https://youtrack.jetbrains.com/issue/KT-48745

The warning should not appear if you only write Kotlin and have no Java code in your plugins. It's fixed in Kotlin 1.6.0.

But that won't help us here until Gradle upgrades to 1.6.0. I think something should be done on the Gradle side as this is a wrong warning that a lot folks get once upgrading. And you should not have to do something in your build to disable it. (If there is a **7.3.1**, I think a fix for this should be included.)

@TWiStErRob if you still want to "fix" it in your build, you should set the target for Java to 8, and not try to change the one for Kotlin. It's fixed on 8 by the `kotlin-dsl` plugin for the reason that Gradle itself runs on Java 8 and thus plugins should ideally run on 8 as well.
Another way to get rid of the warning is to add this to `gradle.properties` in the build of the plugins (`buildSrc` or included build like `build-logic`):
`kotlin.jvm.target.validation.mode = IGNORE`

**Comment by eskatos** [comment] 2021-12-02 08:09
We didn't find any way to fix this from the Gradle side of things without risks to break builds. The correct fix is to upgrade to Kotlin 1.6 which fixes the underlying bug. But, Kotlin 1.6.0 breaks incremental Kotlin compilation in too many cases to be considered ([KT-49822](https://youtrack.jetbrains.com/issue/KT-49822), [KT-49340](https://youtrack.jetbrains.com/issue/KT-49340)). We need to wait for Kotlin 1.6.10 that should be out in a week or so.

**Comment by TWiStErRob** [comment] 2021-12-02 09:45
Does that mean Gradle 7.4 will come with Kotlin 1.6.10?

**Comment by nhalase** [comment] 2021-12-03 18:55
@eskatos, can you elaborate on what you mean by "We need to wait for Kotlin 1.6.10 that should be out in a week or so."? It sounds like you're saying there's potential for the embedded kotlin-dsl to be upgraded to Kotlin 1.6.10, but I was under the impression the Gradle team would only be upgrading embedded Kotlin versions on Gradle major releases (I'd love to be misinformed about this). 

I'm not asking if you're committing to add Kotlin 1.6.10 to Gradle 7.4, but rather, is it even on the table for Kotlin 1.6.x to be added in a Gradle 7.x release?

**Comment by TWiStErRob** [comment] 2021-12-04 11:21
@jjohannes even though I understand KT-48745 means that this warning message is a false positive, I still strongly believe that the configuration of toolchains/jvm target versions is the responsibility of Gradle, not every single project who uses buildSrc. Regardless of having or not having Java code the versions should match in the standard default Gradle setup.

@eskatos how would increasing the buildSrc Kotlin JVM target to the same Java version as the Java version as targetCompatibility (which is equal to the JVM version running the build) break things?

**Comment by eskatos** [comment] 2021-12-07 09:56
@nhalase, I'm happy to inform you that you were misinformed on this :) We do Kotlin upgrades on minor Gradle versions. For example in Gradle 6.8 we moved from Kotlin 1.3.72 to 1.4.20 and in Gradle 7.2 we moved from 1.4.31 to 1.5.21. But, note that in Gradle 6.8 we continued to compile Kotlin build scripts and projects applying the `kotlin-dsl` plugin targeting Kotlin api/language target 1.3 for backwards compatiblity. In Gradle 7.0 we changed that to use Kotlin api/language target 1.4. If we upgrade to Kotlin 1.6.x in Gradle 7.x we would use the same strategy and still target Kotlin api/language target 1.4. We can move to a more recent api/language target in the next major Gradle version, 8.x.

**Comment by eskatos** [comment] 2021-12-07 10:01
@TWiStErRob, us overriding the java target could break builds with an explicit target, like failing compilation.

**Comment by nhalase** [comment] 2021-12-08 22:41
> But, note that in Gradle 6.8 we continued to compile Kotlin build scripts and projects applying the kotlin-dsl plugin targeting Kotlin api/language target 1.3 for backwards compatiblity.

@eskatos Thanks for this explanation! I can see where my initial confusion came from.

**Comment by eskatos** [comment] 2021-12-14 13:04
https://github.com/gradle/gradle/issues/19308 will fix this by bringing the proper Kotlin bugfix

**Comment by jjohannes** [comment] 2022-01-11 07:05
@eskatos Any chance that #19308 may go into 7.4 already? As far as I am concerned, this issue here is a regression (only my opinion of course 😄).

**Comment by eskatos** [comment] 2022-01-11 10:08
#19308 is scheduled for 7.5, the window for 7.4 has closed already

**Comment by asodja** [comment] 2022-03-03 22:40
You can find `7.5` nightlies at: https://services.gradle.org/distributions-snapshots/.

**Comment by WebTiger89** [comment] 2022-03-09 10:27
So far I can say that the nightly does not fix the issue

**Comment by donat** [comment] 2022-04-07 07:35
With https://github.com/gradle/gradle/issues/19308 merged, this issue will be fixed in Gradle 7.5. I've reproduced the problem with Gradle 7.4 and can confirm that switching to the [latest 7.5 snapshot](https://services.gradle.org/distributions-snapshots/gradle-7.5-20220406232819+0000-bin.zip) removes the warning.  Closing as fixed.

**Closed by donat** 2022-04-07 07:35 UTC
Labels: a:bug, in:plugin-development, in:kotlin-dsl, @support

**Comment by simaotwx** [comment] 2022-05-04 08:10
I'm still getting the same on the latest snapshot:

```
Welcome to Gradle 7.5-20220503230329+0000!

Here are the highlights of this release:
 - Support for Java 18
 - Support for building with Groovy 4
 - Much more responsive continuous builds
 - Improved diagnostics for dependency resolution

Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status for details

> Task :compileKotlin
'compileJava' task (current target is 11) and 'compileKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.

BUILD SUCCESSFUL in 30s
3 actionable tasks: 3 executed
```

This fixed it for me:

```
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
}

tasks.withType<JavaCompile> {
    options.compilerArgs.addAll(listOf("-source", "1.8", "-target",  "1.8"))
}
```

**Comment by ljacomet** [comment] 2022-05-05 09:17
@simaotwx Please open a new issue with a full reproducer. It might be a different problem, or an expected message in your setup.

**Comment by A-BEECHEY** [comment] 2023-01-18 09:26
this issue is still occuring, i have raised a buganizer issue here https://issuetracker.google.com/issues/265653154

**Comment by TWiStErRob** [comment] 2023-01-18 09:41
@A-BEECHEY very different issue you have. This issue is about buildSrc only. Here we have a Gradle plugin and a Gradle classpath that controls Kotlin and JVM target; while in AGP's case, we have full control over everything. I'll have a look later at your SO question, should be easy to fix.

**Comment by A-BEECHEY** [comment] 2023-01-18 09:45
[Kaptive.zip](https://github.com/gradle/gradle/files/10444350/Kaptive.zip)
heres the example android project that recreates the issue (if thats any help)
