### ISSUE TITLE
Signing plugin generates overlapping task outputs

### ISSUE THREAD

**Issue by joffrey-bion** [gradle/gradle#26132] opened 2023-08-16 20:32 UTC
### Current Behavior

The signing plugin generates `.asc` files next to the signed files, which is potentially in the output dir of a task which is used by another task. This leads to overlapping outputs.

### Expected Behavior

I'm not entirely sure. It seems that the Signing plugin instead should generate its `.asc` files somewhere else, but somehow still add them to the publication. I don't know if this problem can be fixed in other plugins (like the Kotlin Multiplatform plugin here, see "Context" section).

### Context (optional)

For instance, the Kotlin Multiplatform Gradle plugin configures a task `compileKotlinLinuxX64` which generates a `.klib` file that is part of the publication, and tasks like `linkDebugTestLinuxX64` and `compileKotlinTestLinux64` which use the same file (and likely the directory). When I use the signing plugin to sign my publications, I get a new task `signLinuxX64Publication` which generates a `.asc` file right next to the `.klib` file. When running `publish` tasks (which require both signing and link/test tasks), this leads to errors like:

```
Some problems were found with the configuration of task ':signLinuxX64Publication' (type 'Sign').
  - Gradle detected a problem with the following location: '/Users/runner/work/chrome-devtools-kotlin/chrome-devtools-kotlin/build/classes/kotlin/linuxX64/main/klib/chrome-devtools-kotlin.klib.asc'.
    
    Reason: Task ':linkDebugTestLinuxX64' uses this output of task ':signLinuxX64Publication' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':signLinuxX64Publication' as an input of ':linkDebugTestLinuxX64'.
      2. Declare an explicit dependency on ':signLinuxX64Publication' from ':linkDebugTestLinuxX64' using Task#dependsOn.
      3. Declare an explicit dependency on ':signLinuxX64Publication' from ':linkDebugTestLinuxX64' using Task#mustRunAfter.
    
    For more information, please refer to https://docs.gradle.org/8.2.1/userguide/validation_problems.html#implicit_dependency in the Gradle documentation.
  - Gradle detected a problem with the following location: '/Users/runner/work/chrome-devtools-kotlin/chrome-devtools-kotlin/build/classes/kotlin/linuxX64/main/klib/chrome-devtools-kotlin.klib.asc'.
    
    Reason: Task ':compileTestKotlinLinuxX64' uses this output of task ':signLinuxX64Publication' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':signLinuxX64Publication' as an input of ':compileTestKotlinLinuxX64'.
      2. Declare an explicit dependency on ':signLinuxX64Publication' from ':compileTestKotlinLinuxX64' using Task#dependsOn.
      3. Declare an explicit dependency on ':signLinuxX64Publication' from ':compileTestKotlinLinuxX64' using Task#mustRunAfter.
    
    For more information, please refer to https://docs.gradle.org/8.2.1/userguide/validation_problems.html#implicit_dependency in the Gradle documentation.
```

The same is true for all native targets (just replace `LinuxX64` with other targets and the error is the same).

### Steps to Reproduce

I only consistently reproduced the problem on the CI (Github Actions) when running `./gradlew check publishToSonatype` to publish my library, and only since I moved to Gradle 8 (which made it an error I believe). This led to a lot of back and forth trying to figure that out. I don't manage to get the error locally on my windows machine, though.

Here is the project in which I reproduced:
https://github.com/joffrey-bion/chrome-devtools-kotlin/tree/repro-signing-plugin-issue

The link is to the branch `repro-signing-plugin-issue`, which is pointed just before I managed to workaround the problem (with https://github.com/joffrey-bion/chrome-devtools-kotlin/commit/bfa060b7502243ecfefbb141e11715e4f64b572a) by placing explicit `mustRunAfter` constraints on the problematic task pairs:

```kotlin
// Resolves issues with .asc task output of the sign tasks:
// Task ':linkDebugTest<platform>' uses this output of task ':sign<platform>Publication' without declaring an explicit or implicit dependency
// Task ':compileTestKotlin<platform>' uses this output of task ':sign<platform>Publication' without declaring an explicit or implicit dependency
// With <platform> being one of LinuxX64, IosSimulatorArm64, MacosArm64, and all other native targets...
val problematicNativeTargets = listOf("Ios", "Macos", "Tvos", "Watchos", "Linux", "Mingw")
tasks.withType<Sign>().configureEach {
    if (problematicNativeTargets.any { it in name }) {
        val target = name.removePrefix("sign").removeSuffix("Publication")
        val linkDebugTestTaskName = "linkDebugTest$target"
        val compileTestKotlinTaskName = "compileTestKotlin$target"
        mustRunAfter(linkDebugTestTaskName, compileTestKotlinTaskName)
    }
}
```

EDIT: a cleaner workaround:

```kotlin
// Resolves issues with .asc task output of the sign task of native targets.
// See: https://github.com/gradle/gradle/issues/26132
// And: https://youtrack.jetbrains.com/issue/KT-46466
tasks.withType<Sign>().configureEach {
    val pubName = name.removePrefix("sign").removeSuffix("Publication")

    // These tasks only exist for native targets, hence findByName() to avoid trying to find them for other targets

    // Task ':linkDebugTest<platform>' uses this output of task ':sign<platform>Publication' without declaring an explicit or implicit dependency
    tasks.findByName("linkDebugTest$pubName")?.let {
        mustRunAfter(it)
    }
    // Task ':compileTestKotlin<platform>' uses this output of task ':sign<platform>Publication' without declaring an explicit or implicit dependency
    tasks.findByName("compileTestKotlin$pubName")?.let {
        mustRunAfter(it)
    }
}
```

### Gradle version

8.2.1

### Build scan URL (optional)

https://scans.gradle.com/s/4r5yl2wbifrgs

### Your Environment (optional)

`macos-latest` machine on the GitHub Actions CI.
Kotlin 1.9.0
Kotlin Gradle plugin 1.9.0

Using Kotlin multiplatform with all native targets (linuxX64, mingwX64, macosX64, as well as all tvOS, iOS, watchOS targets, etc.).

**Comment by ljacomet** [comment] 2023-08-30 13:02
Thank you for your interest in Gradle.

Before deciding how to handle this report, can you respond to the following question:

Do you know if Kotlin Multiplatform generates multiple files for a native target?

* If yes, then indeed the way the signing plugin works is annoying as it will generate the reported error if tasks run in a problematic order.
* If no, then the Kotlin Multiplatform plugin should be improved to have downstream task depend on a file instead of a folder. This would no longer trip the problem when the signing plugin adds `.asc` files in the folder

In both cases though, moving generated signature files to different folders may have other side effects on existing builds.

**Comment by martinbonnin** [comment] 2023-08-30 13:32
> Do you know if Kotlin Multiplatform generates multiple files for a native target?

Do you mean the publication contains several artifact? AFAIK, the KMP plugin creates multiple publications:

* kotlinMultiplatform (for common metadata)
* jvm
* macosArm64
* iosArm64
* etc...

Each publication contains several artifacts ([source around here](https://github.com/JetBrains/kotlin/blob/bcf27812cd28041e0b9ffa3bfe52fc58c397d0eb/libraries/tools/kotlin-gradle-plugin/src/common/kotlin/org/jetbrains/kotlin/gradle/plugin/mpp/AbstractKotlinTarget.kt#L216)). It may depends the targets but overall it'll have:

* a main .klib file
* a metadata .jar file
* a source jar ([source around here](https://github.com/JetBrains/kotlin/blob/bcf27812cd28041e0b9ffa3bfe52fc58c397d0eb/libraries/tools/kotlin-gradle-plugin/src/common/kotlin/org/jetbrains/kotlin/gradle/plugin/mpp/AbstractKotlinTarget.kt#L140))
* maybe others (kdoc if dokka is applied?)

So all in all, I'd say the KMP plugin does generate multiple files. @tapchicoma will know more.

> Kotlin Multiplatform plugin should be improved to have downstream task depend on a file instead of a folder

I thought the "contract" between KGP and the signing plugin was in terms of "publications", and not files/folders?

> moving generated signature files to different folders may have other side effects on existing builds.

If existing builds need a folder containing all the artifacts alongside their signatures, could the signing task copy over the artifacts for backward compat?

**Comment by Tapchicoma** [comment] 2023-08-30 13:37
Related Kotlin [issue](https://youtrack.jetbrains.com/issue/KT-61313/Kotlin-MPP-Gradle-Signing-plugin-Task-linkDebugTestLinuxX64-uses-this-output-of-task-signLinuxX64Publication) – probably we may fix it on our side.

**Comment by joffrey-bion** [comment] 2023-08-30 13:38
> Do you know if Kotlin Multiplatform generates multiple files for a native target?

I tried to look at the implementation, but I'm not very familiar with it. It's hard for me to tell for sure.
On the surface, I ran `compileKotlinLinuxX64` and `compileKotlinMingwX64` and both only generated a single `.klib` file in their respective directory.

But in any case, as you said, depending on the use case at hand, an actual output *directory* might be necessary, in which case the signing plugin's behavior is getting in the way.

**Comment by joffrey-bion** [comment] 2023-08-30 13:41
> > Kotlin Multiplatform plugin should be improved to have downstream task depend on a file instead of a folder
>
> I thought the "contract" between KGP and the signing plugin was in terms of "publications", and not files/folders?

But here we're talking about the dependency between Kotlin plugin tasks (e.g. `compile` and `linkDebugTest`), not interaction/contract between the Kotlin tasks and the signing task.

**Comment by martinbonnin** [comment] 2023-08-30 14:03
> @martinbonnin I think here Louis was talking about the dependency between multiple Kotlin plugin tasks (e.g. compile and linkDebugTest), not interaction/contract between the Kotlin tasks and the signing task.

Right 👍 Looks like `linkDebugTest` uses the full directory where the `.klib` file is. If I add manually a placeholder file next to the `.klib` file then `linkDebugTest` becomes out of date which is technically not really true:

```
Task ':compileTestKotlinMacosArm64' is not up-to-date because:
  Input property 'friendModule$kotlin_gradle_plugin_common' file /Users/mbonnin/git/test-kmp/build/classes/kotlin/macosArm64/main/klib/placeholder.test has been added.
```

So yea, as you said, it depends whether a full directory is needed or not. I guess worst case `lingDebutTest` could take a `FileCollection` as input.

**Comment by ov7a** [comment] 2023-09-01 08:56
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team, but this area of Gradle is currently not in focus. It might take a while before it gets implemented.

***

While the Kotlin plugin can be improved, this report highlights that the signing plugin should produce isolated outputs.
This can be added as an opt-in and enabled by default in a future major version of Gradle.

**Comment by martinbonnin** [comment] 2023-12-05 17:19
Just got hit by this again:

```
Reason: Task ':apollo-mockserver:compileTestKotlinIosArm64' uses this output of task 
':apollo-mockserver:signIosArm64Publication' without declaring an explicit or 
implicit dependency. 
This can lead to incorrect results being produced, depending on what order the tasks are executed.
```

> the signing plugin should produce isolated outputs.

@ov7a more of a general thought but would be cool to have a gradle-provided unique output dir like `build/$taskName/output`, maybe could get populated automagically:

```kotlin
task SomeTask: DefaultTask() {
  @get:IsolatedOutput
  val output: DirectoryProperty
}
```

**Comment by jvandort** [comment] 2024-10-15 10:14
> more of a general thought but would be cool to have a gradle-provided unique output dir like build/$taskName/output, maybe could get populated automagically:

This is something we plan to move towards. The general idea is that each unit of work (including tasks) should have its own _workspace__ to operate within, isolated from other units of work. 

This is not the case yet, but a goal we want to move toward.

> the signing plugin should produce isolated outputs.

As a general solution to this issue I think it would make sense to have the signing plugin write its signature files in a separate location from the file being signed.

**Comment by jvandort** [comment] 2024-10-15 10:19
Duplicate of https://github.com/gradle/gradle/issues/26091

**Closed by jvandort** 2024-10-15 10:19 UTC
Labels: in:signing-plugin, a:bug, closed:duplicate
