### ISSUE TITLE
Dependency verification for metadata files seems to fail due to normal gradle cache cleanup

### ISSUE THREAD

**Issue by scottdweber** [gradle/gradle#14884] opened 2020-10-15 18:43 UTC
I've setup the dependency verification feature with `<verify-metadata>true</verify-metadata>` which is great. However, about once a week, every developer and our CI machine start complaining about POM files having been deleted from the cache during normal build activities. The only way to get those files back seems to be by running `./gradlew --refresh-dependences <task>`. Without the `--refresh-dependencies` flag, all builds fail.

### Expected Behavior
Either these POMs should not be deleted from the cache, since they are actually needed by the build, or the normal build process should be re-downloading the necessary POMs, rather than complaining that they don't exist.

### Current Behavior
The POMs are not re-downloaded unless we force _all_ dependencies to re-download by using the `--refresh-dependencies` flag

### Context
Due to the pain involved with this happening to all developers and on our CI machines, we have been forced to turn off the `verify-metadata` setting. It would be great if we could turn this feature back on.

### Steps to Reproduce 
Due to the timing of this behavior appearing to be directly related to automated cleanup of the gradle cache, it is difficult to pinpoint an exact set of reproduction steps. It can be simulated by manually deleting POM files from the cache, but that seems a bit different than when the system does an automatic cleanup of the cache.

### Your Environment
Mostly building on Macs. Using Gradle 6.6.1. Building an Android app, if that is relevant.

**Comment by ljacomet** [comment] 2020-10-16 06:39
This looks like a duplicate of #12713

Could you verify with a [6.8 nightly](https://gradle.org/nightly/) that the issue has been resolved?

**Comment by scottdweber** [comment] 2020-10-16 12:34
Oh, fantastic! Yes, I can confirm that this problem does appear to be fixed in the 6.8 nightly build. Thanks!

**Comment by ljacomet** [comment] 2020-10-26 10:58
Closing as duplicate

**Closed by ljacomet** 2020-10-26 10:58 UTC
Labels: @jvm, a:bug, from:contributor, in:dependency-management
