### ISSUE TITLE
Composite builds should handle included builds where dependency versions are set by resolution rules

### ISSUE THREAD

**Issue by dorongold** [gradle/gradle#947] opened 2016-11-30 10:34 UTC
### Expected Behavior
When running a composite build from a project referencing another project as included-build,
each project (the "main" project and the included project) should be built separately with their own resolutionStrategies as defined in their own build.gradle or their own applied plugins.

### Current Behavior
ResolutionStrategy of the "main" project (the project that `gradle build` is run on) is applied to all other projects (included-builds).
**ResolutionStrategies of included projects are ignored.**

### Context
I use [dependency-management-plugin](https://github.com/spring-gradle-plugins/dependency-management-plugin) in some of my projects. Applying this plugin creates a resolutionStrategy that resolves dependency versions.
In those build files that apply the plugin, I declare dependencies without versions, such as: `compile org.slf4j:slf4j-api`, counting on the resolutionStrategy created by the plugin to determine the vesrion.
If such a project is included with `--included-build` in another project that I try to build, the build fails because the resolutionStrategy of the included-build is ignored and the dependency version cannot be resolved.

This bug is general and not limited to the use of plugins.

Directly declaring a resolutionStrategy in `build.gradle` is ignored when this build is an included-build of another project.

### Steps to Reproduce
create two separate projects: "app" and "common"

**build.gradle of the "app" project:**
```
apply plugin: 'java'
apply plugin: 'maven'

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    compile 'deps:common:1.0'
}
```

**build.gradle of the "common" project:**
```
apply plugin: 'java'

group = 'deps'
version = '1.0'

repositories {
    mavenCentral()
}

configurations.all {
    resolutionStrategy {
        force 'org.slf4j:slf4j-api:1.7.5'
    }
}

dependencies {
    compile 'org.slf4j:slf4j-api'
}
```

Running a composite build on the "app" project fails:
```
user:/var/localwork/dependency-example/app$gradle build --include-build ../common
[composite-build] Configuring build: /var/localwork/dependency-example/common
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compileClasspath'.
> Could not find org.slf4j:slf4j-api:.
  Searched in the following locations:
      file:/home/user/.m2/repository/org/slf4j/slf4j-api//slf4j-api-.pom
      file:/home/user/.m2/repository/org/slf4j/slf4j-api//slf4j-api-.jar
      https://repo1.maven.org/maven2/org/slf4j/slf4j-api//slf4j-api-.pom
      https://repo1.maven.org/maven2/org/slf4j/slf4j-api//slf4j-api-.jar
  Required by:
      project : > project :common:

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.09 secs
```

### Your Environment
```
------------------------------------------------------------
Gradle 3.2.1
------------------------------------------------------------

Build time:   2016-11-22 15:19:54 UTC
Revision:     83b485b914fd4f335ad0e66af9d14aad458d2cc5

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_91 (Oracle Corporation 25.91-b14)
OS:           Linux 3.19.0-32-generic amd64
```

**Comment by oehme** [comment] 2016-12-18 14:55
This is expected. Dependency resolution happens isolated in each configuration, this is not specific to composite builds. 

Only the resolution strategy of the configuration being resolved is taken into account.

**Comment by wilkinsona** [comment] 2017-01-03 09:54
I understand that the behaviour may be expected given the current design, but, in that case, I'd argue that the design doesn't meet the expectations set by the description of the feature. The documentation describes composite builds as allowing your to

> combine builds that are usually developed independently, for instance when trying out a bug fix in a library that your application uses

Without a composite build, the usual way to try out a bug fix would be to build the library locally and install it into a repository, my local Maven cache for example. I'd then update my application to use this new, patched version of the library. Crucially, this would result in my application using the patched artifact's pom for dependency resolution. This doesn't happen with the current approach taken by composite builds and, as a result, the behaviour can be quite different.

If the intention is to keep the current, limited behaviour could [this section](https://docs.gradle.org/current/userguide/composite_builds.html#current_limitations_and_future_work) of the documentation please be updated to reflect that?

**Comment by bigdaz** [comment] 2017-01-03 13:25
I think you're overstating this problem: the things that aren't considered when resolving an artifact from an imported build are the _repositories_ declared for the importing build, and the _resolution strategy_, which defines things like rules and cache timeouts. The _dependency metadata_ for the imported build is definitely used when resolving.

I don't see any difference from the "publish to local repo" use case that you described. Am I missing something?

**Comment by bigdaz** [comment] 2017-01-03 13:40
I don't want to understate the problem either: the core issue is that there are a number of ways that the _published metadata_ can be tweaked for a build, such that the published POM contains information that isn't included in the dependency declarations. These modifications are not taken into account for an included build. Unfortunately, many of these modifications can be quite opaque to Gradle.

The intention is to continue to enhance composite builds so that more of the information that ends up in a published `pom` or `ivy.xml` is used when resolving an included build. We'd like to do something similar for Gradle _projects_ included in a multi-project build.

**Comment by wilkinsona** [comment] 2017-01-03 13:41
>  I don't see any difference from the "publish to local repo" use case that you described. Am I missing something?

The dependency management plugin (linked to in the original comment in this issue) uses a resolution strategy to set dependency versions. It also enhances the generated pom to include that version information.

When using a composite build, neither the resolution strategy nor the generated pom is used so dependency resolution fails. When publising to a local repo, the generated pom complete with additional version information is used so dependency resolution succeeds.

**Comment by wilkinsona** [comment] 2017-01-03 13:43
> The intention is to continue to enhance composite builds so that more of the information that ends up in a published pom or ivy.xml is used when resolving an included build

This is the missing piece in the puzzle, and is what I think should be documented as a limitation.

**Comment by bigdaz** [comment] 2017-01-03 13:46
Right, I think that "No support for included builds that have publications that don't mirror the project default configuration" and [this section](https://docs.gradle.org/current/userguide/composite_builds.html#included_build_substitution_limitations) of the docs was intended to convey this message. Would you mind submitting a PR that would make this clearer to you?

**Comment by wilkinsona** [comment] 2017-01-03 13:55
10.3.2 does indeed convey the message. Sorry, not sure how I missed that earlier. Thanks for bearing with me.

**Comment by bigdaz** [comment] 2017-01-03 14:00
I think it's fair to say that our docs can be impenetrable at times. Any feedback or suggestions for improvement is welcome.

**Comment by vitjouda** [comment] 2017-01-04 15:19
Are there any specific plans to support this feature? I believe composite builds are great tool, even better with IDEA 2016.3 integration. But our projects use spring-boot-gradle-plugin which in turn uses  dependency-management-plugin mentioned above, so they don´t work propertly with composite builds.

Or, is there any known workaround?

**Comment by oehme** [comment] 2017-03-24 19:01
I'm reopening this with a slightly changed title. While the problem is simple to solve within a single build (just declare the same substitution rules in an `allProjects()` block), there is no good way to do so for a composite.

**Comment by avonengel** [comment] 2017-09-27 12:51
@oehme Any news on this? Our project makes heavy use of Spring's dependency-management plugin, and we would like to use composite builds to simplify our development cycle.

Are there any known workarounds we can use to test and debug locally with included builds?

**Comment by oehme** [comment] 2017-09-27 13:41
We are currently working towards dependency constraints as well as BOM support directly in Gradle. I'll keep this issue updated.

To provide a little more background: Resolution rules were not meant as recommenders of versions, but to correct wrong metadata (e.g. version ranges that were too strict). Instead we intend to model constraints such as a 'recommended' version or a 'platform that belongs together' more declaratively and map them to the appropriate Maven concepts where applicable. That way they'll work with composite builds and the generated Poms will need less tweaking by the user.

**Comment by brainbytes42** [comment] 2017-10-27 09:41
Hi,
it's great to see this issue being worked on, as I just ran into a similar limitation for the composite build: the included build used a repository to directly link to github (jitpack.io, to be complete), which the main project didn't use. so the dependencies of the included project could not be resolved. 

As a quick&dirty solution, I added the additional repo to the main project, now it works. But without that change (for example, if I didn't know the included code as well as I do), it would be harder to integrate.

Adding a further remark: From the naive user perspective, I'd expect a composite build to just build that included project, af it were compiled directly - and include the results... That would (a) prevent the issue above and would (b) also allow an included Project, to also include a composite build, which would add flexibility. (For example, I have 3 distinct projects, one is a general purpose library, one is a software using that library, and one 'uber'-software that is using that software...)

(side-notice, just to be clear: composite builds are a really, really great feature, thank you for that!)

**Comment by vehovsky** [comment] 2018-01-29 16:10
@oehme Thank you for the info, is the any way of tracking progress on the mentioned topics? As we would also like to use composite builds, but the current limitations are blocking for us.

**Comment by oehme** [comment] 2018-03-12 13:49
Gradle 4.6 has added support for constraints and BOMs, see the [release notes](https://docs.gradle.org/4.6/release-notes.html#dependency-constraints-for-transitive-dependencies) for more info.

 I'm closing this issue because there is now a way to have recommended versions work together with composites. Composites won't work with resolution rules, but that's unlikely to change and resolution rules will probably be removed in the long term, as we are adding better, more declarative APIs for their use cases.

**Closed by oehme** 2018-03-12 13:49 UTC
Labels: a:feature, from:contributor, in:composite-builds

**Comment by vehovsky** [comment] 2018-03-12 14:26
@oehme well kind of, using that feature is not generating correct pom tough.. #4543

**Comment by rhoughton-pivot** [comment] 2019-02-22 18:08
@oehme Sorry to resurrect an old thread, but what are the "better, more declarative APIs" that will be replacing Resolution Rules?

**Comment by oehme** [comment] 2019-02-22 19:04
The [user guide](https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html#sec:bom_import) gives a good overview of them now.

**Comment by rupebac** [comment] 2019-06-14 10:56
> Gradle 4.6 has added support for constraints and BOMs, see the [release notes](https://docs.gradle.org/4.6/release-notes.html#dependency-constraints-for-transitive-dependencies) for more info.
> 
> I'm closing this issue because there is now a way to have recommended versions work together with composites. Composites won't work with resolution rules, but that's unlikely to change and resolution rules will probably be removed in the long term, as we are adding better, more declarative APIs for their use cases.

Correct me if I am wrong, but there is still no way to share exclusions of transitive dependencies, even if they are defined in a platform and imported. So if composite builds are not handling resolution rules, how should that be done?

**Comment by alexei-osipov** [comment] 2021-12-15 21:58
> The [user guide](https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html#sec:bom_import) gives a good overview of them now.

The link is broken.

Is that true that there still no any workaround for using composite builds with spring-dependency-management plugin?
