### ISSUE TITLE
Option for auto cleanup of ~/.gradle/daemon/daemon-<pid>.log

### ISSUE THREAD

**Issue by gavenkoa** [gradle/gradle#8795] opened 2019-03-16 22:27 UTC
```
bash# du -s -m ~/.gradle/daemon
3040    /cygdrive/c/home/.gradle/daemon

bash# ls ~/.gradle/daemon/*/daemon*.log | wc -l
1575

bash# ls ~/.gradle/daemon/4.6/daemon*.log | wc -l
774
```

It is after 1 year of regular developer work.

It is inefficient to shift cleanup actions to end-users. I don't care about daemon's system.out

**Comment by gavenkoa** [comment] 2020-08-08 20:24
5 GiB of trash:

```
bash# pwd
/cygdrive/c/home/.gradle/daemon

bash# du -s -m *
1       5.1.1
78      5.2.1
2       5.6.2
6       6.2.1
5448    6.3
```

Why should user take care about cleaning of `daemon-*.out.log`?

**Comment by jjohannes** [comment] 2021-04-14 08:08
The problem is essentially the same as described in #2688 . Please upvote/comment/follow there. Closing as duplicate of #2688.

**Closed by jjohannes** 2021-04-14 08:08 UTC
