### ISSUE TITLE
Unable to disable Gradle Daemon after upgrading gradle version to 8.1

### ISSUE THREAD

**Issue by Mrkchv** [gradle/gradle#25548] opened 2023-06-29 08:55 UTC
### Expected Behavior

Gradle Daemon doesn't start when adding `org.gradle.daemon=false` to the global `gradle.properties` file and setting the `JAVA_TOOL_OPTIONS` environment variable with arguments identical to the project's `gradle.properties`.

### Current Behavior

We get a message on CI: "To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/8.1./userguide/gradle_daemon.html#sec:disabling_the_daemon. Daemon will be stopped at the end of the build".

Periodically, the assembly fails with an error: "org.gradle.launcher.daemon.client.DaemonDisappearedException: Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)".

### Context (optional)

We run the assembly on our CI in a docker container and everything worked on gradle version 8.0.2. We don't need Gradle Daemon, since the assemblies are isolated from each other. I also tried to use the `GRADLE_OPTS` and `JAVA_OPTS` environment variables inside our docker image, but it didn't help.

### Steps to Reproduce

Run gradle command inside a docker container with Gradle 8.1+

### Gradle version

8.1

**Comment by ov7a** [comment] 2023-07-03 08:30
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #25272 

Please add your use case and 👍 to that issue.

--- 

Relates to
* #24587

**Closed by ov7a** 2023-07-03 08:30 UTC
Labels: a:bug, to-triage
