### ISSUE TITLE
Task Input Annotated with “@SkipWhenEmpty @InputFiles” Ignores Non-Existent Files

### ISSUE THREAD

**Issue by cspurk** [gradle/gradle#30837] opened 2024-10-08 08:09 UTC
### Current Behavior

A task input annotated with `@SkipWhenEmpty @InputFiles` which is configured with a non-existent file leads to a task status of `NO-SOURCE`. At least that’s the behavior for Gradle 8.10.2.

For Gradle 7.6.2, the task is run.

### Expected Behavior

Gradle 7.6.2 behaves as expected. Gradle 8.10.2 should behave as Gradle 8.10.2.

### Context (optional)

In my use case, the input file paths originally come from a user-provided configuration file. The task is expected to validate both that the configured files exist and that they have a specific content.

With the current behavior in Gradle 8.10.2, there is no way to distinguish between “no paths configured at all” from “only non-existent paths configured”.

### Self-contained Reproducer Project

Given an empty `settings.gradle` and the following `build.gradle`:

```groovy
tasks.register('foo') {
    inputs.files(provider { 'non_existent.txt' }).skipWhenEmpty()
    doLast {
        println('Done.')
    }
}
```

If you run `./gradlew --console=verbose foo` with Gradle 8.10.2, then you’ll get:

```
> Task :foo NO-SOURCE
```

Running the same with Gradle 7.6.2 results in the following instead:

```
> Task :foo
Done.
```

### Gradle version

8.10.2 (vs. 7.6.2)

### Your Environment (optional)

```
------------------------------------------------------------
Gradle 8.10.2
------------------------------------------------------------

Build time:    2024-09-23 21:28:39 UTC
Revision:      415adb9e06a516c44b391edff552fd42139443f7

Kotlin:        1.9.24
Groovy:        3.0.22
Ant:           Apache Ant(TM) version 1.10.14 compiled on August 16 2023
Launcher JVM:  11.0.24 (Ubuntu 11.0.24+8-post-Ubuntu-1ubuntu322.04)
Daemon JVM:    /usr/lib/jvm/java-11-openjdk-amd64 (no JDK specified, using current Java home)
OS:            Linux 6.8.0-45-generic amd64
```

```
------------------------------------------------------------
Gradle 7.6.2
------------------------------------------------------------

Build time:   2023-06-30 15:42:51 UTC
Revision:     dab132169006b16e7ada4ab2456e0c9d6415b52a

Kotlin:       1.7.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.24 (Ubuntu 11.0.24+8-post-Ubuntu-1ubuntu322.04)
OS:           Linux 6.8.0-45-generic amd64
```

**Comment by abstratt** [comment] 2024-10-09 13:25
This issue will be closed as a duplicate of

* #2919

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

As per the documentation for [\@SkipWhenEmpty](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/SkipWhenEmpty.html), it actually describes the behavior you are seeing now (NO-SOURCE) as correct.

Regarding your use case, it should be consideered in the context of #2919, and these comments should be the most relevant:

https://github.com/gradle/gradle/issues/2919#issuecomment-328750267

https://github.com/gradle/gradle/issues/2919#issuecomment-981097984

**Closed by abstratt** 2024-10-09 13:25 UTC
Labels: a:bug, closed:duplicate, to-triage

**Comment by cspurk** [comment] 2024-10-09 14:02
Thanks for checking this issue, @abstratt! However, I don’t agree that his is a duplicate of #2919:

* This ticket specifically talks about a _collection_ of input files: see also `@InputFiles` in the description and the equivalent `inputs.files(…)` (plural!) usage in the reproducer. Such a file collection can contain an arbitrary number of files, i.e., `@InputFile` or the equivalent `inputs.file(…)` (singular!) from #2919 are different.
* More importantly, #2919 request a new feature for supporting the easier handling of non-existent files as _optional_ task inputs. This ticket talks about _non-optional_ task input files which are currently silently ignored when they don’t exist.

> As per the documentation for [@SkipWhenEmpty](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/SkipWhenEmpty.html), it actually describes the behavior you are seeing now (NO-SOURCE) as correct.

I’m afraid, I don’t agree with this either. The docs don’t mention _non-existent_ files at all. The docs only talk about “an empty `FileCollection`” – which I’d consider `files([])` to be but not `files('non_existent.txt', 'neither_existent.txt')`.

Or is “empty `FileCollection`” maybe defined somewhere as a `FileCollection` that only contains non-existent (or no) files?
