### ISSUE TITLE
Gradle Central Repository: Plugin [id: 'org.springframework.boot', version: '2.3.2.RELEASE'] was not found

### ISSUE THREAD

**Issue by devthepenguin** [gradle/gradle#15165] opened 2020-11-14 11:43 UTC
### Expected Behavior

_Gradle Build should be successful_; All the necessary dependencies are installed and the required extensions are already enabled which leaves no reason for the build to fail.

### Current Behavior

**After working in the _vs code_ workspace for a while**, Gradle fails to build repeatedly and is unable to find plugin(s) including the spring-boot plugin despite all necessary extensions and dependencies being installed.

NOTE- This issue occurs after working for a while and not immediately.

**build.gradle file**

![Screenshot 2020-11-14 002458](https://user-images.githubusercontent.com/52373288/99145809-bac01600-2697-11eb-8958-9a0dc32447f1.png)

### Context

Building an application for Spring Security using **Spring-Initializr** as well as cloning the starter. Neither of the methods allows for a successful build.

`git clone` [https://github.com/spring-guides/gs-securing-web.git](url)

![Screenshot 2020-11-14 023349](https://user-images.githubusercontent.com/52373288/99145945-5c943280-2699-11eb-8685-5efe358f4ed2.png)

### Steps to Reproduce 

1. `.\gradlew clean`
2. `.\gradlew --refresh-dependencies`
3. Enable offline builds for gradle

![Screenshot 2020-11-14 163113](https://user-images.githubusercontent.com/52373288/99146263-6703fb80-269c-11eb-98c9-749d4212c4d8.png)

4. Issue at spring-boot repo [https://github.com/spring-projects/spring-boot/issues/24155#issuecomment-727160966](url)

Minimal Reproduction of the sample: [gs-securing-web.zip](https://github.com/gradle/gradle/files/5540582/gs-securing-web.zip)

### Your Environment

**Visual Studio Code Version**
Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Build scan URL:

![Screenshot 2020-11-14 163233](https://user-images.githubusercontent.com/52373288/99145820-d1ff0380-2697-11eb-8e08-ffd5da9cba3c.png)

**Comment by ljacomet** [comment] 2020-11-16 10:28
Currently the Gradle plugin repository serves its artifacts from a Bintray repository. There have been Bintray outages recently that could cause this issue.

Can you confirm that you get the problem even when Bintray has no issue?

**Comment by devthepenguin** [comment] 2020-11-16 17:19
> Currently the Gradle plugin repository serves its artifacts from a Bintray repository. There have been Bintray outages recently that could cause this issue.
> 
> Can you confirm that you get the problem even when Bintray has no issue?

Yes, I checked the Bintray Status. It seems like there have been recent outages but not during the time the most recent builds were performed (including right now), the problem persists.

**Comment by ljacomet** [comment] 2020-11-20 16:18
Looking deeper into your report, you seem to be attempting to run Gradle in offline mode  without doing a full build first.,
Running `./gradlew --refresh-dependencies` will not download all the dependencies since no tasks but `help` are executed, which means the project dependencies will not be fetched for example.

We have not seen other reports of such behavior so there is a very high chance this is setup or environmental.

**Comment by devthepenguin** [comment] 2020-11-21 14:15
Probably it can be environmental, I am able to make projects on Android Studio. Gradle builds successfully without throwing any exceptions. I'm unable to build it on vs code and eclipse.

**Comment by jbartok** [comment] 2021-11-05 09:46
We are unfortunately not able to reproduce the problem. We are going to close the issue. If you can provide more specific steps to use, then we can reopen it later.

**Closed by jbartok** 2021-11-05 09:46 UTC
Labels: in:dependency-management, a:bug
