### ISSUE TITLE
Basic gradle project java meta inf is not loading

### ISSUE THREAD

**Issue by Danjhop4** [gradle/gradle#26191] opened 2023-08-27 09:50 UTC
### Current Behavior

When I I make a project that use gradlew.bat init the the meta inf does not load so the jvm 17 can’t load it appears just be a version info only

### Expected Behavior

The meta inf should have the main class info
And the jar should load when opened

### Context (optional)

Trying to make a basic jar using gradle init since I have only ever used other gradle based tool kits

### Steps to Reproduce

Use gradlew.bat init basic project java , Kitlin config
Java 17 any package name
And build

### Gradle version

Lastest

### Your Environment (optional)

Windows 11

**Comment by Danjhop4** [comment] 2023-08-27 13:05
My grades.bat is rename grade.bat and it uses a portable java so I had to mod the bat a bit

**Comment by jbartok** [comment] 2023-09-04 08:27
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

**Comment by Danjhop4** [comment] 2023-09-06 09:23
I can like a zip with my modded version just replace gradle.bat with the code with a stock version

**Comment by Danjhop4** [comment] 2023-09-06 09:42
Just remove everything but gradle.bat and the wrapper 
Newest version 
make a batch file call init with gadlew.bat init 
Project type 2 app type java build script Kotlin java 17

**Comment by jbartok** [comment] 2023-09-06 12:05
We need a proper reproducer, as described in my previous comment.

**Comment by Danjhop4** [comment] 2023-09-08 09:54
I don’t think that possible

**Comment by Danjhop4** [comment] 2023-09-08 09:55
Plus that tool uses the wrong gradle version

**Comment by Danjhop4** [comment] 2023-09-08 09:57
> We need a proper reproducer, as described in my previous comment.

That is the wrong version it’s way out of date

**Comment by Danjhop4** [comment] 2023-09-08 09:58
The manifest is just version info

**Comment by Danjhop4** [comment] 2023-09-08 09:58
I followed a online info and removed unneeded files

**Comment by Danjhop4** [comment] 2023-09-08 09:59
You keep demanding I use a different template then the one I have the problem with

**Comment by Danjhop4** [comment] 2023-09-08 10:00
I just used what it give me

**Comment by ov7a** [comment] 2023-09-08 12:08
@Danjhop4 Hey, without a reproducer, we can't help you. Perhaps you can get in touch with our community at https://help.gradle.org.

**Comment by Danjhop4** [comment] 2023-09-09 09:33
You can you won’t

**Comment by Danjhop4** [comment] 2023-09-09 09:35
the problem is with the built in template that is version based

**Comment by Danjhop4** [comment] 2023-09-09 09:38
Reproduction is possible only without that template

**Comment by Danjhop4** [comment] 2023-09-09 09:39
Don’t just close this I will remake it or at least give me a work around

**Comment by Danjhop4** [comment] 2023-09-09 09:42
I am using gradle 8.3 not 8.1.1

**Comment by Danjhop4** [comment] 2023-09-09 09:43
> @Danjhop4 Hey, without a reproducer, we can't help you. Perhaps you can get in touch with our community at https://help.gradle.org.

@ov7a wrong version I use 8.3 not 8.1.1 and it is generated by gradle itself so a template is usless

**Comment by Danjhop4** [comment] 2023-09-09 10:00
I made a GitHub with a template and use the batch file called init and read settings.txt to set it it up then use build.bat then run it with a command line jre
https://github.com/Danjhop4/Gradle-template/tree/1.20

**Comment by ov7a** [comment] 2023-09-11 06:36
I can't reproduce the issue with the information you provided in a reproducer. My guess is that there is some problem with your environment.

Note that the purpose of templates is to create something easily runnable. It's not to restrain you or something. You can change everything, including gradle/java versions and Readme's to provide the instructions.

***

Note that Github issue is not a chat, so please refrain from creating noise messages.

Just so you know, this repository is a subject of [CoC](https://gradle.org/conduct/). Some of your messages might be treated as a violation of it.

**Comment by Danjhop4** [comment] 2023-09-13 09:14
https://discord.com/channels/@me/1007343453669171353/1151191735662301194

**Comment by ov7a** [comment] 2023-09-13 09:39
So the only change you have is `gradle.bat`, which hardcodes the `$JAVA_EXE` to `C:\Users\Danie\OneDrive\Desktop\runtime\java-runtime-gamma\windows-x64\java-runtime-gamma\bin\java.exe`. Clearly I don't have it locally. Even if I had, I don't see how it is a Gradle problem, not an environment one. 

This is not a proper reproducer. It does not show a problem with Gradle.

**Comment by Danjhop4** [comment] 2023-09-13 12:19
Why do I have to use that template when my one is fine  
It was made by gradle anyways

**Comment by Danjhop4** [comment] 2023-09-13 12:26
Just adds a layer of randomness that I can’t control

**Comment by Danjhop4** [comment] 2023-09-13 12:27
It’s the bare minimum I needed to be able to compile at all

**Comment by ov7a** [comment] 2023-09-13 13:04
Sorry, I don't see how this is constructive dialogue.

We asked for a proper reproducer multiple times. You didn't provide any.

Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

I'm closing this issue as invalid. I would treat any further unconstructive messages as spam.

**Closed by ov7a** 2023-09-13 13:04 UTC

**Comment by Danjhop4** [comment] 2023-09-14 09:13
You demand I use that template even thought I would have to copy my project files anyways so it pointless and you can't even tell me why other then to use it
________________________________

**Comment by big-guy** [comment] 2023-09-14 19:56
@Danjhop4 please adhere to our [code of conduct](https://gradle.org/conduct/) and assume good faith from us. We want to help if we can, but it's very hard for us to help if we cannot reproduce the problem you're describing.

If you can reproduce the problem using our template or creating your own, you're welcome to open an issue about that. 

From what you've posted so far, I believe it's something in your environment.

**Comment by Danjhop4** [comment] 2023-09-15 09:04
> @Danjhop4 please adhere to our [code of conduct](https://gradle.org/conduct/) and assume good faith from us. We want to help if we can, but it's very hard for us to help if we cannot reproduce the problem you're describing.
> 
> If you can reproduce the problem using our template or creating your own, you're welcome to open an issue about that.
> 
> From what you've posted so far, I believe it's something in your environment.

That’s unavoidable sadly they won’t accept my template

**Comment by Danjhop4** [comment] 2023-09-15 09:16
I am doing what I can it's you that's not doing what you could I produced a minimum example that gradle produced the meta inf manifest is broken only used gradle for minecraft mods so that would be fine normally
________________________________

**Comment by Danjhop4** [comment] 2023-09-20 13:14
Gradle produced the structure of the project for me

**Comment by Danjhop4** [comment] 2023-09-20 13:17
build how ever you want I use build.bat

**Comment by Danjhop4** [comment] 2023-09-21 16:47
[gradle_basic.zip](https://github.com/gradle/gradle/files/12689112/gradle_basic.zip)

**Comment by Danjhop4** [comment] 2023-09-21 16:48
Should work now idk why it did that

**Comment by ov7a** [comment] 2023-09-22 08:35
As before, this reproducer does not demonstrate the problem: there are no meaningful changes apart from bat files. 

This must be a problem with your environment.

**Comment by Danjhop4** [comment] 2023-09-22 15:17
How could it be my java gradle makes the jar it’s gradle

**Comment by Danjhop4** [comment] 2023-09-22 15:19
I had gradle make the project

**Comment by Danjhop4** [comment] 2023-09-22 15:44
![](https://github.com/Danjhop4/Gradle-template/blob/1.20/error.png)

**Comment by Danjhop4** [comment] 2023-09-22 15:47
I don’t know what you want if what I have does not count  @ov7a  your not making any sense jre not jdk the only other thing I use gradle for mods that probably are not effected by the bug

**Comment by Danjhop4** [comment] 2023-09-22 15:51
[build.zip](https://github.com/gradle/gradle/files/12702478/build.zip)

**Comment by Danjhop4** [comment] 2023-09-22 15:52
That has a jar that’s been built and the error code since GitHub decided that a png was an error

**Comment by Danjhop4** [comment] 2023-09-22 16:04
It’s overriding the hand make meta inf manifest nope this is gradle

**Comment by Danjhop4** [comment] 2023-09-22 17:35
I used gradle to make that project that’s how minimal reproducible examples work

**Comment by Danjhop4** [comment] 2023-09-23 16:01
Do you need a jdk or just a jre

**Comment by Danjhop4** [comment] 2023-09-23 16:25
The problem is with the out put jar it’s not some you need new code for

**Comment by Danjhop4** [comment] 2023-09-23 16:43
@ov7a you keep telling me it does not count or it’s my runtime it works for other jars just not jars produced by gradle yes I tried writing the defective bit by hand gradle overrides it

**Comment by ov7a** [comment] 2023-09-25 06:51
> Do you need a jdk or just a jre

JDK is required for Java source code compilation.

**Comment by Danjhop4** [comment] 2023-09-25 16:04
Tried that same thing also wrote a meta inf manifest by hand at this point it’s gradle and it was openjdk not Microsoft jdk the one minecraft uses

**Comment by Danjhop4** [comment] 2023-09-26 09:35
[gradle_basic.zip](https://github.com/gradle/gradle/files/12725753/gradle_basic.zip)
It failed first time

**Comment by Danjhop4** [comment] 2023-09-30 16:34
I don’t get how it’s not working right I used the built in project settings
