### ISSUE TITLE
Error when creating a new android project

### ISSUE THREAD

**Issue by featlast** [gradle/gradle#29701] opened 2024-06-26 14:49 UTC
### Current Behavior

![image](https://github.com/gradle/gradle/assets/66761042/d0106d8c-8083-48da-9356-8e10863a8bb8)

### Expected Behavior

that allows you to create the project without restrictions

### Steps to Reproduce

Caused by: java.io.UncheckedIOException: Could not move temporary workspace (C:\Users\USUARIO\Desktop\APPSJETPACkCOMPOSE\pruebagradle.gradle\8.7\dependencies-accessors\dcbcd87108cec70bb467e05d5172bee8efb944af-8a047ac5-58a0-4750-b4ff-819bcb7c25e2) to immutable location

Caused by: java.nio.file.AccessDeniedException: C:\Users\USUARIO\Desktop\APPSJETPACkCOMPOSE\pruebagradle.gradle\8.7\dependencies-accessors\dcbcd87108cec70bb467e05d5172bee8efb944af-8a047ac5-58a0-4750-b4ff-819bcb7c25e2 ->

### Gradle version

8.7

### Your Environment (optional)

Windows 11 Pro

**Comment by ov7a** [comment] 2024-06-27 09:21
This issue will be closed as a duplicate of

* #28475

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

**Closed by ov7a** 2024-06-27 09:21 UTC
Labels: a:bug, to-triage
