### ISSUE TITLE
[wrapper] fails when upgraded in a Jenkins job in Debian using '-Djsse.enableSNIExtension=false'

### ISSUE THREAD

**Issue by fhuberts** [gradle/gradle#1435] opened 2017-02-20 22:07 UTC
The gradle wrapper in my jenkins job can't download an upgraded version.
I just upgraded the wrapper from 3.3 to 3.4 (and I've seen it before) and this is what I get:

```
Downloading https://services.gradle.org/distributions/gradle-3.4-bin.zip

Exception in thread "main" javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1914)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:279)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:273)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1472)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:213)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:913)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:849)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1033)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1342)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1369)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1353)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2457)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1601)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:60)
	at org.gradle.wrapper.Download.download(Download.java:45)
	at org.gradle.wrapper.Install$1.call(Install.java:62)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:385)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:326)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:126)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1454)
	... 20 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:196)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:268)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:380)
	... 26 more
```

### Expected Behavior

a normal download

### Current Behavior

the stacktrace above, and thus a failed job

### Context

I have this issue on all my Jenkins servers:
- Fedora 25 x64
- Debian Jessie x64
- Debian Jessie x32

Jenkins does not run as a logged in used.

When I run the job as a logged-in jenkins then it works ok, so there is something in the environment that the wrapper depends on.

### Steps to Reproduce (for bugs)

trivial

### Your Environment

 * Build scan URL: 

n.a.

**Comment by fhuberts** [comment] 2017-02-20 22:11
Ah correction: my Fedora Jenkins works fine. It's the Debian servers that have this issue.

**Comment by bmuschko** [comment] 2017-02-20 23:15
Looks like an issue on your machine or your environment with SSL handshaking. Check out these links to get it fixed:

- http://serviceorientedarchitect.com/using-gradle-wrapper-behind-a-proxy-server-with-self-signed-ssl-certificates/
- http://stackoverflow.com/questions/29584328/gradlew-bat-and-gradlew-sslhandshakeexception

**Comment by bmuschko** [comment] 2017-02-23 22:40
@fhuberts Did you solve your issue?

**Comment by fhuberts** [comment] 2017-03-01 09:29
Thanks, I had looked at those links before and they didn't solve the issue for me.
Like I said, there seems to be a difference in the environment that is tripping up gradle.

I've attached the diff in the environment.
[envdiff.txt](https://github.com/gradle/gradle/files/810215/envdiff.txt)

**Comment by fhuberts** [comment] 2017-03-07 08:23
Found it!

Passing '-Djsse.enableSNIExtension=false' to the gradle wrapper when its version has changed and it must download the new version makes the whole thing fail.

On my Fedora machine it makes no difference, but on my Debian machine I must remove the '-Djsse.enableSNIExtension=false' argument

**Comment by eriwen** [comment] 2017-04-13 17:49
Great. It sounds like this is solved.

**Comment by fhuberts** [comment] 2017-04-13 19:45
Ahem, wouldn't it be nice to investigate why gradle trips up on that?
I have that option set for a very good reason obviously and I'd rather not lose it.

**Comment by eriwen** [comment] 2017-04-13 20:14
@fhuberts We can keep it open if you think there's a good chance that someone from the community will investigate. I don't think this would rise to be become a top priority for us in the short or medium-term

**Comment by oehme** [comment] 2017-09-15 17:15
Closing as there has been no further insight here. Feel free to add more details if this is actually an issue caused by Gradle (as opposed to a JRE issue for instance).

**Closed by oehme** 2017-09-15 17:15 UTC
Labels: a:question, affects-version:3.4, from:contributor, help-wanted, in:core
