### ISSUE TITLE
Cannot read password from Console when using Gradle daemon

### ISSUE THREAD

**Issue by sdavids** [gradle/gradle#2091] opened 2017-05-19 10:10 UTC
### Expected Behavior
```
def password = System.console().readPassword("PGP Private Key Password: ")
```
should work with `org.gradle.daemon=true`.

### Current Behavior

`Cannot invoke method readPassword() on null object`

### Context

https://docs.gradle.org/current/userguide/signing_plugin.html#sec:signatory_credentials

Related issue: https://issues.gradle.org/browse/GRADLE-3292

**Comment by bmuschko** [comment] 2017-05-19 10:52
Thanks for reporting. This is a duplicate of https://github.com/gradle/gradle/issues/1251. Please vote on the over there.

**Closed by bmuschko** 2017-05-19 10:52 UTC

**Comment by sdavids** [comment] 2017-05-19 10:54
You might want to at least update the doc ( https://docs.gradle.org/current/userguide/signing_plugin.html#sec:signatory_credentials ) in the meantime.

**Comment by bmuschko** [comment] 2017-05-19 10:58
@sdavids That's a good point. I wasn't aware of the fact that this code is part of an example. Would you be interested in contributing a hint in the documentation?
