### ISSUE TITLE
Crash when manually creating BuildService in two modules

### ISSUE THREAD

**Issue by cmelchior** [gradle/gradle#18821] opened 2021-10-29 14:17 UTC
I'm currently working on making a custom plugin Configuration Cache compatible. As part of that, I'm creating a BuildService. Due to other constraints, I need to manually create the service inside the configuration phase. But applying the same plugin in two different modules, result in Gradle crashing when I try to retrieve the session the second time. 

### Expected Behavior
I expect to be able to access my custom BuildService inside a plugins `apply` method, even if the same plugin is applied to multiple submodels

### Current Behavior
When trying to retrieve the service the second time, it crashes with:

```
* What went wrong:
An exception occurred applying plugin request [id: 'io.realm.kotlin']
> Failed to apply plugin 'io.realm.kotlin'.
   > class io.realm.gradle.analytics.AnalyticsService$Inject cannot be cast to class io.realm.gradle.analytics.AnalyticsService (io.realm.gradle.analytics.AnalyticsService$Inject is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @36c6df8f; io.realm.gradle.analytics.AnalyticsService is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @7568675b)
```

### Context
This currently make it impossible to 

### Steps to Reproduce 

Creating a plugin with this implementation and apply it to two different modules. Our setup looks like this:
```
/test/
/test/base (module 1)
/test/sync (module 2)
```

```
@Suppress("unused")
open class RealmPlugin : Plugin<Project> {

    @Inject
    public open fun getBuildEventsRegistry(): BuildEventsListenerRegistry {
        TODO("Will be replaced")
    }

    override fun apply(project: Project) {
        project.pluginManager.apply(RealmCompilerSubplugin::class.java)

        // Register the service
        val serviceProvider: Provider<AnalyticsService> = project.gradle.sharedServices.registerIfAbsent(
            "realm-analytics",
            AnalyticsService::class.java
        ) { /* Do nothing */ }
        getBuildEventsRegistry().onTaskCompletion(serviceProvider)
        project.logger.log(LogLevel.WARN, "Create service: ${serviceProvider.isPresent}")
        val analyticsService: AnalyticsService = serviceProvider.get() // This crashes when 2nd module is configured
        project.logger.log(LogLevel.WARN, "Service created")
    }

}
```
### Your Environment
https://gradle.com/s/fj5oc2lgl3nh2

**Comment by bamboo** [comment] 2021-12-07 14:39
Duplicate of #17559

**Comment by abstratt** [comment] 2023-03-17 20:29
@bamboo Any reason not to close this since, as you said, it is a duplicate of #17559 (and have that one on our board instead)?

**Comment by bamboo** [comment] 2023-03-17 21:13
Closing as duplicate of https://github.com/gradle/gradle/issues/17559

**Closed by bamboo** 2023-03-17 21:13 UTC
Labels: a:bug, @configuration-cache, closed:duplicate, in:build-services
