### ISSUE TITLE
Accept Groovy performance regressions

### ISSUE THREAD

**Issue by rieske** [gradle/gradle#15566] opened 2020-12-14 15:04 UTC
Gradle currently uses Groovy 2.5.x line which is no longer receiving feature updates.
Upgrade to Groovy 3 to benefit from the latest language features.

This is a prerequisite for Gradle to be able to run on JDK16.

Areas to investigate
- [x] LazyTest
- [x] GroovyDoc tests (due to classpath)
- [x] CodeNarcCompilationClasspathIntegrationTest
- [x] IncrementalGroovyProjectBuildIntegrationTest
- [x] BuildSrcSpockIntegrationTest
- [x] Init tests (GroovyLibraryInitIntegrationTest, ...)
- [x] GroovyCrossCompilationIntegrationTest
- [x] Look into problems using groovybuilder and init scripts
- [x] Groovy Parser issues (ModelDslRuleInputDetectionIntegrationSpec, StronglyTypedConfigurationAttributesResolveIntegrationTest/StringConfigurationAttributesResolveIntegrationTest (@big-guy looking into those)
-- https://github.com/apache/groovy/pull/1485 (to be in `3.0.8`)
- [x] Upgrade to a wrapper built on master
- [x] Look into performance regressions (`BuildSrcApiChangePerformanceTest` and `JavaFirstUsePerformanceTest`)

**Comment by bmuskalla** [comment] 2021-02-19 12:19
Discussion items from @jjohannes and @big-guy 

> I think we're no longer testing the same thing in some of the TestKit integration tests. e.g., whenever we've added JUnit4 to a test that uses Spock 2.0, the Spock 2 tests won't be executed. see GradleRunnerConventionalPluginClasspathInjectionEndUserIntegrationTest.  I think there are others like this, so we need to check every place where we're mixing Spock 2 and JUnit 4. This can happen after merging.

Yes, I think we should always use Junit platform APIs (i thought i switched all tests to use e.g. `@TempDir` instead of getting Junit4 on the classpath but I might have missed some in the beginning.

> I'm also not convinced that we have good coverage for these scenarios:
> 1. A Gradle 6 TestKit with Spock 1/Groovy 2 running tests with Gradle 7 with and without withDebug(...)
> 2. A Gradle 7 TestKit with Spock 2/Groovy 3 running tests with Gradle 6 with and without withDebug(...)
> 3. A Gradle 7 TestKit with Spock 2/Groovy 3 running tests with Gradle 7 with and without withDebug(...)
> It looks like we may have lost coverage at some point where we're only running tests against the newest and oldest versions of Gradle:
> https://ge.gradle.org/scans/tests?search.relativeStartTime=P1D&search.timeZoneId=America/New_York&tests.container=org.gradle.testkit.runner.GradleRunnerGradleVersionIntegrationTest&tests.sortField=FAILED&tests.unstableOnly=true
> I don't think this is related to the Spock 2 upgrade.  I don't see many tests running back in November either.
> This is important to run down, but it's not blocking for merging and the milestone.

Other general comments:

> - The exclude module: 'groovy-all' is useless in all of the tests that use Spock 2. I think this was already the case with Spock 1.3
This has been fixed in the PR

> - I wonder if we should take a pass at all of the integ tests that use Spock and make them use JUnitPlatform consistently (vs sprinkling Junit4 dependencies everywhere).
I'll take care after merging to follow up on this.

> - We're adding several Groovy modules in a piecemeal fashion. Are there other modules we should be adding to have a more "complete" Groovy distribution packaged in Gradle?  e.g., would someone using Groovy 3 expect to have classes in groovy-nio available? Here's the "groovy-all" list of all modules: https://mvnrepository.com/artifact/org.codehaus.groovy/groovy-all/3.0.7

Yeah, I was back and forth on this. For our modules, we should target individual module as dependencies. What we expose as `localGroovy` should contain all modules that used to be in `groovy-all`. Right now, I only added them on demand for our uses but agreed, it should contain all of them. Especially because it makes it really funny when you use extension methods that are suddenly gone due to a missing module not contributing the extension module.

> We need to add the Groovy 3 update to the release notes and release features/highlights for the milestone. Upgrade guide notes can come second or be very rough for the milestone.
> Do you have a build showing the performance regressions? I think we should accept the regression and look into it, but the more disruptive change are all of the Groovy 2 -> 3 quirky changes.
Here is on ad-hoc build with flames for the buildSrc one: https://builds.gradle.org/buildConfiguration/Gradle_Master_Util_Performance_AdHocPerformanceScenarioLinux/41486086?buildTab=artifacts

**Comment by bmuskalla** [comment] 2021-02-24 11:01
Working through the missing modules on the classpath, I've added a few more that we do know are used in practice. Here is a list of modules I've left out now (which used to be part of `groovy-all`) but I don't believe they really belong on the classpath by default. @big-guy WDYT? Do you think we can risk pulling those from the classpath (e.g. using `localGroovy()`)?
```
groovy-cli-picocli
groovy-docgenerator
groovy-groovysh
groovy-jmx
groovy-jsr223
groovy-macro
groovy-servlet
groovy-swing
groovy-test-junit5
groovy-testng
```

**Comment by jjohannes** [comment] 2021-02-24 12:58
My take at this is that we should only add what Gradle core/Groovy DSL needs. In general, we should aim for only adding what is really needed to the distribution for various reasons. If users need more, we should clarify the use case. With my, possible too limited, knowledge they should be able to add what is missing by adding the corresponding dependency to the (buildscript) classpath.

If there are use cases that cannot be solved like that we should clarify first and have a test case for it, before adding anything else.

**Comment by jjohannes** [comment] 2021-02-24 13:06
I added a not to the `localGroovy()` item in the description. Part of the solution could also be to add version constraints for all Groovy modules that are not part of Gradle to `localGroovy()`. Then you can add additional dependencies without version and the version will automatically fit the one in Gradle.

**Comment by breskeby** [comment] 2021-02-24 13:11
This approach will break a lot of builds I would assume. My understanding is that upgrading to 7.0 should „just work“. By changing the groovy default behavior you intentionally break things for no reason without having the users given a heads up on this. At least this needs to be well documented. I would assume that the average gradle user doesn’t even know which library he needs to import to get the previous behavior back. Just my 2 cents.

**Comment by jjohannes** [comment] 2021-02-24 13:23
>  My understanding is that upgrading to 7.0 should „just work“

Well it is a major upgrade and it breaks certain things. Of course we try to avoid that as much as possible.

> This approach will break a lot of builds I would assume.

Can you put some weight behind that assumption? I for one don't think many builds will break (I might be wrong). What we have covered in our tests did not break. What does "many" mean here? Could you share the use case for "previous behaviour" that do break? As I wrote, we should have the concrete use cases and pin them down in some kind of test.

Whatever we do, it's a compromise as Groovy itself might have removed some classes etc. It's always an issue when we update a dependency of Gradle that is not hidden from the API.

**Comment by breskeby** [comment] 2021-02-25 11:00
I don't have hard numbers, but from my experience, especially the Date format extension is quite often used to format file timestamps etc. My understanding was that Gradle should break as little builds as possible and therefore would aim for shipping as close to pre 7.0 behaviour as possible. From reading your comment I understand that my assumption is wrong on this.

**Comment by breskeby** [comment] 2021-02-25 11:06
How would I currently workaround this issue with 7.0-milestone-2? I put the groovy nio module on the buildSrc classpath via the `runtimeOnly` configuration:

```
  runtimeOnly 'org.codehaus.groovy:groovy-nio:3.0.7'
```

However this doesn't solve the issue we see and still get 

```
* What went wrong:
Execution failed for task ':docs:buildRestTests'.
> No signature of method: sun.nio.fs.UnixPath.newPrintWriter() is applicable for argument types: (String) values: [UTF-8]
```

The task implementation that causes the error is located in `buildSrc/src/main/groovy`.

**Comment by bmuskalla** [comment] 2021-02-25 12:37
Did you try to enable info logging? I remember the extension loading mechanism of groovy actually logs when it can't load certain extensions. And maybe you're coming too late for it to be picked up. I've pushed a [PR to fix this in Gradle ](https://github.com/gradle/gradle/pull/16304)itself (the main problem was that it wasn't included in the dist even though it should've been)

**Comment by ice1000** [comment] 2021-03-05 05:02
Does upgrading to groovy 3 bring improvements other than new language features (such as performance)? I know there are some downgrades in performance, but I only see discussion on downgrades and I wish to learn about the enhancements from users' perspective.

**Comment by bmuskalla** [comment] 2021-03-09 12:03
We'll summarize the changes in the release/upgrade notes. Indeed, for certain (not so common) scenarios, the Groovy parser has some performance regressions but the Groovy folks are actively working on getting those fixed. One of the main drivers for Gradle to upgrade is the JDK 16 support.

**Comment by bmuskalla** [comment] 2021-03-10 15:56
The performance part of this is done, we'll be using the new Groovy3 parser for Gradle 7. #16361 track the release notes for Groovy3.

**Closed by bmuskalla** 2021-03-10 15:56 UTC
Labels: @core, a:chore, a:feature, from:member
