### ISSUE TITLE
Composite/includeBuild replacing module with project breaks dependencies in publications

### ISSUE THREAD

**Issue by snazy** [gradle/gradle#21022] opened 2022-06-16 07:20 UTC
Scenario:
```
build A
+--- includesBuild "nessie"
     + --- build "nessie"
          + defines project `:clients:client` - published with module name `nessie-client`
          +--- includeBuild "iceberg"
               + subsitutes module `nessie-client` with `:clients:client` 
               + build "iceberg"
                    + defines project `:iceberg-nessie`
                        + depends on module `nessie-client`
```

When running `:iceberg:iceberg-nessie:publishToMavenLocal`, the generated pom of `:iceberg-nessie` wrongly uses the module name `client` instead of `nessie-client` in the pom's `<depedencies><dependency><artifactId>`.

(Using Gradle build with PR #21016, based on 0452e01706db5d9c88b043af8485a1c0d5a9cfc5)

**Comment by h0tk3y** [comment] 2022-07-12 09:53
Hello @snazy,
I was could not reproduce the issue in either a minimal project that I created using the description you provided or the setup of `nessie-integration-tests` + `nessie` + `iceberg` that you mentioned in #21016.
In both cases the published module metadata in the POMs and `*.module` files contains the correct Maven coordinates of the declared dependencies. In the case of `iceberg-nessie`, the POM contains this dependency:
```xml
<dependency>
    <groupId>org.projectnessie</groupId>
    <artifactId>nessie-client</artifactId>
    <version>0.30.1-SNAPSHOT</version>
    <scope>runtime</scope>
    <exclusions>
      ...
</dependency>
```
Could you please check that the issue is still reproducible on your end? If it is, please ensure that there is a (preferably, minimal) reproducer that I can use for testing.

**Comment by h0tk3y** [comment] 2022-07-12 09:59
I'm closing this issue as unreproducible for now. Feel free to provide more details, and I'll reopen it on relevant updates.

**Closed by h0tk3y** 2022-07-12 09:59 UTC
Labels: in:publishing-plugins, a:bug, in:composite-builds
