### ISSUE TITLE
Composite build bug for layered projects

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#4055] opened 2018-01-17 00:44 UTC
Gradle composite builds have a bug for layered projects.

### Expected Behavior
Composite builds allow to use the same composite dependency from multiple projects

### Current Behavior
See below.

### Context
We are trying to break down our builds into multiple composite builds. We are hitting an issue where we want to use and resolve the same project in multiple configurations.

### Steps to Reproduce (for bugs)
1. Check out https://github.com/liutikas/gradle-composite-build-bug
2. `./gradlew tasks` inside `projectA` directory -> SUCCESS!
3. `./gradlew tasks` at the root project 

```
FAILURE: Build failed with an exception.

* Where:
Build file '/usr/local/foo/composite/projectA/build.gradle' line: 17

* What went wrong:
A problem occurred evaluating project ':projectA'.
> Could not resolve all files for configuration ':projectA:myConfiguration'.
   > Cannot resolve external dependency com.example:projectB:1.0 because no repositories are defined.
     Required by:
         project :projectA
```

If you comment out the line in projectA/build.gradle 
`configurations.getByName("myConfiguration").resolve()` build succeeds on the root projec too.

### Your Environment

 * Build scan URL: build scans seem to be disabled for composite builds?
`Build scan data will not be captured due to this build being a Composite Build.`

Using Gradle 4.4

**Comment by big-guy** [comment] 2018-01-17 03:41
This is working as designed.  Resolving dependencies at configuration time is problematic in general (even without composite builds in the mix).  In this particular case, when evaluating projectA, we haven't evaluated projectB yet, so we don't know which publications are available (and don't do the dependency substitution).  Since projectA doesn't have any repositories defined, there's no place to find the required dependencies.

You can rely on the resolution of a configuration as a dependency, e.g., if you're doing something like this now:

```
task someTask {
   // resolves dependencies on every build during configuration 
   configurations.getByName("myConfiguration").resolve()
}
```

You can instead do:
```
task someTask {
   dependsOn configurations.getByName("myConfiguration")
   // resolves dependencies only when the task is needed
   doLast {
      configurations.getByName("myConfiguration").resolve()
   }
}
```

**Closed by big-guy** 2018-01-17 03:41 UTC

**Comment by blindpirate** [comment] 2018-01-17 04:01
Thanks for reporting, that's kind of expected behavior.

When you run `gradle tasks` in `projectA`, `projectA/settings.gradle` will be evaluated so Gradle knows, "oh, I should use projectB to substitute the dependencies projectA requires". When you run `gradle tasks` in root project, `projectA/settings.gradle` won't be evaludated so Gradle can't know that substitution. In your case, why not use subproject mechanism and `myConfiguration project(":projectB")`?
