### ISSUE TITLE
Support Java 16

### ISSUE THREAD

**Issue by sbrannen** [gradle/gradle#13481] opened 2020-06-17 10:38 UTC
Current attempts to use Gradle 6.5 with `openjdk version "16-ea" 2021-03-16` result in a failure along the lines of:

```
> Task :buildSrc:validatePlugins FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':buildSrc:validatePlugins'.
> There was a failure while executing work items
   > A failure occurred while executing org.gradle.plugin.devel.tasks.internal.ValidateAction
      > Unsupported class file major version 60
```

Please add support for Java 16.

Note, however, that the above failure is due to [lack of support for Java 16 in ASM](https://gitlab.ow2.org/asm/asm/issues/317911).

**Comment by rdehuyss** [comment] 2020-07-07 08:52
I would love to evaluate project loom for my library (https://github.com/jobrunr/jobrunr) but since that is only available in jdk 16 and I also use gradle this is difficult now.

**Comment by eskatos** [comment] 2020-07-07 08:56
@rdehuyss you can use different JVMs for running Gradle and compiling/running tests, see https://docs.gradle.org/current/userguide/building_java_projects.html#sec:java_cross_compilation

**Comment by rdehuyss** [comment] 2020-07-07 08:58
@eskatos , thanks! I did not know that...

**Comment by lppedd** [comment] 2020-08-04 11:00
@rdehuyss were you able to test Loom using Gradle or did you switch to Maven?

**Comment by rdehuyss** [comment] 2020-08-05 11:32
I put it on my backlog for the moment...

**Comment by lppedd** [comment] 2020-08-05 11:48
@rdehuyss I tested it. Instructions by @eskatos works perfectly. It's a matter of minutes.

**Comment by rdehuyss** [comment] 2020-08-16 14:32
@lppedd Thx for your feedback. It indeed wasn't that much work. I'm testing JobRunr now with Project Loom and all seems ok. I still need to do further performance testing.

@eskatos I also have automated tests (it's a test where JobRunr is tested against 12 different JVM's - see also https://www.jobrunr.io/blog/testing-jobrunr-against-12-different-jvms/) where the approach mentioned above is difficult. Since ASM 9 is now available in beta with support for JDK 16, what are the plans for gradle?

**Comment by mikehearn** [comment] 2020-10-11 19:17
This problem really needs to be fixed in a more general way than just bumping ASM versions and doing a new Gradle release.

The problem is that Gradle (sometimes via Groovy) really wants to analyse bytecode in various ways at various points, and pukes when it can't. This is very hard to fix directly because bytecode is not forwards compatible, so you can't analyse versions from the future.

There is therefore only one robust solution: javac must be told to emit old bytecode versions. This it can easily do via the `-target` and `-source` flags. Currently it doesn't work because Gradle is still living in a world where new Java versions were rare events, so it just blithely assumes that whatever Java version is running it is the version it should pass to `-target`/`-source`. It passes `-target 16 -source 16`  to javac as part of compiling some Java/Groovy together, the Groovy compiler tries to read the bytecode and can't, then the error gets partly swallowed and it's all a big mess.

This behaviour makes no sense. If Gradle **must** analyse bytecode then it has only one option: it has to cap the target release at whatever version of Java was the latest supported version at the time of release. This would allow it to be run with the JVM versions "from the future" and still be able to build projects.

That would stem the bleeding, but of course what people want is to be able to use new Java features with old Gradles. They could do so as long as the new feature didn't require new bytecode features (i.e. new APIs but usually not new language features). To support all new Java features with old Gradles implies one of two things:

1. Gradle must be able to optionally sacrifice its features that rely on reading bytecode (some stuff related to incremental builds, I think?)
2. Old Gradles must be able to upgrade themselves on the fly to new versions of ASM, because ASM _is_ forwards compatible. This includes ASMs that are lurking, shaded inside Groovy or other dependencies.

The latter approach is definitely the most work, but it would kill the problem once and for all.

At any rate, I hope the Gradle team read this message and think about how to avoid this problem cropping up every six months. As Gradle is not always backwards compatible, the current approach is basically increasing the cost of Java upgrades for Gradle users - now a Java upgrade costs $JAVA_BACKCOMPAT_BREAKS + $GRADLE_BACKCOMPAT_BREAKS. Although I'm sure the Gradle team would love it if everyone upgraded Gradle immediately on upgrade, the world is full of old projects that are parked and no longer receiving significant work. Yet users wish to have a single JDK and still build and work on those old codebases, without upgrading that project's Gradle build. So this feature would help a lot of people over the coming years.

**Comment by hugmanrique** [comment] 2020-12-25 13:51
@eskatos mind elaborating what you set as `options.release`? I've tried running Gradle with JDK 15, and setting `options.release` to 15, which obviously fails because it cannot find the new classes. Next, I tried using the EA build by passing `-Dorg.gradle.java.home=/home/hugo/panama-b385-jdk-16` to `gradlew` (keeping `options.release = 15`). That fails with the `Unsupported class file major version 60` error seen above. Finally, I tried setting

```groovy
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of('16-panama+3-385')
    }
}
```

which causes an error because `#of` expects an stringified integer value (the AdoptOpenJDK accepts this version value though, see https://api.adoptopenjdk.net/v3/version/16-panama%2B3-385). The docs also say Gradle doesn't support EA versions. I'm running Gradle v6.7.1, and I cannot find any relevant changes in the RCs that would fix this.

**Comment by iotamudelta** [comment] 2020-12-25 15:10
@hugmanrique what works for me is the following:

gradle.properties:
```
org.gradle.java.installations.fromEnv=JDK16
```

build.gradle:
```
java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(16)
  }
}
```
You may need to add JVM args to `compileJava` and `test` groups, e.g., I have:
```
compileJava {
  options.warnings = true
  options.deprecation = true
  options.debug = true
  options.compilerArgs += ["--add-modules=jdk.incubator.foreign"]
  options.incremental = false
}
test {
  useJUnitPlatform()
  jvmArgs '--add-modules=jdk.incubator.foreign'
}
```

build with:
```
JDK16=/path/to/your/jdk16/home gradle build
```
(e.g.: `JDK16=~/software/jdk16/jdk-16.jdk/Contents/Home gradle build`)

**Comment by hugmanrique** [comment] 2020-12-25 21:31
Thank you! Changing from manually specifying the path with `org.gradle.java.installations.paths` to `org.gradle.java.installations.fromEnv` did the trick! 😀

**Comment by koalalam** [comment] 2021-01-11 00:07
Hello @hugmanrique @eskatos @iotamudelta, re: "Changing from manually specifying the path with org.gradle.java.installations.paths to org.gradle.java.installations.fromEnv did the trick", f task "validatePlugins" honor the toolchain configuration, should both `org.gradle.java.installations.paths` and `org.gradle.java.installations.fromEnv` work as well?

**Comment by kevinrushforth** [comment] 2021-02-04 12:37
JDK 16 will be released in just over 1 month. Is there any progress on this issue that the gradle team can share?

**Comment by ipkpjersi** [comment] 2021-02-13 17:30
Is Java 16 support planned for 6.x or is it in 7.x only? What about Java 17 support? I hope both will come to 6.x, ASM is already capable of handling both Java 16 and Java 17.

**Comment by dasKeks28** [comment] 2021-02-25 21:09
As mentioned before by others, ASM (which causes the error) is already able to handle Java 16.
But it seems we're waiting for Gradle to upgrade to use Groovy 3 which "is a prerequisite for Gradle to be able to run on JDK16."
https://github.com/gradle/gradle/issues/15566

**Comment by tbroyer** [comment] 2021-02-27 13:30
Fwiw, #16193 has been merged, so Groovy 3 is there, and available in 7.0-M2.

**Comment by xBlackCat** [comment] 2021-03-08 19:12
Any updates to the issue? Java 16 will be released in a week.

**Comment by ice1000** [comment] 2021-03-16 06:18
I think Java 16 will be released in a day now.

**Comment by cocorossello** [comment] 2021-03-16 07:15
7.0 milestone 3 works fine with jdk16

**Comment by ice1000** [comment] 2021-03-16 08:56
> 7.0 milestone 3 works fine with jdk16

Cool, thanks!

**Comment by swpalmer** [comment] 2021-03-17 14:16
When I use the Java Tooling support to run by build with Java 16, I get this:
```
Execution failed for task ':compileJava'.
> java.lang.IllegalAccessError: class org.gradle.internal.compiler.java.ClassNameCollector (in unnamed module @0x35160ca7) cannot access class com.sun.tools.javac.code.Symbol$TypeSymbol (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.code to unnamed module @0x35160ca7

```

**Comment by wilkinsona** [comment] 2021-03-17 14:28
@swpalmer I think https://github.com/gradle/gradle/issues/15538 covers that one.

**Comment by melix** [comment] 2021-03-17 14:41
@swpalmer just disable incremental compilation and it should pass:

```
tasks.withType(JavaCompile).configureEach {
	// disable incremental compilation
    options.incremental = false
}
```

**Comment by swpalmer** [comment] 2021-03-17 15:51
@melix It is just as easy to add the --add-opens argument

```
tasks.withType( JavaCompile ).configureEach {
    options.forkOptions.jvmArgs.addAll( ['--add-opens', 'jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED'] )
}
```

**Comment by melix** [comment] 2021-03-17 15:52
Absolutely. I'm biased by the fact I find any `--add-opens` suspicious hacks which need to be removed :)

**Comment by LifeIsStrange** [comment] 2021-03-18 02:44
I just created an new, default java gradle project in intellij 2021.1 (beta 3) and the project build throw
```org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:```

**Comment by rieske** [comment] 2021-03-19 15:36
@LifeIsStrange 
The error you are seeing with the preview features enabled is because the code is compiled with `--enable-preview` (JavaCompile task), but then the tests are executed without the preview flag, thus the JVM that is spawned to execute tests does not recognize the bytecode.

In this particular case, you must also set the preview flag on any test tasks that will execute the code compiled with preview features enabled:
```
tasks.withType<Test> {
    jvmArgs("--enable-preview")
}
```

Note, that the same applies if you use Gradle to execute such code with `JavaExec`.
Same applies when running the compiled classes outside of Gradle - the JVM that needs to execute code compiled with preview features needs to receive the `--enable-preview` flag in order to recognize the bytecode.

For reference: https://docs.gradle.org/current/userguide/building_java_projects.html#sec:feature_preview

**Comment by big-guy** [comment] 2021-03-19 22:40
You'll be able to run Gradle with Java 16 in 7.0, but you can already sort of use JDK16 with 6.8.3:

https://melix.github.io/blog/2021/03/gradle-java16.html

We may backport better support for compiling/testing with Java 16 in a future 6.8.x, but you won't be able to run Gradle 6.8.x on Java 16.

**Closed by big-guy** 2021-03-19 22:40 UTC
Labels: @core, a:feature, from:contributor

**Comment by carl-mastrangelo** [comment] 2021-04-07 15:35
@big-guy  Java 16 still have some issues even with `7.0-rc-2`.   https://github.com/gradle/gradle/issues/13629 points to here and is closed as a dupe, but that issue is still broken even with the latest RC.
