### ISSUE TITLE
`maven-publish` plugin doesn't include all artifacts in maven-metadata.xml

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#13330] opened 2020-06-03 22:27 UTC
Gradle 6.5

### Expected Behavior
Can publish multiple `-SNAPSHOT`s to Github Packages ***with sources jar***
https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-gradle-for-use-with-github-packages

### Current Behavior
First version of the snapshot publishes fine.
Second fails with 

```
Caused by: org.gradle.internal.resource.transport.http.HttpErrorStatusCodeException: 
Could not GET 'https://maven.pkg.github.com/foo-org/my-repo/com/example/lib/0.2-SNAPSHOT/maven-metadata.xml'.
 Received status code 400 from server: Bad Request
        at org.gradle.internal.resource.transport.http.HttpClientHelper.processResponse(HttpClientHelper.java:186)
        at org.gradle.internal.resource.transport.http.HttpClientHelper.performGet(HttpClientHelper.java:88)
        at org.gradle.internal.resource.transport.http.HttpResourceAccessor.openResource(HttpResourceAccessor.java:43)
        at org.gradle.internal.resource.transport.http.HttpResourceAccessor.openResource(HttpResourceAccessor.java:28)
        at org.gradle.internal.resource.transfer.DefaultExternalResourceConnector.openResource(DefaultExternalResourceConnector.java:56)
        at org.gradle.internal.resource.transfer.AccessorBackedExternalResource.withContentIfPresent(AccessorBackedExternalResource.java:106)
        at org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator$10.call(BuildOperationFiringExternalResourceDecorator.java:221)
        at org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator$10.call(BuildOperationFiringExternalResourceDecorator.java:213)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator.withContentIfPresent(BuildOperationFiringExternalResourceDecorator.java:213)
        at org.gradle.api.publish.maven.internal.publisher.AbstractMavenPublisher.readExistingMetadata(AbstractMavenPublisher.java:135)
        at org.gradle.api.publish.maven.internal.publisher.MavenRemotePublisher.getNextBuildNumber(MavenRemotePublisher.java:107)
        at org.gradle.api.publish.maven.internal.publisher.MavenRemotePublisher.createSnapshotMetadata(MavenRemotePublisher.java:76)
        at org.gradle.api.publish.maven.internal.publisher.AbstractMavenPublisher.publish(AbstractMavenPublisher.java:68)
        at org.gradle.api.publish.maven.internal.publisher.MavenRemotePublisher.publish(MavenRemotePublisher.java:62)
        at org.gradle.api.publish.maven.internal.publisher.ValidatingMavenPublisher.publish(ValidatingMavenPublisher.java:50)
        at org.gradle.api.publish.maven.tasks.PublishToMavenRepository$1.publish(PublishToMavenRepository.java:77)
        at org.gradle.api.publish.internal.PublishOperation.run(PublishOperation.java:37)
```

if you `curl` the `maven-metadata.xml` you get 
```
HTTP/1.1 400 Bad Request
error retrieving metadata for snapshot file: lib-0.2-20200603.202123-1-sources.jar
```

### Context

I think the Gradle is not adding the sources jar to the `maven-metadata.xml` file and Github validation doesn't like that.

### Steps to Reproduce 

1. Create a gradle project
2. use `maven-publish` plugin
3. add `sourceJar` artifact to the publication
4. publish a SNAPSHOT version. (works fine)
5. publish the same SNAPSHOT version again. will fail. 

If you add a test here with  ***with sources jar*** and verify that sources jar is in the `maven-metadata.xml`, should be able to repro. 
https://github.com/gradle/gradle/blob/112051594d6190dc161a877a841d3f7092c8d3e7/subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishSnapshotIntegTest.groovy#L97

**Comment by ljacomet** [comment] 2020-06-04 07:23
So far we have had reports of multiple publication issues with Github packages and the issue has always been on the Github side.

The `maven-metadata.xml` uploaded by Gradle is visible in the `build` directory, under `build/tmp/**/snapshot-maven-metadata.xml`.

If that one is correct, then the issue is indeed on the Github side, where they do some post processing.

**Comment by melix** [comment] 2020-06-04 09:33
I have modified the test mentioned above like this:

```diff
diff --git a/subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishSnapshotIntegTest.groovy b/subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishSnapshotIntegTest.groovy
index 167465edda3..231e5206049 100644
--- a/subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishSnapshotIntegTest.groovy
+++ b/subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishSnapshotIntegTest.groovy
@@ -33,6 +33,11 @@ class MavenPublishSnapshotIntegTest extends AbstractMavenPublishIntegTest {
     group = 'org.gradle'
     version = '1.0-SNAPSHOT'
 
+    java {
+        withSourcesJar()
+        withJavadocJar()
+    }
+
     publishing {
         repositories {
             maven { url "${mavenRepo.uri}" }
@@ -51,7 +56,11 @@ class MavenPublishSnapshotIntegTest extends AbstractMavenPublishIntegTest {
 
         then:
         def initialVersion = module.publishArtifactVersion
-        def initialArtifacts = ["snapshotPublish-${initialVersion}.module", "snapshotPublish-${initialVersion}.jar", "snapshotPublish-${initialVersion}.pom"]
+        def initialArtifacts = ["snapshotPublish-${initialVersion}.module",
+                                "snapshotPublish-${initialVersion}.jar",
+                                "snapshotPublish-${initialVersion}-sources.jar",
+                                "snapshotPublish-${initialVersion}-javadoc.jar",
+                                "snapshotPublish-${initialVersion}.pom"]
         module.assertArtifactsPublished(initialArtifacts + ["maven-metadata.xml"])
 
         and:
@@ -87,7 +96,11 @@ class MavenPublishSnapshotIntegTest extends AbstractMavenPublishIntegTest {
 
         then:
         def secondVersion = module.publishArtifactVersion
-        List<String> secondArtifacts = ["snapshotPublish-${secondVersion}.module", "snapshotPublish-${secondVersion}.jar", "snapshotPublish-${secondVersion}.pom"]
+        List<String> secondArtifacts = ["snapshotPublish-${secondVersion}.module",
+                                        "snapshotPublish-${secondVersion}.jar",
+                                        "snapshotPublish-${secondVersion}-sources.jar",
+                                        "snapshotPublish-${secondVersion}-javadoc.jar",
+                                        "snapshotPublish-${secondVersion}.pom"]
         module.assertArtifactsPublished(["maven-metadata.xml"] + initialArtifacts + secondArtifacts)
 
         and:
```

and it passes. I also verified that the generated `maven-metadata.xml` file contains the classified sources and javadoc jars with the new snapshot and it does. This would confirm a bug in the GitHub integration rather than Gradle.

**Comment by yogurtearl** [comment] 2020-06-04 18:48
Ah, yes, I can see that the `snapshot-maven-metadata.xml` is correct.
I think that Github packages doesn't support `-SNAPSHOT` with artifacts that have classifiers. 
I will file an issue with Github. You can close this.

**Comment by ljacomet** [comment] 2020-06-05 08:13
Closing as requested.

Do not hesitate to update here when Github announces it fixed.

**Closed by ljacomet** 2020-06-05 08:13 UTC
Labels: @jvm, a:bug, from:contributor, in:dependency-management

**Comment by yogurtearl** [comment] 2022-10-12 22:36
related: https://github.com/orgs/community/discussions/25668
