### ISSUE TITLE
Improve error messages when buildSrc uses incompatible Java toolchain

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#24002] opened 2023-02-22 14:16 UTC
Given that `JAVA_HOME` points to Java 1.8, when I use Java toolchains to set the Java version to 11 in buildSrc

```kotlin
// buildSrc/build.gradle.kts

plugins {
  `kotlin-dsl`
}

kotlin {
  jvmToolchain(11)
}
```

I get incomprehensible errors

```
Could not determine the dependencies of null.
> Could not resolve all task dependencies for configuration ':buildSrc:buildScriptClasspath'.
   > Could not resolve project :buildSrc.
     Required by:
         project :buildSrc
      > No matching variant of project :buildSrc was found. The consumer was configured to find a library for use during runtime, compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.0.1' but:
          - Variant 'apiElements' capability :buildSrc:unspecified declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component for use during compile-time, compatible with Java 11 and the consumer needed a component for use during runtime, compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.1')
          - Variant 'mainSourceElements' capability :buildSrc:unspecified declares a component, and its dependencies declared externally:
              - Incompatible because this component declares a component of category 'verification' and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.1')
                  - Doesn't say anything about its usage (required runtime)
          - Variant 'runtimeElements' capability :buildSrc:unspecified declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 11 and the consumer needed a component, compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.1')
          - Variant 'testResultsElementsForTest' capability :buildSrc:unspecified:
              - Incompatible because this component declares a component of category 'verification' and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.1')
                  - Doesn't say anything about its usage (required runtime)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

The errors are very confusing

* `Could not determine the dependencies of null` - this is the first line and it's already confusing. What is null?
* `Could not resolve all task dependencies for configuration ':buildSrc:buildScriptClasspath'` 
   * 'Configuration' is a vague word and could be replaced with something more descriptive like 'dependency container'
   * this is the first time I've seen `buildScriptClasspath`, so I don't know what it's referring to. It doesn't pop up in build scripts, it's something very under-the-hood.
* `Could not resolve project :buildSrc. Required by: project :buildSrc` - buildSrc requires buildSrc indicates some sort of circular dependency problem 
* `Incompatible because this component declares a component, compatible with Java 11 and the consumer needed a component, compatible with Java 8` - coupled with the error above this looks like its saying "buildSrc provides a Java 11 component, but buildSrc needs a Java 8 component".

Improvements that would help

* Gradle checks to make sure that the `JAVA_HOME` it is using is compatible with the Java toolchain requested, and outputs a more specific error message if they are incompatible
* The error message has an entry in https://docs.gradle.org/current/userguide/troubleshooting.html

Related: #23993

**Comment by eskatos** [comment] 2023-02-22 14:22
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* [#xxx](https://github.com/gradle/gradle/issues/12126)

Please add your use case and 👍 to that issue.

**Closed by eskatos** 2023-02-22 14:22 UTC
Labels: a:bug, to-triage
