### ISSUE TITLE
Provider.filter method

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#22271] opened 2022-09-30 13:30 UTC
[related to](https://github.com/gradle/gradle/issues/22268). Surprisingly while working with provider at one point the suggestion of using `.map` came up. What I really wanted at that point though was to `.filter` the value. Honestly, I hate the keyword filter, I can never tell if it's really keep or discard, terrible verbage. However, it's what kotlin uses for collections so is likely intuitive to look for

### Expected Behavior

this is what I was thinking of doing, but I'm sure there's a lot better reasons, as looking at it this is not a great piece of code 
```
  providers.gradleProperty("ci").filter { it !== "false" } )
```

### Context

```
------------------------------------------------------------
Gradle 7.5.1
------------------------------------------------------------

Build time:   2022-08-05 21:17:56 UTC
Revision:     d1daa0cbf1a0103000b71484e1dbfe096e095918

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.4 (Eclipse Adoptium 17.0.4+8)
OS:           Mac OS X 12.6 x86_64
```

**Comment by jbartok** [comment] 2022-10-03 08:58
What would be the result of the filter operation?

**Comment by xenoterracide** [comment] 2022-10-03 11:13
I would think another provider, which is what the result of a map is right? I'm just treating it like a java `Optional` which has map and filter.

**Comment by aSemy** [comment] 2022-10-04 07:46
In theory this could be achieved with an extension function 


```kotlin
// buildSrc/src/main/kotlin/providerExtensions.kt

fun <T> Provider<T>.filter(evaluate: (T) -> Boolean) : Provider<T> = map { value ->
  value.takeIf(evaluate)
}
// (written without an IDE - I'm not sure if this compiles)
```

but this doesn't work, because of #12388

**Comment by cloudshiftchris** [comment] 2022-10-07 20:47
Using this extension function in the absence of native support:

```
public inline fun <reified S> Provider<S>.filter(crossinline predicate: (S) -> Boolean): Provider<S> {
    return flatMap {
        if (predicate(it)) {
            this@filter
        } else {
            Providers.notDefined()
        }
    }
}
```

**Comment by cloudshiftchris** [comment] 2022-10-14 21:09
Have rethought the naming of this, as `filter` is typically used on collections. In this case, it's used for the optional-value of the Provider.  

The most relevant non-collection parallel for 'filter' is Java's Optional.

More relevant is Kotlin's `takeIf` and 'takeUnless` constructs; building on that proposing `provideIf` and `provideUnless`, as the name is relevant to the action and avoids confusion with takeIf/takeUnless (which, while conceptually equivalent, are different in that they return null).


```
public inline fun <reified T : Any> Provider<T>.provideIf(crossinline predicate: (T) -> Boolean): Provider<T> {
    return flatMap {
        if (predicate(it)) {
            this@provideIf
        } else {
            Providers.notDefined()
        }
    }
}

public inline fun <reified T : Any> Provider<T>.provideUnless(crossinline predicate: (T) -> Boolean): Provider<T> {
    return flatMap {
        if (!predicate(it)) {
            this@provideUnless
        } else {
            Providers.notDefined()
        }
    }
}
```

**Comment by octylFractal** [comment] 2022-12-14 16:53
Duplicate of #19981

**Closed by octylFractal** 2022-12-14 16:53 UTC
Labels: a:feature, in:provider-api
