### ISSUE TITLE
Progress bar not properly cleaned up when build finishes, other build artifacts showing

### ISSUE THREAD

**Issue by w25r** [gradle/gradle#2217] opened 2017-05-31 15:49 UTC
### Expected Behavior

![image](https://cloud.githubusercontent.com/assets/2294198/26640576/baf16108-45ed-11e7-8f98-58038de35971.png)

### Current Behavior

![image](https://cloud.githubusercontent.com/assets/2294198/26640524/916d4658-45ed-11e7-8edf-d08caba66b8a.png)

### Steps to Reproduce (for bugs)

Run `./gradlew clean classes -Dorg.gradle.caching=false` in `gradle/gradle` on `release`

### Your Environment
https://e.grdev.net/s/tjiwnei2ll6h6/

**Comment by w25r** [comment] 2017-05-31 15:50
Verifying that I could reproduce this (I can) I also saw this happen:

![image](https://cloud.githubusercontent.com/assets/2294198/26640981/e88a0b5a-45ee-11e7-99ab-a055640b0e81.png)

**Comment by lacasseio** [comment] 2017-05-31 16:59
We had a similar problem previously where a miss alignment of the state happened while processing test output. I will see what I can do.

**Comment by eriwen** [comment] 2017-05-31 17:36
I believe this is likely a duplicate of #2210, and may be related to a race condition between threads moving cursor and writing with the incremental grouping output changes /cc @lacasseio

**Comment by bmuschko** [comment] 2017-05-31 21:05
Thanks for reporting. I can reproduce the issue. I needed to executed the build a couple of times before I hit the issue.

**Comment by bmuschko** [comment] 2017-05-31 21:07
Closing this as a duplicate. Should we still see the issue after fixing #2210 then we can reopen this one.

**Closed by bmuschko** 2017-05-31 21:07 UTC
Labels: a:bug, from:member, in:logging

**Comment by w25r** [comment] 2017-05-31 21:25
If this one is being closed as a duplicate, the other one should be updated to be more generic, as it isn't specific to a test scenario.

**Comment by bmuschko** [comment] 2017-05-31 21:26
Yes, wanted to do that. Didn't get around to doing it yet.
