### ISSUE TITLE
Task name and error message joined when stderr tied to stdout and redirected to file

### ISSUE THREAD

**Issue by chrycheng** [gradle/gradle#4512] opened 2018-02-24 16:49 UTC
### Expected Behavior
The task name and error message must be on different lines as in when `stderr` and `stdout` are not redirected to file:

![newline-present](https://user-images.githubusercontent.com/650637/36632645-b439cba2-19c3-11e8-95bd-4e3987124add.png)

### Current Behavior
The task name and error are on the same line and are joined with no separator.  Here is a screen shot demonstrating the problem:

![newline-missing](https://user-images.githubusercontent.com/650637/36632648-c35d9d70-19c3-11e8-9b23-e54207152819.png)

### Context
Tools like [`emacs-gradle-mode`](https://github.com/jacobono/emacs-gradle-mode) that work by tying stderr and stdout together and redirecting them to file are unable to provide their users with working feedback (e.g., press a key to go to the first build error) because the output isn't in the expected format.

### Steps to Reproduce (for bugs)
1. Extract [compilejava-bug-test.zip](https://github.com/gradle/gradle/files/1754636/compilejava-bug-test.zip)
2. Run `gradle build > output.txt 2>&1`.
3. Open `output.txt`.
4. Notice that the message describing the compilation error is joined to `:compileJava` as in the screen shot above.

### Your Environment
 * Build scan URL: https://gradle.com/s/v7nv6efwrlnfy

**Comment by blindpirate** [comment] 2018-02-26 06:35
Duplicate of #4306

**Comment by eriwen** [comment] 2018-06-01 16:06
Closing as duplicate

**Closed by eriwen** 2018-06-01 16:06 UTC
Labels: a:bug, affects-version:4.5, from:contributor
