### ISSUE TITLE
Gradle confuses subprojects with same name, CircularReferenceException

### ISSUE THREAD

**Issue by C-Otto** [gradle/gradle#16885] opened 2021-04-19 09:14 UTC
Have three (sub-)projects:

```
:aaa (no dependencies)
:aaa:bbb (depends on :aaa and :bbb)
:bbb (no dependencies)
```

### Expected Behavior
Build passes.

### Current Behavior
Build fails.
```
Circular dependency between the following tasks:
:aaa:bbb:classes
\--- :aaa:bbb:compileJava
     \--- :aaa:bbb:jar
          \--- :aaa:bbb:classes (*)
```

Notable weirdness:
```
compileClasspath - Compile classpath for source set 'main'.
+--- project :aaa
\--- project :bbb -> project :aaa:bbb (*)
```

Reproducer: https://github.com/C-Otto/gradle-nested-same-name

### Context
I'm trying to refactor my project to make use of nested subprojects. This fails if two subprojects (with different "parent" projects) have the same name and the dependencies are "unfortunate".

### Steps to Reproduce 
https://github.com/C-Otto/gradle-nested-same-name

### Your Environment
Gradle 7.0
Scan: https://gradle.com/s/co2b2xqkjzyiy

**Comment by oesolutions** [comment] 2021-04-23 05:56
I would consider this as "works as intended".
When Gradle resolves the `compileClasspath` of `:aaa:bbb` it sees that there are two components with the same group and name `de.cotto:bbb` in the dependency tree. It then must choose one of them as part of conflict resolution (why you see the substitution `project :bbb -> project :aaa:bbb`). If you change the group ID of one of the `bbb` projects, then there is no longer a conflict and the dependency resolution works as you expected.

For extra fun with conflict resolution; with the same group IDs in both `bbb` projects, you can also "fix" the circular reference by setting the version to '0.5' in `:aaa:bbb`. Since `:aaa:bbb` is then a lower version of `de.cotto:bbb`, Gradle will choose the higher version and use the `:bbb` project (`de.cotto:bbb:1.0-SNAPSHOT`).

**Comment by ljacomet** [comment] 2021-04-26 15:50
Closing as there is nothing to be done for Gradle. To be disambiguated in dependency resolution, projects must have different coordinates.

**Closed by ljacomet** 2021-04-26 15:50 UTC
Labels: in:dependency-resolution

**Comment by C-Otto** [comment] 2021-04-26 21:27
Hm, OK. What about a warning/error that two subprojects have the same coordinates? I believe this should not be possible, and the user should be made aware of this instead of silently ignoring one of the subprojects and using the other.

**Comment by C-Otto** [comment] 2021-04-27 07:28
Example of Gradle silently ignoring a subproject: https://github.com/C-Otto/gradle-nested-same-name/tree/without-cycle

**Comment by C-Otto** [comment] 2021-04-27 08:13
Continues as feature request in #16986.

**Comment by Vampire** [comment] 2021-04-28 10:12
Actually I'd say this is a duplicate of #847
