### ISSUE TITLE
Allow convenient execution of Gradle wrapper from subprojects

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1250] opened 2017-01-24 22:27 UTC
Using gradlew is nice for a lot of reasons, but it somewhat forces you to run things from the command line at the top project level only or use ../../gradlew depending upon where in the subproject tree one is.

### Expected Behavior
One can execute `gradlew` (or similar) from any subproject without having to type `../../../../..`

### Current Behavior
`gradlew` must be directly referenced.

### Context
Douglas Borg has created a project for this called [gdub](http://www.gdub.rocks/)

This issue was migrated from [GRADLE-2429](https://issues.gradle.org/browse/GRADLE-2429) where it had 8 votes.

**Comment by pioterj** [comment] 2017-03-24 15:01
Closing as duplicate of https://github.com/gradle/gradle/issues/1368.

**Closed by pioterj** 2017-03-24 15:01 UTC
Labels: a:feature, in:wrapper
