### ISSUE TITLE
Incremental OutputFiles detection not working properly

### ISSUE THREAD

**Issue by NitroG42** [gradle/gradle#26039] opened 2023-08-07 16:31 UTC
### Current Behavior

When a new OutpuFile is added to an OutputFiles collection, the following behavior appears:
> Task ':gentask' is not up-to-date because:
> Output property 'generatedOutputs$2' has been added for task ':gentask' 
> The input changes require a full rebuild for incremental task ':gentask'.

### Expected Behavior

Previously, my plugin was using IncrementalTaskInputs which weren't subject to this ; 

Adding an OutputFile (because of an updated input) should trigger an incremental change, and not a full rebuild.

### Context (optional)

A task read a txt file as input and generate a file for each line read.
`@InputFiles`
a configurablefilecollection filtering on txt files
`@OutputFiles`
a `ConfigurableFileCollection` (I tried with a `Map<String, File>` too)

### Incremental test

We write one line on the txt file, then add another one.
This test purpose is to check that the first file is not "generated" again by comparing lastModified date ; because
generating those file can take time and power.

### Steps to Reproduce

https://github.com/NitroG42/GradleIncrementalOutputFilesIssue

### Gradle version

8.2.1

**Comment by ov7a** [comment] 2023-08-09 12:23
Thank you for providing a valid report.

The issue is in the backlog of the relevant team, but the existence of a workaround makes it non-critical, so it might take a while before a fix is made.

**Comment by NitroG42** [comment] 2023-08-09 12:42
Can you share the workaround/relevant issue ? I don't mind using a workaround if I can make it works.

**Comment by ov7a** [comment] 2023-08-09 13:31
@NitroG42 Sorry, my previous message is incorrect. There is no workaround. But still, this area of Gradle is currently not a focus one, so it might take a while before a fix is made.

**Comment by NitroG42** [comment] 2023-08-09 15:57
Unfortunatelly it will requires some change on my real plugin as right now the V1.0 "output dir" is a mix of user and generated files. I planned to switch to OutputDir for a V2.0 but it requires more work and right now with latest Android Gradle Plugin released requiring Gradle 8.0, I made the choice of changing as little as possible.

Thank you for the solution anyway, I'll try to work on that!

**Comment by lptr** [comment] 2023-12-05 08:51
Let's close this as the intended way to support the use case is to use `@OutputDirectory` as @asodja described above.

**Closed by lptr** 2023-12-05 08:51 UTC
Labels: a:bug, in:writing-tasks, has:reproducer
