### ISSUE TITLE
Extra properties not being passed to subprojects anymore (5.4.1 vs 5.5)

### ISSUE THREAD

**Issue by jponge** [gradle/gradle#9886] opened 2019-07-05 11:09 UTC
### Expected Behavior

Given the following declarations in `build.gradle.kts`:

```kotlin
subprojects {
  extra["vertxVersion"] = "3.8.0-SNAPSHOT"
  extra["junit5Version"] = "5.5.0"
  extra["restAssuredVersion"] = "4.0.0"
  extra["logbackClassicVersion"] = "1.2.3"
  extra["assertjVersion"] = "3.12.2"
  extra["testContainersVersion"] = "1.11.3"
  // ...
}
```

and the following usage in a subproject `build.gradle.kts`:

```kotlin
dependencies {
  val vertxVersion = extra["vertxVersion"]
  val junit5Version = extra["junit5Version"]
  val logbackClassicVersion = extra["logbackClassicVersion"]
  val restAssuredVersion = extra["restAssuredVersion"]
  val assertjVersion = extra["assertjVersion"]
  val testContainersVersion = extra["testContainersVersion"]
  // ...
}
```

### Current Behavior

The project should build, with extra properties allowing to share expected dependencies versions. This worked until 5.4.1 without issues, but upon upgrading to 5.5 I get the following error:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/jponge/Dropbox/Documents/Writings/vertx-in-action/code/part2-steps-challenge/activity-service/build.gradle.kts' line: 2

* What went wrong:
Cannot get property 'vertxVersion' on extra properties extension as it does not exist

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

### Context

It worked in earlier versions, and starting from 5.5 it breaks existing builds.

### Steps to Reproduce 

Take https://github.com/jponge/vertx-in-action/tree/part2-steps-challenge and try upgrading to 5.5.

**Comment by eskatos** [comment] 2019-07-05 13:06
Thanks for the report @jponge 
This is a duplicate of https://github.com/gradle/gradle/issues/9579
See the [upgrade guide](https://docs.gradle.org/current/userguide/upgrading_version_5.html#dependencyhandler_now_statically_exposes_extensionaware) for instructions.

**Closed by eskatos** 2019-07-05 13:06 UTC
Labels: a:regression, from:contributor

**Comment by jponge** [comment] 2019-07-05 13:39
Thanks @eskatos, problem solved, but even looking at the release notes / upgrade guide this was not obvious from the table of contents.

**Comment by eskatos** [comment] 2019-07-05 13:59
Yep the table of contents is just the list of Gradle versions in the upgrade guide. Searching the page for `extra` is how I found it back.
