### ISSUE TITLE
MavenPublication can't be specified for TaskProvider<Jar>

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/gradle#6246] opened 2018-08-08 14:52 UTC
### Expected Behavior
I should be able to configure a publish artifact with the following API:
```kotlin
val sourceJar : TaskProvider<org.gradle.api.tasks.bundling.Jar> 
    = tasks.register("sourceJar", org.gradle.api.tasks.bundling.Jar::class.java) {
    // Add this to a group so that it shows up in the task listings
    group = "build"

    classifier = "sources"
    dependsOn("classes")
    from(java.sourceSets["main"].allSource)
}

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            artifactId = projectArtifactId
            from(components.getByName("java"))
            artifact(sourceJar)
        }
    }
}
```

The above works changing the code to:
```kotlin
val sourceJar = task<org.gradle.api.tasks.bundling.Jar>("sourceJar") {
    ...
```

### Current Behavior

I get the following error:
```
Cannot convert the provided notation to an object of type MavenArtifact: task ':StdLib:sourceJar'.
The following types/formats are supported:
  - Instances of MavenArtifact.
  - Instances of AbstractArchiveTask, for example jar.
  - Instances of PublishArtifact
  - Maps containing a 'source' entry, for example [source: '/path/to/file', extension: 'zip'].
  - Anything that can be converted to a file, as per Project.file()
```

### Context

This limitation means that you can't configure publishing maven artifacts without collapsing the configuration of the `sourceJar`.

### Your Environment
```
------------------------------------------------------------
Gradle 4.9
------------------------------------------------------------

Build time:   2018-07-16 08:14:03 UTC
Revision:     efcf8c1cf533b03c70f394f270f46a174c738efc

Kotlin DSL:   0.18.4
Kotlin:       1.2.41
Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_92 (Oracle Corporation 25.92-b14)
OS:           Mac OS X 10.13.5 x86_64
```

**Comment by big-guy** [comment] 2018-08-08 15:01
👍This is something we want/need to do still.

**Comment by trevjonez** [comment] 2018-08-28 17:29
I just found an easy workaround, wrap the task provider with a `LazyPublishArtifact`

`artifact(sourceJar)` to `artifact(LazyPublishArtifact(sourceJar))`

Perhaps the solution to this pr is to just have the `DefaultMavenPublication` Implementation auto wrap a `TaskProvider` instance in the lazy publish artifact?

**Comment by trevjonez** [comment] 2018-08-28 17:58
looks like other parts of the maven-publish still trigger some eager tasks to be created
https://scans.gradle.com/s/w6z4hybqqmypo/performance/configuration?focused=12&openScriptsAndPlugins=WzNd

maven-publish causes: `publish`, `publishToMavenLocal`, then my call to register seemingly triggers three more `generateMetadataFileForAndroidPublication`, `generatePomFileForAndroidPublication`, `publishAndroidPublicationToMavenLocal`

`generateMetadataFileFor[...]Publication` is maybe specific to components implementing `ComponentWithVariants`?

**Comment by JLLeitschuh** [comment] 2018-08-29 06:16
@eriwen Any chance of updating the error message to helpfully respond with something like:
```
...
  - Instances of AbstractArchiveTask, for example jar.
  - Instances of PublishArtifact (for example LazyPublishArtifact)
...
```

**Comment by adammurdoch** [comment] 2018-08-29 06:56
`LazyPublishArtifact` is an internal type and we'd rather that plugins and build scripts didn't use this. Instead, we'll add some public methods (or perhaps change the existing one) so you can add an artifact for the output of a task given a `TaskProvider` for that task.

**Comment by trevjonez** [comment] 2018-08-29 17:27
yea using LazyPublishArtifact is for sure a fragile `Workaround`.

**Comment by JLLeitschuh** [comment] 2018-09-07 18:01
Is there a planned release where this will be fixed?

**Comment by adammurdoch** [comment] 2018-09-09 22:02
Not yet, "soon" is the plan at this stage. Hopefully in Gradle 5.0 or 5.1 but there are no guarantees.

**Comment by rbrindl** [comment] 2019-02-15 08:16
Is anyone currently working on this?

A simple way to fix this would be to change `FileProviderNotationConverter<Provider, ConfigurablePublishArtifact>` to `ProviderNotationConverter<Provider, PublishArtifact>` and also let it handle `TaskProviders`. This would not require complicated type-based preselection mechanisms.

Another, more complicated way would be to add a `TaskProviderNotationConverter` in `PublishArtifactNotationParserFactory`.
But since we cannot detect the Generic Type of a provider at runtime, a CompositeNotationConverter would need a mechanism to detect the "most specific" converter, so that FileProviderNotationConverter (which registers on Provider) would not overwrite results of a potential TaskProviderNotationConverter that has been registered as TaskProvider (a subtype of Provider) and ran earlier. This sounds like a lot of potential trouble so I would rather vote for the first solution.

**Comment by gabrielittner** [comment] 2020-01-30 12:45
Any updates on this? This makes code trying to use task configuration avoidance APIs really ugly. Right now you'd have to wait for configuration to register a task as an artifact but that means that task won't be added as a dependency on the publish task.

**Comment by chrisr3** [comment] 2020-07-05 20:17
Still not fixed in Gradle 6.5.1.

**Comment by JLLeitschuh** [comment] 2020-07-06 21:47
Spitballing code, I think that adding something like this to `PublishArtifactNotationParserFactory` and adding it as a registered converter in `PublishArtifactNotationParserFactory::create` method, you'd get it to work. But this would need to be tested.

```java
    private class TaskProviderNotationConverter extends TypedNotationConverter<TaskProvider<Task>, ConfigurablePublishArtifact> {
        private TaskProviderNotationConverter() {
            super(new TypeInfo<>(TaskProvider.class));
        }

        @Override
        public void describe(DiagnosticsVisitor visitor) {
            visitor.candidate("Instances of TaskProvider<AbstractArchiveTask>.");
        }

        @Override
        protected ConfigurablePublishArtifact parseType(TaskProvider<Task> notation) {
            Module module = metaDataProvider.getModule();
            return instantiator.newInstance(DecoratingPublishArtifact.class, new LazyPublishArtifact(notation, module.getVersion()));
        }
    }
```

**Comment by cspurk** [comment] 2020-08-13 12:41
Isn’t this a duplicate of #7958 which is now fixed in Gradle 6.6 with #13505?

**Comment by JLLeitschuh** [comment] 2020-08-17 20:53
@melix can you confirm this is fixed and can be closed?

**Comment by melix** [comment] 2020-08-18 07:04
Yes it is.

**Closed by melix** 2020-08-18 07:04 UTC
Labels: @core, from:contributor, in:configuration-model
