### ISSUE TITLE
Gradle 4.3-rc-1 breaks spring-boot plugin

### ISSUE THREAD

**Issue by huxi** [gradle/gradle#3193] opened 2017-10-14 07:40 UTC
A project like the one described in "Steps to Reproduce" worked with Gradle 4.2.1 and earlier.

It does not work with Gradle 4.3-rc-1 anymore.

### Expected Behavior

```
BUILD SUCCESSFUL in 0s
```

### Current Behavior

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bootRepackage'.
> Cannot convert the provided notation to a File or URI: task ':jar'.
  The following types/formats are supported:
    - A String or CharSequence path, for example 'src/main/java' or '/usr/include'.
    - A String or CharSequence URI, for example 'file:/usr/include'.
    - A File instance.
    - A Path instance.
    - A Directory instance.
    - A RegularFile instance.
    - A URI or URL instance.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':bootRepackage'.
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:50)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.internal.typeconversion.UnsupportedNotationException: Cannot convert the provided notation to a File or URI: task ':jar'.
The following types/formats are supported:
  - A String or CharSequence path, for example 'src/main/java' or '/usr/include'.
  - A String or CharSequence URI, for example 'file:/usr/include'.
  - A File instance.
  - A Path instance.
  - A Directory instance.
  - A RegularFile instance.
  - A URI or URL instance.
        at org.gradle.internal.typeconversion.ErrorHandlingNotationParser.parseNotation(ErrorHandlingNotationParser.java:56)
        at org.gradle.api.internal.file.AbstractFileResolver.convertObjectToFile(AbstractFileResolver.java:126)
        at org.gradle.api.internal.file.AbstractBaseDirFileResolver.doResolve(AbstractBaseDirFileResolver.java:69)
        at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:86)
        at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:68)
        at org.gradle.api.internal.tasks.DefaultTaskInputs.toFile(DefaultTaskInputs.java:367)
        at org.gradle.api.internal.tasks.DefaultTaskInputs.access$100(DefaultTaskInputs.java:46)
        at org.gradle.api.internal.tasks.DefaultTaskInputs$6.validate(DefaultTaskInputs.java:345)
        at org.gradle.api.internal.tasks.StaticValue.validate(StaticValue.java:43)
        at org.gradle.api.internal.tasks.DefaultTaskInputFilePropertySpec.validate(DefaultTaskInputFilePropertySpec.java:124)
        at org.gradle.api.internal.tasks.DefaultTaskInputs.validate(DefaultTaskInputs.java:161)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:47)
        ... 24 more
```

### Steps to Reproduce (for bugs)

1. Create the files below.
1. Execute `gradle wrapper` to use Gradle 4.3-rc-1.
1. Execute `gradlew`.

#### build.gradle
```groovy
buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath 'org.springframework.boot:spring-boot-gradle-plugin:1.5.7.RELEASE'
    }
}

wrapper {
    gradleVersion = '4.3-rc-1'
}

apply plugin: 'org.springframework.boot'

bootRepackage {
    // https://github.com/spring-projects/spring-boot/issues/1113
    // https://github.com/spring-projects/spring-boot/issues/8167
    classifier = "repack"
}

defaultTasks 'build'
```

#### src/main/java/foo/Main.java
```java
package foo;

// any class with a public static void main(String[] args) method
public class Main {
    public static void main(String[] args) {
        System.out.println("foo.Main");
    }
}
```

**Comment by huxi** [comment] 2017-10-14 08:17
The build failure does not happen in absence of a `bootRepackage {...]` configuration.

That configuration is necessary because of https://github.com/spring-projects/spring-boot/issues/1113 and https://github.com/spring-projects/spring-boot/issues/8167 .

**Comment by oehme** [comment] 2017-10-14 10:38
@lptr or @adammurdoch does this ring a bell?

**Comment by blindpirate** [comment] 2017-10-15 08:08
@huxi Thanks for reporting.

@oehme @lptr Looks like this is caused by validation which is introduced in https://github.com/gradle/gradle/commit/22b9d7b046ccf9257dbbdee1198751ffa6c91eff

`spring-boot-gradle-plugin` registered `jar` task as another task's input via [runtime API](https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:task_input_output_runtime_api) here: https://github.com/spring-projects/spring-boot/blob/v1.5.7.RELEASE/spring-boot-tools/spring-boot-gradle-plugin/src/main/java/org/springframework/boot/gradle/repackage/RepackagePluginFeatures.java#L150

In previous implementation,  the value passed to `inputs.files()` and `inputs.file()` weren't validated, so a `Task` input property can be passed to `inputs.file()` without any exception. Looks like `inputs.files()` should be used here, but I'm not sure if we should allow this "incorrect" usage of `input.file()`.

**Comment by astellingwerf** [comment] 2017-10-15 16:47
According to documentation on [the release candidates TaskInputs](https://docs.gradle.org/release-candidate/javadoc/org/gradle/api/tasks/TaskInputs.html#file(java.lang.Object)) both `inputs.file` and `inputs.files` are processed through `Project.files`. By that logic, both are equally suitable to process a `Task` or `FileTree`. But the validator added by @lptr blocks it, and does a poor job of telling where in the build script (class/file name and line number) the issue is.

**Comment by lptr** [comment] 2017-10-16 11:32
Thanks @huxi for reporting. PR has been merged, this will be fixed in 4.3-rc-2.

**Comment by lptr** [comment] 2017-10-16 11:47
Reverted original PR, second try #3202.

**Comment by lptr** [comment] 2017-10-16 13:14
PR merged again.

**Closed by lptr** 2017-10-16 13:14 UTC
Labels: a:bug, from:contributor
