### ISSUE TITLE
Tests crash or hang when writing a lot of output to the console.

### ISSUE THREAD

**Issue by matteriben** [gradle/gradle#28498] opened 2024-03-19 03:01 UTC
### Current Behavior

Test cases that write a lot of output to the console through System.out.println or using logger.info (when gradle is run with -i or --info) often crash or hang.

### Expected Behavior

The same test cases pass as expected when run with maven.

### Steps to Reproduce

I created three test cases to demonstrate this.
test1 - System.out.println
test2 - logger.info + platform threads
test3 - logger.info + virtual threads

I created a reproducer repo, and ran each test case on each os (macos, ubuntu & windows). That is 9 test cases in total. I ran the reproducer github action multiple times and got a mix of crashes and hangs.

I also had the reproducer run the same 3 tests with maven, on each os, again 9 tests in total. So far, every time these passed, as expected, when run with maven.

https://github.com/matteriben/gradle-iotest-reproducer

### Gradle version

8.6

### Your Environment (optional)

Using github actions I have tested this in macos, ubuntu, and windows.

**Comment by ov7a** [comment] 2024-03-19 13:23
This issue will be closed as a duplicate of

* #15621

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

**Closed by ov7a** 2024-03-19 13:23 UTC
Labels: a:bug, to-triage
