### ISSUE TITLE
Tooling API seems to ignore proxy settings in ~/.gradle/gradle.properties

### ISSUE THREAD

**Issue by sadovnikov** [gradle/gradle#2571] opened 2017-07-24 09:36 UTC
When used behind proxy Tooling API fails on `ModelBuilder#get()` due to failure to resolve `org.gradle:gradle-tooling-api:4.0.1`, `java.net.UnknownHostException: repo.gradle.org`

### Expected Behavior
Tooling API is able to resolve the repository host because of settings in `~/.gradle/gradle.properties`

```
systemProp.https.proxyHost=proxylb.internal.xxx.org
systemProp.https.proxyPort=8080
systemProp.https.proxyUser=VS86957
systemProp.https.proxyPassword=XXXXXXX
systemProp.https.nonProxyHosts=*.xxx.org|localhost|*.local|127.0.0.1
```

### Current Behavior
Using Tooling API to retrieve a project model fails with the trace below (all details are removed, only messages are left)

```
org.gradle.api.GradleException: Error retrieving ProjectInfoModel from project in C:\development\sources\repos\jvr\project-info-plugins\project-info-gradle-test\src\test\resources\multi with init script C:\Users\vs86957\AppData\Local\Temp\project-info-init402592061672622671gradle
Caused by: org.gradle.tooling.BuildException: Could not fetch model of type 'ProjectInfoModel' using Gradle distribution 'https://services.gradle.org/distributions/gradle-4.0.1-bin.zip'.
Caused by: org.gradle.internal.exceptions.LocationAwareException: Could not resolve all files for configuration 'classpath'.
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration 'classpath'.
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve org.gradle:gradle-tooling-api:4.0.1.
Required by:
    unspecified:unspecified:unspecified > com.jv-ration.gradle.plugins:project-info-gradle-plugin:0.0.9-SNAPSHOT > com.jv-ration.gradle.plugins:project-info-gradle-model:0.0.9-SNAPSHOT
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve org.gradle:gradle-tooling-api:4.0.1.
Caused by: org.gradle.api.resources.ResourceException: Could not get resource 'https://repo.gradle.org/gradle/libs-releases-local/org/gradle/gradle-tooling-api/4.0.1/gradle-tooling-api-4.0.1.pom'.
Caused by: org.gradle.internal.resource.transport.http.HttpRequestException: Could not HEAD 'https://repo.gradle.org/gradle/libs-releases-local/org/gradle/gradle-tooling-api/4.0.1/gradle-tooling-api-4.0.1.pom'.
Caused by: java.net.UnknownHostException: repo.gradle.org
```

### Context
I'm working on https://github.com/JV-ration/project-info-plugins, which attempts to retrieve unified project model from both Maven and Gradle projects. 

### Steps to Reproduce (for bugs)
The problem is reproducible in unit tests of [project-info-plugins](https://github.com/JV-ration/project-info-plugins) project, when run behind firewall

```
git clone git@github.com:JV-ration/project-info-plugins.git
cd project-info-plugins
./gradlew build
```

### Your Environment
 * Build scan URL: https://gradle.com/s/cysevqplaqu2a

**Comment by oehme** [comment] 2018-01-18 08:55
The proxy settings also need to be set in `gradle/wrapper/gradle-wrapper.properties`, so the wrapper download will use them. The `gradle.properties` are only used for the actual build that is performed by the downloaded distribution later.

The reason we don't check for gradle.properties is to keep the wrapper code simple. Otherwise it would have to understand all the different Gradle command line options to find the properties file.

**Comment by oehme** [comment] 2018-01-18 09:14
I added some fake proxy settings to my `~/.gradle/gradle.properties` and loaded a project with the TAPI. I got a proxy error as I expected. Any other steps I might be missing?

**Comment by mrooney** [comment] 2018-01-22 21:08
We are seeing java.net.UnknownHostException as well with the Tooling API behind a proxy, while normal gradle invocations work and we can wget the URL in question fine. I'm wondering if the proxy implementation is using the proxy, but incompletely, and not routing the DNS / name resolution over the proxy? @oehme this would explain why you run into proxy errors (it is attempting to use the proxy), but we see UnknownHostException. You'd probably need to test this on a network that blocks external DNS resolution with a real proxy.

**Comment by sadovnikov** [comment] 2018-01-23 08:36
I'm not getting to the same environment until Feb 5. Will try to reproduce the bug then.

**Comment by oehme** [comment] 2019-01-06 13:15
Turns out that this is an issue specifically related to init scripts, which is why I couldn't reproduce it with a normal build script. It's a duplicate of #6825

**Closed by oehme** 2019-01-06 13:15 UTC
Labels: a:bug, from:contributor, in:core, in:tooling-api
