### ISSUE TITLE
[Tooling-API] `org.gradle.internal.classloader.ClasspathUtil#getClasspath(ClassLoader) blows up on non-file classpath URLs

### ISSUE THREAD

**Issue by BoykoAlex** [gradle/gradle#3354] opened 2017-11-03 00:02 UTC
The project that depends on Gradle Tooling API is built into a "fat jar" with a help of `spring-boot-maven-plugin`.
Everything blows up whenever a `GradleModel` is built. At some point Tooling API attempts to build a classpath provided current ClassLoader. Since everything is packed into a "fat jar" classpath URLs are: `jar:file:/Users/aboyko/git/sts4/vscode-extensions/vscode-boot-java/jars/language-server.jar!/BOOT-INF/classes!/` This cannot be converted to a `File` but can live as a URL.
However, `org.gradle.internal.classloader.ClasspathUtil#getClasspath(ClassLoader)` converts URLs into Files to create instance of `org.gradle.internal.classpath.DefaultClassPath` and blows up with `IllegalArgumentException` trying to convert URL -> URI -> File :-(
Shouldn't everything be based on URLs rather than Files for `ClasspathUtil` and `ClassPath` interface. Think it should be rather painless to add a constructor with list of URLs parameter.

**Comment by oehme** [comment] 2017-11-03 08:50
Duplicate of #2483

**Closed by oehme** 2017-11-03 08:50 UTC
