### ISSUE TITLE
Add JetBrains nullness annotations to Transformer OUT type parameter of all public API classes

### ISSUE THREAD

**Issue by quickstep24** [gradle/gradle#26906] opened 2023-11-01 12:15 UTC
### Current Behavior

The documentation for `filter` in `CopyTask` states that returning `null` will delete the line in the result.
However, Kotlin DSL will not accept `null` as result of `filter(line)` in `CopyTask`.
See example below.

As a workaround, you can declare a function of type `(String) -> String?` and unsafe cast it to `(String) -> String`.
``` kotlin
        fun myFilter(line: String): String? = when {
            line.isBlank() -> null
            else -> line
        }
        project.tasks.register<Copy>("foo") {
            filter(::myFilter as (String) -> String)
        }
```

### Expected Behavior

A null value should be accepted.
This requires a `@nullable` annotation in `AbstractCopyTask`:
``` kotlin
    @Override
    public AbstractCopyTask filter(Transformer<String, String> transformer) {   // should be: Transformer<@Nullable String, String>
        getMainSpec().filter(transformer);
        return this;
    }
``` 

### Steps to Reproduce

``` kotlin
class FooPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        project.tasks.register<Copy>("foo") {
            filter { line -> 
                when {
                    line.isBlank() -> null    // not accepted
                    else -> line
                }
            }
        }
    }
}
```

### Gradle version

8.3

**Comment by cobexer** [comment] 2023-11-02 14:51
Thank you for providing a valid report.

The issue is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before a fix is made.

**Comment by Vampire** [comment] 2024-02-12 13:02
Isn't this a duplicate of #24767 just like #12388 is?

**Comment by eskatos** [comment] 2024-05-17 12:39
@Vampire, unfortunately not, see https://github.com/gradle/gradle/issues/24767#issuecomment-2117511890

**Comment by Vampire** [comment] 2024-05-17 14:26
So then #12388 also needs to be reopened?

**Comment by big-guy** [comment] 2024-06-17 16:33
We don't want to add `@Nullable` to all Transformer OUT parameters, but we should verify that all users of Transformer properly annotate Nullable/NonNull their OUT parameters.

**Closed** 2024-06-25 00:05 UTC
Labels: a:bug, in:kotlin-dsl, in:file-tasks, re:nullability
