### ISSUE TITLE
bug: stuck at task publishToMavenLocal 

### ISSUE THREAD

**Issue by igorgiumellizup** [gradle/gradle#18128] opened 2021-08-26 13:33 UTC
Hello. I need some help with task publishToMavenLocal. I tried with versions 6.7, 6.8, ... until 7.2. 

### Expected Behavior
Command ```./gradlew publishToMavenLocal``` executed in project https://github.com/ZupIT/beagle-backend-kotlin should work and not hang forever.

### Current Behavior
The command gets stuck at step ```framework:generatePomFileForMavenPublication```

### Context
Publish a project locally

### Steps to Reproduce 
1 - Download the mentioned project
2 - Execute the mentioned command

### Environment
macOS Big Sur 11.5.2 (i7, 16gb ram)
openjdk version "14.0.2" 2020-07-14
Apache Maven 3.8.1

**Comment by mlopatkin** [comment] 2021-08-30 04:25
I reproduced the issue and captured a thread dump:
[stack.txt](https://github.com/gradle/gradle/files/7074067/stack.txt)

**Comment by mlopatkin** [comment] 2021-08-30 04:40
I suspect that this is might be a duplicate of #17812. @igorgiumellizup could you please try to verify that the issue is gone with the [nightly build of 7.3](https://gradle.org/nightly/)

**Comment by igorgiumellizup** [comment] 2021-08-30 11:32
> I suspect that this is might be a duplicate of #17812. @igorgiumellizup could you please try to verify that the issue is gone with the [nightly build of 7.3](https://gradle.org/nightly/)?

Hi. I'll try this version, but one thing I noticed is that  the process doesn't hang when I disable the ```org.gradle.parallel=true``` in the submodule https://github.com/ZupIT/beagle-backend-kotlin/blob/main/gradle.properties

**Comment by mlopatkin** [comment] 2021-08-31 11:24
>when I disable the org.gradle.parallel=true

Yes, the issue is a deadlock in the execution engine when tasks start to execute simultaneously. Disabling parallel execution eliminates the very possibility of this.

**Comment by mlopatkin** [comment] 2021-09-07 11:46
I'm closing this issue as a duplicate of #17812. Please comment there if it occurs again in 7.3+.

**Closed by mlopatkin** 2021-09-07 11:46 UTC
Labels: a:bug, to-triage
