### ISSUE TITLE
javaexec leaks classloaders

### ISSUE THREAD

**Issue by astellingwerf** [gradle/gradle#750] opened 2016-10-25 18:07 UTC
I suspect that `javaexec` is leaking classloaders since 3.2-rc-1. I'm using `javaexec` to trigger other Gradle builds:

```
javaexec {
     classpath 'wrapper/gradle-wrapper.jar'
     main = 'org.gradle.wrapper.GradleWrapperMain'
     args ['-b', 'externalBuildFile.gradle', 'externalTask']
}
```

This externalBuildFile.gradle imports an Ant `taskdef` that where the impl loads native libraries. Now, when I execute this block twice, with 3.2-rc-1 I get an error the second time:

> java.lang.UnsatisfiedLinkError: Native Library /full/path/to/my.so already loaded in other classloader

It works fine when running the same with Gradle 3.1.
### Expected Behavior

Classloaders that are instantiated for `javaexec` should be closed once done.
### Your Environment

Linux Mint 18

**Comment by bmuschko** [comment] 2016-10-25 19:37
Thanks for reporting. Could you provide us with more information on what the `externalTask` is doing e.g. what Ant task are you using/what native library are you loading? A reproducible example would be very useful for analyzing the root cause of your issue. Do you think you could put together a minimalistic sample project?

**Comment by astellingwerf** [comment] 2016-10-26 10:09
Hi Benjamin, I might have jumped the gun here. It turns out that the same issue occurs in 3.1 when running the entire build twice with the same daemon. Are you still interested?

The library is proprietary, so I'd need to spend quite an effort to create a minimalistic repro.

**Comment by bmuschko** [comment] 2016-10-26 12:10
Thanks, that's good to know. I'd say let's investigate this more if it's really bothersome to you. Your call. Is this also happening for your build with 2.x plus the daemon enabled?

**Comment by oehme** [comment] 2017-09-06 13:04
JavaExec spawns another process, so I don't see how it would leak classloaders. @astellingwerf is this still happening for you with recent Gradle versions?

**Comment by oehme** [comment] 2017-09-14 16:02
I'm going to close this issue, as there is not enough information to reproduce. Please don't hesistate to follow up with more information if this is still an issue.

**Closed by oehme** 2017-09-14 16:02 UTC
Labels: a:bug, affects-version:3.1, affects-version:3.2, from:contributor, in:daemon, is:not-actionable
