### ISSUE TITLE
Redirect warning when publishing to empty maven repository

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#711] opened 2016-10-19 12:16 UTC
When publishing to an empty file directory using uploadArchives a warning is emitted

> Could not find metadata org.gradle:solution/maven-metadata.xml in remote (file:///Users/Rene/training/labs/19-maven-uploading/solution/build/repo

on quiet log level. This should be redirected to info logging. Otherwise that confuses users.
### Expected Behavior

Given log message should not show up unless using `--info` or `--debug` logging.
### Current Behavior

Given log message appears by default (in "quiet" logging)
### Context

This unnecessarily adds to default build output.

**Comment by 06needhamt** [comment] 2016-10-20 17:20
I am interested on working on this issue however i am unsure on how to locate the code in question. Is there any documentation for the directory structure of Gradle?

**Comment by eriwen** [comment] 2016-10-20 20:42
@06needhamt Wonderful! Locating it is the toughest part. I would suggest looking for places where we try to resolve `maven-metadata.xml`. `subproject/dependency-management` is one place. It's possible you may need to navigate from there to code in `core` or `publish` to see where the logging is called.

Hope that helps!

**Comment by adammurdoch** [comment] 2016-10-20 21:12
I'm pretty sure that warning is produced by aether. Gradle uses this in `MavenDeployAction` and `MavenInstallAction` to do the work of publishing a maven module.

**Comment by eriwen** [comment] 2016-11-10 17:47
Hi @06needhamt. Any update on this? Need any other guidance?

**Comment by alsutton** [comment] 2017-09-17 09:17
The problem is triggered by the call in [MavenDeployAction](https://github.com/gradle/gradle/blob/489f72ee3076b4e5bbeef90512c7af5126f68a51/subprojects/maven/src/main/java/org/gradle/api/publication/maven/internal/action/MavenDeployAction.java#L69), which is a calls through to [Aether](https://github.com/sonatype/sonatype-aether/blob/50983e14b99ff694cbb150612352c621b3d7d695/aether-impl/src/main/java/org/sonatype/aether/impl/internal/DefaultRepositorySystem.java#L439). During the handling of that call the [code to merge the new artefact into the existing repository information](https://github.com/sonatype/sonatype-aether/blob/50983e14b99ff694cbb150612352c621b3d7d695/aether-impl/src/main/java/org/sonatype/aether/impl/internal/DefaultDeployer.java#L356) is triggers an [attempt to get the existing maven-metadata.xml](https://github.com/sonatype/sonatype-aether/blob/50983e14b99ff694cbb150612352c621b3d7d695/aether-impl/src/main/java/org/sonatype/aether/impl/internal/DefaultDeployer.java#L375) which [occurs on a background thread](https://github.com/sonatype/sonatype-aether/blob/50983e14b99ff694cbb150612352c621b3d7d695/aether-connector-wagon/src/main/java/org/sonatype/aether/connector/wagon/WagonRepositoryConnector.java#L431).

The call goes through to the wagon file provider and [triggers an exception](https://github.com/apache/maven-wagon/blob/d011d60a9cb061f213e646f09f48582d803cd390/wagon-providers/wagon-file/src/main/java/org/apache/maven/wagon/providers/file/FileWagon.java#L68), which is, of course, the most common way of propagating a file not found issue in Java. Unfortunately Aether treats all exceptions in this situation [in the same way](https://github.com/sonatype/sonatype-aether/blob/50983e14b99ff694cbb150612352c621b3d7d695/aether-connector-wagon/src/main/java/org/sonatype/aether/connector/wagon/WagonRepositoryConnector.java#L667), so this gets propagated back to Gradle using a generic "Something has gone wrong" mechanism.

So there are multiple components involved, but there seems to be only one way that this could be realistically fixed, but that involves hacking some logic into Gradle to detect this error and silently drop it (which should be behind a config option to avoid breaking backwards compatibility). 

The reason modifying Aether isn't feasible is because it seems to be abandonware :(. The sonartype repo [points to eclipse](https://github.com/sonatype/sonatype-aether/), and the [eclipse page is a redirect to their archived project list](http://www.eclipse.org/aether/).

So what do people think? Is hacky logic what people want or are there other options people think might work?

**Comment by alsutton** [comment] 2017-09-18 09:55
It looks like the [Maven project have switched to a different library](https://maven.apache.org/aether.html) This could be an option if someone has the time.

**Comment by eriwen** [comment] 2017-09-21 14:24
@alsutton Thank you for the thorough investigation. Introducing hacks to silently drop specific exceptions is something we try to avoid, so switching to a different library is an option. 

I'd wager this wouldn't quite make it to the top of our priority queue for some time, so I'd love to see a PR for this.

**Comment by alsutton** [comment] 2017-10-06 14:56
I've not had time to see this through, and this probably won't change in the future, so I'm going to write up what I've found so far in case anyone wants to pick this up.

The version of Aether current being pulled in is an old version by Sonatype, the project moved from Sonatype to Eclipse where a couple more releases were made, then the project was archived. Version 3.3 of maven was using the Eclipse version of Aether, 3.5 has moved to the new library.

Unfortunately moving from the Sonatype version of Aether to the Eclipse version isn't a straight drop-in replacement; 
- The package namespace has been changed to reflect the Eclipse home.
- There are a few API changes which need manual changes
- Gradle then fails to compile with the changes indicating there's more work to be done under the hood.

I've got my [work so far up on my GitHub fork](https://github.com/alsutton/gradle/commit/31f574b451fb4ace47fa7392fd1b1bd695e9f224), if anyone wants to pick it up please feel free.

**Comment by eriwen** [comment] 2017-10-20 00:03
@alsutton thanks again for the additional information; I hope others will be able to take what you've done and get this solved. 👏

**Comment by oehme** [comment] 2018-04-26 07:46
@ldaley Was this also fixed by https://github.com/gradle/gradle/commit/92e1617aac09b6f26bb921eccd7e3aa3131d049e#diff-afed11c0a1872ed31be4dfe32ed9bb23?

**Comment by bigdaz** [comment] 2019-05-22 23:42
This has been fixed #9445

**Closed by bigdaz** 2019-05-22 23:42 UTC
Labels: a:bug, affects-version:3.2, in:publishing-plugin
