### ISSUE TITLE
Allow importing BOMs as force constraints

### ISSUE THREAD

**Issue by ptriller** [gradle/gradle#1812] opened 2017-04-12 16:16 UTC
In some cases when a dependency is included transitively and a dependencyManagement section changes the version in another pom, then gradle resolves the resulting Version differently from Maven

Example: 

Project A has a dependency to artifact D in version 2
Project B has a dependency to the Artifact from Project A and a dependencyManagement of Artifact D to version 1 (in it's pom.xml)
Project C has a dependency to the Artifact of Project B.

If you do this with maven, then Project C has a transitive dependency to D in version 1
If you do it with gradle then Project C has a transitive dependency to D in version 2

I expected the versions to be the same. In my eyes the Maven behavior makes more sense.

To reproduce see this simple test setup:

 https://github.com/ptriller/gradle-bugreport

**Comment by oehme** [comment] 2017-09-20 17:19
This is a limitation in how we currently treat BOMs (we only apply them to the direct dependencies of a module). Instead, we should add the management section of the BOM as constraints on the module that imports that BOM.

**Comment by bigdaz** [comment] 2017-12-21 18:54
There are 2 issues here:
1. POM `<dependencyManagement>` elements do not apply transitively, they only apply to dependencies in the declaring module. We think this is the same behaviour as Maven, but we are considering making these apply transitively
2. A dependency constraint cannot _downgrade_ a dependency version for a transitive dependency. 

We are working to improve things in this space, but our aim is not to perfectly replicate the Maven resolution behaviour.

**Comment by ljacomet** [comment] 2018-08-21 15:41
Edited title to reflect required change to current Gradle behavior with `IMPROVED_POM_SUPPORT`

**Comment by ljacomet** [comment] 2018-09-04 14:16
This feature will be part of the BOM support in Gradle 5.0 - see #4422 for details

**Comment by ljacomet** [comment] 2018-09-11 15:26
This will be available in Gradle 5.0 through `enforcedPlatform`, watch release notes.

**Closed by ljacomet** 2018-09-11 15:26 UTC
Labels: a:feature, from:contributor, in:dependency-management

**Comment by sofax** [comment] 2019-01-09 07:47
BTW, the original title of the issue as reported by @ptriller was _"Version Resolution is wrong in some cases when a dependency uses dependencyManagement in it's pom.xml"_.

For reasons I don't know it has been modified (by @oehme, and then by @ljacomet ). The new title,  _"Allow importing BOMs as force constraints"_, has nothing to do with the actual issue. Misunderstanding?

**Comment by oehme** [comment] 2019-01-09 08:53
You're right, this was misclassified. 

However, the original issue is not correct either - Maven behaves exactly the same if you have a dependency chain like that. `<dependencyManagement>` on transitive dependencies in project B is ignored by project C. The attached example project doesn't show the project C case with Maven. If it did, you would see that it behaves the same as Gradle.

**Comment by sofax** [comment] 2019-01-09 10:08
> You're right, this was misclassified.
> 
> However, the original issue is not correct either - Maven behaves exactly the same if you have a dependency chain like that. `<dependencyManagement>` on transitive dependencies in project B is ignored by project C. The attached example project doesn't show the project C case with Maven. If it did, you would see that it behaves the same as Gradle.

I haven't checked the attached project, but I have encountered this exact problem in our environment, where the setup is exactly as described by the ticket author. Gradle and Maven definitely behave differently here, and the Maven behavior is the correct one.

The concrete situation is:
We have a custom artifact (let's call it `my-artifact`) that uses HK2 v2.5.0-b63 (e.g. `org.glassfish.hk2:hk2-locator:2.5.0-b63`). HK2 needs `jakarta.annotation-api-1.3.4.jar`, which had not been released yet when HK2 v2.5.0-b63 was released. So we added the following section to the `pom.xml` of `my-artifact`:

``
   <dependencyManagement>
      <dependencies>
         
         <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
            <version>1.3.3</version>
         </dependency>
      </dependencies>
   </dependencyManagement>
``
Thus `my-artifact` depends on `jakarta.annotation-api` v1.3.3 (and hence can be built).

Next I created a new Maven artifact (let's call it `deps`)  whose `pom.xml` lists `my-artifact` as a dependency. When I invoke `mvn dependency:copy-dependencies` on that new `pom.xml`, it copies `jakarta.annotation-api-1.3.3.jar`, as expected.

Finally I created a Gradle build script that corresponds to the `pom.xml` of the `deps` Maven artifact, i.e. it lists `my-artifact` as a dependency. I had to use a little workaround to be able to use the Copy task for the desired job:

``
configurations {
   depsToCheck.extendsFrom implementation
}

task copyDeps(type: Copy) {
   from configurations.depsToCheck
   into 'deps'
}

dependencies {
   implementation 'my-company.my-artifact:1.0.0'
}
``

Now, when I invoke `./gradlew copyDeps`, it will copy `jakarta.annotation-api` v1.3.4 instead of `jakarta.annotation-api` v1.3.3.

**Comment by oehme** [comment] 2019-01-09 10:12
Can you create a full reproducible project, including the Maven and Gradle example, please?

**Comment by sofax** [comment] 2019-01-09 10:13
> Can you create a full reproducible project, including the Maven and Gradle example, please?

Yes, but that will take a while.

**Comment by sofax** [comment] 2019-01-09 11:48
https://github.com/sofax/gradle-issue-1812

**Comment by sofax** [comment] 2019-01-09 13:41
@oehme: Can you tell me how the resolution strategy can be configured to enforce the Maven behavior? The Maven `pom.xml` of `demo-artifact` explicitly ensures that the correct version of the dependency is used. This _must not_ be (implicitly) overruled by a Gradle script that depends on `demo-artifact`.

**Comment by oehme** [comment] 2019-01-09 13:54
> The Maven pom.xml of demo-artifact explicitly ensures that the correct version of the dependency is used.

This is not how Gradle works. demo-artifact can't control the version of `annotation-api`. It only says which version it would like. But `glassfish` disagrees and wants a higher one, so Gradle chooses that, since it is more likely to work.

> This must not be (implicitly) overruled by a Gradle script that depends on demo-artifact.

There is no overruling here, just two competing dependencies and Gradle chooses the one that it is more likely to work.

> Can you tell me how the resolution strategy can be configured to enforce the Maven behavior?

You can't, because Maven's model inherently relies on the order of dependency declarations and just uses the first version it sees, which is a pretty broken strategy that we don't support. Instead Gradle considers all version declarations and conflict resolves them. If the resolution that Gradle picks is not what you'd like, you can use the [resolutionStrategy](https://docs.gradle.org/current/userguide/customizing_dependency_resolution_behavior.html#sec:dependency_resolve_rules) or a [force rule](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html#org.gradle.api.artifacts.ResolutionStrategy:force(java.lang.Object[])) to fix it up.

**Comment by sofax** [comment] 2019-01-09 13:58
That won't work in our case. I'm afraid we can't use Gradle then. :(

We need a tool that  downloads all the effective dependencies that are _actually used_ by our base technology artifacts, not the ones that Gradle thinks work better. 

Thanks for clarifying though.

**Comment by ljacomet** [comment] 2019-01-09 14:03
If you need such a strong contract, have a look at defining and [consuming a Maven BOM](https://docs.gradle.org/5.0/userguide/managing_transitive_dependencies.html#sec:bom_import) with the `enforcedPlatform` approach.
Note that Gradle 5.2 will also introduce the `java-platform` plugin to better support such bill of material definitions inside a Gradle project and give the ability to publish them as Maven BOM.

**Comment by sofax** [comment] 2019-01-09 14:12
Hmm ... I'm not sure how the use of `enforcedPlatform` can (generally) help me here. I assume it would have to be applied to _all_ the dependencies (i.e. all our base technology artifacts) - how does Gradle deal with potential conflicts then? 

But this whole discussion is beginning to make me wonder if there really is a "correct" way to handle this requirement. It would probably be more reasonable to deal with one base artifact at a time instead of processing the whole bunch in one script, as we can never know in which order the base artifacts will be referenced by a product.

**Comment by ljacomet** [comment] 2019-01-09 14:45
Defining a BOM would help in having a centralized source for the versions of the dependencies to be used by your product / platform.
Based on that, you would use the Maven BOM in your Maven projects at the different levels, making sure no surprise happens if a new path to a dependency is introduced.
And since the addition of `enforcedPlatform` to Gradle, you have a way to consume a BOM in a way that is Maven compatible: the platform forces the versions instead of just being a source of recommendations.

**Comment by sofax** [comment] 2019-01-09 15:00
We do have a BOM. However, sometimes artifacts must override transitive dependencies introduced by the BOM. 

Anyway, this is a problem I will have to solve. Thanks to both of you for your support! :) :+1:
