### ISSUE TITLE
init scripts from custom distributions are sometimes ignored

### ISSUE THREAD

**Issue by fritaly** [gradle/gradle#5090] opened 2018-04-18 16:50 UTC
It seems that Gradle 4.7 doesn't execute the init scripts stored in the "init.d" directory.

### Expected Behavior

The init scripts should be evaluated upon build.

### Current Behavior

The init scripts are simply ignored.

### Context

I use custom init scripts to pre-configure the access to Artifactory.

### Steps to Reproduce (for bugs)

In the "init.d" directory, create a file "fail.gradle" with the following content.

```
throw new RuntimeException("Fail on purpose !")
```

The build should fail when you run `./gradlew clean` with any build. It doesn't. The test works with Gradle 4.6 but not Gradle 4.7.

**Comment by marcphilipp** [comment] 2018-04-18 18:31
What happens when you run `./gradlew -I $HOME/.gradle/init.d/fail.gradle`?

**Comment by eriwen** [comment] 2018-04-18 18:45
Init scripts can be referenced [from various locations](https://docs.gradle.org/current/userguide/init_scripts.html#sec:using_an_init_script). Is it possible that one location works while another does not? @fritaly could you please specify exactly where and how you're referencing your init script?

**Comment by fritaly** [comment] 2018-04-18 20:50
Thanks for the quick replies. In my case, the init script is located inside the Gradle distribution (that's a custom distro I package). So on my Mac, the file is located at `~/.gradle/wrapper/dists/gradle-4.7-custom/75we120cqoyuuwxr53aaddz7l/gradle-4.7/init.d/fail.gradle`.

Interestingly, the init script is ignored when stored under `~/.gradle/wrapper/dists/gradle-4.7-custom/75we120cqoyuuwxr53aaddz7l/gradle-4.7/init.d` but things work when I move the script to `~/.gradle/init.d`.

Have things changed regarding init scripts embedded inside the Gradle distro ? This used to work in 4.6.

**Comment by big-guy** [comment] 2018-04-20 03:05
@fritaly I can't reproduce this.  Is it possible that you're not using the custom version that has the init script? 

A couple of things to check:
1. Are there any other Gradle daemons running when the build doesn't fail when it should?
1. If you add `println gradle.gradleHomeDir` to your build.gradle, do you see the expected path to the Gradle distribution with the init script?

**Comment by fritaly** [comment] 2018-04-20 08:11
Thanks @big-guy, the issue was indeed a lingering Gradle daemon running unnoticed in the background. I was sure there was none 🤦‍♂️ It started working as soon as I killed it.

Thanks and sorry for the inconvenience 👍

**Comment by marcphilipp** [comment] 2018-04-20 11:25
@fritaly No worries, thanks for letting us know!

**Comment by oehme** [comment] 2018-04-25 07:35
The daemon used should not matter. `init.d` scripts should be run regardless. This is a bug.

**Comment by DanielThomas** [comment] 2018-04-25 16:52
`init.d` might not be the only thing that differs in a custom distribution. We occasionally have to patch a distribution to temporarily fix an issue, and it's really useful to be able to do that without having to build an entire snapshot distribution (or update the version ourselves).

**Comment by oehme** [comment] 2018-04-25 17:11
Changing the Gradle jars themselves is not a use case we intend to officially support. This would require much more changes than just taking the distro into account for which daemon to start. E.g. caching would also be affected.

**Comment by DanielThomas** [comment] 2018-05-09 16:15
@oehme could the priority of this be reviewed please? This is seriously disruptive for those with custom distributions - we're having to manually `--stop` daemons several times a day to prevent Gradle from selecting the wrong daemon and failing builds.

**Comment by oehme** [comment] 2018-05-09 16:20
@DanielThomas It's already assigned to 4.9 and at the top of the backlog.

**Comment by oehme** [comment] 2018-05-09 16:33
@DanielThomas I don't recall you mentioning these problems before 4.7, have you experienced this with older versions? If it's a recent regression that would warrant a higher priority fix.

**Comment by DanielThomas** [comment] 2018-05-09 16:39
@oehme I _think_ we'd occasionally seen this before, but 4.7 definitely made things much worse.

**Comment by oehme** [comment] 2018-05-09 17:41
Okay, I can reproduce the issue. There is a test for it, but for some reason that I have yet to find the test doesn't catch this problem. The fix should be relatively easy, so I guess we can squeeze it in 4.8.

**Comment by oehme** [comment] 2018-05-09 17:56
[This change](https://github.com/gradle/gradle/commit/4ea452bc8ee181143b7f32b327a617b0c5d8e4dc) in 4.7 caused the problem. So this is indeed a recent problem and should go into 4.8.

**Comment by oehme** [comment] 2018-05-09 17:59
I discovered another issue - nested builds (like `buildSrc`) currently don't inherit the gradle home from their enclosing build, leading to the same init script-finding issue. This needs to be fixed as well.

**Comment by oehme** [comment] 2018-05-12 10:25
This is fixed for 4.8

**Closed by oehme** 2018-05-12 10:25 UTC
Labels: a:bug, from:contributor, in:core

**Comment by stmlange** [comment] 2018-05-17 20:43
Hi folks, first of all thanks for the fix and investigation!
Since it turned out to be an actual problem could this be (re)labeled with "affects-version:4.7" so it pops up as known issue in the release notes?
