### ISSUE TITLE
org.gradle.plugins.signing.Sign not compatible with config caching

### ISSUE THREAD

**Issue by bingranl** [gradle/gradle#20275] opened 2022-03-25 00:15 UTC
### Expected Behavior

Sign task should be compatible with configuration caching. ([user guide](https://docs.gradle.org/current/userguide/configuration_cache.html) lists gradle plugins which are not compatible with config caching including Sign plugin. But there doesn't seem to be a ticket tracking the incompatibility of Sign plugin.)

### Current Behavior

When config caching enabled(warning mode), we observed that

1. Warnings are raised in the first run complaining about type cannot be serialized (e.g. `org.gradle.api.internal.artifacts.configurations.DefaultConfiguration`)
2. Sign task doesn't work as expected and "asc" files are missing for all published artifacts.
3. Build fails in the following "config cached" run with error message "Could not load the value of field `toSignGenerator` of `org.gradle.plugins.signing.Signature`"

The most concerning thing is the fact that asc files are missing when running with config caching. This means we couldn't get the correct result even with `task.notCompatibleWithConfigurationCache` and it would potentially block making config caching on by default.

### Steps to Reproduce 
1. update `sdk.dir` in gradle.properties
2. run with config caching warning mode `./gradlew publishToMavenLocal`
3. check published artifacts in local maven repo, asc files are missing
[MyApplication.tar.gz](https://github.com/gradle/gradle/files/8346444/MyApplication.tar.gz)

**Comment by donat** [comment] 2022-03-25 09:35
Duplicate of  #13470.

**Closed by donat** 2022-03-25 09:35 UTC
Labels: in:signing-plugin, a:bug, to-triage

**Comment by bingranl** [comment] 2022-03-30 00:59
@donat This issue can be reproduced with a java library project without android plugin applied. I think this issue deserves a separate ticket which is to focus on making sure the signing task functionally works in the first run when config caching is "enabled" (either with `--configuration-cache-problems=warn` or with `notCompatibleWithConfigurationCache`) Maybe add to "7.5 RC1" like this [bug](https://github.com/gradle/gradle/issues/19959). What do you think?

[java_project.tar.gz](https://github.com/gradle/gradle/files/8375881/java_project.tar.gz)

**Comment by bingranl** [comment] 2022-06-09 19:21
Thanks for the fix, it works for me with `gradle-7.5-20220608002841+0000-bin.zip`
