### ISSUE TITLE
Nullmarked (jspecify)

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#31721] opened 2024-12-14 15:48 UTC
### Expected Behavior

could you add `@Nullmarked` to packages (the api) where packages are known to have the appropriate nullity annotations applied.

### Context

Tools like errorprone nullaway already support this but don't support `NonNullApi` yet https://github.com/uber/NullAway/issues/1084. in this case I believe its supported by name so you could have your own copy of the the annotation.

It would probably be easy enough for me to do this work if it'd be accepted; let me know if it would be accepted and if I should add the dependency or create a fork of that annotation.

**Comment by sdeleuze** [comment] 2024-12-16 11:37
I recommend closing this issue in favor of https://github.com/gradle/gradle/issues/24767 proper JSpecify migration.

**Comment by ljacomet** [comment] 2024-12-17 13:22
This issue will be closed as a duplicate of

* #24767

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

**Closed by ljacomet** 2024-12-17 13:22 UTC
Labels: a:feature, to-triage
