### ISSUE TITLE
Redirecting issue 348 from shadow plugin

### ISSUE THREAD

**Issue by yetanotherion** [gradle/gradle#3633] opened 2017-11-28 07:08 UTC
https://github.com/johnrengelman/shadow/issues/348
### Shadow Version
2.1
### Gradle Version
4.2
### Expected Behavior
Taking a single project build with an external script plugin
```
$ cat build.gradle
plugins {
    id "com.github.johnrengelman.shadow" version "2.0.1" apply false
}

apply plugin:'java-library'
apply from: 'external.gradle'
/* this works
shadowJar { 
 transform(com.github.jengelman.gradle.plugins.shadow.transformers.ApacheLicenseResourceTransformer)
} */
```

```
$ cat external.gradle
apply plugin: 'com.github.johnrengelman.shadow'

shadowJar {
  /* this does not work */
 transform(com.github.jengelman.gradle.plugins.shadow.transformers.ApacheLicenseResourceTransformer) 
}
```
Running 
```
$ gradle shadowJar
```
should not fail.

### Actual Behavior

```
$ gradle shadowJar
...
* What went wrong:
A problem occurred evaluating script.
> Could not get unknown property 'com' for task ':shadowJar' of type com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

It seems transformer cannot be used in script plugins. FYI
got the same issue using 
```
$ cat external.gradle
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "de.sebastianboegl.gradle.plugins:shadow-log4j-transformer:2.1.1"
    }
}
shadowJar {
  transform(de.sebastianboegl.gradle.plugins.shadow.transformers.Log4j2PluginsFileTransformer)
}
```
@johnrengelman suggested the issue was related to a missing import and that the issue
was more related to gradle/groovy rather than to the plugin.

Unfortunately, 
for 
* com.github.jengelman.gradle.plugins.shadow.transformers.ApacheLicenseResourceTransformer:
  * OK: adding the import in the build.gradle
  * NOK: adding the import in the external.gradle
* for de.sebastianboegl.gradle.plugins.shadow.transformers.Log4j2PluginsFileTransformer:
  * NOK: adding the import in the build.gradle
  * NOK: adding the import in the external.gradle

```
$ cat build.gradle
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "de.sebastianboegl.gradle.plugins:shadow-log4j-transformer:2.1.1"
    }
}

import de.sebastianboegl.gradle.plugins.shadow.transformers.Log4j2PluginsFileTransformer

plugins {
    id "com.github.johnrengelman.shadow" version "2.0.1" apply false
}

apply plugin:'java-library'
apply from: 'external.gradle'
```
```
$ cat external.gradle
apply plugin: 'com.github.johnrengelman.shadow'
shadowJar {
    transform(de.sebastianboegl.gradle.plugins.shadow.transformers.Log4j2PluginsFileTransformer)
}
```
```
$ gradle shadowJar
...
* What went wrong:
A problem occurred evaluating script.
> de.sebastianboegl.gradle.plugins.shadow.transformers.Log4j2PluginsFileTransformer cannot be cast to com.github.jengelman.gradle.plugins.shadow.transformers.Transformer

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

If the issue is related to a missing import, we'd like to add the import it in the external.gradle, so that all shadow logic is in the external.gradle file.

Do you see a way around it?

**Comment by oehme** [comment] 2017-11-28 20:33
This is a limitation of scripts that we are unlikely to change anytime soon. The classloaders of the script and the project applying it are independent, so you are loading two different versions of the library. You have several options:

- add your dependencies to buildSrc instead, that way they are visible to all build logic no matter which script
- put all shadow related logic in the external script
- put all shadow related logic in the project's build script

**Comment by oehme** [comment] 2017-11-28 20:35
Closing as a duplicate of https://github.com/gradle/gradle/issues/1370

**Closed by oehme** 2017-11-28 20:35 UTC

**Comment by yetanotherion** [comment] 2017-11-29 09:14
* put all shadow related login in the external script

```
$ cat build.gradle
apply from: 'external.gradle'
$ cat external.gradle
buildscript {
    repositories {
        jcenter()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "de.sebastianboegl.gradle.plugins:shadow-log4j-transformer:2.1.1"
        classpath "com.github.jengelman.gradle.plugins:shadow:2.0.1"
    }
}
apply plugin: 'java-library'
apply plugin: 'com.github.johnrengelman.shadow'
$ gradle shadow
FAILURE: Build failed with an exception.

* Where:
Script '/Users/j.alberdi/debug/shadow/external.gradle' line: 15

* What went wrong:
A problem occurred evaluating script.
> Plugin with id 'com.github.johnrengelman.shadow' not found.

```
Note that
```
$ cat build.gradle
buildscript {
    repositories {
        jcenter()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "de.sebastianboegl.gradle.plugins:shadow-log4j-transformer:2.1.1"
        classpath "com.github.jengelman.gradle.plugins:shadow:2.0.1"
    }
}

apply plugin: "java-library"
apply plugin: "com.github.johnrengelman.shadow"

$ gradle shadow 

BUILD SUCCESSFUL in 0s
1 actionable task: 1 up-to-date
```
works.

This is most probably an issue related to the shadow plugin, thanks for the inputs!

**Comment by yetanotherion** [comment] 2017-11-29 09:45
Actually with:
```$ cat build.gradle
apply from: 'external.gradle'
$ cat external.gradle
buildscript {
    repositories {
        jcenter()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "de.sebastianboegl.gradle.plugins:shadow-log4j-transformer:2.1.1"
        classpath "com.github.jengelman.gradle.plugins:shadow:2.0.1"
    }
}
apply plugin: 'java-library'
apply plugin: com.github.jengelman.gradle.plugins.shadow.ShadowPlugin.class

$ gradle shadow

BUILD SUCCESSFUL in 1s
1 actionable task: 1 up-to-date
```
As far as I understand, the 
- **apply plugin: 'com.github.johnrengelman.shadow'**: seems to look for the file
```
$ tail -1 META-INF/gradle-plugins/com.github.johnrengelman.shadow.properties
implementation-class=com.github.jengelman.gradle.plugins.shadow.ShadowPlugin
````

in the classloader of the build.gradle, when 
- **apply plugin: com.github.jengelman.gradle.plugins.shadow.ShadowPlugin.class**
uses the classloader of the script plugin, is my understanding correct?

**Comment by yetanotherion** [comment] 2017-11-29 09:53
It seems to be related to
https://github.com/gradle/gradle/issues/1262
