### ISSUE TITLE
Improve context logging in plain console for parallel build

### ISSUE THREAD

**Issue by szpak** [gradle/gradle#2462] opened 2017-07-13 11:17 UTC
Currently (as of 4.0.1) the logging in the plain console (CI service/dumping output to a file) with `--info` enabled doesn't provide information about context (task) on behalf which a given line is executed. It makes it really hard to determine some issues when parallel execution (for instance problems with task rebuilding with Build Cache enabled - `Appending inputPropertyHash for ...` are mixed up). It's especially painful using CI server executor with 32 vCPUs...

### Expected Behavior
Ability to clearly determine what task (or processing context in general) a given printed line is connected to. It could be a line prefix pointing to a task or even to a thread id or a worker number. Context switching would need to be marked in the second case to see where given thread/worked started/finished processing of a given unit of work.

### Current Behavior
There is no easy way to connect a printed line to a task if parallel execution is enabled.

### Your Environment
Gradle 4.0.1, Jenkins to execute Gradle jobs (can be anything with non interactive console)

**Comment by bmuschko** [comment] 2017-07-18 21:08
You think that's the same issue as https://github.com/gradle/gradle/issues/2221 which we are currently working on. @eriwen Is that a correct assessment?

**Comment by szpak** [comment] 2017-07-18 21:33
It seems to be another remedy for the same problem. As I understand correctly logs will be grouped by tasks (in execution phrase) giving the whole logs from a given execution put together (not mixed up with other tasks), right @eriwen? If yes, the line prefix would be probably unnecessary.

**Comment by bmuschko** [comment] 2017-07-18 21:42
@szpak That's correct. The output would look similar to the rich console output task grouping.

**Comment by eriwen** [comment] 2017-07-19 17:33
That's correct @szpak. This will be (hopefully) a part of Gradle 4.2.

**Comment by eriwen** [comment] 2017-07-19 23:00
Given that, it seems that we should close this as a duplicate of #2221.

**Closed by eriwen** 2017-07-19 23:00 UTC
Labels: a:feature, from:contributor, in:cli
