### ISSUE TITLE
Gradle 8.4 should support running on Java 21

### ISSUE THREAD

**Issue by melix** [gradle/gradle#26543] opened 2023-09-26 13:53 UTC
### Current Behavior

The current release of Gradle 8.4-rc-1 doesn't support running on Java 21. While the docs say that Java 21 is supported, it's not accurate as to do this, you have to use toolchains.

Toolchains support used to be _optional_ in previous releases, when support for compiling for a particular release was announced. The problem is that toolchain support is still quite broken and cannot be used in many cases.

Trying to run Gradle with Kotlin DSL + Java 21 yields this error : https://github.com/melix/astro4j/actions/runs/6276469081/job/17046224619#step:6:31

### Expected Behavior

It _is_ possible to run with 21, as long as you do, in `buildSrc`:

```
tasks.withType<KotlinJvmCompile>().configureEach {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_17)
    }
}

tasks.withType<JavaCompile>().configureEach {
    targetCompatibility = "17"
}
```

So the expected behavior would be that the convention value for `jvmTarget` (Kotlin) and possibly `targetCompatibility` (Java) should be the highest version that Gradle supports at the moment of the release.

This allows running with JDK 21, while the build scripts would be compiled for 17.

I think making this change would remove quite a few headaches to users.

### Steps to Reproduce

Try to run Gradle KTS with Java 21, see it fail.

### Gradle version

8.4-rc-1

**Comment by octylFractal** [comment] 2023-09-26 16:12
> Toolchains support used to be optional in previous releases, when support for compiling for a particular release was announced.

This has not been the case since 8.1, when Java 20 support for only compiling and testing was added. Prior to this we waited until Kotlin was ready to document that we officially support _either_ case, which resulted in Gradle not officially supporting a JDK for much longer after a new release.

My belief was that splitting the support into "compiling and testing" and "executing Gradle" would be helpful by allowing users to use Gradle for a new release sooner, but it seems it may be causing more confusion instead.

**Comment by melix** [comment] 2023-09-26 16:23
Right, thanks for the explanation. I still think that the suggested change is quite straightforward and would make it easier to run Gradle on JDK 21.

**Comment by rpalcolea** [comment] 2023-09-28 01:13
Lurking here.

I think there has to be some context on which Gradle out of the box plugins can/can't do. For example, I believe people could think that using toolchains will solve the problem because of "compiling and testing" but once you introduce something like PMD or checkstyle you might get into surprises. 

For example, PMD still has work to support Java 21 language features per https://github.com/pmd/pmd/issues/4583 so folks might get into trouble there.

Perhaps adding a note in https://docs.gradle.org/8.4-rc-2/userguide/compatibility.html for folks to be aware?

**Comment by jbartok** [comment] 2023-10-02 08:41
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/25574

Please add your use case and 👍 to that issue.

***

Most likely this won't make it into Gradle `8.4`.

**Closed by jbartok** 2023-10-02 08:41 UTC
Labels: a:bug, to-triage

**Comment by melix** [comment] 2023-10-02 09:04
That is unfortunate, I think it harms Gradle's reputation that it doesn't proper support the latest JDK releases. It seems that #25574 doesn't cover what is suggested here, which seems IMHO a reasonable workaround to implement.

**Comment by eskatos** [comment] 2023-10-18 13:01
Some form of this went into `master` Today for 8.5.
* https://github.com/gradle/gradle/pull/26758

With Kotlin 1.9.20 this won't be necessary anymore though and will be reverted.
For context, also see
* https://github.com/gradle/gradle/issues/26764
