### ISSUE TITLE
Allow platform developers to see all the nagging with location

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#25872] opened 2023-07-23 21:12 UTC
### Expected Behavior

Same as <8.3: when there are nagging, and the stack traces are turned on (--stacktrace or `org.gradle.deprecation.trace` or equivalent), console logs list all the stacktraces without shortening anything.

Hopefully there would be a System property we can set similar to `-Dorg.gradle.deprecation.trace=true` to allow more than 50.

### Current Behavior

Gradle 8.3-rc-1 changed behavior and some nags don't have stack traces because `org.gradle.internal.problems.DefaultProblemDiagnosticsFactory.DefaultProblemStream#getImplicitThrowable` returns null after 50 nags (hard-coded).

### Context (optional)

An example use case: Let's say a company has a large application that has hundreds of modules, and there's a third party proprietary plugin applied to each module. This third party plugin has a very slow release cycle and they take deprecation fixes as low priority. Let's also say there's another plugin which uses deprecated APIs. This plugin's deprecation won't be easily visible until the first one is fixed, because the first one overwhelms the nagging subsystem and exhaust the counter. Humans could filter through the same message and stack easily, but only if it's output! If we want to fix everything else apart from that overwhelming plugin, there's no recourse.

With this recent change, the second plugin's deprecation will show up in the logs (without a stacktrace), it'll be hard to diagnose, potentially having to debug Gradle internals just to figure out where it is coming from.

Note: we don't even need a huge project, just one noisy plugin! The above was the simplest example I could think of.

cc @adammurdoch

### Steps to Reproduce

A build with more than 50 nagging deprecations.

### Gradle version

Gradle 8.3-rc-1

### Gradle version that used to work

Gradle 8.2.1

**Comment by ov7a** [comment] 2023-07-24 08:25
Thank you for providing a valid report.

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by TWiStErRob** [comment] 2023-07-24 12:30
Note: I was wrong in OP, we don't need `--stacktrace`, only `--warning-mode` to list all with location.

Here's a trivial reproducer:
 * https://github.com/TWiStErRob/repros/tree/main/gradle/deprecation-gradle83_stacktrace-limit50
 * `gradlew --warning-mode=all --no-daemon`  
  (No daemon! Because the last deprecation relies on class-loading being triggered.)

Actual (8.3-rc-1): notice there's no indication where `ClosureBackedAction` is used.
```
> Configure project :
Build file 'P:\projects\bugs\gradle\deprecationStackTraces-gradle83_limit50\build.gradle': line 6
The org.gradle.api.plugins.BasePluginConvention type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.3-rc-1/userguide/upgrading_version_8.html#base_convention_deprecation
        at build_dfpxcj4kl23iw30iqwed4n36w.run(P:\projects\bugs\gradle\deprecationStackTraces-gradle83_limit50\build.gradle:6)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
Build file 'P:\projects\bugs\gradle\deprecationStackTraces-gradle83_limit50\build.gradle': line 6
The org.gradle.api.plugins.Convention type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.3-rc-1/userguide/upgrading_version_8.html#deprecated_access_to_conventions
        at build_dfpxcj4kl23iw30iqwed4n36w.run(P:\projects\bugs\gradle\deprecationStackTraces-gradle83_limit50\build.gradle:6)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
The org.gradle.util.ClosureBackedAction type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.3-rc-1/userguide/upgrading_version_7.html#org_gradle_util_reports_deprecations
```

Expected (8.2.1): all 3 show location
```
Build file 'P:\projects\bugs\gradle\deprecationStackTraces-gradle83_limit50\build.gradle': line 6
The org.gradle.api.plugins.BasePluginConvention type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.2.1/userguide/upgrading_version_8.html#base_convention_deprecation
        at build_dfpxcj4kl23iw30iqwed4n36w.run(P:\projects\bugs\gradle\deprecationStackTraces-gradle83_limit50\build.gradle:6)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
Build file 'P:\projects\bugs\gradle\deprecationStackTraces-gradle83_limit50\build.gradle': line 6
The org.gradle.api.plugins.Convention type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.2.1/userguide/upgrading_version_8.html#deprecated_access_to_conventions
        at build_dfpxcj4kl23iw30iqwed4n36w.run(P:\projects\bugs\gradle\deprecationStackTraces-gradle83_limit50\build.gradle:6)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
Build file 'P:\projects\bugs\gradle\deprecationStackTraces-gradle83_limit50\build.gradle': line 10
The org.gradle.util.ClosureBackedAction type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.2.1/userguide/upgrading_version_7.html#org_gradle_util_reports_deprecations
        at build_dfpxcj4kl23iw30iqwed4n36w.run(P:\projects\bugs\gradle\deprecationStackTraces-gradle83_limit50\build.gradle:10)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
```

**Comment by wolfs** [comment] 2023-07-25 14:45
Fixed via https://github.com/gradle/gradle/pull/25880

Aka if you use `--warning-mode=all` or `--warning-mode=fail` then you'll get all stacktraces.

**Closed by wolfs** 2023-07-25 14:45 UTC
Labels: a:regression, in:deprecation-logging, in:problems
