### ISSUE TITLE
Allow setting Java Toolchain `determineReleaseState` via builder DSL/property to use EA releases

### ISSUE THREAD

**Issue by GavinRay97** [gradle/gradle#21227] opened 2022-07-11 16:22 UTC
I wanted to use JDK 19 with Gradle 7.6 master nightly releases

However, it doesn't find the JDK binary. This is because the release type is hardcoded as `ga`, where 19 requires `ea`.
It would be great to give users more control if needed over how to construct Toolchain binary URLs so that preview JDK's could be used 🙂 

https://github.com/gradle/gradle/blob/7af2e5edf3d99eb9bda3b611cf22af70b1a0dde5/subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/install/internal/AdoptOpenJdkRemoteBinary.java#L159-L162

https://github.com/gradle/gradle/blob/7af2e5edf3d99eb9bda3b611cf22af70b1a0dde5/subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/install/internal/AdoptOpenJdkRemoteBinary.java#L93-L106

**Comment by donat** [comment] 2022-07-13 14:31
Duplicate of #18168

**Closed** 2022-07-13 14:33 UTC
Labels: a:feature, to-triage
