### ISSUE TITLE
Gradle fails to resolve classes from local modules with the same name.

### ISSUE THREAD

**Issue by colinrtwhite** [gradle/gradle#22867] opened 2022-11-27 03:41 UTC
Two local modules with the same name, but different groups only resolve the classes from whichever dependency is declared first in the `dependencies` block.

### Expected Behavior
Gradle should resolve classes from both local modules.

### Current Behavior
Gradle only resolves the classes from which dependency is declared first.

### Context
Running into this issue as part of upgrading this project to use 7.6: https://github.com/cashapp/redwood/pull/554
I'm not sure if this issue is specific to 7.6, but we ran into it as part of upgrading.
Seems potentially relate to https://github.com/gradle/gradle/issues/847, but the work-around to change the group didn't work for me.

### Steps to Reproduce 
Repro repo: https://github.com/colinrtwhite/gradle_same_module_name_bug

1. Run `./gradlew assemble`.
2. Note that `main` fails to compile as the `Test2` class is unresolved. `Test1` is resolved.
3. Change the order of the dependencies so `implementation project(':test2:widget')` is first.
4. Note that `main` fails to compile as the `Test1` class is unresolved. `Test2` is resolved.

### Your Environment
JDK 19
Gradle 7.6

**Comment by eskatos** [comment] 2022-11-29 11:01
The very same happens with Gradle 7.5, or 7.0. I adjusted the title according to that.

**Comment by eskatos** [comment] 2022-11-30 10:22
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/847

Please add your 👍 to that issue.

----

Looking at this again, your reproducer uses the same group, so the same GAV coordinates, for both projects. If you can share a reproducer with proper coordinates we can consider reopening this.

**Closed by eskatos** 2022-11-30 10:22 UTC
Labels: closed:duplicate, in:multi-projects
