### ISSUE TITLE
InputChanges can not get correct ChangeType for @Classpath inputFiles

### ISSUE THREAD

**Issue by KaiyuanZhao** [gradle/gradle#27163] opened 2023-11-26 09:11 UTC
### Current Behavior

```
@get:Incremental
@get:Classpath
abstract val inputFiles: ConfigurableFileCollection
```
- add javac output dir into inputFiles
- add some empty jar into inputFiles

Execute the task and we can get the correct increment file through InputChanges.

Next we added a new class into javac output dir and execute task again. A jar that still exists in inputFiles is considered ChangeType.REMOVED by InputChanges.

### Expected Behavior

A jar that still exists in inputFiles should not be considered as ChangeType.REMOVED by InputChanges.

### Context (optional)

In some cases, the dependent jar does not contain any classes. AGP's DexArchiveBuilderTask use this way to check incremental inputs, and we got some crash when we compile our APP.

### Steps to Reproduce

[demo_classpath.zip](https://github.com/gradle/gradle/files/13466319/demo_classpath.zip)
- ./gradlew incrementalClasspathTest
- ./gradlew incrementalClasspathTest -PINCREMENTAL=true

### Gradle version

8.4

### Your Environment (optional)

- JDK17
- AGP8.1.4

**Comment by cobexer** [comment] 2023-11-28 13:35
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.
***
This looks like related to
* #17916

but from playing a little bit with the reproducer we seem to get an `ADDED` event for one file and a `REMOVED` event for the other file.
Could this be a flaw in the detection logic below (lifted from the reproducer)?
```kotlin
    private fun getChanged(
        inputChanges: InputChanges,
        input: FileCollection
    ): Set<FileChange> {
        val fileChanges = mutableMapOf<File, FileChange>()
        inputChanges.getFileChanges(input).forEach { change ->
            val currentValue = fileChanges[change.file]
            if (currentValue == null || (currentValue.changeType == ChangeType.REMOVED && change.changeType == ChangeType.ADDED)) {
                fileChanges[change.file] = change
            }
        }
        return fileChanges.values.toSet()
    }
```

**Comment by KaiyuanZhao** [comment] 2023-11-30 07:48
@cobexer By the way, I copied this detection logic from AGP source code at [this link](https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:build-system/gradle-core/src/main/java/com/android/build/gradle/internal/tasks/DexArchiveBuilderTask.kt;l=447), and we got crashed at [this line](https://cs.android.com/android-studio/platform/tools/base/+/refs/tags/studio-2022.3.1:build-system/gradle-core/src/main/java/com/android/build/gradle/internal/tasks/DexArchiveBuilderTaskDelegate.kt;l=553).
However, it seems that AGP has fixed the problem, but only by removing the throwing exception at [this link](https://issuetracker.google.com/issues/308401803). And as mentioned above, this problem is similar to https://github.com/gradle/gradle/issues/27061.

**Comment by lptr** [comment] 2023-12-07 09:02
Would #27061 solve your issue? Let me close this one as a duplicate, and if you disagree, we can reopen it.

**Closed by lptr** 2023-12-07 09:02 UTC
Labels: a:bug, in:execution-engine, in:input-normalization
