### ISSUE TITLE
Generated java files can end up in `build/classes` dir

### ISSUE THREAD

**Issue by wisechengyi** [gradle/gradle#5728] opened 2018-06-18 23:16 UTC
### Env
Gradle 4.7
Kotlin 1.2.21

### Expected Behavior
Generated java files should not be in `classes` dir.

### Current Behavior
Java files can be generated into  bundled together with APKs as resources.
```
$ find -L build -type f -name '*.java'
build/projects/lib/example/core-java/classes/java/main/tv/example/chatman/model/AutoValue_Chat.java
build/projects/lib/example/core-java/classes/java/main/tv/example/chatman/model/AutoValue_History.java
build/projects/lib/example/core-java/classes/java/main/tv/example/chatman/model/AutoValue_Join.java
...
```
Please note our build dirs are `$repo_root/build/projects/<project path>` instead of the default `$repo_root/<project_path>/build/`, but should not affect the nature of this issue.

### What should happen 
Generated java files should go under `$buildDir/generated/...`

### Steps to Reproduce (for bugs)
Let me know if I should provide a minimal repro, since I was hoping the symptom would be obvious enough.

**Comment by cesar1000** [comment] 2018-06-19 00:42
For some extra context, the default behavior of the `JavaCompile` task is to generate files into the classes directory. We found that this results in the generated files being packaged in the generated jar file as resources, which will cause them to be shipped in the application's apk. This is typically unintended, and it seems like gradle should discourage it - either by setting a default directory for generated source, or by issuing a warning if the generated directory is unset.

**Comment by oehme** [comment] 2018-06-25 10:54
Duplicate of #5728

**Closed by oehme** 2018-06-25 10:54 UTC

**Comment by marcphilipp** [comment] 2018-06-25 11:40
@oehme I'm sure you didn't mean #5728 because this is #5728. 😉

**Comment by marcphilipp** [comment] 2018-06-25 11:41
#4956?

**Comment by oehme** [comment] 2018-06-25 11:44
Indeed :)
