### ISSUE TITLE
Add more granular control for resolution of source jars

### ISSUE THREAD

**Issue by erdi** [gradle/gradle#11247] opened 2019-11-06 10:54 UTC
On my project, we're resolving artifacts from a repository (namely https://packages.atlassian.com/maven-closedsource-local) which allows unauthenticated resolution of binary artifacts but responds with 401 status code when attempting to resolve source artifacts. These 401 responses are treated as a resolution error by Gradle and it attempts re-resolution of source jars every time `ideaModule` task is executed. This unnecessarily and significantly slows down the execution of that task.

What I'm proposing is to build on the excellent [Matching repositories to dependencies](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec::matching_repositories_to_dependencies) feature which we are already using and extend it to provide greater control over how source jars are being resolved from repositories. My idea is that certain repositories could be excluded from resolution of source jars (maybe similarly to what this does for resolution of non-snapshot artifacts):
```
repositories {
    maven {
        mavenContent {
            snapshotsOnly()
        }
    }
}
```
The above is just an idea - any mechanism that will allow me to specify not to resolve source jars for certain artifacts or not to resolve source jars from certain repositories will solve the issue for me. Also, if there is a way to solve my problem with what's already provided in the tool then I would be grateful for any pointers.

**Comment by oehme** [comment] 2020-11-15 20:28
There's actually already a solution: Declare the repo with

```
content {
  onlyForAttribute(Category.CATEGORY_ATTRIBUTE, objects.named(Category, Category.LIBRARY))
}
```
and source/javadoc requests will no longer be made.

This only works by accident at the moment. The IDEs use `ArtifactResolutionQuery` to get at the sources and javadoc. Behind the scenes, `ArtifactResolutionQuery` uses a detached `Configuration` without any attributes. So if you define **any** attribute filter, then that repository will not be used for any `ArtifactResolutionQuery`s. I chose Category.LIBRARY for clarity.

I think that the above should work by design instead of by accident, by making `ArtifactResolutionQuery` use variants behind the scenes.

**Comment by erdi** [comment] 2020-11-15 20:43
Thanks for providing me with a solution, @oehme!

**Comment by ljacomet** [comment] 2021-11-15 17:19
Closing as there is a workaround and we are looking at replacing `ArtifactResolutionQuery` with something more variant aware.

**Closed by ljacomet** 2021-11-15 17:19 UTC
Labels: a:feature, in:dependency-resolution
