### ISSUE TITLE
Documentation: No navigation pane when reading on smartphone

### ISSUE THREAD

**Issue by ksa-real** [gradle/gradle#23550] opened 2023-01-16 12:28 UTC
It is impossible to read through multiple docs pages on mobile devices as there is no navigation section. If the browser width is too small, then the navigation pane just disappears. On desktop open e.g. [this link](https://docs.gradle.org/current/userguide/build_lifecycle.html), and make the browser width smaller until the page layout changes to mobile-style. On mobile just open the provided page. There is no navigation control to move to the next page. 

### Expected Behavior

The navigation (table of contents) section is available.

### Current Behavior

Navgiation section is not available in mobile browser

**Comment by jbartok** [comment] 2023-01-20 10:00
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/15263

Please add your 👍 to that issue.

**Closed by jbartok** 2023-01-20 10:00 UTC
Labels: a:bug, to-triage
