### ISSUE TITLE
Module dependency iml files are being generated with scope PROVIDED

### ISSUE THREAD

**Issue by oilers** [gradle/gradle#1557] opened 2017-03-09 23:34 UTC
When importing a gradle project, all dependencies are being marked as scope="PROVIDED"

This prevents anything from running correctly through the IDE
### Expected Behavior
The Module iml files should have lines like these from 3.3: 
`~/code/my-app/.idea/modules/my-app_main.iml`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<module external.linked.project.id="my-app:main" external.linked.project.path="$MODULE_DIR$/../.." external.root.project.path="$MODULE_DIR$/../.." external.system.id="GRADLE" external.system.module.group="my.app" external.system.module.type="sourceSet" external.system.module.version="1.0.0-2" type="JAVA_MODULE" version="4">
...snip...
    <orderEntry type="library" name="Gradle: org.codehaus.groovy:groovy-all:2.4.9" level="project" />
    .....snip....
    <orderEntry type="library" name="Gradle: commons-logging:commons-logging:1.2" level="project" />
  </component>
</module>
```
### Current Behavior
When generating the same file in 3.4.1 I get this: 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<module external.linked.project.id="my-app:main" external.linked.project.path="$MODULE_DIR$/../.." external.root.project.path="$MODULE_DIR$/../.." external.system.id="GRADLE" external.system.module.group="my.app" external.system.module.type="sourceSet" external.system.module.version="1.0.0-2" type="JAVA_MODULE" version="4">
...snip...
    <orderEntry type="library" scope="PROVIDED" name="Gradle: org.codehaus.groovy:groovy-all:2.4.9" level="project" />
    ...snip...
    <orderEntry type="library" scope="PROVIDED" name="Gradle: commons-logging:commons-logging:1.2" level="project" />
  </component>
</module>
```
The `scope="PROVIDED"` is the issue

### Context
This means anytime I try and run my app, it fails loading anything. Any scripts I create also can't find any classes.

### Steps to Reproduce (for bugs)
1. Have a gradle project (possibly with groovy)
1. Import it with 3.4.1
1. Inspect the `.idea/modules/my-app_main.iml` file

**Comment by markthornton** [comment] 2017-03-10 13:33
I found almost the same - a handful of dependencies were marked as compile, but most were provided.

I am using org.springframework.build.gradle:propdeps-plugin:0.0.7 to give a provided configuration. I don't know if this is part of the problem.

Had to go back to 3.3 as I don't have time to debug this issue.

**Comment by bmuschko** [comment] 2017-03-13 22:38
This is a duplicate of https://github.com/gradle/gradle/issues/1276. Please see instructions on how to fix it there.

**Closed by bmuschko** 2017-03-13 22:38 UTC
