### ISSUE TITLE
Support external source dependencies

### ISSUE THREAD

**Issue by yoni386** [gradle/gradle#2717] opened 2017-08-14 11:57 UTC
Can Gradle fetch and link library from external repository for c++ (e.g. github)? 
As in Cargo (Rust), go, nodejs and etc?

Example:
gem "nokogiri", :git => "git://github.com/tenderlove/nokogiri.git", :branch => "1.4"
1) Is this something Gradle would consider supporting in the future (or does it already)?

dependencies {
     compile git: "git://github.com/someproject/someproject.git", branch: "1.4"
}

**Comment by eljobe** [comment] 2017-08-16 12:36
Good timing. We're actively working on implementing a feature like this in Gradle. No promises on the exact delivery timeframe, but I expect it will make it into one of the next few minor versions of gradle.

**Comment by yoni386** [comment] 2017-08-16 14:03
Great. What should I look for? Is there name of feature or version?

**Comment by eljobe** [comment] 2017-08-16 14:28
We're probably calling it `Source Dependencies` or `External Source Dependencies`

The work is being tracked in [this epic](https://github.com/gradle/gradle-native/issues/42) on the gradle-native board, but we haven't got all the work chopped up and added to that epic yet.  That issue is best viewed with the [ZenHub browser extension](https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd) installed.

**Comment by bigdaz** [comment] 2017-11-13 23:38
Duplicate of gradle/gradle-native#42

**Closed by bigdaz** 2017-11-13 23:38 UTC
Labels: a:feature, from:contributor, in:dependency-management
