### ISSUE TITLE
Could not query file systems: could not get volume information (errno 1331) on Windows when mapped remote file system is unavailable

### ISSUE THREAD

**Issue by Pugga12** [gradle/gradle#16802] opened 2021-04-12 20:59 UTC
When I build my project, an error message is printed even though the build was successful
### Expected Behavior
> Configure project :
System Info: Java Version: 16, JVM: 16+36, OS Version: Windows 10 amd64

BUILD SUCCESSFUL in 7s

### Current Behavior

```text
BUILD SUCCESSFUL in 7s
10 actionable tasks: 8 executed, 2 up-to-date
Unable to watch the file system for changes
net.rubygrapefruit.platform.NativeException: Could not query file systems: could not get volume information (errno 1331
        at net.rubygrapefruit.platform.internal.PosixFileSystems.getFileSystems(PosixFileSystems.java:32)
        at org.gradle.internal.watch.vfs.impl.DefaultWatchableFileSystemDetector.detectUnsupportedFileSystems(DefaultWatchableFileSystemDetector.java:64)
        at org.gradle.internal.watch.registry.impl.WatchableHierarchies.removeUnwatchableFileSystems(WatchableHierarchies.java:113)
        at org.gradle.internal.watch.registry.impl.WatchableHierarchies.removeUnwatchableContent(WatchableHierarchies.java:82)
        at org.gradle.internal.watch.registry.impl.HierarchicalFileWatcherUpdater.buildFinished(HierarchicalFileWatcherUpdater.java:98)
        at org.gradle.internal.watch.registry.impl.DefaultFileWatcherRegistry.buildFinished(DefaultFileWatcherRegistry.java:146)
        at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem$2.lambda$call$0(WatchingVirtualFileSystem.java:199)
        at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem.withWatcherChangeErrorHandling(WatchingVirtualFileSystem.java:320)
        at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem.access$1000(WatchingVirtualFileSystem.java:53)
        at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem$2.call(WatchingVirtualFileSystem.java:199)
        at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem$2.call(WatchingVirtualFileSystem.java:179)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
        at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem.lambda$beforeBuildFinished$5(WatchingVirtualFileSystem.java:179)
        at org.gradle.internal.vfs.impl.VfsRootReference.update(VfsRootReference.java:40)
        at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem.beforeBuildFinished(WatchingVirtualFileSystem.java:179)
        at org.gradle.tooling.internal.provider.FileSystemWatchingBuildActionRunner.run(FileSystemWatchingBuildActionRunner.java:93)
        at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:41)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:49)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:44)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:44)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.lambda$execute$0(InProcessBuildActionExecuter.java:59)
        at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:58)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.BuildTreeScopeLifecycleBuildActionExecuter.lambda$execute$0(BuildTreeScopeLifecycleBuildActionExecuter.java:34)
        at org.gradle.internal.buildtree.BuildTreeState.run(BuildTreeState.java:53)
        at org.gradle.launcher.exec.BuildTreeScopeLifecycleBuildActionExecuter.execute(BuildTreeScopeLifecycleBuildActionExecuter.java:33)
        at org.gradle.launcher.exec.BuildTreeScopeLifecycleBuildActionExecuter.execute(BuildTreeScopeLifecycleBuildActionExecuter.java:28)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:104)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:55)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:64)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:37)
        at org.gradle.tooling.internal.provider.SessionScopeLifecycleBuildActionExecuter.lambda$execute$0(SessionScopeLifecycleBuildActionExecuter.java:54)
        at org.gradle.internal.session.BuildSessionState.run(BuildSessionState.java:67)
        at org.gradle.tooling.internal.provider.SessionScopeLifecycleBuildActionExecuter.execute(SessionScopeLifecycleBuildActionExecuter.java:50)
        at org.gradle.tooling.internal.provider.SessionScopeLifecycleBuildActionExecuter.execute(SessionScopeLifecycleBuildActionExecuter.java:36)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:59)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:58)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:42)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:47)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:31)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:65)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:29)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:84)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base/java.lang.Thread.run(Thread.java:831)
```

### Context

This issue does not affect me, although this is a bug
### Steps to Reproduce 

1. Use gradle 7.0 on windows with Amazon Corretto/OpenJDK 17
2. In Powershell Or Command Prompt, type gradle buildDependents in the folder of any gradle project
### Your Environment

Build scan URL: https://scans.gradle.com/s/y3pddhkq4cwsa

**Comment by lptr** [comment] 2021-04-13 08:34
> `ERROR_ACCOUNT_DISABLED` 1331 (0x533)
>
> This user can't sign in because this account is currently disabled.

Wonder why that happens...

**Comment by lptr** [comment] 2021-04-13 09:18
IIUC, you are running this with an early access preview of Corretto 17? Can you reproduce it with a stable JDK release?

**Comment by Pugga12** [comment] 2021-04-13 11:50
Sorry, I meant Corretto 16, I mistyped. If you look at my build scan, it says "

Java runtime

Amazon.com Inc. OpenJDK Runtime Environment 16+36"

**Comment by andersonkyle** [comment] 2021-04-13 16:02
I've encountered this issue as well.

```
Architecture: x86
Operating System: Windows 10 Pro Build 19041
--Java--
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment 18.9 (build 11.0.10+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.10+9, mixed mode)
```

**Comment by lptr** [comment] 2021-04-13 16:05
Thanks @Pugga12. From @andersonkyle's comment it seems the issue is not unique to that JDK variant anyway.

I think the right way to handle this would be to catch the exception, and kill the whole VFS if this happens.

**Comment by lptr** [comment] 2021-04-13 16:06
Do you have some "interesting" kinds of drives mounted on your computers? Network drives, `SUBST` etc.? I wonder what produces this account disabled problem.

**Comment by andersonkyle** [comment] 2021-04-13 16:16
I did have a NAS share that was mounted but it was in a "disconnected" state as the actual server is offline at the moment.  Removing that drive mount seems to have cleared up the issue for me.

Not sure why it would be looking at path since my Gradle project is on my local C drive.

**Comment by Pugga12** [comment] 2021-04-13 21:20
It turns out my NAS had my account disabled and it was trying to find the NAS on Dirves X and Y, ill remove the mount

**Comment by andersonkyle** [comment] 2021-04-13 21:48
@Pugga12 Mind leaving this issue open so that the problem can eventually be addressed?

**Comment by Pugga12** [comment] 2021-04-13 23:20
Okay

**Comment by MikeChristianson** [comment] 2021-04-13 23:24
I'm not experiencing this same problem, but I did notice the following which may help point in the right direction. I'm on macOS with a volume mounted to an MSB share on a NAS. The file system watcher seems to notice it.

```
2021-04-13T16:13:36.978-0700 [DEBUG] [org.gradle.internal.watch.vfs.impl.DefaultWatchableFileSystemDetector] Detected apfs: / from /dev/disk1s1s1 (remote: false, case-sensitive: false, case-preserving: true)
…
2021-04-13T16:13:36.978-0700 [DEBUG] [org.gradle.internal.watch.vfs.impl.DefaultWatchableFileSystemDetector] Detected smbfs: /Volumes/media from //mike@nas.local/media (remote: true, case-sensitive: false, case-preserving: true)
2021-04-13T16:13:36.978-0700 [INFO] [org.gradle.internal.watch.registry.impl.WatchableHierarchies] Some of the file system contents retained in the virtual file system are on file systems that Gradle doesn't support watching. The relevant state was discarded to ensure changes to these locations are properly detected. You can override this by explicitly enabling file system watching.
```

@andersonkyle This leads me to wonder what you'd see if you reproduced the issue with debug logging turned on.

**Comment by lptr** [comment] 2021-04-13 23:48
Looks like Gradle is not prepared for mounted file systems that are unavailable. :/

> Not sure why it would be looking at that path since my Gradle project is on my local C drive.

The reason for this is that we don't want to keep information about any file system cached in memory that we cannot reliably watch. So we only keep data we collected during the build in memory if it's on a file system with a type that we support. Unfortunately the API we use to query the file system types seems to barf when one is not avaialble.

**Comment by lptr** [comment] 2021-04-13 23:51
How severe is this issue for you? IIUC, it can be fixed by removing any mounted volumes that would anyway be unavailable. Is this a good enough solution? I'm trying to decide if we need to do 7.0.1 to fix this, or if it's okay to have a fix in 7.1.

**Comment by andersonkyle** [comment] 2021-04-14 00:42
@lptr In my case I'm fine with the fix coming in 7.1.

@MikeChristianson Unfortunately the debug logs didn't contain anything useful.  This exception probably occurs early in the process.

**Comment by ramonwirsch** [comment] 2021-04-14 12:38
Just fyi, I've also ran into this issue on Windows, but with
`could not get volume information (errno -2144272384)`
In my case a still locked Bitlocker Volume seems to be the cause of the exception. Unlocking it also resolved it.

**Comment by biberesser** [comment] 2021-04-16 21:28
> Just fyi, I've also ran into this issue on Windows, but with
> `could not get volume information (errno -2144272384)`
> In my case a still locked Bitlocker Volume seems to be the cause of the exception. Unlocking it also resolved it.

**Unlocking all of my Bitlocker drives** seemed to be the issue for me as well.

Win10 Pro x64 (10.0.18363 Build 18363)
AdoptOpenJdk 15.0.2 64bit
Gradle 7.0

**Comment by wolfs** [comment] 2021-04-21 14:03
Fixed via #16899

**Closed by wolfs** 2021-04-21 14:03 UTC
Labels: @execution, in:virtual-file-system

**Comment by wolfs** [comment] 2021-04-21 14:22
@Pugga12 @ramonwirsch @andersonkyle @MikeChristianson  Can you try out `7.0-20210421140649+0000`, it should fix the issue.

**Comment by ramonwirsch** [comment] 2021-04-23 12:20
Can confirm `7.0-20210421140649+0000` fixes it for the bitlocker case.

**Comment by ThadHouse** [comment] 2021-04-23 22:53
Can confirm this fixes the bitlocker case as well, which I started running into. This will make it into a 7.0.x branch, right? It'll be a long wait for 7.1 I suspect.

**Comment by wolfs** [comment] 2021-04-24 08:15
Yes, this will make it into 7.0.1.

**Comment by alastairpatrick** [comment] 2021-04-30 02:56
I ran into this issue after upgrading to gradle 7.0.

The computer has 5 volumes: two SSDs and three mechanical drives, all formatted as NTFS. The system has no external, network or removable drives. One unusual thing about the storage devices is that the user I logged in to Windows as did not have permission to access two of the 5 drives. Gradle would have no good reason to try to access those two drives but, if it did, the operating system would return an error.

I upgraded to 7.0-20210421140649+0000 after finding this bug report and it fixed the issue.

------------------------------------------------------------
Gradle 7.0-20210421140649+0000
------------------------------------------------------------

Build time:   2021-04-21 14:06:49 UTC
Revision:     d47d655c8fe1d807d0070bf09e08f3c4d778a88c

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.7 (AdoptOpenJDK 11.0.7+10)
OS:           Windows 10 10.0 amd64

**Comment by Pugga12** [comment] 2021-05-03 13:26
I upgraded to Gradle 7.0-20210421140649+0000 and it seemed to fix the bug for me. I have access to my WSL VHD. It was mounted at X:, but the distro was uninstalled, therefore the X: drive inaccessible and Gradle seemed to be fine

**Comment by 24glinka** [comment] 2021-05-11 08:08
Hi, it happens also when you run a pipeline in Bitbucket, using gradle:7.0.0-jdk16 as docker image.

**Comment by lptr** [comment] 2021-05-11 09:14
This should be fixed with 7.0.1 already.

**Comment by 24glinka** [comment] 2021-05-11 12:12
Hi again, I confirm: the problem has disappeared. Thanks for the update!

**Comment by KumarShubham001** [comment] 2021-05-29 11:44
This issue is reloved if the system is connected with any locked device, NAS shares, or even if a hard-disk partition is locked using a bit-locker.
Unlocking or removing the hard disk partition, NAS share or any other such removable device will resolve the issue.
I had the same issue and it troubled me for a quite long time. Haha!

**Comment by lptr** [comment] 2021-06-01 07:02
@KumarShubham001 this was a problem in Gradle 7.0, do you still have an issue with Gradle 7.0.1+?

**Comment by KumarShubham001** [comment] 2021-06-04 06:02
Nope, thanks now it's working for me now. :)

Regards,

Kumar Shubham
M: (+91) 840-790-0285
E: ***@***.***
W: www.kumarshubham.in <https://kumarshubham.in/>
