### ISSUE TITLE
Hang downloading dependencies during IntelliJ sync in Gradle 8.11-rc-1

### ISSUE THREAD

**Issue by ianbrandt** [gradle/gradle#30969] opened 2024-10-19 17:38 UTC
### Current Behavior

Initially [reported on Slack](https://gradle-community.slack.com/archives/CJWG8VDM0/p1729352269116149?thread_ts=1729166843.821089&cid=CJWG8VDM0).

Intermittently, when I update from Gradle 8.10.2 to 8.11-rc-1 and run sync in IntelliJ 2024.2.3, the Gradle Daemon hangs with high CPU utilization while downloading dependencies. I've reproduced this with two different projects on both Mac and Windows.

I'm not sure whether this is the same issue as #30905.

Mac screenshots:

![Image](https://github.com/user-attachments/assets/6dad84db-6d4e-4305-ae2c-28d9011f7267)

![Image](https://github.com/user-attachments/assets/500e092f-c2d0-4e60-a137-28e225908397)

Mac thread dump:

[threaddump-1729353285558.tdump.zip](https://github.com/user-attachments/files/17446738/threaddump-1729353285558.tdump.zip)

Windows screenshots:

![Image](https://github.com/user-attachments/assets/2437c85f-2867-4be9-866c-4e778855739a)

![Image](https://github.com/user-attachments/assets/3c5a1344-50b6-4bb3-a71b-e3296c4f7679)

Windows thread dump:

[threaddump-1729354239791.tdump.zip](https://github.com/user-attachments/files/17446770/threaddump-1729354239791.tdump.zip)

### Expected Behavior

IntelliJ sync completes.

### Context (optional)

Testing 8.11-rc-1.

### Self-contained Reproducer Project

1. https://github.com/sdkotlin/sd-kotlin-talks/tree/0f6ed43015f1af2d7350d6617838d25cb1251d63
2. https://github.com/sdkotlin/sd-kotlin-spring-talks/tree/fc619242217a5ac8901cb9179bfb1b3da712ea92

### Gradle version

8.11-rc-1

### Your Environment (optional)

IntelliJ 2024.2.3

Mac:

```text
./gradlew --version

------------------------------------------------------------
Gradle 8.11-rc-1
------------------------------------------------------------

Build time:    2024-10-17 10:40:24 UTC
Revision:      4eab5987e618554d2d5e51fbc7b1dd1a3c7e8cb8

Kotlin:        2.0.20
Groovy:        3.0.22
Ant:           Apache Ant(TM) version 1.10.14 compiled on August 16 2023
Launcher JVM:  21.0.5 (Eclipse Adoptium 21.0.5+11-LTS)
Daemon JVM:    /Users/ianbrandt/Library/Java/JavaVirtualMachines/temurin-21.0.5/Contents/Home (no JDK specified, using current Java home)
OS:            Mac OS X 15.0.1 aarch64
```

Windows:

```text
.\gradlew --version

------------------------------------------------------------
Gradle 8.11-rc-1
------------------------------------------------------------

Build time:    2024-10-17 10:40:24 UTC
Revision:      4eab5987e618554d2d5e51fbc7b1dd1a3c7e8cb8

Kotlin:        2.0.20
Groovy:        3.0.22
Ant:           Apache Ant(TM) version 1.10.14 compiled on August 16 2023
Launcher JVM:  21.0.4 (Eclipse Adoptium 21.0.4+7-LTS)
Daemon JVM:    C:\Dev\.jdks\temurin-21.0.4 (no JDK specified, using current Java home)
OS:            Windows 10 10.0 amd64
```

**Comment by abstratt** [comment] 2024-10-21 14:11
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by jvandort** [comment] 2024-10-21 19:00
You mention this occurs intermittently. How often? I am not able to reproduce this by importing into IntelliJ after updating `sd-kotlin-talks` to 8.11 RC1. 

Which IJ version are you using? Which machine (how many cores)?

**Comment by jvandort** [comment] 2024-10-21 19:09
Can you provide a build scan?

**Comment by jvandort** [comment] 2024-10-21 19:09
Does disabling `org.gradle.parallel=true` do anything?

**Comment by jvandort** [comment] 2024-10-21 19:11
Are you able to simplify any of these reproducers and still hit the deadlock/hang?

**Comment by jvandort** [comment] 2024-10-21 20:39
Looks like I am able to reproduce with `sd-kotlin-spring-talks`

**Comment by ianbrandt** [comment] 2024-10-21 22:22
Thank you for looking into this.

It reproduces most times I try. My steps have been to be synced with 8.10.2, update the [`Wrapper.gradleVersion` in my root 'build.gradle.kts'](https://github.com/sdkotlin/sd-kotlin-spring-talks/commit/fc619242217a5ac8901cb9179bfb1b3da712ea92#diff-c0dfa6bc7a8685217f70a860145fbdf416d449eaff052fa28352c5cec1a98c06L57-L58), run `gradle wrapper` via IntelliJ, and then click the "Load Gradle Changes" notification icon that pops up to perform the sync.

I just reproduced it having first set `org.gradle.parallel=false`.

I just reproduced it from terminal trying to run `./gradlew build` and `./gradlew build --scan`:

```text
ianbrandt@Ians-M2-MBP sd-kotlin-spring-talks % ./gradlew build
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
Configuration on demand is an incubating feature.
Calculating task graph as no cached configuration is available for tasks: build
Type-safe project accessors is an incubating feature.
<=============> 100% CONFIGURING [1m 31s]
> Resolve dependencies of :subprojects:app:testRuntimeClasspath
^C%                                                                                                                                                                                                        ianbrandt@Ians-M2-MBP sd-kotlin-spring-talks % ./gradlew build --scan
Starting a Gradle Daemon, 1 busy and 1 incompatible Daemons could not be reused, use --status for details
Configuration on demand is an incubating feature.
Calculating task graph as no cached configuration is available for tasks: build
Type-safe project accessors is an incubating feature.
<=============> 100% CONFIGURING [30s]
> Resolve dependencies of :subprojects:app:testRuntimeClasspath
^C%                                                                                                                                                                                                        ```
```

My CPUs...

On Mac:

```text
Apple M2 Max
12 Core(s), 8 performance and 4 efficiency
64 GB RAM
```

On Windows:

```text
13th Gen Intel(R) Core(TM) i9-13950HX, 2200 Mhz
24 Core(s), 32 Logical Processor(s)
64GB RAM
```

**Comment by jvandort** [comment] 2024-10-21 22:49
I've simplified down this reproducer into a more minimal integ test:

```
    def "capability conflict does not cause build to hang"() {
        buildFile << """
            plugins {
                id("java-library")
                id("org.gradlex.jvm-dependency-conflict-resolution") version "2.1.2"
            }

            repositories {
                mavenCentral()
            }

            dependencies {
                implementation(platform("org.springframework.boot:spring-boot-dependencies:3.3.4"))

                implementation("org.assertj:assertj-core:3.26.3")
                implementation("io.mockk:mockk:1.13.13")
                implementation("org.junit.platform:junit-platform-launcher")
                implementation("org.junit.jupiter:junit-jupiter:5.11.2")
            }
        """

        expect:
        succeeds(":dependencies", "--configuration", "runtimeClasspath")
    }
```

This reliably causes the build to hang during dependency resolution due to an infinite loop in capability conflict detection. I have not dug into _what_ is happening yet. This is likely caused by #30363

**Comment by ianbrandt** [comment] 2024-10-21 23:53
> I've simplified down this reproducer into a minimal integration test. This reliably causes the build to hang during dependency resolution due to an infinite loop in capability conflict detection.

Well done!

**Comment by jvandort** [comment] 2024-10-22 20:51
We plan to resolve this in 8.11 by reverting the change that cause this

**Comment by jvandort** [comment] 2024-10-26 14:16
@ianbrandt We merged a PR that should resolve this issue. It would be great to hear your feedback on RC2 when it is released

**Closed** 2024-10-30 13:48 UTC
Labels: a:regression, in:dependency-resolution, has:release-notes-decision

**Comment by ianbrandt** [comment] 2024-11-01 01:33
> [@ianbrandt](https://github.com/ianbrandt) We merged a PR that should resolve this issue. It would be great to hear your feedback on RC2 when it is released

@jvandort, Both my test projects sync and build just fine on Mac and Windows with 8.11-rc-2.

**Comment by jvandort** [comment] 2024-11-01 01:40
Thank you for checking! Great to hear, I'm very glad we didn't have to revert
