### ISSUE TITLE
Configurations with defaultDependencies configurations can be observed without dependencies being added

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#2822] opened 2017-08-29 20:24 UTC
Unfortunately the conditions needed to reproduce this are far too complex for me to provide a reduced example, but it's possible for `dependencyReport` and the `checkstyle` plugin to interact. That leads me to believe it's possible for a configuration to be marked as observed, without it's default dependencies being added:

        Caused by: org.gradle.api.InvalidUserDataException: Cannot change dependencies of configuration ':checkstyle' after it has been included in dependency resolution.
                at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.validateMutation(DefaultConfiguration.java:746)
                at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$2.execute(DefaultConfiguration.java:230)
                at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$2.execute(DefaultConfiguration.java:227)
                at org.gradle.internal.ImmutableActionSet$SingletonSet.execute(ImmutableActionSet.java:155)
                at org.gradle.api.internal.DefaultDomainObjectCollection.assertMutable(DefaultDomainObjectCollection.java:320)
                at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:197)
                at org.gradle.api.internal.DelegatingDomainObjectSet.add(DelegatingDomainObjectSet.java:82)
                at org.gradle.api.plugins.quality.CheckstylePlugin$1.execute(CheckstylePlugin.java:70)
                at org.gradle.api.plugins.quality.CheckstylePlugin$1.execute(CheckstylePlugin.java:67)
                at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$3.execute(DefaultConfiguration.java:348)
                at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$3.execute(DefaultConfiguration.java:344)
                at org.gradle.internal.ImmutableActionSet$CompositeSet.execute(ImmutableActionSet.java:196)
                at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.triggerWhenEmptyActionsIfNecessary(DefaultConfiguration.java:358)
                at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.performPreResolveActions(DefaultConfiguration.java:486)
                at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$500(DefaultConfiguration.java:109)
                at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$4.execute(DefaultConfiguration.java:461)
                at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$4.execute(DefaultConfiguration.java:455)
                at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
                at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
                at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
                at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveGraphIfRequired(DefaultConfiguration.java:455)
                at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:431)
                at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1400(DefaultConfiguration.java:109)
                at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationResolvableDependencies.getResolutionResult(DefaultConfiguration.java:963)
                at org.gradle.api.tasks.diagnostics.internal.dependencies.AsciiDependencyReportRenderer.render(AsciiDependencyReportRenderer.java:94)

### Steps to Reproduce (for bugs)
Unknown.

### Your Environment
Gradle 3.5.1

**Comment by bmuschko** [comment] 2017-09-01 15:07
Can you give us a rough idea on which plugins are applied to the project and their order?

**Comment by DanielThomas** [comment] 2017-09-01 15:58
@bmuschko there are dozens of plugins installed. We ran into this while generating a global lock (which is a bonkers solution we've needed on a handful of projects) - but I couldn't manage to reduce it to a reproducible use case:

https://github.com/nebula-plugins/gradle-dependency-lock-plugin/blob/master/src/main/groovy/nebula/plugin/dependencylock/DependencyLockTaskConfigurer.groovy#L224-L254

I hoped that the behavior alone would point to the bug.

**Comment by bigdaz** [comment] 2017-12-23 23:38
Thanks @DanielThomas. It's really hard to see how this can happen by inspecting the code and your attached stacktrace. That said, we've made some simplifications/improvements to the way we process `defaultDependencies` so this issue may have been fixed since it was reported.

I'm going to close this issue pending either:
a) You can verify that this is still a problem with Gradle 4.4, and you're able to work with us to extract more information from the failing build.
b) You can provide a reproducible sample

**Closed by bigdaz** 2017-12-23 23:38 UTC
Labels: a:bug, from:contributor, in:dependency-management
