### ISSUE TITLE
Allow to customize environment variables via tooling API for jdk9

### ISSUE THREAD

**Issue by nskvortsov** [gradle/gradle#5822] opened 2018-06-29 11:54 UTC
IntelliJ IDEA Gradle integration allows to specify customized environment variables when starting a Gradle task using IDEA's run configuration. But this fails to work with JDK9+ and Gradle 4.6+ (https://youtrack.jetbrains.com/issue/IDEA-194794)
The feature implementation relies on `org.gradle.tooling.LongRunningOperation#setEnvironmentVariables` 

### Expected Behavior
Gradle tooling could spin up new daemon with customized env vars if no existing daemons have required env.

### Current Behavior
Gradle silently executed with default set of env. vars, inherited from parent process, without any warnings.

### Context
Existing users' run configurations in IDEA just stop working when switched to JDK9+ 

### Your Environment
IntelliJ IDEA 2018.1+ , Gradle 4.6+, JDK9+

**Comment by oehme** [comment] 2018-06-29 15:13
Duplicate of #3468

**Closed by oehme** 2018-06-29 15:13 UTC
