### ISSUE TITLE
Dependency resolution error

### ISSUE THREAD

**Issue by guylabs** [gradle/gradle#14946] opened 2020-10-22 08:15 UTC
We get the following error when generating a build scan:

```
5-Oct-2020 12:42:07    BUILD SUCCESSFUL in 10m 25s
15-Oct-2020 12:42:07    571 actionable tasks: 327 executed, 244 from cache
15-Oct-2020 12:42:08
15-Oct-2020 12:42:08    A build scan cannot be produced as an error occurred gathering build data.
15-Oct-2020 12:42:08    Please report this problem via https://gradle.com/help/plugin and include the following via copy/paste:
15-Oct-2020 12:42:08
15-Oct-2020 12:42:08    ----------
15-Oct-2020 12:42:08    Gradle version: 6.6
15-Oct-2020 12:42:08    Plugin version: 3.4.1
15-Oct-2020 12:42:08
15-Oct-2020 12:42:08    org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':parent-teacher-impl:testCompileClasspath'.
15-Oct-2020 12:42:08    at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.wrapException(ErrorHandlingConfigurationResolver.java:104)
15-Oct-2020 12:42:08    at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.access$000(ErrorHandlingConfigurationResolver.java:48)
15-Oct-2020 12:42:08    at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver$ErrorHandlingResolutionResult.getRoot(ErrorHandlingConfigurationResolver.java:203)
15-Oct-2020 12:42:08    at org.gradle.api.internal.artifacts.configurations.ResolveConfigurationResolutionBuildOperationResult.getRootComponent(ResolveConfigurationResolutionBuildOperationResult.java:59)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.capture.dependency.resolutionresult.ConfigurationResolutionResultSerializer$Serialization.from(ConfigurationResolutionResultSerializer.java:116)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.capture.dependency.resolutionresult.ConfigurationResolutionResultSerializer$Serialization.access$000(ConfigurationResolutionResultSerializer.java:70)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.capture.dependency.resolutionresult.ConfigurationResolutionResultSerializer$Serialization.access$100(ConfigurationResolutionResultSerializer.java:70)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.capture.dependency.resolutionresult.ConfigurationResolutionResultSerializer.serialize(ConfigurationResolutionResultSerializer.java:51)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.capture.dependency.resolutionresult.ConfigurationResolutionDataStore.resolutionFinished(ConfigurationResolutionDataStore.java:149)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.capture.dependency.ConfigurationResolutionCapturer_5_0.attach(ConfigurationResolutionCapturer_5_0.java:135)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.capture.dependency.ConfigurationResolutionCapturer_5_0.lambda$attach$1(ConfigurationResolutionCapturer_5_0.java:135)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.operations.listener.BuildOperationListenerSpec.progress(BuildOperationListenerSpec.java:12)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.operations.listener.BuildOperationListenerSpec.started(BuildOperationListenerSpec.java:12)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.operations.listener.BuildOperationListenerSpec.finished(BuildOperationListenerSpec.java:12)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.operations.listener.BuildOperationListenerSpec.lambda$finished$0(BuildOperationListenerSpec.java:12)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.operations.BuildOperationListenerIndex$ListenersWithoutProgressListeners.finished(BuildOperationListenerIndex.java:154)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.operations.BuildOperationListenerIndex.finished(BuildOperationListenerIndex.java:65)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.operations.GradleBuildTaskAdaptingNotificationDispatcher.finished(GradleBuildTaskAdaptingNotificationDispatcher.java:58)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.operations.BuildOperationNotificationAdapter.finished(BuildOperationNotificationAdapter.java:103)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.operations.BuildOperationNotificationQueue.onFinished(BuildOperationNotificationQueue.java:48)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.worker.DefaultWorker$Event.process(DefaultWorker.java:31)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.worker.DefaultWorker$Event.access$100(DefaultWorker.java:20)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.worker.DefaultWorker.work(DefaultWorker.java:67)
15-Oct-2020 12:42:08    Caused by: java.lang.RuntimeException: Problems reading data from Binary store in /tmp/gradle3118181872915562252.bin offset 1934575 exists? true
15-Oct-2020 12:42:08    at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore$SimpleBinaryData.read(DefaultBinaryStore.java:132)
15-Oct-2020 12:42:08    at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.lambda$create$0(StreamingResolutionResultBuilder.java:187)
15-Oct-2020 12:42:08    at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory$SimpleStore.load(CachedStoreFactory.java:101)
15-Oct-2020 12:42:08    at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.create(StreamingResolutionResultBuilder.java:185)
15-Oct-2020 12:42:08    at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.create(StreamingResolutionResultBuilder.java:157)
15-Oct-2020 12:42:08    at org.gradle.api.internal.artifacts.result.DefaultResolutionResult.getRoot(DefaultResolutionResult.java:48)
15-Oct-2020 12:42:08    at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver$ErrorHandlingResolutionResult.getRoot(ErrorHandlingConfigurationResolver.java:201)
15-Oct-2020 12:42:08    at org.gradle.api.internal.artifacts.configurations.ResolveConfigurationResolutionBuildOperationResult.getRootComponent(ResolveConfigurationResolutionBuildOperationResult.java:59)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.capture.dependency.resolutionresult.ConfigurationResolutionResultSerializer$Serialization.from(ConfigurationResolutionResultSerializer.java:116)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.capture.dependency.resolutionresult.ConfigurationResolutionResultSerializer$Serialization.access$000(ConfigurationResolutionResultSerializer.java:70)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.capture.dependency.resolutionresult.ConfigurationResolutionResultSerializer$Serialization.access$100(ConfigurationResolutionResultSerializer.java:70)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.capture.dependency.resolutionresult.ConfigurationResolutionResultSerializer.serialize(ConfigurationResolutionResultSerializer.java:51)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.capture.dependency.resolutionresult.ConfigurationResolutionDataStore.resolutionFinished(ConfigurationResolutionDataStore.java:149)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.capture.dependency.ConfigurationResolutionCapturer_5_0.attach(ConfigurationResolutionCapturer_5_0.java:135)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.capture.dependency.ConfigurationResolutionCapturer_5_0.lambda$attach$1(ConfigurationResolutionCapturer_5_0.java:135)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.operations.listener.BuildOperationListenerSpec.progress(BuildOperationListenerSpec.java:12)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.operations.listener.BuildOperationListenerSpec.started(BuildOperationListenerSpec.java:12)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.operations.listener.BuildOperationListenerSpec.finished(BuildOperationListenerSpec.java:12)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.operations.listener.BuildOperationListenerSpec.lambda$finished$0(BuildOperationListenerSpec.java:12)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.operations.BuildOperationListenerIndex$ListenersWithoutProgressListeners.finished(BuildOperationListenerIndex.java:154)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.operations.BuildOperationListenerIndex.finished(BuildOperationListenerIndex.java:65)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.operations.GradleBuildTaskAdaptingNotificationDispatcher.finished(GradleBuildTaskAdaptingNotificationDispatcher.java:58)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.operations.BuildOperationNotificationAdapter.finished(BuildOperationNotificationAdapter.java:103)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.operations.BuildOperationNotificationQueue.onFinished(BuildOperationNotificationQueue.java:48)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.worker.DefaultWorker$Event.process(DefaultWorker.java:31)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.worker.DefaultWorker$Event.access$100(DefaultWorker.java:20)
15-Oct-2020 12:42:08    at com.gradle.scan.plugin.internal.worker.DefaultWorker.work(DefaultWorker.java:67)
15-Oct-2020 12:42:08    Caused by: java.lang.IllegalStateException: Corrupt serialized resolution result. Cannot find selected module (386) for constraint testCompileClasspath -> org.bouncycastle:bcpkix-jdk15on:1.65
15-Oct-2020 12:42:08    at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.DefaultResolutionResultBuilder.visitOutgoingEdges(DefaultResolutionResultBuilder.java:82)
15-Oct-2020 12:42:08    at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.deserialize(StreamingResolutionResultBuilder.java:237)
15-Oct-2020 12:42:08    at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore$SimpleBinaryData.read(DefaultBinaryStore.java:130)
15-Oct-2020 12:42:08    ... 21 more
```

This is the part in the Gradle Enterprise Gradle plugin which fails: https://github.com/gradle/dotcom/blob/gradle-enterprise-2020.3.4/build-agent-gradle/src/main/java/com/gradle/scan/plugin/internal/capture/dependency/resolutionresult/ConfigurationResolutionResultSerializer.java#L116

### Expected Behavior
Build scans can be created and published.

### Current Behavior
Build scans fail to upload.

### Steps to Reproduce 
No reproducer available yet.

### Your Environment
 Gradle `6.7` and Gradle Enterprise Gradle plugin `3.4.1`

**Comment by melix** [comment] 2020-10-22 08:23
For completion: the stack trace mentions 6.6 but this has been tried on 6.7 too.

**Comment by Ftelf** [comment] 2020-10-22 08:29
We have the same problem since yesterday. All builds requiring downloading any gradle package fails like:

> Could not resolve all artifacts for configuration ':sm-app:classpath'.
   > Could not resolve gradle.plugin.com.gorylenko.gradle-git-properties:gradle-git-properties:1.4.16.
     Required by:
         project :sm-app > com.gorylenko.gradle-git-properties:com.gorylenko.gradle-git-properties.gradle.plugin:1.4.16
      > Could not resolve gradle.plugin.com.gorylenko.gradle-git-properties:gradle-git-properties:1.4.16.
         > Could not get resource 'https://plugins.gradle.org/m2/gradle/plugin/com/gorylenko/gradle-git-properties/gradle-git-properties/1.4.16/gradle-git-properties-1.4.16.pom'.
            > Could not HEAD 'https://plugins-artifacts.gradle.org/gradle.plugin.com.gorylenko.gradle-git-properties/gradle-git-properties/1.4.16/e143b8d85d9b0cf44fbe37508fc8599d92b694e78b2b4dac571114c2ad0285c5/gradle-git-properties-1.4.16.pom'.
               > Read timed out

**Comment by melix** [comment] 2020-10-22 08:31
@Ftelf this is not the same issue at all. Yours is a read timeout, which indicates a network issue or plugin portal downtime.
This issue is about an internal error of Gradle (serialization issue).

**Comment by thecodesmith** [comment] 2020-11-17 18:05
Greetings, I reported the original error. Try as I might, I was not able to narrow down a simple case that reproduces the issue. However, I just accidentally found that if I add the missing dependency from the error message (`org.bouncycastle:bcpkix-jdk15on:1.65` in the above) as a `testCompileOnly` dependency in the mentioned subproject, the build scan error disappears. This is strange to me because there appears to be no usage of that dependency in the subproject at all, compile-time or otherwise. I had several of these errors in separate subprojects and was able to work around them all the same way. Just adding as a point of information here in case it helps.

**Comment by melix** [comment] 2020-11-24 16:53
Thanks @thecodesmith . This hints at a transitive dependency which appears during graph resolution but is eventually removed (either by conflict resolution, or because the component which brings it in itself was upgraded). If you have a reproducer for this it would greatly help diagnosing.

**Comment by thecodesmith** [comment] 2021-03-18 21:08
A small update: I just ran across this similar issue, #11844. I tried the workaround suggested by rolandkreuzer in [this comment](https://github.com/gradle/gradle/issues/11844#issuecomment-652953146) and the build scans started working again.
```
maven {
    url 'https://internalmvnrepo'
    metadataSources {
        ignoreGradleMetadataRedirection()
        mavenPom()
    }
}
```
I have not yet dug deeper into this to understand what is going on, but I did notice that our dependency declarations look similar to the example in that comment:
```
javaPlatform {
    allowDependencies()
}

dependencies {
    // some BOM dependencies here

    constraints {
        api "org.bouncycastle:bcpkix-jdk15on:$bouncycastleVersion"
    }
}
```
If you have ideas on how to narrow down a reproducer for this just let me know.

**Comment by wilkinsona** [comment] 2021-06-08 12:56
I saw the same problem during today's Fastly outage. The outage was causing Maven Central to respond with 50x errors. This was causing resolution failures which I think were then having a knock-on effect on the build scan:

```
./gradlew build
> Task :spring-boot-project:spring-boot-starters:spring-boot-starter-oauth2-client:generatePomFileForMavenPublication FAILED
> Task :spring-boot-project:spring-boot-autoconfigure:compileKotlin FAILED
FAILURE: Build completed with 2 failures.
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':spring-boot-project:spring-boot-starters:spring-boot-starter-oauth2-client:generatePomFileForMavenPublication'.
> Could not resolve all dependencies for configuration ':spring-boot-project:spring-boot-starters:spring-boot-starter-oauth2-client:runtimeClasspath'.
   > Problems reading data from Binary store in /private/var/folders/2w/mhq2nt4d0xx2w6w4c36n468h0000gn/T/gradle16165898924152422066.bin offset 130799 exists? true
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================
2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':spring-boot-project:spring-boot-autoconfigure:compileKotlin'.
> Could not resolve all files for configuration ':spring-boot-project:spring-boot-autoconfigure:optional'.
   > Could not resolve net.minidev:json-smart:[1.3.2,2.4.2].
     Required by:
         project :spring-boot-project:spring-boot-autoconfigure > com.nimbusds:oauth2-oidc-sdk:9.3.3
      > Failed to list versions for net.minidev:json-smart.
         > Unable to load Maven meta-data from https://repo.maven.apache.org/maven2/net/minidev/json-smart/maven-metadata.xml.
            > Could not HEAD 'https://repo.maven.apache.org/maven2/net/minidev/json-smart/maven-metadata.xml'. Received status code 502 from server: Gateway Error
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================
* Get more help at https://help.gradle.org
BUILD FAILED in 24s
911 actionable tasks: 137 executed, 774 up-to-date
A build scan cannot be produced as an error occurred gathering build data.
Please report this problem via https://gradle.com/help/plugin and include the following via copy/paste:
----------
Gradle version: 6.9
Plugin version: 3.6.1
org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':spring-boot-project:spring-boot-starters:spring-boot-starter-oauth2-client:runtimeClasspath'.
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.wrapException(ErrorHandlingConfigurationResolver.java:106)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.access$000(ErrorHandlingConfigurationResolver.java:49)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver$ErrorHandlingResolutionResult.getRoot(ErrorHandlingConfigurationResolver.java:215)
        at org.gradle.api.internal.artifacts.configurations.ResolveConfigurationResolutionBuildOperationResult.getRootComponent(ResolveConfigurationResolutionBuildOperationResult.java:59)
        at com.gradle.scan.plugin.internal.b.f.a.h$a.b(SourceFile:113)
        at com.gradle.scan.plugin.internal.b.f.a.h$a.a(SourceFile:66)
        at com.gradle.scan.plugin.internal.b.f.a.h.a(SourceFile:47)
        at com.gradle.scan.plugin.internal.b.f.a.g.a(SourceFile:147)
        at com.gradle.scan.plugin.internal.b.f.c.a(SourceFile:137)
        at com.gradle.scan.plugin.internal.l.a.f.a(SourceFile:12)
        at com.gradle.scan.plugin.internal.l.a$c.finished(SourceFile:154)
        at com.gradle.scan.plugin.internal.l.a.a(SourceFile:65)
        at com.gradle.scan.plugin.internal.l.l.a(SourceFile:58)
        at com.gradle.scan.plugin.internal.l.c.a(SourceFile:98)
        at com.gradle.scan.plugin.internal.l.g.a(SourceFile:51)
        at com.gradle.scan.plugin.internal.q.a$a.a(SourceFile:31)
        at com.gradle.scan.plugin.internal.q.a$a.a(SourceFile:20)
        at com.gradle.scan.plugin.internal.q.a.c(SourceFile:67)
Caused by: java.lang.RuntimeException: Problems reading data from Binary store in /private/var/folders/2w/mhq2nt4d0xx2w6w4c36n468h0000gn/T/gradle16165898924152422066.bin offset 130799 exists? true
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore$SimpleBinaryData.read(DefaultBinaryStore.java:132)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.lambda$create$0(StreamingResolutionResultBuilder.java:189)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory$SimpleStore.load(CachedStoreFactory.java:101)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.create(StreamingResolutionResultBuilder.java:187)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.create(StreamingResolutionResultBuilder.java:159)
        at org.gradle.api.internal.artifacts.result.DefaultResolutionResult.getRoot(DefaultResolutionResult.java:48)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver$ErrorHandlingResolutionResult.getRoot(ErrorHandlingConfigurationResolver.java:213)
        at org.gradle.api.internal.artifacts.configurations.ResolveConfigurationResolutionBuildOperationResult.getRootComponent(ResolveConfigurationResolutionBuildOperationResult.java:59)
        at com.gradle.scan.plugin.internal.b.f.a.h$a.b(SourceFile:113)
        at com.gradle.scan.plugin.internal.b.f.a.h$a.a(SourceFile:66)
        at com.gradle.scan.plugin.internal.b.f.a.h.a(SourceFile:47)
        at com.gradle.scan.plugin.internal.b.f.a.g.a(SourceFile:147)
        at com.gradle.scan.plugin.internal.b.f.c.a(SourceFile:137)
        at com.gradle.scan.plugin.internal.l.a.f.a(SourceFile:12)
        at com.gradle.scan.plugin.internal.l.a$c.finished(SourceFile:154)
        at com.gradle.scan.plugin.internal.l.a.a(SourceFile:65)
        at com.gradle.scan.plugin.internal.l.l.a(SourceFile:58)
        at com.gradle.scan.plugin.internal.l.c.a(SourceFile:98)
        at com.gradle.scan.plugin.internal.l.g.a(SourceFile:51)
        at com.gradle.scan.plugin.internal.q.a$a.a(SourceFile:31)
        at com.gradle.scan.plugin.internal.q.a$a.a(SourceFile:20)
        at com.gradle.scan.plugin.internal.q.a.c(SourceFile:67)
Caused by: java.lang.IllegalStateException: Corrupt serialized resolution result. Cannot find selected module (254) for constraint enforcedRuntimeElements -> net.minidev:json-smart:2.4.7
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.DefaultResolutionResultBuilder.visitOutgoingEdges(DefaultResolutionResultBuilder.java:83)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.deserialize(StreamingResolutionResultBuilder.java:239)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore$SimpleBinaryData.read(DefaultBinaryStore.java:130)
        ... 21 more
```

Failures like the above were repeatable throughout the Fastly outage. Once the outage was resolved, the problem stopped occurring. I'm not 100% sure that there's any causation but the correlation is pretty strong.

**Comment by ljacomet** [comment] 2021-06-09 08:52
Two things on this type of issues:
* They are caused by corner cases in dependency management which can be affected by declared dependencies, order of declarations and other changes that should not affect the dependency resolution result.
* It is quite tricky to figure out unless we get a reproducer, minimal or not.
* Gradle did a number of fixes around that in the 6.x line, so trying the latest version of that line might improve the result.

**Comment by wolfs** [comment] 2022-02-01 12:06
Looks like this reproduces now in the Gradle build: https://builds.gradle.org/buildConfiguration/Gradle_Master_Check_CompileAllBuild/49078114?buildTab=log&focusLine=9180&linesState=1786

I pushed this branch: [`wolfs/scans/reproduce-14962`](https://github.com/gradle/gradle/tree/wolfs/scans%2Freproduce-14962)

**Comment by shivkumar138** [comment] 2022-03-01 19:50
`----------
Gradle version: 6.9.2
Plugin version: 3.7.1
 
org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':ads-engagement-summary-report-job-azkaban_2.11:compileClasspath'.
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.wrapException(ErrorHandlingConfigurationResolver.java:106)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.access$000(ErrorHandlingConfigurationResolver.java:49)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver$ErrorHandlingResolutionResult.getRoot(ErrorHandlingConfigurationResolver.java:215)
        at org.gradle.api.internal.artifacts.configurations.ResolveConfigurationResolutionBuildOperationResult.getRootComponent(ResolveConfigurationResolutionBuildOperationResult.java:59)
        at com.gradle.scan.plugin.internal.b.f.a.h$a.b(SourceFile:113)
        at com.gradle.scan.plugin.internal.b.f.a.h$a.a(SourceFile:66)
        at com.gradle.scan.plugin.internal.b.f.a.h.a(SourceFile:47)
        at com.gradle.scan.plugin.internal.b.f.a.g.a(SourceFile:147)
        at com.gradle.scan.plugin.internal.b.f.c.a(SourceFile:137)
        at com.gradle.scan.plugin.internal.l.a.f.a(SourceFile:12)
        at com.gradle.scan.plugin.internal.l.a$c.finished(SourceFile:154)
        at com.gradle.scan.plugin.internal.l.a.a(SourceFile:65)
        at com.gradle.scan.plugin.internal.l.l.a(SourceFile:58)
        at com.gradle.scan.plugin.internal.l.c.a(SourceFile:98)
        at com.gradle.scan.plugin.internal.l.g.a(SourceFile:51)
        at com.gradle.scan.plugin.internal.q.a$a.a(SourceFile:31)
        at com.gradle.scan.plugin.internal.q.a$a.a(SourceFile:20)
        at com.gradle.scan.plugin.internal.q.a.c(SourceFile:67)
Caused by: java.lang.RuntimeException: Problems reading data from Binary store in /private/var/folders/ft/b5jkwn010tj3llqw2ljgx1h0001dc1/T/gradle6382969199485670936.bin offset 682978 exists? true
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore$SimpleBinaryData.read(DefaultBinaryStore.java:132)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.lambda$create$0(StreamingResolutionResultBuilder.java:189)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory$SimpleStore.load(CachedStoreFactory.java:101)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.create(StreamingResolutionResultBuilder.java:187)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.create(StreamingResolutionResultBuilder.java:159)
        at org.gradle.api.internal.artifacts.result.DefaultResolutionResult.getRoot(DefaultResolutionResult.java:48)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver$ErrorHandlingResolutionResult.getRoot(ErrorHandlingConfigurationResolver.java:213)
        at org.gradle.api.internal.artifacts.configurations.ResolveConfigurationResolutionBuildOperationResult.getRootComponent(ResolveConfigurationResolutionBuildOperationResult.java:59)
        at com.gradle.scan.plugin.internal.b.f.a.h$a.b(SourceFile:113)
        at com.gradle.scan.plugin.internal.b.f.a.h$a.a(SourceFile:66)
        at com.gradle.scan.plugin.internal.b.f.a.h.a(SourceFile:47)
        at com.gradle.scan.plugin.internal.b.f.a.g.a(SourceFile:147)
        at com.gradle.scan.plugin.internal.b.f.c.a(SourceFile:137)
        at com.gradle.scan.plugin.internal.l.a.f.a(SourceFile:12)
        at com.gradle.scan.plugin.internal.l.a$c.finished(SourceFile:154)
        at com.gradle.scan.plugin.internal.l.a.a(SourceFile:65)
        at com.gradle.scan.plugin.internal.l.l.a(SourceFile:58)
        at com.gradle.scan.plugin.internal.l.c.a(SourceFile:98)
        at com.gradle.scan.plugin.internal.l.g.a(SourceFile:51)
        at com.gradle.scan.plugin.internal.q.a$a.a(SourceFile:31)
        at com.gradle.scan.plugin.internal.q.a$a.a(SourceFile:20)
        at com.gradle.scan.plugin.internal.q.a.c(SourceFile:67)
Caused by: java.lang.IllegalStateException: Corrupt serialized resolution result. Cannot find selected module (2241) for default -> com.linkedin.container-core:container-ic-impl:1.2.14
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.DefaultResolutionResultBuilder.visitOutgoingEdges(DefaultResolutionResultBuilder.java:83)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.deserialize(StreamingResolutionResultBuilder.java:239)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore$SimpleBinaryData.read(DefaultBinaryStore.java:130)
        ... 21 more
`

Cannot do a successful build anymore after this.

**Comment by jjohannes** [comment] 2023-06-29 09:58
I think this is probably the same as (or overlaps with) #14200

**Comment by big-guy** [comment] 2023-12-18 17:50
Closing this as a dupe of https://github.com/gradle/gradle/issues/14220

**Closed by big-guy** 2023-12-18 17:50 UTC
Labels: a:bug, in:dependency-resolution
