### ISSUE TITLE
Gradle daemon issue

### ISSUE THREAD

**Issue by clembo590** [gradle/gradle#28807] opened 2024-04-13 10:46 UTC
# Gradle daemon issue:
this issue is fully reproducible with `gradle 8.5` and `gradle 8.7` with `openjdk version "21.0.1" 2023-10-17 LTS`  and `openjdk version "17.0.10" 2024-01-16 LTS`

to reproduce issue:
```
git clone https://github.com/clembo590/issues.git --branch issue_with_gradle_daemon_and_env_var
```

then execute
```
export TEST_VAR=one; ./gradlew help
```
 --> you will get the in the logs
```
TEST_VAR: one
from one
```

then execute
```
export TEST_VAR=two; ./gradlew help
```
 --> you will get a VERY WRONG result and the logs will still show
 ```
from one
```
It is a very wrong result because is should print `two` (and not `one`)

if you now execute without the daemon 
```
export TEST_VAR=two; ./gradlew --no-daemon help
```
--> you will get the following CORRECT logs
 ```
TEST_VAR: two
from two
```

The issue described here is that the daemon is reused even though the environment variables are not the same between the 2 builds....
I see 2 options to fix it:
1. gradle should never reuse the daemon if the environment variables are not the same
2. create a configuration property so that the daemon is not reused when the environment variables are not the same

**Comment by ov7a** [comment] 2024-04-15 08:59
This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/10483

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

Loosely related to: 
* https://github.com/gradle/gradle/issues/27346

**Closed by ov7a** 2024-04-15 08:59 UTC
Labels: a:bug, to-triage
