### ISSUE TITLE
Develocity plugin is not CC compatible in Kotlin DSL

### ISSUE THREAD

**Issue by Goooler** [gradle/gradle#28681] opened 2024-04-04 03:25 UTC
### Current Behavior

Declare the code below in settings.gradle.kts
```kt
plugins {
    id("com.gradle.develocity") version "3.17"
}

val isCI = providers.environmentVariable("CI").isPresent

develocity {
    buildScan {
        termsOfUseUrl = "https://gradle.com/terms-of-service"
        termsOfUseAgree = "yes"
        publishing.onlyIf { isCI }
    }
}
```
Run some Gradle tasks, you'll see this execption:

```
Configuration cache problems found in this build.

1 problem was found storing the configuration cache.
- Gradle runtime: cannot serialize Gradle script object references as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.7/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
```

```
cannot serialize Gradle script object references as these are not supported with the configuration cache.
  field this$0 of Settings_gradle$1$1$1$1
    bean of type Settings_gradle$1$1$1$1
      field a of com.gradle.develocity.agent.gradle.internal.scan.f$b$1
        bean of type com.gradle.develocity.agent.gradle.internal.scan.f$b$1
          field a of com.gradle.scan.plugin.internal.p.b.a
            bean of type com.gradle.scan.plugin.internal.p.b.a
              field e of com.gradle.scan.plugin.internal.service.a.d
                bean of type com.gradle.scan.plugin.internal.service.a.d
                  field m of com.gradle.scan.plugin.internal.service.n
                    bean of type com.gradle.scan.plugin.internal.service.n
                      field a of com.gradle.scan.plugin.internal.service.PluginServiceFactory
                        bean of type com.gradle.scan.plugin.internal.service.PluginServiceFactory
                          field b of com.gradle.scan.plugin.internal.service.d
                            bean of type com.gradle.scan.plugin.internal.service.d
                              field pluginServiceFactory of org.gradle.internal.enterprise.impl.DefaultGradleEnterprisePluginAdapter
                                bean of type org.gradle.internal.enterprise.impl.DefaultGradleEnterprisePluginAdapter
```

The root cause is related to `onlyIf { isCI }`, but this configuration is working in Groovy DSL well.

### Expected Behavior

No CC exceptions are thrown.

### Steps to Reproduce

1. `git clone https://github.com/LawnchairLauncher/lawnicons`
2. `git checkout migrate-to-develocity`
3. `./gradlew spotlessCheck`

You can repro this issue in https://github.com/LawnchairLauncher/lawnicons/pull/1960.

### Gradle version

8.7

**Comment by ov7a** [comment] 2024-04-04 12:58
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by bamboo** [comment] 2024-04-04 13:19
Hi @Goooler, the problem there is likely the `val isCI` at the top-level. Those top-level variables are compiled by the Kotlin DSL as members of the enclosing script class. 

Can you move the `val isCI` declaration to be just before the `publishing.onlyIf { isCI }` expression and see whether that fixes that situation for you?

**Comment by Goooler** [comment] 2024-04-04 14:27
- ✅ Moving `isCI` declaration before `publishing.onlyIf`, it works well.
- ❌ Declare `isCI` before `develocity`, nope.
- ❌ Inline `providers.environmentVariable("CI").isPresent` into `publishing.onlyIf`, nope.

I tried the second and third cases then, as I was migrating from

```kt
val isCI = providers.environmentVariable("CI").isPresent

gradleEnterprise {
    buildScan {
        termsOfServiceUrl = "https://gradle.com/terms-of-service"
        termsOfServiceAgree = "yes"
        publishAlwaysIf(isCI)
    }
}
```

which is compatible with CC in KTS.

**Comment by mlopatkin** [comment] 2024-04-04 18:14
This issue will be closed as a duplicate of

* #22879 

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***
[Configuration cache docs](https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:not_yet_implemented:accessing_top_level_at_execution) have some other workarounds for this issue

BTW, capturing the provider itself and only obtaining it inside the callback is a better practice for the configuration cache hits:
```kotlin
develocity {
    buildScan {
        termsOfUseUrl = "https://gradle.com/terms-of-service"
        termsOfUseAgree = "yes"
        val isCI = providers.environmentVariable("CI")
        publishing.onlyIf { isCI.isPresent }
    }
}
```
This way  the "CI" environment variable doesn't have to become the configuration input.

**Closed by mlopatkin** 2024-04-04 18:14 UTC
Labels: a:bug, in:kotlin-dsl, :wave: team-triage

**Comment by Goooler** [comment] 2024-04-05 00:05
Thanks for your reply!
