### ISSUE TITLE
transitive dependency not resolved using the highest version by 4.10.3  

### ISSUE THREAD

**Issue by restlesswind** [gradle/gradle#8438] opened 2019-02-07 16:58 UTC
We have upgraded from Gradle 3.5.1 to Gradle 4.10.3 which is supposed to include the fix for #6102. 
However, it seems like the transitive dependency is still not resolved using the highest version. The scenario as below:
 
Project B 
  --ch.qos.logback:logback-classic:1.2.3 (depends on ch.qos.logback:logback-core:1.2.3) 

Project A
  -- B [+]
  -- ch.qos.logback:logback-classic:1.1.3 (depends on ch.qos.logback:logback-core:1.1.3) 
    

With Gradle 3.5.1, Project A will use ch.qos.logback:logback-core:1.2.3
With Gradle 4.10.3, Project A will use ch.qos.logback:logback-core:1.1.3

I would like to know if the observed behavior with Gradle 4.10.3 is  intended? 
Is there any configuration/way we can change the default resolution rule back to using the old way (using the highest)? 

Thanks. 

### Your Environment

 * Build scan URL:

**Comment by melix** [comment] 2019-02-07 18:20
Can you provide a reproducer? I have tried locally with both `master` and `4.10.3` and it resolves properly:

#### a/build.gradle

```
dependencies {
   api project(':b')
   api 'ch.qos.logback:logback-classic:1.1.3'
}
```

#### b/build.gradle
````
dependencies {
   api 'ch.qos.logback:logback-classic:1.2.3'
}
````

Then: `gradle a:dependencyInsight --configuration compileClasspath --dependency logback-core`

```
> Task :a:dependencyInsight
ch.qos.logback:logback-core:1.2.3
   variant "runtime" [
      org.gradle.status = release (not requested)
      Requested attributes not found in the selected variant:
         org.gradle.usage  = java-api
   ]

ch.qos.logback:logback-core:1.2.3
\--- ch.qos.logback:logback-classic:1.2.3
     +--- compileClasspath
     \--- project :b
          \--- compileClasspath
```

**Comment by restlesswind** [comment] 2019-02-07 19:05
Thanks for looking this melix, our project structure is not multiple project build and layer is a bit different.... Below are the dependency insight results using different versions of Gradle (4.10 vs 3.5). Please let me know if doesn't provide sufficient information.

[vagrant@nsp-staging-gradle4 webfwk-web-backend]$ /tools/**gradle-4.10.3**/bin/gradle dependencyInsight --configuration compileClasspath --dependency logback-core

> Configure project :
*****************************************************************
Building [webfwk-web-backend] Version [19.6.0-rel.30-SNAPSHOT]
*****************************************************************

> Task :dependencyInsight
ch.qos.logback:logback-core:1.1.3
   variant "runtime" [
      org.gradle.status = release (not requested)
      Requested attributes not found in the selected variant:
         org.gradle.usage  = java-api
   ]

ch.qos.logback:logback-core:1.1.3
\--- ch.qos.logback:logback-access:1.1.3
     \--- compileClasspath

**ch.qos.logback:logback-core:1.2.3 -> 1.1.3**
+--- ch.qos.logback:logback-classic:1.2.3
|    +--- compileClasspath
|    +--- com.alu.nms.web:shared-spring-common:2.4.25
|    |    +--- compileClasspath
|    |    +--- com.nokia.nspos:shared-app-banner-utils:2.4.3
|    |    |    \--- compileClasspath
|    |    +--- com.nokia.nsp.shared:shared-fwk-services:2.0.4
|    |    |    \--- compileClasspath
|    |    +--- com.nokia.nspos.sso:sso-shared-common:19.6.0-rel.8
|    |    |    +--- compileClasspath
|    |    |    +--- com.nokia.nspos:shared-app-banner-utils:2.4.3 (*)
|    |    |    +--- com.alu.nms.web:webfwk-spring-rest:19.6.0-rel.6
|    |    |    |    +--- compileClasspath
|    |    |    |    \--- com.nokia.nspos:nspos-model-ui-rest-app-api:19.6.0-rel.24
|    |    |    |         \--- compileClasspath
|    |    |    \--- com.nokia.nsp.shared:shared-fwk-services:2.0.4 (*)
|    |    +--- com.nokia.nspos:nspos-kafka-messaging:19.6.0-rel.3
|    |    |    \--- com.nokia.nspos.sso:sso-shared-common:19.6.0-rel.8 (*)
|    |    \--- com.alu.nms.web:registration-service:19.6.0-rel.1
|    |         +--- com.nokia.nspos.sso:sso-shared-common:19.6.0-rel.8 (*)
|    |         \--- com.nokia.nspos:nspos-kafka-messaging:19.6.0-rel.3 (*)
|    \--- org.gnieh:logback-config:0.3.1
|         \--- com.alu.nms.web:shared-spring-common:2.4.25 (*)
\--- com.alu.nms.web:shared-spring-common:2.4.25 (*)

(*) - dependencies omitted (listed previously)

A web-based, searchable dependency report is available by adding the --scan option.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 11s
1 actionable task: 1 executed
[vagrant@nsp-staging-gradle4 webfwk-web-backend]$ /tools/**gradle-3.5.1**/bin/gradle dependencyInsight --configuration compileClasspath --dependency logback-core
*****************************************************************
Building [webfwk-web-backend] Version [19.6.0-rel.30-SNAPSHOT]
*****************************************************************
:dependencyInsight
ch.qos.logback:logback-core:1.2.3 (conflict resolution)
+--- ch.qos.logback:logback-classic:1.2.3
|    +--- compileClasspath
|    +--- com.alu.nms.web:shared-spring-common:2.4.25
|    |    +--- compileClasspath
|    |    +--- com.nokia.nspos:shared-app-banner-utils:2.4.3
|    |    |    \--- compileClasspath
|    |    +--- com.nokia.nspos.sso:sso-shared-common:19.6.0-rel.8
|    |    |    +--- compileClasspath
|    |    |    +--- com.nokia.nspos:shared-app-banner-utils:2.4.3 (*)
|    |    |    +--- com.alu.nms.web:webfwk-spring-rest:19.6.0-rel.6
|    |    |    |    +--- compileClasspath
|    |    |    |    \--- com.nokia.nspos:nspos-model-ui-rest-app-api:19.6.0-rel.24
|    |    |    |         \--- compileClasspath
|    |    |    \--- com.nokia.nsp.shared:shared-fwk-services:2.0.4
|    |    |         \--- compileClasspath
|    |    +--- com.nokia.nsp.shared:shared-fwk-services:2.0.4 (*)
|    |    +--- com.alu.nms.web:registration-service:19.6.0-rel.1
|    |    |    +--- com.nokia.nspos.sso:sso-shared-common:19.6.0-rel.8 (*)
|    |    |    \--- com.nokia.nspos:nspos-kafka-messaging:19.6.0-rel.3
|    |    |         \--- com.nokia.nspos.sso:sso-shared-common:19.6.0-rel.8 (*)
|    |    \--- com.nokia.nspos:nspos-kafka-messaging:19.6.0-rel.3 (*)
|    \--- org.gnieh:logback-config:0.3.1
|         \--- com.alu.nms.web:shared-spring-common:2.4.25 (*)
\--- com.alu.nms.web:shared-spring-common:2.4.25 (*)

**ch.qos.logback:logback-core:1.1.3 -> 1.2.3**
\--- ch.qos.logback:logback-access:1.1.3
     \--- compileClasspath

(*) - dependencies omitted (listed previously)

BUILD SUCCESSFUL

**Comment by melix** [comment] 2019-02-08 11:40
@bigdaz given that there are lots of paths leading to the same dependency, I feel like we have another ordering issue.

**Comment by ljacomet** [comment] 2019-02-08 12:24
I believe this is another occurrence of #7050.

@restlesswind Any chance you could try this with Gradle 5+ ?

**Comment by restlesswind** [comment] 2019-02-08 16:05
@ljacomet 
With gradle 5.2, it is resolved with the highest version. details as below. Thanks. 

[vagrant@nsp-staging-gradle4 webfwk-web-backend]$ /tools/gradle-5.2/bin/gradle --refresh-dependencies dependencyInsight --configuration compile --dependency logback-core
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.2/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Configure project :
*****************************************************************
Building [webfwk-web-backend] Version [19.6.0-rel.30-SNAPSHOT]
*****************************************************************
Maven publication 'artifactoryPublications' contains dependencies that will produce a pom file that cannot be consumed by a Maven client.
  - com.nokia.nspos.sso:sso-shared-common:19.6.0-rel.+ declared with a Maven incompatible version notation
  - com.alu.nms.web:webfwk-spring-rest:19.6.0-rel.+ declared with a Maven incompatible version notation
  - com.nokia.nspos:shared-app-banner-utils:2.4.+ declared with a Maven incompatible version notation
  - com.nokia.nspos:nspos-model-ui-rest-app-api:19.6.0-rel.+ declared with a Maven incompatible version notation
  - com.nokia.nsp.shared:shared-ds-defs:1.0.+ declared with a Maven incompatible version notation

> Task :dependencyInsight
ch.qos.logback:logback-core:1.2.3
   variant "runtime" [
      org.gradle.status             = release (not requested)
      org.gradle.usage              = java-runtime (not requested)
      org.gradle.component.category = library (not requested)
   ]
   Selection reasons:
      - By conflict resolution : between versions 1.1.3 and 1.2.3

ch.qos.logback:logback-core:1.2.3
+--- ch.qos.logback:logback-classic:1.2.3
|    +--- compile (requested ch.qos.logback:logback-classic:1.1.3)
|    +--- com.alu.nms.web:shared-spring-common:2.4.25
|    |    +--- compile (requested com.alu.nms.web:shared-spring-common:2.4.8)
|    |    +--- com.nokia.nspos:shared-app-banner-utils:2.4.3 (requested com.alu.nms.web:shared-spring-common:2.3.6)
|    |    |    \--- compile (requested com.nokia.nspos:shared-app-banner-utils:2.4.+)
|    |    +--- com.nokia.nsp.shared:shared-fwk-services:2.0.4
|    |    |    \--- compile
|    |    +--- com.nokia.nspos.sso:sso-shared-common:19.6.0-rel.9
|    |    |    +--- compile (requested com.nokia.nspos.sso:sso-shared-common:19.6.0-rel.+)
|    |    |    +--- com.nokia.nspos:shared-app-banner-utils:2.4.3 (requested com.nokia.nspos.sso:sso-shared-common:19.3.0-rel.+) (*)
|    |    |    +--- com.alu.nms.web:webfwk-spring-rest:19.6.0-rel.7 (requested com.nokia.nspos.sso:sso-shared-common:19.6.0-rel.+)
|    |    |    |    +--- compile (requested com.alu.nms.web:webfwk-spring-rest:19.6.0-rel.+)
|    |    |    |    \--- com.nokia.nspos:nspos-model-ui-rest-app-api:19.6.0-rel.25 (requested com.alu.nms.web:webfwk-spring-rest:19.6.0-rel.+)
|    |    |    |         \--- compile (requested com.nokia.nspos:nspos-model-ui-rest-app-api:19.6.0-rel.+)
|    |    |    \--- com.nokia.nsp.shared:shared-fwk-services:2.0.4 (requested com.nokia.nspos.sso:sso-shared-common:19.3.0-rel.+) (*)
|    |    +--- com.nokia.nspos:nspos-kafka-messaging:19.6.0-rel.3 (requested com.alu.nms.web:shared-spring-common:2.4.4)
|    |    |    \--- com.nokia.nspos.sso:sso-shared-common:19.6.0-rel.9 (requested com.nokia.nspos:nspos-kafka-messaging:19.6.0-rel.+) (*)
|    |    \--- com.alu.nms.web:registration-service:19.6.0-rel.1 (requested com.alu.nms.web:shared-spring-common:2.3.13)
|    |         +--- com.nokia.nspos.sso:sso-shared-common:19.6.0-rel.9 (requested com.alu.nms.web:registration-service:19.6.0-rel.+) (*)
|    |         \--- com.nokia.nspos:nspos-kafka-messaging:19.6.0-rel.3 (requested com.alu.nms.web:registration-service:19.6.0-rel.+) (*)
|    \--- org.gnieh:logback-config:0.3.1
|         \--- com.alu.nms.web:shared-spring-common:2.4.25 (*)
\--- com.alu.nms.web:shared-spring-common:2.4.25 (*)

ch.qos.logback:logback-core:1.1.3 -> 1.2.3
\--- ch.qos.logback:logback-access:1.1.3
     \--- compile

(*) - dependencies omitted (listed previously)

**Comment by ljacomet** [comment] 2019-02-08 16:07
Then I can only confirm that's #7050 you are suffering of. It affected Gradle 4.9 and 4.10. We tried backporting the fix for 4.10.3 but it was too risky for a bugfix release.
If you cannot upgrade to Gradle 5 immediately, I would recommend upgrading to 4.8 as an intermediate step.

**Comment by restlesswind** [comment] 2019-02-08 16:35
Thanks @ljacomet for confirming. Would you be planning to port the fix in 4.10.4 or a 4.11 release soon? We have our own gradle plugin code that has dependency on the underlining Groovy version. So downgrading to 4.8 or upgrading to 5 might not an easy solution for us.  Thanks.

**Comment by ljacomet** [comment] 2019-02-08 17:15
We are now developing in Gradle 5.x only. There is no plan to have another bugfix release on 4.10 nor a 4.11.

However 4.8 and 4.10 should be pretty close together in terms of APIs, including the Groovy version. 4.8 uses Groovy 2.4.12 and 4.10 uses Groovy 2.4.15.

**Comment by big-guy** [comment] 2019-02-08 19:05
Closing since this is a dupe of https://github.com/gradle/gradle/issues/7050 affecting 4.9 and 4.10.

As a workaround, you can downgrade to 4.8 or upgrade to 5.x

**Closed by big-guy** 2019-02-08 19:05 UTC
Labels: a:bug, in:dependency-management
