### ISSUE TITLE
Composite builds confuse projects with same name/path with outer the project

### ISSUE THREAD

**Issue by ApexModder** [gradle/gradle#30931] opened 2024-10-16 06:56 UTC
### Current Behavior

When using `includeBuild` on a build which contains a project of same name/path as the outer build, java fails to compile due to circular dependencies.

### Expected Behavior

expected java to compile and run with no issues, as the projects and deoendencies all hooked up to correct locations in my ide (Intelij IDEA)

### Context (optional)

I was attempting to substituate a included dependency to make development less of a hassle.
_Edit ProjectA -> publish to local maven -> reimport ProjectB_

### Self-contained Reproducer Project

https://github.com/ApexModder/CicularDependencyTest
Both projects should function perfectly fine on their own but `:Mod` does require `:Library` so publishing will be necessary without using `includeBuild`.

Expected `:Mod` to be able to access `:Library`s sub-projects, any edits made to them and be able to compile against them, but java fails due to circular dependencies.

```
FAILURE: Build failed with an exception.

* What went wrong:
Circular dependency between the following tasks:
:Vanilla:compileJava
\--- :Vanilla:compileJava (*)

(*) - details omitted (listed previously)


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 874ms
```

Nowhere am i telling `:Vanilla` to depend on itself, other than if gradle is confusing `:Library:Vanilla` for `:Mod:Vanilla` even though they are apart of 2 completely separate builds.

### Gradle version

8.8

### Your Environment (optional)

I am running under the following
- Windows 11 (23H2)
- Java eclipse-temurin-21
- Gradle Wrapper: 8.8
- Intellij IDEA Ultimate 2024.2.3

**Comment by ov7a** [comment] 2024-10-16 13:14
This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/847

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

**Closed by ov7a** 2024-10-16 13:14 UTC
Labels: a:bug, to-triage
