### ISSUE TITLE
No way to quiet --write-locks

### ISSUE THREAD

**Issue by Kitanotori** [gradle/gradle#21445] opened 2022-08-05 01:16 UTC
### Expected Behavior
`./gradlew dependencies -q --write-locks` should not output dependency info in case of no errors (i.e., only generate lockfiles)

### Current Behavior
`./gradlew dependencies -q --write-locks` outputs all dependency info even if no errors.

### Context
In case of non-trivial projects, the output of --write-locks is quite long and thus causes inconvenience.

**Comment by jgreen210** [comment] 2023-01-03 17:22
For an android project with a moderate but not excessive number of dependencies and a few flavours, it takes about a minute to scroll through the output in iterm2 by holding down page up button. It's therefore very hard to find the start, especially if have run the task a few times. It's also hard to find the interesting parts of the output if do want to look at it.

**Comment by ljacomet** [comment] 2023-01-09 12:06
From what I understand, the issue is that a reporting task is used for its side effect of resolving configurations.

The output problem is not related to using `--write-locks` but to using `dependencies` as the trigger.

The [documentation](https://docs.gradle.org/7.6/userguide/dependency_locking.html#lock_all_configurations_in_one_build_execution) provides an alternative way to handle this, however Android project cannot use it as-is. They need to replicate the way Android does some of its dependency resolution.

There is no intention of making report task silent when used with `-q`.

**Closed by ljacomet** 2023-01-09 12:06 UTC
Labels: a:bug, in:dependency-locking

**Comment by jgreen210** [comment] 2023-01-09 18:22
Having to add some boiler plate to a project using lock files nicely and that boilerplate not working for android suggests to me that more work is needed here and that this issue shouldn't be closed.

**Comment by jgreen210** [comment] 2023-01-09 18:25
The bundler/cocoapods/npm approach would avoid this issue by not needing a special task/command to update the lock files.

**Comment by jgreen210** [comment] 2023-01-09 18:25
Maybe gradle should do the same, even if it means have to avoid lazy configuration if lock files are enabled?

**Comment by jgreen210** [comment] 2023-01-09 18:27
> There is no intention of making report task silent when used with -q.

What about if both -q and --write-locks are used? ...or if invoke the same task using some other name?
