### ISSUE TITLE
Clean install of gradle fails on helloworld

### ISSUE THREAD

**Issue by Nic007** [gradle/gradle#4112] opened 2018-01-22 18:32 UTC
### Expected Behavior
I did a fresh install of Gradle 4.4.1 with sdkman, and I expect the [example hello world](https://docs.gradle.org/current/userguide/tutorial_using_tasks.html) to succeed.

```
gradle -q hello
Hello world!
```

### Current Behavior

```
gradle -q hello

FAILURE: Build failed with an exception.

* What went wrong:
org/apache/http/ssl/SSLInitializationException
> org.apache.http.ssl.SSLInitializationException

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

With the stacktrace option:

```
gradle -q hello --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
org/apache/http/ssl/SSLInitializationException
> org.apache.http.ssl.SSLInitializationException

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
java.lang.NoClassDefFoundError: org/apache/http/ssl/SSLInitializationException
        at org.gradle.internal.resource.transport.http.DefaultSslContextFactory.<init>(DefaultSslContextFactory.java:53)
        at org.gradle.internal.resource.transport.http.HttpResourcesPluginServiceRegistry$GlobalScopeServices.createSslContextFactory(HttpResourcesPluginServiceRegistry.java:39)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.internal.service.ReflectionBasedServiceMethod.invoke(ReflectionBasedServiceMethod.java:35)
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:795)
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:748)
        at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectProvider.getInstance(DefaultServiceRegistry.java:574)
        at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:623)
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:761)
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:747)
        at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectProvider.getInstance(DefaultServiceRegistry.java:574)
        at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:623)
        at org.gradle.internal.service.DefaultServiceRegistry.getAll(DefaultServiceRegistry.java:318)
        at org.gradle.internal.service.DefaultServiceRegistry$ParentServices.getAll(DefaultServiceRegistry.java:1140)
        at org.gradle.internal.service.DefaultServiceRegistry$CachingProvider.getAll(DefaultServiceRegistry.java:997)
        at org.gradle.internal.service.DefaultServiceRegistry$CompositeProvider.getAll(DefaultServiceRegistry.java:1060)
        at org.gradle.internal.service.DefaultServiceRegistry.getAll(DefaultServiceRegistry.java:315)
        at org.gradle.internal.service.DefaultServiceRegistry$ParentServices.getAll(DefaultServiceRegistry.java:1140)
        at org.gradle.internal.service.DefaultServiceRegistry$CachingProvider.getAll(DefaultServiceRegistry.java:997)
        at org.gradle.internal.service.DefaultServiceRegistry$CompositeProvider.getAll(DefaultServiceRegistry.java:1060)
        at org.gradle.internal.service.DefaultServiceRegistry.getAll(DefaultServiceRegistry.java:315)
        at org.gradle.internal.service.DefaultServiceRegistry$ParentServices.getAll(DefaultServiceRegistry.java:1140)
        at org.gradle.internal.service.DefaultServiceRegistry$CachingProvider.getAll(DefaultServiceRegistry.java:997)
        at org.gradle.internal.service.DefaultServiceRegistry$CompositeProvider.getAll(DefaultServiceRegistry.java:1060)
        at org.gradle.internal.service.DefaultServiceRegistry.getAll(DefaultServiceRegistry.java:315)
        at org.gradle.internal.service.DefaultServiceRegistry$ParentServices.getAll(DefaultServiceRegistry.java:1140)
        at org.gradle.internal.service.DefaultServiceRegistry$CachingProvider.getAll(DefaultServiceRegistry.java:997)
        at org.gradle.internal.service.DefaultServiceRegistry$CompositeProvider.getAll(DefaultServiceRegistry.java:1060)
        at org.gradle.internal.service.DefaultServiceRegistry$DefaultLookupContext$ServicesWithTypeLookup.apply(DefaultServiceRegistry.java:1417)
        at org.gradle.internal.service.DefaultServiceRegistry$DefaultLookupContext$ServicesWithTypeLookup.apply(DefaultServiceRegistry.java:1407)
        at org.gradle.internal.service.DefaultServiceRegistry$DefaultLookupContext.getServiceProvider(DefaultServiceRegistry.java:1297)
        at org.gradle.internal.service.DefaultServiceRegistry$DefaultLookupContext.find(DefaultServiceRegistry.java:1285)
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.bind(DefaultServiceRegistry.java:722)
        at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.prepare(DefaultServiceRegistry.java:628)
        at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.getService(DefaultServiceRegistry.java:642)
        at org.gradle.internal.service.DefaultServiceRegistry$OwnServices.getService(DefaultServiceRegistry.java:465)
        at org.gradle.internal.service.DefaultServiceRegistry$CachingProvider.getService(DefaultServiceRegistry.java:970)
        at org.gradle.internal.service.DefaultServiceRegistry$CompositeProvider.getService(DefaultServiceRegistry.java:1034)
        at org.gradle.internal.service.DefaultServiceRegistry$DefaultLookupContext$4.apply(DefaultServiceRegistry.java:1356)
        at org.gradle.internal.service.DefaultServiceRegistry$DefaultLookupContext$4.apply(DefaultServiceRegistry.java:1353)
        at org.gradle.internal.service.DefaultServiceRegistry$DefaultLookupContext.getServiceProvider(DefaultServiceRegistry.java:1297)
        at org.gradle.internal.service.DefaultServiceRegistry$DefaultLookupContext.find(DefaultServiceRegistry.java:1285)
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.bind(DefaultServiceRegistry.java:722)
        at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.prepare(DefaultServiceRegistry.java:628)
        at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.getService(DefaultServiceRegistry.java:642)
        at org.gradle.internal.service.DefaultServiceRegistry$OwnServices.getService(DefaultServiceRegistry.java:465)
        at org.gradle.internal.service.DefaultServiceRegistry$CachingProvider.getService(DefaultServiceRegistry.java:970)
        at org.gradle.internal.service.DefaultServiceRegistry$CompositeProvider.getService(DefaultServiceRegistry.java:1034)
        at org.gradle.internal.service.DefaultServiceRegistry$DefaultLookupContext$4.apply(DefaultServiceRegistry.java:1356)
        at org.gradle.internal.service.DefaultServiceRegistry$DefaultLookupContext$4.apply(DefaultServiceRegistry.java:1353)
        at org.gradle.internal.service.DefaultServiceRegistry$DefaultLookupContext.getServiceProvider(DefaultServiceRegistry.java:1297)
        at org.gradle.internal.service.DefaultServiceRegistry$DefaultLookupContext.find(DefaultServiceRegistry.java:1285)
        at org.gradle.internal.service.DefaultServiceRegistry.getServiceProvider(DefaultServiceRegistry.java:350)
        at org.gradle.internal.service.DefaultServiceRegistry.doGet(DefaultServiceRegistry.java:341)
        at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:325)
        at org.gradle.internal.service.scopes.BuildScopeServices.defaultScriptPluginFactory(BuildScopeServices.java:295)
        at org.gradle.internal.service.scopes.BuildScopeServices.createScriptPluginFactory(BuildScopeServices.java:287)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.internal.service.ReflectionBasedServiceMethod.invoke(ReflectionBasedServiceMethod.java:35)
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:795)
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:748)
        at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectProvider.getInstance(DefaultServiceRegistry.java:574)
        at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:623)
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:761)
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:747)
        at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectProvider.getInstance(DefaultServiceRegistry.java:574)
        at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:623)
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:761)
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:747)
        at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectProvider.getInstance(DefaultServiceRegistry.java:574)
        at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:623)
        at org.gradle.internal.service.DefaultServiceRegistry.doGet(DefaultServiceRegistry.java:344)
        at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:325)
        at org.gradle.initialization.DefaultGradleLauncherFactory.doNewInstance(DefaultGradleLauncherFactory.java:174)
        at org.gradle.initialization.DefaultGradleLauncherFactory.newInstance(DefaultGradleLauncherFactory.java:106)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:40)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:57)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:32)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:69)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:30)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:45)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.ClassNotFoundException: org.apache.http.ssl.SSLInitializationException
        at org.gradle.internal.classloader.TransformingClassLoader.findClass(TransformingClassLoader.java:53)
        ... 120 more


* Get more help at https://help.gradle.org
```

### Context
However the folder and the build file, gradle crash. It seems like the --version and --help work.

### Steps to Reproduce (for bugs)
Installation of Gradle:

`sdk install gradle 4.4.1`

build.gradle file:

```
task hello {
    doLast {
        println 'Hello world!'
    }
}
```

Expected build command:

`gradle -q hello`

### Your Environment
As expected, the scan fail:

```
gradle build --scan

FAILURE: Build failed with an exception.

* What went wrong:
org/apache/http/ssl/SSLInitializationException
> org.apache.http.ssl.SSLInitializationException

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

I work on a computer from university where I don't have the admin right. sdkman is configured at the root of my user folder (which is synced between computer over the network).

I am working on fedora: 9.13-200.fc25.x86_64

Here is my java version:

```
java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
```

**Comment by oehme** [comment] 2018-01-23 09:04
Thank you for the report! It seems there was a security exception on your system, but it could not be reported, because the exception type we were trying to use was not on the classpath. Looks like there is a missing test case for that scenario.

**Comment by Nic007** [comment] 2018-01-23 16:33
Quick update: I've removed ./gradle and ./sdkman and I've re-installed the two tools with the same commands. Now it works. I really don't understand what occured...

**Comment by oehme** [comment] 2018-01-23 16:50
Interesting, so it could be caused by a broken download of Gradle. The system didn't change otherwise?

**Comment by Nic007** [comment] 2018-01-23 16:52
Nothing changed in the system. Another user tried the same thing on my computer and it worked first time.

**Comment by oehme** [comment] 2018-01-23 16:54
Thanks for following up. In that case I'll close this as non-reproducible.

**Closed by oehme** 2018-01-23 16:54 UTC
Labels: a:bug, from:contributor, in:core

**Comment by saleemepoch** [comment] 2020-03-22 10:11
I am on Chromebook's penguin container, running Debian 9, experiencing the same issue.

The first time it worked fine but thereafter it's throwing this error.

System information:
{
"platform": "linux",
"shell": "/bin/bash",
"os": "Linux penguin 4.19.87-07826-g55ab70aff690 #1 SMP PREEMPT Tue Feb 4 17:29:42 PST 2020 x86_64 GNU/Linux\n",
"procArch": "x64",
"nodeVer": "10.19.0",
"npmVer": "6.13.4",
"nodeGypVer": null,
"nativeScriptCliVersion": "6.5.0",
"gitVer": "2.11.0",
"dotNetVer": null,
"javacVersion": "1.8.0_242",
"javaVersion": "1.8.0_242",
"javaPath": "/usr/lib/jvm/java-8-openjdk-amd64/bin/java",
"adbVer": "1.0.41",
"androidInstalled": true,
"monoVer": null,
"gradleVer": "5.2.1",
"isAndroidSdkConfiguredCorrectly": true,
"xcodeprojLocation": null,
"itunesInstalled": false,
"isCocoaPodsWorkingCorrectly": false,
"isCocoaPodsUpdateRequired": false,
"pythonInfo": null
}
