### ISSUE TITLE
Values in TreeMap object not populated correctly

### ISSUE THREAD

**Issue by skyviper** [gradle/gradle#13178] opened 2020-05-19 16:40 UTC
### Expected Behavior

Values should be input to the Map Array as shown in the switch statement.
### Current Behavior

The values are not going into the correct location for the 
sname and version parameters.
### Context

Schedule...accuracy...confidence in Gradle.

### Steps to Reproduce 

[build2.properties.txt](https://github.com/gradle/gradle/files/4651865/build2.properties.txt)
[build.gradle.txt](https://github.com/gradle/gradle/files/4651868/build.gradle.txt)

### Your Environment

Windows 7 and Windows 10

Build scan URL:

**Comment by eskatos** [comment] 2020-05-19 16:52
Hi @skyviper,

Looking at your build script I can see a first issue: your `readProperties` task is processing the properties file at configuration time. It means that if you run `gradle help` your code will be executed even if you don't request your `readProperties` task to be executed. You should add a `doLast {}` action and do the processing inside it.

```groovy
task readProperties {
    doLast {
        // processing goes here
    }
}
```

This is shown at https://docs.gradle.org/current/userguide/tutorial_using_tasks.html#sec:hello_world and below.

Having said that, the problem you are facing is with your algorithm that parses your properties file, not with Gradle. I don't see any Gradle bug here so will close this issue, please reopen if you think something is not working as expected and provide steps to reproduce.

GitHub issues are for bug reports or feature requests. For support questions, please prefer the Gradle forums at https://discuss.gradle.org/ or join the Gradle community on Slack, you can find a link here https://github.com/gradle/gradle#need-help

**Comment by skyviper** [comment] 2020-05-19 17:09
Hi Paul,Why close the issue before I can answer you?
Tony
    On Tuesday, May 19, 2020, 10:53:04 AM MDT, Paul Merlin <notifications@github.com> wrote:  
 
 


Closed #13178.

**Comment by eskatos** [comment] 2020-05-19 17:12
@skyviper you can answer a closed issue as I wrote. But no worries, I reopened. Please provide more information.

**Comment by skyviper** [comment] 2020-05-19 17:14
Hi Paul,It seems that you didn't look at the results. If the algorithm is the issue then why does all of the values going into the method look correct but the behavior is inconsistent? How can you know if there is a bug if you don't look at what its doing?
Regards,
Tony
    On Tuesday, May 19, 2020, 10:53:04 AM MDT, Paul Merlin <notifications@github.com> wrote:  
 
 


Hi @skyviper,

Looking at your build script I can see a first issue: your readProperties task is processing the properties file at configuration time. It means that if you run gradle help your code will be executed even if you don't request your readProperties task to be executed. You should add a doLast {} action and do the processing inside it.
task readProperties {
    doLast {
        // processing goes here
    }
}
This is shown at https://docs.gradle.org/current/userguide/tutorial_using_tasks.html#sec:hello_world and below.

Having said that, the problem you are facing is with your algorithm that parses your properties file, not with Gradle. I don't see any Gradle bug here so will close this issue, please reopen if you think something is not working as expected and provide steps to reproduce.

GitHub issues are for bug reports or feature requests. For support questions, please prefer the Gradle forums at https://discuss.gradle.org/ or join the Gradle community on Slack, you can find a link here https://github.com/gradle/gradle#need-help

**Comment by skyviper** [comment] 2020-05-19 17:22
Hi Paul,
I do understand about using a doLast method but why does it matter here, since I am only running this task in my testing and nothing outside of this task is dependent on the action? Theres also a doFirst method I need a little more detail than what the manual shows.

Thanks.

**Comment by eskatos** [comment] 2020-05-19 17:25
> I do understand about using a doLast method but why does it matter here, since I am only running this task in my testing and nothing outside of this task is dependent on the action?

That was a "by the way" so you don't get surprised once you start using that task in a larger workflow.

> If the algorithm is the issue then why does all of the values going into the method look correct but the behavior is inconsistent?

I did look at what you provided but I suppose I must have missed something. Could you please clarify what do you mean by "the behavior is inconsistent"? What is Gradle doing wrong?

**Comment by skyviper** [comment] 2020-05-19 17:34
Hi,
Replacing the TreeMap with the Groovy def myMap = [sname:'', name:'', buildnr:'', path:'', version:'', pkgAID:'', appletName:'', appletAID:''] fixed the incorrect value issue. So, now that brings the question of why does using TreeMap<String,String> zpackage =[sname:'', name:'', buildnr:'', path:'', version:'', pkgAID:'', appletName:'', appletAID:''] fail? Bug???

**Comment by eskatos** [comment] 2020-05-19 17:45
Could it be the difference between `String` and `GString` in Groovy? https://groovy-lang.org/syntax.html#_gstring_and_string_hashcodes

Anyway, glad you sorted it out.

**Comment by skyviper** [comment] 2020-05-19 17:49
Idk. Thats what I thought the bug reporting is supposed to be for. But it does show incorrect behavior. The question is what will be done about it. Especially since Gradle/Groovy is supposed to be able to run standard Java too.

**Comment by eskatos** [comment] 2020-05-20 08:21
I took another look at your scripts. You can find what I have in this gist https://gist.github.com/eskatos/b318065c6b656d1e52ff196270f59a17 where
- `build-original.gradle` uses `TreeMap<String, String> zpackage = [...]`
- `build.gradle` uses `def zpackage = [...]`
- `output.diff` shows the diff in output between the two

The only difference is the output order which make sense because `TreeMap` has a different ordering contract.

**Comment by eskatos** [comment] 2020-05-20 08:24
I don't see any Gradle bug here.

Gradle runs Groovy. If you think you found a bug in Groovy then please try to reproduce in a `.groovy` class and report to the Groovy project https://groovy-lang.org/

I'm going to close this issue. Please feel free to comment or reopen with reproducing steps if you still think you're facing a Gradle bug.

**Closed by eskatos** 2020-05-20 08:24 UTC
Labels: a:bug, from:contributor

**Comment by skyviper** [comment] 2020-05-22 03:03
Hi,
I reviewed you comments and they don't make sense to me. Since the values are being written by key and read by key the values should align to the correct output. So before I reopen this as an issue, will you explain why this doesn't work correctly. Please review the results against the code.

Thanks.

**Comment by eskatos** [comment] 2020-05-22 07:13
Hi @skyviper,

Sorry if my comments were not clear. From what I tried above, see my comment with the link to gist and diff in output, the only difference I can see with what I have is the output order.

The Map iteration used to produce the output in your code depends on the contract of the Map implementation. Groovy uses `LinkedHashMap` as the default `Map` implementation (e.g. when doing `def zpackages = [...]`).

[LinkedHashMap](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/LinkedHashMap.html) and [TreeMap](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/TreeMap.html) have a different ordering contract. That explains the different order in the output.

I hope this clarifies things.
