### ISSUE TITLE
Spurious task dependency introduced through includeBuild leads to circular dependency error

### ISSUE THREAD

**Issue by hovinen** [gradle/gradle#13104] opened 2020-05-13 09:25 UTC
I have three projects: a library, an application, and a platform. The library has three subprojects, `variant-a`, `variant-b` and `common`; `common` is a common dependency of `variant-a` and `variant-b`. When replacing the library dependency specified by the platform with `variant-a` in the application, Gradle fails claiming that there were a circular dependency between tasks.

### Expected Behavior
The included library should be built exactly as it would be if I built it by itself.

### Current Behavior
When I attempt to build, I get:

```
FAILURE: Build failed with an exception.

* What went wrong:
Circular dependency between the following tasks:
:library:common:classes
\--- :library:common:compileJava
     +--- :library:common:compileKotlin
     |    \--- :library:variant-a:jar
     |         +--- :library:common:classes (*)
```

The dependency of the task `common:compileKotlin` on `variant-a:jar` makes no sense and does not exist when building the library itself. It is spuriously added when including the build in another project.

### Context
I wish to test the application against a development version of the library using a composite build.

### Steps to Reproduce 
With the setup described above, I add:

```
includeBuild("../library") {
    dependencySubstitution {
        substitute module("library group:library name") with project(":variant-a")
    }
}
```

to `settings.gradle` in the application project.

The inclusion of the platform may be related; see https://discuss.gradle.org/t/composite-build-fails-with-circular-dependency-when-using-own-platform-depedency-created-by-java-platform-plugin/33241.

### Your Environment
This appears at least in Gradle version 6.0.1 through 6.4.

**Comment by melix** [comment] 2020-08-17 09:50
Looks like a duplicate of #13979. Would you mind checking if you have the same error with the latest 6.7 snapshot? https://services.gradle.org/distributions-snapshots/gradle-6.7-20200816220041+0000-bin.zip

**Comment by melix** [comment] 2021-04-14 14:39
I'm closing this, please reopen if the problem still happens on latest releases.

**Closed by melix** 2021-04-14 14:39 UTC
Labels: a:bug, in:dependency-management
