### ISSUE TITLE
Gradle Error while build apk in Ionic 3

### ISSUE THREAD

**Issue by Topiya** [gradle/gradle#2851] opened 2017-09-02 05:59 UTC
I am getting below error while build apk in ionic application.

```
[ERROR] An error occurred while running cordova build android (exit code 1):


        ANDROID_HOME=C:\Users\XYZ\AppData\Local\Android\sdk
        JAVA_HOME=C:\Program Files\java\jdk1.8.0_31
        Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
        :wrapper

        BUILD SUCCESSFUL

        Total time: 11.122 secs
        Subproject Path: CordovaLib

        FAILURE: Build failed with an exception.

        * What went wrong:
        Could not dispatch a message to the daemon.

        * Try:
        Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
        Error: cmd: Command failed with exit code 1 Error output:
        FAILURE: Build failed with an exception.

        * What went wrong:
        Could not dispatch a message to the daemon.

        * Try:
        Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```
Result when tried with --stacktrace,--debug

```
[ERROR] An error occurred while running cordova build android (exit code 1):
        ANDROID_HOME=C:\Users\XYZ\AppData\Local\Android\sdk
        JAVA_HOME=C:\Program Files\java\jdk1.8.0_31
        :wrapper

        BUILD SUCCESSFUL

        Total time: 0.862 secs
        Subproject Path: CordovaLib

        FAILURE: Build failed with an exception.

        * What went wrong:
        Received invalid response from the daemon: 'org.gradle.launcher.daemon.protocol.ForwardInput@5b6ec132' is a
        result of a type we don't have a strategy to handle. Earlier, 'Build{id=ce257caf-e024-4abd-90a8-72d733ea91d7.1,
        currentDir=D:\app}' request was sent to the daemon.
        Diagnostics:
        No diagnostics available.

        * Try:
        Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
        Error: cmd: Command failed with exit code 1 Error output:
        FAILURE: Build failed with an exception.

        * What went wrong:
        Received invalid response from the daemon: 'org.gradle.launcher.daemon.protocol.ForwardInput@5b6ec132' is a
        result of a type we don't have a strategy to handle. Earlier, 'Build{id=ce257caf-e024-4abd-90a8-72d733ea91d7.1,
        currentDir=D:\app}' request was sent to the daemon.
        Diagnostics:
        No diagnostics available.

        * Try:
        Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

cordova requirements output:
```
Requirements check results for android:
Java JDK: installed 1.8.0
Android SDK: installed true
Android target: installed android-25
Gradle: installed C:\Program Files\Android\Android Studio\gradle\gradle-3.2\bin\gradle
```

Can anyone please provide any solution for this?

**Comment by blindpirate** [comment] 2017-09-02 06:26
Looks like something is wrong with daemon. Please try `gradle --stop` to stop all daemons and retry or start your build with `--no-daemon`.

**Comment by Topiya** [comment] 2017-09-02 06:37
**gradle --stop** command gives below result
```
'gradle' is not recognized as an internal or external command,
operable program or batch file.
```
So I had tried with `gradlew --stop` command to stop but this command runs for very long time and showing below message only.
`Stopping Daemon(s)`

I have tried `gradlew --status` but this command also not showing any message and keeps running.

**Comment by blindpirate** [comment] 2017-09-02 06:45
Seems you don't add `gradle` into your [`PATH`](https://en.wikipedia.org/wiki/PATH_(variable)#DOS.2C_OS.2F2.2C_and_Windows). Never mind, it's same to use `gradlew --stop`. If it is stuck for a long time, maybe that is the cause of the issue. Try to find the daemon process in windows task manager and kill it (it is named with something like `GradleDaemon`). If it's a bit hard for you, try to restart you computer simply.

**Comment by Topiya** [comment] 2017-09-02 07:15
`gradle --stop `command gives below result

```
'gradle' is not recognized as an internal or external command,
operable program or batch file.
```
So I had tried with `gradlew --stop` command to stop but this command runs for very long time and showing below message only.
`Stopping Daemon(s)
`

I have tried to get status with `gradlew --status` but this command also not showing any message and keeps running.

**Comment by Topiya** [comment] 2017-09-02 07:16
I have tried with computer restarting and tried to build but again same error.

**Comment by blindpirate** [comment] 2017-09-02 07:31
Looks like you're nesting one build into another:

```
An error occurred while running cordova build android (exit code 1):
        ANDROID_HOME=C:\Users\XYZ\AppData\Local\Android\sdk
        JAVA_HOME=C:\Program Files\java\jdk1.8.0_31
        :wrapper

        BUILD SUCCESSFUL

        Total time: 0.862 secs
        Subproject Path: CordovaLib
```
 because there's a successful build. It's a bit weird to have a successful build in a failed build.  It would be great if you can provide a reproducible sample to let me know the project structure.

Here's the advice: add `--no-daemon` option to you build command to disable daemon. See [here](https://docs.gradle.org/current/userguide/gradle_daemon.html) for more details.

**Comment by blindpirate** [comment] 2017-09-04 01:27
@Topiya Since I didn't hear your response, I would close it for the moment. Please feel free to reopen it if you have any questions.

**Closed** 2017-09-04 01:28 UTC
Labels: a:question, affects-version:3.2, from:contributor

**Comment by parkhisharma** [comment] 2018-07-12 07:17
There is a problem with your gradle, it's unable to access the port required or some process is blocking its execution, try disabling anti-virus. It worked for me.

**Comment by lepabloski** [comment] 2019-02-01 11:21
Good morning, I solved this issue, updating the java sdk. Greetings.
