### ISSUE TITLE
Cannot use the version selector

### ISSUE THREAD

**Issue by pnguyen9** [gradle/gradle#27278] opened 2023-12-04 15:18 UTC
### Issue type

Wrong or misleading information

### Problem description

I was trying to look at a different version of Gradle by using the arrow button in the upper left corner. However, after hovering over the arrow to show the list, whenever I moved the mouse down, the list vanished, prompting a Looney Tunesque trolling.

![ezgif-4-2c1774d0cd](https://github.com/gradle/gradle/assets/22443655/ee621ff7-2d04-47c0-b859-b2d6b7989f90)

### Page with the problem

https://docs.gradle.org/current/userguide/networking.html#networking_gradle

**Comment by ov7a** [comment] 2023-12-05 13:57
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/24864

Please add your use case and 👍 to that issue.

***

While it's not 100% duplicate, let's track this in one place.

**Closed by ov7a** 2023-12-05 13:57 UTC
Labels: a:documentation, to-triage
