### ISSUE TITLE
Android source dependency - Unable to find module with Gradle path

### ISSUE THREAD

**Issue by sklinefelter** [gradle/gradle#11538] opened 2019-12-02 23:04 UTC
I am trying to leverage https://blog.gradle.org/introducing-source-dependencies so that Project A can consume a library from source (in this context it's https://github.com/isuPatches/WiseFy). 

I started with the recommended setup in Project A's settings.gradle:
 
```
sourceControl {
    gitRepository(uri("https://github.com/isuPatches/WiseFy.git")) {
        producesModule("com.isupatches:wisefy")
    }
}
```

And added this to the module .gradle:

```
  implementation('com.isupatches:wisefy:v4.0.0') {
        version {
            branch = '4.x'
        }
    }
```
  

But I am receiving this error:

```
ERROR: Unable to find module with Gradle path ':wisefy' (needed by module 'app'.)
```

Here is WiseFy's settings.gradle:

```
include ':wisefy', ':wisefysample'
```

The project structure for WiseFy is a typical Android app with a library module:

```
    project    
      |- wisefy
      |- wisefysample
```

What am I doing incorrectly?

### Expected Behavior

Source code should be downloaded based on the git tag and branch and the gradle sync should complete successfully.

### Current Behavior

```
ERROR: Unable to find module with Gradle path ':wisefy' (needed by module 'app'.)
```

### Context

I am unable to debug or use this library without it being deployed to a Maven repository of some sort.

### Steps to Reproduce 

1.  Create Android project (I started with Empty Activity)
2. Ensure AGP version is set to 3.4.1
3. Add source control block to settings.gradle

```
sourceControl {
    gitRepository(uri("https://github.com/isuPatches/WiseFy.git")) {
        producesModule("com.isupatches:wisefy")
    }
}
```

4. Add implement statement into app level build.gradle

```
  implementation('com.isupatches:wisefy:v4.0.0') {
        version {
            branch = '4.x'
        }
    }
```

### Your Environment

- `com.android.tools.build:gradle:3.4.1`
- Mac 10.14.6
- Android Studio 3.5.2

**Comment by jjohannes** [comment] 2019-12-06 08:46
I am not sure if this is the problem, but I noticed that there is no `rootProject.name` set in `settings.gradle` of the `WiseFy` build. The name of the project then will be `WiseFy` (with upper-case letters) while I think the name has to match the name segment in the coordinates (which is `wisefy`).

Can you try forking the _wisefy_ project and add `rootProject.name="wisefy"` to the branch you are depending on?

**Comment by sklinefelter** [comment] 2019-12-10 04:51
I actually own WiseFy on my non-work GitHub related account :)  I found that if I update Gradle to grade 6.0.1 that I see the source code downloaded into the .gradle/vcs-1 directory, but it seems the classes and code is not available on the classpath.

**Comment by jjohannes** [comment] 2019-12-12 11:19
@sklinefelter I tried what you describe in the issue and for me it is working with Gradle 5.6.4.
With Gradle 6.0.1 it also works, but I get an error in running `cpdCheck` with  `cpd.internal.CpdReportsImpl` (which is most likely a compatibility with that plugin and Gradle 6).

I assume something else in your build is not configured correctly. Can you provide a complete reproducible example please.

**Comment by sklinefelter** [comment] 2019-12-17 05:55
I created this example app to show the issue: https://github.com/isuPatches/SourceDependencyExample

**Comment by jjohannes** [comment] 2019-12-17 10:50
Thank @sklinefelter. I realized now that you are having the issue when syncing in Android Studio. I was able to reproduce the problem there.

- In general this works from the command line. It might also work if you open the project in plain DEA. Maybe that is sufficient for what you want to do.
- The ERROR you are seeing comes from Android Studio and it is an issue on their side: https://issuetracker.google.com/issues/141363239
- Nevertheless, there was also another error printed which is actually a bug with dependency graph serialization/caching when "branch" versions are used. I am workin on fixing that but I am afraid that alone would not improve the Android Studio situation.

**Comment by sklinefelter** [comment] 2019-12-17 17:50
@jjohannes Thanks you so much for the effort.  I added a comment on the Google issue to show that this functionality would be much welcome.

**Comment by jjohannes** [comment] 2019-12-18 10:18
Hi @sklinefelter thanks. The problem is that this setup in `com.github.technoir42.aar-publish` is not sufficient for Gradle 6 and a proper publishing of Android variants:
https://github.com/technoir42/aar-publish-plugin/blame/2a3da935c9d1a618d0a784d1e04f32fb3adab3e2/plugin/src/main/kotlin/com/github/technoir42/plugin/aarpublish/AarPublishPlugin.kt#L41-L44

With Android `3.6.0` (beta05+) and `4.0.0` publishing is supported by the Android plugins directly and the components are setup in the right way there. You should use that directly by using one of the following components in the publication you setup in "org.shipkit.android-publish":

- `"release"` (this is probably what you want).
- `"debug"`
- `"all"`

**Comment by ljacomet** [comment] 2020-05-18 12:54
Closing as the issue discovered on the Gradle side has been fixed.

**Closed by ljacomet** 2020-05-18 12:54 UTC
Labels: @jvm, from:contributor, in:dependency-management
