### ISSUE TITLE
Gradle build is failing for docker in Gradle 8.5 version

### ISSUE THREAD

**Issue by imjackinthegarden** [gradle/gradle#27597] opened 2024-01-05 11:47 UTC
### Current Behavior

I am using Gradle 7.4 to build java application images and updated 'com.palantir.docker' plugins in build.gradle file 

But build are failing after i upgraded gradle to 8.5 version.
we updated dependencies and plugins in build.gradle file as below -

```
dependencies {
           classpath 'com.bmuschko:gradle-docker-plugin:9.4.0'
        }

apply plugin: 'com.bmuschko.docker-java-application'


docker {
    dependsOn build
    name "${getImageName()}"
    copySpec.with {
        from('.') {
            include 'upgrademyapps/**'
            into '.'
        }
    }
    copySpec.with {
        from('../common') {
                include 'sslInitContainer/build/libs/**'
                into '.'
        }
    }
    files "${bootJar.archivePath}","docker-entrypoint.sh","myapps.dep",
    "upgrademyapps/build/libs/myapps.jar","sslInitContainer/build/libs/sslInitContainer.jar"
    buildArgs(['JAR_FILE': "${bootJar.archiveName}"])
    new File("${projectDir}/${project.name}_tag.txt").text = "$name"
}
```

Got below error while building the images using Gradle 8.5
```
* What went wrong:
A problem occurred evaluating project ':myapplication'.
> Could not find method dependsOn() for arguments [task ': myapplication:build'] on extension 'docker' of type com.bmuschko.gradle.docker.DockerExtension.
```

### Expected Behavior

Gradle build should happen with creating images for myapplication using below command-

gradle build docker -x test

### Context (optional)

Please help in fixing the issue. Also provide me the steps how I can proceed with creating docker image using gradle 8.5.

### Steps to Reproduce

I am looking for the right plugins for Gradle build for docker and build to be passed.

### Gradle version

8.5

**Comment by Alovevictor** [comment] 2024-01-06 09:30
Upgrading from the 7.4 version to the 8.5 version isn't an easy task
It may take days for complete upgrading to its normal status.
Regular login will build gradle gradually till full control is taken.
Gradle shouldn't be markdown,it has done more good than any harm.Thank you...

**Comment by cobexer** [comment] 2024-01-11 13:26
Sorry that you're having trouble with Gradle!

Most probably your issue is caused by an external Gradle plugin, which cannot be addressed in the Gradle Build Tool project.

We recommend you open an issue on its issue tracker.

We have some integration tests with major plugins to catch potential problems early, but we don't have the capacity to cover all plugins available.

If you think you have come across a Gradle bug, please provide a reproducer for this issue without the plugin and we’ll consider reopening it.
***
Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

**Closed by cobexer** 2024-01-11 13:26 UTC
Labels: a:bug, to-triage
