### ISSUE TITLE
Can not build gradle from source code

### ISSUE THREAD

**Issue by dmitrykolesnikovich** [gradle/gradle#5282] opened 2018-05-07 06:16 UTC
I try to build gradle from source code
```
git clone https://github.com/gradle/gradle.git
cd gradle
gradlew install -Pgradle_installPath=D:\gradle-source-build
```
Build fails with following message:
```
FAILURE: Build failed with an exception.
* Where:
Build file 'D:\workspace\gradle\build.gradle.kts' line: 169
* What went wrong:
Plugin with id 'gradlebuild.java-projects' not found.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8-20180504212353+0000/userguide/command_line_interface.html#sec:command_line_warnings
BUILD FAILED in 13m 24s
```
My environment:
```
IntelliJ IDEA 2017.2.6
Build #IC-172.4574.11, built on November 14, 2017
JRE: 1.8.0_152-release-915-b12 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1
```

**Comment by oehme** [comment] 2018-05-07 09:42
This looks like a duplicate of https://github.com/gradle/kotlin-dsl/issues/858, especially since you are also on Windows. We'll have this fixed soon.

**Closed by oehme** 2018-05-07 09:42 UTC
