### ISSUE TITLE
Creating custom Ivy configurations excludes dependencies

### ISSUE THREAD

**Issue by slovdahl** [gradle/gradle#8707] opened 2019-03-07 18:48 UTC
### Expected Behavior
It should be possible to have custom configurations (for e.g. javadocs and sources) at the same time as having dependencies for the main JAR artifact.

This is what the `ivy.xml` file should look like:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ivy-module version="2.0" xmlns:m="http://ant.apache.org/ivy/maven">
  <info organisation="com.test.app" module="app" revision="1.1" status="integration" publication="20190307204429"/>
  <configurations>
    <conf name="compile" visibility="public"/>
    <conf name="default" visibility="public" extends="compile,runtime"/>
    <conf name="javadoc" visibility="public"/>
    <conf name="runtime" visibility="public"/>
  </configurations>
  <publications>
    <artifact name="app" type="jar" ext="jar" conf="compile"/>
    <artifact name="app" type="javadoc" ext="jar" conf="javadoc" m:classifier="javadoc"/>
  </publications>
  <dependencies>
    <dependency org="com.test.lib" name="lib" rev="1.0" conf="compile-&gt;default"/>
  </dependencies>
</ivy-module>
```

The relevant gradle configuration:
```groovy
apply plugin: 'java-library'
apply plugin: 'ivy-publish'

task javadocJar(type: Jar, dependsOn: javadoc) {
    from javadoc.destinationDir
    archiveClassifier = 'javadoc'
}

publishing {
    publications {
        ivy(IvyPublication) {
            from components.java

            configurations {
                javadoc {}
            }

            artifact(javadocJar) {
                type = 'javadoc'
                conf = 'javadoc'
            }
        }
    }
}
```

### Current Behavior
The generated `ivy.xml` doesn't contain anything in the `<dependencies>` tags. This problem started happening after updating from Gradle 4.10.3 to 5.2.1.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ivy-module version="2.0" xmlns:m="http://ant.apache.org/ivy/maven">
  <info organisation="com.test.app" module="app" revision="1.1" status="integration" publication="20190307202908"/>
  <configurations>
    <conf name="compile" visibility="public"/>
    <conf name="default" visibility="public" extends="compile,runtime"/>
    <conf name="javadoc" visibility="public"/>
    <conf name="runtime" visibility="public"/>
  </configurations>
  <publications>
    <artifact name="app" type="jar" ext="jar" conf="compile"/>
    <artifact name="app" type="source" ext="jar" conf="sources" m:classifier="sources"/>
  </publications>
  <dependencies/>
</ivy-module>
```

### Context
Using this kind of javadoc artifact, the `<dependencies>` is filled with the expected content:
```groovy
artifact(javadocJar) {
    type = 'javadoc'
    conf = 'compile'
}
```
However, it has one major side-effect: when adding `com.test.app:app:1.1` as a dependency in another project, in addition to the normal `jar` artifact, the `javadoc` artifact is also added on the class path as well.

### Steps to Reproduce (for bugs)
Gradle 5.2.1 variant that doesn't work: https://github.com/slovdahl/gradle-ivy-publish-bug
Gradle 4.10.3 variant that works: https://github.com/slovdahl/gradle-ivy-publish-bug/tree/working

### Your Environment
Ubuntu 16.04, Gradle 5.2.1.

**Comment by ljacomet** [comment] 2019-03-07 20:13
This looks like a duplicate of #8528.

Can you have a look and check if the workaround mentioned works for you?

**Comment by jotel** [comment] 2019-03-08 12:19
@ljacomet the workarounds work (I added one more there).. but IMHO it's a bug which should be addressed as the ditching postponed evaluation of `publications` in Gradle 5.x it think this introduced an regression and there are many projects which might be affected by this when upgrading to 5.x.. there is not obvious reason why artefacts and dependencies are missing which leads to confusions and nothing in documentation mentioned this new behaviour. This: https://docs.gradle.org/current/javadoc/org/gradle/api/publish/ivy/IvyConfigurationContainer.html 
suggest it will work out of the box.

**Comment by ljacomet** [comment] 2019-03-08 13:55
Indeed a solution for this needs to be found, either by failing fast or helping better the migration.

For the record, see [this](https://github.com/gradle/gradle/issues/8528#issuecomment-468366199) for a workaround.

Note that #8528 is now closed and this issue will be used for tracking, as the other had quite a long history before excluding user error.

**Comment by slovdahl** [comment] 2019-03-08 17:18
Thanks for swift responses and for acknowledging the bug!

At the very least, documenting this unexpected behaviour until it's fixed would be a good first step.

**Comment by slovdahl** [comment] 2019-03-11 07:50
I have now verified that the workaround suggested in #8528 works in my case as well. Thank you @ljacomet for the suggestion!

**Comment by ljacomet** [comment] 2019-10-11 14:11
Closing since the workaround from the linked issue works and this relates to behavior change in Gradle 5.x

**Closed by ljacomet** 2019-10-11 14:11 UTC
Labels: from:contributor, in:dependency-management
