### ISSUE TITLE
Composite, included build, dependency substitution to project + configuration

### ISSUE THREAD

**Issue by snazy** [gradle/gradle#21017] opened 2022-06-15 19:26 UTC
Dependency substitution for included builds allows substitution of a module with a project like this:

```kotlin
includeBuild(...) {
  dependencySubstitution {
    substitute(module("org.apache.iceberg:iceberg-bundled-guava")).using(project(":iceberg-bundled-guava"))
  }
}
```

The project mentioned in the above example uses the shadow plugin, and its output is what's being published/released as `org.apache.iceberg:iceberg-bundled-guava`. To substitute that module w/ the "origin project", it would be necessary to reference the configuration `shadow` of the `:iceberg-bundled-guava`, which is currently not possible.

(Gradle 7.4.2)

**Comment by ljacomet** [comment] 2022-06-17 15:00
Thank you for your interest in Gradle!

This issue lacks information and/or a reproducer to track down the problem. Unless you provide that information over the next 7 days, this issue will be closed.

You can use the following as a base for your reproducer: https://github.com/gradle/gradle-issue-reproducer

***

Without a proper reproducer it is hard to be sure, but if the project using shadow was properly setting up the _variants_ and not customizing the _publication_, it should work.

**Comment by kasobol-msft** [comment] 2022-06-21 22:27
+1 for this feature. Lack of `org.gradle.api.artifacts.DependencySubstitutions.project(path, configuration)` that would mirror `org.gradle.kotlin.dsl.DependencyHandler.project(path, configuration)` is a painful gap to work around to.

For the context. I'm prototyping a migration of Azure SDKs for Java where:

I create a custom configuration on the top of Java Library Plugin to get cross JDK8 and JDK9+ composite build. See
https://github.com/kasobol-msft/azure-sdk-for-java/blob/489f78446b1ec13b44f8b04f12d3b8150742083e/buildSrc/src/main/kotlin/com.azure.java-conventions.gradle.kts#L52-L62
This is to make multi-module builds notice both JDK8 and 9 compilation products.

Then I declare dependencies in few places like:
https://github.com/kasobol-msft/azure-sdk-for-java/blob/489f78446b1ec13b44f8b04f12d3b8150742083e/sdk/core/azure-core-amqp/build.gradle.kts#L10

But there are areas where I don't by default like:
https://github.com/kasobol-msft/azure-sdk-for-java/blob/489f78446b1ec13b44f8b04f12d3b8150742083e/sdk/eventhubs/azure-messaging-eventhubs/build.gradle.kts#L11

However we have a couple of workflows where we'd like to use module substitution in both this place or programmatically as a global option. The latter example here.
https://github.com/kasobol-msft/azure-sdk-for-java/blob/489f78446b1ec13b44f8b04f12d3b8150742083e/buildSrc/src/main/kotlin/com.azure.java-conventions.gradle.kts#L331-L340

However, lack of substituting with previously defined custom configuration leads to compile errors (which were the reason configuration got developed in the first place).

I have tried to "solve" the problem by getting rid of that custom configuration and rigging javaCompile to compile both 8 and 9+ (hacky but worked). 

This has worked mostly, until I realized that I have a need to substitute "test jar" with dependency on "tests" configuration in the test project...
https://github.com/kasobol-msft/azure-sdk-for-java/blob/489f78446b1ec13b44f8b04f12d3b8150742083e/sdk/eventhubs/azure-messaging-eventhubs/build.gradle.kts#L14
Which in turn brings me back to lack of  `org.gradle.api.artifacts.DependencySubstitutions.project(path, configuration)` API.

**Comment by kasobol-msft** [comment] 2022-06-21 22:29
Btw. while investigating I found this https://stackoverflow.com/questions/36089156/gradle-dependency-substitution-with-project-configuration (not mine). There seems to be demand for this functionality.

**Comment by snazy** [comment] 2022-06-22 12:15
@Vampire 
> you could also publish to a repository ... make it published as proper variant 

You assume that the owner of the including build has (full) control over the included build, but that's just not always the case. Some projects intentionally chose to _not_ publish the Gradle metadata along with Maven poms.

**Comment by ljacomet** [comment] 2022-06-23 10:22
This is very unlikely to happen. The recommended way to move forward is indeed to have a proper modelling of the project in the source build, with variants.
Then on the consumer side, you should get the right variant, as expressed in the included build.

I fully understand that this means no solution for these problems when you do not control the included build, but I believe that educating the community about proper modelling - and limiting or even abandoning publication level tweaks - is the right path to go.

@kasobol-msft Could you please edit the README of your reproducer and indicate what you expect / what does not work?

**Comment by kasobol-msft** [comment] 2022-06-23 17:38
@ljacomet I updated README, please let me know the description is clear enough.

**Comment by Vampire** [comment] 2022-07-03 01:13
@kasobol-msft 
> @Vampire I noticed that original report uses includeBuild which I'm not using...

Well, then maybe you should open a separate issue, as this is about depending on specific configurations of included builds?
I didn't look at your reproducer, just deduct from your quoted statement, so appologize if I didn't get it right.

@snazy 

> I understand your point, but the [recommendation](https://imperceptiblethoughts.com/shadow/publishing/) in this case - with the widely used shadow plugin - has been followed by the Iceberg project and many many other projects. And the recommended way to [reference the shadowed code](https://imperceptiblethoughts.com/shadow/multi-project/#depending-on-the-shadow-jar-from-another-project) has been followed as well.

Well, **if*** the shadow plugin documentation gives bad advice, that's not a reason to change Gradle to adapt to it imho, but instead the shadow documentation should be fixed to the proper concepts available in Gradle. :-)
I'm actually a big disliker of the `shadow` plugin, as I'm generally against fat jars for a variety of reasons, except if made in a sane way like spring boot jars.
But the docs you linked to do not seem to be wrong.
They explicitly state that the shown snippet is for usage within a multi-project build, not for usage within a composite build between the included builds, that's a very major difference.

> For the particular case of the shadow plugin, what exactly should users do?

From the top of my head, the producer should publish a variant that does not declare dependencies (as they are included in the jar), that has the fat jar as artifact, and that has the attribute `Bundling.BUNDLING_ATTRIBUTE` set to `Bundling.EMBEDDED` if the dependencies are just repacked, or to `Bundling.SHADOWED` if the packages are also relocated. The consumer can then depeclare with the dependency which value he wants for that attribute and gets the according artifact.

> I don't fully understand why there shall be no support to select configurations

Because it is a different level of encapsulation.
If you have a full build that you inlude, that build defines which variants it exposes with which attributes and so on and it is the same that would or is also published to a repository using the Gradle Module Metadata.
So these variants are what the build author supports as consumables for downstream projects.
Configurations on the other hand are a build detail within the multi-project build, that can be used within the multi-project build to have a dependency between the projects that should not be exposed to downstream projects.
You can probably compare it to a package-private class vs. a public class and your question is like "why can't I use package-private classes from other packages, why are they not publicly available?".

> or variants

This should work just fine between included builds.
If that does not work, either you did some error, or found some bug if I'm not majorly mistaken right now.
Or if it works without dependency substitution but there is no way with dependency substitution, you maybe hit a missing feature.
I almost never use dependency substitution, as I usually write my projects in a way I can simply include them into a composite build without the need to do any manual dependency substitutions.

**Comment by kasobol-msft** [comment] 2022-07-05 16:03
@Vampire I created separate issue here https://github.com/gradle/gradle/issues/21177 .
I landed here in first place because the problem reported looked 90% similar to mine.

**Closed** 2023-09-11 16:27 UTC
Labels: a:feature, in:composite-builds, in:dependency-declarations
