### ISSUE TITLE
Incremental build fails while compile build-logic

### ISSUE THREAD

**Issue by ganadist** [gradle/gradle#27462] opened 2023-12-19 08:52 UTC
### Current Behavior

```
./gradlew tasks --no-build-cache

> Task :build-logic:convention:compileKotlin FAILED
e: org.jetbrains.kotlin.util.KotlinFrontEndException: Exception while analyzing expression in (53,21) in /home/ganadist/src/build/AndroidStudioProjects/VersionCodeDemo/build-logic/convention/src/main/kotlin/AndroidBuilderPlugin.kt

Attachments:
causeThrowable
java.lang.AssertionError: Number of arguments should not be less than number of parameters, but: parameters=6, args=5
	at org.jetbrains.kotlin.types.IndexedParametersSubstitution.<init>(TypeSubstitution.kt:119)
	at org.jetbrains.kotlin.types.IndexedParametersSubstitution.<init>(TypeSubstitution.kt:113)
	at org.jetbrains.kotlin.types.IndexedParametersSubstitution.<init>(TypeSubstitution.kt:127)
	at org.jetbrains.kotlin.types.TypeConstructorSubstitution$Companion.create(TypeSubstitution.kt:99)
	at org.jetbrains.kotlin.types.KotlinTypeFactory.computeMemberScope(KotlinTypeFactory.kt:57)
...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':build-logic:convention:compileKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Internal compiler error. See log for more details

```

### Expected Behavior

```
./gradlew tasks --no-build-cache
...
> Task :build-logic:convention:compileKotlin
> Task :build-logic:convention:compileJava NO-SOURCE
> Task :build-logic:convention:classes
> Task :build-logic:convention:jar

> Configure project :
...

> Task :tasks

------------------------------------------------------------
Tasks runnable from root project 'My Application'
------------------------------------------------------------

```

### Context (optional)

Since Android Gradle Plugin 8.3, Type parameter of [CommonExtension](https://developer.android.com/reference/tools/gradle-api/8.3/com/android/build/api/dsl/CommonExtension?hl=en) was changed.
So, [build-logic was updated like this](https://github.com/ganadist/VersionCodeDemo/commit/a75596ef6064caa12512e9259fd09e88db1eebcb#diff-64f558ddc7dbb5cb033864f334dde2275d99c8ff065185250d8a168639e88506).

Then whenever switch branch between [main](https://github.com/ganadist/VersionCodeDemo/tree/main) and [agp83_test](https://github.com/ganadist/VersionCodeDemo/tree/agp83_test), gradle build failed.

The currently available workaround is to delete `build-logic/convention/build` manually before performing gradle task.

### Steps to Reproduce

```
$ git clone https://github.com/ganadist/VersionCodeDemo -b agp83_test

$ cd VersionCodeDemo

### switch to AGP 8.2
$ git checkout HEAD~1

$ ./gradlew tasks --no-build-cache

BUILD SUCCESSFUL in 4s
6 actionable tasks: 6 executed

### switch to AGP 8.3
$ git checkout origin/agp83_test

$ ./gradlew tasks --no-build-cache
...
> Task :build-logic:convention:compileKotlin FAILED
e: org.jetbrains.kotlin.util.KotlinFrontEndException: Exception while analyzing expression in (53,21) in /home/ganadist/src/build/AndroidStudioProjects/VersionCodeDemo/build-logic/convention/src/main/kotlin/AndroidBuilderPlugin.kt

Attachments:
causeThrowable
java.lang.AssertionError: Number of arguments should not be less than number of parameters, but: parameters=6, args=5
	at org.jetbrains.kotlin.types.IndexedParametersSubstitution.<init>(TypeSubstitution.kt:119)
	at org.jetbrains.kotlin.types.IndexedParametersSubstitution.<init>(TypeSubstitution.kt:113)
	at org.jetbrains.kotlin.types.IndexedParametersSubstitution.<init>(TypeSubstitution.kt:127)
...
* What went wrong:
Execution failed for task ':build-logic:convention:compileKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Internal compiler error. See log for more details

BUILD FAILED in 1s
4 actionable tasks: 2 executed, 2 up-to-date

### After clean build-logic manually, it works
$ rm -rf build-logic/convention/build

$ ./gradlew tasks --no-build-cache

BUILD SUCCESSFUL in 4s
6 actionable tasks: 6 executed

### revert to AGP 8.2
$ git checkout HEAD~1

$ ./gradlew tasks --no-build-cache

> Task :build-logic:convention:compileKotlin FAILED
e: file:///home/ganadist/src/build/AndroidStudioProjects/VersionCodeDemo/build-logic/convention/src/main/kotlin/AndroidBuilderPlugin.kt:53:51 Type mismatch: inferred type is CommonExtension<*, *, *, *, *> but AGPCommonExtension /* = [Error type: Inconsistent type CommonExtension<*, *, *, *, *, *> (parameters.size = 5, arguments.size = 6)] */ was expected

```

### Gradle version

8.5

### Your Environment (optional)

OS:
 * MacOS 14.2 Sonoma
 * Archlinux

Java:
 * OpenJDK 17

**Comment by ov7a** [comment] 2023-12-19 13:48
Sorry that you're having trouble with Gradle!

This is an issue with the Kotlin Gradle Plugin, which is developed by JetBrains, and cannot be addressed in the Gradle Build Tool project.

Please open such Kotlin-related issues on the JetBrains YouTrack at https://kotl.in/issue.

***

It also may be caused by AGP <-> Kotlin integration. In any case, it's unlikely that this is a Gradle issue.

**Closed by ov7a** 2023-12-19 13:48 UTC
Labels: a:bug, to-triage

**Comment by ganadist** [comment] 2023-12-19 13:58
Posted at https://youtrack.jetbrains.com/issue/KT-64434

**Comment by buddhasaikia** [comment] 2024-06-16 03:21
Hi, I faced similar situation and I landed here a few days back while searching for a solution. If you are still facing the issue, here is a workaround that I tried and worked for me.

1. Add this line in **gradle.properties**-
`android.experimental.lint.analysisPerComponent=false`

2. Add extra * in your `CommonExtension` parameters where ever required-
e.g. `CommonExtension<*, *, *, *, *, *>`

3. Sync again. 

This should resolve the issue. Once the issue gets resolved you can remove the line from `gradle.properties` file as mentioned in point 1. Hope this would help you.
