### ISSUE TITLE
Gradle's withJavadocJar() includes unlicensed yuidoc-ember-theme 1.1.2 artifact.

### ISSUE THREAD

**Issue by chrisr3** [gradle/gradle#17987] opened 2021-08-10 08:43 UTC
When Gradle 7.x generates a Javadoc jar via
```gradle
java {
    withJavadocJar()
}
```
the `-javadoc` jar contains JQuery. NexusIQ hates this because it contains `yuidoc-ember-theme 1.1.2`, which has no licence.

### Expected Behavior
Gradle should not bundle unlicensed software inside its generated artifacts.

### Current Behavior
NexusIQ complains that:
License-None | Source license not available; no declaration available | Found 'Not Supported' licenseFound 'Not Declared' license

Licence-Status Open | Licence Status Open | License status was OpenComponent does not contain proprietary packages

Architecture-Quality | Version is old | Found component older than 5 years

### Context
We scan all of our artifacts using NexusIQ, and it **hates** Gradle 7.x's javadocs.

### Steps to Reproduce 
Generate Javadocs using
```gradle
java {
    withJavadocJar()
}
```
and scan the artifact with NexusIQ.

**Comment by jbartok** [comment] 2021-08-11 12:49
@chrisr3 could you pls. attach an example JAR which manifests this problem? Turns out it's not as simple to reproduce, as it should be...

**Comment by chrisr3** [comment] 2021-08-11 12:58
[cordapp-configuration-javadoc.zip](https://github.com/gradle/gradle/files/6968521/cordapp-configuration-javadoc.zip)
I've had to rename this `.jar` to `.zip` toget GitHub to accept it for upload.

**Comment by Vampire** [comment] 2021-08-11 13:44
That's not really a Gradle topic.
The standard doclet included in Java did change in Java 9.
Before no jquery was included.
With Java 9 this was majorly rewritten to for example have the nice search functionality in the upper right corner which uses jquery.
It is the same whether you use plain JavaDoc tool or when running it through Gradle.
What I wonder is, what file does it actually complain about?
In the zip you attached I see jquery, but I don't find the string `ember` except as part of `member`.
And even if Nexus is correct that `yuidoc-ember-theme` is included (which actually is a theme for JavaScript docs generated with YUIDoc), then according to it's homepage at https://github.com/offirgolan/yuidoc-ember-theme it is released under MIT License, so there should be no problem in packaging it.

Imho either Nexus IQ is just reporting a false-positive, or you need to complain to yuidoc-ember-theme or jquery to mention the license in a way Nexus IQ can recognize it or otherwise complain to Java that they include this in generate JavaDoc files. :-)

**Comment by chrisr3** [comment] 2021-08-11 14:07
I have no idea which file NexusIQ is actually complaining about. It is entirely possible that the _contents_ of `yuidoc-ember-theme` has been embedded into something, and that NexusIQ has recognised it.

**Comment by jbartok** [comment] 2021-08-12 08:36
@Vampire thank you. @chrisr3 we will close this issue, because it doesn't really seem to be Gradle related. If you still have reason to think otherwise, pls. feel free to open a new one and link to this and we'll see what we can do about it.

**Closed by jbartok** 2021-08-12 08:36 UTC
Labels: a:bug, in:java-plugins, to-triage
