### ISSUE TITLE
Adding JVM args through GRADLE_OPTS overwrites gradle.properties

### ISSUE THREAD

**Issue by fawind** [gradle/gradle#19501] opened 2022-01-06 15:39 UTC
When adding jvm args by adding them to both the `gradle.properties` file and through the `GRADLE_OPTS` env variable, the `GRADLE_OPTS` env variable wins and overwrites jvm args added in `gradle properties`.

E.g. when having the following `gradle.properties` file:
```properties
org.gradle.jvmargs=--add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED
```

When just running Gradle, the jvm args are correctly added. However when also setting jvm args through e.g. `GRADLE_OPTS="-Dorg.gradle.jvmargs='-Xmx1g'"`, the jvm args added through `gradle.properties` are not getting applied.

### Expected Behavior
From the [Gradle docs](https://docs.gradle.org/current/userguide/build_environment.html):
> When configuring Gradle behavior you can use these methods, listed in order of highest to lowest precedence (first one wins):
> * Command-line flags such as --build-cache. These have precedence over properties and environment variables.
> * System properties such as systemProp.http.proxyHost=somehost.org stored in a gradle.properties file.
> * Gradle properties such as org.gradle.caching=true that are typically stored in a gradle.properties file in a project root directory or GRADLE_USER_HOME environment variable.
> * Environment variables such as GRADLE_OPTS sourced by the environment that executes Gradle.

Based on that, I would expect that my jvm args added in `gradle.properties` still apply when also using `GRADLE_OPTS`.

Relatedly, it would be nice to have a way to merge jvm args supplied through multiple methods (i.e. apply all). However reading the docs, this does not seem to be intended.

### Current Behavior
Jvm args added through `GRADLE_OPTS` win and overwrite jvm args added through `gradle.properties`.

### Context
With Java 16, some Gradle plugins require `--add-exports` jvm args to function (e.g. [spotless](https://github.com/diffplug/spotless/tree/e98684a47c2fcb446325b171471b60eb92fb06f3/plugin-gradle#google-java-format) and [google-java-format](https://github.com/google/google-java-format/tree/3b70603449ef7411043a81105919bcda046bd062#jdk-16)). The recommendation is to add these `--add-exports` args to the `gradle.properties` file so they apply to ever Gradle invocation. However if you then also use `GRADLE_OPTS` for adding additional jvm opts (e.g. we use this to set a different heap space in CI), the build fails.

### Steps to Reproduce 
I added a minimal reproducer here: https://github.com/fawind/gradle-build-env-repro

Running `./gradlew printArgs` uses the jvm args added in `gradle.properties` but running `GRADLE_OPTS="-Dorg.gradle.jvmargs='-Xmx1g'" ./gradlew printArgs` does not.

### Your Environment
```
Gradle 7.3.1
Revision:     2c62cec93e0b15a7d2cd68746f3348796d6d42bd
Groovy:       3.0.9
JVM:          15 (Azul Systems, Inc. 15+36)
OS:           Mac OS X 10.15.7 x86_64
```

**Comment by koppor** [comment] 2024-02-09 09:58
> listed in order of highest to lowest precedence (first one wins):

The term "wins" clearly state that one is picked and the other is neglected. - I wonder how `GRADLE_OPTS` are every used if `gradle.properties` are present. I think `3.x` and `4` need to be swapped? I would expect that `GRADLE_OPTS` overwrite the `gradle.properties` (as you also describe).

Intuitively, I would also have expected a merge behavior of `GRADLE_OPTS`. Maybe a new variable `GRADLE_OPTS_PATCH` to make the behavior clear in the variable name?

**Comment by danadam** [comment] 2024-02-21 13:38
AFAIU the [documentation](https://docs.gradle.org/current/userguide/build_environment.html) `jvmargs` and `GRADLE_OPTS` are used for different things:
> org.gradle.jvmargs=(JVM arguments)
>
>   Specifies the JVM arguments used for the Gradle Daemon. [...] This does not affect the JVM settings for the Gradle client VM.

> GRADLE_OPTS
>
>   Specifies JVM arguments to use when starting the Gradle client VM.
>
>    The client VM only handles command line input/output, so it is rare that one would need to change its VM options.

So it's client vs daemon.

Then on [Configuring JVM memory](https://docs.gradle.org/current/userguide/config_gradle.html#sec:configuring_jvm_memory) it says that `JAVA_OPTS` is for the client VM, so I'm not sure if there are two variables for the same thing.

It also says:
> If you deactivate the [Gradle Daemon](https://docs.gradle.org/current/userguide/gradle_daemon.html#gradle_daemon) and the client VM has the same settings as required for the build VM, the client VM will run the build directly.

but I'm not sure how "sameness" of the settings is determined.

**Comment by ov7a** [comment] 2024-11-14 13:27
Sorry for the late reply.

Indeed, the root cause of this confusion is the difference between daemon and client options. Thanks @danadam for the explanation.

Ideally, it should be more clear from the environment variable name (e.g. it should be `GRADLE_CLIENT_OPTS`), but it may be hard to change it while preserving backward compatibility. 

Closing it as a usage question. If you have ideas about improving our docs on how to make it more clear, please open a new issue.

**Closed by ov7a** 2024-11-14 13:27 UTC
Labels: a:bug, to-triage, in:invoking-gradle
