### ISSUE TITLE
Having issues with maven BOM files

### ISSUE THREAD

**Issue by ramses-gomez** [gradle/gradle#6008] opened 2018-07-18 07:17 UTC
I’m using

implementation org.springframework.boot:spring-boot-dependencies:2.0.3.RELEASE

to import a maven bom file however when the pom file is generated for the artifact this gets included in the file:

```
<dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-dependencies</artifactId>
      <version>2.0.3.RELEASE</version>
      <scope>runtime</scope>
</dependency>
```

now if I use this dependency in a maven project it fails since it is looking for a jar artifact not a pom
, is this a bug or is expected behaviour?

I would expect that when the pom file is generated for the artifact it will create something like this:

```
   <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-dependencies</artifactId>
      <version>2.0.3.RELEASE</version>
      <scope>import</scope>
   </dependency>
```

I'm currently using Gradle 4.8

**Comment by ljacomet** [comment] 2018-10-01 10:41
Closing as duplicate of #4543 

Note that the issue will be fixed in Gradle 5.0 for the `maven-publish` plugin and using the new syntax for BOM consumption.

**Closed by ljacomet** 2018-10-01 10:41 UTC
Labels: in:dependency-management
