### ISSUE TITLE
Depending on a particular Maven snapshot version is broken on 3.5

### ISSUE THREAD

**Issue by juandiana** [gradle/gradle#1953] opened 2017-05-05 14:32 UTC
### Expected Behavior
When declaring a compile dependency on a particular Maven snapshot version, the classes it provides should be available on the classpath when compiling.

Example
```
dependencies {
    compile "com.squareup.picasso:picasso:3.0.0-20170423.010317-12"
}
```

For more info on the feature see [2.4's release notes](https://docs.gradle.org/2.4/release-notes.html#depending-on-a-particular-maven-snapshot-version).

### Current Behavior
The classes provided by the declared compile dependency are **not** present on the classpath when compiling. Thus, the build ends up failing because it doesn't find these classes.

### Context
Upgraded our Android build from Gradle 3.4.1 to Gradle 3.5. It was working fine with the previous Gradle version. By the way, we're using Android Gradle Plugin version 2.3.1. We only changed Gradle's version.

Also tried building both from Android Studio and directly from command-line.

### Steps to Reproduce (for bugs)
1. Create an Android project.
2. Put a dependency on a particular Maven snapshot version.
3. Have a class that uses a class of that dependency.
4. Execute the assemble task.

Build-scan link: https://scans.gradle.com/s/zdj7aojjd4q4m

### Your Environment
Windows 10
Gradle 3.5

**Comment by bmuschko** [comment] 2017-05-05 20:10
I tried to reproduce the issue but couldn't. For me that works for the 3.5 and all 3.x versions before. Can you please provide a sample project that reproduces the issue? The sample project can simply publish to a local repository.

**Comment by juandiana** [comment] 2017-05-05 21:11
Sure. Here's a sample project: https://github.com/juandiana/Gradle-Issue-1953

As it is (using Gradle 3.5), it fails to compile. If you switch back to Gradle 3.4.1 it compiles fine.

**Comment by bmuschko** [comment] 2017-05-16 18:47
Thanks for providing the sample project. Any chance you have a non-Android dependency I can use? I'd like to try this out without the Android plugin being involved first to avoid any side effects.

**Comment by bmuschko** [comment] 2017-05-22 12:54
Do you have any more feedback here, @juandiana?

**Comment by juandiana** [comment] 2017-05-23 15:21
Yes, sorry. I couldn't look into this last week.

I removed the Android plugin in favor of the Java plugin and the AAR snapshot dependency in favor of a JAR dependency and I could no longer reproduce this bug.

See [changes](https://github.com/juandiana/Gradle-Issue-1953/commit/9f17d9a28d5e89312eb4033b8936844b46dd5a82) in the sample project.

**Comment by bmuschko** [comment] 2017-05-23 15:24
Could you try out resolving an AAR snapshot with the Java plugin applied. If that works then I'd suggest you ask about this on the Android forum.

**Comment by bmuschko** [comment] 2017-07-05 22:19
I am going to close the issue given that this bug is not reproducible.

**Closed by bmuschko** 2017-07-05 22:19 UTC
Labels: a:question, from:contributor, in:dependency-management

**Comment by anthonylawson** [comment] 2017-07-18 18:49
@juandiana did you ever open an Android ticket for this issue?

**Comment by juandiana** [comment] 2017-07-19 17:34
@anthonylawson No, since I wasn't able to setup a project that resolves an AAR snapshot with only the Java plugin applied (which was what @bmuschko suggested to do before reporting the bug to the AOSP tracker).

As I understand, it's the Android plugin who knows how to handle this package format.

I'll be coming back to this before migrating to the Android Gradle Plugin 3.x, which will require Gradle 4.x.

**Comment by juandiana** [comment] 2017-07-24 18:35
So, I finally was able to dedicate some time into figuring out what was going on.

Turns out that the problem was that the snapshot which we were using was removed from the repository as it can be seen [here](https://oss.sonatype.org/content/repositories/snapshots/com/squareup/picasso/picasso/3.0.0-SNAPSHOT/).

Since we had it cached on our local machines (and the CI server) we didn't notice it. Upon installing a new version of Gradle, it seems to query the repo to check if the artifact is there instead of using the local cache directly. So that's why it was failing! Building using a newer snapshot version with Gradle 4.0.1 works just fine. 

@bmuschko Sorry it took me a while to give you an update on this!

**Comment by aried3r** [comment] 2017-08-02 14:07
We're facing the same problem. Cleaning all caches (`rm -rf ~/.android/build-cache`, `rm -rf ~/.gradle/caches`, `rm -rf ./.gradle`) makes `./gradlew assembleDebug` work exactly *once*. Another `./gradlew assembleDebug` fails because it supposedly can't find Picasso.

@bmuschko, should I open another issue specifically for Android? I did not upgrade the android-gradle-plugin yet, but I'll try that next.

**Comment by bmuschko** [comment] 2017-08-02 14:25
@aried3r I tried to reproduce your guys' issue but couldn't. Please provide me with a sample project (optimally without applying the Android plugin first) that reproduces the issue. If you can't reproduce it with plain Gradle core then please open an issue for the Android plugin.

**Comment by anthonylawson** [comment] 2017-08-02 14:27
@aried3r I already submitted an issue for that on the [Android side here](https://issuetracker.google.com/issues/63992133). Looks like it was assigned to someone at Google to fix.

**Comment by aried3r** [comment] 2017-08-02 18:36
Thank you both! I will star the issue on the Android issue tracker and follow it there.
