### ISSUE TITLE
Using --enable-preview on java13 crashes gradle build

### ISSUE THREAD

**Issue by Klaboe** [gradle/gradle#12583] opened 2020-03-19 19:48 UTC
### Expected Behavior

The build should complete successfully

### Current Behavior

The build seem to crash gradle with the message
"The message received from the daemon indicates that the daemon has disappeared." and then the log

### Context

This makes me unable to build projects that are testing new java features that are still in preview in a JDK-version. In my case no switch-expressions or textblocks

### Steps to Reproduce 

1) Have a project that uses some preview-features (java 13 features in my case)
2) Have 

```
compileJava {
    options.compilerArgs << "--release" << "13"
    options.compilerArgs << "--enable-preview"
}
```

or 

```
tasks.withType(JavaCompile) {
    options.compilerArgs += "--enable-preview"
}
```

in the build file

3) gradle clean build

### Your Environment

```
$ gradle --version
------------------------------------------------------------
Gradle 6.2.2
------------------------------------------------------------

Build time:   2020-03-04 08:49:31 UTC
Revision:     7d0bf6dcb46c143bcc3b7a0fa40a8e5ca28e5856

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          13.0.1 (Eclipse OpenJ9 openj9-0.17.0)
OS:           Windows 10 10.0 amd64
```

**Comment by Klaboe** [comment] 2020-03-26 21:52
Also happens under newly released gradle 6.3:

`------------------------------------------------------------
Gradle 6.3
------------------------------------------------------------

Build time:   2020-03-24 19:52:07 UTC
Revision:     bacd40b727b0130eeac8855ae3f9fd9a0b207c60

Kotlin:       1.3.70
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          13.0.1 (Eclipse OpenJ9 openj9-0.17.0)
OS:           Windows 10 10.0 amd64`

**Comment by ljacomet** [comment] 2020-04-27 15:20
I cannot reproduce this issue, neither with Open J9 0.17.0 or any other Java 13 VM.

Unless you can provide more information on how to reproduce, this is most likely an error outside Gradle caused by some configuration of the JVM.

One possible related issue is #12701. If that's the case, then 6.4 should fix this issue.

**Comment by Klaboe** [comment] 2020-04-27 18:12
Could you share your project mayhaps? I would be curious to see how it runs on my system 😅

**Comment by ljacomet** [comment] 2020-05-18 13:08
Have a look there: [Reproducer](https://github.com/ljacomet/gradle-java-13-feature)

Closing, please provide additional information if you still believe there is an issue on the Gradle side.

**Closed by ljacomet** 2020-05-18 13:08 UTC
Labels: @jvm, a:bug, from:contributor, in:jvm-ecosystem

**Comment by Klaboe** [comment] 2020-06-17 19:28
Update; seems to not be a issue on jdk-14.0.1.7-hotspot
