### ISSUE TITLE
Use only gradle properties utilized in configuration phase as input of configuration cache

### ISSUE THREAD

**Issue by malbano** [gradle/gradle#27900] opened 2024-01-31 23:41 UTC
### Expected Behavior

In an empty java project, running:
```
./gradle app:build -Psomeproperty=1
```
and then running
```
./gradle app:build -Psomeproperty=2
```
Should reuse the configuration cache, if the gradle property is not read during configuration phase.

### Current Behavior (optional)

In an empty java project, running:
```
./gradle app:build -Psomeproperty=1
```
and then running
```
./gradle app:build -Psomeproperty=2
```
Returns a message saying that configuration cache was invalidated, even if the property is not read during configuration phase:
```
Calculating task graph as configuration cache cannot be reused because the set of Gradle properties has changed.
```
Tested and reproducible on gradle 8.5 and 8.6-rc-4.

### Context

Invalidating the configuration cache only when a gradle property is actually used in configuration phase would result in a performance improvement. This is the case, for example, when running instrumentation tests in Android with:
```
./gradlew app:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.sample.app.MyActivity
```
Note that this is not an Android specific issue.

**Comment by ov7a** [comment] 2024-02-01 13:45
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

@gradle/bt-configuration  This is a reasonable request from a user perspective, WDYT?

**Comment by mlopatkin** [comment] 2024-02-01 14:49
>This is a reasonable request from a user perspective, WDYT?

It sure is, but we already have an open issue for that. We hope to address this sooner rather than later, but it is not as easy as we want it to be.

Duplicate of #20969.

**Closed by mlopatkin** 2024-02-01 14:49 UTC
Labels: a:feature, in:configuration-cache, :wave: team-triage
