### ISSUE TITLE
Gradle's compileJava task fails to write .class files if cache is enabled and the resources output dir is the same as the classes output dir

### ISSUE THREAD

**Issue by csterg** [gradle/gradle#20299] opened 2022-03-28 10:30 UTC
Every second `clean/build` cycle, the `.class` files are not written to `$buildDir/classes`.

The problem appears only when:

-  The project has a very few number of java files (1-2 files) and some resource files
-  `sourceSets.main.java.outputDir == sourcesSets.main.java.output.resourceDir`
- cache is enabled for the `compileJava` task

The behavior is this:

- `clean` -> `build`: works, `.class` files are written in `$buildDir/classes`
- Repeat step 1: fails, `.class` files are NOT written
- Repeat 1: works ...
- etc...

Given these conditions, the problem does not occur if either of the following is true:
- Disabling cache globally or for the `compileJava` task
- The resources output directory is different than the `classesDir`
- The are no resources
- The project being build is larger (some timing issue obviously).

The problem happens randomly to other small sub-projects at different machines and at random times. I have searched for days and have not found any similar issue mentioned elsewhere so any hint will be very helpful.

Thanks

Problem appears on Windows 10 with gradle 6.7, 7.0. 7.4
Build scan URL: https://scans.gradle.com/s/hgbffypam5lce

**Comment by donat** [comment] 2022-03-29 07:46
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

**Comment by csterg** [comment] 2022-03-29 11:00
Thank you for getting back. I am attaching a sample project to help reproduce the issue.
[gradle-bug-showcase.zip](https://github.com/gradle/gradle/files/8370666/gradle-bug-showcase.zip)

To reproduce run `gradle build`, then `gradle clean`, then `gradle build`, etc...

Notice that the file `build/classes/Foo.class` is only written every second time. Whenever `compileJava` executes `FROM-CACHE`, the `.class` file is not written.

Costas

**Comment by donat** [comment] 2022-03-30 12:46
I was able to reproduce it, although - as you also mentioned - not in a consistent way. 
It's highly likely, that the problem is with your configuration. You defined overlapping output locations, that can easily mess 
up up-to-date checks and caching as well.
I'd also suggest using distinct file collections for src and resources. For example:
```
sourceSets {
    main {
        java {
            srcDirs = ['src']
			filter.include '**/*.java'
        }

        resources {
            srcDirs = ['src']
			filter.exclude '**/*.java'
        }
    }
}
```

**Comment by csterg** [comment] 2022-03-30 15:20
Thanks donat, I will try that, although I already filter the `processResources` files being copied.
Yes, the issue is with exactly this configuration, e.g `compileJava` and `processResources` have the same output dir.
It is a very common thing to have the .class files being written to the same dir as the resources (netbeans, eclispe, etc do that).
Shouldn't gradle be able to handle this use case gracefully? 
Is this a bug (it only happens with cache enabled)?

Thanks

**Comment by csterg** [comment] 2022-03-31 09:35
I tested adding the `filter` command, they don't help. So it seems that there is an issue when the output dir is the same and gradle uses caching. I would love to see this fixed!
Thanks

**Comment by asodja** [comment] 2022-03-31 19:49
Would it work for you, if you define the third task of type `Copy` or `Sync` that runs after compile and process resources and merges the content?

So it would look like:
- `classes` -> `build/classes` 
- `resources` -> `build/resource`
- copy/sync task that runs after compile and resources: `build/classes`  + `build/resource` merge to -> `build/merged`

With that setup Gradle caching should not be affected.

**Comment by big-guy** [comment] 2024-02-05 17:53
The java and resources source sets need to have different outputs for Gradle to work properly.  Otherwise, there will be multiple tasks writing into the same directory.

**Closed by big-guy** 2024-02-05 17:53 UTC
Labels: a:bug, closed:not-fixed, in:java-plugins
