### ISSUE TITLE
The disadvantage of gradle is that it can't be used after Java upgrade

### ISSUE THREAD

**Issue by 120011676** [gradle/gradle#10787] opened 2019-09-19 08:07 UTC
The disadvantage of gradle is that it can't be used after Java upgrade

I've seen it before, and I'll wait for gradle upgrade to solve it.

#10785

Maven doesn't seem to have this problem.

**Comment by ljacomet** [comment] 2019-09-19 08:27
Closing as duplicate of #10785

**Closed by ljacomet** 2019-09-19 08:27 UTC
Labels: a:feature, from:contributor
