### ISSUE TITLE
Designate attributes as required

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#27991] opened 2024-02-07 20:27 UTC
### Expected Behavior

I can designate attributes as required

```diff
 val myPluginResourcesResolver by configurations.registering {
   resolvable()
   extendsFrom(myPluginResources.get())
   attributes {
-    attribute(MyPluginResources, "foo-resources")
+    attribute(MyPluginResources, "foo-resources", required = true)
   }
 }
```

### Current Behavior (optional)

I cannot designate attributes as required.

### Context

I have a plugin. It has a custom setup of Configurations for sharing some resources between subprojects

```kotlin
// buildSrc/src/main/kotlin/my-plugin.gradle.kts

val MyPluginResources = Attribute.of("my-plugin", String::class.java)

val myPluginResources by configurations.registering {
  declarable()
}

val myPluginResourcesResolver by configurations.registering {
  resolvable()
  extendsFrom(myPluginResources.get())
  attributes {
    attribute(MyPluginResources, "foo-resources")
  }
}

val myPluginResourcesConsumable by configurations.registering {
  consumable()
  extendsFrom(myPluginResources.get())
  attributes {
    attribute(MyPluginResources, "foo-resources")
  }
}

fun Configuration.resolvable() { isCanBeResolved = true;  isCanBeConsumed = false; isCanBeDeclared = false; }
fun Configuration.consumable() { isCanBeResolved = false; isCanBeConsumed = true;  isCanBeDeclared = false; }
fun Configuration.declarable() { isCanBeResolved = false; isCanBeConsumed = false; isCanBeDeclared = true;  }
```

Resources are dynamically added to the Configuration in `:library`

```kotlin
// library/build.gradle.kts

plugins {
  id("my-plugin")
}

if (someCondition == true) {
  myPluginResources.configure {
    dependencies.add(project.dependencies.create("org.example:blah:1.2.3"))
  }
}
```

`:application` depends on `:library` 

```kotlin
// application/build.gradle.kts

plugins {
  id("my-plugin")
}

dependencies {
  myPluginResources(project(":library"))
}
```

What happens is extremely bizarre behaviour.

* If `someCondition == true` then `:application`'s `myPluginResourcesResolver` will correctly retrieve the defined files. This is expected.

* But if `someCondition ==false` then application's `myPluginResourcesResolver` will contain random files, depending on whatever other plugins `:library` has or hasn't defined. This is unexpected, confusing, and undesired.

   There's no reasonable way for `:application` to determine whether the resolved files are correct.

   Additionally, if another subproject `:ultra-application` depends on `:application` and resolves `myPluginResourcesResolver` then those random files from `:library` will be forwarded again, further exacerbating the problem while obscuring the cause.

### Artifact View

Using artifactView and filtering based on the resolved artifacts is insufficient for a few reasons

1. The Javadoc for `artifactView {}` says that it will "_only_" use the defined attributes, but it doesn't, and it will forget about attributes that have been defined (related: https://github.com/gradle/gradle/issues/26007)
2. it requires setting `lenient(true)` which hides other errors
3. it can trigger tasks in the other projects that provide the unwanted files, which can be slow and wasteful
4. it's verbose and tedious and boilerplatey

**Comment by ov7a** [comment] 2024-02-14 10:02
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***
See [the documentation](https://docs.gradle.org/current/userguide/variant_attributes.html#sec:abm_algorithm).

If a producer does not declare an attribute, then it's compatible with a consumer.
If you ask for a single attribute and the producer does not have it, then selection will either be ambiguous or resolve a variant that does not have the requested attribute.

It is critical to always define [category attribute](https://docs.gradle.org/current/javadoc/org/gradle/api/attributes/Category.html#CATEGORY_ATTRIBUTE) for your custom attributes to ambiguate between variants. E.g. always use 'dokkatoo' as your category everywhere.

One recommendation should be added to the documentation to clarify that. 

It is related to:
* https://github.com/gradle/gradle/issues/18846

thus closing this. The lack of documentation should be covered as a part of that issue.

**Closed by ov7a** 2024-02-14 10:02 UTC
Labels: a:feature, to-triage

**Comment by aSemy** [comment] 2024-02-14 15:38
> Sorry that you're having trouble with Gradle!
> 
> Your issue appears to be a question about how to use Gradle.

It's not

> Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

It hasn't been 


> If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

Sure, I'll make a new issue 👍 

> 
> See [the documentation](https://docs.gradle.org/current/userguide/variant_attributes.html#sec:abm_algorithm).
> 
> If a producer does not declare an attribute, then it's compatible with a consumer. If you ask for a single attribute and the producer does not have it, then selection will either be ambiguous or resolve a variant that does not have the requested attribute.

That's why I'm asking for a new feature.

> It is critical to always define [category attribute](https://docs.gradle.org/current/javadoc/org/gradle/api/attributes/Category.html#CATEGORY_ATTRIBUTE) for your custom attributes to ambiguate between variants. E.g. always use 'dokkatoo' as your category everywhere.

A category attribute won't help because it's not treated any differently from other attributes.

**Comment by ljacomet** [comment] 2024-02-19 09:39
> A category attribute won't help because it's not treated any differently from other attributes.

Again, documentation needs to be improved there.

But if you define your producer and consumer also to declare and request [`org.gradle.category`](https://docs.gradle.org/current/userguide/variant_attributes.html#ecosystem_independent_standard_attributes) with a custom value, like `dokka` (or some other value that has no risk of conflict), then you will not have the problem you expose here.

This is caused by the category attribute not having any compatiblity rule and being defined on all existing variants. Which will prevent any variant with `org.gradle.category=<!dokka>` to ever be selected.

**Comment by aSemy** [comment] 2024-02-19 21:42
> > A category attribute won't help because it's not treated any differently from other attributes.
> 
> Again, documentation needs to be improved there.

That's really astonishing to hear. I had no idea that Category was treated specially. So yes, documentation would be appreciated, thanks.

What's the advice? "Don't use Usage, because it's not strict, instead use Category which will be treated as required"?

> But if you define your producer and consumer also to declare and request [`org.gradle.category`](https://docs.gradle.org/current/userguide/variant_attributes.html#ecosystem_independent_standard_attributes) with a custom value, like `dokka` (or some other value that has no risk of conflict), then you will not have the problem you expose here.

Thanks for the suggestion, I've tried Category but I still get the same problems.

It's still also a problem when the my plugin isn't applied to all subprojects. I guess unless the my plugin does something hacky, like adding a custom attribute to all other Configurations:

```kotlin
rootProject.allprojects {
  buildscript {
    configurations
      .matching { it.isCanBeResolved }
      .configureEach {
        attributes {
          attribute(Attribute.of("my-plugin-hack", String::class.java), "x")
        }
      }
  }
  configurations
    .matching { it.isCanBeResolved }
    .configureEach {
      attributes {
        attribute(Attribute.of("my-plugin-hack", String::class.java), "x")
      }
    }
}
```

Of course I try to write plugins that are good Gradle citizens, but it's such a difficult experience it seems like the only option is to give up on being 'correct' and resort to dumb hacks.

> This is caused by the category attribute not having any compatiblity rule and being defined on all existing variants. Which will prevent any variant with `org.gradle.category=<!dokka>` to ever be selected.

Sorry, I don't follow you. Are you suggesting it's required that Category is added to Configurations? Because I'm sure that's not the case?

What it boils down to is: I want to have the option to use defensive programming principles and mark attributes as required. There's no option for this at the moment. I don't see relying on under-documented behaviour and hoping that all plugins uses the same mysterious combination of attributes as practical.
