### ISSUE TITLE
The responding to the lifecycle in the build script example need modifications to work

### ISSUE THREAD

**Issue by Just-some-one** [gradle/gradle#21216] opened 2022-07-10 11:16 UTC
Hello 

Example 2. Adding of test task to each project which has certain property set in this link https://docs.gradle.org/current/userguide/build_lifecycle.html#build_lifecycle_events

the if statement need to be modified to the following code to make it work

```
if (project.hasProperty("hasTests") && project.hasTests) 
```

also it would be better to notify the reader that he/she would need to create subproject called project-a 

and also the property in the build file in the `project-a` should be changed to 
`ext.hasTests = true`

cause there no hasTests property in the Project so we need to create one in the ext part 

hope that help and have a nice day :slight_smile:

**Comment by Just-some-one** [comment] 2022-07-11 21:48
thanks for your help i just read the user guide to learn gradle 

here my full code with output

i have main project and it's build.gradle has only the  current code (groovy) in the documentations 

`build.gradle`

```
allprojects {
    afterEvaluate { project ->
        if (project.hasTests) {
            println "Adding test task to $project"
            project.task('test') {
                doLast {
                    println "Running tests for $project"
                }
            }
        }
    }
}

```

`settings.gradle`

`include 'project-a'`

and inside that project there subproject (another folder ) named `project-a` and it's build file as follow

`build.gradle`  (this the build file inside the subfolder project-a)

`hasTests=true` 

this the output of the  error message 

```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/<username>/IdeaProjects/LearningGradle/build.gradle' line: 3

* What went wrong:
A problem occurred configuring root project 'LearningGradle'.
> Could not get unknown property 'hasTests' for root project 'LearningGradle' of type org.gradle.api.Project.

```
line 3 is where the if statement

then change the if statement as mentioned earlier (in the if statement you can use project.ext.hasTests or project.hasTests both work) then the build success but running the `gradle -q test` will output the following error

```
FAILURE: Build failed with an exception.

* What went wrong:
Task 'test' not found in root project 'LearningGradle'.

```

change the `build.gradle` inside the subproject `project-a` to `ext.hasTests = true` and everything work as expected

so the ext is required in the build.gradle of the subproject (where we declare it) 

and the output will be 

```
Adding test task to project ':project-a'
Running tests for project ':project-a'
```

if this example meant to use different layout or if i miss something then sorry for wasting your time and could you correct me or at least give direction in the documentation to what this example should be built

thanks for your time and have a nice day :)

**Comment by Just-some-one** [comment] 2022-07-11 21:49
sorry i closed it by mistake

**Comment by Just-some-one** [comment] 2022-07-12 00:19
and here the output of the gradle -- version

```
------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Build time:   2022-03-31 15:25:29 UTC
Revision:     540473b8118064efcc264694cbcaa4b677f61041

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.3 (Red Hat, Inc. 17.0.3+7-LTS)
OS:           Linux 4.18.0-372.13.1.el8_6.x86_64 amd64
```

i use Rocky Linux 8.6 (RedHat derivative )

**Comment by ljacomet** [comment] 2022-08-29 08:38
The issue is effectively in the documentation, which is missing some content that is in the snippet file:

`build.gradle` should contain:
```
allprojects {
    ext.hasTests = false
}
```

Or have the line move in the existing `allprojects`, as is done for the Kotlin version.

**Comment by Just-some-one** [comment] 2022-08-29 13:14
thanks @ljacomet  for clarification and have a nice day :)

**Comment by nathan-contino** [comment] 2022-12-02 16:24
Addressed in https://github.com/gradle/gradle/pull/22455

**Closed by nathan-contino** 2022-12-02 16:24 UTC
Labels: in:configuration-model, 🌱 onboarding, a:documentation
