### ISSUE TITLE
Dependency resolution based on attributes

### ISSUE THREAD

**Issue by peterfigure** [gradle/gradle#20016] opened 2022-02-24 00:01 UTC
To minimize the need to update build definitions & version catalogs it's handy to use dynamic version resolution such as wildcards or ranges, however:

`implementation("io.arrow:arrow-core:1.0.+")` will resolve to `io.arrow:arrow-core:1.0.6-alpha.1` when the intention was to use the latest release, ie a semver without a [pre-release label](https://semver.org/#spec-item-9), which would be `io.arrow:arrow-core:1.0.1`. This is also the case with our internally published artifacts which is of more concern. 

There seems to be no way to select the latest non pre-release artifact except using a custom `ComponentSelectionRule`, not ideal. 

A more appealing approach would be to use the [`latest` version selector](https://docs.gradle.org/current/userguide/single_versions.html) along with the [`org.gradle.status` attribute](https://docs.gradle.org/current/userguide/variant_attributes.html#variant_attributes) and populate this attribute as [per docs](https://docs.gradle.org/current/userguide/component_metadata_rules.html#sec:custom_status_scheme):

`At the moment, the only attribute with meaning here is org.gradle.status. It is therefore recommended to only modify this attribute, if any, on the component level. A dedicated API setStatus(value) is available for this. 
`

It would be easy & convenient to be able to set `org.gradle.status` based on the `project.version` and publish our artifacts to Maven repo using our own custom status scheme (or even just following Ivy's: milestone/integration/release)

However, despite being in the documentation for more than 2 years it doesn't appear to work in my own testing and according to this unresolved issue: https://github.com/gradle/gradle/issues/12600

Is there any way to get this resolved or another way to publish the desired `org.gradle.status` in the artifact? Or is there a completely different way to achieve this?

**Comment by eskatos** [comment] 2024-09-17 13:29
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by big-guy** [comment] 2024-09-17 16:34
Like you say, this issue https://github.com/gradle/gradle/issues/12600 prevents you from publishing with a status other than release to Maven.

I don't see another way of changing this because we base the status on the version number always and ignore the attribute when publishing to Maven.

This is a dupe of https://github.com/gradle/gradle/issues/12600.  I've added that issue to 9.x, but we won't be able to fix this in 8.x

**Closed by big-guy** 2024-09-17 16:34 UTC
Labels: a:bug, in:dependency-resolution, :wave: team-triage
