### ISSUE TITLE
jigsaw automatic modules

### ISSUE THREAD

**Issue by wind57** [gradle/gradle#14177] opened 2020-08-17 23:15 UTC
Currently, `gradle` [has some rules of what a module jar is](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/internal/jvm/JavaModuleDetector.java#L154). This class, in general, is responsible for telling if gradle will include a certain jar on the module-path (as opposed to classpath). In the majority of cases, jars exposed to maven repository have _at least_ [Automatic-Module-Name](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/internal/jvm/JavaModuleDetector.java#L45) in the manifest file, indeed. But of course not all. So if you have a dependency like this, for example:

    compile group: 'org.hdrhistogram', name: 'HdrHistogram', version: '2.1.12'

and in `module-info.java` there is:

    requires HdrHistogram;

this entry will be [added to the class-path](https://github.com/gradle/gradle/blob/master/subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java#L360)

But since it fails the filter in `JavaModuleDetector` it is excluded from the module-path, in the very next line. 

What if this dependencies from the class-path would be converted to _automatic_ modules _automatically_. I _think_ that this is what maven does, but I am yet to try.

Inferring the name of this automatic module could be done as simple as : `jar --file=... --describe-module` and probably parsing that. 

The workaround is to do :

```
tasks.withType(JavaCompile) {
        doFirst {
            options.compilerArgs = [
                    '--module-path', classpath.asPath
            ]
            classpath = files()
        }
    }
```

so this is not a blocker; it just feels a little bit strange. Or is it just me being strange here?

**Comment by ljacomet** [comment] 2020-08-18 07:23
Thank you for your interest in Gradle!

This issue is a duplicate of #12630 and will be closed as such.

In addition, the issue above has a link to a sample solving this with artifact transforms.

**Closed by ljacomet** 2020-08-18 07:23 UTC
Labels: @jvm, a:feature, closed:duplicate, from:contributor, in:jvm-ecosystem
