### ISSUE TITLE
IvyArtifactRepository.layout is hard to customize in a type-safe way

### ISSUE THREAD

**Issue by jnizet** [gradle/gradle#6529] opened 2018-08-27 14:18 UTC
### Expected Behavior
One should be able to translate the following groovy code to the kotlin DSL easily, and in a type-safe way:

```groovy
// groovy
repositories {
    ivy {
        url "http://repo.mycompany.com/repo"
        layout "pattern", {
            artifact "[module]/[revision]/[type]/[artifact].[ext]"
        }
    }
}
```

### Current Behavior
It's not easy, because `layout("pattern")` returns a `RepositoryLayout`, and it's not obvious that this needs to be cast (and can be cast) to `IvyPatternRepositoryLayout`:

```kotlin
// kotlin
repositories {
    ivy {
        url = uri("http://repo.mycompany.com/repo")
        layout("pattern") {
            (this as IvyPatternRepositoryLayout).apply {
                artifact("[module]/[revision]/[type]/[artifact].[ext]")
            }
        }
    }
}
```

Quoting Paul Merlin on Slack thread:

> The Gradle API should be enhanced to provide more type safe members

**Comment by eskatos** [comment] 2018-08-27 14:45
Just a nit pick, thanks to kotlin compiler's smart casts this can be shortened a bit:
```kotlin
// kotlin
repositories {
    ivy {
        url = uri("http://repo.mycompany.com/repo")
        layout("pattern") {
            this as IvyPatternRepositoryLayout
            artifact("[module]/[revision]/[type]/[artifact].[ext]")
        }
    }
}
```

**Comment by jnizet** [comment] 2018-08-27 16:43
I know, but i just find it weird to use a cast without using the result (other than indirectly using the smart cast magic). Maybe it's my Java background, but I find it more logical to make the cast and use the result to call apply() on it.

**Comment by ljacomet** [comment] 2018-08-31 13:33
The problem is that the type of the layout is based on the passed in `String`, with only the value `pattern` resulting in an `IvyPatternRepositoryLayout` being made available.

So it might be simply easier to add a method like `patternLayout` that would take an `Action<IvyPatternRepositoryLayout>`.

My historical knowledge of this class is pretty limited, so there might be good reasons for the current API.

@gradle/dependency-management WDYT?

**Comment by bigdaz** [comment] 2018-08-31 14:56
I don't think there are any good reasons for the current API. The allowable values for `layout` are: "gradle", "maven", "ivy" and "pattern". Of these, only "pattern" produces a mutable `IvyPatternRepositoryLayout` that makes sense to modify via an `Action`.

We should come up with an improved, type-safe alternative, and deprecate the current API.

**Comment by ljacomet** [comment] 2018-09-04 07:41
Once the PR above is merged, a follow up PR will need to update the usage in the Gradle build itself once it uses a Gradle version containing the fix.

**Closed** 2018-10-09 15:16 UTC
Labels: from:contributor, in:dependency-management
