### ISSUE TITLE
Unzip produce error for gradle-8.3.0-bin.zip

### ISSUE THREAD

**Issue by wssnetwork** [gradle/gradle#26149] opened 2023-08-21 04:18 UTC
### Current Behavior

When I run `unzip gradle-8.3.0-bin.zip`, it produce error as below.

Archive:  gradle-8.3.0-bin.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of gradle-8.3.0-bin.zip or
        gradle-8.3.0-bin.zip.zip, and cannot find gradle-8.3.0-bin.zip.ZIP, period.

### Expected Behavior

My pipeline scheduled for build docker image to run pull with latest gradle, download the binary and unzip it. It will unzip successfully. 

### Steps to Reproduce

Step in my docker:

RUN export GRADLE_VER=$(curl -sL https://api.github.com/repos/gradle/gradle/releases/latest | jq -r ".tag_name" | sed "s/v//") && \
curl -LO https://downloads.gradle.org/distributions/gradle-$GRADLE_VER-bin.zip && \
unzip gradle-$GRADLE_VER-bin.zip -d $HOME/ && \
mv $HOME/gradle-$GRADLE_VER $HOME/gradle && \
rm gradle-$GRADLE_VER-bin.zip

![image](https://github.com/gradle/gradle/assets/6211900/c55b1c28-d624-438c-a750-c05a376a885b)

### Gradle version

8.3.0

**Comment by jbartok** [comment] 2023-08-21 10:23
Sorry that you're having trouble with Gradle!
Unfortunately, we can't reproduce your issue. 
Can you please check that the download wasn't aborted before it finished or that there is nothing else corrupted on your system? 
I will close this issue for now, but if you still think this is a generic issue, please let me know and provide more information about the environment the unzipping happens in.

**Closed by jbartok** 2023-08-21 10:23 UTC
Labels: a:bug, to-triage

**Comment by wssnetwork** [comment] 2023-08-22 03:27
Hello. Today it still failed the pipeline. For in the pipeline, the Docker image use debian:stable-slim.

I reproduce to our local server it showing same error.
![image](https://github.com/gradle/gradle/assets/6211900/50e4469c-260a-4ae6-871e-a51b0ece4da8)

**Comment by jbartok** [comment] 2023-08-22 11:53
Very weird... We are not getting any other similar complaints, and considering the number of downloads we have, that's relevant. I still suspect something in your local environment/network.

**Comment by h0landa** [comment] 2023-09-06 14:49
Estava com o mesmo erro, mas configurei a versão para ´https\://services.gradle.org/distributions/gradle-8.2.1-bin.zip` e até o momento está funcionando perfeitamente.

**Comment by Omico** [comment] 2024-03-04 22:58
Same issue here. There is some issue with the GitHub CDN. I don't know what is going on. But seems there is no issue if we download via broswer.

This one won't work.
```dockerfile
RUN GRADLE_DISTRIBUTION_URL=$(curl -s "https://services.gradle.org/versions/current" | jq -r .downloadUrl); \
    echo "Downloading Gradle from ${GRADLE_DISTRIBUTION_URL}"; \
    curl -s ${GRADLE_DISTRIBUTION_URL} -o /tmp/gradle.zip; \
    unzip /tmp/gradle.zip
```

```
Downloading Gradle from https://services.gradle.org/distributions/gradle-8.6-bin.zip
Archive: /tmp/gradle.zip
End-of-central-directory signature not found. Either this file is not
a zipfile, or it constitutes one disk of a multi-part archive. In the
latter case the central directory and zipfile comment will be found on
the last disk(s) of this archive.
unzip: cannot find zipfile directory in one of /tmp/gradle.zip or
/tmp/gradle.zip.zip, and cannot find /tmp/gradle.zip.ZIP, period.
```

Instead, this one works.

```
RUN curl -s https://downloads.gradle.org/distributions/gradle-8.6-bin.zip -o /tmp/gradle.zip; \
    unzip /tmp/gradle.zip; \
    sudo mv gradle-* ${GRADLE_HOME}; \
    sudo ln -s ${GRADLE_HOME}/bin/gradle /usr/local/bin/gradle; \
    rm /tmp/gradle.zip
```

So, replace `https://services.gradle.org` into `https://downloads.gradle.org` will solve this issue.
