### ISSUE TITLE
Implicit task dependencies for shared build services

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#24512] opened 2023-03-27 10:00 UTC
One of the use-cases for a shared build service is to setup and tear down a server needed for testing only when the test task/s is/are going to be executed.
This often involves deploying of a build result that can then be tested by the test code.

Currently, as far as I have figured out, you need to configure an explicit task dependency from the test task to the producer task in Gradle 8.0.2.

If you have the following:
```kts
abstract class Producer : DefaultTask() {
    @get:OutputFile
    abstract val output: RegularFileProperty

    @TaskAction
    fun produce() {
        output.get().asFile.writeText("FOO")
    }
}

val producer by tasks.registering(Producer::class) {
    output.set(layout.buildDirectory.file("foo"))
}

abstract class DeployingService : BuildService<DeployingService.Params> {
    interface Params : BuildServiceParameters {
        val deployable: RegularFileProperty
    }

    @get:InputFile
    val deployable = parameters.deployable
}

abstract class IntegTest : DefaultTask() {
    @get:Nested
    abstract val deployingService: Property<DeployingService>

    @TaskAction
    fun test() {
        println(deployingService.get().deployable.get().asFile.readText())
    }
}

val deployingServiceProvider = gradle.sharedServices.registerIfAbsent("deployingService", DeployingService::class) {
    parameters.deployable.set(producer.flatMap { it.output })
}

val integTest by tasks.registering(IntegTest::class) {
    usesService(deployingServiceProvider)
    deployingService.set(deployingServiceProvider)
}
```
Then it would be nice if calling `gw integTest` would automatically run `producer` first.
Currently if the output file is not present, the task complains as the file is missing.
If the output file is already present, it works and does not give a warning about missing task dependency (will create a separate issue for that).

If you add an explicit `dependsOn(producer)` to the `integTest` task it works as intended, but it would be nice if it worked without.

**Comment by ov7a** [comment] 2023-03-30 09:06
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #21599

Please add your use case and 👍 to that issue.

**Closed by ov7a** 2023-03-30 09:06 UTC
Labels: a:feature, to-triage
