### ISSUE TITLE
Gradle 8 compiled plugins are not usable with Gradle <7

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#23440] opened 2023-01-08 15:47 UTC
### Expected Behavior
When I compile a plugin with the latest Gradle version, I expect it to work with older versions, otherwise it's not possible to support a range of Gradle versions. See e.g. Kotlin or Gradle Enterprise plugins which do this extensively.

### Current Behavior
```kotlin
abstract class SomeTask: DefaultTask() // not necessary to be defined here, just to show the inheritance tree

fun something(some: SomeTask) {
   some.inputs.files(...)
}
```
compiling the above against `implementation(gradleApi())` in Gradle 8 RC1, it binds (at compile time) to

https://github.com/gradle/gradle/blob/287aac28bc8f1de1b1b74852da8b254cc376bbfb/subprojects/core/src/main/java/org/gradle/api/internal/TaskInputsInternal.java#L31-L32

### Steps to Reproduce 
1. Compile a plugin with Gradle 8 which calls `task.inputs.files(...)`
2. Use this plugin in Gradle 7.x
3. Stand in awe of this beauty:
```
Caused by: java.lang.NoSuchMethodError: 'org.gradle.api.internal.tasks.TaskInputFilePropertyBuilderInternal org.gradle.api.internal.TaskInputsInternal.files(java.lang.Object[])'
	at com.example.SomethingKt.something(something.kt:4)
```

### Context
@lptr added these methods recently: https://github.com/gradle/gradle/pull/22739
It looks like we've been here before as @big-guy explains with Gradle 3.2 breaking compatibility: https://github.com/gradle/gradle/issues/1030
https://github.com/gradle/gradle/issues/1004 is the issue that's being regressed I guess.
Related, or potentially "caused by": https://github.com/gradle/gradle/issues/23431

### Workaround
`(some as Task).inputs` will force the compile-time binding to resolve `Task.getInputs(): TaskInputs` which doesn't have the `files()` overload and therefore compatible with all Gradle versions.

"Gradle Plugin author DX" will be disrupted if this stays like this.

### Your Environment

Build scan URL: it's simple to see the problem statically, but if really necessary I can set up a running example.
For real examples: [see this build's test report artifacts](https://github.com/TWiStErRob/net.twisterrob.gradle/actions/runs/3866626055) (tests in this project runs many Gradle builds for compatibility testing).

**Comment by TWiStErRob** [comment] 2023-01-08 16:01
KGP will definitely face this:
![image](https://user-images.githubusercontent.com/2906988/211206289-99a3f8fa-2aa2-4118-b6a6-be0a724ecbcb.png)

**Comment by xaviarias** [comment] 2023-01-09 09:44
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed, response time may vary.

**Comment by lptr** [comment] 2023-01-11 08:21
Thanks for the thorough report @TWiStErRob! I've added some more thorough tests to avoid a similar problem from happening again. We'll also need to figure out how to stop `DefaultTask` from leaking all these internal APIs... :/ But that's for another day.

**Comment by eirnym** [comment] 2023-01-11 08:30
@lptr, Using `task.inputs.files()` is quite useful to avoid task execution when inputs are empty. Following example is the best way I found to skip task execution on empty input with support of Gradle 6.0-7.6 (and presumably 8.x) inclusive.

In my case this is quite critical and I really need this or another _compatible_ way to support this feature

```kotlin
private fun skipInputWhenEmpty(task: Task, sourceFiles: FileCollection) {
    val input = task.inputs.files(sourceFiles)
        .skipWhenEmpty()

    if (GradleVersion.current() >= GradleVersion.version("6.8")) {
        input.ignoreEmptyDirectories()
    }
}
```

**Comment by TWiStErRob** [comment] 2023-01-11 09:48
@eirnym he's fixing it, see linked PR

@lptr thanks for the quick response I knew tagging you would get the right person on it with the most background

@xaviarias re "We recommend to test cross-version compatibility", see the link in "Your environment"... testing is one thing, getting a sudden unexpected failure when using public APIs is another. We (plugin authors) are [working around enough changes as it is](https://github.com/TWiStErRob/net.twisterrob.gradle/blob/master/compat/gradle/src/main/kotlin/net/twisterrob/gradle/compat/GradleCompat.kt) to support a wide range of Gradle.

![Screenshot_20230111-094242](https://user-images.githubusercontent.com/2906988/211772156-d807db19-c8bb-4372-b600-0f1750ff3e93.png)

**Comment by lptr** [comment] 2023-01-11 11:07
@TWiStErRob https://github.com/gradle/gradle/pull/23482 has been merged to `release`, and it should fix your problem. This will be released as 8.0-rc-2 very soon. Please reopen if you are still experiencing the problem with tonight's nightly or with 8.0-rc-2. Thanks again for reporting.

**Closed by lptr** 2023-01-11 11:07 UTC
Labels: @execution, a:regression, in:execution-engine

**Comment by mateuszkwiecinski** [comment] 2023-01-29 15:01
Google brought me here, although in my case I tried to test my project against AGP 8.x with Gradle 8.0-rc2 (not <7 as the issue originally reported). I initially thought the issue is still here and wanted to share my [build scan](https://scans.gradle.com/s/fvthy6u4kkxa4), but it seems like the issue is now on Google side, so I'll cross-link it here: https://issuetracker.google.com/issues/265809620

**Comment by TWiStErRob** [comment] 2023-01-29 16:39
Yeah, they didn't notice because at the time of their adoption they (AGP 8.x) were only compatible with that one version (Gradle 8 RC1), not many previous ones (Gradle 7.x). And after Gradle fixed it, that broke the alpha/beta versions. Everyone cuts themselves sometimes, that's why it's called bleeding edge :)
