### ISSUE TITLE
Improve publication selection when capabilities are in play

### ISSUE THREAD

**Issue by melix** [gradle/gradle#16123] opened 2021-02-11 17:17 UTC
### Context

Imagine a project `foo` which, from a single API spec, generates both a `client` and a `server`. We can, technically, create multiple publications in a project which are published at different GAV coordinates: `org:foo-client:1.0` and `org:foo-server:1.0`.

Then, in a multi-project setup, we may also want to have 2 kinds of consumers:
- consumers for the `client`
- consumers for the `server`

By default, Gradle would fail with a variant selection error in this case, because the "outgoing configurations" that we created for our client and server share the same capability. However, this shouldn't be the case: the client and the server are different things, so we can set the capabilities of each component:

```
configurations {
    serverElements {
        ...
        outgoing {
            // IMPORTANT! This is NOT the same thing as the client so it MUST have a different capability
            capability("${group}:foo-server:${version}")
            artifacts {
                artifact(serverJar)
            }
        }
    }
}
```

Then a _consumer_ can depend on this specific component of project `foo` by explicitly asking for the capability:

```
dependencies {
    implementation(project(':producer')) {
        capabilities {
            it.requireCapability("${group}:foo-server")
        }
    }
}
```

If we stop the story here, everything works fine. If we add _publication_ to the game, then things get more complicated. If we only publish the `client` and the `server`, that is to say if we only publish the 2 publications of the `foo` project, then everything works fine.

But, as soon as we try to publish any of the consumers, Gradle will fail:

```
* What went wrong:
Could not determine the dependencies of task ':server-consumer:publishPublishJarPublicationToTestRepository'.
> Publishing is not able to resolve a dependency on a project with multiple publications that have different coordinates.
  Found the following publications in project ':foo':
    - Maven publication 'clientPublishMaven' with coordinates org:foo-client:0.1
    - Maven publication 'serverPublishMaven' with coordinates org:foo-server:0.1
```

What happens is that at publish time, Gradle doesn't use the resolution result: it uses whatever is declared. In the declaration, we have a project dependency that we must map to a particular publication, in order to figure out how to translate the project dependency into GAV coordinates. In this case, the target project has 2 publications with different GAV coordinates so we don't know what to choose.

However, in this case, we _could_ try to be smarter. Because there are requested capabilities, we _could_ look into the publications, then iterate on the variants, and try to figure out the "best" publication of the two. It's, however, likely to fail because even in simple cases, a publication may contain variants with different capabilities so we wouldn't be able to choose.

Another option is to be smarter _only_ when using resolved versions. In this case, we know that we have selected a particular variant of the producer, say `serverElements`. Then we could scan the publications of the `foo` project, and check if a _single_ publication contains the variant `serverElements`. This is the case here. But technically, nothing prevents different publications from using the same configurations, so we could also fail. At least, this would improve the situation a bit and support this use case.

**Comment by melix** [comment] 2022-04-17 17:39
ping

**Comment by jjishin** [comment] 2023-10-26 06:58
any updates on this issue ? this makes the whole capability feature useless

**Comment by ljacomet** [comment] 2023-11-07 10:33
This is currently being worked on under [this specification](https://docs.google.com/document/d/1AzAgC_Zud8sz94ZK__ZkFvA7BKvZQzSXi4pzNroMRgk/edit#heading=h.610fausqnpu6)

cc @jvandort

**Comment by big-guy** [comment] 2024-05-13 16:29
Dupe of https://github.com/gradle/gradle/issues/12324

**Closed by big-guy** 2024-05-13 16:29 UTC
Labels: in:publishing-plugins, a:feature
