### ISSUE TITLE
Composite builds support non-default publications and configurations

### ISSUE THREAD

**Issue by calvertdw** [gradle/gradle#2355] opened 2017-06-28 00:20 UTC
As noted in the [documentation](https://docs.gradle.org/3.3/userguide/composite_builds.html#included_build_substitution_limitations):
> a project dependency that is substituted will always point to the default configuration of the target project

For example, included builds that use the java-library plugin have `api`, `implementation`, and `test` configurations that will not be picked up by the including project and JARs for those will be used instead.

### Expected Behavior

`includeBuild` should be aware of all publication in includedBuilds or allow a way to specify which configurations to include by string matching.

### Context

In a multi-project composite build, it is common for projects to depend on each other's source sets (or configurations) independently. Composite builds will not currently work with such projects.

**Comment by bmuschko** [comment] 2017-07-10 20:17
@bigdaz @big-guy Can you provide some feedback here?

**Comment by bigdaz** [comment] 2017-07-12 22:36
That piece of documentation isn't strictly correct:
- If a module dependency specifies a target configuration, then the substituted project dependency will retain that target configuration.
- With the new work on variant-aware dependency resolution, configuration attributes can be used to select a non-default configuration, and these attributes are respected in composite builds.

When an included build that applies the `java-library` plugin, it produces 'api' and 'implementation' _variants_ of a module, which are modelled internally as configurations with different attributes. By supplying the correct request attributes, I believe that Gradle will resolve the correct variant when the `java-library` plugin is applied to an included build. 

However, if your included build publishes 2 different modules with different coordinates, there's no way for Gradle to substitute the module dependency with a project dependency with a particular configuration, since a configuration does not map 1:1 with a publication.

For this reason, we'd rather not add a simple `configuration` property to the dependency substitution rule: this would prevent variant-aware resolution (since we choose a configuration by attributes) and would imply that a single configuration maps to a particular publication. Instead, we'd like to provide better ways for a build to declare it's publications, and for composite builds to understand these declarations. (Unfortunately, this will be a significant amount of work and we may not get to it very soon).

**Comment by calvertdw** [comment] 2017-07-13 17:16
Which attributes do you set for selecting 'api' and 'implementation' variants? I have tried using: 

compile group: 'my.group', name: 'some-project', version: '1.0', configuration: 'apiCompile'

**Comment by calvertdw** [comment] 2017-07-17 16:25
> By supplying the correct request attributes, I believe that Gradle will resolve the correct variant when the java-library plugin is applied to an included build.

@bigdaz Can you give an example of this?

**Comment by bigdaz** [comment] 2017-07-17 17:04
Sorry, [Configuration Attributes](https://github.com/gradle/gradle/blob/8a7b8ea7bfd2c38689c8fa339c66485f610c10a9/subprojects/core/src/main/java/org/gradle/api/attributes/AttributeContainer.java#L42-L42) are pretty new, and not fully documented at this stage. But I'm suggesting that when you have a project dependency on a `java-library` project, there's no need to specify `apiCompile` or `implementation` in the dependency declaration: Gradle will choose the correct variant (represented by a `Configuration`) based on whether it's compiling against the `java-library` or requires a runtime classpath.

For this reason,  `java-library` projects should work out-of-the-box in a composite build. A regular `my.group:some-project:1.0` dependency declaration will be substituted with a regular `project('some-project')` dependency, and variant aware resolution will select the correct variant based on usage.

For _arbitrary_ configurations (like `test`) then this will only work if you publish the `test` module with the _same coordinates_ but a _different configuration_. Then you can use a dependency like `compile group: 'my.group', name: 'some-project', version: '1.0', configuration: 'test'` which will be substituted with a dependency like `project(path: 'some-project', configuration: 'test')`. Unfortunately, I can't think of a way to do this with a Maven repository: only Ivy repositories have support for published configurations like this.

**Comment by oehme** [comment] 2017-09-06 13:11
Duplicate of #2529

**Closed by oehme** 2017-09-06 13:11 UTC
Labels: a:feature, from:contributor, in:composite-builds
