### ISSUE TITLE
Wrong Eclipse .classpath is generated in Gradle 4.6

### ISSUE THREAD

**Issue by vlotarev** [gradle/gradle#4563] opened 2018-03-02 11:01 UTC
Switching to 4.6 I am observing some troubles with Eclipse .classpath generation. The problem is that now generating "src" classpathentry items Gradle doesn't respect defaultOutputDir. As a result I see the following .classpath now

```
<classpath>
	<classpathentry kind="src" output="bin/main" path="src/main/java">
		<attributes>
			<attribute name="gradle_scope" value="main"/>
			<attribute name="gradle_used_by_scope" value="main,test"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="bin/main" path="src/main/resources">
		<attributes>
			<attribute name="gradle_scope" value="main"/>
			<attribute name="gradle_used_by_scope" value="main,test"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="bin/test" path="src/test/java">
		<attributes>
			<attribute name="gradle_scope" value="test"/>
			<attribute name="gradle_used_by_scope" value="test"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8"/>
	<classpathentry kind="con" path="org.eclipse.buildship.core.gradleclasspathcontainer"/>
	<classpathentry kind="output" path="classes"/>
</classpath>
```

The previous (correct) one was:
```
<classpath>
	<classpathentry kind="src" path="src/main/java"/>
	<classpathentry kind="src" path="src/main/resources"/>
	<classpathentry kind="src" path="src/test/java"/>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8"/>
	<classpathentry kind="con" path="org.eclipse.buildship.core.gradleclasspathcontainer"/>
	<classpathentry kind="output" path="classes"/>
</classpath>
```

I expect compiled classes to be in "classes" folder but not in "bin" one. Moreover Eclipse project setting dialog shows "classes" output folder what is even more confusing ...

**Comment by oehme** [comment] 2018-03-02 11:26
Duplicate of https://github.com/gradle/gradle/issues/3825. See also https://github.com/gradle/gradle/issues/3839

**Closed by oehme** 2018-03-02 11:26 UTC
