### ISSUE TITLE
4.0-milestone-2:  Dependent module resources not included in the processor classpath

### ISSUE THREAD

**Issue by cesar1000** [gradle/gradle#2169] opened 2017-05-27 17:13 UTC
The java plugin in gradle-4.0-milestone-2 does not include the dependent module resources in the processor classpath. As a result, the compiler can't find annotation processors declared by using a META-INF/services file in the resources of the annotation processor jar file (for ServiceLoader).

This used to work in 3.5.

### Expected Behavior
The processor classpath should include the resources of all dependent modules.

### Current Behavior
3.5 used to include the dependent module's jar file in the processor classpath. 4.0-milestone-2 seems to include the classes directory instead, which does not contain resources.

### Context
Declaring annotation processors so that the compiler can load them using ServiceLoader is a convenient and well documented technique. If unavailable, I'd have to declare all my annotation processors explicitly, even if they don't require any options.

### Steps to Reproduce (for bugs)
In my case, I have an autoservice module with an annotation processor declared under META-INF/services. In 3.5, the processor classpath contains auto-service/build/libs/auto-service.jar, but in 4.0-milestone-2 it's auto-service/build/classes/java/main.

### Your Environment
Gradle 4.0-milestone-2

**Comment by melix** [comment] 2017-05-30 13:12
@cesar1000 thanks for the report. I need a bit more information. From what I read, I suppose that you have a dependent project which is an annotation processor. So, somewhere, you have the annotation processor path which has a dependency like `project(':my-annotation-processor')`. If, for that, you are using the `compile` configuration:

```
compile project(':my-annotation-processor')
```

then you are effectively adding the annotation processor on the compile classpath, which will end up in the classes directory being added, and will explain what you see. It would be better to separate your annotation processor from the compile classpath, for example by defining an `apt` configuration:

```
configurations {
   apt
}
dependencies {
   apt project(':my-annotation-processor')
}
```
then wire the annotation processor path:

```
compileJava {
    options.annotationProcessorPath = configurations.apt
}
```

let me know if it helps.

**Comment by oehme** [comment] 2017-05-30 13:53
> then you are effectively adding the annotation processor on the compile classpath, which will end up in the classes directory being added, and will explain what you see.

That should only happen if the project providing the processor uses the `java-library` plugin. If it uses the `java` plugin, then we've broken something.

Nevertheless Cédric is right that annotation processors are better modeled explicitly, because they are quite different from normal compile dependencies and need a runtime to work.

**Comment by oehme** [comment] 2017-05-30 16:07
@cesar1000 would you mind creating a small reproducible example on GitHub? That would really help us resolve this issue.

**Comment by cesar1000** [comment] 2017-05-30 16:44
I'm using the java plugin and I'm adding my annotation processors using compileOnly, which is indeed adding it to both the processor path and the class path. I will add an annotationProcessor configuration (similar to the Android plugin) to make annotation processors explicit when using the java plugin (why not making that available in the plugin by default, by the way?)

However, it looks like there's a regression in 4.0. When running on 3.5, this is what I get in the command line:

```
-processorpath
/Users/cpuerta/workspace/twitter-android/lib/core/util/compiler/auto-service/build/libs/auto-service.jar
-classpath
/Users/cpuerta/workspace/twitter-android/lib/core/util/compiler/auto-service/build/libs/auto-service.jar
```

This is what I get, however, when running on 4.0-milestone-2:

```
-processorpath
/Users/cpuerta/workspace/twitter-android/lib/core/util/compiler/auto-service/build/classes/java/main
-classpath
/Users/cpuerta/workspace/twitter-android/lib/core/util/compiler/auto-service/build/classes/java/main
```

The jar files contain the resources, but the classes directory does not. Let me try to repro in a small project.

**Comment by oehme** [comment] 2017-05-31 07:35
> why not making that available in the plugin by default, by the way?

We will, just need to fit this in with all the other priorities :)

Is the `lib/core/util/compiler/auto-service` also using the `java` plugin?

> Let me try to repro in a small project.

That would be great.

**Comment by cesar1000** [comment] 2017-06-01 09:02
Ah, my bad: of course, I had switched to the java-library plugin, which publishes class directories instead of jar files. Using the java plugin for my annotation processors does the right thing: the jar file containing the resources is published and downstream modules can use the resources to load the annotation processor. This is independent of whether I use a new annotationProcessor configuration (which I will do!).

This looks like a bug though, since the clients of the annotation processor module should be able to see the resources without regard to whether it's using the java or java-library module. Is this behavior intended?

**Comment by melix** [comment] 2017-06-01 09:06
It's not a bug, it works as expected. A Java Library doesn't "publish" class directories, it has several variants, which are selected based on the consumer configuration. The "compile classpath" configuration wants to use the "classes directory", so Java Library gives it the class directory. 

If you use a different configuration (`apt`, for example), then if you say nothing it will choose the default configuration, which should be the jar.

**Comment by cesar1000** [comment] 2017-06-01 09:10
Ah, sounds good. Let me try that.

**Comment by oehme** [comment] 2017-06-01 14:18
Also to add some more context to @melix answer: If you don't explicitly specify your annotationProcessorPath even though you have processors, we shut off compile avoidance, which will make your build slower. So having a dedicated configuration for processors and setting the annotationProcessorPath is very important for compile speed.

**Comment by oehme** [comment] 2017-06-01 14:21
Closing as working as designed. The annotation processing concerns are explained in the [user guide](https://docs.gradle.org/3.5/userguide/java_plugin.html#sec:java_compile_avoidance).

**Closed by oehme** 2017-06-01 14:21 UTC
Labels: a:bug, affects-version:4.0, from:contributor, in:jvm-platform

**Comment by cesar1000** [comment] 2017-06-01 17:11
Thanks for the tip, @oehme!

My concern with the "compile classpath" configuration in java-library is that it's not obvious that it doesn't bring resources into the classpath. The use of a service loader is not limited to annotation processors, and it seems to me that regular projects that publish services for the service loader won't be able to use java-library. Is that the case, or is there a usage pattern we should follow in that case?

**Comment by oehme** [comment] 2017-06-02 08:49
@cesar1000 Compilation should *never* depend on resources, the compiler only reads .class files. 

> The use of a service loader is not limited to annotation processors, and it seems to me that regular projects that publish services for the service loader won't be able to use java-library. Is that the case, or is there a usage pattern we should follow in that case?

I think you're thinking of runtime usage here, in which case you should use `runtimeClasspath`, which will contain the jar.

**Comment by cesar1000** [comment] 2017-06-03 00:35
Yeah, makes sense! Thanks for all the answers. I switched all our annotation processors to a new configuration, as suggested.
