### ISSUE TITLE
Warning about undeclared build service usage is lost in some cases

### ISSUE THREAD

**Issue by ALikhachev** [gradle/gradle#28533] opened 2024-03-21 16:59 UTC
### Current Behavior

If there's some build service that is registered before enabling `STABLE_CONFIGURATION_CACHE` feature preview, it disables the warning about using build service in task action without declaration.

### Expected Behavior

The warning is reported consistnently

### Steps to Reproduce

Please refer to README of https://github.com/ALikhachev/gradle-build-service-declaration-warning-reproducer

### Gradle version

8.7-rc-4

**Comment by ov7a** [comment] 2024-03-25 11:21
So the nagging [depends](https://github.com/gradle/gradle/blob/3afde3ff8add84f12aa7c55e4fac61ee20d37427/subprojects/core/src/main/java/org/gradle/internal/service/scopes/BuildScopeServices.java#L734-L736) on the time of the creation of `DefaultBuildServicesRegistry` which (apparently) is triggered by the `registerIfAbsent` [call](https://github.com/ALikhachev/gradle-build-service-declaration-warning-reproducer/blob/73a40e9b737ce7d3970c7963675e4d4426294010/settings.gradle.kts#L9).

**Comment by mlopatkin** [comment] 2024-11-05 18:31
This issue will be closed as a duplicate of

* #31140

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

Thank you for the report! We're working on retiring `STABLE_CONFIGURATION_CACHE`, so this issue will be obsoleted by making the warning unconditional.

**Closed by mlopatkin** 2024-11-05 18:31 UTC
Labels: a:bug, in:configuration-model, closed:duplicate, in:build-services, re:comprehensibility
