### ISSUE TITLE
Dependency locking locks transitive concrete version instead of latest

### ISSUE THREAD

**Issue by btilbrook-nextfaze** [gradle/gradle#7391] opened 2018-10-15 22:32 UTC
### Expected Behavior
Running `gradle --write-locks` resolves the latest version of `X` that matches the declared dependancy constraint in the build script.

### Current Behavior
If a transitive dependency specifies an older, concrete version of `X`, `gradle --write-locks` resolves that older version and writes it the the lockfiles.

If I disable dependency locking and run the script again, it resolves the latest version as expected. Thus, dependency locking seems to be causing unexpected resolution rule changes.

### Context
My aim is to use dependency locking to achieve the following:
* Ensure deterministic builds when transitive dependencies use dynamic versions
* Make it easier to update to the latest versions of my dependencies, within constraints I specify

### Steps to Reproduce (for bugs)

Sample project:  
[dependency-locking-bug.zip](https://github.com/gradle/gradle/files/2480784/dependency-locking-bug.zip)

1. `cd` into the attached project dir
1. Run `./gradlew dependencies --write-locks`
1. Run `./gradlew -q dependencyInsight --dependency hamcrest-core --configuration testCompile`

Expected:  
`org.hamcrest:hamcrest-core` is resolved to version `1.13`

Actual:  
`org.hamcrest:hamcrest-core` is resolved to version `1.11`

Also: 
1. Comment-out the `dependencyLocking` DSL in `build.gradle`
1. Delete the lockfiles
1. Run dependency insight again

It will resolve to `1.13` - different behavior compared to when locking is enabled.

### Your Environment

* Gradle `4.10.2`
* macOS `10.13.6`
 * Build scan URL for the `./gradlew dependencies --write-locks` command: https://gradle.com/s/ijsnezxua7kl2

**Comment by bigdaz** [comment] 2018-10-16 00:55
Thanks for the report. This looks very much like a duplicate of #6340, which is fixed for Gradle 5.0.
I can reproduce the issue using 4.10.2, and get the correct behaviour with a recent snapshot.

If you still see this behaviour with a [5.0 milestone or release-candidate](https://gradle.org/release-candidate/) please let us know.

**Closed by bigdaz** 2018-10-16 00:55 UTC
Labels: a:bug, from:contributor, in:dependency-management
