### ISSUE TITLE
compileKotlin task is deleting files in destinationDir

### ISSUE THREAD

**Issue by hfazai** [gradle/gradle#19237] opened 2021-12-07 14:07 UTC
I defined a custom destination directory in compileKotlin task using:
````KOTLIN
compileKotlin {
    destinationDir = file("classRoot")
}
````

When start compileKotlin task, all files in `classRoot` directory are deleted.
### Expected Behavior

compileKotlin should'nt clean `classRoot` directory.

### Current Behavior

compileKotlin is cleaning `classRoot` directory.

### Steps to Reproduce 

1. Create a very basic kotlin project.
2. Add this line to your build script build.gradle.kts: (change `classRoot` with a directory in your machine)
````KOTLIN
compileKotlin {
    destinationDir = file("classRoot")
}
````
3. Create a file in the directory `classRoot` (`touch f.txt`)
4. Run compileKotlin task (`./gradlew compileKotlin`)
5. The file `classRoot/f.txt` is deleted.

### Your Environment

Gradle 7.2
OS: Fedora 34

**Comment by jbartok** [comment] 2021-12-08 08:35
Thank you for your interest in Gradle!

This is an issue caused by the interaction of Gradle's up-to-date checking and the lack of incremental compilation feature of the Kotlin compiler, which is developed by JetBrains and cannot be addressed in the core of the Gradle Build Tool.

Please open such IntelliJ-related issues on the JetBrains Issue Tracker at https://youtrack.jetbrains.com/

**Comment by hfazai** [comment] 2021-12-08 08:54
Done in [KT-50130](https://youtrack.jetbrains.com/issue/KT-50130), Thanks :+1:

**Closed** 2021-12-08 09:45 UTC
Labels: a:bug, closed:kotlin
