### ISSUE TITLE
VERSION_CATALOGS feature fails if any dir in project path starts with character "u": "illegal unicode escape"

### ISSUE THREAD

**Issue by ylexus** [gradle/gradle#19752] opened 2022-01-28 16:00 UTC
```
FAILURE: Build failed with an exception.
* What went wrong:
org.gradle.api.internal.catalog.GeneratedClassCompilationException: Unable to compile generated sources:
  - File LibrariesForUnity.java, line: 31, illegal unicode escape
  - File LibrariesForUnity.java, line: 53, illegal unicode escape
> Unable to compile generated sources:
    - File LibrariesForUnity.java, line: 31, illegal unicode escape
    - File LibrariesForUnity.java, line: 53, illegal unicode escape
```

This is because "\u" is treated as a unicode escape even in comments:
`LibrariesForUnity.java` generated by gradle - note `\u` in the javadoc:
```java
...
        /**
         * Creates a dependency provider for platform (com.xxx:unity-xxx)
         * This dependency was declared in settings file '..\unityxxx\settings.gradle'
         */
        public Provider<MinimalExternalModuleDependency> getXxxxxx() { return create("xxxxxx"); }
...
```

This is happening when importing such project to IntelliJ IDEA version 2021.3.2 RC Build #IU-213.6777.38.

`unityxxx/settings.gradle`:
```groovy

include 'aaa', 'bbb'

enableFeaturePreview('VERSION_CATALOGS')
dependencyResolutionManagement {
    versionCatalogs {
        unity {
            version('unity', '3+')
            alias('p').to('com.xxx.xxx', 'unity-p').versionRef('unity')
        }
    }
}
```

`unityxxx/bbb/build.gradle`:
```groovy

dependencies {
    implementation unity.p
}
```

**Comment by ylexus** [comment] 2022-01-31 09:38
To add more details, this is happening when importing such project to IntelliJ IDEA version 2021.3.2 RC Build #IU-213.6777.38.

**Comment by ylexus** [comment] 2022-02-03 12:20
Still present in 7.3.3

**Comment by jmini** [comment] 2022-06-21 12:40
The issue is still present with `7.4.2`

**Comment by jmini** [comment] 2022-06-21 12:58
Some analysis:

The code generator is here:
https://github.com/gradle/gradle/blob/7bc96f17b23ac77288d8100e0a11935ecd3932fe/subprojects/dependency-management/src/main/java/org/gradle/api/internal/catalog/LibrariesSourceGenerator.java#L437-L439

And when the context is from type `DefaultFileTreeElement`:

`toString()` defined in in the parent class:
https://github.com/gradle/gradle/blob/7bc96f17b23ac77288d8100e0a11935ecd3932fe/subprojects/file-collections/src/main/java/org/gradle/api/internal/file/AbstractFileTreeElement.java#L46-L49

Delegates to `getDisplayName()`:
https://github.com/gradle/gradle/blob/7bc96f17b23ac77288d8100e0a11935ecd3932fe/subprojects/file-collections/src/main/java/org/gradle/api/internal/file/DefaultFileTreeElement.java#L49-L52

And this value is suitable for display in a console, but not when it comes to write code under windows, because of the backslash that need to be escaped.

---

A quick and dirty solution is to add `.replace("\\", "\\\\")` right before printing the context in `LibrariesSourceGenerator`:
```java
writeLn("     * This dependency was declared in " + context.replace("\\", "\\\\"))
```

But is this really the fix you would like to see?
@ljacomet, @melix, @jbartok

And I also probably need to add a new test in `LibrariesSourceGeneratorTest.groovy`. Are they executed on Windows as well?

**Comment by jmini** [comment] 2022-06-21 13:21
👍  The good old "replace backslash with slash" that I have everywhere in my code manipulating files as soon it need to run on Windows as well.

So something like:

```java
 @Override 
 public String getDisplayName() { 
     return "file '" + file.toString().replace('\\', '/') + "'"; 
 } 
```

This will impact a lot of places. I can imagine this `getDisplayName()` or `toString()` are used a lot. Not?

**Comment by jmini** [comment] 2022-06-22 07:29
I have opened a PR: https://github.com/gradle/gradle/pull/21064

**Comment by alllex** [comment] 2022-07-07 11:49
After a discussion with the team it was decided that normalizing the display name would impact too many places. Moreover, it is desirable to keep file-related display names platform specific as they are intended for human consumption.

As such, this issue will be fixed by locally sanitizing the generated sources.

**Closed** 2022-07-12 17:41 UTC
Labels: a:bug, windows, in:dependency-version-catalog
