### ISSUE TITLE
Gradle annotation processor and BOM support does not work correctly with Eclipse or Visual Studio Code

### ISSUE THREAD

**Issue by graemerocher** [gradle/gradle#9314] opened 2019-04-29 09:55 UTC
Originating issue: https://github.com/micronaut-projects/micronaut-profiles/issues/124

We are trying to migrate Micronaut from the Spring Dependency Management plugin and the `net.ltgt.apt` plugins for annotation processing however IDE import is currently broken.

### Expected Behavior

You should be able to import a Micronaut project into Visual Studio Code or Eclipse with the BuildShip plugin and run the application and and tests without issue without having to delegate to Gradle.

### Current Behavior

IDE import is broken since no `.factorypath` is built when running `./gradlew eclipse` which sets up the annotation processors. Note this this works fine with Maven.

### Context

It makes it hard to recommend moving away from existing plugins to built in features if IDEs are not supported correctly.

### Steps to Reproduce 

See https://github.com/micronaut-projects/micronaut-profiles/issues/124

**Comment by oehme** [comment] 2019-04-29 10:23
This is unrelated to BOM support. Gradle has never generated a factorypath, so using the `net.ltgt.apt` is still necessary.

Marking as a duplicate of https://github.com/gradle/gradle/issues/2300

**Comment by aalmiray** [comment] 2019-04-29 13:41
@oehme as @graemerocher has pointed out in https://github.com/micronaut-projects/micronaut-profiles/issues/124 the issue stems from a difference in UX from the POV of the developer that performs a migration from Gradle 4.x, Spring's dependency-management plugin, and the `net.ltgt.apt` to Gradle 5.x only.

You may be right, the underlying cause is not BOM support *but* there's a clear difference in behavior when Gradle's annotation support and BOM support are used instead of third party plugins. The build file linked in https://github.com/micronaut-projects/micronaut-profiles/issues/124 is not final, as platform suggestions are only applied to  `compile`  and not `annotationProcessor`. You might remember we briefly discussed this on Slack and you mention one alternative would be `configurations.configureEach { /* apply it */ }` without actually showing how the applying code would look like. But in any case, the provided build file works on the command line perfectily well, but it leads to failure on IDEs, which is why @graemerocher reached out.

The point of this issue is to figure out if we're missing something from the Gradle side, besides contacting IDE vendors to let them know what they may be missing to handle Gradle 5 correctly.

Is it documentation that we're missing? Hope so. Is it engineering effort? Let's find out.

**Comment by oehme** [comment] 2019-04-29 14:05
> But in any case, the provided build file works on the command line perfectily well

It doesn't, it the wrong version of the annotation processor on the command line too. You just notice that more acutely in the IDE.

If this issue is just about documenting how to apply a BOM for annotation procesors, then we should change the title. There is no problem in BOM support, it works as intended/advertised.

**Comment by nedtwigg** [comment] 2020-01-26 22:35
With @tbroyer's blessing, we have fixed the Gradle 6 deprecation warnings in `net.ltgt.apt-eclipse`, and republished as `com.diffplug.eclipse.apt` as part of the [goomph](https://github.com/diffplug/goomph#comdiffplugeclipse-eclipse-project-files-and-eclipse-version-mapping-maven-central-artifacts) plugin. We will continue to maintain and fix any deprecations in the future.

**Closed** 2020-09-16 10:20 UTC
Labels: @jvm
