### ISSUE TITLE
Custom PublishArtifact objects fail at publishing

### ISSUE THREAD

**Issue by martin-linha** [gradle/gradle#12608] opened 2020-03-23 15:52 UTC
### Expected Behavior
Maven-publish task support the following types to be published (defined in the publications block):
```
  The following types/formats are supported:
    - Instances of ConfigurablePublishArtifact.
    - Instances of PublishArtifact.
    - Instances of AbstractArchiveTask, for example jar.
    - Instances of Provider<RegularFile>.
    - Instances of Provider<Directory>.
    - Instances of Provider<File>.
    - Instances of RegularFile.
    - Instances of Directory.
    - Instances of File.
    - Maps with 'file' key
```
Therefore, I expect instances of `PublishArtifact` can be published as well (as it used to be).

### Current Behavior
Currently, when a publication of type `PublishArtifact` is to be published, the following exception is thrown:

```
 class <Class implementing PublishArtifact interface> cannot be cast to class org.gradle.api.publish.internal.PublicationArtifactInternal
```

### Context
It works with 6.1.1, does not work with 6.2.2 (tested). However, my guess is it stopped working with 6.2.0 by introducing this commit: https://github.com/gradle/gradle/commit/55f7c7d5016e90407c6e3ced071c18246ee367e5#diff-dd14ef57db257597bb02198b184f8e81

As many plugins we use for our builds define publications by implementing the `PublishArtifact` interface, all of them stopped working and are totally unusable with Gradle 6.2.2

### Steps to Reproduce 

1. Clone https://github.com/martin-linha/gradle-620-publications-bug.git
2. Run `publishToMavenLocal`
3. The exception is thrown

### Your Environment
Gradle 6.2.2

**Comment by martin-linha** [comment] 2020-05-28 07:23
This issue is still valid in Gradle 6.3.0

**Comment by peyerroger** [comment] 2020-05-28 07:24
Hi there,

Is there any progress on this? Thanks for your answer.

Cheers,
Roger

**Comment by dezavuisan** [comment] 2020-06-03 15:11
Please some comment on this.

**Comment by alexciouca** [comment] 2020-06-09 10:27
Hello there,

Still no progress with this ticket? There are starting to appear a couple of Gradle plugins which accept Gradle 6.3+ (e.g. Spring Boot Gradle Plugin 2.3.0), but because of this bug I cannot upgrade Gradle and also in some cases I have to downgrade Gradle, which causes other compatibility issues and I have to find a lot of workarounds, which don't work most of the time.

Cheers,
Alex

**Comment by blaghed** [comment] 2020-06-24 09:10
Running into this issue, is anyone having look?

**Comment by praitk** [comment] 2020-07-06 14:11
Hello @melix ,

It looks like that your commit introduced a regression.
Do you know if it is possible to fix it?

Cheers,
  Nico

**Comment by melix** [comment] 2020-07-06 14:23
You're not supposed to implement `PublishArtifact`, as the `@HasInternalProtocol` annotation states. Gradle 6.6 will support any kind of task for attaching artifacts as long as they have a single declared output file, but in the mean time the correct way to declare such an artifact is _not_ to implement `PublishArtifact` but do use `builtBy` (see https://docs.gradle.org/current/userguide/publishing_customization.html#sec:publishing_custom_artifacts_to_maven).

**Comment by praitk** [comment] 2020-07-06 14:43
Thank you very much @melix for your fast reply and the hint!
I'll look on my side into how to proceed with this information.

**Comment by martin-linha** [comment] 2020-07-07 11:08
@melix that is indeed very confusing. If I add an artifact of unsupported type to the publication block, I get the following

  The following types/formats are supported:
    - Instances of MavenArtifact.
    - Instances of AbstractArchiveTask, for example jar.
    **- Instances of PublishArtifact**
    - Maps containing a 'source' entry, for example [source: '/path/to/file', extension: 'zip'].
    - Anything that can be converted to a file, as per Project.file()

**Comment by melix** [comment] 2020-07-07 11:39
You can provide instances of `PublishArtifact` **but** you mustn't implement your own.

**Comment by dezavuisan** [comment] 2020-07-21 14:34
> You can provide instances of `PublishArtifact` **but** you mustn't implement your own.

How about instances implementing `MavenArtifact`? I have the same problem for a task that implements only `MavenArtifact` interface.
More specifically the line https://github.com/gradle/gradle/blob/v6.5.1/subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publication/DefaultMavenPublication.java#L124 **assumes** that every class implementing `MavenArtifact` interface also implements `PublicationArtifactInternal` interface. This seems to be a far-fetched assumption.

**Comment by KevinMcT** [comment] 2021-01-26 21:30
Any new information on this? Specifically referencing @dezavuisan question here.

We also have a custom class implementing MavenArtifact, why is this illegitimate?

**Comment by mlopatkin** [comment] 2021-07-14 12:59
We've fixed the issue for custom`PublishArtifact` instances for now but this approach is still not recommended and Gradle may start to issue a warning soon if a custom implementation is used. I'm closing this issue as a duplicate of #17273.

The reasoning applies to `MavenArtifact` as well. Why do you need to implement your own MavenArtifact?

**Closed by mlopatkin** 2021-07-14 12:59 UTC
Labels: in:publishing-plugins
