### ISSUE TITLE
JDK 20 

### ISSUE THREAD

**Issue by mjmk3** [gradle/gradle#24950] opened 2023-05-02 06:00 UTC
### Expected Behavior

jdk 20 working with gradle 

### Current Behavior

the current version is not yet supporting, compatible or working with jdk 20 

### Steps to Reproduce

upgrading 

### Gradle version

8.1

**Comment by jbartok** [comment] 2023-05-03 09:23
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/23488

Please add your use case and 👍 to that issue.

***

We support compiling & testing in Gradle `8.1` (via toolchains), but not yet running.

**Closed by jbartok** 2023-05-03 09:23 UTC
Labels: a:bug, to-triage
