### ISSUE TITLE
Allow suppression of Kotlin compiler version mismatch warning

### ISSUE THREAD

**Issue by cesar1000** [gradle/gradle#13020] opened 2020-05-05 03:46 UTC
### Current Behavior
When using Kotlin DSL, overriding the version of the Kotlin compiler in the script classpath results in this warning:

```
WARNING: Unsupported Kotlin plugin version.
The `embedded-kotlin` and `kotlin-dsl` plugins rely on features of Kotlin `1.3.70` that might work differently than in the requested version `1.3.72`.
```

### Expected Behavior
The mismatch is inconsequential in a majority of cases, and it's distracting that it shows up consistently in the output without an ability to disable. I understand that disabling unconditionally would defeat the purpose of the check, but it would be nice to have the ability to whitelist versions that are known to work.

### Context
Tested on v6.3.

**Comment by counter-reverse** [comment] 2021-01-07 18:35
There is already an option `--warning-mode none` I will use it and fix this issue. please assign me @eskatos .

**Comment by audkar** [comment] 2021-01-07 18:38
Does this option hides this one particular warning or all warnings? IMO second option is not suitable for any production project

**Comment by counter-reverse** [comment] 2021-01-07 18:41
@mahmoud-k yes it fix all warnings instead of only one. I can only agree with you. Fix one warning would be better. I will see what I can do.

**Comment by counter-reverse** [comment] 2021-07-30 22:28
I am still on this issue. Do not loose hope.

**Comment by mochadwi** [comment] 2021-08-25 11:31
`gradle --warning-mode none` seems didn't fixed the issue

**Comment by piefel** [comment] 2023-10-09 07:58
> The \`embedded-kotlin\` and \`kotlin-dsl\` plugins rely on features of Kotlin \`1.8.20\` that might work differently than in the requested version \`1.8.22\`.

Using Gradle 8.2.1; quite a useless warning.

PS: Why is the error message using backticks?

**Comment by aSemy** [comment] 2024-07-24 20:32
The warning is still undocumented and unclear. [The commit](https://github.com/gradle/gradle/commit/42ac0df54b7c6f5acf5fb363626112a345729b83#diff-307bb99f5d29a4d4e04031a8c5cc61e2f7da9117fff6a35b9d29ec498b14d2c1R71) that adds it doesn't reveal any motivation. 
    
Here is a workaround for disabling it:
    

1. In `buildSrc/build.gradle.kts` add a dependency on KGP.
    
    ```kotlin
    // buildSrc/build.gradle.kts
    
    plugins {
        `kotlin-dsl`
    }
    
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    
    dependencies {
        implementation("org.jetbrains.kotlin:kotlin-gradle-plugin:$embeddedKotlinVersion")
    }
    ```
   
    The version doesn't matter, I've used `embeddedKotlinVersion` here for convenience. Just be aware that if you define KGP as a buildSrc dependency, you have to remove the KGP version from all `plugins {}` blocks in all subprojects!

    ```kotlin
    // some-subproject/build.gradle.kts
    plugins {
        // the version is not necessary, it's defined in buildSrc/build.gradle.kts
        kotlin("jvm") // version "1.9.25"
    }
    ```
3. Copy and paste [`EmbeddedKotlinPlugin.kt`](https://github.com/gradle/gradle/blob/v8.9.0/platforms/core-configuration/kotlin-dsl-plugins/src/main/kotlin/org/gradle/kotlin/dsl/plugins/embedded/EmbeddedKotlinPlugin.kt) into `buildSrc/src/main/kotlin`.
4. Comment out the annoying warning:
    
    ```diff
      abstract class EmbeddedKotlinPlugin @Inject internal constructor(
          private val embeddedKotlin: EmbeddedKotlinProvider
      ) : Plugin<Project> {
      
          override fun apply(project: Project) {
              project.run {
      
                  plugins.apply(KotlinPluginWrapper::class.java)
      
    -               logger.warnOnDifferentKotlinVersion(getKotlinPluginVersion())
    + //            logger.warnOnDifferentKotlinVersion(getKotlinPluginVersion())
    ```
5. Tada, no more warnings!

**Comment by bpoland** [comment] 2024-07-25 15:13
> Here is a workaround for disabling it

@aSemy you are my hero, thank you!

**Comment by aSemy** [comment] 2024-07-26 06:40
Here's a simpler workaround. Add this to `buildSrc/build.gradle.kts`:

```kotlin
// buildSrc/build.gradle.kts

plugins {
    `kotlin-dsl`
}

repositories {
    mavenCentral()
    gradlePluginPortal()
}

//region disable 'Unsupported Kotlin plugin version' warning
// Workaround for https://github.com/gradle/gradle/issues/13020
val disableUnsupportedKotlinPluginVersionWarning  by tasks.registering {
    description = "Workaround for https://github.com/gradle/gradle/issues/13020"

    val embeddedKotlinVersion = embeddedKotlinVersion
    inputs.property("embeddedKotlinVersion", embeddedKotlinVersion)

    outputs.dir(temporaryDir).withPropertyName("outputDir")

    doLast {
        temporaryDir.resolve("project.properties").apply {
            parentFile.mkdirs()
            writeText(
                """
                project.version=$embeddedKotlinVersion
                kotlin.native.version=$embeddedKotlinVersion
                """.trimIndent()
            )
        }
    }
}

sourceSets {
    main {
        resources.srcDir(disableUnsupportedKotlinPluginVersionWarning)
    }
}
//endregion
```

**Comment by rocketraman** [comment] 2024-08-16 23:41
One solution which may work in simpler cases is to remove `kotlin-dsl` from the plugins block. From [this message from @Vampire in the Kotlin #gradle Slack](https://kotlinlang.slack.com/archives/C19FD9681/p1656671165944879?thread_ts=1656665924.318359&cid=C19FD9681):

> `kotlin-dsl` applies `java-gradle-plugin`, `kotlin-dsl.base`, and `kotlin-dsl.precompiled-script-plugins` plugins. `kotlin-dsl.base` plugin applies `embedded-kotlin`, adds `gradleKotlinDsl()` to the dependencies of `compileOnly` and `testImplementation` configurations, and configures the Kotlin DSL compiler plugins for example for proper SAM conversion for Action and similar.

If you don't need any of that functionality, then you can simply remove `kotlin-dsl`.

**Comment by ljacomet** [comment] 2024-12-05 13:21
This issue will be closed as a duplicate of

* #22647

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

While this issue is older, keeping the other one as it has a reproducer and a request more aligned with what we would do: make the warning actionable

**Closed by ljacomet** 2024-12-05 13:21 UTC
Labels: a:feature, in:kotlin-dsl, to-triage
