### ISSUE TITLE
Provider.ifPresent biconsumer

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#22269] opened 2022-09-30 13:08 UTC
### Expected Behavior

this would be the same as below, similar syntax to java `Optional.ifPresent`

```kt
providers.gradleProperty("spring.profiles.active").ifPresent({ key, value -> systemProperty(key, value })
```

### Context

current workaround
```kt
  providers.gradleProperty("spring.profiles.active").orNull?.run {
    systemProperty("spring.profiles.active", this)
  }
```

[other ticket which contains more context](https://github.com/gradle/gradle/issues/22268). This is not a solution for *that* problem, but rather some improved syntax when problems like that arise.

```
------------------------------------------------------------
Gradle 7.5.1
------------------------------------------------------------

Build time:   2022-08-05 21:17:56 UTC
Revision:     d1daa0cbf1a0103000b71484e1dbfe096e095918

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.4 (Eclipse Adoptium 17.0.4+8)
OS:           Mac OS X 12.6 x86_64
```

**Comment by cloudshiftchris** [comment] 2022-10-07 20:54
Duplicate of #13401 , though the suggestion here to map a system property to K,V won't work as the Provider api is a single value (given the property name, _provide_ the value).

Doable via a Kotlin extension function: 
```
public inline fun <reified S> Provider<S>.ifPresent(block: (S) -> Unit) {
    if (isPresent) {
        block(get())
    }
}
```

**Comment by ov7a** [comment] 2023-11-21 13:33
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/13401

Please add your use case and 👍 to that issue.

**Closed by ov7a** 2023-11-21 13:33 UTC
Labels: a:feature, in:provider-api
