### ISSUE TITLE
preferProjectModules causes dependency metadata to be resolved serially

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#5076] opened 2018-04-17 23:18 UTC
We enabled `preferProjectModules` recently and it makes parallel dependency resolution ineffective as it resolves metadata during conflict resolution:

    ...
    org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.ComponentState.getMetaData() ComponentState.java:174
    org.gradle.api.internal.artifacts.ivyservice.resolveengine.ProjectDependencyForcingResolver.select(ConflictResolverDetails) ProjectDependencyForcingResolver.java:42
	org.gradle.api.internal.artifacts.ivyservice.resolveengine.VersionSelectionReasonResolver.select(ConflictResolverDetails) VersionSelectionReasonResolver.java:31
	org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.conflicts.CompositeConflictResolver.select(ConflictResolverDetails) CompositeConflictResolver.java:36
	org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.conflicts.DefaultConflictHandler.resolveNextConflict(Action) DefaultConflictHandler.java:72
	org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.traverseGraph(ResolveState) DependencyGraphBuilder.java:143
    ...

### Expected Behavior
Metadata resolution is performed in parallel.

### Current Behavior
Metadata resolution is performed serially.

### Context
Dependency resolution performance has decreased significantly.

### Steps to Reproduce (for bugs)
Compare dependency resolution with and without `preferProjectModules`.

### Your Environment
Gradle 4.6

### Full Stack Trace

	Task worker for ':' Thread 2 State: RUNNABLE CPU usage on sample: 96ms
	java.net.SocketInputStream.socketRead0(FileDescriptor, byte[], int, int, int) SocketInputStream.java (native)
	java.net.SocketInputStream.socketRead(FileDescriptor, byte[], int, int, int) SocketInputStream.java:116
	java.net.SocketInputStream.read(byte[], int, int, int) SocketInputStream.java:171
	java.net.SocketInputStream.read(byte[], int, int) SocketInputStream.java:141
	sun.security.ssl.InputRecord.readFully(InputStream, byte[], int, int) InputRecord.java:465
	sun.security.ssl.InputRecord.read(InputStream, OutputStream) InputRecord.java:503
	sun.security.ssl.SSLSocketImpl.readRecord(InputRecord, boolean) SSLSocketImpl.java:983
	sun.security.ssl.SSLSocketImpl.readDataRecord(InputRecord) SSLSocketImpl.java:940
	sun.security.ssl.AppInputStream.read(byte[], int, int) AppInputStream.java:105
	org.apache.http.impl.io.SessionInputBufferImpl.streamRead(byte[], int, int) SessionInputBufferImpl.java:137
	org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer() SessionInputBufferImpl.java:153
	org.apache.http.impl.io.SessionInputBufferImpl.readLine(CharArrayBuffer) SessionInputBufferImpl.java:282
	org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(SessionInputBuffer) DefaultHttpResponseParser.java:138
	org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(SessionInputBuffer) DefaultHttpResponseParser.java:56
	org.apache.http.impl.io.AbstractMessageParser.parse() AbstractMessageParser.java:259
	org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader() DefaultBHttpClientConnection.java:163
	org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader() CPoolProxy.java:165
	org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequest, HttpClientConnection, HttpContext) HttpRequestExecutor.java:273
	org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequest, HttpClientConnection, HttpContext) HttpRequestExecutor.java:125
	org.apache.http.impl.execchain.MainClientExec.execute(HttpRoute, HttpRequestWrapper, HttpClientContext, HttpExecutionAware) MainClientExec.java:272
	org.apache.http.impl.execchain.ProtocolExec.execute(HttpRoute, HttpRequestWrapper, HttpClientContext, HttpExecutionAware) ProtocolExec.java:185
	org.apache.http.impl.execchain.RetryExec.execute(HttpRoute, HttpRequestWrapper, HttpClientContext, HttpExecutionAware) RetryExec.java:89
	org.apache.http.impl.execchain.RedirectExec.execute(HttpRoute, HttpRequestWrapper, HttpClientContext, HttpExecutionAware) RedirectExec.java:111
	org.apache.http.impl.client.InternalHttpClient.doExecute(HttpHost, HttpRequest, HttpContext) InternalHttpClient.java:185
	org.apache.http.impl.client.CloseableHttpClient.execute(HttpUriRequest, HttpContext) CloseableHttpClient.java:83
	org.gradle.internal.resource.transport.http.HttpClientHelper.performHttpRequest(HttpRequestBase, HttpContext) HttpClientHelper.java:148
	org.gradle.internal.resource.transport.http.HttpClientHelper.performHttpRequest(HttpRequestBase) HttpClientHelper.java:130
	org.gradle.internal.resource.transport.http.HttpClientHelper.executeGetOrHead(HttpRequestBase) HttpClientHelper.java:103
	org.gradle.internal.resource.transport.http.HttpClientHelper.performRequest(HttpRequestBase, boolean) HttpClientHelper.java:94
	org.gradle.internal.resource.transport.http.HttpClientHelper.performRawGet(String, boolean) HttpClientHelper.java:80
	org.gradle.internal.resource.transport.http.HttpClientHelper.performGet(String, boolean) HttpClientHelper.java:84
	org.gradle.internal.resource.transport.http.HttpResourceAccessor.openResource(URI, boolean) HttpResourceAccessor.java:43
	org.gradle.internal.resource.transport.http.HttpResourceAccessor.openResource(URI, boolean) HttpResourceAccessor.java:29
	org.gradle.internal.resource.transfer.DefaultExternalResourceConnector.openResource(URI, boolean) DefaultExternalResourceConnector.java:56
	org.gradle.internal.resource.transfer.ProgressLoggingExternalResourceAccessor.openResource(URI, boolean) ProgressLoggingExternalResourceAccessor.java:36
	org.gradle.internal.resource.transfer.AccessorBackedExternalResource.withContentIfPresent(ExternalResource$ContentAction) AccessorBackedExternalResource.java:130
	org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator$11.call(BuildOperationContext) BuildOperationFiringExternalResourceDecorator.java:237
	org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator$11.call(BuildOperationContext) BuildOperationFiringExternalResourceDecorator.java:229
	org.gradle.internal.progress.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(CallableBuildOperation, BuildOperationContext) DefaultBuildOperationExecutor.java:350
	org.gradle.internal.progress.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(BuildOperation, BuildOperationContext) DefaultBuildOperationExecutor.java:340
	org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(BuildOperation, BuildOperationWorker, DefaultBuildOperationExecutor$DefaultBuildOperationState) DefaultBuildOperationExecutor.java:199
	org.gradle.internal.progress.DefaultBuildOperationExecutor.call(CallableBuildOperation) DefaultBuildOperationExecutor.java:120
	org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator.withContentIfPresent(ExternalResource$ContentAction) BuildOperationFiringExternalResourceDecorator.java:229
	org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor.copyToCache(ExternalResourceName, CacheAwareExternalResourceAccessor$ResourceFileStore, ExternalResource) DefaultCacheAwareExternalResourceAccessor.java:199
	org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor.access$300(DefaultCacheAwareExternalResourceAccessor, ExternalResourceName, CacheAwareExternalResourceAccessor$ResourceFileStore, ExternalResource) DefaultCacheAwareExternalResourceAccessor.java:55
	org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor$1.create() DefaultCacheAwareExternalResourceAccessor.java:90
	org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor$1.create() DefaultCacheAwareExternalResourceAccessor.java:82
	org.gradle.cache.internal.ProducerGuard$AdaptiveProducerGuard.guardByKey(Object, Factory) ProducerGuard.java:97
	org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor.getResource(ExternalResourceName, String, CacheAwareExternalResourceAccessor$ResourceFileStore, LocallyAvailableResourceCandidates) DefaultCacheAwareExternalResourceAccessor.java:82
	org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver.downloadByCoords(List, ModuleComponentArtifactMetadata, ResourceAwareResolveResult) DefaultExternalResourceArtifactResolver.java:138
	org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver.downloadStaticResource(List, ModuleComponentArtifactMetadata, ResourceAwareResolveResult) DefaultExternalResourceArtifactResolver.java:98
	org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver.resolveArtifact(ModuleComponentArtifactMetadata, ResourceAwareResolveResult) DefaultExternalResourceArtifactResolver.java:65
	org.gradle.api.internal.artifacts.repositories.metadata.AbstractRepositoryMetadataSource.parseMetaDataFromArtifact(String, ComponentResolvers, ModuleComponentIdentifier, ExternalResourceArtifactResolver, ResourceAwareResolveResult) AbstractRepositoryMetadataSource.java:69
	org.gradle.api.internal.artifacts.repositories.metadata.AbstractRepositoryMetadataSource.create(String, ComponentResolvers, ModuleComponentIdentifier, ComponentOverrideMetadata, ExternalResourceArtifactResolver, BuildableModuleComponentMetaDataResolveResult) AbstractRepositoryMetadataSource.java:59
	org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver.resolveStaticDependency(ModuleComponentIdentifier, ComponentOverrideMetadata, BuildableModuleComponentMetaDataResolveResult, ExternalResourceArtifactResolver) ExternalResourceResolver.java:199
	org.gradle.api.internal.artifacts.repositories.resolver.MavenResolver.doResolveComponentMetaData(ModuleComponentIdentifier, ComponentOverrideMetadata, BuildableModuleComponentMetaDataResolveResult) MavenResolver.java:117
	org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver$RemoteRepositoryAccess.resolveComponentMetaData(ModuleComponentIdentifier, ComponentOverrideMetadata, BuildableModuleComponentMetaDataResolveResult) ExternalResourceResolver.java:400
	org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository$ResolveAndCacheRepositoryAccess.resolveComponentMetaData(ModuleComponentIdentifier, ComponentOverrideMetadata, BuildableModuleComponentMetaDataResolveResult) CachingModuleComponentRepository.java:381
	org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.resolveComponentMetaData(ModuleComponentIdentifier, ComponentOverrideMetadata, BuildableModuleComponentMetaDataResolveResult) ErrorHandlingModuleComponentRepository.java:136
	org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ComponentMetaDataResolveState.process(ModuleComponentRepositoryAccess) ComponentMetaDataResolveState.java:66
	org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ComponentMetaDataResolveState.resolve() ComponentMetaDataResolveState.java:58
	org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.findBestMatch(LinkedList, Collection, Collection) RepositoryChainComponentMetaDataResolver.java:138
	org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.findBestMatch(List, Collection) RepositoryChainComponentMetaDataResolver.java:119
	org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolveModule(ModuleComponentIdentifier, ComponentOverrideMetadata, BuildableComponentResolveResult) RepositoryChainComponentMetaDataResolver.java:92
	org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolve(ComponentIdentifier, ComponentOverrideMetadata, BuildableComponentResolveResult) RepositoryChainComponentMetaDataResolver.java:63
	org.gradle.api.internal.artifacts.ivyservice.resolveengine.ComponentResolversChain$ComponentMetaDataResolverChain.resolve(ComponentIdentifier, ComponentOverrideMetadata, BuildableComponentResolveResult) ComponentResolversChain.java:93
	org.gradle.api.internal.artifacts.ivyservice.clientmodule.ClientModuleResolver.resolve(ComponentIdentifier, ComponentOverrideMetadata, BuildableComponentResolveResult) ClientModuleResolver.java:60
	org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.ComponentState.resolve() ComponentState.java:163
	org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.ComponentState.getMetaData() ComponentState.java:174
	org.gradle.api.internal.artifacts.ivyservice.resolveengine.ProjectDependencyForcingResolver.select(ConflictResolverDetails) ProjectDependencyForcingResolver.java:42
	org.gradle.api.internal.artifacts.ivyservice.resolveengine.VersionSelectionReasonResolver.select(ConflictResolverDetails) VersionSelectionReasonResolver.java:31
	org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.conflicts.CompositeConflictResolver.select(ConflictResolverDetails) CompositeConflictResolver.java:36
	org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.conflicts.DefaultConflictHandler.resolveNextConflict(Action) DefaultConflictHandler.java:72
	org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.traverseGraph(ResolveState) DependencyGraphBuilder.java:143
	org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.resolve(ResolveContext, DependencyGraphVisitor) DependencyGraphBuilder.java:111

**Comment by DanielThomas** [comment] 2018-08-10 23:33
@oehme believe this is being enabled by default for Gradle 5, in which case wanted to ping you to make sure you don't miss this :)

**Comment by oehme** [comment] 2018-08-11 09:58
@gradle/dependency-management This one is for you :)

**Comment by bigdaz** [comment] 2018-08-11 15:48
We won't be switching `preferProjectModules` on by default in Gradle 5.0.

**Comment by bigdaz** [comment] 2018-08-13 18:44
Coincidentally, it looks like this was fixed in Gradle 4.8. https://github.com/gradle/gradle/commit/e52241ffff66f3357f81c3766a2730326eba2996

I haven't confirmed this addresses the underlying issue of serial component metadata resolution, but it should certainly fix the cause mentioned above.

I'll close this issue for now: @DanielThomas let me know if you still have concerns.

**Closed by bigdaz** 2018-08-13 18:44 UTC
Labels: a:performance-issue, from:contributor, in:dependency-management

**Comment by DanielThomas** [comment] 2018-08-13 18:59
Ah, prefect. Thanks @bigdaz!
