### ISSUE TITLE
type-safe project dependencies do not work inside allprojects/subprojects

### ISSUE THREAD

**Issue by wolfseifert** [gradle/gradle#17185] opened 2021-05-13 16:11 UTC
settings.gradle.kts

```
enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

include("a")`
```

build.gradle.kts

```
plugins {
  `java-library`
}

allprojects {
  apply(plugin = "java-library")
  dependencies {
    api(project(":a"))
    api(projects.a) // Extension with name 'projects' does not exist.
  }
}
```
Extension with name 'projects' does not exist. Currently registered extension names: [ext, defaultArtifacts, sourceSets, reporting, java, javaToolchains]

**Comment by vlsi** [comment] 2021-05-14 07:23
This is a duplicate of #16856

**Closed** 2021-05-14 09:58 UTC
