### ISSUE TITLE
Build fails when using multiple repositories and the 1st repository times out

### ISSUE THREAD

**Issue by darren-rose** [gradle/gradle#7965] opened 2018-12-07 11:04 UTC
If I list multiple maven repositories and the 1st one tmeouts, the build fails

### Expected Behavior

I  would like the 2nd and 3rd repositories to be tried

### Current Behavior

The build fails, but does list the multiple repositores

### Context

Unable to build, have to comment out repositories that timeout

### Your Environment

 * Build scan URL:

**Comment by ljacomet** [comment] 2018-12-07 11:10
This is a design decision to give confidence in build reproducibility. If Gradle was to ignore these timeouts, someone else building the project could end up with different binary artifacts if there was a difference in them between two repositories.

Can't you do something about these timeouts at the source? Did you try with having a mirror repository in your organization that would protect you from these?

**Comment by darren-rose** [comment] 2018-12-07 11:15
thanks, it is the mirrors that are timing out :-)

**Comment by darren-rose** [comment] 2018-12-07 15:32
How does 5.0 place with Lombok?

**Comment by ljacomet** [comment] 2019-03-14 10:00
It should work fine ... given the time since 5.0 was made available 😉 

Closing as the reported behavior will not be changed.

**Closed by ljacomet** 2019-03-14 10:00 UTC
Labels: in:dependency-management
