### ISSUE TITLE
Change in project name should not affect project path

### ISSUE THREAD

**Issue by bcmedeiros** [gradle/gradle#23848] opened 2023-02-09 15:13 UTC
### Expected Behavior
Changing a project name in the `settings.gradle[.kts]` do not affect its path.

### Current Behavior
Changing a project name in the `settings.gradle[.kts]` currently does affect the last component of the project path, which is very not intuitive.

### Context
I work daily in a repository with a relatively big Gradle tree of projects, and we have many modules with the same last segment of the path name (E.g `:feature1:api` and `:feature2:api`), and that has been a nightmare to deal with due to https://github.com/gradle/gradle/issues/847.
In other to work around 847, we decided to assign a different name to projects that have the same last segment so they are unique and, to our surprise, changing the name of the project also affects its path, which is very counter-intuitive since that has not moved at all, not even logically (we are just setting the name to a longer unique one).

So, consider you have the following on your `settings.gradle.kts`:
```
include(":a:lib")
```

If you try to do:
```
include(":a:lib"); project(":a:lib").name = "a-lib"
```
then all the modules with `implementation(project(":a:lib"))` fail with:
```
Project with path ':a:lib' could not be found in project ':b:lib'.
```

### Steps to Reproduce 
Consider the following `settings.gradle.kts`:
```
include(":a:lib")
val aLibProject = project(":a:lib")
aLibProject.name = "a-lib"
println(aLibProject.path)

val aLibProjectAgain = project(":a:lib")
println(aLibProjectAgain?.path)
```

You'll see the following output:
```
:a:a-lib

FAILURE: Build failed with an exception.

* Where:
Settings file '/home/.../.../multi-module-project/settings.gradle.kts' line: 15

* What went wrong:
Project with path ':a:lib' could not be found.
```

> Project with path `:a:lib` could not be found.

This is really unexpected, since we really do not changed the path at all, the project is in the same place, and the same `project(":a:lib")` that worked a few lines above does not work anymore.

### Your Environment
All Gradle versions that I tested, in all environments. Most of the tests were done with Gradle 7.6.

**Comment by jbartok** [comment] 2023-02-20 09:53
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

In this case, the "path" used by Gradle is not the same as the "path on disk". This works as expected, even if you find it surprising because what you have in what you call the "path" is the project name and not the directory name on disk. See here: https://docs.gradle.org/current/userguide/fine_tuning_project_layout.html#sub:modifying_element_of_the_project_tree

So what you most likely want to change is the `projectDir` property.

**Comment by bcmedeiros** [comment] 2023-02-20 16:40
> So what you most likely want to change is the projectDir property.

@jbartok it is not, have you seen the linked issue and my PR? 

> In this case, the "path" used by Gradle is not the same as the "path on disk"

I know path is not path on disk, but that's how Gradle naturally finds your project.

I provided steps to reproduce the issue, and to me it's pretty clear that this behavior is far from expected. Not sure why my issue as closed as a question without even trying to see my point here and look at the related issue and PR.

**Comment by eskatos** [comment] 2023-02-22 10:11
We closed this as a question because this is the way it works.
You cannot disconnect the project path from the project name.
See: https://docs.gradle.org/current/userguide/fine_tuning_project_layout.html#sub:building_the_tree

We looked at your PR. We just sent it to CI expecting it will break things. We have no intention to merge it.
Although at some point we need to improve what you can do with project path and name (#847).

This is the intended behavior and there’s no plan to change it. This issue will be closed.

**Closed by eskatos** 2023-02-22 10:11 UTC
Labels: a:bug, to-triage

**Comment by bcmedeiros** [comment] 2023-02-26 09:31
> We looked at your PR. We just sent it to CI expecting it will break things. 

Well, it didn't. I tested it locally before submitting. I was planning to add more tests in the near future, but with such a hard push back, I'm not sure it's even worth doing anymore.

> You cannot disconnect the project path from the project name.

Why is that? If that is such an important thing, how come we have zero tests asserting this behavior? How come my PR doesn't cause any other test to break?

> See: https://docs.gradle.org/current/userguide/fine_tuning_project_layout.html#sub:building_the_tree

I read this before investigating this issue, I don't see how merging my PR would go against anything written in this page, nor how could merging my PR would break any commitments stated in the docs (please point me to that if I'm missing something here).

> We closed this as a question because this is the way it works.

Every undesired side effect is always going to be "the way it works" until we think about it, re-asses the current design and improve how things are.

I really don't understand why such a hard push back and the rush to close the issue. The proposed change breaks no tests, breaks no commitment in the docs (that I have seen so far) and fixes the weird behavior described in this issue AND offers a great way to close https://github.com/gradle/gradle/issues/847 with minimal impact for the users.

I fear for the future of a project were ideas are rejected so hastily just because "it's how it works now", I really hope that is not the case for Gradle.

cc @eskatos

**Comment by bcmedeiros** [comment] 2023-02-28 15:15
I see some more tests were triggered in the PR and we have failures, so I'll check how I can reproduce those locally and fix them.
