### ISSUE TITLE
configureondemand causes build failure in multi module project with different group name

### ISSUE THREAD

**Issue by kojilin** [gradle/gradle#20377] opened 2022-04-06 00:34 UTC
Multi module project with different group name and `org.gradle.configureondemand=true` may cause
```
../gradlew bootRun
Configuration on demand is an incubating feature.
> Task :server:bootRunMainClassName FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':server:bootRunMainClassName'.
> Could not resolve all files for configuration ':server:runtimeClasspath'.
   > Could not find com.example.search:common:0.0.1-SNAPSHOT.
     Required by:
         project :server
         project :server > project :api
```
When running bootRun task of springboot plugin.
The search-common project and server project has different `group`.

### Expected Behavior
It works at gradle 7.3 but failed from 7.4

### Current Behavior
Failed to run bootRun task.

### Steps to Reproduce 
Sample project at https://github.com/kojilin/demo-issue
group name of server/console/main is `com.example.server`,search:common is `com.example.search `

```
➜  demo-public git:(main) ./gradlew :server:bootRun
Configuration on demand is an incubating feature.
> Task :server:bootRunMainClassName FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':server:bootRunMainClassName'.
> Could not resolve all files for configuration ':server:runtimeClasspath'.
   > Could not find com.example.search:common:0.0.1-SNAPSHOT.
     Required by:
         project :server
         project :server > project :api
```
Below 3 cases works

* run `./gradlew :console:run` works(application plugin)
* Change `org.gradle.configureondemand` to `false` works
* Using the same group name works

### Your Environment
Build scan URL: https://scans.gradle.com/s/vrgi7ncupnydi

**Comment by jbartok** [comment] 2022-04-08 09:51
I can confirm this as a regression in `7.4`, which also persists in `7.4.2`.

**Comment by tresat** [comment] 2022-04-19 11:59
So, after some investigation, we have a few findings to share.

1) The behavior changed after 7.3.  In 7.4+ when configure-on-demand is enabled, a parent project is always configured prior to configuring a project, whereas 7.3 would do this sometimes and not other times.  The current behavior is more predictable and reliable, but it will be a change for some projects.  In this reproducer, Gradle 7.4 configures the root project, then `search` then `search:common`, whereas 7.3 configures the root project, then `search:common` but skips search (which isn’t right).  We are thinking of this as a correction rather than a regression - but the distinction is slightly blurry here.  What's important is that you should expect the current behavior to remain.

2) Using the `subprojects` block like this causes projects to no longer be [decoupled](https://docs.gradle.org/current/userguide/multi_project_configuration_and_execution.html#sec:decoupled_projects).  Decoupled projects are a requirement when using configure-on-demand, and `subprojects` violates that requirement and is a feature that (eventually) we want to deprecate and remove.  If you instead set the group of each affected project within that project's `build.gradle` file directly (or by applying the same convention plugin to each) outside of a `subprojects` block, you can avoid many potential problems like this one.

3) There seems to be a bug in the [Spring Dependency Management Plugin](https://github.com/spring-gradle-plugins/dependency-management-plugin).  If you run the demo project here using the `--debug` flag to see fine grained logging, you can see in the lines that appear shortly after `Task :server:bootRunMainClassName FAILED` output like this:

```2022-04-18T17:33:03.332-0400 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder] Visiting configuration com.example.server:server:0.0.1-SNAPSHOT(detachedConfiguration48).
2022-04-18T17:33:03.332-0400 [DEBUG] [io.spring.gradle.dependencymanagement.internal.VersionConfiguringAction] Processing dependency 'com.example.server:api:0.0.1-SNAPSHOT'
2022-04-18T17:33:03.332-0400 [DEBUG] [io.spring.gradle.dependencymanagement.internal.VersionConfiguringAction] 'com.example.server:api:0.0.1-SNAPSHOT' is a local project dependency. Dependency management has not been applied
2022-04-18T17:33:03.332-0400 [DEBUG] [io.spring.gradle.dependencymanagement.internal.VersionConfiguringAction] Processing dependency 'com.example.search:common:0.0.1-SNAPSHOT'
2022-04-18T17:33:03.332-0400 [DEBUG] [io.spring.gradle.dependencymanagement.internal.DependencyManagementContainer] Found managed version '0.0.1-SNAPSHOT' for dependency 'com.example.search:common' in dependency management for configuration 'runtimeClasspath'
2022-04-18T17:33:03.332-0400 [DEBUG] [io.spring.gradle.dependencymanagement.internal.VersionConfiguringAction] Using version '0.0.1-SNAPSHOT' for dependency 'com.example.search:common:0.0.1-SNAPSHOT'
```

Look at the difference between processing the `api` dependency and the `search:common` dependency.  The plugin is **not** properly determining that `search:common` is a local project dependency.  The relevant code for the plugin is [here](https://github.com/spring-gradle-plugins/dependency-management-plugin/commit/07abeca82496b25190e45f7bada57051f81285fe).  The `if` statement on line 62 there should be coming up `true`, but it is not.  I don't know if the project name caching visible in the commit I've linked to is the ultimate cause or not - I quickly tested version `1.0.10.RELEASE` of this plugin, which was released prior to the change in this commit, and still observed the same behavior.

For some reason, the plugin is not understanding the late change to the projects' groups when the `bootRun` task tries to gather dependencies.  When I run through the debugger and inspect the values of the projects and the dependencies in their configurations in Gradle prior to this task running, the groups look correct.  We also experimented with locking the project's GAV, but further investigation revealed that to be unnecessary.

You may wish to open a bug with the Spring Dependency Management Plugin project and share this reproducer with them.  We're going to close this as "not a Gradle bug".  If you have any further information to provide, please comment and we will take note.

**Closed by tresat** 2022-04-19 11:59 UTC
Labels: a:regression, in:configure-on-demand
