### ISSUE TITLE
Jacoco testCoverageVerification task failing when using Gradle 8.7 but works in Gradle 8.6

### ISSUE THREAD

**Issue by boardbloke** [gradle/gradle#28884] opened 2024-04-19 10:34 UTC
### Current Behavior

I have a project that has a testCoverageVerification task that is enforcing a minimum coverage percentage for the tests in the project.

In Gradle 8.6 the project worked.  However if I make no change other than to upgrade the project to use Gradle 8.7 the  testCoverageVerification task fails.  

I alsosee errors such as:
[ant:jacocoReport] Classes in bundle 'XXX' do not match with execution data. For report generation the same class files must be used as at runtime.

which I'm guessing is the cause - however I don't understand why changing the Gradle version to 8.7 might do this. 

### Expected Behavior

The project should build successfully.  The testCoverageVerification  task should pass as the tests do cover the source to the required percentage

### Steps to Reproduce

[example.zip](https://github.com/gradle/gradle/files/15038996/example.zip)

The project is set up to run with Gradle 8.6 - and the tests pass and the jacoco code verification task executes successfully

If you change the wrapper to use Gradle 8.7 and re-run the jacoco code verification task complains aboutr the executable data being incorrect, and the verification task fails with a code coverage metric of 0.

### Gradle version

8.7

### Gradle version that used to work

8.6

### Your Environment (optional)

Running in WSL2 on Termurin 17

**Comment by ov7a** [comment] 2024-04-19 11:20
This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/28729

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

It's fixed in 8.8 release, and I confirmed that with the latest release nightly

**Closed by ov7a** 2024-04-19 11:20 UTC
Labels: a:regression, to-triage

**Comment by boardbloke** [comment] 2024-04-19 12:17
Thanks - I should have spotted that in the issues. My use case confirmed fixed in 8.8 release nightly - 8.8-20240418010200+0000
