### ISSUE TITLE
Gradle not able to filter tests in inner class using categories

### ISSUE THREAD

**Issue by bemnet4u** [gradle/gradle#2985] opened 2017-09-20 19:59 UTC
I have a test class that looks like this
```
@RunWith(Enclosed.class)
public classs OuterClass {

@Category(SomeCategory.class)
@RunWith(Parameterized.class)
public static class InnerClassOne{

        @Parameterized.Parameter
        public String currentTest = null;

        @Parameterized.Parameters(name = "{0}")
        public static List<String> getTests() {
            return getTests(SomeCategory.class);
        }

        @Test
        public void testMethod() {          
        }
    }

@Category(SomeOtherCategory.class)
@RunWith(Parameterized.class)
public static class InnerClassTwo{
        @Parameterized.Parameter
        public String currentTest = null;
        @Parameterized.Parameters(name = "{0}")
        public static List<String> getTests() {
            return getTests(SomeOtherCategory.class);
        }
        @Test
        public void testMethod() {          
        }
    }
}

```
Now when I try to run the test like gw test it is not able to filter the tests.

My gradle test task has something like this

```
useJUnit { JUnitOptions opts ->
                opts.includeCategories SomeOtherCategory
            }
```

### Expected Behavior
Able to filter tests based on categories even for nested classes. 

### Current Behavior
no test is run

### Steps to Reproduce (for bugs)
See above.

**Comment by oehme** [comment] 2017-09-22 14:13
I think we generally have problems with `@Enclosed`. See also https://github.com/gradle/gradle/issues/2320 and https://github.com/gradle/gradle/issues/2319

**Comment by oehme** [comment] 2018-03-20 08:37
Duplicate of https://github.com/gradle/gradle/issues/1153

**Closed by oehme** 2018-03-20 08:37 UTC
Labels: a:feature, from:contributor, in:testing
