### ISSUE TITLE
Build fails because task is executed to early

### ISSUE THREAD

**Issue by magicwerk** [gradle/gradle#20221] opened 2022-03-19 00:15 UTC
### Expected Behavior
Build should work as done in 7.3.3.

### Current Behavior
Build fails starting with 7.4

### Context
Running "gradle clean setup shadowJar" fails since 7.4:
> Task :MagicTest:ant-create-lib FAILED
FAILURE: Build failed with an exception.

Reason is that the task :MagicTest:ant-create-lib (which is part of shadowJar) is executed too early, i.e. before all tasks of "setup" are finished.

If I run "gradle clean setup shadowJar --dry-run", the tasks are however shown in the correct order
If I run "gradle clean setup", "gradle shadowJar" build succeds

### Steps to Reproduce 
Build "gradle clean setup shadowJar"

### Your Environment
https://scans.gradle.com/s/bjbqoqgoqnzts

**Comment by ljacomet** [comment] 2022-03-21 16:06
Thank you for your interest in Gradle.

This looks like a duplicate of #20062.

While we will look into the unexpected change, not that this can only happen because there is a missing task dependency in your build. So the recommendation is to figure out what's missing so that Gradle cannot run something in the wrong order.

**Closed by ljacomet** 2022-03-21 16:06 UTC
Labels: a:regression, closed:duplicate, in:scheduler
