### ISSUE TITLE
Cannot run main methods from IDEA 2019.2.x with Gradle 6.0

### ISSUE THREAD

**Issue by 120011676** [gradle/gradle#11371] opened 2019-11-14 11:31 UTC
### Expected Behavior

run success

### Current Behavior

run error

<img width="1666" alt="Screen Shot 2019-11-14 at 19 34 34" src="https://user-images.githubusercontent.com/1992933/68853829-cf30a200-0715-11ea-80f7-e86109f5910b.png">

```
19:17:57: Executing task 'T.main()'...

Starting Gradle Daemon...Connected to the target VM, address: '127.0.0.1:51443', transport: 'socket'
Gradle Daemon started in 2 s 993 ms

FAILURE: Build failed with an exception.

* Where:
Initialization script '/private/var/folders/y5/40rk614j5ssg014gkmj2p7sw0000gn/T/T_main__.gradle' line: 18

* What went wrong:
A problem occurred configuring project ':manager'.
> Could not create task ':manager:T.main()'.
   > Unnecessarily replacing a task that does not exist is not supported.  Use create() or register() directly instead.  You attempted to replace a task named 'T.main()', but there is no existing task with that name.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
Disconnected from the target VM, address: '127.0.0.1:51443', transport: 'socket'
19:18:11: Task execution finished 'T.main()'.
```

```
Unnecessarily replacing a task that does not exist is not supported.  Use create() or register() directly instead.  You attempted to replace a task named 'T.main()', but there is no existing task with that name.
```

### Context

fun error

### Steps to Reproduce 

gradle 6.0.0 Sub module
java 13
idea 2019.2.4

### Your Environment

Build scan URL:

**Comment by big-guy** [comment] 2019-11-15 22:27
This is coming from a long deprecated behavior that was finally made an error in Gradle 6.0. Unfortunately, we're not going to restore the old behavior, but we'll work with JetBrains to make this sort of thing work without requiring special handling on IDEA's side.

This is already fixed in IntelliJ IDEA 2019.3 (in beta now).  If you can upgrade to the 2019.3 EAP or beta, this should work there.

**Closed by big-guy** 2019-11-15 22:27 UTC
Labels: a:bug, affects-version:6.0, from:contributor

**Comment by 120011676** [comment] 2019-11-16 02:12
@big-guy All right, Roger

**Comment by 120011676** [comment] 2019-11-18 02:37
@big-guy Do you have this question IntelliJ idea URL? This affects the use of my project

**Comment by xinkunZ** [comment] 2020-01-18 16:15
Same  issue here
I'm already using in IDEA 2019.3.2RC,  but it can be reproduced
Do you guys have the IDEA issue track url of this question?

**Comment by 120011676** [comment] 2020-01-19 07:44
@xinkunZ Upgrade the latest version of idea

**Comment by SomeTroglodyte** [comment] 2020-04-25 13:47
Bug still present in latest stable Android Studio 3.6.3 as downloaded today.

**Comment by drumvas021** [comment] 2020-05-06 18:13
> Bug still present in latest stable Android Studio 3.6.3 as downloaded today.

me too.so what you doing?

**Comment by 120011676** [comment] 2020-05-07 05:33
upgrade idea

**Comment by PRASANTHRAJENDRAN** [comment] 2020-06-05 14:22
As of June 2020, I had this issue in version of IntelliJ Idea 2019.2.4, but after updating to the latest version (2020.1.2) the issue got resolved

**Comment by FrancYescO** [comment] 2020-06-14 22:21
i'm on 2020.1.2 on mac and still having this issue:
```
A problem occurred evaluating root project 'XXX'.
> Failed to apply plugin [id 'javafx-gradle-plugin']
   > Could not create task ':jfxJar'.
      > Unnecessarily replacing a task that does not exist is not supported.  Use create() or register() directly instead.  You attempted to replace a task named 'jfxJar', but there is no existing task with that name.

```

**Comment by Akmenah** [comment] 2020-07-07 02:29
I am using 2020.* And still have the same error while building my gluon project

**Comment by 120011676** [comment] 2020-07-07 06:01
upgrade gradle

**Comment by Akmenah** [comment] 2020-07-17 19:05
I did, but the error still there

**Comment by FrancYescO** [comment] 2020-07-17 19:19
For me the solution was to downgrade gradle to <6.0

**Comment by manishoo** [comment] 2020-09-21 19:41
I have this problem with the latest Android Studio and the latest gradle version

**Comment by OlivierGrenoble** [comment] 2020-09-29 06:43
I have the same problem. I have also downgraded gradle to workaround the issue. I'm now using Gradle 5.6.4 and Gradle Plugin 3.6.4

**Comment by magicliang** [comment] 2022-02-09 05:50
I have the same issue. 

My gradle-wrapper.properties is:

```properties
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.2-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

I am using Intellij Idea is IntelliJ IDEA 2021.3.1 (Community Edition).

While I tested my application with Spring boot 2.6.3 and `ch.vorburger.mariaDB4j:mariaDB4j-springboot:2.4.0`,  I couldn't terminate my application and get this error message finally:

> Execution failed for task ':biz-service-impl:DomainDrivenTransactionSysApplication.main()'.
> Build cancelled while executing task ':biz-service-impl:DomainDrivenTransactionSysApplication.main()'

> * Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by magicliang** [comment] 2022-02-09 05:51
> 

I wonder should I downgrade my gradle to some version under 6.0

**Comment by magicliang** [comment] 2022-02-09 07:00
actually the answer is:

preferences -> build/execution/deployment -> build tool -> Gradle -> build and run with gradle or IntelliJ IDEA

the default config is build and run with gradle, that's the root cause.

I wonder why Idea is designed like this.

**Comment by ramirojestrada** [comment] 2023-03-16 21:32
I'm having this same issue. I can't get it right
