### ISSUE TITLE
Dependency API's to access parent POMs and BOMs

### ISSUE THREAD

**Issue by uklance** [gradle/gradle#2809] opened 2017-08-29 08:06 UTC
I'd like a way to copy BOMs and parent POMs for a given `Configuration` to a local directory for offline use. I'd like the Gradle dependency API's to be enhanced to support obtaining information about the resolved BOMs and parent POMs

Perhaps `org.gradle.api.artifacts.result.ResolvedComponentResult.getAssociatedComponents()` or similar

### Expected Behavior

Given the following `pom.xml`, I should be able to use `com.sample:foo-jar:1.0` to obtain the parent POM `com.sample:foo-parent:1.0` and also the BOM `com.sample:foo-bom:1.0` via the Gradle API's without needing to parse the `pom.xml` myself. I'll ultimately want to copy the POMs to a local directory for offline use so I'd like access to the `java.io.File`

```xml
<project>
   <parent>
      <groupId>com.sample</groupId>
      <artifactId>foo-parent</artifactId>
      <version>1.0</version>
   </parent>
   <artifactId>foo-jar</artifactId>
   <packaging>jar</packaging>
   <dependencyManagement>
      <dependency>
         <groupId>com.sample</groupId>
         <artifactId>foo-bom</artifactId>
         <version>1.0</version>
         <scope>import</scope>
      </dependency>
   </dependencyManagement>
</project>
```

### Current Behavior

There is no way to obtain parent POMs and BOMs from the Gradle dependency API's as stated by @mark-vieira on [this forum post](https://discuss.gradle.org/t/artifactresolutionquery-to-access-parent-poms/23804)

### Context

Forum post [here](https://discuss.gradle.org/t/artifactresolutionquery-to-access-parent-poms/23804)
Failing test [here](https://github.com/uklance/gradle-dependency-export/blob/master/src/test/groovy/com/lazan/dependency/export/MavenDependencyExportTest.groovy#L69)

### Your Environment

Gradle 4.1

**Comment by eddumelendez** [comment] 2017-08-31 20:10
@uklance for `dependencyManagement` section in order to import `BOM` you can use [spring-gradle-plugins/dependency-management-plugin](https://github.com/spring-gradle-plugins/dependency-management-plugin)

**Comment by uklance** [comment] 2017-08-31 21:11
@eddumelendez I'm not sure you understand my requirement. I want to copy all maven artifacts referenced by a gradle build to a folder for offline use. If external dependencies have poms, parent poms and boms I need to copy those too (otherwise the offline copy won't be adequate to build offline)

**Comment by mark-vieira** [comment] 2017-08-31 21:56
@uklance In the mean time have you taken a look at the [IvyPot](https://github.com/ysb33r/ivypot-gradle-plugin) plugin as a possible solution to your use case?

**Comment by bigdaz** [comment] 2017-12-21 21:59
@uklance I know it's not as convenient, but have you tried using `ArtifactResolutionQuery` to access the raw Maven POM file, and then work from there?
```
def allComponentIds = resolutionResult.allComponents*.id
def artifacts = dependencies.createArtifactResolutionQuery()
            .forComponents(allComponentIds)
            .withArtifacts(MavenModule, MavenPomArtifact)
            .execute()
```

One option would be to extend this to allow parent POMs and BOMs to be included in the query result.

**Comment by uklance** [comment] 2017-12-21 22:12
Assuming extending the API to also return parent POMs and BOMs then this would work. 

Without the API extension I'd have to parse the xml manually and do all the parent & BOM logic (including property substitution)  myself which I want to avoid

**Comment by uklance** [comment] 2017-12-21 22:22
One solution with the current API is to integrate Maven's [Model Builder](https://maven.apache.org/ref/3.5.2/maven-model-builder/apidocs/org/apache/maven/model/building/ModelBuilder.html) with Gradle so that Maven does the parsing and Gradle does the artifact downloading. I've actually already done this once [here](https://github.com/uklance/gradle-maven-transform/blob/master/plugin/src/main/groovy/com/lazan/maven/transform/internal/ModelResolverImpl.java) but I think ultimately this information should be available in the Gradle APIs

**Comment by lukecwik** [comment] 2017-12-21 22:24
I'm interested in this as well since I tried out various solutions on how to make a Gradle build become offline. Ivypot was the best as it did seem to get the parent poms but it [didn't resolve the correct versions of artifacts](https://github.com/ysb33r/ivypot-gradle-plugin/issues/28).

**Comment by bigdaz** [comment] 2017-12-22 00:48
Replicating a repository isn't really something we aim to support out of the box with Gradle. 

However we understand that this is something a lot of users desire, so we would be happy to work with a contributor who wants to make this possible via the existing `ArtifactResolutionQuery` API. This API is setup to provide access to the raw metadata files use in resolution, whereas the `ResolutionResult` API provides access to the parsed/processed metadata.

(One thing to note: once you have the raw metadata files, you'll need to parse out the GAV in order to recreate the original repository layout).

@uklance is this something you'd like to work on? Unfortunately it's not going to be trivial because currently we don't keep any reference to the parent POM artifacts after we finish parsing.

**Comment by uklance** [comment] 2017-12-22 07:55
@bigdaz are you saying that any solution will require me to parse the xml and determine the GAV? I'd expect the ArtifactResolutionQuery to return the raw files mapped to their individual GAVs. As I've said I don't want to implement logic where version is inherited from <parent> or any property substitution logic. 

If that's impossible I think I'd prefer my idea of using the Maven model builder API. In that case I won't need any changes in Gradle. Not ideal but in my opinion better than duplicating maven logic

**Comment by bigdaz** [comment] 2017-12-22 16:30
> @bigdaz are you saying that any solution will require me to parse the xml and determine the GAV?

I'm saying that it could be possible to get the raw POM files, but in order to recreate a repository you'd need to know the `group` value for each, which isn't encoded in the file name.

**Comment by uklance** [comment] 2017-12-22 17:34
Hmm, I was hoping that each `java.io.File` would be mapped to a `ModuleComponentIdentifier` like other artifacts. Somewhere in Gradle the mapping from GAV to pom must exist? It would be bad for this mapping to be "lost" in the new API.

As I said, if I need to parse myself I would NOT use the new API.

**Comment by bigdaz** [comment] 2017-12-22 18:49
The problem is that Maven has a concept of a 'parent' relationship, and Gradle does not. Parent POMs and imported BOMs are not treated as separate components outside of the POM parsing engine.

So while the parent POM has a separate GAV, in Gradle the parent POM has no separate `ModuleComponentIdentifier`. The change I suggested would make it available as an additional artifact for the child component, but not as a separate component.

It seems like your best bet might be a custom solution, or to work with the author of [IvyPot](https://github.com/ysb33r/ivypot-gradle-plugin) to come up with something that addresses your needs.

**Comment by uklance** [comment] 2017-12-22 20:37
Yes, obviously there's an impedence mismatch between the Maven model and the Gradle model. I'm sure Ivy has similar issues.

But somewhere in the belly of Gradle it understands poms and BOMs. If I could hook into that, perhaps by passing a custom callback/event handler that would be great.

If not I'll use my Maven model builder API / gradle integration

**Comment by bigdaz** [comment] 2017-12-22 21:16
The understanding of parent POMs is buried in the POM parser: https://github.com/gradle/gradle/blob/ee71b1bc53311c486cc531452b0e1cea73c8f355/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/parser/GradlePomModuleDescriptorParser.java#L105-L114

The `parsePomForSelector` method is doing the work of downloading and parsing the parent POM file.

**Comment by uklance** [comment] 2017-12-22 22:30
Fair enough, there's also the concept of BOMs. You know the code better than me. If it's not simple to customise for maven whilst staying generic I totally understand.

I'll do the ModelBuilder thing in a handful of lines of code

**Comment by bigdaz** [comment] 2017-12-23 18:47
Yep, BOMs (as defined by `<scope>import</scope>`) are handled through the same `parsePomForSelector` in the parser. They are not present in the dependency tree at all.

I'm going to close this issue for now since we don't have any plans to work on this. If anyone is interested in contributing the feature, feel free to comment here and we'll re-open the issue.

**Closed by bigdaz** 2017-12-23 18:47 UTC
Labels: a:feature, from:contributor, in:dependency-management

**Comment by uklance** [comment] 2017-12-25 15:33
For the benefit of anyone wanting to get these artifacts themselves I solved my issue using the [Maven Model Builder API](https://maven.apache.org/ref/3.5.2/maven-model-builder/apidocs/org/apache/maven/model/building/ModelBuilder.html)

See https://github.com/uklance/gradle-dependency-export/commit/c835642d28ab5e6c0cc9f4f388fb4939f637f27d

**Comment by sschuberth** [comment] 2023-03-23 21:24
@bigdaz, has there been any update until now, i.e. in the direction to extend `createArtifactResolutionQuery().withArtifacts()` with artifact class types for parent POMs and BOMs?

**Comment by Vampire** [comment] 2023-03-25 14:44
Here an example on how to traverse a POM including its ancestor POMs with the current API:
```kts
val checkForJdkActivatedProfiles by tasks.registering {
    doLast {
        val pomReader = MavenXpp3Reader()

        fun collectAncestorPoms(pom: ResolvedArtifactResult, result: MutableList<ResolvedArtifactResult>) {
            val parent = FileReader(pom.file)
                .use { pomReader.read(it) }
                .parent
            if (parent != null) {
                val parentPom = dependencies
                    .createArtifactResolutionQuery()
                    .forModule(parent.groupId, parent.artifactId, parent.version)
                    .withArtifacts(MavenModule::class.java, MavenPomArtifact::class.java)
                    .execute()
                    .resolvedComponents
                    .asSequence()
                    .flatMap { it.getArtifacts(MavenPomArtifact::class.java).asSequence() }
                    .filterIsInstance<ResolvedArtifactResult>()
                    .single()
                result.add(parentPom)
                collectAncestorPoms(parentPom, result)
            }
        }

        dependencies
            .createArtifactResolutionQuery()
            .forComponents(configurations.filter { it.isCanBeResolved }.flatMap { configuration ->
                configuration.incoming.resolutionResult.allDependencies.mapNotNull {
                    (it as? ResolvedDependencyResult)?.selected?.id
                }
            }.distinct())
            .withArtifacts(MavenModule::class.java, MavenPomArtifact::class.java)
            .execute()
            .resolvedComponents
            .asSequence()
            .flatMap { it.getArtifacts(MavenPomArtifact::class.java).asSequence() }
            .filterIsInstance<ResolvedArtifactResult>()
            .map { pom ->
                val ancestorPoms = mutableListOf<ResolvedArtifactResult>()
                collectAncestorPoms(pom, ancestorPoms)
                Pair(pom, ancestorPoms)
            }
            .forEach { (bottomPom, ancestorPoms) ->
                sequenceOf(bottomPom, *ancestorPoms.toTypedArray()).forEach { pom ->
                    FileReader(pom.file)
                        .use { pomReader.read(it) }
                        .profiles
                        .forEach { profile ->
                            if ((profile.activation?.jdk != null) && (!profile.dependencies.isNullOrEmpty())) {
                                println("jdk activated Maven profile with dependencies found in ${pom.id}")
                                if (pom != bottomPom) {
                                    println("ancestor of dependency ${bottomPom.id}")
                                }
                            }
                        }
                }
            }
    }
}
```
