### ISSUE TITLE
Stubbed API class breaks when extending a non-public abstract class

### ISSUE THREAD

**Issue by ThiporKong** [gradle/gradle#928] opened 2016-11-25 17:59 UTC
If my API exposes a class `A2` which inherits from a _non-public_ and _abstract_ class `A1`, it won't be possible to compile against `A2`. This should also work if `A1` or `A2` are inner classes.

### Steps to Reproduce (for bugs)
```gradle
plugins {
    id 'jvm-component'
    id 'java-lang'
}

model {
    components {
        def aSrc = Files.createTempDirectory("a-src").toFile()
        new File(aSrc, 'A1.java').text = 'abstract class A1 {}'
        new File(aSrc, 'A2.java').text = 'public class A2 extends A1 {}'

        def bSrc = Files.createTempDirectory("b-src").toFile()
        new File(bSrc, 'B.java').text = 'public class B extends A2 {}'

        a(JvmLibrarySpec) {
            sources.java.source.srcDir aSrc
        }
        b(JvmLibrarySpec) {
            sources.java.source.srcDir bSrc
            dependencies.library 'a'
        }
    }
}
```

yields

```
C:\Users\tk09\AppData\Local\Temp\b-src5834016254609490397\B.java:1: error: cannot access A1
public class B extends A2 {}
       ^
  class file for A1 not found
1 error
```

### Your Environment
Gradle 3.2.1, JDK 1.8

**Comment by melix** [comment] 2016-11-25 18:16
I think this is expected. If you have:

```
package internal;
abstract class A1 {
   public void foo() { }
}

package api;
public class A2 extends A1 {
   void bar() { }
}
```

and a consumer like you defined:

```
package consumer;

class B extends A2 {
   public void baz() { bar() }
}
```

then you are leaking private classes into your public API. This is exactly what this strong encapsulation enforces: you cannot leak internal types. The reason is simple. Since `A1` defines a method `foo` which is public, then A2 is allowed to see it (and all subclasses would also see public methods of `A1`) so A2 can call it, but `B` can do it too. Imagine that you later decide that this was internal details, and that you want to introduce a superclass to `A1`, say `ABase` and move the method `foo` from `A1` to `ABase`. Then you broke the binary compatibility of `B`. This is precisely what strong encapsulation must prevent. There are lots of other examples why you shouldn't do this. For this specific use case you might think that using `protected` in `A1` would have been enough, but that's special case and there's no general rule that would allow us to expose `A1` without leaking it.

**Comment by ThiporKong** [comment] 2016-11-26 09:34
For new code, I'd agree with imposing this kind of design restrictions.

But if you want to port lots of -- language-wise perfectly valid! -- legacy code to the Software model, you'd need at least a flag to relax this restriction.

**Comment by astellingwerf** [comment] 2016-11-27 19:34
This appears to be another duplicate of your own #925 and my #819. @melix, can you have a look at #848.

**Comment by eriwen** [comment] 2016-11-28 16:57
Closing given all of the previous information.

**Closed by eriwen** 2016-11-28 16:57 UTC
