### ISSUE TITLE
dependency substitution api doesn't seem work so well with platform

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#15181] opened 2020-11-16 13:41 UTC
given

```kotlin
dependencies {
  implementation(platform("org.springframework.boot:spring-boot-starter-parent:2.4.+"))
  implementation("org.springframework.boot:spring-boot-starter-web")
}
```
and I want to replace logging which is a dependency of web, with log4j2.

I can do this 
```kotlin
configurations.all {
  resolutionStrategy.dependencySubstitution {
     substitute(module("org.springframework.boot:spring-boot-starter-logging:2.4.0")
       .using(module("org.springframework.boot:spring-boot-starter-log4j2:2.4.0")
  }
}
```

this has the disadvantage that it would only match 2.4.0 with 2.4.0, so as soon as I upgrade spring boot, I have to remember to update this code.

I can also do this, which fixes the problem for this particular use case

```kotlin
configurations.all {
  resolutionStrategy.dependencySubstitution.all {
    requested.let {
      if (it is ModuleComponentSelector && it.module == "spring-boot-starter-logging") {
        useTarget("org.springframework.boot:spring-boot-starter-log4j2:${it.version}", "Use Log4j2 instead of Logback")
      }
    }
  }
}
```
this only fixes the issue if they have the same version, but imagine you're replacing `javax.persistence-api` with `jakarta.persistence-api` then I have a version mismatch. In version 2.4 of spring boot bom both are managed, but they have different version strings.

What I would like to be able to do is this, and just let the final version be resolved by the platform.

```kotlin
configurations.all {
  resolutionStrategy.dependencySubstitution {
     substitute(module("org.springframework.boot:spring-boot-starter-logging")
       .using(module("org.springframework.boot:spring-boot-starter-log4j2")
  }
}
```

would be good to allow ... resolution pattern matching?

```kotlin
configurations.all {
  resolutionStrategy.dependencySubstitution {
     substitute(module("org.springframework.boot:spring-boot-starter-logging:2.4.+")
       .using(module("org.springframework.boot:spring-boot-starter-log4j2")
  }
}
```
which would stop matching with 2.5.0, which might be good if you wanted to see if a problem no longer existed.

I'm kinda certain there's a way to do this, but doesn't seem to be a friendly API.

**Comment by jvandort** [comment] 2023-06-13 16:54
This seem like useful functionality to have

**Comment by jbartok** [comment] 2023-06-26 08:46
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before it gets implemented.

**Comment by jvandort** [comment] 2023-11-13 16:06
This is a duplicate of https://github.com/gradle/gradle/issues/15181

**Closed by jvandort** 2023-11-13 16:06 UTC
Labels: a:feature, closed:duplicate, in:dependency-declarations
