### ISSUE TITLE
add a gradle up command

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#15176] opened 2020-11-16 05:38 UTC
add this

```
gradle up <package>
-A --all
```
with no argument it would update all the dependencies of the current project

`gradle up org.springframework:spring-core`  which would be the same as `gradle dependencies --write-locks`, except maybe it would not output all the dependency info.

`-A` would update all multi/composite projects 

`gradle up org.springframework*` would update all spring framework, spring boot, etc dependencies.

`gradle up org.springframework.boot:spring-boot-starter-parent@2.3.1` would set the package lock to explicitly 2.3.1

`gradle up developmentOnly:org.springframework.boot:spring-boot-starter-parent@2.3.1` would set the package lock to explicitly 2.3.1 for only the developmentOnly scope 

inspired by https://yarnpkg.com/cli/up

I don't expect this to update the gradle.build files because they're code, though it should probably error if you try to update outside of the version range.

**Comment by melix** [comment] 2020-11-18 07:59
Closing as duplicate of #1318

**Closed by melix** 2020-11-18 07:59 UTC
Labels: @jvm, a:feature, from:contributor, in:dependency-management
