### ISSUE TITLE
Recommend included builds as the home for build logic

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#14044] opened 2020-08-07 01:57 UTC
When organizing build logic, it should be placed in included builds. In the simplest cases, buildSrc should be used. Our documentation should reflect that recommendation consistently. buildSrc should be treated as if it were an included build, even if it can do extra things.

- Update all documentation to refer to buildSrc as an included build
- Remove "bad practices" from documentation such as referring to classes from buildSrc without applying a plugin
- Document discouraged practices or behavior we will want to deprecate
- Add/update documentation around using included builds for shared build logic
    - Need to have at least one sample where build logic is shared between buildSrc and root build
- Check Gradle guides for bad practices/bad advice:
    - [ ] designing-gradle-plugins
    - [ ] implementing-gradle-plugins
    - [ ] migrating-build-logic-from-groovy-to-kotlin
    - [ ] performance
    - [ ] publishing-plugins-to-gradle-plugin-portal
    - [ ] using-build-cache
    - [ ] using-the-worker-api

**Comment by jjohannes** [comment] 2021-04-14 06:21
The guides have now been integrated into the user manual, and their snippets have already been updated.

Let's track this as part of #15326 until we do more concrete work here. Closing this as duplicate of  #15326.

**Closed by jjohannes** 2021-04-14 06:21 UTC
Labels: @idiomatic
