### ISSUE TITLE
Add resolveAllDependencies Gradle task

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#19081] opened 2021-11-23 00:20 UTC
Gradle build itself has a [resolveAllDependencies task](https://github.com/gradle/gradle/blob/master/build-logic/root-build/src/main/kotlin/gradlebuild.warmup-ec2.gradle.kts#L19) that is helpful for validating that all the dependencies resolve correctly and for bootstrapping dependency verification without running the full build. It would be great to see this task be built into Gradle.

### Expected Behavior
./gradlew resolveAllDependencies should just work

### Current Behavior
resolveAllDependencies task doesnt exist

### Context
It is helpful for validating that all the dependencies resolve correctly and for bootstrapping dependency verification without running the full build

**Comment by grossws** [comment] 2021-11-24 23:22
It could easily be done in plugin. Simple task that will just resolve all configurations.

But I agree that it's useful to have something like this by default for e.g. air-gapped scenario.

**Comment by jbartok** [comment] 2023-09-25 08:51
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team, but this area of Gradle is currently not in focus. It might take a while before it gets implemented.

***

For this to work, Gradle would need an entry point where plugin authors could register the way that resolvable configurations should be resolved. In Android, for example, a number of resolvable configurations can only be resolved with the right artifact view.

**Comment by ljacomet** [comment] 2023-09-25 08:53
Note that dependency locking could also benefit from this

**Comment by big-guy** [comment] 2024-01-16 17:52
I don't think we should have a task that "resolves everything", but we certainly need to handle these scenarios:

- Generating a cache directory to reuse for dependency artifacts offline
- Generating lock files
- Generating dependency verification reports

**Comment by liutikas** [comment] 2024-01-16 19:36
Another scenario that we have in our project is validating licenses of all dependencies (similar to ones mentioned, but slightly different action when resolved)

**Comment by xenoterracide** [comment] 2024-01-16 20:25
> I don't think we should have a task that "resolves everything", but we certainly need to handle these scenarios:

I mean resolves everthing that can be put in `lockfile`s. If I say lock the plugins, I mean lock any 3rd party dependency the plugin might use (given my configuration). There's no way to do that, because there's no API for them to provide that information.

**Comment by xenoterracide** [comment] 2024-01-16 20:26
> Generating dependency verification reports

what does that mean?

> Generating a cache directory to reuse for dependency artifacts offline

there already is... if you download an artifact it goes into a cache.

**Comment by cobexer** [comment] 2024-01-25 13:50
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #17101

Please add your use case and 👍 to that issue.

**Closed by cobexer** 2024-01-25 13:50 UTC
Labels: a:feature, in:dependency-locking, in:dependency-resolution, to-triage, in:dependency-verification
