### ISSUE TITLE
Java 21 PATH not used in exec

### ISSUE THREAD

**Issue by MrPlow442** [gradle/gradle#28300] opened 2024-02-29 15:05 UTC
### Current Behavior

Using Temurin JDK v21.0.2, running a build which contains an exec call or using a plugin which calls exec for a command which is in the $PATH, i.e. 'docker' or 'aws' will fail with 
`org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'docker''`
if the full path to the command is specified i.e. `/usr/local/bin/docker` then the command works but that is sometimes not possible to configure for plugins. On Temurin JDK 20.0.2 and earlier PATH will be loaded properly so commands can be used without the need for specifying the full path

### Expected Behavior

System $PATH should be respected and commands should work without the need for specifying the full path like they are in earlier JDK versions

### Steps to Reproduce

Install Temurin JDK 21.0.2
- Add an exec task which uses a command which is in your $PATH i.e.
```
task testExec() {
    exec {
        executable "docker"
        args "ps"
    }
}
```
- Run it
- You should get an exception that program `docker` cannot be found in the current working directory
- Change the executable to it's full path i.e. `/usr/local/bin/docker` and run it again
- This time it will work as intended

### Gradle version

8.6

### Gradle version that used to work

8.6 but with an older JDK

### Your Environment (optional)

Mac OS 14.3 (23D56)
Temurin JDK 21.0.2

**Comment by ov7a** [comment] 2024-03-01 12:58
Sorry, I cannot reproduce this.
```
 % gradle --version

------------------------------------------------------------
Gradle 8.6
------------------------------------------------------------

Build time:   2024-02-02 16:47:16 UTC
Revision:     d55c486870a0dc6f6278f53d21381396d0741c6e

Kotlin:       1.9.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          21.0.2 (Eclipse Adoptium 21.0.2+13-LTS)
OS:           Mac OS X 14.3.1 aarch64
```
```% gradle testExec   

> Configure project :
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

BUILD SUCCESSFUL in 334ms
```

Can you provide more details on your environment?
You can leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer) to reproduce the issue with GitHub Actions.

**Comment by ov7a** [comment] 2024-03-04 14:52
> I'm not sure that I can replicate the environment completely using the reproducer template.

Well, I think that's the problem - if it's purely environmental, it's unclear if and how it should be fixed in Gradle.

Can you try standard commands like `ls` instead of `docker` to ensure that it is not a problem with your docker installation? 
Can you verify that your java20 and java21 installations are identical in terms of method of installation?

**Comment by MrPlow442** [comment] 2024-03-04 15:29
standard commands such as `ls` work without the need to specify a full path to the executable.
Java 21 is installed in the same way as Java 20, i.e.

```
brew install --cask temurin21
jenv add /Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home/
```
But this issue is not docker specific and doesn't only happen on my environment.
There is an issue open in `docker-compose-plugin` for gradle with the workaround for this exact issue: https://github.com/avast/gradle-docker-compose-plugin/issues/435 
The person describing the issue has a different docker setup but the same issue.

**Comment by ov7a** [comment] 2024-03-05 08:54
A-ha.
Can you try running with `--no-daemon` as suggested [here](https://github.com/gradle/gradle/issues/26453#issuecomment-1756225541)?

In #26453, similar symptoms are described. If your case is identical, then it's a duplicate of
* https://github.com/gradle/gradle/issues/10483

**Comment by ov7a** [comment] 2024-03-05 08:55
And there is already a [comment](https://github.com/gradle/gradle/issues/10483#issuecomment-1960432723) describing your case. Closing as a duplicate then.

**Closed by ov7a** 2024-03-05 08:55 UTC
Labels: a:bug, to-triage
