### ISSUE TITLE
Running included build task with `--rerun` fails

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#28666] opened 2024-04-03 05:20 UTC
### Current Behavior

If an included composite build is used as a plugin in root build, running `<includedBuildTaskName> --rerun` fails with 

```
Cannot call TaskOutputs.upToDateWhen(Spec) on task ':build-logic:compileJava' after task has started execution.
```

See the reproducer below.

### Expected Behavior

No failure.

### Context (optional)

In short, `--rerun` configures the tasks in root project configuration phase, but because we requires the included `build-logic` as plugin, `:build-logic:compileJava` tasks finishes before the root project configuration phase - so we're trying to configure a task that already finishes execution.

### Steps to Reproduce

[issue-4163.zip](https://github.com/gradle/gradle/files/14847082/issue-4163.zip)

```
$ ./gradlew build-logic:compileJava --rerun

FAILURE: Build failed with an exception.

* What went wrong:
Cannot call TaskOutputs.upToDateWhen(Spec) on task ':build-logic:compileJava' after task has started execution.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 384ms
5 actionable tasks: 1 executed, 4 up-to-date
```

### Gradle version

8.8

**Comment by ov7a** [comment] 2024-04-04 12:38
This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/23886

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

**Closed as not planned by ov7a** 2024-04-04 12:38 UTC
Labels: a:bug, closed:duplicate
