### ISSUE TITLE
Creating new cache for metadata-2.23/artifact-at-url

### ISSUE THREAD

**Issue by youyuo** [gradle/gradle#4103] opened 2018-01-22 08:59 UTC
When I use Jenkins build my project，it get stuck in blew log。
log:
Creating new cache for metadata-2.23/module-artifacts, path /mnt/sdb/jenkins/.gradle/caches/modules-2/metadata-2.23/module-artifacts.bin, access org.gradle.cache.internal.DefaultCacheAccess@d694845
Using incremental javac compilation for :xx_core debug.
Incremental java compilation is an incubating feature.
Not using incremental javac compilation for :xx_core debugUnitTest.
Using incremental javac compilation for :xx_core release.
Not using incremental javac compilation for :xx_core releaseUnitTest.
Not using incremental javac compilation for :xx_core debugAndroidTest.
Creating new cache for metadata-2.23/artifact-at-url, path /mnt/sdb/jenkins/.gradle/caches/modules-2/metadata-2.23/artifact-at-url.bin, access org.gradle.cache.internal.DefaultCacheAccess@d694845

**Comment by blindpirate** [comment] 2018-01-24 06:00
More information please.

- Your OS/Gradle/JDK version?
- What are you doing when encountering this issue? Could you describe more detail?

**Comment by youyuo** [comment] 2018-01-26 13:39
os:Linux(amd64)
gradle:3.3
jdk:1.7
First I depend on a aar through maven server，then for test I depend on this aar local, and it will still pull aar from server and it block。

more detail log:
Creating configuration debugCompile
Creating configuration debugPublish
Creating configuration debugProvided
Creating configuration debugWearApp
Creating configuration debugAnnotationProcessor
Creating configuration debugJackPlugin
Creating configuration testDebugCompile
Creating configuration testDebugPublish
Creating configuration testDebugProvided
Creating configuration testDebugWearApp
Creating configuration testDebugAnnotationProcessor
Creating configuration testDebugJackPlugin
Creating configuration releaseCompile
Creating configuration releasePublish
Creating configuration releaseProvided
Creating configuration releaseWearApp
Creating configuration releaseAnnotationProcessor
Creating configuration releaseJackPlugin
Creating configuration testReleaseCompile
Creating configuration testReleasePublish
Creating configuration testReleaseProvided
Creating configuration testReleaseWearApp
Creating configuration testReleaseAnnotationProcessor
Creating configuration testReleaseJackPlugin
WARNING [Project: :xx_core] Support for libraries with same package name is deprecated and will be removed in a future release.
WARNING [Project: :xx_core] Support for not packaging BuildConfig is deprecated.
useNewCruncher has been deprecated. It will be removed in a future version of the gradle plugin. New cruncher is now always enabled.
WARNING: The `android.dexOptions.incremental` property is deprecated and it has no effect on the build process.
Parsing the SDK, no caching allowed
SDK initialized in 0 ms
Resource missing. [HTTP GET: http://xx.net/nexus/content/repositories/releases/com/github/markzhai/blockcanary-android/1.5.0/blockcanary-android-1.5.0.pom]
Resource missing. [HTTP HEAD: http://xx.net/nexus/content/repositories/releases/com/github/markzhai/blockcanary-android/1.5.0/blockcanary-android-1.5.0.jar]
Resource missing. [HTTP GET: http://xx.net/nexus/content/repositories/xx_component/com/github/markzhai/blockcanary-android/1.5.0/blockcanary-android-1.5.0.pom]
Resource missing. [HTTP HEAD: http://xx.net/nexus/content/repositories/xx_component/com/github/markzhai/blockcanary-android/1.5.0/blockcanary-android-1.5.0.jar]
Resource missing. [HTTP GET: http://xx.net/nexus/content/repositories/thirdparty/com/github/markzhai/blockcanary-android/1.5.0/blockcanary-android-1.5.0.pom]
Resource missing. [HTTP HEAD: http://xx.net/nexus/content/repositories/thirdparty/com/github/markzhai/blockcanary-android/1.5.0/blockcanary-android-1.5.0.jar]
Download http://mvnrepo.xx/mvn/repository/com/github/markzhai/blockcanary-android/1.5.0/blockcanary-android-1.5.0.pom
Resource missing. [HTTP GET: http://xx.net/nexus/content/repositories/releases/com/github/markzhai/blockcanary-analyzer/1.5.0/blockcanary-analyzer-1.5.0.pom]
Resource missing. [HTTP HEAD: http://xx.net/nexus/content/repositories/releases/com/github/markzhai/blockcanary-analyzer/1.5.0/blockcanary-analyzer-1.5.0.jar]
Resource missing. [HTTP GET: http://xx.net/nexus/content/repositories/xx_component/com/github/markzhai/blockcanary-analyzer/1.5.0/blockcanary-analyzer-1.5.0.pom]
Resource missing. [HTTP HEAD: http://xx.net/nexus/content/repositories/xx_component/com/github/markzhai/blockcanary-analyzer/1.5.0/blockcanary-analyzer-1.5.0.jar]
Resource missing. [HTTP GET: http://xx.net/nexus/content/repositories/thirdparty/com/github/markzhai/blockcanary-analyzer/1.5.0/blockcanary-analyzer-1.5.0.pom]
Resource missing. [HTTP HEAD: http://xx.net/nexus/content/repositories/thirdparty/com/github/markzhai/blockcanary-analyzer/1.5.0/blockcanary-analyzer-1.5.0.jar]
Download http://mvnrepo.xx/mvn/repository/com/github/markzhai/blockcanary-analyzer/1.5.0/blockcanary-analyzer-1.5.0.pom
Creating new cache for metadata-2.23/module-artifacts, path /mnt/sdb/jenkins/jobs/xx_123/workspace/caches/modules-2/metadata-2.23/module-artifacts.bin, access org.gradle.cache.internal.DefaultCacheAccess@4130da40
Download http://mvnrepo.xx/mvn/repository/com/github/markzhai/blockcanary-analyzer/1.5.0/blockcanary-analyzer-1.5.0.aar
Download http://mvnrepo.xx/mvn/repository/com/github/markzhai/blockcanary-android/1.5.0/blockcanary-android-1.5.0.aar
Using incremental javac compilation for :xx_core debug.
Incremental java compilation is an incubating feature.
Not using incremental javac compilation for :xx_core debugUnitTest.
Using incremental javac compilation for :xx_core release.
Not using incremental javac compilation for :xx_core releaseUnitTest.
Not using incremental javac compilation for :xx_core debugAndroidTest.
Download http://xx.net/nexus/content/repositories/releases/com/xxnavi/xxxx/inputmethod/1.0.1/inputmethod-1.0.1.pom
Resource missing. [HTTP GET: http://xx.net/nexus/content/repositories/releases/com/xx/location/xx_sdk/release_5.1.301/xx_sdk-release_5.1.301.pom]
Resource missing. [HTTP HEAD: http://xx.net/nexus/content/repositories/releases/com/xx/location/xx_sdk/release_5.1.301/xx_sdk-release_5.1.301.aar]
Resource missing. [HTTP GET: http://xx.net/nexus/content/repositories/xx_component/com/xx/location/xx_sdk/release_5.1.301/xx_sdk-release_5.1.301.pom]
Resource missing. [HTTP HEAD: http://xx.net/nexus/content/repositories/xx_component/com/xx/location/xx_sdk/release_5.1.301/xx_sdk-release_5.1.301.aar]
Resource missing. [HTTP GET: http://xx.net/nexus/content/repositories/thirdparty/com/xx/location/xx_sdk/release_5.1.301/xx_sdk-release_5.1.301.pom]
Resource missing. [HTTP HEAD: http://xx.net/nexus/content/repositories/thirdparty/com/xx/location/xx_sdk/release_5.1.301/xx_sdk-release_5.1.301.aar]
Resource missing. [HTTP GET: http://mvnrepo.xx/mvn/repository/com/xx/location/xx_sdk/release_5.1.301/xx_sdk-release_5.1.301.pom]
Resource missing. [HTTP HEAD: http://mvnrepo.xx/mvn/repository/com/xx/location/xx_sdk/release_5.1.301/xx_sdk-release_5.1.301.aar]
Resource missing. [HTTP GET: http://maven.xx.com/nexus/content/groups/public/com/xx/location/xx_sdk/release_5.1.301/xx_sdk-release_5.1.301.pom]
Resource missing. [HTTP HEAD: http://maven.xx.com/nexus/content/groups/public/com/xx/location/xx_sdk/release_5.1.301/xx_sdk-release_5.1.301.aar]
Download http://maven.xx.com/nexus/content/repositories/xx_location/com/xx/location/xx_sdk/release_5.1.301/xx_sdk-release_5.1.301.pom
Download http://xx.net/nexus/content/repositories/releases/com/xxnavi/xxxx/component-framework/1.0.5/component-framework-1.0.5.pom
Resource missing. [HTTP GET: http://xx.net/nexus/content/repositories/releases//xx-171-release//xx-171-release-.pom]
Resource missing. [HTTP HEAD: http://xx.net/nexus/content/repositories/releases//xx-171-release//xx-171-release-.aar]
Resource missing. [HTTP GET: http://xx.net/nexus/content/repositories/xx_component//xx-171-release//xx-171-release-.pom]
Resource missing. [HTTP HEAD: http://xx.net/nexus/content/repositories/xx_component//xx-171-release//xx-171-release-.aar]
Resource missing. [HTTP GET: http://xx.net/nexus/content/repositories/thirdparty//xx-171-release//xx-171-release-.pom]
Resource missing. [HTTP HEAD: http://xx.net/nexus/content/repositories/thirdparty//xx-171-release//xx-171-release-.aar]
Resource missing. [HTTP GET: http://mvnrepo.xx/mvn/repository//xx-171-release//xx-171-release-.pom]
Resource missing. [HTTP HEAD: http://mvnrepo.xx/mvn/repository//xx-171-release//xx-171-release-.aar]
Resource missing. [HTTP GET: http://maven.xx.com/nexus/content/groups/public//xx-171-release//xx-171-release-.pom]
Resource missing. [HTTP HEAD: http://maven.xx.com/nexus/content/groups/public//xx-171-release//xx-171-release-.aar]
Resource missing. [HTTP GET: http://maven.xx.com/nexus/content/repositories/xx_location//xx-171-release//xx-171-release-.pom]
Resource missing. [HTTP HEAD: http://maven.xx.com/nexus/content/repositories/xx_location//xx-171-release//xx-171-release-.aar]
。。。never complete

**Comment by blindpirate** [comment] 2018-01-26 13:52
Still not clear at all. Please do not assume we know what you're doing. A sample to reproduce this issue is good, or provide us with `build.gradle` at least. We can't understand your project with only description like 

> First I depend on a aar through maven server

and

>  for test I depend on this aar local

**Comment by bmuschko** [comment] 2018-02-06 00:32
I am going to close this issue due to lack of information. Feel free to reopen if you can provide more details.

**Closed by bmuschko** 2018-02-06 00:32 UTC
Labels: from:contributor
