### ISSUE TITLE
do not factor credentials for configuration-cache when set by environment variable

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#28593] opened 2024-03-26 23:25 UTC
### Current Behavior

Gradle is invalidating the cache on the change of an environment variable that is only read via the credentials provider; because it's in the ORG_GRADLE_ namespace. Unfortunately (? probably not) `GITHUB_TOKEN` changes regularly, I'm not certain if it's every build or what, so if you set your credentials this way the cache gets invalidated.

### Expected Behavior

no invalidation

### Context (optional)

it slows down the build, I'm not certain how much, but anything using a credentials provider shouldn't invalidate the cache. which also makes me think it was stored in the cache...

### Steps to Reproduce

this is a public repo so you can actually try it. This is the relevant section of `settings.gradle.kts`
```java
@Suppress("UnstableApiUsage")
dependencyResolutionManagement {
  repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
  repositories {
    maven("https://maven.pkg.github.com/xenoterracide/java-commons") {
      name = "gh"

      mavenContent {
        includeModule("com.xenoterracide", "tools")
        snapshotsOnly()
      }
      credentials(PasswordCredentials::class)
   }
}
```

here's a relevant portion of a CI build

```yml
      - run: ./gradlew build buildHealth
        env:
          ORG_GRADLE_PROJECT_ghUsername: ${{ secrets.GITHUB_ACTOR }}
          ORG_GRADLE_PROJECT_ghPassword: ${{ secrets.GITHUB_TOKEN }}
```

### Gradle version

8.7

### Build scan URL (optional)

https://scans.gradle.com/s/b4z7aqptl26ny

### Your Environment (optional)

```
------------------------------------------------------------
Gradle 8.7
------------------------------------------------------------

Build time:   2024-03-22 15:52:46 UTC
Revision:     650af14d7653aa949fce5e886e685efc9cf97c10

Kotlin:       1.9.22
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          21.0.2 (Eclipse Adoptium 21.0.2+13-LTS)
OS:           Linux 6.6.19-1-MANJARO amd64
```

**Comment by ov7a** [comment] 2024-03-27 09:50
This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/24203

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

**Closed by ov7a** 2024-03-27 09:50 UTC
Labels: a:bug, to-triage
