### ISSUE TITLE
Gradle 7.1 The file published to nexus becomes to `<packaging>pom</packaging>` when I apply plugin `id 'org.springframework.boot' version '2.5.1'`.

### ISSUE THREAD

**Issue by Fatezhang** [gradle/gradle#17498] opened 2021-06-21 08:58 UTC
I created a repo and want to reuse the code in other repos, so I need to publish it to my nexus repository. The previous version was **5.6.3**, the current version is **7.1**.

**[Gradle 7.1]** The file published to nexus becomes to `<packaging>pom</packaging>` and the jar file becomes to `XXX-plain.jar`, but when I delete plugin `id 'org.springframework.boot' version '2.5.1'`, it comes correct.
![image](https://user-images.githubusercontent.com/12826096/122735638-cf116480-d2b1-11eb-809c-f7e9d4ebd856.png)

### Expected Behavior

The jar I upload to nexus should not contain `-plain.jar` in the tail of the name.

### Current Behavior

As mentioned above.

### Steps to Reproduce 

The following code is not working:
```groovy
plugins {
    id 'org.springframework.boot' version '2.5.1'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
    id 'java'
    id 'java-library'
    id 'maven-publish'
}

group 'org.example'
version '0.1'

repositories {
    mavenCentral()
}

jar {
    enabled = true
}

dependencies {
    api 'org.springframework.boot:spring-boot-starter-web'
    api 'org.springframework.boot:spring-boot-starter-aop'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.7.0'
}

test {
    useJUnitPlatform()
}

publishing {
    repositories {
        maven {
            allowInsecureProtocol = true
            name = 'nexus'
            url = "http://localhost:8081/nexus/content/repositories/releases"
            credentials {
                username = "admin"
                password = "admin123"
            }
        }
    }
    publications {
        demo(MavenPublication) {
            from components.java
            versionMapping {
                usage('java-api') {
                    fromResolutionOf('runtimeClasspath')
                }
                usage('java-runtime') {
                    fromResolutionResult()
                }
            }
        }
    }
}

```
But if I remove the plugin `org.springframework.boot` it works:
```groovy
plugins {
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
    id 'java'
    id 'java-library'
    id 'maven-publish'
}

group 'org.example'
version '0.1'

repositories {
    mavenCentral()
}

jar {
    enabled = true
}

dependencies {
    api 'org.springframework.boot:spring-boot-starter-web:2.5.1'
    api 'org.springframework.boot:spring-boot-starter-aop:2.5.1'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.7.0'
}

test {
    useJUnitPlatform()
}

publishing {
    repositories {
        maven {
            allowInsecureProtocol = true
            name = 'nexus'
            url = "http://localhost:8081/nexus/content/repositories/releases"
            credentials {
                username = "admin"
                password = "admin123"
            }
        }
    }
    publications {
        demo(MavenPublication) {
            from components.java
            versionMapping {
                usage('java-api') {
                    fromResolutionOf('runtimeClasspath')
                }
                usage('java-runtime') {
                    fromResolutionResult()
                }
            }
        }
    }
}

```

I have less knowledge about Gradle and didn't find any related information in `Stackoverflow`.

Any ideas would be appreciated. Thanks!!!🙏

### Your Environment

- java 11
- plugin 'org.springframework.boot' version '2.5.1'
- gradle version 7.1

**Comment by mlopatkin** [comment] 2021-06-23 10:28
@Fatezhang, please take a look at the [Spring Boot plugin documentation about plain archive](https://docs.spring.io/spring-boot/docs/2.5.1/gradle-plugin/reference/htmlsingle/#packaging-executable.and-plain-archives). You have to reconfigure classifiers on `jar` and `bootJar` artifacts to avoid what you're having right now.

I'm closing this issue because it is intended behavior.

**Closed by mlopatkin** 2021-06-23 10:28 UTC
Labels: a:bug, to-triage
