### ISSUE TITLE
Investigate potential publishing issue with composite builds

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#5228] opened 2018-05-02 07:20 UTC
See https://github.com/gradle/gradle/issues/1165#issuecomment-384046078

**Comment by marcphilipp** [comment] 2018-05-03 07:26
I've tried to reproduce the issue in a [sample project](https://github.com/marcphilipp/gradle-sandbox/tree/master/5228-publishing-composite-builds). However, it seems to work as expected:

```
./projectB$ ./gradlew --console verbose -Dmaven.repo.local=../m2repo publishToMavenLocal
> Task :generatePomFileForMavenJavaPublication
> Task :processResources NO-SOURCE
> Task :projectA:generatePomFileForMavenJavaPublication
> Task :projectA:compileJava NO-SOURCE
> Task :projectA:processResources NO-SOURCE
> Task :projectA:classes UP-TO-DATE
> Task :compileJava NO-SOURCE
> Task :classes UP-TO-DATE
> Task :jar
> Task :projectA:jar
> Task :projectA:publishMavenJavaPublicationToMavenLocal
> Task :projectA:publishToMavenLocal
> Task :publishMavenJavaPublicationToMavenLocal
> Task :publishToMavenLocal

BUILD SUCCESSFUL in 0s
3 actionable tasks: 3 executed
```

Here's what's published to the local repo:

```
$ ls -R ../m2repo
org

../m2repo/org:
gradle

../m2repo/org/gradle:
sample

../m2repo/org/gradle/sample:
projectA projectB

../m2repo/org/gradle/sample/projectA:
0.1                      maven-metadata-local.xml

../m2repo/org/gradle/sample/projectA/0.1:
projectA-0.1.jar projectA-0.1.pom

../m2repo/org/gradle/sample/projectB:
0.1                      maven-metadata-local.xml

../m2repo/org/gradle/sample/projectB/0.1:
projectB-0.1.jar projectB-0.1.pom
```

@nniesen @oehme Am I missing something?

**Comment by nniesen** [comment] 2018-05-04 17:51
I only notice it in our projects where we're producing multiple artifacts, one from main configuration and one from testSupport configuration. I'm not able to reproduced in a stripped down version of what we're doing so I must be something in our plugin.
[maven-publish-multiple-artifacts.zip](https://github.com/gradle/gradle/files/1975411/maven-publish-multiple-artifacts.zip)

**Comment by marcphilipp** [comment] 2018-05-07 11:47
Thanks for the info! I'm closing this issue for now. Please let us know if you manage to reproduce the issue.

**Closed by marcphilipp** 2018-05-07 11:47 UTC
Labels: a:bug, from:member, in:publishing-plugin
