### ISSUE TITLE
Integrate Kotlin DSL into main documentation

### ISSUE THREAD

**Issue by helmbold** [gradle/gradle#3240] opened 2017-10-19 08:22 UTC
I'd like to use the new Kotlin DSL instead of the old (and error prone!) Groovy DSL. However, it is hard to find examples, since most are written in Groovy. Even the reference documentation doesn't contain Kotlin examples. 

My favorite solution be to have code snippets in a box with tabs, one tab for Groovy and one tab for Kotlin.

If Kotlin should not be integrated into the main documentation for whatever reason, it would be nice to have an extensive separate Kotlin DSL documentation.

**Comment by oehme** [comment] 2017-10-19 16:49
Duplicate of https://github.com/gradle/kotlin-dsl/issues/106

**Closed by oehme** 2017-10-19 16:49 UTC
