### ISSUE TITLE
gradle 4.2 - play 2.6, scala version 2.12 not supported?

### ISSUE THREAD

**Issue by kknd22** [gradle/gradle#2991] opened 2017-09-21 17:18 UTC
in gradle 4.2, it starts to support play 2.6. However, we encounter the following:

> > Exception thrown while executing model rule: PlayApplicationPlugin.Rules#createBinaries(ModelMap<PlayApplicationBinarySpec>, PlayApplicationSpecInternal, PlatformResolvers, PlayToolChainInternal, PlayPluginConfigurations, File, ProjectIdentifier) > create(binary)
   > Not a supported Scala platform identifier 2.12. Supported values are: ['2.10', '2.11'].

does it mean scala 2.12 is not supported? 
Thanks

-cl

**Comment by vkokurin** [comment] 2017-09-22 08:53
U have also a problem starting with play 2.6, but scala 2.11 just by running gradle playRun:

> Failed to run Play
> org.gradle.internal.UncheckedException: java.lang.NoSuchMethodException: play.core.server.DevServerStart$.mainDevHttpMode(play.core.BuildLink, play.core.BuildDocHandler, int, java.lang.String)
> 

By looking into PlayRunAdapterV26X I see that it just extends PlayRunAdapterV24X which calls that mainDevHttpMode with reflections while using wrong arguments.

**Comment by marcospereira** [comment] 2017-09-25 19:55
This is possibly a duplicate of #2999.

**Comment by bmuschko** [comment] 2017-09-26 14:24
@marcospereira Thanks, this looks like a duplicate. Closing this issue.

**Closed by bmuschko** 2017-09-26 14:24 UTC
