### ISSUE TITLE
"Unable to make progress running work" redux2

### ISSUE THREAD

**Issue by jimshowalter** [gradle/gradle#22761] opened 2022-11-17 00:18 UTC
You closed https://github.com/gradle/gradle/issues/21125 and https://github.com/gradle/gradle/issues/21325, saying the problem is fixed in 7.6, but I just tried 7.6-rc-3 and got this error:

16:13:49  Unable to make progress running work. The following items are queued for execution but none of them can be started:
16:13:49    - Build ':':
16:13:49        - Waiting for nodes:
16:13:49            - :verifyAllSignatures (state=SHOULD_RUN, dependencies=NOT_COMPLETE, group=finalizer :verifyAllSignatures ordinal: task group 0, delegate: default group, no dependencies, finalizes=[:bootJar, :buildRelease] )
16:13:49            - :generatePermissions (state=SHOULD_RUN, dependencies=NOT_COMPLETE, group=finalizer :generatePermissions ordinal: task group 0, delegate: default group, dependencies=[:classes, :compileJava, :generateVersion], waiting-for=[:generateVersion, :compileJava, :classes], has-failed-dependency=false, finalizes=[:compileJava] )
16:13:49            - :buildRelease (state=SHOULD_RUN, dependencies=NOT_COMPLETE, group=task group 0, dependencies=[:clean (complete), :generateVersion], waiting-for=[:generateVersion], has-failed-dependency=false )
16:13:49            - :assemble (state=SHOULD_RUN, dependencies=NOT_COMPLETE, group=finalizer :assemble ordinal: task group 0, delegate: default group, dependencies=[:bootJar, :jar], waiting-for=[:bootJar, :jar], has-failed-dependency=false, finalizes=[:buildRelease] )
16:13:49        - Reachable nodes:
16:13:49            - :compileJava (state=SHOULD_RUN, dependencies=NOT_COMPLETE, group=composite group, entry point: false, ordinal: default group, groups: [finalizer :assemble ordinal: task group 0, delegate: default group, finalizer :generatePermissions ordinal: task group 0, delegate: default group], no dependencies )
16:13:49            - :processResources (state=SHOULD_RUN, dependencies=NOT_COMPLETE, group=composite group, entry point: false, ordinal: default group, groups: [finalizer :assemble ordinal: task group 0, delegate: default group, finalizer :generatePermissions ordinal: task group 0, delegate: default group], no dependencies )
16:13:49            - :classes (state=SHOULD_RUN, dependencies=NOT_COMPLETE, group=composite group, entry point: false, ordinal: default group, groups: [finalizer :assemble ordinal: task group 0, delegate: default group, finalizer :generatePermissions ordinal: task group 0, delegate: default group], dependencies=[:compileJava, :processResources], waiting-for=[:processResources, :compileJava], has-failed-dependency=false )
16:13:49            - :generateVersion (state=SHOULD_RUN, dependencies=NOT_COMPLETE, group=finalizer :generateVersion ordinal: task group 0, delegate: composite group, entry point: true, ordinal: task group 0, groups: [finalizer :assemble ordinal: task group 0, delegate: default group, finalizer :generatePermissions ordinal: task group 0, delegate: default group], no dependencies, finalizes=[:processResources] )
16:13:49            - :bootJar (state=SHOULD_RUN, dependencies=NOT_COMPLETE, group=finalizer :assemble ordinal: task group 0, delegate: default group, dependencies=[:classes, :compileJava, :generateVersion], waiting-for=[:generateVersion, :compileJava, :classes], has-failed-dependency=false )
16:13:49            - :jar (state=SHOULD_RUN, dependencies=NOT_COMPLETE, group=finalizer :assemble ordinal: task group 0, delegate: default group, dependencies=[:classes, :compileJava, :generateVersion], waiting-for=[:generateVersion, :compileJava, :classes], has-failed-dependency=false )
16:13:49        - Ordinal groups: group 0 entry nodes: [:buildRelease]
16:13:49    - Workers waiting for work: 16
16:13:49    - Stopped workers: 0
16:13:49  
16:13:49  FAILURE: Build failed with an exception.
16:13:49  
16:13:49  * What went wrong:
16:13:49  Unable to make progress running work. There are items queued for execution but none of them can be started

**Comment by jimshowalter** [comment] 2022-11-17 00:22
It works fine locally. Does that in Jenkins.

**Comment by ljacomet** [comment] 2022-11-17 08:19
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of #22734. Please add your 👍 to that issue.

***

However, if you can still reproduce after trying with the changes done for the issue above, we will need a reproducer to track down the issue.

**Closed by ljacomet** 2022-11-17 08:19 UTC
Labels: a:regression, closed:duplicate, in:scheduler
