### ISSUE TITLE
Gradle should support single sign on enterprise proxy with kerberos / activedirectory /NTLM

### ISSUE THREAD

**Issue by KotlinIsland** [gradle/gradle#17157] opened 2021-05-11 02:48 UTC
Reopening #5454

Gradle output spammed with:
```
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
```
It failed with Kerberos but it seems succeeded with NTLM

Gradle shouldn't need the users proxy username/password when the Windows SSPI interface is available.

**Comment by mlopatkin** [comment] 2021-06-03 08:57
Duplicate of #5454. I'm reopening that one.

**Closed by mlopatkin** 2021-06-03 08:57 UTC
Labels: a:feature, closed:duplicate, to-triage
