### ISSUE TITLE
Bom support - compile-time failure while dependencyInsight is correct

### ISSUE THREAD

**Issue by OdysseusLives** [gradle/gradle#4817] opened 2018-03-23 04:34 UTC
When using Gradle's experimental improved pom support for boms, we see that files and jars provide the correct dependency version when queried via `dependencyInsight`, but we receive a compile-time error when building the project. 

### Expected Behavior
Given that we list dependencies in my project's _build.gradle_ file without version numbers
And we list a bom in my project as a dependency (a .pom file with packaging as pom, and listing `<dependencyManagement>` containing dependencies with versions) that contains version numbers for the above dependencies,
When we run `./gradlew clean build`,
Then we expect the project to compile, and the build to succeed. 

### Current Behavior
As opposed to succeeding, the build fails at compile-time with the error: `error: package ... does not exist`

When we run `dependencyInsight` on the problematic dependency, then I see the correctly resolved version number for the dependency.

### Context
We have been using the [nebula dependency-recommender plugin](https://github.com/nebula-plugins/nebula-dependency-recommender-plugin) to manage boms in a project. We are switching to Gradle's internal bom support. 

As more information about current behavior... 
When we look at the `NormalizingJavaCompiler` classpath when using nebula's dependency recommender and when using Gradle's itself, the output is quite different.

### Steps to Reproduce
Sample project that showcases the issue, as well as the difference when running with nebula's dependency-recommender plugin: 
https://github.com/OdysseusLives/gradle_bom_management

### Your Environment
Gradle 4.5.1 (Gradle wrapper is checked in for the sample project)

**Comment by ljacomet** [comment] 2018-03-23 17:45
Thanks for the report and the reproducible test case.
I confirmed this does not work in 4.51, nor in later versions.

Will be looking into providing a fix.

**Comment by ljacomet** [comment] 2018-03-26 09:19
So the issue is not a bug in Gradle as I believed ... wrongly.

The build problem is caused by the [`astyanax-core` pom](http://repo1.maven.org/maven2/com/netflix/astyanax/astyanax-core/3.9.0/astyanax-core-3.9.0.pom) publishing its dependencies as `runtime` and the enabled _improved pom support_ in Gradle.

With this support, Gradle now honors the difference between `compile` and `runtime` dependencies in Maven pom files.

Because of that, none of the _transitive_ dependencies of `astyanax-core` show up in the `compileClasspath` or `testCompileClasspath`. However, they correctly show in the `runtimeClasspath` or `testRuntimeClasspath` as can be seen below:

```
runtimeClasspath - Runtime classpath of source set 'main'.
+--- sample:recommender:1.0
|    \--- com.netflix.astyanax:astyanax-core:3.9.0
|         +--- joda-time:joda-time:1.6.2 -> 2.9.9
|         +--- com.github.stephenc.high-scale-lib:high-scale-lib:1.1.2
|         +--- com.google.guava:guava:15.0
|         +--- com.eaio.uuid:uuid:3.2
|         +--- org.slf4j:slf4j-api:1.7.2
|         +--- commons-lang:commons-lang:2.4
|         \--- org.apache.cassandra:cassandra-all:2.0.12
|              +--- org.xerial.snappy:snappy-java:1.0.5
|              +--- net.jpountz.lz4:lz4:1.2.0
|              +--- com.ning:compress-lzf:0.8.4
|              +--- com.google.guava:guava:15.0
|              +--- commons-cli:commons-cli:1.1
|              +--- commons-codec:commons-codec:1.2 -> 1.10
|              +--- org.apache.commons:commons-lang3:3.1
|              +--- com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.3
|              +--- org.antlr:antlr:3.2
|              |    \--- org.antlr:antlr-runtime:3.2
|              |         \--- org.antlr:stringtemplate:3.2
|              |              \--- antlr:antlr:2.7.7
|              +--- org.slf4j:slf4j-api:1.7.2
|              +--- org.codehaus.jackson:jackson-core-asl:1.9.2
|              +--- org.codehaus.jackson:jackson-mapper-asl:1.9.2
|              |    \--- org.codehaus.jackson:jackson-core-asl:1.9.2
|              +--- jline:jline:1.0
|              +--- com.googlecode.json-simple:json-simple:1.1
|              +--- com.github.stephenc.high-scale-lib:high-scale-lib:1.1.2
|              +--- org.yaml:snakeyaml:1.11 -> 1.17
|              +--- edu.stanford.ppl:snaptree:0.1
|              +--- org.mindrot:jbcrypt:0.3m
|              +--- com.yammer.metrics:metrics-core:2.2.0
|              |    \--- org.slf4j:slf4j-api:1.7.2
|              +--- com.addthis.metrics:reporter-config:2.1.0
|              |    +--- org.slf4j:slf4j-api:1.7.2
|              |    +--- org.yaml:snakeyaml:1.12 -> 1.17
|              |    +--- org.hibernate:hibernate-validator:4.3.0.Final -> 4.3.2.Final
|              |    |    +--- javax.validation:validation-api:1.0.0.GA
|              |    |    +--- org.jboss.logging:jboss-logging:3.1.0.CR2
|              |    |    \--- joda-time:joda-time:1.6 -> 2.9.9
|              |    \--- com.yammer.metrics:metrics-core:2.2.0 (*)
|              +--- com.thinkaurelius.thrift:thrift-server:0.3.7
|              |    +--- com.lmax:disruptor:3.0.1
|              |    +--- org.apache.thrift:libthrift:0.9.1
|              |    |    +--- org.slf4j:slf4j-api:1.5.8 -> 1.7.2
|              |    |    +--- org.apache.commons:commons-lang3:3.1
|              |    |    +--- org.apache.httpcomponents:httpclient:4.2.5
|              |    |    |    +--- org.apache.httpcomponents:httpcore:4.2.4
|              |    |    |    +--- commons-logging:commons-logging:1.1.1 -> 1.2
|              |    |    |    |    \--- log4j:log4j:1.2.17
|              |    |    |    \--- commons-codec:commons-codec:1.6 -> 1.10
|              |    |    \--- org.apache.httpcomponents:httpcore:4.2.4
|              |    +--- org.slf4j:slf4j-api:1.6.1 -> 1.7.2
|              |    +--- org.slf4j:slf4j-log4j12:1.7.2
|              |    |    +--- org.slf4j:slf4j-api:1.7.2
|              |    |    \--- log4j:log4j:1.2.17
|              |    \--- junit:junit:4.8.1
|              +--- net.sf.supercsv:super-csv:2.1.0
|              +--- log4j:log4j:1.2.16 -> 1.2.17
|              +--- org.slf4j:slf4j-log4j12:1.7.2 (*)
|              +--- org.apache.thrift:libthrift:0.9.1 (*)
|              +--- org.apache.cassandra:cassandra-thrift:2.0.12
|              |    +--- org.apache.commons:commons-lang3:3.1
|              |    +--- org.slf4j:slf4j-api:1.7.2
|              |    \--- org.apache.thrift:libthrift:0.9.1 (*)
|              +--- com.github.stephenc:jamm:0.2.5
|              \--- io.netty:netty:3.6.6.Final
|                   +--- org.slf4j:slf4j-api:1.6.4 -> 1.7.2
|                   +--- commons-logging:commons-logging:1.1.1 -> 1.2 (*)
|                   \--- log4j:log4j:1.2.16 -> 1.2.17
+--- com.netflix.astyanax:astyanax-core:[3.9+,4.0) -> 3.9.0 (*)
\--- org.springframework:spring-context:4.+ -> 4.3.14.RELEASE
     +--- javax.validation:validation-api:1.0.0.GA
     +--- joda-time:joda-time:2.9.9
     +--- org.hibernate:hibernate-validator:4.3.2.Final (*)
     +--- org.springframework:spring-aop:4.3.14.RELEASE
     |    +--- org.springframework:spring-beans:4.3.14.RELEASE
     |    |    +--- org.springframework:spring-core:4.3.14.RELEASE
     |    |    |    +--- commons-codec:commons-codec:1.10
     |    |    |    +--- commons-logging:commons-logging:1.2 (*)
     |    |    |    \--- log4j:log4j:1.2.17
     |    |    \--- org.yaml:snakeyaml:1.17
     |    \--- org.springframework:spring-core:4.3.14.RELEASE (*)
     +--- org.springframework:spring-beans:4.3.14.RELEASE (*)
     +--- org.springframework:spring-core:4.3.14.RELEASE (*)
     \--- org.springframework:spring-expression:4.3.14.RELEASE
          \--- org.springframework:spring-core:4.3.14.RELEASE (*)

(*) - dependencies omitted (listed previously)
```

The correct thing to do is to add the required _compile time_ dependencies to the project, ideally using the `api` or `implementation` configurations over deprecated `compile`.

Note that this _better_ behavior will become the default in Gradle 5.0.

**Comment by ljacomet** [comment] 2018-03-26 09:26
While this behavior can be observed in 4.5.1 through undocumented flags usage, it was made public as part of 4.6. See the [relevant section](https://docs.gradle.org/4.6/release-notes.html?_ga=2.215730961.784771716.1521995601-1636098815.1520361552#compile/runtime-scope-separation-in-pom-consumption) in release notes.

**Comment by ljacomet** [comment] 2018-03-30 15:11
Closing as this is the intended behavior of _improved pom support_.

**Closed by ljacomet** 2018-03-30 15:11 UTC
Labels: a:bug, from:contributor, in:dependency-management
