### ISSUE TITLE
IntelliJ IDEA Jump to Source not working with Gradle and JUnit Parameterized Test

### ISSUE THREAD

**Issue by lars06** [gradle/gradle#24585] opened 2023-03-31 14:25 UTC
***NOTE**: this issue was initially [reported to Jetbrains](https://youtrack.jetbrains.com/issue/IDEA-268107/Jump-to-Source-not-working-with-Gradle-and-JUnit5-ParameterizedTest) by another user but was found to be unrelated to IntelliJ. I couldn't find the bug reported to Gradle yet so am posting here*

## Steps to reproduce:

- Create a new failing JUnit [Parameterized test](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests) in a Gradle project on IntelliJ IDEA
- Run the tests in the IDE
- In the Test Results click on the failure

## Expected result

Expect to be taken to the failing test method in the IDE like regular tests

## Actual result

Nothing happens

**Comment by ov7a** [comment] 2023-04-03 08:57
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed, response time may vary.

**Comment by reinsch82** [comment] 2023-09-07 12:33
Thx for submitting this issue.

Do you by any chance have more specific instructions for reproduction?

- I used `gradle init` to create a project with gradle 8.3.
- opened it with IDEA IntelliJ IDEA 2023.2.1 (Ultimate Edition)
- copied the example from the [IDEA bug report](https://youtrack.jetbrains.com/issue/IDEA-268107/Jump-to-Source-not-working-with-Gradle-and-JUnit5-ParameterizedTest)
- executed the tests
- worked

To be fair while trying out different versions it didn't work initially with 8.3, but trying to repro it again from scratch with 8.3, it worked. And I don't manage to repro it again.

Thx for your help.

**Comment by reinsch82** [comment] 2024-01-03 13:08
This was fixed in the IDE [see](https://youtrack.jetbrains.com/issue/IDEA-266987/Parameterized-JUnit5-tests-missing-any-kind-of-integration#focus=Comments-27-8300789.0-0) which is the duplicate of the issue mentioned in this issue.

**Closed by reinsch82** 2024-01-03 13:08 UTC
Labels: a:bug, to-triage, in:ide, closed:intellij
