### ISSUE TITLE
Gradle's copy of Kotlin 1.1 stdlib seems to leak onto the compile task and break Kotlin 1.0 projects

### ISSUE THREAD

**Issue by mikehearn** [gradle/gradle#1087] opened 2017-01-03 14:01 UTC
Our Kotlin 1.0 project (github.com/corda/corda) can't build with Gradle 3.1+ because somehow Gradle's copy of Kotlin 1.1 leaks onto the classpath and causes the compiler to get confused.

https://github.com/corda/corda/issues/18

### Expected Behavior

The fact that Gradle uses Kotlin internally shouldn't impact our build.

### Current Behavior

We get errors like this:

```
e: /home/lin/git/corda/node/src/main/kotlin/net/corda/node/utilities/JDBCHashMap.kt: (208, 27): Inherited platform declarations clash: The following declarations have the same JVM signature (getOrDefault(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;):
    fun getOrDefault(key: Any!, defaultValue: MutableList<AbstractJDBCHashMap.NotReallyMutableEntry<K, V>>!): MutableList<AbstractJDBCHashMap.NotReallyMutableEntry<K, V>>!
    fun getOrDefault(key: Int, defaultValue: MutableList<AbstractJDBCHashMap.NotReallyMutableEntry<K, V>>): MutableList<AbstractJDBCHashMap.NotReallyMutableEntry<K, V>>
```

... that don't occur when building with Gradle 2.10

### Steps to Reproduce (for bugs)

Just try building corda with the latest gradle to see the error.

**Comment by bamboo** [comment] 2017-01-03 15:17
Hi @mikehearn, the leak is by design and it is necessary to properly support multi-project Gradle builds due to the way the Gradle ClassLoader hierarchy is set up.

Ideally, the Kotlin compiler wouldn't be affected by the presence of a different Kotlin stdlib in the runtime classpath but currently it does.

The good news is that JetBrains is aware of the issue and they are working on a solution. The stable 1.1 release due soon (Q1 2017) should include it.

**Comment by mikehearn** [comment] 2017-01-03 16:05
I'm glad to hear that JetBrains is handling this, but it sounds rather suspicious. Why should the compiler be exposed to random internals of how Gradle loads its configuration files? Even if there's a workaround available soon in the Kotlin compiler itself, shouldn't Gradle be isolating plugins a bit more than that? Would Jigsaw solve this?

**Comment by bamboo** [comment] 2017-04-03 15:01
Fixed in Gradle 3.5 with the update to Kotlin 1.1.0.

**Closed by bamboo** 2017-04-03 15:01 UTC
Labels: a:question, affects-version:3.1, affects-version:3.2, affects-version:3.3, affects-version:3.4, from:contributor, in:kotlin-plugin

**Comment by bmuschko** [comment] 2017-04-03 15:17
@bamboo Can you please add the relevant milestone?

**Comment by bamboo** [comment] 2017-04-03 15:24
@bmuschko added to the 3.5 milestone.

**Comment by bamboo** [comment] 2017-04-03 17:57
Thanks, @lacasseio. I missed the `closed` tab in the `Milestone` drop-down.

**Comment by mikehearn** [comment] 2017-04-04 22:14
Thanks guys! 👍
