### ISSUE TITLE
BOM support seem not to be applied to transitive deps

### ISSUE THREAD

**Issue by mvysny** [gradle/gradle#4417] opened 2018-02-17 19:14 UTC
I tried to use the new Gradle's 4.6-rc1 BOM support feature, however it does not seem to work - the BOM is not applied to transitive dependencies; that causes Gradle to look up for other versions of dependency libraries and ultimately failing to download jars.

### Expected Behavior
The BOM referenced in `compile "com.vaadin:vaadin-bom:10.0.0.alpha18"` should be applied to project transitive dependencies. The vaadin-bom is indeed a pom-type project as can be seen at https://maven.vaadin.com/vaadin-prereleases/com/vaadin/vaadin-bom/10.0.0.alpha18/

### Current Behavior
The BOM is not applied and thus different library versions are attempted to be downloaded.

### Context
Vaadin 10 uses webcomponents packaged as webjars which are automatically generated from bower. Since bower and Maven dependency mechanism differs, Vaadin 10 provides BOM to correct the dependency tree. It seems that the `io.spring.dependency-management` plugin correctly loads the BOM and fixes the tree; however when the plugin is removed and replaced by Gradle 4.6's built-in BOM mechanism, this tree fixing stops working.

### Steps to Reproduce (for bugs)
1. Clone https://github.com/mvysny/karibu10-helloworld-application
2. Edit `build.gradle` file:
  a. delete the `"io.spring.dependency-management"` plugin at line 4
  b. delete the `dependencyManagement` stanza at lines 25-27
  c. Add dependency `compile "com.vaadin:vaadin-bom:10.0.0.alpha18"` at line 34
3. Run `./gradlew` - the build will now fail to download a non-existent versions of webjar dependencies.

### Your Environment
OpenJDK 1.8.0_151; ubuntu 17.10 4.13.0-32-generic 64bit

**Comment by jjohannes** [comment] 2018-02-19 15:38
@mvysny Thanks for reporting. The issue is not the BOM support itself but the way how Gradle handles certain versions differently than Maven. 

```
Could not find any version that matches org.webjars.bowergithub.vaadin:vaadin-progress-bar:[1.0.0,2).
     Versions that do not match:
         1.0.0-beta1
         1.0.0-alpha12
         1.0.0-alpha11
```

The BOM is included but for Gradle `1.0.0-beta1` is currently not in the range `[1.0.0,2)` (it would work if the range defined in the bom where `[1,2)`).

See #1218.

I am closing this as duplicate. But I acknowledge that we should prioritise #1218.

**Closed by jjohannes** 2018-02-19 15:38 UTC
Labels: a:bug, from:contributor, in:dependency-management

**Comment by mvysny** [comment] 2018-02-19 19:29
Thanks for explaining. If I understand correctly, Maven honors BOM version even though it doesn't fall into the accepted range. A bit weird, but I guess we need to mimic that to be compatible with Maven.

**Comment by jjohannes** [comment] 2018-02-20 07:45
Yes you are right. You can argue that Gradle interprets the range correctly in this case as `1.0.0-beta1` < `1.0.0`. Looking at it this way, the BOM is "wrong". Maybe using `[1,2)` instead of `[1.0.0,2)` (and `[2,3)` instead of `[2.0.0,3)`) would work for both Maven and Gradle?

**Comment by mvysny** [comment] 2018-02-20 08:04
I agree that Gradle does the right thing. Let me check if the BOM itself can be fixed. Yet since the Vaadin folk target Maven primarily, we need to bug-report this to Maven as well, otherwise the BOM will experience breakages in the future as well...
