### ISSUE TITLE
Undeletable files on Windows when `ArchiveOperations.zipTree` is used inside a TransformAction

### ISSUE THREAD

**Issue by britter** [gradle/gradle#25752] opened 2023-07-13 07:40 UTC
### Expected Behavior

When using a `ArchiveOperations.zipTree` inside of a `TransformAction`, it should be possible to clean the build output.

### Current Behavior

When running `clean` on Windows in a project that registers a TransformAction using `ArchiveOperations.zipTree` it will sporadically fail, indicating that it can't delete `build\tmp\.cache\expanded\expanded.lock`

Stacktrace:

```
java.io.IOException: Unable to delete directory 'C:\path\to\project\build'
  Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
  - C:\path\to\project\build\tmp\.cache\expanded\expanded.lock
  - C:\path\to\project\build\tmp\.cache\expanded
  - C:\path\to\project\build\tmp\.cache
  - C:\path\to\project\build\tmp
> Unable to delete directory 'C:\path\to\project\build'
    Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
    - C:\path\to\project\build\tmp\.cache\expanded\expanded.lock
    - C:\path\to\project\build\tmp\.cache\expanded
    - C:\path\to\project\build\tmp\.cache
    - C:\path\to\project\build\tmp
```

### Context (optional)

I need to transform a zip archive to a directory while at the same time preserving file permissions. I can't use `org.gradle.api.internal.artifacts.transform.UnzipTransform` because it does not preserve file permissions.

### Steps to Reproduce

1. Add register the following transform:

```kotlin
@DisableCachingByDefault(because = "Not worth caching")
abstract class UnzipTransform : TransformAction<TransformParameters.None> {

    @get:[InputArtifact PathSensitive(PathSensitivity.NAME_ONLY)]
    abstract val zipFile: Provider<FileSystemLocation>

    @get:Inject
    abstract val archiveOperations: ArchiveOperations

    @get:Inject
    abstract val fs: FileSystemOperations

    override fun transform(outputs: TransformOutputs) {
        val zip = zipFile.get().asFile

        fs.sync {
            from(archiveOperations.zipTree(zipFile))
            into(outputs.dir(zip.nameWithoutExtension))
        }
    }
}
```

2. Use it somewhere in the project
3. Run a build with `clean` on Windows multiple times
4. Eventually cleaning will fail because of the lock file can't be deleted

### Gradle version

8.3-20230623143448+0000

**Comment by ov7a** [comment] 2023-07-14 12:13
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before a fix is made.

---

Related:
* #25678

**Comment by tresat** [comment] 2023-07-24 15:52
I am not able to reproduce this behavior.  Here's my build script:

```kotlin
plugins {
    id("java-library")
}

@DisableCachingByDefault(because = "Not worth caching")
abstract class UnzipTransform : TransformAction<TransformParameters.None> {

    @get:[InputArtifact PathSensitive(PathSensitivity.NAME_ONLY)]
    abstract val zipFile: Provider<FileSystemLocation>

    @get:Inject
    abstract val archiveOperations: ArchiveOperations

    @get:Inject
    abstract val fs: FileSystemOperations

    override fun transform(outputs: TransformOutputs) {
        val zip = zipFile.get().asFile

        fs.sync {
            from(archiveOperations.zipTree(zipFile))
            into(outputs.dir(zip.nameWithoutExtension))
        }
    }
}

val artifactType = Attribute.of("artifactType", String::class.java)

dependencies {
    implementation(project(":lib"))

    registerTransform(UnzipTransform::class) {
        from.attribute(artifactType, "jar")
        to.attribute(artifactType, "unzipped")
    }
}

configurations {
    compileClasspath {
        attributes {
            attribute(artifactType, "unzipped")
        }
    }
}
```

I create a simple nested `lib` library project with a single java source file, then run: 

`gradlew.bat clean build --no-build-cache` on Windows repeatedly, using Gradle 8.3-rc-1 and the latest nightly.

I see `lib/build/.transforms` with the extracted contents of the jar from the transform and `build/tmp/.cache/expanded` with the `expanded.lock` file.

I haven't yet seen any issues with deleting files.

Can you please post a complete reproducer, and note the version of Windows you're running?

**Comment by patricklucas** [comment] 2023-07-25 09:17
This is happening for me on Windows 10 after upgrading to Gradle 8.1 from 7.5.1. If I downgrade back to Gradle 7.6.2 (the latest Gradle v7 release) the problem goes away.

However, I also noticed that by changing `task foo(type: Sync) {` to `tasks.register('foo', Sync) {` for lazy evaluation also resolved the issue (and sped up the build as well).

**Comment by tresat** [comment] 2023-07-25 11:39
Lazy registration is recommended whenever possible to improve build speed when tasks aren't executed.  The fact that changing this affects how an artifact transform executes is concerning, though.

Please post a complete reproducer when you can and we will investigate further.

**Comment by pbielicki** [comment] 2023-08-01 10:33
@britter I tried different things but I was not able to reproduce the issue. 
@tresat it might be linked to some other elements in our build - I will try to investigate it further and will get back to you.

**Comment by matthiaskraaz** [comment] 2023-08-04 05:16
This has bitten me too in two situations: 

1. Copy task fails with the following stacktrace:

          // Copy Task schlägt unter Windows fehl mit
          // org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':doc:unzip_doc_html'.
          // ...
          // Caused by: org.gradle.internal.deprecation.DocumentedFailure$DocumentedExceptionWithCause: Cannot access a file in the destination directory. Copying to a directory which contains unreadable content is not supported. Declare the task as untracked by using Task.doNotTrackState(). See https://docs.gradle.org/8.1.1/userguide/incremental_build.html#disable-state-tracking for more details.
          // ...
          // Caused by: java.io.UncheckedIOException: Failed to create MD5 hash for file content.
          // ...
          // Caused by: java.io.IOException: Der Prozess kann nicht auf die Datei zugreifen, da ein anderer Prozess einen Teil der Datei gesperrt hat
          //   at org.gradle.internal.hash.DefaultStreamHasher.doHash(DefaultStreamHasher.java:52)
          //   at org.gradle.internal.hash.DefaultStreamHasher.hash(DefaultStreamHasher.java:35)
          //   ... 96 more

Workaround: Use project.copy instead.

2. npm_run_build from the node plugin fails with "EBUSY: resource busy or locked, unlink 'D:\go\pipelines\OsisWebPortal_trunk\src\client\build\tmp\.cache\expanded\expanded.lock'"

Workaround: run gradle npm_install separately

**Comment by pantherdd** [comment] 2023-09-15 13:46
I am facing the same issue on Windows 10 and Gradle 8.3, i.e. when I try to run the `clean` task from IntelliJ, I always get this:
```
Execution failed for task ':clean'.
> java.io.IOException: Unable to delete directory 'D:\Work\GradleApp\build'
    Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
    - D:\Work\GradleApp\build\tmp\.cache\expanded\expanded.lock
    - D:\Work\GradleApp\build\tmp\.cache\expanded
    - D:\Work\GradleApp\build\tmp\.cache
    - D:\Work\GradleApp\build\tmp
```
This is my project and PR: https://github.com/morganstanley/gradle-plugin-application/pull/12
(I wanted to share it with the Gradle team anyway, but rather as something to contribute, not as a bug reproduction 😄 )

**Comment by Technici4n** [comment] 2023-11-03 17:06
Hi, I came up with the following reproduction script: (requires some `hello.zip` file to exist in the project root directory)

```gradle
plugins {
    id 'lifecycle-base'
}

System.out.println("Executing build.gradle")

def helloArchive = zipTree(file("hello.zip"))
tasks.create("makeArchive", Zip) {
    System.out.println("Files in the archive: " + helloArchive.files)

    archiveFileName = "archive.zip"
    destinationDirectory = layout.buildDirectory

    from helloArchive
}
```

Repo for easy reproduction: https://github.com/Technici4n/gradle-issue-25752.

Try running `gradlew clean` (that should not work).

It is important for the reproduction that we try to read from the archive as we configure the task, hence the `.files` call and the use of `create`.

Hope this helps!

**Comment by payneChen** [comment] 2023-11-06 02:08
Hi @tresat

we could reproduce as well **in window** after upgrade to 8.3 and it is like the same problem mentioned in https://github.com/gradle/gradle/issues/26539:
Operating system | Windows 11 10.0 (amd64) |  
-- | -- | --
CPU cores | 16 cores |  
Max Gradle workers | 16 workers |  
Java runtime | SAP SapMachine OpenJDK Runtime Environment 17.0.7+7-LTS |  
Java VM | SAP SapMachine OpenJDK 64-Bit Server VM 17.0.7+7-LTS (mixed mode, sharing) |  
Max JVM memory heap size | 4 GiB |  
Locale | English (India) |  
Default charset | windows-1252

**Comment by oleg-nenashev** [comment] 2024-01-10 09:00
Most likely it is a full duplicate of #26912 and will be solved by the same patch

**Comment by tresat** [comment] 2024-01-10 12:45
We've been finishing up a fix for this issue over the last few weeks.  The investigation of this issue actually led us into some unexpected areas.  The PR with the current fix under development is https://github.com/gradle/gradle/pull/27392.  I just linked it and closed the other associated PRs.  Look for this to "just work" again in Gradle 8.7.

**Closed** 2024-01-10 22:22 UTC
Labels: a:bug, in:workers, re:windows, in:file-tasks, in:artifact-transforms, has:reproducer

**Comment by Vampire** [comment] 2024-02-27 13:33
Just for reference, this simple snippet in any build script will reproduce the problem.
And it is a problem Windows **and** on Linux.
```kts
repositories {
    mavenCentral()
}
val foo by configurations.creating
dependencies {
    foo("commons-lang:commons-lang:+")
}
zipTree(foo.singleFile).visit { }
```
On Windows executing `clean` will complain that the `expanded.lock` cannot be deleted.
On Linux executin `clean` will first give `BUILD SUCCESSFUL` and then right after `BUILD FAILED` with "No such file or directory".

On 7.6.4 it works fine, in 8.0 - 8.6 it breaks.
8.7-rc-1 indeed fixes the problem.

Here the according forum topic: https://discuss.gradle.org/t/help-needed-with-gradle-clean-failure/47786
