### ISSUE TITLE
Support for lazy evaluation of Provider-Based tasks inputs in Configuration Cache

### ISSUE THREAD

**Issue by dkrasnoff** [gradle/gradle#30355] opened 2024-08-29 18:26 UTC
### Expected Behavior

With the enabled [configuration cache](https://docs.gradle.org/current/userguide/configuration_cache.html), we want to allow task inputs to be lazily configured based on the content of files generated by other tasks.

Here is a simple example of such a project: https://github.com/dkrasnoff/generated-inputs

### Current Behavior (optional)

There is a simple task that creates a text file:

```kotlin
abstract class ProducerTask : DefaultTask() {

    @get:OutputFile
    abstract val producedFile: RegularFileProperty

    @TaskAction
    fun createFile() {
        producedFile.asFile.get().writeText("Hello from producer!")
    }
}
```

On the other hand, we have another task with two inputs: `RegularFileProperty` and `Provider<String>`. The second input is a lazy calculated content of the first one:

```kotlin
abstract class ConsumerTask : DefaultTask() {

    @get:InputFile
    @get:PathSensitive(PathSensitivity.RELATIVE)
    @get:NormalizeLineEndings
    @get:Optional
    abstract val producedFile: RegularFileProperty

    @get:Input
    @get:Optional
    val consumedString: Provider<String> = producedFile.map { it.asFile.readText() }

    @TaskAction
    fun createFile() {
        println(consumedString.get())
    }
}
```

Let's wire the output of `ProducerTask` and the input of `ConsumerTask` like this:
```kotlin
val producerTask by project.tasks.registering(ProducerTask::class) {
    producedFile.set(layout.buildDirectory.file(project.file("producer.txt").absolutePath))
}

val consumerTask by project.tasks.creating(ConsumerTask::class) {
    producedFile.set(producerTask.map { it.producedFile.get() })
}
```

Finally, call the `consumerTask` with enabled [configuration cache](https://docs.gradle.org/current/userguide/configuration_cache.html):

```bash
./gradlew consumerTask --configuration-cache
```

We expect that the `producerTask` will be called first, and then inputs for the `consumerTask` will be calculated, as it works without configuration cache. But it fails with `/{path_to_project}/producer.txt (No such file or directory)`

### Context

For kotlin native could be passe [a def file](https://kotlinlang.org/docs/native-app-with-c-and-libcurl.html#create-a-definition-file) for CInterop task, which contains a list of headers. So we'd like to have the possibility to read def file's header and prepare a list of headers to pass as input inside the provider marked as Input.

**Comment by ljacomet** [comment] 2024-09-03 13:04
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

`producedFile.set(producerTask.flatMap { it.producedFile })` is most likely losing the task dependency and the stricter model of configuration cache trips on it.
@dkrasnoff What happens if you use `map` there instead?

@gradle/bt-configuration If the analysis above is correct, would we have a way to report this in a better way? If the analysis is wrong, please take a look at this surprising difference of behaviour.

**Comment by dkrasnoff** [comment] 2024-09-03 14:21
@ljacomet thank you for the comment!
I've changed `producedFile.set(producerTask.flatMap { it.producedFile })` to `producedFile.set(producerTask.map { it.producedFile.get() })` and added `@get:Optional` to the second input. But the problem reproduces.
Updated both: description here and example project

**Comment by mlopatkin** [comment] 2024-09-10 12:06
This issue will be closed as a duplicate of

* #19252

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

**Closed by mlopatkin** 2024-09-10 12:06 UTC
Labels: a:feature, in:configuration-cache, in:writing-tasks, :wave: team-triage
