### ISSUE TITLE
"Broken pipe (Write failed)" upon attempting to store entry in build cache

### ISSUE THREAD

**Issue by josecoll** [gradle/gradle#6018] opened 2018-07-18 15:23 UTC
I am experiencing this error upon running a sizeable number of tests and attempting to store these in a remote gradle cache (running in an Azure VM using the Docker Container image:
sudo docker run -d -v /opt/build-cache-node:/data -p 80:5071 gradle/build-cache-node:latest).

Command executed for my project:

`../gradlew -Dorg.gradle.caching.debug=true clean test --tests net.corda.node.services.* --build-cache --scan`

Failure output:

```
> Task :node:test
Appending taskClass to build cache key: org.gradle.api.tasks.testing.Test_Decorated
Appending classLoaderHash to build cache key: 9b3fed7a57a4142f251290910f3d648a
Appending actionType to build cache key: org.gradle.api.tasks.testing.Test_Decorated
Appending actionClassLoaderHash to build cache key: 9b3fed7a57a4142f251290910f3d648a
Appending inputPropertyHash for 'debug' to build cache key: c06857e9ea338f3f3a24bb78f8fbdf6f
Appending inputPropertyHash for 'defaultCharacterEncoding' to build cache key: d746f44d09fb58d2971f341d24d74c35
Appending inputPropertyHash for 'enableAssertions' to build cache key: f6d7ed39fe24031e22d54f3fe65b901c
Appending inputPropertyHash for 'filter' to build cache key: 3eb586de3301abc137c0d288b893e13d
Appending inputPropertyHash for 'filter.commandLineIncludePatterns' to build cache key: d7cc7866380e9150f617440615c335cf
Appending inputPropertyHash for 'filter.failOnNoMatchingTests' to build cache key: f6d7ed39fe24031e22d54f3fe65b901c
Appending inputPropertyHash for 'filter.includePatterns' to build cache key: d8a9f2d9ae794a50276a5a0dfa38eb3d
Appending inputPropertyHash for 'javaVersion' to build cache key: 4a465f4e625f50133941afa67afe36be
Appending inputPropertyHash for 'jvmArgs' to build cache key: bf91224da4b5d8b522e58297de39ce00
Appending inputPropertyHash for 'maxHeapSize' to build cache key: f6bd6b3389b872033d462029172c8612
Appending inputPropertyHash for 'minHeapSize' to build cache key: f6bd6b3389b872033d462029172c8612
Appending inputPropertyHash for 'options' to build cache key: 396abcdd5bf74169fe99f00fea286aa4
Appending inputPropertyHash for 'options.excludeCategories' to build cache key: d8a9f2d9ae794a50276a5a0dfa38eb3d
Appending inputPropertyHash for 'options.includeCategories' to build cache key: d8a9f2d9ae794a50276a5a0dfa38eb3d
Appending inputPropertyHash for 'reports' to build cache key: 789ba6a82cd7b7e226785c5a85a120d4
Appending inputPropertyHash for 'reports.enabledReports.html' to build cache key: 366534feb771f9d20bb9e1f9d60c90f9
Appending inputPropertyHash for 'reports.enabledReports.html.displayName' to build cache key: f57a2f6288f7292a18cd41afb89347fc
Appending inputPropertyHash for 'reports.enabledReports.html.enabled' to build cache key: f6d7ed39fe24031e22d54f3fe65b901c
Appending inputPropertyHash for 'reports.enabledReports.html.name' to build cache key: 45b63c04ebea9f3558fe60946eb8d98b
Appending inputPropertyHash for 'reports.enabledReports.html.outputType' to build cache key: 0c5a7f9ee0b1630048617c6a027bb3ce
Appending inputPropertyHash for 'reports.enabledReports.junitXml' to build cache key: d0e3ff4c15a23a80b60087a90f1fe7a8
Appending inputPropertyHash for 'reports.enabledReports.junitXml.displayName' to build cache key: 79aaafea310fa007c47c20ec7dadef1a
Appending inputPropertyHash for 'reports.enabledReports.junitXml.enabled' to build cache key: f6d7ed39fe24031e22d54f3fe65b901c
Appending inputPropertyHash for 'reports.enabledReports.junitXml.name' to build cache key: 1fca07d69580ccd153cbc5aff057ccf5
Appending inputPropertyHash for 'reports.enabledReports.junitXml.outputPerTestCase' to build cache key: c06857e9ea338f3f3a24bb78f8fbdf6f
Appending inputPropertyHash for 'reports.enabledReports.junitXml.outputType' to build cache key: 0c5a7f9ee0b1630048617c6a027bb3ce
Appending inputPropertyHash for 'reports.html' to build cache key: 366534feb771f9d20bb9e1f9d60c90f9
Appending inputPropertyHash for 'reports.html.displayName' to build cache key: f57a2f6288f7292a18cd41afb89347fc
Appending inputPropertyHash for 'reports.html.enabled' to build cache key: f6d7ed39fe24031e22d54f3fe65b901c
Appending inputPropertyHash for 'reports.html.name' to build cache key: 45b63c04ebea9f3558fe60946eb8d98b
Appending inputPropertyHash for 'reports.html.outputType' to build cache key: 0c5a7f9ee0b1630048617c6a027bb3ce
Appending inputPropertyHash for 'reports.junitXml' to build cache key: d0e3ff4c15a23a80b60087a90f1fe7a8
Appending inputPropertyHash for 'reports.junitXml.displayName' to build cache key: 79aaafea310fa007c47c20ec7dadef1a
Appending inputPropertyHash for 'reports.junitXml.enabled' to build cache key: f6d7ed39fe24031e22d54f3fe65b901c
Appending inputPropertyHash for 'reports.junitXml.name' to build cache key: 1fca07d69580ccd153cbc5aff057ccf5
Appending inputPropertyHash for 'reports.junitXml.outputPerTestCase' to build cache key: c06857e9ea338f3f3a24bb78f8fbdf6f
Appending inputPropertyHash for 'reports.junitXml.outputType' to build cache key: 0c5a7f9ee0b1630048617c6a027bb3ce
Appending inputPropertyHash for 'scanForTestClasses' to build cache key: f6d7ed39fe24031e22d54f3fe65b901c
Appending inputPropertyHash for 'systemProperties' to build cache key: 265d1e4be81dd31bf6d64077356baabc
Appending inputPropertyHash for 'bootstrapClasspath' to build cache key: 120263b1c90d14337d99983394e9b80c
Appending inputPropertyHash for 'candidateClassFiles' to build cache key: 55d20ab347f972abd56bff69bed8d234
Appending inputPropertyHash for 'classpath' to build cache key: 4498cfffe95fb101b810cc13b9f303c8
Appending inputPropertyHash for 'nonEmptyCandidateClassFiles' to build cache key: 55d20ab347f972abd56bff69bed8d234
Appending outputPropertyName to build cache key: binResultsDir
Appending outputPropertyName to build cache key: reports.enabledReports.html.destination
Appending outputPropertyName to build cache key: reports.enabledReports.junitXml.destination
Appending outputPropertyName to build cache key: reports.html.destination
Appending outputPropertyName to build cache key: reports.junitXml.destination
Build cache key for task ':node:test' is 55fec24f24dcbff40fc0e3ca23161555
Could not store entry 55fec24f24dcbff40fc0e3ca23161555 for task ':node:test' in remote build cache: Broken pipe (Write failed)

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 6m 13s
67 actionable tasks: 7 executed, 4 from cache, 56 up-to-date

Publishing build scan...
https://gradle.com/s/h52wlsqve54ng

The remote build cache was disabled during the build due to errors.
```

**Note:** if I re-run the same task with a smaller subset of tests the cache is successfully updated.
eg. 

```
../gradlew -Dorg.gradle.caching.debug=true clean test --tests net.corda.node.services.vault.* --build-cache --scan

> Task :node:test
Appending taskClass to build cache key: org.gradle.api.tasks.testing.Test_Decorated
Appending classLoaderHash to build cache key: 9b3fed7a57a4142f251290910f3d648a
Appending actionType to build cache key: org.gradle.api.tasks.testing.Test_Decorated
Appending actionClassLoaderHash to build cache key: 9b3fed7a57a4142f251290910f3d648a
Appending inputPropertyHash for 'debug' to build cache key: c06857e9ea338f3f3a24bb78f8fbdf6f
Appending inputPropertyHash for 'defaultCharacterEncoding' to build cache key: d746f44d09fb58d2971f341d24d74c35
Appending inputPropertyHash for 'enableAssertions' to build cache key: f6d7ed39fe24031e22d54f3fe65b901c
Appending inputPropertyHash for 'filter' to build cache key: 3eb586de3301abc137c0d288b893e13d
Appending inputPropertyHash for 'filter.commandLineIncludePatterns' to build cache key: 3bbffd638e3d94c2cafa2cba12fd8d74
Appending inputPropertyHash for 'filter.failOnNoMatchingTests' to build cache key: f6d7ed39fe24031e22d54f3fe65b901c
Appending inputPropertyHash for 'filter.includePatterns' to build cache key: d8a9f2d9ae794a50276a5a0dfa38eb3d
Appending inputPropertyHash for 'javaVersion' to build cache key: 4a465f4e625f50133941afa67afe36be
Appending inputPropertyHash for 'jvmArgs' to build cache key: bf91224da4b5d8b522e58297de39ce00
Appending inputPropertyHash for 'maxHeapSize' to build cache key: f6bd6b3389b872033d462029172c8612
Appending inputPropertyHash for 'minHeapSize' to build cache key: f6bd6b3389b872033d462029172c8612
Appending inputPropertyHash for 'options' to build cache key: 396abcdd5bf74169fe99f00fea286aa4
Appending inputPropertyHash for 'options.excludeCategories' to build cache key: d8a9f2d9ae794a50276a5a0dfa38eb3d
Appending inputPropertyHash for 'options.includeCategories' to build cache key: d8a9f2d9ae794a50276a5a0dfa38eb3d
Appending inputPropertyHash for 'reports' to build cache key: 789ba6a82cd7b7e226785c5a85a120d4
Appending inputPropertyHash for 'reports.enabledReports.html' to build cache key: 366534feb771f9d20bb9e1f9d60c90f9
Appending inputPropertyHash for 'reports.enabledReports.html.displayName' to build cache key: f57a2f6288f7292a18cd41afb89347fc
Appending inputPropertyHash for 'reports.enabledReports.html.enabled' to build cache key: f6d7ed39fe24031e22d54f3fe65b901c
Appending inputPropertyHash for 'reports.enabledReports.html.name' to build cache key: 45b63c04ebea9f3558fe60946eb8d98b
Appending inputPropertyHash for 'reports.enabledReports.html.outputType' to build cache key: 0c5a7f9ee0b1630048617c6a027bb3ce
Appending inputPropertyHash for 'reports.enabledReports.junitXml' to build cache key: d0e3ff4c15a23a80b60087a90f1fe7a8
Appending inputPropertyHash for 'reports.enabledReports.junitXml.displayName' to build cache key: 79aaafea310fa007c47c20ec7dadef1a
Appending inputPropertyHash for 'reports.enabledReports.junitXml.enabled' to build cache key: f6d7ed39fe24031e22d54f3fe65b901c
Appending inputPropertyHash for 'reports.enabledReports.junitXml.name' to build cache key: 1fca07d69580ccd153cbc5aff057ccf5
Appending inputPropertyHash for 'reports.enabledReports.junitXml.outputPerTestCase' to build cache key: c06857e9ea338f3f3a24bb78f8fbdf6f
Appending inputPropertyHash for 'reports.enabledReports.junitXml.outputType' to build cache key: 0c5a7f9ee0b1630048617c6a027bb3ce
Appending inputPropertyHash for 'reports.html' to build cache key: 366534feb771f9d20bb9e1f9d60c90f9
Appending inputPropertyHash for 'reports.html.displayName' to build cache key: f57a2f6288f7292a18cd41afb89347fc
Appending inputPropertyHash for 'reports.html.enabled' to build cache key: f6d7ed39fe24031e22d54f3fe65b901c
Appending inputPropertyHash for 'reports.html.name' to build cache key: 45b63c04ebea9f3558fe60946eb8d98b
Appending inputPropertyHash for 'reports.html.outputType' to build cache key: 0c5a7f9ee0b1630048617c6a027bb3ce
Appending inputPropertyHash for 'reports.junitXml' to build cache key: d0e3ff4c15a23a80b60087a90f1fe7a8
Appending inputPropertyHash for 'reports.junitXml.displayName' to build cache key: 79aaafea310fa007c47c20ec7dadef1a
Appending inputPropertyHash for 'reports.junitXml.enabled' to build cache key: f6d7ed39fe24031e22d54f3fe65b901c
Appending inputPropertyHash for 'reports.junitXml.name' to build cache key: 1fca07d69580ccd153cbc5aff057ccf5
Appending inputPropertyHash for 'reports.junitXml.outputPerTestCase' to build cache key: c06857e9ea338f3f3a24bb78f8fbdf6f
Appending inputPropertyHash for 'reports.junitXml.outputType' to build cache key: 0c5a7f9ee0b1630048617c6a027bb3ce
Appending inputPropertyHash for 'scanForTestClasses' to build cache key: f6d7ed39fe24031e22d54f3fe65b901c
Appending inputPropertyHash for 'systemProperties' to build cache key: 265d1e4be81dd31bf6d64077356baabc
Appending inputPropertyHash for 'bootstrapClasspath' to build cache key: 120263b1c90d14337d99983394e9b80c
Appending inputPropertyHash for 'candidateClassFiles' to build cache key: 55d20ab347f972abd56bff69bed8d234
Appending inputPropertyHash for 'classpath' to build cache key: 4498cfffe95fb101b810cc13b9f303c8
Appending inputPropertyHash for 'nonEmptyCandidateClassFiles' to build cache key: 55d20ab347f972abd56bff69bed8d234
Appending outputPropertyName to build cache key: binResultsDir
Appending outputPropertyName to build cache key: reports.enabledReports.html.destination
Appending outputPropertyName to build cache key: reports.enabledReports.junitXml.destination
Appending outputPropertyName to build cache key: reports.html.destination
Appending outputPropertyName to build cache key: reports.junitXml.destination
Build cache key for task ':node:test' is 0f6972572512a9243cb4a01041da7d19

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 2m 3s
67 actionable tasks: 7 executed, 4 from cache, 56 up-to-date
```

**Comment by josecoll** [comment] 2018-07-18 16:43
I have reproduced exactly the same failure between 2 Virtual Machines (gradle project builder, gradle remote cache) sitting on the same Azure subnet.

**Comment by josecoll** [comment] 2018-07-19 07:58
Hi @wolfs.
The build cache node logs show nothing (maybe I need to up the logging level).
I am going to switch from using the Docker image to using the Java JAR file (and perhaps up the logging level). 
I also checked the default configuration parameters, such as:

"Maximum artifact size
Attempts to store artifacts larger than this limit will be rejected. The default setting of 100 MB is suitable for most builds and should only need to be increased if your builds produce large outputs that you wish to cache."

and can confirm the artifact that is failing to upload is < 100Mb.

In my local gradle build cache:
```
Joses-MacBook-Pro:corda-ci josecoll$ find ~/.gradle/caches/build-cache-1/ -type f -size +10M -exec ls -l {} \;
-rw-r--r--  1 josecoll  staff  13942313 18 Jul 18:11 /Users/josecoll/.gradle/caches/build-cache-1//f88c9f7d36b51dc79db33921991fd0f7
-rw-r--r--  1 josecoll  staff  11748613 18 Jul 16:49 /Users/josecoll/.gradle/caches/build-cache-1//5ced04e838b657d96f376b68c8bcb69c
```

**Comment by ldaley** [comment] 2018-07-19 08:02
Hi @josecoll,

The build scan also tells us that the size is < 10MB: https://scans.gradle.com/s/h52wlsqve54ng/performance/buildCache?cacheDetails=WyJyZW1vdGUtU3RvcmUiXQ#remote-cache-failure-0

It looks like something is closing the connection at the remote end. Can you try running up a cache node locally and trying to reproduce with that? That will confirm that it's something in the networking environment between your build and the node.

**Comment by josecoll** [comment] 2018-07-19 08:30
OK - so yes, running everything locally works fine.

**Comment by ldaley** [comment] 2018-07-19 09:44
@josecoll so something in the network chain is closing the connection when it's over that size. Do you know of any proxies in the way?

**Comment by josecoll** [comment] 2018-07-19 09:59
@ldaley yes - sounds like there are some nasty shenanigans going on within our Azure setup (which we use for CI and hence attempting to add the shared gradle cache to speed execution times).
Will talk to our networking guys and checkout Microsoft Azure forums for any similar reported behaviour.
Cheers.

**Comment by wolfs** [comment] 2018-07-19 10:00
I'll close this issue since it seems to be caused by network problems not related to Gradle.

**Closed by wolfs** 2018-07-19 10:00 UTC
Labels: a:bug, in:build-cache

**Comment by josecoll** [comment] 2018-07-19 18:21
@wolfs can you suggest how best to run the `build-cache-node-4.2.jar` to extract as much networking debug as possible.
I've tried overriding the `log4j2.xml` configuration file to set an additional logger:

```
    <Logger name="com.gradle.buildcache" level="debug" additivity="false">
      <AppenderRef ref="file"/>
    </Logger>
```

but this seems to be ignored at startup:

` java -Dlog4j.configurationFile=./log4j2.xml -jar build-cache-node-4.2.jar --data-dir /opt/build-cache-node `

Thanks.

**Comment by ldaley** [comment] 2018-07-19 21:09
@josecoll are you seeing this timeout when using a locally running node? It’s likely that your network environment is causing this as well.

It’s likely that these requests are not getting to the node at all, given there is no indication of error in the logs.

**Comment by josecoll** [comment] 2018-08-21 14:09
Turns out that on Microsoft Azure Cloud VM’s outbound socket connections have a 4-minute idle timeout.
“This timeout is not adjustable. However, you can use transport (for example, TCP keepalives) or application-layer keepalives to refresh an idle flow and reset this idle timeout if necessary.”

https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-connections#idletimeout

Is there any configuration mechanism to enable keepalives within the Gradle Cache Client ?

**Comment by ldaley** [comment] 2018-08-22 00:34
There's no configuration mechanism. We will need to change this code:

https://github.com/gradle/gradle/blob/4a98d4b5b9eaa2505db2e873ee4c7a5817928601/subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/HttpClientConfigurer.java#L250

To enabled SO_KEEPALIVE. We should do this. 

@josecoll keep in mind that your OS is responsible for actually doing the keep alive. You'll want to check what settings your OS uses for this and confirm they are suitable.

**Comment by ldaley** [comment] 2018-08-22 00:46
@josecoll raised: https://github.com/gradle/gradle/issues/6461

**Comment by dmitrygusev** [comment] 2020-02-05 09:10
it happened to us today, but the reason was load balancer preventing large payloads, from nginx logs:

```
... client intended to send too large body: 4203879 bytes, client: 172.31.11.216, server: ..., request: "PUT /cache/8b9fa10b5b02013cee850ffb577c8b14 HTTP/1.1", host: "..."
```

changing `  client_max_body_size 100M;` to match max cache entry in the server configuration helped
