### ISSUE TITLE
Gradle wrapper task executes successfully, but does not update `gradle-wrapper.jar`

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#23506] opened 2023-01-12 12:14 UTC
I have a Gradle 7.6 project.

[gradlew-update-example.zip](https://github.com/gradle/gradle/files/10401415/gradlew-update-example.zip)

When I run 

```sh
./gradlew wrapper --gradle-version 8.0-rc-1
```

### Expected Behavior

I expect that Gradle updates the wrapper `gradle/wrapper/gradle-wrapper.jar` to version 8.0 RC1.

### Current Behavior

However, the only change I observe is in `gradle/wrapper/gradle-wrapper.properties`

<img width="327" alt="image" src="https://user-images.githubusercontent.com/897017/212062900-5c119c8d-4f14-47bc-b035-1cb4cdea2436.png">

* before:
   ```properties
   distributionBase=GRADLE_USER_HOME
   distributionPath=wrapper/dists
   distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-bin.zip
   networkTimeout=10000
   zipStoreBase=GRADLE_USER_HOME
   zipStorePath=wrapper/dists
   ```
* after: 
   ```properties
   distributionBase=GRADLE_USER_HOME
   distributionPath=wrapper/dists
   distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-rc-1-bin.zip
   networkTimeout=10000
   zipStoreBase=GRADLE_USER_HOME
   zipStorePath=wrapper/dists
   ```

### Steps to Reproduce 

```console
➜  gradlew-update-example git:(main) ./gradlew wrapper --gradle-version 8.0-rc-1
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
Configuration cache is an incubating feature.
Calculating task graph as no configuration cache is available for tasks: wrapper --gradle-version 8.0-rc-1
Type-safe project accessors is an incubating feature.

0 problems were found storing the configuration cache.

See the complete report at file:///.../gradlew-update-example/build/reports/configuration-cache/bwnu31qrxew9zb5lnkk7c5ynw/2hxwuscedtj5wbmkg7wa8b8x4/configuration-cache-report.html

BUILD SUCCESSFUL in 26s
7 actionable tasks: 2 executed, 5 up-to-date
Configuration cache entry stored.
```

When I check `git status`, I can see there is no change to `gradle-wrapper.jar`

```console
➜  gradlew-update-example git:(main) ✗ git status
On branch main
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   gradle/wrapper/gradle-wrapper.properties

no changes added to commit (use "git add" and/or "git commit -a")
```

When I run `./gradlew assemble`, there is still no change to `gradle-wrapper.jar`

```console
➜  gradlew-update-example git:(main) ✗ ./gradlew assemble
Configuration cache is an incubating feature.
Calculating task graph as no configuration cache is available for tasks: assemble
Type-safe project accessors is an incubating feature.

> Task :buildSrc:jar
:jar: No valid plugin descriptors were found in META-INF/gradle-plugins

0 problems were found storing the configuration cache.

See the complete report at file:///.../gradlew-update-example/build/reports/configuration-cache/ey85tqvz98675trimokbo6gyi/5k72mkt8es09evebv5ntxrews/configuration-cache-report.html

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0-rc-1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 14s
10 actionable tasks: 10 executed
Configuration cache entry stored.
```

```console
➜  gradlew-update-example git:(main) ✗ git status        
On branch main
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   gradle/wrapper/gradle-wrapper.properties

no changes added to commit (use "git add" and/or "git commit -a")
```

### Context

Build and Configuration caches are enabled

When I first encountered this problem I created this issue: https://github.com/gradle/gradle/issues/23453

### Your Environment

* Gradle 7.6

**Comment by eskatos** [comment] 2023-01-12 12:27
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/884

Please add your 👍 to that issue.

**Closed by eskatos** 2023-01-12 12:27 UTC
Labels: closed:duplicate
