### ISSUE TITLE
Certain specific characters in the Windows username break compilation of project

### ISSUE THREAD

**Issue by Lolothepro** [gradle/gradle#29213] opened 2024-05-18 18:47 UTC
### Current Behavior

Compilation fails with error :
```
2024-05-13T14:06:13.547+0200 [DEBUG] [org.gradle.process.internal.worker.child.WorkerProcessClassPathProvider] Using worker process classpath: [C:\Users\Loïc\.gradle\caches\8.6\workerMain\gradle-worker.jar]
2024-05-13T14:06:13.550+0200 [INFO] [org.gradle.process.internal.DefaultExecHandle] Starting process 'Gradle Worker Daemon 2'. Working directory: C:\Users\Loïc\.gradle\workers Command: C:\Program Files\Eclipse Adoptium\jdk-21.0.3.9-hotspot\bin\java.exe @C:\Users\Loïc\.gradle\.tmp\gradle-worker-classpath7642616729207495934txt -Xmx1g -Dfile.encoding=UTF-8 -Duser.country=FR -Duser.language=fr -Duser.variant worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Worker Daemon 2'
2024-05-13T14:06:13.550+0200 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTING
2024-05-13T14:06:13.551+0200 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Waiting until process started: Gradle Worker Daemon 2.
2024-05-13T14:06:13.572+0200 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTED
2024-05-13T14:06:13.572+0200 [INFO] [org.gradle.process.internal.DefaultExecHandle] Successfully started process 'Gradle Worker Daemon 2'
2024-05-13T14:06:13.572+0200 [DEBUG] [org.gradle.process.internal.ExecHandleRunner] waiting until streams are handled...
2024-05-13T14:06:13.861+0200 [ERROR] [system.err] Erreur : impossible de trouver ou de charger la classe principale worker.org.gradle.process.internal.worker.GradleWorkerMain
2024-05-13T14:06:13.862+0200 [ERROR] [system.err] Causé par : java.lang.ClassNotFoundException: worker.org.gradle.process.internal.worker.GradleWorkerMain
2024-05-13T14:06:13.889+0200 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
```

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':neoforge:neoFormRecompile'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:130)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:128)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:116)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:331)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:318)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.lambda$execute$0(DefaultTaskExecutionGraph.java:314)
        at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:80)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:314)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.gradle.process.internal.worker.WorkerProcessException: Failed to run Gradle Worker Daemon
        at org.gradle.process.internal.worker.WorkerProcessException.runFailed(WorkerProcessException.java:29)
```

Here, the Windows user name is "Loïc", which causes a compilation error

### Expected Behavior

There shouldn't be any compilation errors

### Context (optional)

I want to compile Minecraft mods for me
NeoGradle source code: https://github.com/neoforged/NeoGradle

### Steps to Reproduce

Try compiling a Minecraft NeoForge mod with a Windows username containing the `ï` character.

### Gradle version

8.7

### Build scan URL (optional)

https://gradle.com/s/yzxqrkcay5vpu

### Your Environment (optional)

`C:\Users\*username with ï*\.gradle\caches\8.6\workerMain\gradle-worker.jar`

**Comment by marchermans** [comment] 2024-05-18 18:50
This is not really a plugin related issue, but more a duplicate of: #27188

**Comment by ljacomet** [comment] 2024-05-21 12:35
This issue will be closed as a duplicate of

* #25322 

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

**Closed by ljacomet** 2024-05-21 12:35 UTC
Labels: a:bug, in:workers, closed:duplicate
