### ISSUE TITLE
Setting sourceSets resource config srcDir property in build script causes build failure due to duplicateStrategy in Windows

### ISSUE THREAD

**Issue by psvkushal** [gradle/gradle#27103] opened 2023-11-20 15:45 UTC
### Current Behavior

In windows 11, with gradle 7.6.1

`
sourceSets {
    main {
        resources {
            srcDir 'src/main/resources'
        }
    }
}
`
When the above property is set and there are any files present in the srcDir location, then build failure occurs with the following message 

> Task :app:processResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processResources'.
> Entry testingFile.txt is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.6.1/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details. 

The build failure could be resolved with commenting out srcDir (since this is a default value) or setting duplicateStrategy to any of the available values. 

### Expected Behavior

The build script should have been executed without any issue. without the need to set duplicateStrategy or commenting out the srcDir

### Context (optional)

https://discuss.gradle.org/t/using-sourcesets-along-with-jar-task-in-gradle-build-causing-build-failure-in-windows-due-to-duplicatestrategy-not-being-set/47034
The discussion related to this bug has occurred in the gradle forum which might give additional context.

### Steps to Reproduce
mentioned in this repo
https://github.com/psvkushal/gradle-sourceSets-buildFailure-Windows

### Gradle version

7.6.1

### Your Environment (optional)

Windows 11, the issue is not occurring in macOS

**Comment by cobexer** [comment] 2023-11-21 13:42
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #17236

Please add your use case and 👍 to that issue.
***
`srcDir` is additive, you should use [setSrcDirs](https://docs.gradle.org/current/javadoc/org/gradle/api/file/SourceDirectorySet.html#setSrcDirs-java.lang.Iterable-) to override the default value.

**Closed by cobexer** 2023-11-21 13:42 UTC
Labels: a:bug, to-triage

**Comment by psvkushal** [comment] 2023-11-22 13:33
Hi @cobexer if possible can you elaborate on what would additive here would mean here? or point me to any resource where this is mentioned in context to srcDir?
Main issue here is I need to do case handling when I am working with windows which is not required for macOS any reason for difference in behaviour between the 2 OS? I was not able to get any answer in the forum so asking the question here it self.

**Comment by cobexer** [comment] 2023-12-22 07:45
Sorry for the late reply!

From the [Javadoc](https://docs.gradle.org/current/javadoc/org/gradle/api/file/SourceDirectorySet.html#srcDir-java.lang.Object-):
> Adds the given source directory to this set.

And for:
> Main issue here is I need to do case handling when I am working with windows which is not required for macOS any reason for difference in behaviour between the 2 OS?

I don't see how Windows and Mac OS would differ here since both default to case-insensitive filesystems. If you do see different behavior and can create a reproducer, please file that as a separate issue.

**Comment by lapo-luchini** [comment] 2024-01-09 15:13
> `srcDir` is additive, you should use [setSrcDirs](https://docs.gradle.org/current/javadoc/org/gradle/api/file/SourceDirectorySet.html#setSrcDirs-java.lang.Iterable-) to override the default value.

Just in case anyone is puzzled by this as I was, I found an example to do that (in either Kotlin or Groovy) [in this URL](https://docs.gradle.org/current/userguide/java_plugin.html#ex-custom-java-source-layout):

```Groovy
srcDirs = [ 'src/main/resources' ]
```

**Comment by psvkushal** [comment] 2024-01-14 09:47
@cobexer I am sorry it took me some time, but I raised a seperate issue here https://github.com/gradle/gradle/issues/27685.
