### ISSUE TITLE
Configured extra properties on Test task are not accessible on execution with configuration cache enabled

### ISSUE THREAD

**Issue by breskeby** [gradle/gradle#24172] opened 2023-03-06 12:47 UTC
### Expected Behavior
We declare extra properties for test tasks using

```
test.getExtensions().getExtraProperties().set("dumpOutputOnFailure", true);
```

then late when executing this test task we access this extra property again in a test listener:

```
Object errorReportingEnabled = testTask.getExtensions().getExtraProperties().get("dumpOutputOnFailure");
```

This worked with gradle < 8.0.2

### Current Behavior

The configuration above is broken with the following error message:

```
* What went wrong:
Execution failed for task ':lib:test'.
> Cannot get property 'dumpOutputOnFailure' on extra properties extension as it does not exist
```

### Context
We ran into this with updating to gradle 8.0.2 (from 7.6) as we couldn't update to earlier gradle 8.x versions due to other blocking issues. So it might be a general problem since 8.0.

### Steps to Reproduce 

Find attached a simple project to reproduce. If you run the attached project with

```
./gradlew :lib:test --rerun-tasks --scan
```

the build succeeds. running in addition with `--configuration-cache` makes it fail as described above. This worked with earlier gradle versions.

[testExtraProperties.zip](https://github.com/gradle/gradle/files/10898281/testExtraProperties.zip)

### Your Environment

Build scan URL:

failure: https://scans.gradle.com/s/fcpr4jdqcpftw

**Comment by bamboo** [comment] 2023-03-06 13:31
Related to #22522

**Comment by bamboo** [comment] 2023-03-06 16:09
Hi @breskeby! 

I'm afraid this has never worked as intended. It likely seemed to work before 8.0 because the configuration cache was not being loaded on the very first run and problems like that were not being reported.

Moving forward, Gradle will report extra property reads at task execution time as configuration cache problems, see #22522.

**Comment by bamboo** [comment] 2023-03-07 15:01
Closing as not planned. The recommended way to pass values to tasks is to use task properties.

**Closed by bamboo** 2023-03-07 15:01 UTC
Labels: a:bug, to-triage

**Comment by breskeby** [comment] 2023-03-07 15:10
by task properties you mean actual properties of the class implementation? meaning I'd need to extend the Test class?

**Comment by bamboo** [comment] 2023-03-07 16:20
Dynamic properties would work as well:
```kotlin
tasks.register("test") {
    inputs.property("dumpOutputOnFailure", true)
    doLast {
        val dumpOutputOnFailure: Boolean by inputs.properties
        println("dump: $dumpOutputOnFailure")
    }
}
```
