### ISSUE TITLE
Fail if Jar task replaces output of another

### ISSUE THREAD

**Issue by carlolf** [gradle/gradle#1624] opened 2017-03-21 12:52 UTC
### Expected Behavior
The manual states for MavenPublishing two methods a closure might use:
- artifact: with a task argument serving as the output of the given task
- setArtifacts: argument list for the artifacts
So, my expectation is, either should work.

### Current Behavior
Using artifact method with the task argument, this error occurs:

> Execution failed for task ':de.uvdms.jadice.common:publishMavenJavaPublicationToMavenRepository'.
> Failed to publish publication 'mavenJava' to repository 'maven'
   > Invalid publication 'mavenJava': multiple artifacts with the identical extension and classifier ('jar', 'null').

Using the method artifacts with task argument  in the form `[ serverJarWithoutAnnoProfile ]`, the regular jar is published - which I do not want.

### Context
What I'm trying to do: NOT to publish the regular built jar, but a special jar built by calling a user task (serverJarWithoutAnnoProfile).
### Steps to Reproduce (for bugs)
This is my user task:
`task serverJarWithoutAnnoProfile(type: Jar) { 
   archiveName jadiceCommonWebappJar
   from(sourceSets.main.output)   
}`
The publish closure is this:
`publishing.publications {   
   mavenJava(MavenPublication) {                 
      artifacts = [ serverJarWithoutAnnoProfile ]      
      //artifact serverJarWithoutAnnoProfile 
   }
}`

### Your Environment
I use Gradle 3.4.1 with JDK 1.7 under Windows 10.

**Comment by oehme** [comment] 2017-09-15 17:29
Your `Jar` task needs to define a `classifier`, otherwise you are overwriting the main `Jar` accidentally. We should fail on this earlier to make that clear to the user.

**Comment by oehme** [comment] 2017-09-15 17:30
Duplicate of https://github.com/gradle/gradle/issues/2299

**Closed by oehme** 2017-09-15 17:30 UTC
Labels: a:bug, from:contributor, in:jvm-platform

**Comment by carlolf** [comment] 2017-09-20 10:04
Hi Stefan,
I tried with a ` classifier`. But this does no solve my problem. I want to upload this special jar now qualified with a classifier. But it does not get uploaded by the puplish task. Instead, publish uploads the 'normal' jar - this is not wanted. See the closure above.
I have no idea how I can solve this case if the publish closure does not work.

**Comment by carlolf** [comment] 2017-09-20 11:15
Ah, now I got it! I had to set the `classifier` qualifiying the `artifact `level.

One problem I need to solve: how to exclude the normal jar from uploading? Is there a skip statement?

**Comment by oehme** [comment] 2017-09-20 14:39
Calling `artifacts = [...]` should overwrite which artifacts are published. If that doesn't work, could you create a small example project showing the problem?

**Comment by carlolf** [comment] 2017-10-20 09:52
yes, thank you. Declaring `artifacts = [serverJarWithoutAnnoProfile , sourcesJar]` did the correct job.
