### ISSUE TITLE
Incorrect cache behavior when file name contains special characters

### ISSUE THREAD

**Issue by ketan** [gradle/gradle#3043] opened 2017-09-27 16:13 UTC
### Current Behavior

I've turned on caching for some tasks that generate dirnames with special characters, and it seems that the gradle cache is escaping the characters (perhaps using URL encoder?)

### Steps to Reproduce (for bugs)

Create the following files:

* `build.gradle`

    ```gradle
    task badCacheTask(type: Exec) {
      inputs.file('foo.sh')
      outputs.dir("output")
      outputs.cacheIf { true }
      commandLine = ['bash', 'foo.sh']
    }
    ```
* `foo.sh` (creates a bunch of files with special chars)
    ```shell
    bad_dir='output/dir/#/special$char'
    bad_file='f!ile .txt'
    mkdir -p "${bad_dir}"
    echo "foo" > "${bad_dir}/${bad_file}"
    ```
* run the following:
    ```shell
    gradle badCacheTask
    mv output good-cache
    gradle badCacheTask
    tree output good-cache
    ```
* The output of the above command looks like:
   ```plain
    output
    └── dir
        └── %23
            └── special$char
                └── f!ile%20.txt
    good-cache
    └── dir
        └── #
            └── special$char
                └── f!ile\ .txt
    ```

As can be seen in the output above. The actual state of the `output` dir after cache restoration is not the same as expected.

* The [cache file contents](https://scans.gradle.com/s/2eytczf3jj74q/timeline?task=63ipnljja4psg) from the cache key `5a1a4e7a01d4080c60ba674aac2cfd8a` are as follows:
    ```plain
    $ tar -ztvf ~/.gradle/caches/build-cache-1/5a1a4e7a01d4080c60ba674aac2cfd8a
    -rw-r--r-- 0/0             342 2017-09-27 21:35 METADATA
    drwxr-xr-x 0/0               0 2017-09-27 21:35 property-$1/
    drwxr-xr-x 0/0               0 2017-09-27 21:35 property-$1/dir//
    drwxr-xr-x 0/0               0 2017-09-27 21:35 property-$1/dir/%23//
    drwxr-xr-x 0/0               0 2017-09-27 21:35 property-$1/dir/%23/special$char//
    -rw-r--r-- 0/0               4 2017-09-27 21:35 property-$1/dir/%23/special$char/f!ile%20.txt
    ```

### Your Environment

 * Build scan URL: https://scans.gradle.com/s/2eytczf3jj74q

**Comment by lptr** [comment] 2017-09-28 07:52
Thanks for reporting. Looks like we have a problem handling spaces in cached file names since 4.2.

**Comment by ketan** [comment] 2017-09-28 07:53
> Looks like we have a problem handling spaces in cached file names since 4.2

I don't believe this is limited to just spaces — in my case the pound character `#` is also escaped. I don't know if there are other chars are escaped as well.

**Comment by lptr** [comment] 2017-09-28 08:16
Indeed, the problem seems to be caused by any character that is escaped in URIs: spaces, percent signs etc.

**Comment by lptr** [comment] 2017-09-28 16:32
PR merged.

**Closed by lptr** 2017-09-28 16:32 UTC
Labels: a:bug, affects-version:4.2, from:contributor
