### ISSUE TITLE
Composite build with caller-provided properties

### ISSUE THREAD

**Issue by swankjesse** [gradle/gradle#31638] opened 2024-12-09 20:27 UTC
### Expected Behavior

I’d like to `includeBuild()` and set a property on the included build, as if I were invoking it with `-PmyProperty=someValue`.

### Current Behavior (optional)

The best I can come up with is to write some code that edits the included build’s `gradle.properties` before I include it, and this is pretty clumsy. In particular it exposes unexpected edits to engineers working in the projects who aren’t otherwise interested in this mechanism.

### Context

My included build is set up to omit some optional modules by default, but I absolutely need 'em in from the calling build, so I was hoping to request it that way.

Here’s a possible syntax to implement this feature.

```kotlin
  includeBuild("subproject") {
    property("myProperty", "someValue")
    dependencySubstitution {
      ...
    }
  }
```

I raised this issue in the Gradle Community slack [here](https://gradle-community.slack.com/archives/CAHSN3LDN/p1733772139256779).

**Comment by jbartok** [comment] 2024-12-10 13:08
This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/21144

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

**Closed by jbartok** 2024-12-10 13:08 UTC
Labels: a:feature, to-triage
