### ISSUE TITLE
TestKit with build.gradle.kts and withDebug(true) fails with CNF SourceSet

### ISSUE THREAD

**Issue by ysb33r** [gradle/gradle#9246] opened 2018-11-25 20:18 UTC
The issue is similar to #492 and #862, but both issues were closed in May 2018, with a fix sumitted by @bamboo. However it seems there is again a related issue and Gradle 5.0 close to release I would have thought it to be resolved. I have originally described the problem on the [discussion forum](https://discuss.gradle.org/t/test-kotlin-dsl-from-testkit-if-plugin-was-written-in-groovy/29617/3).

The issue is seen when testing a plugin written in Groovy, but with TestKit and using `build.gradle.kts`. If the build script is executed as a normal build there is no problem.

### Expected Behavior

I am expecting the behaviour of TesKit wil `build.gradle.kts` to be the same as when running a Kotlin-DSL-based build.

### Current Behavior

I see this error when testing with 

```
org.gradle.testkit.runner.UnexpectedBuildFailure: Unexpected build execution failure in ..../asciidoctor-gradle-plugin/asciidoctor-gradle-jvm/build/gradleTest/complex-jvm-setup/4.10.2 with arguments [runGradleTest, --init-script, ..../asciidoctor-gradle-plugin/asciidoctor-gradle-jvm/build/gradleTest/init.gradle, --full-stacktrace, --info, --rerun-tasks, -i, -s, --console=plain, --warning-mode=all]

Output:
Using 4 worker leases.
Starting Build
Settings evaluated using settings file '..../asciidoctor-gradle-plugin/asciidoctor-gradle-jvm/build/gradleTest/complex-jvm-setup/4.10.2/settings.gradle'.
Projects loaded. Root project using build file '..../asciidoctor-gradle-plugin/asciidoctor-gradle-jvm/build/gradleTest/complex-jvm-setup/4.10.2/build.gradle.kts'.
Included projects: [root project '4.10.2']

> Configure project :
Evaluating root project '4.10.2' using build file '..../asciidoctor-gradle-plugin/asciidoctor-gradle-jvm/build/gradleTest/complex-jvm-setup/4.10.2/build.gradle.kts'.
This JVM does not support getting OS memory, so no OS memory status updates will be broadcast

FAILURE: Build failed with an exception.

* What went wrong:
java.lang.ExceptionInInitializerError (no error message)
> Type org.gradle.api.tasks.SourceSet not present

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
java.lang.ExceptionInInitializerError
	at org.gradle.kotlin.dsl.provider.plugins.DefaultProjectSchemaProvider.schemaFor(DefaultProjectSchemaProvider.kt:35)
	at org.gradle.kotlin.dsl.accessors.AccessorsClassPathKt.schemaFor(AccessorsClassPath.kt:127)
	at org.gradle.kotlin.dsl.accessors.AccessorsClassPathKt.jitProjectSchemaOf(AccessorsClassPath.kt:104)
	at org.gradle.kotlin.dsl.accessors.AccessorsClassPathKt.configuredProjectSchemaOf(AccessorsClassPath.kt:86)
	at org.gradle.kotlin.dsl.accessors.AccessorsClassPathKt.buildAccessorsClassPathFor(AccessorsClassPath.kt:72)
	at org.gradle.kotlin.dsl.accessors.AccessorsClassPathKt.access$buildAccessorsClassPathFor(AccessorsClassPath.kt:1)
	at org.gradle.kotlin.dsl.accessors.AccessorsClassPathKt.accessorsClassPathFor(AccessorsClassPath.kt:58)
	at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.accessorsClassPathFor(Interpreter.kt:418)
	at Program.execute(Unknown Source)
	at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.eval(Interpreter.kt:498)
	at org.gradle.kotlin.dsl.execution.Interpreter.eval(Interpreter.kt:184)
	at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator.evaluate(KotlinScriptEvaluator.kt:112)
	at org.gradle.kotlin.dsl.provider.KotlinScriptPluginFactory$create$1.invoke(KotlinScriptPluginFactory.kt:51)
	at org.gradle.kotlin.dsl.provider.KotlinScriptPluginFactory$create$1.invoke(KotlinScriptPluginFactory.kt:36)
	at org.gradle.kotlin.dsl.provider.KotlinScriptPlugin.apply(KotlinScriptPlugin.kt:34)
	at org.gradle.configuration.BuildOperationScriptPlugin$1$1.run(BuildOperationScriptPlugin.java:69)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.configuration.BuildOperationScriptPlugin$1.execute(BuildOperationScriptPlugin.java:66)
	at org.gradle.configuration.BuildOperationScriptPlugin$1.execute(BuildOperationScriptPlugin.java:63)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:48)
	at org.gradle.configuration.BuildOperationScriptPlugin.apply(BuildOperationScriptPlugin.java:63)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:41)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject.run(LifecycleProjectEvaluator.java:105)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:68)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:687)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:140)
	at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:60)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:41)
	at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuild.run(DefaultGradleLauncher.java:274)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.initialization.DefaultGradleLauncher.configureBuild(DefaultGradleLauncher.java:182)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:141)
	at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:124)
	at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:77)
	at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:74)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:154)
	at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:38)
	at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:96)
	at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:74)
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:55)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.run(RunAsBuildOperationBuildActionRunner.java:50)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:45)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:47)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:44)
	at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:79)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:44)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:62)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:34)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:46)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
	at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:60)
	at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:41)
	at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:58)
	at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:37)
	at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:180)
	at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:124)
	at org.gradle.tooling.internal.provider.DefaultConnection.getModel(DefaultConnection.java:208)
	at org.gradle.tooling.internal.consumer.connection.CancellableModelBuilderBackedModelProducer.produceModel(CancellableModelBuilderBackedModelProducer.java:53)
	at org.gradle.tooling.internal.consumer.connection.PluginClasspathInjectionSupportedCheckModelProducer.produceModel(PluginClasspathInjectionSupportedCheckModelProducer.java:41)
	at org.gradle.tooling.internal.consumer.connection.AbstractConsumerConnection.run(AbstractConsumerConnection.java:59)
	at org.gradle.tooling.internal.consumer.connection.ParameterValidatingConsumerConnection.run(ParameterValidatingConsumerConnection.java:47)
	at org.gradle.tooling.internal.consumer.DefaultBuildLauncher$1.run(DefaultBuildLauncher.java:89)
	at org.gradle.tooling.internal.consumer.DefaultBuildLauncher$1.run(DefaultBuildLauncher.java:83)
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:84)
	at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45)
	at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58)
	at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.TypeNotPresentException: Type org.gradle.api.tasks.SourceSet not present
	at org.gradle.api.reflect.TypeOf.captureTypeArgument(TypeOf.java:260)
	at org.gradle.api.reflect.TypeOf.<init>(TypeOf.java:98)
	at org.gradle.kotlin.dsl.provider.plugins.DefaultProjectSchemaProviderKt$$special$$inlined$typeOf$2.<init>(DefaultProjectSchemaProvider.kt:134)
	at org.gradle.kotlin.dsl.provider.plugins.DefaultProjectSchemaProviderKt.<clinit>(DefaultProjectSchemaProvider.kt:156)
	... 109 more
Caused by: java.lang.ClassNotFoundException: org.gradle.api.tasks.SourceSet
	... 113 more
```

### Context

This error is currently seen in  the [Asciidoctor Gradle plugin 2.0 development](https://github.com/asciidoctor/asciidoctor-gradle-plugin/tree/development-2.0).  We are adding both integration tests (direct with TestKit) and compatibility tests (with [GradleTest](https://gitlab.com/ysb33rOrg/gradleTest)) to ensure that the plugin suite privdes a first class experience to Kotlin DL users.

It is possible that the issue is related to multi-project builds and I have used `build.gradle.kts` in a simple plugin without a problem.

This issue is preventing us from writing any testable code snippets of the documentation and verifying that the plugin suite are fully compatibile with the Kotlin DSL.

### Steps to Reproduce (with an integration test)

[WarningsAsErrorsFunctionalSpec.groovy](https://github.com/ysb33r/asciidoctor-gradle-plugin/blob/4924466e3e0ba96001f6c95a666d80cea3256f07/asciidoctor-gradle-jvm/src/intTest/groovy/org/asciidoctor/gradle/jvm/WarningsAsErrorsFunctionalSpec.groovy#L63)

Currently this test is set to `@Ignore`. Remove that line and run

```bash
$ ./gradlew :asciidoctor-gradle-jvm:intTest --tests WarningsAsErrorsFunctionalSpec
```

Note in this case as there is three failing tests, which are executed in random order. The first test always fails with not finding `SourceSet` whereas the second two simply cannot initialise the Kotlin DSL provider. 

### Steps to Reproduce (with a compatibility test)

There are two examples here. One is very simple without even loading asciidoctor, the second is more complex with actual Asciidoctor tasks.

[#1 Simple project](https://github.com/ysb33r/asciidoctor-gradle-plugin/tree/kotlin-inttest/asciidoctor-gradle-base/src/gradleTest/apply-the-base-plugin)

Run as 

```bash
$ ./gradlew :asciidoctor-gradle-base:gradleTest -DgradleTest.versions=4.10.2
```

This will always fail. 

[#2 Complex Asciidoctor project](https://github.com/ysb33r/asciidoctor-gradle-plugin/tree/kotlin-inttest/asciidoctor-gradle-jvm/src/gradleTest/complex-jvm-setup)

Run as
 
```
$ ./gradlew :asciidoctor-gradle-jvm:gradleTest  -DgradleTest.versions=4.10.2 -DgradleTest.include=*jvm-setup*
```

There are two tests in case. The Groovy opne will pass, but the Kotlin one will fail.

### Your Environment
Gradle 4.10.2, 5.0-rc-5 (Mac, Linux & Windows)
JDK8

**Comment by eskatos** [comment] 2019-04-25 16:01
Closing as duplicate of #6862

**Closed by eskatos** 2019-04-25 16:01 UTC
Labels: a:bug, from:contributor, in:test-kit
