### ISSUE TITLE
No java incremental compile after compile failure - "unable to get source-classes mapping relationship from last compilation."

### ISSUE THREAD

**Issue by asvitkine** [gradle/gradle#13601] opened 2020-06-26 10:37 UTC
### Expected Behavior

Incremental builds should work.

### Current Behavior

They don't seem to.
--info prints this message:
"Full recompilation is required because unable to get source-classes mapping relationship from last compilation."

### Context

This is causing slow compiles for our project.
See investigation on our side in:
https://github.com/triplea-game/triplea/issues/6841

### Steps to Reproduce 

1. Checkout this project: https://github.com/triplea-game/triplea
2. Do a build via: ./gradlew :game-core:compileJava 
3. Change a line in ImageScrollModel.java in that project
4. Do another build via: ./gradlew :game-core:compileJava --info

Expected behavior is incremental compile, but instead get a full compile with the above error message.

It seems that this would be caused when sourceFileClassNameConverter.isEmpty() is true:
https://github.com/gradle/gradle/blob/f71651cd8bf8300268d2759004a68863081958fd/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/JavaRecompilationSpecProvider.java#L66

But per my investigation (see linked issue), it seems the source-classes-mapping.txt files exist and have content. Is there an issue with finding them at the wrong path or with their parser perhaps?

### Your Environment

```

------------------------------------------------------------
Gradle 6.5
------------------------------------------------------------

Build time:   2020-06-02 20:46:21 UTC
Revision:     a27f41e4ae5e8a41ab9b19f8dd6d86d7b384dad4

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          12.0.2 (Oracle Corporation 12.0.2+10)
OS:           Mac OS X 10.14.6 x86_64
```
Build scan URL: https://scans.gradle.com/s/zqmgbuwjtcipy/timeline?outcomeFilter=SUCCESS,FAILED&sort=longest

**Comment by bigdaz** [comment] 2021-03-09 19:44
For me, the full recompile only occurs after a previous compile failure. I've reworded the bug title to reflect this.
Please let me know if you think I'm not correct in this.

**Comment by sfc-gh-akazantsev** [comment] 2021-03-09 23:56
Hi guys, this really feels like a severe issue for us.

We are trying to migrate from maven to gradle. While maven does not have reasonable incremental compile this get mitigated via use if IntelliJ incremental compile.
One of the benefits we are looking for is to delegate IDE (IntelliJ) build to gradle so there is no difference between CLI and IDE. 

But our early experiments show that this issue causes is huge productivity hit for us. While in active development code gets broken quite often. And ANY compilation that fails triggers full recompile after that (as compile failure deletes all source mappings). Full recompile takes up to 10 minutes and is unacceptable. 

In similar usecase/situation IntelliJ incremental compilation is **instant**. 

It would be really nice if this issue can be prioritized! Thank you!

**Comment by oehme** [comment] 2021-03-16 15:29
Duplicate of #13766

**Closed** 2022-07-08 12:16 UTC
Labels: a:bug, in:jvm-ecosystem, @execution
