### ISSUE TITLE
Provide archetype functionality (a la maven)

### ISSUE THREAD

**Issue by gonzalad** [gradle/gradle#3840] opened 2017-12-18 20:13 UTC
Provide an archetype-like functionnality similar to that of maven.

The projects generated from an archetype can be a single module or multi-module project.

The archetype needs to support some templating technology to allow easy content generation.

Some JIRAs already exist for this need, but those are closed and afaik as of now, gradle doesn't support yet a maven like archetype functionnality.
i.e. 
https://issues.gradle.org/browse/GRADLE-1387
https://issues.gradle.org/browse/GRADLE-1289

**Comment by aadrian** [comment] 2018-03-21 19:28
@gonzalad SBT (the default build tool for Scala) https://www.scala-sbt.org/1.x/docs/sbt-new-and-Templates.html is using simple GitHub repos as templates. It's very flexible, but still does not exclude to use the "official" templates to ensure quality.

Other tools even have interactive input: http://yeoman.io/codelab/scaffold-app.html so that the user can override the default parameters of a template to get a more suitable and helpful initial project :) .

**Comment by aemaem** [comment] 2018-10-29 12:28
There is a plugin for this one: https://plugins.gradle.org/plugin/com.orctom.archetype

**Comment by gonzalad** [comment] 2018-10-29 13:43
@aemaem : Agreed, there are 2/3 gradle plugins out there for that.

My point when I raised this topic is that there's no such functionnality in gradle core plugins (maintained by gradle core devs).

**Comment by aemaem** [comment] 2018-10-29 14:30
@aemaem Totally agree with you!

**Comment by aadrian** [comment] 2022-04-16 09:30
Could we please have Bots disabled instead of tickets with real issues ?

At the moment, among all tools targeting JVM, Gradle seems to have the worst project setup experience.

Thank you.

**Comment by jifeiiii** [comment] 2022-04-18 08:57
@jjohannes Any progress here?

**Comment by jjohannes** [comment] 2022-04-19 06:12
@jifeiiii I cannot answer that as I am no longer part of the Gradle team.

FWIW, there is `gradle init` and there has been some progress on that over the years. I think it is pretty good to start certain types of projects.

Although, it does not provide a hook to put in you own "templates" about which this feature request is. 

I personally think what SBT offers, which you linked back in 2018, is pretty neat and it would be great to have something similar for Gradle. I think this could be built as community tool/plugin first. It does not necessarily need to be a part of Gradle core.

**Comment by jifeiiii** [comment] 2022-04-27 14:12
@bmuschko

**Comment by code-magician323** [comment] 2022-05-20 15:08
Agree. Super important and anticipated issue

**Comment by ljacomet** [comment] 2023-09-06 12:51
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #1686

Please add your use case and 👍 to that issue.

**Closed by ljacomet** 2023-09-06 12:51 UTC
Labels: in:build-init-plugin, a:feature
