### ISSUE TITLE
Play plugin stops working with lombok (annotation processor) starting from version 3.4

### ISSUE THREAD

**Issue by ymwang1984** [gradle/gradle#2337] opened 2017-06-21 17:42 UTC
Play plugin stops working with lombok (annotation processor) starting from version 3.4
### Expected Behavior

[Lombok](https://projectlombok.org/) is a compileOnly dependency that save people from boiler plate code such as getter, setter and log. It uses very short annotations instead of all the codes. Gradle 2.12 introduces compileOnly configuration for Java projects which is very suitable for lombok. For a [Play](https://docs.gradle.org/current/userguide/play_plugin.html) project, it should work the same way as a Java project.
### Current Behavior

For Gradle 3.4+, it does not seem to compile lombok. All lombok imports in the Java file are correctly recognized. But the annotations in the source files are not really processed and honored.
### Context

We cannot compile a production Play project at LinkedIn which is a blocking issue.

We cannot simply roll back to Gradle 3.3 and lower because there are specific issues for those versions as well, such as

https://discuss.gradle.org/t/gradle-3-x-behavior-change-wrt-classifier-artifact-resolution-in-ivy-modules/21226

https://discuss.gradle.org/t/problem-with-gradle-play-plugin-could-not-copy-manifest-mf-multiple-entries-with-same-key/19880

### Steps to Reproduce (for bugs)

We created a small [repo](https://github.com/linjer/lombok-play-gradle) to reproduce the issue.

This works for 3.3

`gradle wrapper --gradle-version 3.3`
`./gradlew compilePlayBinaryScala`

This does not work for 3.4

`gradle wrapper --gradle-version 3.4`
`./gradlew compilePlayBinaryScala`

### Your Environment

 * Build scan URL:

**Comment by ymwang1984** [comment] 2017-06-21 17:45
We also verified that the Java plugin (Gradle 3.5) still works with lombok. Just not the Play plugin.

**Comment by ymwang1984** [comment] 2017-06-21 19:55
Now we tend to believe that the issue comes from the Scala plugin.

We could formulate the repo (just rename directory "app/controller" to "src/main/scala/controller") to Scala to reproduce the exact same error.

build.gradle

apply plugin: 'scala'

repositories {
    mavenCentral()
}

dependencies {
    compile 'org.scala-lang:scala-library:2.10.4'
    compile group: 'org.projectlombok', name: 'lombok', version: '1.16.2'
}

**Comment by ymwang1984** [comment] 2017-06-22 15:54
Could be related to https://github.com/gradle/gradle/pull/2281

**Comment by benmccann** [comment] 2017-06-22 17:14
Yes, they're definitely related. Good find!

**Comment by ymwang1984** [comment] 2017-06-27 17:13
Verified that #2281 works and we've published an internal forked Gradle version to unblock teams

**Comment by eriwen** [comment] 2017-07-07 15:25
@ymwang1984 Can you provide a really simple example that exposes this issue, so that we can turn it into an integration test?

**Comment by eriwen** [comment] 2017-07-07 15:32
@ymwang1984 Nevermind! We have an example :)

**Comment by ymwang1984** [comment] 2017-07-10 19:37
@eriwen 

Thank you for the update. We are not blocked by this but we do hope the fix will be merged to master soon.

**Comment by bmuschko** [comment] 2017-07-11 21:38
> Now we tend to believe that the issue comes from the Scala plugin.

@ymwang1984 I couldn't reproduce the same issue with a plain Scala project. Could you please provide a repository on GitHub that demonstrates the issue?

**Comment by ymwang1984** [comment] 2017-07-12 00:04
@bmuschko 

https://github.com/linjer/lombok-play-gradle

It is a Play repo (which uses Scala compiler). Thanks.

**Comment by bmuschko** [comment] 2017-07-12 00:30
@ymwang1984 I already had a look at that example. That's a Play app but not a plain Scala project. [In another comment](https://github.com/gradle/gradle/issues/2337#issuecomment-310187489) you hinted that the issue would also occur in a Scala project that doesn't apply the Play plugin. The code you posted there does not produce the issue for me.

**Comment by ymwang1984** [comment] 2017-07-12 00:36
@bmuschko 

I am literally facing the same issue as https://github.com/gradle/gradle/issues/1498

In the issue, the reporter posted a sample minimal Scala repo: https://github.com/blendmaster/gradle-1498

I can create another one if that is necessary.

**Comment by bmuschko** [comment] 2017-07-12 00:55
@ymwang1984 Thanks for that pointer. I assume this is only an issue for Java classes? All the examples only use Java classes but no Scala classes.

**Comment by ymwang1984** [comment] 2017-07-12 01:01
@bmuschko 

Yes, currently the issue all comes from Java classes + lombok, etc. inside the company as people try to leverage lombok to reduce boilerplate code.

**Comment by bmuschko** [comment] 2017-07-12 15:14
Internal review: https://github.com/gradle/gradle/pull/2281

**Comment by ymwang1984** [comment] 2017-07-12 20:40
@bmuschko 

Thank you for merging the request! 

We internally patched this pull request and forked a Gradle version to unblock product teams. And the pull request was confirmed by folks to fix the issue for now.

Since the pull request has been merged, I can close this issue, right?

**Comment by bmuschko** [comment] 2017-07-12 20:42
@ymwang1984 We are still code reviewing the changes internally. I am going to close it when ready and provide you with a distribution URL so you can try it out with your own project.

**Comment by ymwang1984** [comment] 2017-07-12 20:43
@bmuschko  Thank you.

**Comment by bmuschko** [comment] 2017-07-14 12:43
I'd appreciate if you could test out a nightly build on your project to verify the fix: https://services.gradle.org/distributions-snapshots/gradle-4.1-20170714074750+0000-bin.zip

**Closed by bmuschko** 2017-07-14 12:43 UTC
Labels: a:bug, from:contributor, in:jvm-platform

**Comment by ymwang1984** [comment] 2017-07-14 15:31
@bmuschko 

Most likely I will NOT be able to test the nightly-build version on our production Play projects because there are compatibility issues for LinkedIn's internal Gradle plugin with 4.0 for the time being. 

But we've tested the forked version of 3.5 (with PR 2281 applied) on production Play projects and it worked. Thank you.
