### ISSUE TITLE
PMD exclude rules are failing with IllegalArgumentException: "Unable to exclude rules"

### ISSUE THREAD

**Issue by asarkar** [gradle/gradle#1970] opened 2017-05-09 01:01 UTC
Upgraded to using PMD 5.6.1, now the following rules in our custom ruleset are failing the build with

> java.lang.IllegalArgumentException: Unable to exclude rules [RuleNameGoesHere]; perhaps the rule name is mispelled?

[DataflowAnomalyAnalysis](https://pmd.github.io/pmd-5.6.1/pmd-java/rules/java/controversial.html#DataflowAnomalyAnalysis)
[ShortClassName](https://pmd.github.io/pmd-5.6.1/pmd-java/rules/java/naming.html#ShortClassName)
[UselessParentheses](https://pmd.github.io/pmd-5.6.1/pmd-java/rules/java/unnecessary.html#UselessParentheses)

The rule names match up with latest PMD doc (given above) so they are **not** misspelled (ironically, the error message misspells the word `misspelled`). Why are these failing? 
In addition, the plugin should provide a list of all available rules (perhaps in INFO mode) instead of a pretty useless error message that leaves the user in the dark.

**Comment by bmuschko** [comment] 2017-05-11 13:47
Can you please provide a reproducible example? I am not able to reproduce the issue.

> The rule names match up with latest PMD doc (given above) so they are not misspelled (ironically, the error message misspells the word misspelled).

The error message is emitted from the PMD Ant task. The Gradle plugin is wrapping the Ant task and just redirecting error message. If you feel like error message should be fixed then I'd suggest you open an issue with the PMD project.

> In addition, the plugin should provide a list of all available rules (perhaps in INFO mode) instead of a pretty useless error message that leaves the user in the dark.

This functionality could only be provided if the PMD library would allow for querying the information.

**Comment by asarkar** [comment] 2017-05-12 01:41
[demo.zip](https://github.com/gradle/gradle/files/994842/demo.zip)

@bmuschko Running `./gradlew clean check` on the attached project will reproduce this issue.

**Comment by asarkar** [comment] 2017-05-15 22:12
@bmuschko You asked for a reproducible example, I created one for you. Have you had a chance to take a look?

**Comment by bmuschko** [comment] 2017-05-16 15:40
The exception you see is coming from PMD itself. I'd suggest you ask over there. They might have simply removed or renamed that rule.

```
Caused by: java.lang.IllegalArgumentException: Unable to exclude rules [DataflowAnomalyAnalysis]; perhaps the rule name is mispelled?
        at net.sourceforge.pmd.RuleSetFactory.parseRuleSetReferenceNode(RuleSetFactory.java:465)
        at net.sourceforge.pmd.RuleSetFactory.parseRuleNode(RuleSetFactory.java:405)
        at net.sourceforge.pmd.RuleSetFactory.parseRuleSetNode(RuleSetFactory.java:357)
        at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:212)
        at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:207)
        at net.sourceforge.pmd.RuleSetFactory.createRuleSets(RuleSetFactory.java:168)
        at net.sourceforge.pmd.RuleSetFactory.createRuleSets(RuleSetFactory.java:152)
        at net.sourceforge.pmd.ant.internal.PMDTaskImpl.doTask(PMDTaskImpl.java:114)
        at net.sourceforge.pmd.ant.internal.PMDTaskImpl.execute(PMDTaskImpl.java:269)
        at net.sourceforge.pmd.ant.PMDTask.execute(PMDTask.java:49)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        ... 48 more
```

Side note: I would not put `ruleset.xml` into `src/main/resource` as it would be packaged into the JAR file (which you most likely do not want to happen).

**Comment by asarkar** [comment] 2017-05-16 16:56
@bmuschko Thanks for looking into this. 

1. How can the PMD plugin provide more information, perhaps in the form of the stacktrace you posted above, to the user, so that we can avoid coming to Gradle where the real problem seems to be in PMD?

2. I'm aware that anything put in `src/main/resources` is packed in the jar; this was a sample project so I didn't bother creating a new directory.

**Comment by bmuschko** [comment] 2017-05-16 18:02
> How can the PMD plugin provide more information, perhaps in the form of the stacktrace you posted above, to the user, so that we can avoid coming to Gradle where the real problem seems to be in PMD?

Simply run it with a different log level and/or add `-s` to render the stack trace.

**Comment by bmuschko** [comment] 2017-05-16 18:35
Thanks for opening the issue for the PMD project. I am going to close this issue here. Should we need to dig into Gradle internals again then we can reopen it.

**Closed by bmuschko** 2017-05-16 18:35 UTC
Labels: a:question, from:contributor, in:pmd-plugin
