### ISSUE TITLE
Cannot input password when using the GPG Agent

### ISSUE THREAD

**Issue by ansman** [gradle/gradle#17300] opened 2021-05-27 18:36 UTC
### Expected Behavior
When using the GPG Agent for signing artifacts I expect a password prompt if one is not provided in the gradle properties.

### Current Behavior
I do get a prompt but it's broken and I cannot input the passphrase:
![image](https://user-images.githubusercontent.com/102883/119876071-7c809a80-bef5-11eb-9f18-e8d10925c135.png)

Trying to input blindly and pressing tab does not work either and I get a GPG error.

### Context
I'm trying to sign my artifacts for upload to Maven Central.

### Steps to Reproduce 
1. Clone [Kotshi](https://github.com/ansman/kotshi/tree/gradle-bug).
2. Check out the `gradle-bug` branch
3. Ensure you have GPG installed and at least one key
4. Run `./gradlew :api:signKotshiPublication`

### Your Environment

Build scan URL: https://scans.gradle.com/s/6ipaut4krslpw

**Comment by britter** [comment] 2021-05-28 07:10
This looks like a duplicate of #11706. The key thing is that you're using pinentry to grap the password for gpg-agent.

**Comment by britter** [comment] 2021-06-02 06:53
Closing this as duplicate.

**Closed by britter** 2021-06-02 06:53 UTC
Labels: a:bug, to-triage
