### ISSUE TITLE
Upgrading from 5.4 to 5.5: Cannot get property 'gradle' on extra properties extension as it does not exist

### ISSUE THREAD

**Issue by jaredsburrows** [gradle/gradle#9787] opened 2019-06-08 04:05 UTC
## Repro:
1. git clone https://github.com/jaredsburrows/android-gif-example
2. cd android-gif-example
3. Edit `gradle-wrapper.properties`, set wrapper to 5.5
4. Run `gradlew wrapper`

## Error:
```
$ gradlew 
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/<>/repo/android-gif-example/build.gradle.kts' line: 15

* What went wrong:
Cannot get property 'gradle' on extra properties extension as it does not exist

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 698ms
```

**Comment by eskatos** [comment] 2019-06-25 10:32
Thanks for the report @jaredsburrows !
Closing as a duplicate of https://github.com/gradle/gradle/issues/9579

**Closed by eskatos** 2019-06-25 10:32 UTC
