### ISSUE TITLE
Failed to delete some children when switch branch (different gradle version)

### ISSUE THREAD

**Issue by mtrakal** [gradle/gradle#13677] opened 2020-07-03 09:03 UTC
When build with one gradle version, after switch to different branch with another gradle version (we upgraded gradle in develop branch, but release/hotfix branch still have older version) it stuck on `Failed to delete some children` error, because java.exe process with daemon is still present for older gradle (or newer) and stuck on this message in Android studio until I kill all java.exe processes.

### Expected Behavior
Gradle recognize, that some java.exe process is Gradle daemon for different version of grade. Stop them and after start building.

### Current Behavior
Gradle start second daemon which try to access to resources which are still locked by previous daemon and can't delete folder/etc...

### Context
Failed build, must kill java.exe processes and start build again

### Steps to Reproduce 
- Android studio
- create 2 branches
- one branch with Gradle 6.5
- second branch with Gradle 6.5.1
- build with daemon enabled on one branch (success), switch branch to second one, try to build (it will failed with): 
```
Unable to delete directory 'D:\Projects\project1\android-app\app\build\outputs\apk\test\debug'
  Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
  - D:\Projects\project1\android-app\app\build\outputs\apk\test\debug\output.json

```

```
java.exe	28484	OpenJDK Platform binary	D:\develop\android\android-studio\jre\bin\java.exe -XX:MaxPermSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Xmx3060M -Dfile.encoding=UTF-8 -Duser.country=CZ -Duser.language=cs -Duser.variant -cp C:\Users\mtrakal\.gradle\wrapper\dists\gradle-6.5-all\2oz4ud9k3tuxjg84bbf55q0tn\gradle-6.5\lib\gradle-launcher-6.5.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 6.5
java.exe	19548	OpenJDK Platform binary	D:\develop\android\android-studio\jre\bin\java.exe -XX:MaxPermSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Xmx3060M -Dfile.encoding=UTF-8 -Duser.country=CZ -Duser.language=cs -Duser.variant -cp C:\Users\mtrakal\.gradle\wrapper\dists\gradle-6.5.1-all\cdund22i8guosqylfo49op4dv\gradle-6.5.1\lib\gradle-launcher-6.5.1.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 6.5.1
```
 
### Your Environment
Android Studio 4.0
Build #AI-193.6911.18.40.6514223, built on May 20, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: analyze.exceptions.on.the.fly=true, ide.new.welcome.screen.force=true, search.everywhere.settings=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: CheckStyle-IDEA, Equals and HashCode Deluxe Generator, FindBugs-IDEA, GenerateSerialVersionUID, String Manipulation, org.jetbrains.kotlin, cn.wjdghd.unique.plugin.id, com.dafa.plugin.easyperfs, com.developerphil.adbidea, com.github.shiraji.colormanager, com.github.shiraji.findpullrequest, com.google.services.firebase, com.idamobile.android.toolbox, com.materkey.codepoints, com.mistamek.drawablepreview.drawable-preview, com.morcinek.android.codegenerator.plugin.intellij, com.nvinayshetty.DTOnator, com.ppismerov.ksvu, com.thoughtworks.gauge, com.vladsch.idea.multimarkdown, detekt, engineer.echo.plugin.mvvm, mobi.hsz.idea.gitignore, net.avenwu.tools.biu, uk.co.ben-gibson.remote.repository.mapper, wu.seal.tool.jsontokotlin, xyz.belvi.droid_snippet

=== About ===
Build version: Android Studio 4.0 Build #AI-193.6911.18.40.6514223 May 20, 2020
Java version: 1.8.0_242-release-1644-b01amd64
Operating System: Windows 10 (10.0, amd64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o

=== System ===
Number of CPU: 8
Used memory: 1194Mb 
Free memory: 1798Mb 
Total memory: 2993Mb 
Maximum available memory: 4029Mb

=== Displays ===
Displays: 
Display 0: 3840x2160; scale: 1,50
Display 1: 6720x3780; scale: 1,75

=== Plugins ===
Custom plugins: [CheckStyle-IDEA (5.40.0), Equals and HashCode Deluxe Generator (1.0.12), FindBugs-IDEA (1.0.1), GenerateSerialVersionUID (3.0.3), String Manipulation (8.0.191.000.2), Kotlin (1.3.72-release-Studio4.0-5), BugKotlinDocument (0.2.5), android easy sharedprefs (1.4), ADB Idea (1.6.1), Android Color Manager (1.1.6), Find Pull Request (1.7.1), Firebase Services (4.0.0), Android Toolbox Plugin (1.1.7), Unicode Escaper (1.0.2), Android Drawable Preview (1.1.4), Android Code Generator (1.6), DTO generator (V0.997), Kotlin serialVersionUID generator (0.0.1), Gauge (0.3.21), Markdown Navigator Enhanced (3.0.197.72), detekt (1.2.0), EasyMVVM (0.0.2), .ignore (3.2.3.193), Biu (0.2.0), GitLink (3.3.3), JSON To Kotlin Class (JsonToKotlinClass) (3.6.1), Droid Snippet (1.0.2)]
Disabled plugins:[Gradle View (3.0.0), Layoutlib Native (1.0), Android NDK Support (1.0), Android APK Support (1.0), RegexpTester (1.0.7)]

<img width="652" alt="2020-07-03" src="https://user-images.githubusercontent.com/1458891/86452549-c03a4680-bd1c-11ea-9f6f-9a423acc1ad6.png">

[studio-logs-20200703-110132.zip](https://github.com/gradle/gradle/files/4868769/studio-logs-20200703-110132.zip)

**Comment by wolfs** [comment] 2020-07-03 10:55
@mtrakal Thank you for you bug report!

The file `output.json` is not created by any plugins bundled with Gradle. It is created by the Android Gradle plugin or maybe another android related plugin. Do you maybe know which one?

There also seems to be a Gradle plugin which reads the `output.json` and fails to close it. This plugin is the culprit, so you should open an issue on the issue tracker there.

I am closing this issue since it is not a bug in Gradle itself.

**Closed by wolfs** 2020-07-03 10:55 UTC
Labels: a:bug, from:contributor

**Comment by mtrakal** [comment] 2020-07-03 11:23
`output.json` is generated by Android Studio itself, so have no idea how to solve it

**Comment by wolfs** [comment] 2020-07-03 11:28
It seems to be generated by the Android Gradle plugin, since it ends up in `build\outputs\apk\test\debug\output.json` directory.

**Comment by mtrakal** [comment] 2020-07-03 22:39
thank you for your help, really appreciate it.

So I filled issue to Google: https://issuetracker.google.com/issues/160447766
