### ISSUE TITLE
SLF4J ClassCastException when testing with custom system ClassLoader or Java 9+

### ISSUE THREAD

**Issue by chrisr3** [gradle/gradle#2657] opened 2017-08-04 09:29 UTC
Setting ` java.system.class.loader` property breaks unit tests with Gradle >= 3.4.1 for any project that uses SLF4J. I've also reproduced this with Gradle 4.0.2, where the bug makes Gradle hang as well as fail.

### Expected Behavior
My unit tests should run using the classloader specified by the `java.system.class.loader` property,

### Current Behavior
Gradle fails with an exception like:
```java
java.lang.ClassCastException: org.slf4j.helpers.NOPLoggerFactory cannot be cast to org.gradle.internal.logging.slf4j.OutputEventListenerBackedLoggerContext
        at org.gradle.internal.logging.slf4j.Slf4jLoggingConfigurer.configure(Slf4jLoggingConfigurer.java:42)
        at org.gradle.internal.logging.config.LoggingSystemAdapter.startCapture(LoggingSystemAdapter.java:54)
        at org.gradle.internal.logging.services.DefaultLoggingManager$StartableLoggingSystem.start(DefaultLoggingManager.java:297)
        at org.gradle.internal.logging.services.DefaultLoggingManager.start(DefaultLoggingManager.java:73)
        at org.gradle.internal.logging.services.DefaultLoggingManager.start(DefaultLoggingManager.java:37)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:46)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:62)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:67)
:test FAILED
```
Note that my example project is using the NOP SLF4J implementation for simplicity only, 
### Steps to Reproduce (for bugs)
Basic sample project:
[classloader.zip](https://github.com/gradle/gradle/files/1199825/classloader.zip)

### Your Environment
Linux x86_64, Oracle JDK 1.8.0_144 and OpenJDK 1.8.0_141.

[Build Scan](https://scans.gradle.com/s/3bmf2vuduv6pm)

**Comment by chrisr3** [comment] 2017-08-04 12:40
This looks like a recurrence of [GRADLE-1093](https://issues.gradle.org/browse/GRADLE-1093). Perhaps the integration test mentioned in the final comment should also include SLF4J?

**Comment by dimitarg** [comment] 2017-09-12 15:13
Here is a public repo reproducing the problem also:
https://github.com/dimitarg/bootstrap-test

Bumped into it, too.

**Comment by dimitarg** [comment] 2017-09-12 15:14
I really hate to be the guy "this blocks me I'm losing money blah blah", but I am. Is there a workaround, however hacky?

**Comment by oehme** [comment] 2017-09-14 07:51
I'm not aware of a workaround. Since this seems to be a regression in 3.4, I'll move this up in the backlog for investigation.

**Comment by chrisr3** [comment] 2017-09-14 10:32
I first encountered this issue using Gradle 3.4.1 and did not test any earlier versions. This bug could easily have been present already.

**Comment by chrisr3** [comment] 2017-12-11 15:17
This issue still exists with Gradle 4.3.1.

**Comment by jiakuan** [comment] 2018-01-07 08:47
This issue still exists with Gradle 4.4.1.
```
java.lang.ClassCastException: logback.classic@1.2.3/ch.qos.logback.classic.LoggerContext cannot be cast to org.gradle.internal.logging.slf4j.OutputEventListenerBackedLoggerContext
        at org.gradle.internal.logging.slf4j.Slf4jLoggingConfigurer.configure(Slf4jLoggingConfigurer.java:42)
        at org.gradle.internal.logging.config.LoggingSystemAdapter.startCapture(LoggingSystemAdapter.java:54)
        at org.gradle.internal.logging.services.DefaultLoggingManager$StartableLoggingSystem.start(DefaultLoggingManager.java:297)
        at org.gradle.internal.logging.services.DefaultLoggingManager.start(DefaultLoggingManager.java:73)
        at org.gradle.internal.logging.services.DefaultLoggingManager.start(DefaultLoggingManager.java:37)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:83)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:64)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:62)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:67)
java.lang.ClassCastException: logback.classic@1.2.3/ch.qos.logback.classic.LoggerContext cannot be cast to org.gradle.internal.logging.slf4j.OutputEventListenerBackedLoggerContext
        at org.gradle.internal.logging.slf4j.Slf4jLoggingConfigurer.configure(Slf4jLoggingConfigurer.java:42)
        at org.gradle.internal.logging.config.LoggingSystemAdapter.startCapture(LoggingSystemAdapter.java:54)
        at org.gradle.internal.logging.services.DefaultLoggingManager$StartableLoggingSystem.start(DefaultLoggingManager.java:297)
        at org.gradle.internal.logging.services.DefaultLoggingManager.start(DefaultLoggingManager.java:73)
        at org.gradle.internal.logging.services.DefaultLoggingManager.start(DefaultLoggingManager.java:37)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:83)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:64)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:62)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:67)
Process 'Gradle Test Executor 2' finished with non-zero exit value 1
org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 2' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:382)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.onProcessStop(DefaultWorkerProcess.java:118)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.access$000(DefaultWorkerProcess.java:41)
        at org.gradle.process.internal.worker.DefaultWorkerProcess$1.executionFinished(DefaultWorkerProcess.java:74)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy79.executionFinished(Unknown Source)
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:215)
        at org.gradle.process.internal.DefaultExecHandle.finished(DefaultExecHandle.java:327)
        at org.gradle.process.internal.ExecHandleRunner.completed(ExecHandleRunner.java:103)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:83)
        at org.gradle.internal.operations.BuildOperationIdentifierPreservingRunnable.run(BuildOperationIdentifierPreservingRunnable.java:39)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.base/java.lang.Thread.run(Thread.java:844)
java.lang.ClassCastException: logback.classic@1.2.3/ch.qos.logback.classic.LoggerContext cannot be cast to org.gradle.internal.logging.slf4j.OutputEventListenerBackedLoggerContext
        at org.gradle.internal.logging.slf4j.Slf4jLoggingConfigurer.configure(Slf4jLoggingConfigurer.java:42)
        at org.gradle.internal.logging.config.LoggingSystemAdapter.startCapture(LoggingSystemAdapter.java:54)
        at org.gradle.internal.logging.services.DefaultLoggingManager$StartableLoggingSystem.start(DefaultLoggingManager.java:297)
        at org.gradle.internal.logging.services.DefaultLoggingManager.start(DefaultLoggingManager.java:73)
        at org.gradle.internal.logging.services.DefaultLoggingManager.start(DefaultLoggingManager.java:37)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:83)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:64)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:62)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:67)
Process 'Gradle Test Executor 3' finished with non-zero exit value 1
org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 3' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:382)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.onProcessStop(DefaultWorkerProcess.java:118)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.access$000(DefaultWorkerProcess.java:41)
        at org.gradle.process.internal.worker.DefaultWorkerProcess$1.executionFinished(DefaultWorkerProcess.java:74)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy79.executionFinished(Unknown Source)
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:215)
        at org.gradle.process.internal.DefaultExecHandle.finished(DefaultExecHandle.java:327)
        at org.gradle.process.internal.ExecHandleRunner.completed(ExecHandleRunner.java:103)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:83)
        at org.gradle.internal.operations.BuildOperationIdentifierPreservingRunnable.run(BuildOperationIdentifierPreservingRunnable.java:39)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by zlooo** [comment] 2018-02-13 21:15
Happens for me as well using gradle 4.5.1, https://github.com/zlooo/gradle-classpath-problem

However in my case it's not a matter of using custom class loader but simply putting slf4j-api or any binding on **MODULE PATH**. When put on classpath, remove jigsaw plugin, tests run fine.

**Comment by reda-alaoui** [comment] 2018-02-25 15:59
@zlooo , I am in the same configuration :/
https://github.com/Cosium/vet/tree/93426a24f9893600d3b95e371d7b8dccf411cf90

**Comment by christopher-johnson** [comment] 2018-03-12 12:02
same issue as @zlooo  here.

For me, using 4.5.1 with chainsaw plugin and `slf4j-api` in dependencies produces this:
```java
java.lang.ClassCastException: slf4j.api@1.7.25/org.slf4j.helpers.NOPLoggerFactory cannot be cast to org.gradle.internal.logging.slf4j.OutputEventListenerBackedLoggerContext 
```
and `slf4j-api` with `logback-classic` this:
```java
java.lang.ClassCastException: logback.classic@1.2.3/ch.qos.logback.classic.LoggerContext cannot be cast to org.gradle.internal.logging.slf4j.OutputEventListenerBackedLoggerContext
```

**Comment by stoyle** [comment] 2018-04-07 04:43
I guess we're seeing a variant of this. We're on gradle 4.6. Still no workaround or fix? 

For us it only happens when we do a continuous run, e.g. `./gradlew -t run`. Without the `-t` everything is fine.

Full error:
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/stoyle/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-nop/1.6.2/f743dc5b4a3d1d1a64d868257e099e2e5004dcd9/slf4j-nop-1.6.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/stoyle/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.3/7c4f3c474fb2c041d8028740440937705ebb473a/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/stoyle/.gradle/wrapper/dists/gradle-4.6-all/bcst21l2brirad8k2ben1letg/gradle-4.6/lib/gradle-logging-4.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.helpers.NOPLoggerFactory]
java.lang.ClassCastException: org.slf4j.helpers.NOPLoggerFactory cannot be cast to org.gradle.internal.logging.slf4j.OutputEventListenerBackedLoggerContext
        at org.gradle.internal.logging.slf4j.Slf4jLoggingConfigurer.configure(Slf4jLoggingConfigurer.java:42)
        at org.gradle.internal.logging.config.LoggingSystemAdapter.startCapture(LoggingSystemAdapter.java:54)
        at org.gradle.internal.logging.services.DefaultLoggingManager$StartableLoggingSystem.start(DefaultLoggingManager.java:297)
        at org.gradle.internal.logging.services.DefaultLoggingManager.start(DefaultLoggingManager.java:73)
        at org.gradle.internal.logging.services.DefaultLoggingManager.start(DefaultLoggingManager.java:37)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:83)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:64)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:62)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:67)
```

Everything is fine with continuous testing though...

Cheers,
Alf

**Comment by christopher-johnson** [comment] 2018-04-07 12:16
In my case, the ClassCastException only appears during testCompile in a JPMS build.  Using `./gradlew build -x test` allows the builds to finish.

The problem is resolved by removing any references to the junit-platform-runner (and the `@RunWith(JUnitPlatform.class` annotation that invokes JUnit 4) from the Tests and only using the junit-jupiter-engine.  Thus it seems to be a Reflection related problem in JUnit4, that is resolved in JUnit5.

**Comment by himanshukandwal** [comment] 2018-06-27 17:38
Still facing this issue in gradle ver 4.8.1.

**Comment by eiswind** [comment] 2018-07-29 11:55
Same issue here:

https://github.com/eiswind/spring-boot-module-path

**Comment by TumanovViktor** [comment] 2018-07-30 06:35
Same issue with java 9 modularity and running unit tests. 

Trying to find any workaround. I guess the problem is that SLF4J doesn't find class org.slf4j.impl.StaticLoggerBinder from gradle-logging module. Why?

**Comment by jmalyik** [comment] 2018-09-22 21:11
A simple workaround can be to provide the OutputEventListenerBackedLoggerContext class as testCompile dependency. Unfortunately you have to reference the right jars from the gradle binaries. A bit ugly and will not work for all the cases, but more than nothing.
I made a [fork](https://github.com/jmalyik/bootstrap-test) from @dimitarg's project.

**Closed** 2018-10-03 22:00 UTC
Labels: a:bug, affects-version:3.4, from:contributor, in:testing

**Comment by goodidea-kp** [comment] 2018-10-09 16:06
Any updates or workaround? Most recent Gradle 5.x fails due to other errors, but Gradle 4.10.2 fails on 
`java.lang.ClassCastException: class org.slf4j.helpers.NOPLoggerFactory cannot be cast to class org.gradle.internal.logging.slf4j.OutputEventListenerBackedLoggerContext (org.slf4j.helpers.NOPLoggerFactory is in module org.slf4j of loader 'app'; org.gradle.internal.logging.slf4j.OutputEventListenerBackedLoggerContext is in unnamed module of loader java.net.URLClassLoader @55a561cf)`
That is really blocking me. Any help?

**Comment by oehme** [comment] 2018-10-09 16:14
> Most recent Gradle 5.x fails due to other errors

What errors? 

> Gradle 4.10.2 fails

It's only fixed on 5.0, as the issues says.

**Comment by goodidea-kp** [comment] 2018-10-09 16:19
`Never received a connection from Gradle Test Executor 67.
org.gradle.process.internal.ExecException: Never received a connection from Gradle Test Executor 67.
        at org.gradle.process.internal.worker.DefaultWorkerProcess.doStart(DefaultWorkerProcess.java:201)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.start(DefaultWorkerProcess.java:164)
        at org.gradle.process.internal.worker.DefaultWorkerProcessBuilder$MemoryRequestingWorkerProcess.start(DefaultWorkerProcessBuilder.java:218)
        at org.gradle.api.internal.tasks.testing.worker.ForkingTestClassProcessor.forkProcess(ForkingTestClassProcessor.java:108)
        at org.gradle.api.internal.tasks.testing.worker.ForkingTestClassProcessor.processTestClass(ForkingTestClassProcessor.java:84)
        at org.gradle.api.internal.tasks.testing.processors.RestartEveryNTestClassProcessor.processTestClass(RestartEveryNTestClassProcessor.java:52)
        at jdk.internal.reflect.GeneratedMethodAccessor126.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:29)
        at org.gradle.internal.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:87)
        at org.gradle.internal.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:36)
        at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:71)
        at org.gradle.internal.concurrent.InterruptibleRunnable.run(InterruptibleRunnable.java:42)
        at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.base/java.lang.Thread.run(Thread.java:834)
`

**Comment by oehme** [comment] 2018-10-09 16:32
Please open a separate issue, with a reproducible sample project attached.
