### ISSUE TITLE
Stable publishing plugins

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#3876] opened 2017-12-21 19:50 UTC
Improve the current `ivy-publish` and `maven-publish` plugins so that we can recommend them as a serious replacement for `uploadArchives`, and remove `@Incubating`.

**Comment by devinrsmith** [comment] 2017-12-29 21:26
Yes. As a new user it's very frustrating trying to work my way through documentation, examples, and related plugins to try and get `maven-publish` working. It seems like `uploadArchives` is the best way forward ATM.

**Comment by devinrsmith** [comment] 2017-12-29 21:33
Similar to https://github.com/gradle/gradle/issues/1165

**Comment by adecker89** [comment] 2018-02-02 00:06
`ivy-publish` and `maven-publish` make use of the rule engine which is going to be deprecated according to this blogpost https://blog.gradle.org/state-and-future-of-the-gradle-software-model  

So if I'm reading it right, those plugins will need to be either migrated back to the current Gradle model or scrapped entirely.

**Comment by lacasseio** [comment] 2018-02-02 13:49
Thanks for sharing your concern @adecker89. Those plugins will be migrated to Gradle's current model. We don't have an exact ETA for this work to happen. It will be part of the work once we start phasing out the software model which isn't happening soon.

**Comment by adecker89** [comment] 2018-02-02 17:47
So I assume that removing the `@Incubating` tag could hinder such a migration.

**Comment by lacasseio** [comment] 2018-02-02 20:19
That could be a reason but it will most likely happen in a backward compatible way or on a major version boundary if we can't keep backward compatibilities. We are having a lot of discussions internally regarding "essentially stable `@Incubating`" and ways forward to de-incubate plugins and APIs.

**Comment by oehme** [comment] 2018-04-04 09:46
Closing as duplicate of https://github.com/gradle/gradle/issues/1165

**Closed by oehme** 2018-04-04 09:46 UTC
Labels: epic, from:member, in:publishing-plugin
