### ISSUE TITLE
Ability to create FileCollections from a settings plugin, or other improvement to VersionCatalogBuilder#from

### ISSUE THREAD

**Issue by jpenilla** [gradle/gradle#27165] opened 2023-11-26 17:31 UTC
### Expected Behavior

Able to create a `FileCollection` for use with `VersionCatalogBuilder#from(Object)` from a settings plugin in a similar fashion to my `settings.gradle` script (where I can simply do `files(file("path"))`.

Or alternatively, be allowed to pass a `File`/`Path` (this currently errors). With the current limitation of the collection having one file, requiring a collection seems strange.

### Current Behavior (optional)

I was unable to find public API for this, but was able to get it working with Gradle internals:
```kotlin
import org.gradle.api.file.FileCollection
import org.gradle.api.initialization.Settings
import org.gradle.api.internal.file.FileOperations
import org.gradle.initialization.DefaultSettings
import java.io.File
import java.util.function.Function

fun Settings.builtInFileCollectionFactory(): Function<File, FileCollection> {
    // is there a way to do this without using internals?
    // from a settings.gradle.kts we can just do `files(file("path/to/file.toml"))`...
    val settingsInternal = this as DefaultSettings
    val fileOpsInternal = settingsInternal.services[FileOperations::class.java]

    return Function { fileOpsInternal.configurableFiles(it) }
}
```

### Context

I am authoring a settings plugin that applies some conventions, including version catalog toml file locations.

**Comment by cobexer** [comment] 2023-11-28 13:50
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #16506

***
This will only be possible using internal APIs until 8.5 is released. In 8.5 you can inject `BuildLayout`.

**Closed by cobexer** 2023-11-28 13:50 UTC
Labels: a:feature, to-triage
