### ISSUE TITLE
NativeComponentSpec baseName is not honored in NativeExecutableSpec with buildType debug

### ISSUE THREAD

**Issue by zosrothko** [gradle/gradle#743] opened 2016-10-22 10:40 UTC
Hi
When building a NativeExecutableSpec with a specific baseName, the release build produces the proper baseName executable while the debug build produces an executable with the default baseName
### Expected Behavior

Both build (debug, release) should honor the baseName specified in the script
The binaries produced are

```
Z:\git\cpp_gradle\build\exe\main\debug\main.exe
Z:\git\cpp_gradle\build\exe\main\release\foo.exe
```

instead of

```
Z:\git\cpp_gradle\build\exe\main\debug\foo.exe
Z:\git\cpp_gradle\build\exe\main\release\foo.exe
```
### Current Behavior

Only the second build is honoring the baseName specification in the build script. When there are more than 2 builds as for exemple with NativeSharedLibrary, only the first build gets the default name instead of the baseName.

```
        hello(NativeLibrarySpec) {
            binaries.all {
                cppCompiler.define "HELLO_EXPORT"
                baseName 'bar'
           }
```

produces

```
Z:\git\cpp_gradle\build\libs\hello\shared\debug\hello.dll
Z:\git\cpp_gradle\build\libs\hello\shared\release\bar.dll
Z:\git\cpp_gradle\build\libs\hello\static\debug\bar.lib
Z:\git\cpp_gradle\build\libs\hello\static\release\bar.lib
```
### Context

I am trying to produce binaries for VS2015 with specific base name
### Steps to Reproduce (for bugs)

1/ Clone this git repo: https://github.com/carlosvin/cpp_gradle/
2/ Edit the build.gradle by adding baseName 'foo' as

```
        main(NativeExecutableSpec) {
            binaries.all {
                lib library: "hello"
        baseName 'foo'
            }
        }
```
### Your Environment

Z:\git\gradle>gradlew --version
---
## Gradle 3.3-20161013000043+0000

Build time:   2016-10-13 00:00:43 UTC
Revision:     021d8723c1ada4cd04725099dfb7326b5e1a624f

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.7.0_51 (Oracle Corporation 24.51-b03)
OS:           Windows 7 6.1 amd64

**Comment by eriwen** [comment] 2016-10-22 19:56
@zosrothko Thank you for the well-written issue, we'll get this triaged and prioritized soon.

**Comment by zosrothko** [comment] 2016-10-30 09:25
Can someone have a look at this issue or give some pointers where to look for a problem?

**Comment by bamboo** [comment] 2016-10-30 10:30
Hi @zosrothko,

I suspect the baseName property is being set too late. Note that baseName belongs to NativeExecutableSpec itself and not to its binaries.

If you move it up one level it should work:

    main(NativeExecutableSpec) {
        baseName 'foo'
            
        binaries.all {
           lib library: "hello"
        }
     }

**Comment by zosrothko** [comment] 2016-10-30 14:52
Sorry but that does not work
```
        main(NativeExecutableSpec) {
            binaries.all {
                baseName 'foo'
                lib library: "hello"
            }
        }
```
produces
```
Z:\git\cpp_gradle\build\exe\main\debug\main.exe
Z:\git\cpp_gradle\build\exe\main\release\foo.exe
```

**Comment by bamboo** [comment] 2016-10-30 22:17
@zosrothko, I meant moving the `baseName` property out and before the `binaries.all { ... }` block. Have you tried that?

    main(NativeExecutableSpec) {
        baseName 'foo'

        binaries.all {
           lib library: "hello"
        }
     }

**Comment by zosrothko** [comment] 2016-10-31 01:06
OK I misunderstood your proposal and it works thanks....

**Comment by zosrothko** [comment] 2016-10-31 07:43
By the way, I have another question. Why setting baseName as
```
subprojects {
    components.withType(NativeLibrarySpec) {
        baseName = "Poco$project.name"
    }
}
```
does not work as expected

**Comment by zosrothko** [comment] 2016-10-31 07:50
By the way, why this script
```
subprojects {
    components.withType(NativeLibrarySpec) {
        baseName "Poco$project.name"
    }
}
```
does not seems to work as expected

**Comment by lacasseio** [comment] 2016-10-31 12:28
@zosrothko The `components` DSL is inside the `model` DSL. This means you need to specifically configure the `model` DSL. Anything reference in the `model` DSL will be intepreted as a rule which means that simply adding `components.withType` inside the `model` DSL will also fail as it will try to find a model node of path `components.withType` which is not what is expected. To solve both problem the code should look like this:
```
subprojects {
  model {
    components {
      withType(NativeLibrarySpec) {
        baseName "Poco$project.name"
      }
    }
  }
}
```

I hope this answer all your question. As @bamboo said, the `baseName` configuration need to be done at the component level. Configuring it from the binary level is too late and will result in the behavior expressed in this issue. This is not a bug but we understand confusion may suround this construct. We took note of this and will be closing this issue.

**Closed by lacasseio** 2016-10-31 12:28 UTC
Labels: a:bug, affects-version:3.2, contributed

**Comment by zosrothko** [comment] 2016-10-31 13:50
Ok got it

**Comment by zosrothko** [comment] 2017-07-23 10:14
I come back on this issue because I am not able to achieve what I want. While the solution exposed by @lacasseio works fine, it fails as soon as the baseName setting is conditioned by the buildType.
The spec are that in debug mode, the shared/static library name should be suffixed by a 'd'. Thus I tried the following build
```
// START SNIPPET libraries
model {
    components {
		withType(NativeComponentSpec) {
					if (buildType == buildTypes.debug) {
						baseName "Poco${project.name}d"
					} else
					if (buildType == buildTypes.release) {
						baseName "Poco${project.name}"
					} else {
						throw new GradleException("Unknown native binary spec")
					}
		}
        hello(NativeLibrarySpec)
    }
}

```
which result in an error as below
```
C:\Users\fandre\Documents\git\gradle\subprojects\docs\src\samples\native-binaries\cpp>c:\programfiles\gradle-4.0.1\bin\gradle clean build

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\fandre\Documents\git\gradle\subprojects\docs\src\samples\native-binaries\cpp\build.gradle' line: 14

* What went wrong:
A problem occurred configuring root project 'cpp'.
> Exception thrown while executing model rule: withType(org.gradle.nativeplatform.NativeComponentSpec) { ... } @ build.gradle line 13, column 3
   > No such property: buildType for class: org.gradle.nativeplatform.NativeLibrarySpec
```
For solving this error, I was asked to insert a binaries reference as below:
```
// START SNIPPET libraries
model {
    components {
		withType(NativeComponentSpec) {
				binaries.withType(NativeLibraryBinarySpec) {
					if (buildType == buildTypes.debug) {
						baseName "Poco${project.name}d"
					} else
					if (buildType == buildTypes.release) {
						baseName "Poco${project.name}"
					} else {
						throw new GradleException("Unknown native binary spec")
					}
				}
		}
        hello(NativeLibrarySpec)
    }
}
```
but this coma back to the initial problem that it is too late for changing the basename at the binary level. So how could I achieve this conditional suffixing?

**Comment by lacasseio** [comment] 2017-07-27 19:37
We already had a discussion regarding a [similar issue on the forum](https://discuss.gradle.org/t/native-how-to-reference-the-buildtypes-value-in-a-component/20256). Reading the discussion again, I can see that I didn't answer your question regarding moving the binaries to specific directories - e.g. `bin`, `imp`, `lib`. Your suggestion of creating a container for those configurations could be done as part of a community plugin mixed with [my proposed solution](https://discuss.gradle.org/t/native-how-to-reference-the-buildtypes-value-in-a-component/20256/4). The solution simply adds a suffix, however, the entire path could be changed without any issues.

One thing to be mindful is to avoid name collisions when moving all the binaries in the same directory. If two projects have the same component name, there is a high chance of collision. This is why Gradle separate by default.

We have seen with our partners that grouping/renaming binaries together is sometimes just a way to share the built project with other teams. In these cases, an alternative would be to modeling the assembling of such package as a separate unit of work that is independent of the build process. At this point, Gradle would simply query all the binaries and move them to the appropriate folders while renaming them. The advantage of such approach is the detection of name collision. It really depends on what are your use cases.

Don't hesitate to ask more question on the [user forum](https://discuss.gradle.org/).
