### ISSUE TITLE
Remove Gradle GUI

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#717] opened 2016-10-19 12:54 UTC
Remove Gradle GUI from the codebase, documentation and website (e.g. https://gradle.org/why/build-reporting/).

Note that this is also related to this is removing the OpenAPI bits (which the GUI depends on).

**Comment by bmuschko** [comment] 2017-01-25 22:18
Closing as duplicate of https://github.com/gradle/gradle/issues/995

**Closed by bmuschko** 2017-01-25 22:18 UTC
