### ISSUE TITLE
Parallel configuration configures projects that should be excluded by Configuration On Demand

### ISSUE THREAD

**Issue by DSteve595** [gradle/gradle#30353] opened 2024-08-29 15:45 UTC
### Current Behavior

With Project Isolation and Configuration on Demand enabled, running a task on a subproject causes all other subprojects to be configured, including those which would normally be skipped due to Configuration On Demand.

### Expected Behavior

With Project Isolation and Configuration on Demand enabled, I expect running a task on a subproject to only configure projects that that subproject depends on.

### Context (optional)

I enabled Project Isolation in a large project with many subprojects. I ran a task on one of the subprojects that does not have all of the other subprojects in its dependency graph. I noticed that while the subprojects are configured in parallel, all of the subprojects in the entire project seem to be configured, even those not in the subproject's dependency graph.

### Steps to Reproduce

1. Create subprojects `:a`, `:b`, `:c`.
2. Make `:a` depend on a task in `:b`.
3. With Project Isolation and Configuration On Demand enabled, run a task on `:a`.
Observe that `:c` is configured even though it runs no tasks.

### Gradle version

8.11-20240829002031+0000

### Your Environment (optional)

```
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache-problems=warn
org.gradle.unsafe.isolated-projects=true
```

**Comment by ljacomet** [comment] 2024-09-03 12:55
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by mlopatkin** [comment] 2024-09-10 12:11
The issue is in the backlog of the relevant team and is prioritized by them.

***

Our end goal is to honor configure on demand with the parallel configuration, but the current implementation doesn't do that for simplicity. In #30401 we'll provide a way to get back to the previous behavior, while we're working on a proper solution.

**Comment by 6hundreds** [comment] 2024-09-20 15:21
Fixed in #30401. Can be controlled via internal flag `org.gradle.internal.isolated-projects.configure-on-demand.tasks=true` since `8.11`.

**Closed by 6hundreds** 2024-09-20 15:21 UTC
Labels: a:bug, in:configure-on-demand, in:isolated-projects

**Comment by DSteve595** [comment] 2024-09-20 15:26
This seems like a workaround, is there an open bug for the two to be fully compatible?

**Comment by DSteve595** [comment] 2025-04-15 19:10
@6hundreds This is still an issue as far as I can tell.

**Comment by 6hundreds** [comment] 2025-04-18 11:27
@DSteve595 It is indeed. Fixing this is not in our immediate plans. We'll continue IP active development track on the early Gradle 9.x timeline
