### ISSUE TITLE
Heap usage regression in 8.3-rc-1

### ISSUE THREAD

**Issue by erdi** [gradle/gradle#25834] opened 2023-07-20 10:03 UTC
### Expected Behavior

8.3-rc-1 does not use significantly more heap space memory.

### Current Behavior

A build invocation which passes on `8.2.1` fails with `java.lang.OutOfMemoryError: Java heap space` on `8.3-rc-1`.

### Context (optional)

This is an early heads up that there seems to be a heap space usage regression in `8.3-rc-1`. I need to do some more digging but from what I've seen so far on our fairly large build (1100+ projects) it seems to be related to resolving of a lot of dependency configurations when tasks contributed by [`com.github.jk1.dependency-license-report`](https://plugins.gradle.org/plugin/com.github.jk1.dependency-license-report) plugin are executed. 

The main point is that executing the exact same tasks on `8.2.1` does not throw `OutOfMemoryError` but it does on `8.3-rc-1`.

I will take some heap dumps and compare them between the versions in an effort to try to pin point what it is being kept in memory on `8.3-rc-1`.

### Steps to Reproduce

Currently unknown.

### Gradle version

8.3-rc-1

### Gradle version that used to work

8.2.1

**Comment by ov7a** [comment] 2023-07-20 14:28
@erdi Thank you for the heads up! 

You can use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project and see whether the issue persists.

**Comment by erdi** [comment] 2023-07-25 14:14
A small update on this, @ov7a. 

I took some heap dumps using [`gradle-profiler`](https://github.com/gradle/gradle-profiler) and I can see 4 times as many `DefaultConfiguration_Decorated` instances retained on `8.3-rc-1` compared to `8.2.1`, all of them referenced via `DetachedConfigurationsProvider`. The next step would be to verify if these detached configurations are resolved on both versions and only retained in memory on `8.3-rc-1` or whether they are not even created on `8.2.1`. I unfortunately cannot spend any more time on this at the moment but it will look into it again when I'm back at work next week.

**Comment by eskatos** [comment] 2023-07-27 15:31
Hi Marcin 👋 
Would it be possible for you to share heap dumps? This would help us pinpoint the problem

**Comment by erdi** [comment] 2023-07-27 19:11
I’m off until Tuesday so I unfortunately won’t be able to provide any more info before then as I don’t even have access to the project atm. It’s also highly unlikely that I will be able to provide you with full heap dumps as that poses a risk of leaking credentials that are being passed to the build. My current plan is to prioritise investigating this further as soon as I’m back at work so that I can provide feedback in as timely manner as possible. 

Just FYI, it’s clearly a regression but there is a third party plugin involved so it might be just due to that plugin doing something silly. I will come back to you on Tuesday even if it will be just to let you know that I’ve not made any progress.

**Comment by erdi** [comment] 2023-08-01 08:06
Do I understand correctly that you managed to track this issue down on your end with #25949 being a potential fix? Do you still need me to investigate and provide more info, @eskatos, @ljacomet, @jvandort? 

FYI, I'm more than happy to test any nightlies with a potential fix as they become available, just let me know.

**Comment by jvandort** [comment] 2023-08-01 14:41
We have determined the root cause of holding references to the detached configurations, which the PR attempts to resolve. An optimization was added in 8.3 which cached all resolved components in a given build in memory. This would normally be acceptable, however detached configurations themselves create ad-hoc components which in this case causes the memory regression. 

We are still looking into a proper solution to this, as the above linked PR will undo other important memory optimizations for non-detached-configuration situations.

**Comment by ljacomet** [comment] 2023-08-01 14:46
@erdi Could you try increasing memory to have the build pass and communicate how much more is needed?

**Comment by ljacomet** [comment] 2023-08-02 13:48
Thank you for the additional information.
Given the work required to fix this regression with detached configurations, we have decided to accept it for 8.3 and provide a fix at the latest in Gradle 8.4.

Builds affected by this regression should stick with Gradle 8.2.1.

**Comment by eboudrant** [comment] 2023-08-29 07:31
@ljacomet does this issue also affect Gradle 8.2.1? we're getting similar error with we run the `DependencyReportTask`:
```
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-1-thread-1"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"
```
And same error with Gradle 8.3. 

If you think this is unrelated I can create a new issue.

**Comment by jvandort** [comment] 2023-08-29 14:38
This should have been fixed by https://github.com/gradle/gradle/pull/26134

**Closed by jvandort** 2023-08-29 14:38 UTC
Labels: a:regression, in:dependency-resolution, affects-version:8.3

**Comment by ljacomet** [comment] 2023-08-29 16:29
@erdi @eboudrant Could you test a recent 8.4 nightly and see if the memory usage is back to normal?

**Comment by eboudrant** [comment] 2023-08-29 17:03
Same error with 
```
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-1-thread-1"
```
I suspect something different since my heap is 56G but the OOM happen before it's exhausted, happen at about 10G usage. 
<img width="205" alt="image" src="https://github.com/gradle/gradle/assets/773377/2fd384f7-8d2a-4ea8-aca4-281a8d960fb8">

I also wonder what is the thread `"pool-1-thread-1"`, when I use Yourkit I can't find this thread.

**Comment by erdi** [comment] 2023-08-29 20:54
@ljacomet, here's the heap summary from a dump taken using `gradle-profiler` on `8.2.1`:
```
Total Bytes: 790,360,722
Total Classes: 29,665
Total Instances: 14,811,477
Classloaders: 2,242
GC Roots: 4,140
```
And here's the same for `8.4-20230828223511+0000`
```
Total Bytes: 829,980,840
Total Classes: 40,224
Total Instances: 15,490,462
Classloaders: 2,443
GC Roots: 5,138
```
The heap size increase is minimal now (it was double) so I guess the regression has been fixed.

**Comment by ljacomet** [comment] 2023-08-30 07:45
@erdi Thanks, let's consider this issue as resolved then.

@eboudrant Please file another issue as it seems you are hitting a different problem.

**Comment by eboudrant** [comment] 2023-08-31 17:24
@ljacomet it's a different problem, the OOM actually happen in the wrapper : [#26228](https://github.com/gradle/gradle/issues/26228)
