### ISSUE TITLE
Provide an API for controlling Gradle daemons

### ISSUE THREAD

**Issue by srmurguia** [gradle/gradle#12633] opened 2020-03-25 20:10 UTC
IDEA and AS get information and stop daemons using DaemonClientFactory and DaemonParameters, but those classes have changed causing exiting functionality that depends on those classes to break, for example:

https://github.com/JetBrains/intellij-community/commit/c5aeb6495feb0bcd3f30db544f1854bf34279c1a
and
https://issuetracker.google.com/issues/148656285

The cause of those issues is that two methods used by IDEA and AS (DaemonParameters#DaemonParameters(BuildLayoutParameters) and DaemonClientFactory#createStopDaemonServices) were removed in Gradle 6.0.

**Comment by big-guy** [comment] 2020-05-12 17:15
I'm going to call this a dupe of #8219, but I could see there might be more that's being asked for (e.g., being able to list the currently running daemons).

The most commonly requested feature is a way to tell Gradle that the TAPI client is done and things can be cleaned up (e.g., shut down daemons).  This is being delivered in 6.5, so if new APIs or features are needed, we can open additional issues for those.  It'll take a bit of time for IDEA/AS to adopt the new API.

**Closed by big-guy** 2020-05-12 17:15 UTC
