### ISSUE TITLE
Plugin Marker Artifact contains wrong dependency when the artifactId is customized

### ISSUE THREAD

**Issue by jmini** [gradle/gradle#19687] opened 2022-01-25 05:22 UTC
In a build where the `artifactId` value of the plugin is changed in the publication bloc (it is not equals to the project name), then the dependency bloc in the published pom file is wrong.

### Expected Behavior
`artifactId` should be the one that was defined.

### Current Behavior
`artifactId` is equals to the project name.

### Context
This was working with Gradle `6.5.1` and has stopped working after a gradle update to `6.8` (and is still broken with `7.2`)

See the analysis in the project:
https://github.com/OpenAPITools/openapi-style-validator/issues/288#issuecomment-1013661594

### Steps to Reproduce

Create a new project using `gradle init`:
```
Select type of project to generate:
  1: basic
  2: application
  3: library
  4: Gradle plugin
Enter selection (default: basic) [1..4] 4

Select implementation language:
  1: Groovy
  2: Java
  3: Kotlin
Enter selection (default: Java) [1..3] 2

Select build script DSL:
  1: Groovy
  2: Kotlin
Enter selection (default: Groovy) [1..2] 1

Generate build using new APIs and behavior (some features may change in the next minor release)? (default: no) [yes, no] no

Project name (default: plugintest): plugintest

Source package (default: plugintest): com.company.plugin
```

And you add following lines to `plugin/build.gradle` (replace the existing `plugins` section):
```
plugins {
    id 'java-gradle-plugin'
    id 'maven-publish'
}

group = 'com.company.plugin'
version = '1.2.4'

publishing {
    // afterEvaluate is necessary because java-gradle-plugin
    // creates its publications in an afterEvaluate callback
    afterEvaluate {
        publications {
            pluginMaven {
                artifactId = 'custom-artifact-id' //<--set a value different from the project name
            }
        }
    }
    repositories {
        maven {
            name = "local"
            url = file("build/repo")
        }
    }
}
```

Then you run:
`./gradlew publish`

And observe the generated pom file:
`plugin/build/repo/com/company/plugin/greeting/com.company.plugin.greeting.gradle.plugin/1.2.4/com.company.plugin.greeting.gradle.plugin-1.2.4.pom`

The dependencies bloc is wrong in the XML:
```xml
  <dependencies>
    <dependency>
      <groupId>com.company.plugin</groupId>
      <artifactId>plugin</artifactId>
      <version>1.2.4</version>
    </dependency>
  </dependencies>
```

It should be:

```xml
  <dependencies>
    <dependency>
      <groupId>com.company.plugin</groupId>
      <artifactId>custom-artifact-id</artifactId>
      <version>1.2.4</version>
    </dependency>
  </dependencies>
```

### Your Environment

Tested with:
```
------------------------------------------------------------
Gradle 7.3
------------------------------------------------------------

Build time:   2021-11-09 20:40:36 UTC
Revision:     96754b8c44399658178a768ac764d727c2addb37

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0_202 (Azul Systems, Inc. 25.202-b05)
OS:           Mac OS X 10.15.2 x86_64
```

**Comment by jbartok** [comment] 2022-03-30 07:32
Hi @jmini. 

The [java-gradle-plugin](https://github.com/gradle/gradle/blob/master/subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/plugins/JavaGradlePluginPlugin.java), when applied together with the `maven-publish` plugin, auto-applies the [MavenPluginPublishPlugin](https://github.com/gradle/gradle/blob/master/subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/plugins/MavenPluginPublishPlugin.java).

This is the plugin responsible for [creating the marker publication](https://github.com/gradle/gradle/blob/26410ffc2fef2a6674cb609f67e686d607e8119e/subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/plugins/MavenPluginPublishPlugin.java#L84). It does it based on the "[main publication](https://github.com/gradle/gradle/blob/26410ffc2fef2a6674cb609f67e686d607e8119e/subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/plugins/MavenPluginPublishPlugin.java#L72)" and it indeed does it [in an afterEvaluate block](https://github.com/gradle/gradle/blob/26410ffc2fef2a6674cb609f67e686d607e8119e/subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/plugins/MavenPluginPublishPlugin.java#L49), but I guess the reason for that is exactly to enable the modification of that publication, before this all happens.

So I think all you need to do is remove the `afterEvaluate` part from you build file and then all works as expected:
```
publishing {
    publications {
        pluginMaven(MavenPublication) {
            artifactId = 'custom-artifact-id' //<--set a value different from the project name
        }
    }
    repositories {
        maven {
            name = "local"
            url = file("build/repo")
        }
    }
}
```

Confirmed it with your reproducer. 

I'll close the issue, but if something still feels off, let me know and we'll reopen it.

**Closed by jbartok** 2022-03-30 07:32 UTC
Labels: in:plugin-development, a:regression
