### ISSUE TITLE
Adding group to projects causes recursive dependency resolution

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#27504] opened 2023-12-21 23:36 UTC
### Current Behavior

```
FAILURE: Build failed with an exception.

* What went wrong:
Circular dependency between the following tasks:
:app:something:classes
\--- :app:something:compileJava
     \--- :app:something:jar
          +--- :app:something:classes (*)
          \--- :app:something:compileJava (*)

(*) - details omitted (listed previously)
```

### Expected Behavior

It works. The dependency is an explicit `project(":absolute:path")`.

### Context (optional)

This is the real life example where it happened:
https://scans.gradle.com/s/olto6hxhdj2ry/dependencies?focusedDependency=WzEsNSwzNjk1LFsxLDUsWzM2OTVdXV0&focusedDependencyView=details&toggled=W1sxXSxbMSw1XV0

it looks a little bit different than the repro, but the root cause seems to be the same (except not visible in repro build scan).

Based on where I found this, there's a dependency tree like this (following the repro structure):

```
project :app:something
\--- project :feature:something
```
which when adding a group to both projects becomes:
```
project :app:something
\--- project :feature:something -> project :app:something
```
i.e. the two modules become "equivalent" and substituted when it comes to Gradle dependencies.

See `gradlew :app:something:dependencies`, because it is not visible in the repro build scan, but is visible in the above real scan. (Could be because they're different Gradle versions).

### Steps to Reproduce

1. Clone https://github.com/TWiStErRob/repros/tree/main/gradle/dependency_group-recursion
2. `gradlew build` &rarr; failure
3. Remove `group = ...` from root `build.gradle`
4. `gradlew build` &rarr; success

### Gradle version

Found in 8.2, repro in 8.5

### Build scan URL (optional)

https://gradle.com/s/e35g2qznofm22

### Issues (these might become enhancements, depending on your response)
 * Dependency gets substituted just because of existence of group (this issue)
 * Build scan not showing dependencies in minimal repro (while it works in real/Android project)
 * Error message is complaining about recursive task dependencies, while in reality there's recursive project dependencies; so it's hard to figure out what's going on.
 * Even if dependency substitution is correct, it's impossible to see why, even `dependencyInsight` doesn't tell me.

**Comment by ov7a** [comment] 2023-12-26 13:20
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/847

Please add your use case and 👍 to that issue.

***

The root cause should be addressed in the linked issue first. Other issues you pointed out might be addressed or changed depending on the final solution.

**Closed** 2023-12-26 13:21 UTC
Labels: closed:duplicate, in:multi-projects
