### ISSUE TITLE
[maven-publish]: Error when running the generateMetadataFileFor*Publication task

### ISSUE THREAD

**Issue by morohon** [gradle/gradle#28122] opened 2024-02-19 21:51 UTC
### Current Behavior

An error occurs when running the generateMetadataFileFor*Publication task:
<pre>
* What went wrong:
   Execution failed for task ':publish-problem-spring-boot-autoconfigure:generateMetadataFileForStarterPublication'.
   > Invalid publication 'starter':
   - Publication only contains dependencies and/or constraints without a version. You need to add minimal version information, publish resolved versions (For more on this, please refer to https://docs.gradle.org/8.6/userguide/publishing_maven.html#publishing_maven:resolved_dependencies in the Gradle documentation.) or reference a platform (For more platforms, please refer to https://docs.gradle.org/8.6/userguide/platforms.html in the Gradle documentation.)
</pre>

full stacktrace: https://gist.github.com/morohon/555b4d093733e088eda0d707d60751bf

### Expected Behavior

Executing the generateMetadataFileFor*Publication task does not produce an error.
maven-publish uses the dependency versions provided by the spring dependency management plugin.

### Context (optional)

A very similar issue was previously raised in this issue: https://github.com/gradle/gradle/issues/27789 and was closed.
In the comment there is a request to re-open

### Steps to Reproduce

1. Clone the [repository](https://github.com/morohon/publish-problem-spring-boot-starter): 
```shell 
git clone git@github.com:morohon/publish-problem-spring-boot-starter.git
```
2. Go to the main branch: 
```shell
git checkout main
```
3. Run the command: 
```shell
./gradlew publish-problem-spring-boot-autoconfigure:clean publish-problem-spring-boot-autoconfigure:generateMetadataFileForStarterPublication
```
4. See an error in the logs

**Important note**:
The project builds successfully and does not cause an error. That is, if you execute the command: 
```shell
./gradlew publish-problem-spring-boot-autoconfigure:clean publish-problem-spring-boot-autoconfigure:build
```
it will be executed successfully. The only problem is with publishing the artifact.

Workaround:
You must specify dependency versions manually; an example of a fix is provided in the [commit](https://github.com/morohon/publish-problem-spring-boot-starter/commit/ea04fd57010fce922d40b6d0974d4f042528acc8).
1. Clone the [repository](https://github.com/morohon/publish-problem-spring-boot-starter): 
```shell 
git clone git@github.com:morohon/publish-problem-spring-boot-starter.git
```
2. Go to the fix-publish branch: 
```shell
git checkout fix-publish
```
3. Run the command:
```shell
./gradlew publish-problem-spring-boot-autoconfigure:clean publish-problem-spring-boot-autoconfigure:generateMetadataFileForStarterPublication
```
4. See information about the successful execution of the command in the log

### Gradle version

8.6

### Build scan URL (optional)

https://scans.gradle.com/s/5deahcckx2wxm

### Your Environment (optional)

macbook pro 2021 (m1 max), java 21, spring boot 3.2.2

**Comment by ljacomet** [comment] 2024-02-20 14:02
This issue will be closed as a duplicate of
* #23030 

***
This was a strict failure in Gradle 8.6 and before.
With Gradle 8.7, you will be able to skip this validation and publish metadata without versions.

Note that we still do not recommend doing so for any public library as it is unlikely to behave properly in all cases

**Closed by ljacomet** 2024-02-20 14:02 UTC
Labels: closed:duplicate, to-triage
