### ISSUE TITLE
Wrong dependencies scope with Spring Boot and Gradle 3.4-rc1

### ISSUE THREAD

**Issue by dwursteisen** [gradle/gradle#1335] opened 2017-02-06 14:09 UTC
When building a new Spring Boot Application using gradle 3.4-rc1, starting a Spring boot application crash with `ClassNotFoundException`

### Expected Behavior

- create a new Spring Boot application
- update gradle wrapper with gradle 3.4-rc-1
- run Spring Boot Application
- the application start

### Current Behavior

- create a new Spring Boot application
- update gradle wrapper with gradle 3.4-rc-1
- run Spring Boot Application
- the application crash with `java.lang.NoClassDefFoundError: org/springframework/boot/SpringApplication`.

In intelliJ, all gradle dependencies (ie: spring boot dependencies, etc) are with the scope `Provided` instead of `Compile` with gradle 3.3

### Context

I'm trying to start a new spring boot project using gradle 3.4-rc-1

### Steps to Reproduce (for bugs)

- create a new spring boot project with http://start.spring.io/ (using gradle + Spring boot 1.5.2-SNAPSHOT, no dependencies)
- generate project
- unzip 
- open gradle-wrapper.properties
- update `distributionUrl` with `https\://services.gradle.org/distributions/gradle-3.4-rc-1-bin.zip`
- open project in IntelliJ
- run as application the spring boot application (`*Application.java`)

### Your Environment

- Windows 7 / IntelliJ 2016.3

**Comment by oehme** [comment] 2017-02-06 15:19
This is a duplicate of #1276, will be fixed in IntelliJ soon.

**Closed by oehme** 2017-02-06 15:19 UTC
