### ISSUE TITLE
The --java-version option doesn't prevent "gradle init" from entering interactive mode, as expected

### ISSUE THREAD

**Issue by nfonrose** [gradle/gradle#27520] opened 2023-12-26 16:25 UTC
### Current Behavior

The gradle init `--java-version` option doesn't work as expected since gradle still enters the interactive mode and ask for the Java version (which defeats the purpose of this option)

### Expected Behavior

When the `--java-version` option is used, `gradle init` should not enter interactive mode to ask for the Java version

### Steps to Reproduce

Everything to reproduce is described in details here
https://github.com/gradle/gradle/issues/26598#issuecomment-1869513296

### Gradle version

8.5

### Your Environment (optional)

The most important info about the environment are  described in the link provided above through SDKMAN commands

**Comment by nfonrose** [comment] 2023-12-26 17:00
Some more info to help debug.

When using the `--java-version` option, grade not only asks (in interactive mode) for the "Java version" but also for the "new API" question. When you provide a value through `stdin` gradle doesn't enter interactive mode at all, even though only one answer is provided.

The command below does not enter interactive mode
```
echo 'no' | gradle init --type java-application --dsl groovy --project-name s3onezoneexpress --package com.teevity.sandbox.s3onezoneexpress --test-framework junit-jupiter
```

Not sure how this can help but as it doesn't seem very consistent, it probably does

**Comment by SimonScholz** [comment] 2024-01-08 08:54
I can confirm this issue with Gradle 8.5.

**Comment by cobexer** [comment] 2024-01-08 09:42
Thank you for providing a valid report.

The issue is in the backlog of the relevant team and is prioritized by them.
***
This indeed should skip interactive mode, I'll take a look.

**Comment by cobexer** [comment] 2024-01-09 11:33
This was already fixed by https://github.com/gradle/gradle/pull/27408 which is part of 8.6 RC1.

**Closed by cobexer** 2024-01-09 11:33 UTC
Labels: in:build-init-plugin, a:regression, has:reproducer, affects-version:8.5
