### ISSUE TITLE
Jar task archivesBaseName changes kotlin -module-name

### ISSUE THREAD

**Issue by taras-hillsidetec** [gradle/gradle#30611] opened 2024-09-18 20:07 UTC
### Current Behavior

setting archivesBaseName property changes value passed to the kotlin compiler in -module-name parameter.

with a project XYZ setting archive prefix such as:
```
archivesBaseName = "prefix-XYZ"
```

results in kotlin compiler getting the following argument added
```
-module-name prefix-XYZ
```

### Expected Behavior

archivesBaseName should not influence kotlin compiler 0module-name parameter

### Self-contained Reproducer Project

None

### Gradle version

8.10.1

**Comment by ov7a** [comment] 2024-09-19 12:50
This is an issue with the Kotlin Gradle Plugin, which is developed by JetBrains, and cannot be addressed in the Gradle Build Tool project. We cannot just move the issue.

Please open such Kotlin-related issues on the JetBrains YouTrack at https://kotl.in/issue.

If you believe this is not a Kotlin plugin issue, please update with a reproducer that does not involve the Kotlin plugin.


***

This might be the intended behavior, but please get more info from the Kotlin Gradle Plugin community.

**Closed by ov7a** 2024-09-19 12:50 UTC
Labels: a:bug, to-triage
