### ISSUE TITLE
Detached configurations cannot extend from existing configurations

### ISSUE THREAD

**Issue by melix** [gradle/gradle#6881] opened 2018-09-25 11:04 UTC
### Context

Dependency resolution using attribute matching doesn't work if the configuration being resolved is a detached configuration. I'm actually surprised we went that far without fixing this. Given the following build file:

```
subprojects {
   apply plugin: 'java-library'
}

project(":app") {
    dependencies {
        implementation project(":lib")
    }

    tasks.create("resolve") {
       def detached = configurations.detachedConfiguration()
       detached.with {
           canBeResolved = true
           canBeConsumed = false
           extendsFrom(configurations.implementation)
           attributes {
               attribute(Attribute.of('org.gradle.usage', Usage), project.objects.named(Usage, 'java-api'))
           }
       }
       println configurations.compileClasspath.files
       println detached.files
    }
}

```

I would expect the `detached.files` collection to be the same as `compileClasspath.files`, given that it asks for the same attributes and both extend `implementation`. However, in practice, the collection is empty. Replacing `configurations.detachedConfiguration()` with `configuration.create("foo")` solves the problem, indicating that the issue is really with detached configurations, not with attribute matching.

**Comment by melix** [comment] 2018-09-25 12:01
FWIW, there's a first problem which is that detached configurations cannot inherit from configurations defined in a different container. So, in fact, we get no dependencies because we don't inherit dependencies from the parent configuration here.

**Comment by melix** [comment] 2018-09-25 12:06
Yes, I can confirm it works properly if we include the set of configurations from the container the detached configuration was created from in the list.

**Comment by melix** [comment] 2020-01-08 18:33
Updated the title to reflect the real problem

**Comment by vlsi** [comment] 2021-06-02 16:10
counter++

I think I hit this the second or the third time already

**Comment by chrisr3** [comment] 2021-07-30 11:43
Interesting. I have tried creating a detached configuration that extends from another detached configuration, both from the same configuration container. The first configuration contains a dependency without a `version`, and the second contains a relevant `platform` dependency. My hope was that I could resolve the first configuration and then examine the `ResolveConfiguration`'s only `firstLevelModuleDependency`, especially since `allDependencies` contains what I expect. However, Gradle refuses to resolve this, forcing me to add both dependences to a single detached configuration instead.

**Comment by kristian** [comment] 2022-01-19 09:22
I stumbled across the same issue and described it on the forum [here](https://discuss.gradle.org/t/how-to-extend-from-runtimeclasspath/41983):

```groovy
def newConfiguration = project.configurations.detachedConfiguration()
newConfiguration.setCanBeResolved(true)
newConfiguration.extendsFrom(project.configurations.runtimeClasspath)
```

Resolving results in an empty array:

```groovy
doFirst {
    println newConfiguration.resolve()
}
```

So this issue gets a +1 from me. Would love to see this one resolved. Workaround is to create a attached configuration.

**Comment by aSemy** [comment] 2023-02-04 14:42
This problem is a little painful when trying to resolve the non-transitive elements of a configuration. The suggested workaround https://github.com/gradle/gradle/issues/14880 is to create a non-transitive Configuration that extends the transitive Configuration. It would be nice to create the intransitive Configuration as detached, so it does not get confused with the transitive configuration, generate unnecessary Kotlin DSL accessors, or pollute IDE auto-completion.

Here is an example that reproduces the problem. Copy it into a `build.gradle.kts`, and run 

```
./gradlew listPluginsIntransitive
```

It should list the declared dependency, and the transitive dependencies, and then finally the declared dependency. However, the detached and attached intransitive configurations produce different results

```
Execution failed for task ':listPluginsIntransitive'.
> attached: kotlin-gradle-plugin-1.8.0-gradle76.jar
  detached: 
```



```kotlin
import org.gradle.api.attributes.Bundling.BUNDLING_ATTRIBUTE
import org.gradle.api.attributes.Bundling.EXTERNAL
import org.gradle.api.attributes.Category.CATEGORY_ATTRIBUTE
import org.gradle.api.attributes.Category.LIBRARY
import org.gradle.api.attributes.LibraryElements.JAR
import org.gradle.api.attributes.LibraryElements.LIBRARY_ELEMENTS_ATTRIBUTE
import org.gradle.api.attributes.Usage.JAVA_RUNTIME
import org.gradle.api.attributes.Usage.USAGE_ATTRIBUTE
import org.gradle.api.attributes.java.TargetJvmEnvironment.STANDARD_JVM
import org.gradle.api.attributes.java.TargetJvmEnvironment.TARGET_JVM_ENVIRONMENT_ATTRIBUTE

plugins {
  base
}

val generatorPlugins by configurations.registering {
  isCanBeResolved = true
  isCanBeConsumed = false
  isVisible = false
  attributes {
    attribute(USAGE_ATTRIBUTE, objects.named(JAVA_RUNTIME))
    attribute(CATEGORY_ATTRIBUTE, objects.named(LIBRARY))
    attribute(BUNDLING_ATTRIBUTE, objects.named(EXTERNAL))
    attribute(TARGET_JVM_ENVIRONMENT_ATTRIBUTE, objects.named(STANDARD_JVM))
    attribute(LIBRARY_ELEMENTS_ATTRIBUTE, objects.named(JAR))
  }
}

val generatorPluginsIntransitiveAttachedConfiguration = configurations.create("generatorPluginsIntransitive") {
  isCanBeResolved = true
  isCanBeConsumed = false
  isVisible = false
  isTransitive = false
  extendsFrom(generatorPlugins.get())
  attributes {
    attribute(USAGE_ATTRIBUTE, objects.named(JAVA_RUNTIME))
    attribute(CATEGORY_ATTRIBUTE, objects.named(LIBRARY))
    attribute(BUNDLING_ATTRIBUTE, objects.named(EXTERNAL))
    attribute(TARGET_JVM_ENVIRONMENT_ATTRIBUTE, objects.named(STANDARD_JVM))
    attribute(LIBRARY_ELEMENTS_ATTRIBUTE, objects.named(JAR))
  }
}

val generatorPluginsIntransitiveDetachedConfiguration = configurations.detachedConfiguration().apply {
  isCanBeResolved = true
  isCanBeConsumed = false
  isVisible = false
  isTransitive = false
  extendsFrom(generatorPlugins.get())
  attributes {
    attribute(USAGE_ATTRIBUTE, objects.named(JAVA_RUNTIME))
    attribute(CATEGORY_ATTRIBUTE, objects.named(LIBRARY))
    attribute(BUNDLING_ATTRIBUTE, objects.named(EXTERNAL))
    attribute(TARGET_JVM_ENVIRONMENT_ATTRIBUTE, objects.named(STANDARD_JVM))
    attribute(LIBRARY_ELEMENTS_ATTRIBUTE, objects.named(JAR))
  }
}

dependencies {
  "generatorPlugins"("org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0")
}

val listPlugins by tasks.registering {
  inputs.files(generatorPlugins)
  doLast {
    generatorPlugins.get().files.forEach { println(it.name) }
  }
}
val listPluginsIntransitive by tasks.registering {
  dependsOn(listPlugins)
  inputs.files(generatorPluginsIntransitiveAttachedConfiguration)
  inputs.files(generatorPluginsIntransitiveDetachedConfiguration)
  doLast {
    val attachedResult = generatorPluginsIntransitiveAttachedConfiguration.files.joinToString { it.name }
    val detachedResult = generatorPluginsIntransitiveDetachedConfiguration.files.joinToString { it.name }

    require(attachedResult == detachedResult) {
      """
        attached: $attachedResult
        detached: $detachedResult
      """.trimIndent()
    }
  }
}
```

**Comment by jvandort** [comment] 2024-01-10 00:31
We should fix this by failing fast instead of failing silently.

**Comment by marchermans** [comment] 2024-01-27 21:19
> We should fix this by failing fast instead of failing silently.

Why?, The detached configuration is created from a given container, restricting it from extending configuration reachable through that container, seems like an arbitrary blocker.
Is there a functional reason why this should not be possible?

**Comment by melix** [comment] 2024-01-29 11:08
I agree that ideally this shouldn't fail but simply make it work. I guess that what Justin is saying is that it is currently broken anyway, so making it fail is a "better" solution in the sense that it would fail eagerly instead of being simply ignored. However it is reasonable to expect that this feature works.

**Comment by tresat** [comment] 2024-09-19 13:51
@bot-gradle test and merge

**Closed** 2024-10-01 11:44 UTC
Labels: a:bug, in:dependency-resolution
