### ISSUE TITLE
gradle metata doesn't work smoothly with 403's (s3+cloudfront)

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#9319] opened 2019-04-29 20:05 UTC
```
> Could not resolve all files for configuration ':compileClasspath'.
   > Did not resolve 'tld.my:accuryn-monitor-2.1-data:0.3.2' which is part of the dependency lock state
   > Could not resolve tld.my:accuryn-monitor-2.1-data:[0.3,0.4).
     Required by:
         project :
      > Could not resolve tld.my:accuryn-monitor-2.1-data:0.3.2.
         > Could not get resource 'https://artifacts.my.tld/tld/my/accuryn-monitor-2.1-data/0.3.2/accuryn-monitor-2.1-data-0.3.2.module'.
            > Could not GET 'https://artifacts.my.tld/tld/my/accuryn-monitor-2.1-data/0.3.2/accuryn-monitor-2.1-data-0.3.2.module'. Received status code 403 from server: Forbidden
```

Arguably the problem here is that when you put cloudfront in front of an s3 bucket, instead of returning the appropriate 404 on not found, it returns a secure 403... I can see an argument that it is aws that needs to change but... good luck with that? It might be nice to have a flag, or simply treat 403's the same way instead of bailing out.

```
------------------------------------------------------------
Gradle 5.4.1
------------------------------------------------------------
Build time:   2019-04-26 08:14:42 UTC
Revision:     261d171646b36a6a28d5a19a69676cd098a4c19d
Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_212 (Oracle Corporation 25.212-b01)
OS:           Linux 4.19.23-coreos-r1 amd64
```

 failure is permanent. I think it would be nice if gradle treated 403's and 404's the same as in both cases you're unable to retrieve the metadata, so simply treat it like it doesn't exist.

**Comment by ljacomet** [comment] 2019-04-30 07:14
Can you please add the Gradle version and whether this is transient or permanent?

Also what you would expect Gradle to do?

**Comment by xenoterracide** [comment] 2019-04-30 12:45
information added

**Comment by ljacomet** [comment] 2019-05-02 08:06
The reason Gradle bails out on a 403 is that it is more likely to indicate a configuration issue than anything else.

As replied in the [community slack](https://gradle-community.slack.com/archives/CA7UM03V3/p1556640926145100?thread_ts=1556609476.143300&cid=CA7UM03V3), you can configure your S3 based repository to properly get a `404` there instead. That [Stackoverflow question](https://stackoverflow.com/questions/19037664/how-do-i-have-an-s3-bucket-return-404-instead-of-403-for-a-key-that-does-not-e) covers this point.

Gradle, to offer better reproducibility, will not continue a build when things go wrong in a repository, in a way that indicates this is not transient.

**Comment by ljacomet** [comment] 2019-06-04 16:27
Closing as there will be no change for this on the Gradle side.

**Closed by ljacomet** 2019-06-04 16:27 UTC
Labels: a:feature, in:dependency-management

**Comment by jhouserizer** [comment] 2021-03-16 23:56
@ljacomet is this because you use RegEx to distinguish return codes?    We just used the OAI work-around to resolve this.
