### ISSUE TITLE
Automatically downloaded toolchains massively slow down the build (possibly only on Linux, otherwise only on CI)

### ISSUE THREAD

**Issue by anuraaga** [gradle/gradle#15325] opened 2020-11-26 09:13 UTC
Apologies for a very rough description, but the issue may be serious so filing as best I can.

### Expected Behavior
Build performance should be the same, except for an initial download period, whether a toolchain is automatically downloaded or not.

### Current Behavior
Build performance tanks when setting toolchains for tests and having it automatically download the toolchains.

### Context

We have recently been suffering from extremely slow builds in our large repository. We eventually realized that it is a problem with automatically downloaded toolchains that doesn't happen with provided ones. I had incorrectly used `-D` instead of `-P` to set the paths, fixed in

https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1775

Before that, even if a build was fully cached, the build would take 30min instead of 5min. We can see two here

Preloaded JDK - https://scans.gradle.com/s/frbajdj3zfyr6/timeline?anchor=qnx7l7tpz5l2i
Downloaded JDK - https://scans.gradle.com/s/v6cux6ukulbdq/timeline?anchor=ukxmf7budwyhy

The automatically downloaded JDK was only used for `test` tasks.

Notably, with the downloaded JDK, all `test FROM-CACHE` hits take around 30s for "Fingerprinting inputs". On other builds, they take less than 1s. And after fixing our configuration problem, this behavior went away. We finally found the configuration issue because we noticed in the network tab of the build scan that it was downloading JDK.

While we could expect even a few minutes of extra time taken in the beginning for a downloaded JDK, in our case the difference was 5min to 30min for fully cached build, and 30min to 2hour for non-cached build.

Build scans for extremely slow, mostly non-cached builds
Preloaded JDK: https://gradle.com/s/x3ri24ow3ni6o
Downloaded JDK: https://scans.gradle.com/s/wtvetc5j2wmnw

### Steps to Reproduce 

I don't know a good way to reproduce this unfortunately. Our configuration is here

Gradle:
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/gradle/java.gradle#L204

GitHub workflow:
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/91a9e1885ea6a54d457173420eb249f0099ed26f/.github/workflows/nightly.yaml#L79
(notice the typo of `-D` instead of `-P`)

On my Mac, tests always use a downloaded JDK and there's no added slowness. I don't have Linux handy to try there, it might be Linux-only and if so, easy to repro there. If running locally, can use `./gradlew test -PtestJavaVersion=15`, unless your default JDK is Java 15 in which case you would change that to any other version to have it register the launcher.

The only way I know of reproducing this right now is by forking https://github.com/open-telemetry/opentelemetry-java-instrumentation/commit/91a9e1885ea6a54d457173420eb249f0099ed26f  and pushing commits to master to trigger the build on GitHub. GitHub actions will run and demonstrate the slowness.

We have many builds over the past week we've had this issue with build scan links in case they can help - https://github.com/open-telemetry/opentelemetry-java-instrumentation/actions

### Your Environment
GitHub Actions, ubuntu-latest runner, Java 11 build toolchain (provided by OS), Java 15 test launcher (downloaded by Gradle), Gradle 6.7.1

**Comment by bmuskalla** [comment] 2020-12-03 11:55
Thanks, @anuraaga for the detailed description, steps to reproduce, and the build scans. I finally found the reason why the fingerprinting was taking so long on your builds. Toolchains are used as task input for the various compile/test tasks (major version and more information in 6.8). But due to a bug, we re-provisioned the downloaded toolchain again when checking the inputs from a task. We didn't download it again (that's why it doesn't show up in the network tab in the scan) but we just unzip the whole jdk again. 
The fix will be in 6.8 RC2 (to be released in the next few days). At this stage, I don't think we'll backport this to 6.7.x as there is an easy workaround. In case you're curious to try it out, I quickly [hacked together the changes](https://github.com/bmuskalla/opentelemetry-java-instrumentation/commits/master) needed for upgrading to 6.8 on a fork of your project.

**Closed** 2020-12-03 11:55 UTC
Labels: @jvm, a:bug, from:contributor, in:toolchains
