### ISSUE TITLE
Be more nice/smart with Groovy 'indy' dependencies

### ISSUE THREAD

**Issue by mauromol** [gradle/gradle#9318] opened 2019-04-29 13:24 UTC
### Expected Behavior
When I have dependencies like:

```groovy
implementation 'org.codehaus.groovy:groovy:2.5.6:indy'
implementation 'org.codehaus.groovy:groovy-dateutil:2.5.6:indy'
```
Gradle could be smart enough to filter out the non-indy dependency of `groovy-dateutil` on `groovy`. Otherwise, provide some way to easily solve this problem.

### Current Behavior
`org.codehaus.groovy:groovy-dateutil:2.5.6:indy` carries on `org.codehaus.groovy:groovy:2.5.6`, so that its JAR gets into the classpath together with `org.codehaus.groovy:groovy:2.5.6:indy`.
`dependencyInsight` does not help, because the `indy` classifier is not reported (see [GRADLE-2978](https://issues.gradle.org/browse/GRADLE-2978)).
I can't exclude a transitive dependency by classifier; i.e., the following does not work:

```groovy
	implementation('org.codehaus.groovy:groovy-dateutil:2.5.6:indy') {
		exclude group: 'org.codehaus.groovy', classifier: ''
	}
```

It would also be quite verbose...

The best I could do is to disable transitive dependencies for `groovy-dateutil` as a whole, which is risky.
Or give up and use non-indy Groovy modules.

### Context
This problem became quite evident after I tried to upgrade from Groovy 2.4 to 2.5: the latter was split into different modules, like the aforementioned `groovy-dateutil`, or `groovy-jaxb`, or `groovy-datetime` and so on.

**Comment by ljacomet** [comment] 2019-06-05 15:54
This is the kind of scenario that [Gradle Module Metadata](https://blog.gradle.org/gradle-metadata-1.0) is designed to support.

By using [variant attributes](https://docs.gradle.org/5.4.1/userguide/dependency_management_attribute_based_matching.html), the metadata for the Groovy project could differentiate between the `indy` and normal variants, including proper dependency tracking: `indy` bits would only depend on other `indy` bits.
By also declaring that the indy variants provide the same [capabilities](https://docs.gradle.org/5.4.1/userguide/managing_transitive_dependencies.html#sec:capabilities), Gradle could let you know when your dependency graph incorrectly includes both the `indy` and regular versions of a Groovy module.

Sadly, until such metadata is made available by Groovy, you do not really have an alternative. There are too many moving parts and the existing Maven metadata format does not carry enough information.

**Comment by mauromol** [comment] 2019-06-05 16:08
I see. However, I was wondering whether, since Groovy should be a first-class citizen in Gradle, some kind of special processing couldn't be added to Gradle for it until such metadata is made available.

Also, do you know whether Groovy developers know about the opportunity to add such metadata?

**Comment by ljacomet** [comment] 2019-06-05 16:21
The problem is that it is not just about the metadata, it is also about the lack of information encoded in transitive dependencies.

The Groovy project is a clear candidate to be early adopters of the Gradle Module Metadata. The Gradle team plans to do some outreach on this topic in the near future.

**Comment by ljacomet** [comment] 2019-06-14 10:39
Closing as there is no plan on having special casing for this inside Gradle.

**Closed by ljacomet** 2019-06-14 10:39 UTC
Labels: a:feature, from:contributor, in:dependency-management

**Comment by Fiouz** [comment] 2020-08-26 01:11
This seems to do the trick:

```kotlin
dependencies {
    components {
        all(GroovyIndyRule::class.java)
    }
    IMPLEMENTATION_CONFIGURATION_NAME("org.codehaus.groovy:groovy-all:3.0.5")
}
tasks.register("listJars") {
    val conf = configurations[JavaPlugin.COMPILE_CLASSPATH_CONFIGURATION_NAME]
    dependsOn(conf)
    description = "Lists the resolved files for ${conf.name}."
    doFirst {
        conf.resolve().forEach {
            logger.lifecycle("Dependency: {}", it)
        }
    }
}
class GroovyIndyRule : ComponentMetadataRule {
    override fun execute(context: ComponentMetadataContext) {
        context.details.run {
            if (id.group == "org.codehaus.groovy" && context.getDescriptor(org.gradle.api.artifacts.maven.PomModuleDescriptor::class.java)?.packaging == "jar") {
                allVariants {
                    withFiles {
                        removeAllFiles()
                        addFile("${id.name}-${id.version}-indy.jar")
                    }
                }
            }
        }
    }
}
```

This tells Gradle not to consider any classifier during dependency resolution (i.e. there is no classifier in the dependency notation), and to change the way it resolves the underlying file name of `org.codehaus.groovy` modules by then adding the `-indy` part.
(if you need to convert to Groovy, Kotlin [`.run`](https://kotlinlang.org/docs/reference/scope-functions.html#run) is similar syntactic sugar as Groovy [`.with`](https://docs.groovy-lang.org/latest/html/groovy-jdk/java/lang/Object.html#with(groovy.lang.Closure)))

This [requires](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/maven/PomModuleDescriptor.html) Gradle 6.3+ (tested with 6.6).

**Comment by melix** [comment] 2020-08-26 06:57
Using Groovy 6.6 you could use dependency substitutions with classifiers instead: https://docs.gradle.org/6.6/userguide/resolution_rules.html#sec:substitution_with_classifier

**Comment by Fiouz** [comment] 2020-08-26 08:15
> 
> 
> Using Groovy 6.6 you could use dependency substitutions with classifiers instead: https://docs.gradle.org/6.6/userguide/resolution_rules.html#sec:substitution_with_classifier

Thank you for pointing that alternate approach.

I tried it but I am not sure how to exclude non-jar dependencies (such as [`groovy-all`](https://search.maven.org/artifact/org.codehaus.groovy/groovy-all/3.0.5/pom)), as it's only a `pom` packaging and not `jar` (i.e. can we access a `PomModuleDescriptor` instance) ?

```kotlin
configurations.configureEach {
    resolutionStrategy.dependencySubstitution {
        all {
            val moduleSelector = requested as? ModuleComponentSelector
            if (moduleSelector?.group == "org.codehaus.groovy") {
                artifactSelection {
                    selectArtifact("jar", "jar", "indy")
                }
            }
        }
    }
}
```

**Comment by mauromol** [comment] 2020-08-26 08:53
Hi Cédric, is it possible with 6.6 dependency substitutions with classifiers to replace all modules from group `org.codehaus.groovy` with corresponding ones _at the same version_? I mean, this obviously does not work:

```groovy
configurations.all {
	resolutionStrategy.dependencySubstitution {
		substitute module('org.codehaus.groovy') using module('org.codehaus.groovy') withClassifier('indy')
	}
}
```

And, if I want to limit myself to the core `groovy` module (which would however require me to repeat this for ALL transitive Groovy modules I discover I depend on), the following does not work either, because Gradle still wants the version in the target module specification (see #12459):

```groovy
configurations.all {
	resolutionStrategy.dependencySubstitution {
		substitute module('org.codehaus.groovy:groovy') using module('org.codehaus.groovy:groovy') withClassifier('indy')
	}
}
```

The following two do not work either:

```groovy
configurations.all {
  resolutionStrategy.dependencySubstitution.all { DependencySubstitution dependency ->
    if (dependency.requested instanceof ModuleComponentSelector && dependency.requested.group == 'org.codehaus.groovy')
      dependency.useTarget("org.codehaus.groovy:$dependency.requested.module:$dependency.requested.version", 'we use the indy version') withClassifier('indy')
  }
}
```
This makes the resolution of Groovy dependencies fail.

And:

```groovy
configurations.all {
  resolutionStrategy.dependencySubstitution.all { DependencySubstitution dependency ->
    if (dependency.requested instanceof ModuleComponentSelector && dependency.requested.group == 'org.codehaus.groovy')
      dependency.useTarget("org.codehaus.groovy:$dependency.requested.module:$dependency.requested.version:indy", 'we use the indy version')
  }
}
```
This simply seems to do nothing, I still get both groovy-2.5.9.jar and groovy-2.5.9-indy.jar in the classpath. I made some tests and it seems like the `indy` classifier in target is ignored.
