### ISSUE TITLE
Gradle 8.10 Significantly Slower Due to Dependency Resolution

### ISSUE THREAD

**Issue by bardolf** [gradle/gradle#30239] opened 2024-08-20 08:14 UTC
### Current Behavior

After upgrading from Gradle 8.9 to Gradle 8.10, I am experiencing a significant performance slowdown in my build process, particularly related to dependency resolution. In my project, the build time has increased from 44 seconds (in Gradle 8.9) to 2 minutes and 39 seconds (in Gradle 8.10).

The issue appears to stem from the increased time spent in resolving detached configurations. I am also seeing a large number of messages related to detached configurations that were not present in Gradle 8.9, such as:

`Resolve dependencies of :api> develop-b996c3c-detachedConfiguration100-develop-b996c3c.pom`

Running the build with the `--offline` flag in Gradle 8.10 restores the build speed to what I experienced in Gradle 8.9, but this is not a viable solution since it alters the behavior of dependency resolution.

### Expected Behavior

The performance of Gradle 8.10 should be on par with or better than Gradle 8.9, particularly in terms of dependency resolution. The build should not experience significant slowdowns in the dependency resolution phase, and the large number of detached configuration resolution messages should not be present unless necessary.

### Context (optional)

- **Project Type**: Spring Boot, Kotlin, multi-module-project
- **OS**: Linux 6.5.0-45-generic (Ubuntu-based)
- **JVM**: Eclipse Adoptium 21.0.1+12-LTS
- **Gradle Versions Tested**: 8.9 and 8.10
- **Build Command**: `./gradlew clean build -x test`

I disabled the Gradle daemon (`org.gradle.daemon=false`) for reproducibility and comparison between the two versions. No changes were made to the codebase during this testing.

### Steps to Reproduce

On my source code, just ./gradlew clean build -x test

Profile outputs 

**8.10** 
All dependencies	1m43.36s
:api:detachedConfiguration10	0.903s
:backend:detachedConfiguration13	0.852s
:api:detachedConfiguration81	0.613s
:common:detachedConfiguration115	0.610s
:security:detachedConfiguration124	0.610s
:api:detachedConfiguration75	0.595s
...

**8.9** 
All dependencies	2.648s
:backend:detachedConfiguration13	0.301s
:classpath	0.077s
:strategic-planning-export:detachedConfiguration13	0.073s
:api:detachedConfiguration9	0.033s
:migration:detachedConfiguration178	0.031s
:migration:detachedConfiguration13	0.026s

### Gradle version

8.10

### Build scan URL (optional)

https://scans.gradle.com/s/ht2k7xctcwwfc

### Your Environment (optional)

- **OS**: Linux 6.5.0-45-generic (Ubuntu-based)
- **JVM**: Eclipse Adoptium 21.0.1+12-LTS
- **Gradle Versions Tested**: 8.9 and 8.10

**Comment by ljacomet** [comment] 2024-08-20 13:25
We appreciate the effort, but we must ask for more information so that we can triage it. 

We do not see an immediate root cause, and we need a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) for the triage. If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

***

Unfortunately, without a reproducer, tracking down the source of the problem is going to be almost impossible.

Improvements were actually delivered around dependency resolution performance and memory usage in Gradle 8.10.

So this might indicate that you have a particular setup that possible is affected by those improvements.

A minimal thing that could help: share a build scan of the same build with Gradle 8.9.

**Comment by gurpreetsingh85** [comment] 2024-08-20 16:21
@ljacomet 

This is indeed an issue with 8.10. The delay is caused by several dependencies that fail to be resolved, which happens only with 8.10. The failed configuration is just a project configuration repeated several times.
 
e.g `com.foo:1.00-SNAPSHOT-detachedConfigurationxxx:1.0.0-SNAPSHOT FAILED`

I can share my build scan URLs via email (if possible) instead of sharing the links here.

8.9
<img width="591" alt="Screenshot 2024-08-20 at 9 13 23 AM" src="https://github.com/user-attachments/assets/42e910bc-ed1a-40fd-9121-78804e8959f8">

<img width="605" alt="Screenshot 2024-08-20 at 9 15 52 AM" src="https://github.com/user-attachments/assets/4c7ae68a-3b82-4663-9f66-f622e71ab3f1">


8.10
<img width="824" alt="Screenshot 2024-08-20 at 9 13 39 AM" src="https://github.com/user-attachments/assets/a9c0c62c-dc33-436b-af12-651a6f1f4aeb">

<img width="652" alt="Screenshot 2024-08-20 at 9 16 07 AM" src="https://github.com/user-attachments/assets/3158235e-71db-469a-a481-df94feb6d270">

**Comment by ljacomet** [comment] 2024-08-21 08:42
Thanks for providing additional information. Marking this as a regression for the relevant team to investigate.

**Comment by lynheo** [comment] 2024-08-23 00:12
I am experiencing the same issue. After the 8.10 upgrade, I keep seeing messages like "detachedConfiguration281 > 2.0.2-detachedConfiguration280-2.0.2.pom" repeatedly.

The build time has increased significantly from 1 minute to 18 minutes.

**Comment by timbotetsu** [comment] 2024-08-23 03:04
same issue here, keep showing "Resolving global dependency management for project 'xxx'"

**Comment by octylFractal** [comment] 2024-08-26 20:31
Fixed by reverting the change in #30317, full proper fix is tracked by #30320.

**Closed** 2024-08-27 17:29 UTC
Labels: a:regression, in:dependency-resolution, has:release-notes

**Comment by ljacomet** [comment] 2025-01-09 15:06
For future investigation:

This was caused by #29468 in an attempt to fix #24126
