### ISSUE TITLE
An unexpected error while updating to 8.11

### ISSUE THREAD

**Issue by JanecekPetr** [gradle/gradle#31272] opened 2024-11-13 15:08 UTC
### Current Behavior

While updating an old project from Gradle 7.5.1 to 8.11 via `./gradlew wrapper --gradle-version 8.11`, while the update seems to have worked, there was an error mssage. I got this output by the end of the update:
```
BUILD SUCCESSFUL in 58s
1 actionable task: 1 executed
Configuration cache entry stored.
'VA_OPTSGRADLE_OPTSAPP_BASE_NAMECLASSPATH*' is not recognized as an internal or external command,
operable program or batch file.
```

This is on Windows 11, 23H2, in Powershell, using Java 11.0.25 (Temurin)

### Expected Behavior

```
BUILD SUCCESSFUL in 58s
1 actionable task: 1 executed
Configuration cache entry stored.
```
was the expected output, without any errors.

### Context (optional)

I also tried updating a completeyl empty project from 7.6.4 to 8.11, this consistently gives:
```
BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
'ainEnd' is not recognized as an internal or external command,
operable program or batch file.
```

If I rerun `./gradlew wrapper --gradle-version 8.11` on this just-updated project with 8.11, I get
```
BUILD SUCCESSFUL in 3s
1 actionable task: 1 executed
Configuration cache entry reused.
'gradle.appname' is not recognized as an internal or external command,
operable program or batch file.
```

Further invocation do not get any errors.

### Self-contained Reproducer Project

A literal empty project.
```
gradle init
./gradlew wrapper --gradle-version 7.6.4
./gradlew wrapper --gradle-version 8.11
```

### Gradle version

8.11

### Your Environment (optional)

Windows 11 23H2, Czech locale
Java 11.0.25 (Temurin)
Powershell 7.4.5

**Comment by BlockyTheDev** [comment] 2024-11-13 19:52
I noticed the same thing today when updating from 8.10.2 to 8.11.

Powershell 7.4.6 / Java 21.0.5 (Azul Zulu)

**Comment by ov7a** [comment] 2024-11-14 15:11
We're investigating this.
FTR, I cannot reproduce the issue with windows 10.

There are no recent changes related to the wrapper script (IIUC), but the error with garbled output (...GRADLE_OPTS...) indicates that this might be something changed with bat processing.

Meanwhile, @BlockyTheDev @JanecekPetr can you confirm that `.bat` is used and the issue is reproducible with `./gradlew.bat wrapper --gradle-version 8.11`? Can you also double-check the wrapper script contents are not changed by any third party? 

And if you are aware of any new features in Windows/Powershell related to bat/scripts execution, please share this as well.

**Comment by BlockyTheDev** [comment] 2024-11-14 15:37
Tested on Windows Version 10.0.22631.4391

What I found out the command wrong text appears **after** the "BUILD SUCCESSFUL in" text.

Version 8.10.2 to 8.11 - with following command in Powershell: `./gradlew wrapper --gradle-version 8.11`
```
Starting a Gradle Daemon (subsequent builds will be faster)

BUILD SUCCESSFUL in 32s
1 actionable task: 1 executed
Der Befehl "GRADLE_OPTSAPP_BASE_NAMECLASSPATH*" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
```

Version 8.10.2 to 8.11 - with following command in Powershell: `./gradlew.bat wrapper --gradle-version 8.11`
```
BUILD SUCCESSFUL in 4s
1 actionable task: 1 executed
Der Befehl "GRADLE_OPTSAPP_BASE_NAMECLASSPATH*" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
```

Version 8.10.2 to 8.11 - same happens on a normal Windows command prompt with following command: `gradlew wrapper --gradle-version 8.11` and `gradlew.bat wrapper --gradle-version 8.11`.


Version 8.11 to 8.11 - the error gets not printed, but I think that the logic is not executed when the version is already the same: `1 up-to-date`

Following things get changed on the update from Gradle 8.10.2 to 8.11:
![Image](https://github.com/user-attachments/assets/21aac5f0-bf12-4d51-af29-48b2ba76ae15)
![Image](https://github.com/user-attachments/assets/06b8ec05-8d6c-41e4-9d06-f70517d5b223)
![Image](https://github.com/user-attachments/assets/969d9b40-721b-441f-968b-177fa0dacff7)
![Image](https://github.com/user-attachments/assets/ae15eebf-83a6-4cd3-8e59-30e3bd87fb3e)
![Image](https://github.com/user-attachments/assets/dd3d8104-a88a-4878-a470-17b948ffe018)
![Image](https://github.com/user-attachments/assets/ffe60351-c517-4142-8ccb-07b0a66dae2a)
![Image](https://github.com/user-attachments/assets/c260ab0f-ea46-4dce-aa99-647b5705bdd0)

**Comment by ov7a** [comment] 2024-11-14 15:46
@BlockyTheDev Thanks for the test.

Regarding the changes in the script - that's odd. There are no changes in scripts between 8.10.2 and 8.11. See, for example, [this PR](https://github.com/gradle/gradle-issue-reproducer/pull/23/files). Judging by the changes, it seems the old script is [at most](https://github.com/gradle/gradle/commit/10d48cde66cf55b707c86553d749fb7e2e9a8a74) from 8.6.

**Comment by ov7a** [comment] 2024-11-14 15:52
I managed to reproduce this eventually.

This will be closed as a duplicate of
* https://github.com/gradle/gradle/issues/7883

**Closed by ov7a** 2024-11-14 15:52 UTC
Labels: a:regression, to-triage

**Comment by BlockyTheDev** [comment] 2024-11-14 15:54
> [@BlockyTheDev](https://github.com/BlockyTheDev) Thanks for the test.
> 
> Regarding the changes in the script - that's odd. There are no changes in scripts between 8.10.2 and 8.11. See, for example, [this PR](https://github.com/gradle/gradle-issue-reproducer/pull/23/files). Judging by the changes, it seems the old script is [at most](https://github.com/gradle/gradle/commit/10d48cde66cf55b707c86553d749fb7e2e9a8a74) from 8.6.

Updated another project of mine, the repository "it-project-10th-grade" on my profile, which ended in

```
BUILD SUCCESSFUL in 31s
1 actionable task: 1 executed
Der Befehl "gradle.appname" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
```

**Comment by BlockyTheDev** [comment] 2024-11-14 15:55
Interesting, that it happened the first time on 8.11 on my side with such errors when it is existing for such a long time already

**Comment by ov7a** [comment] 2024-11-14 16:00
> Interesting, that it happened the first time on 8.11 on my side with such errors when it is existing for such a long time already

I agree that it's odd, indeed. But it's flaky. Maybe something has changed that causes the problem to occur more often. In any case, the root cause should be fixed, and further investigation is not worth the effort, IMO.
