### ISSUE TITLE
Tooling API reports incorrect origin plugin of tasks

### ISSUE THREAD

**Issue by AmrAfifiy** [gradle/gradle#11183] opened 2019-10-30 12:18 UTC
In android when a plugin creates a task inside the afterevaluate callback of Android Gradle Plugin, this task is attributed to AGP instead of the plugin that created it. It's a problem because almost all of the plugins create their tasks this way when they want to specify a dependency on AGP.

To reproduce, simply have a plugin that registers a task inside AGP variant API like the following

```
apply plugin: 'com.android.application'

class DummyTask extends DefaultTask {
    @TaskAction
    def run() {
    }
}
class DummyPlugin implements Plugin<Project> {
    void apply(Project project) {
        project.android.applicationVariants.all { variant ->
            DummyTask task = project.tasks.create("dummy${variant.name.capitalize()}Task", DummyTask)
            variant.mergeResourcesProvider.configure {
                dependsOn(task)
            }
        }
    }
}
apply plugin: DummyPlugin
```
When the TaskFinishEvent for this task is received, `event.descriptor.originPlugin.displayName` will be `com.android.internal.application`

**Comment by adammurdoch** [comment] 2019-10-31 02:03
I suspect this is due to the AGP using the internal `DefaultDomainObjectSet` constructor to create `DomainObjectSet` instances, rather than using the factory methods on the `ObjectFactory` public API. The internal constructor does not instrument the collections to collect any plugin attribution information, whereas the public factory methods do instrument the collections. If you change the AGP to use the factory methods, the attribution information reported by the tooling API should be correct. There seem to be a few usages of `DefaultDomainObjectSet` in the AGP, and these should all be replaced.

The factory methods are relatively recent, and there is more detail here: https://docs.gradle.org/current/userguide/custom_gradle_types.html#collection_types

**Comment by adammurdoch** [comment] 2019-11-01 21:45
Related, this PR adds a few missing factory methods and some deprecation warnings to the internal constructors to avoid people falling into this trap in the future: https://github.com/gradle/gradle/pull/11201

**Comment by adammurdoch** [comment] 2019-11-01 21:46
I'm going to close this as not a bug, and the problem will be fixed once the AGP is migrated to use the factory methods. Please reopen if this turns out to not be the case.

**Closed by adammurdoch** 2019-11-01 21:46 UTC
Labels: @instant-execution, a:bug, from:contributor
