### ISSUE TITLE
Build fails to switch repositories after a successful DNS resolution but connection timeout

### ISSUE THREAD

**Issue by stager0909-ray** [gradle/gradle#28865] opened 2024-04-18 10:41 UTC
### Current Behavior

We are using Gradle builds across various company IDCs, each having its own Nexus repository configured in build.gradle.kts. Our configuration specifies multiple repositories as follows:
```
repositories {
    maven {
        name = "A"
        url = uri("http://nexus.a.com/repository/test")
        isAllowInsecureProtocol = true
    }
    maven {
        name = "B"
        url = uri("http://nexus.b.com/repository/test")
        isAllowInsecureProtocol = true
    }
    maven {
        name = "C"
        url = uri("http://nexus.c.com/repository/test")
        isAllowInsecureProtocol = true
    }
}
```
When building at company B, if DNS resolution for the first listed repository nexus.a.com fails, Gradle correctly switches to the next repository nexus.b.com and the build succeeds. However, if DNS resolution is mistakenly successful for nexus.a.com but the connection times out, Gradle does not attempt to connect to the next repository and the build fails. This behavior prevents the build from switching to a subsequent repository after a connection timeout, despite a successful DNS resolution.

### Expected Behavior

After a successful DNS resolution, if a connection timeout occurs, Gradle should attempt to connect to the next configured repository.

### Steps to Reproduce

1. Configure multiple Nexus repositories in build.gradle.kts.
2. Introduce a scenario where DNS resolution for the first repository is successful, but the connection times out.
3. Attempt a Gradle build.
4. Observe that the build does not proceed to the next repository and fails due to a timeout with the first one.

### Gradle version

7.5.1

**Comment by ov7a** [comment] 2024-04-18 12:22
This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/22135

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

**Closed by ov7a** 2024-04-18 12:22 UTC
Labels: a:bug, to-triage

**Comment by honorhs** [comment] 2024-04-19 03:06
@ov7a This issue appears to be a situation that requires a fallback, not a retry.

The search for the repository should proceed in the order of nexus.a.com -> nexus.b.com -> nexus.c.com. However, due to a timeout occurring at nexus.a.com, it fails to continue the search at nexus.b.com, resulting in a timeout failure.

**Comment by ov7a** [comment] 2024-04-19 06:50
@honorhs I agree with you. The reason why I marked it as a duplicate - it's a coupled logic and it would be easier to track in one place.
