### ISSUE TITLE
Unable to create a Groovy Map object inside of a task

### ISSUE THREAD

**Issue by skyviper** [gradle/gradle#13177] opened 2020-05-19 16:17 UTC
### Expected Behavior

A Groovy Map object should be created inside of a task.
task{
def newMap = [sname:'', name:'', buildnr:'', path:'']
}
Should work according to documentation but doesn't.
And the limitation should be documented.
### Current Behavior

A Groovy Map object can't be created inside of a task.
Document these limitation.
### Context

Too much time spent trying to implement an incomplete example and researching the issue. This is affecting our schedule and lowing our confidence. The task was completed faster using Ant.

Documentation quality. Document limitations and work-arounds.
### Steps to Reproduce 

Tun the task above.

### Your Environment

Windows 7 and 10

Build scan URL:

**Comment by eskatos** [comment] 2020-05-19 16:23
Hi @skyviper,

Your code works for me:

```groovy
// build.gradle

task myTask {
    def newMap = [sname:'', name:'', buildnr:'', path:'']
    doLast {
        println(newMap)
    }
}
```

Running `gradle myTask` outputs:
```
> Task :myTask
[sname:, name:, buildnr:, path:]

BUILD SUCCESSFUL in 547ms
1 actionable task: 1 executed
```
https://scans.gradle.com/s/iqan4fwpiiruq/console-log?anchor=4

Could you provide a bit more information about what doesn't work?
A build script that we can use to reproduce the problem would help.

**Comment by skyviper** [comment] 2020-05-19 17:08
Hi Paul,There error I get is " Could not set unknown property 'newMap' for task ':myTask' of type org.gradle.api.DefaultTask."Build Scan:https://gradle.com/s/2cv2pos3xbiqm

I also attached a debug log.
Regards,
Tony
    On Tuesday, May 19, 2020, 10:23:28 AM MDT, Paul Merlin <notifications@github.com> wrote:  
 
 


Hi @skyviper,

Your code works for me:
// build.gradle

task myTask {
    def newMap = [sname:'', name:'', buildnr:'', path:'']
    doLast {
        println(newMap)
    }
}
Running gradle myTask outputs:
> Task :myTask
[sname:, name:, buildnr:, path:]

BUILD SUCCESSFUL in 547ms
1 actionable task: 1 executed

https://scans.gradle.com/s/iqan4fwpiiruq/console-log?anchor=4

Could you provide a bit more information about what doesn't work?
A build script that we can use to reproduce the problem would help.

**Comment by eskatos** [comment] 2020-05-19 17:14
Hard to say what happens without the corresponding build script.

But it seems like a Groovy programming error.

I guess you do something like:
```groovy
newMap = [...]
```

without the Groovy `def` keyword to declare a variable.

Where the following would work:
```groovy
def newMap = [...]
```

Did I guess right?

**Comment by skyviper** [comment] 2020-05-19 17:29
That looks like it fixed the issue. Funny thing is that I must have missed this through the trees.

**Comment by eskatos** [comment] 2020-05-20 08:24
Thanks for confirming you fixed it. Closing this issue

GitHub issues are for bug reports or feature requests. For support questions, please prefer the Gradle forums at https://discuss.gradle.org/ or join the Gradle community on Slack, you can find a link here https://github.com/gradle/gradle#need-help

**Closed by eskatos** 2020-05-20 08:24 UTC
Labels: a:bug, from:contributor
