### ISSUE TITLE
Gradle should ship with its own copy of the JVM

### ISSUE THREAD

**Issue by axelfontaine** [gradle/gradle#25753] opened 2023-07-13 08:19 UTC
### Expected Behavior

When checking out a project containing `gradlew`, it should be possible to simply run `gradlew` and have it download a Gradle distribution also containing the matching latest supported JVM version.

Equally when downloading Gradle from the website, it should be fully functional from the get go. I did this with the Flyway CLI at the time and the users really appreciated it. Less friction and guaranteed compatibility is always a win and the extra disk space required is not really an issue anymore these days.

### Current Behavior (optional)

Users must look up what the required JVM version is, download and install it, set up the necessary environment variables and only then will Gradle actually run.

### Context

This provides a much better out of the box experience for new users and is much more convenient when setting up a new machine or upgrading Gradle.

**Comment by ov7a** [comment] 2023-07-14 12:20
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #2508

Please add your use case and 👍 to that issue.

**Closed by ov7a** 2023-07-14 12:20 UTC
Labels: a:feature, to-triage
