### ISSUE TITLE
Grails Core - Could not resolve all files for configuration ':detachedConfiguration2'. with sourcesJar task

### ISSUE THREAD

**Issue by puneetbehl** [gradle/gradle#14481] opened 2020-09-09 15:20 UTC
We recently upgraded Grails Core to use Gradle 6.5, and now we are not able to execute sourcesJar due to the following error:
```
> Task :sourcesJars FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sourcesJars'.
> Could not resolve all files for configuration ':detachedConfiguration2'.
   > Could not resolve org.grails:grails-datastore-core:7.1.0.M2.
     Required by:
         project :
      > Project : declares a dependency from configuration 'detachedConfiguration2' to configuration 'runtimeElements' which is not declared in the descriptor for org.grails:grails-datastore-core:7.1.0.M2.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

### Expected Behavior
Should be able to execute assemble without any errors. 

### Current Behavior
The above exception is thrown. 

### Context
This failed while executing the assemble task as part of releasing Grails 4.1.0.M2. 

### Steps to Reproduce 

* Please clone https://github.com/grails/grails-core/tree/v4.1.0.M2 (Tag v4.1.0.M2)
* Execute `./gradlew assemble`.

**Comment by puneetbehl** [comment] 2020-09-09 21:30
I think the problem might be related to something in Gradle 6 which might affect the following code:
```
task sourcesJars(type: Sync) {
    into homeSrcDir
    from subprojects.findAll { !it.name.startsWith('grails-test-suite') && !it.name.startsWith('grails-dependencies') && !it.name.startsWith('grails-bom') }.sourcesJar*.outputs*.files

    // sourcesFor comes from GrailsBuildPlugin
    from { sourcesFor(libsConfigurations*.copyRecursive { it.name.startsWith('grails-datastore') }.collect { it.transitive = false; it }) }
}
```
Ref: https://github.com/grails/grails-core/blob/v4.1.0.M2/gradle/assemble.gradle#L128-L133

**Comment by puneetbehl** [comment] 2020-09-09 21:42
Another information that may be helpful is when I debug backward from the `ConfigurationNotFoundException` [here](https://github.com/gradle/gradle/blob/v6.5.0/subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/LocalComponentDependencyMetadata.java#L140).

I noticed that the following code return empty information now vs before:
```
((DefaultMavenModuleResolveMetadata) targetComponent).configurationDefinitions
```

**Comment by puneetbehl** [comment] 2020-09-10 13:46
It seems like the problem goes away after updating the `maven { url "https://repo.grails.org/grails/core" }` with  the following in https://github.com/grails/grails-core/blob/v4.1.0.M2/build.gradle#L190  as: 

```
maven {
            url "https://repo.grails.org/grails/core"
            metadataSources {
                mavenPom()
                artifact()
                ignoreGradleMetadataRedirection()
            }
        }
```

However, I do not fully understand the reason and what might be the side effect of adding it.

**Comment by jjohannes** [comment] 2020-09-17 08:47
What you are seeing is a combination of things caused by the fact that [Gradle 6+ publishes and consumes Gradle Module Metadata by default](https://docs.gradle.org/current/userguide/upgrading_version_5.html#gradle_module_metadata_is_always_published).

In Gradle metadata all _variants_ of a component (such as _Java runtime_ or _Java API_) are explicitly declared. Gradle's dependency management engine then goes into [variant aware mode](https://docs.gradle.org/current/userguide/variant_model.html) and selects the right variant based on what you request, expressed through _attributes_.

In this mode, the explicit selection of a _configuration_ as part of a dependency declaration no longer works. You do this here:
https://github.com/grails/grails-core/blob/676bbb9504fd4613e32daa9c62dc6477ee07ddd8/buildSrc/src/main/groovy/org/grails/gradle/GrailsBuildPlugin.groovy#L54

You can fix this be removing `dependency.setTargetConfiguration(resolvedDependency.configuration)` and instead request the Java runtime variant when resolving here:
https://github.com/grails/grails-core/blob/676bbb9504fd4613e32daa9c62dc6477ee07ddd8/buildSrc/src/main/groovy/org/grails/gradle/GrailsBuildPlugin.groovy#L68

```
project.configurations.detachedConfiguration(sourceDependencies as Dependency[]).with(true) { 
  attributes.attribute(Usage.USAGE_ATTRIBUTE, project.objects.named(Usage, Usage.JAVA_RUNTIME))
}
```

That's the simplest fix.

In general, _variant aware dependency management_ in Gradle 6 could be used to simplify your use case here a lot. You can use [`withSources()` to publish the sources Jar](https://docs.gradle.org/current/userguide/publishing_customization.html#sec:adding-variants-to-existing-components). Then _sources_ will be an additional variant in the metadata. You can then match that by resolving a configuration with attributes `Category = Categroy.DOCUMENTATION` and `DocsType = DocsType.SOURCES`. You can probably remove most of the special build logic your have around your `sourcesFor` method. (And you can do a similar thing for Javadoc as well).

**Comment by puneetbehl** [comment] 2020-09-23 12:14
Thank you @jjohannes for your input, the fix above solves the problem. I will also try to work towards improving the logic around `sourcesFor` method.

**Comment by jjohannes** [comment] 2020-09-24 07:06
Great to her @puneetbehl. I am closing this issue since there is nothing to fix on the Gradle side at the moment. Let use know if you run into other issues.

**Closed by jjohannes** 2020-09-24 07:06 UTC
Labels: @jvm, from:contributor, in:dependency-management
