### ISSUE TITLE
Groovy plugin interferes idea plugin while processing source sets

### ISSUE THREAD

**Issue by bkpawlowski** [gradle/gradle#13929] opened 2020-07-26 15:03 UTC
Hello, this is my first issue report over here, I hope it's pretty decent and well described.
I'm not sure if this problem is related with `IntelliJ Idea` itself or with `groovy-plugin`, however I found out processing source sets by `IntelliJ Idea` works perfectly fine without `groovy-plugin` so I decided to start here.

Groovy plugin interferes idea plugin while processing source sets. 

### Expected Behavior
Source sets marked as `test source sets` within `idea-plugin` config, should be recognized by intellij idea as `test sources`.
![obraz](https://user-images.githubusercontent.com/4988070/88482195-0e2f1c80-cf60-11ea-963d-58ca0e9fae01.png)

### Current Behavior
Source sets marked as `test source set` within `idea-plugin` config, is recognized by intellij idea as `sources`.
![obraz](https://user-images.githubusercontent.com/4988070/88482189-07080e80-cf60-11ea-8c27-e09342a8af69.png)

### Context
It's painful during refactoring, because moving certain packages with source code elsewhere, makes your tests source code (from the same package) to move to the same package in the same folder where source code was moved.

So lets say I have structure like:
```
src/main/java - source code
src/test/groovy - test source code
src/additionalTest/groovy - additional test source code
```

moving classes/packages from inside `src/main/java`, makes `src/test/groovy` and `src/additionalTest/groovy` classes to move to `src/main/java`

### Steps to Reproduce 
[github repo](https://github.com/bkpawlowski/gradle-groovy-plugin-affects-idea-plugin)

1. Define additional test source set using `idea-plugin`
2. IntelliJ Idea should recognize your test source set perfectly fine as in subproject in linked repository(idea-plugin-standalone)

3. Add `groovy-plugin`, you can optionally define another test source set for groovy language
4. IntelliJ Idea is no longer recognizing your previously creates test source set as test source set, but rather like source set as in subproject in linked repository (groovy-affects-idea-plugin)

NOTE: This does not affect default test source sets under `src/test/*`

### Your Environment
Build scan URL: https://scans.gradle.com/s/lrkwnubtbyidu

**Comment by jbartok** [comment] 2021-09-08 11:59
This has been recently fixed in the gradle/gradle build, we will get back with exactly how and when and with documentation updates.

**Comment by big-guy** [comment] 2021-12-10 17:26
@jbartok do you know if this could be closed?

**Comment by jbartok** [comment] 2021-12-13 08:49
@big-guy no, I didn't get to investigate it.

**Comment by ljacomet** [comment] 2022-11-04 10:52
There is no bug here, the issue is that when you add the groovy plugin, there is an addition source `src/additionalTest/groovy` which also needs to be recorded as a test one.
If not, then IntelliJ will see a single `sourceSet` as both production and test and most likely then marks it as prod.

**Closed by ljacomet** 2022-11-04 10:52 UTC
Labels: a:bug, to-triage, @support
