### ISSUE TITLE
Test Fixtures are incompatible with project isolation

### ISSUE THREAD

**Issue by leonard84** [gradle/gradle#30156] opened 2024-08-12 13:53 UTC
### Current Behavior

When using `jvm-test-fixtures` to refer to another project with project isolation enabled this  will fail with 
```
- Unknown location: Project ':lib' cannot access 'Project.group' functionality on another project ':common'
- Unknown location: Project ':lib' cannot access 'Project.version' functionality on another project ':common'
```
[configuration-cache-report.html.zip](https://github.com/user-attachments/files/16582911/configuration-cache-report.html.zip)

### Expected Behavior

Test fixtures are compatible with project isolation.

### Steps to Reproduce

Check and run `./gradlew :lib:test -Dorg.gradle.unsafe.isolated-projects=true --configuration-cache`[project-isolation-reproducer.zip](https://github.com/user-attachments/files/16582899/project-isolation-reproducer.zip)

### Gradle version

8.9

### Build scan URL (optional)

https://scans.gradle.com/s/kfoyti7z5qi3u

**Comment by jvandort** [comment] 2024-08-12 15:14
We need an IP-safe version of `ProjectDerivedCapability`. 

A `testFixtures` modifier for a project dependency derives the capability coordinates from a live project instance. When the resolution engine tries to fetch the capability coordinates from another project, it accesses the mutable state of the other project. 

We need a replacement for `ProjectDerivedCapability` that does not rely on a live project instance. Instead, it should hold a reference to the project's build tree path, and then construct the capability coordinates using the module identity of the target project component, which is itself generated in an IP compatible way.

**Comment by jvandort** [comment] 2024-08-12 15:21
We can still use a `ProjectDerivedCapability` on the producer side, as that is realized to an `ImmutableCapability` during construction of the component metadata -- which is done while holding the project lock of the target component. 

However, we need this functionality for the consumer-side, which declares a dependency on the target component. Those dependencies are resolved without the lock on the target component.

**Comment by jvandort** [comment] 2024-08-12 15:25
A solution like this however may be impossible, given that on the consumer side, we would still need to implement the `Capability` interface, which has `getName`, `getVersion`, and `getGroup`. These cannot be safely implemented on the consumer side, as it is impossible to know what these values are on the consumer side without accessing the target project. 

We may need to either have a hacky way of implementing these on the consumer side by properly acquiring project locks (and holding a reference to the target project build tree path), or change the `Capability` interface to be an opaque identifier. This would mean only Gradle will be able to implement the `Capability` interface -- but this is something we already kinda want to enforce.

**Comment by jvandort** [comment] 2024-08-12 15:29
Currently, it seems you can only use `ProjectDerivedCapability` on the consumer side using `testFixtures`, however we have seen users try to emulate their own behavior with things like (psuedocode below)

```
def projectDependencyFor(Project p, String feature) {
    return dependencyFactory.create(p) {
        capabilities {
            requireCapability(provider {
                "project.group:project.name-${feature}:project.version"
            })
        }
    }
}
```

We should introduce an API that allows you to request a feature of a component:

```
implementation(project(":foo")) {
    capabilities {
        requireFeature("testFixtures")
    }
}
```

Or perhaps

```
implementation(featureOf(project(":foo"), "testFixtures"))
```

**Comment by big-guy** [comment] 2024-08-12 16:47
@bamboo @alllex how important is this to solve for you to make progress with IP?

**Comment by jjohannes** [comment] 2024-08-20 12:23
For context:
- Workaround: https://github.com/gradle/gradle/issues/27872#issuecomment-2151775051 (maybe this is even a duplicate of that issue?)
- Related, for the general "feature" case: https://github.com/gradle/gradle/issues/25629

**Closed** 2024-09-24 19:13 UTC
Labels: a:bug, in:dependency-declarations, in:isolated-projects
