### ISSUE TITLE
Not mapping ‘+’ version range selectors for generated pom files

### ISSUE THREAD

**Issue by kuniss** [gradle/gradle#931] opened 2016-11-28 10:16 UTC
This issue was moved from Jira https://issues.gradle.org/browse/GRADLE-3213 to GitHub.

### Description (taken over from Jira issue)
When using version ranges like 1.+ or 1+ Gradle doesn't map this to a maven version syntax. There is no proper maven version selector syntax that represents the same range that `1.+` or `1+` represents in Gradle.

### Expected Behavior
It would be very helpful for Gradle/Maven mixed teams to generate POM file with Maven valid syntax for dynamic version dependencies. E.g.
```xml
<version>[1.1.0,1.2.0)</version>
```
for an dependency specified in a Gradle build file as `1.1.+`.

### Current Behavior

Currently the following POM file content is generated. 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>platform-bln</groupId>
  <artifactId>javapos-config</artifactId>
  <version>1.55.32</version>
  <dependencies>
    <dependency>
      <groupId>platform-bln</groupId>
      <artifactId>javapos-jcl</artifactId>
      <version>1.1.+</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>thirdparty</groupId>
      <artifactId>jcl</artifactId>
      <version>2.2.0</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</project>
```

The problem is the line
```xml
<version>1.1.+</version>
``` 
as it contains version syntax not processable by Maven build systems.

### Context
We have two teams, one working with Maven, the other having implemented a Gradle build process. This build process relies on a 3 point version X.Y.Z where X is the major version and Y is the minor version, both maintained manually by the developers according to semantic version rules. However, the Z part is maintained automatically by our build server which increments it for every release candidate it builds (also checking in the change into the source repo). We call Z the "build number".
This works very well for the Gradle-based team. Every release candidate version is ensured to be unique; there cannot be two release candidate packages with the same full qualified version number at all (as long as the build system is implemented correctly).

The build server builds the release candidates very frequently (each night) such that the Gradle team does not want to maintain the dependencies in the projects including the build number as it would become a night mare as it changes so often and in fact does not provide any additional dependency information.
As long as every developer consider the semantic version rules (which every one is required), the build number is not important for dependency maintenance. Therefore we are using dynamic versions in the form of "X.Y.+" to maintain the dependencies.
This fits well to our version model and together with the Gradle caching provides a very good build experience.

The problem come in the first time when the Maven team wanted to add a dependency to one of our components. The maven dependency resolution system just fails as it tried to get a version "X.Y.+" which of course does not exist in our Nexus repository.

### Steps to Reproduce
Just publish a package to a Maven's Nexus repository with dynamic dependencies (those with a dynamic marker '+'  at the end) instead of explicit versions. The POM file will contain the dynamic markers too.

### Your Environment
Not important here, as it is a principle problem.

### Workaround
The workaround replaces the Ivy/Gradle version range syntax with '+' at the end by the equivalent Maven version range syntax defined at http://maven.apache.org/enforcer/enforcer-rules/versionRanges.html.
It uses a post configuration hook provided by the maven plugin:

```groovy
uploadArchives.repositories.mavenDeployer.pom*.whenConfigured { pom ->
	pom.dependencies.each { dep -> dep.version = dep.version.replaceFirst('(\\d+(\\.\\d+)*)\\.?\\+', '[$1.0,)') }
}
```
The code example is derived from Example 31.7 "Modifying auto-generated content" https://docs.gradle.org/3.0/userguide/maven_plugin.html.

It should properly handle all kinds of dynamic dependency versions like 2+, 2.+, 3.2+, 3.2.+, 4.2.1+, 4.2.1.+ (shortly tested).

**Comment by bigdaz** [comment] 2016-11-28 17:34
One problem is that many projects use the Maven POM format with both Gradle producers and consumers. Since we don't have an exact 1:1 mapping between `1.+` and the Maven version range, we don't want to do this mapping for Gradle consumers.

For this reason, we can't simply map to the Maven version range syntax whenever we publish. There are a couple of options:
- Make it possible to declare whether a generated POM is destined for consumption by Maven, or just by Gradle. Do the conversion when publishing for consumption by Maven.
- Add a better version range syntax for Gradle, that permits a non-lossy conversion in the Maven version range syntax.

**Comment by kuniss** [comment] 2016-11-29 09:00
Seems I missed something. I thought, there is a unique mapping from Gradle to Maven version expressions. Of course, it is not a bi-directional mapping, more a partial one (means, there are Maven representations which do not map to a Gradle version representation). However, the mapping from Gradle to Maven version representation should be unique. But that's what's important!

@bigdaz Could you please provide an example, where mapping from a dynamic Gradle version to Maven is ambiguous and would produce 2 or more Maven representations?

I tried to figure it out for my self, as it seems my work around is not completely valid: Here is the table from http://maven.apache.org/enforcer/enforcer-rules/versionRanges.html enriched by an Gradle version column to map from.

Range | Meaning | Gradle dynamic version representation
-------|-----------|----------------------------------------------
1.0 | x >= 1.0 * The default Maven meaning for 1.0 is everything (,) but with 1.0 recommended. Obviously this doesn't work for enforcing versions here, so it has been redefined as a minimum version. | no representation applicable; however, I would recommend to map this to the Gradle version representation '1.+' assuming a semantic versioning schema as '1.0' is the version kind which is almost used in POMs; I'm not sure, but I guess, it is already done that way today?
(,1.0] | x <= 1.0 | no representation applicable
(,1.0) | x < 1.0 | no representation applicable
[1.0] 	|  x == 1.0 | 1.0
[1.0,) | x >= 1.0 | no representation applicable (that was my workaround)
(1.0,) | x > 1.0 | no representation applicable
(1.0,2.0) | 1.0 < x < 2.0 | no representation applicable
[1.0,2.0] | 1.0 <= x <= 2.0 | no representation applicable
[1.0,2.0) | 1.0 <= x < 2.0 | 1.+  (added by me, was not in the original table)
(,1.0],[1.2,) | x <= 1.0 or x >= 1.2. Multiple sets are comma-separated | no representation applicable
(,1.1),(1.1,) | x != 1.1 | no representation applicable

It seems there are only 2 lines of the table applicable as mapping from Gradle to Maven version representation.

Gradle version representation | Maven version representation | Meaning
-------------------------------|--------------------------------|-----------
1.0 | [1.0] | x == 1.0
1.+| [1.0,2.0) | 1.0 <= x < 2.0

So, the mapping from Gradle versions to Maven version representation is unique but not vice versa.
Gradle could provide a valid version representation for Maven consumers of Gradle dependencies. 
However, Gradle could not provide a Gradle version representation for Gradle consumers of Maven dependencies for any case. But that was also the case before. Gradle could made the "world" a little bit better by providing at least a valid mapping for Maven consumers...

... And of course, in our company we have Maven consumers as well as Gradle consumers. So, I'm very interested in getting this figured out for both cases. :-)

BTW: Would Gradle be able to handle version representations like '[1.0,2.0)' appearing in POM files quite well?

**Comment by bigdaz** [comment] 2016-11-29 13:42
This has been discussed in depth before:
https://groups.google.com/forum/#!msg/gradle-dev/wMkBhc-05tA/SZCvsIP23jQJ
https://groups.google.com/forum/#!msg/gradle-dev/owj_dKEqrKQ/OU6UNj5LwcIJ

I don't want to suggest that we shouldn't do anything, but in the past we've always ended up deciding that adding a new _semantic_ version range syntax for Gradle would be preferable to mapping our current _string matching_ syntax to a semantic on in POM files.

**Comment by kuniss** [comment] 2016-12-02 11:53
Thanks for the links. That was what I was locking for before contributing to https://issues.gradle.org/browse/GRADLE-3213 but never found... :-(

Due to the mentioned discussion I understand the problem now deeper (I've never used Maven, so I'm not really familiar with their version semantic in detail). 

So, my conclusion is, until Gradle does not get a more refined semantic version schema we have to use our own workaround to support Maven and Gradle teams from Gradle published components. It's quite clear that the work around will never solve it for any case. But setting up some constraints for a cross-team versioning schema a valid work around should be possible for us.

To realize that workaround, however, I'm lacking some information (not sure whether this documentation is elsewhere): Which mapping is implemented in Gradle for mapping POM version information back to Gradle version information?
@breskeby [mentioned](https://groups.google.com/d/msg/gradle-dev/wMkBhc-05tA/H17H1scmFPYJ) that the implementation is done. However, I could not exactly figure out what was implemented... 

Could some one of the Gradle team elaborate on that , or point me to the already done documentation or the implementation of the that mapping?

**Comment by oehme** [comment] 2017-09-06 13:53
Duplicate of #1232

**Closed by oehme** 2017-09-06 13:53 UTC
Labels: a:bug, affects-version:2.14, from:contributor, in:publishing-plugin
