### ISSUE TITLE
FileCollection is evaluated early in Gradle 5.0-rc4

### ISSUE THREAD

**Issue by tobiash** [gradle/gradle#7784] opened 2018-11-20 17:29 UTC
In Gradle 5.0-rc4, given a `Provider` wrapped in a `FileCollection` like this:

```
project.files(provider { File("a") }).builtBy("taskName")
```

the provider is evaluated before the `FileCollection.builtBy` is executed. With Gradle 4.10.2, it is evaluated only after `taskName` has been executed.

### Expected Behavior

The provider should only be called once the build dependencies have been executed. Alternatively there should be a way to create a truly lazy `FileCollection` that behaves like this.

### Current Behavior

The provider is called before the build dependencies have been executed.

### Context

This causes problems when the contents that the `FileCollection` should are not known without the results of the `builtBy` task.

I assume the new behaviour could stem from the necessity to look at all task input files before any tasks are executed?

### Steps to Reproduce (for bugs)

```kotlin
// build.gradle.kts
task("first") {
    doLast {
        println("Write")
        File("${project.buildDir}/foo").also { it.parentFile.mkdirs() }.writeText("Hello World")
    }
}

open class Consumer : DefaultTask() {

    @InputFiles
    val ins : ConfigurableFileCollection = project.files()

    @TaskAction
    fun run() {
        ins.forEach {
            println(it.absolutePath)
        }
    }
}

task("second", Consumer::class) {
    ins.from(files(provider {
        println("Accessed file collection")
        File("${project.buildDir}/foo")
    }) {
        builtBy("first")
    })
}
```
When the "second" task is run, the `FileCollection` is accessed twice, once apparently during the Configuration-Phase, and once when the task is actually run.

Gradle 4.10.2 output:
```
> Task :first
Write

> Task :second
Accessed file collection
```

Gradle 5.0-rc-4 output:
```
Accessed file collection

> Task :first
Write

> Task :second
Accessed file collection
```

**Comment by eskatos** [comment] 2018-11-20 18:05
Thank your for the report @tobiash.
I can reproduce using both the Groovy and the Kotlin DSL.

**Comment by tobiash** [comment] 2018-11-21 07:40
I am not completely sure. I changed my code to no throw and return an empty collection for the early evaluation, but I haven't checked yet if the early evaluation causes problems with the build cache or the up-to-date checks.

**Comment by big-guy** [comment] 2018-11-21 18:55
This isn't a regression, but it's a consequence of [trying to track inputs](https://docs.gradle.org/release-candidate/release-notes.html#plugin-authoring-features) to the `Consumer`. We need to unpack any the `provider {}` to see if it is something that's `Buildable`. The provider's value is checked when we're building the execution graph.

There are a few issues/things that could be better with your example:
- Please do not use `new File(...)` (Groovy, Java) or `File(...)` (Kotlin). This is always wrong.
- Combining `files()` and `provider {}` is a little odd.
- Explicitly calling `builtBy` should be unnecessary if things are wired together properly.

Here's a cleaned up version of what I was thinking:
```
open class Producer : DefaultTask() {
    @OutputFile
    val outputFile : RegularFileProperty = project.objects.fileProperty()

    @TaskAction
    fun run() {
        println("Write")
        outputFile.get().asFile.writeText("Hello World")
    }
}

open class Consumer : DefaultTask() {
    @InputFiles
    val ins : ConfigurableFileCollection = project.files()

    @TaskAction
    fun run() {
        ins.forEach {
            println(it.absolutePath)
        }
    }
}

val first = tasks.create("first", Producer::class) {
    outputFile.set(layout.buildDirectory.file("foo"))
}

task("second", Consumer::class) {
    ins.from(first.outputFile)
}
```

I'm going to close this issue as this is working as intended.  Thanks!

**Closed by big-guy** 2018-11-21 18:55 UTC
Labels: a:bug, in:core
