### ISSUE TITLE
Documentation link in CopySpec duplicate strategy not set error message should not be broken 

### ISSUE THREAD

**Issue by breskeby** [gradle/gradle#16824] opened 2021-04-14 07:10 UTC
When not declaring a duplicateStrategy we see an error message like this:

```
> Entry org/elasticsearch/spark/deploy/yarn/security/EsServiceCredentialProvider.scala is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.0/dsl/org.gradle.api.file.CopySpec.html#org.gradle.api.file.CopySpec:duplicatesStrategy for details.
```

The DSL link in the error message is broken due to `CopySpec` not part of the DSL. Instead only javadoc for `CopySpec` is available and should property be linked to from here.

 
### Expected Behavior

Documentation link in error messages point to valid Gradle documentation

### Current Behavior

Documentation link is broken.

### Your Environment
Gradle 7.0

Reproducible:

- Clone https://github.com/elastic/elasticsearch-hadoop/
- Run `./gradlew distribution`

**Comment by jjohannes** [comment] 2021-04-14 07:32
Thanks for reporting. This is a duplicate of #16785.

**Closed by jjohannes** 2021-04-14 07:32 UTC
Labels: a:bug, to-triage

**Comment by breskeby** [comment] 2021-04-14 07:53
sorry haven't seen that one. 👍
