### ISSUE TITLE
gradle disobeying its own environmental variables 

### ISSUE THREAD

**Issue by c3ph3us** [gradle/gradle#2106] opened 2017-05-22 15:23 UTC
1) setup gradle env variables 
`set GRADLE_HOME
and GRADLE_USER_HOME
in /etc/environment `
3) create dir when gradle likes to write 
`$ mkdir ~/.gradle `
4)  block complete access to this file 
`$ chmod 000 ~/.gradle `
5) exec gradle  version 3.5
` $ gradle `

```
    FAILURE: Build failed with an exception.
    * What went wrong:
    Failed to load native library 'libnative-platform.so' for Linux amd64.
```

**why gradle is not using the directory pointed by GRADLE_USER_HOME ???? and its stubbornly trying to gain access to forbidden place.** 

**no i don't want any gradle  files in my HOME !!!** 

checkup ( where gradle has  full capability to write) :

```
ls -al $GRADLE_HOME
razem 948
drwxr-xr-x+  7 ceph3us ceph3us   4096 maj 22 17:12 ./
drwxrwxr-x+ 39 root    opt       4096 maj 22 17:12 ../
drwxr-xr-x+  2 ceph3us ceph3us   4096 kwi 10 13:43 bin/
drwxrwx---+  2 ceph3us ceph3us   4096 maj 22 17:12 ceph3us/
-rw-r--r--+  1 ceph3us ceph3us 877522 kwi 10 13:39 getting-started.html
drwxr-xr-x+  2 ceph3us ceph3us   4096 kwi  7 00:00 init.d/
drwxr-xr-x+  3 ceph3us ceph3us   4096 kwi 10 13:43 lib/
-rw-r--r--+  1 ceph3us ceph3us  51625 kwi  7 00:00 LICENSE
drwxr-xr-x+  2 ceph3us ceph3us   4096 kwi  7 00:00 media/
-rw-r--r--+  1 ceph3us ceph3us    802 kwi  7 00:00 NOTICE
```

```
ls -al $GRADLE_USER_HOME
razem 8
drwxrwx---+ 2 ceph3us ceph3us 4096 maj 22 17:12 ./
drwxr-xr-x+ 7 ceph3us ceph3us 4096 maj 22 17:12 ../
```

**Comment by c3ph3us** [comment] 2017-05-22 15:25
btw 
**one way to trick gradle is to soft link this directory**

**Comment by lacasseio** [comment] 2017-05-24 11:21
Thanks for reporting this @c3ph3us. I'm not able to reproduce this error. What system are you using? Your first step assumes Windows and the console output from the follow-up steps seems to be *nix system. Could you double check that you set the environment variable with `export GRADLE_USER_HOME=...`? Thanks.

**Comment by c3ph3us** [comment] 2017-06-03 14:48
@lacasseio  no linux

**Comment by lacasseio** [comment] 2017-07-07 20:21
According to the Gradle code base, the order Gradle use to determine what path to use is the following:
1. The [command line flag](https://github.com/gradle/gradle/blob/master/subprojects/wrapper/src/main/java/org/gradle/wrapper/GradleWrapperMain.java#L116-L118): `--gradle-user-home` or `-g`
2. The [Java property](https://github.com/gradle/gradle/blob/master/subprojects/wrapper/src/main/java/org/gradle/wrapper/GradleUserHomeLookup.java#L28-L30): `gradle.user.home`
3. The [System environment variable](https://github.com/gradle/gradle/blob/master/subprojects/wrapper/src/main/java/org/gradle/wrapper/GradleUserHomeLookup.java#L31-L33): `GRADLE_USER_HOME`
4. Default to [`System.getProperty("user.home") + "/.gradle"`](https://github.com/gradle/gradle/blob/master/subprojects/wrapper/src/main/java/org/gradle/wrapper/GradleUserHomeLookup.java#L34)

Anything that changes the values (or lack changing the values) for those keys will have the Gradle user home directory default to _`user.home`/.gradle_. I tried with all possibilities and Gradle obeys to all the rules without issues. The test was done on Gradle 3.5 under Ubuntu 17.04 with an empty project. One thing to take into consideration is if your project is forking Gradle execution without passing the flag/property/environment variable to the forked process.

I'm going to close this issue. If you still have some problem with this I recommend discussing it on the [forum](https://discuss.gradle.org/) or provide more information to reproduce this issue.

**Closed by lacasseio** 2017-07-07 20:21 UTC
Labels: a:question, from:contributor, in:cli

**Comment by c3ph3us** [comment] 2018-03-29 02:56
@lacasseio  after checkup i came to  the following conclusion:

the **problem here is not that the gradle disobeys env or its variables but that it could not write to directory pointed by env or propoerty var**  -in this case it has no writte permission to directory pointed by user gradle home var

- the output of error is missleading (gradle should check first if has a write permissions to directory if not output a proper message and not as here not related one -that it cant load native  .so lib  

so pleas add the checkup on RW permissions when it need to be done - this way we will know when to look for source of issue rather than blinding

**Comment by lacasseio** [comment] 2018-04-17 12:14
Thanks @c3ph3us for following up with your conclusion. I agree with you Gradle isn't doing a great job, in this case, informing the user of the failure. I opened issue https://github.com/gradle/gradle/issues/5067 to follow up with a fix to improve this use case.
