### ISSUE TITLE
MavenPublish plugin is not compatible with Isolated Projects

### ISSUE THREAD

**Issue by antohaby** [gradle/gradle#30609] opened 2024-09-18 16:48 UTC
### Current Behavior

```
> Project ':lib2' cannot access 'Project.group' functionality on another project ':lib1'

```

Relevant part in the Stacktrace:

```
	at org.gradle.internal.cc.impl.ProblemReportingCrossProjectModelAccess$ProblemReportingProject_Decorated.getGroup(Unknown Source)
	at org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency.getGroup(DefaultProjectDependency.java:71)
	at org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency_Decorated.getGroup(Unknown Source)
	!!! at org.gradle.api.publish.maven.internal.publication.MavenComponentParser.dependencyMatchesProject(MavenComponentParser.java:265)
	at org.gradle.api.publish.maven.internal.publication.MavenComponentParser.getDependenciesForVariant(MavenComponentParser.java:220)
	at org.gradle.api.publish.maven.internal.publication.MavenComponentParser.lambda$parseDependencies$2(MavenComponentParser.java:149)
```

From the reproducer below.

### Expected Behavior

No error is reported. Same behaviour as without Isolated Projects feature enabled.

### Self-contained Reproducer Project

```
// :lib1 subproject
plugins {
    `java-library`
}

repositories {
    mavenCentral()
}
```

```
// :lib2 subproject
plugins {
    `java-library`
    `maven-publish`
}

dependencies {
    api(project(":lib1"))
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
        }
    }
}
```

```
./gradlew :lib2:generatePomFileForMavenPublication -Dorg.gradle.unsafe.isolated-projects=true
```

### Gradle version

8.10.1

**Comment by antohaby** [comment] 2024-09-18 17:48
It seems even if I apply `maven-publish` it still fails.

**Comment by ov7a** [comment] 2024-09-19 12:43
The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by mlopatkin** [comment] 2024-09-24 12:21
This issue will be closed as a duplicate of

* #30186 

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

**Closed by mlopatkin** 2024-09-24 12:21 UTC
Labels: in:publishing-plugins, a:bug, in:isolated-projects
