### ISSUE TITLE
NamedDomainObjectProvider self mutation should be allowed

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#27097] opened 2023-11-20 10:56 UTC
### Current Behavior

See https://github.com/gradle/gradle/issues/18109

### Expected Behavior

See https://github.com/gradle/gradle/issues/18109

### Context (optional)

The [previous issue](https://github.com/gradle/gradle/issues/18109) was closed prematurely by the stale bot, please reopen it. It will become a problem when Gradle decide to adopt the Provider API everywhere.

### Steps to Reproduce

See https://github.com/gradle/gradle/issues/18109

### Gradle version

See https://github.com/gradle/gradle/issues/18109

**Comment by cobexer** [comment] 2023-11-21 13:25
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #18109
***
Thanks for the ping, we reopened the other issue.

**Closed by cobexer** 2023-11-21 13:25 UTC
Labels: closed:duplicate
