### ISSUE TITLE
Need Gradle v8.0.2 to please be compatible with Java JDK v20 Official Oracle Release

### ISSUE THREAD

**Issue by RobFosterNYC** [gradle/gradle#24501] opened 2023-03-25 16:29 UTC
Need Gradle v8.0.2 to please be compatible with Java JDK v20 Official Release

Java has released the official version of Java JDK v20.
https://www.oracle.com/java/technologies/downloads/#jdk20-windows

Its not a pre-release, its not a beta, its not an alpha, its an official JDK v20 release from Oracle and I need Gradle v8.0.2 
to be compatible with it please.

Thank you.

**Comment by rpalcolea** [comment] 2023-03-27 22:02
This is related https://github.com/gradle/gradle/issues/23488. The fact that Kotlin and Scala do not support JDK 20 yet is a blocker for Gradle itself so this also impacts the Kotlin DSL hence why Gradle does not support JDK 20 yet 

If your project uses java or groovy, you probably want to decouple your build runtime jdk from your project's jdk using [Toolchains](https://docs.gradle.org/current/userguide/toolchains.html). Today you could use toolchains to build your project against 20 and continue using gradle with an older jdk (17 for example)

**Comment by RobFosterNYC** [comment] 2023-03-28 08:02
Just curiously asking  😁
If Kotlin does not support JDK 20 (which is officially released) by both https://jdk.java.net/ and Oracle Official JDK Website,  
Then why does it run perfectly within InteliJ Idea IDE without a problem ? (the company who created kotlin) 
But when you use it on Android Studio things fall apart?

Also why is there no mention of this on the Kotlin official issue tracker or release notes for Kotlin 1.8.10?
https://kotlinlang.org/docs/compatibility-guide-18.html


Again, just curiously asking with a smile 😁

**Comment by rpalcolea** [comment] 2023-03-28 16:44
I don't work for Gradle but I if you were very curious, you would try to compile a kotlin plugin with jdk 20 and you would get this:

```
Caused by: java.lang.IllegalArgumentException: Unknown Kotlin JVM target: 20
        at org.jetbrains.kotlin.gradle.dsl.JvmTarget$Companion.fromTarget(JvmTarget.kt:26)
        at org.jetbrains.kotlin.gradle.tasks.DefaultKotlinJavaToolchain$wireJvmTargetToToolchain$1$1.invoke(DefaultKotlinJavaToolchain.kt:78)
        at org.jetbrains.kotlin.gradle.tasks.DefaultKotlinJavaToolchain$wireJvmTargetToToolchain$1$1.invoke(DefaultKotlinJavaToolchain.kt:70)
        at org.jetbrains.kotlin.gradle.tasks.DefaultKotlinJavaToolchain$sam$org_gradle_api_Transformer$0.transform(DefaultKotlinJavaToolchain.kt)
``` 

and you would have to modify the compiler to target java 19 or lower 😉 

If you look at the kotlin source code (owned by Jetbrains) -> https://github.com/JetBrains/kotlin/blob/master/compiler/config.jvm/src/org/jetbrains/kotlin/config/JvmTarget.kt#L22-L39. you will see that indeed you always need to target to lower versions as the compiler does not support it. 

So this becomes a huge blocker for things like KotlinDSL or any other kotlin based tools where you can't hook into the compiler easily

And the fact that his code hasn't changed, I don't see how it would change with 1.8.20 in the near future 

This is also in the docs-> https://kotlinlang.org/docs/compiler-reference.html#xjdk-release-version

```
-jvm-target version
Specify the target version of the generated JVM bytecode. Possible values are 1.8, 9, 10, ..., 19. The default value is 1.8.
```

**Comment by ice1000** [comment] 2023-03-29 19:03
> If Kotlin does not support JDK 20 (which is officially released) by both https://jdk.java.net/ and Oracle Official JDK Website,
> Then why does it run perfectly within InteliJ Idea IDE without a problem ? (the company who created kotlin)

I have a shorter answer: because IntelliJ IDEA is running in JDK 17

**Comment by ov7a** [comment] 2023-03-30 08:47
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #23488 

Please add your use case and 👍 to that issue.

***

The support of JDK 20 won't happen in 8.0.x or 8.1.x, but would be added in later versions.

**Closed by ov7a** 2023-03-30 08:47 UTC
Labels: a:bug, to-triage
