### ISSUE TITLE
Gradle not respecting --tests when using JUnit Platform

### ISSUE THREAD

**Issue by edeandrea** [gradle/gradle#4748] opened 2018-03-16 14:33 UTC
First off - Great job with the JUnit platform support in Gradle 4.6. This is essential functionality & it was trivial to swap it in with my current JUnit 4 test suite. Kudos!

### Expected Behavior
Tools like IntelliJ are smart about test execution. I can click on the little triangle in a test class or a specific test method and IntelliJ uses the `--tests` flag to tell it to only execute the specific test, like `Executing tasks ':projectName:cleanTest :projectName:test --tests com.mycompany.somepackage.SomeTests'...`. I would then expect that IntelliJ would just run that test or test class & only show those results in the **Run** window.

### Current Behavior
More than the tests I'm expecting are now being run. Not all the project's test, but more than the tests that are in the current package. I haven't quite figured out the logic behind what its executing. All I know is its executing some subset that includes the tests I want but less than all the tests in the project.

### Context
When I'm trying to iterate and write specific tests I tend to re-run the tests a lot until they are correct, or until the object under test is correct. By having to re-run lots of tests each time its increasing the amount of time it takes to write good tests.

### Steps to Reproduce (for bugs)
Switch to use the JUnit platform support (doesn't matter if the tests are written with JUnit 4 or 5). Then in IntelliJ click the little triangle on a test class or test method.

### Your Environment
IntelliJ Ultimate 2017.3.5

I can't publish a build scan as my company won't allow it, but here's my environment:

```
------------------------------------------------------------
Gradle 4.6
------------------------------------------------------------

Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_131 (Oracle Corporation 25.131-b11)
OS:           Mac OS X 10.12.6 x86_64
```

**Comment by oehme** [comment] 2018-03-16 18:16
Can you give us an example of tests that are run in addition to the ones you expect? Maybe a small example project on GitHub?

**Comment by edeandrea** [comment] 2018-03-16 19:20
I'm working on building a small project. Even in my much larger project it seems to be somewhat intermittent. Could it have something to do with wrapper jvms or something?

**Comment by oehme** [comment] 2018-03-16 21:07
What do you mean by intermittent? If you try the same test multiple times you get different behavior? Or you get different behavior depending on which test you try?

**Comment by edeandrea** [comment] 2018-03-16 21:23
A little of both intermittently. I was re-running the same test for a while. Mostly worked as expected then sometimes would invoke other tests. Other times I was executing different test classes and was seeing inconsistent behavior.

Very strange. I've been bouncing back and forth between different projects as well (same Gradle version - some projects use Jupiter others don't).

**Comment by oehme** [comment] 2018-03-17 16:21
That sounds really odd, there should be no difference from run to run. An example would really help, since there is plenty of test coverage for this feature, but we must be missing something that's breaking your case.

**Comment by edeandrea** [comment] 2018-03-19 12:42
So I haven't been able to put a sample project together that can demonstrate this, but I have gathered a screenshot of an instance of this happening. Attached you can find the screenshot of my test class. I clicked the little triangle within IntelliJ to run the `AutoConfigureServiceTests` class.

Here is the console output of what IntelliJ told Gradle to do and what Gradle did (we have some stuff in our plugins that outputs other stuff during tests) (I've also trimmed the log down to only the stuff thats necessary). As you can see, more than just the `AutoConfigureServiceTests` class was executed, but not every test class within the `com.mycompany.commercial.acid.boot.test.autoconfigure.service` package (or its sub-packages). There are a few other test classes right there in the same package as well as in sub-packages that did not get executed.

```
Testing started at 8:29 AM ...
8:29:20 AM: Executing tasks ':acid-spring-boot-starter-test:cleanTest :acid-spring-boot-starter-test:test --tests com.mycompany.commercial.acid.boot.test.autoconfigure.service.AutoConfigureServiceTests'...

Mar 19, 2018 8:29:30 AM org.junit.vintage.engine.descriptor.RunnerTestDescriptor logIncompleteFiltering
WARNING: Runner junitparams.JUnitParamsRunner (used on class com.mycompany.commercial.acid.boot.test.autoconfigure.service.AutoConfigureApiTests) was not able to satisfy all filter requests.
Mar 19, 2018 8:29:30 AM org.junit.vintage.engine.descriptor.RunnerTestDescriptor logIncompleteFiltering
Mar 19, 2018 8:29:30 AM org.junit.vintage.engine.descriptor.RunnerTestDescriptor logIncompleteFiltering
WARNING: Runner junitparams.JUnitParamsRunner (used on class com.mycompany.commercial.acid.boot.test.autoconfigure.service.security.servlet.AutoConfigureServiceServletSecurityTests) was not able to satisfy all filter requests.
com.mycompany.commercial.acid.boot.test.autoconfigure.service.AutoConfigureApiTests > testExpectedClassesArentThere.[0] class com.mycompany.commercial.acid.boot.test.autoconfigure.service.AutoConfigureApiTests$AutoConfigureApiNotPresent  PASSED
com.mycompany.commercial.acid.boot.test.autoconfigure.service.AutoConfigureApiTests > testExpectedClassesArentThere.[1] class com.mycompany.commercial.acid.boot.test.autoconfigure.service.AutoConfigureApiTests$AutoConfigureApiPresentNoWebApplication  PASSED
com.mycompany.commercial.acid.boot.test.autoconfigure.service.AutoConfigureServiceTests > testExpectedClassesArentThere PASSED
com.mycompany.commercial.acid.boot.test.autoconfigure.service.AutoConfigureServiceTests > testExpectedClassesAreThere PASSED
com.mycompany.commercial.acid.boot.test.autoconfigure.service.security.server.AutoConfigureServiceReactiveSecurityTests > testExpectedSecurityClassesArentThere.[0] class com.mycompany.commercial.acid.boot.test.autoconfigure.service.security.server.AutoConfigureServiceReactiveSecurityTests$AutoConfigureServiceReactiveSecurityPresent, true, false  PASSED
com.mycompany.commercial.acid.boot.test.autoconfigure.service.security.server.AutoConfigureServiceReactiveSecurityTests > testExpectedSecurityClassesArentThere.[1] class com.mycompany.commercial.acid.boot.test.autoconfigure.service.security.server.AutoConfigureServiceReactiveSecurityTests$AutoConfigureServiceReactiveSecurityNotPresent, false, false  PASSED
com.mycompany.commercial.acid.boot.test.autoconfigure.service.security.server.AutoConfigureServiceReactiveSecurityTests > testExpectedSecurityClassesArentThere.[2] class com.mycompany.commercial.acid.boot.test.autoconfigure.service.security.server.AutoConfigureServiceReactiveSecurityTests$AutoConfigureServiceReactiveSecurityPresentAndEnabled, true, true  PASSED
com.mycompany.commercial.acid.boot.test.autoconfigure.service.security.servlet.AutoConfigureServiceServletSecurityTests > testExpectedSecurityClassesArentThere.[0] class com.mycompany.commercial.acid.boot.test.autoconfigure.service.security.servlet.AutoConfigureServiceServletSecurityTests$AutoConfigureServiceServletSecurityPresent, true, false  PASSED
com.mycompany.commercial.acid.boot.test.autoconfigure.service.security.servlet.AutoConfigureServiceServletSecurityTests > testExpectedSecurityClassesArentThere.[1] class com.mycompany.commercial.acid.boot.test.autoconfigure.service.security.servlet.AutoConfigureServiceServletSecurityTests$AutoConfigureServiceServletSecurityNotPresent, false, false  PASSED
com.mycompany.commercial.acid.boot.test.autoconfigure.service.security.servlet.AutoConfigureServiceServletSecurityTests > testExpectedSecurityClassesArentThere.[2] class com.mycompany.commercial.acid.boot.test.autoconfigure.service.security.servlet.AutoConfigureServiceServletSecurityTests$AutoConfigureServiceServletSecurityPresentAndEnabled, true, true  PASSED
:acid-spring-boot-starter-test:buildDashboard UP-TO-DATE
:buildDashboard UP-TO-DATE
Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings
BUILD SUCCESSFUL in 16s
37 actionable tasks: 2 executed, 35 up-to-date
8:29:36 AM: Tasks execution finished ':acid-spring-boot-starter-test:cleanTest :acid-spring-boot-starter-test:test --tests com.mycompany.commercial.acid.boot.test.autoconfigure.service.AutoConfigureServiceTests'.
```

![screen shot 2018-03-19 at 8 31 08 am](https://user-images.githubusercontent.com/363447/37595729-4041ade8-2b50-11e8-9813-93c5be2f5fc0.png)

**Comment by blindpirate** [comment] 2018-03-19 13:00
> 8:29:20 AM: Executing tasks ':acid-spring-boot-starter-test:cleanTest :acid-spring-boot-starter-test:test --tests com.mycompany.commercial.acid.boot.test.autoconfigure.service.AutoConfigureServiceTests'...

@edeandrea Thanks for the information. According to the log, what happens if you run the command manually `:acid-spring-boot-starter-test:cleanTest :acid-spring-boot-starter-test:test --tests com.mycompany.commercial.acid.boot.test.autoconfigure.service.AutoConfigureServiceTests` in console?

**Comment by edeandrea** [comment] 2018-03-19 13:05
Hi @blindpirate When I run manually on the console I get the same output. I thought maybe somehow the daemon is getting corrupted, so I also tried stopping the daemon (via `./gradlew --stop` as well as opening my task manager & killing any `java.exe` processes). Re-running produced the same output. After that I stopped all daemons again and ran with the `--no-daemon` flag & again same output.

**Comment by edeandrea** [comment] 2018-03-19 13:30
Hi @blindpirate I've been trying to extract things out so that I can reproduce this outside of my project. Unfortunately I can't share all of the code because company legal won't allow it.

Essentially this project is a large multi-module project. The project itself is a framework (not an application) that wraps Spring Boot with a set of functionality customized to our organization. This instance of logs is from one of the child projects, specifically one that provides testing capabilities very similar to what `spring-boot-starter-test` does. It follows a lot of the same patterns & principles. 

As part of the framework we have lots of Spring Boot auto-configuration that we build. In our test starter project (this particular project - not the only instance where I'm seeing this issue) we provide lots of `@AutoConfigure...` annotations, similar to what is available in the `spring-boot-starter-test` module for being able to slice the Spring context when writing unit tests.

What these tests in particular do is test our `@AutoConfigure...` annotations using Spring Boot 2's `@ApplicationContextRunner`/`@WebApplicationContextRunner`/`@ReactiveWebApplicationContextRunner`. All the tests in this module are all currently written using JUnit 4, but the multi-module project as a whole is configured to use JUnit Platform, since we are in the process of converting our test suite from JUnit 4 to JUnit 5. We write a lot of parameterized tests and we use https://github.com/Pragmatists/JUnitParams version 1.1.1 for doing that. (We used to write lots of our tests in Groovy using Spock for this, but decided it was better to keep things in Java). Now that JUnit 5 is out and has built-in support for parameterized tests, the long-term goal is to phase out the custom library for the built-in one.

The multi-module project as a whole shares a suite of Gradle plugins, one of which applies the JUnit Jupiter customization to all of the child modules:

```groovy
class JUnitPlatformConfigurationPlugin implements Plugin<Project> {
	@Override
	void apply(Project project) {
		project.afterEvaluate {
			if (project.plugins.hasPlugin('java')) {
				// Enable JUnit Platform
				project.tasks.withType(Test) {
					useJUnitPlatform()
				}

				def junitJupiterVersion = project.property 'junit-jupiter.version'

				project.dependencies {
					testCompile "org.junit.jupiter:junit-jupiter-api:$junitJupiterVersion"
					testCompile "org.junit.jupiter:junit-jupiter-params:$junitJupiterVersion"
					testRuntime "org.junit.jupiter:junit-jupiter-engine:$junitJupiterVersion"
					testRuntime "org.junit.vintage:junit-vintage-engine:$junitJupiterVersion"
				}
			}
		}
	}
}
```

Here's a sample of what one of them looks like:

```java
package com.mycompany.commercial.acid.boot.test.autoconfigure.core;

import static org.assertj.core.api.Assertions.*;

import org.junit.Test;

import org.springframework.boot.autoconfigure.AutoConfigurations;
import org.springframework.boot.test.context.assertj.ApplicationContextAssertProvider;
import org.springframework.boot.test.context.runner.ApplicationContextRunner;
import org.springframework.boot.test.context.runner.ContextConsumer;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.context.annotation.Configuration;

import com.mycompany.commercial.acid.boot.core.util.UtilAutoConfiguration;
import com.mycompany.commercial.acid.core.util.ApplicationContextHolder;
import com.mycompany.commercial.acid.core.util.ApplicationContexts;

public class AutoConfigureUtilTests {
	public static final ContextConsumer<ApplicationContextAssertProvider<? extends ConfigurableApplicationContext>> expectedClassesAreThereConsumer = context -> {
		assertThat(context)
			.hasSingleBean(UtilAutoConfiguration.class);

		assertThat(context)
			.getBean(ApplicationContextHolder.BEAN_NAME, ApplicationContextHolder.class)
			.isNotNull();

		assertThat(context)
			.getBean(ApplicationContexts.BEAN_NAME, ApplicationContexts.class)
			.isNotNull();
	};

	public static final ContextConsumer<ApplicationContextAssertProvider<? extends ConfigurableApplicationContext>> expectedClassesArentThereConsumer = context -> {
		assertThat(context)
			.doesNotHaveBean(UtilAutoConfiguration.class);

		assertThat(context)
			.getBean(ApplicationContextHolder.BEAN_NAME, ApplicationContextHolder.class)
			.isNull();

		assertThat(context)
			.getBean(ApplicationContexts.BEAN_NAME, ApplicationContexts.class)
			.isNull();
	};

	@Test
	public void testExpectedClassesAreThere() {
		new ApplicationContextRunner()
			.withConfiguration(AutoConfigurations.of(AutoConfigureUtilPresent.class))
			.run(expectedClassesAreThereConsumer);
	}

	@Test
	public void testExpectedClassesArentThere() {
		new ApplicationContextRunner()
			.withConfiguration(AutoConfigurations.of(AutoConfigureUtilNotPresent.class))
			.run(expectedClassesArentThereConsumer);
	}

	@Configuration
	@AutoConfigureUtil
	public static class AutoConfigureUtilPresent {

	}

	@Configuration
	public static class AutoConfigureUtilNotPresent {

	}
}
```

Here's a screenshot of the test hierarchy:
![screen shot 2018-03-19 at 9 28 02 am](https://user-images.githubusercontent.com/363447/37598179-e46d4574-2b57-11e8-9a01-967e197d17a3.png)

**Comment by blindpirate** [comment] 2018-03-19 13:44
@edeandrea Thank you very much! I understand you cannot provide a full sample here. It's very helpful and I'll take an investigation. I kind of suspect `JUnitParams` since there's a line in your log:

```
WARNING: Runner junitparams.JUnitParamsRunner (used on class com.mycompany.commercial.acid.boot.test.autoconfigure.service.AutoConfigureApiTests) was not able to satisfy all filter requests.
```

I'll let you know if I need further inforamation.

**Comment by edeandrea** [comment] 2018-03-19 13:46
Thanks. There are other tests in the package that don't use it. The test class I was originally trying to execute (`AutoConfigureServiceTests`) doesn't use it. Its just plain vanilla JUnit.

**Comment by oehme** [comment] 2018-03-19 13:55
My gut feeling says that we have some bug in how we match segments of the name.

See the similarity:

-  **autoconfigure**.**service**.AutoConfigureApi**Tests**
- **AutoConfigureServiceTest**

**Comment by blindpirate** [comment] 2018-03-19 14:01
@oehme Maybe, anyway it's gonna be a tough case.

@edeandrea One more thing, are ALL tests or just SOME tests of `AutoConfigureServiceReactiveSecurityTests`/`AutoConfigureApiTests` misexecuted in the case you mentioned?

**Comment by edeandrea** [comment] 2018-03-19 14:03
Only some of the tests in the classes that aren't supposed to be executed were executed.

**Comment by blindpirate** [comment] 2018-03-20 01:35
@edeandrea I've already reproduced this issue on my machine. I believe it's believe to some incompatibility of JUnitParams and JUnit Vintage Engine filtering mechanism. However, this issue is resolved by some improvements we did recently: #4597 , would you mind trying with latest snapshot version? http://services.gradle.org/distributions-snapshots/

**Comment by blindpirate** [comment] 2018-03-20 02:24
Looks like a Vintage issue: https://github.com/junit-team/junit5/issues/1336

**Comment by edeandrea** [comment] 2018-03-20 13:03
Thanks for the follow-up @blindpirate. I did test with gradle-4.7-20180320095059+0000 and whatever magic you worked there seems to have cleaned this up. I also don't see that `JUnitParamsRunner` warning anymore either.

**Comment by oehme** [comment] 2018-03-20 13:29
Closing as the underlying issue is with JUnit and #4597 hides this issue for most cases now.

Thanks for verifying @edeandrea!

**Closed by oehme** 2018-03-20 13:29 UTC
Labels: a:bug, from:contributor, in:testing
