### ISSUE TITLE
plugins block to support configurable version

### ISSUE THREAD

**Issue by luistrigueiros** [gradle/gradle#7731] opened 2018-11-14 12:35 UTC
I would like to be able to pass a property defined in gradle.properties in the plugin block like the example below where I have the  kotlinVersion:

plugins {
    id "org.jetbrains.kotlin.jvm" version "$kotlinVersion"
    id "org.jetbrains.kotlin.kapt" version "$kotlinVersion"
    id "io.spring.dependency-management" version "1.0.6.RELEASE"
    id "com.github.johnrengelman.plugin-shadow" version "2.0.3"
    id "application"
}

Currently I am getting the error:

```
Could not compile build file 'C:\work\git\kapp\build.gradle'.
> startup failed:
  build file 'C:\work\git\kapp\build.gradle': 2: argument list must be exactly 1 literal non empty string

  See https://docs.gradle.org/4.10.2/userguide/plugins.html#sec:plugins_block for information on the plugins {} block

   @ line 2, column 5.
         id "org.jetbrains.kotlin.jvm" version "$kotlinVersion"
         ^

  build file 'C:\work\git\kapp\build.gradle': 3: argument list must be exactly 1 literal non empty string

  See https://docs.gradle.org/4.10.2/userguide/plugins.html#sec:plugins_block for information on the plugins {} block

   @ line 3, column 5.
         id "org.jetbrains.kotlin.kapt" version "$kotlinVersion"
         ^

  2 errors

```
Thank you, kindly
Luis Oscar

**Comment by oehme** [comment] 2018-11-14 14:19
Duplicate of https://github.com/gradle/gradle/issues/7705

**Closed by oehme** 2018-11-14 14:19 UTC
