### ISSUE TITLE
add SPDX license to metadata

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#27798] opened 2024-01-23 20:43 UTC
### Expected Behavior

Gradle appears to have no concept of license in it's metadata. This is uncommon amongst many language build tools now. NPM even requires it and that it be valid.

I believe this should be a list of licenses, possibly even categorized in some way (such as if documentation is separate).

However, it's defined the API should be exposed to plugins.

https://spdx.org/licenses/

### Context

not being able to easily identify licenses. See various SPDX (iso standard) use cases.

**Comment by cobexer** [comment] 2024-01-25 13:42
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

An explanation of what you are trying to solve with this feature request is a must for us to be able to reason about the use cases. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a valid use case, we may be able also to suggest workarounds or ways to avoid the problem.

This issue will be closed after 7 days unless you provide more information.

***
Are you talking about a license field in the gradle module metadata similar to a license field in a maven POM? Or something else and in the latter case please describe where is the information stored, where is it authored and who consumes the information.

**Comment by xenoterracide** [comment] 2024-01-25 19:34
Yes, I'm talking about a field similar to the maven pom or more correctly the field in `package.json` which is not arbitrary and must be SPDX compatible. If pom isn't published, determining what the license is used "reflectively" would be difficult.

Due to the ability and popularity of licensing portions of the code, such as documentation, separately good would have different categories. At the very least I would probably support a field for documentation that is separate from code.

I also think if the API was appropriately typed plugins could also use this data to generate additional information.

**Comment by cobexer** [comment] 2024-01-29 09:34
This feature request is in the backlog of the relevant team and is prioritized by them.
***
There are no plans to stop publishing Maven POMs, and there is no way today to skip that.

Our understanding of your request is:
* have an SPDX-compatible license field somewhere in the Gradle Module Metadata
* have an API on the resolution result to retrieve that information

If there is something missing, please clarify by describing a usecase.

**Comment by sschuberth** [comment] 2024-04-12 14:43
Sounds like a duplicate of my https://github.com/gradle/gradle/issues/7682, or?

**Comment by xenoterracide** [comment] 2024-04-12 16:41
Yeah I guess so

**Comment by sschuberth** [comment] 2024-04-12 16:57
> Yeah I guess so

Mind closing this then, @xenoterracide?

**Closed** 2024-10-08 13:54 UTC
Labels: a:feature, in:gradle-module-metadata, to-triage, pending:release-notes, pending:milestone
