### ISSUE TITLE
Gradle auto applies build scan plugin, even when plugin is already applied by class, from a script plugin

### ISSUE THREAD

**Issue by facewindu** [gradle/gradle#3283] opened 2017-10-25 06:18 UTC
### Expected Behavior
Gradle should detect that the build scan plugin is already requested, and should not auto-apply it.

### Current Behavior
Gradle correctly applies the requested build scan plugin, but also auto-applies version 1.9.1 of the plugin.

### Context
We have to load the build scan plugin by class because we load in a script plugin.
We do that because the version of this plugin changes very frequently for us (Gradle Enterprise team).
If we load it at the root project, we invalidate lots of cached classloaders and tasks.

### Steps to Reproduce (for bugs)
[gradle-build-scan-quickstart.zip](https://github.com/gradle/gradle/files/1413428/gradle-build-scan-quickstart.zip)
Execute `./gradlew --scan`

### Your Environment
 * Build scan URL: https://scans.gradle.com/s/iirov4wxxclic

**Comment by oehme** [comment] 2017-10-25 06:27
This is a problem, because we recommend application by class in our [documentation](https://docs.gradle.com/build-scan-plugin/#for_all_your_builds).

A possible solution would be to also have the class name known to the auto-applied plugin handler, so that it can check for that as well.

**Comment by bmuschko** [comment] 2017-10-25 14:30
> Gradle correctly applies the requested build scan plugin, but also auto-applies version 1.9.1 of the plugin.

Gradle actually only uses the version 1.9.1 and renders a warning. I am going to fix it but to be honest I don't think it's not such a big deal.

```
WARNING: Several versions of the build scan plugin were applied: [1.9.1, 1.10].
The build scan data was captured by version [1.9.1].
This is often caused by multiple init scripts and/or build scripts applying the plugin.
```

**Comment by facewindu** [comment] 2017-10-25 14:33
@bmuschko the warning is raised by the build scan plugin, when the second one is applied.
Plus, since I'm requesting 1.10 in the buildscript block, it should use that, and not 1.9.1.

**Comment by bmuschko** [comment] 2017-10-25 14:41
> Plus, since I'm requesting 1.10 in the buildscript block, it should use that, and not 1.9.1.

I understand. I was somewhat expecting an actual breakage. Either way I don't think the version selection process is super clear to users as not documented.

**Comment by etiennestuder** [comment] 2017-10-25 15:32
> Plus, since I'm requesting 1.10 in the buildscript block, it should use that, and not 1.9.1.

> I understand. I was somewhat expecting an actual breakage. Either way I don't think the version selection process is super clear to users as not documented.

This is bad, the user _must_ be able to define a more recent version than the version that is auto-applied. Regardless of how well this is documented.

**Comment by bamboo** [comment] 2017-10-25 15:59
> This is bad, the user must be able to define a more recent version than the version that is auto-applied. 

@etiennestuder That is possible as long as the plugin is not applied by class but by id either in the `plugins` block or via `apply`.

**Comment by etiennestuder** [comment] 2017-10-25 16:48
Got it. Thanks, @bamboo.

**Comment by ldaley** [comment] 2017-10-26 02:50
FWIW, this is one of the reasons I originally advocated not doing something generic and instead doing something build scan specific. We already have a mechanism for detecting whether the build scan plugin is present, that sidesteps all of this mess around plugins. My fault for not being more aware of what was going on here.

**Comment by ldaley** [comment] 2017-10-26 02:53
Supporting ID only application is not feasible as it doesn't work from init scripts, which is a hard requirement, and doesn't work from script plugins which is a not-quite-so hard requirement.

The only solutions I can see are:

1) Detect via ID and/or classname (i.e. what @oehme said)
2) Use https://github.com/gradle/gradle/blob/313f7cdc8a27f5b4aa51b417124f0c78ea52fd3a/subprojects/core/src/main/java/org/gradle/internal/scan/config/BuildScanPluginApplied.java#L28

2 is what I wanted to do originally.

**Comment by oehme** [comment] 2017-10-26 07:24
I changed the title of this ticket, because we only intend to fix the init script case. We don't want to generically fix how script plugins work.

**Comment by oehme** [comment] 2017-10-26 09:07
Okay, I see there was some confusion here. I thought applying from an init script was broken, but that's not actually the case. The init script use case works fine. That's because we already do a reverse lookup, even if it was applied by class. We actually have [tests](https://github.com/gradle/gradle/blob/master/subprojects/core/src/integTest/groovy/org/gradle/internal/scan/config/BuildScanAutoApplyIntegrationTest.groovy#L157) for that.

The example attached by @facewindu won't work even if we did something scan-specific, because it applies the scan plugin very late, during the imperative part of build script evaluation. To make that use case work reasonably you'd have to do something like:

```
buildscript {
  apply from: 'scan.gradle'
}
```

That way the script is evaluated early, before auto-applied plugin handling. I don't think there's anything else we could do about that, short of completely changing how script plugins work, which is of course out of scope for 4.3.

I think we should close this issue and adjust the build scan quickstart to use the fix above.

**Comment by ldaley** [comment] 2017-10-26 09:53
@oehme I just tried your suggestion and it doesn't work. We still get the auto applied version.

**Comment by ldaley** [comment] 2017-10-26 09:54
It actually fails in a weird way:

```
FAILURE: Build failed with an exception.

* Where:
Auto-applied by using --scan

* What went wrong:
Could not apply requested plugin [id: 'com.gradle.build-scan', version: '1.10', artifact: 'com.gradle:build-scan-plugin:1.10'] as it does not provide a plugin with id 'com.gradle.build-scan'. This is caused by an incorrect plugin implementation. Please contact the plugin author(s).
> Plugin with id 'com.gradle.build-scan' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org
```

**Comment by oehme** [comment] 2017-10-26 10:03
@ldaley That was fixed in RC3

**Comment by ldaley** [comment] 2017-10-26 10:03
Scratch that. It works with 4.3-rc-3 but not the latest nightly. It appears something was added to release that hasn't yet been merged. Can we get it merged?

**Comment by oehme** [comment] 2017-10-26 10:03
Yes, let's merge release.

**Comment by oehme** [comment] 2017-10-26 10:07
Actually, the changes are already on master and the latest nightly should contain them. Are you sure you're on the latest nightly?

**Comment by ldaley** [comment] 2017-10-26 10:11
I was, but I had it in the bad state when I thought it was good.

Fix confirmed 👍

**Comment by oehme** [comment] 2017-10-26 11:53
Cool, thanks for verifying!

**Closed by oehme** 2017-10-26 11:53 UTC
Labels: a:bug, from:member, in:core
