### ISSUE TITLE
Virtual platform doesn't always align constituents [6.5-rc-1]

### ISSUE THREAD

**Issue by dansanduleac** [gradle/gradle#13272] opened 2020-05-28 17:27 UTC
We are using [gradle-consistent-versions](https://github.com/palantir/gradle-consistent-versions) in a repo to create a virtual platform for dependencies under the group `com.palantir.dialogue`, which ends up having the effect of the following gradle code:

```groovy
dependencies {
  components.all {
    if (it.id.group == 'com.palantir.dialogue') {
      it.belongsTo "com.palantir.dialogue:_:${it.id.version}"
    }
  }
  constraints {
    // a configuration all others extend from
    rootConfiguration 'com.palantir.dialogue:_:1.50.2'
  }
}
```

The dependency structure between the relevant dialogue modules looks roughly like this:
```
dialogue-clients
  \_ ( api) dialogue-target
  \_ (impl) dialogue-apache-hc4-client
     \_ (api) dialogue-core (*)
     \_ (api) dialogue-target
  \_ (impl) dialogue-serde
  \_ (impl) -> dialogue-core
     \_ (api) -> dialogue-target
```

In this situation, the problem is that **a transitive constraint of `com.palantir.dialogue:dialogue-target:1.51.0` does not end up bumping `com.palantir.dialogue:dialogue-clients`.**

Here's the transitive constraint coming from a non-dialogue transitive dependency:

![image](https://user-images.githubusercontent.com/222827/83173088-6ab4bd80-a110-11ea-9e90-a5522cf60ff0.png)

### Expected Behavior

I would expect that all dialogue modules are aligned up to 1.51.1 thanks to the virtual platform.

### Current Behavior

The platform doesn't align `com.palantir.dialogue:dialogue-clients` to 1.51.0.

You can see that it does align all of the other modules, for example dialogue-core, and the platform is indicated in the resolution result:
![image](https://user-images.githubusercontent.com/222827/83170687-d4cb6380-a10c-11ea-9f71-d7ce043cddfd.png)

However dialogue-clients doesn't seem to get added to any platform and thus remains un-bumped:

![image](https://user-images.githubusercontent.com/222827/83172324-558b5f00-a10f-11ea-8854-863948ae3128.png)

Adding logs before the `belongsTo` code illustrated above shows that Gradle never creates a component `com.palantir.dialogue:dialogue-clients:1.51.0`, so the code never gets a chance to assign it to the platform.

Note: this resolution of `unifiedClasspath` is happening in the root project's afterEvaluate, _after_ all other projects have been evaluated too, though I'm not sure if that's relevant.

### Context

This makes gradle's resolution unstable and produces unresolvable lock files, preventing certain teams from having their gradle dependencies be seamlessly auto-upgraded.

Once the lock file is written with the bad constraints as shown above, a new gradle run that doesn't resolve  gradle-consistent-versions' `unifiedClasspath` configuration, but instead just does resolves the normal configurations e.g. `runtimeClasspath`, fails because of unsatisfiable constraints:

```
Cannot find a version of 'com.palantir.dialogue:dialogue-clients' that satisfies the version constraints:
   Dependency path '<this-project>' --> 'com.palantir.atlasdb:atlasdb-config:0.220.2' --> 'com.palantir.dialogue:dialogue-clients:1.40.1'
   Constraint path '<this-project>' --> 'com.palantir.dialogue:dialogue-clients:{strictly 1.50.2}' because of the following reason: Locked by versions.lock
   Dependency path '<this-project>' --> '<redacted>' --> 'com.palantir.witchcraft:witchcraft-core:0.265.0' --> 'com.palantir.dialogue:dialogue-clients:1.50.2'
   Dependency path '<this-project>' --> 'com.palantir.atlasdb:atlasdb-config:0.220.2' --> 'com.palantir.atlasdb:atlasdb-conjure:0.220.2' --> 'com.palantir.dialogue:dialogue-clients:1.40.1'
   Constraint path '<this-project>' --> 'com.palantir.dialogue:dialogue-apache-hc4-client:1.51.0' --> 'com.palantir.dialogue:_:1.51.0' --> 'com.palantir.dialogue:dialogue-clients:1.51.0' because of the following reason: belongs to platform com.palantir.dialogue:_:1.51.0
```

### Steps to Reproduce 

described above 

### Your Environment

This is an internal repo and I sadly wasn't able to produce a repro, so I'll have to describe as many details as I can here.

Additional notes: this was happening on gradle 5.6.4, then on 6.3, and all the way up to 6.5-rc-1.
I was hoping https://github.com/gradle/gradle/commit/c73511663e5c1d7ba7131ea8a61ea807d9e6e6ff might have fixed some situations with 'platform constraints on lower versions' but it doesn't look like it helped here.

**Comment by melix** [comment] 2020-07-16 09:06
I haven't been able to reproduce this behavior. If you can figure out a reproducer, it would be greatly appreciated.

**Comment by jjohannes** [comment] 2021-03-23 09:28
Closing this because a reproducer is missing

**Closed by jjohannes** 2021-03-23 09:28 UTC
Labels: a:bug, from:contributor, in:dependency-management, waiting-for:contributor
