### ISSUE TITLE
Internal caching for archives is too simplistic

### ISSUE THREAD

**Issue by jbartok** [gradle/gradle#24971] opened 2023-05-03 13:12 UTC
### Expected Behavior

Manipulating independent archives from tasks should happen independently.

### Current Behavior

Due to internal caching of archive content weird things can happen.

### Context (optional)

This issue has been filed after noticing weird behavior in an [internal Gradle test](https://github.com/gradle/gradle/blob/1237dcc6e43930d2be08d76489cf37fc338b91a7/subprojects/core/src/integTest/groovy/org/gradle/api/tasks/bundling/ConcurrentArchiveIntegrationTest.groovy#L436).

### Steps to Reproduce

Use the reproducer located [here](https://github.com/jbartok/archive-cache-issue).

Run: `./gradlew clean update1 verify1 verify2`

See the output:

```
> Task :update1
Updating tar entry /Users/jozsef/Work/bt-support/tmp/build/archives1/test1.tar!subdir2/file2.txt
         BEFORE: original text 2
         AFTER: modification 1 text 2
Updating tar entry /Users/jozsef/Work/bt-support/tmp/build/archives1/test1.tar!subdir2/file3.txt
         BEFORE: original text 3
         AFTER: modification 1 text 3
Updating tar entry /Users/jozsef/Work/bt-support/tmp/build/archives1/test1.tar!subdir1/file.txt
         BEFORE: original text 1
         AFTER: modification 1 text 1

> Task :verify1
Verifying tar entry /Users/jozsef/Work/bt-support/tmp/build/archives1/test1.tar!subdir2/file2.txt
         IS: modification 1 text 2

Verifying tar entry /Users/jozsef/Work/bt-support/tmp/build/archives1/test1.tar!subdir2/file3.txt
         IS: modification 1 text 3

Verifying tar entry /Users/jozsef/Work/bt-support/tmp/build/archives1/test1.tar!subdir1/file.txt
         IS: modification 1 text 1


> Task :verify2
Verifying tar entry /Users/jozsef/Work/bt-support/tmp/build/archives2/test2.tar!subdir2/file2.txt
         IS: modification 1 text 2

Verifying tar entry /Users/jozsef/Work/bt-support/tmp/build/archives2/test2.tar!subdir2/file3.txt
         IS: modification 1 text 3

Verifying tar entry /Users/jozsef/Work/bt-support/tmp/build/archives2/test2.tar!subdir1/file.txt
         IS: modification 1 text 1
```

* there is a tar file created by task `createArchive`
* there is another tar file, created by `copyArchive` task; it is copied to make it identical to the first archive; it is identical, but it's a separate archive
* `update1` task is run and it updates the content of the first archive
* `verify1` and `verify2` tasks are run, which show that the content of archive 2 ALSO CHANGED
* this is not right; nobody wanted to change the content of that archive; it changed due to caching being too primitive in this area of Gradle (the two archives are incorrectly sharing a cache entry due to being identical files)

True, the use case is weird, the update task changes the content of the files in the archive, but since this is (apparently) allowed, it should work in non-surprising ways.

### Gradle version

8.1.1

**Comment by lptr** [comment] 2023-09-12 09:55
It's unclear what you mean by "manipulating archives" that should happen independently, and what "some tasks work" means. The title of the issue is also not helpful, as "too simplistic" is not something we can fix.

What is the expected behavior and what happens instead?

**Comment by lptr** [comment] 2023-10-17 09:37
Okay, now I understand the problem.

It's not really related to the main problem, but there's an issue with the reproducer. Gradle does not support incremental execution for tasks like `UpdateTask` that modify their own inputs. Your definition is incorrect, as `getArchive()` is annotated with `@InputFile` but it's also an output of the task. Once we do https://github.com/gradle/gradle/issues/9134 this build should fail with a validation error. A way to make this work properly is to make `UpdateTask` `@Untracked`.

That out of the way, the main issue here is that you are misusing `ArchiveOperations.tarTree()`. Here's what the Javadoc says:

> Creates a read-only `FileTree` which contains the contents of the given TAR file, as defined by `Project.tarTree(Object)`.

True, it's relatively easy to shoot yourself in the foot like you do in the reproduced. Do you have a proposal to make this safer, or to make the problem easier to spot?

**Comment by lptr** [comment] 2023-10-17 09:40
Actually, let's close this, because I don't see how we could improve this in a feasible way. Please reopen if you have a proposal to do so.

**Closed by lptr** 2023-10-17 09:40 UTC
Labels: a:bug, in:file-tasks
