### ISSUE TITLE
ScalaCompile build cache configuration is not portable 

### ISSUE THREAD

**Issue by alpar-t** [gradle/gradle#15785] opened 2021-01-14 08:33 UTC
### Expected Behavior
Scala compilation is cached and results are re-usable across different machine as long as they use the same compiler.

### Current Behavior
The cache is invalidated because input`options.forkOptions.executable` is different across invocations. 

### Context
This makes the build cache non usable when compiling locally, as the  path to the compiler will be different depending on the user running it. The caches are populated and work in CI, but everything is recompiled locally and Scala compilation takes a significant part of the build. 

This seems to be because the input is a string:
```
    /**
     * Returns the compiler executable to be used. If set,
     * a new compiler process will be forked for every compile task.
     * Defaults to {@code null}.
     *
     * <p>Setting the executable disables task output caching.</p>
     */
    @Nullable
    @Optional
    @Input
    public String getExecutable() {
        return executable;
    }
```

### Steps to Reproduce 
Run any sample Scala compilation with different users or  different Gradle home dir. 

### Your Environment
Build scan URL: Can't link as our Gradle Enterprise instance is private. 
Gradle 6.8

**Comment by ljacomet** [comment] 2021-01-14 08:38
Closing as duplicate of #15757

**Closed by ljacomet** 2021-01-14 08:38 UTC
Labels: a:bug, closed:duplicate, from:contributor
