### ISSUE TITLE
Up to Date checking wrong for different file content

### ISSUE THREAD

**Issue by swimmesberger** [gradle/gradle#8974] opened 2019-04-08 14:04 UTC
### Expected Behavior
The task with the changed file as a input file should be reexecuted

### Current Behavior
The task is considered up-to-date

### Context
I'm writing a gradle plugin based on the output of a other gradle plugin (bnd).
Look at the initial discussion in the issue I have created first for the bnd plugin:
https://github.com/bndtools/bnd/issues/3118

### Steps to Reproduce 
https://github.com/swimmesberger/bnd-manifest-bug-test

### Your Environment
Build scan URL:
https://scans.gradle.com/s/lolwpcgger2oe

**Comment by lptr** [comment] 2019-04-08 18:03
This is working as expected. The BND plugin enables `Jar.preserveFileTimestamps`, which means that the resulting JAR file will be the same byte-for-byte, no matter how many times it gets recreated.

BTW, BND should probably also enable `Jar.reproducibleFileOrder` if the goal is to create the same JAR file every time.

**Comment by swimmesberger** [comment] 2019-04-09 06:28
Thats not completely correct in this case the jar is different and therefore not byte-for-byte the same - so the hash of the file is different but gradle does not detect it.
The change is in the MANIFEST.MF which depends on a environment variable, you can change it before each execution, bnd always spits out a different jar with a different hash, but gradle sometimes just "ignores" the change

An execution example (with hashes) can be seen here: https://github.com/bndtools/bnd/issues/3118#issuecomment-480822138
or
you can try it yourself with this repo:
https://github.com/swimmesberger/bnd-manifest-bug-test

**Comment by paplorinc** [comment] 2019-05-22 13:06
Hey @swimmesberger, thanks for bringing this to our attention.
We've investigated it and agree that it's a confusing use case, we'll update the documentation to clarify it.

When detecting changes, Gradle first checks file modification date and file size changes. If both are the same, the file will be marked as up-to-date.
Since your plugin sets the file's last modified date explicitly to the same value, and you're also changing the content, the compression sometimes results in a different file size, hence the inconsistency.

**Comment by paplorinc** [comment] 2019-05-23 13:17
Fixed by https://github.com/gradle/gradle/pull/9521

**Closed** 2019-05-23 13:16 UTC
Labels: @build-cache, from:contributor
