### ISSUE TITLE
Provide ability to depend on a task in continuous mode

### ISSUE THREAD

**Issue by pioterj** [gradle/gradle#3089] opened 2017-10-05 11:18 UTC
Provide ability to depend on a task in continuous mode.

### Expected Behavior

When a task is executed (for example a server is started), it starts another task in continuous mode. When the main task is finished, the continuous build of the dependent task is finished as well.

### Current Behavior

There is no way currently to depend on a task in continuous mode.

### Context

I came across [this issue](https://github.com/robfletcher/gradle-compass/issues/73) with `gradle-compass` plugin. With compass watch mode not working I [suggested](https://github.com/robfletcher/gradle-compass/issues/73#issuecomment-333315705) an alternative of using composite build functionality instead: `./gradlew -t compassCompile`.

However, one thing that was possible with a dedicated watch mode was starting and stopping the watch task on server start/restart like this: 

```
run.dependsOn compassWatchStart
run.finalizedBy compassWatchStop
```

To ensure continuous build parity with custom watch modes, it would be nice to be able to specify that the `run` task starts `compassCompile` task in continuous mode and stops the continuous build after it's finished.

**Comment by oehme** [comment] 2017-10-05 15:24
I don't think that's the way to model it. Instead, the `run` task should be started in continuous mode and use the deployment API to either do a full or incremental deploy. That's what the Play plugin does.

As such I think this is a duplicate of https://github.com/gradle/gradle/issues/2336

**Closed by oehme** 2017-10-05 15:24 UTC
Labels: a:feature, from:member, in:continuous-build

**Comment by pioterj** [comment] 2017-10-06 08:57
@oehme I don't understand how the other issue would address this use case. 

Note that `run` and `compileCompass` tasks are completely independent and come from different plugins. The first one could be for example `bootRun` from Spring Boot with [developer tools](https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html) enabled so that you wouldn't need to start it in continuous mode. It's the second task that you want to be run continuously, for example to compile SASS to CSS.

**Comment by oehme** [comment] 2017-10-06 09:10
`bootRun` should be started in continous mode. It would just see that the app is already running and do nothing in that case. That's the same we do for [`playRun`](https://github.com/gradle/gradle/blob/master/subprojects/platform-play/src/main/java/org/gradle/play/tasks/PlayRun.java#L83). The play framework takes care of the reloading, the Gradle task just makes sure the server is running.

**Comment by pioterj** [comment] 2017-10-06 09:25
I guess you can but I don't see how it helps if you use developer tools. That's not the point of the issue though. How will deployment API help you to execute a completely independent task continuously when you are running your app?

**Comment by oehme** [comment] 2017-10-06 10:38
You call `gradle run --continous`. `run` depends on whatever preparation tasks you need, like `compileCompass`. Whenever Gradle detects a change, these tasks are re-executed. `run` only starts the app once (through the deployment API) and keeps it running on subsequent changes. It only shuts it down when the user exists continuous mode.

**Comment by pioterj** [comment] 2017-10-06 10:56
Got it, thanks!

**Comment by gunslingor** [comment] 2022-09-24 15:51
It doesn't really work great guys... I would highly recommend a application/devRun default task... people are struggling and sometimes the CLI isn't used to interface with gradle (e.g. intellij IDE gradle Plugin), so we really need this I think. 

I was struggling for weeks to get a good dev environment setup and running, because I assumed gradle (a development tool)  already accounted for a dev run configuration, the problem was gradles defaults not the other tool defaults:
 (https://stackoverflow.com/questions/73765993/how-to-setup-a-docker-compose-springboot-webserver-mysql-project-using-gradle-an?noredirect=1#comment130270460_73765993). 

I will be trying to write the custom gradle devRun task soon, I don't see any other option if I want to use the gradle plugin for dev run.
