### ISSUE TITLE
Deprecation warning on trivial kotlin-dsl project due to KGP's checkKotlinGradlePluginConfigurationErrors

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#26981] opened 2023-11-08 08:44 UTC
### Current Behavior

```
> Task :checkKotlinGradlePluginConfigurationErrors
Build service 'KotlinToolingDiagnosticsCollector_879319487' is being used by task ':checkKotlinGradlePluginConfigurationErrors' without the corresponding declaration via 'Task#usesService'. This behavior has been deprecated. This will fail with an error in Gradle 9.0. Declare the association between the task and the build service using 'Task#usesService'. Consult the upgrading guide for further information: https://docs.gradle.org/8.5-rc-1/userguide/upgrading_version_7.html#undeclared_build_service_usage

FAILURE: Build failed with an exception.

* What went wrong:
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1s
4 actionable tasks: 1 executed, 3 up-to-date
```

### Expected Behavior

Build passes as before.

Could Gradle `kotlin-dsl` apply the workaround until Kotlin fixes it?

### Context (optional)

https://youtrack.jetbrains.com/issue/KT-63165

### Steps to Reproduce

1. Clone https://github.com/TWiStErRob/repros/tree/main/gradle/kotlinDsl-stableConfigurationCache-checkKotlinGradlePluginConfigurationErrors-usesService
2. `gradlew build`

<details><summary>Note: the minimal repro is very minimal</summary>

`build.gradle.kts`
```kotlin
plugins {
	`kotlin-dsl`
}
```
`settings.gradle(.kts)`
```kotlin
enableFeaturePreview("STABLE_CONFIGURATION_CACHE")
```
`gradle.properties`
```properties
org.gradle.warning.mode=fail
```

</details>

### Gradle version

Gradle 8.5-rc-1

### Gradle version that used to work

Gradle 8.4

**Comment by cobexer** [comment] 2023-11-09 13:16
Thank you for providing a valid report.

The issue is in the backlog of the relevant team and is prioritized by them.
***
@gradle/bt-configuration  Do we still consider this a regression if the `STABLE_CONFIGURATION_CACHE` feature preview is turned on?

**Comment by ljacomet** [comment] 2023-11-13 09:39
Hey @TWiStErRob ,

After discussing this in the team, we are not going to consider this a regression and a blocker for 8.5.

There are a couple reasons for that:
* The root problem is in the Kotlin Gradle plugin and needs to be fixed there. We will work with them on making sure they do run tests with `STABLE_CONFIGURATION_CACHE` enabled.
* The issue is only visible when enabling a feature preview

Given the above, I am closing this as a problem with KGP and no changes needed on the Gradle side.

**Closed by ljacomet** 2023-11-13 09:39 UTC
Labels: in:kotlin-dsl, in:build-services, closed:kotlin

**Comment by TWiStErRob** [comment] 2023-11-13 10:07
Makes sense, thanks for the update. If anyone runs into this they can use the workaround.

Note: there's something to do on Gradle side, which is to use the fixed Kotlin version later on. This is likely to be Kotlin 2.0, which probably means this will stay with us until Gradle 9?
