### ISSUE TITLE
How can I expand only a particular subdirectory of a zipTree?

### ISSUE THREAD

**Issue by kenzierocks** [gradle/gradle#1108] opened 2017-01-05 23:21 UTC
Right now, if you have a zip tree like this:
```
file.zip
├── a
│   └── b
└── c
    ├── d
    └── e
```
...it is impossible to extract _just `c`_.

If I want files `d` and `e` to be copied to another folder, I have to copy the entirety of `file.zip` to a temporary directory, then copy the contents of `c` to the destination.

### Expected Behavior
`zipTree` should have an option, perhaps `root`, to specify the folder to be used as the root of the zip tree. If not that, there should be a similar function to achieve the same goal.

Example:
```groovy
copy {
     from zipTree('file.zip', root: 'c')
     into 'z'
}
```

### Current Behavior
To achieve the same effect as the proposed `root` option, something like this can be used:
```groovy
def tempDir = File.createTempFile("gradle-unzip", "")
tempDir.mkdir()
copy {
     from zipTree('file.zip')
     into tempDir
}
copy {
     from new File(tempDir, 'c')
     into 'z'
}
```
This is much longer than it needs to be, and it requires the entire zip to be unpacked rather than only a small section.

### Context
This bug affects me when I'm handling zips of program distributions. I often need only the binaries, or only the source, and there's no way for me to just pull files from `file.zip/bin`. I need to unpack the whole archive, which sometimes contains a folder with many files and the resulting extraction time can be upwards of 30 seconds.

Note: A majority of this bug was migrated from [GRADLE-3025](https://issues.gradle.org/browse/GRADLE-3025) and there is a related forum post [here](https://discuss.gradle.org/t/how-can-i-expand-only-a-particular-subdirectory-of-a-zip-tree/7497/14).

**Comment by Flamenco** [comment] 2017-06-14 13:43
Here's how we solved this.
```
def subDir = 'my/sub/dir'
copy {
  from zipTree(sourceJar).matching {include "$subDir/**"}
  into targetDir                        
  eachFile { fcp ->
    fcp.path = fcp.path.replaceFirst("^$subDir", '')
  }
}
```

**Comment by nicolas-albert** [comment] 2017-06-21 08:38
I have the same need, so I handle this case like this :
```
	task unzipWarLib(type: Copy, dependsOn: 'syncLibs') {
		from zipTree(configurations.war[0])
		include 'WEB-INF/lib/**'
		into 'lib'
		eachFile { f ->
			f.path = f.path.replaceFirst('WEB-INF/lib', '')
		}
		includeEmptyDirs false
	}
```
But it could be very nice to do this with one line.

**Comment by tillKaiser** [comment] 2018-03-02 09:23
This works fine. However it fails if I want to include empty directories. For those the path replace does not work, so they end up with the full path e.g. WEB-INF/lib/... Is there a reasonable way to make this work for empty directories?

**Comment by wszeboreq** [comment] 2018-05-02 19:25
This is a really awaited feature also for us. I hope it will be implemented.

**Comment by kenzierocks** [comment] 2018-05-14 22:46
Please see if #5405 will solve your use case. I think it should handle all of them.

**Comment by wszeboreq** [comment] 2018-05-22 13:58
@kenzierocks: For me, your solution looks very promising.

**Comment by big-guy** [comment] 2018-08-31 19:56
@kenzierocks I may be missing something, but you can filter directly in the copy.  

Here's a reproducible build that does what you want (just run `gradle assertContainsOnlyC`):

```
apply plugin: 'base'

task generate {
    outputs.dir temporaryDir
    doLast {
        project.delete temporaryDir
        def a = new File(temporaryDir, "a")
        a.mkdirs()
        new File(a, "b").text = "b file"
        def c = new File(temporaryDir, "c")
        c.mkdirs()
        new File(c, "d").text = "d file"
        new File(c, "e").text = "e file"
    }
}

task zip(type: Zip) {
    from(generate)
}

task unzip(type: Sync) {
    dependsOn zip
    from (zipTree(zip.archivePath)) {
        include "c/**"
    }
    into temporaryDir
}

task assertContainsOnlyC {
    dependsOn unzip

    doLast {
        def outputDir = unzip.destinationDir
        assert outputDir.listFiles()*.name == ["c"]
        assert new File(outputDir, "c/d").exists()
        assert new File(outputDir, "c/e").exists()
    }
}
```

**Comment by kenzierocks** [comment] 2018-08-31 20:31
The intent here, which may be unclear from the original post but is visible in the following comments, is to also exclude the `c` directory from existing: your last two lines should be:
```groovy
        assert new File(outputDir, "d").exists()
        assert new File(outputDir, "e").exists()
```

**Comment by wszeboreq** [comment] 2019-01-10 10:38
Lack of this feature is currently our #1 problem we have with Gradle. We hit it constantly. The solution proposed in pull request https://github.com/gradle/gradle/pull/5405 looks promising, but the pull request unfortunately still waits for Gradle team.

**Comment by big-guy** [comment] 2019-01-29 22:50
@wszeboreq I took another look and I think you should be able to do this with the existing APIs.

The issue with #5405 is that it combines two different things into one (filtering the ZIP and changing the extracted path).

Here's a tweak based on https://github.com/gradle/gradle/issues/1108#issuecomment-417773298:
```
task unzip(type: Sync) {
    dependsOn zip
    from (zipTree(zip.archivePath)) {
        include "c/**"
        includeEmptyDirs = false
        eachFile { fcd ->
            fcd.relativePath = new RelativePath(true, fcd.relativePath.segments.drop(1))
        }
    }
    into temporaryDir
}
```
This should only extract the `c` directory from the ZIP and removes that 'c' level from the output.

I think that the majority of builds either extract the whole zip or extract only a subset (but keep the same structure). A smaller number of builds need to rearrange the output from a given ZIP file and I don't think that should be a high level API for doing that without another example of how this could be used.  I think we could add a sample for this, some documentation and maybe something to `RelativePath` to make it easier to remove the leading segment(s).

If this is really common in your environment, you could also consider having a helper method for it:
```
task unzip(type: Sync) {
    dependsOn zip
    with subTree(zipTree(zip.archivePath), "c/**")
    into temporaryDir
}

CopySpec subTree(Object archive, String includePattern) {
    return project.copySpec {
        from(archive) {
            include includePattern
            includeEmptyDirs = false
            eachFile { fcd ->
                fcd.relativePath = new RelativePath(true, fcd.relativePath.segments.drop(1))
            }
        }
    }
}
```

**Comment by tjaneczko** [comment] 2019-01-30 13:39
Just ran into this on a project, the main issue with the current solutions / workarounds is the `includeEmptyDirs = false` line since we also want to extract empty directories from the zip file.  Our use case is extracting tomcat without the top-level directory. The tomcat zip contains two empty directories which we then need to manually recreate after the extraction.

**Comment by wszeboreq** [comment] 2019-01-31 15:10
@big-guy, thank you for your response, comments and the recommendation.

The workaround with 'eachFile()' and 'fcd.relativePath' is a standard workaround for the problem here, recommended in all the places where people complain about lack of possibility to extract some deep part of the archive. In fact we already use this workaround extensively. The main issue with it is the 'includeEmptyDirs = false' mentioned by @tjaneczko - to be able to workaround this problem with the workaround (yes, a workaround to the problem caused by the other workaround) in a small desperation I'm lobbying for providing the 'eachFile()' iterating also over the directories (see https://github.com/gradle/gradle/issues/2940). The second issue with the 'fcd.relativePath' workaround is that it is quite verbose and quickly gets complicated in case of nested copySpec hierarchies, where 'relativePath' constructed manually usually should start with some prefix resulting from 'into' statements in parent copy specs.

The ability to obtain a subtree of the fileTree would significantly improve the flexibility of Gradle file-realted features. For me it looks as a natural move in fileTree API evolution and a very good candidate for significant improvement. I'm sure users would appreciate it.

The simplest scenario we have here is having a dependency component archive used in two different products. One product requires the entire archive content, so for it the dependency is just expanded and the component content structure just matches it. The second product just needs some part of the archive, rooted somewhere inside it.

Lack of API for handling this scenario for me is quite surprising and... just does not fit with the magnificence of Gradle in general. :-)

The example about the 'subTree()' helper method is extremely valuable, thank you - I was not aware of the way to achieve this. Could you please provide some hint how to ship such a helper method inside a binary Gradle plugin in a professional way?

**Comment by lacasseio** [comment] 2019-02-12 19:20
The `subTree()` can be written in a variety of ways to allows a certain degree of flexibility and reusability. I won't go into those details. The best way I can think of packaging the logic inside a "plugin" to use in Gradle is simply creating a library that depends on the `gradleApi()`. You have can have a `CopySpecUtils` class with a static method `subTree`. Then you can add the library to the `classpath` dependency inside the `buildscript` bloc. You then `import static` the method to be used in your build script. You could also use a plugin that adds the method as an extended property of all `Copy` task. However, that solution wouldn't so great when using the Kotlin DSL.

**Comment by lacasseio** [comment] 2019-02-12 23:07
As explained by Sterling, the solution to this problem should be ad-hoc. However, the solution only works when `includeEmptyDirs` is set to `false`. In the other case, the user needs to be able to write the relative path of the empty directory as well which would be similar to solving https://github.com/gradle/gradle/issues/2940. However, the way forward on this isn't cut and dried as the `FileCopyDetails` seems strange for a directory, specifically methods from `ContentFilterable`. The behaviour of those methods would need to be handled properly in a backward manner as users may not expect directories to be passed through `eachFile` actions.

As a way forward, we will extract a sample to put in the user guide, add a simple coverage test including both empty and non-empty directories. The empty directory test case won't be implemented until https://github.com/gradle/gradle/issues/2940 is handled in some way.

**Comment by lacasseio** [comment] 2019-02-13 00:20
PR https://github.com/gradle/gradle/pull/8494 was created to document how to solve this use case.

**Closed** 2019-02-15 17:14 UTC
Labels: a:feature, from:contributor, in:core
