### ISSUE TITLE
Gradle fails to obtain AWS IAM permissions when running in AWS CodeBuild

### ISSUE THREAD

**Issue by cslee00** [gradle/gradle#4041] opened 2018-01-15 20:47 UTC
When running a Gradle build under AWS CodeBuild that uses Gradle's built-in AWS support it fails to obtain credentials:

``` 
repositories {
            maven {
                url "s3://somebucket"
                authentication {
                    awsIm(AwsImAuthentication)
                }
            }
        }
```
Results in:
```
20:09:46.849 [DEBUG] [org.gradle.internal.resource.transport.aws.s3.S3Client] Attempting to put resource:[snapshots/com/me/sample-project/1.1/sample-project-1.1.pom] into s3 bucket [devtools-regional-mavenrepositorys3bucket-qwoqo4bp0unb]
20:09:46.849 [DEBUG] [com.amazonaws.auth.AWSCredentialsProviderChain] Unable to load credentials from EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY))
20:09:46.850 [DEBUG] [com.amazonaws.auth.AWSCredentialsProviderChain] Unable to load credentials from SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey)
20:09:46.850 [DEBUG] [com.amazonaws.auth.AWSCredentialsProviderChain] Unable to load credentials from com.amazonaws.auth.profile.ProfileCredentialsProvider@653b3345: AWS credential profiles file not found in the given path: /root/.aws/credentials
20:09:46.850 [DEBUG] [com.amazonaws.internal.EC2MetadataClient] Connecting to EC2 instance metadata service at URL: http://169.254.169.254/latest/meta-data/iam/security-credentials/
20:09:48.853 [DEBUG] [com.amazonaws.auth.AWSCredentialsProviderChain] Unable to load credentials from InstanceProfileCredentialsProvider: Unable to load credentials from Amazon EC2 metadata service
20:09:48.853 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Upload s3://devtools-regional-mavenrepositorys3bucket-qwoqo4bp0unb/snapshots/com/me/sample-project/1.1/sample-project-1.1.pom'
20:09:48.853 [ERROR] [org.gradle.api.publication.maven.internal.action.LoggingMavenTransferListener] Could not transfer artifact com.me:sample-project:pom:1.1 from/to remote (s3://devtools-regional-mavenrepositorys3bucket-qwoqo4bp0unb/snapshots): Could not write to resource 'com/me/sample-project/1.1/sample-project-1.1.pom'
```

This may be related to info from here: https://docs.aws.amazon.com/codebuild/latest/userguide/troubleshooting.html#troubleshooting-versions, which indicates that AWS Java SDK 1.1.16 or higher is required to pickup credentials (Gradle 4.4.1 is using 1.1.6).

Use case is publishing artifacts to S3 repository, where access to the repository is part of the CodeBuild service role.

**Comment by bmuschko** [comment] 2018-01-15 21:31
Thanks for making us aware of the issue. I am closing this as it is a duplicate of https://github.com/gradle/gradle/issues/4012. A pull request has already been submitted: https://github.com/gradle/gradle/pull/4029.

**Closed by bmuschko** 2018-01-15 21:31 UTC
