### ISSUE TITLE
Unable to configure task property (in extension actually) from another task property

### ISSUE THREAD

**Issue by tbroyer** [gradle/gradle#16604] opened 2021-03-21 19:07 UTC
Trying to configure a property of ErrorProne's extension from another property of the same task causes circular dependency of the task on itself.
Using an intermediary provider works in Gradle 6 with a deprecation warning, but fails in Gradle 7.

### Expected Behavior
No error or warning should be emitted.

Dependency of a task on itself (at least without any intermediary) should be allowed.

### Current Behavior
Circular dependency of the task on itself, or deprecation warning in Gradle 6 (error in Gradle 7)

### Context
Trying to configure `compileJava.options.errorprone.excludedPaths` using `compileJava.options.generatedSourceOutputDirectory` such that ErrorProne ignores sources generated by annotation processors.

There does not seem to be any workaround besides reconfiguring the `options.generatedSourceOutputDirectory`, which cannot always be used (e.g. in a plugin, where you'd like to let users reconfigure the `options.generatedSourceOutputDirectory` themselves).

See https://github.com/tbroyer/gradle-errorprone-plugin/issues/54

### Steps to Reproduce 
1. use `gradle init` to create a Java library project (here using the Kotlin DSL)
2. edit `lib/build.gradle.kts` to add `id("net.ltgt.errorprone") version "1.3.1"` plugin, and ErrorProne dependencies
```kotlin
    errorprone("com.google.errorprone:error_prone_core:2.5.1")
    errorproneJavac("com.google.errorprone:javac:9+181-r4173-1")
```
3. try to configure `options.errorprone.excludedPaths` on all `JavaCompile` tasks using their `options.generatedSourceOutputDirectory`
```kotlin
tasks.withType<JavaCompile>().configureEach {
    options.errorprone.excludedPaths.set(
        options.generatedSourceOutputDirectory.map { """.*/\Q${relativePath(it)}\E/*""" })
    // Added here to help debugging
    doFirst {
        print(options.errorprone.excludedPaths.orNull)
    }
}
```
4. run `./gradlew build`; with Gradle 6.8.3 or 7.0-milestone-3, this leads to a circular dependency of the tasks on themselves:
```
FAILURE: Build failed with an exception.

* What went wrong:
Circular dependency between the following tasks:
:lib:compileJava
\--- :lib:compileJava (*)

(*) - details omitted (listed previously)
```
5. try introducing an intermediary provider:
```kotlin
    options.errorprone.excludedPaths.set(provider {
        options.generatedSourceOutputDirectory.map { """.*/\Q${relativePath(it)}\E/*""" }.orNull })
```
6. run `./gradlew build` again; with Gradle 6.8.3 this works, but prints a deprecation warning:
```
> Task :lib:compileJava
Querying the mapped value of task ':lib:compileJava' property 'options.generatedSourceOutputDirectory' before task ':lib:compileJava' has completed has been deprecated. This will fail with an error in Gradle 7.0. Consult the upgrading guide for further information: https://docs.gradle.org/6.8.3/userguide/upgrading_version_6.html#querying_a_mapped_output_property_of_a_task_before_the_task_has_completed
        at Build_gradle$4$1.call(build.gradle.kts:45)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
.*/\Qbuild/generated/sources/annotationProcessor/java/main\E/*
> Task :lib:compileTestJava
Querying the mapped value of task ':lib:compileTestJava' property 'options.generatedSourceOutputDirectory' before task ':lib:compileTestJava' has completed has been deprecated. This will fail with an error in Gradle 7.0. Consult the upgrading guide for further information: https://docs.gradle.org/6.8.3/userguide/upgrading_version_6.html#querying_a_mapped_output_property_of_a_task_before_the_task_has_completed
        at Build_gradle$4$1.call(build.gradle.kts:45)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
.*/\Qbuild/generated/sources/annotationProcessor/java/test\E/*
```
with Gradle 7.0-milestone-3, build fails.

### Your Environment

Build scan URL: https://scans.gradle.com/s/kvc5vzebt5uxm

**Comment by tbroyer** [comment] 2022-04-02 10:21
This is still an issue with 7.4.2. Error message is slightly different but still the same overall (for the "intermediate provider" step above):

```
> Task :lib:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lib:compileJava'.
> Error while evaluating property 'options.compilerArgumentProviders.errorprone$0.errorproneOptions.excludedPaths' of task ':lib:compileJava'
   > Failed to calculate the value of extension 'errorprone' property 'excludedPaths'.
      > Querying the mapped value of task ':lib:compileJava' property 'options.generatedSourceOutputDirectory' before task ':lib:compileJava' has completed is not supported
```

And I still haven't found a workaround ‼

IMO Gradle should at least allow reading the task's properties when it itself evaluates them, avoiding the "Querying … before task has completed" message. Even better if it would special-case direct dependencies of tasks on themselves (no intermediate in the circular dependency).

**Comment by tbroyer** [comment] 2022-04-02 10:31
Note that this is also a problem with a task's own properties, but it doesn't create a circular dependency here; e.g.
```kotlin
tasks.withType<JavaCompile>().configureEach {
    options.headerOutputDirectory.set(destinationDirectory.map { it.dir("headers") })
}
```
```
* What went wrong:
Execution failed for task ':lib:compileJava'.
> Failed to calculate the value of task ':lib:compileJava' property 'options.headerOutputDirectory'.
   > Querying the mapped value of task ':lib:compileJava' property 'destinationDirectory' before task ':lib:compileJava' has completed is not supported
```

**Comment by mlopatkin** [comment] 2024-06-20 09:04
This issue will be closed as a duplicate of

* #26340

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

I see that the linked ErrorProne plugin issue already has a solution, but I'll add some background here for compeleteness.

The contract for `map` currently aims to ensure that the mapping function not only sees the actual value of the source provider (the path in this case), but also the actual contents of that file, which is produced by the task. It is unsafe to relax this restriction even when obtaining the mapped provider in the task's own action, because the mapping function may come from elsewhere and expect the file contents to be ready - in which case the circular failure is legit.

To allow accessing the path itself,  there is [`FileSystemLocationProperty.getLocationOnly`](https://docs.gradle.org/current/javadoc/org/gradle/api/file/FileSystemLocationProperty.html#getLocationOnly()) method, which returns a provider obtainable without making the task dependency. Such a provider can be safely `map`-ed and used.

**Closed by mlopatkin** 2024-06-20 09:04 UTC
Labels: a:bug, in:configuration-model
