### ISSUE TITLE
reportsUnreadableSourceDir: The build should fail but did not

### ISSUE THREAD

**Issue by McPringle** [gradle/gradle#1069] opened 2016-12-26 16:41 UTC
### Expected Behavior
The test CopyErrorIntegrationTest#reportsUnreadableSourceDir expects the build to fail.

### Current Behavior
The build did not fail: `java.lang.AssertionError: expected build to fail but it did not.`

### Context
I tried to build Gradle.

### Steps to Reproduce (for bugs)
```
$ git clone git@github.com:gradle/gradle.git
$ cd gradle
$ ./gradlew build
```

### Your Environment
- Mac OS X 10.12.2 Build 16C67
- Java 1.8.0 Build 112
- git 2.11.0

For details like stack trace, standard out and standard error please take a look at this Gist:
https://gist.github.com/McPringle/3f84fc24c0610f122e26cd0502abf126

**Comment by bmuschko** [comment] 2017-01-03 17:08
I just tried the following command on `master` but couldn't reproduce the issue on my Mac with Java 1.8.0_60: 

    ./gradlew core:integTest --tests org.gradle.api.tasks.CopyErrorIntegrationTest

We also do see the test failing on our CI builds for Linux or Windows with Java 8. The error message suggests that the type of an input property is wrong. Can you check if you didn't change any code? If that's not the case I might want to upgrade to the latest Java 8 version but I don't think that's the issue really.

**Comment by McPringle** [comment] 2017-01-16 08:39
Good morning

Please excuse the long time of my reaction. New Year and holidays.

I did not change the source, my working space is clean. Today I ran the tests again and, well, they are successful. I did not update my environment. I ran the failing test last month about five times (failed every time) and yesterday again five times (every time successful). I'll investigate it. Something must have changed because of the different results.

Where are your CI builds running? They have still the same error or are they now successful, too?

**Comment by oehme** [comment] 2017-09-15 16:51
Closing as this was likely a situational problem. CI is green.

**Closed** 2017-09-15 16:50 UTC
Labels: a:question, affects-version:3.4, from:contributor, in:core
