### ISSUE TITLE
Project.getProperties triggers (early) evaluation of the publishing block

### ISSUE THREAD

**Issue by 3ll3d00d** [gradle/gradle#2496] opened 2017-07-18 09:48 UTC
Configuration for the maven-publish plugin is eagerly evaluated in obscure ways that break the build.

### Expected Behavior
Accessing `project.properties` should not affect the `publishing` block

### Current Behavior
Accessing `project.properties` triggers the evaluation of `publishing` block which can lead to a POM that has no dependencies.

### Context
This issue means the maven-publish plugin creates an invalid POM. 

I am using the maven-publish plugin because I am migrating a build system to artifactory and the existing build use the PomFilter functionality to customize the POM on publication. The gradle artifactory plugin doesn't seem to support this behaviour without using the maven-publish plugin.

### Steps to Reproduce (for bugs)
(I can't upload to github from behind a corporate firewall so examples inline)

Create a basic java project with this build.gradle

    buildscript {
        repositories {
            mavenCentral()
        }
    }
    
    apply plugin: 'java'
    apply plugin: 'maven-publish'
    
    project.group = 'foo.bar'
    project.version = '0.0.1'
    
    publishing {
        publications {
            mavenJava(MavenPublication) {
                from components.java
            }
        }
    }
    
    // triggers the bug
    properties.each {
        project.logger.error(it.toString())
    }
    
    dependencies {
        compile 'org.testng:testng:6.9.11'
    }

Run `gradle generatePomFileForMavenJavaPublication`

The output is 

	<?xml version="1.0" encoding="UTF-8"?>
	<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	  <modelVersion>4.0.0</modelVersion>
	  <groupId>foo.bar</groupId>
	  <artifactId>baz</artifactId>
	  <version>0.0.1</version>
	</project>

Remove the call to project.properties and repeat, i.e. change build.gradle to

    buildscript {
        repositories {
            mavenCentral()
        }
    }

    apply plugin: 'java'
    apply plugin: 'maven-publish'

    project.group = 'foo.bar'
    project.version = '0.0.1'

    publishing {
        publications {
            mavenJava(MavenPublication) {
                from components.java
            }
        }
    }

    dependencies {
        compile 'org.testng:testng:6.9.11'
    }

Repeat the pom task and the output is now

	<?xml version="1.0" encoding="UTF-8"?>
	<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	  <modelVersion>4.0.0</modelVersion>
	  <groupId>foo.bar</groupId>
	  <artifactId>baz</artifactId>
	  <version>0.0.1</version>
	  <dependencies>
		<dependency>
		  <groupId>org.testng</groupId>
		  <artifactId>testng</artifactId>
		  <version>6.9.11</version>
		  <scope>compile</scope>
		</dependency>
	  </dependencies>
	</project>

i.e. dependencies are now included in the output

### Your Environment
gradle 4.0.1

**Comment by bmuschko** [comment] 2017-07-18 20:43
Interesting side effect. I can reproduce the issue.

Why exactly do your iterate over _all_ properties? Wouldn't you want to retrieve a specific one? If that's the case you can use `project.findProperty('...')` which does not trigger the issue.

**Comment by 3ll3d00d** [comment] 2017-07-18 21:51
most uses can be replaced by `findProperty`, previously they were like `project.properties['foo']`

I do have one bit of code though that is mainly used by CI builds to allow certain properties on custom extensions to be overridden just by adding a property like `env.ORG_GRADLE_PROJECT_some.customextension.property` to the teamcity build config

This is basically implemented via `project.properties.grep { it.key.startsWith(somePrefix) }.each { // use Eval.xy to get the value into the extension }` where somePrefix is dictated by the plugin that calls this code. No doubt I could replace this with something a bit more targeted.

**Comment by bmuschko** [comment] 2017-07-18 21:52
Thanks for the feedback. What I proposed is a workaround. Would you be interested in potentially finding a solution for this problem in Gradle itself?

**Comment by 3ll3d00d** [comment] 2017-07-18 21:54
sure, I can take a look at least anyway.

**Comment by bmuschko** [comment] 2017-07-18 21:59
Thanks so much!

**Comment by 3ll3d00d** [comment] 2017-07-23 14:47
This problem seems to occur because requesting all properties ends up hitting `ExtensionsHolder#get` (which is called by `CompositeDynamicObject#getProperties` -> `ExtensionDynamicObject#getProperties` -> `ExtensionStorage#getAsMap` ). In the case of the `PublishingExtension`, which is annotated by `DeferredConfigurable`, this is wrapped in a `DeferredConfigurableExtensionHolder` which specialises `get` as follows;

    public T get() {
        configureNow();
        return extension;
    }

In contrast, `hasProperty` just checks for the presence of the named extension in the `ExtensionsStorage` map.

It's not obvious to me what the correct behaviour is here. It seems to me that configuring the deferred thing in an uncontrolled fashion (i.e. not relying on an explicit "configure me now" call) is an implementation that will always be prone to this sort of problem. The fact that this behaviour is specific to a single implementation makes me wonder if there are plans to revise this design substantially anyway (in order to use it more broadly), are there?

If not I'm not really sure what behaviour is expected here? Should it ignore the fact the unconfigured extension exists? expose the extension in an unconfigured state? something else?

**Comment by lacasseio** [comment] 2017-08-04 19:19
@3ll3d00d It's funny because I did something similar to you but in the software model, a year ago which doesn't have [easy] access to the project property. What I ended up doing was using `System.getProperty` properties through `-D` flag. Given what you are trying to do seems to pass properties via the environment variable, you could iterate through `System.env` for anything starting with `ORG_GRADLE_PROJECT_` then filter for your prefix.

You could also do what I did and use `System` properties via `-D` flag. If you need to be able to pass properties via the environment variable, you could `GRADLE_OPTS` and pass your properties via the `-D` flag.

These are workarounds to your problem. The solution would probably to use the [Provider API](https://docs.gradle.org/4.0/release-notes.html#public-type-for-representing-lazily-evaluated-properties). Gradle doesn't yet have `Provider` enabled setter, but if you see places those would be needed, you are welcome to open a PR.

**Comment by oehme** [comment] 2018-05-02 06:28
Fixed by #4997

**Closed by oehme** 2018-05-02 06:28 UTC
Labels: a:bug, from:contributor, in:maven-plugin
