### ISSUE TITLE
Consistent release versioning

### ISSUE THREAD

**Issue by pvegh** [gradle/gradle#12645] opened 2020-03-26 12:16 UTC
gradle wrapper --gradle-version 6.3.0
works though (probably shouldn't) but downloading the 6.3.0 zip file fails LATER (!) when actually syncing the project.

Only this works correctly in both steps:
gradle wrapper --gradle-version 6.3

This is a bit awkward, because the current release is tagged with `6.3.0`
Also, when searching in the shell history for the last wrapper command, it might have been 6.2.1 or something. So I would change it to 6.3.0, which won't work.

Request: Can we have major.minor.patch everywhere even for .0 releases?

My 50 cents: we might need an easier to use CLI for this, which helps choose the correct/newest version without remembering a long-double-dash parameter. Very few devs I know actually upgrade gradle regularly, because they don't know how AND because it's cumbersome to do.

**Comment by pvegh** [comment] 2021-03-30 12:11
IDK, ping?

**Comment by pvegh** [comment] 2021-06-01 05:32
Sorry but this really makes it hard to try new versions.
One page 3 different versioning styles?
One of them is correct, can you guess which one?

<img width="628" alt="gradle ver fail" src="https://user-images.githubusercontent.com/3873889/120271303-5f5c1b00-c2ab-11eb-9f28-d61ab9b33561.png">

**Comment by mlopatkin** [comment] 2021-07-20 14:02
Closing as a duplicate of #17329 as it states that we aren't planning to change the versioning scheme any time soon.

**Closed by mlopatkin** 2021-07-20 14:02 UTC
Labels: a:feature, to-triage
