### ISSUE TITLE
BuildOperationTrace is broken for composite builds 

### ISSUE THREAD

**Issue by breskeby** [gradle/gradle#3873] opened 2017-12-21 15:06 UTC
When running a composite build with `-Dorg.gradle.internal.operations.trace`, the trace is broken due to 
`ApplyScriptPluginBuildOperationType.Details#getBuildPath()` always throwing an `IllegalStateException` for `settings.gradle` scripts of included builds resulting in a trace file that doesn't contain the buildPath for applied settings scripts of non root builds.

**Comment by breskeby** [comment] 2017-12-21 15:17
Added PR exposing the problem at https://github.com/gradle/gradle/pull/3874

**Comment by ldaley** [comment] 2018-02-02 02:56
This aspect has effectively been fixed by #4227. I have raised #4241 to cover the fundamental root cause.

**Closed by ldaley** 2018-02-02 02:56 UTC
Labels: a:bug, affects-version:4.4, from:member
