### ISSUE TITLE
processResources + filesMatching + filter does not replacing last generated file

### ISSUE THREAD

**Issue by adnsimona** [gradle/gradle#22748] opened 2022-11-16 10:34 UTC
### Context & Steps to Reproduce 
We're using a code snippet like this to generate a properties file with replacing the version.

```
processResources {
    filesMatching('**/settings.properties') {
        def appVersionWithCommitTimestamp="${appVersion}.${gitCommitTimestamp}".toString()
        filter(ReplaceTokens, tokens: ['VERSION': appVersionWithCommitTimestamp])
    }
}
```

### Expected Behavior
File should be replaced in the build/resources folder when the generated file has changed (newer version)

### Current Behavior
File is not replaced when it is already exists. No matter the version change.

### 

### Workaround
```
task deleteBuildResources(type: Delete) {
    delete 'build/resources'
}

processResources.dependsOn(deleteBuildResources)
```

### Your Environment

Gradle version is 6.8.3

**Comment by eskatos** [comment] 2022-11-25 09:07
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/861

Please add your 👍 to that issue.

----

The workaround is to explicitly declare your task inputs. In your example it would be as follows:

```groovy
processResources {
    inputs.property('appVersion', appVersion)
    inputs.property('gitCommitTimestamp', gitCommitTimestamp)
    filesMatching('**/settings.properties') {
        def appVersionWithCommitTimestamp="${appVersion}.${gitCommitTimestamp}".toString()
        filter(ReplaceTokens, tokens: ['VERSION': appVersionWithCommitTimestamp])
    }
}
```

See https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:task_input_output_runtime_api

**Closed** 2022-12-05 09:39 UTC
Labels: closed:duplicate, in:file-tasks
