### ISSUE TITLE
disagree on InnerClasses attribute

### ISSUE THREAD

**Issue by alexbezhan** [gradle/gradle#17478] opened 2021-06-17 11:17 UTC
Inlined functions that use enum in exhausted `when` expression fail compilation when used from test compilation unit and `useJUnitPlatform()` is enabled in gradle build.

### Expected Behavior
Compilation should succeed

### Current Behavior
Compilation fails with the following exception:
```
org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not execute test class 'app.IncompatibleClassMainKt$main$$inlined$f$1$wm$ApiKt$WhenMappings'.
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IncompatibleClassChangeError: api.ApiKt and app.IncompatibleClassMainKt$main$$inlined$f$1$wm$ApiKt$WhenMappings disagree on InnerClasses attribute
	at java.base/java.lang.Class.getDeclaringClass0(Native Method)
	at java.base/java.lang.Class.getEnclosingClass(Class.java:1517)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.isInnerClass(JUnitPlatformTestClassProcessor.java:104)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.access$200(JUnitPlatformTestClassProcessor.java:54)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.execute(JUnitPlatformTestClassProcessor.java:90)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.execute(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	... 25 more
```

### Context
I was trying to write a test, but then found this problem and tried to reduce it to the smallest reproducible code and it turns out it happens in main method as well.

### Your Environment
I made a minimal project that reproduces this problem: https://github.com/alexbezhan/kotlin-junitplatform-incompatible-inner-class-error

Gradle: 7.1
Kotlin: 1.5.10

**Comment by alexbezhan** [comment] 2021-06-17 11:18
Related issue: https://github.com/gradle/gradle/issues/6693

**Comment by alexbezhan** [comment] 2021-06-30 12:02
@mlopatkin Hi, any updates on that one?

**Comment by mlopatkin** [comment] 2021-06-30 12:15
Thank you for the report and the reproducer. The issue is valud but this area is not in focus now so I can't give any estimates about when the solution will be available.

**Comment by alexbezhan** [comment] 2021-06-30 14:50
@mlopatkin gotcha. Do you know how to workaround this problem? It is blocking me to upgrade to Kotlin 1.5

**Comment by mlopatkin** [comment] 2021-06-30 15:22
Upon further investigation, I suspect that this is an issue with [the new Kotlin compiler's backend](https://kotlinlang.org/docs/whatsnew15.html#stable-jvm-ir-backend). I was able to "fix" the reproducer by switching to the old IR:
```
kotlinOptions.useOldBackend = true
```
It seems that the old backend doesn't emit InnerClass annotations at all thus avoiding the trouble.

This makes me suspect that the Gradle has nothing to do with the issue and it is better to report it to the [Kotlin's bugtracker](https://youtrack.jetbrains.com/issues?q=project:%20Kotlin) instead.

**Comment by mlopatkin** [comment] 2021-06-30 15:24
Actually, the issue is already reported for Kotlin https://youtrack.jetbrains.com/issue/KT-47475. Therefore I'm closing this one.

Sorry that it took so much time to figure things out.

**Closed by mlopatkin** 2021-06-30 15:24 UTC
Labels: a:bug, in:testing-junit5
