### ISSUE TITLE
Cannot resolve recursive copy of configuration with cyclic project dependencies.

### ISSUE THREAD

**Issue by funvin** [gradle/gradle#3913] opened 2017-12-27 00:02 UTC
Here's all the context you need - 
https://discuss.gradle.org/t/cannot-resolve-recursive-copy-of-configuration-with-cyclic-dependencies-within-beforeresolve/8726
https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/46

**Comment by bmuschko** [comment] 2017-12-28 18:28
@bigdaz @melix @jjohannes Could you please comment on this?

**Comment by bigdaz** [comment] 2017-12-28 19:40
Closing as duplicate of #1638

**Closed by bigdaz** 2017-12-28 19:40 UTC
Labels: a:bug, from:contributor, in:dependency-management
