### ISSUE TITLE
FileTreeElement.getPath() returns absolute system dependent filepath

### ISSUE THREAD

**Issue by Larusso** [gradle/gradle#6656] opened 2018-09-06 14:10 UTC
With Gradle 4.10 the result of `FileTreeElement.getPath()` changed in a breaking way.

### Expected Behavior
From the method documentation:

> Returns the path of this file, relative to the root of the containing file tree. Always uses '/' as the hierarchy separator, regardless of platform file separator. Same as calling <code>getRelativePath().getPathString()</code>.

The expected String path should be relative to the `FileTree` and use `/` as file seperators even on windows environments.

### Current Behavior

With Gradle `4.10` this changed. The resulting String is an absolute system dependent path.

### Context

In my plugin I provide a default `FileCollection` which is constructed with the help of `PatternFilterable include(Spec<FileTreeElement> includeSpec);` API.
In my `Spec<FileTreeElement>` implementation I retrieve the file path with `element.getPath() and do some checks based on the asumption that it is relative and normalized.

In gradle `<= 4.9` the `FileTreeElement` was implemented as a `DefaultFileVisitDetails` which calls `getRelativePath().getPathString();` as advertised in the docs.
As of gradle `4.10` some elements are implemented as `PathBackedFileTreeElement` which implements `getPath()` as follows:

https://github.com/gradle/gradle/blob/f3079d75d8377c73b996aa19caf898ead63c21ca/subprojects/core/src/main/java/org/gradle/internal/snapshot/impl/DirectorySnapshotter.java#L304-L307

### Steps to Reproduce (for bugs)

https://github.com/wooga/atlas-build-unity in branch `gradle/issue_6656`

running the test specs from `UnityBuildPlayerTaskIntegrationSpec` will work from gradle version `3.5` - `4.9` and start to fail on `4.10`.

### Your Environment

I can verify this issue both on macOS and windows systems.

**Comment by wolfs** [comment] 2018-09-06 16:06
@Larusso Thank you for the report! That really seems to be a problem and we will fix it for 4.10.1.

I cannot reproduce the test failure for your project. I have been running:
```
GRADLE_VERSION=4.10 ./gradlew integrationTest --tests="*UnityBuildPlayerTaskIntegrationSpec*"
```

See https://scans.gradle.com/s/d5lyvljx62jke/tests

**Comment by Larusso** [comment] 2018-09-06 16:44
Ah sorry I already fixed it with the last commit.

**Comment by Larusso** [comment] 2018-09-06 17:09
I pushed a branch (`gradle/issue_6656`) to replicate the issue.

`GRADLE_VERSION=4.9 ./gradlew integrationTest --tests="*UnityBuildPlayerTaskIntegrationSpec*"` works

`GRADLE_VERSION=4.10 ./gradlew integrationTest --tests="*UnityBuildPlayerTaskIntegrationSpec*"` fails

**Comment by wolfs** [comment] 2018-09-07 12:46
Fixed via https://github.com/gradle/gradle/pull/6667.

**Closed by wolfs** 2018-09-07 12:46 UTC
Labels: a:bug, from:contributor, in:incremental-build
