### ISSUE TITLE
Circular dependency created if java subprojects are named the same

### ISSUE THREAD

**Issue by exFalso** [gradle/gradle#6615] opened 2018-09-03 17:49 UTC
### Expected Behavior

Given the following example project:

```
$ tree .
.
|-- build.gradle
|-- gradle
|   `-- wrapper
|       |-- gradle-wrapper.jar
|       `-- gradle-wrapper.properties
|-- gradlew
|-- gradlew.bat
|-- settings.gradle
|-- sub1
|   `-- a
|       `-- build.gradle
`-- sub2
    `-- a
        `-- build.gradle

6 directories, 8 files
$ cat build.gradle
allprojects {
    group 'bug'
    version '1.0-SNAPSHOT'

    repositories {
        mavenCentral()
    }
}
$ cat settings.gradle 
rootProject.name = 'example'

include 'sub1:a'
include 'sub2:a'
$ cat sub1/a/build.gradle
plugins {
    id 'java'
}
$ cat sub2/a/build.gradle
plugins {
    id 'java'
}

dependencies {
    compile project(":sub1:a")
}
```

Running
```
./gradlew sub2:a:jar
```
Should not give a circular dependency error

### Current Behavior

```
$ ./gradlew sub2:a:jar

FAILURE: Build failed with an exception.

* What went wrong:
Circular dependency between the following tasks:
:sub2:a:classes
\--- :sub2:a:compileJava
     \--- :sub2:a:jar
          \--- :sub2:a:classes (*)

(*) - details omitted (listed previously)


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

### Context

I think the issue is `sub2:a`'s *own jar* is added to its `compile` configuration instead of `sub1:a`'s, most probably because of some internal name clash.

### Steps to Reproduce (for bugs)

Just create two subprojects like that, have one depend on the other and try to invoke the jar task.

### Your Environment

 * Build scan URL: 
https://scans.gradle.com/s/qhrvftctchsxa

**Comment by atorok** [comment] 2018-09-04 04:49
same as #847 ?

**Comment by marcphilipp** [comment] 2018-09-04 07:46
Duplicate of #847

**Closed by marcphilipp** 2018-09-04 07:46 UTC

**Comment by marcphilipp** [comment] 2018-09-04 07:48
@exFalso A known workaround is to give projects in `sub2` a different group id (see https://github.com/gradle/gradle/issues/847#issuecomment-287515195).
