### ISSUE TITLE
build failed at ci but local

### ISSUE THREAD

**Issue by pipinet** [gradle/gradle#30020] opened 2024-07-25 00:58 UTC
### Current Behavior

```log
              +check | Error: Could not find or load main class .362.jar:.root..gradle.caches.modules-2.files-2.1.org.slf4j.slf4j-api.2.1.0-alpha1.4e2525fc4327cc553c52e3937427c7cf2114735f.slf4j-api-2.1.0-alpha1.jar:.root..gradle.caches.modules-2.files-2.1.org.jboss.logging.jboss-logging.3.6.0.Final.a050a37d9f104d2fda97464ccfe9f756fe79bf27.jboss-logging-3.6.0.Final.jar:.root..gradle.caches.modules-2.files-2.1.org.jboss.logging.jboss-logging-annotations.3.0.1.Final.af93bdaecf65773a3d051c2649e51e9d1ceff57d.jboss-logging-annotations-3.0.1.Final.jar:.root..gradle.caches.modules-2.files-2.1.com.google.guava.guava.33.2.1-jre.818e780da2c66c63bbb6480fef1f3855eeafa3e4.guava-33.2.1-jre.jar:.root..gradle.caches.modules-2.files-2.1.jakarta.validation.jakarta.validation-api.3.1.0.846b536eff8a32c1b91fdeb3c9c5b6c39916767d.jakarta.validation-api-3.1.0.jar:.root..gradle.caches.modules-2.files-2.1.com.fasterxml.jackson.core.jackson-core.2.17.2.969a35cb35c86512acbadcdbbbfb044c877db814.jackson-core-2.17.2.jar:.root..gradle.caches.modules-2.files-2.1.com.fasterxml.jackson.core.jackson-databind.2.17.2.e6deb029e5901e027c129341fac39e515066b68c.jackson-databind-2.17.2.jar:.root..gradle.caches.modules-2.files-2.1.com.fasterxml.jackson.core.jackson-annotations.2.17.2.147b7b9412ffff24339f8aba080b292448e08698.jackson-annotations-2.17.2.jar:.root..gradle.caches.modules-2.files-2.1.org.junit.platform.junit-platform-engine.1.10.2.d53bb4e0ce7f211a498705783440614bfaf0df2e.junit-platform-engine-1.10.2.jar:.root..gradle.caches.modules-2.files-2.1.org.junit.platform.junit-platform-commons.1.10.2.3197154a1f0c88da46c47a9ca27611ac7ec5d797.junit-platform-commons-1.10.2.jar:.root..gradle.caches.modules-2.files-2.1.org.junit.jupiter.junit-jupiter-engine.5.10.2.f1f8fe97bd58e85569205f071274d459c2c4f8cd.junit-jupiter-engine-5.10.2.jar:.root..gradle.caches.modules-2.files-2.1.org.mockito.mockito-junit-jupiter.5.11.0.8e658dd339f40305ed4293db25545b5df98b171b.mockito-junit-jupiter-5.11.0.jar:.root..gradle.caches.modules-2.files-2.1.org.junit.jupiter.junit-jupiter-api.5.10.2.fb55d6e2bce173f35fd28422e7975539621055ef.junit-jupiter-api-5.10.2.jar:.root..gradle.caches.modules-2.files-2.1.org.hamcrest.hamcrest-core.2.2.3f2bd07716a31c395e2837254f37f21f0f0ab24b.hamcrest-core-2.2.jar:.root..gradle.caches.modules-2.files-2.1.org.openjdk.jmh.jmh-generator-annprocess.1.37.da93888682df163144edf9b13d2b78e54166063a.jmh-generator-annprocess-1.37.jar:.root..gradle.caches.modules-2.files-2.1.org.openjdk.jmh.jmh-core.1.37.896f27e49105b35ea1964319c83d12082e7a79ef.jmh-core-1.37.jar:.root..gradle.caches.modules-2.files-2.1.jakarta.annotation.jakarta.annotation-api.3.0.0.54f928fadec906a99d558536756d171917b9d936.jakarta.annotation-api-3.0.0.jar:.root..gradle.caches.modules-2.files-2.1.com.google.guava.failureaccess.1.0.2.c4a06a64e650562f30b7bf9aaec1bfed43aca12b.failureaccess-1.0.2.jar:.root..gradle.caches.modules-2.files-2.1.com.google.guava.listenablefuture.9999.0-empty-to-avoid-conflict-with-guava.b421526c5f297295adef1c886e5246c39d4ac629.listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:.root..gradle.caches.modules-2.files-2.1.com.google.code.findbugs.jsr305.3.0.2.25ea2e8b0c338a877313bd4672d3fe056ea78f0d.jsr305-3.0.2.jar:.root..gradle.caches.modules-2.files-2.1.org.checkerframework.checker-qual.3.42.0.638ec33f363a94d41a4f03c3e7d3dcfba64e402d.checker-qual-3.42.0.jar:.root..gradle.caches.modules-2.files-2.1.com.google.errorprone.error_prone_annotations.2.26.1.c1fde57694bdc14e8618899aaa6e857d9465d7de.error_prone_annotations-2.26.1.jar:.root..gradle.caches.modules-2.files-2.1.org.opentest4j.opentest4j.1.3.0.152ea56b3a72f655d4fd677fc0ef2596c3dd5e6e.opentest4j-1.3.0.jar:.root..gradle.caches.modules-2.files-2.1.org.mockito.mockito-core.5.11.0.e4069fa4f4ff2c94322cfec5f2e45341c6c70aff.mockito-core-5.11.0.jar:.root..gradle.caches.modules-2.files-2.1.org.hamcrest.hamcrest.2.2.1820c0968dba3a11a1b30669bb1f01978a91dedc.hamcrest-2.2.jar:.root..gradle.caches.modules-2.files-2.1.net.sf.jopt-simple.jopt-simple.5.0.4.4fdac2fbe92dfad86aa6e9301736f6b4342a3f5c.jopt-simple-5.0.4.jar:.root..gradle.caches.modules-2.files-2.1.org.apache.commons.commons-math3.3.6.1.e4ba98f1d4b3c80ec46392f25e094a6a2e58fcbf.commons-math3-3.6.1.jar:.root..gradle.caches.modules-2.files-2.1.net.bytebuddy.byte-buddy.1.14.12.6e37f743dc15a8d7a4feb3eb0025cbc612d5b9e1.byte-buddy-1.14.12.jar:.root..gradle.caches.modules-2.files-2.1.net.bytebuddy.byte-buddy-agent.1.14.12.be4984cb6fd1ef1d11f218a648889dfda44b8a15.byte-buddy-agent-1.14.12.jar:.root..gradle.caches.modules-2.files-2.1.org.objenesis.objenesis.3.3.1049c09f1de4331e8193e579448d0916d75b7631.objenesis-3.3.jar:.root..gradle.wrapper.dists.gradle-8.9-bin.90cnw93cvbtalezasaz0blq0a.gradle-8.9.lib.plugins.junit-platform-engine-1.8.2.jar:.root..gradle.wrapper.dists.gradle-8.9-bin.90cnw93cvbtalezasaz0blq0a.gradle-8.9.lib.plugins.junit-platform-launcher-1.8.2.jar:.root..gradle.wrapper.dists.gradle-8.9-bin.90cnw93cvbtalezasaz0blq0a.gradle-8.9.lib.plugins.junit-platform-commons-1.8.2.jar
              +check | Caused by: java.lang.ClassNotFoundException: /362/jar:/root//gradle/caches/modules-2/files-2/1/org/slf4j/slf4j-api/2/1/0-alpha1/4e2525fc4327cc553c52e3937427c7cf2114735f/slf4j-api-2/1/0-alpha1/jar:/root//gradle/caches/modules-2/files-2/1/org/jboss/logging/jboss-logging/3/6/0/Final/a050a37d9f104d2fda97464ccfe9f756fe79bf27/jboss-logging-3/6/0/Final/jar:/root//gradle/caches/modules-2/files-2/1/org/jboss/logging/jboss-logging-annotations/3/0/1/Final/af93bdaecf65773a3d051c2649e51e9d1ceff57d/jboss-logging-annotations-3/0/1/Final/jar:/root//gradle/caches/modules-2/files-2/1/com/google/guava/guava/33/2/1-jre/818e780da2c66c63bbb6480fef1f3855eeafa3e4/guava-33/2/1-jre/jar:/root//gradle/caches/modules-2/files-2/1/jakarta/validation/jakarta/validation-api/3/1/0/846b536eff8a32c1b91fdeb3c9c5b6c39916767d/jakarta/validation-api-3/1/0/jar:/root//gradle/caches/modules-2/files-2/1/com/fasterxml/jackson/core/jackson-core/2/17/2/969a35cb35c86512acbadcdbbbfb044c877db814/jackson-core-2/17/2/jar:/root//gradle/caches/modules-2/files-2/1/com/fasterxml/jackson/core/jackson-databind/2/17/2/e6deb029e5901e027c129341fac39e515066b68c/jackson-databind-2/17/2/jar:/root//gradle/caches/modules-2/files-2/1/com/fasterxml/jackson/core/jackson-annotations/2/17/2/147b7b9412ffff24339f8aba080b292448e08698/jackson-annotations-2/17/2/jar:/root//gradle/caches/modules-2/files-2/1/org/junit/platform/junit-platform-engine/1/10/2/d53bb4e0ce7f211a498705783440614bfaf0df2e/junit-platform-engine-1/10/2/jar:/root//gradle/caches/modules-2/files-2/1/org/junit/platform/junit-platform-commons/1/10/2/3197154a1f0c88da46c47a9ca27611ac7ec5d797/junit-platform-commons-1/10/2/jar:/root//gradle/caches/modules-2/files-2/1/org/junit/jupiter/junit-jupiter-engine/5/10/2/f1f8fe97bd58e85569205f071274d459c2c4f8cd/junit-jupiter-engine-5/10/2/jar:/root//gradle/caches/modules-2/files-2/1/org/mockito/mockito-junit-jupiter/5/11/0/8e658dd339f40305ed4293db25545b5df98b171b/mockito-junit-jupiter-5/11/0/jar:/root//gradle/caches/modules-2/files-2/1/org/junit/jupiter/junit-jupiter-api/5/10/2/fb55d6e2bce173f35fd28422e7975539621055ef/junit-jupiter-api-5/10/2/jar:/root//gradle/caches/modules-2/files-2/1/org/hamcrest/hamcrest-core/2/2/3f2bd07716a31c395e2837254f37f21f0f0ab24b/hamcrest-core-2/2/jar:/root//gradle/caches/modules-2/files-2/1/org/openjdk/jmh/jmh-generator-annprocess/1/37/da93888682df163144edf9b13d2b78e54166063a/jmh-generator-annprocess-1/37/jar:/root//gradle/caches/modules-2/files-2/1/org/openjdk/jmh/jmh-core/1/37/896f27e49105b35ea1964319c83d12082e7a79ef/jmh-core-1/37/jar:/root//gradle/caches/modules-2/files-2/1/jakarta/annotation/jakarta/annotation-api/3/0/0/54f928fadec906a99d558536756d171917b9d936/jakarta/annotation-api-3/0/0/jar:/root//gradle/caches/modules-2/files-2/1/com/google/guava/failureaccess/1/0/2/c4a06a64e650562f30b7bf9aaec1bfed43aca12b/failureaccess-1/0/2/jar:/root//gradle/caches/modules-2/files-2/1/com/google/guava/listenablefuture/9999/0-empty-to-avoid-conflict-with-guava/b421526c5f297295adef1c886e5246c39d4ac629/listenablefuture-9999/0-empty-to-avoid-conflict-with-guava/jar:/root//gradle/caches/modules-2/files-2/1/com/google/code/findbugs/jsr305/3/0/2/25ea2e8b0c338a877313bd4672d3fe056ea78f0d/jsr305-3/0/2/jar:/root//gradle/caches/modules-2/files-2/1/org/checkerframework/checker-qual/3/42/0/638ec33f363a94d41a4f03c3e7d3dcfba64e402d/checker-qual-3/42/0/jar:/root//gradle/caches/modules-2/files-2/1/com/google/errorprone/error_prone_annotations/2/26/1/c1fde57694bdc14e8618899aaa6e857d9465d7de/error_prone_annotations-2/26/1/jar:/root//gradle/caches/modules-2/files-2/1/org/opentest4j/opentest4j/1/3/0/152ea56b3a72f655d4fd677fc0ef2596c3dd5e6e/opentest4j-1/3/0/jar:/root//gradle/caches/modules-2/files-2/1/org/mockito/mockito-core/5/11/0/e4069fa4f4ff2c94322cfec5f2e45341c6c70aff/mockito-core-5/11/0/jar:/root//gradle/caches/modules-2/files-2/1/org/hamcrest/hamcrest/2/2/1820c0968dba3a11a1b30669bb1f01978a91dedc/hamcrest-2/2/jar:/root//gradle/caches/modules-2/files-2/1/net/sf/jopt-simple/jopt-simple/5/0/4/4fdac2fbe92dfad86aa6e9301736f6b4342a3f5c/jopt-simple-5/0/4/jar:/root//gradle/caches/modules-2/files-2/1/org/apache/commons/commons-math3/3/6/1/e4ba98f1d4b3c80ec46392f25e094a6a2e58fcbf/commons-math3-3/6/1/jar:/root//gradle/caches/modules-2/files-2/1/net/bytebuddy/byte-buddy/1/14/12/6e37f743dc15a8d7a4feb3eb0025cbc612d5b9e1/byte-buddy-1/14/12/jar:/root//gradle/caches/modules-2/files-2/1/net/bytebuddy/byte-buddy-agent/1/14/12/be4984cb6fd1ef1d11f218a648889dfda44b8a15/byte-buddy-agent-1/14/12/jar:/root//gradle/caches/modules-2/files-2/1/org/objenesis/objenesis/3/3/1049c09f1de4331e8193e579448d0916d75b7631/objenesis-3/3/jar:/root//gradle/wrapper/dists/gradle-8/9-bin/90cnw93cvbtalezasaz0blq0a/gradle-8/9/lib/plugins/junit-platform-engine-1/8/2/jar:/root//gradle/wrapper/dists/gradle-8/9-bin/90cnw93cvbtalezasaz0blq0a/gradle-8/9/lib/plugins/junit-platform-launcher-1/8/2/jar:/root//gradle/wrapper/dists/gradle-8/9-bin/90cnw93cvbtalezasaz0blq0a/gradle-8/9/lib/plugins/junit-platform-commons-1/8/2/jar

              +check | > Task :basic-tree:test FAILED
              +check |

              +check | FAILURE: Build failed with an exception.
              +check |

              +check | * What went wrong:

              +check | Execution failed for task ':basic-tree:test'.

              +check | > Process 'Gradle Test Executor 1' finished with non-zero exit value 1
              +check |

              +check | * Try:

              +check | > Run with --info or --debug option to get more log output.
              +check |
              +check | > Run with --scan to get full insights.
              +check |
              +check | > Get more help at https://help.gradle.org.
              +check |

              +check | * Exception is:

              +check | org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':basic-tree:test'.

              +check | 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:130)

              +check | 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:293)

              +check | 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:128)

              +check | 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:116)
              +check | 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)

              +check | 	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)

              +check | 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)

              +check | 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)

              +check | 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)

              +check | 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
              +check | 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)

              +check | 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)

              +check | 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)

              +check | 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
              +check | 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
              +check | 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
              +check | 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
              +check | 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
              +check | 	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
              +check | 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
              +check | 	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
              +check | 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:331)
              +check | 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:318)
              +check | 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.lambda$execute$0(DefaultTaskExecutionGraph.java:314)
              +check | 	at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:85)
              +check | 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:314)
              +check | 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
              +check | 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:459)
              +check | 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:376)
              +check | 	at org.gradle.execution.plan.DefaultPlanExecutor.process(DefaultPlanExecutor.java:111)
              +check | 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.executeWithServices(DefaultTaskExecutionGraph.java:138)

              +check | 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.execute(DefaultTaskExecutionGraph.java:123)
              +check | 	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:35)
              +check | 	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:51)
              +check | 	at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor$ExecuteTasks.call(BuildOperationFiringBuildWorkerExecutor.java:54)
              +check | 	at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor$ExecuteTasks.call(BuildOperationFiringBuildWorkerExecutor.java:43)
              +check | 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
              +check | 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
              +check | 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)

              +check | 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
              +check | 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
              +check | 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)

              +check | 	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
              +check | 	at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor.execute(BuildOperationFiringBuildWorkerExecutor.java:40)
              +check | 	at org.gradle.internal.build.DefaultBuildLifecycleController.lambda$executeTasks$10(DefaultBuildLifecycleController.java:313)

              +check | 	at org.gradle.internal.model.StateTransitionController.doTransition(StateTransitionController.java:266)
              +check | 	at org.gradle.internal.model.StateTransitionController.lambda$tryTransition$8(StateTransitionController.java:177)
              +check | 	at org.gradle.internal.work.DefaultSynchronizer.withLock(DefaultSynchronizer.java:44)
              +check | 	at org.gradle.internal.model.StateTransitionController.tryTransition(StateTransitionController.java:177)
              +check | 	at org.gradle.internal.build.DefaultBuildLifecycleController.executeTasks(DefaultBuildLifecycleController.java:304)
              +check | 	at org.gradle.internal.build.DefaultBuildWorkGraphController$DefaultBuildWorkGraph.runWork(DefaultBuildWorkGraphController.java:220)
              +check | 	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:267)
              +check | 	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:131)
              +check | 	at org.gradle.composite.internal.DefaultBuildController.doRun(DefaultBuildController.java:181)

              +check | 	at org.gradle.composite.internal.DefaultBuildController.access$000(DefaultBuildController.java:50)
              +check | 	at org.gradle.composite.internal.DefaultBuildController$BuildOpRunnable.lambda$run$0(DefaultBuildController.java:198)
              +check | 	at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:85)
              +check | 	at org.gradle.composite.internal.DefaultBuildController$BuildOpRunnable.run(DefaultBuildController.java:198)
              +check | 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
              +check | 	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:48)
              +check | Caused by: org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 1' finished with non-zero exit value 1
              +check | 	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:442)
              +check | 	at org.gradle.process.internal.worker.DefaultWorkerProcess.onProcessStop(DefaultWorkerProcess.java:146)
              +check | 	at org.gradle.process.internal.worker.DefaultWorkerProcess.access$000(DefaultWorkerProcess.java:43)
              +check | 	at org.gradle.process.internal.worker.DefaultWorkerProcess$1.executionFinished(DefaultWorkerProcess.java:99)
              +check | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
              +check | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
              +check | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
              +check | 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
              +check | 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
              +check | 	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
              +check | 	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:268)
              +check | 	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:170)
              +check | 	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:148)
              +check | 	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
              +check | 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:92)
              +check | 	at jdk.proxy1/jdk.proxy1.$Proxy141.executionFinished(Unknown Source)
              +check | 	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:221)
              +check | 	at org.gradle.process.internal.DefaultExecHandle.finished(DefaultExecHandle.java:381)
              +check | 	at org.gradle.process.internal.ExecHandleRunner.completed(ExecHandleRunner.java:134)
              +check | 	at org.gradle.process.internal.ExecHandleRunner.lambda$run$2(ExecHandleRunner.java:97)
              +check | 	at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:85)
              +check | 	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:95)
              +check | 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
              +check | 	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:48)

              +check | Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.



              +check | You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

              +check | For more on this, please refer to https://docs.gradle.org/8.9/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.


              +check | BUILD FAILED10 actionable tasks: 10 executed in 2m 52s
              +check |
              +check | earthly debugger | Command /bin/sh -c './gradlew :basic-tree:test --tests "com.qwlabs.tree.LocationComparatorTest" --stacktrace --no-parallel --no-daemon' failed with exit code 1
              +check | Entering interactive debugger
```

### Expected Behavior

build succeed as local

### Steps to Reproduce

# clone code
```shell
git clone git@github.com:qwlabs/doraemon.git
```
# will succeed at local
```shell
./gradlew :basic-tree:test  --tests "com.qwlabs.tree.LocationComparatorTest" --stacktrace --no-parallel --no-daemon
```
# will failed at earthly
install earthly guide at [earthly](https://earthly.dev/get-earthly)

```shell
earthly --allow-privileged --interactive +ci-check --PIPELINE_ID=362
```
# will failed at github actions 
https://github.com/qwlabs/doraemon/actions
<img width="1515" alt="image" src="https://github.com/user-attachments/assets/7579cda5-4ad6-45ed-93f6-7e3084077608">

### Gradle version

8.7,8.8,8.9

### Your Environment (optional)

# java version
```log
java 17.0.12 2024-07-16 LTS
Java(TM) SE Runtime Environment Oracle GraalVM 17.0.12+8.1 (build 17.0.12+8-LTS-jvmci-23.0-b41)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 17.0.12+8.1 (build 17.0.12+8-LTS-jvmci-23.0-b41, mixed mode, sharing)
```

# gradle version
```log
------------------------------------------------------------
Gradle 8.9
------------------------------------------------------------

Build time:    2024-07-11 14:37:41 UTC
Revision:      d536ef36a19186ccc596d8817123e5445f30fef8

Kotlin:        1.9.23
Groovy:        3.0.21
Ant:           Apache Ant(TM) version 1.10.13 compiled on January 4 2023
Launcher JVM:  17.0.12 (Oracle Corporation 17.0.12+8-LTS-jvmci-23.0-b41)
Daemon JVM:    /Users/pipinet/.sdkman/candidates/java/17.0.12-graal (no JDK specified, using current Java home)
OS:            Mac OS X 14.5 x86_64
```

**Comment by alllex** [comment] 2024-07-25 13:18
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

If the issue is only reproducible on your CI, but not locally, please check the differences in the environment

**Closed by alllex** 2024-07-25 13:18 UTC
Labels: a:bug, to-triage

**Comment by pipinet** [comment] 2024-07-28 01:11
@alllex 
you can run earthly command at local 
```bash
earthly --allow-privileged --interactive +ci-check --PIPELINE_ID=362
```
