### ISSUE TITLE
Gradle 8.2 to support projects w/ JDK 17 when multi-release JARs offer JDK-21 class files

### ISSUE THREAD

**Issue by mmoayyed** [gradle/gradle#25523] opened 2023-06-27 12:30 UTC
### Expected Behavior

Gradle should support multi-release JARs that offer support for JDK 21. 

### Current Behavior (optional)

Building a project with JDK 17 that contains a multi-release JAR offering support for JDK 21 results in:

```
A problem occurred configuring root project 'cas'.
> java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to create Jar file /home/runner/.gradle/caches/jars-9/e68c7e667170499f021871f6fff47fa2/spring-core-6.1.0-M1.jar.
```

This is seen with Gradle 8.2 RC2 and JDK 17. 

### Context

Testing projects that offer JDK-21 support via MR JARs is at the moment not possible given the above error. At a minimum, I suspect Gradle ought to switch to ASM 9.5: https://asm.ow2.io/versions.html

The only viable alternative is to downgrade the specific JAR version that offers JDK 21 support (In this case going from Spring 6.1.x to 6.0.x)  Please note that force-downgrading the version using Gradle's dependency management and resolution is not possible; the crash above happens very early on before Gradle has had a chance to load the relevant rules.

**Comment by jbartok** [comment] 2023-06-28 12:07
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/25434

Please add your use case and 👍 to that issue.

**Closed by jbartok** 2023-06-28 12:07 UTC
Labels: a:feature, to-triage
