### ISSUE TITLE
Gradle queries tasks' input getters after the task action when using --rerun-tasks

### ISSUE THREAD

**Issue by ducrohet** [gradle/gradle#2401] opened 2017-07-06 19:18 UTC
Due to some aggressive clean up on our side that ended up generating an NPE, we noticed that if you run with `--rerun-tasks` the getters of a task can be queried *after* the task action has run. They are also queried before the task is run. This seems unnecessary and inefficient. This only happens with the `--rerun-tasks` options

Repro steps:

- Git clone the `android-30` branch from https://github.com/gradle/perf-android-large
- update android plugin to 3.0.0-alpha5 (alpha1 is expired), and wrapper to 4.1-M1
- run `./gradlew :fratry:linotype:packageDebugResources`
- run `./gradlew :fratry:linotype:packageDebugResources --rerun-tasks`

This will fail with an NPE because we reset task fields to `null` after running to free memory, however one of the fields is needed by a getter annotated with `@InputFiles`

**Comment by lptr** [comment] 2017-07-07 14:32
Can you please post the stacktrace for the NPE you get?

**Comment by lptr** [comment] 2017-07-07 14:34
In general we don't recommend changing your inputs during execution. We'd like to add more validation in the future to prevent users from doing this, because mutable inputs is one of the main causes of caching problems.

**Comment by ducrohet** [comment] 2017-07-07 16:03
Right, we don't want to change our inputs either. This is a case where the input was dynamically computed from a complex data structure we wanted to get rid of after task execution to free memory. In our next release we have fixed this by having the inputs by stored in a field we don't reset to null.

Here's the trace:

java.lang.NullPointerException
        at com.android.build.gradle.tasks.MergeResources.getSourceFolderInputs(MergeResources.java:544)
        at com.android.build.gradle.tasks.MergeResources_Decorated.getSourceFolderInputs(Unknown Source)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.TaskPropertyInfo$4.create(TaskPropertyInfo.java:99)
        at org.gradle.util.SingleMessageLogger.whileDisabled(SingleMessageLogger.java:217)
        at org.gradle.api.internal.project.taskfactory.TaskPropertyInfo.getValue(TaskPropertyInfo.java:97)
        at org.gradle.api.internal.project.taskfactory.TaskClassValidator$FutureValue.call(TaskClassValidator.java:65)
        at org.gradle.util.GUtil.uncheckedCall(GUtil.java:418)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.doResolve(DefaultFileCollectionResolveContext.java:124)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.resolveAsFileCollections(DefaultFileCollectionResolveContext.java:93)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext$FileCollectionConverter.convertInto(DefaultFileCollectionResolveContext.java:158)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.doResolve(DefaultFileCollectionResolveContext.java:110)
        at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.resolveAsFileCollections(DefaultFileCollectionResolveContext.java:93)
        at org.gradle.api.internal.file.CompositeFileCollection.getSourceCollections(CompositeFileCollection.java:172)
        at org.gradle.api.internal.file.CompositeFileCollection.visitRootElements(CompositeFileCollection.java:184)
        at org.gradle.api.internal.changedetection.state.AbstractFileCollectionSnapshotter.snapshot(AbstractFileCollectionSnapshotter.java:51)
        at org.gradle.api.internal.changedetection.state.DefaultGenericFileCollectionSnapshotter.snapshot(DefaultGenericFileCollectionSnapshotter.java:36)
        at org.gradle.api.internal.changedetection.rules.AbstractNamedFileSnapshotTaskStateChanges.buildSnapshots(AbstractNamedFileSnapshotTaskStateChanges.java:91)
        at org.gradle.api.internal.changedetection.rules.AbstractNamedFileSnapshotTaskStateChanges.<init>(AbstractNamedFileSnapshotTaskStateChanges.java:58)
        at org.gradle.api.internal.changedetection.rules.InputFilesTaskStateChanges.<init>(InputFilesTaskStateChanges.java:29)
        at org.gradle.api.internal.changedetection.rules.TaskUpToDateState.<init>(TaskUpToDateState.java:60)
        at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.getStates(DefaultTaskArtifactStateRepository.java:178)
        at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.afterTask(DefaultTaskArtifactStateRepository.java:168)
        at org.gradle.api.internal.changedetection.changes.ShortCircuitTaskArtifactStateRepository$RerunTaskArtifactState.afterTask(ShortCircuitTaskArtifactStateRepository.java:107)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:243)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:236)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:225)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)

**Comment by lptr** [comment] 2017-07-10 09:08
I did some looking into this, and it's not a bug as such. What happens is in normal execution we snapshot the task's inputs and outputs before execution to figure out if the task is already `UP-TO-DATE`. When we also snapshot it after execution, we don't re-snapshot the inputs, because we expect them to be unchanged anyway.

However, when the task is executed with `--rerun-tasks`, we don't snapshot its state before execution, because we don't care about it's up-to-date state. This means that in the rerun case we first get to snapshot the inputs _after_ execution.

Let's figure out what we can do about this. The general direction we'd like to go is to prevent tasks from changing their inputs altogether, though this is hard to do in some cases.

One thing we could do is to capture the finalization of the task's inputs as a thing, but I'm not completely sure that's something common enough to support.

Another approach would be to store the memory-heavy inputs in a service independent of the task itself, and only refer to the inputs from the task. The data could then be cleaned up using a [finalizer task](https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:finalizer_tasks) perhaps.

**Comment by lptr** [comment] 2017-07-12 07:02
This has been fixed in https://github.com/gradle/gradle/pull/2439 and will be delivered in 4.1.

**Closed** 2017-07-12 07:03 UTC
Labels: a:bug, from:contributor, in:core
