### ISSUE TITLE
Add a lazy way to set publishing maven repository directory

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#25850] opened 2023-07-20 23:22 UTC
### Expected Behavior

```
publishing {
    repositories {
        maven {
          someNewApi.set(layout.buildDirectory.dir("repos/releases"))
          ...
```

A way to set maven publishing directory in a lazy way so that this directory is not resolved at until the task to publish is run or input checked.

### Current Behavior (optional)

[Gradle publishing docs](https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:repositories) suggest to use:
```
publishing {
    repositories {
        maven {
            // change to point to your repo, e.g. http://my.org/repo
            url = uri(layout.buildDirectory.dir("repo"))
        }
    }
}
```

However, `Project.uri` causes the type to be resolved right away, thus if the buildDirectory value is changed after this code is executed, the value set is obsolete.

### Context

Attempting to write publishing code for our libraries that is not sensitive to when the `buildDirectory` is changed.

**Comment by gabrielittner** [comment] 2023-07-21 05:20
Unless you want an API specifically for setting a directory this is a duplicate of https://github.com/gradle/gradle/issues/22779

**Comment by hfhbd** [comment] 2023-07-21 08:33
Maybe duplicate of https://github.com/gradle/gradle/issues/22779?

**Closed** 2023-07-24 08:29 UTC
Labels: a:feature, to-triage
