### ISSUE TITLE
Make outgoing configuration capability registration lazy

### ISSUE THREAD

**Issue by oesolutions** [gradle/gradle#25650] opened 2023-07-06 17:40 UTC
### Expected Behavior

As a plugin author I should be able to configure the capabilities of an outgoing configuration using lazy values. The current, documented, acceptable notations are `String` or `Map<String, String>`, neither of which operate in a lazy manner.
For example, potentially support `Map<String, Provider<String>>`:
```
Map<String, Provider<String>> cap = new HashMap<>();
cap.put( "group", project.getProviders().provider( () -> project.getGroup().toString() ) );
cap.put( "name", project.getProviders().provider( () -> project.getName() + "-" + myThing.getName() ) );
cap.put( "version", project.getProviders().provider( () -> project.getVersion().toString() ) );
someConfiguration.getOutgoing().capability( cap );
```

### Context

Currently my plugin is using the internal `org.gradle.internal.component.external.model.ProjectDerivedCapability` class in a similar fashion as the JVM plugins. I am not using the `registerFeature` API provided by the jvm plugins because I am not writing a jvm based plugin, but am doing something similar.

```
someConfiguration.getOutgoing().capability( new ProjectDerivedCapability( project, myThing.getName() ) );
```

I should not have to use these internals.

**Comment by octylFractal** [comment] 2024-01-08 18:03
Duplicate of #26163

**Closed by octylFractal** 2024-01-08 18:03 UTC
Labels: in:publishing-plugins, a:feature, in:provider-api
