### ISSUE TITLE
compileTestJava fails with an Interface with nested classes

### ISSUE THREAD

**Issue by LionH** [gradle/gradle#11345] opened 2019-11-12 19:10 UTC
We work in a Gradle Multi Project and we enabled cache. We got an exception when compiling test class that points to an Interface with nested classes. When using flag --no-build-cache, the problem disappears.
`Build cache key for task ':backend-services:core-services:rpc-permissions-client:compileTestJava' is 77fd2efe8b977c5dd455f03c910801a9
root-project/backend-services/core-services/rpc-permissions-client/src/test/java/com/####/permissions/client/MockPermissionClient.java:15: error: cannot find symbol
public class MockPermissionClient implements PermissionService {`
`                                             ^`
`symbol: class PermissionService
root-project/backend-services/core-services/rpc-permissions-client/src/test/java/com/####/permissions/client/MockPermissionClient.java:17: error: cannot find symbol
    public ListenableFuture<ClientResult<CheckActionResults>> checkActionsAsync(UUID userUUID, Collection<CheckUserPermission> entries) {`
`                                         ^`
It can't find PermissionService that is the class in src/main/java of the same subproject
PermissionService looks like that:

`
    
        public interface PermissionService {

        .....

           // user permissions checking
        class Unit {
            private final PermissionUnit permissionUnit;
            private final UUID uuid;

            public Unit(PermissionUnit permissionUnit, UUID uuid) {
                this.permissionUnit = permissionUnit;
                this.uuid = uuid;
            }

            public PermissionUnit getPermissionUnit() {
                return permissionUnit;
            }

            public UUID getUuid() {
                return uuid;
            }

            @Override
            public boolean equals(Object o) {
                if (this == o) return true;
                if (o == null || getClass() != o.getClass()) return false;
                Unit unit = (Unit) o;
                return permissionUnit == unit.permissionUnit &&
                        Objects.equals(uuid, unit.uuid);
            }

            @Override
            public int hashCode() {
                return Objects.hash(permissionUnit, uuid);
            }
        }

        .....
        
    }
`
---
cc: @gradle/build-cache

**Comment by wolfs** [comment] 2019-11-18 10:09
@LionH Thank you for reporting!

This is a duplicate of https://github.com/gradle/gradle/issues/7363:
The incremental compiler tries to infer the name of the `class` files from the name of the `java` files. You need to move the package private class to its own file for incremental compilation to work correctly - or disable incremental compilation.

**Closed by wolfs** 2019-11-18 10:09 UTC
Labels: @build-cache, from:contributor
