### ISSUE TITLE
Artifact view contains wrong file dependency in Android project

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#16962] opened 2021-04-24 08:49 UTC
### Expected Behavior
File dependencies should only be part of the artifact view they contain

### Current Behavior
File dependencies are part of artifact views they don't contain

### Context
This affects Android projects with multiple variants (aka debug, release) which use different file dependencies for the different variants. Depending on the order of which e.g. `compile{Release,Debug}Kotlin` or `merge{Release,Debug}NativeLibs` is being executed, the classpath of those tasks wrongly contains the debug or release file dependency.

This works for me in Gradle 6.8 but breaks in Gradle 7.0.

### Steps to Reproduce 
`settings.gradle`:
```gradle
pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "reproduces-file-deps"
```

`build.gradle`:
```gradle
plugins {
    id 'com.android.library' version '4.2.0-beta06'
    id 'org.jetbrains.kotlin.android' version '1.4.32'
}


TaskProvider<Jar> jarRelease = tasks.register("myJarRelease", Jar) {
    destinationDirectory = file("build/release/jar_output")
    archiveFileName = "another_one1.jar"
    archiveVersion = ""
}

dependencies {
    releaseImplementation files(jarRelease.flatMap { it.archiveFile })
}

TaskProvider<Jar> jarDebug = tasks.register("myJarDebug", Jar) {
    destinationDirectory = file("build/debug/jar_output")
    archiveFileName = "another_one2.jar"
    archiveVersion = ""
}

dependencies {
    debugImplementation files(jarDebug.flatMap { it.archiveFile })
}

android {
    compileSdk 30

    defaultConfig {
        minSdk 21
        targetSdk 30
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

Attribute<String> ARTIFACT_TYPE = Attribute.of("artifactType", String.class)
["debug", "release"].each { variant ->
    tasks.register("${variant}Consume") {
        def view = configurations."${variant}RuntimeClasspath".incoming
            .artifactView { config->
                config.attributes {
                    it.attribute(ARTIFACT_TYPE, "android-java-res")
                }
            }.artifacts.artifactFiles
        it.inputs.files(view)
        doLast {
            println "${variant}ArtifactView contains build/debug/jar_output/*: ${view.files.any { it.absolutePath.contains('build/debug/jar_output')}}"
            println "${variant}ArtifactView contains build/release/jar_output/*: ${view.files.any { it.absolutePath.contains('build/release/jar_output')}}"
            println "variant consume"
        }
    }
}
```

When running
```
gradle clean debugConsume releaseConsume
```
Then you have this output:
```
:clean
:myJarDebug
:debugConsume
debugArtifactView contains build/debug/jar_output/*: true
debugArtifactView contains build/release/jar_output/*: false
variant consume
:myJarRelease
:releaseConsume
releaseArtifactView contains build/debug/jar_output/*: true
releaseArtifactView contains build/release/jar_output/*: false
variant consume
```

So you see that both artifact views contain the debug jar and none contains the release jar. There is also a deprecations warning about a missing task dependency, see the build scan for more details.

### Your Environment
Build scan URL: https://ge.gradle.org/s/4ubrszv3nveuy/console-log#L11

**Comment by wolfs** [comment] 2021-04-24 08:51
Here is a zip of the reproducer
[reproducer-file-deps-16962.zip](https://github.com/gradle/gradle/files/6369272/reproducer-file-deps-16962.zip)

**Comment by rieske** [comment] 2021-04-27 08:09
Initial investigation revealed that this problem is present both in Gradle `6.8` line and earlier versions (tested down to `6.5`).
The only change in `7.0` around this problem is a warning emitted about disabled optimizations when this problem manifests itself.

Initially, a few times I got the correct result with `6.8` line, but repeated invocations always started yielding the wrong result (always debug jar present, and no release jar in the artifact view) which makes me think that there might be a race condition involved.

This is a legitimate problem that should be fixed, but it is not a `7.0` regression.

**Comment by liutikas** [comment] 2021-04-27 23:51
I'd argue it is at minimum an unexpected behavior change. We are logging a warning `Reason: Task ':releaseConsume' uses this output of task ':myJarDebug' without declaring an explicit or implicit dependency.` which cannot be fixed by Gradle user as it is a bug in Gradle core. In addition to that, we also make these tasks not up to date (it used to be in 6.*). This affects a number of Android developers that use Gradle Plugins generating file dependencies (shadow, jarjar, square/wire, google/proto, etc).

**Comment by jjohannes** [comment] 2021-05-11 14:40
This is a real bug, which only happens when two files involved in an artefact transform are exactly the same (regarding their content). It also concerns artefact views without "real" transforms, because when Gradle filters in a view, all files go through the "identity transform" in the implementation.

The problem lays here:
https://github.com/gradle/gradle/blob/754fac1f2667b5201a3ae8a84a79cb0cc126ddd3/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformerInvocationFactory.java#L229

`inputArtifactFingerprinter.normalizePath(inputArtifactSnapshot)` always gives the empty String `""` if we are on a classpath.  See:
https://github.com/gradle/gradle/blob/eca186aede4e0617ab92c20ef0cc52778f97fe65/subprojects/normalization-java/src/main/java/org/gradle/internal/fingerprint/classpath/impl/ClasspathFingerprintingStrategy.java#L129-L131

Consequently the name or path of a file does not matter. In the reproducer, both `jar` files are empty and are the same from the caches perspective. So it might happen that the wrong file is returned as a cached transformation result.

I don't know if this should be fixed in the `DefaultTransformerInvocationFactory` (for example doing `return inputArtifactSnapshot.getAbsolutePath()` fixes the issue) or in another place. @gradle/execution can you please take this over or advice.

**Comment by jjohannes** [comment] 2021-05-17 10:13
Possibly related issue with the mentioned identity transform: https://github.com/gradle/gradle/issues/15647

**Comment by jjohannes** [comment] 2021-05-26 09:08
Closing as this was an issue with the _identity transform_ in AGP.

**Comment by gavra0** [comment] 2021-05-26 09:17
I'm not sure if this should be closed, there are other transforms that aren't using absolute path sensitivity that may output the input file. With Gradle 7.0 this is an issue because of task dependency validation that prevents task from being up-to-date and running in parallel.

**Comment by wolfs** [comment] 2021-06-11 08:16
We're probably going to fix this via https://github.com/gradle/gradle/pull/17392.

**Closed** 2021-06-16 15:19 UTC
Labels: in:artifact-transforms
