### ISSUE TITLE
publishing extension is very ordering sensitive

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#5142] opened 2018-04-23 18:04 UTC
I'm not sure this is intended, so I post it here for you to know.
If this is expected, please just close it.

The `publishing` extension is heavily dependent on ordering of stuff in your Gradle scripts.
I have two examples, for both it complains that the `publishing` extension cannot be modified after it was accessed.

---
The first example is with the new publication signing capabilities in 4.8.
If you put the `signing { sign publishing.publications }` anywhere before the publications are configuration completely, including in plugins, it fails.

---
The second example even happens with 4.6 (didn't test any other version besides 4.6 and a 4.8 nightly).
I wanted to do something similar to
```groovy
task compileJava9(type: JavaCompile, dependsOn: sourceSets.main.runtimeClasspath) {
    description 'Compiles main Java 9 source'
    source sourceSets.main.java
    source 'src/main/java9/'
    classpath = files()
    destinationDir = file("$buildDir/classes/java9/main")
    sourceCompatibility = 9
    targetCompatibility = 9
    options.compilerArgs << '--module-path' << sourceSets.main.runtimeClasspath.asPath
}
```

But then again I got the error and instead needed to put the last line into an `afterEvaluate` block or move that configuration after the publishing configuration, where especially in this case I don't see the direct relationship.

**Comment by oehme** [comment] 2018-04-23 21:29
Duplicate of #4997

**Closed by oehme** 2018-04-23 21:29 UTC
