### ISSUE TITLE
Unable to resolve Groovy classes from project dependency when using java-library plugin

### ISSUE THREAD

**Issue by LittleMikeDev** [gradle/gradle#6457] opened 2018-08-21 18:52 UTC
### Expected Behavior
When declaring an `implementation` or `testImplementation` dependency on a Groovy project, all that project's Groovy classes should be available during compilation, as when using `compile` or `testCompile`, or with Java classes

### Current Behavior
When compiling code that references a groovy class from an `implementation` or `testImplementation` project dependency, an "unable to resolve class XXX" error is raised

### Context
Just trying to use some groovy code from a library module in another module. Works fine for Java classes. It also works fine if I stop using the `java-library` plugin and switch to `compile` and `testCompile` dependencies

### Steps to Reproduce (for bugs)
Checkout project: https://github.com/LittleMikeDev/java-library-groovy-bug
Run ./gradlew

Note:
* The import of AJavaInterface works fine
* Removing the `java-library` plugin, and changing the project dependency to `compile` instead of `implementation` fixes the issue. Just changing the dependency type does not work, the `java-library` plugin must be removed for the bug to go away.

### Your Environment

Tried with Groovy versions 2.5.2, 2.4.15, 2.3.11
Tried with Gradle versions 4.10-RC2, 4.9, 4.8.1, 4.7

 * Build scan URL: https://scans.gradle.com/s/twlybo5dfpriu

**Comment by lacasseio** [comment] 2018-09-01 17:30
I'm seeing this a well. It seems the dependencies is pointing to `[...]/build/classes/java/main` regardless when using `java-library`. Using only the plugin `groovy` will cause the dependency to point at the jar. It would seem that using both plugins cause unexpected behavior.

**Comment by bigdaz** [comment] 2018-10-16 00:42
Thanks for your detailed report. This is a known issue, as documented here: https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_known_issues_compat

However, I couldn't find a matching GitHub issue to track this issue.  I've created #7398, and will close this issue as a duplicate of the new issue.

**Closed by bigdaz** 2018-10-16 00:42 UTC
Labels: in:dependency-management
