### ISSUE TITLE
Jar task returns wrong output in a Multiplatform project

### ISSUE THREAD

**Issue by yschimke** [gradle/gradle#19449] opened 2021-12-29 19:18 UTC
Related to https://github.com/palantir/gradle-graal/issues/129 and maybe https://github.com/gradle/gradle/issues/8113

emulator-tools-jvm-kmp-f632f62-dirty.jar
emulator-tools-kmp-f632f62-dirty.jar

### Expected Behavior

1) ./gradlew installDist should contain the main jar file.

2) The palantir graal plugin should run and find the jar file

### Current Behavior

The instalDist output is missing the main jar file.

graal plugin fails with a missing jar file.

### Context

Output from jar task shows the wrong output

### Steps to Reproduce 

`println(project.tasks.getByName("jar").outputs.files.singleFile)` -> `.../emulator-tools/build/libs/emulator-tools-kmp-f632f62-dirty.jar`

This does not exist and is missing jvm in the filename.

### Your Environment

Build scan URL:

**Comment by yschimke** [comment] 2022-01-01 21:30
I suspect that it's a broken assumption of using the `jar` task is the issue.  Is there guidance on this?

```
println(project.tasks.getByName("jar").outputs.files.singleFile) -> certifikit-cli-0.3.0-SNAPSHOT.jar
println(project.tasks.getByName("jvmJar").outputs.files.singleFile) -> certifikit-cli-jvm-0.3.0-SNAPSHOT.jar
```

**Comment by jbartok** [comment] 2022-01-12 09:56
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

This issue will be closed after 7 days, unless you can provide more information.

**Comment by yschimke** [comment] 2022-01-12 11:29
I'll see if I get a chance to open a reproduction this week.  The issue linked in the description https://github.com/palantir/gradle-graal/issues/129 has a lot more context.

Assuming there is no bug, and that gradle is correct here, but that plugins that currently use the Jar task, now need to also check for JvmJar, is there documentation on the behaviour here? It seems to be affecting multiple plugins when trying to use them with a multiplatform build.

**Comment by yschimke** [comment] 2022-01-15 13:37
An example branch with a failing build

https://github.com/yschimke/emulator-tools/pull/3/files

```
$ ./gradlew nativeImage
A problem was found with the configuration of task ':nativeImage' (type 'NativeImageTask').
  - In plugin 'com.palantir.graal' type 'com.palantir.gradle.graal.NativeImageTask' property 'jarFiles' specifies file '/Users/yschimke/IdeaProjects/emulator-tools/build/libs/emulator-tools-0.5.0-SNAPSHOT.jar' which doesn't exist.
```

Presumably a bug in the https://github.com/palantir/gradle-graal/issues/129 plugin, but if so it would be good to have documented behaviour, or preferably a fix in gradle to make this continue working.

**Comment by ljacomet** [comment] 2022-01-19 10:01
My understanding is that there is nothing wrong in Gradle itself but rather some strong assumptions in the Palantir Graal plugin that are broken with the multiplatform Kotlin one.

Given this, I will close this issue. We can consider re-opening if more specific information is provided that point at a Gradle issues.

**Closed by ljacomet** 2022-01-19 10:01 UTC
Labels: a:bug, to-triage

**Comment by yschimke** [comment] 2022-01-19 10:49
Yep - it seems like a common problem.  Hence my question

> is there documentation on the behaviour here? It seems to be affecting multiple plugins when trying to use them with a multiplatform build.

Is there a clean way to do this? Or should every plugin using jar output, check specifically for Jar and JvmJar?

**Comment by ljacomet** [comment] 2022-01-19 11:28
A plugin should not assume the main artifact of a project is the output of the default `jar` task but instead allow this to be configurable.
Of course the plugin could wire itself to the `jar` task by convention, allowing an override when necessary.

The issue is that your check is not limited to `jar` and `jvmJar`, it could include `bootJar` for Spring Boot, and some other for different setups.

**Comment by yschimke** [comment] 2022-01-19 12:27
OK, so default to jar, but always allow overriding.
