### ISSUE TITLE
Artifact transforms with file-based deps fail

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#15647] opened 2020-12-23 11:21 UTC
Using [this project](https://github.com/gradle/gradle/files/5734822/repro.1.zip) and running `./gradlew assembleDeb assemAndTest` fails with 6.8-rc-3 and it passes with 6.8-rc-1. The failure is:
```
          > Type android.support.v8.renderscript.Allocation$1 is defined multiple times:
renderscriptNdk/build/intermediates/external_file_lib_dex_archives/debug/0_renderscript-v8.jar:classes.dex,
renderscriptNdk/build/intermediates/external_file_lib_dex_archives/debug/1_renderscript-v8.jar:classes.dex
```

`renderscript-v8.jar` is a file-based dependency, coming from Android SDK.

**Comment by wolfs** [comment] 2021-01-11 17:31
This seems to be similar to https://github.com/gradle/gradle/issues/15536, but different enough that it is not yet fixed. Though the above reproducer works now since we reverted #15737, I suppose the underlying problem is still present. It should be possible to expose it when using a similar dependency/transform constellation, only for a project dependency instead of a file dependency.

**Comment by jjohannes** [comment] 2021-05-17 13:57
In the reproducer shared above, `renderscript-v8.jar` is added twice: By AGP and by a line in the build script `implementation files('libs/renderscript-v8.jar')`.

To check it, add a task like this to print the jars:

```
tasks.register('cpJars') {
    doLast {
        configurations.debugCompileClasspath.files.each {println(it) }
    }
}
```

Then you see:

```
> Task :cpJars
../Library/Android/sdk/build-tools/30.0.2/renderscript/lib/renderscript-v8.jar
../renderscriptNdk/libs/renderscript-v8.jar

```

The reported error could be better (on the AGP side). I don't think there is a problem in Gradle.

**Comment by jjohannes** [comment] 2021-05-26 09:07
Closing this, as it turned out to be an issue in the reproducer and not in Gradle.

**Closed by jjohannes** 2021-05-26 09:07 UTC
Labels: @execution, in:android-support, in:artifact-transforms
