### ISSUE TITLE
Dependency from evicted node keeps forcing transitive up

### ISSUE THREAD

**Issue by dansanduleac** [gradle/gradle#10214] opened 2019-08-07 15:42 UTC
Gradle was selecting a version 2.18.0 of a component `com.palantir.foo:foo-api` deep in our resolution graph, when all dependents asked only for 1.44.1, and nothing asked for 2.18.0.

When debugging, dependencyInsight confirmed that all dependents required the old version only (1.44.1), and same with the build scan.

No virtual platforms contained this particular component, and we are not using module metadata yet so all nodes in question use plain POMs.

This repros on all of 5.3.1, 5.4.1 and 5.5.1 (we haven't checked lower versions).

### Expected Behavior

`com.palantir.foo:foo-api` resolves to `1.44.1`

### Current Behavior

The bump is being shown in the dependency insight but it wasn't clear where it came from:

```
com.palantir.foo:foo-api:1.44.1 -> 2.18.0
+--- ... (another dep)
|    +-- com.palantir.transforms:testing-lib:6.1.0
|        ...
|        \--- project :vector-ete (requested com.palantir.transforms:testing-lib:5.19.0) (*)
\--- com.palantir.transforms:testing-lib:6.1.0 (*)
```

We inspected the POM of `testing-lib:6.1.0` and saw that 2.18.0 was never mentioned, but using an eachDependency block noticed that _something_ was still pulling in this newer version.

```gradle
configurations.all {
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            if (details.requested.group == 'com.palantir.foo' 
                    && details.requested.name == 'foo-api'
                    && details.requested.version == '2.18.0') {
                System.out.println("[BOOM] " + details.requested)
            }
        }
    }
```

Eventually, we realized that `testing-lib:5.19.0` _does_ actually depend on the unexpected `com.palantir.foo:foo-api:2.18.0`, but we expected that this dependency should have been ignored because `testing-lib` was resolved to `6.1.0`, so dependencies from `5.19.0` shouldn't affect the final resolution result.

### Context

We were unable to get gradle to downgrade a version of a deep transitive, without resorting to forces, even though no constraint in the graph should have bumped that transitive up.

### Workaround

In `project :vector-ete`, we had to add a non-sensical exclude of `foo-api` from the transitives of `testing-lib`:

```diff
 testCompile 'com.palantir.transforms:testing-lib', {
+    exclude group: 'com.palantir.foo', module: 'foo-api' 
 }
```

### Steps to Reproduce 

We have an internal repo that reproduces this issue reliably on gradle 5.3.1, 5.4.1, 5.5.1, but distilling this into a self-contained repro will take some time. 

### Your Environment

Build scan URL:

This repros identically on CircleCI and multiple developer osx machines.

cc @iamdanfox

**Comment by ljacomet** [comment] 2019-08-07 15:56
I believe you are hitting #6567 which never was reported _in the wild_. And since the solution has quite a severe performance impact, we never merged the fix for it.

The dependency management team bandwidth is taken by the upcoming 6.0 release (and holidays) but we will revisit this after, now that there is actually someone affected by the issue. I can't promise when it will land though as we will have to mitigate as much as possible the performance impact.

**Comment by iamdanfox** [comment] 2019-08-07 16:05
Thanks @ljacomet, that sounds like exactly the issue we encountered. We have a ton of Gradle projects internally and have also never hit this problem, because upgrading deps a bit more than necessary is _usually_ fine.  This specific case came to our attention because we really needed this specific application to stay on the `foo-api:1.X` series because taking `foo-api:2.X` made it undeployable in the wild.

(Out of curiosity, are you expecting 6.X land before 2020? We still have a bunch of deprecations to resolve!)

**Comment by ljacomet** [comment] 2019-08-07 16:41
@iamdanfox Indeed, I assume that's why this went unnoticed for so long.
For Gradle 6.0, it will be the next version after Gradle 5.6, so you have 2 months I would say. Of course, this is software, so planning may change. But clearly well before 2020 😉

**Comment by jjohannes** [comment] 2019-11-07 10:02
Closing this as a duplicate of #6567 (which is now marked as a bug).

**Closed by jjohannes** 2019-11-07 10:02 UTC
Labels: a:bug, from:contributor, in:dependency-management
