### ISSUE TITLE
Build init plugin should offer JUnit 5 test framework selection

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#4485] opened 2018-02-22 19:41 UTC
### Expected Behavior

The command line option `--test-framework` should offer an option for JUnit 5 tests.

### Current Behavior

JUnit 5-based tests are not supported at the moment for the project type `java-application` or `java-library`.

### Context

The build init plugin should support JUnit 5 natively now that the test framework has become a core functionality.

**Comment by karanveersp** [comment] 2019-03-28 16:57
Until Gradle updates this, I've created a python script that others may find helpful. It generates a JUnit5 Gradle Java project.
https://github.com/karanveersp/junit5-project-initializer

**Comment by adammurdoch** [comment] 2019-05-23 23:56
This is a duplicate of #8826 (which has been fixed).

**Closed by adammurdoch** 2019-05-23 23:56 UTC
Labels: a:feature, from:member, in:build-init-plugin
