### ISSUE TITLE
kotlin api doc but example used groovy

### ISSUE THREAD

**Issue by thetbw** [gradle/gradle#27000] opened 2023-11-09 09:01 UTC
### Issue type

Missing information

### Problem description

https://docs.gradle.org/current/kotlin-dsl/gradle/org.gradle.api.tasks/-exec/index.html

I don’t have groovy skills，can provide kotlin documentation?

### Page with the problem

https://docs.gradle.org/current/kotlin-dsl/gradle/org.gradle.api.tasks/-exec/index.html

**Comment by cobexer** [comment] 2023-11-09 13:45
Thank you for providing a valid report.

The issue is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before a fix is made.

***
There is a general problem with Groovy based snippets in Javadoc because there should be examples for both Groovy and Kotlin.

**Comment by eskatos** [comment] 2023-11-09 13:51
This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/24622

Please add your use case and 👍 to that issue.

**Closed by eskatos** 2023-11-09 13:51 UTC
Labels: in:documentation-infrastructure, a:bug, in:kotlin-dsl
