### ISSUE TITLE
Dependency of plugin gets ignored when a settings plugin has the same dependency

### ISSUE THREAD

**Issue by Technici4n** [gradle/gradle#29117] opened 2024-05-13 16:33 UTC
### Current Behavior

Hi Gradle team,

It seems that project plugin dependencies do not get respected when a settings plugin already uses them.

### Expected Behavior

I would expect the project plugin to have access to the dependencies it declares, or at the very least to receive a meaningful error whenever the project plugin gets applied.

### Steps to Reproduce

- Make a custom binary project plugin that depends on GSON version `2.10.1`.
- Add an outdated settings plugin that depends on an older GSON version (here `2.9.1`).
- Notice that the older GSON is used for tasks defined in the project plugin.

Here is a minimum reproduction case: https://github.com/Technici4n/gradle-issue-29117. Simply run `gradlew doSomething` in the root project and it should fail with `Unexpected IllegalAccessException occurred (Gson 2.9.1).`, indicating that the wrong GSON version was used to run the task.

### Gradle version

8.7

**Comment by ljacomet** [comment] 2024-05-16 12:18
This issue will be closed as a duplicate of

* #1370

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

This issue is the same as the 3rd point in the bullet list under "Performance and correctness"

**Closed by ljacomet** 2024-05-16 12:18 UTC
Labels: a:bug, in:plugin-management, closed:duplicate
