### ISSUE TITLE
Using included builds for local settings plugins don't seem to work

### ISSUE THREAD

**Issue by elect86** [gradle/gradle#16163] opened 2021-02-15 21:06 UTC
According to [here](https://docs.gradle.org/7.0-milestone-1/release-notes.html#using-included-builds-for-local-plugins), 
> Developing plugins as part of a composite build was so far only possible for project plugins. Settings plugins always had to be developed in isolation and published to a binary repository.
> This release introduces a new DSL construct in the settings file for including plugin builds. Build included like that can provide both project and settings plugins.

### Current Behavior or error
if I double click `assemble`, I get 
> Plugin [id: 'sciJava.catalogs'] was not found in any of the following sources:

If I run `gradle :build-logic:commons:assemble`, then no catalog alias is resolved

### Steps to Reproduce 
Clone this [commit](https://github.com/elect86/umbrella/commit/55983c0d0a1d4c847b4028438aee2cd325ff8f76) and run `gradle :build-logic:commons:assemble`

### Your Environment
M1 (`gradle-7.0-milestone-1-all.zip`)

Ubuntu 20.10 x64, IDEA 2021.1 EAP (Ultimate Edition)
> Build #IU-211.5787.15, built on February 10, 2021
IntelliJ IDEA EAP User
Expiration date: March 12, 2021
Runtime version: 11.0.10+9-b1319.6 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 5.8.0-41-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 3987M
Cores: 16
Non-Bundled Plugins: GLSL (1.19), com.4lex4.intellij.solarized (2.3.0), com.intellij.nativeDebug (211.5787.11), com.jetbrains.plugins.ini4idea (211.5787.4), org.toml.lang (0.2.140.3644-203), com.kaylerrenslow.plugin.armaplugin.id (2.0.2), kotest-plugin-intellij (1.0.5)
Kotlin: 211-1.4.21-release-IJ5787.2
Current Desktop: ubuntu:GNOME

Build scan URL:
I tried to `gradle build --scan`, but I get the following
> * What went wrong:
Plugin [id: 'sciJava.catalogs'] was not found in any of the following sources:
> - Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
> - Plugin Repositories (plugin dependency must include a version number for this source)

Edit: it works for the `build.gradle.kts` of the `build-logic` component, it doesn't if I want to use an alias inside a module (like `build-logic:commons`)

**Comment by jjohannes** [comment] 2021-02-16 15:57
I am closing this then. The include build feature should work well if you do **not use a catalog**. If that is not the case, please provide a reproducer without catalogs involved.

The actual issue seems to be accurately captured by #15383. The catalog feature is incubating/experimental and further work has been delayed for after 7.0.

**Closed by jjohannes** 2021-02-16 15:57 UTC
Labels: a:investigation, affects-version:7.0

**Comment by elect86** [comment] 2021-02-16 16:05
Sorry, thanks for pointing it that out, @Vampire
