### ISSUE TITLE
java-library-distribution plugin missing implementation dependencies of java-library plugin

### ISSUE THREAD

**Issue by vgarmash-chewy** [gradle/gradle#6399] opened 2018-08-16 19:49 UTC
Consider you have Gradle 4.9 script like this:
```
plugins {
    // Apply the java-library plugin to add support for Java Library
    id 'java-library'
    id 'java-library-distribution'
}
sourceCompatibility = 1.8
targetCompatibility = 1.8
version = '0.1-SNAPSHOT'
def guavaVersion = '26.0-jre'

dependencies {
   implementation "com.google.guava:guava:$guavaVersion"
}

/**
 * Create jar with sources
 */
task sourcesJar(type: Jar, dependsOn: classes) {
    classifier = 'sources'
    from sourceSets.main.allSource
}

/**
 * Create jar with JavaDocs
 */
task javadocJar(type: Jar, dependsOn: javadoc) {
    classifier = 'javadoc'
    from javadoc.destinationDir
}

artifacts {
    archives sourcesJar
    archives javadocJar
}

distributions {
    main{
        baseName = 'your-name'

    }
}
```

### Expected Behavior
after you run
`clean installDist`

we expect to see in build/install the following sutructure:

```
your-name
 -lib
      animal-sniffer-annotations-1.14.jar
      checker-qual-2.5.2.jar
     error_prone_annotations-2.1.3.jar
     guava-26.0-jre.jar
     j2objc-annotations-1.1.jar
     jsr305-3.0.2.jar
-your-library-0.1-SNAPSHOT.jar
```
### Current Behavior
Currently the distribution is being generated without dependencies in lib folder:

```
your-name
-your-library-0.1-SNAPSHOT.jar
```

### Workaround
If I change `implementation` to `compile` in dependency declaration, then it works as expected.

**Comment by thc202** [comment] 2018-08-16 22:59
Seems to be a duplicate of #5695.

**Closed** 2018-08-17 00:00 UTC
