### ISSUE TITLE
Build scan reports dependencies being resolved at configuration time in buildSrc

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#6423] opened 2018-08-18 05:54 UTC
Looks like this:
![image](https://user-images.githubusercontent.com/9490724/44296254-e01f0900-a26f-11e8-9b26-7e744a50eb06.png)

Project: https://github.com/SUPERCILEX/Robot-Scouter/tree/f684754ef87cd50bfb3238a2fed456f4dd9458de
Setup: `./gradlew setup`

I'm not applying any external plugins or doing anything in my `buildSrc` build file, so I don't see how I could be causing it.

**Comment by etiennestuder** [comment] 2018-08-20 10:18
@oehme This has come up repeatedly from different sources. Can you share your view on this, please? (the Gradle side and the mentioning in build scans)

**Comment by oehme** [comment] 2018-08-21 08:11
This is a duplicate of https://github.com/gradle/gradle/issues/5549, which includes the reason for this bug.

**Comment by etiennestuder** [comment] 2018-08-21 08:35
@oehme I see, so this is actually a bug in Gradle exposed by build scans. Proper solution is to fix it in Gradle rather than to hide it in build scans.

**Closed by etiennestuder** 2018-08-21 08:35 UTC

**Comment by etiennestuder** [comment] 2018-08-21 09:04
Thanks, @oehme .

**Comment by bigdaz** [comment] 2018-10-01 13:42
FYI This has been fixed via #6960
