### ISSUE TITLE
Cannot cancel watching on Windows due to "device or resource busy"

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#13366] opened 2020-06-08 15:15 UTC
Sometimes cancelling a watch point fails on Windows with
```
Couldn't cancel watch point <work-dir>\subprojects\ide\build\tmp\test files\CompositeBuildIdeaProjectIntegrationTest\builds_IDEA_metadat...ame_build\8484g\buildA: device or resource busy: device or resource busy
```
See for example https://e.grdev.net/s/r7hh2az6r74qy/tests/:ide:vfsRetentionIntegTest/org.gradle.plugins.ide.idea.CompositeBuildIdeaProjectIntegrationTest/builds%20IDEA%20metadata%20with%20substituted%20dependency%20from%20same%20build#1

It seems that Gradle starts watching the project root and then very shortly after stops watching it again, most probably because nothing is left to watch in the project root.

See https://github.com/gradle/gradle/issues/13135#issuecomment-633445781.

---
cc: @gradle/execution

**Comment by lptr** [comment] 2020-06-08 15:57
This has to be something at least a bit more complicated than starting and stopping watchers in quick succession. We have a test that should be doing almost exactly that: https://github.com/gradle/native-platform/blob/b8f27b864ff82621cb80e127579c1a75b682be91/src/test/groovy/net/rubygrapefruit/platform/file/FileEventFunctionsStressTest.groovy#L37-L47

I'll try to run the test with closing the watched directory instead of shutting down the watcher. Maybe that makes a difference, but I don't think so.

**Comment by lptr** [comment] 2020-06-08 20:47
Right, we already have a test like that, just underneath the previous one:

https://github.com/gradle/native-platform/blob/b8f27b864ff82621cb80e127579c1a75b682be91/src/test/groovy/net/rubygrapefruit/platform/file/FileEventFunctionsStressTest.groovy#L48-L62

**Comment by wolfs** [comment] 2020-06-18 13:44
This is still happening, even with the lastest native platform snapshot: https://e.grdev.net/s/ztobpvl4ufk3w/tests/:logging:watchFsIntegTest/org.gradle.internal.logging.console.taskgrouping.plain.AutoConsoleCompositeBuildGroupedTaskFunctionalTest/can%20group%20task%20output%20in%20composite%20build%20%5Bconsole%20attached%20to%20both%20stdout%20and%20stderr%5D?focused-exception-line=0-10#1

**Comment by wolfs** [comment] 2020-06-19 12:31
Even after upgrading to the new native platform version, we get the exception from the Windows side: https://e.grdev.net/s/xzgocrnc4evl6/tests/:compositeBuilds:watchFsIntegTest/org.gradle.integtests.composite.CompositeBuildDependencyGraphIntegrationTest/substitutes%20external%20dependencies%20with%20project%20dependencies%20using%20--include-build?focused-exception-line=0-11#1

```
Couldn't cancel watch point C:\tcagent1\work\a16b87e0a70f8c6e\subprojects\composite-builds\build\tmp\test files\CompositeBuildDependencyGraphIntegrationTest\2hdee\buildB: device or resource busy: device or resource busy
```

Note that it is not `CloseHandle` which throws the exception, since then we would get something like `Couldn't close handle ...`, see [here](https://github.com/gradle/native-platform/blob/e44fdb350623ba00376a7074ae4faf2be2454c1a/src/file-events/cpp/win_fsnotifier.cpp#L110-L124).

I suppose [`CancelIoEx`](https://github.com/gradle/native-platform/blob/e44fdb350623ba00376a7074ae4faf2be2454c1a/src/file-events/cpp/win_fsnotifier.cpp#L44) is the only Windows call which could throw within `cancel`.

**Comment by wolfs** [comment] 2020-06-19 13:29
It seems like tests using composite builds or native compilation are affected the most. So tests which watch more than one directory.

**Comment by wolfs** [comment] 2020-06-19 14:52
Here is a typical daemon log sequence:

```
Watching the file system is an incubating feature.
Spent 94 ms registering watches for file system events
Virtual file system retained information about 0 files, 0 directories and 0 missing files since last build
Watching 1 directory hierarchies to track changes: [C:\tcagent1\work\a16b87e0a70f8c6e\subprojects\composite-builds\build\tmp\test files\CompositeBuildArtifactTransformIntegrationTest\hb9x1\buildB]
Watching 2 directory hierarchies to track changes: [C:\tcagent1\work\a16b87e0a70f8c6e\subprojects\composite-builds\build\tmp\test files\CompositeBuildArtifactTransformIntegrationTest\hb9x1\buildC, C:\tcagent1\work\a16b87e0a70f8c6e\subprojects\composite-builds\build\tmp\test files\CompositeBuildArtifactTransformIntegrationTest\hb9x1\buildB]
Couldn't cancel watch point C:\tcagent1\work\a16b87e0a70f8c6e\subprojects\composite-builds\build\tmp\test files\CompositeBuildArtifactTransformIntegrationTest\hb9x1\buildC: device or resource busy: device or resource busy
Watching 1 directory hierarchies to track changes: [C:\tcagent1\work\a16b87e0a70f8c6e\subprojects\composite-builds\build\tmp\test files\CompositeBuildArtifactTransformIntegrationTest\hb9x1\buildB]
Watching 2 directory hierarchies to track changes: [C:\tcagent1\work\a16b87e0a70f8c6e\subprojects\composite-builds\build\tmp\test files\CompositeBuildArtifactTransformIntegrationTest\hb9x1\buildC, C:\tcagent1\work\a16b87e0a70f8c6e\subprojects\composite-builds\build\tmp\test files\CompositeBuildArtifactTransformIntegrationTest\hb9x1\buildB]
Watching 1 directory hierarchies to track changes: [C:\tcagent1\work\a16b87e0a70f8c6e\subprojects\composite-builds\build\tmp\test files\CompositeBuildArtifactTransformIntegrationTest\hb9x1\buildB]
Watching 2 directory hierarchies to track changes: [C:\tcagent1\work\a16b87e0a70f8c6e\subprojects\composite-builds\build\tmp\test files\CompositeBuildArtifactTransformIntegrationTest\hb9x1\buildC, C:\tcagent1\work\a16b87e0a70f8c6e\subprojects\composite-builds\build\tmp\test files\CompositeBuildArtifactTransformIntegrationTest\hb9x1\buildB]
Transforming C:\tcagent1\work\a16b87e0a70f8c6e\subprojects\composite-builds\build\tmp\test files\CompositeBuildArtifactTransformIntegrationTest\hb9x1\buildC\build\libs\buildC-1.0.jar in output directory C:\tcagent1\work\a16b87e0a70f8c6e\subprojects\composite-builds\build\tmp\test files\CompositeBuildArtifactTransformIntegrationTest\hb9x1\buildC\build\.transforms\074709aa0e7074f1a1a03a89dd1b2992
Transforming C:\tcagent1\work\a16b87e0a70f8c6e\subprojects\composite-builds\build\tmp\test files\CompositeBuildArtifactTransformIntegrationTest\hb9x1\buildB\build\libs\buildB-1.0.jar in output directory C:\tcagent1\work\a16b87e0a70f8c6e\subprojects\composite-builds\build\tmp\test files\CompositeBuildArtifactTransformIntegrationTest\hb9x1\buildB\build\.transforms\499f38cf10cf8d97684e35b88ef9b2a4
Transformed artifact: buildB-1.0.jar.xform (project :buildB), location: C:\tcagent1\work\a16b87e0a70f8c6e\subprojects\composite-builds\build\tmp\test files\CompositeBuildArtifactTransformIntegrationTest\hb9x1\buildB\build\.transforms\499f38cf10cf8d97684e35b88ef9b2a4\buildB-1.0.jar.xform
Transformed artifact: buildC-1.0.jar.xform (project :buildC), location: C:\tcagent1\work\a16b87e0a70f8c6e\subprojects\composite-builds\build\tmp\test files\CompositeBuildArtifactTransformIntegrationTest\hb9x1\buildC\build\.transforms\074709aa0e7074f1a1a03a89dd1b2992\buildC-1.0.jar.xform
```

**Comment by wolfs** [comment] 2020-06-21 20:49
Finally it seems like [`SleepEx`](https://github.com/gradle/native-platform/blob/c4e9b5afc15a13c299156cc4cc2289e6b165f1b4/src/file-events/cpp/win_fsnotifier.cpp#L65) in the destructor of `WatchPoint` is throwing the exception. I have no idea how that can happen, though putting a `try ... catch` around that statement allows me to catch the exception and log it.

The problem is pretty easily reproducible by running some of the failed `compositeBuild:watchFsIntegTest` tests from [here](https://builds.gradle.org/buildConfiguration/Gradle_Check_WatchFs_38_bucket46/36096173?buildTab=overview) on [the branch](https://github.com/gradle/gradle/pull/13528) which checks for the `device or resource busy` message.

**Comment by lptr** [comment] 2020-06-22 05:05
I wonder if this is relevant:

> The problem is that the compiler optimized the catch away. Why? Because according to the C++ standard it's undefined (or unspecified, or implementation defined... I don't remember the exact formulation) what happens if an extern "C" function exists through an exception. So the compiler assumes that SleepEx (which is extern "C") does not ever throw, after inlining of Test::Test and Test::~Test it sees that the printf doesn't throw either, and consequently if something in this block exists via an exception [...] the behavior is undefined!
> 
> In MSVC the code doesn't work with the `/EHsc` switch in Release build, but it will work with `/EHa` or `/EHs`, which tell it to assume that C function may throw. Perhaps GCC has similar flag.

I'll try to reproduce with `/EHs` instead of `/EHsc`. After all, we do know we have a C function that throws...

**Comment by wolfs** [comment] 2020-06-22 06:42
I specifically did this:
```cpp
try {
    SleepEx(0, true);
} catch (const exception& ex) {
    logToJava(LogLevel::WARNING, "SleepEx threw exception %s: %s", utf16ToUtf8String(path).c_str(), ex.what());            
}
```

Then I got the `SleepEx` log message. I don't see how this can be related to removing the `try ... catch` by the compiler.

**Comment by lacasseio** [comment] 2020-06-22 14:53
The optimizer can be pretty ruthless when it comes to removing code that shouldn't be required. Windows API will now throw C++ exception unless you set the flag to bridge structured exception with C++ exception. The structured exception is a Windows-only feature that typically uses `__try` keyword. In general, you should not expect exceptions coming from the Windows API and check the status code of every API call.

It's important to note the MSVC version used for compiling as, for example, `noexcept` keyword was a no-op in VS2015 and I believe it was until later release of VS2017. This may have an effect on how the optimization is done.

**Comment by wolfs** [comment] 2020-07-17 14:32
I checked via #13528 again, and the error still seems to happen for latest `master`: https://ge.gradle.org/s/rdcdkq2wduj4y/tests/:compositeBuilds:watchFsIntegTest/org.gradle.integtests.composite.CompositeBuildDependencyArtifactsIntegrationTest/builds%20multiple%20configurations%20for%20the%20same%20project%20via%20separate%20dependency%20paths#1

**Comment by wolfs** [comment] 2020-07-21 07:47
The `device or resource busy` exception can be thrown by a mutex on Windows: https://stackoverflow.com/a/31205382/2137015

**Comment by lptr** [comment] 2020-07-21 08:58
Looks like `std::mutex` is _not_ reentrant, and instead we should have used `std::recursive_mutex`:

> A calling thread must not own the `mutex` prior to calling `lock` or `try_lock`.

vs

> A calling thread owns a `recursive_mutex` for a period of time that starts when it successfully calls either `lock` or `try_lock`. **During this period, the thread may make additional calls to `lock` or `try_lock`.** The period of ownership ends when the thread makes a matching number of calls to `unlock`.

**Comment by lptr** [comment] 2020-07-21 10:12
https://github.com/gradle/native-platform/pull/249 fixes this in `native-platform`.

**Comment by lptr** [comment] 2020-07-21 13:13
Just confirmed: locking twice on a `mutex` reliably generates the exception.

**Closed** 2020-07-22 10:35 UTC
Labels: @execution, from:member
