### ISSUE TITLE
Let Gradle Report shows the report generated through the name attribute of the @ParameterizedTest

### ISSUE THREAD

**Issue by manueljordan** [gradle/gradle#4712] opened 2018-03-13 20:52 UTC
### Expected Behavior

Let `Gradle Report` shows the report generated through the `name` attribute of the `@ParameterizedTest` through a link (or other way)

### Current Behavior

Having the following:

```
@ParameterizedTest(name = "{index} ==> person: {0}   - arguments: {arguments}")
@MethodSource("data")
@Sql(scripts={"classpath:/com/manuel/jordan/db/delete.sql"})
void saveOneTest(Persona persona){
...
}
```
It works how is expected about the _parameterized_ behavior. 

The situation is about the `name = "{index} ==> person: {0}   - arguments: {arguments}"` pattern, its data result should be available through the `Gradle Report`

Through  `Jenkins` and with the `JUnit` plugin I can see the following _links_:

![01](https://user-images.githubusercontent.com/2552795/37367867-9ab1acf6-26d2-11e8-8d41-428e53df07ca.png)

If I do click in any of them I can see:

![02](https://user-images.githubusercontent.com/2552795/37367899-ac47c0ae-26d2-11e8-8561-f30d4f9474f6.png)

Until here I am assuming it is the expected behaviour

But If I open the `Gradle Report` I can see the following:

![03](https://user-images.githubusercontent.com/2552795/37367923-b6eeb58a-26d2-11e8-93fc-e40d54031b4a.png)

But sadly each one has no the _link_ feature, thus I can see just the raw text

### Context

I think is valuable get the report generated by `@ParameterizedTest(name = "{index} ==> person: {0}   - arguments: {arguments}")` into the `Gradle Report` too.

### Your Environment

* `Gradle 4.6` 
* `JUnit 5.1.0` 

It happens (I already did a do a confirmation) for `JUnit` 4.12 and either `Gradle` 4.3.1  or 4.5.1. It about for other older projects

**Comment by marcphilipp** [comment] 2018-03-14 11:45
Related to https://github.com/junit-team/junit5/issues/1320.

**Comment by sbrannen** [comment] 2018-03-14 16:25
This issue is essentially a duplicate of https://github.com/gradle/gradle/issues/4423, since the key topic here is "display names vs. technical names".

**Comment by manueljordan** [comment] 2018-03-14 17:16
Agree `@DisplayName` vs `@ParameterizedTest(name = "pattern")

**Comment by blindpirate** [comment] 2018-03-17 02:24
Closed by #4425 .

Now it looks like:

![image](https://user-images.githubusercontent.com/12689835/37550732-5c1c95fc-29cd-11e8-9286-4de983576740.png)

**Closed by blindpirate** 2018-03-17 02:24 UTC
Labels: a:bug, from:contributor, in:testing

**Comment by manueljordan** [comment] 2018-03-17 13:31
Thanks by your valuable support. I will wait in peace the `4.7` release.

**Comment by sbrannen** [comment] 2018-03-21 13:14
Nice work, @blindpirate! 👍
