### ISSUE TITLE
How to import bom files for all configurations

### ISSUE THREAD

**Issue by remy-tiitre** [gradle/gradle#7576] opened 2018-10-30 12:26 UTC
So far I have been using Spring Dependency Management plugin. But as the gradle 5.0 will be released soon I started to play with those gradle native dependency management features. Its nice that gradle finally integrates them to core. But the documentation is lacking and I it seems that its also not that intuitive. For example, lets say that you are using Spring Boot 2 and have multi module project. What you would want to do is apply Spring Boot plugin at root project and import springs bom file for all projects and all configurations. I don't think this can be done right now.

This works at root project:
```
plugins {
    id 'org.springframework.boot' version '2.0.5.RELEASE'
}
allprojects {
    afterEvaluate {
        dependencies {
            implementation org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES
```
But I have a lot more configurations like runtimeOnly, testImplementation, testRuntimeOnly, integTestImplementation, integTestRuntimeOnly, annotationProcessor, compileOnly, providedCompile, provdidedRuntime. Adding this bom import line for every configuration seems redundant. Whats even worse, providedCompile and providedRuntime are not available on every project, only those that are packaged as war. Yet, it would be nice to set it up at the root project level so that spring boot versions would be aligned. I do understand that sometimes you would prefer to add separate bom files for different configurations but more than likely you want to align the versions for all configurations. Maybe we should add "all" configuration?

So I could write
```
allprojects {
    afterEvaluate {
        dependencies {
            all org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES
```

**Comment by melix** [comment] 2018-10-31 10:32
Hi @remy-tiitre ,

First of all, the configuration inheritance model of Gradle makes it so that in most cases you only need to declare the BOM in a few configurations. For example if you add it to `implementation`, you _will_ get the effect in `compileClasspath`, `runtimeClasspath`, `testRuntimeClasspath` and more. It makes therefore no sense to _also_ declare it to `testImplementation`. You'd only have to do so if your test runtime dependencies need a _different_ platform, which is exactly why it is designed as intended.

Now, should you really want to use a hammer and apply the BOM to all possible configurations, then you only need to apply it to the _resolvable_ configurations. And it can be achieved quite simply. First, define a configuration for the platforms you want to apply everywhere:

```
configurations {
    globalPlatforms {
       canBeResolved = false
       canBeConsumed = false
    }
}
```

then add your dependency to this configuration:

```
dependencies {
      globalPlatforms platform(org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES)
}
```
And eventually, make it so that all configurations that can be resolved will inherit from this global platform configuration:

```
configurations.all {
    if (canBeResolved) {
       extendsFrom(configurations.globalPlatforms)
    }
}
```

which gives, in the end:

```
configurations {
    globalPlatforms {
       canBeResolved = false
       canBeConsumed = false
    }
}
configurations.all {
    if (canBeResolved) {
       // configurations like compileClasspath, runtimeClasspath, ... will inherit global platforms
       extendsFrom(configurations.globalPlatforms)
    }
}
dependencies {
      globalPlatforms platform(org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES)
}
```

**Comment by remy-tiitre** [comment] 2018-10-31 10:41
Ok, thanks for this guide. I admit, that my initial example was a little bit misleading. You do not need to apply it to every configuration. Yet, extract from my current configuration:
```
allprojects {
    plugins.withId('war') {
        dependencies {
            providedCompile org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES

            constraints {
                providedCompile('javax.servlet:javax.servlet-api:3.1.0') { because 'We use Tomcat 8.x' }
            }
        }
    }

    plugins.withId('java') {
        dependencies {
            compile org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES

            constraints {
                annotationProcessor('org.projectlombok:lombok:1.18.2') { because 'Gradle 4.9+ does not work with 1.16.22 version' }
                compileOnly('org.projectlombok:lombok:1.18.2') { because 'Gradle 4.9+ does not work with 1.16.22 version' }
                integTestCompileOnly('org.projectlombok:lombok:1.18.2') { because 'Gradle 4.9+ does not work with 1.16.22 version' }
            }
        }
    }
}
```
So to be fair, its not that much of a limitation with bom import than with constraints. I would rather write something like this:
```
allprojects {
        dependencies {
            all org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES

            constraints {
                all('javax.servlet:javax.servlet-api:3.1.0') { because 'We use Tomcat 8.x' }
                all('org.projectlombok:lombok:1.18.2') { because 'Gradle 4.9+ does not work with 1.16.22 version' }
            }
        }
    }
}
```
But I think with the examples you provided I can archive something like that if the logis is added to gradle wrappers init scripts

**Comment by melix** [comment] 2018-10-31 10:44
I understand. Even with `constraints` the logic is the same: if you have shared configuration, you can design it using a dedicated configuration and make resolvable configurations inherit from it.

**Comment by remy-tiitre** [comment] 2018-10-31 11:49
One more thing, if I don't want to detect that some plugin has been applied before I set the version configuration then I have to use afterevaluete, right? Like so:
```
allprojects {
    afterevaluate {
        dependencies {
            ....
            constraints {
```

**Comment by melix** [comment] 2018-10-31 12:16
I'm not sure I follow you. A plugin can contribute versions, constraints, anything. You can detect a specific plugin application by using `https://github.com/gradle/gradle/blob/master/subprojects/core-api/src/main/java/org/gradle/api/plugins/PluginManager.java#L103`

**Comment by remy-tiitre** [comment] 2018-10-31 13:47
Ok, let me explain my usecase. I have multi project configuration. Most subprojects are generating jar libraries, some are generating war files. Its not a huge one, lets say 1 root project + 3-4 subprojects. Now, fixing dependency versions is reasonable to be done at the root project with allprojects scope. That way, if I update Spring Boot version for example, it will be updated in all subprojects as well. Having said that, I can't configure providedCompile scope dependencies at allprojects closure without checking that this plugin is applied or not. But with the examples you provided I can now create a configuration recommendedVersion and apply that without checking that java or war plugins are applied. These dependencies are inherited automatically by providedCompile and compile configurations. But I already checked that I do have to use afterEvaluate if I want to set constraints to "implementation" configuration or any other configuration added by some plugin. But for reference to other people who might be interested in doing something similar, here is the configuration that works in root project:
```
allprojects {
    afterEvaluate {
        configurations {
            recommendedVersion {
                canBeResolved = false
                canBeConsumed = false
            }
        }

        configurations.all {
            if (canBeResolved) {
                extendsFrom(configurations.recommendedVersion)
            }
        }

        dependencies {
            recommendedVersion org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES

            constraints {
                recommendedVersion('javax.servlet:javax.servlet-api:3.1.0') { because 'We use Tomcat 8.x' }
                recommendedVersion('org.projectlombok:lombok:1.18.2') { because 'Gradle 4.9+ does not work with 1.16.22 version' }

                recommendedVersion('org.mockito:mockito-junit-jupiter:2.18.3') { because 'Not in Spring Boot' }
            }
        }
    }
}
```

**Comment by ljacomet** [comment] 2018-11-05 19:05
There is no need for the `afterEvaluate` in this case. That requirement probably came from trying to reference configurations by name before they were created.
However in this case, the only configuration you reference explicitly is the one you create, `recommendedVersion`.

The `configurations.all` is what enables this to work. It will effectively applying the block to any configuration, already existing or created later.

I believe with these exchanges, the issue can be closed. Unless there is further activity in the next 12 hours, I will close it.

**Comment by remy-tiitre** [comment] 2018-11-05 20:02
You do need afterEvaluate. Even the configurations and configurations.all have to be inside afterEvaluate. Tried without and it failed.

**Comment by ljacomet** [comment] 2018-11-05 20:48
Can you share the exception you get? Cause it really should not be needed. That's the whole point of the `.all` constructs in the Gradle DSL.

**Comment by remy-tiitre** [comment] 2018-11-28 15:58
Well, I tried to move this block out of afterEvaluate

**Comment by remy-tiitre** [comment] 2018-11-28 16:04
Nope, the problem is still there. Adding this code will generate error:
```
    configurations {
        recommendedVersion {
            canBeResolved = false
            canBeConsumed = false
        }
    }

    configurations.all {
        if (canBeResolved) {
            extendsFrom(configurations.recommendedVersion)
        }
    }

    pluginManager.apply(nebula.plugin.resolutionrules.ResolutionRulesPlugin)
```
When I put first 2 block inside afterEvaluate it will work

**Comment by ljacomet** [comment] 2018-12-03 15:19
@remy-tiitre I have created a sample project that uses the code above and it builds without problem. Would you mind opening up a PR against it that shows the issue?

Repository: https://github.com/ljacomet/after-evaluate

**Comment by ljacomet** [comment] 2018-12-11 15:52
Closing as the initial issue has been answered and there is no plan to have a dedicated construct in Gradle core for this.
The conversation on the `afterEvaluate` can move to the forums if it is not resolved at this point.

**Closed by ljacomet** 2018-12-11 15:52 UTC
Labels: in:dependency-management

**Comment by remy-tiitre** [comment] 2019-02-26 09:11
Well I found the reason, if (canBeResolved) matched my recommendedVersion as well and that caused issues. Will post my final solution here for other people who want to accomplish the same thing:
```
    configurations {
        recommendedVersion {
            canBeResolved = false
            canBeConsumed = false
        }
    }

    afterEvaluate {
        configurations.all { configuration ->
            if (configuration.canBeResolved && !['checkstyle', 'jacocoAgent', 'recommendedVersion', 'resolutionRules', 'spotbugs', 'spotbugsPlugins'].contains(configuration.name)) {
                extendsFrom(configurations.recommendedVersion)
            }
        }
    }
```
Just add those configurations in the list that you don't want to extend from the recommendedVersion
