### ISSUE TITLE
Calling `java.lang.System::load` will be blocked in the future

### ISSUE THREAD

**Issue by clin1234** [gradle/gradle#31876] opened 2024-12-23 17:08 UTC
### Issue type

Deprecation

### Problem description

C:\Users\שזדס>gradle.cmd  -v
WARNING: A restricted method in java.lang.System has been called
WARNING: java.lang.System::load has been called by net.rubygrapefruit.platform.internal.NativeLibraryLoader in an unnamed module (file:/C:/Users/שזדס/scoop/apps/gradle-bin/8.12/lib/native-platform-0.22-milestone-27.jar)
WARNING: Use --enable-native-access=ALL-UNNAMED to avoid a warning for callers in this module
WARNING: Restricted methods will be blocked in a future release unless native access is enabled

------------------------------------------------------------
Gradle 8.12
------------------------------------------------------------

Build time:    2024-12-20 15:46:53 UTC
Revision:      a3cacb207fec727859be9354c1937da2e59004c1

Kotlin:        2.0.21
Groovy:        3.0.22
Ant:           Apache Ant(TM) version 1.10.15 compiled on August 25 2024
Launcher JVM:  24-ea (Oracle Corporation 24-ea+29-3578)
Daemon JVM:    C:\Users\שזדס\scoop\apps\openjdk-ea\24-29-ea (no JDK specified, using current Java home)
OS:            Windows 11 10.0 amd64

**Comment by abstratt** [comment] 2024-12-27 15:23
This issue will be closed as a duplicate of

* #31625

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

**Closed** 2024-12-28 21:02 UTC
Labels: a:bug, closed:duplicate, in:java-plugins
