### ISSUE TITLE
Exclusions declared in a dependency's pom should work as they do in Maven

### ISSUE THREAD

**Issue by wilkinsona** [gradle/gradle#1473] opened 2017-02-28 10:57 UTC
### Expected Behavior

Gradle and Maven have subtly different semantics when it comes to excluding dependencies. When a dependency is resolved from a Maven repository and its pom is being used, I would like Gradle to apply Maven's semantics to the exclusions declared in the pom.

### Current Behavior

The current behaviour is described [here](https://spring.io/blog/2015/02/23/better-dependency-management-for-gradle#exclusions-in-gradle). With this dependency configuration in a pom:

```xml
<dependency>
  <groupId>org.springframework</groupId>
  <artifactId>spring-core</artifactId>
  <version>4.1.4.RELEASE</version>
  <exclusions>
    <exclusion>
      <groupId>commons-logging</groupId>
      <artifactId>commons-logging</artifactId>
    </exclusion>
  </exclusions>
</dependency>
<dependency>
  <groupId>org.springframework</groupId>
  <artifactId>spring-beans</artifactId>
  <version>4.1.4.RELEASE</version>
</dependency>
<dependency>
  <groupId>org.slf4j</groupId>
  <artifactId>jcl-over-slf4j</artifactId>
  <version>1.7.10</version>
</dependency>
```

Maven produces this dependency graph:

```
\- com.example:my-library:jar:0.0.1-SNAPSHOT:compile
   +- org.springframework:spring-core:jar:4.1.4.RELEASE:compile
   +- org.springframework:spring-beans:jar:4.1.4.RELEASE:compile
   \- org.slf4j:jcl-over-slf4j:jar:1.7.10:compile
      \- org.slf4j:slf4j-api:jar:1.7.10:compile
```

Gradle produces this dependency graph:

```
\--- com.example:my-library:0.0.1-SNAPSHOT
     +--- org.springframework:spring-core:4.1.4.RELEASE
     |    \--- commons-logging:commons-logging:1.2
     +--- org.springframework:spring-beans:4.1.4.RELEASE
     |    \--- org.springframework:spring-core:4.1.4.RELEASE (*)
     \--- org.slf4j:jcl-over-slf4j:1.7.10
          \--- org.slf4j:slf4j-api:1.7.10
```

Note the presence of `commons-logging:commons-logging:1.2` when Gradle resolves the graph.

### Context

The difference in behaviour is problematic for libraries in the JVM ecosystem that are published to a Maven repository and consumed using Gradle. Gradle users may end up with transitive dependencies that the library's authors had excluded due to the different interpretations of the exclusions declared in the library's pom.

I'd like to be able to publish a library that declares its dependencies in a pom file and for Gradle to treat any exclusions declared in that pom as Maven would.

**Comment by scr** [comment] 2017-03-08 23:46
FYI https://issues.gradle.org/browse/GRADLE-3115 is also related to this

**Comment by bigdaz** [comment] 2017-11-08 19:50
For clarity, I'll explain why Gradle is including 'commons-logging' in the above example.  
I'm not trying to justify the behaviour, but hopefully my explanation will help us to decide how to address this issue.

In Gradle, dependency exclusions belong to a particular dependency (edge) in the graph. Gradle will only exclude a transitive dependency if excluded from _all_ edges: if there is no possible path that would include the transitive dependency.

In this case, we have 2 paths:
- `example -> spring-core -X-> commons-logging`
- `example -> spring-beans -> spring-core -> commons-logging`

Naturally we only end up with a single `spring-core` node in the graph. When Gradle merges the 2 `spring-core` nodes, the intersection of the excludes is calculated. Hence `common-logging` is not excluded.

The alternative, to use the _union_ of the excludes might not be any better however: consider the case where A depends on X & Y, and both depend on Z, which brings in more dependencies transitively. The publisher of Y might say "I don't need any of Z's dependencies to work, exclude them all". Then, A would not get any of Z's dependencies in the graph, where some of these might really be required by X.

I'm guessing that the reason this works in Maven is due to it's "proximity base" (_nearest wins_) dependency resolution. Instead of attempting to merge the 2 nodes in the graph, Maven would just choose the one closest to the consumer. I'm not sure what Maven would do in my example immediately above.

**Comment by macdanny** [comment] 2018-02-24 20:55
@bigdaz Your explanation doesn't seem correct, because I am seeing transitive dependencies included when they are excluded from all paths. e.g.

```
> Task :dependencyInsight 
org.codehaus.woodstox:woodstox-core-asl:4.2.0
+--- org.apache.chemistry.opencmis:chemistry-opencmis-client-impl:0.12.0
|    +--- com.primavera:intgserver:17.7.0-d
|    |    \--- compileClasspath
|    \--- com.primavera:prm-ucr:17.3.0-a
|         \--- com.primavera:intgserver:17.7.0-d (*)
\--- org.apache.chemistry.opencmis:chemistry-opencmis-commons-impl:0.12.0
     +--- com.primavera:intgserver:17.7.0-d (*)
     +--- org.apache.chemistry.opencmis:chemistry-opencmis-client-impl:0.12.0 (*)
     \--- org.apache.chemistry.opencmis:chemistry-opencmis-client-bindings:0.12.0
          +--- com.primavera:intgserver:17.7.0-d (*)
          \--- org.apache.chemistry.opencmis:chemistry-opencmis-client-impl:0.12.0 (*)
```

My project depends on com.primavera.intgserver:17.7.0-d.  It depends on the chemistry libraries, which then depends on woodstox-core-asl. But the POM for intgserver includes this:

```
    <dependency>
      <groupId>org.apache.chemistry.opencmis</groupId>
      <artifactId>chemistry-opencmis-client-impl</artifactId>
      <version>0.12.0</version>
      <exclusions>
        <exclusion>
          <groupId>org.codehaus.woodstox</groupId>
          <artifactId>woodstox-core-asl</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.apache.chemistry.opencmis</groupId>
      <artifactId>chemistry-opencmis-commons-impl</artifactId>
      <version>0.12.0</version>
      <exclusions>
        <exclusion>
          <groupId>org.codehaus.woodstox</groupId>
          <artifactId>woodstox-core-asl</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

```
Both of the paths to woodstox-core-asl exclude it, but it is still being pulled into my project.

You said "Gradle will only exclude a transitive dependency if excluded from all edges: if there is no possible path that would include the transitive dependency." But there is a difference between all edges and all paths. All paths means it should be excluded with the configuration I have above. All edges means I would have to modify the chemistry POMs to get this dependency excluded. This can't be seen to be reasonable.

**Comment by bigdaz** [comment] 2018-03-04 20:18
Thanks for the detailed report @macdanny. I can reproduce your example, but only by including a second path to the chemistry libraries, via `prm-ucr`.

It looks like you have the following path that would bring in `woodstox`:
```
com.primavera:intgserver:17.7.0-d 
-> com.primavera:prm-ucr:17.3.0-a 
-> org.apache.chemistry.opencmis:chemistry-opencmis-client-impl:0.12.0
-> org.codehaus.woodstox:woodstox-core-asl:4.2.0
```

So either the `integserver -> prm-ucr` dependency or the `prm-ucr -> chemistry-opencmis-client-impl` would need to exclude `woodstox`. Is that the case?

**Comment by macdanny** [comment] 2018-03-09 04:18
@bigdaz Thanks for looking at this. You are absolutely right. Neither of those edges exclude it ... so there is a path that causes it to be included. I don't know why I didn't see it at first. I guess I'm not used to looking at the dependencyInsight output.

**Comment by bigdaz** [comment] 2018-08-15 20:56
So we've been doing a little research into way Maven interprets dependency exclusions, and how this is different from Gradle. It's important to note that in Gradle, exclusions defined for a POM file are not interpreted in isolation, but are combined with exclusions defined in other POM files, the build script itself, and even modules published with `ivy.xml`. So it's not a simple matter of applying Maven semantics for all exclusions defined in a POM file: exclusions have an impact on dependencies brought in by other modules, both in Maven and in Gradle.

### How Maven applies exclusions

From my understanding, much of the resolution behaviour of Maven can be explained by it's "nearest wins" conflict resolution. Given multiple paths to a dependency, Maven will choose a single one of these paths, and will choose the version and exclusions defined for that path (ignoring any version and or exclusions defined for other paths).

The choice of path by Maven is done by finding the shortest path in the graph, choosing the first one declared if there is a tie. So given the following 2 examples, the first one will include C in the result, but the second one won't (because the path with the exclude is shorter) and the third one won't (because the path with the exclude was the first one found).
```
Project -> A -(exclude C)-> B -> C
        \-> B -> C

Project -> A -(exclude C)-> B -> C
        \-> D -> E -> B -> C

Project -> A -(exclude C)-> B -> C
        \-> D -> B -> C
```

This behaviour is confusing (to me) and doesn't seem to be justified. In particular, having dependency ordering be significant seems like a terrible idea.  Even if it was easy to do, we are pretty sure we don't want to introduce this behaviour in Gradle. And remember, each of `A-E` could each be represented by a POM, and Ivy module or a Gradle project.

### How Gradle applies exclusions

Rather than choosing a single path to a module and ignoring all others, Gradle will consider all paths to a module when determining which exclusions to apply. The assumption is that we can only safely exclude a transitive dependency if it's not required by _any_ of the things that use it. So if I have 2 dependencies (`A` and `B`), both of which depend on `C`, then we can only exclude `C` if both of my dependencies declare the exclusion.

In all 3 of the examples above, Gradle will include `C` in the result.

-----

@wilkinsona I'm curious how much of the Maven behaviour you've replicated with the `spring-dependency-management` plugin. Do you inspect the paths and only apply the exclusion to the shortest? Are you actually excluding more than Maven would in the examples above? 

What's the primary area of concern with Gradle's current handling of exclusions? Is it limited to dependencies that are declared _in the same POM file_ (like the example that started this issue)? Or is the use case described [in the plugin docs](https://github.com/spring-gradle-plugins/dependency-management-plugin#maven-exclusions) a real-world use case?**

Since we are almost certainly not going to exactly replicate the Maven behaviour described above, perhaps there's some middle ground that _does_ make sense and we can agree on.

** It looks to me like that example will only work in Maven if the dependency on `exclusion-example` is declared before the dependency on `spring-beans`. Otherwise the `Project -> spring-beans -> spring-core` path will be used, and the path `Project -> exclusion-example -> spring-core` will be ignored.

**Comment by bigdaz** [comment] 2018-08-15 21:49
From my testing, it seems like the `spring-dependency-management` plugin replicates all of the ordering issues and path-length sensitivity that Maven has in it's application of exclusions. So the order of dependencies declared in a build script will impact whether or not a transitive dependency is excluded.

Huge kudos to you for implementing this. However, now I'm a bit stuck on knowing the way forward. We aren't going to completely change the dependency resolution engine in Gradle to work like Maven, and it's not clear to me if there are things we can do to make it _less different_ for users that are trying to maintain a POM that will function the same way in Maven and Gradle.

**Comment by wilkinsona** [comment] 2018-08-16 08:13
> So the order of dependencies declared in a build script will impact whether or not a transitive dependency is excluded.

FWIW, this makes sense to me, although I acknowledge that I'm probably in the minority having gone through the process of implementing the behaviour in the dependency management plugin. I would say though that dependency ordering in the build script affects classpath ordering in Gradle (I think) so extending that to the behaviour of exclusions doesn't seem like too much of a stretch.

> Is the use case described in the plugin docs a real-world use case?

I'm afraid I can't remember if the example in the plugin docs came from a real-world use case that I'd experienced first-hand, or if it was something that I came up with as I began to understand the problem. It's certainly possible that it was the latter.

> It's not clear to me if there are things we can do to make it less different for users that are trying to maintain a POM that will function the same way in Maven and Gradle.

Development of the dependency management plugin was, initially at least, entirely driven by the needs of Spring Boot. It has a [large bom](https://github.com/spring-projects/spring-boot/blob/9201db320098b6a87578f95ea5b3061824eab89b/spring-boot-project/spring-boot-dependencies/pom.xml) that manages dependency versions and exclusions. We also have numerous [starter modules](https://github.com/spring-projects/spring-boot/tree/9201db320098b6a87578f95ea5b3061824eab89b/spring-boot-project/spring-boot-starters). A starter module is intended to make it easy for someone to make use of multiple dependencies by pulling them all together into a single dependency and also excluding some dependencies that aren't wanted **.

If I consider things from a largely selfish perspective, I wonder how much it would take for Gradle to resolve the same dependencies from each of Spring Boot's starter poms as Maven does? This is the dependency management plugin's primary goal. Perhaps investigating that would help to find some pragmatic middle ground for the handling of exclusions that's a bit closer to the broader intent of Maven's behaviour without exactly mimicking all of its idiosyncrasies?

** The split of exclusions between the bom and that starter poms isn't entirely logical and has largely happened by accident. We have [an issue](https://github.com/spring-projects/spring-boot/issues/13957) open to make it more considered and consistent.

**Comment by bigdaz** [comment] 2018-08-16 19:13
Thanks Andy.

There are 2 clear use cases for excludes:
1) I'm depending on a module X that should _never_ bring in a transitive dependency on Y, no matter where it appears in the graph (e.g. a library that brings in a dependency on a logging implementation). In this case, an `exclude` is used to correct the published metadata of X, similar to Gradle's component metadata rules.  In the end, the consumer needs to declare a direct dependency on Y (ie appropriate logging implementation) if they want it in their graph.

2) For _a particular use_ of module X, the transitive dependency Y is not required. For example, say I have 2 dependencies X1 and X2 that both use `activemq-broker`. X1 only uses some declared constants in `activemq-broker.jar`, and so could easily exclude `activemq-openwire-legacy` from it's dependency on `activemq-broker`. But X2 might need the full functionality of `activemq-broker`, so the exclusion should not be applied globally to `activemq-broker`.

Can you think of any `exclusions` in the Spring Boot bom or starter poms that target the second use case? I'm thinking that most/all of your exclusions should be applied globally, as in the first use case.

If the exclusions truly are global, the I think we could address this by:
1) When a BOM is imported in Gradle, treat any `<exclusion>` defined in a `<dependencyManagement>` block as _global_, meaning it would affect the node anywhere that it appears in the graph.  This is #6382.
2) Move all of the `<exclusions>` out of the Spring Boot starter POMs and into the Spring Boot BOM.

**Comment by bigdaz** [comment] 2018-08-30 19:40
#6382 has now been implemented. This will allow an imported BOM to define exclusions that apply unconditionally within a resolution. I believe that by moving all critical exclusions to the Spring Boot BOM (https://github.com/spring-projects/spring-boot/issues/13957) it should now be possible to create a Spring Boot BOM and set of Starter POMs that function in the same way in Maven and Gradle.

**Comment by ljacomet** [comment] 2019-04-01 15:25
Closing given the work that went into #6382 and the fact that there is no plan to change exclusion semantic in Gradle at this point.

**Closed by ljacomet** 2019-04-01 15:25 UTC
Labels: a:feature, from:contributor, in:dependency-management
