### ISSUE TITLE
maven-publish sometimes erroneously up-to-date - skips generation and publishing of the artifact

### ISSUE THREAD

**Issue by swpalmer** [gradle/gradle#1657] opened 2017-03-23 18:07 UTC
Some publications are skipped when they shouldn't be.  The publish task claims it is up-to-date because it has no actions. The tasks that should build them are never triggered as they should be.

### Expected Behavior
The 'builtBy' task of a publication should be triggered when the publish task is run, the generated artifact should be uploaded.

### Current Behavior
Sometimes the publish task claims to have no actions when it should.    It then claims the the publish task is UP-TO-DATE and the artifacts that were to be published may never get built.
This happens in a multi-project build where two of three publications are successful.  All the publications have artifacts with a 'builtBy' specifying the task that produces the artifact file.   When this happens that task is never even attempted, it is not listed as skipped or up-to-date in the build log.

### Context
I have a multi-project build with custom task to generate various windows installer bits.  Two .msi files and an .exe bootstrapper that contains and installs those .msi installs and one other that is provided elsewhere.  When I run a release build (using 'net.researchgate:gradle-release') in my root project, which depends on the 'publish' task of the three subprojects, the two .msis are produced and published, but the often (not always) the main .exe installer is skipped in the manner described above.

### Steps to Reproduce (for bugs)
A multi-project build with at least three sub-projects that each publish a single artifact file via the 'maven-publish' plugin.  These are not java artifacts, but files produced by custom tasks.
Each artifact has the task that produces the artifact file specified via 'builtBy' .
Run 'gradle publish' in the root project.

### Your Environment
Windows 10 64-bit
Java 8u121
Gradle 3.4.1

**Comment by swpalmer** [comment] 2017-03-23 18:10
Note that the 'generatePomFileFor...' task also is never shown in the build log for the publication that is skipped.

**Comment by bmuschko** [comment] 2017-03-28 19:08
Please provide a reproducible code example on GitHub.

**Comment by oehme** [comment] 2017-09-20 17:36
I'm closing this since there is no reproducible example. Please provide one if you'd like us to investigate.

**Closed by oehme** 2017-09-20 17:36 UTC
Labels: a:question, from:contributor, in:publishing-plugin
