### ISSUE TITLE
Selecting an evicted version using a dynamic version selector causes dependency edge to be lost

### ISSUE THREAD

**Issue by sonicsnes** [gradle/gradle#3923] opened 2017-12-28 22:39 UTC
If a module requests a dependency using a dynamic version, and that dependency version has already been evicted as a part of a previous conflict resolution, the edge remains unconnected forever. This is typically not an issue, as the newer version is still typically included, but does cause problems when additional configurations from the dynamic version requested are not included.

### Expected Behavior

No dependency edges should remain unconnected after a full resolve has completed.

### Current Behavior

If a dynamic version is used to select a module version which has already been evicted as part of the resolve process, the edge is never connected and any requested configurations from that edge are silently dropped.

### Context

This issue has impacted some of our builds directly, causing configurations of some dependencies to be missing unexpectedly.

### Steps to Reproduce (for bugs)

Run `./gradlew resolveTest` with this repository:
https://github.com/sonicsnes/gradle-3923
The output should contain `test:d:2;default -> test:c:2;beta`, but doesn't.

Here's what happens:
* Dependency `a` and `b` both depend on different versions of `c` and `d`, causing a conflict resolution to occur for `c` first, followed by `d`. Once `d` has been resolved, it makes a request using a dynamic version for the already evicted version of `c`, and the edge is dropped.
* As you can see from the build output, module `test:d:2 (default)` has been pulled into the project, and if you look in d-2.xml, this should result in the `beta` configuration of module `c` being included as well. However, the edge is missing and `beta` is not pulled into the build.
* If you flip the order of the two dependencies in b-1.xml (causing the conflict resolution to occur for `d` first), all edges are resolved properly, and `beta` of `c` is included.

### Your Environment
Gradle 4.4.1 (although I believe I have noticed the issue as far back as 4.0)

**Comment by jjohannes** [comment] 2018-01-05 13:36
Thanks for reporting @sonicsnes.

Looks like this is a general issue with dynamic versions that has been there "forever". I think the offending part is somewhere here:

https://github.com/gradle/gradle/blob/319a31cd7a51720c8936d66c6943b70bee0bbc66/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/DependencyGraphBuilder.java#L172-L175

If a fix is a complex change, we can maybe fail as a first step to improve this. I.e. fail if a previously deselected version is selected again later.

**Comment by sonicsnes** [comment] 2018-01-05 19:14
It would probably be overkill to fail on conflict. Triggering this bug requires a published dependency to contain a dynamic version selector (which on its own is already quite rare) in addition to it using a non-standard conf (which is also rare).

As a pair, it probably makes this bug extremely rare in the wild and our solution was just to re-publish the internal module in question to remove the dynamic version from its dependencies.

**Comment by bigdaz** [comment] 2018-05-17 21:34
@sonicsnes I just tried to reproduce this issue, and it seems that we might have fortuitously fixed this with our major refactoring of the resolution engine, that occurred between 4.6 and 4.7.

```
➜  gradle-3923 (master) ✗ sdk use gradle 4.6
➜  gradle-3923 (master) ✗ gradle -q resolveTest
test:main:1;default -> test:a:1;default
test:main:1;default -> test:b:1;default
test:a:1;default -> test:c:2;alpha
test:a:1;default -> test:d:2;default
test:b:1;default -> test:c:2;alpha
test:b:1;default -> test:d:2;default

➜  gradle-3923 (master) ✗ sdk use gradle 4.7   
➜  gradle-3923 (master) ✗ gradle -q resolveTest
test:main:1;default -> test:a:1;default
test:main:1;default -> test:b:1;default
test:a:1;default -> test:d:2;default
test:a:1;default -> test:c:2;alpha
test:b:1;default -> test:d:2;default
test:b:1;default -> test:c:2;alpha
test:d:2;default -> test:c:2;beta 
```

Now it's entirely possible that we've just tweaked the ordering or conflict resolution, and that the problem persists. However, conflict resolution is now much simpler internally, so I'm hopeful that this is properly fixed.

I'm going to close this issue for now. Please re-open if you see the problem persisting in the wild with Gradle 4.7+.

Note that `dependencyInsight` now reports the resolved configurations (as part of a generated "variant name"). This might make it easier to investigate if you see odd behaviour:

```
➜  gradle-3923 (master) ✗ gradle dependencyInsight --configuration compile --dependency c

> Task :dependencyInsight
test:c:2 (conflict resolution)
   variant "alpha+beta"
\--- test:b:1
     \--- test:main:1
          \--- compile
```

**Closed by bigdaz** 2018-05-17 21:34 UTC
Labels: a:bug, from:contributor, in:dependency-management

**Comment by bigdaz** [comment] 2018-05-17 21:40
Just to clarify, I'm closing this issue based on more than hope, it makes sense that the refactored resolution engine fixes this problem.
 
The resolution engine no longer does pairwise conflict resolution as new dependencies are discovered. Instead, we re-evaluate the entire set of dependency constraints when a new one is discovered, discarding the previous result. This made the logic much simpler internally, but also helped us to fix some long-standing bugs (i.e #4145).
