### ISSUE TITLE
Checkstyle import control bad xml causes Unhandled Exception, file handle not released

### ISSUE THREAD

**Issue by tkruse** [gradle/gradle#1416] opened 2017-02-16 03:22 UTC
Hi,
I am using gradle with Checktyle, including import control. The import control file has a well-defined XML structure. When viloating that structure, the gradle build fails with an ugly exception, and the file handle on the file defining the import rules is not released (causing problems on windows for git).

### Expected Behavior
Exception should be handled, telling users about the problem in a less confusing way. File handle should be released.

### Context
Checkstyle checks

### Steps to Reproduce (for bugs)
I can set up a project on github, but will take some time.
Here is some setup data
```
## build.gradle
apply plugin: 'java'
apply plugin: 'checkstyle'
// exclude checkstyle using -x checkstyleMain
checkstyleMain {
    configProperties = ['basedir': "$rootDir/config/checkstyle"]
    ignoreFailures = false
    configFile = new File(rootDir, 'config/checkstyle/checkstyle.xml')
}

checkstyle {
    toolVersion = "7.5.1"
}

## config/checkstyle/checkstyle xml

<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.2//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_2.dtd">
<module name="Checker">
    <module name="TreeWalker">
        <module name="ImportControl">
            <!--This location is relative to the checkstyle invocation :-(( -->
            <property name="file" value="${basedir}/import-control.xml"/>
        </module>
    </module>
</module>

# config/checkstyle/import-control.xml

<?xml version="1.0"?>
<!DOCTYPE import-control PUBLIC
        "-//Puppy Crawl//DTD Import Control 1.1//EN"
        "http://www.puppycrawl.com/dtds/import_control_1_1.dtd">
<import-control pkg="com.rakuten">
    <subpackage name="rapid">
        <allow pkg="com"/>
    </subpackage>
    <!--This is invalid, subpackages must come last inside each node-->
    <allow pkg="java.io"/>
</import-control>
```

Causes something like:
```
:controller:checkstyleMain FAILED
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':controller:checkstyleMain'.
> Unable to create Root Module: configLocation {D:\git\foo\config\checkstyle\checkstyle.xml}, classpath                                                                             {D:\git\foo\build\classes\main;D:\git\foo\build\resources\main;........... # whole classpath shown, of zero relevance to actual problem



$ git reset --hard
Unlink of file 'config/checkstyle/import-control.xml' failed. Should I try again? (y/n)
```
### Your Environment
Windows7, Java8, gradle3.3

**Comment by eriwen** [comment] 2017-02-16 16:15
Thanks for the reproducible example @tkruse. Would you be willing to submit a PR to make this a bit better? I expect that the community may be able to handle this sooner than the core team, so I've marked this `help-wanted` for now.

**Comment by gaganis** [comment] 2017-03-08 23:35
I have done some work and was able to reproduce and track the root cause of why the file handle is not released and the problem lies within the checkstyle library. 

Relevant issue https://github.com/checkstyle/checkstyle/issues/3962.

Also put together a small PR https://github.com/checkstyle/checkstyle/pull/3963 using a try-with-resources approach but it proved difficult to keep the 100% coverage rule required by checkstyle by all proposed fixes.

-------------------------------------------
IMHO this is not a problem with gradle so I suggest we close this issue.

**Comment by eriwen** [comment] 2017-03-14 19:54
I'm good with that @gaganis. Thanks for digging in! 

Closing this issue for now. Please reopen or submit a new issue if the previous comment is incorrect.

**Closed by eriwen** 2017-03-14 19:54 UTC
Labels: a:bug, affects-version:3.3, from:contributor, help-wanted, in:checkstyle-plugin

**Comment by gaganis** [comment] 2017-03-26 16:28
FYI @tkruse the [latest release of checkstyle(7.6.1)](http://checkstyle.sourceforge.net/releasenotes.html#Release_7.6.1#Release_7.6.1) contains my fix for this. Upgrading checkstyle should resolve your issue.

Cheers!
Giorgos
