### ISSUE TITLE
Kotlin DSL reference contains Groovy DSL on some pages

### ISSUE THREAD

**Issue by ov7a** [gradle/gradle#26454] opened 2023-09-21 06:46 UTC
### Issue type

Wrong or misleading information

### Problem description

See an [example, SourceSets](https://docs.gradle.org/current/kotlin-dsl/gradle/org.gradle.api.plugins/-java-plugin-extension/source-sets.html?query=abstract%20fun%20sourceSets(closure:%20Closure):%20Any)

It provides an inline example that is written with Groovy DSL, not Kotlin.

As a user of Kotlin DSL, I want to see Kotlin DSL examples in Kotlin DSL reference.

### Page with the problem

https://docs.gradle.org/current/kotlin-dsl/gradle/org.gradle.api.plugins/-java-plugin-extension/source-sets.html?query=abstract%20fun%20sourceSets(closure:%20Closure):%20Any

**Comment by jbartok** [comment] 2023-09-21 06:54
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/24622

Please add your use case and 👍 to that issue.

**Closed by jbartok** 2023-09-21 06:54 UTC
Labels: in:kotlin-dsl, a:documentation, to-triage
