### ISSUE TITLE
Gradle public APIs to get repository info

### ISSUE THREAD

**Issue by micahjo7** [gradle/gradle#29631] opened 2024-06-20 16:31 UTC
### Expected Behavior

In Android, we have a task `PerModuleReportDependenciesTask` that has usages of internal Gradle APIs that we would like to remove. In the past, we have had issues (e.g. [bug](https://issuetracker.google.com/265809620)) that have resulted from using the internal APIs and we have a task to clean up these usages in Android.

The two usages in the file are:

1. [GradleInternal](https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:build-system/gradle-core/src/main/java/com/android/build/gradle/internal/tasks/PerModuleReportDependenciesTask.kt;l=317)
2. [ResolvedComponentResultInternal](https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:build-system/gradle-core/src/main/java/com/android/build/gradle/internal/tasks/PerModuleReportDependenciesTask.kt;l=158)

Getting this repository information is important because it records this data in the report and is used by the Play Store to determine canonical Maven and Ivy repos.

The request is to create a public API to access this information (repository name, dependencyResolutionManagement) so that we don't have to rely on the internal classes.

### Context

The Android Gradle Plugin is using these internal APIs and we would like to remove these usages to prevent future bugs.

**Comment by ljacomet** [comment] 2024-06-24 08:56
This issue will be closed as a duplicate of

* #9763 

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

**Closed by ljacomet** 2024-06-24 08:56 UTC
Labels: a:feature, closed:duplicate, in:dependency-resolution
