### ISSUE TITLE
Reduce verbosity of `buildDir` replacement

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#26234] opened 2023-08-31 12:32 UTC
### Expected Behavior

`buildDir` has been deprecated https://github.com/gradle/gradle/issues/20210

The replacement, `layout.buildDirectory.get().asFile`, is verbose and introduces strange concepts like 'layout'.

It leads to difficult to read code compared to the previous version.

Before:

```kotlin
val aggregateTestReports by tasks.registering(TestReport::class) {
  // ...

  testResults.from("$buildDir/test-results/test/binary")
  testResults.from("$buildDir/test-results/testFunctional/binary")
  testResults.from("$buildDir/test-results/testIntegration/binary")
}
```

After: 

```kotlin
val aggregateTestReports by tasks.registering(TestReport::class) {
  // ...

  testResults.from("${layout.buildDirectory.get().asFile}/test-results/test/binary")
  testResults.from("${layout.buildDirectory.get().asFile}/test-results/testFunctional/binary")
  testResults.from("${layout.buildDirectory.get().asFile}/test-results/testIntegration/binary")
}
```

While `buildDir` returns a non-lazy property it is still a useful property, as a significant proportion of Gradle properties don't accept Provider API compatible properties.

### Context

For now I've added a replacement in my buildSrc utils

```kotlin
// buildSrc/src/main/kotlin/utils.kt

// workaround for the overly verbose replacement for the deprecated buildDir property
val Project.buildDir_: File get() = layout.buildDirectory.get().asFile
```

**Comment by melix** [comment] 2023-09-01 15:08
While I agree that the replacement is more verbose, you are actually using it wrong. The whole point of the layout API is to be lazy. In other words, every time you have to call `.get()` explicitly, it is likely you are doing something wrong.

In your case, the code should be :

```kotlin
val aggregateTestReports by tasks.registering(TestReport::class) {
  // ...

  testResults.from(layout.buildDirectory.dir("/test-results/test/binary")
  testResults.from(layout.buildDirectory.dir("test-results/testFunctional/binary")
  testResults.from(layout.buildDirectory.dir("test-results/testIntegration/binary")
}
```

which isn't that bad. Also instead of having a call to `layout.buildDirectory`, there should probably be a task which provides the output directory you're looking for, in which case you would get rid of the call altogether _and_ have automatic task dependency tracking.

**Comment by wilkinsona** [comment] 2023-09-04 07:00
I think there are cases where the replacement is verbose and, as far as I know, isn't being used incorrectly. Configuring the `destinationDir` of a `Sync` task was one [that I encountered](https://github.com/spring-projects/spring-boot/commit/a77863245d8637a187fd4e4a772ced1e4ba2da73) when moving away from `buildDir`.

**Comment by jbartok** [comment] 2023-09-04 09:01
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #26211 

Please add your use case and 👍 to that issue.

**Closed by jbartok** 2023-09-04 09:01 UTC
Labels: a:feature, to-triage
