### ISSUE TITLE
publishMavenJavaPublicationToMavenLocal bug in gradle 6.8

### ISSUE THREAD

**Issue by marcelbaumann** [gradle/gradle#15733] opened 2021-01-10 08:11 UTC
When having a multi-module projects where you have reference between module (meaning module A uses B, in my case     implementation project(':net.tangly.commons'), the publishMavenJavaPublicationToMavenLocal task generates the wrong maven references for all such references in the POM file in the part dependencies.

The same project generates all Maven POM correctly when using e.g. gradle 6.7.1
(tested it with gradlew and used once gradle 6.8 and once gradle 6.7.1)

### Expected Behavior
Generate the correct pom dependencies. In my case in the form

    <dependency>
      <groupId>net.tangly</groupId>
      <artifactId>core</artifactId>
      <version>0.2.6</version>
      <scope>runtime</scope>
    </dependency>

### Current Behavior
Currently, the wrong dependency is generated

    <dependency>
      <groupId>tangly-os</groupId>
      <artifactId>net.tangly.core</artifactId>
      <version>0.2.6</version>
      <scope>runtime</scope>
    </dependency>

### Context

gradle 6.8

the generated Maven artifacts are wrong and cannot be deployed

### Steps to Reproduce 

Multi-module projects with implementation project dependencies
### Your Environment

jdk oracle 14.0.2
Mac OS X 10.16 x86_64

Build scan URL:

**Comment by vlsi** [comment] 2021-01-10 17:42
@marcelbaumann , is this a duplicate of https://github.com/gradle/gradle/issues/15731 ?

**Comment by ljacomet** [comment] 2021-01-11 08:59
Closing as duplicate of #15731

**Closed by ljacomet** 2021-01-11 08:59 UTC
Labels: a:regression, closed:duplicate, from:contributor, in:publishing-plugin
