### ISSUE TITLE
Plugins using a platform dependency can't be published

### ISSUE THREAD

**Issue by larsgrefer** [gradle/gradle#12323] opened 2020-02-23 21:35 UTC
### Expected Behavior

It should be possible to deploy a gradle plugin to the Gradle Plugin Portal, which uses a platform dependency

### Current Behavior

The publishing fails with the following exception:

```
> Task :okhttp-plugin:publishPlugins FAILED
Could not reuse POM from pluginMaven publication because mavenCoordinates() was used

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':okhttp-plugin:publishPlugins'.
> No version found for com.squareup.okhttp3:okhttp on pom generation.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':okhttp-plugin:publishPlugins'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:205)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:203)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:184)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: com.gradle.publish.MissingDependencyVersionException: No version found for com.squareup.okhttp3:okhttp on pom generation.
        at com.gradle.publish.PomWriter.addDependency(PomWriter.java:58)
        at com.gradle.publish.PomWriter.createPomDocument(PomWriter.java:44)
        at com.gradle.publish.PomWriter.writePom(PomWriter.java:30)
        at com.gradle.publish.PublishTask.generatePom(PublishTask.java:168)
        at com.gradle.publish.PublishTask.ensurePomIsAvailable(PublishTask.java:154)
        at com.gradle.publish.PublishTask.publish(PublishTask.java:70)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:727)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:694)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.run(ExecuteActionsTaskExecuter.java:568)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:553)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:536)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$300(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:276)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:265)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:67)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:36)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:49)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:34)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:43)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:34)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:44)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:54)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:38)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:153)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:67)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:41)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:44)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:33)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:92)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:85)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:39)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:94)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:49)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:79)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:53)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:192)
        ... 30 more

```

### Context
I've updated the `dependencies` section from one of my gradle plugins to use a `platform` dependency, so I can omit some version numbers in my other dependency declaration.
With this change, it is not possible anymore to deploy the plugin to the Gradle Plugin Portal

https://travis-ci.org/freefair/gradle-plugins/jobs/654152950

### Steps to Reproduce 
Execute `./gradlew :okhttp-plugin:publishPlugins` in https://github.com/freefair/gradle-plugins/tree/5.0.0-rc4

### Your Environment

Build scan URL: https://scans.gradle.com/s/tgdf2ncqcfy3i

**Comment by jjohannes** [comment] 2020-02-24 10:59
Thanks for bringing this up @larsgrefer.

Unfortunately 😞, publishing Gradle Module Metadata is not yet supported for plugins. For full platform dependency support, that would be required.  We will work on that soon and then also get back to this bug report.

But you can still use platforms today.

First, you should remove this from your build script (you don't need it, `project.group` is used by default):
```
mavenCoordinates {
  groupId = project.group
}
```

Then the warning you are seeing about `mavenCoordinates` will go away and the POM generated by the `maven-publish` plugin will be used.

Then you can [publish with resolved versions](https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:resolved_dependencies) by adding the following to your `publications.withType(MavenPublication) { }` block:
```
versionMapping {
  usage('java-api') {
    fromResolutionResult()
  }
  usage('java-runtime') {
    fromResolutionResult()
  }
}
```

Then the pom should have the versions, without the need to publish the platform. The POM will contain an (invalid) _dependencyManagement_ entry to the platform. But since this is not used by any tool automatically, it should not hurt.

To make it completely _right_ you can follow this pattern to put the platform on a separate Configuration that is not published. Then you won't get the _dependencyManagement_ entry:
https://github.com/gradle/gradle/issues/10861#issuecomment-576562961

**Comment by larsgrefer** [comment] 2020-02-24 21:52
@jjohannes Thanks for the fast and detailed response.

Just removing 
```
mavenCoordinates {
  groupId = project.group
}
```
fixed the upload issue.

**Comment by jjohannes** [comment] 2020-09-30 10:25
Closing, as this is not a bug but rather badly documented. 

Improving documentation around plugin development is tracked separately (https://github.com/gradle/gradle-private/issues/688,  https://github.com/gradle/gradle-private/issues/913)

**Closed by jjohannes** 2020-09-30 10:25 UTC
Labels: @jvm, a:bug, from:contributor, in:plugin-development, in:publishing-plugin

**Comment by pmaedel** [comment] 2021-02-01 17:59
> Unfortunately 😞, publishing Gradle Module Metadata is not yet supported for plugins.

Is there any ticket for this?

**Comment by jjohannes** [comment] 2021-02-02 07:46
Good point @pmaedel. We only tracked this internally, but we should have a public issue. I created one: https://github.com/gradle/gradle/issues/15992

The current plan is to tackle this during the Gradle 7.0 release which we are working on right now.


Also to revise my earlier comment: It's really a bit weird, but if you publish the plugin to a "normal" repository (like Maven Central), using the publishing mechanism of "maven-publish", it already works. (see also: https://docs.gradle.org/current/userguide/publishing_gradle_plugins.html#custom-plugin-repositories)

Of course that is not a good solution long term, because only the portal is added as source for plugins by default in Gradle. Hope we'll have this fixed really soon.

**Comment by elect86** [comment] 2021-05-15 09:04
this still happens with 7.0
```
implementation(platform("org.http4k:http4k-bom:4.8.0.0"))
implementation("org.http4k:http4k-core")
implementation("org.http4k:http4k-server-netty")
implementation("org.http4k:http4k-client-apache")
```

**Comment by jjohannes** [comment] 2021-05-17 08:14
If you use the latest version of the plugin - `id("com.gradle.plugin-publish") version "0.14.0"` - module metadata is published that should including platform dependencies.

What exactly is not working for you @elect86?

**Comment by elect86** [comment] 2021-05-17 12:00
That `implementation`s I quoted earlier will trigger the same error whenever I try to publish it

> Execution failed for task ':plugin:publishPlugins'.
> No version found for org.http4k:http4k-core on pom generation.

If I manually set the version for each of them, it runs fine
```
//    implementation(platform("org.http4k:http4k-bom:4.9.0.2"))
implementation("org.http4k:http4k-core:4.9.0.2")
implementation("org.http4k:http4k-server-netty:4.9.0.2")
implementation("org.http4k:http4k-client-apache:4.9.0.2")
```

**Comment by jjohannes** [comment] 2021-05-17 15:03
@elect86 the (legacy) code that throws the error should not run. Please check:

- Apply the `maven-publish` plugin (in addition to `com.gradle.plugin-publish`)
- Do **not** use `mavenCoordinates { ... }` (inside `pluginBundle { ... }`)

**Comment by elect86** [comment] 2021-05-19 07:50
Ah, stupid mistake, `maven-publish` wasn't there

Sorry and thanks for the help, @jjohannes

**Comment by jjohannes** [comment] 2021-05-19 08:15
Np. `com.gradle.plugin-publish` should be improved to give a warning or just apply `maven-publish` automatically.

Glad to hear it works.

**Comment by elect86** [comment] 2021-05-19 09:05
I'd prefer the latter

my 2c
