### ISSUE TITLE
Version catalog bugs

### ISSUE THREAD

**Issue by elect86** [gradle/gradle#16250] opened 2021-02-22 12:52 UTC
Some aliases provoke a silent crash (you don't get the generated accessors in the project importing the setting plugin)

### Current Behavior or error

Entries with a leading underscore make accessor generation crash, I get no any other alias after [this](https://github.com/elect86/sciJava-catalogs/blob/7d213855/src/main/kotlin/sciJava/catalogs/fiji.kt#L38) if I uncomment it

Also all of [these](https://github.com/elect86/sciJava-catalogs/blob/master/src/main/kotlin/sciJava/catalogs/SciJavaCatalogsPlugin.kt#L507-L511) aliases seems to provoke other crashes

### Steps to Reproduce 

Apply with jitpack
```
pluginManagement {
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "sciJava.catalogs")
                useModule("com.github.elect86:sciJava-catalogs:7d213855") //.also { println("found") }
        }
    }
    repositories {
        gradlePluginPortal()
        maven("https://jitpack.io")
    }
}
plugins { id("sciJava.catalogs") }
```

### Your Environment
Gradle 7.0 M1 bin

**Comment by melix** [comment] 2021-03-18 14:49
@elect86 do you still have the problem with 7.0-milestone-3? I can't reproduce.

**Comment by jjohannes** [comment] 2021-03-23 08:43
Closing this as it seems to be fixed. @elect86 use know, if there is still an issue with this in 7.0 RC1.

**Comment by elect86** [comment] 2021-03-23 09:53
Sorry, I still didnt have the chance to test it again

**Comment by elect86** [comment] 2021-04-15 18:53
I tested, issues still present

> Settings file '/home/elect/IdeaProjects/sciJava-platform/settings.gradle.kts' line: 10
>
> An exception occurred applying plugin request [id: 'sciJava.catalogs', version: '30.0.0+10']
> Failed to apply plugin 'sciJava.catalogs'.
   > Invalid catalog definition:
       - Problem: In version catalog fiji, invalid alias '_3dBlobSegmentation' name.

**Comment by ljacomet** [comment] 2021-04-19 08:35
From what I can tell, while there are limitations to names, this no longer causes a _silent crash_. Is that correct?

If you want you could open another issue (or search for one) about supporting more name patterns.

**Comment by elect86** [comment] 2021-04-19 13:05
Yep, got it

**Comment by elect86** [comment] 2021-04-19 13:29
Wait @ljacomet , if leaving `_3dBlobSegmentation` causes some of the catalogs not being available later on consumer without any error, is this still considered a silent crash?

**Comment by ljacomet** [comment] 2021-04-19 14:19
Yes, while the feature is opt-in for now, once it gets released generally I would consider this a bug. So it is one now 😉 

Can you update or confirm your reproducer? And I would re-open this issue then.

**Comment by elect86** [comment] 2021-04-19 14:20
I can confirm

**Comment by octylFractal** [comment] 2021-12-20 21:02
Hi @elect86, your reproducer does not seem to silently fail under 7.3.2l, I instead get this error:

```
An exception occurred applying plugin request [id: 'sciJava.catalogs', artifact: 'com.github.elect86:sciJava-catalogs:7d213855']
> Failed to apply plugin 'sciJava.catalogs'.
   > Using dependency catalogs requires the activation of the matching feature preview.
     See the documentation at https://docs.gradle.org/7.3.2/userguide/platforms.html#sub:central-declaration-of-dependencies
```

If there is more required to reproduce this than just those lines in the `settings.gradle`, please provide more steps / code.

**Closed** 2022-01-11 16:53 UTC
Labels: a:bug, @core, in:dependency-version-catalog
